### ISSUE TITLE
unable to cycle segments of different bit rates

### ISSUE THREAD

**Issue by nickdesaulniers** [google/shaka-player#100]
See also: https://github.com/axiomatic-systems/Bento4/issues/13 and https://github.com/Dash-Industry-Forum/dash.js/issues/587

my manifest looks like:
```xml
<?xml version="1.0" ?>
<MPD mediaPresentationDuration="PT1M0.08S" minBufferTime="PT3.00S" profiles="urn:mpeg:dash:profile:isoff-live:2011" type="static" xmlns="urn:mpeg:dash:schema:mpd:2011">
  <!-- Created with Bento4 mp4-dash.py, VERSION=1.6.0-594 -->
  <Period>
    <!-- Audio -->
    <AdaptationSet mimeType="audio/mp4" segmentAlignment="true" startWithSAP="1">
      <SegmentTemplate duration="3000" initialization="$RepresentationID$/init.mp4" media="$RepresentationID$/seg-$Number$.m4f" startNumber="1" timescale="1000"/>
      <Representation audioSamplingRate="22050" bandwidth="130635" codecs="mp4a.40.2" id="audio/und">
        <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
      </Representation>
    </AdaptationSet>
    <!-- Video -->
    <AdaptationSet mimeType="video/mp4" segmentAlignment="true" startWithSAP="1">
      <SegmentTemplate duration="3000" initialization="$RepresentationID$/init.mp4" media="$RepresentationID$/seg-$Number$.m4f" startNumber="1" timescale="1000"/>
      <Representation bandwidth="170203" codecs="avc1.42C00D" frameRate="24" height="144" id="video/1" scanType="progressive" width="256"/>
      <Representation bandwidth="405617" codecs="avc1.42C014" frameRate="24" height="216" id="video/2" scanType="progressive" width="384"/>
      <Representation bandwidth="563833" codecs="avc1.42C015" frameRate="24" height="270" id="video/3" scanType="progressive" width="480"/>
      <Representation bandwidth="718137" codecs="avc1.42C015" frameRate="24" height="316" id="video/4" scanType="progressive" width="560"/>
      <Representation bandwidth="698854" codecs="avc1.42C01E" frameRate="24" height="360" id="video/5" scanType="progressive" width="640"/>
    </AdaptationSet>
  </Period>
</MPD>
```
but the demos at:
* http://shaka-player-demo.appspot.com

all seem to only fetch and only be able to play the lowest possible resolution.  Bug in the manifest generator, or the client?

I do not see any errors in the console.

**Comment by joeyparrish** [comment]
The appspot demo does not have an uncompiled mode at the moment, so it does not generate logs.  Sorry about that.

Please try that manifest on a local build and see what the logs have to say.  I tried your manifest (without your content, obviously), and Shaka Player was able to parse all of the Representations just fine.  I see 5 video tracks listed under "Available video tracks" in the test app UI.

Is the problem that you only have one track to choose from, or that it never switches?  Which track does it play?

**Comment by nickdesaulniers** [comment]
> Is the problem that you only have one track to choose from, or that it never switches? Which track does it play?

I only have one choice of track: 640x360 656625 bits/s

Tested in Opera beta 30.0 and the hosted demo: http://shaka-player-demo.appspot.com/.  Will try downloading a debug build.

**Comment by nickdesaulniers** [comment]
With a local build of v1.3.0-debug, same thing; just one track, no errors in the console.  Would sharing my assets be helpful?

**Comment by joeyparrish** [comment]
Yes, please share your assets.  We have not tested in Opera before, so that sounds like an important detail.

Could you also please share the full JavaScript log from your session?  Not just errors, but warnings and even mime-type-support info could be very important.

**Comment by nickdesaulniers** [comment]
assets + console log (18MB): https://www.dropbox.com/s/d8h1h1pnbfsdaj9/assets.zip.gz?dl=0
there's an error about the cors header in there, has to do with my server I'm using, see: https://github.com/indexzero/http-server/pull/157#issuecomment-110910350

**Comment by nickdesaulniers** [comment]
sorry, this does work in Opera.  Other issues in other browsers such as #101.  will file other issues.
