### ISSUE TITLE
1000!

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#1000]
![I don't know if you heard me counting.  I did over a thousand.](https://user-images.githubusercontent.com/6843156/29808817-6fbf50bc-8c4e-11e7-9993-69eabdb3a6eb.gif)

**Comment by joeyparrish** [comment]
1000 issues!  I can hardly believe it.

Thank you to all of our contributors, to our users, to everyone who ever filed an issue against us over the years, and to the browser vendors who have responded so kindly to the issues we filed in turn.  Shaka Player exists thanks to all of you.

Here's to 1000 more!  :beers:

**Comment by chrisfillmore** [comment]
Thanks Shaka team for all your hard work and support. It's really a pleasure working with you!

**Comment by joeyparrish** [comment]
Thanks!

**Comment by chrisfillmore** [comment]
<img width="227" alt="screen shot 2018-02-13 at 8 35 31 pm" src="https://user-images.githubusercontent.com/7190265/36183719-992fddca-10fd-11e8-83be-9b29403107d6.png">

1000 closed! GJ
