### ISSUE TITLE
Support AirPlay

### ISSUE THREAD

**Issue by vasimi** [google/shaka-player#1003]
If there is Google Cast support for Chrome, it would be nice to have AirPlay support for Safari. :)

**Comment by avelad** [comment]
According to https://developer.apple.com/library/content/releasenotes/General/WhatsNewInSafari/Articles/Safari_9_0.html , it's possible detect Airplay availability with:

```
if (window.WebKitPlaybackTargetAvailabilityEvent) {
    video.addEventListener('webkitplaybacktargetavailabilitychanged',
        function(event) {
           switch (event.availability) {
                case "available": /* turn stuff on */
                break;
                case "not-available": /* turn AirPlay button off */
                break;
           }
        })
}```

For launch, you can use: https://developer.apple.com/documentation/webkitjs/htmlmediaelement/1632172-webkitshowplaybacktargetpicker

`
video.webkitShowPlaybackTargetPicker();
`

Sample: https://www.mobila.name/post/558136319cb8c/ (in russian)

**Comment by MekliCZ** [comment]
@avelad Yes, I know, but there is a button in Shaka controls for Google Cast and no button for AirPlay. What I'm suggesting is add this button so AirPlay can be used with Shaka "out of the box".

**Comment by joeyparrish** [comment]
@MekliCZ, we will look into it.  We already have a pretty full plate for v2.3, so for now, I've placed this enhancement on the backlog.  Thanks!

**Comment by MekliCZ** [comment]
@joeyparrish Nice, that's enough, I guess. It isn't anything critic, but it would be really nice to have it in Shaka. :)

**Comment by joeyparrish** [comment]
And we would love to add it, but we have to put some more critical HLS features first.  Thanks for your patience!

**Comment by avelad** [comment]
With the code in the `master`, Airplay is working for Clear and Fairplay. Then, the only thing left is the part of the user interface.

Note: Airplay only works in src mode.

**Comment by joeyparrish** [comment]
Thanks, @avelad!
