### ISSUE TITLE
What is the purpose of LOAD_INTERRUPTED?

### ISSUE THREAD

**Issue by chrisfillmore** [google/shaka-player#1006]
I am troubleshooting an issue in our application in which, if a user is channel-surfing (i.e. switching contents quickly), they get LOAD_INTERRUPTED, which causes the new call to `Player#load()` to reject.

I understand the circumstances which _produce_ LOAD_INTERRUPTED. But why does LOAD_INTERRUPTED cause the load process to fail? Instead of causing it to restart? (i.e. unload resources and start again with new parameters)

I'm not suggesting Shaka should make any change, I just want to understand the circumstances better. Thanks for the help.

**Comment by joeyparrish** [comment]
I'm not completely sure I understand the question, but I'll start by explaining the semantics of load/unload/destroy.

`load()` returns a `Promise`, so anything that causes that `load()` to fail results in the Promise being rejected with an error code.  Failures which may occur later during playback result in an error event being dispatched from the Player.

`LOAD_INTERRUPTED`, as you probably already know, is the error code we use to reject the `load()` Promise when some later method interrupts that process and causes it to be aborted.  There are three ways this can happen:

1. Another call to `load()`.  In the general case, this more recent load() may be for a different content or with a different Player configuration.  Each call to load() returns a different Promise.  The first load(), which never completed and will never complete, is rejected with LOAD_INTERRUPTED, while the second load() may yet complete (or be interrupted itself).  These Promises represent different requests from the application and are therefore independent.
2. A call to `unload()`.  This effectively cancels any load() operation in progress.  unload() also returns a Promise which is resolved when a pending load() is completely canceled, or when the currently streaming content has been fully unloaded, depending on the state of Player at the time unload() is called.  After this Promise is resolved, the Player is ready to use again, as if it were newly-constructed.
3. A call to `destroy()`.  This not only cancels any load() in progress and unloads any playing content, but tears down everything, frees all resources, and leaves the Player instance unusable.  It is the antithesis of the constructor.

If I understand your question correctly, the answer is that we *do* restart the `load()` process, but we do so in a way that tracks the state and success/failure of each individual load() in a separate Promise.  Each load() Promise represents that particular request, so we would never resolve the first Promise if the load() operation didn't complete.

If you are loading rapidly based on user input, I recommend selectively ignoring the LOAD_INTERRUPTED error code in your `catch()` handler on the load() Promise.  Any time the load operation is interrupted by the user changing their mind, that is not an actual error you would want to log to the server or surface to the user, even though the process "failed".

Does this help?

**Comment by chrisfillmore** [comment]
Yes absolutely, thank you for that detailed explanation!

**Comment by joeyparrish** [comment]
Glad I could help!
