### ISSUE TITLE
Unable to play manifest having single adaptation set

### ISSUE THREAD

**Issue by skstronghold** [google/shaka-player#1007]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**: Yes

**What version of Shaka Player are you using**:  2.2.1

**Can you reproduce the issue with our latest release version**: yes

**Can you reproduce the issue with the latest code from `master`**: yes

**Are you using the demo app or your own custom app**: Custom app

**If custom app, can you reproduce the issue using our demo app**: yes. Link - http://bit.ly/2iQcf4O

**What browser and OS are you using**: Chrome Version 59.0.3071.115 (Official Build) (64-bit). Ubuntu 14.04.02

**What are the manifest and license server URIs**:
*(you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*
Manifest URI - http://bit.ly/2vzXHMK
No license server was used.

**What did you do?**
I tried playing the manifest

**What did you expect to happen?**
I expected it to play

**What actually happened?**
It didn't play. There were no errors on console either. It works fine with other players

**Comment by vaage** [comment]
This appears to be a problem with the WebM file. It does not appear to be set-up to stream properly. When I package the content with the Shaka Packager, I can get it to work but it does restructure the WebM file. If I manually change the manifest created by the shaka packager to use the original file (updating values as needed) it will fail with errors about the WebM content.
