### ISSUE TITLE
 Will the content be played using the widevine offline license on the chrome desktop?

### ISSUE THREAD

**Issue by mateon01** [google/shaka-player#1019]
I want to use the widevine on my chrome desktop to play content offline. 

`servers: {
        'com.widevine.alpha': 'license server',
      },
      advanced: {
        'com.widevine.alpha': {
          'persistentStateRequired':true,
          'serverCertificate': serverCertificate
        }
      }`
This is normal when streaming playback is performed with the above settings. However, when attempting to download a license, an Unsupported keySystem or supportedConfigurations error occurred and the keySystem access was restricted. Even if you test with ssl, is this scenario possible?

p.s)I used chrome 64, and shaka used version 2.2.1

**Comment by TheModMaker** [comment]
Chrome doesn't support offline licenses on desktop platforms.  It is only supported on Chromebooks and is planned for Android.

Also note that `persistentStateRequired` doesn't mean offline licenses.  You can still set that parameter and play streaming licenses.  The only way to use offline licenses with Shaka is to use [`shaka.offline.Storage`](https://shaka-player-demo.appspot.com/docs/api/shaka.offline.Storage.html).

**Comment by joeyparrish** [comment]
Note that for PWAs specifically, you should *probably* not be using your service worker to store the content, and you should *definitely* not be using your service worker to try to store the license.  Licenses don't work that way, and caching a license response in a service worker is essentially a replay attack on the CDM.

**Comment by mateon01** [comment]
The bottom line is that you can not use the sessionTypes: ['persistent-license'] attribute. Thank you for your answers.
