### ISSUE TITLE
CORS issues in Safari

### ISSUE THREAD

**Issue by nickdesaulniers** [google/shaka-player#102]
trying to host the assets from #100 , in Safari Version 8.0.6 (10600.6.3) I see errors in the console:

[Error] XMLHttpRequest cannot load http://localhost:8000/stream.mpd. Origin http://localhost:8002 is not allowed by Access-Control-Allow-Origin. (localhost, line 0)

where I'm hosting Shaka player on port 8002 and the assets on port 8000.  I'm quite sure that I have CORS enabled on my server (port 8000), but it doesn't look like Safari is even making a request.  I would expect it to be making an HTTP OPTIONS request to check the headers, but I can't see it server side, even with a small test case.  When I manually make an xhr from the console, I see the same error printed, but actually see the request in the server logs, just not when clicking "Load Stream" in Shaka player.  This might even be a bug in Safari, but a second set of eyes to confirm would be helpful.

```javascript
xhr = new XMLHttpRequest
xhr.open('get', 'http://localhost:8000/stream.mpd')
xhr.onload = function () { console.log(xhr.response); }
xhr.onerror = function (e) { console.error(e) };
xhr.send()
```

I happen to be using [http-server](https://github.com/indexzero/http-server) with the --cors flag for testing.

**Comment by nickdesaulniers** [comment]
wtf: https://github.com/photonstorm/phaser/issues/1355 Develop > Clear caches

**Comment by joeyparrish** [comment]
Yay for Safari.  :-)

**Comment by revtechbhav** [comment]
is any way to resolve the 
Failed to set referrer policy: The value 'origin-when-cross-origin' is not one of 'no-referrer', 'origin', 'no-referrer-when-downgrade', or 'unsafe-url'. Defaulting to 'no-referrer'. 

issue 
it is coming in my safari mac browser, and is working fine rest of browsers
