### ISSUE TITLE
Shaka player unable to retrieve license in Chrome on Android 5

### ISSUE THREAD

**Issue by mateon01** [google/shaka-player#1023]
I am using chrome canary, android5, and shaka 2.2.1.

On desktop Chrome, licensing is successful. However, mobile chrome does not enter the licensing process.

I have tried remote debugging
`if (type == shaka.net.NetworkingEngine.RequestType.LICENSE) {
      request.headers['customHeader'] = 'Header Info';
  }`

type == shaka.net.NetworkingEngine.RequestType.LICENSE In this section, i have discovered that the Type drops to a segment and does not fall under the license.

What settings have I missed?

**Comment by TheModMaker** [comment]
Double check the content you are trying to play is protected.  Do you get any other errors?  For example, do you get a `REQUESTED_KEY_SYSTEM_CONFIG_UNAVAILABLE` error?  Did you wait enough time for the license request?  We may not send the license request immediately, the first request you get may be for the media segment.  Did you see the popup requesting access for premium content?  Did you allow it?  How about trying in an incognito tab?

**Comment by mateon01** [comment]
1. The content you want to play is protected by Widevine DRM.

2. I did not get any errors and I had enough time.

3. Protected media playback popups have been viewed and accepted.

4. I also initialized the cache as well as the incognito tab.

**Comment by theodab** [comment]
A duplicate issue for this was also filed, #1027.
For reference, the duplicate did mention that these licensing problems do not happen on Android 6 and 7, only 5. I will rename this issue to reflect that new information.

**Comment by joeyparrish** [comment]
@mateon01, you did not provide any way for us to reproduce the problem.  Please provide the following information, which was requested in the issue template:

=====

**What version of Shaka Player are you using**:

**Can you reproduce the issue with our latest release version**:

**Can you reproduce the issue with the latest code from `master`**:

**Are you using the demo app or your own custom app**:

**If custom app, can you reproduce the issue using our demo app**:

**What browser and OS are you using**:

**What are the manifest and license server URIs**:
*(you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*

**What did you do?**

**What did you expect to happen?**

**What actually happened?**

**Comment by mateon01** [comment]
Sorry for the delay.

What version of Shaka Player are you using: 
* I used shaka player version 2.2.1.

Can you reproduce the issue with our latest release version:
* It is possible. The latest versions of shaka player, Android and chrome are available.

Can you reproduce the issue with the latest code from master: 
* yes
Are you using the demo app or your own custom app:
* https://github.com/GoogleChromeLabs/sample-media-pwa I refer to this.
If custom app, can you reproduce the issue using our demo app:It is possible.

What browser and OS are you using:
*  Android 6 and 7, Android Chrome canary

What are the manifest and license server URIs: 
* https://contents.pallycon.com/bunny/stream.mpd, https://tokyo.pallycon.com/ri/licenseManager.do (you can send the URIs to shaka-player-issues@google.com instead, but please use GitHub and the template for the rest)

What did you do?
* I stored the Widevine license using PWA technology and tried to play the encrypted content using it.

What did you expect to happen?
* I expected to recover the Widevine license stored in the Media Key Session and play mpd.

What actually happened?
* The license was successfully saved and the key set ID was issued successfully. However, the 
license saved in the session was not restored when I tried to play it after saving.

**Comment by joeyparrish** [comment]
Thanks!  We will try to reproduce using our demo app.  If this is specific to the Chrome PWA sample, we may not be able to offer direct support for that.  If we can reproduce with our demo, we should be able to help you.

**Comment by vaage** [comment]
@mateon01 After reviewing this issue, there seems to be some contradicting information that I hope you can clear up for me. Right now the bug title specifies Android 5 based on information from a duplicate bug #1027. In your repo steps you say you have done this on Android 4, 5, 6, 7. Is this an issue only on Android 5 or on all Android versions?

**Comment by mateon01** [comment]
Android versions that are not licensed are versions 4 and 5. Versions 6 and 7 will proceed normally until the license is issued.

**Comment by vaage** [comment]
@mateon01  I'll have to sync-up with Widevine's Android test engineer as we don't have the devices to reproduce this right now.

**Comment by mateon01** [comment]
Okay. Thank you for always.

**Comment by vaage** [comment]
@mateon01 The example you are using not the correct way to handle licenses for offline content. You cannot just cache a license and replay it later - that would expose the DRM system to replay attacks. If you wish to have offline playback you need to use persistent licenses. We suggest that you use Shaka Player's built-in offline support rather than the PWA example you are using.

**Comment by joeyparrish** [comment]
To clarify, caching a license response in your service worker is the same as a replay attack against the CDM.  The CDM defends itself against this and will reject such a cached response.

Shaka Player's offline APIs take care of media storage and persistent licensing for you, so these are what you should use instead.  Service workers should not be used to cache media or licenses.
