### ISSUE TITLE
Chrome Mac decoder error

### ISSUE THREAD

**Issue by shanmugapriyaEK** [google/shaka-player#1024]
Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues:Yes

What version of Shaka Player are you using: 2.1.7

Can you reproduce the issue with our latest release version: Yes. Tested the same in the hosted demo app as a custom asset

Can you reproduce the issue with the latest code from `master`: I haven't tried it yet.

Are you using the demo app or your own custom app: Our custom app

If custom app, can you reproduce the issue using our demo app: yes

What browser and OS are you using: chrome - mac

What are the manifest and license server URIs:
URL details are present in our live application (https://www.directvnow.com/)

Credentials will be shared through email

What did you do?
We are trying to play the live restart content in the application .

What did you expect to happen?
Content is expected to play from cdn as well as from origin server
What actually happened?

When we try to play the content using our origin server it is playing properly without any error. When we try the same thing from cdn, we get error 3014 "failed fetch and append: code=3014"
-CHUNK_DEMUXER_ERROR_APPEND_FAILED: Failed to prepare video sample for decode

We could not find the reason behind it as it happens only from cdn. Could you please help us in resolving the issue.

**Comment by shanmugapriyaEK** [comment]
Log from chrome console

**Comment by joeyparrish** [comment]
Note that this has also been filed internally as b/65674425.

**Comment by joeyparrish** [comment]
Error 3014 would indicate a decoder or demuxer error in the browser.  It's mostly out of our hands, and usually indicates a problem with the encoder.  With these sorts of issues, it's best to use `chrome://media-internals` in Chrome to see logs from the media stack.

In cases where the logs indicate an issue, but it's not obvious what the encoder would have done wrong, we usually end up having to analyze the media itself and/or forward the issue to the Chrome media team for deeper diagnosis.

We will post `media-internals` results soon.

**Comment by joeyparrish** [comment]
Timestamp | Property | Value
-- | -- | --
00:00:00 00 | origin_url | (omitted)
00:00:00 00 | frame_url | (omitted)
00:00:00 00 | frame_title | DIRECTV NOW
00:00:00 00 | url | blob:(omitted)
00:00:00 00 | pipeline_state | kStarting
00:00:01 275 | has_cdm | true
00:00:01 490 | found_video_stream | true
00:00:01 490 | video_codec_name | h264
00:00:01 611 | found_audio_stream | true
00:00:01 611 | audio_codec_name | aac
00:00:01 613 | seek_target | 1
00:00:01 624 | debug | DecryptingAudioDecoder: failed to init decoder on decryptor
00:00:01 625 | audio_dds | true
00:00:01 625 | audio_decoder | FFmpegAudioDecoder
00:00:01 625 | debug | Video rendering in low delay mode.
00:00:01 649 | video_dds | false
00:00:01 649 | video_decoder | DecryptingVideoDecoder
00:00:01 649 | pipeline_state | kPlaying
00:00:01 649 | pipeline_state | kSeeking
00:00:01 278 | duration | 4294967296
00:00:02 44 | pipeline_state | kPlaying
00:00:02 88 | audio_buffering_state | BUFFERING_HAVE_ENOUGH
00:00:04 491 | error | Failed to prepare video sample for decode
00:00:04 491 | error | Append: stream parsing failed. Data size=131072 append_window_start=0 append_window_end=inf
00:00:04 492 | pipeline_error | CHUNK_DEMUXER_ERROR_APPEND_FAILED
00:00:04 492 | pipeline_state | kStopping
00:00:04 492 | pipeline_state | kStopped
00:00:04 517 | event | WEBMEDIAPLAYER_DESTROYED

**Comment by shanmugapriyaEK** [comment]
I don't face this issue now. Thanks @joeyparrish
