### ISSUE TITLE
ttml play issue

### ISSUE THREAD

**Issue by kuznetcoff777** [google/shaka-player#1028]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**:yes

**What version of Shaka Player are you using**: latest

**Can you reproduce the issue with our latest release version**:demo 

**Can you reproduce the issue with the latest code from `master`**: demo

**Are you using the demo app or your own custom app**:demo

**If custom app, can you reproduce the issue using our demo app**:

**What browser and OS are you using**: any

**What are the manifest and license server URIs**:
*(you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*sent to mail

**What did you do?** Opened stream and waited for subtitles

**What did you expect to happen?** Subtitles in player

**What actually happened?** No subs appeared, but in http://dashif.org/reference/players/javascript/v2.5.0/samples/dash-if-reference-player/index.html it works fine. I suppose there is some trouble with ttml itslef, but how to workaround this problem? We need to lauch stream on your player with subtitles.

**Comment by theodab** [comment]
Looking over the caption mp4s, I think see the problem.
Our mp4 ttml parser assumes that an mp4 will only have a single mdat with ttml inside. These samples, however, have two mdats containing ttml each. Therefore, we end up ignoring the first mdat, and only using the second one... and the second mdat has only a single ttml cue in it, and that cue has a duration of 0.
This should be fairly simple to fix. Thanks for pointing it out.

**Comment by kuznetcoff777** [comment]
Is there any way to make a hot fix on 2.2 version by ourself? We cannot wait for 2.3 version...

**Comment by theodab** [comment]
Well, I got the change out now, so you can just pull from master.

**Comment by theodab** [comment]
On reflection I'm not entirely sure if this is a bug, or if it's bad content, but I can't find a spec for ttml in mp4 so I'll leave the bug label for now.
This... bug (?) should be present in 2.0, but this change will only work after the ttml parser refactoring in 2.1.

**Comment by kuznetcoff777** [comment]
Maybe label is enhancement?
Thanks a lot, it works now.

**Comment by joeyparrish** [comment]
The fix has been cherry-picked to v2.2.x and will be released in v2.2.2.

**Comment by kuznetcoff777** [comment]
Guys, have not you destroyed fix in 2.3.0? We checked new version and it seems to be does not work, if button cc is pressed, then captions are not downloaded

**Comment by kuznetcoff777** [comment]
@theodab @joeyparrish 
Guys, have not you destroyed fix in 2.3.0? We checked new version and it seems to be does not work, if button cc is pressed, then captions are not downloaded

**Comment by theodab** [comment]
I tried it out in the demo. Your example asset doesn't work in the v2.3.0 demo for non-caption-related reasons, but in the [nightly build demo](https://nightly-dot-shaka-player-demo.appspot.com/demo/) it works fine for me. Have you tried out the nightly?
