### ISSUE TITLE
Question: Manifest Parser where manifest url request isn't needed?

### ISSUE THREAD

**Issue by peterdotjs** [google/shaka-player#1029]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**:
yes

**What version of Shaka Player are you using**:
2.2.1

**Are you using the demo app or your own custom app**:
custom app

**What browser and OS are you using**:
Chrome/ OSX

Hi Shaka Team,

I'm trying to integrate shaka player with our existing infrastructure. Currently the MPD content will be available through a separate request so by the time I'm initializing the shaka player and executing `.load` I'd idealy want to pass it the content directly at this point rather than an uri.

From some previous issues like #946 it seemed the approach would be to create a custom manifest parser factory to remove the logic of requesting the manifest. I then tried to fork `dash_parser` but after reading #716 and it seemed like not the best approach especially with lots of references to `uri`. 

Per the [documentation](https://github.com/google/shaka-player/blob/master/docs/tutorials/manifest-parser.md) :
> The function of a manifest parser is to take a URL that was passed to load() and give us back a manifest object.

This unfortunately doesn't fit our use case.  Before attempting to create a hacked manifest parser I wanted to check if there was an alternative.

Are any recommendations on how to approach this?

Thanks!

**Comment by theodab** [comment]
When you say you have the MPD content already, do you mean that you have already retrieved the manifest but have yet to parse it, or do you mean that you have retrieved the manifest and parsed it and now need Shaka Player to use the data?

If you have yet to parse the manifest, you might want to make a custom networking plugin. You can register one with `shaka.net.NetworkingEngine.registerScheme`, and it will be used by our existing DASH parser if you provide an uri that uses the custom scheme you registered it under. You can look at lib/net/http_plugin.js if you want an example.

If you have parsed the manifest already, and just want to translate your internal parsed manifest format into our parsed manifest format, then a custom manifest parser that ignores the uri and doesn't make any network requests is probably the way to go after all. Unless you make a custom networking plugin anyway and just send over the un-parsed raw manifest and parse it again, I suppose.

**Comment by peterdotjs** [comment]
@theodab thanks for the quick response! We have the content of the MPD file but have yet to parse it so I'll try out the custom networking plugin approach.

**Comment by chrisfillmore** [comment]
We have a scenario where we need to know the bandwidth levels from the manifest before we start playback, so that we can set the max bandwidth in order to restrict certain variants.

@peterdotjs if you do make a custom plugin, would you share with a PR? @theodab could something like that get merged?

**Comment by joeyparrish** [comment]
@peterdotjs, it sounds like what you need is the ability to pass in the MPD text, which you have already fetched.  Network filters and/or scheme plugins are a reasonable approach for that.  Another approach could be the [Service Worker API](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API) and [Cache API](https://developer.mozilla.org/en-US/docs/Web/API/Cache), but Shaka's plugins will work on all browsers.

@chrisfillmore, it sounds like what you need is a hook or event to examine content metadata between manifest parsing and the start of streaming.  I believe this should be a separate feature request.

**Comment by joeyparrish** [comment]
Filed #1043 to address the scenario mentioned by @chrisfillmore.  Closing this issue.  Thanks!
