### ISSUE TITLE
How can we know if the license request was successful, and the CDM accepted the response?

### ISSUE THREAD

**Issue by chrisfillmore** [google/shaka-player#1035]
I have a requirement to signal to our downstream clients that the license request (and CDM update) was successful and we are able to play content.
```
// drm_engine
return session.update(response.data).then(function() {
  // I need to know this has happened
  if (updatePromise)
    updatePromise.resolve();
});
```
Could Shaka signal that the call to session.update() was fulfilled?

**Comment by michellezhuogg** [comment]
@joeyparrish Could you take a look to see if we should add the feature?

**Comment by joeyparrish** [comment]
I see no reason we couldn't add an informative event for this.  Adding to v2.3, with the caveat that it will skip to v2.4 if we don't have time.

**Comment by chrisfillmore** [comment]
@joeyparrish I can make a PR for this since delivering this I'm supposed to deliver this feature, not only for Shaka but also for our Safari player implementation. Here's what I had in mind, can you advise:

- Provide the player's `onEvent` callback to `new shaka.media.DrmEngine(...)`
- Invoke `onEvent` with a FakeEvent when the call to session.update() is fulfilled
- I was thinking of giving the event a type of `keysessionupdate`

Only thing I noticed was the signature for `new shaka.media.DrmEngine(...)` is getting a little long, and I see in other places you use a `playerInterface`. Would you suggest using a `playerInterface` in this case?

**Comment by joeyparrish** [comment]
Yes, absolutely.  DrmEngine is not directly accessible to apps through our exported API, so there's no compatibility concerns there.  A Player interface object makes sense.

**Comment by joeyparrish** [comment]
I'm not sure I like the event name "keysessionupdate", though.  It doesn't match current EME terminology, as we don't call them "key sessions".

How about "licenseupdate", "drmsessionupdate", or "drmupdate"?

**Comment by chrisfillmore** [comment]
I'm about done the work, and running the tests now I see this fail on master:

```
Safari 11.0.0 (Mac OS X 10.12.6) MediaSourceEngine removes segments FAILED
	Expected 15 to be close to 10.
	test/media/media_source_engine_integration.js:142:57
	promiseReactionJob@[native code]
	Expected 15 to be close to 20.
	test/media/media_source_engine_integration.js:143:58
	promiseReactionJob@[native code]
	Expected 25 to be 20.
	test/media/media_source_engine_integration.js:146:50
	promiseReactionJob@[native code]
	Expected 5 to be close to 10.
	test/media/media_source_engine_integration.js:147:58
	promiseReactionJob@[native code]
```

This is without my changes.

On the branch with my changes, in my most recent test run, I see this failure too:

```
Safari 11.0.0 (Mac OS X 10.12.6) MediaSourceEngine trims content at appendWindowEnd FAILED
	Expected 6.916666666666667 to be close to 10.
	http://localhost:9877test/media/media_source_engine_integration.js:332:57
	promiseReactionJob@[native code]
	Expected 6.916666666666667 to be close to 18, 1.
	http://localhost:9877test/media/media_source_engine_integration.js:335:57
	promiseReactionJob@[native code]
```

But I've run the tests a few times and I think I see varying behaviour out of some integration tests. Do you usually see 100% success rate across browsers for integration tests?

**Comment by chrisfillmore** [comment]
Nevermind I see you just posted about this in #1048.

**Comment by joeyparrish** [comment]
Yeah, I have the Safari 11 issues fixed locally with a new polyfill, but I am still in the process of writing a bug report to Apple about the `remove` failure.

**Comment by joeyparrish** [comment]
New MediaSource bug filed against Safari 11: https://bugs.webkit.org/show_bug.cgi?id=177884

**Comment by joeyparrish** [comment]
Cherry-picked to v2.2.3.
