### ISSUE TITLE
Support for MPD Anchors

### ISSUE THREAD

**Issue by ivivona** [google/shaka-player#1038]
Hi! I'm trying to play a live stream not from the live edge (now) but from the manifest first segment (ex: start from the beginning of a live concert). I read the specification and such issue can be solved using the MPD Anchors, specifying a t parameter. 
I'll tried using the shaka demo player (latest version) and it doesn't seem to be working (it always start form the live edge). Is it supported? Or should I try using the player API instead?

Thanks in advance.

**Comment by vaage** [comment]
@ivivona Could you provide more information? Is this in your app and you just looking for a way to start from the start of the video regardless of it being live? Or are you trying to prepare content for use in someone else's app and need a way to signal to them that they should start at the start and not the live edge?

**Comment by ivivona** [comment]
@vaage i control both the generation and the player, so any solution is ok, but I think it will be better to let the player know from where to reproduce using the info in the MPD (in this case the url anchor). The use case is: a "watch from the start" button in page A goes to the player in page B with certain manifest URL, the player's page is kind of generic because the the manifest could be a VOD or a live.

**Comment by vaage** [comment]
@ivivona When you load a manifest (`shaka.media.player.load`), there is an optional parameter you can set called `opt_startTime`. If you set that to `0`, does it solve your problem? That would be the simplest way to ensure that the player always starts playing the content from the start.

**Comment by ivivona** [comment]
@vaage thanks for the response. I understand that there is a javascript solution, but my question was if shaka implements/supports MPD Anchors as indicated in the DASH specification.

**Comment by joeyparrish** [comment]
Shaka Player does not support MPD anchors, but we do have other solutions to that problem.  As @vaage pointed out, you can specify a start time when you call `load()`.  For your case (starting a live stream at time zero), that seems like the best solution.

For more complex scenarios, you can configure a payable range.  See #246 for the discussion that led to that feature, and the `playRangeStart` and `playRangeEnd` fields of [https://shaka-player-demo.appspot.com/docs/api/shakaExtern.html#PlayerConfiguration](PlayerConfiguration) for the API.

Does that help answer your question?

**Comment by vaage** [comment]
@ivivona Was @joeyparrish able to answer your question? If so, feel free to close the issue.

**Comment by ivivona** [comment]
Yes, thanks. Anyway, should this be implement in the future?

**Comment by joeyparrish** [comment]
We don't have any plans to support MPD anchors at this time.  We believe that specifying start times and play ranges is a more general solution that applies across manifest types.
