### ISSUE TITLE
Getting current playback rate on auto

### ISSUE THREAD

**Issue by Awais-cb** [google/shaka-player#1041]
is there any way i can get current video playback quality or resolution on auto mode and display it to user so that user could know which quality is being played now?

i am try to append current quality on auto mode like this

`setInnerText(label, "Auto" + currentResolution);`

**Comment by Awais-cb** [comment]
any answer to that would be really appreciated!

**Comment by joeyparrish** [comment]
Yes, you can use the Track APIs and look for the active track:

```js
player.getVariantTracks().forEach(function(track) {
  if (track.active) {
    setInnerText(label, "Auto (" + track.width + " x " + track.height + ")");
  }
});
```

Does this help?

**Comment by Awais-cb** [comment]
hey @joeyparrish i fixed it using
`var currentRes = 'Adaptation: ' + shakaPlayer.getStats().width + "x" + shakaPlayer.getStats().height;`
please let me know if this is the right way btw thanks for your response much appreciated.

**Comment by joeyparrish** [comment]
That works, too.  getStats() should return the width & height of the active track.

Let us know if you need anything else!

**Comment by Awais-cb** [comment]
no sir not for now thanks for this awesome open source project
