### ISSUE TITLE
Event needed between manifest parsing and the start of streaming

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#1043]
@chrisfillmore writes in https://github.com/google/shaka-player/issues/1029#issuecomment-332386309:

> We have a scenario where we need to know the bandwidth levels from the manifest before we start playback, so that we can set the max bandwidth in order to restrict certain variants.

It sounds like we need a hook or event to examine content metadata between manifest parsing and the start of streaming.

The only tricky bit is to make sure that the event is dispatched in a synchronous way at the right point.  I *think* this should be after filtering based on MSE & EME, and after Track info is available, but before an initial track selection is made by AbrManager.  That will allow restrictions to be set before any segment requests are made.

**Comment by chrisfillmore** [comment]
Ooh, very nice. We would need to know bandwidth and codec information. Thanks Joey.

**Comment by joeyparrish** [comment]
That should all be available from `shakaExtern.Track`.  Let us know if there's anything missing!

**Comment by joeyparrish** [comment]
New method cherry-picked for v2.2.5.
