### ISSUE TITLE
Subtitles are not respect the region (tts:origin and tts:extent)

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#1045]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**:

**What version of Shaka Player are you using**: 2.2.2

**Can you reproduce the issue with our latest release version**: Yes

**Can you reproduce the issue with the latest code from `master`**: Yes

**Are you using the demo app or your own custom app**: Demo app

**What browser and OS are you using**: Chrome - Any

**What are the manifest and license server URIs**:
*(you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*
https://irtdashreference-i.akamaihd.net/dash/live/901161/bfs/manifestBR.mpd
https://shaka-player-demo.appspot.com/demo/#asset=https://irtdashreference-i.akamaihd.net/dash/live/901161/bfs/manifestBR.mpd;lang=es

**What did you expect to happen?**
Subtitles are shown in the correct region

**What actually happened?**
Subtitles are not respect the region (tts:origin and tts:extent)

Sample:
```
<tt xmlns="http://www.w3.org/ns/ttml" xmlns:tt="http://www.w3.org/ns/ttml" xmlns:ttm="http://www.w3.org/ns/ttml#metadata" xmlns:tts="http://www.w3.org/ns/ttml#styling" xmlns:ttp="http://www.w3.org/ns/ttml#parameter" xmlns:ebutts="urn:ebu:tt:style" xmlns:ebuttm="urn:ebu:tt:metadata" xml:lang="" ttp:timeBase="media">
  <head>
    <metadata>
      <ebuttm:documentMetadata>
        <ebuttm:conformsToStandard>urn:ebu:tt:distribution:2014-01</ebuttm:conformsToStandard>
      </ebuttm:documentMetadata>
    </metadata>
    <styling>
      <style xml:id="Style0_0" tts:fontFamily="proportionalSansSerif" tts:backgroundColor="#00000099" tts:color="#FFFF00" tts:fontSize="100%" tts:lineHeight="normal" ebutts:linePadding="0.5c" />
      <style xml:id="textAlignment_0" tts:textAlign="center" />
    </styling>
    <layout>
      <region xml:id="Region" tts:origin="10% 10%" tts:extent="80% 80%" tts:displayAlign="after" />
    </layout>
  </head>
  <body>
    <div>
      <p region="Region" style="textAlignment_0" begin="176:12:20.120" end="176:12:22.120" xml:id="sub_0">
        <span style="Style0_0">Ihr seid so fesch.</span>
      </p>
    </div>
  </body>
</tt>
```

**Comment by joeyparrish** [comment]
We parse the region data, but regions are not supported by the browser, so you would have to write a custom TextDisplayer to render your own cues.

For reference:
  - TextDisplayer interface docs: https://shaka-player-demo.appspot.com/docs/api/shakaExtern.TextDisplayer.html
  - Default TextDisplayer implementation which delegates to the browser: https://github.com/google/shaka-player/blob/master/lib/text/simple_text_displayer.js

We apologize for the inconvenience.

**Comment by avelad** [comment]
Thanks @joeyparrish !
