### ISSUE TITLE
Text parser plugin docs out of date

### ISSUE THREAD

**Issue by hghazzi** [google/shaka-player#1046]
It looks like the namespace of `TextEngine` was changed in `v2.2` from`shaka.media.TextEngine.registerParser` to `shaka.text.TextEngine.registerParser`. The docs still says `shaka.media` and there's is no mention of this change in in the upgrade guide.

Commit: 
https://github.com/google/shaka-player/commit/c6c6d058105dce25fb044e8884c4a179519d37f4#diff-3b4369b30c3ae2bbec5bd1048456ba71R91

Docs: 
https://shaka-player-demo.appspot.com/docs/api/tutorial-upgrade-v2-1.html
https://shaka-player-demo.appspot.com/docs/api/tutorial-plugins.html

**Comment by joeyparrish** [comment]
Good catch!  I'm sorry we made that mistake.  We will update the docs and get the fix out in v2.2.3.

**Comment by joeyparrish** [comment]
Cherry-picked to v2.2.3.
