### ISSUE TITLE
Concurrency Issues with Multiple Storage Instances

### ISSUE THREAD

**Issue by vaage** [google/shaka-player#1047]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**:
No

**What version of Shaka Player are you using**:
Master

**Can you reproduce the issue with our latest release version**:

**Can you reproduce the issue with the latest code from `master`**:
Yes

**Are you using the demo app or your own custom app**:
Custom App

**If custom app, can you reproduce the issue using our demo app**:
No. There are modifications needed to reproduce this bug as the demo app does not support concurrent downloads.

**What browser and OS are you using**:
Chrome on Mac

**What are the manifest and license server URIs**:
*(you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*

Using content from the demo app.

**What did you do?**

Create multiple instances of `shaka.offline.Storage` to download separate copies of content. For testing I had each instance download the same content.

**What did you expect to happen?**

I expected at content would download in parallel and would be playable offline after.

**What actually happened?**

The content downloads in parallel but they all use the same key so you lose all but one copy of the data. Since I had each instance download the same content, the one copy was still playable. I do not know what would happen if they were downloading different content.

**Comment by joeyparrish** [comment]
We have not been tagging this issue in commits so far.  I believe these are the relevant commits to date:

 - 07e81f7bc9af49f665f9551f2a5eea2e2b3a9ca9
 - 9e043882925fd8b3683b558daa6d37388a2dd113
 - ddf8cb838e0344a733ea9bde14c0d56a2a527ba9
 - d6f6927de3c15062d02a6968204b716224992524
 - 3cd9b6af3e386e9be12b537291aff2f589ac3fce
 - ee006d45238ddf5f924076528c09a433b4d581a1
 - d90821a1a5830cdf09caa9707a99c945979ffd0e
 - b68623180c9146b8f778d216529b02fed10fd296
 - b98ce99f08e6f22d41eb5e87cea051f7a515d65f
 - 0e43b62f04fd4093fe304746e46530582ec93392
 - 2f47e6d7695bd22c939135e207f26f18e3dff76d
 - 540e533e69e5d16b8f21456a7da5f3d0afe8dcbd
 - 834d960f88d7f23b1ba107b108e90913f3c0b7e4
 - 6a03ceb30febf3462bcbab386e783ee3f76ea5b9
 - 8f45f7939de02fed60a5018a3343560cb7256063
 - b53f5a0816b2bbab4481928704ed277983e86b6f
 - dff382b9a3eb792f52c5c85955350d5b04c0f2d4
 - 3399292d4991c9cbae5b6e2d1307b15313903f1b
 - e7c5a3a8aae16c3e542efd498de9b12652b8e444
 - b8e0f8028daf91e6536f60febc520a7565f8972e
 - 46685fbd15b4e777a4c06d3d3b87213125879c40
