### ISSUE TITLE
It is possible to obtain an unique identifier id for a browser (Chrome/Firefox), using shaka-player and widevine?

### ISSUE THREAD

**Issue by aleian84** [google/shaka-player#1050]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**:
Y

**What version of Shaka Player are you using**:
2.2.2

**Can you reproduce the issue with our latest release version**:
N/A
**Can you reproduce the issue with the latest code from `master`**:
N/A

**Are you using the demo app or your own custom app**:
Custom App

**If custom app, can you reproduce the issue using our demo app**:
N/A

**What browser and OS are you using**:
Chrome/ Firefox

**What are the manifest and license server URIs**:
*(you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*
N/A

**What did you do?**
I'm trying to obtain an unique identifier id for Chrome and Firefox using shaka-player and widevine

**What did you expect to happen?**
N/A

**What actually happened?**
N/A

**Comment by joeyparrish** [comment]
No, you can't use Shaka Player or Widevine to obtain a unique identifier for the user.  This goes against privacy principles on the web.

While DRM systems may create persistent identifiers if configured to do so ([persistentStateRequired in advanced DRM config in Shaka](https://shaka-player-demo.appspot.com/docs/api/tutorial-drm-config.html)):
 * some platforms show a prompt for user consent first
 * those identifiers are not available to JavaScript in any way
 * those identifiers may be cleared by the user at any time through the "media licenses" checkbox in "Clear browsing data"

These restrictions are designed to avoid creating new ways to track users without their knowledge or consent.  Shaka Player cannot and will not provide means of circumventing these basic privacy protections.
