### ISSUE TITLE
MediaSource duration should be +Infinite for Live Streams

### ISSUE THREAD

**Issue by beaufortfrancois** [google/shaka-player#1052]
Steps to reproduce with Shaka Player v2.2.2-debug:
1. Go to https://shaka-player-demo.appspot.com/demo/#asset=//storage.googleapis.com/shaka-live-assets/player-source.mpd;lang=en-US
2. Click "Load" button
3. Open DevTools and run `shakaDemo.localPlayer_.mediaSource_.duration`;

What is the expected result?
It should be `+Infinite` as this is how are defined live streams

What happens instead?
It is a finite value `4294967296`.

Background: https://googlechrome.github.io/samples/media/live-seekable-range.html and https://www.chromestatus.com/feature/5671401352593408

**Comment by joeyparrish** [comment]
Although live streams should ideally have an infinite duration in MediaSource and HTML5 video, that doesn't work across browsers.  We are glad Chrome has implemented seekable range for live streams, but everywhere else, an infinite duration precludes seeking.

Quoted from the chromestatus.com page you linked:
> Consensus & Standardization
> - Firefox: In development
> - Edge: Public support
> - Safari: No public signals

The best we can do across browsers is to set duration to a large, finite value.  Here's what we [currently do](https://github.com/google/shaka-player/blob/859d7d1a8f729f84e9c7884ede0a068b4be1ed20/lib/media/streaming_engine.js#L910) in `StreamingEngine`:

```js
shaka.media.StreamingEngine.prototype.setDuration_ = function() {
  var duration = this.manifest_.presentationTimeline.getDuration();
  if (duration < Infinity) {
    this.playerInterface_.mediaSourceEngine.setDuration(duration);
  } else {
    // Not all platforms support infinite durations, so set a finite duration
    // so we can append segments and so the user agent can seek.
    this.playerInterface_.mediaSourceEngine.setDuration(Math.pow(2, 32));
  }
};
```

In the mean time, to determine if a stream is live without examining duration, we provide the [`isLive()` method on Player](https://shaka-player-demo.appspot.com/docs/api/shaka.Player.html#isLive), which returns true if the currently-loaded content is live.

**Comment by beaufortfrancois** [comment]
Noted. Thanks for the explanation Joey.
