### ISSUE TITLE
Chrome crashes with experimental flags enabled

### ISSUE THREAD

**Issue by OrenMe** [google/shaka-player#1053]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**:

**What version of Shaka Player are you using**: v2.2.2

**Can you reproduce the issue with our latest release version**: yes

**Can you reproduce the issue with the latest code from `master`**: didn't try yet

**Are you using the demo app or your own custom app**: demo app

**If custom app, can you reproduce the issue using our demo app**: 

**What browser and OS are you using**: Chrome 61 on Mac OS

**What are the manifest and license server URIs**: https://shaka-player-demo.appspot.com/demo/#asset=//storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd;lang=en-US
*(you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*

**What did you do?**
load demo app with first default source

**What did you expect to happen?**
play till the end

**What actually happened?**
crash after a couple of seconds
this also happens on our player as well with other content

**Comment by OrenMe** [comment]
Apparently it is due to a "Experimental Web Platform features" flag I opened in chrome://flags so we can turn the alarm off for now.
This is probably a bug with Chrome so I will report it in Chromium, but this might be an indication that a crash is about to happen when this feature will get its flag removed.

**Comment by joeyparrish** [comment]
Please link to the chrome bug here so that we can follow along.  Thanks!

**Comment by hbengali** [comment]
I was able to repro this and have filed a chromium bug:
https://bugs.chromium.org/p/chromium/issues/detail?id=772508

**Comment by joeyparrish** [comment]
Thanks!

**Comment by OrenMe** [comment]
Thanks @hbengali - I was in transit till today and wanted to debug to get more info before opening the bug.
Do you happen to know why I can't access the chromium bug?

**Comment by joeyparrish** [comment]
No longer occurs with the current stable version of Chrome.
