### ISSUE TITLE
buffer ahead for live stream

### ISSUE THREAD

**Issue by kuznetcoff777** [google/shaka-player#1054]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**: yes

**What version of Shaka Player are you using**: latest

**Can you reproduce the issue with our latest release version**:yes

**Can you reproduce the issue with the latest code from `master`**: yes

**Are you using the demo app or your own custom app**: custom

**If custom app, can you reproduce the issue using our demo app**: yes

**What browser and OS are you using**: chrome

**What are the manifest and license server URIs**: sent to gmail
*(you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*

**What did you do?** Opened live stream with suggestet presentation delay = 20s
checked how buffer worked, it fetches 20-30 seconds ahead, as just described in #1051.
After that i changed suggested presentation delay to 60, reloaded player, saw that delay between player time and real time is about 60s (as just expected) but player still fetches the same 20-30 seconds ahead, but supposed to fetch ~60 seconds ahead.

**Comment by kuznetcoff777** [comment]
One thing i also cannot understand. What if we have big timeShiftBufferDepth and we paused for several minutes. What time will player buffer ahead? Still the same supposed suggested presentation delay?

**Comment by joeyparrish** [comment]
We never buffer more than bufferingGoal + 1 segment.  For 10s segments and 20s bufferingGoal, that could be up to 30s.

We can't reach bufferingGoal if the content is not available.  Video's currentTime, mpd's timeShiftBufferDepth, and mpd's suggestedPresentationDelay all affect what is available.  If you are less than N seconds from the end of what is available from the server, you can't buffer N seconds of content.

The timeShiftBufferDepth and suggestedPresentationDelay attributes don't affect buffering goals, but do dictate what is available to buffer.

What is your player configuration?  The default bufferingGoal is 30s, if I recall correctly.

**Comment by joeyparrish** [comment]
Once we have your configuration, we will attempt to reproduce and explain what is happening.

**Comment by kuznetcoff777** [comment]
The same issue i got on demo app.
My config is 
streaming:
bufferBehind:30
bufferingGoal:10
failureCallback:ƒ ()
ignoreTextStreamFailures:false
jumpLargeGaps:false
rebufferingGoal:2
retryParameters:{maxAttempts: 2, baseDelay: 1000, backoffFactor: 2, fuzzFactor: 0.5, timeout: 0}
smallGapLimit:0.5
startAtSegmentBoundary:true


So it seems to I made wrong conclusion from #1051.

So now as i understand - when we watch very live content - only suggested presentation delay is active, so player can fetch only that segments which is in presentation delay time.

But when we paused (and buffer depth is huge) for a couple of minutes, if only buffering goal is active in this case? If we configure buffering goal = 10 seconds, then player can fetch bufferingGoal + 1 segment.

If everyting i described correctly?

**Comment by TheModMaker** [comment]
@kuznetcoff777 That is correct.  We will buffer up to bufferingGoal + 1 segment.  So in your case, we will only buffer 30 seconds of content plus up to a partial segment.  If you're close to the live edge, there will only be `suggestedPresentationDelay` amount of content available, so we don't have any more content to buffer.

Also note that you may need to reload the asset if you change the `suggestedPresentationDelay`.
