### ISSUE TITLE
Question: Checking Dash Support for Older Clients

### ISSUE THREAD

**Issue by peterdotjs** [google/shaka-player#1056]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**:
Yes

**What version of Shaka Player are you using**:
2.2.1

Question: Would you recommend also checking for device version in conjunction with `isBrowserSupported` in order to handle older android devices that don't support DASH or is the existing check enough? 
https://github.com/google/shaka-player/blob/d1ddd720c29a72c6f6b94ae15457b44178e2f72b/lib/player.js#L433-L439

Thanks!

**Comment by joeyparrish** [comment]
DASH is implemented by Shaka Player, not the platform, so there shouldn't be any issue with platform support.  If isBrowserSupported returns true, and you are still unable to play DASH content, please file a bug with us to investigate further.

Does that answer your question?

**Comment by peterdotjs** [comment]
Yup, thanks for confirming!
