### ISSUE TITLE
Player get stuck on seeking back - safari 9

### ISSUE THREAD

**Issue by yairans** [google/shaka-player#1059]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**: Yes

**What version of Shaka Player are you using**: 2.2.2

**Can you reproduce the issue with our latest release version**: Yes

**Are you using the demo app or your own custom app**: Demo app

**What browser and OS are you using**: safari 9.1.3 / OS X El Capitan

**What are the manifest and license server URIs**:
https://shaka-player-demo.appspot.com/demo/#asset=https://qa-nginx-vod.dev.kaltura.com/dash/p/1091/sp/109100/serveFlavor/entryId/0_fl4ioobl/v/2/flavorId/0_,2mljkpm2,24x9f8vn,sj9skgo4,udfmex0j,k57g4n4f,xgb3ecqf,frro2i00,/forceproxy/true/name/a.mp4.urlset/manifest.mpd;lang=en-US

**What did you do?**
Load -> play for a min -> seek back to ~0.10

**What did you expect to happen?**
Playback from the seeked position

**What actually happened?**
The player get stuck

log:
[Log] Choosing new streams after changing configuration (demo, line 81)
[Log] switch: Stream (video:2) already active (demo, line 81)
[Log] switch: Stream (audio:3) already active (demo, line 81)
[Log] switch: Stream (text:7) already active (demo, line 81)
[Log] Choosing new streams after changing configuration (demo, line 81)
[Log] switch: Stream (video:2) already active (demo, line 81)
[Log] switch: Stream (audio:3) already active (demo, line 81)
[Log] switch: Stream (text:7) already active (demo, line 81)
[Log] Choosing new streams after changing configuration (demo, line 81)
[Log] switch: Stream (video:2) already active (demo, line 81)
[Log] switch: Stream (audio:3) already active (demo, line 81)
[Log] switch: Stream (text:7) already active (demo, line 81)
[Log] Unload latency:  0.017 (demo, line 81)
[Info] No Period ID given for Period with start time 0,  Assigning a default (demo, line 81)
[Log] Found variant with audio and video content, so filtering all periods. (demo, line 81)
[Log] codecs (3) (demo, line 81)
[Log] onChooseStreams_  {startTime: 0, textStreams: Array, variants: Array} (demo, line 81)
[Log] Choosing new streams after period changed (demo, line 81)
[Log] init: completed initial Stream setup (demo, line 81)
[Log] (audio:3) (3) (demo, line 81)
[Log] (video:1) (3) (demo, line 81)
[Log] (text:7) (3) (demo, line 81)
[Log] (text:7)  "buffered to end of presentation" (demo, line 81)
[Log] Load latency:  0.195 (demo, line 81)
[Log] (audio:3)  "startup complete" (demo, line 81)
[Log] (all) setting up Period 0 (demo, line 81)
[Log] (all) Period 0 is being or has been set up (demo, line 81)
[Log] (all) Stream 3 is being or has been set up (demo, line 81)
[Log] (all) Stream 1 is being or has been set up (demo, line 81)
[Log] (all) Stream 7 is being or has been set up (demo, line 81)
[Log] canSwitch_ (demo, line 81)
[Log] Calling switch_(), bandwidth=459213 kbps (demo, line 81)
[Log] switch_ (demo, line 81)
[Log] switch: switching to Stream (video:2) (demo, line 81)
[Log] switch: Stream (audio:3) already active (demo, line 81)
[Log] (video:2) (3) (demo, line 81)
[Log] Calling switch_(), bandwidth=901229 kbps (demo, line 81)
[Log] switch_ (demo, line 81)
[Log] switch: Stream (video:2) already active (demo, line 81)
[Log] switch: Stream (audio:3) already active (demo, line 81)
[Log] Calling switch_(), bandwidth=996760 kbps (demo, line 81)
[Log] switch_ (demo, line 81)
[Log] switch: Stream (video:2) already active (demo, line 81)
[Log] switch: Stream (audio:3) already active (demo, line 81)
[Log] Calling switch_(), bandwidth=1116194 kbps (demo, line 81)
[Log] switch_ (demo, line 81)
[Log] switch: Stream (video:2) already active (demo, line 81)
[Log] switch: Stream (audio:3) already active (demo, line 81)
[Log] Calling switch_(), bandwidth=1167670 kbps (demo, line 81)
[Log] switch_ (demo, line 81)
[Log] switch: Stream (video:2) already active (demo, line 81)
[Log] switch: Stream (audio:3) already active (demo, line 81)
[Log] Calling switch_(), bandwidth=1281775 kbps (demo, line 81)
[Log] switch_ (demo, line 81)
[Log] switch: Stream (video:2) already active (demo, line 81)
[Log] switch: Stream (audio:3) already active (demo, line 81)
[Log] Calling switch_(), bandwidth=1246710 kbps (demo, line 81)
[Log] switch_ (demo, line 81)
[Log] switch: Stream (video:2) already active (demo, line 81)
[Log] switch: Stream (audio:3) already active (demo, line 81)
[Log] Calling switch_(), bandwidth=1260910 kbps (demo, line 81)
[Log] switch_ (demo, line 81)
[Log] switch: Stream (video:2) already active (demo, line 81)
[Log] switch: Stream (audio:3) already active (demo, line 81)
[Log] (all): seeked: buffered seek: playheadTime=8.03106647314949 (demo, line 81)
[Info] Ignoring large gap at  8.03106647314949 (demo, line 81)

**Comment by vaage** [comment]
@yairans I am sorry to inform you but we have stopped officially supporting Safari 9. Our current support is for Safari 10 to 11.
