### ISSUE TITLE
Playback crashes when USB headset is suddenly unplugged in Windows + Chrome

### ISSUE THREAD

**Issue by adgllorente** [google/shaka-player#1060]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**:
Yes

**What version of Shaka Player are you using**:
Shaka Player v2.2.2-debug

**Can you reproduce the issue with our latest release version**:
On the demo app.

**Can you reproduce the issue with the latest code from `master`**:
On the demo app.

**Are you using the demo app or your own custom app**:
On the demo app.

**If custom app, can you reproduce the issue using our demo app**:
Yes

**What browser and OS are you using**:
- Browser: Chrome Versión 61.0.3163.100
- OS: Windows 10 Pro / Version: 1703 / Compilation number: 15063.632

It works in:
- MacOS + Chrome
- Windows + Edge or Firefox

**What are the manifest and license server URIs**:
I've tested with: https://shaka-player-demo.appspot.com/demo/#asset=//storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd;lang=es

**What did you do?**
I start playback with a headset connected to USB. While the video is playing I suddenly unplug the headset from the USB.

**What did you expect to happen?**
I would expect playback to continue.

**What actually happened?**
Video crashes showing an error like this:
![img_10102017_172832_0](https://user-images.githubusercontent.com/1067480/31395878-2450fb02-ade2-11e7-8191-662d8367e219.png)

```
main.js:547 Player error shaka.util.Error
shakaDemo.onError_ @ main.js:547
```

**Comment by vaage** [comment]
This appears to be a Chrome problem and they are already looking into it. https://bugs.chromium.org/p/chromium/issues/detail?id=751780#c4

**Comment by vaage** [comment]
@adgllorente We were not able to reproduce this issue. As chrome is aware of issues with USB audio (see the bug above) there is little we can do.

**Comment by adgllorente** [comment]
Thanks for the information @vaage, I've seen the bug related has been fixed in Chrome 62. I've tried with a Chrome Canary (v63) and I have reproduced it but just sometimes and when the headset is plugged, anyway I will report this to the Chrome team since this is on their side.
