### ISSUE TITLE
JumpLargeGaps prevents seeking sometimes.

### ISSUE THREAD

**Issue by bwallbergBonnier** [google/shaka-player#1061]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**: Yes

**What version of Shaka Player are you using**: 2.2.1

**Can you reproduce the issue with our latest release version**: Yes

**Can you reproduce the issue with the latest code from `master`**: Yes

**Are you using the demo app or your own custom app**: demo

**If custom app, can you reproduce the issue using our demo app**:

**What browser and OS are you using**: Chromecast ( Chrome )

**What are the manifest and license server URIs**: Sintel 4k in the demo app
*(you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*

**What did you do?**
1) Open https://shaka-player-demo.appspot.com/demo/#asset=//storage.googleapis.com/shaka-demo-assets/sintel-widevine/dash.mpd;jumpLargeGaps;lang=en-GB

Make sure that `jumpLargeGaps` is true 

2) Load the asset and cast to a Gen 2 chromecast ( Should be reproducible on any chromecast device but that's the one I used )

3) Seek to random positions with a few minutes between them

**What did you expect to happen?**
All seeks should seek to the selected position

**What actually happened?**
Sometimes a seek does nothing

The issue seems to originate in `shaka.media.Playhead.prototype.onPollGapJump_` it detects a large gap and seeks back to the previous position. Preventing it from running when `this.video_.seeking` is `true` seems to resolve the issue but I'm not sure if this breaks any other functionality.

**Comment by theodab** [comment]
I've reproduced it. It looks like it only happens when seeking backwards, which makes sense since you only jump gaps forward.
When I see it happen, it looks like it is momentarily going to the new position and then jumping back to where it was before, so it does look like it's gap-jumping.
I'll see if disabling long gap jumps messes up anything.

**Comment by joeyparrish** [comment]
Cherry-picked for v2.2.3.

**Comment by bwallbergBonnier** [comment]
Awesome and thanks @theodab :)

**Comment by TheModMaker** [comment]
Unfortunately this fix broke seeking into a gap and gaps before the start (since `video.seeking` will be true in those cases).  So this will require a different fix.

**Comment by theodab** [comment]
On further inspection, this appears to be a race condition within the playhead.
The playhead has a timer that checks if it should gap jump, every 0.25 seconds. We use the 'seeking' event to check whether we should clear the buffer after a seek, and the 'seeking' event is asynchronously fired after currentTime is changed. There is the possibility that currentTime is changed, the playhead decides to gap jump back to its previous position, and THEN the 'seeking' event is fired. That means that this is not a Chromecast specific error, it is simply more likely to happen on slower platforms such as Chromecast.

**Comment by theodab** [comment]
Oh, this fix needs to be on the cast receiver, and we don't have cast receiver nightly builds, so while the issue is closed you won't be able to see it on the nightly. Just FYI.

**Comment by joeyparrish** [comment]
Cherry-picked to v2.3.1.

**Comment by joeyparrish** [comment]
Cherry-picked for v2.2.10.

**Comment by johnBartos** [comment]
@TheModMaker This still seems to be the case (in IE/Edge). Has there been a resolution on start gap seeking?

**Comment by joeyparrish** [comment]
@johnBartos, are you saying you can still reproduce this issue on IE and Edge?  What version of Shaka Player are you using?

**Comment by johnBartos** [comment]
@joeyparrish Thanks for the quick reply. Yeah we can still reproduce on the latest version (2.3.2), in JW and the demo. Test stream: https://s3.amazonaws.com/bob.jwplayer.com/~alex/107415/dash/dash2.mpd

IE/Edge will buffer this stream at time ~1.5s, keeping the tag in `readyState 1`. Chrome/FF will buffer at 0 (thus avoiding the issue altogether). So this may still exist there too (unless you're massaging the buffered start internally).

We have a workaround in JW where we'll seek to `buffered.start(0)` on the first `progress` event if we're not already at `buffered.start(0)`. With safety checks it seems to work fine (e.g. ensuring were in `readyState 1`) but there's probably a few edge cases we're missing.

**Comment by TheModMaker** [comment]
@johnBartos I think you should file a new issue for that, thanks.

**Comment by johnBartos** [comment]
@TheModMaker Done https://github.com/google/shaka-player/issues/1281
