### ISSUE TITLE
Cast receiver progress bar stays at zero

### ISSUE THREAD

**Issue by theodab** [google/shaka-player#1064]
When casting, the cast receiver's progress bar says it's at time 0, no matter what time it is. This is probably incorrect behavior.

**Comment by theodab** [comment]
It looks like we just need to update the cast receiver app. I uploaded the most recent Shaka version to the debug id, and it worked fine.

**Comment by joeyparrish** [comment]
The receiver is up-to-date with the latest release, but we are preparing another one.  If the receiver for v2.2.3 is not fixed, then the fix was something that has not yet been cherry-picked from `master` to `v2.2.x`.

**Comment by joeyparrish** [comment]
This is fixed in v2.2.x, presumably by 4670d6ccab03d15e6ad1565bd4186db7bf36c7c2.
