### ISSUE TITLE
Optional StartTime is not working properly because of invalid startTime check

### ISSUE THREAD

**Issue by SemihGk** [google/shaka-player#1069]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**:
Yes
**What version of Shaka Player are you using**:
latest
**Can you reproduce the issue with our latest release version**:
yes
**Can you reproduce the issue with the latest code from `master`**:
yes

**What did you do?**
I sent optional startTime paramater to [shaka.Player.load()](https://github.com/google/shaka-player/blob/master/lib/player.js#L490) method as 0, but video was not starting from currentTime = 0. After some investigation, I found some invalid checks on your code blocks that handles startTime. Please check
https://github.com/google/shaka-player/blob/master/lib/player.js#L818 .
At this line, PlayHead method recieves null instead of 0.

Also: https://github.com/google/shaka-player/blob/master/lib/media/playhead.js#L201
Same problem exists at this line as well. 

After fixing this 2 line, it works well. It should be a quick fix for you since we may need this fix soon. If you prefer a PR, I do not mind to create one as well.

Thanks,
Semih.

**Comment by chrisfillmore** [comment]
To add more context: we need to be able to set a startTime of 0 in order to support restartable live content.

**Comment by TheModMaker** [comment]
Thanks for finding this, will have a fix up soon.

**Comment by joeyparrish** [comment]
Cherry-picked to v2.2.3.

**Comment by joeyparrish** [comment]
A follow-up fix (fix of the fix) has been cherry-picked to v2.2.4.
