### ISSUE TITLE
Allow client app to make the license request?

### ISSUE THREAD

**Issue by chrisfillmore** [google/shaka-player#1075]
Could Shaka allow the client application to make the license request, and return the license response back to the player?

```
// Request failed!
goog.asserts.assert(error instanceof shaka.util.Error,
                    'Wrong NetworkingEngine error type!');
var shakaErr = new shaka.util.Error(
    shaka.util.Error.Severity.CRITICAL,
    shaka.util.Error.Category.DRM,
    shaka.util.Error.Code.LICENSE_REQUEST_FAILED,
    error);
this.onError_(shakaErr);
if (activeSession && activeSession.updatePromise)
  activeSession.updatePromise.reject(shakaErr);
```

We have many cases where the license server will send back an HTTP error status along with an error code which we need to triage, and it's possible we could attempt the request again. But with the above logic, the updatePromise gets rejected.

Such functionality would be a long-term interest of ours so we could probably provide a PR for it. But what are your thoughts on this?

**Comment by joeyparrish** [comment]
You should be able to do this with async response filters.  You can examine the response, make an additional request if appropriate, then replace the original response body with the second response.

Would this help?

**Comment by TheModMaker** [comment]
We also already do retry logic for non 2xx response codes.  So if we (for example) get a 500 response, we will simly wait a second and resend the request.  We will retry for any non-2xx response except 401/403.  You can set the DRM retry count to a larger number and we will retry that number of times before registering a failure. (this logic is inside `NetworkingEngine.request`)

```js
player.configure({drm: {retryParameters: {maxAttempts: 5}}});
```

Also, you can't use a response filter for retrying since a response filter isn't ran for error cases, only when we get a 2xx response from the server.  But you could retry if the server gives a 2xx response but the response is wrapped in some error text.

**Comment by chrisfillmore** [comment]
Our license request bodies look roughly like:

```
{
  authorizationToken: (some data here)
  licenseChallenge: (base64-encoded license challenge here)
}
```

The server may send back a response, with HTTP 401, and a response body:

```
{
  errorCode: 1234
}
```

Suppose I know that this means "Invalid token". I need to initiate another flow to obtain a new `authorizationToken` and send the license request again.

I can't do this with a response filter since those aren't invoked due to HTTP 401. I also don't want to just retry right await, because I need to do some other work before retrying.

**Comment by TheModMaker** [comment]
It looks like we need an app callback to handle network errors and retries.  This is possible for media streaming using #960.  But it isn't possible for license requests (or manifest requests for that matter).  We will need to think about how this will be best implemented.

**Comment by chrisfillmore** [comment]
Thanks @TheModMaker, let me know if we can help.

**Comment by chrisfillmore** [comment]
This is back on my mind because I'm part of a week-long lockdown to investigate our error rate. So I wanted to add another note:

In our production application, error statistics are tracked via [New Relic](https://newrelic.com/), which informs management / executive decisions about whether or not, for example, we are ready for expanded beta or public launch. Some Shaka errors (notably LICENSE_REQUEST_FAILED) have to be translated to errors in our own domain because we support other players as well.

So there are two main reasons why I would like to make the license request myself:

- License request failure handling (described in this ticket)
- End-to-end error handling

I would argue that Shaka performing the license request does not add value for the client application, because:

1. The client almost certainly has its own networking stack already
2. The client provides Shaka the license URL
3. The client has to register request/response filters for license wrapping/unwrapping

I don't really want a handful of hooks into Shaka. It's awkward, when what I really want is to handle the process end-to-end myself. I would far prefer a simple callback on Player, which is invoked when it needs a license. Here is what I propose:

1. Add a new property to `PlayerConfiguration` called `drm.licenseRequestHandlers`, with keySystems as keys, Functions as values. Player will pass these values on to DrmEngine.
2. If a callback is set for a given keySystem, `DrmEngine#sendLicenseRequest_` will forego making the request, and instead invoke the provided callback with the challenge message.
3. The callback is expected to return a license.
4. Add a new error code LICENSE_REQUEST_HANDLER_ERROR in case the callback throws.
5. Update `DrmEngine#unpackPlayReadyRequest_` to simply extract the challenge message, and not to populate a Shaka Request object (since we would want to share this behaviour with the request handlers). Although there is some question of what to do with the HttpHeader PlayReady information.

I can make a PR with these changes but I would like your feedback first.

**Comment by chrisfillmore** [comment]
It has occurred to me that I could potentially get what I want by providing my own networking plugin that proxies requests to our own networking stack. I will look into that as it could be simplest for all involved.

**Comment by joeyparrish** [comment]
Honestly, `drm.licenseRequestHandlers` seems like a lot of effort, and I don't completely understand why it is better for you to make the request yourself.  However, if you want to do it, I think a scheme plugin might be best.

Imagine that your license URI was "drm:playready" or "drm:widevine", and you register a plugin for the "drm" scheme.  You can handle the whole thing there, using your own net stack, etc.

Is that helpful?

**Comment by chrisfillmore** [comment]
I think I'll register my own plugin for `http` and `https`, if `requestType === LICENSE` handle it myself, and if not pass it off to one of Shaka's HTTP plugins. At quick glance I think that should work.

I work on a client SDK that provides downstream client UI teams with integrations for two things:
- players
- hosted entitlement/DRM services

In our architecture, these two concerns are decoupled, and each has a dependency on our core SDK abstractions, but players know nothing about DRM services and DRM services know nothing about playback. This makes it very easy to swap player implementations (e.g. we support playback in Safari via native `src=`), and we can reuse service integrations across different projects in different HTML5 environments.

Having the player do the license request is awkward for us because it involves piping multiple callbacks through our core SDK and reasoning about Shaka's networking behaviour. Philosophically, Shaka's evaluation of HTTP status codes in the networking layer is at odds with our design; we consider this to be application-specific business logic.

The historical motivation for this design comes from iOS, where AVPlayer does not do license networking itself. AVPlayer tells the client that it needs a license, and the client can do whatever it wants as long as it provides the player a license. Our design on other platforms has followed this model.

**Comment by chrisfillmore** [comment]
With #1296 this is what I will do:

```
var customHttpPlugin = function (uri, request, requestType) {
  if (requestType === shaka.net.NetworkingEngine.RequestType.LICENSE) {
    // Send it to my networking stack
  } else if (shaka.net.HttpFetchPlugin.isSupported()) {
    return shaka.net.HttpFetchPlugin(uri, request, requestType);
  } else {
    return shaka.net.HttpXHRPlugin(uri, request, requestType);
  }
}

shaka.net.NetworkingEngine.registerScheme('http', customHttpPlugin,
    shaka.net.NetworkingEngine.PluginPriority.APPLICATION);
shaka.net.NetworkingEngine.registerScheme('https', customHttpPlugin,
    shaka.net.NetworkingEngine.PluginPriority.APPLICATION);
```

This seems manageable to me, if it works for you!

**Comment by joeyparrish** [comment]
Okay, that sounds good.  #1296 looks good to me.  Thanks!

**Comment by chrisfillmore** [comment]
Going to close this given the workaround I proposed above.

If there is an opportunity for redesign in a future major version increment, please consider adding a formal mechanism for the client to handle the license request. Thanks for the discussion!

**Comment by joeyparrish** [comment]
Will do.  Thanks!
