### ISSUE TITLE
License URL in manifest

### ISSUE THREAD

**Issue by aaani** [google/shaka-player#1076]
As per http://dashif.org/wp-content/uploads/2016/12/DASH-IF-IOP-v4.0-clean.pdf

```
One can also use HTTPS for retrieving other types of data carried with an MPD that are HTTP-
 URL based, such as DRM licenses specified within the <ContentProtection> descriptor:

 <ContentProtection schemeIdUri="http://example.net/052011/drm">
 <drm:License>https://MoviesSP.example.com/protect?license=kljklsdfiowek</drm:License>
 </ContentProtection>
```
I am wondering if support for license uri in `<drm:License>` or `schemeIdUri` is implemented by Shaka player. I tried it and it doesn't seem to make any requests to either of them.

**Comment by TheModMaker** [comment]
That is only an example, not a specification.  The contents of a `<ContentProtection>` element is dependent on the key system.  In this case, the contents is defined by the non-existent, example key system `http://example.net/052011/drm`.  PlayReady has an element `<ms:laurl>` to specify the url, which you can follow that feature in #1010 and #484.  Widevine doesn't have a standardized way of providing the URL in the manifest.

The `schemeIdUri` attribute specifies the type of key system that element is dealing with.  It is only a URL in that example.  For example, the `schemeIdUri` for Widevine is `urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed`.

The preferred way is to specify the URL in the app by using `player.configure`:

```js
player.configure({drm: {servers: {
  'com.widevine.alpha': 'https://widevine-proxy.appspot.com/proxy',
}}});
```

**Comment by aaani** [comment]
Makes sense. Thanks for the clarification @TheModMaker.
