### ISSUE TITLE
Playback fails with MS error 8004b896 on Edge 15 if license takes longer than ~200 ms

### ISSUE THREAD

**Issue by TheJohnBowers** [google/shaka-player#1077]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**:

**What version of Shaka Player are you using**:
Multiple.  I tried 2.3 and master today and found no difference in behavior
**Can you reproduce the issue with our latest release version**:
Yes
**Can you reproduce the issue with the latest code from `master`**:
Yes
**Are you using the demo app or your own custom app**:
Demo App
**If custom app, can you reproduce the issue using our demo app**:
N/A
**What browser and OS are you using**:
MS Edge 40.15063.0.0 - MS EdgeHTML 15.15063
**What are the manifest and license server URIs**:
*(you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*
I have multiple VDMS assets that I am running into this issue with as I work on getting playready support running, but I have discovered that I can reproduce the issue with the Axinom Multi DRM assets in the demo app.  I liked using the first one for testing because it is a single license request.  So you can easily observe what happens with a single license request.

**What did you do?**
I have been observing that playback starts are super flaky.  I can watch our license server and proxy and everything seems to be fine.  Also the edge network pane will show license returning successfully, but sometime playback starts and sometimes it does not.  If it does not start it always gives this MEDIA.VIDEO_ERROR(5,8004b896) error.    I started to suspect that it was related to the length of time it takes to get a response from the license server.

Today I tried to start playback 100 times to test this and the evidence supports it.  Every time the license request came back in 190ms or less playback would work.  Everytime it was over 200ms it would fail with the above error.  EVERY TIME -- No exception in the number of starts I tried.  There were a few times it got close to 200ms (198, 199).  In those cases the behavior was somewhat random.  One at 198 failed while one at 199 succeeded for example. 

**What did you expect to happen?**
I do not expect playback to fail based upon the length of time it takes to acquire a license!  

**What actually happened?**
Kind of already described this, but license requests longer than 200ms would cause playback to fail to start.
![shaka_pr_gt_200ms_failure](https://user-images.githubusercontent.com/26491119/31839571-e487da58-b59e-11e7-9641-9a8982e97147.png)

**Comment by chrisfillmore** [comment]
I saw this MediaError with code 5 in another scenario recently. This is an MS-specific error code.

It used to be described here:
https://msdn.microsoft.com/en-us/library/ff974742(v=vs.85).aspx

But now the above link just forwards to MDN. Wayback Machine to the rescue:

https://web.archive.org/web/20171004203049/https://msdn.microsoft.com/en-us/library/ff974742(v=vs.85).aspx

> **MEDIA_ERR_SRC_NOT_SUPPORTED (5)**
> The encrypted media stream could not be played. This is because of one of the following conditions:
> - A key was not provided and a onmsneedkey handler was not provided
> - The provided key could not be applied.
> - Decryption is not supported for this media data.

Just FYI

**Comment by joeyparrish** [comment]
According to Microsoft, 8004b896 is a playready error:

https://msdn.microsoft.com/en-us/library/dn468822.aspx

> MSPR_E_NO_DECRYPTOR_AVAILABLE	Failure occurred when attempting to find a correct PlayReady decryptor object - no decryptor was found.	0x8004B896

Is it a race between playback and licensing?  Does it take 200ms to get an encrypted segment?

What happens if you don't autoplay the video and leave it paused until after the license is complete?

**Comment by TheJohnBowers** [comment]
Having autoplay disabled does not appear to affect the behavior at all.  Sometimes you will end up with a paused video and a media error.  Sometimes you will end up with a paused video that you can start.  It still seems to have to do with how long it takes to get the license.  

I cannot see a correlation to what segments have or haven't downloaded by the time the license is acquired.  Additionally I would say the same problem occurs with the VDMS assets which don't actually have ANY unencrypted segments/portions.  I didn't actually check the Axinom asset to see that it had an unencrypted segment, but since you are asking the question I assume you believe that it does.  If it is different than my fully encrypted assets that difference doesn't affect behavior.

**Comment by joeyparrish** [comment]
Whether or not there are unencrypted segments, I'm speculating about whether this is a race between one part of the media stack in Edge and another.

Try this, if you would:

1. Edit `lib/media/media_source_engine.js`
2. In `shaka.media.MediaSourceEngine.prototype.append_`, add a log statement like `console.log('append media segment', contentType)`.
3. In `shaka.media.MediaSourceEngine.prototype.onUpdateEnd_`, add another log statement like `console.log('update complete', contentType)`
4. Edit `lib/media/drm_engine.js`
5. In `shaka.media.DrmEngine.prototype.sendLicenseRequest_`, right before `session.update`, add a log statement like `console.log('license response received')`
6. On the next line, where we create the `'drmsessionupdate'` event, add another log statement like `console.log('license response processed')`

This should give us an idea of the timing of these things.  I suspect, based on what you've told us, that we will see success if the license is processed before we append media, and that we will see failure if the media is appended first.  If this is the case, then we have a bug in Edge and we can report it to Microsoft.

**Comment by TheJohnBowers** [comment]
It seems to me that the license acquisition definitely happens after appending media in both instances.  

It should be reasonably easy for you to reproduce unless your connection is so lightning fast that you never see acquisition take more than 200 ms.  

If you need to test playback in a virtual environment, I have discovered that you can add a playenabler to the MS test license server that allows VMs to playback when normally they would not be allowed.  I am not sure if Axinom's license server supports it, but if it does, perhaps modifying the license server acquisition url on the axinom assets to something like this:

'com.microsoft.playready': '//drm-playready-licensing.axtest.net/AcquireLicense?PlayRight=1&UseSimpleNonPersistentLicense=1&PlayEnablers=B621D91F-EDCC-4035-8D4B-DC71760D43E9'

would allow for testing in a VM.

![successful playback](https://user-images.githubusercontent.com/26491119/31961614-6c48687e-b8b8-11e7-90d9-13de2e4c3282.png)
![failedattempt](https://user-images.githubusercontent.com/26491119/31961622-70abc8d4-b8b8-11e7-875e-3d3ca0e011c4.png)

**Comment by TheJohnBowers** [comment]
Never mind on the play enabler thing.  That argument works on the MS test playready license server, but I was trying to get it to work with the Axinom assets and it doesn't make a difference.  So their license server must not accept it.   I can still see the MEDIA.VIDEO_ERROR(5,8004b896) sometimes, but I also see a MEDIA.VIDEO_ERROR(3,c0262500) which I don't see with actual hardware. 

I cannot get their assets to play back in a VM.  So I guess it is important to say that I am doing my testing on actual hardware running windows 10.

**Comment by joeyparrish** [comment]
So to clarify, you see this issue:

1. on real hardware running Windows 10, not just on a VM
2. with the Axinom test assets in our demo, not just with your own content

Is that correct?

**Comment by TheJohnBowers** [comment]
Yes, I see it on real hardware with the Axinom assets.  Since the demo has the Axinom assets already, I expect anyone to be able to reproduce the issue I am describing here by using the existing code on an actual hardware. 

I see additional failures trying to playback the Axinom assets on a virtual machine.  I expect this is because the license returned is not allowing playback on virtualized hardware.

**Comment by joeyparrish** [comment]
Got it.  Thanks for the info.  We will look into this.

We recently updated our lab to Edge 16, so if we have difficulty reproducing, we may have to assume that this is something Microsoft already fixed.

**Comment by sandersaares** [comment]
Oh, I did not realize the PlayReady license configuration was missing from the original test vectors. Sorry about that! I will make a note to replace the tokens in the Axinom test vector repository with proper ones that include the license configuration.

Meanwhile, here is a temporary license token for Axinom DRM that should authorize all the v7 test vector keys and include the necessary PlayReady license policies to allow playback on a VM for your testing purposes.

`eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZXNzYWdlIjp7InBsYXlyZWFkeSI6eyJtaW5fYXBwX3NlY3VyaXR5X2xldmVsIjoxNTAsInBsYXlfZW5hYmxlcnMiOlsiNzg2NjI3RDgtQzJBNi00NEJFLThGODgtMDhBRTI1NUIwMUE3Il19LCJrZXlzIjpbeyJlbmNyeXB0ZWRfa2V5IjoibEszT2pITFlXMjRjcjJrdFI3NGZudz09IiwiaWQiOiI5ZWI0MDUwZC1lNDRiLTQ4MDItOTMyZS0yN2Q3NTA4M2UyNjYifSx7ImVuY3J5cHRlZF9rZXkiOiJsaU5KcVZhWWtOaCtNS2N4SkZrN0lnPT0iLCJpZCI6IjgwMzk5YmY1LThhMjEtNDAxNC04MDUzLWUyN2U3NDhlOThjMCJ9LHsiZW5jcnlwdGVkX2tleSI6ImtZdEhIdnJyZkNNZVZkSjZMa2Jrbmc9PSIsImlkIjoiOTA5NTNlMDktNmNiMi00OWEzLWEyNjAtN2E1ZmVmZWFkNDk5In0seyJlbmNyeXB0ZWRfa2V5IjoiN3c3TlpISExNZ0o0bVFLRUs1TFRNUT09IiwiaWQiOiIwZTRkYTkyYi1kMGU4LTRhNjYtOGMzZi1jMjVhOTdlYjY1MzIifSx7ImVuY3J5cHRlZF9rZXkiOiJBYzRVVW1ZdEJKNW5QUTlOMTVyYzNnPT0iLCJpZCI6IjU4NWYyMzNmLTMwNzItNDZmMS05ZmE0LTZkYzIyYzY2YTAxNCJ9LHsiZW5jcnlwdGVkX2tleSI6Ik82Rk8wZnFTV29wcDdiamMvRDRsTUE9PSIsImlkIjoiNDIyMmJkNzgtYmM0NS00MWJmLWI2M2UtNmY4MTRkYzM5MWRmIn0seyJlbmNyeXB0ZWRfa2V5IjoiUHc2K2VFWU5jdmpZYmZzaDNYM2ZtZz09IiwiaWQiOiIwODcyNzg2ZS1mOWU3LTQ2NWYtYTNhMi00ZTViMGVmOGZhNDUifSx7ImVuY3J5cHRlZF9rZXkiOiIvMStmTmloMzhtcVJ2NHljWXpudC93PT0iLCJpZCI6ImMxNGYwNzA5LWYyYjktNDQyNy05MTZiLTYxYjUyNTg2NTA2YSJ9LHsiZW5jcnlwdGVkX2tleSI6ImtxMEp1WkVqcEZOOHNhVG10NTYwT2c9PSIsImlkIjoiOGIwMjllNTEtZDU2YS00NGJkLTkxMGYtZDRiNWZkOTBmYmEyIn0seyJlbmNyeXB0ZWRfa2V5IjoiVGNSUWVCV3hFb0hPS0hyYWQ0U2VWUT09IiwiaWQiOiIyZDZlOTM4Ny02MGNhLTQxNDUtYWVjMi1jNDA4MzdiNGIwMjYifSx7ImVuY3J5cHRlZF9rZXkiOiJwb2VuY1M3R2dtZUdGZW9KNlBFQVRRPT0iLCJpZCI6ImRlMDJmMDdmLWEwOTgtNGVlMC1iNTU2LTkwN2MwZDE3ZmJiYyJ9LHsiZW5jcnlwdGVkX2tleSI6ImVpSS9Nc2xsclE0d0NsUlQvTE5tQ0E9PSIsImlkIjoiOTE0ZTY5ZjQtMGFiMy00NTM0LTllOWYtOTg1MzYxNWUyNmY2In0seyJlbmNyeXB0ZWRfa2V5IjoiMncremR2cXJwRFYzeFIwYkp5NHVndz09IiwiaWQiOiJkYTQ0NDVjMi1kYjVlLTQ4ZWYtYjA5Ni0zZWYzNDdiMTZjN2YifSx7ImVuY3J5cHRlZF9rZXkiOiIveGxTSHB4d3F1M2dvL2dscG1TZ2FRPT0iLCJpZCI6IjI5ZjA1ZThmLWExYWUtNDZlNC04MGU5LTIyZGNkNDRjZDdhMSJ9LHsiZW5jcnlwdGVkX2tleSI6Inp1Nml1ek4ycHNpMFpTeFFpQVRrUlE9PSIsImlkIjoiNjlmZTcwNzctZGFkZC00YjU1LTk2Y2QtYzNlZGIzOTkxODUzIn1dLCJ0eXBlIjoiZW50aXRsZW1lbnRfbWVzc2FnZSJ9LCJjb21fa2V5X2lkIjoiYjMzNjRlYjUtNTFmNi00YWUzLThjOTgtMzNjZWQ1ZTMxYzc4IiwidmVyc2lvbiI6MX0.IEKKWIHFROEWaOvmFu16NIZoOq6pEf42s-_Y9bwTqoQ`

I also confirm that I can reproduce this issue on  `Microsoft Edge 40.15063.674.0; Microsoft EdgeHTML 15.15063`.

**Comment by joeyparrish** [comment]
Sorry for the delay.  We have been busy on some HLS issues lately.  We will be looking into this issue over the next few days.

**Comment by TheJohnBowers** [comment]
Thanks!

**Comment by joeyparrish** [comment]
Instead of MS error code 8004b896, I get error code 80070241.  I also get a failure no matter the timing.

**Comment by joeyparrish** [comment]
I can't reproduce exactly your results.  I am unable to play any Axinom PlayReady content regardless of license timing, but I can play a PlayReady stream from Unified Streaming every time.

@TheJohnBowers, can you play this?
https://nightly-dot-shaka-player-demo.appspot.com/demo/#asset=//demo.unified-streaming.com/video/tears-of-steel/tears-of-steel-dash-playready.ism/.mpd;lang=en-US

**Comment by TheJohnBowers** [comment]
@joeyparrish -- Yes, I can play the Axinom content.  It behaves the same way with your nightly as it does with any of the other versions I have checked.  I suspect there is some reason a license won't be issued in your environment (VM, it doesn't like your cable, something like that possibly?)  Although I couldn't tell you what that specific error code means.

I made a very simple test asset that can demonstrate the issue and possibly bypass license restrictions.  I am going to use the MS test license server (test.playready.microsoft.com) and pass the keys via URL parameters as well as adding a playenabler that should allow for playback on a VM.   Additionally I will set the security level down to 150, which is, I think, the lest restrictive level.  Hopefully this should play just about anywhere, AND it still duplicates the issue.  If the license takes more than 200ms to come back, you will see the playback error described.   I just tested it on a VM (as the Axinom tests wouldn't play on a VM) and was able to reproduce the issue, although it is hard to get the license request to take more than 200ms.  You might need to do some network latency injection to get it to happen on a reliable basis.

  {
    name: 'PR - Two Simple keys (one audio one video) test.playready.microsoft.com as license server', //gjslint: disable=110
    manifestUri: 'https://content.uplynk.com/dea42163a7b3496980412632266237ab.mpd?rays=g', // gjslint: disable=110
    encoder: shakaAssets.Encoder.UPLYNK,
    source: shakaAssets.Source.UPLYNK,
    drm: [
      shakaAssets.KeySystem.PLAYREADY
    ],
    features: [
      shakaAssets.Feature.MP4,
      shakaAssets.Feature.PSSH,
      shakaAssets.Feature.HIGH_DEFINITION
    ],
    licenseServers: {
      'com.microsoft.playready': 'https://test.playready.microsoft.com/service/rightsmanager.asmx?cfg=(kid:nGI+4kw9N0W/aB8Q99Px8Q==,sl:150,contentkey:EREREREREREREREREREREQ==,playenablers:(786627D8-C2A6-44BE-8F88-08AE255B01A7)),(kid:o6CBo3JY+kiwce+S5s2Zsw==,sl:150,contentkey:MzMzMzMzMzMzMzMzMzMzMw==,playenablers:(786627D8-C2A6-44BE-8F88-08AE255B01A7))' // gjslint: disable=110
    }
  },

**Comment by sandersaares** [comment]
Just to confirm, I also get 80070241 on Edge 41 (Windows 10 v1709) with Axinom content. Will ask the Axinom DRM team to check it out and report back on the findings.

> Axinom tests wouldn't play on a VM

If you replace the token in the playlist with the one I pasted above in a previous comment it should work.

I was able to easily reproduce this issue using Fiddler as a proxy - it has a "Simulate Modem Speeds" setting that nicely drags network performance down to a level where a suitable delay occurred every time.

**Comment by TheJohnBowers** [comment]
I am still using:
Windows 10 Pro - Version 1703 - OS Build 15063.674
MS Edge 40.15063.674.0 edgeHTML 15.15063

This is unchanged from my previous tests -- Windows update doesn't seem to be giving me anything newer (like the v1709 mentioned in the previous comment).

**Comment by joeyparrish** [comment]
Someone from Microsoft has just informed me that the error code I'm getting (80070241) seems to refer to a DLL or driver signing error.  Not sure how we could run into that.

**Comment by sandersaares** [comment]
I heard back from Axinom DRM team: on Windows 10 1709, neither the 80070241 nor the 8004b896 reproduces for them. I guess the 80070241 we get remains a mystery for now.

**Comment by joeyparrish** [comment]
Someone from Microsoft recommended checking code integrity logs for 80070241, and we found this:

> Code Integrity is unable to verify the image integrity of the file (path involving Microsoft.HEVCVideoExtension) because the set of per-page image hashes could not be found on the system.

The command we ran was:

```sh
wevtutil qe Microsoft-Windows-CodeIntegrity/Operational  /f:Text
```

Waiting on further guidance from MS.

**Comment by joeyparrish** [comment]
Using the content from @TheJohnBowers in [an earlier comment](https://github.com/google/shaka-player/issues/1077#issuecomment-342283759), I am able to get around the apparent code integrity error 80070241.  However, I am still unable to reproduce the issue with failures related to license delay.

The server is returning a license in less than 100ms every time.  To artificially delay the request, I'm using a network request filter:

```js
networkingEngine.registerRequestFilter(function(type, request) {
  if (type != shaka.net.NetworkingEngine.RequestType.LICENSE) return;
  var p = new shaka.util.PublicPromise();
  setTimeout(function() {
    console.log('RESOLVING');
    p.resolve();
  }, 3000);
  console.log('WAITING', p);
  return p;
});
```

It makes no difference if I delay 300ms or 3s.  Either I am unable to reproduce the original issue at all, or this type of artificial delay is ineffective at triggering the issue.

**Comment by joeyparrish** [comment]
I am also unable to reproduce using a response filter for delay.

Is there a way to simulate slow networks on Edge?  I know there is such a thing in Chrome's dev tools, but I couldn't find an equivalent in Edge.

**Comment by joeyparrish** [comment]
Note: the filters I am inserting are being put right after `networkingEnging.clearAllResponseFilters()` in demo/common/demo_utils.js, to make sure they catch the first license requests.

**Comment by joeyparrish** [comment]
Using the content from @TheJohnBowers and a very slow WiFi network, license requests are taking consistently more than 750ms, and I am unable to reproduce any failure.  (Even though the 5Mbit/s HD-only content takes about 2-3 minutes to buffer and start playback on this 250kbit/s network.)

So, ignoring the strange integrity check errors from the Axinom content (which may be unrelated) and using the content that fails for @TheJohnBowers, I am unable to reproduce in Edge 16.  For now, please try again in an updated version of Edge, as this delay-related issue may have been fixed already.

**Comment by TheJohnBowers** [comment]
@joeyparrish it looks like edge must have fixed something indeed.  I cannot duplicate with edge16 either.  Sorry to waste your time on this.  Windows 10 apparently has the "Fall creators update" which includes edge 16 and came out on 10/17/2017.  I had to manually find and run the update to get it though. I am not sure when that will come through windows update.

 Now that I have this worked out I am probably going to put together a pull request for you with VDMS MultiDRM content for the demo app if you are open to that.

**Comment by joeyparrish** [comment]
@TheJohnBowers, it certainly wasn't wasted time.  I learned a lot about certain Windows errors and had a good conversation with a very kind and helpful person at Microsoft.

More demo content sounds good.  Thanks!
