### ISSUE TITLE
Add HLS TS streams and mux.js to the appspot demo

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#1078]
Mux.js is not being deployed to appspot with our demo, so this, for example, isn't working yet:

https://nightly-dot-shaka-player-demo.appspot.com/demo/#asset=https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8;lang=en-US

We also need to add TS resources to our demo list.  We should publish some of our own with Shaka Packager, as well as third-party assets, such as those published by Apple and Bitmovin.

https://developer.apple.com/streaming/examples/

https://bitmovin.com/mpeg-dash-hls-examples-sample-streams/

**Comment by joeyparrish** [comment]
Update: the content from Apple linked above does not allow cross-origin access, so we can't add that to our demo.

**Comment by joeyparrish** [comment]
TS assets have been added to the demo, the service worker will cache mux.js, and the next nightly build will include mux.js.

**Comment by osmestad** [comment]
This does not seem to be working currently?
Testing https://shaka-player-demo.appspot.com/demo/ with Chrome 63 (macOS 10.13.2) the Bitmovin Art of Motion (HLS, TS) and Sintel (HLS, TS, 4k) are not selectable.

**Comment by joeyparrish** [comment]
@osmestad, yes, this is a bug in the demo, #1214.
