### ISSUE TITLE
Increase Java memory for the closure compiler

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#108]
We should increase the memory the JVM gets when running the compiler.  See [this discussion](https://groups.google.com/d/msgid/shaka-player-users/6cf71068-09ab-4841-9cf3-eb963a8e344e%40googlegroups.com) for more info.

**Comment by joeyparrish** [comment]
@sarge:  I've done some experimenting with this, and it seems that a compile for me on a 64-bit Ubuntu machine takes around 420MB of RAM.  My system's default for max heap size is quite large, around 8GB.

I tried to find the limit by lowering the maximum from 500MB down to 100MB, but it seems that for me, Closure is able to adjust and fit inside of 100MB of RAM if I tell Java that this is my maximum heap size.

I've had successful builds as low as 35MB, but at 30MB it fails for me.

What are your system's defaults?  Please reply with the output of:
```java -XX:+PrintFlagsFinal -version | grep HeapSize```

I could just set it to 512MB for everyone, but I'm starting to think that would just be a band-aid on a problem I don't really understand yet.

**Comment by sarge** [comment]
Sure here are my settings, as I read them they should be high enough based on your tests.

Let me know if you want me to run any other tests

```
java -XX:+PrintFlagsFinal -version | grep HeapSize
    uintx ErgoHeapSizeLimit                         = 0               {product}
    uintx HeapSizePerGCThread                       = 87241520        {product}
    uintx InitialHeapSize                          := 11533440        {product}
    uintx LargePageHeapSizeThreshold                = 134217728       {product}
    uintx MaxHeapSize                              := 184549376       {product}
java version "1.7.0_21"
Java(TM) SE Runtime Environment (build 1.7.0_21-b12)
Java HotSpot(TM) 64-Bit Server VM (build 23.21-b01, mixed mode)
```

**Comment by joeyparrish** [comment]
@sarge, is this still an issue for you?  I have still not been able to reproduce.

**Comment by sarge** [comment]
Have just run 6 builds in a row. Happy for you to close

**Comment by joeyparrish** [comment]
Thanks, @sarge
