### ISSUE TITLE
Problems with DASH streaming from Flussonic (manifest generation)

### ISSUE THREAD

**Issue by TomHetmer** [google/shaka-player#1082]
Hi, this is a follow up to my email conversation with Joey. There's probably no bugs in Shaka, it's just an issue with incorrect manifests from Flussonic.

**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**:
Yes.

**What version of Shaka Player are you using**:
v2.0.0 (for now) and the demo (v2.2.4).

**Can you reproduce the issue with our latest release version**:
Yes.

**Can you reproduce the issue with the latest code from `master`**:
Yes.

**Are you using the demo app or your own custom app**:
Tested on both.

**If custom app, can you reproduce the issue using our demo app**:
Yes.

**What browser and OS are you using**:
Chrome 62.0.3202.62 on Windows 10. Issue doesn't depend on the browser/OS.

**What are the manifest and license server URIs**:
*(you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*
I can't publish the real URLs for this setup,, but the issue can be replicated with something like

```
stream 102 {
  url m4f://localhost/EL1-102; # any source will do
  title "Live stream";
  segment_count 10; # common HLS setting = 10 segments
  gop_duration 1; # we require 1sec segments due to the DVR export feature in flussonic
  dvr /opt/flussonic/dvr 3h;
}
```
Here's [an example manifest](https://pastebin.com/ZK7JCXfB).

**What did you do?**
Playing the streams using both a custom player based on Shaka and the demo player.

**What did you expect to happen?**
Stream plays OK.

**What actually happened?**
We're seeing issues with random stops, buffering/freezing and error messages such as "cannot find segment".
Per the FAQ ("Q: My live stream is buffering forever or doesn't play.") we implemented clockSyncUri as a workaround using Akamai's time server before we can get UTCTiming included in the manifest.
But the issues still exist.

**Comment by TomHetmer** [comment]
Email response (Thanks!)

> 
> 
> The issue seems to be that the suggestedPresentationDelay attribute is too small. In this example, it's set to 1s.
> 
> The timeShiftBufferDepth attribute defines how much data is available from the server. In this case, it's 45s.
> 
> The "live edge" of the stream is defined by the difference between now and the availabilityStartTime attribute. (This is why clock sync matters.)
> 
> There is also an explicit description of segments in SegmentTimeline in this manifest. So we only know about the ones we have seen in this timeline.
> 
> Finally, the minimumUpdatePeriod attribute is set to 5s.
> 
> 
> Let's dig into how this works. The player fetches a manifest, which in this case contains descriptions of around 10 segments, at about 1s each. So we know about 10s worth of content, and that's the most we can fetch. Based on minimumUpdatePeriod, we update a new manifest 5s later, which contains about 5 new segments we didn't know about. When you compare this to the calculated live edge, you'll see that we can't stay within 5s of that live edge. The buffering indicator will jump forward to the right edge, then fall back toward around -5s, then jump forward again, over and over.
> 
> The purpose of suggestedPresentationDelay is to introduce a difference between the "ideal" live edge and what we present to the user as the live edge. It covers up this window in which the buffering indicator jumps back and forth. With a delay of 5-10s, you should see this effect disappear. The player will be able to buffer ahead up to the "ideal" live edge, so with a suggestedPresentationDelay of 10s, the player can get up to 10s ahead of what it shows to the user.
> 
> Coming back to timeShiftBufferDepth, you will find that suggestedPresentationDelay eats into this, because both represent content that is available on the server. So if you want a 10s delay and you want the user to be able to rewind or pause up to 45s, you should set timeShiftBufferDepth to 55s.
> 
>

**Comment by joeyparrish** [comment]
Thanks for migrating this into public, where it might help others dealing with similar issues.  I'm going to leave this open for the moment until we hear back from Flussonic.

**Comment by TomHetmer** [comment]
Seems to be fixed in flussonic_4.7.0-20-g8699909 :-)

**Comment by joeyparrish** [comment]
Great, thanks for the update!
