### ISSUE TITLE
Unable to destroy() the player if the user is offline.

### ISSUE THREAD

**Issue by londonshliach** [google/shaka-player#1084]
If the user loses their internet connection, but the player is still retrying (as maxAttempts has not yet been reached,) then the destroy() function will not work.
The player will only be destroyed after all the retry attempts have failed.

I can reprodue this problem on the Shaka player demo page by doing the following:

1) Visit the demo page: 
https://shaka-player-demo.appspot.com/demo/#asset=//storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd;lang=en-US

2) Developer tools -> Network tab -> Offline.

3) Enter the following commands (one at a time) in the console:

var player = new shaka.Player(document.getElementById('video'))

player.configure({
    'manifest': {
        'retryParameters': {
            'timeout': 0,
            'maxAttempts': 10,
            'baseDelay': 5000,
            'backoffFactor': 1,
            'fuzzFactor': 0.5,
        }                        
    }
});

player.load('https://www.test.com/test.mpd')

var destroyPromise = player.destroy();

4) Check the destroyPromise and you will see that it remains "Pending" for 50 seconds (while the player is trying to load the manifest).

**Comment by londonshliach** [comment]
The same issue occurs when I try to unload().

So there is no way for me to detect when the user loses connectivity and switch to a video which has already been downloaded, as I cannot unload() or destroy() the player.

**Comment by theodab** [comment]
Reproduced. It looks like NetworkingEngine might need some refactoring. Thanks for the report.

**Comment by joeyparrish** [comment]
Fixes to date cherry-picked for v2.2.6.

**Comment by joeyparrish** [comment]
We have significantly improved cancellation time, and destroy should no longer block forever.  There are more optimizations coming with cancelable requests as part of #829.

Please let us know if you have any questions.  Thanks!

**Comment by londonshliach** [comment]
Thanks.
