### ISSUE TITLE
Support muxed video+audio with URI-less EXT-X-MEDIA tag

### ISSUE THREAD

**Issue by hung-yueh** [google/shaka-player#1086]
Based on the [HLS spec](https://tools.ietf.org/html/rfc8216#section-4.3.4.2.1)
> The URI attribute of the EXT-X-MEDIA tag is REQUIRED if the media
   type is SUBTITLES, but OPTIONAL if the media type is VIDEO or AUDIO.
   If the media type is VIDEO or AUDIO, a missing URI attribute
   indicates that the media data for this Rendition is included in the
   Media Playlist of any EXT-X-STREAM-INF tag referencing this EXT-
   X-MEDIA tag.  If the media TYPE is AUDIO and the URI attribute is
   missing, clients MUST assume that the audio data for this Rendition
   is present in every video Rendition specified by the EXT-X-STREAM-INF
   tag.

There is a missing logic in Shaka-player HLS parser which is the URI attribute should be optional if the media type is VIDEO or AUDIO. Current Shaka-player(version:2.2.4) sees them are all REQUIRED. 

Please let me know if the above statements are true. If it's true, is there any plan to add this missing logic to the HLS parser? I might be able to help for creating PR for this. Thanks!

**Comment by joeyparrish** [comment]
We were not aware of this issue, and we must have overlooked this in the spec.  I've tentatively scheduled for v2.4.

To help us plan the work and understand the issue better, can you please provide sample content which is currently failing due to this issue?  If you can't post a URL publicly, please email to <shaka-player-issues@google.com> instead.

Thanks!

**Comment by hung-yueh** [comment]
Hi @joeyparrish ,

Thanks for responding the issue so quickly, I have sent the testing stream via email. Please let me know if there is anything I can help.

**Comment by joeyparrish** [comment]
Ah, I see now.  So without the URI attribute in the EXT-X-MEDIA audio tag, the audio is muxed in with the video.  Is that correct?

**Comment by hung-yueh** [comment]
@joeyparrish Yes, you are totally correct!

**Comment by sagb** [comment]
We have the same problem. Flussonic (major video streaming software) generates playlists with audio tracks URI, except of the default:
```
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aac",NAME="a1",DEFAULT=YES,AUTOSELECT=YES
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aac",NAME="a2",DEFAULT=NO,AUTOSELECT=YES,URI=....
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aac",NAME="a3",DEFAULT=NO,AUTOSELECT=YES,URI=....
```
It would be nice if shaka could handle this.

**Comment by joeyparrish** [comment]
The commit message in adde0bd38daca175df1c7feed8d46d5cde83aef0 is malformed, but this issue was fixed by that commit.
