### ISSUE TITLE
PNG in TTML 

### ISSUE THREAD

**Issue by aptly-io** [google/shaka-player#1089]
I'm faced with TTML PNG subtitles in media containers (for a Japanese market; that seems void of unicode T_T). dashif.org handles this case by fetching the media samples and splitting it into sub-samples (based on 'subs' boxes in the MP4 container). The TTML xml doc in the first sub-sample is processed by the imsc library, the other subsamples, that hold the PNG image binary blobs, are kept separately.
Would a PR that implements this be accepted? Would such implementation then eventually end up in the shaka used by the CAF receiver?

PS The PNG TTML I refer to is described in DECE's CFF v2.1 (see chapter 6.5, image track)

**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**: Yes
**What version of Shaka Player are you using**: 2.2.4
**Can you reproduce the issue with our latest release version**: Yes
**Can you reproduce the issue with the latest code from `master`**: Yes
**Are you using the demo app or your own custom app**: demo/cast_receiver
**If custom app, can you reproduce the issue using our demo app**: Yes
**What browser and OS are you using**: chromecast
**What are the manifest and license server URIs**: in-house
**What did you do?** load crippled DASH manifest
**What did you expect to happen?**
Extracting segment info from the media container's sidx boxes.

**What actually happened?**
shaka cracks its teeth upon swallowing non-unicode characters (that are actually the binary PNG's)

**Comment by joeyparrish** [comment]
We don't support PNG at this time, and this would require a redesign of our `Cue` interface.  See https://github.com/google/shaka-player/issues/1080#issuecomment-339741268 and the other comments in #1080 for deeper discussion on redesign.

For now, I will put this in the backlog along with the other TTML enhancement issue.  If you would like to propose change to `Cue`, please do.  I would strongly prefer to agree on a design for `Cue` before work is started on a PR, but a PR is still welcome if you want to contribute.

**Comment by palemieux** [comment]
As discussed in #1080, perhaps it is simplest to simply create a text parser and cue renderer plugin outside of this project, using imscJS potentially.

**Comment by TheModMaker** [comment]
We support PNG in TTML subtitles.  If you are seeing an error, please open a new issues with the bug template with a link to your content so we can see what is wrong.
