### ISSUE TITLE
[Announcement] Features and Support Survey

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#1096]
We would like to announce our first survey!  Please help us decide what features and platforms to prioritize in Shaka Player.   This survey will be open until December 1, 2017.  Take the survey here:

https://docs.google.com/forms/d/e/1FAIpQLSfCAjWTmMtXeS4CL3n2v-oVzL5yaXJdEttc5RhZFAq2j02yfw/viewform?usp=sf_link

**Comment by chrisfillmore** [comment]
Will you share the results of the survey once it's done?

**Comment by joeyparrish** [comment]
We could share the aggregate results from the multiple choice questions, but I wouldn't want to share email addresses, company names, or any of the comments left in the open comment sections.  We never explicitly asked in the survey if that information could be shared, and we want people to feel free to speak their minds when giving us direct feedback.

**Comment by joeyparrish** [comment]
Just a quick reminder (to anyone subscribed to github activity) that we are seeking your feedback.  Please take our survey and help us decide what features and platforms to prioritize in Shaka Player:
https://docs.google.com/forms/d/e/1FAIpQLSfCAjWTmMtXeS4CL3n2v-oVzL5yaXJdEttc5RhZFAq2j02yfw/viewform?usp=sf_link

The survey will be open until December 1, 2017.

Thanks!

**Comment by joeyparrish** [comment]
The survey is now closed.  I'll post aggregate results here some time next week.

**Comment by joeyparrish** [comment]
Here are the results of the survey:  [Shaka Player 2017 Q4 Survey Report.pdf](https://github.com/google/shaka-player/files/1532459/Shaka.Player.2017.Q4.Survey.Report.public.pdf)

Please let us know if you have any questions.  Thanks!

**Comment by sandersaares** [comment]
Nice report - good reading! However, I find the pie chart colors very confusing due to no association with the "weight" of the values and thus the pie charts are very difficult to parse.

**Comment by joeyparrish** [comment]
Hi Sanders,

Thanks for the feedback.  I'm not sure what you mean about colors and weights.

Feature responses are assigned the same colors across charts.  So, for example, "very important" is blue in all pie charts, "important" is red, "nice to have" is orange, "not important" is green.  (I did not put any thought into the color assignments.  These are the default colors in Google Sheets, and I simply made sure the answers were in the same order across charts.)

How would you expect the colors to be chosen for the pie charts?

**Comment by sandersaares** [comment]
I would expect the colors to be on some scale, like "blue...red" for less/more important ends of the scale. Right now they are just arbitrary colors, so there is no mental mapping from "there is much green here" to "a lot of people consider it important" (or was it blue for very important? I forget already - illustrating the problem)
