### ISSUE TITLE
presentationTimeOffset in SegmentBase is interpreted in seconds instead of time units

### ISSUE THREAD

**Issue by kqyang** [google/shaka-player#1099]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**: YES

**What version of Shaka Player are you using**: Latest

**Can you reproduce the issue with our latest release version**: YES

**Can you reproduce the issue with the latest code from `master`**: YES

**Are you using the demo app or your own custom app**: Demo

**What browser and OS are you using**: Chrome on Linux

**What are the manifest and license server URIs**:

https://storage.googleapis.com/wvtemp/shaka/bourne/bourne_audio_pto_20.mpd
https://storage.googleapis.com/wvtemp/shaka/bourne/bourne_audio_pto_4410.mpd

**What did you do?**

Play the above manifests in Shaka demo player.

**What did you expect to happen?**

https://storage.googleapis.com/wvtemp/shaka/bourne/bourne_audio_pto_20.mpd
The audio should start playing from 20/44100 in media timeline. However, it starts from 20 seconds instead.

https://storage.googleapis.com/wvtemp/shaka/bourne/bourne_audio_pto_4410.mpd
The audio should start playing from 4410/44100 = 0.1 seconds in media timeline. However, the player returns "segment_index.js:240 The last segment should not end before the end of the Period." instead.

**Here is the relevant clause of presentationTimeOffset in the spec:**

> ISO/IEC 23009-1:2014 5.3.9.2 Segment base information
>
> @presentationTimeOffset specifies the presentation time offset of the Representation relative to the start of the Period, i.e. the presentation time value of the media stream that shall be presented at the start of this Period.
> 
> The value of the presentation time offset in seconds is the division of the value of this attribute and the value of the @timescale attribute.

**Comment by kqyang** [comment]
Just realized that a similar issue has just been filed: #1098

**Comment by joeyparrish** [comment]
A brief review of DASH parser from v1 makes me think we didn't have this bug in v1.

In v2 (all versions), we seem to parse SegmentTemplate and SegmentTimeline correctly and divide by timescale, but not SegmentBase.  So the damage is limited to SegmentBase's presentationTimeOffset, but the bug seems to be present in every single v2 release, all the way back to v2.0.0-beta.

**Comment by joeyparrish** [comment]
The fix has been cherry-picked for v2.2.5 and v2.1.9.
