### ISSUE TITLE
WebM-Dash video corruption with Chrome + VP9 Hardware Decoding

### ISSUE THREAD

**Issue by TomMettam** [google/shaka-player#1103]
Greetings Shaka team!

I've been chasing an issue with video corruption with WebM-Dash streams when played on Chrome/Chromium with VP9 Hardware acceleration (Windows 10 Creators Update or newer).

The corruption occurs on ABR changes. I initially observed the issue with Dash.js, and after corroborating with the video guys on the Chromium bug tracker they pointed out that Shaka plays the examples that I had provided perfectly, which points to a possible dash implementation issue with Dash.js.

However, I've found ONE example where Shaka exhibits the same issue:

https://shaka-player-demo.appspot.com/demo/#asset=https://login.plasticpictures.tv/stream/14e350d17948c99e73d00cda7443c0b57744a67f/manifest.mpd;lang=en-US

Screenshot: https://gyazo.com/bd9982e211b1d97ee132443ab6ff9247

I'm posting this issue with the hope that someone might know why this is happening. It seems you guys have solved it for the vast majority of the examples that show corruption with dash.js, so perhaps you have some insight into this.

Here's the ticket with Dash.JS: https://github.com/Dash-Industry-Forum/dash.js/issues/1988
Here's the ticket with Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=729600

**Comment by TomMettam** [comment]
I forgot to mention: One way in which this example is different from the previous examples, is that this isn't 100% reproducible - it doesn't happen on every play.

**Comment by joeyparrish** [comment]
Based on your description and the conversation on the Chrome bug tracker, it seems that this is an issue with the VP9 hardware decoder on Windows, or with the way Chrome is interfacing with it.  So I'm going to treat this as an external issue.

I left some comments on the Chrome bug speculating on how Shaka Player and dash.js might do things differently to trigger this bug, and suggested ways we could instrument things for more consistent repro.

Thanks for engaging with Chrome team!

**Comment by joeyparrish** [comment]
The external bug is marked as fixed in Chrome 65, and I just confirmed the fix in our lab.
