### ISSUE TITLE
Failure to extract HLS text cue start time

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#1104]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**: Yes

**Can you reproduce the issue with the latest code from `master`**: Yes, HLS Live is only in master branch.

**Are you using the demo app or your own custom app**: demo app

**What browser and OS are you using**:  Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.75 Safari/537.36

**What are the manifest and license server URIs**:
https://cdn.demo.anevia.com/live/eds/Arte/HLS-MP4/Arte.m3u8

**What did you do?**
Open https://nightly-dot-shaka-player-demo.appspot.com/demo/#asset=https://cdn.demo.anevia.com/live/eds/Arte/HLS-MP4/Arte.m3u8;lang=es and click on load button.

**What did you expect to happen?**
The video starts to reproduce.

**What actually happened?**
The video never starts

Note: the same video works in AVPlayer (iOS), ExoPlayer (Android) and Safari (macOS).

In the console, I see:

> Using native EME as-is.
> mediasource.js:95 Using native MSE as-is.
> promise.js:118 Using native Promises.
> vttcue.js:36 Using native VTTCue.
> drm_engine.js:1390 It is recommended that a robustness level be specified. Not specifying the robustness level could result in unexpected behavior, potentially including failure to play.
> (anonymous) @ drm_engine.js:1390
> shaka.media.DrmEngine.probeSupport @ drm_engine.js:1389
> shaka.Player.probeSupport @ player.js:469
> shakaDemo.init @ main.js:177
> streaming_engine.js:1254 (video:41) cannot find segment: currentPeriod.startTime=0 lookupTime=47799265.319211245
> shaka.media.StreamingEngine.lookupSegmentPosition_ @ streaming_engine.js:1254
> shaka.media.StreamingEngine.getSegmentReferenceNeeded_ @ streaming_engine.js:1206
> shaka.media.StreamingEngine.update_ @ streaming_engine.js:1094
> shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:991
> setTimeout (async)
> shaka.media.StreamingEngine.scheduleUpdate_ @ streaming_engine.js:2048
> (anonymous) @ streaming_engine.js:810
> Promise resolved (async)
> shaka.media.StreamingEngine.initStreams_ @ streaming_engine.js:786
> shaka.media.StreamingEngine.init @ streaming_engine.js:385
> (anonymous) @ player.js:667
> Promise resolved (async)
> shaka.util.CancelableChain.then @ cancelable_chain.js:72
> shaka.Player.load @ player.js:642
> shakaDemo.load @ asset_section.js:242
> streaming_engine.js:1254 (video:41) cannot find segment: currentPeriod.startTime=0 lookupTime=47799266.32021117
> shaka.media.StreamingEngine.lookupSegmentPosition_ @ streaming_engine.js:1254
> shaka.media.StreamingEngine.getSegmentReferenceNeeded_ @ streaming_engine.js:1206
> shaka.media.StreamingEngine.update_ @ streaming_engine.js:1094
> shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:991
> setTimeout (async)
> shaka.media.StreamingEngine.scheduleUpdate_ @ streaming_engine.js:2048
> shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:993
> setTimeout (async)
> shaka.media.StreamingEngine.scheduleUpdate_ @ streaming_engine.js:2048
> (anonymous) @ streaming_engine.js:810
> Promise resolved (async)
> shaka.media.StreamingEngine.initStreams_ @ streaming_engine.js:786
> shaka.media.StreamingEngine.init @ streaming_engine.js:385
> (anonymous) @ player.js:667
> Promise resolved (async)
> shaka.util.CancelableChain.then @ cancelable_chain.js:72
> shaka.Player.load @ player.js:642
> shakaDemo.load @ asset_section.js:242
> streaming_engine.js:1254 (video:41) cannot find segment: currentPeriod.startTime=0 lookupTime=47799267.32221103
> shaka.media.StreamingEngine.lookupSegmentPosition_ @ streaming_engine.js:1254
> shaka.media.StreamingEngine.getSegmentReferenceNeeded_ @ streaming_engine.js:1206
> shaka.media.StreamingEngine.update_ @ streaming_engine.js:1094
> shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:991
> setTimeout (async)
> shaka.media.StreamingEngine.scheduleUpdate_ @ streaming_engine.js:2048
> shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:993
> setTimeout (async)
> shaka.media.StreamingEngine.scheduleUpdate_ @ streaming_engine.js:2048
> shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:993
> setTimeout (async)
> shaka.media.StreamingEngine.scheduleUpdate_ @ streaming_engine.js:2048
> (anonymous) @ streaming_engine.js:810
> Promise resolved (async)
> shaka.media.StreamingEngine.initStreams_ @ streaming_engine.js:786
> shaka.media.StreamingEngine.init @ streaming_engine.js:385
> (anonymous) @ player.js:667
> Promise resolved (async)
> shaka.util.CancelableChain.then @ cancelable_chain.js:72
> shaka.Player.load @ player.js:642
> shakaDemo.load @ asset_section.js:242
> streaming_engine.js:1254 (video:41) cannot find segment: currentPeriod.startTime=0 lookupTime=47799268.32421112
> shaka.media.StreamingEngine.lookupSegmentPosition_ @ streaming_engine.js:1254
> shaka.media.StreamingEngine.getSegmentReferenceNeeded_ @ streaming_engine.js:1206
> shaka.media.StreamingEngine.update_ @ streaming_engine.js:1094
> shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:991
> setTimeout (async)
> shaka.media.StreamingEngine.scheduleUpdate_ @ streaming_engine.js:2048
> shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:993
> setTimeout (async)
> shaka.media.StreamingEngine.scheduleUpdate_ @ streaming_engine.js:2048
> shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:993
> setTimeout (async)
> shaka.media.StreamingEngine.scheduleUpdate_ @ streaming_engine.js:2048
> shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:993
> setTimeout (async)
> shaka.media.StreamingEngine.scheduleUpdate_ @ streaming_engine.js:2048
> (anonymous) @ streaming_engine.js:810
> Promise resolved (async)
> shaka.media.StreamingEngine.initStreams_ @ streaming_engine.js:786
> shaka.media.StreamingEngine.init @ streaming_engine.js:385
> (anonymous) @ player.js:667
> Promise resolved (async)
> shaka.util.CancelableChain.then @ cancelable_chain.js:72
> shaka.Player.load @ player.js:642
> shakaDemo.load @ asset_section.js:242
> streaming_engine.js:1254 (video:41) cannot find segment: currentPeriod.startTime=0 lookupTime=47799269.32521105
> shaka.media.StreamingEngine.lookupSegmentPosition_ @ streaming_engine.js:1254
> shaka.media.StreamingEngine.getSegmentReferenceNeeded_ @ streaming_engine.js:1206
> shaka.media.StreamingEngine.update_ @ streaming_engine.js:1094
> shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:991
> setTimeout (async)
> shaka.media.StreamingEngine.scheduleUpdate_ @ streaming_engine.js:2048
> shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:993
> setTimeout (async)
> shaka.media.StreamingEngine.scheduleUpdate_ @ streaming_engine.js:2048
> shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:993
> setTimeout (async)
> shaka.media.StreamingEngine.scheduleUpdate_ @ streaming_engine.js:2048
> shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:993
> setTimeout (async)
> shaka.media.StreamingEngine.scheduleUpdate_ @ streaming_engine.js:2048
> shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:993
> setTimeout (async)
> shaka.media.StreamingEngine.scheduleUpdate_ @ streaming_engine.js:2048
> (anonymous) @ streaming_engine.js:810
> Promise resolved (async)
> shaka.media.StreamingEngine.initStreams_ @ streaming_engine.js:786
> shaka.media.StreamingEngine.init @ streaming_engine.js:385
> (anonymous) @ player.js:667
> Promise resolved (async)
> shaka.util.CancelableChain.then @ cancelable_chain.js:72
> shaka.Player.load @ player.js:642
> shakaDemo.load @ asset_section.js:242
> streaming_engine.js:1254 (video:41) cannot find segment: currentPeriod.startTime=0 lookupTime=47799270.32721114
> shaka.media.StreamingEngine.lookupSegmentPosition_ @ streaming_engine.js:1254
> shaka.media.StreamingEngine.getSegmentReferenceNeeded_ @ streaming_engine.js:1206
> shaka.media.StreamingEngine.update_ @ streaming_engine.js:1094
> shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:991
> setTimeout (async)
> shaka.media.StreamingEngine.scheduleUpdate_ @ streaming_engine.js:2048
> shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:993
> setTimeout (async)
> shaka.media.StreamingEngine.scheduleUpdate_ @ streaming_engine.js:2048
> shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:993
> setTimeout (async)
> shaka.media.StreamingEngine.scheduleUpdate_ @ streaming_engine.js:2048
> shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:993
> setTimeout (async)
> shaka.media.StreamingEngine.scheduleUpdate_ @ streaming_engine.js:2048
> shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:993
> setTimeout (async)
> shaka.media.StreamingEngine.scheduleUpdate_ @ streaming_engine.js:2048
> shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:993
> setTimeout (async)
> shaka.media.StreamingEngine.scheduleUpdate_ @ streaming_engine.js:2048
> (anonymous) @ streaming_engine.js:810
> Promise resolved (async)
> shaka.media.StreamingEngine.initStreams_ @ streaming_engine.js:786
> shaka.media.StreamingEngine.init @ streaming_engine.js:385
> (anonymous) @ player.js:667
> Promise resolved (async)
> shaka.util.CancelableChain.then @ cancelable_chain.js:72
> shaka.Player.load @ player.js:642
> shakaDemo.load @ asset_section.js:242
> streaming_engine.js:1254 (video:41) cannot find segment: currentPeriod.startTime=0 lookupTime=47799271.329211235
> shaka.media.StreamingEngine.lookupSegmentPosition_ @ streaming_engine.js:1254
> shaka.media.StreamingEngine.getSegmentReferenceNeeded_ @ streaming_engine.js:1206
> shaka.media.StreamingEngine.update_ @ streaming_engine.js:1094
> shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:991
> setTimeout (async)
> shaka.media.StreamingEngine.scheduleUpdate_ @ streaming_engine.js:2048
> shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:993
> setTimeout (async)
> shaka.media.StreamingEngine.scheduleUpdate_ @ streaming_engine.js:2048
> shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:993
> setTimeout (async)
> shaka.media.StreamingEngine.scheduleUpdate_ @ streaming_engine.js:2048
> shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:993
> setTimeout (async)
> shaka.media.StreamingEngine.scheduleUpdate_ @ streaming_engine.js:2048
> shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:993
> setTimeout (async)
> shaka.media.StreamingEngine.scheduleUpdate_ @ streaming_engine.js:2048
> shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:993
> setTimeout (async)
> shaka.media.StreamingEngine.scheduleUpdate_ @ streaming_engine.js:2048
> shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:993
> setTimeout (async)
> shaka.media.StreamingEngine.scheduleUpdate_ @ streaming_engine.js:2048
> (anonymous) @ streaming_engine.js:810
> Promise resolved (async)
> shaka.media.StreamingEngine.initStreams_ @ streaming_engine.js:786
> shaka.media.StreamingEngine.init @ streaming_engine.js:385
> (anonymous) @ player.js:667
> Promise resolved (async)
> shaka.util.CancelableChain.then @ cancelable_chain.js:72
> shaka.Player.load @ player.js:642
> shakaDemo.load @ asset_section.js:242
> streaming_engine.js:1254 (video:41) cannot find segment: currentPeriod.startTime=0 lookupTime=47799272.332211256
> shaka.media.StreamingEngine.lookupSegmentPosition_ @ streaming_engine.js:1254
> shaka.media.StreamingEngine.getSegmentReferenceNeeded_ @ streaming_engine.js:1206
> shaka.media.StreamingEngine.update_ @ streaming_engine.js:1094
> shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:991
> setTimeout (async)
> shaka.media.StreamingEngine.scheduleUpdate_ @ streaming_engine.js:2048
> shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:993
> setTimeout (async)
> shaka.media.StreamingEngine.scheduleUpdate_ @ streaming_engine.js:2048
> shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:993
> setTimeout (async)
> shaka.media.StreamingEngine.scheduleUpdate_ @ streaming_engine.js:2048
> shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:993
> setTimeout (async)
> shaka.media.StreamingEngine.scheduleUpdate_ @ streaming_engine.js:2048
> shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:993
> setTimeout (async)
> shaka.media.StreamingEngine.scheduleUpdate_ @ streaming_engine.js:2048
> shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:993
> setTimeout (async)
> shaka.media.StreamingEngine.scheduleUpdate_ @ streaming_engine.js:2048
> shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:993
> setTimeout (async)
> shaka.media.StreamingEngine.scheduleUpdate_ @ streaming_engine.js:2048
> shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:993
> setTimeout (async)
> shaka.media.StreamingEngine.scheduleUpdate_ @ streaming_engine.js:2048
> (anonymous) @ streaming_engine.js:810
> Promise resolved (async)
> shaka.media.StreamingEngine.initStreams_ @ streaming_engine.js:786
> shaka.media.StreamingEngine.init @ streaming_engine.js:385
> (anonymous) @ player.js:667
> Promise resolved (async)
> shaka.util.CancelableChain.then @ cancelable_chain.js:72
> shaka.Player.load @ player.js:642
> shakaDemo.load @ asset_section.js:242
> streaming_engine.js:1254 (video:41) cannot find segment: currentPeriod.startTime=0 lookupTime=47799273.33421111
> shaka.media.StreamingEngine.lookupSegmentPosition_ @ streaming_engine.js:1254
> shaka.media.StreamingEngine.getSegmentReferenceNeeded_ @ streaming_engine.js:1206
> shaka.media.StreamingEngine.update_ @ streaming_engine.js:1094
> shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:991
> setTimeout (async)
> shaka.media.StreamingEngine.scheduleUpdate_ @ streaming_engine.js:2048
> shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:993
> setTimeout (async)
> shaka.media.StreamingEngine.scheduleUpdate_ @ streaming_engine.js:2048
> shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:993
> setTimeout (async)
> shaka.media.StreamingEngine.scheduleUpdate_ @ streaming_engine.js:2048
> shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:993
> setTimeout (async)
> shaka.media.StreamingEngine.scheduleUpdate_ @ streaming_engine.js:2048
> shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:993
> setTimeout (async)
> shaka.media.StreamingEngine.scheduleUpdate_ @ streaming_engine.js:2048
> shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:993
> setTimeout (async)
> shaka.media.StreamingEngine.scheduleUpdate_ @ streaming_engine.js:2048
> shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:993
> setTimeout (async)
> shaka.media.StreamingEngine.scheduleUpdate_ @ streaming_engine.js:2048
> shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:993
> setTimeout (async)
> shaka.media.StreamingEngine.scheduleUpdate_ @ streaming_engine.js:2048
> shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:993
> setTimeout (async)
> shaka.media.StreamingEngine.scheduleUpdate_ @ streaming_engine.js:2048
> (anonymous) @ streaming_engine.js:810
> Promise resolved (async)
> shaka.media.StreamingEngine.initStreams_ @ streaming_engine.js:786
> shaka.media.StreamingEngine.init @ streaming_engine.js:385
> (anonymous) @ player.js:667
> Promise resolved (async)
> shaka.util.CancelableChain.then @ cancelable_chain.js:72
> shaka.Player.load @ player.js:642
> shakaDemo.load @ asset_section.js:242
> streaming_engine.js:1254 (video:41) cannot find segment: currentPeriod.startTime=0 lookupTime=47799274.336211205
> shaka.media.StreamingEngine.lookupSegmentPosition_ @ streaming_engine.js:1254
> shaka.media.StreamingEngine.getSegmentReferenceNeeded_ @ streaming_engine.js:1206
> shaka.media.StreamingEngine.update_ @ streaming_engine.js:1094
> shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:991
> setTimeout (async)
> shaka.media.StreamingEngine.scheduleUpdate_ @ streaming_engine.js:2048
> shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:993
> setTimeout (async)
> shaka.media.StreamingEngine.scheduleUpdate_ @ streaming_engine.js:2048
> shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:993
> setTimeout (async)
> shaka.media.StreamingEngine.scheduleUpdate_ @ streaming_engine.js:2048
> shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:993
> setTimeout (async)
> shaka.media.StreamingEngine.scheduleUpdate_ @ streaming_engine.js:2048
> shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:993
> setTimeout (async)
> shaka.media.StreamingEngine.scheduleUpdate_ @ streaming_engine.js:2048
> shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:993
> setTimeout (async)
> shaka.media.StreamingEngine.scheduleUpdate_ @ streaming_engine.js:2048
> shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:993
> setTimeout (async)
> shaka.media.StreamingEngine.scheduleUpdate_ @ streaming_engine.js:2048
> shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:993
> setTimeout (async)
> shaka.media.StreamingEngine.scheduleUpdate_ @ streaming_engine.js:2048
> shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:993
> setTimeout (async)
> shaka.media.StreamingEngine.scheduleUpdate_ @ streaming_engine.js:2048
> shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:993
> setTimeout (async)
> shaka.media.StreamingEngine.scheduleUpdate_ @ streaming_engine.js:2048
> (anonymous) @ streaming_engine.js:810
> Promise resolved (async)
> shaka.media.StreamingEngine.initStreams_ @ streaming_engine.js:786
> shaka.media.StreamingEngine.init @ streaming_engine.js:385
> (anonymous) @ player.js:667
> Promise resolved (async)
> shaka.util.CancelableChain.then @ cancelable_chain.js:72
> shaka.Player.load @ player.js:642
> shakaDemo.load @ asset_section.js:242
> hls_parser.js:1824 Updating manifest...

**Comment by joeyparrish** [comment]
I'm getting CORS errors with the link you sent.  Can you retest this content in the latest nightly build, or allow cross-origin access for us to test?

**Comment by joeyparrish** [comment]
@avelad, I'm now able to access the main playlist, but I'm getting a 404 for one of the media playlists (TTML_fra).

**Comment by avelad** [comment]
@joeyparrish I'm on vacation until Monday, I can not look at it now, I'm sorry

**Comment by joeyparrish** [comment]
@avelad, there's no rush.  We didn't mean to disturb your vacation.  Just trying to provide updates.  Please take your time getting back to us.

**Comment by avelad** [comment]
@joeyparrish , The stream is working now.

**Comment by avelad** [comment]
![hls](https://user-images.githubusercontent.com/8983024/32768589-b9193956-c918-11e7-984a-7897a12d8731.png)

**Comment by joeyparrish** [comment]
With https://cdn.demo.anevia.com/live/eds/dvb_txt/HLS-MP4/dvb_txt.m3u8 I get Shaka Error `TEXT.UNABLE_TO_EXTRACT_CUE_START_TIME`.

**Comment by joeyparrish** [comment]
This seems to be caused by the style block in your VTT files.  Our WebVTT parser is failing on that.  It should be easy to fix.

**Comment by joeyparrish** [comment]
The fix has been cherry-picked for v2.2.8.
