### ISSUE TITLE
Fetching HLS segments to parse start time takes too long

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#1106]
Fetching one segment from each playlist uses a lot of time and transfers a lot of bytes.  We should try fetching a partial segment instead.

**Comment by joeyparrish** [comment]
@avelad, please take a look at this.  We want to make partial segment requests to determine the start time of each HLS playlist, but the content you linked to in #1102 (https://cdn.demo.anevia.com/live/nas40/Arte/mirada_test/Arte.m3u8) resides on a server which doesn't permit this.  We can work around it by falling back to full segments, but the fallback is expensive.  It will cost you a lot of time and bandwidth on startup of the stream if we can't fetch partial segments.

We will issue a warning about this in the console, but I wanted to bring it to your attention explicitly, in case you want to look into changes on your servers.

The specific issue is that a cross-origin range request results in a preflight request, but your servers return HTTP 405 because they don't support preflight.  Here's a doc about preflight: https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request

**Comment by avelad** [comment]
@joeyparrish , I asked for our provider, and this feature will be implemented in a few weeks. I'm back to you when this is implemented

**Comment by joeyparrish** [comment]
Excellent, thanks!
