### ISSUE TITLE
Unexpected gap detected in presentation

### ISSUE THREAD

**Issue by sandersaares** [google/shaka-player#1109]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**: yes

**What version of Shaka Player are you using**: 2.2.5-debug

**Can you reproduce the issue with our latest release version**: unknown, used demo app

**Can you reproduce the issue with the latest code from `master`**: unknown, used demo app

**Are you using the demo app or your own custom app**: demo app

**If custom app, can you reproduce the issue using our demo app**: N/A

**What browser and OS are you using**:

Windows 10 1709
Firefox 56

**What are the manifest and license server URIs**: sent privately

**What did you do?**

Start playback and play across the period change at 3 minutes.

**What did you expect to happen?**

Period changes at 3 minutes, no special glitching or errors.

**What actually happened?**

`Jumping forward 0.13492199999998888 seconds because of gap starting at 177.886045 and ending at 178.000001`

This was unexpected because all the segments are filled with 4 seconds of content as far as I can tell (except for the first video segment which has 2 seconds because of some keyframe rounding). There might be tiny jitter due to timing rounding but 0.134 seconds sounds too big for a sample-level glitch and too small for a segment-level glitch.

The media segments actually keep going after the period ends (I made an artificially short period in the MPD) so there is unlikely to be any production-side funny business at the end there. When I change the end point of the period (just by adjusting the duration), the phantom gap is still reported but in different places, further indicating it is not related to the actual contents of the media segments.

There is also some apparent de-sync at the moment of period change (I heard audio of period 2 before seeing video of period 2). Not sure what to make of that.

I notice that the 2nd period content starts playing already before the 1st period is over (1st period ends at 03:00 but I can already see 2nd period content at 02:58).

I am unable to test with Chrome 62/64 because of https://github.com/google/shaka-player/issues/1108
I am unable to test with Edge because playback seems to freeze at the start of the 2nd period: https://github.com/google/shaka-player/issues/1110

Shaka also reports at gap at the very start (rounding stuff?) but this does not appear to really affect anything, so I think is best left out of scope of this issue for now: `Jumping forward 0.000001 seconds because of gap before start time of 0.000001`

**Comment by sandersaares** [comment]
I made a second version of this video with slightly different segment/period timing and got a "Large gap detected" this time, breaking playback at the period change. I assume this is simply some timing differences making Shaka decide differently on the largeness/smallness of the gap in different conditions.

You can increment the 1 in the test video URL to 2 to see the 2nd video.

**Comment by joeyparrish** [comment]
Using the content you sent in #1108, with the same Chrome version and flags that allowed it to play back, I see that the content fails to play into the second period.  This is due to the presentationTimeOffset field in your second Period, which, based on my analysis, should be zero.

The media timestamps in the mp4 segmenst in period 2 start at DTS 0, so there is no need for a presentationTimeOffset in the second period.  The effect of presentationTimeOffset (PTO) is this:

`presentation time in MediaSource buffer = media timestamp + period start time - PTO`

Since the media timestamps start at 0, PTO should also be 0 to align the content to the start of the period.

**Comment by sandersaares** [comment]
Thank you for investigating!

I confirm your finding that there is something fishy with presentationTimeOffset happening in this content. After adjusting the timing on the production side to reflect reality - there should be a small offset here but not the huge value actually present in the content - this issue no longer occurs. There are still some oddities but I will file separate issues for the issues I see with the fixed (presumably) content.
