### ISSUE TITLE
TTML support

### ISSUE THREAD

**Issue by sirkro** [google/shaka-player#111]
In the latest release of DashJS (1.4.0), they added support for TTML.

It would be perfect if support for TTML could be added to Shaka-player.

Teststream: http://dash.edgesuite.net/dash264/TestCases/4b/qualcomm/1/ED_OnDemand_5SecSeg_Subtitles.mpd

```xml
<AdaptationSet mimeType="application/ttml+xml" lang="en">
	  <Role schemeIdUri="urn:mpeg:dash:role" value="subtitle" />
      <Representation id="7"  bandwidth="268" >
        <BaseURL>English_track.xml</BaseURL>
      </Representation>
    </AdaptationSet>
	  <AdaptationSet mimeType="application/ttml+xml" lang="ge">
	  <Role schemeIdUri="urn:mpeg:dash:role" value="subtitle" />
      <Representation id="8"  bandwidth="268" >
        <BaseURL>German_track.xml</BaseURL>
      </Representation>
    </AdaptationSet>
```

**Comment by joeyparrish** [comment]
Thanks for the request.  At the moment, we rely on the browser's subtitle support.  On Chrome or Firefox, Shaka Player will do WebVTT.

For context, Shaka Player has made a point of not doing any DOM manipulation or CSS so far.  Both of those things would have to change in order for us to render any subtitle format not directly supported by the browser.  It's doable, but would require some architectural changes first.

We can't fit this into our schedule right now, but we'll keep it in mind.

**Comment by sanbornhnewyyz** [comment]
Related to this and a possible alternative for some people, how difficult would it be to add an option to sidecar load WebVTT subtitles?

**Comment by tdrews** [comment]
Please see #133 for a separate discussion on sidecar loading (outside of the MPD) WebVTT subtitles.

**Comment by dougdoe** [comment]
Hi, my team is watching this issue. I have a couple of questions that I hope you can answer to help me plan:

1. Are you implementing TTML Language 1 or TTML Language 2 support? I don't see references to TTML2, so I assume you are following the [TTML Language 1 specification](https://www.w3.org/TR/ttaf1-dfxp/). Is that right?
2. Does this work include support for chunked TTML for Live streams?

**Comment by joeyparrish** [comment]
Hi Doug,

1. We are implementing partial TTML 1 support.  We are using the TTML 1 spec, but we are only implementing what can be represented in the browser's native cues interface.  The means we can't implement extents or origins based on pixel sizes, animation, etc.
2. Shaka v2 betas already support chunked/segmented subtitles, but only in the specific formats we parse.  Currently, that's the textual forms of WebVTT and TTML.  We do not *yet* support text streams embedded in MP4 (#277 and #278).

One important note about segmented text is that just like audio and video, segments must exist to cover the entire period.  If there are no cues to display during a given segment's time, the segment would be a valid WebVTT or TTML file, but would contain no cues.
