### ISSUE TITLE
Edge fails to play 2nd period of presentation

### ISSUE THREAD

**Issue by sandersaares** [google/shaka-player#1110]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**: yes

**What version of Shaka Player are you using**: 2.2.5-debug

**Can you reproduce the issue with our latest release version**: unknown, used demo app

**Can you reproduce the issue with the latest code from `master`**: unknown, used demo app

**Are you using the demo app or your own custom app**: demo app

**If custom app, can you reproduce the issue using our demo app**: N/A

**What browser and OS are you using**:

Windows 10 1709
Edge 40

**What are the manifest and license server URIs**: sent privately

**What did you do?**

Start playback and play over the period change at the 3 minute mark.

**What did you expect to happen?**

Playback continues into 2nd period.

**What actually happened?**

Playback stops with:

```
(video:6) failed fetch and append: code=3015
streaming_engine.js (1377,7)

Player error shaka.util.Error {
  "severity": 2,
  "category": 3,
  "code": 3015,
  "data": [
    {}
  ],
  "handled": false,
  "message": "Shaka Error MEDIA.MEDIA_SOURCE_OPERATION_THREW (InvalidAccessError)",
  "stack": "Error: Shaka Error MEDIA.MEDIA_SOURCE_OPERATION_THREW (InvalidAccessError)\n   at shaka.util.Error (https://shaka-player-demo.appspot.com/lib/util/error.js:72:7)\n   at shaka.media.MediaSourceEngine.prototype.enqueueOperation_ (https://shaka-player-demo.appspot.com/lib/media/media_source_engine.js:772:9)\n   at shaka.media.MediaSourceEngine.prototype.remove (https://shaka-player-demo.appspot.com/lib/media/media_source_engine.js:450:3)\n   at shaka.media.StreamingEngine.prototype.evict_ (https://shaka-player-demo.appspot.com/lib/media/streaming_engine.js:1671:3)\n   at shaka.media.StreamingEngine.prototype.append_ (https://shaka-player-demo.appspot.com/lib/media/streaming_engine.js:1561:3)\n   at Anonymous function (https://shaka-player-demo.appspot.com/lib/media/streaming_engine.js:1332:5)"
}
main.js (550,3)
   "Player error"
   {
      [functions]: ,
      __proto__: { },
      category: 3,
      code: 3015,
      data: [ ],
      handled: false,
      message: "Shaka Error MEDIA.MEDIA_SOURCE_OPERATION_THREW (InvalidAccessError)",
      severity: 2,
      stack: "Error: Shaka Error MEDIA.MEDIA_SOURCE_OPERATION_THREW (InvalidAccessError)
   at shaka.util.Error (https://shaka-player-demo.appspot.com/lib/util/error.js:72:7)
   at shaka.media.MediaSourceEngine.prototype.enqueueOperation_ (https://shaka-player-demo.appspot.com/lib/media/media_source_engine.js:772:9)
   at shaka.media.MediaSourceEngine.prototype.remove (https://shaka-player-demo.appspot.com/lib/media/media_source_engine.js:450:3)
   at shaka.media.StreamingEngine.prototype.evict_ (https://shaka-player-demo.appspot.com/lib/media/streaming_engine.js:1671:3)
   at shaka.media.StreamingEngine.prototype.append_ (https://shaka-player-demo.appspot.com/lib/media/streaming_engine.js:1561:3)
   at Anonymous function (https://shaka-player-demo.appspot.com/lib/media/streaming_engine.js:1332:5)"
   }

```

Chrome 62/64 is unable to start playback of this video due to https://github.com/google/shaka-player/issues/1108
Firefox successfully starts 2nd period, though with some glitching as described in https://github.com/google/shaka-player/issues/1109

**Comment by joeyparrish** [comment]
Using the content you sent in #1108, with the same Chrome version and flags that allowed it to play back, I see that the content fails to play into the second period. This is due to the presentationTimeOffset field in your second Period, which, based on my analysis, should be zero.

The media timestamps in the mp4 segmenst in period 2 start at DTS 0, so there is no need for a presentationTimeOffset in the second period. The effect of presentationTimeOffset (PTO) is this:

presentation time in MediaSource buffer = media timestamp + period start time - PTO

Since the media timestamps start at 0, PTO should also be 0 to align the content to the start of the period.

**Comment by sandersaares** [comment]
Thank you for investigating!

I confirm your finding that there is something fishy with presentationTimeOffset happening in this content. After adjusting the timing on the production side to reflect reality - there should be a small offset here but not the huge value actually present in the content - this issue no longer occurs. There are still some oddities but I will file separate issues for the issues I see with the fixed (presumably) content.
