### ISSUE TITLE
Unexpected large gap detected at start of presentation, in Chrome and Firefox Nightly

### ISSUE THREAD

**Issue by sandersaares** [google/shaka-player#1112]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**: yes

**What version of Shaka Player are you using**: 2.2.5-debug

**Can you reproduce the issue with our latest release version**: unknown, used demo app

**Can you reproduce the issue with the latest code from `master`**: unknown, used demo app

**Are you using the demo app or your own custom app**: demo app

**If custom app, can you reproduce the issue using our demo app**: N/A

**What browser and OS are you using**:

Windows 10 v1709
Chrome 62 and Canary
Firefox 56 and Nightly
Edge 40

**What are the manifest and license server URIs**: sent privately

**What did you do?**

Press Load to start playback.

**What did you expect to happen?**

Playback starts.

**What actually happened?**

In Firefox 56 and Edge, all is well.

In Chome and Firefox Nightly, I get "Ignoring large gap at 0" in console and nothing else happens.

With dash.js, Chrome and Firefox Nightly successfully start playback, so I assume this is some Shaka specific gap logic issue.

The video is similar to the one used for https://github.com/google/shaka-player/issues/1108 except encoded without B-frames to avoid PTS/DTS issues that seemed to be tripping up Chrome. The timing of segments/periods might also be slightly different.

**Comment by joeyparrish** [comment]
In this piece of content, the first period media starts at DTS & PTS of 0.  Your presentationTimeOffset field for that period is set to 2842, with timescale 1000.  The effect of presentationTimeOffset (PTO) is:

`presentation time in MediaSource buffer = media timestamp + period start time - PTO`

So the media timestamps are adjusted back to -2.842 seconds.  The MediaSource spec states that anything before 0 is chopped off, and that removal proceeds up to the next keyframe.

`shakaDemo.localPlayer_.getBufferedInfo()` shows that the buffered range starts at 3.164 seconds, which corresponds to media timestamp of 3.164 + 2.842 = 6.006 seconds, which is indeed the first keyframe after 2.842 seconds.

**Comment by sandersaares** [comment]
Thank you for investigating!

I confirm your finding that there is something fishy with presentationTimeOffset happening in this content. After adjusting the timing on the production side to reflect reality - there should be a small offset here but not the huge value actually present in the content - this issue no longer occurs. There are still some oddities but I will file separate issues for the issues I see with the fixed (presumably) content.
