### ISSUE TITLE
Video flashes on Safari during initial play

### ISSUE THREAD

**Issue by jeremypress** [google/shaka-player#1116]
This issue occurs on the demo site as well as our implementation (version  2.1.8). It looks like the video player disappears and reappears briefly before play. Disabling audio fixes the issue in our implementation. Also, if you seek before playing it seems to avoid the problem. 

Thanks!

Issue Template: 
Have you read the FAQ and checked for duplicate issues:
**Yes**

What version of Shaka Player are you using:
**2.1.8**

Can you reproduce the issue with our latest release version:
**Yes**

Can you reproduce the issue with the latest code from master:
**Yes**

Are you using the demo app or your own custom app:
**Custom**

If custom app, can you reproduce the issue using our demo app:
**Yes**

What browser and OS are you using:
**Safari 11 on Mac OSX Sierra**

What are the manifest and license server URIs:
(you can send the URIs to shaka-player-issues@google.com instead, but please use GitHub and the template for the rest)
**We don't have a license server URI, but here's a link to what an example manifest file looks like:
https://cloud.box.com/s/j7rzq2shdjjk5xikirp7v7zs4wvo1jmi**

What did you do?
**I clicked play on the video after the metadata was loaded**

What did you expect to happen?
**For the video to play with no artifacts**

What actually happened?
**The video briefly disappears and reappears to start playing**

**Comment by vaage** [comment]
@jeremypress Please use the provided issue template so that we can have all the information we need to reproduce the issue in full.

**Comment by vaage** [comment]
Here is a copy of the issue template:

**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**:

**What version of Shaka Player are you using**:

**Can you reproduce the issue with our latest release version**:

**Can you reproduce the issue with the latest code from `master`**:

**Are you using the demo app or your own custom app**:

**If custom app, can you reproduce the issue using our demo app**:

**What browser and OS are you using**:

**What are the manifest and license server URIs**:
*(you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*


**What did you do?**


**What did you expect to happen?**


**What actually happened?**

**Comment by jeremypress** [comment]
@vaage, my bad. Updated the description following the template.

**Comment by vaage** [comment]
Thanks @jeremypress. I am going to leave the "waiting for response" label until we get the manifest.

**Comment by jeremypress** [comment]
@vaage updated

**Comment by vaage** [comment]
@jeremypress I was able to reproduce this with and without Shaka Player. Unfortunately this appears to be a problem with Safari's media source implementation so there is no much we can do. We will file a bug against Safari and update this issue with a link to it once it is filed.

**Comment by jeremypress** [comment]
Thanks @vaage!

**Comment by joeyparrish** [comment]
Closing this stale external (non-Shaka) issue. If you disagree, please reply with @shaka-bot reopen, and it will be automatically reopened.
