### ISSUE TITLE
Edge bug: video glitches when playhead within buffered region

### ISSUE THREAD

**Issue by gesinger** [google/shaka-player#1118]
This appears to be a browser bug, and a ticket has been filed with Microsoft: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/14600375/

Included in that ticket are reproduction steps with Shaka (and dash.js), as well as a note from the dash.js source code related to IE11 and a similar issue.

I wanted to post here to raise the issue for issue tracking, and to point to the relevant bug filed with Microsoft (as well as dash.js).

Please let me know if you have any comments, questions, or workarounds.

Thank you.

There is a mirrored ticket filed with dash.js here: https://github.com/Dash-Industry-Forum/dash.js/issues/2282

**Comment by vaage** [comment]
Thank you @gesinger for filing that for us.

**Comment by joeyparrish** [comment]
Reopening to track that external issue.  We will close when Microsoft releases a fix.  Thanks!

**Comment by joeyparrish** [comment]
Closing this stale external (non-Shaka) issue. In particular, Edge is completely different now, so this is likely no longer valid.
