### ISSUE TITLE
Stop fetching live stream while paused #2

### ISSUE THREAD

**Issue by kuznetcoff777** [google/shaka-player#1121]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**: yes

**What version of Shaka Player are you using**: 2.2.5-debug

**Can you reproduce the issue with our latest release version**: yes

**Can you reproduce the issue with the latest code from `master`**: yes

**Are you using the demo app or your own custom app**:demo

**If custom app, can you reproduce the issue using our demo app**:

**What browser and OS are you using**: win7x64+chrome

**What are the manifest and license server URIs**: vm2.dashif.org/livesim/utc_head/testpic_6s/Manifest.mpd
*(you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*

**What did you do?** Opened stream https://shaka-player-demo.appspot.com/demo/#asset=//vm2.dashif.org/livesim/utc_head/testpic_6s/Manifest.mpd;lang=ru
Paused it and waited for >5 minutes

**What did you expect to happen?** Player will not fetch segments when paused even after >5 minutes (up to timeShiftBufferDepth="PT5M")

**What actually happened?** Palyer still feteches segments after > 5 minutes of being paused

P.s. the same issue https://github.com/google/shaka-player/issues/982 - must be fixed , but in fact it is not.

**Comment by kuznetcoff777** [comment]
Guys, hi! Will it be fixed in 2.3.0?

**Comment by joeyparrish** [comment]
Yes, I'm sure it will.  We have identified the cause and will have a fix out in the near future.

**Comment by joeyparrish** [comment]
The fix has been cherry-picked for v2.2.7.

**Comment by kuznetcoff777** [comment]
Confirm, thanks!
