### ISSUE TITLE
Question about manifest requests

### ISSUE THREAD

**Issue by mimse** [google/shaka-player#1122]
Hi,

When doing live dash, is it possible to only request the manifest ones?  We have a token on our manifests and when it times out we get a 403 from our CDN.

**Comment by TheModMaker** [comment]
Are you asking to only request the manifest **once**?  That really depends on the content of the manifest.  DASH has multiple representations of segments.  Some representations don't require updates and some do.  If you use SegmentTemplate+duration, we can know all possible segments from the first manifest.  You can then set `minimumUpdatePeriod` to a huge value so we never request the manifest again.

However, if you use other segment representations, we will require manifest updates to know about future segments.  Many of the representations require explicitly listing every segment in the manifest, so we need a new manifest to know about new segments.

The prefered way of doing this would be to use the `<Location>` element.  This tells us to make future manifest requests to the given URL instead.  This allows the first request to get a new token, but for future manifest requests (to the new URL) to always give the same token back.

**Comment by joeyparrish** [comment]
@mimse, did we answer your question?  Is there anything else we can do for you on this?

**Comment by vaage** [comment]
Closed due to inactively. @mimse, please feel free to reopen this issue later if this is still an issue for you.
