### ISSUE TITLE
Add support for being able to get KeyStatus

### ISSUE THREAD

**Issue by vasanthap** [google/shaka-player#113]
As part of Un-Prefixed EME we should be able to query for KeyStatus. I request this support to be added to Shaka Player.

**Comment by vasanthap** [comment]
https://w3c.github.io/encrypted-media/#widl-MediaKeySession-keyStatuses

**Comment by vasanthap** [comment]
The correct link is: https://w3c.github.io/encrypted-media/#idl-def-MediaKeyStatus

**Comment by vasanthap** [comment]
Looks like this is already implemented in shaka player: https://github.com/google/shaka-player/blob/master/lib/media/eme_manager.js#L539

**Comment by joeyparrish** [comment]
Okay, then if you have what you need, I'll close this issue.  Thanks!

**Comment by natalieharris** [comment]
I'm not sure if this is what you are looking for. This checks for error key statuses and dispatches an error event if one is found. The ability to query the current keyStatuses does not exist.
