### ISSUE TITLE
[question] How shaka player choose audio stream, can I manually pick one ?

### ISSUE THREAD

**Issue by kocoten1992** [google/shaka-player#1131]
Sorry I didn't read the code (yet), but any explain or guidance are much appreciated

Scenario: when user are playing video on laptop, stereo audio are good enough, but when they have 5.1 audio system, I want to give them the option to switch to 5.1 audio stream.

Does we support that (manually or automatically) ?

**Comment by kocoten1992** [comment]
Does this relate to https://github.com/google/shaka-player/issues/924

**Comment by TheModMaker** [comment]
See #1013.  Currently we will select an audio track based on the current preferred audio language.  If there are multiple matches, we will pick an arbitrary choice.  It is possible to select an explicit one using `selectVariantTrack`.  You can use `getVariantTracks` to get an array of tracks, then find the one with the correct `channelsCount` value and switch to that.  Note that variants refer to an audio+video pair, so you'll need to select the one that has the desired video properties as well.

**Comment by kocoten1992** [comment]
@TheModMaker thank you :+1:
