### ISSUE TITLE
Audio/Video synchronization issue

### ISSUE THREAD

**Issue by pszemus** [google/shaka-player#1132]
**What version of Shaka Player are you using**:
v2.2.6-debug

**Can you reproduce the issue with our latest release version**:
yes

**Can you reproduce the issue with the latest code from `master`**:
didn't check

**Are you using the demo app or your own custom app**:
demo app

**What browser and OS are you using**:
Chrome 62.0.3202.94 (official) (64-bit) @ Fedora 26

**What are the manifest and license server URIs**:
sent to <shaka-player-issues@google.com> as it should not be distributed to public

**What did you do?**
played the stream and waited for more than 5 minutes 

**What did you expect to happen?**
no audio/video synchronization problems

**What actually happened?**
audio/video synchronization issue (video delay that grows)

I've got a source multicast stream that's being transcoded by Wowza Streaming Engine and packaged into DASH stream. After playing the transcoded DASH stream for more than 5 minutes I can see/hear an audio/video delay that grows over time. I think it can be related with UDP frame drops that happens occasionally with the source stream. Restarting the playback helps for a while but after another few mintues this problem comes back. Can something be done on the player's side or it's a browser / Wowza / source stream issue?

**Comment by TheModMaker** [comment]
This looks similar to #707.  There isn't really anything Shaka Player can do to help.  All we do is give the media segments to the browser, it is up to the browser to play them correctly.  This is likely a problem with the media segments.  This is probably a better question for the Wowza team (https://www.wowza.com/support).

**Comment by joeyparrish** [comment]
@pszemus, if you can link us to a public support discussion so we can understand what went wrong, that would be great.  If not, could you provide some update here once this is resolved with Wowza?  That way future Shaka Player users will have a hint about what it took to resolve this issue.  Thanks!

**Comment by pszemus** [comment]
I've created a question in Wowza Streaming Engine forum that's read by the support team, let's wait and see what happens.
https://www.wowza.com/community/questions/46529/audiovideo-synchronization-issue-on-multicast-fram.html

**Comment by joeyparrish** [comment]
Thanks!

**Comment by TheModMaker** [comment]
Two and a half years later, no response on their forum.  Going to close since it's not our fault and there isn't anything we can do.
