### ISSUE TITLE
500 Error returned on Windows and OSX but not Linux

### ISSUE THREAD

**Issue by samwidmer** [google/shaka-player#1134]
[USA_wv.mpd.txt](https://github.com/google/shaka-player/files/1480436/USA_wv.mpd.txt)
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**: Yes

**What version of Shaka Player are you using**: 2.2.6

**Can you reproduce the issue with our latest release version**: Yes

**Can you reproduce the issue with the latest code from `master`**: Yes

**Are you using the demo app or your own custom app**: demo

**If custom app, can you reproduce the issue using our demo app**: N/A

**What browser and OS are you using**: Win7 / Chrome 62.0.3202.75 (64bit) - OSX / Same Chrome Version

**What are the manifest and license server URIs**:
*(you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*
e-mailing manifest URL. I am attaching the mpd however
https://verimatrix-public-alab-tx.mystream2.com:81

/?deviceId=c2Ftc2xhcHRvcA==

**What did you expect to happen?**
When I load these URLs with Ubuntu 16.04 LTS and the same version of Chrome I get good playback.

**What actually happened?**
When loading these URLs with either Windows or OSX I get a 500 error back from the license server. Further digging shows that the payload of the POST operation going to the license server is nearly empty when done from Windows or OSX. The payload for the POST from my Ubuntu system is populated correctly.

**Comment by samwidmer** [comment]
CORS are setup for https://shaka-player-demo.appspot.com/

Here is the request body from my Ubuntu laptop

Ý
ë	
®a|c'VÚkÚP"3Ç"¸öáÅ"0
¦zF¬±rùTNzþ3ÿ6F°ó!àAzcØ.¨£tG|õKí!ORìZÒl]õ¨»r'ÿôëh¶»7R±Ä-¾l
aÜ;3=Uã¿îãfï,É| $Ï·êwö6¾×£~U4¿;*{È}ã¾.*b	ôóøYôyáËíWMÔ$yIgniËo×}Ñ½ß.ÁÝá¼ñ±%¾nÇpÈ>Ç@ïäkØ$íì^±vr+]m,ëÜWÙx<­RáäMé¶Î-Mrè8Rà_9n¨Dsò¡ù%VÎ¢¸y( 9*º²»e|X8÷Q\û8é>®ÚÇÆPJÉRäÕnÚ¦âÃV	 5ÎÅçälu¦S¿e&oF;MM]ÄTý(L±÷UFBx¾Ñà
mÁw¦Q×
Axî&ëyîóï+{N¹jT	Zö´!¡,¶I½Ìy>MäõôNn L©bÑ!·Âfj¢§|ìkIÁ±ê=qö<¬\vßµ¥¹,fjaÝ0Iõ4®âì>Ïg±¡ÛüÓ¡Z5*K»óÌ]P¹óý4Írð¨7»)"­ºà)iQFàHß¯Ù#¾³g×´+«y&´
®Ùå )j²iToÈ7ØôÜÅ"0
ÖZs+þì¯ó!Rê97Î)l´¼qãMÍ½l+2Ý:Jó"ï¬U3bsQâ©:¡ \p,rJ¬@ªÔË=Ýúe°tww)ÝÝÿRÇ<×kÈ'ÒH/¹*fTÿëÖßsÅ	4¨¡¿æBt>NK\²ÑÝÍ#Ûr}X éArêAªN½<ÖxÜÈê¾¿?Ó&F±óGITþ»2óL¬þ5y?çKp ä¸bv5I¥´.â£Ã·éf¾8fgK0ùáj tCÅúºó÷ä³ÉÂ,Û|Û{´ ëTy( 9EP@®G­znÙ*½ªS÷²Ðª\îØqªt||5¦Òëþww·ÍX«b0ÙmKäÍpæß´úx¤:ÛÙäÓ[¯)hí±>ÏoNæ /1O¼þ[¯P ó3êxo ø@
ÈNÌôve1ôÖ¯ó,!r'¬´_Æªnz_
¬
Dã)ÌÒIí¡V\ÒE¨ºb` 'n¼T? Ùï&øýDÇtHjÎutW%ÄÚM"owâ Z95Þc:Ôõ3ô'0ÍMÐbÓ}WþÄØ):µ-¥5h°_ÅºØÜwªp
XpÛÃ!ý£ $AZÞ|iÑðÈìõÌéÎÁ¼¹|D kkYÐú%[ÃàyÆñWPI*C_Èæ7N#½áä×Ökñ%åf8çþ`¼óó²Y=d¿@Æ"±|[±0Û³íZ
architecture_namex86-64
company_nameGoogle

model_name	ChromeCDM

platform_nameLinux"
widevine_cdm_version
1.4.8.10082 J
H
2¢ \ÝoN¨ì½ôí¿apogeeverimatrix"USA*AUDIOÞ²ªg¢×;Þ²L¾Ù £¸Ð01úÏÈ²ì¬ñÖ`d&°iaûN1+ybý ,s¥ëc	×øWWcu95p_æ9éý¯DI³5Àë:³&øØrÀW¨ÕÇª÷S¯GC[e>O¥>ïÐ5ºNì#$þXËõéB©ìåÑÊR»Æ
B¾å[~~è§wÈÎ[&7¾¢´Ò)¤ùV¾¤²07¥½|Àý	ïÏVê²l§n¥¹3Fò!shëa:+{).m¨®ÄaM¨B/}	èq(XPî¶eowæþ;þ\Í[´Ø&9JÿU´Ëõ+5rÌ

**Comment by samwidmer** [comment]
Here is the request payload from my windows box.


**Comment by TheModMaker** [comment]
A 2-4 byte request is usually a server certificate request.  My guess is your license server proxy doesn't support this request (probably it is assuming just license requests), so it is rejecting it.  You'll need to either talk to the proxy host to handle this request or update it to handle the request (the request should just be sent as-is to the license server).

**Comment by samwidmer** [comment]
Why would it be handled differently on Linux and Windows boxes though. Also is there a way we can actually verify this is what's happening?

**Comment by samwidmer** [comment]
I ran it against the proxy at proxy.uat.widevine.com/proxy and it looks like you are right. There is an empty req like I'm getting a 500 on and then another full req. It failed ofcourse because I didn't pass any client id info like I do for our proxy but I think we've found the problem.

**Comment by samwidmer** [comment]
It would probably also be helpful if there was some explanation I could pass on to the proxy vendor about why it happens with one OS but not the other. Do you have any ideas about that?

**Comment by joeyparrish** [comment]
I'm not sure why it's OS-specific.  We (Shaka Player team) aren't in control of the browser or CDM implementations, but you may be able to contact Widevine support for that.

**Comment by mhosman** [comment]
Same error here!!! 500 Internal Server Error from license server. Only in Windows. Only with Chrome 62.

**Comment by joeyparrish** [comment]
Starting in Chrome 62, the Widevine CDM sends a certificate request message that was not always sent in earlier versions.  Your proxy needs to forward this to the Widevine license server.  It sounds like this is a bug in your proxy.

**Comment by joeyparrish** [comment]
Also, this would seem to explain why it doesn't happen on Linux.  The certificate feature introduced in Chrome 62 may not have been implemented on Linux.

**Comment by TheModMaker** [comment]
As Chrome starts requiring certificate requests, people may need to update their license server proxies to handle the new certificate requests.  If you have any questions about how to do this, it is best send to Widevine directly at <http://www.widevine.com/contact.html>.
