### ISSUE TITLE
Add certificate field to custom asset section in demo app

### ISSUE THREAD

**Issue by chrisfillmore** [google/shaka-player#1135]
The demo app should include a 'Certificate URL' field in the custom asset section. This would be helpful for testing:
- Fairplay content
- Widevine content where the license server isn't configured to handle certificate requests

I can make a PR for this.

**Comment by chrisfillmore** [comment]
I'm having a compiler issue. Here is the offending function:

```
/**
 * @param {!string} uri
 * @return {!Promise}
 * @private
 */
shakaDemo.requestCertificate_ = function(uri) {
  var netEngine = shakaDemo.player_.getNetworkingEngine();
  var requestType = shaka.net.NetworkingEngine.RequestType.APP;
  var uris = /** @type {!Array.<string>} */ ([uri]);
  var request = shaka.net.NetworkingEngine.makeRequest(uris);

  return netEngine.request(requestType, request).then(function(response) {
    return response.data;
  });
};
```

This is the message I get from the compiler:

```
[INFO] Compiling the demo app (debug)...
/Users/chrisf/Documents/github_forks/shaka-player/demo/asset_section.js:143: ERROR - Property makeRequest never defined on shaka.net.NetworkingEngine
  var request = shaka.net.NetworkingEngine.makeRequest(uris);
                                           ^^^^^^^^^^^
```

I thought maybe it was the args I was passing to `makeRequest`, so I've tried all of the following:
`var request = shaka.net.NetworkingEngine.makeRequest([uri]);`
`var request = shaka.net.NetworkingEngine.makeRequest(uris);`
`var request = shaka.net.NetworkingEngine.makeRequest(uris, null);`
`var request = shaka.net.NetworkingEngine.makeRequest(uris, shaka.net.NetworkingEngine.defaultRetryParameters);`

Also, is the type annotation necessary here:

```
var uris = /** @type {!Array.<string>} */ ([uri]);
```

?

Thanks for the help.

**Comment by TheModMaker** [comment]
It looks like `makeRequest` isn't exported, so the demo can't access it.  You can either add `@export` to the method or you can create a `Request` object manually and just not include the fields you don't need.  NetworkingEngine will fill any missing fields with defaults.

```js
var request = /** @type {shakaExtern.Request} */ ({uris: [uri]});
```

That cast is needed since it has missing fields.  But the cast for `Array.<string>` shouldn't be needed.

**Comment by chrisfillmore** [comment]
Thanks @TheModMaker, I've submitted a PR.
