### ISSUE TITLE
Playback error with VP9+Opus in DASH

### ISSUE THREAD

**Issue by johnluther** [google/shaka-player#114]
I'm getting an error trying to play unmuxed VP9 and Opus WebM files using a DASH manifest. I get an error, "The browser does not support the media content." The files do play progressively, though (i.e., loaded individually in Chrome as .webm files).

Testing w/ Shaka 1.3.1, Chrome 44.0.2403.61 beta, Mac OS 10.10.4

See http://demo.jwplayer.com/jluther/shaka-no-workie.html. 

I created the files and manifest using FFmpeg (libvpx v1.4.0) according to the instructions at http://wiki.webmproject.org/adaptive-streaming/instructions-to-playback-adaptive-webm-using-dash.

Thanks--
JL

**Comment by joeyparrish** [comment]
I can reproduce your results even with the latest Shaka Player sources, but I don't see anything obviously wrong with Shaka Player here.  Does this MPD work on any other web-based DASH player in Chrome?

It could be that the content is not encoded correctly, which might cause Chrome's MSE implementation to reject it even though Chrome's decoder will handle it as a progressive playback.  I can only speculate.

We do have a working VP9 sample in the test app, and I don't see any differences in the manifests.  So the difference must be in the content itself.

If another MSE-based player can make this work in Chrome, then it would probably be a Shaka Player bug.  If that's the case, please re-open this bug and we'll investigate.  For now, Shaka Player appears to be working as intended.

If the content is correctly encoded, it could be a Chrome bug, which you could file at http://crbug.com/.  Feel free to CC me if you do.

If the content is broken, then the ffmpeg instructions from the WebM project may be at fault, in which case you should contact the WebM team.  I'm not sure where their bug tracker is off-hand.

**Comment by FrankGalligan** [comment]
John if I try to pull the webm content from the BaseURL in the mpd I get 404's. Are the permissions on webm files set correctly?

**Comment by johnluther** [comment]
Sorry, @FrankGalligan , I moved those files around while testing. I moved them back, please try again.

JL

**Comment by johnluther** [comment]
I think there might be a bug in Chrome with odd (i.e., not divisible by 2) frame sizes in WebM w/ DASH. 

I made two sets of files. The *only* difference between them is that one was encoded with the FFmpeg scaling filter set to "-1" for width, and the other was set to "-2." (The "-1" scales proportionally but sometimes results in widths that are not divisible by 2. The "-2" always forces a size that is divisible by two.)

This set (-1) produces the error: http://demo.jwplayer.com/jluther/shaka-odd.html 

This set (-2) does not: http://demo.jwplayer.com/jluther/shaka-even.html

JL

**Comment by joeyparrish** [comment]
@johnluther, good find!  Have you filed on http://crbug.com/ ?  I'd love to subscribe to that issue and keep informed on their progress.

**Comment by johnluther** [comment]
@joeyparrish, I was going to file it, but it looks like it was reported last month & the team is looking into it:

https://code.google.com/p/chromium/issues/detail?id=505070&q=odd%20size&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Cr%20Status%20Owner%20Summary%20OS%20Modified

I'll add my info as another test case.

JL

**Comment by joeyparrish** [comment]
Awesome, thanks for the link!
