### ISSUE TITLE
Add VDMS "Multi DRM" test assets to the demo app.

### ISSUE THREAD

**Issue by TheJohnBowers** [google/shaka-player#1140]
I would like to provide a pull request to add "Multi DRM" assets into the demo app from VDMS.  These assets will provide some VDMS assets that support PlayReady playback in addition to the existing VDMS demo assets that already support WideVine playback.

As it has been suggested that an issue be opened before submitting a pull request, I am doing just that.

**Comment by joeyparrish** [comment]
@TheJohnBowers, can we close this issue now that you added some multi-DRM VDMS assets back in November?  Thanks!

**Comment by sandersaares** [comment]
FYI an anomaly was discovered in these assets https://github.com/Dash-Industry-Forum/dash.js/issues/2334

**Comment by TheJohnBowers** [comment]
Yeah, done.
