### ISSUE TITLE
Transmuxed TS content produces Shaka error 3016 and 3015 in Safari

### ISSUE THREAD

**Issue by chrisfillmore** [google/shaka-player#1143]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**:
Yes

**What version of Shaka Player are you using**:
Latest from master

**Can you reproduce the issue with our latest release version**:
Unknown

**Can you reproduce the issue with the latest code from `master`**:
Yes

**Are you using the demo app or your own custom app**:
Demo app

**What browser and OS are you using**:
Safari Version 11.0.1 (13604.3.5), macOS 10.13.1

**What are the manifest and license server URIs**:
Sent by email

**What did you do?**
Attempt to load the playlist using the demo

**What did you expect to happen?**
Content to play

**What actually happened?**
Shaka publishes error 3016, with a MediaError code 3, MEDIA_ERR_DECODE. Then it publishes error 3015, but I assume that 3015 happens as a result of the underlying decoding error. See attached image below.

If I modify the MediaSource polyfill so that TS content does not get rejected, I can play the video. That is to say, I just make this change in `mediasource.js`:

```
if (container == 'mp2t') {
  // return false;
}
```

The video has other problems (seeking causes errors), but it does play. It's also worth pointing out that Shaka produces some logging indicating a gap at the start of the content. I don't know exactly what this means or if it could be a source of errors for muxjs.

![screen shot 2017-11-21 at 1 07 20 pm](https://user-images.githubusercontent.com/7190265/33088902-02ab866a-cebd-11e7-9d05-a28cef3ded2b.png)

**Comment by TheModMaker** [comment]
Error 3016 is a decoder error, Safari is just refusing to play the content.  I notice the content is multiplexed; maybe Safari doesn't support multiplexed MP4?  Do you have the same stream without audio or with a separate audio stream?

When I play in Chrome, I notice some logs from `chrome://media-internals`:

> Media segment did not contain any coded frames for track 257, mismatching initialization segment. Therefore, MSE coded frame processing may not interoperably detect discontinuities in appended media.

Maybe Safari is choking on this or the multiplexed content?  I'll look into why we are getting these logs.

Also, FYI, we disabled native TS playback on Safari since it is broken for a lot of content and doesn't play adaptation or track switching well with MSE.

**Comment by chrisfillmore** [comment]
I may be able to send a custom application that will play content that is not multiplexed; I'll have to look into it. I will get back to you.

**Comment by TheModMaker** [comment]
I just re-tested and it seems to work for me.  So it may be fixed unless you fixed the stream another way (I didn't look too much into it).  Since a lot has changed since then I would suggest testing again.

For now I'll close it, but if the issue persists you can reopen.

**Comment by chrisfillmore** [comment]
I just tested again on master and it plays for me as well. Thanks for the follow up.
