### ISSUE TITLE
DRM.FAILED_TO_CREATE_SESSION - Rejected with system code (70)

### ISSUE THREAD

**Issue by danmo** [google/shaka-player#1144]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**: yes

**What version of Shaka Player are you using**:2.2.6

**Can you reproduce the issue with our latest release version**: yes

**Can you reproduce the issue with the latest code from `master`**: yes

**Are you using the demo app or your own custom app**: own

**If custom app, can you reproduce the issue using our demo app**: yes

**What browser and OS are you using**: DRM enabled Electron in Windows

**What are the manifest and license server URIs**: 
*(you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*

**What did you do?**
Trying to playback downloaded asset

**What did you expect to happen?**
Playback should work

**What actually happened?**
Player throws error:
"Shaka Error DRM.FAILED_TO_CREATE_SESSION (Rejected with system code (70))"

Hi, what's the meaning of system code 70 ?I have an electron app that downloads DRM encrypted content and plays it locally. This error happens only on Windows (tested on 8.1 and 10 so far).

On mac everything works fine.

Implementation follows this example: https://shaka-player-demo.appspot.com/docs/api/tutorial-offline.html

**Comment by TheModMaker** [comment]
That is a code given to us by the browser.  These codes are not publically documented.  Did you set `usePersistentLicense` to false?  You can't store licenses offline on desktop.  Does the error happen during storage or when playing?  If you reload the page, can you play it then?  Can you provide a link to the code you are testing with?  You can send it privately to shaka-player-issues@google.com if you want.

**Comment by joeyparrish** [comment]
@danmo, is this still an issue for you?  If so, can you provide a way for us to reproduce the issue?

**Comment by danmo** [comment]
Solved. In my case, it was due to missing VMP signing.

**Comment by joeyparrish** [comment]
Okay.  Thanks for the update!
