### ISSUE TITLE
Live stream doesn't play on Chromecast

### ISSUE THREAD

**Issue by shaygolan01** [google/shaka-player#1149]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**: Yes

**What version of Shaka Player are you using**: 2.2.6

**Can you reproduce the issue with our latest release version**: Yes

**Can you reproduce the issue with the latest code from `master`**: Yes

**Are you using the demo app or your own custom app**: Custom app

**If custom app, can you reproduce the issue using our demo app**: 

**What browser and OS are you using**: Chromecast Ultra and gen2

**What are the manifest and license server URIs**: 
https://dfwlive-sponsored.akamaized.net/Content/DASH.abre/Live/channel(BBCAHD-6053.dfw.1080.mobile)/manifest.mpd
(the content is DRM protected and I cannot supply the license for it)

**What did you do?**
Loaded the live content.

**What did you expect to happen?**
Stream begins to play after a couple of seconds of requesting video and audio data.

**What actually happened?**
Stream doesn't play, though I see video and audio downloading. 

This issue started after bug fix #1061 
It seems that our manifest imposes a 'video.seeking' and 'video.paused' on the first attempt to set the play head position, that prevents   shaka.media.Playhead.prototype.onPollGapJump_ completing.
See playhead.js onPollGapJump_ function

**Comment by TheModMaker** [comment]
Without a license server URL, we can't reproduce the problem.  You can send the URL privately to shaka-player-issues@google.com if you like.  I can play all our live and protected content fine on Chromecast, so we need to be able to play your content to see any issue.

**Comment by TheModMaker** [comment]
We just reverted the fix for #1061.  Can you test again to see if that fixes it?  You can use the nightly, but be sure to clear the cache and check the version starts with `v2.2.0` followed by a number that is at least 133:

https://nightly-dot-shaka-player-demo.appspot.com/demo/

**Comment by shaygolan01** [comment]
Thank you for understanding the license issue.
I tested the reverted fix #1061 and our live stream still doesn't play.
On v2.2.2 the live stream plays fine. 
It seem  that another change for #982, this [fix](https://github.com/google/shaka-player/commit/0d5c357a98dd048b1e60e7561087d134cbfc3ca0#diff-bffea2e14c5acdb1cf1c0b406eec2808) ` if (this.video_.paused) return;` has the same effect as ` if (this.video_.seeking) return;`
Only removing both lines enables the stream to start playing.

I understand that these fixes are for issues occurring during playback, maybe a condition allowing to ignore these lines **only** on playback start is a suitable fix for our issue?

**Comment by shaygolan01** [comment]
#

**Comment by joeyparrish** [comment]
We should retest this once v2.2.7 is out.  We have fixed a few issues lately that might be related: #1105, #1150.  When those fixes are in the demo receiver, we should see if those fixes help at all.

**Comment by shaygolan01** [comment]
Tested with 2.2.7 Our live streams are playing.
