### ISSUE TITLE
Mousing over video while window is shrunk down causes it to rapidly resize

### ISSUE THREAD

**Issue by theodab** [google/shaka-player#1151]
In the demo app, if the window is shrunk down sufficiently small (for example, the dev tools are open and expanded to be very wide) and there isn't a scrollbar onscreen, mousing over the window causes it to rapidly fluctuate in size. In addition, playing an asset causes the video to fluctuate and spew out "ResizeObserver loop limit exceeded" errors. Presumably this is a CSS issue, because Shaka Player does not set any ResizeObservers.
It looks like what is happening is that the scroll bar appears, causes the video to resize to be slightly smaller, which then causes the scroll bar to disappear. Repeat over and over.

I first noticed this when testing a CL in progress, because if the version string in the title is wider than the shrunk-down window it will make a scroll bar appear. window.innerWidth=371 and window.innerHeight=723. I got the error by having the dev tools take up ~70% of the width of the screen.

**Comment by joeyparrish** [comment]
Any time there are mouseovers which cause layout changes, it will always be possible for a resize to trigger scrollbars, which changes layout, which changes the element under the mouse, which triggers a resize, and so on.

The root of this issue, to me, seems to be that mousing over the video should change the layout of the demo page at all.  The visibility of the controls overlay should not change the size or position of anything.

**Comment by joeyparrish** [comment]
Obsoleted by the new UI.
