### ISSUE TITLE
Shaka Packager HLS MP4 Fails to play - failed fetch and append: code=3014

### ISSUE THREAD

**Issue by buggles333** [google/shaka-player#1152]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**:
Yes

**What version of Shaka Player are you using**:
2.2.6

**Can you reproduce the issue with our latest release version**:
Yes

**Can you reproduce the issue with the latest code from `master`**:
Yese

**Are you using the demo app or your own custom app**:
Demo App

**What browser and OS are you using**:
Windows 7, Chrome 62

**What are the manifest and license server URIs**:
[d2o1ul0cbfdx5w.cloudfront.net/test/h264_master.m3u8](d2o1ul0cbfdx5w.cloudfront.net/test/h264_master.m3u8)

**What did you do?**
I have encoded a[ small video](http://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_1mb.mp4) into HLS MP4 using the [Shaka Packager tutorial](https://google.github.io/shaka-packager/html/tutorials/hls.html) - I then tried playing it using the demo Shaka Player code from the wiki

**What did you expect to happen?**
I expected the video to play

**What actually happened?**
All looks like it is loading in the console but it then runs into the following errors...
- The video has now been loaded!
streaming_engine.js:1211 (video:1) looking up segment: presentationTime=0 currentPeriod.startTime=0
streaming_engine.js:1374 (video:1) failed fetch and append: code=3014
CHUNK_DEMUXER_ERROR_APPEND_FAILED: Append: stream …1072 append_window_start=0 append_window_end=5.28"]

I am assuming it is something to do with the encoding but I have followed the official tutorial exactly, can anyone shed any light on what is going wrong?

**Comment by buggles333** [comment]
Have just tried with a different source file and encoded it to HLS again using shaka-packager.  Still get the same results.

Does anyone have a zipped HLS file they can link to so I can download and compare layout and manifests?

**Comment by kqyang** [comment]
It is actually a bug in Shaka Packager, which is already fixed. v1.6.2 does not properly support fmp4+hls.

Please try again with Shaka Packager latest commit. (Shaka Packager team is preparing for a new release, so hopefully a new release will come out soon)

**Comment by joeyparrish** [comment]
@buggles333, please let us know if an updated Shaka Packager fixes it for you.

**Comment by buggles333** [comment]
Will give it a try now and let you know

**Comment by buggles333** [comment]
Struggling to build a windows binary for the latest commit, I think a later version of Visual Studio is causing conflicts.  Anyone have a prebuilt binary?

**Comment by joeyparrish** [comment]
@kqyang, can you provide an up-to-date binary of the packager for Windows?  Or should we wait for the next release?

**Comment by kqyang** [comment]
Here it is: https://ci.appveyor.com/api/buildjobs/00kv3f0a5lo28vwt/artifacts/packager-win.exe

**Comment by buggles333** [comment]
Thank you!  I was just creating a clean windows install but this saves me a job.  Will try out a new encode now and update

**Comment by kqyang** [comment]
No problem. 

Btw, the binary above is for 64-bit Windows. If you happen to use 32-bit, you can always go to this link: https://ci.appveyor.com/project/shaka/shaka-packager and select the relevant config and download the binary from "artifacts" tab.

**Comment by buggles333** [comment]
Did a fresh encode using the new version of the packager and all is working now, thanks for the help. Once further question though, does Shaka Player work on iOs or am I better of using their native HLS player?

**Comment by TheModMaker** [comment]
We currently don't support iOS since iOS doesn't support MediaSource.  But after #997 we will support direct playback of HLS content on iOS, but not DASH.  Also, we will just be using the native HLS support anyway, so it won't gain you anything.
