### ISSUE TITLE
including external file

### ISSUE THREAD

**Issue by Giuscar** [google/shaka-player#1153]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**:
yes
**What version of Shaka Player are you using**:
v2.2.6
**Are you using the demo app or your own custom app**:
I have created a new plugin. Therefore custom app.

**What browser and OS are you using**:
Firefox v57.0

**What did you do?**
I try to compile the new plugin as explained into the guide using the command python build/build.py +@complete +path/to/my/plugin 

**What did you expect to happen?**
I would expect that the plugin is built.

**What actually happened?**
Desktop/Shaka_Player/shaka-player/lib/net/my_http_plugin.js:39: ERROR - missing require: 'Object'
    var myObject = new Object("/app1");
Object is a class coming from another javascript file (it's a kind of library). Is there a way to include external libraries inside shaka?

**Comment by theodab** [comment]
Well, if the library in question is made to be compatible with the Closure compiler, you can add the line `goog.require(Object');` to the top of the file.
If it isn't, you can write externs for the methods/classes you use from it. Externs are meant to tell the Closure compiler of the interfaces of things from the environment. You can learn more about externs [here](https://developers.google.com/closure/compiler/docs/api-tutorial3#externs), or look at our externs folder for some examples. You can add the new extern file just like the plugin file, by adding `+path/to/the/extern` to the build command.

**Comment by Giuscar** [comment]
Thank you for your answer.
This is what I am trying to do.
After I finish to define the externs how can Closure match my externs with my external library? Is it a process done automatically by the compiler?

Thank you.

**Comment by theodab** [comment]
Once you have written externs, you can load the library into the HTML page separately with script tags. Once it has been provided the externs, Closure just assumes that the defined things exist independently to the compiled code; for all it knows, your Object library is just some browser API.

**Comment by Giuscar** [comment]
Thank you. 
I have been able to compile the library. But what about the demo app?
Shouldn't it be compiled as well?

**Comment by joeyparrish** [comment]
We do compile the demo app now (in master branch).  It's a recent change that isn't in the v2.2.x releases.

**Comment by Giuscar** [comment]
Ok, thank you.
