### ISSUE TITLE
Question - MPD Refreshment

### ISSUE THREAD

**Issue by remoroethlisberger** [google/shaka-player#1155]
Hi there,

I have question concerning the Shaka Player and the MPD file. Is there some easy way to automatically fetch the MPD file every now and then. I want to modify it on the server side and then always fetch the updated MPD description. I read about the *minimumUpdatePeriod*, but I am not sure if this works for a MPD file, which is of type *static*. What is the easiest way to achieve this, how would the head of the MPD file look like?

Thanks in advance
Remo

**Comment by theodab** [comment]
The minimumUpdatePeriod attribute can be used for all MPDs, even static ones. So minimumUpdatePeriod should work for your purposes.

**Comment by TheModMaker** [comment]
What are you trying to update?  If the content is VOD, you don't need to update the segment list, so there isn't much else that needs updating.  If you are adding segments later, then it isn't static.

**Comment by remoroethlisberger** [comment]
Thanks for your answers, to be more specific, I am currently using the following MPD file:

```
<?xml version="1.0"?>
<!-- MPD file Generated with GPAC version 0.5.1-DEV-rev5619  on 2017-11-30T20:56:02Z-->
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" minBufferTime="PT1.500000S" type="dynamic" availabilityStartTime="2017-11-30T20:56:02Z" timeShiftBufferDepth="PT0H0M0.00S" minimumUpdatePeriod="PT0H0M10.00S" profiles="urn:mpeg:dash:profile:isoff-live:2011">
 <ProgramInformation moreInformationURL="http://gpac.sourceforge.net">
  <Title>DASH.mpd generated by GPAC</Title>
 </ProgramInformation>

 <Period id="GENID_DEF" start="PT0H0M0.00S">
  <AdaptationSet segmentAlignment="true" bitstreamSwitching="true" maxWidth="320" maxHeight="180" maxFrameRate="24" par="16:9" lang="und">
   <SegmentTemplate initialization="DASH_init.mp4"/>
   <Representation id="1" mimeType="video/mp4" codecs="avc1.42c00d" width="320" height="180" frameRate="24" sar="1:1" startWithSAP="1" bandwidth="22380">
    <SegmentTemplate timescale="12288" media="output_low_dash_track1_$Number$.m4s" startNumber="1" duration="96764"/>
   </Representation>
   <Representation id="2" mimeType="video/mp4" codecs="avc1.42c00d" width="320" height="180" frameRate="24" sar="1:1" startWithSAP="1" bandwidth="203825">
    <SegmentTemplate timescale="12288" media="output_medium_dash_track1_$Number$.m4s" startNumber="1" duration="96764"/>
   </Representation>
  </AdaptationSet>
 </Period>
</MPD>
```

this works fine for me and the MPD file does get fetched every 10 seconds. However when I remove one representation during the playback, I will most likely get an error. (tested it out on MP4Client). Any ideas on how to dynamically change the number of representations available and let the client know? :)

**Comment by joeyparrish** [comment]
Changing the Representations is not allowed as far as I know.  At least, doing so would come with serious compatibility and interoperability issues.

In general, we do not support DASH content that goes far afield of the [DASH Interoperability Points (IOP)](http://dashif.org/wp-content/uploads/2017/09/DASH-IF-IOP-v4.1-clean.pdf).

**Comment by remoroethlisberger** [comment]
Ok, thanks for the update. Appreciate your input! :)

**Comment by joeyparrish** [comment]
Happy to help!
