### ISSUE TITLE
ECMAScript 6?

### ISSUE THREAD

**Issue by gkal19** [google/shaka-player#1157]
What do you guys think of refactoring the code from ES5 to ES6?

**Comment by theodab** [comment]
At the moment we still support IE 11, and IE 11 does not support ES6 and (presumably) never will.

Maybe at some point in the future we will stop supporting IE 11 and upgrade everything to ES6. Perhaps if, once the [Shaka Player survey](https://docs.google.com/forms/d/e/1FAIpQLSfCAjWTmMtXeS4CL3n2v-oVzL5yaXJdEttc5RhZFAq2j02yfw/viewform) has ended, we find that not many people care about IE 11 support? I can't make any promises, of course.

**Comment by joeyparrish** [comment]
We could move to ES6 without dropping IE11 support, by changing the way we develop.  Uncompiled mode is the issue.  In uncompiled mode, ES6 code won't run on IE11.  If we are compiling ES6 down to ES5, we can still develop in ES6 and run compiled ES5 on IE11.

**Comment by joeyparrish** [comment]
This will be a long transition.  In particular, replacing the linter will be a giant pain.

Checklist for ES6 conversion:
 - [ ] Use Babel to serve ES5 in unit tests, so we can still test uncompiled code on IE11
 - [ ] Disallow uncompiled build in the demo app on IE11
 - [ ] Allow ES6 input in the compiler settings
 - [ ] Replace the long-deprecated gjslint with modern JS linters that understand ES6
   - [ ] Convert code to pass new linters/settings
   - [ ] Reimplement property doc enforcement for typedefs (move from gjslint to jsdoc?)
 - [ ] Start converting library code to ES6 syntax
 - [ ] Polyfill some ES6 methods and lift some of the bans in `build/conformance.textproto`

**Comment by joeyparrish** [comment]
ES6 work and linter changes cherry-picked to v2.3.1 to make it easier to cherry-pick bug fixes from after these ES6 changes.

**Comment by joeyparrish** [comment]
Until https://github.com/google/closure-compiler/issues/893 is resolved, we can't use ES6 syntax in our externs.

**Comment by joeyparrish** [comment]
ES6 is now possible in externs!  If it doesn't work right away, we may need a compiler update.
