### ISSUE TITLE
2.2.7 broke the shaka demo

### ISSUE THREAD

**Issue by squarebracket** [google/shaka-player#1158]
[This change to index.html](https://github.com/google/shaka-player/commit/54d2c0d199bf82092896f6ddfa5847fa30e4cf29#diff-3e22c50371c76d64ea9738dbc46a6e57) does not seem to be in the [demo player](https://shaka-player-demo.appspot.com/demo/)'s index.html. This is causing the demo player to not work for custom assets.

**Comment by joeyparrish** [comment]
Our demo is cacheable for 1 hour.  Right after a deployment, this sometimes causes issues.  Please clear your browser cache and try again.

**Comment by squarebracket** [comment]
Huh. Ctrl+f5 didn't do it, having the console open didn't do it. Guess I specifically needed the network tab focused for "disable cache" to take effect. It's showing now, thanks!

**Comment by joeyparrish** [comment]
Glad it's working.  Sorry for the trouble!
