### ISSUE TITLE
Player stops at the end of unencrypted samples

### ISSUE THREAD

**Issue by simhavenkat** [google/shaka-player#1170]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**:
Yes
**What version of Shaka Player are you using**:
1.6.4
**Are you using the demo app or your own custom app**:
Custom app
**What browser and OS are you using**:
Chrome/macSierra
**What did you do?**
I have a widevine video that fails to play beyond the initial unencrypted portion. In the emelogger - i see the license request succeeds. But once it hits the encrypted portion it says Stream audio/mp4: stream has ended and the playback stops. The actual video is much longer. 

I have been able to play the video on android using exoplayer. The video itself is fine.

I am stuck with an old version of shaka-player for reasons beyond my control. I am looking for some directional help with debugging this. 

Per the emelogger - keystatuseschangedevent all my keys are usable. Any tips on where to look?

**Comment by TheModMaker** [comment]
Usually the reason the video stops and you don't get errors is because the key is missing.  This can happen because of problems packaging the content or because of proxy problems.  On Chrome, you can navigate to `chrome://media-internals` to get more info about what the media element is doing.  Also if the audio ends and the video doesn't, it will stop playing while it waits for the audio segments.  Your audio and video streams need to be the same duration.

**Comment by joeyparrish** [comment]
If your keys are usable, but it won't play through the encrypted part, it could be that the key IDs in your license do not match what is in your content.

**Comment by simhavenkat** [comment]
Media Internals shows: DecryptingAudioDecoder: failed to init decoder on decryptor
Will check on the keyid mismatch but Android exoplayer also wouldn't be able to play in that case. Right? Looking into StreamVideoSource onKeyStatusesChange - all my streams are marked with allowedByKeySystem

**Comment by joeyparrish** [comment]
I would suspect Exoplayer also to fail with a keyid mismatch.  If you get the same keyids on both platforms, then that's not the issue.

Also, the "DecryptingAudioDecoder failed to init" message is a good clue that it's not a problem with key IDs.

Can you test the same manifest and license server in the current demo?  https://shaka-player-demo.appspot.com/demo/

If it plays in v2, then an upgrade should help.  We have an [upgrade guide](https://shaka-player-demo.appspot.com/docs/api/tutorial-upgrade-v1.html) to help you with that process.

If it fails the same way in v2, then it's nothing to do with Shaka Player.  It could be a problem with the content itself, for example, if the hardware decoder can't decode but a software decoder can.  You may want to try disabling hardware decoding in chrome://flags and see if that affects the issue.

**Comment by simhavenkat** [comment]
Will do the V2 test - quick followup question: Can shaka player play a partially encrypted stream? Or was that something added recently?

**Comment by joeyparrish** [comment]
We have always been able to play encrypted content with a clear lead, or any other kind of partial encryption, for that matter.  We really don't do anything special for that.  The browser just handles it for us.

**Comment by simhavenkat** [comment]
Verified that my content is fine as it plays fine with my local demo app built off 1.6.x. The difference i see between my local copy of shaka and the 1.6.x is - the stream starts saying there is no more segment references and signals end of stream. Is there any action required from the player once the license is fetched?

**Comment by joeyparrish** [comment]
There is no action required from the application once a license is fetched.

Were you able to play your content with the v2 demo?
