### ISSUE TITLE
Incorrect parsing of headers in MSIE

### ISSUE THREAD

**Issue by TomHetmer** [google/shaka-player#1172]
Hi,

this is probably a bug in IE(?) but we observed the following issue when parsing the Content-Type header in IE which causes shaka to fail when the playlist doesn't have an extension:
![pasted image at 2017_12_06 11_50 am](https://user-images.githubusercontent.com/5316250/33660262-8a3cccd4-da83-11e7-8b52-fe6b99bd4916.png)

It seems some random newlines are inserted to getAllResponseHeaders() in MSIE:

![bez nazvu](https://user-images.githubusercontent.com/5316250/33660267-8d42fb56-da83-11e7-956e-8ef749bcbf21.png)

shaka-player/lib/net/http_plugin.js should filter empty lines to parse it correctly, otherwise we end up with shaka.util.Error.Code.UNABLE_TO_GUESS_MANIFEST_TYPE in shaka-player/lib/media/manifest_parser.js

Relevant issue may be:
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/5403401/

IE 11.674 / Win 10 x64

**Comment by TomHetmer** [comment]
We workarounded around this by changing all[header[0].toLowerCase() to all[header[0].toLowerCase().trim()

**Comment by michellezhuogg** [comment]
Could you please add a manifest URL that reproduces the issue?

**Comment by TomHetmer** [comment]
Sure. This link is valid for 30 days.
https://mgmt.ct.cdn77.eu/play?token=fe5dbccf3dd0ade9022f12876037b3b7851bc566&contentType=live&expiry=1515281018&id=2402&playerType=dash&quality=web&region=1&skipIpAddressCheck=true&userId=user_id

**Comment by joeyparrish** [comment]
The fix has been cherry-picked for v2.2.9.
