### ISSUE TITLE
Progress bar in cast dialogue has incorrect duration.

### ISSUE THREAD

**Issue by theodab** [google/shaka-player#1174]
![screen shot 2017-12-07 at 1 35 16 pm](https://user-images.githubusercontent.com/21047092/33739874-8b1c17a6-db53-11e7-81d4-4f6f8c9d7922.png)

The currentTime property is being synchronized properly, but the duration does not seem to be.

**Comment by theodab** [comment]
Looking over Chromecast [docs on media playback messages](https://developers.google.com/cast/docs/reference/messages), it looks like current time is synchronized by MediaStatus messages, which we emit. Duration, on the other hand, is handled by MediaInformation messages, which we do not. That would explain why the dialogue has a current time, but not a duration.

As far as I can tell, however, MediaInformation messages are supposed to be sent by the sender as part of the process of loading the media? We load media through our own pipeline, so we don't make use of castSession.loadMedia. And I don't know if you can just send a MediaInformation message on it's own, solely to set duration.

You can include a MediaInformation message as part of the MediaStatus block, but that is meant to be a signal that the asset playing has changed on the receiver's end, so it would probably be improper to use it to set duration.

**Comment by theodab** [comment]
Note that this change will need to be in the cast receiver to work, so it won't show up until we upload a new version of the receiver.

**Comment by joeyparrish** [comment]
Cherry-picked to v2.3.1.

**Comment by joeyparrish** [comment]
Cherry-picked for v2.2.10.

**Comment by joeyparrish** [comment]
The cast receiver has been updated for v2.2.10 and v2.3.1.
