### ISSUE TITLE
On ubuntu 14, python build/all.py fails with error for npm and node.js version mismatch

### ISSUE THREAD

**Issue by jmcsagdc** [google/shaka-player#1175]
These are the install steps from the page:
(1)
sudo apt-get update
sudo apt-get install git python2.7 default-jre-headless npm
(2)
sudo npm install -g n
sudo n stable
sudo npm install -g npm
(3)
git clone https://github.com/google/shaka-player.git
cd shaka-player
(4)
python build/all.py

EXPECTED:
dist bundles to be created

ACTUAL:
Fails with the following text:
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8.
npm WARN npm You can find the latest version at https://nodejs.org/
WARNING: You are likely using a version of node-tar or npm that is incompatible with this version of Node.js.
Please use either the version of npm that is bundled with Node.js, or a version of npm (> 5.5.1 or < 5.4.0) or node-tar (> 4.0.1) that is compatible with Node.js 9 and above.
/usr/local/bin/node[31143]: ../src/node_zlib.cc:437:static void node::{anonymous}::ZCtx::Init(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args.Length() == 7 && "init(windowBits, level, memLevel, strategy, writeResult, writeCallback," " dictionary)"' failed.
 1: node::Abort() [npm]
 2: node::Assert(char const* const (*) [4]) [npm]
 3: 0x1255aff [npm]
 4: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [npm]
 5: 0xb77f9c [npm]
 6: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [npm]
 7: 0x38cc29e842fd
Traceback (most recent call last):
  File "build/all.py", line 86, in <module>
    shakaBuildHelpers.run_main(main)
  File "/home/myusername/shaka-player/build/shakaBuildHelpers.py", line 292, in run_main
    sys.exit(main(sys.argv[1:]))
  File "build/all.py", line 55, in main
    code = check.main([])
  File "/home/myusername/shaka-player/build/check.py", line 215, in main
    if not step():
  File "/home/myusername/shaka-player/build/check.py", line 69, in check_html_lint
    if not shakaBuildHelpers.update_node_modules():
  File "/home/myusername/shaka-player/build/shakaBuildHelpers.py", line 270, in update_node_modules
    execute_get_output([cmd, 'install'])
  File "/home/myusername/shaka-player/build/shakaBuildHelpers.py", line 143, in execute_get_output
    raise subprocess.CalledProcessError(obj.returncode, args[0], stdout)
subprocess.CalledProcessError: Command 'npm' returned non-zero exit status -6

**Comment by joeyparrish** [comment]
It looks like `sudo n stable` now installs nodejs v9, but you had npm v5.5.1, which is incompatible with nodejs v9.

We'll see if we can write more universally-usable instructions for this.

**Comment by joeyparrish** [comment]
Cherry-picked for v2.3.3.
