### ISSUE TITLE
Allow user to override timeShift value in dash live stream through the config

### ISSUE THREAD

**Issue by amity177** [google/shaka-player#1177]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**:

**What version of Shaka Player are you using**:

**Can you reproduce the issue with our latest release version**:

**Can you reproduce the issue with the latest code from `master`**:

**Are you using the demo app or your own custom app**:

**If custom app, can you reproduce the issue using our demo app**:

**What browser and OS are you using**:

**What are the manifest and license server URIs**:
*(you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*

**What did you do?**

**What did you expect to happen?**

**What actually happened?**

**Comment by TheModMaker** [comment]
Are you talking about the `timeShiftBufferDepth` attribute?  That attribute specifies how long the content is alive on the server.  If you tried to make it longer, we may not be able to download the segments because the segments no longer exist on the server.  We could add a way to reduce the size similar to the seek range but for live.

**Comment by joeyparrish** [comment]
I think this feature is not working correctly. I will reopen and investigate.

**Comment by joeyparrish** [comment]
The override set by the player after the initial manifest is parsed is wiped when a live manifest is updated.

**Comment by theodab** [comment]
Huh. But only on DASH. Well, that explains why I didn't notice, I was mostly testing with HLS.
I'll look into it.

**Comment by joeyparrish** [comment]
No need, I'm already putting together the CL.
