### ISSUE TITLE
Allow live stream to start from a relative point to the live edge

### ISSUE THREAD

**Issue by amity177** [google/shaka-player#1178]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**:

**What version of Shaka Player are you using**:

**Can you reproduce the issue with our latest release version**:

**Can you reproduce the issue with the latest code from `master`**:

**Are you using the demo app or your own custom app**:

**If custom app, can you reproduce the issue using our demo app**:

**What browser and OS are you using**:

**What are the manifest and license server URIs**:
*(you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*

**What did you do?**

**What did you expect to happen?**

**What actually happened?**

**Comment by joeyparrish** [comment]
We will add a way for an app to specify a relative offset from the live edge when calling `Player.load()`.  For example, playback starting at -10 in a live stream would be 10 seconds before the live edge.  This is in contrast to an absolute media timestamp (as we expect now).
