### ISSUE TITLE
Update FAQ, upgrade guides for v2.3

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#1183]
As we close out v2.3, the FAQ and upgrade guides need to be updated.  Many things have changed since v2.2.

**Comment by joeyparrish** [comment]
Architecture diagrams should be updated as well.

**Comment by vaage** [comment]
@joeyparrish Do you want the parallel downloads tutorial as part of 2.3 or 2.4? I slotted the issue for the tutorial for 2.4.

**Comment by joeyparrish** [comment]
I will update the comment in the existing tutorial to note that parallel downloads are possible, but I will defer fully updating the tutorial to demonstrate that (#1196).
