### ISSUE TITLE
Support TTML forced captioning (itts:forcedDisplay)

### ISSUE THREAD

**Issue by kchandran1029** [google/shaka-player#1184]
Hi @joeyparrish ,

**Comment by joeyparrish** [comment]
A quick search of the code shows that this is not yet supported.  I've put it on the backlog for now, but we will consider this during our next planning phase in February.

**Comment by kchandran1029** [comment]
Thanks @joeyparrish . Make sense to de-prioritize since the standards are changing , but good to have to be backward compatible.

**Comment by avelad** [comment]
I think the standard says we should use https://github.com/google/shaka-player/issues/2122. This being at the TTML file level it is not possible to use it in the tracks, because it would imply that we must download all the subtitle tracks and see if they have this attribute.

**Comment by joeyparrish** [comment]
@avelad, you make a good point.  I have marked this with the "will not implement" label.
