### ISSUE TITLE
Add support for legacy H.264 codec strings

### ISSUE THREAD

**Issue by mrlika** [google/shaka-player#1186]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**: yes

**What version of Shaka Player are you using**: build from latest master

**Can you reproduce the issue with our latest release version**: TS streams are not supported there

**Can you reproduce the issue with the latest code from `master`**: yes

**Are you using the demo app or your own custom app**: using demo app

**If custom app, can you reproduce the issue using our demo app**:

**What browser and OS are you using**: Firefox & Chromium on Ubuntu (everything latest release versions)

**What are the manifest and license server URIs**: https://wowza.peer5.com/vod/mp4:avengers.mp4/playlist.m3u8
*(you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*

**What did you do?**
Trying to play this HLS/MPEG-TS/H.464/AAC stream. This stream plays well using hls.js and other players.

**What did you expect to happen?**
See the stream playing

**What actually happened?**
ERROR
Object { severity: 2, category: 4, code: 9009, data: [], handled: false, message: "Shaka Error MANIFEST.CONTENT_UNSUPPORTED_BY_BROWSER ()", stack: "shaka.util.Error@http://localhost:4546/lib/util/error.js:72:13\nshaka.Player.prototype.filterAllPeriods_@http://localhost:4546/lib/player.js:2066:11\nshaka.hls.HlsParser.prototype.parseManifest_/<@http://localhost:4546/lib/hls/hls_parser.js:304:5\n" }
main.js:611:3
Cannot play media. No decoders for requested formats: video/mp2t; codecs="avc1.100.42 mp4a.40.2"; width="1920"; height="800", video/mp4; codecs="avc1.100.42 mp4a.40.2"

**Comment by mrlika** [comment]
Just tested videojs with videojs-contrib-hls plugin (that AFAIK also uses mux.js) can play the stream:
https://jsfiddle.net/2h4Lmtv8/1/

**Comment by joeyparrish** [comment]
Chrome does not support the video codec ("avc1.100.42") specified in the manifest.

```js
MediaSource.isTypeSupported('video/mp4; codecs="avc1.100.42,mp4a.40.2"')
 => false

MediaSource.isTypeSupported('video/mp4; codecs="avc1.100.42"')
 => false
```

The hls.js demo converts this string into "avc1.64002a".  It's not clear how this conversion is done, or why the player should do it.

**Comment by joeyparrish** [comment]
Chrome has code for this conversion, but it is only enabled when the TS parser is enabled (which it isn't in standard Chrome builds).

https://github.com/scheib/chromium/blob/b03fc92a51679a4a04645614879bc8e3a2955e77/media/base/video_codecs.cc#L356

**Comment by joeyparrish** [comment]
Looks easy enough to add support for.  Shouldn't take long.
