### ISSUE TITLE
Crash if there is no EXT-X-MEDIA-SEQUENCE in live HLS stream

### ISSUE THREAD

**Issue by ivanovaleksey** [google/shaka-player#1189]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**: yes

**What version of Shaka Player are you using**: master branch

**Can you reproduce the issue with our latest release version**: yes

**Can you reproduce the issue with the latest code from `master`**: yes

**Are you using the demo app or your own custom app**: demo app

**What browser and OS are you using**: Chrome, mac OS

**What are the manifest and license server URIs**: I generated test live stream with FFmpeg locally

**What did you do?**
I used the packager to generate HLS for live stream.
First I run Shaka in Docker:
```
packager \
 'input=udp://0.0.0.0:5004,stream=video,init_segment=hls/video_init.mp4,segment_template=hls/video_$Number$.ts,playlist_name=video.m3u8' \
 'input=udp://0.0.0.0:5004,stream=audio,init_segment=hls/audio_init.mp4,segment_template=hls/audio_$Number$.ts,playlist_name=audio.m3u8' \
  --hls_master_playlist_output hls/playlist.m3u8 --hls_playlist_type LIVE
```

Then I run FFmpeg on host machine:
```
ffmpeg \
  -f lavfi -re -i "testsrc=duration=-1:size=1280x720:rate=30" \
  -f lavfi -re -i "sine=f=50:beep_factor=6" \
  -pix_fmt yuv420p \
  -c:v libx264 -preset:v ultrafast -profile:v high -level 3.1 -tune:v zerolatency -r 30 -g 60 -sc_threshold 0 \
  -c:a libfdk_aac -preset:a ultrafast \
  -f mpegts udp://$(docker-machine ip default):5004
```

**What did you expect to happen?**
I expected the stream to be played.

**What actually happened?**
I got the following error:
```
Shaka Error MANIFEST.HLS_MEDIA_SEQUENCE_REQUIRED_IN_LIVE_STREAMS ()
```

Previously I asked this question on [Google Group](https://groups.google.com/forum/#!topic/shaka-packager-users/iY-yvIusVcc).
> According to HLS spec https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#section-4.3.3.2:
> If the Media Playlist file does not contain an EXT-X-MEDIA-SEQUENCE
   tag then the Media Sequence Number of the first Media Segment in the
   Media Playlist SHALL be considered to be 0.  A client MUST NOT assume
   that segments with the same Media Sequence Number in different Media
   Playlists contain matching content - see Section 6.3.2.

It was supposed that it might a bug in the player.

Thank you.

**Comment by joeyparrish** [comment]
Confirmed.  It should be easy to fix.
