### ISSUE TITLE
DASH live stream starts at wrong time

### ISSUE THREAD

**Issue by boredom2** [google/shaka-player#1192]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**:
yes

**What version of Shaka Player are you using**:
2.2.8

**Can you reproduce the issue with our latest release version**:
we use the latest Version

**Can you reproduce the issue with the latest code from `master`**:
didnt try

**Are you using the demo app or your own custom app**:
both

**If custom app, can you reproduce the issue using our demo app**:
no

**What browser and OS are you using**:
chrome, FF, Edge

**What are the manifest and license server URIs**:
https://nx-p01.akamaized.net/c950b062-9407-4335-afc3-8cd3200c37ea/3c1d302a-9b71-4d38-a4cb-5d8a27c81302.ism/Manifest(format=mpd-time-csf) 
(this wont be alive forever)

**What did you do?**
load Manifest and wanted to playback

**What did you expect to happen?**
Stream starts

**What actually happened?**
We received a "stalled" Event from the underlying Video Object.

I know, this is not a Bug, we are doing something wrong obviously.
This is a DASH-LIVE-DVR Stream, which worked at the Beginning of the Stream fine in our Players. Now, 1.5 Hours later, we only get "stalled" and the Stream does not start - but it works fine in your Demo Player.
I am quite new to this Topic, so I suppose, in case of LIVE-DVR Stream, we maybe have to manually set the Start Point of the Stream ("NOW")? Is that true? Can you give me a Hint, how to set that? I couldnt find anything in the Docs for that (but I may have missed that).
Or is there any other Reason for the "stalled" Event happening (I can also see, that the Manifest gets called permanently, which results in a 304 Response from the Media Server).

Thanks!

**Comment by joeyparrish** [comment]
Actually, I'm not certain, but it looks like a bug.  With the latest code, it does not start up well.

It seems to start playback at the start of the seek range instead of the end, which makes me think we have a bug.

If I seek to the middle of the seek range, it will eventually start playing.  It won't play within the last few minutes of the seek range, which makes me think the stream is also drifting a bit.

I will investigate.  Thanks for the report, and the manifest link to reproduce it!

**Comment by boredom2** [comment]
Oh really?
Ok, I judt thought, I dont have enough Knowledge here...

But fine, Ill try to let the Stream on as long as possible...

As always, thanks a lot!

**Comment by joeyparrish** [comment]
It's pretty difficult to diagnose content issues, especially with live streams.  It's not your fault.  I wish live streaming were simpler.

**Comment by sandersaares** [comment]
http://dashif.org/conformance has some sort of dynamic manifest validator builtin - you might try that on your stream if you have not already. It shows up as a link if you feed it a dynamic manifest. I am not sure of its scope of features, however. Still, maybe it gives you some hints that enable further diagnostics. It seems to have trouble with your manifest when feeding a URL, though. When feeding the file as an upload, it reports some MPD validation errors.

@joeyparrish do you think there is anything in particular that could be done by whoever to make it easier to troubleshoot issues with live streams? I only recently started dealing with live and am fast running into difficulties in understanding behavior. As you say, it is pretty difficult. I wonder if you already have some thoughts on what could be the most "cost-effective" investments of effort for helping diagnose such issues? Could the DASH-IF conformance validator be amended to do more validation in some regard? Or would runtime diagnostics from players be more useful? What mechanisms do you use to understand such occurrences?

**Comment by joeyparrish** [comment]
There are a few common patterns of things that go wrong with DASH streams, and I generally follow the same mechanical steps to diagnose content issues.  Usually, we find either an issue with availabilityStartTime or some drift.

We have considered building tools for this, but have never found the time.  Ironically, had we done it a year ago, the time savings would have paid for itself by now.

**Comment by vaage** [comment]
@boredom2 is the stream down? If so, @joeyparrish how do you want to proceed with this?

**Comment by joeyparrish** [comment]
The "wrong start time" behavior can be reproduced with the DASH version of our live history stream, which is also suffering from drift.

**Comment by joeyparrish** [comment]
The stream does recover in less than a minute, and on seek.  So it may not be a severe issue.  The UI is confusing, though, since it shows a large negative number until startup succeeds.

**Comment by joeyparrish** [comment]
@boredom2, we haven't heard back from you in the past month, and we're unable to access the stream in your original report.  I'm going to close this issue now due to inactivity.  If/when you have time to look at this again and provide access to the stream, we would be happy to reopen the issue and investigate.  Thanks!
