### ISSUE TITLE
Expose a way to delete the entire storage database

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#1193]
Right now, we offer a way to delete individual pieces of stored content, but no option to drop the entire database.  For extreme situations (corruption) and to enable users to start clean, we should offer a way to delete everything.

We should include a test that ensures unexpected database versions and other forms of corruption do not prevent us from dropping the database and getting a clean slate.

**Comment by vaage** [comment]
Right now we have DBEngine.deleteDatabase which deletes the database. What is missing from that to meet the requirements of this issue?

**Comment by joeyparrish** [comment]
Some method on shaka.offline.Storage to call deleteDatabase through IStorageEngine.

**Comment by joeyparrish** [comment]
Plus new tests.

**Comment by vaage** [comment]
It would have to be on StorageEngineFactory as IStorageEngine would require you to create an instance of the database you are asking to delete.

**Comment by joeyparrish** [comment]
I believe this was solved by c168ee86ad61ae856d4d71cee6264622c151db91, which came out in v2.3.2.  We now have `Storage.deleteAll()`.
