### ISSUE TITLE
Player is not able to parse exponential notation e.g. PT1.28911e+06S

### ISSUE THREAD

**Issue by karlovich** [google/shaka-player#1202]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**:
yes
**What version of Shaka Player are you using**:
2.0.6, 2.2.2
**Can you reproduce the issue with our latest release version**:
yes
**Can you reproduce the issue with the latest code from `master`**:
yes
**Are you using the demo app or your own custom app**:
both
**If custom app, can you reproduce the issue using our demo app**:
yes
**What browser and OS are you using**:
Windows10, CHrome, MS Edge, etc
**What are the manifest and license server URIs**:
[Manifest.txt](https://github.com/google/shaka-player/files/1582424/Manifest.txt)

**What did you do?**
I have tried to play attached manifest

**What did you expect to happen?**
Successful playback

**What actually happened?**
Manifest is loading not-existing chunks.

Hi dear shaka dev team!

We have found rootcause of the issue: Media Packager provides the following Period:
<Period id="864525" start="PT1.28911e+06S">

And shaka player is not able to correctly parse such value - "PT1.28911e+06S"

This issue affects streaming for set of our LIVE manifests.

Are you going to support parsing of such exponential notation?

Best regards,

Sasha

**Comment by joeyparrish** [comment]
Is that actually valid XML?  I am having a hard time finding any examples of scientific notation in xml durations.  I haven't dug into the spec yet.

**Comment by joeyparrish** [comment]
XML durations seem to follow ISO 8601 duration format.  [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) has ABNF syntax of ISO 8601 durations in appendix A.  According to that, the seconds part is a string of digits, and does not allow for scientific notiation.

**Comment by karlovich** [comment]
@joeyparrish  Great thanks for the answer!
