### ISSUE TITLE
Live doesn't work in 2.2.9

### ISSUE THREAD

**Issue by theifish** [google/shaka-player#1204]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**: yes

**What version of Shaka Player are you using**: 2.2.9

**Can you reproduce the issue with our latest release version**: yes

**Can you reproduce the issue with the latest code from `master`**: yes

**Are you using the demo app or your own custom app**: demo app and custom app

**If custom app, can you reproduce the issue using our demo app**: yes

**What browser and OS are you using**: Win 10 Chrome

**What are the manifest and license server URIs**:
*(you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*

https://shaka-player-demo.appspot.com/demo/#asset=//vm2.dashif.org/livesim/utc_head/testpic_6s/Manifest.mpd;lang=ru

**What did you do?**

Load live stream and press play

**What did you expect to happen?**

Stream started

**What actually happened?**

Infinite loading indicator.
In console I see many errors like this:
 
segment_reference.js:83 Assertion failed: startTime must be less than endTime

Looks like something broken in new release.

**Comment by lucasdavila86** [comment]
I'm experiencing the same issue, under the same test conditions (custom app, demo app, chrome on W10 adding chrome on Ubuntu 16.04)

I've noticed that the manifest failing looks like this:
`
<?xml version="1.0" encoding="utf-8"?>
<MPD xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" type="dynamic" xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011 http://standards.iso.org/ittf/PubliclyAvailableStandards/MPEG-DASH_schema_files/DASH-MPD.xsd" maxSegmentDuration="PT4S" minBufferTime="PT4S" profiles="urn:mpeg:dash:profile:isoff-live:2011" availabilityStartTime="2014-01-01T00:00:15" publishTime="2014-01-01T00:00:15" minimumUpdatePeriod="PT4S" timeShiftBufferDepth="PT40S" xmlns="urn:mpeg:dash:schema:mpd:2011">
  <Period start="PT0.0S" id="1">
    <AdaptationSet mimeType="video/mp4" minBandwidth="1500000" maxBandwidth="6000000" segmentAlignment="true" startWithSAP="1">
      <ContentComponent id="1" contentType="video" />
      <SegmentTemplate initialization="Video$RepresentationID$.mp4" media="Video$RepresentationID$-$Number$.mp4" duration="4" startNumber="1" />
      <Representation id="0" bandwidth="6000000" codecs="avc1.4d401e" />
      <Representation id="1" bandwidth="1500000" codecs="avc1.4d401e" />
    </AdaptationSet>
    <AdaptationSet mimeType="audio/mp4" minBandwidth="64000" maxBandwidth="64000" segmentAlignment="true" startWithSAP="1">
      <ContentComponent id="1" contentType="audio" />
      <SegmentTemplate initialization="Audio$RepresentationID$.mp4" media="Audio$RepresentationID$-$Number$.mp4" duration="4" startNumber="1" />
      <Representation id="2" bandwidth="64000" codecs="mp4a.40.5" />
    </AdaptationSet>
  </Period>
</MPD>
`

**Comment by joeyparrish** [comment]
Confirmed.  Looks like for the DASH live sim, it's a bug in our SegmentTemplate parser that is causing segment end times to be screwed up.

**Comment by joeyparrish** [comment]
The bug was introduced in v2.2.9.  The fix, once published, will be cherry-picked for v2.2.10 and v2.3.1.

**Comment by joeyparrish** [comment]
Cherry-picked for v2.3.1.

**Comment by joeyparrish** [comment]
Cherry-picked for v2.2.10.
