### ISSUE TITLE
Support MP3 in HLS 

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#1210]
Sample:
http://wilma.betalounge.com/mod/_definst_/mp3:lounge/2005/050910_dsl_de.mp3/playlist.m3u8

Master playlist
> #EXTM3U
> #EXT-X-VERSION:3
> #EXT-X-STREAM-INF:BANDWIDTH=191998,CODECS="mp4a.40.34"
> chunklist_w680247602.m3u8

Media playlist

> #EXTM3U
> #EXT-X-VERSION:3
> #EXT-X-TARGETDURATION:10
> #EXT-X-MEDIA-SEQUENCE:0
> #EXTINF:10.0,
> media_w680247602_0.mp3
> #EXTINF:10.0,
> media_w680247602_1.mp3
> #EXTINF:10.0,
> media_w680247602_2.mp3
> #EXTINF:10.0,
> media_w680247602_3.mp3
> #EXTINF:10.0,
> media_w680247602_4.mp3
> #EXTINF:10.0,
> media_w680247602_5.mp3
> #EXTINF:10.0,
> media_w680247602_6.mp3
> #EXTINF:10.0,
> media_w680247602_7.mp3
> #EXTINF:10.0,
> media_w680247602_8.mp3
> #EXTINF:10.0,
> media_w680247602_9.mp3
> ....

According to https://tools.ietf.org/html/rfc8216#section-3.4 should be supported.

I know that now we should use aac, but there a lot of legacy content.

Sample:
https://shaka-player-demo.appspot.com/demo/#asset=http://wilma.betalounge.com/mod/_definst_/mp3:lounge/2005/050910_dsl_de.mp3/playlist.m3u8;lang=es
Note: enable mixed content

**Comment by joeyparrish** [comment]
Cherry-picked to v2.3.1.
