### ISSUE TITLE
player.isAudioOnly() is not working in HLS

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#1213]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**: YES

**What version of Shaka Player are you using**: master branch

**Can you reproduce the issue with our latest release version**: yes

**Can you reproduce the issue with the latest code from `master`**: yes

**Are you using the demo app or your own custom app**: Demo app

**What browser and OS are you using**: Chrome 63 / Ubuntu 17.10

**What are the manifest and license server URIs**:
*(you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*
http://wilma.betalounge.com/mod/_definst_/mp3:lounge/2005/050910_dsl_de.mp3/playlist.m3u8

**What did you do?**
Load the stream

**What did you expect to happen?**
Demo app shows a audio only poster

**What actually happened?**
Demo app doesn't show a audio poster

Note: with Dash stream, it works. Sample: http://storage.googleapis.com/shaka-demo-assets/dig-the-uke-clear/dash.mpd

**Comment by theodab** [comment]
Looks like a bug with my fix for issue #1210. The code which guesses if a stream is audio or video is misidentifying mp3 files as multiplexed audio-video streams.

**Comment by joeyparrish** [comment]
Cherry-picked to v2.3.1.
