### ISSUE TITLE
TS Assets are disabled in asset list

### ISSUE THREAD

**Issue by TheModMaker** [google/shaka-player#1214]
The TS assets from Bitcodin are disabled in the demo app.  This is caused by the support probe not detecting either the transmuxing or the presence of muxjs.  The support page doesn't show TS support even though we support it through transmuxing.  The assets are playable if I manually enter the URL or I remove the support check code.

On a related note, I see a bunch of 403 errors on preflight checks when I play the assets.  This doesn't stop playback though, since this is only for the start time calculations (I think).

**Comment by joeyparrish** [comment]
Fix cherry-picked for v2.3.4.
