### ISSUE TITLE
tile aggregation

### ISSUE THREAD

**Issue by fujunustc** [google/shaka-player#1219]
Does shaka-player support tile aggregation?

**Comment by vaage** [comment]
@fujunustc Could you clarify what you mean by tile aggregation?

**Comment by fujunustc** [comment]
Yep. for example, I divdie  a 1920x1080 video into 4 480x270 video using mp4box and then I aggregate the first and second 480x270 into a 960x540 video. This is also called SRD in mpeg dash protocol.

**Comment by joeyparrish** [comment]
Shaka Player does not support tile aggregation.  We just stream video to a video element using MediaSource.  If you want to stream 4 videos at once to 4 video elements, you can create 4 Shaka Player instances, but you will probably have issues keeping them synchronized.

Does that answer your question?

**Comment by fujunustc** [comment]
Thanks  a lot!

**Comment by joeyparrish** [comment]
Glad to help!
