### ISSUE TITLE
Starting playback from middle of the video.

### ISSUE THREAD

**Issue by sanbornhnewyyz** [google/shaka-player#122]
Is there an accepted way to begin playback not from the beginning of the video? For example let's say we want to bookmark a place in the video so we know that last time a user played they stopped playing at 30 seconds into the video. One way we could do this is add an event listener for 'loadedmetadata' and then set video.currentTime = 30. This works but there is a significant delay in starting playback when we do this vs letting it start from the beginning. It looks like it starts loading chunks from the beginning of the video regardless of where we set the time. Is there a way to dictate ahead of time that this is where we want to start, so just start getting junks from this point onward?

**Comment by tdrews** [comment]
There is currently no 'nice' way to do this since the stream start time is deduced from the "stream limits" in StreamVideoSource. We could add a method on Player to set the desired playback start time, when the stream starts we could just start from this time so long as it is within the stream limits.

**Comment by sanbornhnewyyz** [comment]
Great, this would be a very useful addition.

**Comment by sanbornhnewyyz** [comment]
Based on this short discussion I opened pull request #123 with a possible change.

**Comment by tdrews** [comment]
Closed via 03703f1a0c86e4b4ae987943dd4c4e41e9c30f80

**Comment by sanbornhnewyyz** [comment]
Based on the addition of the new configure() method, setPlaybackStartTime should get removed and handled by this configure() method, no?

**Comment by joeyparrish** [comment]
We discussed this yesterday internally, and decided that settings in configure() will not automatically be cleared, but setPlaybackStartTime should be reset between playbacks.  For example:

```player.setPlaybackStartTime(10);
player.load(source1);  // starts at 10s
// ... later ...
player.load(source2);  // starts at 0s
```

vs:

```player.setPlaybackStartTime(10);
player.load(source1);  // starts at 10s
// ... later ...
player.setPlaybackStartTime(30);
player.load(source2);  // starts at 30s
```

(Note that it isn't reset between playbacks *now*, but I planned to change that today.)

If you disagree on any of this, please let me know.  I would welcome your opinions on the matter.

Do you feel like start time should be cleared between playbacks?

Do you feel like setPlaybackStartTime should be replaced by a key in configure or should be independent?

**Comment by sanbornhnewyyz** [comment]
I ran into this today actually and I agree it should be reset between playbacks.

Is the idea that configuration persists across playbacks so anything that shouldn't persist will not go in the configure() method?

**Comment by joeyparrish** [comment]
That was my rationale, yes, but I could be convinced otherwise if this doesn't fit with your use-case.

**Comment by sanbornhnewyyz** [comment]
No I think that makes things clearer. As a temp workaround I was just setting playbackStartTime to null if I wanted to wipe out the previous one and just get the default but intuitively I think you're right that setting the start time should be a one time thing. 

I think all your rationale makes sense so I'll just leave it for the moment.

**Comment by joeyparrish** [comment]
Okay, then I'll re-open this and close it when I've fixed the start time to clear automatically.
