### ISSUE TITLE
Question for HLS URL Error

### ISSUE THREAD

**Issue by boredom2** [google/shaka-player#1221]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**:
yes

**What version of Shaka Player are you using**:
2.3.0

**Can you reproduce the issue with our latest release version**:
yes

**Can you reproduce the issue with the latest code from `master`**:
yes

**Are you using the demo app or your own custom app**:
both

**If custom app, can you reproduce the issue using our demo app**:
yes

**What browser and OS are you using**:
Chrome, Window s10

**What are the manifest and license server URIs**:

https://vcdn.hls.spiegel.de/1409/1175610/asset.ism/manifest.m3u8?dcp_ver=aos4&videostream=X8Y3IC11756105_320x180_400.mp4:400000,X8Y3IC11756105_640x360_700.mp4:700000,X8Y3IC11756105_720x404_900.mp4:900000,X8Y3IC11756105_1024x576_1500.mp4:1500000,X8Y3IC11756105_1280x720_2500.mp4:2500000,X8Y3IC11756105_1920x1080_4000.mp4:4000000,X8Y3IC11756105_1920x1080_6000.mp4:6000000&audiostream=X8Y3IC11756105_1920x1080_6000.mp4:6000000

**What did you do?**
trying to start this HLS Stream

**What did you expect to happen?**
it should start

**What actually happened?**
nothing :)

This HLS URL can be played by "native HLS-capable Devices" (like iPhone), but via Shaka, it does not work. I am no Expert in HLS Structure, but the Debug Log mentions "Shaka Error MANIFEST.HLS_REQUIRED_ATTRIBUTE_MISSING (URI)". What can I tell the CDN Provider to change in order to make this work with SHAKA (or is this a Bug?).

Thanks,
Christoph

**Comment by theodab** [comment]
It looks like this is a bug. We assume that EXT-X-MEDIA tags have an URI, but according to the HLS spec that field is optional.

**Comment by theodab** [comment]
Actually, looks like there's already an issue open for this. #1086. I'll close this one, then.
