### ISSUE TITLE
Register HttpPlugin for file:// for use in eg. electron

### ISSUE THREAD

**Issue by Cromefire** [google/shaka-player#1222]
~~**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for dublicates?**: yes~~

~~**What version of Shaka Player are you using**: jscdn from about one month ago~~

~~**Can you reproduce the issue with our latest release version**: Unless someone implemented it, no and I don't think so, but I don't tested it.~~

~~**Can you reproduce the issue with the latest code from `master`**: same as above~~

~~**Are you using the demo app or your own custom app**: A custom app~~

~~**If custom app, can you reproduce the issue using our demo app**: I can't test it in the demo app, because I use local files (but on a web server every thing works fine)~~

~~**What browser and OS are you using**: Electron with node v8 on Ubuntu artful~~

~~**What are the manifest and license server URIs**: it is a local file generated by Shaka packager from an mp4, it has no protection~~

~~**What did you do?**~~
~~I loaded the locally stored manifest (electron seemed to make file:// from it)~~

~~**What did you expect to happen?**~~
~~Shaka loads the manifest~~

~~**What actually happened?**~~
~~Shaka says, it can't load the manifest (1000)~~

#### Edit
Shaka doesn't know by default how to handle file:// requests as use in for example electron. Please register it by default.

**Comment by theodab** [comment]
A 1000 error is UNSUPPORTED_SCHEME. That means that we have no network plugin registered for the "file" scheme. I think our XMLHttpRequest plugin would work for it (assuming CORS doesn't become a problem, of course).

Try running this code when launching your app:
`shaka.net.NetworkingEngine.registerScheme('file', shaka.net.HttpPlugin, shaka.net.NetworkingEngine.PluginPriority.FALLBACK);`
That will register the XMLHttpRequest plugin to also handle file:// requests. Hope that helps.

**Comment by Cromefire** [comment]
I currently have some minor issues with my application, but it seems to be working.
How about registering it by default?

**Comment by Cromefire** [comment]
If anyone tells me, where the registering happens, I can do a PR.

**Comment by chrisfillmore** [comment]
@Cromefire take a look at `http_plugin`, at the bottom:

```
shaka.net.NetworkingEngine.registerScheme('http', shaka.net.HttpPlugin);
shaka.net.NetworkingEngine.registerScheme('https', shaka.net.HttpPlugin);
```

**Comment by theodab** [comment]
I have a CL for that change waiting on review.

**Comment by theodab** [comment]
Ok, we had a discussion about this internally, and decided to not make this an official part of Shaka Player. Browsers are our primary target, not Electron, and supporting requests to file:// would be inappropriate in a browser environment.
Instead, I will make an entry in the FAQ about this issue.

**Comment by joeyparrish** [comment]
The short version is: you can add this at the application level with one line after loading the Shaka library:

```js
shaka.net.NetworkingEngine.registerScheme('file', shaka.net.HttpPlugin);
```

We aren't doing this in the library because `file:` URIs are not accessible from web pages in a browser.  @theodab will update the FAQ with this info.

**Comment by joeyparrish** [comment]
Cherry-picked to v2.3.1.

**Comment by joeyparrish** [comment]
Cherry-picked for v2.2.10.

**Comment by theodab** [comment]
Note that, when #829 is out, the solution previously presented will stop working, as the XHR-based HttpPlugin now has a new name. At that point, you will want to instead use:
```
shaka.net.NetworkingEngine.registerScheme('file', shaka.net.HttpXHRPlugin);
```
#829 will also change the FAQ entry to match.
