### ISSUE TITLE
segment_reference.js:119 Assertion failed: startTime must be less than endTime

### ISSUE THREAD

**Issue by sandersaares** [google/shaka-player#1223]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**:
yes

**What version of Shaka Player are you using**:
v2.3.0

**Can you reproduce the issue with our latest release version**:
unknown

**Can you reproduce the issue with the latest code from `master`**:
unknown

**Are you using the demo app or your own custom app**:
demo app

**If custom app, can you reproduce the issue using our demo app**:
N/A

**What browser and OS are you using**:
Chrome 63 on Windows 10 v1709

**What are the manifest and license server URIs**:
URL currently unavailable, attaching manifest:

[Manifest.txt](https://github.com/google/shaka-player/files/1625996/Manifest.txt)

**What did you do?**

Press Load to start playing in the demo app.

**What did you expect to happen?**

Playback starts with no assertions, errors or warnings.

**What actually happened?**

I see the following assertion repeating in the console (quite a lot, seems like once a second at least) and playback does not start.

```
Assertion failed: startTime must be less than endTime
shaka.media.SegmentReference @ segment_reference.js:119
get @ segment_template.js:353
shaka.media.StreamingEngine.getSegmentReferenceIfAvailable_ @ streaming_engine.js:1339
shaka.media.StreamingEngine.getSegmentReferenceNeeded_ @ streaming_engine.js:1285
shaka.media.StreamingEngine.update_ @ streaming_engine.js:1154
shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:1051
setTimeout (async)
shaka.media.StreamingEngine.scheduleUpdate_ @ streaming_engine.js:2110
shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:1053
setTimeout (async)
shaka.media.StreamingEngine.scheduleUpdate_ @ streaming_engine.js:2110
shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:1053
setTimeout (async)
shaka.media.StreamingEngine.scheduleUpdate_ @ streaming_engine.js:2110
shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:1053
setTimeout (async)
shaka.media.StreamingEngine.scheduleUpdate_ @ streaming_engine.js:2110
shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:1053
setTimeout (async)
shaka.media.StreamingEngine.scheduleUpdate_ @ streaming_engine.js:2110
shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:1053
setTimeout (async)
shaka.media.StreamingEngine.scheduleUpdate_ @ streaming_engine.js:2110
shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:1053
setTimeout (async)
shaka.media.StreamingEngine.scheduleUpdate_ @ streaming_engine.js:2110
shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:1053
setTimeout (async)
shaka.media.StreamingEngine.scheduleUpdate_ @ streaming_engine.js:2110
shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:1053
setTimeout (async)
shaka.media.StreamingEngine.scheduleUpdate_ @ streaming_engine.js:2110
shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:1053
setTimeout (async)
shaka.media.StreamingEngine.scheduleUpdate_ @ streaming_engine.js:2110
shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:1053
setTimeout (async)
...
```

When this happens endTime is 0. This seems to be because periodDuration is null, so segment end time clipping produces 0. I am not familiar enough with Shaka logic to guess why periodDuration is null but indeed - the last period in the manifest does not have a fixed duration - it lasts forever - so it seems somwhat reasonable.

**Comment by joeyparrish** [comment]
I believe this is a duplicate of #1204, which we fixed on Dec 22.  The fix for #1204 is on the `master` branch and will be out in v2.3.1 in the very near future.

Can you please try again with the latest code from the `master` branch?  I can't check for you, because you didn't provide a manifest URI.  Thanks!

**Comment by sandersaares** [comment]
I confirm the issues does not appear to reproduce with the master branch!

The master branch also tries to download segments from 2066, though. I will see if I can get some URLs available to you and post a new issue about that (anything change in segment number calculations recently?).

**Comment by joeyparrish** [comment]
Excellent, thanks!
