### ISSUE TITLE
Assertion failed: SegmentReferences are incorrect

### ISSUE THREAD

**Issue by mhosman** [google/shaka-player#1226]
Hi, I have this live streaming and I get this error (stream work's ok but the console is displaying errors).
Assertion failed: SegmentReferences are incorrect (in uncompiled and debug).

* Tested with reference player:

https://shaka-player-demo.appspot.com/demo/#asset=https://lsp07.boldmss.com:5550/WARNER/WARNER.isml/WARNER.mpd;lang=es

**Comment by mhosman** [comment]
Solved. Just an error with the manifest.

**Comment by joeyparrish** [comment]
Thanks for letting us know!  Any details you can share with the rest of the community, in case anyone else has a similar issue?
