### ISSUE TITLE
[HLS] Add support for SAMPLE-AES-CTR and deprecate SAMPLE-AES-CENC

### ISSUE THREAD

**Issue by kqyang** [google/shaka-player#1227]
In latest [Widevine DRM for HLS spec](https://storage.googleapis.com/wvdocs/Widevine_DRM_HLS.pdf), SAMPLE-AES-CTR method replaces SAMPLE-AES-CENC method. We will add support for SAMPLE-AES-CTR and keep both methods around for some time. SAMPLE-AES-CENC will be deprecated in a future release.

**Comment by joeyparrish** [comment]
Cherry-picked to v2.3.1.

**Comment by joeyparrish** [comment]
Cherry-picked for v2.2.10.
