### ISSUE TITLE
Make default presentation delay for DASH configurable

### ISSUE THREAD

**Issue by bwallbergBonnier** [google/shaka-player#1234]
In `dash_parser.js` there is a hardcoded value that is used if `suggestedPresentationDelay` is missing from the manifest.
It will be used as long as it's bigger than `minBufferTime` * 1.5, this is a useful property to have configurable in the scenario where the stream provider either can't or won't provide the value desired by the developer.

**Comment by joeyparrish** [comment]
Sounds reasonable.  Thanks!

**Comment by joeyparrish** [comment]
Cherry-picked for v2.3.2.  Just barely missed the cut-off for v2.3.1.
