### ISSUE TITLE
Change NetworkEngine to use Blobs

### ISSUE THREAD

**Issue by vaage** [google/shaka-player#1243]
Blobs leave a smaller memory footprint as they are more like temp files. This makes it fast to move data between processes. We would like to change NetworkEngine to use Blobs instead of ArrayBuffers.

**Comment by joeyparrish** [comment]
See comments in https://github.com/google/shaka-player/issues/1244#issuecomment-359900982 and above.  I was wrong, and we will not do this after all.  Sorry for the confusion.
