### ISSUE TITLE
shaka did not correctly calculate first index of chunk to fetch.

### ISSUE THREAD

**Issue by DenisDashkevich** [google/shaka-player#1245]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**:
yes.

**What version of Shaka Player are you using**:
check 2.3.1 | 2.2.9 | master.

**Can you reproduce the issue with our latest release version**:
yes.

**Can you reproduce the issue with the latest code from `master`**:
yes.

**Are you using the demo app or your own custom app**:
both.

**If custom app, can you reproduce the issue using our demo app**:
yes.

**What browser and OS are you using**:
chrome(63.0.3239.132) | macOS High Sierra(10.13.2)

**What are the manifest and license server URIs**:
*(you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*
[manifest.txt](https://github.com/google/shaka-player/files/1659950/manifest.txt)

**What did you do?**
try to play live content

**What did you expect to happen?**
expect live playback starting

**What actually happened?**
actually shaka did not correctly calculate first index of chunk to fetch.
Correct first index for this manifest is 520617
but got 8979424
![image](https://user-images.githubusercontent.com/18233725/35335064-6e1f0a12-0125-11e8-9e13-a72ac40f26b5.png)

i did not dig deeper but i suppose problems in calculation position/startNumber which are passed to getUris func in SegmentReference
https://github.com/google/shaka-player/blob/master/lib/dash/segment_template.js#L347-L352

**Comment by joeyparrish** [comment]
@DenisDashkevich, please provide a manifest URI.  A copy of the manifest text is not enough to reproduce most issues, including this one.

**Comment by sandersaares** [comment]
I see presentationTimeOffset in the example manifest, so I bet this is the same as https://github.com/google/shaka-player/issues/1232 where PTO is incorrectly added to determine segment position. Behavior matches what I saw with my content (manifest position far in the future).

**Comment by DenisDashkevich** [comment]
@joeyparrish i sent message on this mail shaka-player-issues@google.com

**Comment by TheModMaker** [comment]
@DenisDashkevich #1232 has been fixed, can you please retest?

https://nightly-dot-shaka-player-demo.appspot.com/demo/

**Comment by DenisDashkevich** [comment]
Hi, it works pretty well. thanks!

2018-02-01 21:26 GMT+03:00 Jacob Trimble <notifications@github.com>:
