### ISSUE TITLE
Cast blob urls?

### ISSUE THREAD

**Issue by Jad3z** [google/shaka-player#1247]
Searching the internet did not answer my question, sorry if I'm in the wrong place here.
I got shaka player working with blob files, but I'm not able to cast this to my chromecast.
I'm wondering if this is even possible in the browser without extentions?

**Comment by joeyparrish** [comment]
If the Blob refers to something on your local computer, the Chromecast won't have access to it.  When you cast in Shaka, you are simply transferring the playback URI to the other device.  So it must be a URI that is accessible to the Chromecast.

Does this answer your question?

**Comment by TheModMaker** [comment]
@Jad3z Does that answer your question?  Do you need any more help?

**Comment by Jad3z** [comment]
It answered my question, I will close it.
