### ISSUE TITLE
We have customized licence verification. What is the best way to trap licence requests and provide responses in shaka.

### ISSUE THREAD

**Issue by krvangala** [google/shaka-player#1257]
We have customized licence verification. What is the best way to trap licence requests and provide responses in shaka.

**Comment by chrisfillmore** [comment]
If by "trap" you mean cancel the license request and provide a custom response, AFAIK there is no way to do this in Shaka. I have an open issue #1075 to allow the client to handle the license request, but it is pending Shaka team's approval of the design.

If you just need to customize the license request and process the response, you need to register networking filters:

https://shaka-player-demo.appspot.com/docs/api/tutorial-license-server-auth.html

**Comment by ismena** [comment]
@chrisfillmore Thanks for helping us address the questions! :)

@krvangala Is there anything else we can help you with? Do you need more information?

**Comment by krvangala** [comment]
our customized license verification is not based on direct http call. Has to call another API (async with callback) to get license.
to workaround for this. i have added following code in my app. it is working for me now. is there any better way to do this?

shaka.media.DrmEngine.prototype.sendLicenseRequest_ = function(event) {
  /** @type {!MediaKeySession} */
  var session = event.target;

  var activeSession;
  for (var i = 0; i < this.activeSessions_.length; i++) {
    if (this.activeSessions_[i].session == session) {
      activeSession = this.activeSessions_[i];
      break;
    }
  }
  var thisPtr = this;
  var drmType ="widevine";
  if(this.currentDrmInfo_.keySystem.indexOf("playready",0) != -1)
  	drmType = "playready";
  custom_license_request(drmType, event.message,function (data) {
    if (this.destroyed_) return Promise.reject();

        // Request succeeded, now pass the response to the CDM.
        return session.update(data).then(function()
         {
          var event = new shaka.util.FakeEvent('drmsessionupdate');
          thisPtr.playerInterface_.onEvent(event);

          if (activeSession) 
          {
            if (activeSession.updatePromise)
              activeSession.updatePromise.resolve();
            // In case there are no key statuses, consider this session loaded
            // after a reasonable timeout.  It should definitely not take 5
            // seconds to process a license.
            setTimeout(function() {
              activeSession.loaded = true;
              if (thisPtr.activeSessions_.every(function(s) { return s.loaded; }))
                thisPtr.allSessionsLoaded_.resolve();
            }.bind(this), 5000);
            
          }
   	});
   }.bind(this), function(error){
   // Ignore destruction errors
        if (this.destroyed_) return Promise.resolve();

       
        var shakaErr = new shaka.util.Error(
            shaka.util.Error.Severity.CRITICAL,
            shaka.util.Error.Category.DRM,
            shaka.util.Error.Code.LICENSE_REQUEST_FAILED,
            error);
        this.onError_(shakaErr);
        if (activeSession && activeSession.updatePromise)
          activeSession.updatePromise.reject(shakaErr);
      
   }.bind(this));
 
}

**Comment by TheModMaker** [comment]
If you're not using http, how about writing your own [scheme plugin](https://nightly-dot-shaka-player-demo.appspot.com/docs/api/shakaExtern.html#.SchemePlugin)?  You could look at the [HttpXhrPlugin](https://github.com/google/shaka-player/blob/master/lib/net/http_xhr_plugin.js) for an example.  For example, you could do something like:

```js
let MyScheme = function(uri, request, requestType) { ... };

shaka.net.NetworkingEngine.registerScheme('drm', MyScheme);
```

Then you could set the license server URL to `drm://my-custom-url`.

**Comment by joeyparrish** [comment]
@krvangala, were you able to make any progress with these suggestions?  Is there anything else we can do for you?

**Comment by krvangala** [comment]
@joeyparrish, i am planning to write own drm scheme plugin. it will take a while to start work on that.
mean while, i am exploring the stats provided  by shaka player.

**Comment by joeyparrish** [comment]
Okay.  I'll go ahead and close the issue for now.  If you need more help, just let us know, and we can reopen the issue.  Thanks!
