### ISSUE TITLE
Issue with getTextLanguagesAndRoles and getAudioLanguagesAndRoles in DemoApp

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#1258]
## NOTE: For bugs, if you delete this template, we will send it again and ask you to fill it out.

**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate open issues?**: Yes

**What version of Shaka Player are you using?**: 2.3.1

**Can you reproduce the issue with our latest release version?**: Yes

**Can you reproduce the issue with the latest code from `master`?**: Yes

**Are you using the demo app or your own custom app?**: Demo app

**If custom app, can you reproduce the issue using our demo app?**:

**What browser and OS are you using?**: Chrome 64 / Ubuntu 17.04

**What did you do?**

Load demo page in uncompiled mode and compiled mode

**What did you expect to happen?**
Track selector is not working (audio and text)

**What actually happened?**
Uncompiled mode
![image](https://user-images.githubusercontent.com/8983024/35502519-929e8dde-04dd-11e8-90a7-883bb4603cb2.png)

Compile mode
![image](https://user-images.githubusercontent.com/8983024/35502570-ace846ee-04dd-11e8-8467-d1760ba1c929.png)

Note: I think that the problem is getTextLanguagesAndRoles and getAudioLanguagesAndRoles, the spec saids that returns (non-null) {Array.<{language: string, role: string}>} and I see: 
[{"language":"en","vb":"main"},{"language":"fr","vb":""},{"language":"de","vb":""},{"language":"it","vb":""},{"language":"es","vb":""}]  and [{"language":"el","vb":""},{"language":"en","vb":"main"},{"language":"fr","vb":""},{"language":"pt-br","vb":""}]

**Comment by joeyparrish** [comment]
Fix cherry-picked for v2.3.2
