### ISSUE TITLE
Can't generate documentation

### ISSUE THREAD

**Issue by TheModMaker** [google/shaka-player#1259]
Trying to generate documentation using `build/docs.py` generates a large number of errors and doesn't generate anything.  This seems to be caused by the new ES6 syntax.  This means the nightly page no longer has the documentation page.  Also, for some reason, the errors in generation don't result in a non-zero exit code, so the scripts still "succeed".

**Comment by joeyparrish** [comment]
The latest jsdoc can parse ES6, but we would lose some of our customizations.  I will investigate what it would take to unfork jsdoc.  If we can, we will use jsdoc from npm instead of keeping a forked copy in the repo.

**Comment by joeyparrish** [comment]
I can't find an easy way to deal with the lack of error code when the existing jsdoc fails.  Executing latest jsdoc from npm, we do get a non-zero error code when it fails.

**Comment by joeyparrish** [comment]
Good news: new jsdoc is WAY faster.  On my workstation, building the docs went from about 35s with the old tools to about 5s with the new tools.  7x faster.

**Comment by joeyparrish** [comment]
Some of the code which triggers this has been cherry-picked to v2.3.x and must be patched up in that branch.  Otherwise, this issue will block v2.3.x releases.
