### ISSUE TITLE
HLS masterlist m3u8 with ts files ends up in error code 9009

### ISSUE THREAD

**Issue by aminasyeda** [google/shaka-player#1269]
Hi,

I am trying to load an .m3u8 master playlist with shaka player. Here are the details of the file:
`#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=8,BANDWIDTH=1453992,RESOLUTION=2880x1440,CODECS="avc1.4d0032,mp4a.40.2"
web1_h264_1510786297.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=8,BANDWIDTH=3208784,RESOLUTION=2880x1440,CODECS="avc1.4d0032,mp4a.40.2"
web2_h264_1510786500.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=8,BANDWIDTH=11904160,RESOLUTION=3840x1920,CODECS="avc1.4d0033,mp4a.40.2"
web4_h264_1510786910.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=8,BANDWIDTH=5948696,RESOLUTION=3840x1920,CODECS="avc1.4d0033,mp4a.40.2"
web3_h264_1510786704.m3u8`

Each of the above .m3u8 variant has .ts file. 

When I try to render this file with shaka player by giving the manifest url, it ends up in an error code 9009 which according to documentation says `When the manifest contains no period playable streams, it means the manifest is unsupported by the browser.` 

I have also tried to load the mux.js to make the .ts files play as mentioned in the FAQ.
I still get the same error code and the file doesn't play.
Interestingly, the same file plays on the shaka player demo site. 
Could you please advise what is missing here ?

## NOTE: For bugs, if you delete this template, we will send it again and ask you to fill it out.

**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate open issues?**: Yes

**What version of Shaka Player are you using?**: 2.3.1

**Can you reproduce the issue with our latest release version?**: Yes

**Can you reproduce the issue with the latest code from `master`?**: Yes

**Are you using the demo app or your own custom app?**: Both

**If custom app, can you reproduce the issue using our demo app?**: No

**What browser and OS are you using?**: Chrome/ Firefox on ubuntu

**What are the manifest URIs?**:
https://samsungvr.com/cdn/DM2nFvy1vr9/master_list.m3u8

**What did you do?**
Loaded a master_list.m3u8 file which refuses to load/play

**What did you expect to happen?**
The .m3u8 plays absolutely well on the shaka player demo site (https://shaka-player-demo.appspot.com/demo/#asset=https://samsungvr.com/cdn/_MtRTKk1C8O/master_list.m3u8;lang=en-US;build=debug_compiled) but doesn't play on my local app.

**What actually happened?**
It ended up in error code 9009.

**Comment by TheModMaker** [comment]
TS content is only supported when we have native support (e.g. on Edge or Chromecast) or when we have mux.js loaded.  My guess is that you didn't load mux.js correctly.  Be sure to load it into the global scope (on `window`) and make sure it is loaded before Shaka player is.  In the demo this is done using a `<script>` tag; if you are loading using a module loader or having your server combine/minify things you may not be exposing it correctly. You can see if it was loaded correctly by typing `window.muxjs` into the developer console.

Can you provide a link to your app so we can help debug?  You can send it privately to shaka-player-issues@google.com.

**Comment by aminasyeda** [comment]
@TheModMaker: Thank you so much for the response. Yes, it was with the mux.js not getting loaded properly in my module loader. Once I fixed it, it started to work. All good for now. Appreciate your help!
