### ISSUE TITLE
HLS: use video duration instead of using text duration

### ISSUE THREAD

**Issue by kqyang** [google/shaka-player#1271]
## NOTE: For bugs, if you delete this template, we will send it again and ask you to fill it out.

**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate open issues?**:

Yes.

**What version of Shaka Player are you using?**:

Latest public demo.

**Can you reproduce the issue with our latest release version?**:

Yes.

**Can you reproduce the issue with the latest code from `master`?**:

Yes.

**Are you using the demo app or your own custom app?**:

Demo app.

**If custom app, can you reproduce the issue using our demo app?**:

**What browser and OS are you using?**:

Chrome on Linux.

**What are the manifest and license server URIs?**:
*(NOTE: you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*
*(NOTE: a copy of the manifest text or an attached manifest will **not** be enough to reproduce your issue, and we **will** ask you to send a URI instead)*

https://storage.googleapis.com/wvtemp/kqyang/vtt6/bunny_vtt_master.m3u8

**What did you do?**

https://shaka-player-demo.appspot.com/demo/#asset=https://storage.googleapis.com/wvtemp/kqyang/vtt6/bunny_vtt_master.m3u8;lang=en-US;build=uncompiled

**What did you expect to happen?**

Total duration should be around 60 seconds. See the equivalent manifest in DASH, which is handled properly: https://shaka-player-demo.appspot.com/demo/#asset=https://storage.googleapis.com/wvtemp/kqyang/vtt6/bunny.mpd;lang=en-US;build=uncompiled.

**What actually happened?**

The total duration is about 10 seconds, which is based on the text duration.

v2.1.9 seems to work.

**Comment by TheModMaker** [comment]
Yep, looks like a bug.  Should be easy to fix, we just need to ignore text tracks when calculating the min stream duration.

**Comment by joeyparrish** [comment]
Cherry-picked for v2.3.3.
