### ISSUE TITLE
Storage.deleteAll does not free offline licenses 

### ISSUE THREAD

**Issue by vaage** [google/shaka-player#1277]
When clearing storage with Storage.deleteAll, offline licenses are not released.

**Comment by joeyparrish** [comment]
Cherry-picked for v2.3.8.

**Comment by joeyparrish** [comment]
This makes it impossible to wipe the database when it is corrupt or unusable.  This change will be reverted.

**Comment by joeyparrish** [comment]
To properly remove content, call `storage.remove()` on each of the stored contents.  Only use `deleteAll()` for a complete erasure of the database with no business logic.  The docs will be updated accordingly.
