### ISSUE TITLE
Assertion failed: Wrong error type in Player#load

### ISSUE THREAD

**Issue by chrisfillmore** [google/shaka-player#1278]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate open issues?**:
Yes

**What version of Shaka Player are you using?**:
Latest from master

**Can you reproduce the issue with our latest release version?**:
No

**Can you reproduce the issue with the latest code from `master`?**:
Yes

**Are you using the demo app or your own custom app?**:
Demo app

**What browser and OS are you using?**:
Chrome 63 on macOS

**What are the manifest and license server URIs?**:
Sintel 4k (multicodec, Widevine) but any content should do

**What did you do?**
Rewrite the manifest response in Charles Proxy with an HTTP error status

**What did you expect to happen?**
Load should fail with BAD_HTTP_STATUS error

**What actually happened?**
The error caught in Player#load is `undefined`, so `error instanceof shaka.util.Error` fails. I do not see this problem in v2.3.2, so I assume this is a bug in the new AbortableOperation error handling.

![screen shot 2018-02-06 at 10 13 58 am](https://user-images.githubusercontent.com/7190265/35866954-8c8c0d6e-0b26-11e8-9d4a-597951aa9d59.png)

**Comment by theodab** [comment]
It looks like this happens whenever the networking engine hits the max number of retry attempts, now.
