### ISSUE TITLE
No play, pause method in shaka.Player()

### ISSUE THREAD

**Issue by krvangala** [google/shaka-player#1285]
I have not found any play, pause methods in Shaka Player. How to call  pause or play or seek playback ?

**Comment by TheModMaker** [comment]
You can just use the normal HTML5 methods on the video.  For example, `video.play()` and `video.pause()`.  You can seek by setting the current time, `video.currentTime = 123`.  All the normal video methods and properties should work fine (except `src`).

**Comment by krvangala** [comment]
thank you!
