### ISSUE TITLE
Allow no-cors mode on Fetch

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#1286]
Fetch API allow use no-cors mode (https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch). Is it possible add it using a configuration param?

**Comment by chrisfillmore** [comment]
What is the use case for `no-cors`? This is what the [spec](https://fetch.spec.whatwg.org/) says:

> **"no-cors"** 
> Restricts requests to using CORS-safelisted methods and CORS-safelisted request-headers. Upon success, fetch will return an opaque filtered response.

**Comment by joeyparrish** [comment]
The "no-cors" mode is pretty restrictive:

Quoting [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Request/mode):
> `no-cors` — Prevents the method from being anything other than HEAD, GET or POST, and the headers from being anything other than simple headers. In addition, JavaScript may not access any properties of the resulting Response.

Quoting the spec on "[simple headers](https://fetch.spec.whatwg.org/#simple-header)":
> A CORS-safelisted request-header is a header whose name is a byte-case-insensitive match for one of:
> * `Accept`
> * `Accept-Language`
> * `Content-Language`
> * `Content-Type` and whose value, once extracted, has a MIME type (ignoring parameters) that is `application/x-www-form-urlencoded`, `multipart/form-data`, or `text/plain`

So "no-cors" mode precludes `Range` requests, which are frequently required for DASH VOD content.  It also would prevent us from reading responses, which means we would not be able to use response filters, TS-to-MP4 transmuxing, EMSG event support, or subtitle support.

In my estimation, "no-cors" mode is simply too restrictive for Shaka Player.  If you have a compelling reason to need it, we can reconsider.

**Comment by avelad** [comment]
I understand the problems, it is better not to implement it, you are right.
