### ISSUE TITLE
How to append buffers manually to shaka player

### ISSUE THREAD

**Issue by Er-rchydy** [google/shaka-player#1291]
I have fmp4 list of files created by FFMPEG, (` init.mp4, playlist0.m4s, playlist2.m4s, playlist3.m4s` ).
i send those file's buffer using Socket, i send first `init.mp4` buffer followed by `playlist0.m4s , playlist1.m4s ...` buffers.
i know i can use m3u8 url, but i'm looking if it's possible to feed those chunks to the player manually without m3u8 file.

**Comment by Er-rchydy** [comment]
@theodab 
Unfortunately i didn't understand, I'm a newbie, i notice some links but that's why i don't want to use manifest because i don't deal with links , i'm sending video data ( buffers ) directly from the server so there are no links involved, you will understand what i'm trying to do when you see client code i'm using:
`let socket = io();
var video = document.querySelector('video');
var mimeCodec = 'video/mp4; codecs="avc1.42E01E, mp4a.40.2"';
if ('MediaSource' in window && MediaSource.isTypeSupported(mimeCodec)) 
{
    var mediaSource = new MediaSource;
    video.src = URL.createObjectURL(mediaSource);
    mediaSource.addEventListener('sourceopen', function () {
            var mediaSource = this;
            var sourceBuffer = mediaSource.addSourceBuffer(mimeCodec);
           sourceBuffer.mode = 'sequence'; 
            sourceBuffer.addEventListener('updateend', function (_) { video.play().then(function() { }).catch(function(error) { }); });
            socket.on('broadcast', function (Buffer) {
                sourceBuffer.appendBuffer(Buffer);
            });
    });
} else {
    console.error('Unsupported MIME type or codec: ', mimeCodec);
}` 
You see, i'm sending buffer from the server every 10 seconds ( segments are 30 seconds each ) using `socket` , the code above works fine , but i want to use `shaka-player` instead of `html5 video`, so i'm looking how can i append buffers that i get from `socket` to `shaka-player`, if that makes sense . something like this:
`socket.on('broadcast', function (Buffer) {
        // feed the Buffer data to shaka-player
 });`

**Comment by theodab** [comment]
Ah, I had thought you meant you were loading all of the segments in advance and just wanted to play them as though they were a stream.

Well, Shaka Player has no built-in support for being fed buffers directly. Shaka Player does have a robust plugin interface, with which you could create support for your specific use-case. You would need to make a custom manifest parser and a custom network scheme plugin; you would be tricking Shaka Player into thinking it is playing a manifest and downloading segments from the internet when actually it is just being sent a series of buffers.

I do have to ask what you want out of Shaka Player though, in this case. It sounds like the wrong tool for this situation. A lot of Shaka Player's features wouldn't work if it is just being fed buffers at a fixed interval. ABR requires Shaka Player to be able to choose which buffers to request, Shaka Player's configurable buffering goal would mean nothing if it doesn't choose when to stop downloading, etc. So I'm not sure if adopting Shaka Player and writing the necessary plugins would actually be worth the effort for you.
