### ISSUE TITLE
Regression: Subtitles are not changed when they're invisible 

### ISSUE THREAD

**Issue by yairans** [google/shaka-player#1293]
## NOTE: For bugs, if you delete this template, we will send it again and ask you to fill it out.

**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate open issues?**:

**What version of Shaka Player are you using?**: 2.3.2

**Can you reproduce the issue with our latest release version?**: yes

**Are you using the demo app or your own custom app?**: demo

**What browser and OS are you using?**: Chrome 64/macOS High Sierra

**What are the manifest and license server URIs?**:
https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd

**What did you do?**
Load 
Turn on the CC button 
Verify the text language is English
Turn off the CC button 
Switch to another text language (French for example)
Turn on the CC button 
**What did you expect to happen?**
The captions should be in French
**What actually happened?**
The captions are still in English

**Comment by chrisfillmore** [comment]
I would not expect changing the audio language to change the subtitle language.

**Comment by theodab** [comment]
Reproduced. I'll look into it, thanks for the report.

**Comment by chambs** [comment]
Seems to work fine when rolling back a change at `player.js#onChooseStreams_` at the return statement.
Not sure what kind of problems this can bring though. From my tests so far, no side effects were found.

```javascript
  // Don't fire a tracks-changed event since we aren't inside the new Period
  // yet.
  // Don't initialize with text stream if the caption is not visible.
  // if (this.isTextTrackVisible()) {
  //   return { variant: chosenVariant, text: chosenTextStream };
  // } else {
  //   return { variant: chosenVariant, text: null };
  // }
  return { variant: chosenVariant, text: chosenTextStream };
```

**Comment by theodab** [comment]
I have a CL out for this. The problem was that we are trying to unload the text stream when captions are disabled, but we forgot to actually unload the text data from MediaSource. In that asset the entire video's captions are a single segment, so it never loads new text data.

**Comment by joeyparrish** [comment]
Cherry-picked for v2.3.3.
