### ISSUE TITLE
Create pssh block for Playready content protection elements

### ISSUE THREAD

**Issue by SemihGk** [google/shaka-player#1294]
Our content manifests only includes <mspr:pro> element in the content protection tags for Playready and <cenc:pssh> blocks are not existed. After some further investigation, I have found that pssh blocks in dash manifest are not mandotory although microsoft's cenc documentation suggests to put them as well [(DownloadPDF)](http://download.microsoft.com/download/7/7/6/7762455C-D254-4C84-BE17-16B0C60E31FD/MPEG%20DASH%20PlayReady%201.2%20-%202014-10-08.pdf) .  On the other hand, I have noticed that you only create initData to create MediaKeySession if pssh blocks exist in the manifest. That's why, MediaKeySession can be initiated only if 'encrypted' event is fired due to manifest does not pssh blocks. However, I found out that we can create pssh blocks from <ms:pro> elements. Please read this [article](http://go.buydrm.com/thedrmblog/advanced_encryption_techniques) . It explains very well how can we create it. Plus, I found a sample code block in [ExoPlayer](https://github.com/google/ExoPlayer/blob/e7c60a2a234ab11bc75335453a7836fef9509610/library/core/src/main/java/com/google/android/exoplayer2/extractor/mp4/PsshAtomUtil.java#L51) library. So, I prepared a fix which is based on that article and that code block. I will create a PR soon. 

As for why we need this, I provided a fix for #1094 . However, this fix does not work in Tizen platform. If stream starts during unencrypted content (although initial manifest has content protection blocks) , MediaKeySession cannot be initialized due to encrypted event is not fired. If session cannot be started before video start, Tizen TV cannot decode the stream when the encrypted content is started to stream.  Plus, no error occurs and stream becomes pixelated. Player just thinks it is playing fine. As I mentioned above, this is happening only in Tizen TV. That's why, we need to initialize media key session for every scenario. On the other hand, we still need to cover the case that we should need to initialize the drmEngine with initData if there is no content protection elements exist. I consider to create a phony initData to create a fake session, but I was not sure that would you be interested in adding this change for only Tizen platform. Please let me know your thoughts.

Please let me know if you need more information. Thank you.

**Comment by chrisfillmore** [comment]
FYI this is a duplicate of #484, which has #1010, but it looks like progress on that has stalled. May be worth looking at for reference.

**Comment by SemihGk** [comment]
Hmm, I have not noticed them. Thank you for sharing. Although it seems very similar to this ticket, I think there is a slight difference. From my understanding, that PR provide a mechanism to get the licenseUrl from ms:pro object and so, it won't need to configure shaka for licenseUrl. Unlikely, I need to create pssh to create MediaKeySession for my case. I hope I do not miss something?

**Comment by SemihGk** [comment]
After further discussions with Samsung, they prepared a fix for this issue and this fix is going to be released in May in their next firmware update. So, this workaround will be no longer necessary.
