### ISSUE TITLE
Pausing does not work with a negative playback rate

### ISSUE THREAD

**Issue by gonemad** [google/shaka-player#130]
This is reproducible on the test page http://shaka-player-demo.appspot.com/

Load a video with trick play enabled.  Press the rewind button and then hit the pause button.  The video will continue to rewind.

**Comment by tdrews** [comment]
Thanks for the report. We'll take a look.

**Comment by gonemad** [comment]
Just to let you know this bug is still present in 1.4.2.  The test page shows the behavior as well

**Comment by tdrews** [comment]
Thanks. I believe this should be fixed in 1.4.1. The regression is most likely from bc7b826e41e2cc96dbc2196d1924045489f35a74.
