### ISSUE TITLE
Uncaught BAD_HTTP_STATUS error in xhr.onload

### ISSUE THREAD

**Issue by chrisfillmore** [google/shaka-player#1302]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate open issues?**:
Yes

**What version of Shaka Player are you using?**:
Latest from master

**Can you reproduce the issue with our latest release version?**:
Did not test

**Can you reproduce the issue with the latest code from `master`?**:
Yes

**Are you using the demo app or your own custom app?**:
Demo app

**What browser and OS are you using?**:
Chrome 63 macOS

**What are the manifest and license server URIs?**:
Any demo content should do

**What did you do?**
Rewrite manifest response to HTTP error status

**What did you expect to happen?**
No uncaught errors

**What actually happened?**
Chrome logs an uncaught error.
<img width="731" alt="screen shot 2018-02-13 at 2 26 42 pm" src="https://user-images.githubusercontent.com/7190265/36183147-0ed19fc6-10fb-11e8-9150-e647a5cdaecb.png">

The failure is obscured by the fact that the sample app listens for `error` events from `window`. Unit tests aren't failing because promise-polyfill (used by promise-mock, per test/util/boot.js) catches otherwise uncaught exceptions and rejects the Promise in the test.

**Comment by theodab** [comment]
Yeah, that is definitely a problem with how I broke that code off into http_plugin_utils. Good job catching it.
