### ISSUE TITLE
Infer audio CODEC missing in HLS

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#1305]
With https://github.com/google/shaka-player/issues/805 the parser add default codecs for audio and video.

I have the next master playlist:
```
#EXTM3U
#EXT-X-VERSION:4
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio",NAME="unknown",LANGUAGE="spa",DEFAULT=YES,AUTOSELECT=YES,URI="a64000_spa/index.m3u8"
#EXT-X-STREAM-INF:BANDWIDTH=5064000,AUDIO="audio",CODECS="avc1.4d001f"
v5000000/index.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=5564000,AUDIO="audio",CODECS="avc1.4d001f"
v5500000/index.m3u8
```

Video codec is defined as `avc1.4d001f` but the audio codec is not defined and the parser identify the audio codec as `avc1.4d001f` and `audio/mp4` with this codec is not supported. 

Is possible infer audio CODEC missing? or is it possible to validate audio and video codec separately and default codec for each?

Note: The same stream works in hls.js.

**Comment by joeyparrish** [comment]
We have to infer a lot of things in HLS, unfortunately.  I'm not sure how complicated this will be, but we'll take a look.

**Comment by joeyparrish** [comment]
@avelad, can you provide sample content?  What is the actual audio codec in this case?  What are we meant to infer?

**Comment by avelad** [comment]
I cannot provide a sample content (is in our lab and it's not public)

The default codec detectd by ShakaPlayer is `avc1.42E01E,mp4a.40.2`. This is `avc1.42E01E` for video and `mp4a.40.2` for audio.

The master playlist is

```
#EXTM3U
#EXT-X-VERSION:4
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio",NAME="unknown",LANGUAGE="spa",DEFAULT=YES,AUTOSELECT=YES,URI="a64000_spa/index.m3u8"
#EXT-X-STREAM-INF:BANDWIDTH=5064000,AUDIO="audio",CODECS="avc1.4d001f"
v5000000/index.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=5564000,AUDIO="audio",CODECS="avc1.4d001f"
v5500000/index.m3u8
```

In the codecs attribute you can see `CODECS="avc1.4d001f"`. The video codec is `avc1.4d001f`. The audio codec is not defined.

The media playlist are TS segments.

My proposal is differenciate video codec by default and audio codec by default separately.

In the previous case, ShakaPlayer should use `avc1.4d001f` for video and `mp4a.40.2` for audio.

**Comment by avelad** [comment]
I think this case is a content error and should not be handled in the ShakaPlayer
