### ISSUE TITLE
Demo: HLS Live seek is not possible

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#1307]
Using https://shaka-player-demo.appspot.com/demo/#asset=//storage.googleapis.com/shaka-live-assets/player-source.m3u8;lang=es-419;build=uncompiled

Seek is not possible with HLS Live

[Shaka Player Demo.zip](https://github.com/google/shaka-player/files/1729110/Shaka.Player.Demo.zip)

**Comment by joeyparrish** [comment]
This is intended, and is consistent with built-in HLS support in Safari.

Can you give us some details on how you expected it to work?

**Comment by avelad** [comment]
I expect that works the same way that DASH.
We want offer to the user the same experiencie with DASH and HLS. We offer to the users a n-timeshift over live stream ( the same as Youtube, eg: https://www.youtube.com/watch?v=0tek2aa8hAQ)

https://shaka-player-demo.appspot.com/demo/#asset=//storage.googleapis.com/shaka-live-assets/player-source.mpd;lang=es-419;build=uncompiled

[Shaka Player Demo.zip](https://github.com/google/shaka-player/files/1729189/Shaka.Player.Demo.zip)

**Comment by joeyparrish** [comment]
We can probably make this configurable, and make it apply to all live streams (DASH & HLS).  By default, we would allow seeking to any segment we know about.  The other option would be to disallow live stream seeking, as we do today for HLS live.

**Comment by theodab** [comment]
You should be able to seek in HLS live streams now. Just set the `manifest.availabilityWindowOverride` configuration to an appropriate value before loading the stream.

**Comment by avelad** [comment]
hi @theodab 

it's not working as expected, how can you knowWindow by default in HLS? with the new configuration I can only set a value if the value it's know by the application, but the real availabilityWindow is already included in the stream

By default the behavior it's the same as in previous releases (eg 2.4.2) and the default behavior is different to DASH.

**Comment by theodab** [comment]
Well, in that case, you should wait on #999.
That issue is currently blocked, awaiting other refactors, but it's also in the 2.5 milestone so you won't be waiting forever.

**Comment by avelad** [comment]
Hi @joeyparrish,

I just tested with Infinity and I get more range than declared in the playlist. This does not work for an EVENT playlist (startover funcionality) because the start is a known value, but the duration change in each update.

I attach a video with the test.
[Issue-1307.zip](https://github.com/google/shaka-player/files/2204632/Issue-1307.zip)

**Comment by joeyparrish** [comment]
I think this feature is not working correctly.  I will reopen and investigate.

**Comment by joeyparrish** [comment]
The override set by the player after the initial manifest is parsed is wiped when a live manifest is updated.

**Comment by joeyparrish** [comment]
@avelad, can you please try again with the latest code?  I believe we have fixed the issue.

**Comment by avelad** [comment]
I found thaht it's not possible configure availabilityWindowOverride = Infinity in Demo page, is it possible add Infinity value?

**Comment by joeyparrish** [comment]
That's a limitation of `<input type=number>`.  You could use a sufficiently large number in the demo, such as 9999999999 (larger than the current Unix time in seconds).

**Comment by TheModMaker** [comment]
@joeyparrish I would think there would be three distinct use cases for this setting:

1. Not setting anything: Non-seekable HLS and using `timeShiftBufferDepth` for DASH.
1. Setting `availabilityWindowOverride`: Using that value to indicate the time that segments remain alive for and determining the seek range.
1. Using #999: The segments that appear in the latest manifest determine the seek range.

So setting to Infinity would mean (to me) to be all segments are available forever, similar to not having a `timeShiftBufferDepth` in DASH.  If I am wrong, how do you see setting to Infinity being different than #999?

**Comment by joeyparrish** [comment]
@TheModMaker, you are right.  For HLS, there is no difference between a window override of `Infinity` and my plans for #999.  For DASH, it is a bit different.  Until #999 is solved, the DASH live edge is based on `availabilityStartTime`, not the segment list.  For HLS, it is already based on the segment list.

**Comment by theodab** [comment]
Okay, with that change, setting availabilityWindowOverride to Infinity (or some other arbitrary large value) should now properly set the start time on an HLS livestream.

**Comment by avelad** [comment]
I just tested and everything works as expected. Thanks!!
