### ISSUE TITLE
Playback of some static MPD doesn't automatically start in Chrome, possibly due to floating point error in MSE interface

### ISSUE THREAD

**Issue by albertcsm** [google/shaka-player#1309]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate open issues?**: Yes

**What version of Shaka Player are you using?**: v2.3.2

**Can you reproduce the issue with our latest release version?**: Yes

**Can you reproduce the issue with the latest code from `master`?**: Yes

**Are you using the demo app or your own custom app?**: Demo app

**What browser and OS are you using?**: Chrome, Windows or Linux

**What are the manifest and license server URIs?**: Attached manifest

**What did you do?** Load static asset

**What did you expect to happen?** Playback automatically start after load

**What actually happened?** Need manual seek to start playback

I loaded a static MPD in Shaka player in Chrome and expect it to automatically start playing.
But the loading indicator keep spinning, and console logs showed that it keep attempting gap-jumping to 0.062633s.
![image](https://user-images.githubusercontent.com/2263504/36417079-e807b16c-1665-11e8-9249-35d122715601.png)

I need to do a manual seek on the seek bar to get the MPD playing.

Chrome's media-internal page showed that the seek_target was at 0.062632s, instead of 0.062633s
![image](https://user-images.githubusercontent.com/2263504/36417212-3fd8e29e-1666-11e8-8060-7204003514f0.png)

The issue can only be reproduced in Chrome, but not Firefox, and happenens on both Windows and Linux.

I tried adding a small number to the gap-jumping code in "playhead.js", and the problem seems resolved:
`this.movePlayhead_(currentTime, jumpTo);`
to `this.movePlayhead_(currentTime, jumpTo + Number.EPSILON);`

So I think the issue is likely due to floating-point precision in the MSE interface of Chrome.

**Comment by albertcsm** [comment]
Here is a sample asset:
[DASH.zip](https://github.com/google/shaka-player/files/1739592/DASH.zip)

**Comment by ismena** [comment]
Hi @albertcsm, thanks for the investigative work you put into this!

@TheModMaker could I ask you to take a quick look and say whether you think there might be more to this in terms of our gap-jumping logic? If not, I'll be happy to follow the floating-point precision lead.

**Comment by TheModMaker** [comment]
It seems weird that the browser would says that 0.062633 is buffered, but when we seek to it, it puts us at 0.062632.  Maybe this is a browser bug.  You may want to file a bug on Chrome.

But we should still not get stuck in infinite loops like this.  We can just ignore extremely small gaps since the browser should ignore them anyway.

**Comment by joeyparrish** [comment]
Cherry-picked for v2.3.3.
