### ISSUE TITLE
Single segment download failure is fatal

### ISSUE THREAD

**Issue by jonoward** [google/shaka-player#131]
Prior to 1.4, a single segment download failure (i.e. a rejected promise out of RangeRequest) would be retried in Stream.onUpdate. In 1.4 (and latest master) I notice this doesn't seem to be the case. From what I can see it looks like SourceBufferManager.fetch does not reject it's promise if the RangeRequest promise is rejected. I think it's because a rejected promise triggering the "catch" in Task.startNextStage_ is swallowed (only when task is aborted is the promise rejected). So I think SourceBufferManager.fetch is left hanging, with neither resolve of reject funcs being fired. Not 100% sure if my diagnosis is correct though.

I can repro it on http://shaka-player-demo.appspot.com/ , by blocking a segment request just once - this stops future requests from executing, and then player eventually enters a permanent buffering state.

**Comment by tdrews** [comment]
Thanks for the report. I have a repro. I'll take a look.

**Comment by tdrews** [comment]
We should have a patch up soon.

**Comment by jonoward** [comment]
Great, thanks @tdrews, this resolves the issue for us
