### ISSUE TITLE
Subtitles aren't being displayed

### ISSUE THREAD

**Issue by ismena** [google/shaka-player#1314]
Reproes on a nightly build in Firefox & Chrome (at least).

**What did you do?**
Load _Angel One_, click the caption button.

**What did you expect to happen?**
Subtitles are displayed.

**What actually happened?**
No subtitles.

**Comment by joeyparrish** [comment]
With the nightly build?  Or a release version?

**Comment by ismena** [comment]
Nightly. I noticed on the latest master than checked the demo page and nightly build.
https://shaka-player-demo.appspot.com/demo is okay, https://nightly-dot-shaka-player-demo.appspot.com/demo/ isn't.

**Comment by ismena** [comment]
This is a regression introduced by I61acedd95d73610d3e67436d9c7767d643fe2d29: MediaSource is being created before the text displayer is set, which results in not having a text displayer at playback time.
