### ISSUE TITLE
Safari subtitle toggling delayed

### ISSUE THREAD

**Issue by DanDeMicco** [google/shaka-player#1316]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate open issues?**:
yes
**What version of Shaka Player are you using?**:
2.3.2
**Can you reproduce the issue with our latest release version?**:
yes
**Can you reproduce the issue with the latest code from `master`?**:

**Are you using the demo app or your own custom app?**:
demo
**If custom app, can you reproduce the issue using our demo app?**:
yes 
**What browser and OS are you using?**:
safai 11 mac osx 10.12.6
**What are the manifest and license server URIs?**:

*(NOTE: you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*
*(NOTE: a copy of the manifest text or an attached manifest will **not** be enough to reproduce your issue, and we **will** ask you to send a URI instead)*

**What did you do?**
Opened a video with subtitles in safari, with subtitles were disabled. Scrubbed to a point where subtitles should be and will appear for a few seconds, and paused video. Toggled subtitles on.

**What did you expect to happen?**
Subtitles should appear instantly when toggled, like chrome does, or at least after clicking play

**What actually happened?**
The subtitles did not appear, and noticed the subtitles did not appear for a few seconds, until the next subtitle appeared.

**Comment by joeyparrish** [comment]
Repro steps:

1. Visit https://shaka-player-demo.appspot.com/demo/#asset=//storage.googleapis.com/shaka-demo-assets/sintel-mp4-only/dash.mpd;lang=en-US;play;build=uncompiled
2. video.pause();
3. video.currentTime = 210;
4. shakaDemo.localPlayer_.setTextTrackVisibility(true);

Subs should appear right away, and they do in Chrome 64 on Linux.

**Comment by joeyparrish** [comment]
Works on Safari 11.0.3 (13604.5.6) on macOS High Sierra.

@DanDeMicco, I'm unable to reproduce this issue with the steps I detailed.  Is this still an issue for you?  Are there some different steps that you are following?

**Comment by DanDeMicco** [comment]
@joeyparrish here is a repro based off your script:

Repro steps:

Visit https://shaka-player-demo.appspot.com/demo/#asset=//storage.googleapis.com/shaka-demo-assets/sintel-mp4-only/dash.mpd;lang=en-US;play;build=uncompiled

```javascript
video.pause();
video.currentTime = 210;
shakaDemo.localPlayer_.setTextTrackVisibility(true);
setTimeout(function(){
    shakaDemo.localPlayer_.setTextTrackVisibility(false);
}, 1000);
setTimeout(function(){
    shakaDemo.localPlayer_.setTextTrackVisibility(true);
}, 2000);
```


Another interesting bug which came up (intermittent 25-50%), subtitles appear twice in safari
<img width="401" alt="screen shot 2018-02-26 at 2 29 30 pm" src="https://user-images.githubusercontent.com/661216/36699590-fb7882d0-1b01-11e8-9406-200d51184679.png">

```javascript
video.play();
video.pause();
video.currentTime = 210;
shakaDemo.localPlayer_.setTextTrackVisibility(true);
setTimeout(function(){
    shakaDemo.localPlayer_.setTextTrackVisibility(false);
    shakaDemo.localPlayer_.setTextTrackVisibility(true);
}, 100);
```

**Comment by joeyparrish** [comment]
I can reproduce the issue with v2.3.2, but not with v2.3.3 (released yesterday).  Can you try this newer release?

**Comment by DanDeMicco** [comment]
@joeyparrish seems to be resolved in latest release! Thanks for looking into it. Closing the issue

**Comment by joeyparrish** [comment]
No problem.  Happy to help!
