### ISSUE TITLE
Shaka silently fails time synchronization if time server returns timestamp that cannot be parsed

### ISSUE THREAD

**Issue by TheJohnBowers** [google/shaka-player#1317]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate open issues?**:
Yes
**What version of Shaka Player are you using?**:
Master
**Can you reproduce the issue with our latest release version?**:
I didn't try it, I figure master is current enough.
**Can you reproduce the issue with the latest code from `master`?**:
Yes
**Are you using the demo app or your own custom app?**:
Demo App
**If custom app, can you reproduce the issue using our demo app?**:

**What browser and OS are you using?**:
Chrome
**What are the manifest and license server URIs?**:
  'https://content-duswqa1.downlynk.com/channel/0da2e2615f6a413f9717d6a27859eb63.mpd'

**What did you do?**
My time server wasn't exposing the 'date' header, so it wasn't there when shaka did the time synchronization.  

**What did you expect to happen?**
If the UTCTiming element is completely missing, shaka warns about that.  If it isn't missing, but just returns unparseable data then there is no warning.

**What actually happened?**
Silent failure to timesync

**Comment by joeyparrish** [comment]
@TheJohnBowers, this fails to play for me at all.  What particular commit of Shaka Player are you using?

**Comment by joeyparrish** [comment]
I'm getting failed assertions in StreamingEngine with the content you linked to.

**Comment by joeyparrish** [comment]
Cherry-picked for v2.3.3.
