### ISSUE TITLE
'seeked' event is being sent on playback start

### ISSUE THREAD

**Issue by victep** [google/shaka-player#132]
'seeked' event is being sent after 'timeupdate' event every time I start playback. 

1. Seek event should not be sent if position is 0. 
2. Seek event should be sent only if setPlaybackStartTime was set to >0 position 
3. Seek event should be sent BEFORE timeupdate event

Reproduced on version: 1.4.0

Thanks!

**Comment by tdrews** [comment]
Thanks for the report. This is likely a side-effect of our "timestamp correction" mechanism. However, if the stream starts at 0 and the timestamp correction is 0 then we should be able to forego any initial seek. I'll take a look.
