### ISSUE TITLE
Could Shaka do clock synchronization at a configurable interval?

### ISSUE THREAD

**Issue by chrisfillmore** [google/shaka-player#1321]
Our content teams are working to add UTCTiming to our live manifests. There is a question of how frequently the player will make requests to the clock sync server. From what I can tell, Shaka will make a request for every manifest which contains UTCTiming (which I believe will be every manifest).

I am guessing that the offset value is unlikely to deviate substantially from one manifest to the next, and since PresentationTimeline stores the offset value, perhaps Shaka is making unnecessary requests. I wonder if there's an opportunity for optimization here, if the client app could configure how often Shaka should update the offset.

Would Shaka be willing to accept such a feature? Thanks.

**Comment by joeyparrish** [comment]
Sounds reasonable.  What do you think the configuration would look like?

**Comment by chrisfillmore** [comment]
How about a new property on shakaExtern.DashManifestConfiguration:

```
@property {number} minClockSyncInterval
The length of time, in seconds, that Shaka will wait in between clock synchronization requests. Set to 0 by default, meaning the player will perform clock sync with every manifest request.
```

**Comment by joeyparrish** [comment]
Sounds good to me.  Thanks!

**Comment by chrisfillmore** [comment]
I may have made a mistake, and missed something before. DashParser#processManifest_ does this:

```
...
if (this.manifest_) {
  // This is a manifest update, so we're done.
  return Promise.resolve();
}

// This is the first manifest parse, so we cannot return until we calculate
// the clock offset.
let timingElements = XmlUtils.findChildren(mpd, 'UTCTiming');
...
```

So the player will only do clock sync once, for the first manifest? If that's the case then I don't need a configurable interval.

**Comment by joeyparrish** [comment]
Yes, that's right.  We only do it once, on the assumption that your clock won't signficantly desync over the course of one playback session.

**Comment by chrisfillmore** [comment]
Ok my bad, I totally missed that and thought it was updating with every manifest request.

**Comment by joeyparrish** [comment]
No worries.  I didn't remember that it worked that way, and I didn't check when you proposed the change.
