### ISSUE TITLE
Policy on let/const

### ISSUE THREAD

**Issue by chrisfillmore** [google/shaka-player#1322]
I noticed this in the [commit messages](https://github.com/google/shaka-player/commit/61fc107be38c115ca07edb586bddcd3a94975492) for switching over to let/const:

```
This takes a conservative approach for 'const' where
it will only be used for aliases and storing the "original" values in
tests.
```

I find this policy a bit confusing. In our code, `let` is an indication that that identifier is reassigned at some point. Everything else must be `const`. The Google style guide has the [same policy](https://google.github.io/styleguide/jsguide.html#features-use-const-and-let):

> **5.1.1 Use const and let**
> Declare all local variables with either const or let. Use const by default, unless a variable needs to be reassigned. The var keyword must not be used.

Any reason for the deviation? I think not using `const` by default creates a lot of mental overhead.

**Comment by joeyparrish** [comment]
No, you correctly understand the policy.  But when we were getting rid of "var" by using a massive "sed" script, "let" was safer.  So the times you see "const" today, those were done by hand.  Most of the "let" you see today were written by a regex.

We followed an outdated, pre-ES6 style guide until we started incorporating ES6 into our project.  We are still transitioning in terms of style.

**Comment by chrisfillmore** [comment]
Oh great, thanks for clarifying. So if I am contributing new code, I will follow the Google style guide.
