### ISSUE TITLE
Different track bitrates between browsers

### ISSUE THREAD

**Issue by hghazzi** [google/shaka-player#1327]
## NOTE: For bugs, if you delete this template, we will send it again and ask you to fill it out.

**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate open issues?**:

Yes

**What version of Shaka Player are you using?**:

v2.3.2

**Can you reproduce the issue with our latest release version?**:

Yes

**Can you reproduce the issue with the latest code from `master`?**:

**Are you using the demo app or your own custom app?**: Both

**If custom app, can you reproduce the issue using our demo app?**: Yes

**What browser and OS are you using?**:

Mac High Sierra 10.13.3
Chrome 64
Safari 11
Firefox 58

**What are the manifest and license server URIs?**:
*(NOTE: you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*
*(NOTE: a copy of the manifest text or an attached manifest will **not** be enough to reproduce your issue, and we **will** ask you to send a URI instead)*

Angel One: https://shaka-player-demo.appspot.com/demo/#asset=//storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd;lang=en-US;build=uncompiled

Azure Trailer: https://shaka-player-demo.appspot.com/demo/#asset=//amssamples.streaming.mediaservices.windows.net/91492735-c523-432b-ba01-faba6c2206a2/AzureMediaServicesPromo.ism/manifest(format=mpd-time-csf);lang=en-US;build=uncompiled

**What did you do?**

Play the stream

**What did you expect to happen?**

For the Angel One stream, when selecting the video+audio track combo in the demo page, I would expect the bitrates of each track to be the same or at least similar to each other in Safari, Firefox, Chrome

**What actually happened?**

The bitrates between Safari and Firefox are similar, but Chrome is pretty different. See attached screenshots

**Chrome**
<img width="678" alt="screenshot 2018-02-28 16 27 51" src="https://user-images.githubusercontent.com/584053/36814846-cdeb425c-1ca6-11e8-90a8-5025880831cd.png">

**Safari**
<img width="547" alt="screenshot 2018-02-28 16 28 08" src="https://user-images.githubusercontent.com/584053/36814847-cdf903ba-1ca6-11e8-8da0-aaaba4bce8a1.png">

**Comment by joeyparrish** [comment]
On Chrome, the VP9 streams are selected over the H.264 streams, because the VP9 streams have a lower bitrate.  This is a feature of Shaka Player's multicodec content support.

On Safari, VP9 is not available, so we fall back to H.264.  Compared to VP9, H.264 requires a higher bitrate to achieve the same visual quality.

If you try any non-multicodec content, you will see consistent bitrates across browsers.

Does this help?

**Comment by hghazzi** [comment]
@joeyparrish Yes, thanks for the clarification!
