### ISSUE TITLE
Memory leak while processing webvtt resulting in a crash

### ISSUE THREAD

**Issue by jigneshdhruv** [google/shaka-player#1329]
We are using Shaka Packager version: 594d1f0-release

We came across a issue where shaka packager leaks memory while processing a webvtt file for HLS. We do not see this issue when processing the same webvtt with DASH.

Also this does not happen with all webvtt files.

This happened on a ubuntu server that has 64GB memory and shaka packager process took up all 64GB and then crashed.

We are trying to be very careful with our webvtt but we are worried that a bad webvtt can cause a memory leak and crash the process/server.

Here is the package command to reproduce the problem.
packager 'in=/tmp/abc.vtt,stream=text,segment_template=/tmp/output/abc/seg_$Number$.vtt,language=en,playlist_name=abc/stream_vtt.m3u8,hls_group_id=abc_vtt,hls_name=ENGLISH' --clear_lead 0 --segment_duration 6 --hls_master_playlist_output tmp/output/master.m3u8

I have send the bad webvtt file that caused memory leak to @kqyang .

Can you please take a look and let us know what is causing this memory leak?

Let us know if you need more information.

Thanks & Regards,
Jignesh

**Comment by joeyparrish** [comment]
I believe you've filed this bug on the wrong repository.  This is Shaka Player.  I think you want the Shaka Packager repo: https://github.com/google/shaka-packager/issues/new
