### ISSUE TITLE
Does this player support LG WebOS TV for DASH&playready combination?

### ISSUE THREAD

**Issue by kingctan** [google/shaka-player#1330]
Does this player support LG WebOS TV for DASH&playready combination?
Thanks.

**Comment by chrisfillmore** [comment]
I don't think that Shaka team has investigated this platform specifically. Generally speaking, Shaka supports any platform that is spec-compliant, but in my experience these kinds of smart TV platforms are not very mature and require extensive testing, validation, and workarounds. Things are getting better, though.

We will soon be investigating LG WebOS for DASH-PR, so you may soon see tickets related to this platform, and you'll get a better sense for whether or not Shaka will work on these TV's.

**Comment by joeyparrish** [comment]
We have never tested Shaka Player on this platform, but you can help by running our support page and sending a screenshot:  https://shaka-player-demo.appspot.com/support.html

This will tell us whether or not the platform has the basic capabilities we need, and if so, what specific containers, codecs, and DRM systems it has.

**Comment by avelad** [comment]
We are using ShakaPlayer with WebOS 3.5 and DASH+Widevine without any problem.

**Comment by ismena** [comment]
@kingctan Does this answer your question? Is there anything else we can do?

**Comment by chrisfillmore** [comment]
@ismena I have a question. It seems there are at least 3 projects using Shaka on LG WebOS: @kingctan, @avelad, and me. Would Shaka team be willing to adopt this as an officially supported platform?

**Comment by avelad** [comment]
@chrisfillmore , What versions of WebOS have you tried? I only tried WebOS 3.5.

**Comment by ismena** [comment]
Let's get our TL to consider it!
@joeyparrish

**Comment by joeyparrish** [comment]
If you can send us some documentation on WebOS testing, we could consider adding a WebOS device to our test lab.  We can't call it an officially supported platform until we are running tests on it nightly to make sure we don't break it.  But in general, expanding our platform coverage is a Good Thing:tm:.

In particular, we would appreciate any tips on how to automate directing the device to an arbitrary URL.  That's a key part of the testing process with Karma.

**Comment by chrisfillmore** [comment]
@shaka-bot reopen please

Here is the Shaka support page for the WebOS TV I have:

```
Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.122 Safari/537.36 WebAppManager
v2.3.6

{
  "manifest": {
    "application/dash+xml": true,
    "application/x-mpegurl": true,
    "application/vnd.apple.mpegurl": true,
    "application/x-offline-manifest": true,
    "mpd": true,
    "m3u8": true,
    "application/vnd.ms-sstr+xml": false,
    "ism": false
  },
  "media": {
    "video/mp4; codecs=\"avc1.42E01E\"": true,
    "video/mp4": true,
    "video/mp4; codecs=\"avc3.42E01E\"": true,
    "video/mp4; codecs=\"hev1.1.6.L93.90\"": true,
    "video/mp4; codecs=\"hvc1.1.6.L93.90\"": true,
    "video/mp4; codecs=\"hev1.2.4.L153.B0\"; eotf=\"smpte2084\"": true,
    "video/mp4; codecs=\"hvc1.2.4.L153.B0\"; eotf=\"smpte2084\"": true,
    "video/mp4; codecs=\"vp9\"": false,
    "video/mp4; codecs=\"vp09.00.10.08\"": false,
    "audio/mp4; codecs=\"mp4a.40.2\"": true,
    "audio/mp4": true,
    "audio/mp4; codecs=\"ac-3\"": true,
    "audio/mp4; codecs=\"ec-3\"": true,
    "audio/mp4; codecs=\"opus\"": false,
    "audio/mp4; codecs=\"flac\"": false,
    "video/webm; codecs=\"vp8\"": true,
    "video/webm": true,
    "video/webm; codecs=\"vp9\"": true,
    "video/webm; codecs=\"av1\"": false,
    "audio/webm; codecs=\"vorbis\"": false,
    "audio/webm": false,
    "audio/webm; codecs=\"opus\"": false,
    "video/mp2t; codecs=\"avc1.42E01E\"": false,
    "video/mp2t": false,
    "video/mp2t; codecs=\"avc3.42E01E\"": false,
    "video/mp2t; codecs=\"hvc1.1.6.L93.90\"": false,
    "video/mp2t; codecs=\"mp4a.40.2\"": false,
    "video/mp2t; codecs=\"ac-3\"": false,
    "video/mp2t; codecs=\"ec-3\"": false,
    "text/vtt": true,
    "application/mp4; codecs=\"wvtt\"": true,
    "application/mp4": true,
    "application/ttml+xml": true,
    "application/mp4; codecs=\"stpp\"": true
  },
  "drm": {
    "org.w3.clearkey": {
      "persistentState": false
    },
    "com.widevine.alpha": {
      "persistentState": false
    },
    "com.microsoft.playready": {
      "persistentState": false
    },
    "com.apple.fps.2_0": null,
    "com.apple.fps.1_0": null,
    "com.apple.fps": null,
    "com.adobe.primetime": null
  },
  "offline": true
}
```

The TV is a UJ6500. In "About This TV" it says Software Version 4.70.10, although I'm not totally clear if this is the WebOS version.

**Comment by chrisfillmore** [comment]
Could we reopen this as an official WebOS support issue? I have an internal ticket assigned to me to ensure Shaka works out of the box on LG TV's, so I'm happy to help get this resolved.

**Comment by joeyparrish** [comment]
Sure thing.  I've renamed the issue to reflect that.

@chrisfillmore, based on your support report, I see no reason WebOS shouldn't work.  If you can confirm what version of WebOS you have, that would be helpful.  @avelad reports that WebOS 3.5 works for him.

For this to be an officially supported platform, and not just a platform that happens to work, we will need to add a WebOS device to our lab environment and integrate it with our test automation.  None of that work will affect the open-source library unless we need to adjust any of the tests themselves.

The open question is what version of WebOS we should try to put in our lab.  Ideally, we would test on the oldest version we intend to support, which may be 3.5.  @chrisfillmore, @avelad, we would be happy to have your input on this.

The other issue is that we may be limited in the WebOS version we can actually purchase.  For example, when we tried to purchase a Tizen 2016 TV, we could only find 2017 models in stores.  It seems that WebOS 3.5 models are still available, but I'm not sure about earlier models.

**Comment by avelad** [comment]
I'd prefer that Shaka Player supports WebOS 3.5 or above (WebOS 4 is scheduled for the end of year).

The only "strange" thing that i found in some WebOS TV is related to video resolution, eg:
Model: lg-24MT49S-PZ (this is a low end model) with HD ready resolution (1366x768px) is not able to reproduce streams of 1080p, so I need configure setMaxHardwareResolution with 1366x768

**Comment by joeyparrish** [comment]
Cool, thanks for the feedback, @avelad!

**Comment by chrisfillmore** [comment]
Ok here's what I've learned so far.

**WebOS SDK**
http://webostv.developer.lge.com/sdk/download/download-sdk/

**Using WebOS CLI**
http://webostv.developer.lge.com/sdk/using-webos-tv-cli/

**Testing a WebOS app**
http://webostv.developer.lge.com/sdk/using-webos-tv-cli/testing-web-app-cli/

**WebOS Application Lifecycle**
http://webostv.developer.lge.com/develop/app-developer-guide/web-app-lifecycle/

You can launch an app from the command line via something similar to:

```
ares-launch --device deviceName com.domain.app --params "{'url':'www.foo.com'}"
```

You can listen for this value in WebOS:

```
document.addEventListener('webOSLaunch', function (event) {
  console.log(event.detail.url); // www.foo.com
});
```

Does this help?

**Comment by joeyparrish** [comment]
Very much, yes!  Thank you!

**Comment by chrisfillmore** [comment]
FYI we believe 2017 model WebOS TV's suffer from the same bug described here:

https://groups.google.com/forum/#!msg/shaka-player-users/DZuG1MzR2DA/R7Fduj_E2OMJ

@avelad Do your media segments include multiple PSSH boxes, or just one?

**Comment by avelad** [comment]
@chrisfillmore, our media segment only include one PSSH box

**Comment by chrisfillmore** [comment]
Ok thanks. We're going to do some testing with our streams to remove all but one PSSH and see if we are able to play.

**Comment by htleeab** [comment]
@avelad 
I tried to run shaka-player demo on browser of LG OLED C7. It seem that Widevine assets are not supported and disabled. 
Also, WebOS LG require its own library to create DRM client http://webostv.developer.lge.com/develop/app-developer-guide/playing-drm-content/
Do you using web page in browser or webOS sdk installed app with/without DRM client when you using shaka with DASH + Widevine? 
Thank.

**Comment by Kogoruhn** [comment]
I use shaka player on webOS 3.5. Non-encrypted and Widevine DASH .mpd works well.
HLS (with help of mux.js) video looks like slideshow. (On Tizen and Chrome no problem)

**Comment by MilosRasic** [comment]
DASH + Widevine also working fine on 4.x

2.x fails, only supports Widevine Classic according to http://webostv.developer.lge.com/discover/specifications/supported-media-formats/

Might be a good test case for resolving #494 if someone still cares.

**Comment by bitsleft** [comment]
WebOS 4.x - Playing multi-period dash with Playready or Widevine, play is stopping after first period:  Getting following error:

(video:20) looking up segment: presentationTime=2266 currentPeriod.startTime=2266
shaka-player.compiled.debug.js:1 (audio:17) failed fetch and append: code=3014(anonymous function) @ shaka-player.compiled.debug.js:1
index.html:114 Error code 3016 object s…a.u…l.Error {severity: 2, category: 3, code: 3016, data: Array[3], handled: false…}category: 3code: 3016data: Array[3]0: 31: undefined2: undefinedlength: 3__proto__: Array[0]handled: falsemessage: "Shaka Error MEDIA.VIDEO_ERROR (3,,)"severity: 2stack: "Error: Shaka Error MEDIA.VIDEO_ERROR (3,,)↵    at new shaka.util.Error (file:///media/developer/apps/usr/palm/applications/com.swm.lgapp/shaka-player.compiled.debug.js:1:38894)↵    at shaka.Player.videoErrorToShakaError_ (file:///media/developer/apps/usr/palm/applications/com.swm.lgapp/shaka-player.compiled.debug.js:1:480628)↵    at shaka.Player.onVideoError_ (file:///media/developer/apps/usr/palm/applications/com.swm.lgapp/shaka-player.compiled.debug.js:1:480839)↵    at HTMLVideoElement.<anonymous> (file:///media/developer/apps/usr/palm/applications/com.swm.lgapp/shaka-player.compiled.debug.js:1:429039)"__proto__: ObjectonError @ index.html:114onErrorEvent @ index.html:109shaka.util.FakeEventTarget.dispatchEvent @ shaka-player.compiled.debug.js:1shaka.Player.onError_ @ shaka-player.compiled.debug.js:1shaka.Player.onVideoError_ @ shaka-player.compiled.debug.js:1(anonymous function) @ shaka-player.compiled.debug.js:1
shaka-player.compiled.debug.js:1 (video:20) failed fetch and append: code=3015(anonymous function) @ shaka-player.compiled.debug.js:1
index.html:114 Error code 3014 object s…a.u…l.Error {severity: 2, category: 3, code: 3014, data: Array[1], handled: false…}onError @ index.html:114onErrorEvent @ index.html:109shaka.util.FakeEventTarget.dispatchEvent @ shaka-player.compiled.debug.js:1shaka.Player.onError_ @ shaka-player.compiled.debug.js:1(anonymous function) @ shaka-player.compiled.debug.js:1
index.html:114 Error code 3015 object s…a.u…l.Error {severity: 2, category: 3, code: 3015, data: Array[1], handled: false…}onError @ index.html:114onErrorEvent @ index.html:109shaka.util.FakeEventTarget.dispatchEvent @ shaka-player.compiled.debug.js:1shaka.Player.onError_ @ shaka-player.compiled.debug.js:1(anonymous function) @ shaka-player.compiled.debug.js:1

I noticed that the drmInfos in the variants is not set when changing period:

onChooseStreams_ Object {startTime: 2266, textStreams: Array[0], variants: Array[8]}startTime: 2266textStreams: Array[0]length: 0__proto__: Array[0]variants: Array[8]0: ObjectallowedByApplication: trueallowedByKeySystem: trueaudio: Objectbandwidth: 1627000drmInfos: Array[0]length: 0__proto__: Array[0]id: 25language: "en"primary: truevideo: Objectbandwidth: 1499000channelsCount: nullclosedCaptions: Mapcodecs: "avc1.64001f"createSegmentIndex: ()emsgSchemeIdUris: Array[0]encrypted: falsefindSegmentPosition: ()frameRate: 25getSegmentReference: ()height: 504id: 20initSegmentReference: shaka.media.InitSegmentReferencekeyId: nullkind: undefinedlabel: nulllanguage: "und"mimeType: "video/mp4"originalId: "5303576322001_video-1500-wtmk_1_896x504"presentationTimeOffset: 0primary: trueroles: Array[1]trickModeVideo: nulltype: "video"width: 896__proto__: Object__proto__: Object1: Object2: Object3: Object4: Object5: Object6: Object7: Objectlength: 8__proto__: Array[0]__proto__: Object
shaka-player.compiled.debug.js:1 Choosing new streams after period changed

**Comment by joeyparrish** [comment]
@bitsleft, thanks for the info.  We haven't started working on WebOS yet, but we're always happy to accept pull requests if you have a fix in mind.  Otherwise, I apologize for the delay, but we should have WebOS set up in our test lab later this year.

**Comment by bitsleft** [comment]
Thanks @joeyparrish.  My mistake in last message, the empty DRM was because the second period had no DRM. Content is served as DRM, but the ads are clear.  Where it's actually failing is in the function:

`   async fetchAndAppend_ {
    ... 
    try {
      const results = await Promise.all([initSourceBuffer, fetchSegment]);
`

It's throwing the following error: 
`
failed fetch and append: code=XXX
`
I'll keep investigating, but if you have any tips / pointers to help me out that would be greatly appreciated.  I'm quite new to video.

**Comment by Beor18** [comment]
@avelad  Hello,

Do you have an example to implement shaka player with lg webos?

**Comment by EZDRM** [comment]
does anyone have a build or can test two streams for me as I dont have access to a LG device in our demo lab

**Comment by avelad** [comment]
I tested streams of Anevia+EZDRM and I has not issues. I also have LG running with other providers without problem.

**Comment by EZDRM** [comment]
Hello,
Can you send me a sample player? As our attempts seem to have an issue with play back of the dash stream.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by TheJohnBowers** [comment]
I know that there is no official support here -- Just to report the issues we are seeing:

(Shaka 2.5.6) returns a 6006 error
FAILED_TO_GENERATE_LICENSE_REQUEST

on Verizon Media dash manifests occasionally.  It will playback sometimes while other times failing to generate a license request.

**Comment by SunDr17** [comment]
On WebOS 4.7 I'm playing DASH + PlayReady stream with multi audio tracks. At first all plays well, but after switching audio track to another video plays as slideshow (frame by frame without audio). It is also reproduces on your demo page on LG. For tizen all right plays well. I described it in this ticket https://github.com/google/shaka-player/issues/2431

**Comment by piyush2dev** [comment]
@avelad 
On Emulator 3.0, 4.0, 5.0, we are getting this Error when using. DASH + WIDEVINE.
[310][Stream] [Stream] codec not supported: video/mp4;codecs="avc1.42c00d";width="1080";height="540" 

Infact with basic Dash. URL we are getting this error. on emulator.
DASH URL:
https://bitmovin-a.akamaihd.net/content/playhouse-vr/mpds/105560.mpd

**Comment by avelad** [comment]
The emulator is very basic, and is not suitable for these tests. You have to use a physical device.

**Comment by piyush2dev** [comment]
@avelad Thanks. Just ordered a TV for this.

Can you also help in Tizen Playback. How to play Widevine+Dash content. in Tizen TV. Can I use. Shaka Player or any other player. Your input would. be really helpful

**Comment by piyush2dev** [comment]
@MilosRasic 
Thanks for your quick reply. Can. u confirm which version of Shaka you are using. Is below sample fine seems good to you or Is there any other way to implement. The Url specified and the token has expiry time of 3 Hours.

@MilosRasic You input will. be really appreciated as. I. am struggling in it for long time.

var manifestUri = 'https://ahatvhlsns.akamaized.net/aha-tv/Renditions/20200103/Pencil/dash/Pencil.mpd?hdnts=exp=1595261144~acl=/*~hmac=d86795311ca206c78bfcdac1888168449c7e2d221c7caac633c75e43c7703df0';
var licenseServer = 'https://0d45cc6b-drm-widevine-licensing.axprod.net/AcquireLicense';
   
function initApp() {
  setTimeout(function(){ 
	  // Install built-in polyfills to patch browser incompatibilities.
	  shaka.polyfill.installAll();

	  // Check to see if the browser supports the basic APIs Shaka needs.
	  if (shaka.Player.isBrowserSupported()) {
	    // Everything looks good!
	    initPlayer();
	  } else {
	    // This browser does not have the minimum set of APIs we need.
	    console.error('Browser not supported!');
	  }  
  }, 3000);
 
}

function initPlayer() {
  // Create a Player instance.
  var video = document.getElementById('video');
  var player = new shaka.Player(video);

  // Attach player to the window to make it easy to access in the JS console.
  window.player = player;

  player.configure({
    drm: {
      servers: { 'com.widevine.alpha': licenseServer }
    }
  });

  player.getNetworkingEngine().registerRequestFilter(function(type, request) {
    // Only add headers to license requests:
    if (type == shaka.net.NetworkingEngine.RequestType.LICENSE) {
      // This is the specific header name and value the server wants:
      request.headers['X-AxDRM-Message'] = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ2ZXJzaW9uIjoxLCJjb21fa2V5X2lkIjoiRDQ5QTEwRjktRkZDMy00ODhDLUI2NEEtQUIwNjAwQTE1NkJEIiwibWVzc2FnZSI6eyJ0eXBlIjoiZW50aXRsZW1lbnRfbWVzc2FnZSIsInZlcnNpb24iOjIsImxpY2Vuc2UiOnsic3RhcnRfZGF0ZXRpbWUiOiIyMDIwLTA3LTIwVDEyOjQzOjM4Ljk4OVoiLCJleHBpcmF0aW9uX2RhdGV0aW1lIjoiMjAyMC0wNy0yMFQxNjowNTo0NC45OTBaIn0sImNvbnRlbnRfa2V5c19zb3VyY2UiOnsiaW5saW5lIjpbeyJpZCI6IjA2MDk2YjIyLTE1YTYtNDYzZi05NTFiLTZlNjg3Yjg3YzBjZiIsInVzYWdlX3BvbGljeSI6IlBvbGljeSBBIn1dfSwiY29udGVudF9rZXlfdXNhZ2VfcG9saWNpZXMiOlt7Im5hbWUiOiJQb2xpY3kgQSIsInBsYXlyZWFkeSI6eyJtaW5fZGV2aWNlX3NlY3VyaXR5X2xldmVsIjoyMDAwLCJwbGF5X2VuYWJsZXJzIjpbIjc4NjYyN0Q4LUMyQTYtNDRCRS04Rjg4LTA4QUUyNTVCMDFBNyJdfSwid2lkZXZpbmUiOnsiZGV2aWNlX3NlY3VyaXR5X2xldmVsIjoiU1dfU0VDVVJFX0NSWVBUTyJ9fV19LCJiZWdpbl9kYXRlIjoiMjAyMC0wNy0yMFQxMjo0MzozOC45ODlaIiwiZXhwaXJhdGlvbl9kYXRlIjoiMjAyMC0wNy0yMFQxNjowNTo0NC45OTBaIn0.--Z3qhqucTSxGW7XDvz3xvJYFJlosOjHsK7iAAaeVC0';
    }
  });


  // Listen for error events.
  player.addEventListener('error', onErrorEvent);

  // Try to load a manifest.
  // This is an asynchronous process.
  player.load(manifestUri).then(function() {
    // This runs if the asynchronous load is successful.
    console.log('The video has now been loaded!');
  }); // onError is executed if the asynchronous load fails.
}

function onErrorEvent(event) {
  // Extract the shaka.util.Error object from the event.
  onError(event.detail);
}

function onError(error) {
  // Log the error.
  console.error('Error code', error.code, 'object', error);
}

document.addEventListener('DOMContentLoaded', initApp);

**Comment by piyush2dev** [comment]
@avelad @MilosRasic 
I tried playing DASH+WIDEVINE Content using above mentioned code. I am. getting this Error. The Video is stalled. Can you please help me how to. resolve. it.

I am using Tizen 4 TV. (**UA43NU7100**)

Please help.

(audio:9) startup complete
streaming_engine.js:1146 (all) setting up Period 0
streaming_engine.js:1140 (all) Period 0 is being or has been set up
streaming_engine.js:1214 (all) Stream 9 is being or has been set up
streaming_engine.js:1214 (all) Stream 5 is being or has been set up
player.js:4580 canSwitch_
simple_abr_manager.js:254 Calling switch_(), bandwidth=9742 kbps
player.js:4644 switch_
streaming_engine.js:803 switch: switching to Stream (video:1)
streaming_engine.js:786 switch: Stream (audio:9) already active
streaming_engine.js:1611 (video:1) looking up segment: presentationTime=3.7916666666666665 currentPeriod.startTime=0
**playhead.js:504 Stall detected at 0 for 1.002000093460083 seconds. Seeking forward 0.1 seconds.
streaming_engine.js:960 (all): seeked: buffered seek: presentationTime=0.1**

**Comment by joeyparrish** [comment]
@piyush2dev, your latest messages are off-topic.  Please don't ask for specific Tizen debugging help on an issue about official support for LG WebOS.  There are a number of open Tizen-related issues already, and yours looks similar to #2620, which I've been working on for a while now with no results.  I suggest you subscribe to #2620.

**Comment by SunDr17** [comment]
I'm using WebOS 3.0 DASH+PlayReady with shaka 2.5.7. And video doesn't play. Returns error code 6001.

**Comment by joeyparrish** [comment]
@asgvard, please let us now what you find out about that.  We would be very happy to review a PR, but since we don't have an LG TV of our own at this time.

**Comment by kasmihmed** [comment]
I wouldn't mind helping

> at

i have an lg tv and I wouldn't mind helping out.

**Comment by avelad** [comment]
Update from @joeyparrish : https://github.com/google/shaka-player/issues/3345#issuecomment-822661923

**Comment by joeyparrish** [comment]
These are the steps that must be done to add LG as an officially-supported platform:

1. Build an LG TV backend in [Generic WebDriver Server](https://github.com/google/generic-webdriver-server) (https://github.com/google/generic-webdriver-server/issues/18) so that we can automate tests and debug on the platform (can be done by **anyone** with the hardware and time and energy)
2. Set up the LG TV test infrastructure in our lab (must be done by the **Shaka team**)
3. Run all Shaka Player tests on LG TV and catalog test failures (can be done by **anyone** after part 1 is complete)
4. Fix individual test failures, either by updating test cases or fixing Shaka bugs or working around platform bugs, as appropriate (can be done by anyone or many people in parallel after part 2 is complete)
5. Enable nightly testing in the Shaka Player lab (must be done by the **Shaka team**)
6. Update docs (can be done by **anyone**)

These are the same steps we went through this year to add official Xbox One support ([step 1 PR](https://github.com/google/generic-webdriver-server/pull/12), step 4 changes [1](https://github.com/google/shaka-player/commit/572e512375a6c432187a4e90a97e99e456d63c10), [2](https://github.com/google/shaka-player/commit/95371df0118f8afe0e1b69e37f67b71d03877db2), [3](https://github.com/google/shaka-player/commit/8ee5dd987bf5d63932087f98f562460aa28a6346), and [step 6 docs updates](https://github.com/google/shaka-player/commit/04714707a81b0537b692778da0991d67d822369b)).  If anyone is interested in helping us expand official support to LG WebOS, please feel free to volunteer!

**Comment by gperulliniroque** [comment]
> Estamos usando ShakaPlayer con WebOS 3.5 y DASH+Widevine sin ningún problema.

Hola buenas noches estimado, podrias ayudarme con la configuracion del player. @avelad

**Comment by FelipeAndresLopez** [comment]
> > Estamos usando ShakaPlayer con WebOS 3.5 y DASH+Widevine sin ningún problema.
> 
> Hola buenas noches estimado, podrias ayudarme con la configuracion del player. @avelad

@avelad It would be great if you can help us with that configuration that you set, I will appreciate it.

**Comment by avelad** [comment]
Another WebOS topic: https://github.com/shaka-project/shaka-player/issues/5479

**Comment by stuartflanagan** [comment]
@avelad Wanted to let you know the latest update `4.8.0` introduces error code 4032 when playing AES HLS on webOS.
`4.7.x `.
Is there a way around this issue?

**Comment by avelad** [comment]
@stuartflanagan In 4.8.0 there are the following related changes:

- https://github.com/shaka-project/shaka-player/pull/6002
- https://github.com/shaka-project/shaka-player/pull/6118
- https://github.com/shaka-project/shaka-player/pull/6399
- https://github.com/shaka-project/shaka-player/pull/6434
- And: https://github.com/shaka-project/shaka-player/pull/6382

Anyway to fix any bug we need a test stream.

Please note that this is an unofficially supported platform, so if you want to submit a PR to fix this, we'd be happy to review it.

**Comment by stuartflanagan** [comment]
Thanks @avelad.
The issue actually occurs with any HLS stream. not just AES encrypted.
But here is a demo stream from unified that also triggers the `4032` error.
https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel-aes.ism/.m3u8


The error occurs in thePlayer load sequence. Has there been any change to the `isSupported` method used?
It seems it is now returning false for `webOS` this is webOS3 through `webOS2024`

Happy to have a look at this. Can you please point me to any commits that may have impacted `isSupported` method?

```
    this.player
      .load(mediaItem.manifest, startTime)
      .then(() => {
        handlePlayerReady();
      })
      .catch(error => {
        this.error = error;
        this.dispatchEvent(new Event('error'));
      }); 
```

**Comment by avelad** [comment]
Are you using fMP4 or TS?

**Comment by stuartflanagan** [comment]
TS

**Comment by stuartflanagan** [comment]
Thank you I will see how I go.

**Comment by stuartflanagan** [comment]
Seems to be affecting MPEGDASH and DRM as well.
Same error 4032.

**Comment by stuartflanagan** [comment]
Hi @avelad just wondering if I can get some help contributing for this issue.

I realise this ticket is probably not the place to do it as it is regarding offical support.

At present I have the `shaka-player` lib forked and it is building.

webOS is returning 4032 for manifest media types
HLS: https://demo.unified-streaming.com/k8s/features/stable/usp-s3-storage/tears-of-steel/tears-of-steel.ism/.m3u8
MPD: https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd

The interesting thing is when I switch to the debug player to investigate the logs playback is fine with no 4032 error code.

**Comment by rampratapyadav91** [comment]
minimumUpdatePeriod is 30 for live content which is causing delayed playback start if I am keeping rebufferinggoal as 30 and if set ignoreminbuffertime true then seeing a stall during playback, how to configure shaka for lower webos so that there is not any delayed playback start as well as any stall ?
