### ISSUE TITLE
Can not stop or destroy the player

### ISSUE THREAD

**Issue by tranzitwww** [google/shaka-player#1333]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate open issues?**:
Yes

**What version of Shaka Player are you using?**:
cdnjs.cloudflare.com/ajax/libs/shaka-player/2.3.3/shaka-player.compiled.js

**Can you reproduce the issue with our latest release version?**:
Yes

**Can you reproduce the issue with the latest code from `master`?**:
Yes

**Are you using the demo app or your own custom app?**:
Both

**If custom app, can you reproduce the issue using our demo app?**:
Yes

**What browser and OS are you using?**:
Firefox 58, Chrome 64

**What are the manifest and license server URIs?**:
*(NOTE: you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*
*(NOTE: a copy of the manifest text or an attached manifest will **not** be enough to reproduce your issue, and we **will** ask you to send a URI instead)*

**What did you do?**
After setting up the player and getting images (it works on that), I wan't to stop the player.

```
function player_start(){
	shaka.polyfill.installAll();
	if (!(shaka.Player.isBrowserSupported())) {
		return false;
	}

	var video = document.getElementById("player_shaka");
	var player = new shaka.Player(video);
	window.player = player;

	player.addEventListener('error', function(event) {
		console.error(event);
	});

	var mpdUrl = host + myStream + '/manifest.mpd?' + Token; //Wowza
	player.load(mpdUrl).then(function() {
		console.log('The video has now been loaded with Shaka player!');
	}).catch(function(event) {
		console.error('Error code', event.code, 'object', event);
	});
}
function player_stop(){
	var video = document.getElementById("player_shaka");
	if((typeof video  !== 'undefined') && (video  !== null)){
		video.pause();
		video.currentTime = 0;
	}
	if((typeof player !== 'undefined') && (player !== null)){
		//player.resetConfiguration();
		player.unload();
		player.destroy();
		//player = null;
	}
}

```

**What did you expect to happen?**
To stop the player for real.
Now it is shown as stopped on the browser,  but in fact it still generates network traffic to the video server (getting more data)

**What actually happened?**
It was working fine, playing the stream, but when I use my stop function to end it, it still make requests as shown below (last 3 GETs, but if the browser will not be closed it will generate those messages forever).
The error is shown in the moment I stop it with the above function and after a while will repeat itself.

```
GETXHR
http://myserver.com/live/mp4:mystream/manifest.mpd
[HTTP/1.1 200 OK 15ms]
The video has now been loaded with Shaka player!
player.php:443:5
GETXHR
http://myserver.com/live/mp4:mystream/chunk_ctvideo_cfm4s_ridp0va0br68793_cinit_w1789609982_tkcGxheWVyc3RhcnR0aW1lPTE1MjAxMTM4MzUmcGxheWVyZW5kdGltZT0xNTIwMTE0MTM1JnBsYXllcmhhc2g9TzZuaEJqc3dSRG5seS1YZEJZc2FhQjNxNVdPcnM3MFdnZDRHX2hSbW5saz0=_mpd.m4s
[HTTP/1.1 200 OK 218ms]
GETXHR
http://myserver.com/live/mp4:mystream/chunk_ctvideo_cfm4s_ridp0va0br68793_cs136810241299350_w1789609982_tkcGxheWVyc3RhcnR0aW1lPTE1MjAxMTM4MzUmcGxheWVyZW5kdGltZT0xNTIwMTE0MTM1JnBsYXllcmhhc2g9TzZuaEJqc3dSRG5seS1YZEJZc2FhQjNxNVdPcnM3MFdnZDRHX2hSbW5saz0=_mpd.m4s
[HTTP/1.1 200 OK 125ms]
GETXHR
http://myserver.com/live/mp4:mystream/chunk_ctvideo_cfm4s_ridp0va0br68793_cs136810242199260_w1789609982_tkcGxheWVyc3RhcnR0aW1lPTE1MjAxMTM4MzUmcGxheWVyZW5kdGltZT0xNTIwMTE0MTM1JnBsYXllcmhhc2g9TzZuaEJqc3dSRG5seS1YZEJZc2FhQjNxNVdPcnM3MFdnZDRHX2hSbW5saz0=_mpd.m4s
[HTTP/1.1 200 OK 218ms]
GETXHR
http://myserver.com/live/mp4:mystream/chunk_ctvideo_cfm4s_ridp0va0br68793_cs136810243099170_w1789609982_tkcGxheWVyc3RhcnR0aW1lPTE1MjAxMTM4MzUmcGxheWVyZW5kdGltZT0xNTIwMTE0MTM1JnBsYXllcmhhc2g9TzZuaEJqc3dSRG5seS1YZEJZc2FhQjNxNVdPcnM3MFdnZDRHX2hSbW5saz0=_mpd.m4s
[HTTP/1.1 200 OK 163ms]
GETXHR
http://myserver.com/live/mp4:mystream/chunk_ctvideo_cfm4s_ridp0va0br68793_cs136810243999080_w1789609982_tkcGxheWVyc3RhcnR0aW1lPTE1MjAxMTM4MzUmcGxheWVyZW5kdGltZT0xNTIwMTE0MTM1JnBsYXllcmhhc2g9TzZuaEJqc3dSRG5seS1YZEJZc2FhQjNxNVdPcnM3MFdnZDRHX2hSbW5saz0=_mpd.m4s
[HTTP/1.1 200 OK 110ms]
Object { detail: {…}, bubbles: false, cancelable: false, defaultPrevented: false, timeStamp: 12740.08, type: "error", isTrusted: false, currentTarget: {…}, target: {…}, a: false }
player.php:434:5
GETXHR
http://myserver.com/live/mp4:mystream/manifest_w1789609982_tkcGxheWVyc3RhcnR0aW1lPTE1MjAxMTM4MzUmcGxheWVyZW5kdGltZT0xNTIwMTE0MTM1JnBsYXllcmhhc2g9TzZuaEJqc3dSRG5seS1YZEJZc2FhQjNxNVdPcnM3MFdnZDRHX2hSbW5saz0=.mpd
[HTTP/1.1 200 OK 16ms]
GETXHR
http://myserver.com/live/mp4:mystream/manifest_w1789609982_tkcGxheWVyc3RhcnR0aW1lPTE1MjAxMTM4MzUmcGxheWVyZW5kdGltZT0xNTIwMTE0MTM1JnBsYXllcmhhc2g9TzZuaEJqc3dSRG5seS1YZEJZc2FhQjNxNVdPcnM3MFdnZDRHX2hSbW5saz0=.mpd
[HTTP/1.1 200 OK 21ms]
GETXHR
http://myserver.com/live/mp4:mystream/manifest_w1789609982_tkcGxheWVyc3RhcnR0aW1lPTE1MjAxMTM4MzUmcGxheWVyZW5kdGltZT0xNTIwMTE0MTM1JnBsYXllcmhhc2g9TzZuaEJqc3dSRG5seS1YZEJZc2FhQjNxNVdPcnM3MFdnZDRHX2hSbW5saz0=.mpd
[HTTP/1.1 200 OK 15ms]

```

**Comment by tranzitwww** [comment]
Thank you Jacob for reply and investigation,

>   When do you stop the player (immediately after load or a while after playback)?

After a while when it was playing the video.

>  Does this problem happen consistently? 

Yes. All the time.

> Could you provide a link to your app or to a full, working snippet that reproduces your problem?

Open the link bellow in Firefox (in Chrome is the same deal, but is not that quick related to this issue)
http://live.politiadefrontiera.ro/index2.php
In the top-right corner are 3 buttons to select a player. Pick the middle one :D
After that pick a policemen, then select a camera and the video should start.
Then close the info window or select other camera/policemen/player
Now check the console for new GET requests from shaka player.

It gets more intens if you select multiple streams (one by one) which will not completely stop, and in the background will still run the connections to the streaming server for all the streams you opened before.
It is bad for bandwidth (from mobile devices perspective) and server useless connections.

> Can you try without the if checks in player_stop? I am thinking you may not be actually calling the unload and destroy methods.

Without that I have to use try and catch, otherwise it will get errors if the player was not yet defined.
It does execute the unload and destroy functions. I've inserted a console.log inside that if block for debug.

**Comment by TheModMaker** [comment]
First I see you are calling the `stopPlayer` method 12 times!  You may want to see why this is happening, we don't support calling anything after calling `destroy`, so the second call to `unload` may break in the future.

Second, I think this is a scoping problem.  I am basing this on the code right now.  Line 414 creates a player instance and attaches it to window.  Then line 431 creates a *second* player instance and loads the video into that.

Then in `stopPlayer`, it destroys the player that is attached on window.  This is because the `player_shaka` variable is scoped to the `initPlayer` method, so it will look for a global variable with that name.  So the `stopPlayer` method will stop the first player, not the second player, which is what loaded the video.

Also I would suggest you move the JavaScript code to its own file.  This allows you to edit the JavaScript in DevTools.  It would make debugging easier.

**Comment by tranzitwww** [comment]
Now the main script is moved to a separated .js file. :)

I am using stopPlayer on different events, so it will always terminate the player when the infowindow is close, or before opening a new camera. 
The code is still beta, and there can be some issues (like this one)

You are right about that code from Line 414. I've commented that block and now seems to behave as expected :D
I've been using the part to be sure that no other instance was running before starting the new one, but it wasn't doing what I was expecting.

Thank you very much for the troubleshooting!
Citizens of the world will be happy to use the player while traveling to Romania. :D
