### ISSUE TITLE
Clean up async tests using async/await

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#1337]
Since Jasmine v2.7.0, Jasmine supports async functions and functions that return Promises.  We should no longer have to do this:

```js
    it('can be used before load()', function(done) {
      player.attach().then(() => {
        return player.load('test:sintel_compiled');
      }).catch(fail).then(done);
    });
```

Instead, we should be able to let the returned Promise manage both completion and failures:

```js
    it('can be used before load()', function() {
      return player.attach().then(() => {
        return player.load('test:sintel_compiled');
      });
    });  // no catch(fail), no then(done), no "done" at all!
```

Or even use async functions which implicitly return Promises:
```js
    it('can be used before load()', async function() {
      await player.attach();
      await player.load('test:sintel_compiled');
    });
```

**Comment by vaage** [comment]
Just a small nit, according to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function:
```js
    it('can be used before load()', function() {
      await player.attach();
      await player.load('test:sintel_compiled');
    });
```
will need to be:
```js
    it('can be used before load()', async function() {
      await player.attach();
      await player.load('test:sintel_compiled');
    });
```

**Comment by joeyparrish** [comment]
Updated.  Thanks for catching that!

**Comment by theodab** [comment]
I started on this, but it will have to be put on hold for a while due to issues with Closure compiler type inference and async functions.

**Comment by TheModMaker** [comment]
Jasmine has `expect(...).toThrow` which allows us to assert that a function will throw an exception.  We should look into adding one for async methods.   There appears to be `expectAsync`, but I don't think it supports asserting the value of the rejection.  For example:

```js
// Instead of:
try {
  await foo();
  fail();
} catch (e) {
  expect(e).toEqual(expected);
}

// Instead write:
await expectAsync(foo()).toBeRejectedWith(expected);
// Or
await expectAsync(foo).toRejectWhenCalled(expected);
```

**Comment by TheModMaker** [comment]
Handled as part of #1157.
