### ISSUE TITLE
Recommend shaka.util.LicenseRequest `method` be configurable.

### ISSUE THREAD

**Issue by chemoish** [google/shaka-player#134]
I am executing the following code and the license_server I am using only accepts `method: "GET"`.

```js
var license_server = ...

return new shaka.player.DrmSchemeInfo(
    'com.widevine.alpha',
    license_server,
    false, /* withCredentials */
    null, /* licensePostProcessor */
    null /* licensePreProcessor */
);
```

Can we please allow `shaka.player.DrmSchemeInfo` be configurable to handle such case?

---

https://github.com/google/shaka-player/blob/master/lib/util/license_request.js#L44

```js
// please update me
this.parameters.method = 'POST';
```

**Comment by tdrews** [comment]
We can add an HTTP method override to the licenseRequestInfoObject.
