### ISSUE TITLE
How get sidx info for DASH streams

### ISSUE THREAD

**Issue by krvangala** [google/shaka-player#1344]
for better seeking ( w.r.t buffer),  i would like to have sidx table info so that seek time can be aligned to fragment. like if the seek time is almost near to end of fragment, seek can can be aligned to next fragment . 
is there any way i can extract this info from shaka player.
Thanks
Krishna

**Comment by TheModMaker** [comment]
There is no convenient API to do this, but you could query the manifest.  

1. Use `player.getVariantTracks()` and find the one that has `active` of true; using the `id` property is the variant ID of what we are currently streaming.
1. Use `player.getManifest()` to get the manifest object.
    * [Manifest definition](https://shaka-player-demo.appspot.com/docs/api/shakaExtern.html#Manifest).
1. Search the `manifest.periods[0].variants` array for the one with the same ID.
1. For each `audio` and `video` streams:
    1. Use `findSegmentPosition` to find the segment index that contains the given time (in seconds)
        * e.g. `variant.audio.findSegmentPosition(300)` may return 12
    1. Use `getSegmentReference` to get that segment reference
        * e.g. `variant.audio.getSegmentReference(12)` will return a [shaka.media.SegmentReference](https://shaka-player-demo.appspot.com/docs/api/shaka.media.SegmentReference.html) object.
    1. Use this to determine seek position.  For example, you could instead seek to `segment.getStartTime()`, which could be 295 in this example.

This also will be much more complicated if you have multi-Period content or if the first Period doesn't start at 0.  Also, this uses the segment info present in the manifest, which may not be the `sidx` box.  If you are using `SegmentBase`, then we use the `sidx` to determine the segments; but other segment formats explicitly list the segments, so we ignore any `sidx` boxes we see.

Also, for the initial start time, you can set the `streaming.startAtSegmentBoundary` configuration to snap the start time to a segment boundary.  But this only applies to the start time.

```js
player.configure({streaming: {startAtSegmentBoundary: true}});
player.load('https://example.com/manifest.mpd', 30);
// May change start time to 25 so it is at a segment boundary.
```

**Comment by TheModMaker** [comment]
@krvangala Does this answer all your questions?

**Comment by krvangala** [comment]
@TheModMaker   yes. it helped.
