### ISSUE TITLE
Recommend allowing the license server be configurable.

### ISSUE THREAD

**Issue by chemoish** [google/shaka-player#135]
The `license_server` I am using consists of the following format…

```
www.example.com
&token={{token}}
&account={{account}}
&_releasePid={{releasePid}}
&_widevineChallenge={{widevineChallenge}}
```

I am able to construct everything beyond the `widevineChallenge` before instantiating `shaka.player.DrmSchemeInfo`.

I need to be able to append the `widevineChallenge` to the license server before the request gets sent by `shaka.util.LicenseRequest.send()`.

```js
var license_server = ...

return new shaka.player.DrmSchemeInfo(
    'com.widevine.alpha',
    license_server,
    false, /* withCredentials */
    null, /* licensePostProcessor */
    licensePreProcessor /* licensePreProcessor */
);

function licensePreProcessor(license_request_info) {
    // modify license server somehow
}
```

Currently the `license_request_info` has `body` and `headers` (https://github.com/google/shaka-player/blob/master/lib/player/drm_scheme_info.js#L142).
- Possibly add a way to pass query string parameters?
- Possible add a way to manipulate the license server beyond string manipulation?

**Comment by tdrews** [comment]
We can add a licenseServerUrl override to the licenseRequestInfo object.
