### ISSUE TITLE
Update {Object.<key, value>} to use ES6 Map

### ISSUE THREAD

**Issue by vaage** [google/shaka-player#1356]
Using `{Object.<key, value>}` key type is not preserved (converted to string). ES6 Map does preserve key types (and can even have functions and objects as keys). Map can't be used until Shaka Player either polyfill it or drops IE.

An area where using ES6 Map would make things easier would be in the offline code, where maps are being used to pass groups of objects between memory and storage.

**Comment by joeyparrish** [comment]
Duplicate of #1672
