### ISSUE TITLE
Immediately seeking while content is loading causes player to stall.

### ISSUE THREAD

**Issue by sanbornhnewyyz** [google/shaka-player#136]
1) In the sample app, set playbackStartTime to 25 (somewhere mid video)
2) Load content
3) While content starts loading the progress indicator will move to 25. Immediately seek back to a previous position by clicking on the bar.
4) Content will continue to buffer from 25 instead of playing from the seeked location. Playback won't begin from the seeked position even after toggling play/pause. Playback will only start if you seek back into the buffered range.

**Comment by tdrews** [comment]
Yep, I see the problem: we aren't handling seek events until the initial buffering is done. This is a tricky one, but I have a fix in mind.

**Comment by dougdoe** [comment]
@tdrews Is it possible to plan to include your [potential] fix in v1.5.0?

**Comment by tdrews** [comment]
This fix is nearly ready and will be included in v1.5.0.
