### ISSUE TITLE
Write a StreamingEngine unit test for seeking during a period transition

### ISSUE THREAD

**Issue by theodab** [google/shaka-player#1361]
In `streaming_engine.js`, there's a comment in `handlePeriodTransition_`:
```
// TODO: Write unit tests for this case.
```

Well, it's a little over a year later, and that comment's still there. We should probably make a unit test like the comment says.

**Comment by joeyparrish** [comment]
I believe this will be obsolete after #1339, but we will see.

**Comment by joeyparrish** [comment]
This is obsoleted by #1339.
