### ISSUE TITLE
question: rewinding over gaps

### ISSUE THREAD

**Issue by gaxunil** [google/shaka-player#1369]
Hi, I'm pretty new to the player world.

I'm using Shaka ver 2.3.3 on Chrome  65.0.3325.162

We have a project that is using Shaka wrapped as a Tech to VideoJs.
I'm investigating issues on MPEG DASH playback of on demand videos with gaps.  On normal playback, Shaka seems to understand when it hits a gap and jumps over it correctly.

Our asset / manifest URLs are all behind a private VPC / App.

On rewind, things don't work so well.  What I see via logging is that when we hit a gap in rewind, Shaka starts triggering **largegap** events and doesn't seem to know the correct duration of the gap.  I see ever increasing gapSizes doubling with every call.  It seems like Shaka is just trying to increasing gap sizes, hoping the next **largegap** event will give a gapSize that lands outside the gap.

example from our gap handler logs, notice how gapSize increases:

```
{currentTime: 30.833731, gapSize: 1.326267999999999, bubbles: false, cancelable: true, defaultPrevented: false, …}  

{currentTime: 29.507463, gapSize: 2.652535999999998, bubbles: false, cancelable: true, defaultPrevented: false, …}  

{currentTime: 26.854927, gapSize: 5.305071999999999, bubbles: false, cancelable: true, defaultPrevented: false, …}  

{currentTime: 21.549855, gapSize: 10.610143999999998, bubbles: false, cancelable: true, defaultPrevented: false, …}  
```
And so on, until we backtrack outside of the gap, usually overshooting it by quite a lot.

I'm not sure why Shaka doesn't use the MPD manifest Period information, which contains a start and duration for each Period.  With this info, it seems like Shaka could know where the gaps are and jump over them (in both play AND rewind) without having to do the gapSize doubling algorithm.

In hopes of handling the gap jump in our **largegap** handler, I tried grabbing the parsed manifest from the Shaka player via the getManifest() function, but I couldn't find any Period duration information in the data structure returned.  It seems like a duration or end time is needed to figure out where gaps start and end.

Here's an example manifest
```
<MPD mediaPresentationDuration="PT5M" profiles="urn:mpeg:dash:profile:full:2011" maxSegmentDuration="PT0H0M16.683S" type="static" minBufferTime="PT1.500S" xmlns="urn:mpeg:dash:schema:mpd:2011"><BaseURL>removed-private-url</BaseURL>
 <ProgramInformation moreInformationURL="http://gpac.io">
  <Title>manifest.mpd generated by GPAC</Title>
 </ProgramInformation>

 
 
<Period start="PT0.060S" duration="PT0H0M8.943S" id="0">
  <AdaptationSet lang="und" par="4:3" maxFrameRate="15314/1022" maxHeight="480" maxWidth="640" segmentAlignment="true">
   <SegmentTemplate timescale="15314">
    <SegmentTimeline>
     <S d="136948" t="0"/>
    </SegmentTimeline>
   </SegmentTemplate>
   <Representation bandwidth="82106" startWithSAP="0" sar="1:1" frameRate="15314/1022" height="480" width="640" codecs="avc1.640016" mimeType="video/mp4" id="1">
    <SegmentTemplate media="ch0_0_20171201T071919_9_dash_track1_$Number$.m4s" initialization="ch0_0_20171201T071919_9_dash_track1_init.mp4" startNumber="1" timescale="15314"/>
   </Representation>
  </AdaptationSet>
 </Period><Period start="PT3M35.980S" duration="PT0H1M24.017S" id="1">
  <AdaptationSet lang="und" par="4:3" maxFrameRate="15000/1001" maxHeight="480" maxWidth="640" segmentAlignment="true">
   <SegmentTemplate timescale="14101">
    <SegmentTimeline>
     <S r="3" d="235250" t="0"/>
     <S d="235249"/>
     <S d="8469"/>
    </SegmentTimeline>
   </SegmentTemplate>
   <Representation bandwidth="80604" startWithSAP="1" sar="1:1" frameRate="15000/1001" height="480" width="640" codecs="avc1.640016" mimeType="video/mp4" id="2">
    <SegmentTemplate media="ch0_1_20171201T072254_85_dash_track1_$Number$.m4s" initialization="ch0_1_20171201T072254_85_dash_track1_init.mp4" startNumber="1" timescale="14101"/>
   </Representation>
  </AdaptationSet>
 </Period></MPD>
```

We setup into rewind mode by calling trickPlay(-2) to enter rewind.
We attempt to handle gaps in rewind in our **largegap** handler by calling `videojsPlayer.currentTime(gapEvent.currentTime - gapEvent.gapSize)`

Our gap related settings are these:
```
streaming: {
        jumpLargeGaps: true,
        smallGapLimit: 0.0 
}
```
Questions:

- Should Shaka be able to handle jumping over gaps in rewind?
- Why doesn't Shaka know the gap boundaries (from the MPD) to handle rewind?
- Should the parsed manifest have Period duration or end time somewhere?
- Is there a better way to handle this that I'm missing?

Thanks so much.

**Comment by ismena** [comment]
Hi @gaxunil, welcome to the community!

Let me get out in-house gap mastermind @TheModMaker :)

In the meantime, could you describe the problem in more detail and ideally provide a way for us to repro the issue. Do you have a manifest we could use for the repro?
We have a convenient filing form that asks you all kind of useful questions to help us triage issues quickly and effectively. Here it is:
**What version of Shaka Player are you using?**:

**Can you reproduce the issue with our latest release version?**:

**Can you reproduce the issue with the latest code from `master`?**:

**Are you using the demo app or your own custom app?**:

**If custom app, can you reproduce the issue using our demo app?**:

**What browser and OS are you using?**:

**What are the manifest and license server URIs?**:
*(NOTE: you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*
*(NOTE: a copy of the manifest text or an attached manifest will **not** be enough to reproduce your issue, and we **will** ask you to send a URI instead)*

**What did you do?**

**What did you expect to happen?**

**What actually happened?**

As I understand, the problem occurs in trick play mode, when rewinding over a gap. What exactly happens? Does rewind stop working? Hangs or something else? Does it happen in the middle of the rewind or after?

**Comment by gaxunil** [comment]
**What version of Shaka Player are you using?:**
2.3.3

**Can you reproduce the issue with our latest release version?:**
I believe 2.3.3 is the latest, so yes.

**Can you reproduce the issue with the latest code from master?:**
Working on trying, don't know yet

**Are you using the demo app or your own custom app?:**
Custom App: Shaka as a Tech backend to VideoJS

**If custom app, can you reproduce the issue using our demo app?:**
I have not tired yet.  I think I would need to run the demo app locally as our manifest are behind private infrastructure.  If there is a way to do this, let me know.

**What browser and OS are you using?:**
Chrome: 65.0.3325.162 (Official Build) (64-bit)   
OSX: 10.13.3

**What are the manifest and license server URIs?:**
I know you said you need a URI, but they are protected behind private infrastructure.
Here's an MPD for a problem case:
```
<MPD mediaPresentationDuration="PT5M" profiles="urn:mpeg:dash:profile:full:2011" maxSegmentDuration="PT0H0M16.683S" type="static" minBufferTime="PT1.500S" xmlns="urn:mpeg:dash:schema:mpd:2011"><BaseURL>removed-private-url</BaseURL>
 <ProgramInformation moreInformationURL="http://gpac.io">
  <Title>manifest.mpd generated by GPAC</Title>
 </ProgramInformation>

 
 
<Period start="PT0.060S" duration="PT0H0M8.943S" id="0">
  <AdaptationSet lang="und" par="4:3" maxFrameRate="15314/1022" maxHeight="480" maxWidth="640" segmentAlignment="true">
   <SegmentTemplate timescale="15314">
    <SegmentTimeline>
     <S d="136948" t="0"/>
    </SegmentTimeline>
   </SegmentTemplate>
   <Representation bandwidth="82106" startWithSAP="0" sar="1:1" frameRate="15314/1022" height="480" width="640" codecs="avc1.640016" mimeType="video/mp4" id="1">
    <SegmentTemplate media="ch0_0_20171201T071919_9_dash_track1_$Number$.m4s" initialization="ch0_0_20171201T071919_9_dash_track1_init.mp4" startNumber="1" timescale="15314"/>
   </Representation>
  </AdaptationSet>
 </Period><Period start="PT3M35.980S" duration="PT0H1M24.017S" id="1">
  <AdaptationSet lang="und" par="4:3" maxFrameRate="15000/1001" maxHeight="480" maxWidth="640" segmentAlignment="true">
   <SegmentTemplate timescale="14101">
    <SegmentTimeline>
     <S r="3" d="235250" t="0"/>
     <S d="235249"/>
     <S d="8469"/>
    </SegmentTimeline>
   </SegmentTemplate>
   <Representation bandwidth="80604" startWithSAP="1" sar="1:1" frameRate="15000/1001" height="480" width="640" codecs="avc1.640016" mimeType="video/mp4" id="2">
    <SegmentTemplate media="ch0_1_20171201T072254_85_dash_track1_$Number$.m4s" initialization="ch0_1_20171201T072254_85_dash_track1_init.mp4" startNumber="1" timescale="14101"/>
   </Representation>
  </AdaptationSet>
 </Period></MPD>
```

**What did you do?**
We have a project that is using Shaka wrapped as a Tech to VideoJs.
I'm investigating issues on MPEG DASH playback of on demand videos with gaps. On normal playback, Shaka seems to understand when it hits a gap and jumps over it correctly.

Our asset / manifest URLs are all behind a private VPC / App.

On rewind, things don't work so well. What I see via logging is that when we hit a gap in rewind, Shaka starts triggering largegap events and doesn't seem to know the correct duration of the gap. I see ever increasing gapSizes doubling with every call. It seems like Shaka is just trying to increasing gap sizes, hoping the next largegap event will give a gapSize that lands outside the gap.

example from our gap handler logs, notice how gapSize increases:
```
{currentTime: 30.833731, gapSize: 1.326267999999999, bubbles: false, cancelable: true, defaultPrevented: false, …}  

{currentTime: 29.507463, gapSize: 2.652535999999998, bubbles: false, cancelable: true, defaultPrevented: false, …}  

{currentTime: 26.854927, gapSize: 5.305071999999999, bubbles: false, cancelable: true, defaultPrevented: false, …}  

{currentTime: 21.549855, gapSize: 10.610143999999998, bubbles: false, cancelable: true, defaultPrevented: false, …}  
```

And so on, until we backtrack outside of the gap, usually overshooting it by quite a lot.

I'm not sure why Shaka doesn't use the MPD manifest Period information, which contains a start and duration for each Period. With this info, it seems like Shaka could know where the gaps are and jump over them (in both play AND rewind) without having to do the gapSize doubling algorithm.

In hopes of handling the gap jump in our largegap handler, I tried grabbing the parsed manifest from the Shaka player via the getManifest() function, but I couldn't find any Period duration information in the data structure returned. It seems like a duration or end time is needed to figure out where gaps start and end.

We setup into rewind mode by calling trickPlay(-2) to enter rewind.
We attempt to handle gaps in rewind in our largegap handler by calling videojsPlayer.currentTime(gapEvent.currentTime - gapEvent.gapSize)

Our gap related settings are these:
```
streaming: {
        jumpLargeGaps: true,
        smallGapLimit: 0.0 
}
```

**What did you expect to happen?**
Expected Shaka to know about gaps in rewind mode and jump them without the doubling search / guess algorithm for gap length.  Or to provide accurate gap length to the largegap event handler, or for the parsed manifest to provide Period duration or endTime so I could maybe handle the gap myself.
Questions:

- Should Shaka be able to handle jumping over gaps in rewind?
- Why doesn't Shaka know the gap boundaries (from the MPD) to handle rewind?
- Should the parsed manifest have Period duration or end time somewhere?
- Is there a better way to handle this that I'm missing?
 

**What actually happened?**
Shaka provides gap lengths on increasing doubling algorithm, probably trying to find the end of the gap.  We set the playhead like this:
`videojsPlayer.currentTime(gapEvent.currentTime - gapEvent.gapSize)`
Which will overshoot the gap usually.
The player will either overshoot the gap and put you back too far in the video, or, if the gap is close to the beginning, cause a seek back to the very beginning of the video.

**Comment by joeyparrish** [comment]
> **Are you using the demo app or your own custom app?:**
> Custom App: Shaka as a Tech backend to VideoJS
>
> **If custom app, can you reproduce the issue using our demo app?:**
> I have not tired yet. I think I would need to run the demo app locally as our manifest are behind private infrastructure. If there is a way to do this, let me know.

Just check out our source code and compile it.  See https://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html

Your local web server needs to be able to access the source code.  Then just load index.html.

We can't debug integrations into third-party apps like videojs, but if you can reproduce with our demo app, it becomes much easier for us to work on.

> **What are the manifest and license server URIs?:**
> I know you said you need a URI, but they are protected behind private infrastructure.

We need this to be able to reproduce any content-specific issue.  The manifest contents are rarely enough for us to work with.

If you can't provide the URI publicly, you can share it privately by emailing to shaka-player-issues@google.com and referencing this issue number.  The information will only be accessible by the Shaka Player Team at Google.

If you can't do this, you may want to try reproducing the issue with some public piece of content.  We have dozens of pieces of publicly accessible content in the demo app.  If one of them can be used to trigger the issue, we should be able to reproduce it easily.

**Comment by TheModMaker** [comment]
First, rewinding is not well supported.  For example, we still buffer forward when rewinding and we will clear the buffer as we seek outside the buffered range during the rewind.  There are a few things we could do to make it better, but it is a lower priority feature.

Second, our gap jumping only works for playback, it doesn't work for rewinding.  Rewinding isn't playing, the video is just paused and repeatedly seeking backwards to simulate reverse playback.  Really, the video should be paused, so the gap jumping shouldn't be triggering at all.  It is a bug to try to jump gaps while rewinding.

Also, we aren't doubling the `gapSize` and trying it.  What is happening is we are moving backward, so the gap to the next (forward) content is getting larger.  I'm not sure why it would appear to double each time.  But again, gap jumping only works for playback, not rewinding.  We also can't always rely on the info in the manifest to be accurate.  There are frequently gaps in the media that don't appear in the manifest.  So we have to wait until we have downloaded the segments to determine where the gaps are.  But we don't "poll and try", we detect the buffered ranges of the video and seek to that.  When playing forward, our gap jumping will immediately and accurately detect the gap.

**Comment by gaxunil** [comment]
@TheModMaker thank you so much for the explanation and info!  I'll take this back to our team and we'll figure out how we want to proceed.  Having that explained makes it much clearer.

**Comment by gaxunil** [comment]
@TheModMaker one follow up question - is the Period end time or duration available anywhere?  For our use case on rewind, if we knew the Period boundaries, we could probably detect the gaps on our end and adjust.  Is this info available at all in the parsed MPD data structure returned from ShakaPlayer.getManifest() for example?

**Comment by wayneseymour** [comment]
bump

**Comment by TheModMaker** [comment]
The original Period end is not available.  When we parse the manifest, we extend our Period to fill the gap and when we append the segments, there will be a gap that we will jump.  Note that this extending will not introduce new segments, we'll just extend the duration of the last segment to fill the gap.

Think of it this way, you have two segments: [0-1] and [3-4].  We extend the duration of the first so there are no gaps, so we think the segments are [0-3] and [3-4].  When we append the first segment, it only fills [0-1], when we append the second segment, [0-1, 3-4] is filled, so we detect the gap and jump it if needed.
