### ISSUE TITLE
Dash Live not work with Firefox 59 and ^

### ISSUE THREAD

**Issue by stanislavche** [google/shaka-player#1371]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate open issues?**:
Yes
**What version of Shaka Player are you using?**:
1.6 and 2.3.3
**Can you reproduce the issue with our latest release version?**:
yes
**Can you reproduce the issue with the latest code from `master`?**:
yes
**Are you using the demo app or your own custom app?**:
custom app
**If custom app, can you reproduce the issue using our demo app?**:
I don't know
**What browser and OS are you using?**:
Firefox 59 and Firefox Night version - not worked
Chrome all version, Firefox 58 and less - worked
**What are the manifest and license server URIs?**:
if code is not enough I will send link be email, let me know if it needed
`<?xml version="1.0" encoding="UTF-8"?>
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" profiles="urn:mpeg:dash:profile:isoff-live:2011" type="dynamic" availabilityStartTime="2011-03-01T00:00:10Z" minimumUpdatePeriod="PT2.0S" minBufferTime="PT2.0S" publishTime="2018-03-22T14:41:51Z" timeShiftBufferDepth="PT2M" xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011 DASH-MPD.xsd">
   <Period start="PT0S" id="1">
      <AdaptationSet mimeType="video/mp4" startWithSAP="1" segmentAlignment="true">
         <ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc" />
         <ContentProtection schemeIdUri="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed" />
         <SegmentTemplate timescale="10000000" presentationTimeOffset="0" media="$RepresentationID$/Segment-$Time$.m4v" initialization="$RepresentationID$/init.m4i">
            <SegmentTimeline>
               <S t="2227919917710000" d="20000000" r="59" />
            </SegmentTimeline>
         </SegmentTemplate>
         <Representation width="256" height="144" frameRate="25" codecs="avc1.42801e" scanType="progressive" id="stream_0" bandwidth="256000" />
         <Representation width="512" height="288" frameRate="25" codecs="avc1.4d401f" scanType="progressive" id="stream_1" bandwidth="512000" />
         <Representation width="768" height="432" frameRate="25" codecs="avc1.4d401f" scanType="progressive" id="stream_2" bandwidth="1000000" />
         <Representation width="1024" height="576" frameRate="25" codecs="avc1.640029" scanType="progressive" id="stream_3" bandwidth="1600000" />
         <Representation width="1024" height="576" frameRate="25" codecs="avc1.640029" scanType="progressive" id="stream_4" bandwidth="2200000" />
         <Representation width="1280" height="720" frameRate="25" codecs="avc1.640029" scanType="progressive" id="stream_5" bandwidth="3000000" />
         <Representation width="1920" height="1080" frameRate="25" codecs="avc1.640029" scanType="progressive" id="stream_6" bandwidth="3900000" />
         <Representation width="1920" height="1080" frameRate="25" codecs="avc1.640029" scanType="progressive" id="stream_7" bandwidth="4800000" />
      </AdaptationSet>
      <AdaptationSet mimeType="audio/mp4" startWithSAP="1" lang="ita" segmentAlignment="true">
         <ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc" />
         <ContentProtection schemeIdUri="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed" />
         <SegmentTemplate timescale="10000000" presentationTimeOffset="0" media="$RepresentationID$/Segment-$Time$.m4a" initialization="$RepresentationID$/init.m4i">
            <SegmentTimeline>
               <S t="2227919899376222" d="20480000" />
               <S t="2227919919856222" d="38400000" />
               <S t="2227919958256222" d="20480000" r="3" />
               <S t="2227920040176222" d="38400000" />
               <S t="2227920078576222" d="20480000" r="2" />
               <S t="2227920140016222" d="38400000" />
               <S t="2227920178416222" d="20480000" r="2" />
               <S t="2227920239856222" d="38400000" />
               <S t="2227920278256222" d="20480000" r="3" />
               <S t="2227920360176222" d="38400000" />
               <S t="2227920398576222" d="20480000" r="2" />
               <S t="2227920460016222" d="38400000" />
               <S t="2227920498416222" d="20480000" r="2" />
               <S t="2227920559856222" d="38400000" />
               <S t="2227920598256222" d="20480000" r="3" />
               <S t="2227920680176222" d="38400000" />
               <S t="2227920718576222" d="20480000" r="2" />
               <S t="2227920780016222" d="38400000" />
               <S t="2227920818416222" d="20480000" r="2" />
               <S t="2227920879856222" d="38400000" />
               <S t="2227920918256222" d="20480000" r="3" />
               <S t="2227921000176222" d="38400000" />
               <S t="2227921038576222" d="20480000" r="2" />
            </SegmentTimeline>
         </SegmentTemplate>
         <Representation audioSamplingRate="48000" codecs="mp4a.40.5" id="stream_8" bandwidth="96000" />
      </AdaptationSet>
   </Period>
</MPD>`

**What did you do?**
Try to play Dash Live content
**What did you expect to happen?**
Live content should play
**What actually happened?**
I got error and video and audio not played
**Media resource blob:[...our page...] could not be decoded, error: Error Code: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005) Details: void __cdecl mozilla::EMEDecryptor::AttemptDecode(class mozilla::MediaRawData *): Failed to convert encrypted AAC sample to ADTS**

**Comment by TheModMaker** [comment]
That error looks like a decoder error, which there is usually nothing we can do about.  This is likely a bug in Firefox or with your content.  I would also suggest filing a bug on: https://bugzilla.mozilla.org/.  But we can still look at it if you want.

**Comment by stanislavche** [comment]
@ismena @TheModMaker I have send email with our manifest link

**Comment by ismena** [comment]
@stanislavche Looks like the stream is encrypted. If that's the case we also need the license server and certificate to be able to access it.

**Comment by stanislavche** [comment]
@ismena I've send you email. Please check it as soon as it possible

**Comment by joeyparrish** [comment]
I'm marking this as "external" because it seems to be a Firefox-specific decoding error.  @stanislavche, you didn't mention what OS you are using with Firefox 59 and nightly.  Can you tell us what OS you are using?

@cpeterso, can you weigh in on this?  The content fails to play on FF 59 and up, with `Error Code: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005) Details: void __cdecl mozilla::EMEDecryptor::AttemptDecode(class mozilla::MediaRawData ): Failed to convert encrypted AAC sample to ADTS`.  We have been provided with a DASH manifest privately, but we do not yet have access to request a license.  Can you tell us anything based on the error code?  Or tag someone else at Mozilla who can?

**Comment by Cherniavskaia** [comment]
@joeyparrish Windows 10 OS. I have send email with our link / credentials and some instruction. I can forward this email to you or someone else.

**Comment by stanislavche** [comment]
@joeyparrish Windows 10 OS. I have send email with our link / credentials and some instruction. I can forward this email to you or someone else.

**Comment by cpeterso** [comment]
> The content fails to play on FF 59 and up, with Error Code: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005) Details: void __cdecl mozilla::EMEDecryptor::AttemptDecode(class mozilla::MediaRawData ): Failed to convert encrypted AAC sample to ADTS.

I think this is [Firefox bug 1447821](https://bugzilla.mozilla.org/show_bug.cgi?id=1447821). A fix should land in Firefox Nightly this week. I expect the fix will ship in Firefox 60 (May 9). If this affects a lot of content, please comment in the Firefox bug and we might be able to patch this bug in a Firefox 59.0.3 dot release sooner. Until the fix ships, you could try not encrypting the audio content.

**Comment by joeyparrish** [comment]
Thanks, Chris!  @stanislavche, does this help?  Is there anything else we can do?

(We will keep this bug open until we see the corresponding Mozilla bug closed.)

**Comment by joeyparrish** [comment]
The corresponding Firefox bug has been closed, with this note:

> The bug was reproduced on Firefox 59.0.2 using the steps from comment 0.  We verified the issue on Windows 10 x64, Windows 8.1 x64, Ubuntu 16.04 x86 and macOS 10.13 using Firefox 60 Beta 8.

Please retest with a nightly or beta build of Firefox.

Since the upstream bug has been closed, we will close this one as well.  Thanks!
