### ISSUE TITLE
Impossible to bind an AudioContext to the audio element 'cause it's already connected to another sourceNode.

### ISSUE THREAD

**Issue by Mathieu-R** [google/shaka-player#1372]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate open issues?**: Yes

**What version of Shaka Player are you using?**: 2.3.3

**Can you reproduce the issue with our latest release version?**: Yes

**Can you reproduce the issue with the latest code from `master`?**: Yes

**Are you using the demo app or your own custom app?**: Custom app

**If custom app, can you reproduce the issue using our demo app?**: Yes

**What browser and OS are you using?**: Chrome 65 and OS X 10.13.3

**What are the manifest and license server URIs?**:
*(NOTE: you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*
*(NOTE: a copy of the manifest text or an attached manifest will **not** be enough to reproduce your issue, and we **will** ask you to send a URI instead)*

**What did you do?**
I tried to bind an AudioContext to my <audio /> element which is wrapped in shaka-player.
```js
const context = new (AudioContext || webkitAudioContext)();
// bind the context to <audio /> element
const source = context.createMediaElementSource(audio);
```

**What did you expect to happen?**
The binding would work so I could implement my crossfade function. (I wanna crossfade 2 songs in a playlist)

**What actually happened?**

```
home.js?6205:148 Uncaught (in promise) DOMException: Failed to execute 'createMediaElementSource' on 'BaseAudioContext': HTMLMediaElement already connected previously to a different MediaElementSourceNode.
```

Seems like shaka-player is already connecting the HTMLMediaElement to a MediaElementSourceNode. If it's the case, is there any way to retrieve this MediaElementSourceNode ?

**Comment by TheModMaker** [comment]
I have a little experience with the Web Audio API, but we don't use it in Shaka Player.  I know that it is possible to do with Shaka Player as I have used it to create a visualizer. My guess is this is a problem with your app.  Maybe this is getting called twice and the second one is failing?  Or maybe you are using another library that is binding to the element?

**Comment by Mathieu-R** [comment]
When I try to bind the audiocontext before init shaka-player I don't have that error. I'm inverstigating.

**Comment by Mathieu-R** [comment]
Update : 

I have bound the audiocontext at the lauch of the app. Now I don't have this error anymore **but**, the music is no played as a click on a track. This problem disappear if comment the `initWebAudioApi()` function.

```js
componentDidMount () {
  this.initWebAudioApi();
  this.initShakaPlayer();
  this.initMediaSession();
}

initWebAudioApi () {
  // create a new audio context
  this.context = new (AudioContext || webkitAudioContext)();
  // bind the context to our <audio /> element
  this.source = this.context.createMediaElementSource(this.audio.base);
}
```

**Comment by TheModMaker** [comment]
Once you create the `source` object, the audio output is detached from the audio device.  You'll need to attach the source to something to be able to hear the audio again.  For example, if you wanted to put an analyser between the `<video>` and the audio device:

```js
let analyser = this.context.createAnalyser();
// The <audio> should output to the analyser.
this.source.connect(analyser);
// The analyser should output to the audio device.
analyser.connect(this.context.destination);
```

**Comment by Mathieu-R** [comment]
Thanks ! That works perfectly.
