### ISSUE TITLE
Error code 3016 returned with playback from IE11 Windows 8.1+

### ISSUE THREAD

**Issue by stuartflanagan** [google/shaka-player#1376]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate open issues?**:
Yes
**What version of Shaka Player are you using?**:
2.3.4
https://cdnjs.cloudflare.com/ajax/libs/shaka-player/2.3.4/shaka-player.compiled.debug.externs.js
**Can you reproduce the issue with our latest release version?**:
Yes please find example attached with latest version

**Can you reproduce the issue with the latest code from `master`?**:
I have not tried as yet

**Are you using the demo app or your own custom app?**:
Own custom. URL supplied with all JS in source
**If custom app, can you reproduce the issue using our demo app?**:
It is with a DRM block with a custom header

**What browser and OS are you using?**:
IE11 Win8.1

**What are the manifest and license server URIs?**:
have sent to: shaka-player-issues@google.com

*(NOTE: you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*
*(NOTE: a copy of the manifest text or an attached manifest will **not** be enough to reproduce your issue, and we **will** ask you to send a URI instead)*

**What did you do?**
Arrived at URL: https://abc-dn-jwplayer-stream-tester.s3-ap-southeast-2.amazonaws.com/index-shaka-playready.html
**What did you expect to happen?**
Video should play back
**What actually happened?**
Receive an error of code 3016

**Comment by theodab** [comment]
The 3016 (`VIDEO_ERROR`) error signals that the video element has output an 'error' event. It should include the error event's code, IE11 extended error code, and message in it's `data` property, so you could check those for more information. I don't have a computer with Win 8 on it to check, though.

I was able to try this on Win 10, and it played there without issue. So a license problem does sound likely, yes; decoder errors will definitely lead to a `VIDEO_ERROR`.

Also, for reference, the example player you linked loads the Shaka Player externs. The externs are the public interface of Shaka Player, and do not contain any actual code. You should use `https://cdnjs.cloudflare.com/ajax/libs/shaka-player/2.3.4/shaka-player.compiled.debug.js` instead.

**Comment by joeyparrish** [comment]
@stuartflanagan, did @BucherTomas's comments help?

**Comment by stuartflanagan** [comment]
@shaka-bot reopen

I am very sorry I did not see this notification.

This issue has evolved a bit since I created it and is affecting all browsers including Chrome.

At present we are trying to ascertain if the issue we are experiencing lies with the player, manifest or license acquisition.

The manifests we have been provided are supposed to be configureed identically.
1 plays without issue and the other does not. It does not seem to throw an error but does not playback at all.

Is it possible to get some assistance as to why this may be as the provider of the manifest says that there is no difference in the configuration.

I have emailed 2 files with the streams and a blanket key.

Both have the same configuration but point to a different manifest.

Again sorry for the lateness of my reply.

Kind regards,

Stuart Flanagan.

**Comment by TheModMaker** [comment]
From the files you provided, the one that won't play has an incorrect `pssh` box in the manifest.  The `<cenc:pssh>` element contains a base-64 encoded `pssh` box that contains initialization data sent to the CDM.  In the asset that doesn't work, the key ID in the `pssh` box doesn't match what is encoded in the media.  If I go to `chrome://media-internals`, I can see the browser is blocked waiting for a key, but since the `pssh` contained the wrong key ID, the browser will wait forever.  It also looks like the `pssh` box in the media is correct, so it looks like the value in the manifest is the only thing that's wrong.

Whatever is generating the manifest needs to ensure the key ID and `pssh` in the manifest  match the key ID in the media itself.  Another option might be to set the following config value, which will ignore the `pssh` in the manifest:

```js
player.configure({manifest: {dash: {ignoreDrmInfo: true}}});
```

**Comment by stuartflanagan** [comment]
Thank you very much for the response and information.
I will close this ticket now and provide the information to the generators of the manifest.
