### ISSUE TITLE
Fix flakey CastUtils test

### ISSUE THREAD

**Issue by theodab** [google/shaka-player#1377]
The test `CastUtils serialize/deserialize TimeRanges deserialize into equivalent objects` is flakey on OSX. Sometimes the test will time out; the test itself isn't asynchronous, but the beforeEach on `CastUtils TimeRanges` has to load some mp4 files.

**Comment by chrisfillmore** [comment]
Is this the same as #1215?

**Comment by theodab** [comment]
Yeah.
I guess I had already filed a report for this issue, and just forgotten.
I'll close this one, then. The older report was from when I was previously investigating the flake, and has more detailed information.
