### ISSUE TITLE
Clean up Date mocking in tests

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#1379]
We currently have some test suites which use `jasmine.clock().mockDate()` and others which overwrite Date.now.  Mixing these two styles in one test suite is subtle and doesn't work well.

We should clean up the DASH live tests to use mockDate() exclusively, but this will require refactoring these tests heavily.  Currently, they control timers through `jasmine.clock().tick()` and control the current time separately through `Date.now`.  We should let `jasmine.clock()` fully simulate the passage of time by mocking `Date`, but this will require us to be more careful about how much time we `tick()` by, so get the `Date` we require for the test.

There are two other suites (PresentationTimeline unit and DASH manifest unit) which directly modify `Date.now`, but the cleanup there is less critical.  It may also be simpler to clean up those two, so we should try it anyway.

**Comment by TheModMaker** [comment]
With #1953 we are moving away from PromiseMock, which means the tests will have real delays in them.  The `mockDate` only works with the mock clocks with Jasmine, which requires changing `setTimeout`.  It may be easier and simpler to just use real timeouts and just manually change `Date.now`.  This also allows us to control the current time and the timeouts separately.

Also, using `jasmine.clock().tick()` to handle timeouts is fragile.  Any case when we need to fire a timeout for a test we should do it explicitly.  This ensures that updates to the timeout don't change tests.  As such, we should keep the `Date.now` value separate from when the timeouts fire.

**Comment by joeyparrish** [comment]
This looks like it is done, so I'm going to close it.
