### ISSUE TITLE
setPlaybackRate when video paused

### ISSUE THREAD

**Issue by sanbornhnewyyz** [google/shaka-player#138]
setPlaybackRate behaves inconsistently when paused. If a negative playbackrate is provided when the video is paused, then the video will start playing backwards. But if a value > 1 is given, nothing happens. I think the expected behaviour is that the video would start fast forwarding in the second case. It nicely handles the case where we want to fastforward while the video is paused and it makes setPlaybackRate consistent between fast forward and rewind.

**Comment by tdrews** [comment]
Thanks for the report.

**Comment by tdrews** [comment]
Yep Player.setPlaybackRate is inconsistent. However, I think the behavior should be consistent with how video.playbackRate works; for example,
```
video.pause();
video.playbackRate = 2;
// Stays paused until...
video.play();
```
So we should have
```
video.pause();
player.setPlaybackRate(2);
// Stays paused until...
video.play();
```
and
```
video.pause();
player.setPlaybackRate(-1);
// Stays paused until...
video.play();
```

**Comment by sanbornhnewyyz** [comment]
Yeah, that's a good point.
