### ISSUE TITLE
Error 4012 when Casting using Widevine license with HDCP restriction

### ISSUE THREAD

**Issue by enteractive-dev** [google/shaka-player#1381]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate open issues?**: Yes

**What version of Shaka Player are you using?**: 2.3.4

**Can you reproduce the issue with our latest release version?**: Yes

**Can you reproduce the issue with the latest code from `master`?**: Yes

**Are you using the demo app or your own custom app?**: Custom

**If custom app, can you reproduce the issue using our demo app?**: Could not load custom asset and LA URL. The console logged CORS errors which don't seem right...

**What browser and OS are you using?**: Chrome 65, Windows 7

**What are the manifest and license server URIs?**:
```
https://d4hhk6jc6dmwq.cloudfront.net/de/ble/1727587/201f7a9e52034036af1fc399808ce436/movie/smooth/stream-01.mpd
HDCP V1: https://wv.test.expressplay.com/hms/wv/rights/?ExpressPlayToken=BAAAAAOzaTcAAABgYt0v-_tOdXl1A8izs0rvfwjjKwuVGSkEAF1kdQqO9Uj_8EOXcAhDwCFHFW4Xl566gqE3VlPy1936oFcmRKYsUDFVv0vNbTjHffYHy4VnsolOEc47KVOPT3r5vU0KoMdiKO_Ue4R2qyZ5SJRC72pBBoEprh8
NO HDCP: https://wv.test.expressplay.com/hms/wv/rights/?ExpressPlayToken=BAAAAAOzaXsAAABg3BwCQNP-iFgE-arRdjJrEpk4FsJKKD4bmouOK51EnpT3_Fg0x1XZmGqP-j2C2Di4UTygGTG4OrxcZoe0zokOiJbUpXLTvcJuE38js69nHmaj_IlbhCQSIXuJz9DZIESGD9MMm0WymqjmYvV7XP3TALwUY04
```

**What did you do?**
Created a minimal player app based on the demo:
```javascript
shaka.polyfill.installAll();
var video = document.getElementById('video');
var player = new shaka.Player(video);
var proxy = new shaka.cast.CastProxy(video, player, 'A15A181D');
var controls = new ShakaControls();
controls.init(proxy, function(error) { console.error('error:', error); }, function(casting) { console.debug('casting:', casting); });
player.configure({ drm: { servers: { 'com.widevine.alpha': '...' }}});
player.configure({ drm: { advanced: { 'com.widevine.alpha': { 'audioRobustness': 'SW_SECURE_CRYPTO', 'videoRobustness': 'SW_SECURE_CRYPTO' }}}});
player.load('https://d4hhk6jc6dmwq.cloudfront.net/de/ble/1727587/201f7a9e52034036af1fc399808ce436/movie/smooth/stream-01.mpd');
```

**What did you expect to happen?**
Expected playback on Cast device. (1st gen Chromecast stick and NVidia Shield used for testing)

**What actually happened?**
Playback in Browser works but after switching to the Cast device playback fails with error 4012 when HDCP is enforced in the Widevine license. Without the HDCP option playback starts as intended.

Using Intertrust's Google Cast demo app playback works as intended even with HDCP restriction set:
https://d31lwto7rjo21l.cloudfront.net/chromecast/sender.html

**Comment by karlg-arris** [comment]
Hi,


The Chromecast Gen1 device reports itself as not supporting HDCP validation - at least I can see this in our Widevine proxy logs, therefore it would be expected that playback fails.

**Comment by theodab** [comment]
This looks like more of a Chromecast problem than a Shaka Player problem, yes.
I'll contact someone on the Chromecast team, and tell them to have a look at this.

**Comment by enteractive-dev** [comment]
Thanks for looking into this. How come the Intertrust test app works even with the HDCP restriction enabled? Is it simply ignoring the (reported) device capabilities, starts playback anyway and gets lucky?

**Comment by joeyparrish** [comment]
We consulted the Chromecast team internally, and this appears to be a minor bug in the device firmware on gen1 Chromecasts.  As a workaround, they recommend setting the robustness to "HW_SECURE_ALL", "HW_SECURE_DECODE" or  "HW_SECURE_CRYPTO".  This will trigger a different CDM implementation that reports HDCP correctly.

I am not familiar with the intertrust test app, but I notice there is no robustness setting in the application UI.  If they are hardcoding one of the above robustness values in their application, that could explain the difference.

**Comment by enteractive-dev** [comment]
I was also using Widevine with the Intertrust app. PlayReady seems unproblematic even with high OPLs.

Thanks for the robustness tip. I'll give this a try when I'm back at the office after the Easter holidays but I guess browser playback might fail with these. So we might need separate license settings for each device.

Thank you all. I'll update this issue next week.

**Comment by enteractive-dev** [comment]
As expected at least with older hardware configurations browser playback fails in this situation with anything other than SW_SECURE_CRYPTO.

&nbsp; | Chromecast 1 | Chromecast 2 | NVidia Shield | Philips 32PFS6402/12&nbsp;
-- | -- | -- | -- | --
SW_SECURE_CRYPTO | FAIL | OK | FAIL | FAIL
SW_SECURE_DECODE | OK | OK | FAIL | FAIL
HW_SECURE_CRYPTO | OK | OK | OK | OK
HW_SECURE_DECODE | OK | OK | FAIL | FAIL
HW_SECURE_ALL | OK | OK | FAIL | FAIL

Also it seems https://www.gstatic.com/cast/sdk/libs/mediaplayer/1.0.0/media_player.js defaults to HW_SECURE_CRYPTO which seems to be the lowest common denominator.
