### ISSUE TITLE
Shaka Player 4017 error

### ISSUE THREAD

**Issue by aryan007** [google/shaka-player#1382]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate open issues?**: Yes

**What version of Shaka Player are you using?**: 2.3.3

**Can you reproduce the issue with our latest release version?**: Im using latest version

**Can you reproduce the issue with the latest code from `master`?**:  Yes

**Are you using the demo app or your own custom app?**: demo app 

**If custom app, can you reproduce the issue using our demo app?**: NA

**What browser and OS are you using?**: Mac , Chrome

**What are the manifest and license server URIs?**: https://manifest.prod.boltdns.net/manifest/v1/hls/v5/aes128/5182475815001/261fac78-8dcf-417e-a9c1-47b1e66e873f/10s/master.m3u8?fastly_token=NWFlMjI3ZWRfNWRiNjBiMDlkYWE3MDRmMTM3YWU1M2VlYTAyMGE4ZDc0NzkzZDA0YzY2YWZmOTU1NDJlNzU4ZjdiMmZkYWNhNw%3D%3D
*(NOTE: you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*
*(NOTE: a copy of the manifest text or an attached manifest will **not** be enough to reproduce your issue, and we **will** ask you to send a URI instead)*

**What did you do?** Loaded the manifest file in custom asset

**What did you expect to happen?** Play the video

**What actually happened?** 4017 Error

**Comment by theodab** [comment]
We didn't account for the possibility that a segment tag like `EXT-X-KEY` would be in a media playlist but would come before a media playlist tag, like the `EXT-X-PLAYLIST-TYPE` tag your asset has.
It should be a pretty simple fix. Thanks for the bug report.

**Comment by theodab** [comment]
Ok, now I'm getting a 4030 (`HLS_COULD_NOT_PARSE_SEGMENT_START_TIME`) error. The TS file your manifest is fetching seems messed up. I tried to examine it with ffprobe, and ffprobe errored with the message `Invalid data found when processing input`.

**Comment by joeyparrish** [comment]
The fix for error 4017 has been cherry-picked for v2.3.6.

**Comment by joeyparrish** [comment]
@aryan007, can you double-check that your TS content is valid?  We are unable to read it after fixing the bug in our HLS parser.
