### ISSUE TITLE
PIPELINE_ERROR_DECODE

### ISSUE THREAD

**Issue by samaduttan** [google/shaka-player#1394]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate open issues?**:
yes

**What version of Shaka Player are you using?**:
"version": "2.3.0"

**Can you reproduce the issue with our latest release version?**:
yes

**Can you reproduce the issue with the latest code from `master`?**:
yes

**Are you using the demo app or your own custom app?**:
custom app

**If custom app, can you reproduce the issue using our demo app?**: 
no

**What browser and OS are you using?**:
chrome, firefox, Windows 10

**What are the manifest and license server URIs?**: 
`
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011 DASH-MPD.xsd" xmlns:cenc="urn:mpeg:cenc:2013" profiles="urn:mpeg:dash:profile:isoff-live:2011" minBufferTime="PT5S" type="dynamic" publishTime="2018-04-04T19:28:22Z" availabilityStartTime="2018-04-04T18:22:33Z" minimumUpdatePeriod="PT5S" timeShiftBufferDepth="PT26S" suggestedPresentationDelay="PT15S"> <Period id="0" start="PT0S"> <AdaptationSet id="0" contentType="audio" segmentAlignment="true"> <Representation id="0" bandwidth="191162" codecs="mp4a.40.2" mimeType="audio/mp4" audioSamplingRate="48000"> <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/> <SegmentTemplate timescale="90000" initialization="audio_first.mp4" media="audio_first_$Number$.m4s" startNumber="720"> <SegmentTimeline> <S t="352360650" d="451200" r="1"/> <S t="353263050" d="449280"/> <S t="353712330" d="451200"/> <S t="354163530" d="449280"/> <S t="354612810" d="451200" r="1"/> </SegmentTimeline> </SegmentTemplate> </Representation> </AdaptationSet> <AdaptationSet id="1" contentType="video" width="1280" height="720" frameRate="90000/1501" segmentAlignment="true" par="16:9"> <Representation id="1" bandwidth="3005054" codecs="avc3.64002a" mimeType="video/mp4" sar="1:1"> <SegmentTemplate timescale="90000" initialization="video_first.mp4" media="video_first_$Number$.m4s" startNumber="720"> <SegmentTimeline> <S t="352362991" d="450450" r="6"/> </SegmentTimeline> </SegmentTemplate> </Representation> </AdaptationSet> </Period> </MPD>
`

*(NOTE: you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*
*(NOTE: a copy of the manifest text or an attached manifest will **not** be enough to reproduce your issue, and we **will** ask you to send a URI instead)*

**What did you do?** 
loaded the player in autoplay mode.it was playing fine for some time after that it is getting halted

**What did you expect to happen?** 
Continuous Playback

**What actually happened?** 
Halted the playback after playing for sometime.

The shaka-player("version": "2.3.0") playback getting halted after played for some time.Am getting the failure as PIPELINE_ERROR_DECODE.Attached the error screen shot.

![capture](https://user-images.githubusercontent.com/38025723/38336890-01686590-3829-11e8-9966-b2a8fb984adf.PNG)

**Comment by joeyparrish** [comment]
@samaduttan, please provide manifest URIs, not the contents of the manifest.  We cannot attempt to play your content with the manifest text alone.  Thanks!

**Comment by joeyparrish** [comment]
If you can't give us access to the stream remotely, then it will be very difficult for us to reproduce your issue.  Since it appears to be a live stream, there's no good way to give us a static dump of the content, either.

If you can share the manifest URI privately, you can send it to shaka-player-issues@google.com and it will not leave the team.

Ultimately, if we can't reproduce the issue, we can't help you diagnose the cause.

**Comment by joeyparrish** [comment]
You sent us a manifest privately, but all of the segment requests result in 404 errors.  We need access to both the manifest and the segments in order to reproduce your issue.  Thanks!

**Comment by joeyparrish** [comment]
@samaduttan sent me some relevant info personally, which I didn't realize.  I have forwarded it to the shaka-player-issues alias so the team can take a look.

**Comment by TheModMaker** [comment]
Usually decoder errors are outside our control.  Either the browser can play the content or it can't.  These kinds of errors are either bad content or browser limitations.  I can play the stream fine on Linux, but get errors on Mac and Windows.  Both those platforms use hardware decoders.  If I disable hardware decode in Chrome, the stream plays fine.  What is likely happening is the hardware decoders are more strict than Chrome's software decoders.  The only thing that can be done is to change your content to be playable (I have no insight on how to do this).

Some notes: you can go to `chrome://media-internals` to see a list of the current video players to get better logs.  From there I see two logs that are important.

> Prepared video sample is not conformant

Though it doesn't tell how, and

> Warning: presentation time of most recently processed random access point (55548.6 s) is later than the presentation time of a non-keyframe (55548.5 s) that depends on it. This type of random access point is not well supported by MSE; buffered range reporting may be less precise.

**Comment by samaduttan** [comment]
when i do the playback at the same time in chrome, firefox and Edge, in chrome alone the playback  getting interrupted. 

It is working fine in chrome, if i disable the hardware decoder, but by default the chrome settings is hardware decoder enabled.

**Comment by joeyparrish** [comment]
We believe this is an issue with your content.  If you believe that the content should be playable on hardware decoders as-is, you can file a bug on chrome at crbug.com.

Please let us know if you need any assistance from us on this.
