### ISSUE TITLE
Question on TextTrack Management

### ISSUE THREAD

**Issue by boredom2** [google/shaka-player#1396]
Hi there,

this is not a real "Issue", its more a Question.
Our Players have their own Logic for handling TextTracks and display them by our Logic. Therefore, they handle the List of TextTracks and Cues by themselved and disable/hide them on demand.
We noticed, that the current Behaviour is more-or-less unexplainable, on Media Reload or Media Change, suddenly, all TextTracks are disabled and a "Shaka Text Track" is available (that we didnt put there :P).
I know, that Shaka can handle TextTracks - but is there a way to stop this and stop doing anything with TextTracks? Is there a Method for this (we didnt find one) - or is a special TextRenderer necessary for this?

Thanks a lot!

**Comment by joeyparrish** [comment]
Good question!  We don't have a way to configure Shaka to avoid all text handling.  What we have instead is a plugin to allow applications to handle text rendering.

It's called [TextDisplayer](https://shaka-player-demo.appspot.com/docs/api/shakaExtern.TextDisplayer.html), and you can configure Shaka to plug in your own implementation of this interface.  See the [configuration dictionary definition](https://shaka-player-demo.appspot.com/docs/api/shakaExtern.html#PlayerConfiguration), specifically the `textDisplayFactory` field.

Does this help?

**Comment by boredom2** [comment]
Yeah, I saw this Configuration, but I would prefer to disable all SHAKA Handling of Captions at all - in all other Aspects, I would like to give everything to SHAKA, but not here :) We also handle Tons of Videos in MP4/WEBM Formats without DASH/HLS and also cover Tons of Ads via VAST and VPAID, where all Kinds of Exceptions and Special Caption Treatment is necessary. 
Additionally, we use our Players also on iOS - where SHAKA can sadly not help (yet). So for a consistent Treatment, we will take care of all this ourselves.
Is there a Way to create a TextRenderer, which stops all Text Handling at all (which is probably not really, what it was built for, I agree :P).
