### ISSUE TITLE
Consider adopting Promise.prototype.finally

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#1397]
During our cleanup efforts, we should look into adopting [`Promise.prototype.finally`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally).  There are many cases in which we need to clean up after some asynchronous process, regardless of whether or not it succeeded.

`Promise.prototype.finally` is currently not supported on Safari or Edge, so a polyfill would be needed.  Our [recommended Promise polyfill for IE 11](https://github.com/lahmatiy/es6-promise-polyfill) does not include this post-es6 addition to the Promise spec.

We should balance this against our desire to start using `async/await`, though.  With `await`, it's possible that `try/catch/finally` could be used, without the need for `Promise.prototype.finally`.  If `try/catch/finally` covers all of our needs, it may be easier than requiring/writing yet another polyfill.

**Comment by TheModMaker** [comment]
We no longer use Promise objects directly, we almost exclusively use `await`.  So we have no need to use `Promise.finally`.
