### ISSUE TITLE
No handler for HDCP errors

### ISSUE THREAD

**Issue by allenevans** [google/shaka-player#14]
Currently there does not appear to be a way to listen to any HDCP errors raised by Widevine DRM.

On certain hardware, playback of Widevine protected content has failed to start without any errors being thrown. Turning off the Widevine output protection enables playback on the affected hardware.

It would be very useful to listen to HDCP errors so that an appropriate message can be displayed  when these occur.

**Comment by joeyparrish** [comment]
The necessary EME feature to detect this has not yet landed in Chrome.  We will try to add HDCP error detection as soon as the necessary API is available in Chrome canary.

**Comment by joeyparrish** [comment]
This should be functional in Chrome 39 and 42, but due to a bug, the necessary information is not present in Chrome 40 and 41.
