### ISSUE TITLE
Some text tracks not showing in 2.3.3+, but worked in 2.3.2

### ISSUE THREAD

**Issue by chrisfillmore** [google/shaka-player#1405]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate open issues?**:
Yes

**What version of Shaka Player are you using?**:
2.3.3

**Can you reproduce the issue with our latest release version?**:
Yes

**Can you reproduce the issue with the latest code from `master`?**:
Yes

**Are you using the demo app or your own custom app?**:
Custom app

**If custom app, can you reproduce the issue using our demo app?**:
Unknown

**What browser and OS are you using?**:
Chrome 65 on macOS

**What are the manifest and license server URIs?**:
Unfortunately I can't provide a license url, so you won't be able to reproduce, but you can inspect these manifests, which produce this problem for me:

(this one may expire)
https://csm-e-cedtuswxaws101j8-29egsc6klywa.tls1.yospace.com/csm/live/129868121/1.mpd;jsessionid=11A4747350CAD6DDE0265CE92F61BE9E.csm-e-cedtuswxaws101j8-29egsc6klywa.bln1.yospace.com?yo.up=https://dfwlive-sponsored.secure.footprint.net/Content/DASH.abre/Live/channel(FNCHD-1380.dfw.720.mobile)/&yo.ac=true&yo.ec=503&yo.d.ut=no&externalId=FNCHD-1380.dfw.720.mobile.abre.dash

https://dfwlive-sponsored.secure.footprint.net/Content/DASH.abre/Live/channel(FBNHD-1381.dfw.720.mobile)/manifest.mpd

On the other hand, here are two manifests for which subtitles work fine:
https://dfwlive-sponsored.secure.footprint.net/Content/DASH.abre/Live/channel(CNNHD-8249.dfw.1080)/manifest_mobile.mpd

https://dfwlive-sponsored.secure.footprint.net/Content/DASH.abre/Live/channel(AUDHD-3304.dfw.720)/manifest_mobile.mpd

**What did you do?**
Load the stream and enable subtitles.

**What did you expect to happen?**
Subtitles should show.

**What actually happened?**
Subtitles did not show.

In Shaka 2.3.2: All subtitles display fine on all channels.

In Shaka 2.3.3 or newer, and master branch: Some channels' subtitles display fine, other channels do not show up at all. See manifest URL's above.

The only difference I can discern between working manifests and non-working ones is that non-working ones have a non-zero `presentationTimeOffset`. However, playback of audio and video works fine, so I'm not sure what this might mean. The .vtt files are fetched fine, I can see them in the network panel. But subtitles do not show on screen.

Sorry to not provide a reproducible test case. I will work on putting together a simple test app if I don't make any more progress. In the meantime, any ideas you might have about the difference between 2.3.2 and 2.3.3 with respect to subtitles? Thanks.

**Comment by TheModMaker** [comment]
This appears to be caused by 554cffc.  The problem is that we are using the PTO twice since it is in both the timestampOffset and in the segment times.

**Comment by chrisfillmore** [comment]
Yep, if I add the PTO back in, it works again. That is, I made this hacky change in `TextEngine#appendBuffer`:

```
var pto = /* I just did a hardcoded calculation of pto / timescale from the manifest of the stream I was watching*/;
var time = {
  periodStart: this.timestampOffset_ + pto,
  segmentStart: this.timestampOffset_ + startTime + pto,
  segmentEnd: this.timestampOffset_ + endTime + pto
};
```

**Comment by TheModMaker** [comment]
Actually, thinking about this more, this is the intended behavior.  The PTO should affect the media times as well as the `S@t` attribute.  So in that asset, the cue times in the segment start at 0, but are then adjusted backward by the PTO, so the cues appear before the real segment and are dropped.

See [#1164 (comment)](https://github.com/google/shaka-player/issues/1164#issuecomment-351170643) for some test assets that use PTO and multi-Period text.

**Comment by chrisfillmore** [comment]
@TheModMaker has Shaka been ignoring PTO for media times up until 2.3.3? It appears to be the case, at least for every version between 2.2.8 through 2.3.2.

**Comment by TheModMaker** [comment]
In v2.2.9 we started adding the Period start to the values passed to appendBuffer as a fix for #1164.  Then in v2.3.3 we stopped and used the timestampOffset (Period start - PTO) in TextEngine as a fix for #1232.  But note that appendBuffer only uses those times  for text streams.  So we always have used PTO on audio/video segments, but we have had varying support for PTO on text streams.

**Comment by chrisfillmore** [comment]
@TheModMaker I got some support from the ExoPlayer team because these text tracks are displayed in Exo. See analysis here https://github.com/google/ExoPlayer/issues/4132#issuecomment-381713040

It seems that IOP instructs clients to ignore PTO in cases where subtitles are side-loaded. I realize I did not explicitly say that this was my use case in my original post; sorry for any misunderstanding.

Is Shaka able to differentiate between WebVTT tracks packaged in fmp4 containers versus ones which are side-loaded (for the purposes of timing)? If not, this would seem to be a bug.

**Comment by joeyparrish** [comment]
When VTT is segmented, but not packaged in MP4, the only standard I can find for how to interpret those timestamps is in the context of HLS and an extension that maps VTT cues to units in the MPEG2TS timescale.

Essentially, there is no standard for the interpretation of segmented VTT in text form.

**Comment by chrisfillmore** [comment]
Thanks for your help, I will send this issue back to our packaging teams.

**Comment by chrisfillmore** [comment]
I need to investigate a workaround for this issue on the client. One thing I've tried is processing the manifest response to set `presentationTimeOffset=0` for text tracks only. But this doesn't work. If I do this, Shaka doesn't fetch text tracks at all. I am trying to do this with this manifest:

https://dfwlive-sponsored.secure.footprint.net/Content/DASH.abre/Live/channel(FBNHD-1381.dfw.720.mobile)/manifest.mpd

But the hack I described here https://github.com/google/shaka-player/issues/1405#issuecomment-380564482 does work.

Are different AdaptationSet allowed to contain different PTO values? Are there some circumstances under which Shaka would not fetch segments at all?

**Comment by TheModMaker** [comment]
Each AdaptationSet can have different values for PTO, even each Representation can if they use different segments.  The problem with your manifest is it uses `<SegmentTimeline>`, so the `S@t` attribute will be adjusted by the PTO and we use that to determine where the segments are.  So if you just reset PTO to zero, the segments won't be at the correct time.

One possible solution would be to use `$Number$` instead of `$Time$`, so you can change the PTO without changing the segment URLs.
