### ISSUE TITLE
Three buffering logs on seek

### ISSUE THREAD

**Issue by rounce** [google/shaka-player#1406]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate open issues?**:
Yes
**What version of Shaka Player are you using?**:
master commit 8985f5cfa58a6b18971eefb6d7b9e1bde6bd49cd
**Are you using the demo app or your own custom app?**:
custom app
**If custom app, can you reproduce the issue using our demo app?**:
I think
**What browser and OS are you using?**:
chrome 66, linux
**What are the manifest and license server URIs?**:
*(NOTE: you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*
*(NOTE: a copy of the manifest text or an attached manifest will **not** be enough to reproduce your issue, and we **will** ask you to send a URI instead)*
http://media5.krasview.ru/video/866b3c5b88c4f74/28d74e7fde2d683.mpd
**What did you do?**
Right after load player (before the first segment has time to load) rewind at 1:30 (for example).
**What did you expect to happen?**
One buffering
**What actually happened?**
player.js:2584 onChooseStreams_ {startTime: 0, textStreams: Array(0), variants: Array(1)}
player.js:2596 Choosing new streams after period changed
streaming_engine.js:423 init: completed initial Stream setup
shaka.Player.load @ player.js:790
shaka.Player.load @ player.js:665
streaming_engine.js:1366 (audio:2) looking up segment: presentationTime=89.09519456314838 currentPeriod.startTime=0
streaming_engine.js:2104 fetching: reference= shaka.media.InitSegmentReference {getUris: ƒ, startByte: 0, endByte: 752}endByte: 752getUris: ƒ ()startByte: 0__proto__: Object
streaming_engine.js:2104 fetching: reference= shaka.media.SegmentReference {position: 7, startTime: 70.00816326530612, endTime: 80.01596371882086, getUris: ƒ, startByte: 1069818, …}
streaming_engine.js:1366 (video:1) looking up segment: presentationTime=89.09519456314838 currentPeriod.startTime=0
streaming_engine.js:2104 fetching: reference= shaka.media.InitSegmentReference {getUris: ƒ, startByte: 0, endByte: 825}
streaming_engine.js:2104 fetching: reference= shaka.media.SegmentReference {position: 7, startTime: 70, endTime: 80, getUris: ƒ, startByte: 10022315, …}
streaming_engine.js:752 (all): **seeked: unbuffered seek: clearing all buffers**
streaming_engine.js:785 (audio:2) clear: currently updating
streaming_engine.js:785 (video:1) clear: currently updating
video_wrapper.js:187 Video playback rate changed to 1
streaming_engine.js:1074 (audio:2) skipping update and clearing the buffer
streaming_engine.js:2131 (audio:2) clearing buffer
streaming_engine.js:2139 (audio:2) **cleared buffer**
streaming_engine.js:1366 (audio:2) looking up segment: presentationTime=89.095194 currentPeriod.startTime=0
streaming_engine.js:2104 fetching: reference= shaka.media.SegmentReference {position: 7, startTime: 70.00816326530612, endTime: 80.01596371882086, getUris: ƒ, startByte: 1069818, …}
streaming_engine.js:2104 fetching: reference= shaka.media.SegmentReference {position: 8, startTime: 80.01596371882086, endTime: 90.00054421768708, getUris: ƒ, startByte: 1219467, …}
streaming_engine.js:2104 fetching: reference= shaka.media.SegmentReference {position: 9, startTime: 90.00054421768708, endTime: 100.00834467120181, getUris: ƒ, startByte: 1367584, …}
streaming_engine.js:1074 (video:1) skipping update and clearing the buffer
streaming_engine.js:2131 (video:1) clearing buffer
streaming_engine.js:2139 (video:1) **cleared buffer**
streaming_engine.js:1366 (video:1) looking up segment: presentationTime=89.095194 currentPeriod.startTime=0
streaming_engine.js:2104 fetching: reference= shaka.media.SegmentReference {position: 7, startTime: 70, endTime: 80, getUris: ƒ, startByte: 10022315, …}
streaming_engine.js:1865 (video:1) startup complete
streaming_engine.js:924 (all) setting up Period 0
streaming_engine.js:918 (all) Period 0 is being or has been set up
streaming_engine.js:994 (all) Stream 2 is being or has been set up
streaming_engine.js:994 (all) Stream 1 is being or has been set up
player.js:2676 canSwitch_
streaming_engine.js:2104 fetching: reference= shaka.media.SegmentReference {position: 8, startTime: 80, endTime: 90, getUris: ƒ, startByte: 11543151, …}
streaming_engine.js:2104 fetching: reference= shaka.media.SegmentReference {position: 9, startTime: 90, endTime: 100, getUris: ƒ, startByte: 13016745, …}
player.js:803 Load latency: 19.843
streaming_engine.js:2104 fetching: reference= shaka.media.SegmentReference {position: 10, startTime: 100, endTime: 110, getUris: ƒ, startByte: 14563289, …}
streaming_engine.js:2104 fetching: reference= shaka.media.SegmentReference {position: 10, startTime: 100.00834467120181, endTime: 110.01614512471656, getUris: ƒ, startByte: 1516668, …}
streaming_engine.js:2104 fetching: reference= shaka.media.SegmentReference {position: 11, startTime: 110, endTime: 120, getUris: ƒ, startByte: 16256498, …}
streaming_engine.js:2104 fetching: reference= shaka.media.SegmentReference {position: 11, startTime: 110.01614512471656, endTime: 120.00072562358277, getUris: ƒ, startByte: 1667247, …}
streaming_engine.js:2104 fetching: reference= shaka.media.SegmentReference {position: 12, startTime: 120.00072562358277, endTime: 130.0085260770975, getUris: ƒ, startByte: 1818605, …}
streaming_engine.js:2104 fetching: reference= shaka.media.SegmentReference {position: 12, startTime: 120, endTime: 130, getUris: ƒ, startByte: 17885350, …}

P.S. by the way to get the log it was necessary to slightly change:
diff --git a/lib/media/streaming_engine.js b/lib/media/streaming_engine.js
index a8621357..74e1a37b 100644
--- a/lib/media/streaming_engine.js
+++ b/lib/media/streaming_engine.js
@@ -2101,7 +2101,7 @@ shaka.media.StreamingEngine.prototype.fetch_ = function(reference) {
     request.headers['Range'] = range;
   }
 
-  shaka.log.v2('fetching: reference=' + reference);
+  shaka.log.v2('fetching: reference=', reference);
   let op = this.playerInterface_.netEngine.request(requestType, request);

**Comment by joeyparrish** [comment]
This is only one buffering.  Here's what these logs mean:

> streaming_engine.js:752 (**all**): seeked: unbuffered seek: **clearing all buffers**
This means the StreamingEngine detected a seek and set a flag to clear all buffers.

Audio and video are buffered separately in MediaSource, and so each individual buffer needs to be cleared.  This action is deferred until the MediaSource buffers are idle because MediaSource doesn't allow you to manipulate buffers that are currently being updated.

> streaming_engine.js:1074 (**audio**:2) skipping update and **clearing the buffer**
> streaming_engine.js:2131 (**audio**:2) __clear*ing*__ buffer
> streaming_engine.js:2139 (**audio**:2) __clear*ed*__ buffer

Now the audio update is complete, and we can finally remove the buffered audio data.  Then we can finally start filling the audio buffer with data from the new seek position.

> streaming_engine.js:1074 (**video**:1) skipping update and **clearing the buffer**
> streaming_engine.js:2131 (**video**:1) __clear*ing*__ buffer
> streaming_engine.js:2139 (**video**:1) __clear*ed*__ buffer

This is the same as just above, but specifically for the video buffer.

Does this clear things up for you?

**Comment by rounce** [comment]
But here are three fetching:
streaming_engine.js:2104 fetching: reference= shaka.media.SegmentReference {position: 7, startTime: 70.00816326530612, endTime: 80.01596371882086, getUris: ƒ, startByte: 1069818, …}
Each fetching leads to the loading of the segment via shaka.net.NetworkingEngine request.

**Comment by rounce** [comment]
Thanks.
