### ISSUE TITLE
No TTML subtitle displayed with Live DASH Halo pakager using Shaka 2.3.5 version

### ISSUE THREAD

**Issue by hdodev** [google/shaka-player#1407]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate open issues?**:
Yes, but I didn't find anything recent and opened relative to it. But for information , it's the same packager as the one in #1311.

**What version of Shaka Player are you using?**: 2.3.3 - 2.3.4 - 2.3.5

**Can you reproduce the issue with our latest release version?**: YES

**Can you reproduce the issue with the latest code from `master`?**: YES

**Are you using the demo app or your own custom app?**: BOTH

**If custom app, can you reproduce the issue using our demo app?**: DONE

**What browser and OS are you using?**: CHROME on UBUNTU

**What are the manifest and license server URIs?**:
CLEAR DASH: http://195.36.159.232/cleardashSO_tml/arte/manifest.mpd

**What did you do?**
I tried to playback a Live Stream which contains many audio languages and many TTML subtitles.

**What did you expect to happen?**
The selected language to be heard, and the selected subtitle to be displayed.

**What actually happened?**
The subtitle is not displayed, and we have the following error:
“11:01:02.340 mpd_utils.js:283 SegmentTimeline contains a large gap/overlap: the content may have errors in it. <S t=​"4516177790222" d=​"180000" r=​"164">​</S>​.

Thanks for your help.

**Comment by TheModMaker** [comment]
First, there are CORS errors again, which makes it hard to test.  I also sometimes get 403 Forbidden errors from the segments.  But after disabling CORS I see INVALID_XML errors.  It looks like some of the text segments are missing a `>` in the XML header.

Also note that we, by default, don't stream text streams unless you enable the text tracks.  This can be done in the demo by clicking the 'CC' button, but a custom app needs to call `player.setTextTrackVisibility`.

**Comment by joeyparrish** [comment]
Marked as "bad content" due to the invalid XML.  @hdodev, please let us know if you need any further assistance.

**Comment by hdodev** [comment]
Hi,
In all my tests I didn't find the > missing in XML, but I'm trying. Please let me until next week to make you a definitive feedback.

**Comment by hdodev** [comment]
Finally I think I got it. It'is rather the / character that is badly place when the track is empty:

Not empty case:
<tt xml:lang="fra" xmlns="http://www.w3.org/ns/ttml" ... >
    <head>...</head>
    <body timeContainer="par">...</body>
</tt>

Empty case:
<tt xml:lang="fra" xmlns="http://www.w3.org/ns/ttml" ...
    <head/>
    <body/>
<tt/>

I'll open an issue, and I close the case now. Thanks again.
