### ISSUE TITLE
Would you like to know if this player plays mp3?

### ISSUE THREAD

**Issue by Thiagobhmg** [google/shaka-player#1410]
Would you like to know if this player plays mp3? I really enjoyed offline functionality. Or another audio extension.

**Comment by chrisfillmore** [comment]
It's possible to play mp3 files using an `<audio>` element, Shaka is not required:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio

**Comment by chrisfillmore** [comment]
Ah, then you will want to follow #816, which is the same thing.

**Comment by joeyparrish** [comment]
@Thiagobhmg, for offline playback of MP3, or MP3 playback in general, you don't really need Shaka Player.  You can cache MP3s using the [Cache API](https://developer.mozilla.org/en-US/docs/Web/API/Cache) and play them back using the HTML5 audio element.  Your application itself needs to be available offline as well, [using a Service Worker](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers) to turn the application into a [PWA](https://developers.google.com/web/progressive-web-apps/).

**Comment by ismena** [comment]
@Thiagobhmg does that answer your question? Is there anything else we can help you with?
