### ISSUE TITLE
HLS Live stream - Chromecast reproduction fails

### ISSUE THREAD

**Issue by sergioavazquez** [google/shaka-player#1411]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate open issues?**:
Yes
**What version of Shaka Player are you using?**:
v2.3.6
**Can you reproduce the issue with our latest release version?**:
Yes
**Can you reproduce the issue with the latest code from `master`?**:
Yes
**Are you using the demo app or your own custom app?**:
Demo app

**What browser and OS are you using?**:
Chrome 64 - Ubuntu
**What are the manifest and license server URIs?**:
Shaka demo asset: Shaka Player History (Live, HLS)
Also tested with a custom stream, same result. 
*(NOTE: a copy of the manifest text or an attached manifest will **not** be enough to reproduce your issue, and we **will** ask you to send a URI instead)*

**What did you do?**
Start playing stream, initialize cast from player's controls. 
**What did you expect to happen?**
Content being casted.
**What actually happened?**
Cast reproduction fails.

**Comment by theodab** [comment]
When you say that "cast reproduction fails", do you mean that the receiver app fails to load, or that it loads but fails to play the stream?

I tried casting that sample from our Ubuntu lab machine, and it launched the receiver app but failed to play there. I tried other computers to cast from and other Chromecasts to cast to, and they failed to play Shaka Player History (Live, HLS) also.
Looking at VV output, the cast sender is receiving 'seeking' events, so it might be that the Chromecast is stuck trying to get into the seek window.

**Comment by sergioavazquez** [comment]
It's the same behavior you experienced, it launches the receiver app but fails to play the stream.

**Comment by theodab** [comment]
I tried using my WIP change for #1307, and the asset played correctly. So it definitely looks like this is a problem with the narrow seek window on HLS livestreams.
I think that it is seeking ahead to the start of the window and buffering, but by the time it is done buffering the start of the window has slipped ahead of the buffered range. So it seeks ahead again, and so on and so forth, in a loop.
I suppose you could just wait on the change for #1307, but requiring someone to turn on an optional configuration option just for one of our sample assets to work properly seems non-ideal. Perhaps it'd be better to make the seek range on live HLS a little bit wider than 0s, by default. Investigation will be required.

**Comment by joeyparrish** [comment]
@theodab, how much wider does the seek range need to be to avoid this?  Take a look at 7edb11ba39285bc9f92edbc1b88dbcb163b43c71 and see if MIN_SEEK_RANGE needs to be increased.

**Comment by theodab** [comment]
Ok, I've tried a few values for MIN_SEEK_RANGE. 1s played, but was a bit choppy; it periodically had to pause and seek forward. Of the values I tried, 3s was the smallest that didn't have any choppiness.

**Comment by theodab** [comment]
This change is for the sake of the cast receiver, so you won't be able to see it in effect until we update the cast receiver.
It also doesn't fix things for v1 Chromecasts; no matter how much longer I made MIN_SEEK_RANGE, our test v1 Chromecast was unable to play that livestream reliably. I'll have to look into what additional problem is plaguing our playback on v1 Chromecasts, and address it in a followup CL.

**Comment by joeyparrish** [comment]
The changes that have been made so far are in v2.3.7 and will also be in our upcoming v2.4.0 release.  I'm going to bump this to v2.5 for any additional investigation that is needed.

**Comment by joeyparrish** [comment]
Cherry-picked for v2.4.2.

**Comment by joeyparrish** [comment]
Cherry-picked for v2.3.10.
