### ISSUE TITLE
External text track needs to be enabled twice to become visible

### ISSUE THREAD

**Issue by BucherTomas** [google/shaka-player#1412]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate open issues?**:
yes
**What version of Shaka Player are you using?**:
2.3.6
**Can you reproduce the issue with our latest release version?**:
yes
**Can you reproduce the issue with the latest code from `master`?**:
yes
**Are you using the demo app or your own custom app?**:
both
**If custom app, can you reproduce the issue using our demo app?**:
yes
**What browser and OS are you using?**:
any, Windows 7 and 10
**What are the manifest and license server URIs?**:
no need for that as the issue can be reproduced with demo app and its assets as well

**What did you do?**
Load https://nightly-dot-shaka-player-demo.appspot.com/demo/#asset=https://ams-samplescdn.streaming.mediaservices.windows.net/11196e3d-2f40-4835-9a4d-fc52751b0323/TearsOfSteel_WAMEH264SmoothStreaming720p.ism/manifest(format=mpd-time-csf);lang=cs-CZ;build=uncompiled and click on CC button to enable the text track
**What did you expect to happen?**
Subtitles are visible at approx 00:00:25 when the dialog starts
**What actually happened?**
No subtitles are visible. It is necessary to disable/enable the CC button again or change the language of subtitles in Text languages box for the subtitles to become visible.

Judging by testing previous versions at https://index-dot-shaka-player-demo.appspot.com/ , this issue was introduced in version 2.3.3. External text tracks are being rendered properly right away when enabled up to version 2.3.2.

**Comment by theodab** [comment]
This could possibly be related to the fix for #1293, which was cherry-picked in 2.3.3.

**Comment by BucherTomas** [comment]
Just want to add that although it might seem a cosmetic issue, it negatively affects user experience in our own custom app as well, so some focus on this issue would be very much appreciated.

We do not wish to go back to an earlier version of Shaka.

**Comment by joeyparrish** [comment]
@BucherTomas, I have reproduced and confirmed the bug, and scheduled it for v2.4.  We will attend to it as soon as we can.

Technical details for whoever picks this bug up:

Before enabling subtitles:
  - `video.textTracks[0].mode` evaluates to `"hidden"`
  - `shakaDemo.localPlayer_.isTextTrackVisible()` evaluates to `false`
  - `shakaDemo.localPlayer_.streamingEngine_.mediaStates_.text` is **non-null** (which is a surprise)
  - subtitles are not shown

After enabling subtitles:
  - `video.textTracks[0].mode` evaluates to `"showing"`
  - `shakaDemo.localPlayer_.isTextTrackVisible()` evaluates to `true`
  - `shakaDemo.localPlayer_.streamingEngine_.mediaStates_.text` is non-null
  - subtitles are **not shown**, but should be shown

After disabling subtitles again:
  - `video.textTracks[0].mode` evaluates to `"hidden"`
  - `shakaDemo.localPlayer_.isTextTrackVisible()` evaluates to `false`
  - `shakaDemo.localPlayer_.streamingEngine_.mediaStates_.text` is **null** (as it should be)
  - subtitles are not shown

After enabling subtitles a second time:
  - `video.textTracks[0].mode` evaluates to `"showing"`
  - `shakaDemo.localPlayer_.isTextTrackVisible()` evaluates to `true`
  - `shakaDemo.localPlayer_.streamingEngine_.mediaStates_.text` is **non-null** (as it should be)
  - subtitles **are** shown (as they should be)

**Comment by ismena** [comment]
@BucherTomas sorry for the delay, I'll try to have a CL for this out this week or early next one.

**Comment by ismena** [comment]
Should be working now, let us know if there are any issues.

**Comment by joeyparrish** [comment]
Cherry-picked for v2.3.8.

**Comment by BucherTomas** [comment]
Thank you. Haven't tested our own app yet, but there is still one nit to pick, at least based on Shaka demo app.
1. Load https://nightly-dot-shaka-player-demo.appspot.com/demo/#asset=https://ams-samplescdn.streaming.mediaservices.windows.net/11196e3d-2f40-4835-9a4d-fc52751b0323/TearsOfSteel_WAMEH264SmoothStreaming720p.ism/manifest(format=mpd-time-csf);lang=cs-CZ;build=uncompiled and enable text track with CC button. Subtitles are correctly visible.
2. Click on Load button again without refreshing the page, text track is pre-enabled according to the player UI, however, the subtitles are not visible and need to be re-enabled again by toggling the CC button.

**Comment by joeyparrish** [comment]
Thanks, @BucherTomas, we'll take a look.

**Comment by michellezhuogg** [comment]
Reproduced the bug, will work on the fix.

**Comment by michellezhuogg** [comment]
@BucherTomas, I have reproduced and confirmed the bug, and scheduled it for v2.4. We will attend to it as soon as we can.

**Comment by joeyparrish** [comment]
Fixes cherry-picked for v2.3.8.
