### ISSUE TITLE
Start playback with async license fetch

### ISSUE THREAD

**Issue by simhavenkat** [google/shaka-player#1413]
Question: Does shaka player wait for license exchange before starting playback even it there is a clear lead? Looking at the https://shaka-player-demo.appspot.com/demo e.g. Angel-one - it has a clear lead that i can play without license when i directly download the mp4 - but the demo player doesn't start playing till the license is fetched. 

Is there a way to start playback while the license is being fetched?

**Comment by joeyparrish** [comment]
I'm fairly sure playback does start without waiting for a license exchange.  What makes you say that it doesn't start until the license is fetched?  Can you provide steps to reproduce your results?

**Comment by simhavenkat** [comment]
Mostly eyeballed with eme logger open. The encrypted event and license events happen right in the beginning while the video is preparing to play. I suppose the startup time with or without DRM is comparable to the time it takes to fetch the license? 

I just played one of the widevine videos in the shaka-player-demo.

**Comment by joeyparrish** [comment]
Well, we always start playback without waiting for DRM.  Here's a demo that shows this in action:

https://shaka-player-demo.appspot.com/demo/#asset=https://storage.googleapis.com/shaka-demo-assets/angel-one-widevine/dash.mpd?;license=https://240.0.0.0/this_will_never_respond;play

It's the same Widevine-encrypted Angel One clip, but with the license server set to an address that will not respond.  You will see playback stop after the 10-second clear lead runs out.

I think what you have been seeing is that our license server responds fast relative to the time it takes to fetch segments.

Does this help?

**Comment by simhavenkat** [comment]
Cool - ya - i delayed the license response and see the playback starts. Thanks.
