### ISSUE TITLE
I have a problem when I hide the subtitles in EDGE

### ISSUE THREAD

**Issue by ZarateAF** [google/shaka-player#1414]
Hi, when I play a movie in its original language and it has subtitles in VTT is ok, but when I change to hide the subtitles its no hide  I use setTextTrackVisibility(false) to hide it

I use the 2.3.0 Shaka Player Version 

Thank fort help me and sorry for my english

**Comment by michellezhuogg** [comment]
What manifest did you use? 
Could you please describe the steps to reproduce the issue? Thank you!
