### ISSUE TITLE
Custom Jasmine Functions Not Working With "async function"

### ISSUE THREAD

**Issue by vaage** [google/shaka-player#1415]
In the test framework. The custom jasmine functions (e.g. drm_it) do not handle async functions correctly. For example:

```
drm_it("My Test Name", async function() {
  // My test code
});
```

The above code will not work. It will treat it the same as:

```
drm_it("My Test Name", function() {
  // My test code
});
```

In order to get the correct behavior, the test needs to be written as:
```
drm_it("My Test Name", async function(done) {
  // My test code
  done();
});
```

The custom jasmine test types need to be updated.

**Comment by joeyparrish** [comment]
There may be a way to keep our wrappers (`drm_it` wrapping `it`) without breaking the detection of async functions by `it`.  I'm not sure though.

I'll try to look into it this week.

**Comment by TheModMaker** [comment]
I would think you could just do the following:

```js
function drm_it(name, callback) {
  it(name, async function() {
    // Setup code.

    if (callback.length)
      await new Promise((resolve) => callback(resolve));
    else
      await callback();
  });
}
```

If `callback` has a `done` callback, wrap it in a Promise.  Otherwise, if `callback` is async, it will return a Promise, which will get waited on.  If `callback` is synchronous, it will return `undefined`, which will do nothing in `await`.
