### ISSUE TITLE
Is there any way to track the streaming ?

### ISSUE THREAD

**Issue by Mathieu-R** [google/shaka-player#1416]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate open issues?**: Yes

**What version of Shaka Player are you using?**: 2.3.3

**Can you reproduce the issue with our latest release version?**: Yes

**Can you reproduce the issue with the latest code from `master`?**: Yes

**Are you using the demo app or your own custom app?**: Custom app

**If custom app, can you reproduce the issue using our demo app?**: Yes

**What browser and OS are you using?**: Chrome 65 and OS X 10.13.3

**What are the manifest and license server URIs?**:
*(NOTE: you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*
*(NOTE: a copy of the manifest text or an attached manifest will **not** be enough to reproduce your issue, and we **will** ask you to send a URI instead)*

**What did you do?**
Is there any way to track the download of the segments as we are streaming. I would like to measure the quantity of data streamed.

**What did you expect to happen?**
Something like this.
```js
const player = new shaka.player(mediaElement);
player.onStream = evt => {
  const {value} = evt; // content-length of the chunk fetched.
 ...
}
```

**What actually happened?**
That's a question so.

**Comment by ismena** [comment]
Hi @Mathieu-R, could you elaborate a bit? Are you interested in the number of segments downloaded? Or number of bytes? (Or something else? :))

**Comment by Mathieu-R** [comment]
The number of bytes downloaded.

Everytime, I do a `player.load(manifestURL)`, I would like to be able to track the number of bytes streamed.

My use case is that I would like to allow the user in my app to set a limit of data. He would be able to set let's say 500mo of max data volume. 
Once he reached that volume, I disable the possibility to play a song (until next month for instance) that is not put in cache (in my case - service worker - cache api).

I could also show a beautiful UI where I could show how much data he consumed this month in my app.

For now I am only able to track how much data is downloaded (by `download` I mean through a button who performs some `fetch()` and put the responses in the cache-api) because I have a control on the response object but not how much data is streamed.

Hope it is clear 😀

**Comment by Mathieu-R** [comment]
Yeah it seems.
I'm gonna try this.

Thanks a lot 😀

**Comment by ismena** [comment]
My pleasure. Please reach out if you need more help.
