### ISSUE TITLE
Video Adaptation Switching for DASH

### ISSUE THREAD

**Issue by sparkyish** [google/shaka-player#1418]
There does not appear to be a way to switch video adaptations within Shaka player. This is necessary to support multi-camera events (a current need for upcoming projects). 

From [previous issues](https://github.com/google/shaka-player/issues/679), it looks like switching video adaptations (tracks) was abandoned to support limitations in HLS - where you can only select by _Variants_ (audio/video pair). In DASH, there is no requirement to switch in pairs, and the video adaptation can be selected independently. Will Shaka support video adaptation switching?

Below is a test URL for a DASH event with 2 multi-bitrate video adaptation sets. This content was encoded with bitstreamSwitching enabled, which _allows a switched sequence of Media Segments to be decoded without resetting the decoder at switch points because the resulting Segment stream is a valid track of the source type (so the decoder is not even aware of the switch)_. Reference [DASH-IF 3.2.10](http://dashif.org/wp-content/uploads/2017/09/DASH-IF-IOP-v4.1-clean.pdf).

Manifest: http://storage.googleapis.com/lao-permanent_content/2018-04-20-13-40-31/Manifest.mpd

Shaka Demo: https://shaka-player-demo.appspot.com/demo/#asset=https://storage.googleapis.com/lao-permanent_content/2018-04-20-13-40-31/Manifest.mpd;lang=en-US;build=uncompiled

**Comment by joeyparrish** [comment]
Shaka Player already supports adapting video streams.  Without that, we wouldn't be an ABR player!

To switch video streams manually, disable ABR with `player.configure()` and use `player.selectVariantTrack()` to select a specific track.

I'm not sure, but it sounds like you're actually looking for support for multiple camera angles.  Is that right?

**Comment by sparkyish** [comment]
@joeyparrish I think the way Shaka currently uses the term "adaptation" confuses this conversation. I'd like to clarify the terms dealing with ABR between HLS & DASH to help.

With HLS, multiple versions of the same content encoded in different ways (with differences in bitrate, resolution, etc) are called [**Variant Streams**](https://developer.apple.com/library/content/technotes/tn2224/_index.html#//apple_ref/doc/uid/DTS40009745-CH1-ENCODEYOURVARIANTS). Alternate versions of content, such as audio produced in different languages or video recorded from different camera angles, are called [**Renditions**](https://tools.ietf.org/html/draft-pantos-http-live-streaming-23). 

With DASH, multiple versions of the same content are called **Representations**, and alternate versions of content are called **Adaptations**. ABR is possible by switching between _representations_; alternate languages and camera angles are possible through switching _adaptations_. If you need more reading, [here](https://www.brendanlong.com/the-structure-of-an-mpeg-dash-mpd.html) is a short a quick blog post about it. In my opinion, creating content with multiple representations and multiple adaptations in DASH is significantly more straight-forward than HLS.

I believe Shaka calls a change in the stream due to network conditions an _adaptation_, hence the confusion, since with DASH an adaptation is different content instead of a change in quality. So in essence, yes I am looking to support multiple camera angles, but those are contained in DASH adaptations, which I do not think are supported correctly in Shaka at the moment.

**Comment by ismena** [comment]
@sparkyish In terms of us adopting HLS Variant structure, let me also add that while we did change our internal structure to operate on audio+video pairs, for DASH we create all possible combinations, so if you want to switch from playing audio1+video1 to still playing audio1, but with video2 instead there is going to be an audio1+video2 variant!
(Let me know if that explanation was unclear, I'll give more detail and examples).

So, while the switch to variants makes operating with DASH less intuitive, you should still be able to get the behavior you want.

Is that helpful? I'm not entirely sure, but it sounded like you were ultimately interested in switching video without changing audio. If that's the case we can provide guidance on how to accomplish that in the new variant world.

**Comment by ismena** [comment]
@sparkyish yup, your idea is correct, I was going to suggest something along these lines.
You can use player.getManifest() to get the [manifest object](https://github.com/google/shaka-player/blob/master/externs/shaka/manifest.js#L91).
manifest.periods[i].variants will give you all the variants for a given period.
individual streams can be accessed by variant.video and variant.audio.

You will need to keep track of the stream ids when you show the adaptations to the users, so you can later map their choices to the the streams and variants.
Sorry, I know this is way more complicated than it used to be when we only had DASH support, but it was the most meaningful way for us to add support for HLS.

Let us know if you run into complications, I'll help with the code and debug with you if need be :)
