### ISSUE TITLE
Unable to use own Chromecast APP ID

### ISSUE THREAD

**Issue by frhi** [google/shaka-player#1424]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate open issues?**: Yes

**What version of Shaka Player are you using?**: 2.3.7

**Can you reproduce the issue with our latest release version?**:

**Can you reproduce the issue with the latest code from `master`?**:

**Are you using the demo app or your own custom app?**: custom app based on demo app

**If custom app, can you reproduce the issue using our demo app?**: n/a

**What browser and OS are you using?**: Chrome on Windows 10

**What are the manifest and license server URIs?**:
*(NOTE: you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*
*(NOTE: a copy of the manifest text or an attached manifest will **not** be enough to reproduce your issue, and we **will** ask you to send a URI instead)*

**What did you do?**
Used our own Chromecast APP ID instead of the Shaka Demo APP ID

**What did you expect to happen?**
Chromecast works great using the Shaka Demo APP ID, so expected it to work same with our own APP ID.

**What actually happened?**
Chromecast doesn't work when we use our own APP ID. Summary below.

If we use the Chromecast APP ID that is used in the Shaka Demo (CC_APP_ID = 'A15A181D'), everything works great. If I change that APP ID to our own, then Chromecast does not work. When I press the cast button, everything acts like it is going to work, but then the television I'm casting to just shows a black screen with white text in the middle stating our app name and the video never loads. If I try using the default media receiver APP ID (chrome.cast.media.DEFAULT_MEDIA_RECEIVER_APP_ID), the result is basically the same. The television I'm casting to just shows a black screen with a blue chromecast logo in the center.

Any ideas on why Shaka and Chromecast don't work when we change the APP ID?

**Comment by frhi** [comment]
We were using a Styled Media Receiver. I have not developed for Chromecast before and didn't realize we needed to make a custom receiver app. So I took a look at the Shaka receiver app you mentioned and we've got it working now. Thanks for the help!

**Comment by ismena** [comment]
@frhi Glad we could help! Please reach out in the future if you need anything :)
