### ISSUE TITLE
Multiple media elements per stream

### ISSUE THREAD

**Issue by chrisfillmore** [google/shaka-player#1425]
In the media element spec, it describes how two video elements can be kept in sync if their content is related:

> A MediaController is an object that coordinates the playback of multiple media elements, for instance so that a sign-language interpreter track can be overlaid on a video track, with the two being kept in sync.

https://dev.w3.org/html5/spec-preview/media-elements.html#synchronising-multiple-media-elements

This use case actually seems comparable to #1418, where the same content is represented with different camera angles, and the user can pick between them. A user could also want to watch multiple at the same time. Thus, multiple video elements could be used to render content described by a single manifest.

To be clear, I do not personally have a requirement for this. It looks like a lot of work. It's just a thought, although my team is always exploring potential new features.

**Comment by ismena** [comment]
@chrisfillmore thanks for the idea!
@joeyparrish is this something we're interested in working on? I'm adding the issue to backlog for now.

**Comment by joeyparrish** [comment]
Let's leave it in the backlog for now, since we don't have any partners who require this at the moment.  If someone needs something like this, we can consider it in a subsequent round of release planning.

**Comment by avelad** [comment]
Is anyone interested in this? If not, the issue will be closed in 7 days.
