### ISSUE TITLE
Is there any way to crossfade between 2 tracks while streaming ?

### ISSUE THREAD

**Issue by Mathieu-R** [google/shaka-player#1428]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate open issues?**: Yes

**What version of Shaka Player are you using?**: 2.3.3

**Can you reproduce the issue with our latest release version?**: Yes

**Can you reproduce the issue with the latest code from `master`?**: Yes

**Are you using the demo app or your own custom app?**: custom app

**If custom app, can you reproduce the issue using our demo app?**: Yes 

**What browser and OS are you using?**: Chrome 66 and OSX 10.13.3

**What are the manifest and license server URIs?**:
*(NOTE: you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*
*(NOTE: a copy of the manifest text or an attached manifest will **not** be enough to reproduce your issue, and we **will** ask you to send a URI instead)*

**What did you do?**

I'm using the Google Shaka-Player to stream musics in my app. In this one I can launch a tracklist.

How can I do with the help of the `Web Audio API` to crossfade between two tracks while they are streaming ?

Is there something in the library that I'm not aware of and that could help me ?

I've heard of extra-buffering but I do not really know how it should works nor how I could implement it.

Thanks.

(Btw, I tried to ask this question on stackoverflow but received no answers)

**What did you expect to happen?**
Crossfade between the music that is streaming and the next one that will be streamed.

**What actually happened?**
That's a question ;)

**Comment by michellezhuogg** [comment]
Shaka Player doesn't really interact with Web Audio API, and doesn't support streaming two audio tracks at the same time so far.
However, to implement crossfading, you can have multiple Player instances, so that you can have two tracks streaming at the same time.
If you have any specific questions when implementing crossfading, let us know and we'd love to help.

**Comment by TheModMaker** [comment]
We have little to no experience with the Web Audio API, so we can't really help much.  But you should be able to use a [MediaElementAudioSourceNode](https://developer.mozilla.org/en-US/docs/Web/API/MediaElementAudioSourceNode) to create a source object from the `<video>` element and then use that as part of cross-fading.  The fact that we are streaming into the `<video>` shouldn't make any difference.

**Comment by Mathieu-R** [comment]
Yes.
