### ISSUE TITLE
Live playback doesn't start - are segments in the future?

### ISSUE THREAD

**Issue by chrisfillmore** [google/shaka-player#1430]
If you guys are willing, I was hoping you could validate my analysis of a problem I'm having with a live stream. I am using Shaka v2.3.4. I am trying to play this manifest:

https://dfwlive-sponsored.secure.footprint.net/Content/DASH.abre/Live/channel(ECTV-2819.dfw.480.mobile)/manifest.mpd

As far as I can tell, the segments are in the future, so playback never starts, and Shaka fetches updated manifests indefinitely.

Using values from my recent testing:

_Live edge is:_
(current time + clock offset) / 1000 - availabilityStartTime
= ((1525296979574 + (-22925)) / 1000) - 0
= 1525296956.649

_First segment start time is:_
availabilityStartTime + Period@start + (S@t - presentationTimeOffset) / timescale
= 0 + 1525016546.358 + (193582283794 - 0) / 90000
= 1527167460.6223779

Thus the segments are ~3 weeks in the future.

If this is correct, are there multiple possible paths to resolution? It's not clear to me which value is wrong: Period@start, S@t, PTO...?

I appreciate any insight you can offer. Thanks for the help.

**Comment by chrisfillmore** [comment]
Interestingly, the distance from the live edge appears to be growing. Today segments are ~24 hrs further from the live edge than it was last night.

**Comment by chrisfillmore** [comment]
I now understand that Exo has the behaviour described in #999, and ignores device time in cases of SegmentTemplate + SegmentTimeline.

Our packager restarted the stream last night and it works, but has advised us that it will be a bit unstable as they identify the problems they're having.

Thanks, I will close.

**Comment by joeyparrish** [comment]
Okay.  Sorry I wasn't able to get to this fast enough to be helpful.  We are going to be working toward v2.5 very soon, and #999 is at the top of my agenda for that release.
