### ISSUE TITLE
Android MediaDrm provisioning fails on closed network

### ISSUE THREAD

**Issue by grantg182** [google/shaka-player#1433]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate open issues?**:
Yes.
**What version of Shaka Player are you using?**:
2.3.7
**Can you reproduce the issue with our latest release version?**:
Yes
**Can you reproduce the issue with the latest code from `master`?**:
Yes
**Are you using the demo app or your own custom app?**:
Both
**If custom app, can you reproduce the issue using our demo app?**:
Yes
**What browser and OS are you using?**:
Chrome 66.0.3359.126

**What did you do?**

Deployed Shaka player to an offline media server, which also hosts the Widevine license server.

On some Android devices, all using the latest Chrome 66 build, with a variety of hardware manufacturers including Huawei, Samsung and LG, some of these devices fail to even request a license in an offline server environment (neither our server nor client devices have internet access). However, the same client devices which receive this error can also successfully play back Widevine-encrypted content from the Shaka demo site. Inspecting the network traffic of each client device, none of the devices which produce this error are attempting to call our license server.

We deployed the same instance of shaka player onto an internet-enabled server and were able to get to the license server request stage, which failed due to not being able to connect to our offline server, as expected.

From this, I believe the only difference between these two setups is that one server has internet access and the other does not. As far as I know, the non-working devices have been provisioned by WV and can play other WV encrypted content online without any issues.

**What did you expect to happen?**
License requested and obtained followed by video playback.
**What actually happened?**
Upon loading the player and attempting to play, I get:-

Shaka Error DRM.FAILED_TO_GENERATE_LICENSE_REQUEST (Create session aborted.)

This is followed by further errors, such as "failed to get buffered range for audio DOMException: Failed to read the 'buffered' property from 'SourceBuffer': This SourceBuffer has been removed from the parent media source.". I suspect these errors happen because the license request failure.

The video does not even attempt to play the first 10s of clear video, but it does on the internet-enabled server before stopping playback at 10s due to the network connectivity to our offline servers license server failing.

I have attached a sample MPD in case this is believed to be an issue with our packaging, which I do not think is the case. 
[Tears_Of_Steel-En.mpd.txt](https://github.com/google/shaka-player/files/1974950/Tears_Of_Steel-En.mpd.txt)

Is there anything obvious we should be doing to resolve this? Known bugs, or otherwise plain stupidity on our part? Thanks!

**Comment by Murmur** [comment]
You are using ShakaPackager? Do you provide `--clear_lead 0` parameter so that all the segments from 0..n are encrypted, default I guess is first 10s is not encrypted.

**Comment by grantg182** [comment]
Yes, we are using the ShakaPackager but are not specifying the --clear_lead parameter - in any case, the devices which fail to playback do not even attempt to playback the first 10s of default clear content.

**Comment by joeyparrish** [comment]
@grantg182, I admit, I'm not sure what this could be.  I am having trouble following some of the details.  Let me see if I can ask some clarifying questions:

 - Your license server does not have access to the open internet, correct?
 - Are you trying to set up some kind of self-contained, isolated network that can still give out content licenses locally?
 - Your license server is not a Widevine license server proxy, correct?
 - What network traffic is sent by the browser?
 - Are there any connections attempted from the browser out to the internet?
 - What network traffic is sent by the license server?
 - Are there any connections attempted from the server out to the internet?

Thanks!

**Comment by grantg182** [comment]
Hey @joeyparrish 

Your license server does not have access to the open internet, correct?
That is correct, it is hosted on the local server in an offline environment.

Are you trying to set up some kind of self-contained, isolated network that can still give out content licenses locally?
Yes, that is correct. 

Your license server is not a Widevine license server proxy, correct?
Correct, the license server is a Docker component and is fully accessible on the network (in requests, inspecting traffic, etc, via other devices, including Android devices from Samsung).

What network traffic is sent by the browser?
Absolutely none. On Desktop Chrome, we can see the license server request coming from the browser and can inspect this no problem. However, on the Android devices which are failing, there is not even a request made to the license server.

Are there any connections attempted from the browser out to the internet?
No, all requests go to our local proxy server which forward on to the license server; all within the local network. Inspecting the Android logs, shortly before and after the failure (presumed) of GenerateKeyRequest, there are attempts by the devices to connect to api.google.com (or similar, definitely a google URL containing api, though this may be a red herring with the Android devices attempting to upload/download data to other Google services).

What network traffic is sent by the license server?
None, since the Chrome browser on these Android devices are not even making a request to the license server. 

Are there any connections attempted from the server out to the internet?
No, I have inspected all network traffic and access logs and can confirm neither client nor server attempts to connect to the internet.

What I suspect, is that the devices are being provisioned by Widevine on a domain basis, though I am not able to confirm this as yet. If I remove the Media Licenses within Chrome and go back to the UAT demo video, I get the "premium content" popup and then can get successful playback after accepting. Then connecting solely to our intranet, I get the same "premium content" popup, upon acceptance, no playback and the error as before. It was my understanding devices were provisioned once with Widevine, but it appears that may not be the case.

If it helps, I posted some of the logs from Android on the Widevine forum, in case that sheds any light.

I am 99% certain this is not an issue with Shaka itself, though I intend to deploy an instance of dashJS or similar tomorrow to remove any doubt.

Thanks again!

**Comment by joeyparrish** [comment]
I think this is something going wrong at the Android OS layer.  If the browser is not making any network request, then this is not something Shaka Player can control.

It's possible that there is some provisioning step needed by the Android CDM, and that it happens outside of the control of the JavaScript application.  I don't know for sure, though.

I will try to ask a colleague who works on Chrome and see if they have any insight.

**Comment by grantg182** [comment]
Thanks @joeyparrish - some insight from other teams would be great!

You would think the CDM would 'just work' after being provisioned - it works on all other Widevine-encrypted content using a variety of other players on the internet, but not on our network, before and after getting successful playback on the open internet.

Quite worrying really; I've had more device failures than successes; even more so because every Huawei device has failed with the same error - and look to be overtaking as the second largest smartphone manufacturer!

Cheers

**Comment by joeyparrish** [comment]
According to my colleague, what is happening is that MediaDrm requests that the device be provisioned, and Chrome handles the provisioning request under the hood.  This request goes to a central address, which is not accessible on your network.

So the next question should be: Why does the device need to be provisioned again?

I don't know enough about MediaDrm to speculate, but I believe the answer lies there.  Shaka Player talks to Chrome, which talks to MediaDrm.  MediaDrm asks Chrome to send a provisioning request, but I don't know how MediaDrm decides that.  Hopefully you can find the answer in the MediaDrm docs.

I will leave this marked as "external" for now (to indicate a problem outside Shaka Player) and rename the issue to reflect what we've learned so far.  Please let us know what you find about MediaDrm, and please let us know if we can do anything more to help.

**Comment by grantg182** [comment]
Thank you again @joeyparrish ! Much appreciated.

That makes sense, given the testing we have done. I was afraid that was going to be the outcome. |

I'll have a dig through the MediaDRM documentation, if I can locate it, and see what we can find out and where we can go next.

Thanks again,
Grant

**Comment by onetae** [comment]
Hi @grantg182 
Did you solve this after? I am having the same problems with offline android and would like to compare notes. 
Thanks Matt

**Comment by grantg182** [comment]
Hi @onetae 

Unfortunately you will require an Offline Provisioning Server to resolve the issue. You'll find everything works just fine in Chrome <58 - it seems that the VMP update for Chrome also slipped in this change which means devices need provisioned every time (or at least, for every domain, license retrieval attempt, or _something_).

So far, I have not had great success from the Widevine team in obtaining such a thing.

**Comment by onetae** [comment]
Hi @grantg182
Thanks for the info, you saved me a few days which I would of spent coming to the same conclusion.
We contacted Widevine and they are aware of this problem, and looking to solve it.
Which isn't much good to us.
Regards

**Comment by ryancl01** [comment]
@grantg182 Have you tried setting the service certificate for the client as outlined in page 30 of the License Server SDK document?  If you need more detailed instructions please send me a message and I can further assist off of github.

**Comment by grantg182** [comment]
@ryancl01 No, I have not. The Widevine Partner License SDK document I have is v1.12.1 which only has 23 pages. I get a 403 on the Widevine SDK document link within the CWIP portal too, so cannot currently access the latest documentation for some reason(?). Alas, I'll try figure out how to PM you...

**Comment by ryancl01** [comment]
@grantg182 Hi Grant no problem I just sent you an email with the latest document.

**Comment by grantg182** [comment]
@ryancl01 Great, thank you!

**Comment by Murmur** [comment]
Is that doc available for everyone? I could use it as well.

**Comment by onetae** [comment]
Hi Guys,
You can also set the serverCertificate in the Shaka player in the advanced drm area:
You set it as a Uint8Array, see below.

I tried both ways: setting it in the player and setting it in the widevine SDK as stated in the document.

But still have no luck with later versions of Android.

      player.configure({
            drm: {
              servers: { 'com.widevine.alpha': 'https://widevineServer/?id=ac5499b1-4240-4616-b475-c8440d5ffeea' }
           , advanced: {
                  'com.widevine.alpha': {
                  **'serverCertificate' : arryCert,**
                  'distinctiveIdentifierRequired' : false,
                  'videoRobustness': 'SW_SECURE_CRYPTO',
                  'audioRobustness': 'SW_SECURE_CRYPTO'
                          }
                        }
            }
        });

**Comment by ryancl01** [comment]
All, 

Which version of Android did you first notice this problem?

Thanks,
Ryan

**Comment by grantg182** [comment]
@ryancl01 We have tested with a variety of devices with various versions of Android and Android forks.

Up to and Chrome 58, we have no issues with license requests in an offline environment on any of these devices.

After Chrome 59, here are some examples of devices I tested 2 months ago:-

Samsung Galaxy S8 - Android 7.0, Chrome 66
Samsung Galaxy S6 -Android 7.0, Chrome 66
Huawei Nova Lite - Android 7.0, Chrome 66
Huawei P8 - Android 6.0, Chrome 66

However, in the same environment, the following devices did successfully get a license and successfully played Widevine-encrypted content:-

LG V30 - Android 8.0.0, Chrome 66 
Samsung Note 3 - Android 5.0, Chrome 66 *

*Note, that for this device, it is possible that it had previously received a license via another license server which did have internet access some 12+ months ago, so on a previous version of Chrome but same Android version. Unable to verify further by factory reset as this is a colleagues personal device.

Thanks,
Grant

**Comment by ryancl01** [comment]
Thank you Grant.  I am working with Chrome engineering to investigate this and hope to have an update soon.

**Comment by TboneX** [comment]
@ryancl01 Is there any news on this matter? It's been a couple of months now

**Comment by garfieldjty** [comment]
@ryancl01 We are facing the same issue now with Chrome and Firefox. Is there any news about this issue?

**Comment by grantg182** [comment]
@garfieldjty just as an FYI, this issue is tracked by Chromium here - https://bugs.chromium.org/p/chromium/issues/detail?id=866625

Note, it is targeted for Chrome 74. It has previously been targeted for Chrome 70, 71, 72 and 73. However, it has been 'started' and 'assigned' to a Chromium dev since January 11th. As yet, it is still not working in the latest build of Canary.

**Comment by joeyparrish** [comment]
Closing this stale external (non-Shaka) issue. If you disagree, please reply with @shaka-bot reopen, and it will be automatically reopened.
