### ISSUE TITLE
Video artifacting in Canary 68.0.xxxx

### ISSUE THREAD

**Issue by chrisfillmore** [google/shaka-player#1441]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate open issues?**:
Yes

**What version of Shaka Player are you using?**:
v2.3.4

**Can you reproduce the issue with our latest release version?**:
Did not check

**Can you reproduce the issue with the latest code from `master`?**:
Yes

**Are you using the demo app or your own custom app?**:
Demo app

**What browser and OS are you using?**:
macOS Canary 68.0.3415.0, and newer versions

**What are the manifest and license server URIs?**:
Sent by email

**What did you do?**
Load the stream

**What did you expect to happen?**
Video should play clearly

**What actually happened?**
Video showed artifacting / blocking throughout

I have filed a Chromium ticket with more details:
https://bugs.chromium.org/p/chromium/issues/detail?id=844799

Could you please forward the manifest url on to Chrome team?

![artifacting_demo](https://user-images.githubusercontent.com/7190265/40263113-bc9fe660-5ac2-11e8-83a7-660398388052.png)

**Comment by chrisfillmore** [comment]
This issue is easily reproduced in Canary with `--enable-features=MseBufferByPts` and the stream provided, see analysis here:
https://bugs.chromium.org/p/chromium/issues/detail?id=844799#c33

This is now an issue for our video engineering group to tackle, so I will close. Maybe you'd like to tag as Chrome PTS/DTS?

Thanks for the help!

**Comment by joeyparrish** [comment]
Done.  Thanks!
