### ISSUE TITLE
require shaka-player in nodejs

### ISSUE THREAD

**Issue by mimse** [google/shaka-player#1445]
**What version of Shaka Player are you using?**:
2.3.7

**Can you reproduce the issue with our latest release version?**:
Yes

**Can you reproduce the issue with the latest code from `master`?**:
Yes

**Are you using the demo app or your own custom app?**:
No

**If custom app, can you reproduce the issue using our demo app?**:

**What browser and OS are you using?**:
Nodejs 8.x.x macOS Sierra

**What did you do?**
Trying to import shaka-player in nodejs for server-side rendering

**What did you expect to happen?**
Import without errors

**What actually happened?**
![image](https://user-images.githubusercontent.com/1250254/40474356-1a355cda-5f3f-11e8-9722-8cb908c812ac.png)

For a more in-depth discussion look at this issue 

https://github.com/sampotts/plyr/issues/935

**Comment by joeyparrish** [comment]
Cherry-picked for v2.3.9 and v2.4.1.
