### ISSUE TITLE
DASH multi-period live stream - Assertion failed: This should be an update of the last segment in a period

### ISSUE THREAD

**Issue by plzhang** [google/shaka-player#1448]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate open issues?**:
Yes
**What version of Shaka Player are you using?**:
Shaka Player v2.4.0-uncompiled
**Can you reproduce the issue with our latest release version?**:
Yes
**Can you reproduce the issue with the latest code from `master`?**:
Yes
**Are you using the demo app or your own custom app?**:
Demo App
**If custom app, can you reproduce the issue using our demo app?**:
Yes
**What browser and OS are you using?**:
Chrome on Linux
**What are the manifest and license server URIs?**:
Sent.

**What did you do?**
Loaded the stream and checked the log console in developer tools.

**What did you expect to happen?**
Stream playback is good, and no errors shown in the console.

**What actually happened?**
Stream playback is good, but with error in console:
Assertion failed: This should be an update of the last segment in a period.

**Comment by theodab** [comment]
It looks like we might have a bad assertion. I'll look into it more, thanks for reporting.

**Comment by joeyparrish** [comment]
Cherry-picked for v2.3.9 and v2.4.1.
