### ISSUE TITLE
CatchUP Content not working 

### ISSUE THREAD

**Issue by ronenneumark** [google/shaka-player#1450]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate open issues?**:
Yes

**What version of Shaka Player are you using?**:
2.4.0
**Can you reproduce the issue with our latest release version?**:
yes
**Can you reproduce the issue with the latest code from `master`?**:
yes
**Are you using the demo app or your own custom app?**:
demo app
**If custom app, can you reproduce the issue using our demo app?**:

**What browser and OS are you using?**:
Win chrome
**What are the manifest and license server URIs?**:
https://sportstv-cdvr.akamaized.net/Cars_TV/manifest.mpd?begin=20180527T081000&end=20180527T082000

**What did you do?**
hit Play
**What did you expect to happen?**
Stream should play
**What actually happened?**
freeze on first frame and buffering

**Comment by theodab** [comment]
It wasn't me!
Glancing at this, it seems to play sometimes. And when it does play, it doesn't mention gap jumping. So I agree that it's related to gap jumping somehow.

**Comment by TheModMaker** [comment]
`chrome://media-internals` reports the following logs:

> Parsed video frame has DTS 88572646555us, which is after the frame's PTS 88572579822us

> Warning: presentation time of most recently processed random access point (7.54188 s) is later than the presentation time of a non-keyframe (7.47514 s) that depends on it. This type of random access point is not well supported by MSE; buffered range reporting may be less precise.

It looks like we seek to exactly the start of the buffered range, but the video doesn't move forward.  My guess would be the seek was inaccurate and caused the browser to stall.  These warnings should be fixed in your content.

We could introduce a fudge factor when we seek in gap jumping, but in your content, we would need to set it to at least 0.05 to work, which seems like a lot for a fudge factor.  It would be better to fix your content.

**Comment by joeyparrish** [comment]
@ronenneumark, have you had a chance to read the earlier replies from the team?  Is this helpful?  Is there anything else we can do for you?

**Comment by ronenneumark** [comment]
HI @joeyparrish - thanks for your help! we ask our content provider to make the needed changes and work with a standard DTS/PTS settings

**Comment by joeyparrish** [comment]
Okay, great.  I'm going to go ahead and close the issue, then, but please feel free to let us know if it needs to be reopened.  Thanks!
