### ISSUE TITLE
Shaka Player repeatedly throws the warning "Assertion failed: SegmentReferences are incorrect" when playing certain DASH assets

### ISSUE THREAD

**Issue by ravics78** [google/shaka-player#1451]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate open issues?**: Yes.

**What version of Shaka Player are you using?**: 2.3.7

**Can you reproduce the issue with our latest release version?**: Yes

**Can you reproduce the issue with the latest code from `master`?**: Yes

**Are you using the demo app or your own custom app?**:custom  portal that launches shaka player

**If custom app, can you reproduce the issue using our demo app?**: It is reproduceable

**What browser and OS are you using?**: The shaka player runs on a Set- Top-Box on Ekioh browser

**What are the manifest and license server URIs?**: 
Manifest URL: http://85.206.131.32/live/eds/LRT_HD/DASH/LRT_HD.mpd
--

**What did you do?**

**What did you expect to happen?**

**What actually happened?**

**Comment by ravics78** [comment]
[segmentincorrect-5.log](https://github.com/google/shaka-player/files/2044448/segmentincorrect-5.log)
attached logs showing the above warning message

**Comment by ravics78** [comment]
More details about the issue:
Although the playback is not halted due to the warnings, logs get accumulated due to excessive warning statements which can slow down the system

**Comment by ismena** [comment]
Hi @ravics78,
Can you repro it in any other browser? I don't seem to get the assertion in either Chrome or Firefox.
