### ISSUE TITLE
Skip MIME type guess for fragment URIs not containing MIME types

### ISSUE THREAD

**Issue by nickrobinson** [google/shaka-player#1456]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate open issues?**:

**What version of Shaka Player are you using?**:
2.4.0

**Can you reproduce the issue with our latest release version?**:
Yes

**Can you reproduce the issue with the latest code from `master`?**:
Yes

**Are you using the demo app or your own custom app?**:
Custom

**If custom app, can you reproduce the issue using our demo app?**:
N/A

**What browser and OS are you using?**:
Chrome/OSX

**What are the manifest and license server URIs?**:

**What did you do?**
Attempt to load my HLS manifest. Because my manifest URI does not include a MIME extension I specified that I am using an HLS parser via the manifestParserFactory option.

**What did you expect to happen?**
I expected Shaka to determine that my fragments were MP4 and start streaming my video.

**What actually happened?**
Because my fragment URIs do not include a MIME type Shaka attempts to determine the MIME type via a HEAD call which does not work against the API I am using. Is there a way to override this setting to force Shaka to assume it is receiving MP4 fragments?

**Comment by ismena** [comment]
Hi @nickrobinson,
We will need to repro to better understand the problem. From what you're describing I suspect that specifying HLS parser might have worked, but then the parser got confused with the extension of your segments.

That's just my idle speculations though. Please post the manifest url here or send it to shaka-player-issues@google.com.
