### ISSUE TITLE
Send assets to update receiver UI (Chromecast)

### ISSUE THREAD

**Issue by Mathieu-R** [google/shaka-player#1457]
Have you read the FAQ and checked for duplicate open issues?: Yes

What version of Shaka Player are you using?: 2.3.7

Can you reproduce the issue with our latest release version?: Yes

Can you reproduce the issue with the latest code from master?: Yes

Are you using the demo app or your own custom app?: custom app

If custom app, can you reproduce the issue using our demo app?: Yes

What browser and OS are you using?: Chrome 67 and OSX 10.13.3

What are the manifest and license server URIs?:

What did you do?
I'm using shaka castProxy and shakaReceiver to cast media on a remote device.

I'm simply wondering how can I pass additionnal assets (like title, artworks,...) to the presentation receiver ?

The documentation says that the receiver is responsable is responsable of its UI but on the other hand, the documentation is not clear on how to send theses assets to update the receiver UI.

There seems to have `shaka.cast.CastProxy.prototype.setAppData(appData)` but it's not clear how to use it in both the sender and the receiver. 

Thanks.

What did you expect to happen?
Would like to send media assets to update the UI of the receiver

What actually happened?
Not assets sent cause I do not know how to do.

**Comment by joeyparrish** [comment]
`shaka.cast.CastProxy.prototype.setAppData` is the right place to send metadata.  That is used on the sender side to communicate arbitrary metadata to the receiver.

The receiver gets that metadata via a callback.  When you construct a `shaka.cast.CastReceiver` object on the receiver side, you pass a callback to the `appDataCallback` parameter (optional 3rd parameter, after `video` and `player`).  That callback is invoked when the sender first connects, with whatever value was given to `setAppData()` before connecting.  While connected, the callback is invoked any time the `setAppData` method is used on the sender.

Does this help?

(We have open issue #1142 for us to write a proper tutorial for Shaka Player on Chromecast.  I apologize that this isn't documented as well as it could be yet.)

**Comment by Mathieu-R** [comment]
Thanks but can I pass whatever data type I want to setAppData (like an object) ?

**Comment by joeyparrish** [comment]
We have special serialization support for `TimeRanges` objects, in lib/cast/cast_utils.js.  This could be extended for any reasonable thing you might need to send, except for code.  We wouldn't accept any change that used `eval` to get and execute JS code sent across the wire, because that would be inherently insecure.  For that sort of thing, it's best to have your receiver load any necessary code itself, independent of anything sent by the local browser.

For example, if some content required a certain request filter, but other content did not, the filter code would be part of both the sender (for local playback) and receiver (for remote playback).  The metadata you send across could contain a flag to indicate the need for the request filter, but not the request filter code itself.

Does that make sense?

**Comment by Mathieu-R** [comment]
Yes thanks

**Comment by joeyparrish** [comment]
Happy to help!  Please let us know if you need anything else.

**Comment by Mathieu-R** [comment]
@joeyparrish Shouldn't the receiver be controlled by the app when casting. 
If I hit pause, seek, change music or whatever else on the app, it does not reflect on the receiver.

**Comment by joeyparrish** [comment]
The receiver app is controlled by the sender app, but that happens through proxied references to the video and player.  You use `CastProxy` to get those, and your UI talks to the proxies.  For example:

```js
const localVideo = document.getElementById('video');
const localPlayer = new shaka.Player(localVideo);

const castProxy = new shaka.cast.CastProxy(localVideo, localPlayer);

const proxyVideo = castProxy.getVideo();
const proxyPlayer = castProxy.getPlayer();

localVideo.pause();  // only has an effect while you are playing locally
castVideo.pause();  // affects the local video while playing locally, or the receiver while casting
```

Your app's UI should always be calling methods and setting properties on the proxied objects, not directly on the local ones.  The UI controls for "pause", for example, don't have to check whether or not you are casting.  The proxy will handle that for you and route the command appropriately.

Does that help?

**Comment by Mathieu-R** [comment]
Yes, and for the second question ?

**Comment by joeyparrish** [comment]
> Another question, I'm sending my assets through setAppData but when I try to update receiver UI, it makes all crash (I mean no sound on the receiver).

> You can check the receiver code here : https://github.com/Mathieu-R/streamwave-presentation in sw-presentation.js especially the method (initShakaPlayer() and metadataCallback (data)). The problematic line is the line 103 : this.updateUI(data).

I'm sorry, I can't spend the time to debug your application.  Just glancing at your code, though, I see that you are doing this:

```js
    this.receiver =  new shaka.cast.CastReceiver(this.audio, this.player, this.metadataCallback);
```

So I'm going to guess that the unbound callback is the problem.  I think if you go to metadataCallback and log "this", you'll see it's not what you think.

In JavaScript, if you take a method from an object, like `var cb = foo.method;`, you end up with an unbound function.  Calling `cb()` invokes `foo.method` with `this` set to `window`.  If you stick that callback into another object, and call it that way, such as `baz.cb = foo.method;  baz.cb();`, it will invoke `foo.method` with `this` set to `baz`.

If you haven't seen this before, this is just an annoying/surprising part of the JavaScript language.

The solution is `bind()`, which attaches a specific `this` to the object.  For example, `var cb = foo.method.bind(foo); cb();` will invoke `foo.method` with `this` set to `foo`.  The same is true here: `baz.cb = foo.method.bind(foo); baz.cb();`

Does that help?

**Comment by Mathieu-R** [comment]
How could I forgot to bind 😮 Thanks to point to that.

**Comment by joeyparrish** [comment]
No worries!  We all do it from time to time.
