### ISSUE TITLE
Add support for EXT-X-SESSION-DATA

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#1460]
Is it possible add support to EXT-X-SESSION-DATA?

https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#section-4.3.4.4

The EXT-X-SESSION-DATA tag allows arbitrary session data to be  carried in a Master Playlist.

 In this example, only the EXT-X-SESSION-DATA is shown:
 #EXT-X-SESSION-DATA:DATA-ID="com.example.lyrics",URI="lyrics.json"
 #EXT-X-SESSION-DATA:DATA-ID="com.example.title",LANGUAGE="en", VALUE="This is an example"
 #EXT-X-SESSION-DATA:DATA-ID="com.example.title",LANGUAGE="es", VALUE="Este es un ejemplo"

Usage sample (Chaptering and Thumbnails): https://developer.apple.com/documentation/avfoundation/media_assets_playback_and_editing/javascript_object_notation_json_chapter_format_for_http_live_streaming

**Comment by michellezhuogg** [comment]
@joeyparrish Are we going to add this?

**Comment by TheModMaker** [comment]
@avelad What do you see us doing with this information?  It looks like what we would do is fire an event when we see that tag and let the app do something with it.

**Comment by avelad** [comment]
@TheModMaker , We will use this information for chaptering and thumbnails using this "standard" json https://developer.apple.com/documentation/avfoundation/media_assets_playback_and_editing/javascript_object_notation_json_chapter_format_for_http_live_streaming 
Fire a event with all information(DATA-ID, VALUE, URI, LANGUAGE) is enough for me.

**Comment by NathanSass** [comment]
Any updates on this? I would also like this for chaptering.

**Comment by joeyparrish** [comment]
I don't see any reason why we couldn't parse it and send an event.  When would you expect the event to be fired?  When the master playlist is parsed?

**Comment by avelad** [comment]
Yes, I expect the event when the master playlist is parsed. Another possibility is provide a method in the player for get this information.
