### ISSUE TITLE
[QUESTION] Offline license server

### ISSUE THREAD

**Issue by robertoviola** [google/shaka-player#1462]
I have some questions, this post is not for bugs.
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate open issues?**:
Yes.
**What version of Shaka Player are you using?**:
v2.4.0
**Are you using the demo app or your own custom app?**:
demo app
**What browser and OS are you using?**:
Ubuntu 16.04 and Firefox 60.0.1
**What did you do?**
I would develop an offline license server which I would like to be compliant with Widevine specifications. Then, my problem consists in parsing the HTTP POST request for license and generate a response. The request is something like the following:

**Request header:**
Referer: http://192.168.10.103:8090/static/my-player/myapp.html
Origin: http://192.168.10.103:8090
Content-Length: 1738
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0
Connection: keep-alive
Host: 192.168.10.103:8090
Accept: */*
Accept-Language: en-GB,en;q=0.5
Accept-Encoding: gzip, deflate

**Request body:**
�a|c'Vk�P"�3�"����"0�
a�;�3=U�������f�,| �$Ϸ��w!�Azc.��tG|�K��!OR�Z�l]�����r'���h��7�R��ğ-���l
                           �6�ף~U4�;*{�}��.*b�	����Y�y�������W�M�$yIgni�o�}і���ߟ.�������%�n�p��>�@��k�$��^�vr+]m��,���W��x<�R��M���-Mr��8R�_9n�Ds���%V΢�y(�9�*���e|�
                                        X8�
Ax�&�y����+{N�jT        Z��!�,�I���y>M���Nn L���b�!��fj��|kI���nڌ�≋V� 5����lu�S�e&oF;MM]��T�(�L��UF�Bx��

                                                              ���=q�<�\v߈���,f�ja�0I4���>�g�����ӡZ5*K��́]P��
                                                                                                              �4�r��7�)��"�����)iQF�H߯��#��g״+�y&�
��堞)j���iTo�7����"0�
��Zs+�쯃�!R��97�)l��q�Mͽl�+2���:J��"��UbsQ�⋩�:�� \p,rJ�@����=݆�e�t�ww)����R�<�kȒ'�H/��*fT�����߅s�	4����B�t>N��K\����#�r}X��Ar�A�N�<�x��ꅾ�?��&F��GIT��2�L��5y?��Kp ��bv�5I��.��÷�f�fgK�0�ᚚj
                                                        �tC���������,�|��{���Ty(�9�EP@��G�zn�*������Ъ\��q�t|5����ww��X��0�mK���p��
                                                                                                                                                    ��x�:���[�)h��>�oN���/1O��[��P� ��3�xo���@
��N���ve1�֓��,!r�'��_ƪn�z_
�
D�)��I���V\�E��b�'�T?���&��D�tHj�utW%ā�M"�o�w��Z95�c:��3�'�0͎M�b�}�W���):�-���5h�_��
                                                                                        ����w��p
Xp��!�� $A�Z�|i��������̘�����|D kk�Y���%�[Ò�y��WP�I*C_��7N�#�����k�%��f8��`�����Y=d�@�"���|�[�0�۳�Z
architecture_namex86-64

company_nameGoogle

model_name	ChromeCDM
platform_nameLinux"
widevine_cdm_version
1.4.8.100 /
-
"test content idH�ܕ�>l3�������
W�o��|�ǜN_:��*��-ڂ2+�'�%�Qs��f�]�4sz��OY�x1XW��J�ћ%C���h#D�bĩ�3+�e�^���݆�����IV�(����1�nؼ���|���JG�(����R>W=5z<
�rDc����������m	�fZ�]�Yπ���J��

I guess the body is generated by the Widevine CDM, but if I am not able to understand it, I am not able to generate a response which fits with the request. Are there any specifications about how to parse it?

I found the following post which is asking almost the same: [https://github.com/google/shaka-player/issues/557](https://github.com/google/shaka-player/issues/557)

By the way, I understand from the post that it is not possible for me to know the content of the request ( **Both request and response are in a non-readable binary format.**), then how can I develop a Widevine compliant offline license server?

I undestand that I can wrap the request with some other data which could fit with my development, but this is not solve my problem to answer to Widevine CDM request.

**Comment by TheModMaker** [comment]
The Widevine license request and response formats are proprietary and undocumented.  Even if you knew the format, the response is signed with keys and certificates you don't have access to.  The CDM will only talk with official Widevine license servers.

If you want more information or would like to talk about hosting your own Widevine license server, you should talk with Widevine support directly: http://www.widevine.com/contact.html

If you are working offline, you could use our [offline storage API](https://shaka-player-demo.appspot.com/docs/api/tutorial-offline.html) to store the license while you are online and then play the content while you are offline.  But this requires being online to make the first license request.

**Comment by joeyparrish** [comment]
In short, you can't develop your own Widevine license server.  Please send any further questions about running a Widevine license server directly to Widevine.  Thanks!
