### ISSUE TITLE
Unable to load shaka-player.compiled.js in Electron 2

### ISSUE THREAD

**Issue by radiantmediaplayer** [google/shaka-player#1463]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate open issues?**
Y

**What version of Shaka Player are you using?**:
2.4.0

**Can you reproduce the issue with our latest release version?**:
Y

**Can you reproduce the issue with the latest code from `master`?**:
Not tried

**Are you using the demo app or your own custom app?**:
custom

**If custom app, can you reproduce the issue using our demo app?**:
N/A

**What browser and OS are you using?**:
Electron 2.0.2 for Windows 10 x64
Chromium   61.0.3163.100

**What are the manifest and license server URIs?**:
https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd

**What did you do?**
Try to run the basic usage example at https://shaka-player-demo.appspot.com/docs/api/tutorial-basic-usage.html in an Electron 2.0 app for Windows 10.

**What did you expect to happen?**
It should work

**What actually happened?**
It did not work

I see in the Chromium console:
Uncaught ReferenceError: shaka is not defined
    at HTMLDocument.initApp (index.html:14)

This happens when I try to include the shaka-player.compiled.js file, either from cdnjs or locally. 
The weirdest thing is that this issue does not happen when I include shaka-player.compiled.debug.js either from cdnjs or locally. I have verified that shaka-player.compiled.js works fine in Google Chrome and can be loaded. 

Note that this issue is not about using the FILE protocol with shaka.net.NetworkingEngine.registerScheme but loading the compiled version of Shaka player in an Electron app.
We are also working with other libs in Electron (hls.js, three.js) and Shaka player is the only lib we are seeing this issue with. At this stage my best guess is that there is some sort of incompatibility due to the Shaka player build process (maybe some closure thing?) that causes shaka-player.compiled.js to not work in an Electron 2 app.
I don't know if you officially support Electron, or if this could be of interest to the community, but any hint would be appreciate.

**Comment by joeyparrish** [comment]
Can you load any of these Shaka Player demo app links in Electron?

v2.4.0, uncompiled: https://shaka-player-demo.appspot.com/demo/#build=uncompiled
v2.4.0, debug: https://shaka-player-demo.appspot.com/demo/#build=debug_compiled
v2.4.0, release: https://shaka-player-demo.appspot.com/demo/#build=compiled

nightly, uncompiled: https://nightly-dot-shaka-player-demo.appspot.com/demo/#build=uncompiled
nightly, debug: https://nightly-dot-shaka-player-demo.appspot.com/demo/#build=debug_compiled
nightly, release: https://nightly-dot-shaka-player-demo.appspot.com/demo/#build=compiled

**Comment by radiantmediaplayer** [comment]
@joeyparrish thanks for the reply. Here are the results:
v2.4.0, uncompiled: https://shaka-player-demo.appspot.com/demo/#build=uncompiled
>> loads ok
v2.4.0, debug: https://shaka-player-demo.appspot.com/demo/#build=debug_compiled
>> loads ok
v2.4.0, release: https://shaka-player-demo.appspot.com/demo/#build=compiled
>> FAILS to load and print the following error in console
Uncaught ReferenceError: shaka is not defined
    at shakaDemo.init (main.js:102)

nightly, uncompiled: https://nightly-dot-shaka-player-demo.appspot.com/demo/#build=uncompiled
>> loads ok
nightly, debug: https://nightly-dot-shaka-player-demo.appspot.com/demo/#build=debug_compiled
>> loads ok
nightly, release: https://nightly-dot-shaka-player-demo.appspot.com/demo/#build=compiled
>> FAILS to load and print the following error in console
Uncaught ReferenceError: shaka is not defined
    at shakaDemo.init (main.js:102)

One very easy way to reproduce it is install https://github.com/electron/electron-quick-start and then go to main.js and replace mainWindow.loadFile('index.html') with mainWindow.loadURL('https://shaka-player-demo.appspot.com/demo/#build=compiled') and then run npm start. I have verified that the issue is the same when packaging an Electron app with electron-packager.

**Comment by joeyparrish** [comment]
Thanks for the details on how to use electron.  Very helpful!  I'll take a look.

**Comment by joeyparrish** [comment]
I can reproduce the issue.  It looks like it has something to do with the [output wrapper](https://github.com/google/shaka-player/blob/master/build/wrapper.template.js) we use with the compiler.  It is meant to allow Shaka to be used with module loaders, but it seems that Electron has a "module" global variable that is confusing the wrapper.

**Comment by radiantmediaplayer** [comment]
Thanks for looking into it. Since Electron runs a local node server, all API and variables available with node are available in the window of the Chromium view generated, including global node variables like `module` or `process`.

**Comment by joeyparrish** [comment]
I'm struggling to build a single output wrapper that works in all of these environments:

1. CommonJS (supported already)
2. AMD (supported already)
3. NodeJS (not well supported, but sort of works)
4. Electron (not yet supported, wrapper is confusing this with CommonJS/NodeJS)

And in a perfect world, I'd some day add:

5. ES module support

I'll let you know as I make progress.

**Comment by joeyparrish** [comment]
I think I have something working in all cases.  I need to clean it up and get it through code review, but I see Electron, nodejs, CommonJS, AMD, and ES modules all working.  I have also been able to revert an earlier change made to the compiler to fix #1455.

**Comment by radiantmediaplayer** [comment]
I went into this a bit further and I found that the issue I reported also exists with other libs like jQuery that are module compatible. 
[A solution is described here](https://github.com/electron/electron/issues/254#issuecomment-42351776) and I have verified this works with Shaka (I have not covered all use-cases yet like DRM, but it works for basic playback). This is what I did to make it work:

`window.shaka = require('./rmp/dash/shaka-player.compiled.js');`

Since both `window ` and `module ` are defined in Electron we need to re-attach shaka global variable to the `window` object (the shaka compiled lib cannot be included with a script tag as of now, we need to use `require`). If you have a long-term out-of-the-box solution this is great, but in the meantime the above could be used as a workaround.

**Comment by joeyparrish** [comment]
This has been fixed in the master branch, and the fix will be cherry-picked to our next releases.  Sorry for the inconvenience!

**Comment by joeyparrish** [comment]
Cherry-picked for v2.4.2.

**Comment by joeyparrish** [comment]
Cherry-picked for v2.3.10.
