### ISSUE TITLE
Broken links to bug reports

### ISSUE THREAD

**Issue by theodab** [google/shaka-player#1472]
Several of the issues we had reported on IE/Edge and linked to in comments are now no longer accessible.
[Issue 10322657](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/10322657)
[Issue 7774622](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/7774622)

However, those issues still exist; they can be seen when searching for issues on Microsoft's developer website ([like this](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/?page=1&q=10322657)). Presumably they were marked internal. Until they are made public again, those links in our comments will be useless.

**Comment by TheModMaker** [comment]
Links to these issues appear in `lib/media/drm_engine.js`.

**Comment by theodab** [comment]
Microsoft has made these issues public again.
