### ISSUE TITLE
Security of offline downloads

### ISSUE THREAD

**Issue by sridhard** [google/shaka-player#1475]
Shaka support offline download and persistent licenses for widevine.

How secure is offline download and persistent licenses?
Are the widevine licenses are node locked? if not node locked then the user can download the content offline and use the persistent token to play it in other nodes and distribute the content? Because it is easy to copy the token from the chrome networking trace or by putting breakpoints in js code.

**Comment by TheModMaker** [comment]
This is a question best for the Widevine team: http://www.widevine.com/contact.html

The handling of licenses and persistent files is handled by the browser, so we don't do anything for it.  All we do is download the segments, save them, and fetch the license (which we just give it to the browser).

Widevine is highly secure; from my understanding: the license is encrypted over the wire, so you can't read the keys from the Network tab.  The response is timestamped and has [nonces](https://en.wikipedia.org/wiki/Cryptographic_nonce), so you can't use the response in another computer, save it to use later, or give it to Chrome twice.  Also you can't get the keys from the license, so there is no way to distribute the decrypted content, only the encrypted files.  Only Chrome can use the keys and it will only allow playing the content, not just decrypting it.

**Comment by joeyparrish** [comment]
I will add that licenses, as they appear over the wire, are only readable by the CDM (a content security component inside the browser) that requested the license.  Persistent licenses are stored securely by the CDM itself, and cannot be tampered with or transferred to other machines.

Does this help?

**Comment by sridhard** [comment]
ok...thanks for the detailed explain
