### ISSUE TITLE
DASH period parsing without IDs

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#1478]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**: Yes

**What version of Shaka Player are you using?**: v2.4.1

**Can you reproduce the issue with our latest release version?**: yes

**Can you reproduce the issue with the latest code from `master`?**: yes

**Are you using the demo app or your own custom app?**: custom

**If custom app, can you reproduce the issue using our demo app?**: haven't tried, but I expect so

**What browser and OS are you using?**: Chrome 68 beta on Linux

**What are the manifest and license server URIs?**: still working on access to those

**What did you do?**
Loaded a live stream with only one Period, no Period ID, and an update frequency of 2s.  On each update, the period start time changes.

**What did you expect to happen?**
Only one period should be seen by the DASH parser.

**What actually happened?**
The DASH parser assigns period IDs based on the period start time, so it creates new periods all the time.  After 10 updates, there are 11 periods in the manifest.

Should we use the period index instead of the start time for the auto-generated ID?

**Comment by TheModMaker** [comment]
We currently don't support changing Period start.  As of v4.1.2, this is actually forbidden according to the DASH IOP. See Dash-Industry-Forum/DASH-IF-IOP#160.  In v4.2 of the IOP, section 4.4.3.3 states:

> MPD@availabilityStartTime and Period@start shall not be changed over MPD updates.

**Comment by joeyparrish** [comment]
@TheModMaker, thank you for pointing that out.  I will close as "intended behavior" and let the affected partner know that this is to be avoided in their manifests.
