### ISSUE TITLE
Add ability to intercept network requests to add additional query params or headers

### ISSUE THREAD

**Issue by priyajeet** [google/shaka-player#148]
...or provide the ability to add additional query params or optional headers to the Player / VideoSource constructor

...or re-use the query params provided on the MPD url for network requests to the content segments.

Use case: When serving an mpd file /foo/bar.mpd?foo=bar, requests that go out to fetch the mp4 segments should also have ?foo=bar. This is useful in providing some context, auth tokens etc if needed when the MPD file is static but the content requires some additional information based on who is trying to fetch it.

Something similar is accomplished in dash.js by overriding MediaPlayer.dependencies.RequestModifierExtensions

More info: https://groups.google.com/forum/#!topic/shaka-player-users/kmT_-eVn1ZM

Thanks

**Comment by gerwinbrunner** [comment]
We would need the same. It would be awesome to have a callback for each video and being able to change the url completely for each video before loading it actually.

We are thinking of dynamically generate temporary (secure) S3 url which work for 15min per video.

**Comment by tdrews** [comment]
@priyajeet from #162 wrote
> Thanks for getting this implemented. One thing I did notice was that the MPD fetching bypasses the request callback. Wouldn't requesting the MPD also go through the callback for consistancy?

By-design the API only modifies segment request URLs and headers.

For live-content, the server can specify the next MPD update URL via the `<Location>` element.
Do you require modifying the MPD update URLs (for live-content) client-side as well?

**Comment by priyajeet** [comment]
If the contents of the MPD are being fetched from /foo/bar/baz.mpd, and the server expects some authentication headers in that request, then yeah one would need the MPD url to also go through the same interceptor.

**Comment by joeyparrish** [comment]
@tdrews, it seems the idea is that we have a static manifest, but the server has some front-end that does authentication based on headers or parameters before serving the static content.

Seems as reasonable as the rest of the feature request, so re-opening.

**Comment by sridhard** [comment]
Hi @joeyparrish ,

Is this feature not available for the latest V2 player

**Comment by joeyparrish** [comment]
@sridhard, it is definitely available and has been implemented for some time now.  (This issue has been closed for over one year.)

Since you already filled a new issue for help using this feature (#531), let's discuss there.  Please don't spread our conversation over multiple issues.
