### ISSUE TITLE
Due date for release 2.5

### ISSUE THREAD

**Issue by dmunozpolo** [google/shaka-player#1480]
Hi all,

Could anyone confirm which is the due date for version 2.5 of Shakaplayer?

Thanks.

Regards,
David.

**Comment by joeyparrish** [comment]
We don't have a firm due date for v2.5.  The [v2.5 milestone](https://github.com/google/shaka-player/milestone/16) is currently 14% complete.  There are many major features still left to be completed, and I'm sure some of them will wind up getting bumped to another release.

We typically get out a minor release (v2.3, v2.4, etc) every 3 months or so.  The last minor release, v2.4, took 5.5 months.  At that time, we were short-staffed.

During the v2.5 development cycle, the team is currently splitting their attention among multiple projects, so I would predict another slow cycle.  We are doing what we can to speed things up, of course, but we are only human.

What features are you most eager to see in v2.5?

**Comment by boredom2** [comment]
If I am also allowed to answer - definetely the "Pre-load API". That would make so much Sense when playing Playlists or short Bumpers one after the other. In these Contexts, its not even speculative, its absolutely sure, that this Video will come next.

**Comment by jakubvojacek** [comment]
For me, it would be https://github.com/google/shaka-player/issues/999 (dealing with encoder drift). Until that is resolved, we will have to stick with dashjs as our live content is playable there :(

**Comment by dmunozpolo** [comment]
Hi Joe,

We are interested in having the issue of Shakaplayer being able to play FairPlay encrypted streams in Safari.

Could we have an estiamtion if this could be included in v2.5? It would be very helpful for us.

Thanks.

**Comment by joeyparrish** [comment]
Thanks, everyone.  This is very helpful for planning.  I'll let you all know when we do our next round of planning.  I will try to decide definitively what we have time for in v2.5.

**Comment by sergioavazquez** [comment]
I'd love to see this one #1431. I'm using Shaka in production and I have `HLS` streams I can't reproduce.  Let me know if you need any help with it! 
Thanks!

**Comment by vaage** [comment]
Just to give everyone an update, we have reached 32% completion for v2.5. If you would like to follow the progress more directly, you can check it out [here](https://github.com/google/shaka-player/milestone/16).

**Comment by dmunozpolo** [comment]
Hi,

My main concern is knowing when the issue for Shakaplayer being able to play FairPlay encrypted streams in Safari will be available.

I guess the issue is this one:  "Safari Fairplay MediaKeys Polyfill #382", am I right?

Could you help me with this?

Thanks.

**Comment by dmunozpolo** [comment]
Thanks for the update.

Any new update on when #382 will be ready?

**Comment by bansalvks** [comment]
**First of all I am a fan of Shaka**

I love Shaka player but unfortunately, my team has to choose **VideoJs** just because you are currently not supporting **Fairplay** and we cannot loose our safari users. 

Is there a workaround/Plugin that we can use with shaka to play DRM on safari?
Can you confirm a date, when the [#382](https://github.com/google/shaka-player/issues/382) will be ready?

Many thanks for building such a great player.

Your Admirer,
Vikas Bansal

**Comment by mimse** [comment]
@bansalvks You can always use native Safari HLS/Fairplay support, and use shaka-player for the other browsers.
Also, I can recommend Plyr for video controls and styling.

**Comment by ismena** [comment]
Thank you for you kind words @bansalvks, greatly appreciated!
We are working on #816, which is a stepping stone for #382.

@vaage, do you think you could give an update in terms how much more time/effort is needed?

**Comment by vaage** [comment]
It is hard for me to say. Right now Joey and I are working on a design for a large change to the load system that is needed to make src= work cleanly. I am hoping that once the design is done and I can move onto implementation that I will be able to make substantial progress on #816.

**Comment by bansalvks** [comment]
Many thanks for the response @mimse 

If I understood you correctly then I need to detect browser and if it safari then use a simple video tag and set it's `src=` and the fair-play stream will be played?

I will need to use 2 players... shaka for rest of the world and native video tag for safari...

**Comment by mimse** [comment]
@bansalvks 

Yes, that was the idea. You will also need a bit of javascript code to handle Fairplay.

If I remember correctly there is a code example is this SDK from apple

https://download.developer.apple.com/Developer_Tools/FairPlay_Streaming_Server_SDK/FairPlay_Streaming_Server_SDK_v4.2.0.zip

Sadly use need an Apple developer account.

You will need two playback technologies (native HLS and Shaka-player) but they can both be controlled by the same player. ex. Plyr https://github.com/sampotts/plyr

**Comment by bansalvks** [comment]
@mimse I am not able use the link as it is showing unauthorised access. I am currently struggling to play DRM **fairplay** in native Video tag.

Is it possible for you to provide any help.., as it has been more than 2 weeks since I am struggling with it.

**Comment by mimse** [comment]
Hi @bansalvks, I cannot provide access to the Fairplay SDK. As I said in my previous comment, you will need an Apple developer account to download the SDK.
Sorry I cannot be of more help.

**Comment by dmunozpolo** [comment]
Hello all,

Sorry to ask again but do we have updated information on when #382 will be completed?

I know you were working on #816 but it is important for us to get #382 ready.

Thanks for your help!

**Comment by joeyparrish** [comment]
#382 (FairPlay) depends on #816 (src=), because Apple **only** has documented support for FairPlay through src= on desktop & iOS Safari.  Without #816, there is no way for us to complete #382.  We apologize for the inconvenience.

**Comment by fadomire** [comment]
is #816 scheduled for v2.5 ?

**Comment by joeyparrish** [comment]
Currently, #816 is schedule for v2.5.  You can see our scheduling in the "milestone" field of github issues.

I understand this particular release cycle has been slow and may be frustrating to our users.  We are working to improve our release cadence.  To help our users make plans of their own and to help give our users a chance to see and influence our long-term plans, next year we will publish a longer-term roadmap in addition to our issues and milestones.

**Comment by dmunozpolo** [comment]
I see that #382 is planned for V2.5, unless I am wrong.

Is there a planned date for releasing v2.5?

Thanks.

**Comment by joeyparrish** [comment]
It's beginning to look a lot like January.

We'll continue to release v2.5 betas as we achieve meaningful progress through particular features.

**Comment by joeyparrish** [comment]
We are nearing completion of v2.5's critical features.  We expect a release by the end of April.
