### ISSUE TITLE
License Server Connection Stalled - No Error Thrown

### ISSUE THREAD

**Issue by grantg182** [google/shaka-player#1482]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:
Yes
**What version of Shaka Player are you using?**:
2.4.1 (cherry-picked [this](https://github.com/google/shaka-player/commit/0641b6c0d7c41b68c2a7b03c3050e7b4ee7fff38) into the master build)
**Can you reproduce the issue with our latest release version?**:
No
**Can you reproduce the issue with the latest code from `master`?**:
Yes
**Are you using the demo app or your own custom app?**:
Custom
**If custom app, can you reproduce the issue using our demo app?**:
Yes
**What browser and OS are you using?**:
Chrome 67, OSX 10.13.3

**What did you do?**
Attempt playback of WV-encrypted content when license server is "unavailable" - for a variety of reasons, for example because the client device has disconnected from the local network (essentially an intranet without internet access) and is now connected to the internet (through another wifi connection or 3/4G); license server is only available on intranet network, not the open web.

**What did you expect to happen?**
LICENSE_REQUEST_FAILED (6007) to be returned.

**What actually happened?**
License server call went from Queueing->Stalled ("CAUTION: request is not finished yet!"). 

Intermittently, the license server call will return the 6007 error within 2-3 seconds which is perfectly acceptable. 

Intermittently, this call won't return anything at all - the license server call appears to stall indefinitely, therefore no errors are returned to handle in the UI. Chrome Network tab eventually shows this request as Failed after "1.3m". I guess the 1.3 minutes is an arbitrary timeout set by Chrome, as I have not (yet) set up retryParameters (perhaps I should, if that would help this situation?).

This means the user can play the default 10s of clear content, then because no error is thrown, we are currently doing nothing. The end result being the video looks to have stalled.

I suspect the network switch/fail should be handled by Chrome, although it doesn't appear to be, in that Chrome should return something to Shaka instead of waiting for the connection to eventually die 1.3 minutes later. Alas, when this timeout eventually does happen, still no errors are thrown by Shaka. 

A timeout over 1 minute seems horrendous - I have not yet tested other browsers to see how they are impacted.

Any suggestions of what we can we do in this instance? 

Thanks!

**Comment by joeyparrish** [comment]
@grantg182, have you tried configuring a timeout in the player's retryParameters?  By default there is no timeout.  See https://shaka-player-demo.appspot.com/docs/api/tutorial-network-and-buffering-config.html

**Comment by grantg182** [comment]
Hey @joeyparrish . Thanks for your reply. 

As I said I have not yet set up retryParameters. Does this mean, once those are implemented, an error will be thrown once maxAttempts has been reached? I'll give that a spin later today and see where that leaves me.

**Comment by joeyparrish** [comment]
Sorry I overlooked that in your original post!

The maxAttempts parameter will control how many attempts are made (including the first attempt).  But without the timeout parameter, the JavaScript application has no control over when a failure occurs.  You should definitely set the timeout parameter, which defaults to 0 (no timeout).  With a timeout set, you are in control over how long a transfer may take before it is aborted.
