### ISSUE TITLE
Shaka keep downloading the same segment of multi-period live MPD and playback stuck

### ISSUE THREAD

**Issue by albertcsm** [google/shaka-player#1486]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:
Yes

**What version of Shaka Player are you using?**:
2.4.2

**Can you reproduce the issue with our latest release version?**:
Yes

**Can you reproduce the issue with the latest code from `master`?**:
Yes

**Are you using the demo app or your own custom app?**:
Demo app

**What browser and OS are you using?**:
Chrome/Windows

**What did you do?**
Play live DASH stream with multiple periods

**What actually happened?**
Playback stuck and browser keep downloading the same segment
![image](https://user-images.githubusercontent.com/2263504/42446928-a4209538-83aa-11e8-82f8-2476fc63da45.png)

From browser dev Console, there were a lot of assertion failures: "SegmentReferences are incorrect"
![image](https://user-images.githubusercontent.com/2263504/42447032-00b290e4-83ab-11e8-94f5-2142061031d3.png)

Suspect it is caused by bug in segment merge during manifest update, which failed to associate new segment reference with existing ones and consequently produced duplicated segment references in segment index.
![image](https://user-images.githubusercontent.com/2263504/42447057-16e44498-83ab-11e8-9d27-e3e0fb57af31.png)
![image](https://user-images.githubusercontent.com/2263504/42447074-25050d14-83ab-11e8-846e-955e19facc07.png)

After modifying the segment index "fit" function to always use the original segment reference startTime, the problem seems to be solved.
https://github.com/google/shaka-player/blob/master/lib/media/segment_index.js#L294

Sample MPDs:
[manifest-927.mpd.txt](https://github.com/google/shaka-player/files/2175859/manifest-927.mpd.txt)
[manifest-926.mpd.txt](https://github.com/google/shaka-player/files/2175860/manifest-926.mpd.txt)
[manifest-924.mpd.txt](https://github.com/google/shaka-player/files/2175861/manifest-924.mpd.txt)

**Comment by chrisfillmore** [comment]
I think this is the same as https://github.com/google/shaka-player/issues/1464

**Comment by albertcsm** [comment]
Yes, it is the same as #1464
