### ISSUE TITLE
Can't play webm live stream in Chrome

### ISSUE THREAD

**Issue by kiranbsravi** [google/shaka-player#1487]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:
yes
**What version of Shaka Player are you using?**:
2.4.1
**Can you reproduce the issue with our latest release version?**:
yes
**Can you reproduce the issue with the latest code from `master`?**:

**Are you using the demo app or your own custom app?**:
own custom app
**If custom app, can you reproduce the issue using our demo app?**:

**What browser and OS are you using?**:
Chrome browser on MacOS
**What are the manifest and license server URIs?**:

**What did you do?**
I create live webm dash segments using ffmpeg shared libraries (not from command line). My input live stream is from a webrtc server, which i want to stream over dash. I have attached the generated manifest. It is playing correctly in Firefox. Before a recent Chrome update it was playing correctly on Chrome too. But now it just doesn't play on Chrome. There is no console error. The segments are being fetched correctly. But I cant see the playback on Chrome. There is a message "canSwitch_" in browser console. Apart from that there is no other error thrown. 
**What did you expect to happen?**
I expected to see the play back in shaka player in Chrome.
**What actually happened?**
The player is just loading the segments and no play back is seen. No error thrown in th ebrowser console too, except for the message "canSwitch_".
[manifest.txt](https://github.com/google/shaka-player/files/2183003/manifest.txt)

**Comment by bafolts** [comment]
Depending on which version of chrome you updated to there was a recent update to the auto play policy in april.

https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

**Comment by kiranbsravi** [comment]
My chrome version is 67.0.3396.99. But the video should start to play after i hit on play button explicitly right. It doesn't play even if i give explicit play.

**Comment by joeyparrish** [comment]
We will need usable manifest URIs to reproduce the bug, not just attachments.  If you can't post them publicly, please send the URIs to <shaka-player-issues@google.com> instead.  There was a note about this in the issue template.

If you have a publicly accessible manifest URI, you can copy the URI of the demo app after loading to send us the exact asset, licence server, and settings you have selected there.

**Comment by kiranbsravi** [comment]
As of now we are running it on my internal machine. It is not exposed to external world. So unable to share any manifest uris. I am configuring my player as follows :

player.configure({
    			  streaming: {
    			    bufferingGoal: 5
    			  },
    			  abr: {
    				  enabled: false
    			  }
   });
It was playing fine before. but after the chrome update it is not playing.

**Comment by joeyparrish** [comment]
Unfortunately, we can't diagnose anything if you can't give us a way to reproduce the bug.  Is there anything you can do to provide us with content?
