### ISSUE TITLE
Clock sync HEAD requests marked as type shaka.net.NetworkingEngine.RequestType.MANIFEST

### ISSUE THREAD

**Issue by pcruiksh** [google/shaka-player#1488]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:
yes

**What version of Shaka Player are you using?**:
2.4.2 latest master

**Can you reproduce the issue with our latest release version?**:
Yes

**Can you reproduce the issue with the latest code from `master`?**:
Yes

**Are you using the demo app or your own custom app?**:
Custom

**If custom app, can you reproduce the issue using our demo app?**:

**What browser and OS are you using?**:
Chrome 67.0.3396.99

**What are the manifest and license server URIs?**:
Any

**What did you do?**
configure clockSyncUri and register filter with networking engine that performs manifest-request specific logic

**What did you expect to happen?**
clockSyncUri HEAD request isn't marked as manifest request

**What actually happened?**
Clock sync request is tagged as either something descriptive of what it is, or something generic.

Currently the requests Shaka makes for clock sync purposes are marked as request type MANIFEST, which can be misleading and cause problems in networking filters that rely on request type identification to perform specific logic. These requests should either have a generic type or perhaps a new type such as ```shaka.net.NetworkingEngine.RequestType.TIMING``` for example.

**Comment by joeyparrish** [comment]
Sounds reasonable.  I'll schedule it.

**Comment by joeyparrish** [comment]
We would be happy to take a pull request for this, if you're interested.  It should be quick and easy.

**Comment by pcruiksh** [comment]
Sounds good @joeyparrish I'll do that
