### ISSUE TITLE
Ability to seek live shows from beginning to end

### ISSUE THREAD

**Issue by kfwerf** [google/shaka-player#149]
Hi,

we have live content that needs to have the ability to be seeked through completely, not just from the moment we start live watching. 

E.g. start watching a live stream and then jumping to the beginning. I tried to see if adjusting the seek range helps but that doesnt do any fetching anymore, im guessing because the seekrange works with from wherever you started.

Is there a way to circumvent the current live behaviour? Its not really ideal for our streams, as we have realistic beginnings and endings.

**Comment by kfwerf** [comment]
Nevermind i added this simple patch, left the code below in case anyone else wants to use it. Its pretty crappy but it works for my implemntation.

I only added the comments and author so i can find back what i modded in case of future updates. 

Cheers!

*/lib/dash/dynamic_live_segment_index.js*

`Lines 71-78`
```javascript
      /**
      * Implementation of override for initial early segment
      * @author kenneth.vanderwerf@magine.com (Kenneth van der Werf)
      * @type {number}
      */
     earliestSegmentNumber =
         (shaka.dash.DynamicLiveSegmentIndex.overrideEarliestRange_ ||
         earliestSegmentNumber);
```

`Lines 281-288`
```javascript
  /**
   * Implementation of override for initial early segment
   * @author kenneth.vanderwerf@magine.com (Kenneth van der Werf)
   * @type {number}
   */
  var earliestSegmentNumber =
      (shaka.dash.DynamicLiveSegmentIndex.overrideEarliestRange_ ||
      (earliestAvailableSegmentStartTime / scaledSegmentDuration) + 1);
````

`Lines 304-315`
```javascript


/**
 * If higher than 0, will set a override to the earliest range
 * Allows seeking further back, to as far back as segment 1
 * @author kenneth.vanderwerf@magine.com (Kenneth van der Werf)
 * @type {number}
 * @private
 */
shaka.dash.DynamicLiveSegmentIndex.overrideEarliestRange_ = 1;
````

**Comment by tdrews** [comment]
If you have control over the server then you can accomplish this by setting `timeShiftBufferDepth` in the MPD to some value greater than or equal to the time since the stream started broadcasting (at the time the MPD is fetched).

Alternatively you should be able to just override `timeShiftBufferDepth` in mpd_parser.js to some large value (i.e., 1 day).
