### ISSUE TITLE
Shaka Error DRM.NO_RECOGNIZED_KEY_SYSTEMS ()

### ISSUE THREAD

**Issue by kuznetcoff777** [google/shaka-player#1490]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**: yes

**What version of Shaka Player are you using?**: latest

**Can you reproduce the issue with our latest release version?**: yes

**Can you reproduce the issue with the latest code from `master`?**: on demo page

**Are you using the demo app or your own custom app?**: demo

**If custom app, can you reproduce the issue using our demo app?**:

**What browser and OS are you using?**: win7/chrome

**What are the manifest and license server URIs?**: sent on mail

**What did you do?** launched player and drm stream (cenc widevine+playready)

**What did you expect to happen?** stream is playing

**What actually happened?** stream did not start, error appeared "Shaka Error DRM.NO_RECOGNIZED_KEY_SYSTEMS ()"

**Comment by TheModMaker** [comment]
The problem is the `schemeIdUri` attribute is incorrect.  You have it as `9a04f079-9840-4286-ab92-e65be0885f95` when the correct value is `urn:uuid:9a04f079-9840-4286-ab92-e65be0885f95`.  Similar for Widevine.

**Comment by kuznetcoff777** [comment]
Guys, anyone?

**Comment by kuznetcoff777** [comment]
Thanks for explanation!
