### ISSUE TITLE
Suggestion: issue label for set-top-box type platforms?

### ISSUE THREAD

**Issue by chrisfillmore** [google/shaka-player#1494]
I know that my team is going to be supporting more and more smart TV / STB platforms in our future. It seems lots of other people are working in these environments too. Could we have an issue label for bugs from these platforms? This would cover any smart TV (Tizen, LG WebOS, Vizio, etc) as well set-top-boxes that support HTML5 environment (Enseo STB).

**Comment by joeyparrish** [comment]
Sure, no problem.  I'll create a "TV/STB" label we can use for that.

**Comment by joeyparrish** [comment]
Done!  https://github.com/google/shaka-player/issues?q=label%3ATV%2FSTB

**Comment by chrisfillmore** [comment]
Thank you!

**Comment by joeyparrish** [comment]
De nada.
