### ISSUE TITLE
Check for text language match after filtering in Player

### ISSUE THREAD

**Issue by vaage** [google/shaka-player#1497]
In `lib/player.js` there is a TODO with very little context. We can use this issue to explore the intent of the TODO and then update the TODO with the issue number.

https://github.com/google/shaka-player/blob/master/lib/player.js#L2869

```
  // Create empty object first and initialize the fields through
  // [] to allow field names to be expressions.
  // TODO: This feedback system for language matches could be cleaned up.
  let languageMatches = {};
  languageMatches[ContentType.AUDIO] = false;
  languageMatches[ContentType.TEXT] = false;

  let variants = StreamUtils.filterVariantsByConfig(
      period.variants,
      this.currentAudioLanguage_,
      this.currentVariantRole_,
      this.currentAudioChannelCount_,
      languageMatches);
```

**Comment by joeyparrish** [comment]
The `languageMatches` dictionary serves as an output parameter for both `filterVariantsByConfig` and `filterStreamsByLanguageAndRole`.  The output from those is then used to decide whether or not to display the text track by default.

The high level requirement is shown in a comment lower down in the same code:

```js
    // If audio and text tracks have different languages, and the text track
    // matches the user's preference, then show the captions.  Only do this
    // when we are choosing the initial tracks during startup.
```

When we do fuzzy language matching in the filter methods, we flag audio or text as having a language match if any of the streams matches the language preference at any of the fuzzy match levels:

```js
shaka.util.LanguageUtils.MatchType = {
  /** Accepts an exact match. */
  EXACT: 0,
  /** Accepts a less-specific version of the preferred sublanguage. */
  BASE_LANGUAGE_OKAY: 1,
  /** Accepts a different sublanguage of the preferred base language. */
  OTHER_SUB_LANGUAGE_OKAY: 2,
};
```

That's the full context for what we're trying to do.

What the `TODO` means is that the way we achieve that feature feels clunky: we let the filter methods also flag matches (which isn't really the job of the filters), we use the side-effect of changing a dictionary as an output param, and we don't end up using the audio flag at all (we used to, I think).

**Comment by joeyparrish** [comment]
Instead, let's just check for a language match explicitly after filtering.  We only need to do it for text, only on startup, and only on the chosen text track.  It shouldn't be expensive to repeat the language check, but it will be clearer.

**Comment by TheModMaker** [comment]
Looks like this was fixed at some point.  I can't find the TODO anymore and the StreamUtils methods don't use that object output parameter anymore.
