### ISSUE TITLE
Add segmented subtitles to the player

### ISSUE THREAD

**Issue by kfwerf** [google/shaka-player#150]
Add the ability to rather than just appending a text track, instead allow to add segments of the subtitle to the player.

Im gonna try to patch this for now by making a segmented_text_track. 

This should be the case if manifest has a templated setup for the subtitles, e.g.

```xml
  <AdaptationSet contentType="text" mimeType="text/vtt" segmentAlignment="true" group="1" lang="swe">
   <SegmentTemplate timescale="10000000" duration="60000000" media="$RepresentationID$/$Number$.m4v" startNumber="0"/>
   <Representation id="subtitlesvttswe/0" codecs="vtt" startWithSAP="1" bandwidth="0"/>
  </AdaptationSet>
  <AdaptationSet contentType="text" mimeType="text/vtt" segmentAlignment="true" group="1" lang="fin">
   <SegmentTemplate timescale="10000000" duration="60000000" media="$RepresentationID$/$Number$.m4v" startNumber="0"/>
   <Representation id="subtitlesvttfin/0" codecs="vtt" startWithSAP="1" bandwidth="0"/>
  </AdaptationSet>
```

We have done something similar for dash.js, all we did was use a vtt parser and pushed it to the text tracks. Should be relatively easy to add.

Ill post an example here of what ive done for refrence, but this sort of behaviour is required for live streams as we are generating subtitles on the fly.

**Comment by tdrews** [comment]
We will definitely be looking at enhanced subtitle support post v1.5.0. Please see #111 and #146.

**Comment by kfwerf** [comment]
Cheers! Ill add a gist of the code somewhere for reference once im done adding it, might be helpfull for the shaka player and am not a official contributor yet

**Comment by kfwerf** [comment]
We added some initial segmented subtitle support. See here: https://github.com/tvoli/shaka-player/tree/table-flip-subtitles

Our implementation is not really by the book yet so i dont think we can add it as a contribution yet, but maybe its a nice reference for implementing segmented subtitles

**Comment by joeyparrish** [comment]
@kfwerf I wanted to check in and confirm what you're doing in your fork to see how well aligned we are with Shaka 2.  Your sample manifest uses text/vtt, and your implementation seems to use browser's built-in VTT support.  So these are complete WebVTT text files, as opposed to VTT cues packaged in ISO BMFF segments?

**Comment by sanbornhnewyyz** [comment]
I'm confused about where this issue ended up and what the WebVTT support is in V2. This issue seems to be related to segmented VTT files in a text/vtt format whereas #277 was about support for segmented WebVTT in mp4 segments. Is there support for both or only the latter?

**Comment by joeyparrish** [comment]
Sorry for the confusion.  We have supported segmented text in general and "text/vtt" in specific since February.  Support for "application/mp4; codecs=wvtt" was added 3 days ago.

Support for segmented text in general is a consequence of how we load text in v2, in a MediaSource-like way.  This is independent of the individual parsers.  We now have parsers for both text/vtt and VTT in MP4.
