### ISSUE TITLE
CDATA in DASH Location tag

### ISSUE THREAD

**Issue by tmagnien** [google/shaka-player#1508]
Hi. We're using DASH Location tag to load-balance our streams on different servers.

However, our URL has a query string and `&` characters should be quoted to `&amp;`. I tried enclosing it in a CDATA block but it does not seem to work. Is this normal ? (Using &amp; works but it would be easier for me not to rewrite the URL).

Thanks,
Thierry

**Comment by vaage** [comment]
@tmagnien does @TheModMaker instructions fix your problem?

**Comment by tmagnien** [comment]
Hi. Sorry, I realize my question was not clear.

To sum up, this works:
`<Location>http://somedomain/url?foo=1&amp;bar=2</Location>`

But this is ignored:
`<Location><![CDATA[http://somedomain/url?foo=1&bar=2]]></Location>`

And I wanted to know if this is expected behaviour, as the 2nd form using CDATA is easier for me to generate.

Thanks,
Thierry

**Comment by TheModMaker** [comment]
I don't really see a reason this shouldn't be supported.  It should be a simple fix.  I'll add it to our next release.
