### ISSUE TITLE
Exceptions while destroy()

### ISSUE THREAD

**Issue by jozefchutka** [google/shaka-player#151]
Using shaka-player.compiled.js v1.4.0 I can observe two exceptions when destroying player instance. Here is my test player - clicking in the document a current instance of player is disposed and a new one created:

```html
<!DOCTYPE html>
<html>
<head>
<meta charset='utf-8'/>
<title>Shaka Player</title>
<style>video {display: block;}</style>
<script src="http://shaka-player-demo.appspot.com/shaka-player.compiled.js"></script>
</head>
<body>
	<script>
		(function () { "use strict";
		var Main = function() {
			var _g = this;
			window.document.body.addEventListener("click",function(event) {
				_g.reloadPlayer();
			});
			this.initPlayer();
		};
		Main.main = function() {
			new Main();
		};
		Main.prototype = {
			initPlayer: function() {
				console.log("initPlayer");
				shaka.polyfill.installAll();
				this.createPlayer();
			}
			,createPlayer: function() {
				this.element = window.document.createElement("video");
				this.element.autoplay = true;
				window.document.body.appendChild(this.element);
				var mpdUrl = "http://shaka-player-demo.appspot.com/assets/angel_one.mpd";
				var estimator = new shaka.util.EWMABandwidthEstimator();
				var source = new shaka.player.DashVideoSource(mpdUrl,null,estimator,null);
				this.player = new shaka.player.Player(this.element);
				this.player.load(source);
			}
			,disposePlayer: function() {
				this.player.unload();
				this.player.destroy();
			}
			,reloadPlayer: function() {
				this.disposePlayer();
				this.createPlayer();
				this.disposePlayer();
				this.createPlayer();
			}
		};
		Main.main();
		})();
	</script>
</body>
</html>
```

First exception seems to be related to `<style>video {display: block;}</style>`:
```
Uncaught (in promise) TypeError: Cannot read property 'reject' of null
    at Be.<anonymous> (http://shaka-player-demo.appspot.com/shaka-player.compiled.js:108:133)(anonymous function) @ shaka-player.compiled.js:108
```

Second one seems to be related to quickly destroying and recreating player. It is easily replicated by creating and destroying the player twice in a row (see dispose/create/dispose/create sequence)

```
Uncaught (in promise) TypeError: Cannot read property 'addEventListener' of null
    at new Ua (http://shaka-player-demo.appspot.com/shaka-player.compiled.js:16:868)
    at J (http://shaka-player-demo.appspot.com/shaka-player.compiled.js:16:563)
    at Q.<anonymous> (http://shaka-player-demo.appspot.com/shaka-player.compiled.js:76:328)Ua @ shaka-player.compiled.js:16J @ shaka-player.compiled.js:16(anonymous function) @ shaka-player.compiled.js:76
```

Its also worth mentioning that unload() seems to be required before destroy(). I would suggest to have that call inside destroy() so memory can be released easily by calling just one master method.

**Comment by tdrews** [comment]
`Player.destroy()` does call `Player.unload()`, but both of these methods return a promise (it's unfortunate that they have to return a promise, but it's required to reset encrypted media extensions). So, you should be able to avoid the exceptions by doing something like this,
``` javascript
var reload = function(mpd) {
  return player.unload().then(function() {
    return player.load(newMpdUrl, null, sameEstimator, null);
  });
};
```

**Comment by jozefchutka** [comment]
would it be possible to implement fix in the shaka player so it would not throw these exceptions?

**Comment by joeyparrish** [comment]
@jozefchutka Do you still get these exceptions when you follow advice from @tdrews about the unload promise?

**Comment by jozefchutka** [comment]
hi joeyparrish, the async solution is not ideal in my case as I need to destroy old instance / change source synchronously. Is it preffered the Player instance to be reused or new one to be recreated for every new source?

**Comment by joeyparrish** [comment]
@jozefchutka 

For what it's worth, the Player is designed to be reusable.  You are welcome to create new Player instances if you like, but if there are still async processes happening with your video tag, attaching a new Player to the same tag before that completes may cause problems for you.

If you intend to create new Players, you should either wait for the old one to be destroyed or add remove the old video tag from the DOM and create a new one for the new Player.  However, given that we designed Player to be reusable, I really can't see any reason to do it.  Plus, this process would still be async.

The asynchronicity of unload() cannot be avoided due to the asynchronicity of EME APIs that must be used during unload().

My recommendation is to call load() with a first source, then when you want to change sources, just call load() again.  load(), which is async, will call unload() internally if need be and wait for the result.  If you need to destroy the player, just call destroy() instead of unload() and destroy().  The destroy() method, like load(), will call unload() internally if needed.

Does this work for you?  If not, can you explain your use case?  I don't understand why a real application would do the things you are doing in your sample above.

**Comment by jozefchutka** [comment]
@joeyparrish you can see I try to create a new video instance for each Player insntance so that should not be an issue. I have also tried to remove <video> element in dispose method but the same exceptions appear. I understand that EME APIs are asynchronous, however I would expect shaka to correctly handle its own implementation. There is no problem with playback not being initiated but rather there are exceptions flying around like `Cannot read property 'addEventListener' of null` that could easily be avoided on shaka side.

In my realworld application I need to navigate around a singe page app and there is <video> in some sections. I prefer to create and add new video and new shaka for each of these sections as it might require different drm/configuration etc., but I can not guarantee the user will wait long enough for async process to finish when he navigates to a new page.

**Comment by joeyparrish** [comment]
@jozefchutka, I see.  Well, we did not consider rapid creation and destruction as a use case, but it seems reasonable to expect destruction to interrupt async processes and cause their failure.  Any Promises returned to you would be rejected, and your application would then have to avoid calling methods on that instance from any handlers you attach to that Promise.

For what it's worth, I would still recommend against calling unload() and then destroy() synchronously.  Just destroy() should suffice, and will trigger the same logic as unload() during the destruction process.

I notice you say that these exceptions could "easily be avoided".  Does that mean you have already looked into it and worked out the fix?  Do you have a patch ready?  Or is this something you would still like us to work on?

Thanks,
Joey

**Comment by jozefchutka** [comment]
@joeyparrish, I can not recall why I needed to call unload() before destroy(), but I can confirm that even without unload() being called it does work the same in my test. So I can see the same exception while new video being created correctly and old one is gone. If I recall the reason, I will report it as a separate issue. 

By saying easily avoided I referred to the fact that apart from the exception in the console the player works as expected, and as that one seems to be a null pointer it can be avoided by having a null check in place. I do not have a patch or fix on my side.

**Comment by joeyparrish** [comment]
I have a fix for this in review, including new Player tests to cover your use case.  Thanks for the report!

**Comment by joeyparrish** [comment]
Found one more case we missed.

**Comment by jozefchutka** [comment]
great job. thanks @joeyparrish
