### ISSUE TITLE
Empty VTT file not supported in Shaka Player

### ISSUE THREAD

**Issue by kqyang** [google/shaka-player#1510]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:

Yes.

**What version of Shaka Player are you using?**:

Latest demo.

**Can you reproduce the issue with our latest release version?**:

Yes.

**Can you reproduce the issue with the latest code from `master`?**:

**Are you using the demo app or your own custom app?**:

Demo app.

**If custom app, can you reproduce the issue using our demo app?**:

**What browser and OS are you using?**:

Chrome on Linux.

**What are the manifest and license server URIs?**:

https://storage.googleapis.com/wvtemp/kqyang/vtt0/bourne_1000k.m3u8

**What did you do?**

Click "Load" to play the media.

**What did you expect to happen?**

Content plays.

**What actually happened?**

Shaka Error TEXT.UNABLE_TO_EXTRACT_CUE_START_TIME (TypeError: Cannot read property 'startTime' of undefined)

The VTT files referenced in the text playlists are empty with just one line:

```
WEBVTT

```

The playlist plays in Safari and hls.js. Also, The file is compliant to WEBVTT spec here: https://www.w3.org/TR/webvtt1/#file-structure. 

Let me know if I missed anything.

**Comment by joeyparrish** [comment]
Replaced by #1563, as this is part of a broader issue we have with HLS text.
