### ISSUE TITLE
Opera browser fails to play 96khZ audio

### ISSUE THREAD

**Issue by sasank4git** [google/shaka-player#1511]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:
yes

**What version of Shaka Player are you using?**:
Tested with github latest code and also with hosted demo
 
**Can you reproduce the issue with our latest release version?**:
yes

**Can you reproduce the issue with the latest code from `master`?**:
Yes

**Are you using the demo app or your own custom app?**:
Custom app , but the issue can be reproduced with demo app also

**If custom app, can you reproduce the issue using our demo app?**:
Yes

**What browser and OS are you using?**:
Windows 10 and Browser - Opera
Our customers are facing the same problem in Windows chrome browser also.We are not able reproduce the issue in chrome browser but able to reproduce in opera.
 
**What are the manifest and license server URIs?**:
https://s3-ap-southeast-1.amazonaws.com/learnyst/testfolder/video/i30test/01_MatterwebTrack.mpd
This is not DRM. So, no license is required

**What did you do?**
We tried to play this mpd with the latest master code and also with hosted demo in Opera browser.

**What did you expect to happen?**
Video should play without errors .We have hundreds of videos working fine but issue is with only five videos.

**What actually happened?**
Video playback failed because of audio decode issues. Below is the attached log.

Log:
Player errorshaka.util.Error {
  "severity": 2,
  "category": 3,
  "code": 3016,
  "data": [
    4,
    null,
    "DECODER_ERROR_NOT_SUPPORTED: audio decoder initialization failed"
  ],
  "handled": false,
  "message": "Shaka Error MEDIA.VIDEO_ERROR (4,,DECODER_ERROR_NOT_SUPPORTED: audio decoder initialization failed)",
  "stack": "Error: Shaka Error MEDIA.VIDEO_ERROR (4,,DECODER_ERROR_NOT_SUPPORTED: audio decoder initialization failed)\n    at new shaka.util.Error (https://shaka-player-demo.appspot.com/lib/util/error.js:89:13)\n    at shaka.Player.onVideoError_ (https://shaka-player-demo.appspot.com/lib/player.js:3123:17)"
}
failed to get buffered range for videoInvalidStateError: Failed to read the 'buffered' property from 'SourceBuffer': This SourceBuffer has been removed from the parent media source.
(video:1)failed fetch and append: code=3015
failed to get buffered range for audioInvalidStateError: Failed to read the 'buffered' property from 'SourceBuffer': This SourceBuffer has been removed from the parent media source.
(audio:5)failed fetch and append: code=3015
Player errorshaka.util.Error {
  "severity": 2,
  "category": 3,
  "code": 3015,
  "data": [
    {
      "stack": "Error: Failed to execute 'appendBuffer' on 'SourceBuffer': This SourceBuffer has been removed from the parent media source.\n    at shaka.media.MediaSourceEngine.append_ (https://shaka-player-demo.appspot.com/lib/media/media_source_engine.js:716:36)\n    at shaka.media.MediaSourceEngine.enqueueOperation_ (https://shaka-player-demo.appspot.com/lib/media/media_source_engine.js:890:17)\n    at shaka.media.MediaSourceEngine.appendBuffer (https://shaka-player-demo.appspot.com/lib/media/media_source_engine.js:515:17)\n    at shaka.media.StreamingEngine.<anonymous> (https://shaka-player-demo.appspot.com/lib/media/streaming_engine.js:1746:52)"
    }
  ],
  "handled": false,
  "message": "Shaka Error MEDIA.MEDIA_SOURCE_OPERATION_THREW (InvalidStateError: Failed to execute 'appendBuffer' on 'SourceBuffer': This SourceBuffer has been removed from the parent media source.)",
  "stack": "Error: Shaka Error MEDIA.MEDIA_SOURCE_OPERATION_THREW (InvalidStateError: Failed to execute 'appendBuffer' on 'SourceBuffer': This SourceBuffer has been removed from the parent media source.)\n    at new shaka.util.Error (https://shaka-player-demo.appspot.com/lib/util/error.js:89:13)\n    at shaka.media.MediaSourceEngine.enqueueOperation_ (https://shaka-player-demo.appspot.com/lib/media/media_source_engine.js:899:28)\n    at shaka.media.MediaSourceEngine.appendBuffer (https://shaka-player-demo.appspot.com/lib/media/media_source_engine.js:515:17)\n    at shaka.media.StreamingEngine.<anonymous> (https://shaka-player-demo.appspot.com/lib/media/streaming_engine.js:1746:52)"
}
Player errorshaka.util.Error {
  "severity": 2,
  "category": 3,
  "code": 3015,
  "data": [
    {
      "stack": "Error: Failed to execute 'appendBuffer' on 'SourceBuffer': This SourceBuffer has been removed from the parent media source.\n    at shaka.media.MediaSourceEngine.append_ (https://shaka-player-demo.appspot.com/lib/media/media_source_engine.js:716:36)\n    at shaka.media.MediaSourceEngine.enqueueOperation_ (https://shaka-player-demo.appspot.com/lib/media/media_source_engine.js:890:17)\n    at shaka.media.MediaSourceEngine.appendBuffer (https://shaka-player-demo.appspot.com/lib/media/media_source_engine.js:515:17)\n    at shaka.media.StreamingEngine.<anonymous> (https://shaka-player-demo.appspot.com/lib/media/streaming_engine.js:1746:52)"
    }
  ],
  "handled": false,
  "message": "Shaka Error MEDIA.MEDIA_SOURCE_OPERATION_THREW (InvalidStateError: Failed to execute 'appendBuffer' on 'SourceBuffer': This SourceBuffer has been removed from the parent media source.)",
  "stack": "Error: Shaka Error MEDIA.MEDIA_SOURCE_OPERATION_THREW (InvalidStateError: Failed to execute 'appendBuffer' on 'SourceBuffer': This SourceBuffer has been removed from the parent media source.)\n    at new shaka.util.Error (https://shaka-player-demo.appspot.com/lib/util/error.js:89:13)\n    at shaka.media.MediaSourceEngine.enqueueOperation_ (https://shaka-player-demo.appspot.com/lib/media/media_source_engine.js:899:28)\n    at shaka.media.MediaSourceEngine.appendBuffer (https://shaka-player-demo.appspot.com/lib/media/media_source_engine.js:515:17)\n    at shaka.media.StreamingEngine.<anonymous> (https://shaka-player-demo.appspot.com/lib/media/streaming_engine.js:1746:52)"
}
Unload latency:0.002
notifyNewSegmentDuration:maxSegmentDuration=1
Found variant with audio and video content, so filtering all periods.
codecsavc1-mp4aavg bandwidth759125
onChooseStreams_{"startTime":0,"textStreams":[],"variants":[{"id":7,"language":"en","primary":true,"audio":{"id":5,"initSegmentReference":{"startByte":0,"endByte":655},"presentationTimeOffset":0,"mimeType":"audio/mp4","codecs":"mp4a.40.2","bandwidth":127500,"encrypted":false,"keyId":null,"language":"en","label":null,"type":"audio","primary":true,"trickModeVideo":null,"containsEmsgBoxes":false,"roles":["main"],"channelsCount":2},"video":{"id":1,"initSegmentReference":{"startByte":0,"endByte":722},"presentationTimeOffset":0,"mimeType":"video/mp4","codecs":"avc1.42c01f","frameRate":30,"bandwidth":90400,"width":256,"height":144,"encrypted":false,"keyId":null,"language":"und","label":null,"type":"video","primary":true,"trickModeVideo":null,"containsEmsgBoxes":false,"roles":["main"],"channelsCount":null},"bandwidth":217900,"drmInfos":[],"allowedByApplication":true,"allowedByKeySystem":true},{"id":8,"language":"en","primary":true,"audio":{"id":5,"initSegmentReference":{"startByte":0,"endByte":655},"presentationTimeOffset":0,"mimeType":"audio/mp4","codecs":"mp4a.40.2","bandwidth":127500,"encrypted":false,"keyId":null,"language":"en","label":null,"type":"audio","primary":true,"trickModeVideo":null,"containsEmsgBoxes":false,"roles":["main"],"channelsCount":2},"video":{"id":2,"initSegmentReference":{"startByte":0,"endByte":723},"presentationTimeOffset":0,"mimeType":"video/mp4","codecs":"avc1.42c01f","frameRate":30,"bandwidth":455200,"width":640,"height":360,"encrypted":false,"keyId":null,"language":"und","label":null,"type":"video","primary":true,"trickModeVideo":null,"containsEmsgBoxes":false,"roles":["main"],"channelsCount":null},"bandwidth":582700,"drmInfos":[],"allowedByApplication":true,"allowedByKeySystem":true},{"id":9,"language":"en","primary":true,"audio":{"id":5,"initSegmentReference":{"startByte":0,"endByte":655},"presentationTimeOffset":0,"mimeType":"audio/mp4","codecs":"mp4a.40.2","bandwidth":127500,"encrypted":false,"keyId":null,"language":"en","label":null,"type":"audio","primary":true,"trickModeVideo":null,"containsEmsgBoxes":false,"roles":["main"],"channelsCount":2},"video":{"id":3,"initSegmentReference":{"startByte":0,"endByte":791},"presentationTimeOffset":0,"mimeType":"video/mp4","codecs":"avc1.42c01f","frameRate":30,"bandwidth":701700,"width":854,"height":480,"encrypted":false,"keyId":null,"language":"und","label":null,"type":"video","primary":true,"trickModeVideo":null,"containsEmsgBoxes":false,"roles":["main"],"channelsCount":null},"bandwidth":829200,"drmInfos":[],"allowedByApplication":true,"allowedByKeySystem":true},{"id":10,"language":"en","primary":true,"audio":{"id":5,"initSegmentReference":{"startByte":0,"endByte":655},"presentationTimeOffset":0,"mimeType":"audio/mp4","codecs":"mp4a.40.2","bandwidth":127500,"encrypted":false,"keyId":null,"language":"en","label":null,"type":"audio","primary":true,"trickModeVideo":null,"containsEmsgBoxes":false,"roles":["main"],"channelsCount":2},"video":{"id":4,"initSegmentReference":{"startByte":0,"endByte":792},"presentationTimeOffset":0,"mimeType":"video/mp4","codecs":"avc1.42c01f","frameRate":30,"bandwidth":1279200,"width":1198,"height":674,"encrypted":false,"keyId":null,"language":"und","label":null,"type":"video","primary":true,"trickModeVideo":null,"containsEmsgBoxes":false,"roles":["main"],"channelsCount":null},"bandwidth":1406700,"drmInfos":[],"allowedByApplication":true,"allowedByKeySystem":true}]}
Choosing new streams after period changed
onChooseStreams_, variants and text streams: [{"id":7,"language":"en","primary":true,"audio":{"id":5,"initSegmentReference":{"startByte":0,"endByte":655},"presentationTimeOffset":0,"mimeType":"audio/mp4","codecs":"mp4a.40.2","bandwidth":127500,"encrypted":false,"keyId":null,"language":"en","label":null,"type":"audio","primary":true,"trickModeVideo":null,"containsEmsgBoxes":false,"roles":["main"],"channelsCount":2},"video":{"id":1,"initSegmentReference":{"startByte":0,"endByte":722},"presentationTimeOffset":0,"mimeType":"video/mp4","codecs":"avc1.42c01f","frameRate":30,"bandwidth":90400,"width":256,"height":144,"encrypted":false,"keyId":null,"language":"und","label":null,"type":"video","primary":true,"trickModeVideo":null,"containsEmsgBoxes":false,"roles":["main"],"channelsCount":null},"bandwidth":217900,"drmInfos":[],"allowedByApplication":true,"allowedByKeySystem":true},{"id":8,"language":"en","primary":true,"audio":{"id":5,"initSegmentReference":{"startByte":0,"endByte":655},"presentationTimeOffset":0,"mimeType":"audio/mp4","codecs":"mp4a.40.2","bandwidth":127500,"encrypted":false,"keyId":null,"language":"en","label":null,"type":"audio","primary":true,"trickModeVideo":null,"containsEmsgBoxes":false,"roles":["main"],"channelsCount":2},"video":{"id":2,"initSegmentReference":{"startByte":0,"endByte":723},"presentationTimeOffset":0,"mimeType":"video/mp4","codecs":"avc1.42c01f","frameRate":30,"bandwidth":455200,"width":640,"height":360,"encrypted":false,"keyId":null,"language":"und","label":null,"type":"video","primary":true,"trickModeVideo":null,"containsEmsgBoxes":false,"roles":["main"],"channelsCount":null},"bandwidth":582700,"drmInfos":[],"allowedByApplication":true,"allowedByKeySystem":true},{"id":9,"language":"en","primary":true,"audio":{"id":5,"initSegmentReference":{"startByte":0,"endByte":655},"presentationTimeOffset":0,"mimeType":"audio/mp4","codecs":"mp4a.40.2","bandwidth":127500,"encrypted":false,"keyId":null,"language":"en","label":null,"type":"audio","primary":true,"trickModeVideo":null,"containsEmsgBoxes":false,"roles":["main"],"channelsCount":2},"video":{"id":3,"initSegmentReference":{"startByte":0,"endByte":791},"presentationTimeOffset":0,"mimeType":"video/mp4","codecs":"avc1.42c01f","frameRate":30,"bandwidth":701700,"width":854,"height":480,"encrypted":false,"keyId":null,"language":"und","label":null,"type":"video","primary":true,"trickModeVideo":null,"containsEmsgBoxes":false,"roles":["main"],"channelsCount":null},"bandwidth":829200,"drmInfos":[],"allowedByApplication":true,"allowedByKeySystem":true},{"id":10,"language":"en","primary":true,"audio":{"id":5,"initSegmentReference":{"startByte":0,"endByte":655},"presentationTimeOffset":0,"mimeType":"audio/mp4","codecs":"mp4a.40.2","bandwidth":127500,"encrypted":false,"keyId":null,"language":"en","label":null,"type":"audio","primary":true,"trickModeVideo":null,"containsEmsgBoxes":false,"roles":["main"],"channelsCount":2},"video":{"id":4,"initSegmentReference":{"startByte":0,"endByte":792},"presentationTimeOffset":0,"mimeType":"video/mp4","codecs":"avc1.42c01f","frameRate":30,"bandwidth":1279200,"width":1198,"height":674,"encrypted":false,"keyId":null,"language":"und","label":null,"type":"video","primary":true,"trickModeVideo":null,"containsEmsgBoxes":false,"roles":["main"],"channelsCount":null},"bandwidth":1406700,"drmInfos":[],"allowedByApplication":true,"allowedByKeySystem":true}][]
Bandwidth ranges:0.2180.2290.686
Bandwidth ranges:0.5830.6130.976
Bandwidth ranges:0.8290.8731.655
Bandwidth ranges:1.4071.481Infinity
onChooseStreams_, chosen={"id":7,"language":"en","primary":true,"audio":{"id":5,"initSegmentReference":{"startByte":0,"endByte":655},"presentationTimeOffset":0,"mimeType":"audio/mp4","codecs":"mp4a.40.2","bandwidth":127500,"encrypted":false,"keyId":null,"language":"en","label":null,"type":"audio","primary":true,"trickModeVideo":null,"containsEmsgBoxes":false,"roles":["main"],"channelsCount":2},"video":{"id":1,"initSegmentReference":{"startByte":0,"endByte":722},"presentationTimeOffset":0,"mimeType":"video/mp4","codecs":"avc1.42c01f","frameRate":30,"bandwidth":90400,"width":256,"height":144,"encrypted":false,"keyId":null,"language":"und","label":null,"type":"video","primary":true,"trickModeVideo":null,"containsEmsgBoxes":false,"roles":["main"],"channelsCount":null},"bandwidth":217900,"drmInfos":[],"allowedByApplication":true,"allowedByKeySystem":true}null
(all) setting up Stream 5
(all) setting up Stream 1
Segment downloaded:deltaTimeMs=393numBytes=6236lastTimeChosenMs=1532764385592enabled=false
Parsing MP4 boxsidx
notifySegments:maxSegmentDuration=4
Segment downloaded:deltaTimeMs=411numBytes=1688lastTimeChosenMs=1532764385592enabled=false
Parsing MP4 boxsidx
notifySegments:maxSegmentDuration=15.008
(all) setup Stream 5
(all) setup Stream 1
(audio:5)updating in 0 seconds
(video:1)updating in 0 seconds
init: completed initial Stream setup
(audio:5)timeNeeded=0
(audio:5)update_:playheadTime=0bufferedAhead=0
(audio:5)next position unknown: nothing buffered
(audio:5)looking up segment:presentationTime=0currentPeriod.startTime=0
(audio:5)fetchAndAppend_:playheadTime=0currentPeriod.startTime=0reference.position=0reference.startTime=0reference.endTime=15.008
(audio:5)setting timestamp offset to 0
(audio:5)setting appstart window start to 0
(audio:5)setting append window end to 2064
(audio:5)fetching init segment
fetching: reference=[object Object]
(audio:5)fetching segment
fetching: reference=[object Object]
(video:1)timeNeeded=0
(video:1)update_:playheadTime=0bufferedAhead=0
(video:1)next position unknown: nothing buffered
(video:1)looking up segment:presentationTime=0currentPeriod.startTime=0
(video:1)fetchAndAppend_:playheadTime=0currentPeriod.startTime=0reference.position=0reference.startTime=0reference.endTime=4
(video:1)setting timestamp offset to 0
(video:1)setting appstart window start to 0
(video:1)setting append window end to 2064
(video:1)fetching init segment
fetching: reference=[object Object]
(video:1)fetching segment
fetching: reference=[object Object]
Segment downloaded:deltaTimeMs=63numBytes=656lastTimeChosenMs=1532764385592enabled=false
(audio:5)appending init segment
Segment downloaded:deltaTimeMs=70numBytes=723lastTimeChosenMs=1532764385592enabled=false
(video:1)appending init segment
Player errorshaka.util.Error {
  "severity": 2,
  "category": 3,
  "code": 3016,
  "data": [
    4,
    null,
    "DECODER_ERROR_NOT_SUPPORTED: audio decoder initialization failed"
  ],
  "handled": false,
  "message": "Shaka Error MEDIA.VIDEO_ERROR (4,,DECODER_ERROR_NOT_SUPPORTED: audio decoder initialization failed)",
  "stack": "Error: Shaka Error MEDIA.VIDEO_ERROR (4,,DECODER_ERROR_NOT_SUPPORTED: audio decoder initialization failed)\n    at new shaka.util.Error (https://shaka-player-demo.appspot.com/lib/util/error.js:89:13)\n    at shaka.Player.onVideoError_ (https://shaka-player-demo.appspot.com/lib/player.js:3123:17)"
}
Segment downloaded:deltaTimeMs=174numBytes=252247lastTimeChosenMs=1532764385592enabled=false
(audio:5)checking buffer length
failed to get buffered range for audioInvalidStateError: Failed to read the 'buffered' property from 'SourceBuffer': This SourceBuffer has been removed from the parent media source.
(audio:5)buffer behind okay because nothing buffered:playheadTime=0bufferBehind=30
(audio:5)appending media segment
(audio:5)failed fetch and append: code=3015
Segment downloaded:deltaTimeMs=187numBytes=15167lastTimeChosenMs=1532764385592enabled=false
(video:1)checking buffer length
failed to get buffered range for videoInvalidStateError: Failed to read the 'buffered' property from 'SourceBuffer': This SourceBuffer has been removed from the parent media source.
(video:1)buffer behind okay because nothing buffered:playheadTime=0bufferBehind=30
(video:1)appending media segment
(video:1)failed fetch and append: code=3015
Player errorshaka.util.Error {
  "severity": 2,
  "category": 3,
  "code": 3015,
  "data": [
    {
      "stack": "Error: Failed to execute 'appendBuffer' on 'SourceBuffer': This SourceBuffer has been removed from the parent media source.\n    at shaka.media.MediaSourceEngine.append_ (https://shaka-player-demo.appspot.com/lib/media/media_source_engine.js:716:36)\n    at shaka.media.MediaSourceEngine.enqueueOperation_ (https://shaka-player-demo.appspot.com/lib/media/media_source_engine.js:890:17)\n    at shaka.media.MediaSourceEngine.appendBuffer (https://shaka-player-demo.appspot.com/lib/media/media_source_engine.js:515:17)\n    at shaka.media.StreamingEngine.<anonymous> (https://shaka-player-demo.appspot.com/lib/media/streaming_engine.js:1746:52)"
    }
  ],
  "handled": false,
  "message": "Shaka Error MEDIA.MEDIA_SOURCE_OPERATION_THREW (InvalidStateError: Failed to execute 'appendBuffer' on 'SourceBuffer': This SourceBuffer has been removed from the parent media source.)",
  "stack": "Error: Shaka Error MEDIA.MEDIA_SOURCE_OPERATION_THREW (InvalidStateError: Failed to execute 'appendBuffer' on 'SourceBuffer': This SourceBuffer has been removed from the parent media source.)\n    at new shaka.util.Error (https://shaka-player-demo.appspot.com/lib/util/error.js:89:13)\n    at shaka.media.MediaSourceEngine.enqueueOperation_ (https://shaka-player-demo.appspot.com/lib/media/media_source_engine.js:899:28)\n    at shaka.media.MediaSourceEngine.appendBuffer (https://shaka-player-demo.appspot.com/lib/media/media_source_engine.js:515:17)\n    at shaka.media.StreamingEngine.<anonymous> (https://shaka-player-demo.appspot.com/lib/media/streaming_engine.js:1746:52)"
}
Player errorshaka.util.Error {
  "severity": 2,
  "category": 3,
  "code": 3015,
  "data": [
    {
      "stack": "Error: Failed to execute 'appendBuffer' on 'SourceBuffer': This SourceBuffer has been removed from the parent media source.\n    at shaka.media.MediaSourceEngine.append_ (https://shaka-player-demo.appspot.com/lib/media/media_source_engine.js:716:36)\n    at shaka.media.MediaSourceEngine.enqueueOperation_ (https://shaka-player-demo.appspot.com/lib/media/media_source_engine.js:890:17)\n    at shaka.media.MediaSourceEngine.appendBuffer (https://shaka-player-demo.appspot.com/lib/media/media_source_engine.js:515:17)\n    at shaka.media.StreamingEngine.<anonymous> (https://shaka-player-demo.appspot.com/lib/media/streaming_engine.js:1746:52)"
    }
  ],
  "handled": false,
  "message": "Shaka Error MEDIA.MEDIA_SOURCE_OPERATION_THREW (InvalidStateError: Failed to execute 'appendBuffer' on 'SourceBuffer': This SourceBuffer has been removed from the parent media source.)",
  "stack": "Error: Shaka Error MEDIA.MEDIA_SOURCE_OPERATION_THREW (InvalidStateError: Failed to execute 'appendBuffer' on 'SourceBuffer': This SourceBuffer has been removed from the parent media source.)\n    at new shaka.util.Error (https://shaka-player-demo.appspot.com/lib/util/error.js:89:13)\n    at shaka.media.MediaSourceEngine.enqueueOperation_ (https://shaka-player-demo.appspot.com/lib/media/media_source_engine.js:899:28)\n    at shaka.media.MediaSourceEngine.appendBuffer (https://shaka-player-demo.appspot.com/lib/media/media_source_engine.js:515:17)\n    at shaka.media.StreamingEngine.<anonymous> (https://shaka-player-demo.appspot.com/lib/media/streaming_engine.js:1746:52)"
}

**Comment by TheModMaker** [comment]
Unfortunately there isn't anything we can do for this.  The browser doesn't support playing your content.  Since it plays fine in Chrome, you may want to file a bug with Opera ([link](https://bugs.opera.com/wizard/)).

Some things to try:
- Make sure Opera is up to date.
- Make sure you've installed Windows updates.
- Make sure your graphics drivers are up to date.
- Try disabling hardware decode.
- Try installing a third-party codec pack (Opera may be using the system decoders).

**Comment by sasank4git** [comment]
Thank you for the information. We will try raising an issue with opera. 
But the actual concern for us is that "few users have reported the issue is happening while using google chrome browser too",while we are unable to reproduce the issue on our end in chrome browser its happening with opera browser.

**Comment by BucherTomas** [comment]
@sasank4git  The exception complains about `audio decoder initialization failed`. The audio in your content has sampling frequency of 96000 Hz. I would say that this is the reason for the issues you are experiencing.
Resample the audio to more common 48000 or 44100 Hz and try again with Opera. Chrome likely has some internal resampling involved that takes care of this.

**Comment by TheModMaker** [comment]
@sasank4git Did you try changing the audio frequency?  Did it work?  Did you file a bug on Opera and could you provide a link?  Do you have any other questions?

**Comment by sasank4git** [comment]
@TheModMaker  Tried changing bit-rate of the audio to 64kbps and checked but it didn't help. Already raised an issue with Opera team and awaiting for the response , issue-id:ID: 
DNAWIZ-38425
,

**Comment by joeyparrish** [comment]
There doesn't seem to be anything we can do to control Opera's support for audio frequencies, so I'm closing this issue.
