### ISSUE TITLE
Duration of in-progress recording is not updated

### ISSUE THREAD

**Issue by chrisfillmore** [google/shaka-player#1513]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:
Yes

**What version of Shaka Player are you using?**:
2.3.4 (in production) and 2.4.0 (in testing right now)

**Can you reproduce the issue with our latest release version?**:
Yes, also tested in 2.4.2

**Can you reproduce the issue with the latest code from `master`?**:
Yes

**Are you using the demo app or your own custom app?**:
Custom app

**If custom app, can you reproduce the issue using our demo app?**:
No, there is a custom authorization flow

**What browser and OS are you using?**:
Chrome 68 macOS

**What are the manifest and license server URIs?**:
I am working on getting credentials for you to observe the problem in our prod environment. I will email when I have them.

**What did you do?**
Attempt to play an in-progress recording of some live content. The DASH manifest has an increasing `mediaPresentationDuration` and `Period@duration` (the values are the same).

**What did you expect to happen?**
Playback should continue smoothly until the end of the recording, and the video duration should be updated as the recording grows longer.

**What actually happened?**
Playback stops after the initial recorded duration of content (that is, the value of `mediaPresentationDuration` from the first manifest requested at the start of playback. When the player reaches this point, it continues to fetch updated manifests but does not fetch segments, so playback stalls.

I see that Shaka only calls `MediaSourceEngine#setDuration` at the start of playback. This seems unexpected. How does Shaka handle increasing presentation duration?

**Comment by chrisfillmore** [comment]
From discussion in #1148 it seems unclear if the duration must be known at the start of playback.

**Comment by TheModMaker** [comment]
Is the duration you set the duration of the content in the manifest or is it longer than the content available?  If we didn't do a manifest update, could we play to the duration or would it run out of available content?

The idea of IPR is that we know the duration ahead of time; if you are changing the duration, why not use a normal live stream?  Once the live stream ends you can convert it to VOD.

We set the duration at the beginning since not having a duration makes seeking not work well.  Even for live streams we set a huge duration so that we can seek while playing.  We could increase the duration while we play, but decreasing it would be difficult.

It looks like the DASH parser already updates the duration in the `PresentationTimeline`, it just doesn't get updated to the `<video>`.  We may be able to support changing the duration in the future, but I'll but this on the backlog for now.

**Comment by chrisfillmore** [comment]
>Is the duration you set the duration of the content in the manifest or is it longer than the content available? If we didn't do a manifest update, could we play to the duration or would it run out of available content?

The duration is the duration of the content available. On inspection I see that `mediaPresentationDuration` is one segment length longer than the sum of all segments described in the manifest. We are using 6s segments. For example:

```
<MPD availabilityStartTime="2018-07-30T16:45:07.578Z" mediaPresentationDuration="PT2M54.174S" minBufferTime="PT4S" minimumUpdatePeriod="PT6.006S" profiles="urn:mpeg:dash:profile:isoff-live:2011" publishTime="2018-07-30T16:48:54.000000Z" type="dynamic" xmlns="urn:mpeg:dash:schema:mpd:2011" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011 http://standards.iso.org/ittf/PubliclyAvailableStandards/MPEG-DASH_schema_files/DASH-MPD.xsd" xmlns:cenc="urn:mpeg:cenc:2013" xmlns:mspr="urn:microsoft:playready">
  <Period duration="PT2M54.174S" id="0zB9AK2PRki_2B81Zp6jYA" start="PT0S">
...
      <SegmentTemplate initialization="pts/init.mp4" media="pts/$Time$.m4f" presentationTimeOffset="369804134700" startNumber="0" timescale="90000">
        <SegmentTimeline>
          <S d="540540" r="28" t="369804134700" />
        </SegmentTimeline>
      </SegmentTemplate>
```

Generally, in each subsequent manifest request, `mediaPresentationDuration` is increased by 6.006s, and `S@r` is incremented by 1. Without doing a manifest update, you could play this content to completion.

>The idea of IPR is that we know the duration ahead of time; if you are changing the duration, why not use a normal live stream? Once the live stream ends you can convert it to VOD.

This stream is converted to VOD once the recording is complete. At that time the MPD becomes `type="static"`. I'm not sure why we don't use a live stream for the in-progress portion, I'll check with our packaging team.

**Comment by chrisfillmore** [comment]
@TheModMaker My team did some troubleshooting on an identical issue in late January this year. At the time we were using Shaka v2.2.8 and I observed that the player was able to update the duration of an in-progress recording. However, I believe our headend services and content has changed since then. When I try to play this content with v2.2.8, it doesn't work, it stops at the recorded duration.

Looking at our old ticket, I see this is the feedback we received from our packager:

>The MediaPresentationDuration is constantly updated in the dash MPD as we add segments to it during the recording state, so if the player is only using the initial MediaPresentationDuration and its not adjusting it due to the addition of new segments then that's likely a player issue. The player should be re-requesting the dash MPD while playing out to get the updated new video segments as they are added so it should be fully aware of the new MediaPresentationDuration

**Comment by chrisfillmore** [comment]
It seems it's easy to force to player to treat the IPR as live just by removing `mediaPresentationDuration` from the manifest, which I can do in a response filter. This allows the player to play past the initial recorded duration. I will keep testing to see what happens when the presentation ends.

**Comment by chrisfillmore** [comment]
I see that if I just remove `mediaPresentationDuration` from the manifest, playback proceeds normally. When the recording ends, the stream is converted to VOD and playback ends as expected. This is a bit of a hack so I'd prefer to avoid doing this if possible.

How big is the change to add support for updating duration throughout playback? I'd be happy to add this functionality if I could be pointed to some of the key areas of the code. I made a change to `StreamingEngine#append_` to call `this.setDuration_()` after appending a new segment. The duration would update throughout playback, but playback still stalled after the initial recorded duration. What other changes would be required?

**Comment by chrisfillmore** [comment]
After some more reading of the spec, I think it's the content that is wrong. From ISO/IEC 23009-1:2014(E), 5.3.1.2 Semantics, Table 3:

> @mediaPresentationDuration specifies the duration of the entire Media Presentation. If the attribute is not present, the duration of the Media Presentation is unknown.
This attribute shall be present when neither the attribute MPD@minimumUpdatePeriod nor the Period@duration of the last Period are present.

Also in IOP 4.2, section 4.6.4 Transition Phase between Live and On-Demand
 
> In the scenario for which the same MPD URL is used for live and On-Demand content, once the URL and publish time of the last Segment is known for the live service, and the duration of the service is known as well, the service provider acts as defined in clause 4.4.3.1, i.e.,
>- adds the attribute MPD@mediaPresentationDuration

I will close. Please label "Working as intended". Thanks!
