### ISSUE TITLE
Angel One HLS Widevine clip doesn't have byte ranges

### ISSUE THREAD

**Issue by TheModMaker** [google/shaka-player#1520]
**What are the manifest and license server URIs?**:
`Angel One (HLS, MP4, multilingual, Widevine)`

**What did you do?**
Play the asset.

**What did you expect to happen?**
Stream normally; buffer progressively.

**What actually happened?**
Buffered the whole video at once.  It appears that the manifest doesn't specify any `#EXT-X-BYTERANGE` tags so Shaka Player requests the whole file.  The manifest says it was generated with Shaka Packager version `379e9de0e8`, which is from April 2017; it may be a bug in the packager that was fixed or that we need to file.

**Comment by joeyparrish** [comment]
I will regenerate this and any other out-of-date HLS assets.

**Comment by joeyparrish** [comment]
Note that the new files also will not have byte ranges, because Packager v2.2 requires separate segment files for any text stream.  Since the affects clips includes subtitles, we will just use separate segments for all streams.

**Comment by joeyparrish** [comment]
The files have been updated, but this has spawned #1563.
