### ISSUE TITLE
Player configure drm advanced settings change other key systems

### ISSUE THREAD

**Issue by TheModMaker** [google/shaka-player#1524]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:
Yes
**What version of Shaka Player are you using?**:
v2.4.2
**Can you reproduce the issue with our latest release version?**:
Yes
**Can you reproduce the issue with the latest code from `master`?**:
Yes
**Are you using the demo app or your own custom app?**:
Demo app
**If custom app, can you reproduce the issue using our demo app?**:
N/A
**What browser and OS are you using?**:
Chrome Linux and Window (and probably others)
**What are the manifest and license server URIs?**:
Any demo asset.

**What did you do?**
- Load any asset.
- Open DevTools.
- `shakaDemo.localPlayer_.getConfiguration().drm.advanced`
- `shakaDemo.localPlayer_.configure({drm: {advanced:{'com.widevine.alpha': {distinctiveIdentifierRequired: true}}}})`
- `shakaDemo.localPlayer_.getConfiguration().drm.advanced`

**What did you expect to happen?**
Should only update the `com.widevine.alpha` settings.

**What actually happened?**
The other key systems are updated to the new settings too.

**Comment by joeyparrish** [comment]
Fix cherry-picked to v2.4.5.
