### ISSUE TITLE
When starting a video from the beginning, an initial seek event is fired which may cause significant delays.

### ISSUE THREAD

**Issue by pix-dgee** [google/shaka-player#1526]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:

Yes
**What version of Shaka Player are you using?**:

2.1.0, 2.2.7, 2.4.2

**Can you reproduce the issue with our latest release version?**:
Yes, and with 2.1.0, but not with 2.2.7

**Can you reproduce the issue with the latest code from `master`?**:
Did not attempt.

**Are you using the demo app or your own custom app?**:
Custom app

**If custom app, can you reproduce the issue using our demo app?**:
Not possible

**What browser and OS are you using?**:
Chrome 67, Chrome 59, Firefox 61

**What are the manifest and license server URIs?**:
I cannot provide these

**What did you do?**
Implemented video playback using Shaka 2.1.0. Upgraded at some point to Shaka 2.2.7, released to production. Released a subsequent release that upgraded to 2.4.2

**What did you expect to happen?**
When loading a video and playing it back from the beginning of the video, no `seeking` or `seeked` events should fire before playback starts.

**What actually happened?**
When using anything but Shaka 2.2.7, an initial seek event is fired. In some cases, this initial seek event is taking over 10s to resolve, when viewing DASH content hosted on AWS Cloudfront and being viewed from London, Ukraine, or Spain. This does not occur with every view, but after testing over 1000 views, the average impact on initial playback time was ~1.5s.

Using Shaka 2.2.7, no initial seek event is fired. It does seem as if some of this overhead is moved to the `loadedmetadata` event, but without the initial seek firing, time to initial playback is substantially faster, especially over slower networks.

**Comment by theodab** [comment]
If the problem happens with a custom app that we don't have, playing custom content that you can't provide, I'm not sure how we can reproduce it.
You can send manifest and license server URIs over to the <shaka-player-issues@google.com> mailing list, if you're worried about privacy. If we have reproduction steps, we can look into the problem. There were a lot of changes related to gap-jumping and starting gaps around 2.2.7, so it's hard to say what the exact culprit for this behavior is without being able to reproduce it.

**Comment by theodab** [comment]
A manifest alone isn't enough to reproduce a problem like this, no. We'll need something that can be used to actually reproduce the problem on our end.

**Comment by chrisfillmore** [comment]
@pix-dgee There were a lot of changes between 2.2.7 and 2.4.2, I would recommend you test with each intermediate version to see when the problem appears.

This is just a thought, but a colleague had some similar-sounding seek-related problems at the start of playback. He was able to resolve them by lowering the value of `Playhead.MIN_SEEK_RANGE_` to 1.5. See https://github.com/google/shaka-player/commit/a039c66cac3308356c43c12bccd50e112fb3d916
