### ISSUE TITLE
Support for CBCS decryption

### ISSUE THREAD

**Issue by mlondon1** [google/shaka-player#1527]
Does Shaka support CBCS fmp4 / CMAF (Dash and/or HLS) content decryption now that Chrome 68 supports the decryption?

**Comment by TheModMaker** [comment]
We shouldn't have to do anything to support the new encryption.  There isn't anything we do special for encryption schemes, so it should already be supported.  The exception to that is in HLS we needed to add support for a new scheme in an HLS attribute, but that was added in #1515.

**Comment by mlondon1** [comment]
Thanks, on a related note do you also support the Playready 4.0 Header in manifests when running on Edge?

https://docs.microsoft.com/en-us/playready/packaging/content-encryption-modes

**Comment by TheModMaker** [comment]
I don't believe we touch the PlayReady headers, so I think it would only depend on the platform.  I think this data is part of the init data in the segment, which we just pass directly to the platform.  So it should be supported.

**Comment by mlondon1** [comment]
Ok thanks, we'll test.  you can close
