### ISSUE TITLE
Event for RECOVERABLE networking errors and subsequent retries

### ISSUE THREAD

**Issue by chrisfillmore** [google/shaka-player#1529]
We would like to know when a networking error occurs which results in a retry. Our application tracks this information for performance metrics purposes.

To implement such a change, it seems `NetworkingEngine` would need to accept a `PlayerInterface`, but I don't know how that would work with alternative use cases as in #1297. Perhaps the `PlayerInterface` could be optional, and `NetworkingEngine` could do:

```
// NetworkingEngine#send_
if (error && error.severity == shaka.util.Error.Severity.RECOVERABLE) {
  if (this.playerInterface) {
    this.playerInterface.onNetworkingRetry_(error); // new method
  }
  // Move to the next URI.
  index = (index + 1) % request.uris.length;
  let shakaError = /** @type {shaka.util.Error} */(error);
  return this.send_(type, request, backoff, index, shakaError);
}
```

Is this feasible?

**Comment by chrisfillmore** [comment]
@theodab I don't mind sending in a PR if we agree on a design.

**Comment by theodab** [comment]
@chrisfillmore No, I should probably do it. @vaage is currently working on #1297, so it'd probably be best to do this in-house, to avoid collisions.

**Comment by theodab** [comment]
I had a discussion with the team, and we decided that it would probably be best to avoid anything that changes the constructor of networking engine, since networking engine is also being modified as part of #1051. Instead, I will add a method on the networking engine that adds a listener function. So you'd use it like:
```
player.getNetworkingEngine().addNetworkingRetryListener((error) => {
  // Your listener code here.
});
```

**Comment by chrisfillmore** [comment]
Sounds good, thank you!

**Comment by theodab** [comment]
Okay, after another round of code review, this should be out soon.
There was some further discussion, and we decided that it should work as an event listener, using our `FakeEventListener` code. So you'd use it like:
```
player.getNetworkingEngine().addEventListener('retry', (event) => {
  let error = event.error;
  // Your listener code here.
});
```
Sorry we changed our minds so often on this!

**Comment by chrisfillmore** [comment]
Thanks, @theodab!
