### ISSUE TITLE
Typo in the documentation with availabilityWindowOverride configuration

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#1530]
availabilityWindowOverride name is missing and appears (number)

https://shaka-player-demo.appspot.com/docs/api/shakaExtern.html#.ManifestConfiguration

![image](https://user-images.githubusercontent.com/8983024/43820010-35361c40-9ae5-11e8-849c-ef7f7d499fb6.png)

**Comment by theodab** [comment]
Oops, I used parentheses in the JSDoc instead of brackets.
