### ISSUE TITLE
Master don't build

### ISSUE THREAD

**Issue by PatrikCarlander** [google/shaka-player#1536]
$ python ./build/all.py

[INFO] Checking that the build files are complete...
[INFO] Checking the tests for type errors...
//test/dash/dash_parser_manifest_unit.js:1075: ERROR - Violation: Using properties of unknown types is not allowed; add an explicit type to the variable.
The property "setResponseMapAsText" on type "shaka.test.FakeNetworkingEngine"
    fakeNetEngine.setResponseMapAsText({'dummy://foo': manifestText});
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//test/dash/dash_parser_manifest_unit.js:1075: ERROR - Property setResponseMapAsText never defined on shaka.test.FakeNetworkingEngine
    fakeNetEngine.setResponseMapAsText({'dummy://foo': manifestText});
                  ^^^^^^^^^^^^^^^^^^^^

2 error(s), 0 warning(s), 91.7% typed
[ERROR] Build failed

**Comment by TheModMaker** [comment]
Fixed in 376c5001c32b80dd17aca4d3d83843981ea4c3fe.
