### ISSUE TITLE
Support for DASHEventMessageBox Version 1

### ISSUE THREAD

**Issue by damienlevin** [google/shaka-player#1539]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:
Yes
**What version of Shaka Player are you using?**:
v2.4.3
**Can you reproduce the issue with our latest release version?**:
Yes
**Can you reproduce the issue with the latest code from `master`?**:
Yes
**Are you using the demo app or your own custom app?**:
Demo app
**If custom app, can you reproduce the issue using our demo app?**:
N/A
**What browser and OS are you using?**:
Chrome/OSX
**What are the manifest and license server URIs?**:

**What did you do?**
Play the following MPD containing emsg v1

> https://storage.googleapis.com/dlevin/dash_id3/manifest_id3_v1.mpd

**What did you expect to happen?**
Proper handling of DASHEventMessageBox v1 (see CMAF/ISO BMFF spec)

> aligned(8) class DASHEventMessageBox extends FullBox(‘emsg’, version, flags = 0){
> if (version==0) {
> string scheme_id_uri;
> string value;
> unsigned int(32) timescale;
> unsigned int(32) presentation_time_delta;
> unsigned int(32) event_duration;
> unsigned int(32) id;
> } else if (version==1) {
> unsigned int(32) timescale;
> unsigned int(64) presentation_time;
> unsigned int(32) event_duration;
> unsigned int(32) id;
> string scheme_id_uri;
> string value;
> }
> unsigned int(8) message_data[];

**What actually happened?**
Broken  playback

> "Error: Shaka Error TEXT.BAD_ENCODING ()
>     at new shaka.util.Error (https://shaka-player-demo.appspot.com/lib/util/error.js:89:13)
>     at Object.shaka.util.StringUtils.fromUTF8 (https://shaka-player-demo.appspot.com/lib/util/string_utils.js:61:11)
>     at shaka.util.DataViewReader.readTerminatedString (https://shaka-player-demo.appspot.com/lib/util/data_view_reader.js:279:33)
>     at shaka.media.StreamingEngine.parseEMSG_ (https://shaka-player-demo.appspot.com/lib/media/streaming_engine.js:1775:26)
>     at shaka.util.Mp4Parser.parseNext (https://shaka-player-demo.appspot.com/lib/util/mp4_parser.js:233:5)
>     at shaka.util.Mp4Parser.parse (https://shaka-player-demo.appspot.com/lib/util/mp4_parser.js:161:10)
>     at shaka.media.StreamingEngine.append_ (https://shaka-player-demo.appspot.com/lib/media/streaming_engine.js:1740:10)
>     at shaka.media.StreamingEngine.<anonymous> (https://shaka-player-demo.appspot.com/lib/media/streaming_engine.js:1509:17)"
>

**Comment by johndeu** [comment]
@joeyparrish - also requesting this one be prioritized as well - since Apple and MSFT need emsg v1 now as well.

**Comment by johndeu** [comment]
Thanks Prakah @duggaraju ! good to see this one closed out.
