### ISSUE TITLE
Video.videoWidth vs. AdaptationEvent.size.width

### ISSUE THREAD

**Issue by jozefchutka** [google/shaka-player#154]
It seems that video.videoWidth / video.videoHeight (recommended via doc) seems to provide different values then AdaptationEvent.size does in some cases. I can observe video values being updated not synchronously but a couple of seconds later after after AdaptationEvent is recieved. I.e. when 320x240 switches to 640x480, first and adaptation event is fired with new values and I can see the rendered image being improved but video.videoWidth / height values would still provide 320x240 for some 1-3 seconds.

**Comment by joeyparrish** [comment]
This is out of our control.  The videoHeight / videoWidth attributes are implemented by the browser, not by us.  I believe they show the resolution of the current frame being displayed.  The adaptation event shows what the ABR manager has decided to fetch, which may lead what is being displayed.
