### ISSUE TITLE
keepOriginalTimestamps will not adjust caption and ID3 timestamps in a future mux.js version

### ISSUE THREAD

**Issue by ldayananda** [google/shaka-player#1540]
👋  I'm currently working on https://github.com/videojs/mux.js/pull/213, which we plan to release as a new major version once merged. 

As I understand it, Shaka uses mux.js to transmux TS to mp4 on platforms without native HLS support, and uses the cea-608 captions parsed out from the segments as well? The PR I linked will no longer adjust caption timings when the `keepOriginalTimestamps` is set, as the [timing adjustment](https://github.com/videojs/mux.js/blob/master/lib/mp4/transmuxer.js#L848) may not actually be accurate when using the original timestamps. 

I plan to post in this issue when the major version of mux.js is released, so the dependency version can be locked down if necessary.

**Comment by ismena** [comment]
Thanks a lot for letting us know! Yes, we are using mux.js.

@michellezhuogg could you please take a look, see what the impact is going to be for us?

@joeyparrish FYI

**Comment by joeyparrish** [comment]
I'm sorry, I don't understand why the `keepOriginalTimestamps` option will no longer work.  Is the option being removed?  How can we keep the behavior we have now after your change?

**Comment by joeyparrish** [comment]
Oh, never mind.  I think I understand now that I've read https://github.com/videojs/mux.js/pull/213.  Tell me if I have this right:

1. The `keepOriginalTimestamps` option will still be there.
2. The behavior for video & audio will not change.
3. The behavior change is for captions, which will now have their original timestamps as well.  This was not the case before the change.

Is that correct?

**Comment by ldayananda** [comment]
Yes, correct for all three. If Shaka were to update to include the upcoming mux.js change, you would need to apply a similar adjustment to caption start/end times as is currently applied to video and audio.

**Comment by joeyparrish** [comment]
Gotcha.  Thanks!  We'll keep an eye on that as we work on upgrading.

I'll go ahead and close the issue.
