### ISSUE TITLE
Tests error with incomprehensible Babel errors in some situations

### ISSUE THREAD

**Issue by theodab** [google/shaka-player#1546]
There are some situations where, if a test is erroring, the actual error will be swallowed up and replaced by an unreadable Babel error.
Specifically, it seems to happen if you compare something to a `shaka.util.Error` object after an `await`. It doesn't seem to happen for generic objects; like, `{'foo': 'bar'}` can be compared just fine. I also tried to make a `shaka.Player` and compare that, and it also worked fine.

Here's a minimal reproduction. Put this into some test, and run it. It won't give the error you expect:
```
it('will error in an unreadable way', async() => {
  await Promise.resolve();
  expect('foobar').toEqual(new shaka.util.Error());
});
```

**Comment by TheModMaker** [comment]
I believe this was fixed by 615ce93178c7cf5c0fd609ffe86536adc7a554d6.
