### ISSUE TITLE
Emsg not referenced in MPD should be ignored.

### ISSUE THREAD

**Issue by damienlevin** [google/shaka-player#1548]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:
Yes
**What version of Shaka Player are you using?**:
2.4.3
**Can you reproduce the issue with our latest release version?**:
Yes
**Can you reproduce the issue with the latest code from `master`?**:
Yes
**Are you using the demo app or your own custom app?**:
Yes
**If custom app, can you reproduce the issue using our demo app?**:
Yes
**What browser and OS are you using?**:
Chrome/Linux
**What are the manifest and license server URIs?**:
N/A
**What did you do?**
Played a stream where the emsg scheme_id_uri referenced in the MPD isn't matching the one in the media files.
**What did you expect to happen?**
Events should be ignored as per specification. 

> 5.10.3.3.1
Event message boxes with scheme identifiers that are not defined in the MPD should not be present. If a DASH client detects an event message box with a scheme that is not defined in MPD, the client is expected to ignore it.

**What actually happened?**
All events were provided to the callback.
Tested URL:
https://storage.googleapis.com/dlevin/dash_id3/manifest_id3_v0_scheme_bug.mpd

**Comment by ismena** [comment]
Summoning the dash expert.

@TheModMaker could you please comment.

**Comment by TheModMaker** [comment]
Yeah, that looks like a bug.  Since we are already full for the next two releases and this seems lower priority, I'll put this on the backlog.  But feel free to send a PR if you (or anyone) wants.
