### ISSUE TITLE
Player hangs when progress button dragged to end of video...

### ISSUE THREAD

**Issue by sanbornhnewyyz** [google/shaka-player#155]
1. Start playing a video
2. Right click on the player and set to 'loop'
3. Play video until it finishes and restarts 
4. While it is playing the second time, drag the progress button to the very end of the video
5. Playback hangs - With verbose logging on, the statement 'A new segment is not needed or is not available' is repeatedly logged.

This is reproducible using at least the following two pieces of content:

'Oops' - assets/oops_cenc-20121114-signedlicenseurl-manifest.mpd

'Big Buck Bunny' - http://sit-mp5content.quickplay.com/integration/u/qpmezzdisneycommxlbbbclear1feature/master.ism/master.mpd

**Comment by tdrews** [comment]
Confirmed. Thanks for the report. We'll take a look!
