### ISSUE TITLE
Fragment duration vs Segment duration

### ISSUE THREAD

**Issue by ctoshni** [google/shaka-player#1550]
Hi, i'm using latest Shaka version ;
I have two questions:

What is the difference between fragment-duration and segment-duration?
Why it is recommended to use both?

Thanks in advance.

**Comment by TheModMaker** [comment]
This is best asked on the [Shaka Packager](https://github.com/google/shaka-packager) page as it more relates to them.  +@kqyang 

The segment duration refers to the duration of full segments, which represents the portions of the stream that the player downloads at a time.  For example, for 10 second segments, the player will download 10 seconds at a time.  For certain profiles (e.g. Live) segments are stored in separate files, but for others, the segments are all stored in a single file and the player makes range requests to get the part of the file that represents that segment.

Changing the segment duration affects how much the player will download at once.  Smaller segments can reduce latency by allowing the player to download faster and closer to the live edge; but small segments have some size overhead and can increase network usage.  Common settings are 10 seconds for VOD and 2 seconds for Live.

I'm not sure about fragment duration and I think it may be a term used by the Shaka Packager specifically.  I believe it means creating sub-segments.  For example, in MP4, each segment will be composed of multiple `moof` boxes of the given length.  Smaller values might make seeking easier and some players support subsegment fetching; but I don't think changing the fragment duration will change Shaka Player that much.

**Comment by kqyang** [comment]
> I believe it means creating sub-segments. For example, in MP4, each segment will be composed of multiple moof boxes of the given length. Smaller values might make seeking easier and some players support subsegment fetching

Correct. More precisely, fragment duration is the duration of the movie fragment (moof) in MP4. There could be more than one fragments in a segment, which some players can potentially take advantage of. It is also needed in HLS if you want to have more granularity in iframe only playlists as iframe only playlists can only index up to one iframe in a movie fragment (moof).

It will also be useful for CMAF low latency chunk support. AdaptationSet switching still happens in segment boundary, but with multiple chunks in a segment, content server can deliver the chunks sooner instead of waiting for the full segment to be available thus reduces the latency. We will provide guidelines on how to do this in coming quarters in Shaka Packager documentation.

**Comment by ctoshni** [comment]
So if fragment_duration represents moof then what happens if --segment_duration and --fragment_duration is set to the same value? 

      1. Does this mean only 1 fragment per segment?
      2. What happens to mdat box in above case?

Also what happens f I provide only segment_duration and not fragment_duration? Will it behave similarly as above i.e 1 fragment per segment?

**Comment by kqyang** [comment]
>   1. Does this mean only 1 fragment per segment?

Yes.

>  2. What happens to mdat box in above case?

There is always one moof and one mdat in a movie fragment.

> what happens f I provide only segment_duration and not fragment_duration? 

There will be one fragment per segment if fragment_duration is set to 0. The default fragment_duration may not be zero. You may want to set it to 0 to be safe.

**Comment by ctoshni** [comment]
> There will be one fragment per segment if fragment_duration is set to 0. The default fragment_duration may not be zero. You may want to set it to 0 to be safe.

So what is the recommend option when I want 1 fragment per segment?

a. Set both segment_duration and fragment_duration to same value eg : --segment_duration=10 --fragment_duration=10
b. Set fragment_duration=0 i.e  --segment_duration=10 --fragment_duration=0

**Comment by kqyang** [comment]
There isn't really a difference between the two - you can use any one as you wish.

If you are using Shaka Packager v2.2 (released last week), you can set --segment_duration only as the default --fragment_duration has been changed to 0.

**Comment by ctoshni** [comment]
Thanks @kqyang ! This is really helpful.
Closing the issue as all the queries have been addressed.
