### ISSUE TITLE
Question about Audio Media Element

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#1555]
I just tested initialize the player with audio element. It works as expect with DASH radio channels. 

I reviewed the documentation and only i could found information about video element (eg: https://shaka-player-demo.appspot.com/docs/api/shaka.Player.html ). Are there issues knowloged? 

Are there plans to support the same as the video element?

There will be support to https://github.com/google/shaka-player/issues/816 with the audio element?

**Comment by TheModMaker** [comment]
The Player constructor accepts an `HTMLMediaElement`, which is both a `<video>` and an `<audio>`.  I don't think there are any problems with using an `<audio>` element instead.  It should be handled exactly the same.

**Comment by avelad** [comment]
Is possible update the documentation to reflect it? I see that the player constructor has a video param which is HTMLMediaElement, is it possible change the video param to mediaElement param?

**Comment by joeyparrish** [comment]
Sure, we can update the docs and possibly rename parameters without breaking compatibility.

**Comment by joeyparrish** [comment]
Docs change cherry-picked to v2.4.5.
