### ISSUE TITLE
Question about offline support in MS Edge

### ISSUE THREAD

**Issue by TheJohnBowers** [google/shaka-player#1556]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:
Yes
**What version of Shaka Player are you using?**:
2.4.3
**Can you reproduce the issue with our latest release version?**:
Yes
**Can you reproduce the issue with the latest code from `master`?**:
Haven't checked
**Are you using the demo app or your own custom app?**:
Demo App
**If custom app, can you reproduce the issue using our demo app?**:
NA
**What browser and OS are you using?**:
MS Edge on Windows
**What are the manifest and license server URIs?**:
I can provide if useful, but since this is just a question I am not going worry about it for now
**What did you do?**
Click "Store" on a asset
**What did you expect to happen?**
Store for offline playback
**What actually happened?**
Error Message "This browser does not support persistent licenses"

So this seems to suggest that there is an issue with edge?  I am hoping to understand the limitation here as well as is there any way around this, anything that could be changed in the demo app / shaka codebase to somehow support offline storage on edge?    I.E.  Is there some work here that could be done to fix this if I was so inclined?

**Comment by BucherTomas** [comment]
Support for persistent licenses on Edge is tied to resolving this first https://github.com/google/shaka-player/issues/1495.
Essentially, it is now up to Microsoft to provide proper documentation about how to utilize this new key system.

**Comment by joeyparrish** [comment]
@TheJohnBowers, @BucherTomas is right.  The `com.microsoft.playready` key system does not support persistent licenses.  There is a lack of documentation from Microsoft on their new alternative, which is blocking our adoption of it.

**Comment by TheJohnBowers** [comment]
Yes, thank you very much for the info. I will see if anyone in our org has some contacts at MS. Maybe we can emphasize how useful this documentation would be fore us. It will make testing persistent PlayReady licenses much easier for us.
