### ISSUE TITLE
License restrictions not obeyed, when preroll server side ad present in manifest

### ISSUE THREAD

**Issue by sandeep-mirpuri** [google/shaka-player#1557]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:
Yes

**What version of Shaka Player are you using?**:
2.4.3

**Can you reproduce the issue with our latest release version?**:
Yes

**Can you reproduce the issue with the latest code from `master`?**:
Yes

**Are you using the demo app or your own custom app?**:
Tried on Both

**If custom app, can you reproduce the issue using our demo app?**:
Yes

**What browser and OS are you using?**:
Mac OS, Chrome 68

**What are the manifest and license server URIs?**:
Unable to share

**What did you do?**
Played (on an external VGA screen) a manifest with a server side ad inserted as the first period. The content after the ad is DRM protected and the license enforces HDCP restrictions.

**What did you expect to happen?**
Since the ad is not protected it plays the highest possible bandwidth, then when the variants for the actual content were set it should've reevaluated the variants based on the license restrictions. Instead it adds all of them and freezes since it is neither able to play nor throw an output-restricted error

**What actually happened?**
It appears that Shaka only evaluates the restrictions on variants when playback begins, so if there are no restrictions to begin with and the later periods are restricted, it doesnt respect those restrictions. Since server side ads will often be unprotected, this means that the player will use no restrictions. I noticed that this function processKeyStatusChanges_() in drm_engine.js  gets called only once when initialising and not again when the license is obtained.

**Please :)**
If this is an easy fix can it please be cherry-picked to the current release. It is a blocker for me. If not I would really appreciate any advise on potential work arounds

**Comment by michellezhuogg** [comment]
Hi, thanks for reporting this issue, and we appreciate if you can send a test file to reproduce it. You can send it to us privately through email: shaka-player-eng@google.com. Thank you!

**Comment by joeyparrish** [comment]
Correction: shaka-player-issues@google.com is the email alias for sending us content URLs privately.

**Comment by sandeep-mirpuri** [comment]
@joeyparrish @michellezhuogg I am working on getting the permissions to share the required URLs to test this with you. Until then I can describe the scenario more accurately based on my investigation.

1) Player loads the manifest
2) Period 1 doesnt require a license so it loads it and marks all variants as "allowedByKeySystem: true"
3) Player encounters the need for a license in Period 2
4) Player makes license request and successfully receives key
5) DRM Engine kicks in and experiences a "keystatuseschange" event and fires onKeyStatusesChange_ callback
6) This schedules the keyStatusTimer_ which calls processKeyStatusChanges_ which calls playerInterface_.onKeyStatus
7) From what I can see, the onKeyStatus_ callback is the one that reevaluates the variants with the new restrictions imposed by the license
8) However, when the license is acquired and these callbacks are fired, the player is still in period 1 and it runs the filters on the variants for period 1, which are clear and have no keyIds associated, so they are all allowed again.
9) But the variants for period 2 which need to be filtered never are because the keyStatusChange event is not fired again and the filters are not run on the variants of period 2

I don't know if this helps any more, but I thought better than nothing until I can get permissions to share the urls with you guys

**Comment by joeyparrish** [comment]
Restrictions (as in the `Restrictions` object from the config) are applied to every new period when it is introduced in a manifest update.  DRM restrictions (as reported by key status) are applied every time we get a key status event, but we require key IDs in the manifest to match this information up.

Chrome definitely reports key status changes, but I can't say whether or not your content contains key ID info in the manifest.  If not, this would explain your problem.

I can look into it more when you are able to share manifest and license URIs with us, but in the mean time, you can check for the `default_KID` attributes in your DASH manifest.  If they are missing, then that's the root of your problem.
