### ISSUE TITLE
HLS: Support variable substitution

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#1561]
Relevant info:
https://tools.ietf.org/html/draft-pantos-hls-rfc8216bis-00#section-4.3
https://tools.ietf.org/html/draft-pantos-hls-rfc8216bis-00#section-4.4.5.3
https://devstreaming-cdn.apple.com/videos/wwdc/2017/504op4c3001w2f222/504/504_advances_in_http_live_streaming.pdf?dl=1

Sample:

> #EXTM3U
> #EXT-X-TARGETDURATION:6
> #EXT-X-DEFINE:NAME="path",VALUE="/media/encoded/asset127-a/1MB/"
> #EXT-X-DEFINE:IMPORT="auth"
> #EXT-X-MEDIA-SEQUENCE:44
> #EXTINF 6,
> {$path}segment44.mp4{$auth}

Is possible add support to it?

**Comment by joeyparrish** [comment]
Sounds reasonable.  I'll add it to the backlog for now.  v2.5 is too full already.
