### ISSUE TITLE
PlayReady content is not playable 

### ISSUE THREAD

**Issue by ronenneumark** [google/shaka-player#1568]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:
yes
**What version of Shaka Player are you using?**:
2.4.4
**Can you reproduce the issue with our latest release version?**:
yes
**Can you reproduce the issue with the latest code from `master`?**:
yes
**Are you using the demo app or your own custom app?**:
no
**If custom app, can you reproduce the issue using our demo app?**:
no
**What browser and OS are you using?**:
IE 11, win 8.1 pro 
**What are the manifest and license server URIs?**:

https://imagine-pkg-test.edm-cloud.tv/mpdl/1/Cars_TV_D/manifest.mpd

https://udrmv3-eus1.ott.kaltura.com/cenc/playready/license?custom_data=eyJjYV9zeXN0ZW0iOiJodHRwczovL3Jlc3QtZXVzMS5vdHQua2FsdHVyYS5jb20vcmVzdGZ1bF92NF84L2FwaV92My9zZXJ2aWNlL2Fzc2V0RmlsZS9hY3Rpb24vZ2V0Q29udGV4dD9rcz1kako4TkRneGZNVFhjc0JpaWtEMG9JaTNySS1oX0ZralB6UFpSM3pBcmJILXRSTEE3d3R5cEo4RnFCYmNvNnNET2FETDhrNnExUzFOYzl5enRTNjVkb2hlNHJlWjhZajZzYkRvMXBpMkRTY1g1ZldQXy1ZVTdoRjNERm1nS2tuelNSYlRIdU00NWREME1VVWxHczBreGtWdXVWcl90TUE9JmNvbnRleHRUeXBlPW5vbmUmaWQ9MzAzMTYzNiIsImFjY291bnRfaWQiOjQ4MSwiY29udGVudF9pZCI6IkwwNzEzMDJ2IiwiZmlsZXMiOiIiLCJ1c2VyX3Rva2VuIjoiZGpKOE5EZ3hmTVRYY3NCaWlrRDBvSWkzckktaF9Ga2pQelBaUjN6QXJiSC10UkxBN3d0eXBKOEZxQmJjbzZzRE9hREw4azZxMVMxTmM5eXp0UzY1ZG9oZTRyZVo4WWo2c2JEbzFwaTJEU2NYNWZXUF8tWVU3aEYzREZtZ0trbnpTUmJUSHVNNDVkRDBNVVVsR3Mwa3hrVnV1VnJfdE1BPSIsInVkaWQiOiI3ODciLCJhZGRpdGlvbmFsX2Nhc19zeXN0ZW0iOjQ4MX0%3d&signature=o2jdcvnQ0t7dMn2BThQOtXppJdk%3d

**What did you do?**
play
**What did you expect to happen?**
play
**What actually happened?**
video is not playing Shaka Error MEDIA.VIDEO_ERROR (3,c00d36bb,)

**Comment by joeyparrish** [comment]
I get different error details on my Windows 10 machine (5,8004b8d2), but it fails for me, too.  I tried both IE & Edge and got the same failure.

I can't find any publicly documented meaning for either c00d36bb or 8004b8d2, but both are Microsoft error codes.  From what I can tell, they appear to be decoder-related, but that's just my best guess.

Other PlayReady content plays fine, such as the "Axinom Multi-DRM" or "Unified Streaming Tears of Steel (PlayReady)" assets in the demo app's asset list.

To fix this, you would probably have to change something about the way the content is encoded, but I don't know what.  I would advise you to file an issue with Microsoft asking for support: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/
