### ISSUE TITLE
Multiple createMediaSource calls when initiating the playback

### ISSUE THREAD

**Issue by SemihGk** [google/shaka-player#1570]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:
Yes
**What version of Shaka Player are you using?**:
master
**Can you reproduce the issue with our latest release version?**:
yes
**Can you reproduce the issue with the latest code from `master`?**:
yes
**Are you using the demo app or your own custom app?**:
demo app
**If custom app, can you reproduce the issue using our demo app?**:

**What browser and OS are you using?**:
Chrome MacOS
**What are the manifest and license server URIs?**:

It does not matter. Use any sample content.
**What did you do?**
Initiated playback and call load method of shaka player.
**What did you expect to happen?**
It should create MediaSource only once, not twice in order.
**What actually happened?**
It created MediaSource and it removed it. Then, it created again.

When we initialize Shaka Player, [attach](https://github.com/google/shaka-player/blob/master/lib/player.js#L197) method calls [createMediaSource](https://github.com/google/shaka-player/blob/master/lib/player.js#L197) method. Then, when we call .load() method, it also calls [unload](https://github.com/google/shaka-player/blob/master/lib/player.js#L736) method. However, unload method calls [createMediaSource](https://github.com/google/shaka-player/blob/master/lib/player.js#L1495) as well. Eventually, this creates MediaSource twice even though previous one is destroyed.

Please let me know if the issue is still unclear, but solution should be very straightforward. This [if](https://github.com/google/shaka-player/blob/master/lib/player.js#L1475) seems very suspicious .

Thank you,
Semih.

**Comment by vaage** [comment]
@SemihGk Good new, I am already looking through the load chain code for work with #816. If this issue is not causing any major issues for you or your users, would you be willing to wait until I make more progress on #816 where then we can re-evaulate whether this is still an issue after more of that work is complete?

**Comment by SemihGk** [comment]
@vaage , I appreciate for your concern. This is definitely not an issue as this is not causing any problem on most of the problems (if we do not count performance case) except LG TV. I made a fix on my fork. So, there is no rush at all. This is just a 'good to have' enhancement. Thank you.

**Comment by joeyparrish** [comment]
I'm relabeling this as a bug, since I can say with certainty that I didn't intend this part of the system to behave in this way.  But since you have a workaround and this may be solved during #816, I'm going to leave it in the backlog for now.  Thanks!
