### ISSUE TITLE
Add additional audio codes which is not supported by browser?

### ISSUE THREAD

**Issue by ShaoWeiguo** [google/shaka-player#1571]
Is it possible to add additional audio codec which is not supported by browser? For example, chrome doesn't support Dolby Digital Plus.  How can Shake Player support Dolby Digital Plus in chrome?

**Comment by vaage** [comment]
Shaka Player is limited to what the platform (the browser) supports. This means if Chrome/Firefox/Edge do not support a feature, we cannot play that content on that browser. The one exception is if it is something at the manifest-level (which we parse). If Chrome does not support it, there is not much we can do.
