### ISSUE TITLE
FilterNewVariants method is never called when there is a manifest update.

### ISSUE THREAD

**Issue by SemihGk** [google/shaka-player#1574]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:
yes
**What version of Shaka Player are you using?**:
master
**Can you reproduce the issue with our latest release version?**:
yes
**Can you reproduce the issue with the latest code from `master`?**:
yes
**Are you using the demo app or your own custom app?**:
demo app
**If custom app, can you reproduce the issue using our demo app?**:
yes
**What browser and OS are you using?**:
Chrome MacOS
**What are the manifest and license server URIs?**:

It is happening on all live stream. I tested Big Bug Bunny (Live) asset on the demo app.
**What did you do?**
Just started a live stream.
**What did you expect to happen?**
[filterNewPeriods](https://github.com/google/shaka-player/blob/master/lib/dash/dash_parser.js#L679) should be called when there is a manifest update. 
**What actually happened?**
This method is never called.

This might be a potential question as I am not certain, but I would like to learn whether this is a bug or not. Shaka player calls [filterAllPeriods](https://github.com/google/shaka-player/blob/master/lib/dash/dash_parser.js#L703) method when initiating a live stream. As for same logic, manifest updates should also be filtered out [here](https://github.com/google/shaka-player/blob/master/lib/dash/dash_parser.js#L675) as you can read the comments. However, that block never gets called due to [this check](https://github.com/google/shaka-player/blob/master/lib/dash/dash_parser.js#L672). Let's say, initiated manifest period id = 0. When there is a new manifest update, next manifest period id may also be 0 because period id does not necessarily have to be unique. That's why that if block would never be called.

My question is that does shaka player assume periods which have the same id would always have the same type of variants(codec profile etc)? For instance, shaka player should only filter out variants when a next manifest has an extra period or period id is changed instead of calling for all new period variants?

**Comment by TheModMaker** [comment]
That is working as intended, DASH requires that all Periods have unique IDs.  If a manifest update has a Period with the same ID, it needs to represent the same content and have the same streams in it.  You can't reuse Period IDs for new Periods and can't change streams during playback.  New Periods need a new ID, but can have different streams than the previous; but an existing Period can't change streams.

Period IDs are used to associate the previous manifest update with this one.  It allows us to determine which of the Periods from the previous manifest update correspond with the Period in this update.  So the same Period needs to have the same ID and new Periods need to use different IDs.

Note that if a Period doesn't have an `id` attribute, we will generate an ID based on the `start` time of the Period.

**Comment by SemihGk** [comment]
Thank you so much for your response, @TheModMaker  The reason I asked is that there is a discussion going on #1567 . It looks like shaka player should support codec profile change during live playback. So, I was not quite sure that must period Id be changed if codec profile changes. As for your comments, it has to be. It looks like our stream also changes this periodId all the time when there is a codec profile change. Thanks a lot. We can close this ticket so.
