### ISSUE TITLE
Expose live edge?

### ISSUE THREAD

**Issue by chrisfillmore** [google/shaka-player#1575]
Could `PresentationTimeline#getLiveEdge_()` be exposed through `Player`?

I'd like to track my application's distance from the live edge, for stats and diagnostic purposes. I realize I could do the calculation myself by inspecting the manifest, but this duplicates code which is already in Shaka. I'd prefer to just get the value that Shaka calculated.

If this is ok, I can make a PR. Thanks.

**Comment by vaage** [comment]
As for surfacing that information, I don't see any problems (@joeyparrish will have final say).

I am concerned with the numerous functions we have on the top-level player api so adding `getLiveEdge` to it worries me. 

Right now we have a lot of functions that extract read-only values from the timeline. If we had a read-only interface for the timeline, we could just return a readonly version of it and then we could drop multiple functions from the player interfaces with just `getTimeline`.

@joeyparrish What do you think of that idea?
@chrisfillmore What do you think of that idea?

**Comment by TheModMaker** [comment]
Since the timeline is available using `getManifest()`, how about just making `getLiveEdge` public and exporting it?

**Comment by chrisfillmore** [comment]
Sounds good to me @TheModMaker. No new method required this way.

**Comment by chrisfillmore** [comment]
There is the question of what to do with this assertion:

```
shaka.media.PresentationTimeline.prototype.getLiveEdge = function() {
  goog.asserts.assert(this.presentationStartTime_ != null,
                      'Cannot compute timeline live edge without start time');
```
Users who call this for VOD will get a failed assertion. Could we not say, for VOD, that `presentationStartTime` is zero? The spec says, for `MPD@availabilityStartTime`:

> For `@type="static"` if present, it specifies the Segment availability start time for all Segments referred to in this MPD. If not present, all Segments described in the MPD shall become available at the time the MPD becomes available.

I think this can be interpreted to mean that AST is, by default, zero. Agree/disagree?

**Comment by joeyparrish** [comment]
Why not use `player.seekRange().end`?

**Comment by chrisfillmore** [comment]
Oh yeah, that's perfect! Thanks Joey
