### ISSUE TITLE
Error 4002 DASH_NO_SEGMENT_INFO trying to play DASH content

### ISSUE THREAD

**Issue by albertotirado** [google/shaka-player#1579]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:
Yes I have

**What version of Shaka Player are you using?**:
The actual demo page https://shaka-player-demo.appspot.com/demo
**Can you reproduce the issue with our latest release version?**:
Last Release https://shaka-player-demo.appspot.com/demo

**Can you reproduce the issue with the latest code from `master`?**:
https://shaka-player-demo.appspot.com/demo

**Are you using the demo app or your own custom app?**:
Demo app https://shaka-player-demo.appspot.com/demo

**If custom app, can you reproduce the issue using our demo app?**:
N/A

**What browser and OS are you using?**:
Microsoft Edge

**What are the manifest and license server URIs?**:
https://b26807-p1-h97-afpq2p4v.1.cdnprepro.telefonica.com/_26807/Dash2Smooth/set064/MEZZ_THEHELP_30Mbps_1080i30.mpd
Playready Server: https://test.playready.microsoft.com/service/rightsmanager.asmx

**What did you do?**
Tryng to play in demo app https://shaka-player-demo.appspot.com/demo/#asset=https://b26807-p1-h97-afpq2p4v.1.cdnprepro.telefonica.com/_26807/Dash2Smooth/set064/MEZZ_THEHELP_30Mbps_1080i30.mpd;lang=en;build=compiled

**What did you expect to happen?**
Play content video and audio without problem

**What actually happened?**
DASH_NO_SEGMENT_INFO
4002 
number 
The DASH Manifest contained a Representation with insufficient segment information.

**Comment by TheModMaker** [comment]
I am able to play that asset fine.  What Shaka Player version are you using (the version number is at the top of the page)?  Does it work if you clear your browser cache?

https://shaka-player-demo.appspot.com/demo/#asset=https://b26807-p1-h97-afpq2p4v.1.cdnprepro.telefonica.com/_26807/Dash2Smooth/set064/MEZZ_THEHELP_30Mbps_1080i30.mpd;license=https://test.playready.microsoft.com/service/rightsmanager.asmx;lang=en;build=compiled;play
