### ISSUE TITLE
Subtitle remain stucked after loading a new source

### ISSUE THREAD

**Issue by stefanovualto** [google/shaka-player#1583]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:
Yes
**What version of Shaka Player are you using?**:
2.4.4
**Can you reproduce the issue with our latest release version?**:
The latest stable yes
**Can you reproduce the issue with the latest code from `master`?**:
I didn't tested it
**Are you using the demo app or your own custom app?**:
demo
**If custom app, can you reproduce the issue using our demo app?**:

**What browser and OS are you using?**:
Firefox 62.0
**What are the manifest and license server URIs?**:
//storage.googleapis.com/shaka-demo-assets/sintel-mp4-only/dash.mpd

**What did you do?**
- go to: https://shaka-player-demo.appspot.com/demo/#asset=//storage.googleapis.com/shaka-demo-assets/sintel-mp4-only/dash.mpd;lang=en-US;play;build=compiled
- enable subtitles
- seek to 7 minutes 34 seconds
- pause
- press load button

**What did you expect to happen?**
I expect the subtitles to be removed when I load a new source (even if it is the same)
**What actually happened?**
the subtitles shown on the previous video remains for too much time.

**Comment by chrisfillmore** [comment]
Is this what you mean?
<img width="780" alt="screen shot 2018-09-13 at 10 34 34 am" src="https://user-images.githubusercontent.com/7190265/45495155-ac38e580-b740-11e8-95d2-c853f4e23535.png">

**Comment by chrisfillmore** [comment]
On macOS, I am also able to reproduce in Firefox 62. Doesn't happen on Chrome 69.

**Comment by TheModMaker** [comment]
This looks like a Firefox bug.  https://bugzilla.mozilla.org/show_bug.cgi?id=1491045

**Comment by joeyparrish** [comment]
Closing this stale external (non-Shaka) issue. If you disagree, please reply with @shaka-bot reopen, and it will be automatically reopened.
