### ISSUE TITLE
TTML parser doesn't support namespaces

### ISSUE THREAD

**Issue by TheModMaker** [google/shaka-player#1585]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:
Yes
**What version of Shaka Player are you using?**:
v2.4.4
**Can you reproduce the issue with our latest release version?**:
Yes
**Can you reproduce the issue with the latest code from `master`?**:
Yes
**Are you using the demo app or your own custom app?**:
Demo app
**If custom app, can you reproduce the issue using our demo app?**:

**What browser and OS are you using?**:
Any
**What are the manifest and license server URIs?**:
https://d1chyo78gdexn4.cloudfront.net/vualto-demo/elephants-dream/elephants-dream_nodrm.ism/manifest.mpd

**What did you do?**
Play TTML asset that uses XML namespaces with different prefixes than normal.
**What did you expect to happen?**
Play text fine.
**What actually happened?**
Cannot find attributes since the TTML parser looks up by simple name instead of namespace-qualified.

Found while investigating #1584.

**Comment by joeyparrish** [comment]
Fix cherry-picked to v2.4.5.
