### ISSUE TITLE
Duration showing -14:-8

### ISSUE THREAD

**Issue by samaduttan** [google/shaka-player#1586]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:
yes
**What version of Shaka Player are you using?**:
33792ca-release

**Can you reproduce the issue with our latest release version?**:
yes

**Can you reproduce the issue with the latest code from `master`?**:
yes

**Are you using the demo app or your own custom app?**:
custom app

**If custom app, can you reproduce the issue using our demo app?**:
yes
**What browser and OS are you using?**:
chrome 

**What are the manifest and license server URIs?**:

<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011 DASH-MPD.xsd" >
  <Period id="0" start="PT0S">
    <AdaptationSet id="0" contentType="audio" segmentAlignment="true">
      <Representation id="0" bandwidth="192661" codecs="mp4a.40.2" mimeType="audio/mp4" audioSamplingRate="48000">
        <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
        <SegmentTemplate timescale="90000" initialization="audio_first.mp4" media="audio_first_$Number$.m4s" startNumber="1212">
          <SegmentTimeline>
            <S t="129508350" d="48000"/>
            <S t="129556350" d="44160" r="2"/>
            <S t="129688830" d="48000"/>
            <S t="129736830" d="44160" r="3"/>
            <S t="129913470" d="48000"/>
            <S t="129961470" d="44160" r="3"/>
            <S t="130138110" d="48000"/>
            <S t="130186110" d="44160" r="2"/>
            <S t="130318590" d="48000"/>
            <S t="130366590" d="44160" r="3"/>
            <S t="130543230" d="48000"/>
            <S t="130591230" d="44160" r="2"/>
            <S t="130723710" d="48000"/>
            <S t="130771710" d="44160" r="3"/>
            <S t="130948350" d="48000"/>
            <S t="130996350" d="44160" r="2"/>
            <S t="131128830" d="48000"/>
            <S t="131176830" d="44160" r="3"/>
            <S t="131353470" d="48000"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
    </AdaptationSet>
    <AdaptationSet id="1" contentType="video" width="720" height="480" frameRate="90000/90" segmentAlignment="true" par="16:9">
      <Representation id="1" bandwidth="3004316" codecs="avc1.4d401e" mimeType="video/mp4" sar="32:27">
        <SegmentTemplate timescale="90000" initialization="video_first.mp4" media="video_first_$Number$.m4s" startNumber="1214">
          <SegmentTimeline>
            <S t="129608844" d="36036"/>
            <S t="129644880" d="72072"/>
            <S t="129716952" d="36036" r="2"/>
            <S t="129825060" d="72072"/>
            <S t="129897132" d="36036" r="2"/>
            <S t="130005240" d="72072"/>
            <S t="130077312" d="36036" r="2"/>
            <S t="130185420" d="72072"/>
            <S t="130257492" d="36036" r="2"/>
            <S t="130365600" d="72072"/>
            <S t="130437672" d="36036" r="2"/>
            <S t="130545780" d="72072"/>
            <S t="130617852" d="36036" r="2"/>
            <S t="130725960" d="72072"/>
            <S t="130798032" d="36036" r="2"/>
            <S t="130906140" d="72072"/>
            <S t="130978212" d="36036" r="2"/>
            <S t="131086320" d="72072"/>
            <S t="131158392" d="36036" r="2"/>
            <S t="131266500" d="72072"/>
            <S t="131338572" d="36036" r="2"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
    </AdaptationSet>
  </Period>
  <UTCTiming schemeIdUri="urn:mpeg:dash:utc:direct:2014" value="2018-09-14T20:56:49Z"/>
</MPD>

**What did you do?**
dash live streaming using shaka player

**What did you expect to happen?**
expected to see the current time / live Edge time stamp

**What actually happened?**
its showing some random number

![capture-1](https://user-images.githubusercontent.com/38025723/45575561-91966780-b839-11e8-9139-e63ac9787e5e.PNG)

**Comment by TheModMaker** [comment]
First, you didn't post a manifest URL, so it will be hard to reproduce.  If you go to the hosted demo and play a live stream it works fine with the demo assets.  Second, the version you posted isn't a Shaka Player version, it actually appears to be a Shaka Packager version.  Please post the Shaka **Player** version.  Lastly, the image you posted doesn't appear to be the demo app's UI.  Displaying the correct time is the job of the UI, which is currently the job of the app.  Our demo app has custom controls to handle this better, but your custom app will need to implement it.

**Comment by joeyparrish** [comment]
If you are using the browser's native controls (`video.controls = true` or `<video controls>`), then this is expected.  The browser's native controls do not understand live streams.  To get a reasonable seek bar and duration for live streams, you need to use `player.isLive()` and `player.seekRange()` to display your own controls.

For an example of that, you can look at the controls in our demo app:
 - https://github.com/google/shaka-player/blob/89e1545510be5e4679ba02f939c969642e3b3ef5/demo/index.html#L130
 - https://github.com/google/shaka-player/blob/89e1545510be5e4679ba02f939c969642e3b3ef5/demo/common/controls.js#L20
 - https://github.com/google/shaka-player/blob/89e1545510be5e4679ba02f939c969642e3b3ef5/demo/common/controls.css#L17

We are working on building a UI library that will encapsulate these custom controls for you and make it easier to get consistent, usable controls on all platforms.

**Comment by samaduttan** [comment]
Thanks joey, for the quick catch up and response of the issue.I would like to know when the UI library release would be, is it some time around near by.

**Comment by joeyparrish** [comment]
I am not sure of a release date yet.  We are going through release processes that depend on things we can't control.  But I expect that we will release it by the end of the year.
