### ISSUE TITLE
Configure maxAttempts

### ISSUE THREAD

**Issue by grantg182** [google/shaka-player#1587]
**What version of Shaka Player are you using?**:
2.4.1
**What did you do?**
Attempt to access maxAttempts from retryParameters.
**What did you expect to happen?**
Get the value of maxAttempts
**What actually happened?**
"Assertion failed: only methods on Player"

I am trying to add some custom error handling; a 'diagnostic mode'. Essentially, pass in a predefined parameter and the player enters a debug mode, where error stacks, stats and such-like are printed to the display. That works fine; however, I seem to have hit a stumbling block with getting at the maxAttempts defined in shakaPlayer.player_.configure().

For simplicities sake, I'm looking to do something along the lines of:-

```
     if (!shakaPlayer.player_.networkingEngine_.manifest.retryParameters.maxAttempts) {
console.log('do something');
}
```
But evidently, I am getting the "only methods on Player" error.  I can see I can get the default parameters from shaka.net.Backoff but how can I access those set in configure()? Went round and round in circles with this today and didn't gain any headway!

Thanks.

**Comment by joeyparrish** [comment]
If you want access to the values in the current configuration, try `Player.prototype.getConfiguration()`:

```js
player = new shaka.Player(videoElement);
// ...
const maxAttempts = player.getConfiguration().manifest.retryParameters.maxAttempts;
```

You may also be interested in the [config tutorial](https://shaka-player-demo.appspot.com/docs/api/tutorial-config.html), which introduces the basic config concepts and API.

Does this answer your question?

**Comment by grantg182** [comment]
Thanks @joeyparrish. That did the job; cheers.
