### ISSUE TITLE
Rename variables called 'async'

### ISSUE THREAD

**Issue by theodab** [google/shaka-player#1588]
In a number of places in the code, we make an array of variables called `async`. This was our coding convention for when we want an array of promises that correspond to asynchronous processes.
However, we've adopted ES6 since then, and `async` is now a reserved word with semantic meaning. Giving a variable that name is not a bug, technically, but it can be confusing.
We should go through the code, and rename all of those arrays.

**Comment by TheModMaker** [comment]
Once we do this we can use the [id-blacklist](https://eslint.org/docs/rules/id-blacklist) rule from eslint to ensure we don't do this in the future.  That rule also allows us to easily find where we are currently doing it.
