### ISSUE TITLE
Live DASH stream buffering with warning cannot find segment

### ISSUE THREAD

**Issue by plzhang** [google/shaka-player#1589]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:
Yes

**What version of Shaka Player are you using?**:
Shaka Player v2.4.4-uncompiled Demo player

**Can you reproduce the issue with our latest release version?**:
Yes

**Can you reproduce the issue with the latest code from `master`?**:

**Are you using the demo app or your own custom app?**:
Demo app

**If custom app, can you reproduce the issue using our demo app?**:

**What browser and OS are you using?**:
Chrome on Linux

**What are the manifest and license server URIs?**:

Sent.

**What did you do?**
Load the stream and check the console logs

**What did you expect to happen?**
smooth playback with no buffering and error in console.

**What actually happened?**
stream buffers periodically
Console logs two types of message:
1. Uncaught exception in event handler TypeError: Cannot read property 'language' of undefined
2. currentPeriod.startTime=... lookupTime=...

However even when it is not buffering new messages with these two type keeps showing up.

**Comment by theodab** [comment]
Running your asset, I seem to be getting a lot of mixed content errors at the very beginning, before the other errors. Looking at the manifest, the manifest itself is loaded through `https`, but the segments are all loaded through `http`. So it's a CORS issue.
I tried playing it with CORS disabled, and it seems to play fine.

**Comment by plzhang** [comment]
Sorry forgot to mention in **What did you do** part:
After loading the stream, also need to let chrome **load unsafe script** due to the mixed content this test stream has.

And the behavior described above happens after this.

**Comment by theodab** [comment]
I just tried loading Chrome with CORS disabled, and I was able to load your stream with no errors.

I can't find any documentation about the exact behavior of the 'load unsafe script' button, but I don't think it completely disables CORS.

**Comment by joeyparrish** [comment]
That's correct.  "Load unsafe scripts" will work around mixed content errors (http resources in http**s** context), but CORS is separate from that.  The server must declare to the browser through HTTP response headers that the origin (the page context) is permitted to load that resource.  You can read more on CORS at MDN: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by theodab** [comment]
The Mixed Content errors show up in the top of the developer console. They're not Shaka Player errors, so they are styled differently; specifically, they all get collapsed into a single line, with a number by it representing the number of mixed content errors. You can also go to the network tab of the developer console to see all of the downloads failing.

Did you also provide an (empty) user data directory to the arguments? I find that that's necessary for `--disable-web-security` to work, for whatever reason. If Chrome starts up with a message on the top that it's been loaded with an unsupported command-line argument, that means that `--disable-web-security` didn't work.

Sometimes it plays partially because, looking at your manifest, there are some periods that are loaded from `https`. Presumably when it's playing smoothly, that's when you happened to turn the stream on while it was on a period that could be downloaded.

**Comment by theodab** [comment]
Also, in addition to the CORS issue, I think some of the periods on that manifest are messed up somehow. It looks like periodically it can't choose a variant, so it only plays properly with jumpLargeGaps enabled (to skip over those periods).

**Comment by joeyparrish** [comment]
Correction: If you see the "unsupported command-line argument: disable-web-security" banner, it means disable-web-security **is** active.

**Comment by joeyparrish** [comment]
You may still need to disable the service worker with --disable-web-security.

**Comment by plzhang** [comment]
Yep I also set **--user-data-dir**.

And it is true there are two types of Periods(can be distinguished by id). But if **Load unsafe scripts** is set (shows up in the URL bar when loading mixed content). Both of them plays (and all segments 200 status code), just it might be buffering for around 10 seconds. if it is a cors issue I assume it won't play right?

Yep **Service Workder** is always  set with **bypass for network**

And **jump Large Gaps** is also applied, cannot be so certain if there is improvement but buffering and the two types of logs are still seen...

Can you also observe the shifted progress bar and two types of logs on your side, if just leave it playing for 10 to 20 minutes?

**Comment by theodab** [comment]
Sometimes, it looks like your stream puts out manifests that contain just an `MPD` tag with a `BaseURL` tag inside it. And no periods or anything. If that happens to be the most recent manifest when the player first loads the stream, the player can't play at all. When that manifest shows up mid-stream, it just causes big gaps; that seems to be what's causing the progress bar to jump back ~20 seconds from the live edge sometimes.

**Comment by plzhang** [comment]
Thanks for the good catch! I'll look into it.

**Comment by joeyparrish** [comment]
@plzhang, does this answer your questions?  Is there anything else you need?

**Comment by plzhang** [comment]
Yep, and nothing else we need for now. Thanks, @theodab , @joeyparrish.
After fixing the missing periods issue we noticed that there are a few other problems in the stream regarding the timeline. The fix might take sometime, I'll close the issue for now.
