### ISSUE TITLE
Refused to get unsafe header "Date"

### ISSUE THREAD

**Issue by JobaDiniz** [google/shaka-player#159]
I'm always getting this error:

```
Refused to get unsafe header "Date"
  h.pe @ shaka-player-1.4.0.min.js:49
```

Playback works just fine, but why I'm getting this all the time. Is this an *error* or *warning*? *- it shows as console error*

**Comment by joeyparrish** [comment]
Unfortunately, that's being emitted by Chrome directly.  It's harmless, but we can't silence it.  See this code in [shaka.util.AjaxRequest.prototype.onReadyStateChange_](https://github.com/google/shaka-player/blob/master/lib/util/ajax_request.js):

```
  // This may not be available, depending on server configuration and CORS.
  // For clock synchronization to work cross-origin, the server explicitly
  // has to allow the client access to the "Date" header using the response
  // header "Access-Control-Expose-Headers".
  // It is also worth noting that this is not a fancy sync mechanism and
  // does not account for round-trip times or latency.  For our purposes,
  // subsecond synchronization is not really necessary.
  var date = Date.parse(this.xhr_.getResponseHeader('Date'));
  if (date) {
    shaka.util.Clock.sync(date);
  }
```

See also the clock sync and CORS sections of the [docs on live playback](http://shaka-player-demo.appspot.com/docs/tutorial-live.html), which state:

> If your application operates same-origin, no special configuration is required for clock synchronization. If manifests come from another origin, your server must allow Cross-Origin Resource Sharing, also known as CORS. The response for the manifest must include the "Access-Control-Expose-Headers" header with "Date" in the list of values. If this is not given, the browser will not permit the application to read the Date header. Chrome will log an error message to the JS console saying "Refused to get unsafe header". (Note that this is coming directly from Chrome and cannot be silenced by the library.)

Hope that helps!

**Comment by JobaDiniz** [comment]
Didn't see that in docs, thanks :+1:
