### ISSUE TITLE
API for detecting if screen recording is on.

### ISSUE THREAD

**Issue by shineyjames123** [google/shaka-player#1593]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:
Yes
**What version of Shaka Player are you using?**:
shaka-player 2.5-beta
**Can you reproduce the issue with our latest release version?**:
not an issue, this is a query.
**Can you reproduce the issue with the latest code from `master`?**:
not an issue, this is a query.
**Are you using the demo app or your own custom app?**:
custom app
**If custom app, can you reproduce the issue using our demo app?**:

**What browser and OS are you using?**:
chrome, firefox 
**What are the manifest and license server URIs?**:

**What did you do?**
play widevine content in chrome browser in laptops. Able to record the movie.
**What did you expect to happen?**
Playback should either fail if screen recording is turned on.
**What actually happened?**
Playback was successful.

**Comment by joeyparrish** [comment]
This isn't something that a JavaScript application can control.  Please file a bug on Chrome or Widevine about this.
