### ISSUE TITLE
Does anyone know how to use DOMParser in nodejs environment?

### ISSUE THREAD

**Issue by oldmtn** [google/shaka-player#1594]
I saw file mpd_utils_unit.js(shaka-player\test\dash\mpd_utils_unit.js) using DOMParser to parse XML file.
But nodejs environment don't have DOMParser class.

Does anyone know how to use DOMParser in nodejs environment?

**Comment by oldmtn** [comment]
Know it. Thanks
karma + jasmine

**Comment by joeyparrish** [comment]
According to https://stackoverflow.com/questions/47881242/is-there-a-polyfill-for-window-domparser-for-node you can use https://www.npmjs.com/package/xmldom

Hope that helps!
