### ISSUE TITLE
Parse HLS CHARACTERISTICS attribute and pass through to application

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#1598]
Similar to what we do with DASH `<Role>` elements, we should parse HLS CHARACTERISTICS attributes and pass those through to the application.

**Comment by vaage** [comment]
How/Should this affect filtering?

**Comment by joeyparrish** [comment]
I don't know exactly.  But I don't *think* it will necessarily change filtering.  These attributes could be put into the roles list in the manifest structure.

**Comment by avelad** [comment]
I’ll send a PR tomorrow to resolve it!

**Comment by joeyparrish** [comment]
Thanks!
