### ISSUE TITLE
Force onBandwidth() update on restrictions update.

### ISSUE THREAD

**Issue by sanbornhnewyyz** [google/shaka-player#160]
It looks to me like, while restrictions get updated immediately, they don't have any impact on the set of available tracks until an onBandwidth_() call, when it tries to select a new track. This means if you want to set restrictions on the fly, ex: you're playing a video track with bitrate 400000 and you want to restrict bitrate to 300000, then you won't actually see a reduction in video quality until the network changes and triggers an onBandwidth() call. If your network never changes or takes a long time to change you'll never see a change or you'll see a change after a considerable delay. 

Is there a way to force a track update or onBandwidth_() call or something so that restricting bitrates takes effect quickly.

**Comment by joeyparrish** [comment]
Sorry, no method for this currently.  You could add a method to IAbrManager & IVideoSource to trigger choosing new tracks.  Then, when new restrictions are set, Player could trigger this through the video source.

**Comment by sanbornhnewyyz** [comment]
As an alternative, what do you think of adding a 'restrictionschanged' event that gets fired when someone sets new restrictions. Or a 'configurationchanged' event that gets fired when player.configure is called as a way to keep things decoupled.
