### ISSUE TITLE
2.5 Master -- Playback skips first period of VOD asset

### ISSUE THREAD

**Issue by TheJohnBowers** [google/shaka-player#1601]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:
Yes, I don't see anything.  I hope I haven't missed something.
**What version of Shaka Player are you using?**:
2.5 Master
**Can you reproduce the issue with our latest release version?**:
No
**Can you reproduce the issue with the latest code from `master`?**:
Yes
**Are you using the demo app or your own custom app?**:
Demo App
**If custom app, can you reproduce the issue using our demo app?**:
NA
**What browser and OS are you using?**:
Chrome  macos
**What are the manifest and license server URIs?**:
https://content.downlynk.com/88ec75470b1a48efbe943986c4517be2.mpd?ad=superbowl&prettydash=1
https://content.downlynk.com/wv
**What did you do?**
Playback from 2.4.x and earlier does not skip the first period.  Playback from master updated yesterday does skip the first period.  Nothing interesting or informative is logged in the console.
**What did you expect to happen?**
Not skipping the first period.
**What actually happened?**
First Period was skipped.

**Comment by michellezhuogg** [comment]
Found that [Latest nightly build](https://nightly-dot-shaka-player-demo.appspot.com/demo/#asset=https://content.downlynk.com/88ec75470b1a48efbe943986c4517be2.mpd?ad=superbowl&prettydash=1;license=https://content.downlynk.com/wv;lang=en-US;build=uncompiled) skips the first period while [v2.4.4](https://shaka-player-demo.appspot.com/demo/#asset=https://content.downlynk.com/88ec75470b1a48efbe943986c4517be2.mpd?ad=superbowl&prettydash=1;license=https://content.downlynk.com/wv;lang=en-US;v;build=uncompiled) doesn't. Will work on fixing this.

**Comment by joeyparrish** [comment]
Fix released in v2.5.0-beta2.
