### ISSUE TITLE
Question: checking the response of the playManifest before loading the player

### ISSUE THREAD

**Issue by odedhutzler** [google/shaka-player#1603]
Hi,

I would like to check the .mpd response and maybe initiate a new one with a different playManifest URL (before continuing and parsing it, only for dash content)

I thought the best place to do it would be to create a `manifest_parser` plugin, and implement this check in the `start` method.

However, besides that check, I don't want to change the other parsing flow. 

What would be the best way to implement it?

Thanks!
Oded

**Comment by joeyparrish** [comment]
Hi @odedhutzler,

If you just need to examine the manifest contents and redirect to another URL, you can do that with an async response filter.  Some useful docs for this:
 - [License Server Authentication tutorial](https://shaka-player-demo.appspot.com/docs/api/tutorial-license-server-auth.html), which includes async filters
 - [License Wrapping](https://shaka-player-demo.appspot.com/docs/api/tutorial-license-wrapping.html), which uses a response filter
 - API docs for [registerResponseFilter()](https://shaka-player-demo.appspot.com/docs/api/shaka.net.NetworkingEngine.html#registerResponseFilter)
 - API docs for [ResponseFilter](https://shaka-player-demo.appspot.com/docs/api/shakaExtern.html#.ResponseFilter) type
 - API docs for [Response](https://shaka-player-demo.appspot.com/docs/api/shakaExtern.html#.Response) type

Example (untested):

```js
const networkingEngine = player.getNetworkingEngine();
networkingEngine.registerResponseFilter(async (type, response) => {
  // Ignore non-manifest responses.
  if (type != shaka.net.NetworkingEngine.RequestType.MANIFEST) {
    return;
  }

  // Decide whether or not to redirect.
  const manifestData = StringUtils.fromUTF8(response.data);
  const redirectUri = decideWhetherOrNotToRedirect(manifestData);
  if (!redirectUri) {
    // The original manifest data will be used unmodified. 
    return;
  }

  // Make an additional request to the redirect URI.
  const redirectedRequest = {uris: [redirectUri]};
  const redirectedResponse = await networkingEngine.request(type, redirectedRequest);

  // Copy the response back onto the original response object.
  response.uri = redirectedResponse.uri;
  response.headers = redirectedResponse.headers;
  response.data = redirectedResponse.data;

  // Now the rest of the system will see the replaced manifest data.
});
```

Does this help?

**Comment by odedhutzler** [comment]
Hey, @joeyparrish thanks. Yes, it does.

Oded

**Comment by joeyparrish** [comment]
Then it seems like we can close this issue.  Let us know if you need anything else.
