### ISSUE TITLE
Allow client to override presentationDelay

### ISSUE THREAD

**Issue by chrisfillmore** [google/shaka-player#1604]
DASH IOP 4.2 says:
> **4.3.4.4.2 Joining at the live edge**
For joining at the live edge there are basically two high-level strategies:
>- Every client participating in the service commits to the same presentation delay (PD) relative to the announced segment availability start time at start-up and in continuous presentation, possible using one suggested by the Content Provider and then attempts to minimise start-up latency and maintain the buffer. The content provider may have provided the MPD@suggestedPresentationDelay (SPD) or may have provided this value by other means outside the DASH formats. The content author should be aware that the client may ignore the presence of MPD@suggestedPresentationDelay and may choose its own suitable playout scheduling.
>- The client individually picks the presentation delay (PD) in order to maximize stable quality and does this dependent on its access, user preferences and other considerations.

If I understand correctly, Shaka's current behaviour is to allow the client to provide a `defaultPresentationDelay`, but that this is overridden by any `suggestedPresentationDelay` present in the MPD. It seems this should be the other way around, based on what the spec says.

We are currently overriding `suggestedPresentationDelay` using a manifest response filter, but it would be nice to be able to just provide the value we want to Shaka.

If you agree with this change, I can put together a PR.

**Comment by joeyparrish** [comment]
Sounds reasonable.  I would suggest adding a flag to the DASH config that would ignore the suggestedPresentationDelay, which defaults to false.  With that flag set, the configured default would be the only value in effect.  This way would not break compatibility or change behavior for anyone by default.
