### ISSUE TITLE
DASH thumbnail hack

### ISSUE THREAD

**Issue by jozefchutka** [google/shaka-player#1606]
Hi everyone,

we would like to run two instances of shaka next to each other at the same time, one large format for main video and small one for a scrub thumbnail which would load the same dash manifest and seek when user hover scrollbar. (I am aware of the better image sprite approach but we do not have option to add this feature into the dash manifest on server side). So far this appears working:
```html
<!DOCTYPE html>
<html>
<head>
<script src="shaka-player.compiled.js"></script>
<style>#thumbnail {position: absolute;border: 1px solid white;background: black;}</style>
</head>
<body>
<video id="video" width="640" controls></video>
<video id="thumbnail" width="200" muted></video>
<script>
var videoLoaded = 0;
var video = document.getElementById('video');
var thumbnail = document.getElementById('thumbnail');
var manifestUri = 'https://demo.unified-streaming.com/video/tears-of-steel/tears-of-steel-dash-widevine.ism/.mpd';
var videoConfig = {drm:{servers:{"com.widevine.alpha": "https://cwip-shaka-proxy.appspot.com/no_auth"}}};
var thumbnailConfig = Object.assign({}, videoConfig);
thumbnailConfig.abr = {restrictions: {minBandwidth: 0, maxBandwidth: 0}}
thumbnailConfig.streaming = {bufferingGoal:1, bufferBehind:1, rebufferingGoal:1}

function initApp() {
	shaka.polyfill.installAll();
	initPlayer(video, videoConfig);
	initPlayer(thumbnail, thumbnailConfig);
}

function initPlayer(video, config) {
	var player = new shaka.Player(video);
	player.addEventListener('error', console.error);
	player.configure(config);
	player.load(manifestUri).then(function() {
		videoLoaded++;
	}).catch(console.error);
}

function mouseMove(event) {
	var rect = video.getBoundingClientRect();
	thumbnail.style.left = (event.clientX - thumbnail.clientWidth / 2) + "px";
	thumbnail.style.top = (rect.top + rect.height - thumbnail.clientHeight - 25) + "px";
	if(videoLoaded == 2)
		thumbnail.currentTime = (event.clientX - rect.left) / rect.width * video.duration;
}

document.addEventListener('DOMContentLoaded', initApp);
document.addEventListener('mousemove', mouseMove);
</script>
</body>
</html>
```

We are trying to optimize thumbnail appearing asap for each seek by removing extra network traffic:
- removing audio track by removing AdaptationSet-s from manifest response through `player.getNetworkingEngine().registerResponseFilter` (not in this example)
- reducing various different buffer config instructions or manifest `minBufferTime`, but no luck so far to get down to a single segment only (observe 3-5 video segments downloaded with each `currentTime` change in the example)

Can you please recommend any further optimizations, as well as confirm the most suitable way of removing audio tracks from playback?

thanks

**Comment by chrisfillmore** [comment]
A few questions:
- Are you doing this just for VOD? Or do you support seeking (e.g. backwards) in Live?
- What is your lowest bandwidth video Representation?
- If VOD, how long are your assets? A few minutes? 30 minutes? An hour? 2+ hours?

**Comment by jozefchutka** [comment]
thanks @chrisfillmore 
1. Our content is both VOD and Live with seeking. Do you have any suggestions if this was for VOD only?
2. 192x108 @112227
3. actually VOD can be between 5 minutes to few hours, same for live
4. single period at this point

Please shout any ideas  you can think of.

**Comment by chrisfillmore** [comment]
There is not really a good solution here, that I can think of. The key problem is that, for thumbnails, you presumably want to prefetch this content, because the user may attempt to scrub to any point in the video at any time. If you fetch the thumbnails on-demand, it will likely be too slow to be useful. (I could be wrong on this point, I've never tested this.)

Prefetching would likely consume too much bandwidth. 112kbps * 300s = ~33 Mb. This means that for a 5-minute video, you will have to prefetch 33 Mb of video data in order to provide thumbnail support. For a 1hr video, the amount is closer to 400Mb.

I imagine (but again I may be wrong) that users do their scrubbing at the start of playback, presumably to get to the point where they want to start watching, then watch the content to completion (or stop at some point). This means you wouldn't be able to prefetch the thumbnail video data in time to actually use it.

**Comment by jozefchutka** [comment]
I see your point. So probably that would be too large portion of data to load upfront that would even affect initial adaptation/quality. 

Downloading 1 segment of the lowest quality is relatively quick, but for some reasons we can see rather a few segments downloaded for each seek, do you have any idea why that is happening? May it be its looking for a keyframe or similar reason? Any way to avoid it?

**Comment by jozefchutka** [comment]
Is there a way/api to get information where to seek to get to the beginning of the segment? So lets say instead of seeking to time 12345 (middle of segment file), I would seek to 12347 which is exactly the start time of a segment?

**Comment by jozefchutka** [comment]
Using this we are able to seek to the beginning of the segment:

```
function fixSeekTime(time) {
	var track = thumbnailPlayer.getVariantTracks().find(function(track){return track.active === true;});
	var variant = thumbnailPlayer.getManifest().periods[0].variants.find(function(variant){return variant.id === track.id;});
	var position = variant.video.findSegmentPosition(time);
	var reference = variant.video.getSegmentReference(position);
	return reference.startTime;
}
```

however I can still see 2 segment requests are being done and following information from `thumbnailPlayer.getBufferedInfo().video[0]` it seems it loads one extra segment behind although `config.streaming.bufferBehind = 0`

**Comment by joeyparrish** [comment]
> We are trying to optimize thumbnail appearing asap for each seek by removing extra network traffic

> no luck so far to get down to a single segment only (observe 3-5 video segments downloaded with each currentTime change)

> Downloading 1 segment of the lowest quality is relatively quick, but for some reasons we can see rather a few segments downloaded for each seek, do you have any idea why that is happening? May it be its looking for a keyframe or similar reason? Any way to avoid it?

>  it seems it loads one extra segment behind. 

For content with both video & audio, that's 2 segments at a minimum.  Add to that some off-by-one logic we have to deal with manifest inaccuracies, and you're at 4 segments minimum for any time later than the first segment of the presentation.

Even if you remove that logic in a fork, you're still (in my opinion) trying to solve this problem in a strange way.  If you want thumbnails, you should probably just have a JPEG thumbnail sheet.  It's the right tool for the job, and I would expect that it would go much better.

You could also try using a "trick play track" which is 1fps and all key-frames.  With a low-framerate track, you could then skip Shaka Player and MediaSource for the trick play track and use video.src= to load a single track (video only).

You could also try removing the logic which clears the buffer on an unbuffered seek.  That way, even if you fetch two segments, you're unlikely to have to refetch them ever.  That 33MB of buffering for the entire presentation at low bitrate would be an upper limit.  You'd eventually reach it by seeking around the presentation, but you'd never download a segment twice.

Does any of that help?

**Comment by jozefchutka** [comment]
hi @joeyparrish 

we are able to remove audio tracks on fly (on client) from manifest so for thumbnail player instance its only video segments loaded. Can you please elaborate a bit on "some off-by-one logic we have to deal with manifest inaccuracies" maybe that is why we see 2 video segments downloaded for each seek.

I understand there are better and more optimal ways of displaying thumbnails, including jpeg sheet/sprite or trick play track, and we would surely prefer to use that when available. However we do not have control over streaming server or manifest creation in this case - so looking for options on client.

We will play around with buffering options further, at this point browser level segment caching works good enough to no to keep additional data on JS heap.

We believe we have reached quite solid implementation at this point, the only remaining question remains why two video segments of the same profile are loaded for each seek, and if there is a way to avoid it, and so, to speed up rendering the "thumbnail" frame.

**Comment by TheModMaker** [comment]
> Can you please elaborate a bit on "some off-by-one logic we have to deal with manifest inaccuracies" maybe that is why we see 2 video segments downloaded for each seek.

When we seek, we always request the the segment before the seek time.  This ensures that if the segments in the manifest are different than the media, we get content at the seek time.  The media times in the manifest may not be exactly the same times as the times in the segments.  So if we seek to a time of 31 seconds and download the segment starting at 30 seconds, that segment may really start at 32 seconds, meaning we won't have any content at the current time of 31 seconds.

Unfortunately there is no way to change this behavior.

**Comment by jozefchutka** [comment]
Hi @TheModMaker ,
Understood, I think I have also identified the piece of code you are referring to ( https://github.com/google/shaka-player/blob/master/lib/media/streaming_engine.js#L1355 ) that causes the additional segment to be loaded. Is there an elegant way you can suggest to customize streaming engine in runtime, so it does not optimize segment position? For now I have commented out that line of code in sources, and works perfect. However I was thinking if this is something that can be handled without having to do custom shaka build?

**Comment by TheModMaker** [comment]
No, there isn't any way to change this behavior, the only way would be to edit the sources and create a custom build.

**Comment by jozefchutka** [comment]
Thanks everyone, I believe I have collected enough information for further work.
