### ISSUE TITLE
Offline tutorial: sorting tracks for selecting by highest bandwidth is incorrect in the code sample

### ISSUE THREAD

**Issue by gigon** [google/shaka-player#1608]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**: Yes

**What version of Shaka Player are you using?**: v2.5.0-beta-master

**Can you reproduce the issue with our latest release version?**: yes

**Can you reproduce the issue with the latest code from `master`?**: yes

**Are you using the demo app or your own custom app?**: n/a

**If custom app, can you reproduce the issue using our demo app?**: n/a

**What browser and OS are you using?**: Chrome/Windows 10 

**What are the manifest and license server URIs?**: https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd

**What did you do?**
Modified a bit the sample code from the Offline tutorial, to select the lowest bandwidth track. 
You can see an example here: https://jsbin.com/tejutojuvu/2/edit?html,js,console,output
(download the asset to see the issue).

I logged to the console the correct sorting (bandwidths sorted from 
189957 to 1544182), as opposed to the current wrong one (bandwidths run from 
863227 to 1544182). 

**What did you expect to happen?**
1) Expected to be able to select the highest or lowest bandwidth track.
2) Expected to see in the log the selected track bandwidth
 
**What actually happened?**
Got tracks sorted by lexicographic rather than numeric order 
Saw in the log [object object] instead of selected track's bandwidth.

**Comment by joeyparrish** [comment]
Fix cherry-picked to v2.4.5.
