### ISSUE TITLE
catchup is not playing

### ISSUE THREAD

**Issue by avichayn** [google/shaka-player#1613]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:

**What version of Shaka Player are you using?**:
v2.4.4-uncompiled

**Can you reproduce the issue with our latest release version?**:
yes - on v2.4.4-uncompiled

**Can you reproduce the issue with the latest code from `master`?**:

**Are you using the demo app or your own custom app?**:
using https://shaka-player-demo.appspot.com/demo/#

**If custom app, can you reproduce the issue using our demo app?**:

**What browser and OS are you using?**:
windows 10 and chrome 69.0.3497.100 (Official Build) (64-bit)

**What are the manifest and license server URIs?**: it's clear

**What did you do?**
played the following url:
https://d2q8p4pe5spbak.cloudfront.net/bpk-tv/ABPnews/ABPnews.isml/manifest.mpd?begin=20181010T044000&end=20181010T052000

**What did you expect to happen?**
playing the url as VOD (catchup)

**What actually happened?**
nothing played

**Comment by joeyparrish** [comment]
This plays for me as a live stream in Chrome on Linux.  Why do you say it should play as VOD?  I'm not sure I see what the problem is.

**Comment by avichayn** [comment]
The manifest was fixed...

**Comment by joeyparrish** [comment]
Thanks for letting us know!
