### ISSUE TITLE
Bug on disconnect from chromecast

### ISSUE THREAD

**Issue by bgimmig** [google/shaka-player#1614]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:
yes
**What version of Shaka Player are you using?**:
2.5.0-beta
**Can you reproduce the issue with our latest release version?**:
yes
**Can you reproduce the issue with the latest code from `master`?**:
yes
**Are you using the demo app or your own custom app?**:
both
**If custom app, can you reproduce the issue using our demo app?**:

**What browser and OS are you using?**: chrome, linux, windows
Debia, windows 10, chrome
**What are the manifest and license server URIs?**:
I send you an email on shaka-player-issues@google.com

**What did you do?**

I was playing live stream on chromecast, i disconect from suggestDisconnect method of castProxy

**What did you expect to happen?**

the local player should continue to play the stream

**What actually happened?**

by stopping playback on the chromecast, the local player does not continue playing the stream. with version 2.4.4 this problem does not exist.

**Comment by joeyparrish** [comment]
This is still an issue in v2.5.  My guess is that it's something to do with our cast proxy, but we need to dig deeper.  Unfortunately, we couldn't solve this before v2.5.0, but the fix could be cherry-picked to a bugfix release once we find it.

**Comment by joeyparrish** [comment]
This is not reproducible in the latest release, v2.5.8.  I'm not sure when we fixed it, but it's fixed.
