### ISSUE TITLE
Cast Receiver appearance

### ISSUE THREAD

**Issue by bgimmig** [google/shaka-player#1615]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:
yes
**What version of Shaka Player are you using?**:
2.4.4, 2.5.0-beta, master
**Can you reproduce the issue with our latest release version?**:
yes
**Can you reproduce the issue with the latest code from `master`?**:
yes
**Are you using the demo app or your own custom app?**:
both
**If custom app, can you reproduce the issue using our demo app?**:
yes
**What browser and OS are you using?**:
linux, windows 10, chrome
**What are the manifest and license server URIs?**:
not needed

**What did you do?**

I modified the index.html and receiver_app.css files in the demo directory. Then I compiled the code by running the python build / build.py + @ complete --force or python build / all.py --force command

**What did you expect to happen?**

I would like to change the appearance of cast_receiver, to integrate the logo of my company. I would also like to change the title that appears in the Chromecast selection popup that is currently Shaka v2.1 Cast Demo. This title is just above the progress bar

**What actually happened?**

the appearance of cast_receiver doesn't change

**Comment by joeyparrish** [comment]
Does this answer your question?

**Comment by bgimmig** [comment]
Thank you for your fast answer, I am quickly going to test.

**Comment by bgimmig** [comment]
Thank you for your help, I succeeded well has to modify the appearance of the chromecast.
