### ISSUE TITLE
Getting CORS error when trying to enable offline storage 

### ISSUE THREAD

**Issue by pineapplejoe** [google/shaka-player#1616]
I have DASH media on AWS S3 - distributed via AWS CloudFront. 

Cloudfront uses signed cookies to restrict access to restrict access to content.  

When streaming the content with the player I use the following code to ensure that the local signed cookies get sent.  

			player.getNetworkingEngine().registerRequestFilter(function(request_type, request) {
				request.allowCrossSiteCredentials = true;
			});

This works.  Note that not having this code when trying to play the media will result in a CORS error. 

However when I try and save the DASH content for offline use - I get a CORS error.  If I add the same code above to the player that I create and pass to the offline.storage object it doesnt seem to make a difference. 

I have a test environment that does not need signed cookies and the saving code works just fine. Its only when its in the production environment, which requires the signed cookies, do I then get the CORS error.

If it matters - i dont care about protecting this offline content because the person that has theability to save it has permissions to do so. 

How can I get this to work?

**Comment by vaage** [comment]
@pineapplejoe next time, please use the issue template provide when creating a new issue. It will help us ensure that we have all the information we need to help you resolve your issues.

I have included below the issue template for to use for this issue. I would also ask that you include some way for our to reproduce what you are seeing.

Thanks!



**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:

**What version of Shaka Player are you using?**:

**Can you reproduce the issue with our latest release version?**:

**Can you reproduce the issue with the latest code from `master`?**:

**Are you using the demo app or your own custom app?**:

**If custom app, can you reproduce the issue using our demo app?**:

**What browser and OS are you using?**:

**What are the manifest and license server URIs?**:
_You can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest.  A copy of the manifest text or an attached manifest will **not** be enough to reproduce your issue, and we **will** ask you to send a URI instead.  You can copy the URI of the demo app to send us the exact asset, licence server, and settings you have selected there._

**What did you do?**

**What did you expect to happen?**

**What actually happened?**
