### ISSUE TITLE
getting buffer levels

### ISSUE THREAD

**Issue by krvangala** [google/shaka-player#1617]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:
Yes
**What version of Shaka Player are you using?**:
2.4.2
**Can you reproduce the issue with our latest release version?**:
NA
**Can you reproduce the issue with the latest code from `master`?**:
NA
**Are you using the demo app or your own custom app?**:
NA
**If custom app, can you reproduce the issue using our demo app?**:
NA
**What browser and OS are you using?**:
Linux Chrome
**What are the manifest and license server URIs?**:

NA
**What did you do?**

**What did you expect to happen?**
NA
**What actually happened?**
NA

Hi,
what is the best way get audio and video buffer levels?. 
what is the best place i can add a hook or fir an event when buffer level changed like buffer added or removed.
Thanks
Krishna

**Comment by vaage** [comment]
@krvangala Could you elaborate on what you are looking to do? We will be able to provide more specific guidance if you know what use case you are looking to implement as I am not clear on some of the terms you are using (e.g. "buffer level").

Here is a board explanation of what is happening in Shaka Player:
1. ABR Manager picks which streams should be streamed based on the current network bandwidth by telling Streaming Engine what streams to download.
2. Streaming Engine fetches segments using NetworkingEngine and pushes them to Media Source Engine.
3. Media Source Engine manages Media Source and appends and removes buffers from Media Source.

**Comment by chrisfillmore** [comment]
@krvangala If you are asking about how much video is buffered at any given moment, you can obtain this information from the video element:

```
// Get your video element
const videoElement = document.querySelector('video');

// This is a TimeRanges object, see: https://developer.mozilla.org/en-US/docs/Web/API/TimeRanges
const buffered = videoElement.buffered;

// There could be multiple buffered ranges, so you will need to find the one you want.
for (let i = 0; i < buffered.length; i++) {
  console.log(buffered.start(i), buffered.end(i));
}
```

Let me know if this is useful to you.

**Comment by krvangala** [comment]
Hi @vaage  and @chrisfillmore  thanks for reply.

buffer level  here means, buffer level (time ranges) in Media source (  video or audio).
We have deployed our player( uses Shaka 2.4.2)  on field. Would like collect  buffer levels of audio and video in Media Source.  
looks like shaka.Player.prototype.getBufferedInfo    will serve the purpose.
Thanks
Krishna

**Comment by vaage** [comment]
@krvangala I am glad you found what will work for you. I am going to close the issue.

**Comment by joeyparrish** [comment]
The `buffered` member of the video element is the intersection of audio and video buffer levels.  If you want a breakdown, use `player.getBufferedInfo()`.  This will show you video, audio, text, and "total" (intersection of audio and video as reported by video element).

https://shaka-player-demo.appspot.com/docs/api/shaka.Player.html

Hope that helps!
