### ISSUE TITLE
Support 'S' elements with negative 'r' attributes in SegmentTimeline.

### ISSUE THREAD

**Issue by tdrews** [google/shaka-player#162]
A negative 'r' attribute indicates that a specified segment spans until the 't' attribute of the specified segment following it or to the end of the Period.

**Comment by priyajeet** [comment]
Thanks for getting this implemented. One thing I did notice was that the MPD fetching bypasses the request callback. Wouldn't requesting the MPD also go through the callback for consistancy?

**Comment by tdrews** [comment]
I assume that the above comment pertains to #148. Please see my response there.
