### ISSUE TITLE
player chromecast communication

### ISSUE THREAD

**Issue by bgimmig** [google/shaka-player#1622]
Hello,
#
I would like to know if there is a way of communication between the player and the chromecast, I was thinking of a system of custom events or a communication channel.

I found, on receiver side, the cast.receiver.CastReceiverManager.getInstance() and the broadcast method in your source code, but I do not know if I'm in the right direction

Thanks for your help

**Comment by vaage** [comment]
@bgimmig Right now there is no generic message support exposed to the app.

The way things are implemented right now, [CastSender](https://github.com/google/shaka-player/blob/master/lib/cast/cast_sender.js) is responsible for sending messages to [CastReceiver](https://github.com/google/shaka-player/blob/master/lib/cast/cast_receiver.js). By adding methods to CastSender, you can use its [sendMessage_](https://github.com/google/shaka-player/blob/b3f6e24fdb2b6c3244143b4d9836ff21f1307ad8/lib/cast/cast_sender.js#L647) to send messages to the receiver.

However, I do see this as something that we would be willing to consider as an enhancement. If this is something you need. I would suggest opening a new issue requesting it as an enhancement.

If you choose to open a new issue for an enhancement, I ask that you include a description of the problem you are trying to solve / the use-case you are trying to support in your app. This way, we can be more informed when it comes to designing the enhancement.

Does this help?

**Comment by TheModMaker** [comment]
If you're interested in a Chromecast API solution, you should look at their [messaging](https://developers.google.com/cast/docs/custom_receiver#messages) protocol.  You can use that to send generic messages to the receiver app, and your custom receiver can handle it.  We use a specific channel to send messages related to playback, but you could use a different namespace and send messages for your app.

**Comment by bgimmig** [comment]
Hello,

Thank you for your fast answer.

I have make some tries with the proposals of @vaage . The problem, with this solution, is that I have to modify your code to succeed in realizing my need. I am thus going to create an issue as an enhancement. My need is to make pass dated in the chromecast to display them above the video (a kind of pop-up). But we can easily imagine many of the other applications, the receiver having a technology html/js/css, it would be nice to play with.

While waiting for I go and look at the protocol messaging advised(recommended) by @TheModMaker 

Thank you for your help and your advice
