### ISSUE TITLE
Server certificate is not configured before Store and Delete operations

### ISSUE THREAD

**Issue by gigon** [google/shaka-player#1623]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**: Yes

**What version of Shaka Player are you using?**: v2.5.0-beta-master

**Can you reproduce the issue with our latest release version?**: yes

**Can you reproduce the issue with the latest code from `master`?**: yes

**Are you using the demo app or your own custom app?**: demo app

**If custom app, can you reproduce the issue using our demo app?**: yes

**What browser and OS are you using?**: Chrome/Windows 10

**What are the manifest and license server URIs?**:
Will send the manifest, license, and certificate URIs to shaka-player-issues@google.com

**What did you do?**
Added my asset to the demo assets list OR filled the manifest, license, and certificate URIs as Custom asset, select my asset and download it.

**What did you expect to happen?**
a) No errors in the debug console
b) The first (and only) license request raised from the CDM is for a license.

**What actually happened?**
a) The call to storage.configure raises an error:  "Invalid config, unrecognized key .progressCallback"

b) The first license request raised from the CDM is for a widevine certificate (2nd one is for a license)

**Comment by vaage** [comment]
@gigon When I try your content, it plays without issue. Now I noticed that in the content your provided the cert path was different from the cert you sent us. After fixing that, everything played without issue on master.

**Comment by gigon** [comment]
@vaage The issue is not about playback, it is about download.
And it does get downloaded fine. 
The issue is about the optimization where the application has the certificate beforehand (e.g. by downloading it), and feeds it to Shaka library, which calls the widevine (EME) function setServerCertificate before creating the key sessions. 
This prevents getting a "key message" event from the CDM that requests a widevine certificate, 
before the event that requests the actual license.

This optimization is demonstrated in case of playback, but in case of Download (and also in the release of a persistent license!), the demo application does not preload the certificate I set in the Custom field. 

You can see this by looking at XHR requests in the chrome debugger.
In case of streaming playback you get only one request to our license server.
In case of Download or Delete you get two requests.

I added code to the demo application, to preload the certificate, in a Pull request I submitted.
But later I saw that Shaka library does not call setServerCertificate at all in case of Storage session. 
It calls it only when a video tag is attached before playback.

Please correct me if I misunderstand.

**Comment by joeyparrish** [comment]
Released in v2.5.0-beta2.
