### ISSUE TITLE
Unable to play m3u8 HLS stream

### ISSUE THREAD

**Issue by bansalvks** [google/shaka-player#1625]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:
YES

**What version of Shaka Player are you using?**:
2.5.0-beta

**Can you reproduce the issue with our latest release version?**:
YES

**Can you reproduce the issue with the latest code from `master`?**:
YES

**Are you using the demo app or your own custom app?**:

**If custom app, can you reproduce the issue using our demo app?**:

**What browser and OS are you using?**:
Chrome on OSX

**What are the manifest and license server URIs?**:
_Skipping to 10 seconds_
https://video-dev.github.io/streams/x36xhzz/x36xhzz.m3u8

_Not playing_
https://watch.hoichoi.stream/movies/Chaya-Surya/hls/CHAYA_SURYA.m3u8

**What did you do?**
Tried to play normal HLS

**What did you expect to happen?**
Video should be played

**What actually happened?**
Errors

A very heartwarming hello to shaka team :)

I am facing 2 issues with Non DRM HLS Streams.

**ISSUE 1**
![skipping to 10](https://user-images.githubusercontent.com/8565993/47077479-a7bf8b00-d21e-11e8-8dff-ac870713e11f.gif)

URI: [https://video-dev.github.io/streams/x36xhzz/x36xhzz.m3u8]( https://video-dev.github.io/streams/x36xhzz/x36xhzz.m3u8)

Content automatically skipping to 10 seconds.
CodePen Example: [https://codepen.io/bansalvks-the-decoder/pen/xyYgEp?editors=1010](https://codepen.io/bansalvks-the-decoder/pen/xyYgEp?editors=1010)

If I am playing the same stream with HLS.js then its working fine, example
[https://codepen.io/bansalvks-the-decoder/pen/pxaRdN?editors=0010](https://codepen.io/bansalvks-the-decoder/pen/pxaRdN?editors=0010)

**ISSUE 2**

ERROR: 4030 -- **MANIFEST.HLS_COULD_NOT_PARSE_SEGMENT_START_TIME**
Unable to fetch a partial HLS segment! Falling back to a full segment request, which is expensive! 

URI: [https://watch.hoichoi.stream/movies/Chaya-Surya/hls/CHAYA_SURYA.m3u8](https://watch.hoichoi.stream/movies/Chaya-Surya/hls/CHAYA_SURYA.m3u8)

SHAKA CODEPEN: [https://codepen.io/bansalvks-the-decoder/pen/JmpXWR?editors=1011](https://codepen.io/bansalvks-the-decoder/pen/JmpXWR?editors=1011)

With Hls.js its working fine.
HLS.js CODEPEN : [https://codepen.io/bansalvks-the-decoder/pen/gBvgGN?editors=0010](https://codepen.io/bansalvks-the-decoder/pen/gBvgGN?editors=0010)

I am very new to streaming domain and I am trying my best.. Many Thanks for everything,

Your Fan,
Vikas Bansal

P.S: I am not comparing HLS.js with Shaka player, I am just trying to validate the streams... Please do not take it wrong..

**Comment by bansalvks** [comment]
@ismena thank you for replying, it means a lot.

I updated the codepen : https://codepen.io/bansalvks-the-decoder/pen/xyYgEp?editors=0010

and added the config that you mentioned
``` player.configure('manifest.defaultPresentationDelay', 0);```
However it does not work. :( still stuck with both issues.

**Comment by ismena** [comment]
Ahh, I was so sure, that was it :)
Sorry for the random guess, I'll do a proper investigation tomorrow.

**Comment by vksbansal** [comment]
Many thanks @ismena... it feels so good and emotionally helpful that someone is looking after your issue. Huge thanks for devoting your time.

I struggling with playing HLS .m3u8 streams in shaka player...

P.S/FYI: I am working for a content distributor not content owners so I have to support all kind of streams.. I cannot or request to alter or change streams manifest. We just have to play it.

**Comment by ismena** [comment]
@joeyparrish could you please check if our parser is doing something wrong, once you're back

**Comment by vksbansal** [comment]
@ismena You have the skill of cutting the tension with a hilarious comment just like one of my fav char [Cisco Ramon](https://g.co/kgs/BAzw3x)

Will be waiting for the response from @joeyparrish and hope he will like the big **pink** sticky note on his monitor :D :X :)

**Comment by ismena** [comment]
Aww, I've never been compared to a superhero before :blush:

**Comment by TheModMaker** [comment]
Noticed in #1602, fixed in bc7f31efbd6d57ef905c344338bba8fd8c0da5ab.  You can try the nightly to see it works: https://nightly-dot-shaka-player-demo.appspot.com

**Comment by TheModMaker** [comment]
The second isn't playing because we can't parse the TS data.  We only support playing encrypted TS through Widevine, we don't support AES-128 (see #850).  With Widevine encryption, the TS headers are still in the clear, so we can pull the start time out of it.  With AES-128, the whole data is encrypted, so we can't get the start time.  Even if we ignored that error, we would get a different error later since we don't support AES-128.

**Comment by ismena** [comment]
Thank you @TheModMaker, I should've known to ask you!
On the down side, I'll have to take the sticky note off Joey's monitor now.

**Comment by vksbansal** [comment]
Many thanks @TheModMaker  @ismena  for sparing your time to look at this issue 

First Issue:
As you said I used 
https://nightly-dot-shaka-player-demo.appspot.com/dist/shaka-player.compiled.debug.js
and found that the video is still skipping 10 seconds as you can see in this [code pen](https://codepen.io/bansalvks/pen/XxPYvx?editors=1010)

Second issue:
Its seems that I have to use ```HLS.js``` to play the ```AES-128``` content or please let me know if there is any work around to do so.

**Comment by TheModMaker** [comment]
> Many thanks @TheModMaker @ismena for sparing your time to look at this issue
> 
> First Issue:
> As you said I used
> https://nightly-dot-shaka-player-demo.appspot.com/dist/shaka-player.compiled.debug.js
> and found that the video is still skipping 10 seconds as you can see in this [code pen](https://codepen.io/bansalvks/pen/XxPYvx?editors=1010)

Did you try clearing your browser cache?  When I go to the code pen link it plays from 0.
> 
> Second issue:
> Its seems that I have to use another lib e.g.`HLS.js` to play the `AES-128` content. If you know a workaround please let me know.

Unfortunately yes, until #850 is closed you'll need to use something else to play that content.

**Comment by vksbansal** [comment]
Yes its working fine after cleaning cache. Pardon me for my ignorance @TheModMaker 

Waiting for the release with this fix. 
May I Know when will it be released?

Many thanks  : )

**Comment by bansalvks** [comment]
This is a Disheartening News for me @TheModMaker

May I know the release cycle span. So that I may guess how soon will we get the release v2.7

**Comment by TheModMaker** [comment]
We released v2.4 in May and are still working on v2.5.  v2.6 will hopefully have a shorter release cycle, but it is hard to tell.  It will probably be at least 6 months before we can work on that feature.
