### ISSUE TITLE
FR: fix python shebang lines

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#1637]
`/usr/bin/python` is usually a symlink to a particular version of python, but it could be python 3 in some cases.  Our scripts only work on python 2.7.

Also, some environments don't use /usr/bin for python.  We shouldn't assume /usr/bin for this.

Instead, we should use `env`, which will find the desired binary in the `PATH`:

```sh
#!/usr/bin/env python2.7
```

Any scripts that use `env python` or `/usr/bin/python` need to be fixed.  In addition to `build/`, please check all python scripts in `third_party/` as well.

**Comment by joeyparrish** [comment]
@thasso

**Comment by vaage** [comment]
@TheModMaker has updated our scripts to be Python2.7 and Python3 compatible, thanks Jacob! We have also vetting all our script and they all already use `#!/usr/bin/env`. So we should be good to go.

**Comment by joeyparrish** [comment]
Fixed in 841f31b3ba485d1a8f82cda4d2e5e0d97aa8c139
