### ISSUE TITLE
hosting content locally for testing

### ISSUE THREAD

**Issue by hanumantha03** [google/shaka-player#1645]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:
Yes 

**What version of Shaka Player are you using?**: 2.4

**Can you reproduce the issue with our latest release version?**: 
Yes

**Can you reproduce the issue with the latest code from `master`?**: 

**Are you using the demo app or your own custom app?**:
Demo app. But using my own .mpd file which was made from .mp4 using mp4box

**If custom app, can you reproduce the issue using our demo app?**:

**What browser and OS are you using?**:
Browser : Chrome.      OS: Windows 10

**What are the manifest and license server URIs?**:

**What did you do?**
I have a video file (**.mp4**) in my system in C drive i have converted it into .mpd using mp4box and i copy-pasted the **.mpd** file path in javascript **var manifest = ""** variable.

**What did you expect to happen?**
I expected that the video would play 

**What actually happened?**
**Error 1000** in console was the output.

Can you please tell me where and how to put these .mpd files so that they would get played on the browser

**Comment by vaage** [comment]
@hanumantha03 are you trying to load it with a `file://` url? If so, that won't work.

The content needs to be hosted in order to play, but thankfully running a local web server will solve that. If you don't want to install a web server, python actually makes it really easy to run a web server and server any directory. Here's the [documentation](https://docs.python.org/2/library/simplehttpserver.html) that I've used in the past to do that.

**Comment by hanumantha03** [comment]
Thank you very much.
Can I use Nodejs to create a server and host the .mpd and dashinit.mp4 on the server?

**Comment by vaage** [comment]
I don't see any reason why that would not work. But you may run into some CORS issues if you are hosting the content from a different domain than the site (i.e. you host the content but use our hosted demo page). Normally I'll build the demo page and host the demo page and content locally when I am testing to ensure that I don't run into an CORS issues.

**Comment by hanumantha03** [comment]
Actually I want to test it locally first.
was it easy when you were working with python web server?

**Comment by vaage** [comment]
Yup. Just run `python -m SimpleHTTPServer 8000` in a directory that contains both the content and the demo. Then you should be able to go to `localhost:8000` and browser until you find the demo.

**Comment by hanumantha03** [comment]
thank you vaage it is working!!

**Comment by hanumantha03** [comment]
If I want to play N number of videos, do I have to create N number of javascript files for them?
or can I create one common xml file for all the .mpd files?

**Comment by joeyparrish** [comment]
For `N` videos, you would need `N` MPD files.  But you can easily create one HTML & JS page with `N` video elements and `N` instances of Shaka Player controlling them.

Does that help?

**Comment by shabab11** [comment]
I am able to play .mpd file but i need thumbnail for my video......How can I create a thumbnail for newly created .mpd file????

**Comment by shabab11** [comment]
@joeyparrish @vaage @johan please help...................

**Comment by vaage** [comment]
@shabab11 Since your new question strays beyond the scope of the original topic, could you please open a new issue for it. This will make it easier to others to find solutions to similar problems and will make it easier on us to track issues.

**Comment by shabab11** [comment]
thanks @joeyparrish that is helpful...........it will be very much appreciated if u can give some insight on How can i add and play subscript along with the video and subscript should be highlighted as video progress?

**Comment by shabab11** [comment]
@vaage  sure i will open a new issue on that... thanks for the response

**Comment by joeyparrish** [comment]
@shabab11, I'm sorry, but I don't understand your question.  What do you mean by "subscript"?  Do you mean "subtitles"?

**Comment by shabab11** [comment]
@joeyparrish yes i mean to say "subtitles".....Thanks

**Comment by shabab11** [comment]
@joeyparrish subtitle issue has been resolved........I am able to play video with subtitle without any error 🥇  .............can u confirm that shaka only allow .vtt format subtitle because .txt and .srt was not playing in my case. Also I need a **download** option for the video am playing, so that user can download the video as well........ can u give some insight on download feature by shaka please??

**Comment by joeyparrish** [comment]
As far as I know, txt is not a web standard for subtitles.

SRT predates WebVTT, and VTT seems to be derived from SRT.  SRT, however, has no standard character set or header, whereas WebVTT is always in UTF-8 and has a header.

So it would not be possible to support SRT without additional character set info and conversion routines.  If you want to support SRT, you might be able to write a text parsing plugin for that, but my guess is that it would be much easier to convert your subs to VTT on the backend.

As for download, you can store content in a database for offline playback, but it's not the same as downloading the files to your filesystem.  In general, web pages don't have access to your filesystem for playback.  (At least not through standard APIs across browsers.)

We have an API for offline storage and playback, with a fairly detailed tutorial here:

https://shaka-player-demo.appspot.com/docs/api/tutorial-offline.html

Now that your original questions have been resolved (locally hosting content, plus subtitles), may we close this ticket?  Please feel free to open a new one for further help with offline or for other issues.  Thanks!

**Comment by shabab11** [comment]
@joeyparrish thank you so much for your help and i am sorry for not creating a new issue..... I will create a new issue for rest of my queries.... Thank you once again.

**Comment by joeyparrish** [comment]
No problem.  I'm glad we could help.
