### ISSUE TITLE
Problems playing a LIVE DASH with multiperiod

### ISSUE THREAD

**Issue by mimse** [google/shaka-player#1646]
https://shaka-player-demo.appspot.com/demo/#asset=https://moln.edgeware.tv/__cl/cg:ibc/__c/ibc2018/__op/default/__f/Manifest.mpd;lang=en-GB;build=uncompiled

**What browser and OS are you using?**:
Chrome 70 on macOS Mojave

**What did you expect to happen?**
Playing the LIVE stream without problems

**What actually happened?**
Starts, but stopped after a short while

Console shows this

![image](https://user-images.githubusercontent.com/1250254/47708052-894d8c80-dc2d-11e8-8dcc-08e25f203f5e.png)

Some feedback on why this is happing would be appreciated.

Thanks in advance.

**Comment by theodab** [comment]
I tried out that link, but I was getting CORS errors. If you control this asset, could you set up an 'Access-Control-Allow-Origin' header?

**Comment by mimse** [comment]
Hi @theodab the stream is protected by IP. If you can provide me with your external IP address I can get it unblocked.

**Comment by theodab** [comment]
Ok, I sent it to the email address you have listed in your GitHub profile.

**Comment by mimse** [comment]
Hi, @theodab your subnet should be unblocked now.

**Comment by theodab** [comment]
Looking at your manifests, the `SegmentTemplate` tags don't include a `startNumber` attribute. Consequently, Shaka Player doesn't know how to merge the old manifest and the new manifest together.

**Comment by mimse** [comment]
Hi, @theodab Thank you for looking at this. I´ll take your feedback back to my streaming team.

**Comment by TobbeEdgeware** [comment]
@theodab I think there is some confusion here about the type of manifest.

SegmentTimeline can be used with $Time$ or $Number$.
In this case, $Time$ is used and startNumber is not relevant at all.
In the case of $Number$, the MPD needs a startNumber attribute in the SegmentTemplate.

The difference can be seen on DASH-IF dash-live-source-simulator, where I just added the $Number$ version on the dev version.

$Time$: https://livesim.dashif.org/livesim/segtimeline_1/testpic_2s/Manifest.mpd
$Number$: https://livesim.dashif.org/livesim-dev/segtimelinenr_1/testpic_2s/Manifest.mpd

Adding number is one way to solve this issue, but Shaka-player should also work with this URL for $Time$.

In fact, we have been running this content,

https://moln.edgeware.tv/__cl/cg:ibc/__c/ibc2018/__op/default/__f/Manifest.mp

with Shaka-player during the full IBC show in September, and I have a compiled version that still works fine.

However, it does not work well with with the 2.3-master version, 2.4-master or 2.5.0-beta.

It is an assert in segment_index.js on line 169 (v2.5.0-beta) that fires

 goog.asserts.assert(r2.endTime > r1.endTime &&
            i == this.references_.length - 1 &&
            j == references.length - 1,
            'This should be an update of the last segment in a period'); 

The URL is IP-address blocked, but I'd be happy to open it up if you want to investigate this further. I can also provide a link to the compiled shaka-player that works.

**Comment by TobbeEdgeware** [comment]
All of the sudden things are working in 2.5.0-beta in Chrome 70 an in Safari 12.0.1 on my Mac running High Sierra. The content now plays nicely for 10 minutes which is about 20 period boundaries. I have not touched the source, nor the Shaka-player code.

So it seems that something is unstable, but I don't know what. I saw a similar behavior a couple of days ago as our canned demo with this source worked on one Mac, but not another, although having the same Chrome and OS versions.

Maybe the mapping between adaptationSets or Representations between the periods can be flawed somehow?

**Comment by theodab** [comment]
I can look into adding support for numbering segments by time, if number isn't provided.

Though things suddenly working is a little suspicious. I'm not sure why it would? Unless we have suddenly started fitting the segments, but we shouldn't do that for dynamic manifests.

**Comment by TheModMaker** [comment]
When I notice the errors, the `Period@start` has changed.  We don't support this case and it is now against the DASH IOP guidelines.  We also support missing `startNumber` when using $Time$.

**Comment by TobbeEdgeware** [comment]
OK. I'll look into if the Period@start changes. It should not!  It may be because we create the Period with a SCTE-35 ad marker as early as possible in order to get minimal delay. This means that we create it when we know at what time we close the old period, but we do not yet have a segment in the new Period, which is thus empty. This is something that is not yet allowed in DASH but considered a bug by the editor.

**Comment by TobbeEdgeware** [comment]
The **M**anifest.mpd is a bad source with one period which is changing Period@start.

The proper URL ends with **m**anifest.mpd (lower **m**):
 https://moln.edgeware.tv/__cl/cg:ibc/__c/ibc2018/__op/default/__f/manifest.mpd

The latter produces periods like

         <Period start="PT1541685905S" id="p_0_385421476" duration="PT40S">
         <Period start="PT1541685945S" id="p_0_385421486">

while the Manifest.mpd has only the latest period start and with non-changing id="p_0_0" which is obviously wrong: 

         <Period start="PT1541685945S" id="p_0_0">

The **m**anifest.mpd URL plays nicely in Chrome 70 with Shaka-player v2.5.0-beta.

**Comment by ismena** [comment]
@TobbeEdgeware Glad to hear! Does this mean we can close the issue, or is there something else we can help with?

**Comment by mimse** [comment]
@ismena If no one else has something to add, you can close the issue. Thank you all for the investigation into this issue.

**Comment by TobbeEdgeware** [comment]
@ismena I think you can close this. Thanks for your engagement.
