### ISSUE TITLE
Shaka Player in Chrome does not load the keys received from the ClearKey server

### ISSUE THREAD

**Issue by robertoviola** [google/shaka-player#1647]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:
YES
**What version of Shaka Player are you using?**:
My custom player based on 2.4
**Can you reproduce the issue with our latest release version?**:
My custom player is based on the last version 
**Can you reproduce the issue with the latest code from `master`?**:
As above
**Are you using the demo app or your own custom app?**:
My custom app
**If custom app, can you reproduce the issue using our demo app?**:
I can't, I added special headers in the resquests/responses that the demo app does not handle.
**What browser and OS are you using?**:
Firefox and Chrome on Ubuntu OS 16.04
**What are the manifest and license server URIs?**:
My manifest generated through Shaka Packager for ClearKey encryption.
[Film_MultipleKey.mpd.zip](https://github.com/google/shaka-player/files/2533888/Film_MultipleKey.mpd.zip)
**What did you do?**
Load the manifest and play the content.
**What did you expect to happen?**
Play the content.
**What actually happened?**
Firefox receives decryption keys from the ClearKey server and starts playing the content, while Google receives the same keys but shows the errors: **Failed to execute 'update' on MediaKeySession: Invalid response** and **DecryptingDemuxerStream: no key for key ID 5AB8EDD5ACC531C770E3AAC8BC054BF0; will resume decrypting after new usable key is available**

**Both Firefox and Chrome receive the keys:**
![screenshot from 2018-10-30 17-32-37](https://user-images.githubusercontent.com/19425348/47783060-1c57f680-dd02-11e8-8d05-ac7da956b315.png)

**Firefox works, while Chrome shows errors:**
![screenshot from 2018-10-31 11-43-46](https://user-images.githubusercontent.com/19425348/47783177-56c19380-dd02-11e8-9c56-fa19ed435fc8.png)
![screenshot from 2018-10-31 11-44-07](https://user-images.githubusercontent.com/19425348/47783178-575a2a00-dd02-11e8-9b51-1dac5a10e7b7.png)

**Comment by theodab** [comment]
I can't diagnose this problem without a way to reproduce it. In your case, that would be the custom app, or at least details on the headers and URIs you can use to reproduce the problem. You can send it to <shaka-player-issues@google.com> instead, if you don't want that to be public information.

**Comment by deutschtang** [comment]
From the picture, key is not right encoded, the key need be base64url, so in the "k" or "kid", it should contain "/"

**Comment by theodab** [comment]
Could you provide the content? And the license response in text form, also; I transcribed it by hand from your screenshot but I think I made a typo or something.

**Comment by robertoviola** [comment]
I already found the solution.
The problem was due to Google Chrome which employs "-" and "_" as character 62 and 63 for base64 encoding instead of using "+" and "/" as defined by standard base64:
![image](https://user-images.githubusercontent.com/19425348/47995731-869fdb00-e0f6-11e8-87f8-c752398cb5f6.png)
On the contrary, Firefox is able to work with both "versions" of base64 encoding, this is why it was already working. I just replaced the two characters inside the encoded string and now it correctly works on Chorme, too.

**Comment by joeyparrish** [comment]
The use of the URL-safe variant of Base64 is mandated by the EME spec.  Firefox's decision to be flexible and support both variants is nice, but not required by the spec.  See section 9.1.4 of EME ("Clear Key > License Format"): https://www.w3.org/TR/encrypted-media/#clear-key-license-format

> ### 9.1.4 License Format
> This section describes the format of the license to be provided via the response parameter of the update() method.
> 
> The format is a JSON Web Key (JWK) Set containing representation of the symmetric key to be used for decryption, as defined in the JSON Web Key (JWK) specification [RFC7517].
> 
> For each JWK in the set, the parameter values are as follows:
> 
> * "kty" (key type)
> * "oct" (octet sequence)
> * "k" (key value)
> * * The **base64url encoding** of the octet sequence containing the symmetric key value
> * "kid" (key ID)
> * * The **base64url encoding** of the octet sequence containing the key ID value
