### ISSUE TITLE
Html Form pass values to Shakaplayer script

### ISSUE THREAD

**Issue by weshamoh** [google/shaka-player#1648]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:
yes
**What version of Shaka Player are you using?**:
2.4
**Can you reproduce the issue with our latest release version?**:

**Can you reproduce the issue with the latest code from `master`?**:
n/d
**Are you using the demo app or your own custom app?**:
demo
**If custom app, can you reproduce the issue using our demo app?**:
cordova
**What browser and OS are you using?**:
android
**What are the manifest and license server URIs?**:

**What did you do?**
i have managed to make cordova app,i want toreplace this 
// myapp.js
var manifestUri =
    'https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd';
//
to this
// myapp.js
var manifestUri = document.getElementById('myvideo').value;
//
my form 
<form name="parameters" method="GET" action="movie.html" target="_parent"><input type="text" id="myvideo"value="//storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd">
<input type="submit"></form>

**What did you expect to happen?**

i expect if i pass parameter from form.html  to movie.html the id values should pass to myapp.js
and play video.
**What actually happened?**
not working  can someone help me pass one variable of form.html to movie.html
Thanks

**Comment by weshamoh** [comment]
Thanks @joeyparrish yes i will ,  really appreciate for  kind of work your doing.Thank you.

**Comment by joeyparrish** [comment]
No problem.  Good luck with your project!
