### ISSUE TITLE
error 7002,how do i fix it?no video element,

### ISSUE THREAD

**Issue by BlessingD** [google/shaka-player#1649]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:

**What version of Shaka Player are you using?**:

**Can you reproduce the issue with our latest release version?**:

**Can you reproduce the issue with the latest code from `master`?**:

**Are you using the demo app or your own custom app?**:

**If custom app, can you reproduce the issue using our demo app?**:

**What browser and OS are you using?**:

**What are the manifest and license server URIs?**:

**What did you do?**

**What did you expect to happen?**

**What actually happened?**

**Comment by ismena** [comment]
Hi @BlessingD 
Could you post a snippet of your code when you're creating a new shaka.Player object?
Are you calling Player.attach() anywhere?

**Comment by BlessingD** [comment]
No I’m not calling it, where do I call it? And what’s the syntax?

**Comment by ismena** [comment]
We really need to see your code to help identify the problem.

In the mean time, if you haven't already, please take a look at our [basic usage tutorial](https://shaka-player-demo.appspot.com/docs/api/tutorial-basic-usage.html) and see if that helps.

**Comment by BlessingD** [comment]
Hi,please find attached, a snippet of my offlinedownload.js which is
basically exactly as your myapp.js then also a snippet of my console in
chrome which shows the error,which says..(uncaught in promise...).May you
also elaborate on the manifest Uri,what is that dash.mpd file? Basically i
have a system where users can login and watch educational content. I am
using the shaka player to cater for downloads for offline viewing.,Also
registering a service worker to cache assets for offline experience.


I do apologize as I am a bit of a rookie, lol.

regards

Blessing

**Comment by joeyparrish** [comment]
When we refer to manifests, you should understand that Shaka Player is for adaptive bitrate streaming.  In ABR streaming, the player can switch between various alternative formats on-the-fly.  For example, the player can adapt to the network bandwidth of the client and select the ideal resolution for your internet connection.

As opposed to a single MP4 or WebM file, this ABR streaming requires a format like DASH or HLS, which uses a manifest.  A manifest is a file that contains metadata for several alternative media files.  For example, English, Russian, or Chinese audio, or French, German, or Welsh subtitles, or different resolutions of video.

If you need guidance on creating DASH or HLS content for streaming/offline viewing in Shaka Player, may I recommend our sister project, Shaka Packager: https://github.com/google/shaka-packager  The Packager, when combined with something like ffmpeg to create different resolutions/bitrates, can be used to create DASH or HLS content and the manifests needed by the player.

@BlessingD, if you're still interested after all that, can you please try again with the attachment of your source?  We don't see anything attached to your last post.  Thanks!

**Comment by BlessingD** [comment]
![code-shaka](https://user-images.githubusercontent.com/35054400/48034555-935d1700-e168-11e8-94fb-8d655b40d0e0.PNG)
![chrome-shaka](https://user-images.githubusercontent.com/35054400/48034575-a40d8d00-e168-11e8-873d-92560ce0628b.PNG)

**Comment by BlessingD** [comment]
Hi, I have 2 snippets above as mentioned in my previous email.

**Comment by joeyparrish** [comment]
Here are the docs for error 7002:  https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html#value:7002

name | value | type | description
-- | -- | -- | --
NO_VIDEO_ELEMENT | 7002 | number | The call to Player.load() failed because the Player does not have a video element. The video element must either be provided to the constructor or to Player.attach() before Player.load() is called.

So when you call `player.load()`, the `Player` instance must have a `<video>` element associated with it.  You do this either in the `Player` constructor or by calling `player.attach(video)`.  For example:

```js
const video = document.getElementById('my-video-element');
const player = new shaka.Player(video);
//  ... some time later ...
player.load(someManifestUri);
```

Or:

```js
const player = new shaka.Player();
//  ... some time later ...
const video = document.getElementById('my-video-element');
player.attach(video);
//  ... some time later ...
player.load(someManifestUri);
```

Does this help?

**Comment by vaage** [comment]
Just to add onto what @joeyparrish commented. Based on the current state of the code the second option for attaching to the video element is recommended. However to add something that is missing from the code snippet, keep in mind that both attach and load are async.

```
const player = new shaka.Player();

//  ... some time later ...
const video = document.getElementById('my-video-element');
await player.attach(video);

//  ... some time later ...
await player.load(someManifestUri);

**Comment by BlessingD** [comment]
thanks guys! really helped a lot. just one more question,how do i fix these invalid config errors
![errors](https://user-images.githubusercontent.com/35054400/48048274-a5a87680-e1a3-11e8-9fdc-1f505217674b.PNG)

**Comment by vaage** [comment]
@BlessingD are you configuring the player yourself? If so, could you post the configuration you are passing the player?
