### ISSUE TITLE
Negative PlaybackRate past the beginning of the buffer doesn't work.

### ISSUE THREAD

**Issue by sanbornhnewyyz** [google/shaka-player#165]
Another inconsistency between negative and >1 playback rates is that it will not go past the beginning of the buffer. If you start playback somewhere in the middle of the video and start playing for some time and then try to go back with playbackRate = <1 it will play in reverse up to the point of the beginning of the buffer. And then it will just pause. If you go forward with a playbackRate = >1 then it will buffer new content if you go past the end of the buffered content. Is there a plan to update negative playbackRates to allow for going past the beginning of the buffer?

**Comment by joeyparrish** [comment]
I can't tell from the title what the issue is.  Is this a bug or a feature request?  Can you please provide some details in the description?

**Comment by sanbornhnewyyz** [comment]
Yup, sorry. I accidentally hit create before I had added all the info

**Comment by tdrews** [comment]
Currently, this is by-design, but I suppose we could buffer backwards.

**Comment by joeyparrish** [comment]
@sanbornhnewyyz Not sure I completely understand.  To clarify, by "beginning of the buffer", do you mean the beginning of the buffered region?  As opposed to the beginning of the seek range (often 0s)?

For example, times 60s to 70s are in buffer, and we start rewinding.  Are you saying that in this case, you can't rewind to anything earlier than 60s?

**Comment by sanbornhnewyyz** [comment]
Yes. Video starts playing at 60s because we setPlaybackStartTime to 60. Then if you try to rewind it just goes into a paused state at 60s (which is the beginning of the buffered region) and doesn't go into the time period 59s and less.

**Comment by sanbornhnewyyz** [comment]
To me it seems like as a user the expected behaviour would be to keep going backwards past the beginning of the buffered area but if this is as designed I'm wondering what the reason is for implementing it the way it is now.

**Comment by joeyparrish** [comment]
@sanbornhnewyyz I see what you mean.  We used to have that behavior, but on closer inspection, this was lost in a refactor.  We will consider it a regression, but I don't have a timeline for the fix right now.  Stay tuned.
