### ISSUE TITLE
[Question] - What is shaka-player-embedded?

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#1650]
I found the repo: https://github.com/google/shaka-player-embedded

What is it?

**Comment by TheModMaker** [comment]
I think we created the project today, so you found that fast.

It is a new project to give the features of Shaka Player to native apps (i.e. iOS).  This will be a Framework that allows an iOS app to play streaming media the same as the browser.  It will have a similar looking API as JavaScript and it will be just as easy to use.  You will be able to load a manifest and play the video/audio without any work in your app.

**Comment by joeyparrish** [comment]
Coming soon!  ;-)

**Comment by ismena** [comment]
Case closed! Congrats to the attentive detectives :)
