### ISSUE TITLE
Widevine offline store failed

### ISSUE THREAD

**Issue by sridhard** [google/shaka-player#1653]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:
Yes

**What version of Shaka Player are you using?**:
Demo hosted version

**Can you reproduce the issue with our latest release version?**:
yes

**Can you reproduce the issue with the latest code from `master`?**:
yes

**Are you using the demo app or your own custom app?**:
Demoapp

**If custom app, can you reproduce the issue using our demo app?**:

**What browser and OS are you using?**:
Chrome, Mac

**What are the manifest and license server URIs?**:
Mainfest: https://s3-ap-southeast-1.amazonaws.com/learnyst/testfolder/video/dash1/h264.mpd

license: https://wv.service.expressplay.com/hms/wv/rights/?ExpressPlayToken=BAAAAA2dKcoAAABg82HP71W03Swkp5STJq5Xkbp77qK1tdSFM6Ka_0S5Nq6MhgSOtGyixPrv-DrbKkRMr-MNQB9ZaBmqnSL6EKu1dW9AxJtn1R0jl1v2_-lqatFGtvl1JIS49Zlwv3z0EiA_-rmaTlf0m-dAIjg7DvGm6uKqBiA

**What did you do?**
When I play the above manifest with the above license url it plays successfully.
When I try to store the content offline I am getting the below error

Shaka Error DRM.LICENSE_REQUEST_FAILED (shaka.util.Error { "severity": 2, "category": 1, "code": 1001, "data": [ "https://wv.service.expressplay.com/hms/wv/rights/?ExpressPlayToken=BAAAAA2dKcoAAABg82HP71W03Swkp5STJq5Xkbp77qK1tdSFM6Ka_0S5Nq6MhgSOtGyixPrv-DrbKkRMr-MNQB9ZaBmqnSL6EKu1dW9AxJtn1R0jl1v2_-lqatFGtvl1JIS49Zlwv3z0EiA_-rmaTlf0m-dAIjg7DvGm6uKqBiA", 403, "{\"error\":{\"message\":\"[-7008] Failed to generate Widevine license: INTERNAL_ERROR\",\"code\":-7008}}", { "content-type": "application/json" }, 2 ], "handled": false, "message": "Shaka Error NETWORK.BAD_HTTP_STATUS (https://wv.service.expressplay.com/hms/wv/rights/?ExpressPlayToken=BAAAAA2dKcoAAABg82HP71W03Swkp5STJq5Xkbp77qK1tdSFM6Ka_0S5Nq6MhgSOtGyixPrv-DrbKkRMr-MNQB9ZaBmqnSL6EKu1dW9AxJtn1R0jl1v2_-lqatFGtvl1JIS49Zlwv3z0EiA_-rmaTlf0m-dAIjg7DvGm6uKqBiA,403,{\"error\":{\"message\":\"[-7008] Failed to generate Widevine license: INTERNAL_ERROR\",\"code\":-7008}},[object Object],2)", "stack": "Error: Shaka Error NETWORK.BAD_HTTP_STATUS (https://wv.service.expressplay.com/hms/wv/rights/?ExpressPlayToken=BAAAAA2dKcoAAABg82HP71W03Swkp5STJq5Xkbp77qK1tdSFM6Ka_0S5Nq6MhgSOtGyixPrv-DrbKkRMr-MNQB9ZaBmqnSL6EKu1dW9AxJtn1R0jl1v2_-lqatFGtvl1JIS49Zlwv3z0EiA_-rmaTlf0m-dAIjg7DvGm6uKqBiA,403,{\"error\":{\"message\":\"[-7008] Failed to generate Widevine license: INTERNAL_ERROR\",\"code\":-7008}},[object Object],2)\n at new shaka.util.Error (https://shaka-player-demo.appspot.com/lib/util/error.js:89:13)\n at Object.shaka.net.HttpPluginUtils.makeResponse (https://shaka-player-demo.appspot.com/lib/net/http_plugin_utils.js:66:11)\n at Function.shaka.net.HttpFetchPlugin.request_ (https://shaka-player-demo.appspot.com/lib/net/http_fetch_plugin.js:134:36)" }) 

**What did you expect to happen?**
Offline store should be success

**What actually happened?**
Offline store failed with error

**Comment by TheModMaker** [comment]
Your license server rejected the license request with a 403 error giving us `{"error":{"message":"[-7008] Failed to generate Widevine license: INTERNAL_ERROR","code":-7008}}` as response text.  Chances are your policy settings don't allow offline storage or the token is invalid.

From the [documentation](https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html#value:6007), the data[0] field of the LICENSE_REQUEST_FAILED error is the internal error that caused the failure.  In this case it is a BAD_HTTP_STATUS, whose [documentation](https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html#value:1001) says data[1] is the HTTP response code and data[2] is the response text.

**Comment by sridhard** [comment]
ok..thanks
