### ISSUE TITLE
[app] split videos into chapters

### ISSUE THREAD

**Issue by shabab11** [google/shaka-player#1655]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**: 
yes

**What version of Shaka Player are you using?**:
2.3

**Can you reproduce the issue with our latest release version?**:
yes

**Can you reproduce the issue with the latest code from `master`?**:

**Are you using the demo app or your own custom app?**:
demo

**If custom app, can you reproduce the issue using our demo app?**:

**What browser and OS are you using?**:
chrome, windows 10

**What are the manifest and license server URIs?**:

**What did you do?**
I have added download feature to my video in shaka player, I tried to split my videos into sections I mean as we see in youtube on streaming line there is some red or yellow dot after which adds play automatically and in video description tried to provide link within the video after clicking on the link that particular part of video should play. But it didn't work in my case.

**What did you expect to happen?**
I expect my video to be played in section separated by yellow or red dots on streaming line and i should be able to play only that part of video whose link is provided under video description like video chapters.

**What actually happened?**
unable to add this feature.

**Comment by ismena** [comment]
Hi! I'm having trouble understanding your use case. Could you help me out?

Are the chapters represented in the manifest in any way (like one DASH period per chapter or something like that?)

**Comment by shabab11** [comment]
No they are not.
I want to put checkpoints on stream/buffer line and I want to create links to those checkpoints so that when user click that link he can start watching the video from that particular checkpoint on the streaming line.

**Comment by TheModMaker** [comment]
This seems like something you would do in your app.  You can just use `player.load(url, startTime)` to load at a specific time.  So when they click that link, your app will load at that start time.  You can use `video.currentTime` to determine when the current time is to set the checkpoint, or you could pass it from your server.  Note that in a live stream, the `video.currentTime` is (usually) equal to the time since the live stream started; so if the live stream has been going for an hour, you would set the time to 3600 (in seconds).

**Comment by shabab11** [comment]
Thanks @TheModMaker  hope this will work.......will get back to you for further info if needed.

**Comment by shabab11** [comment]
@TheModMaker ..........Thank you........ I am able to add and play chapters/checkpoint. we can close this issue now.
