### ISSUE TITLE
[CAF] [cast.framework.media.ShakaPlayer] category: 6 code: 6006

### ISSUE THREAD

**Issue by jvjvjv** [google/shaka-player#1657]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:

**What version of Shaka Player are you using?**: 
Looks like version 2.4.0, which is packaged with the current version of the Google Cast CAF Receiver

    [  0.009s] [cast.receiver.CastReceiverManager] Version: 2.0.0.0073
    [cast.framework.Application] CAF Recever Version: 3.0.0033

**Can you reproduce the issue with our latest release version?**:
To be honest, I have not tried. I'm trying to build a Google Cast receiver and it's using Shaka.

**Can you reproduce the issue with the latest code from `master`?**:
I have not tried.

**Are you using the demo app or your own custom app?**:
I am using the CaseHelloVideo-Chrome app and the basic and custom Cast CAF receiver with the DRM code added.

**If custom app, can you reproduce the issue using our demo app?**:
Yes. 

**What browser and OS are you using?**:
I was using Android 8.1 in a mobile app, and Chrome 70 on macOS Mojave.

**What are the manifest and license server URIs?**:
They will be emailed to shaka-player-issues@google.com

**What did you do?**
I have created a custom receiver app to play Widevine-encrypted movies through Azure Media Services. I have to add a Bearer Token which comes from an in-house API to the license acquisition call. From my understanding, the Shaka Player will get all of the required information from the manifest. I even build in the actual License URL because when I do not, I receve a `6012` error. 

    const context = cast.framework.CastReceiverContext.getInstance();
    const playerManager = context.getPlayerManager();
    let playbackConfig = Object.assign(new cast.framework.PlaybackConfig(), 
      playerManager.getPlaybackConfig());

    let bearerToken = "";

    // Set up license acquisition
    // In the below example, <space> is of course my media service,
    // and <key> is the key that is listed in the DASH manifest.
    playbackConfig.licenseUrl = 
      "https://<space>.keydelivery.mediaservices.windows.net/Widevine/?kid=<key>";

    playerManager.setMessageInterceptor(cast.framework.messages.MessageType.LOAD, (request) => {
      if (request.media.customData && request.media.customData.bearerToken) {
        bearerToken = request.media.customData.bearerToken;
      }
      return request;  
    });

    context.start({playbackConfig: playbackConfig});

So I would launch the receiver app from the HelloVideo Chrome app, and then load the custom URL provided.

**What did you expect to happen?**
At some point, the player calls the makes a request to the License Acquisition URL, and at this point I would inject the bearer token.

Within the cast app's code, I would place a `playbackConfig.licenseRequestHandler = request => { console.log("Hey! I'm calling you!"); }` and even if the request fails, I'd expect to see this in the debug console.

**What actually happened?**
Both with and without the license request handler, I would wait a bunch of seconds, and then see `[ 47.058s] [cast.framework.media.ShakaPlayer] category: 6 code: 6006` appear in the console.

**Comment by joeyparrish** [comment]
I'm sorry, but my team doesn't directly support CAF.  CAF uses Shaka Player, but we are not responsible for the API or features exposed by CAF.  I will reach out to the CAF team today and see if they are able to help you, either in this forum, or in some other forum.  Thank you for your patience.

**Comment by joeyparrish** [comment]
Hi @jvjvjv, I just had a talk with the Cast team.  For support on issues related to the Cast SDK and CAF, they asked that you please reach out to that team directly via one of the channels described here: https://developers.google.com/cast/docs/support

**Comment by joeyparrish** [comment]
Since there's nothing else I can do to directly support you on this, I'll go ahead and close this issue.  But please feel free to reach out to us in the future for any issues with direct usage of Shaka Player.  Thanks!

**Comment by flixfling** [comment]
Thanks for everything, Joey.

**Comment by jvjvjv** [comment]
Thanks for everything, Joey. I've logged this issue in Google's Issue Tracker.
