### ISSUE TITLE
Log level does not change the output

### ISSUE THREAD

**Issue by chavoosh** [google/shaka-player#1659]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**: Yes

**What version of Shaka Player are you using?**:  v2.5

**Can you reproduce the issue with our latest release version?**: Yes

**Can you reproduce the issue with the latest code from `master`?**: Yes

**Are you using the demo app or your own custom app?**: Demo

**If custom app, can you reproduce the issue using our demo app?**: --

**What browser and OS are you using?**: Chrome | Ubuntu 18.04

**What are the manifest and license server URIs?**: --

**What did you do?** Tried different log levels

**What did you expect to happen?** Different outputs

**What actually happened?** Exactly the same outputs

**Comment by joeyparrish** [comment]
Can you please provide more details?

Changing the log level doesn't inherently change the logs that happen.  It changes which logs are shown.  So, for example, you may not see any difference between log level info and log level debug if your actions didn't trigger any debug logs.  Or if you reduce the log level, you'll never get **more** logs than you did with a higher level.

Can you tell us what actions you took in the demo, and what log levels you tried?

**Comment by chavoosh** [comment]
Thanks for the reply, but it did not solve the problem.
