### ISSUE TITLE
Live stream doesn't start on Edge on first try.

### ISSUE THREAD

**Issue by adgllorente** [google/shaka-player#1661]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:

Yes. This issue #1281 seemed similar but I've applied the fix and it hasn't worked.

**What version of Shaka Player are you using?**:

2.4.5

**Can you reproduce the issue with our latest release version?**:

Yes.

**Can you reproduce the issue with the latest code from `master`?**:

Not tried.

**Are you using the demo app or your own custom app?**:

A custom demo app just adding a custom header for DRM request.

**If custom app, can you reproduce the issue using our demo app?**:

Yes.

**What browser and OS are you using?**:

Windows 10 / Edge 42.17134.1.0

**What are the manifest and license server URIs?**:

Manifest: https://bridge-to-cert.cdnprepro.telefonica.com/_89/live/disk01/CINEMA/DASH_CINEMA_HD/CINEMA.mpd
DRM Issuer: https://msplayreadydrm.labs.gvp.telefonica.com/rightsmanager.asmx

**What did you do?**

First, we should configure shaka-player with a new request filter to add two custom headers to the License request:

```
  player.getNetworkingEngine().registerRequestFilter(function (type, request) {
    if (type == shaka.net.NetworkingEngine.RequestType.LICENSE) {
      request.headers = {
        'content-type': 'text/xml',
        'x-authentication': 'AU_ZGAE6U_ULGyONgCgYVX238wZ1hKH_7pHaqdUB8PPFveH4J8dvH8W4qNlMN-AE8sle_gRNaO1ka49Li5GnFdUn3THgeRMEDRO0QZy_womUMUH-E0neFowUNh6PMLim4AkFvNVEHWHtixNSM7ChsgK8tqOKvTA80vnVG6z5MQfcvbVYJKtBmgYczJvsmJM4mEBi1I0XpPRliTiC_z-RrU5mjAQn9D9soHoBeQIfwnaW2D7svsT3U',
      };
    }
  });
```

Then, I launch the playback in Edge.

**What did you expect to happen?**

Playback should start like in Chrome or Firefox.

**What actually happened?**

Playback doesn't start but Manifest are requested several times. If you stop the player and start again, playback is played properly.

**Comment by joeyparrish** [comment]
I was somewhat hindered in debugging by this Edge bug: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/18153935/

But I have worked around that, and I am now looking into this playback issue.

**Comment by joeyparrish** [comment]
With your request filter installed, I'm able to test your content.

I tested several times in a row and playback did not begin.  I could click the play button manually, though, and get playback.

Then I enabled the "jump large gaps" checkbox and reloaded.  I tested several more times and playback started automatically.

I then disabled that checkbox and reloaded.  The next several times I tested, playback started automatically.

I'm not sure what's going on, but at this point, I'm assuming it's an autoplay issue.  Can you confirm whether or not the play button works for you when you are in this stuck state?

**Comment by joeyparrish** [comment]
Thanks.  We'll keeping working on it.

**Comment by joeyparrish** [comment]
I'm unable to reproduce the issue at all today with the latest code.  About 10 times in a row, the stream started automatically.

I did notice that the load latency is fairly high for this content, about 8-12 seconds.

Some questions for you, @adgllorente, to help drive this forward:

1. Can you reproduce the issue with the latest Shaka Player code from the `master` branch?  (It's possible that we already fixed something relevant.)
2. Roughly how frequently does the issue reproduce for you?  (1 in 10, 1 in 20, 1 in 298, etc.)
3. How long are you waiting to evaluate whether or not playback begins?  (I had to wait 8-12 seconds each time.  There's a console log that gives the load latency, if you're curious.)
4. If/when the issue does reproduce, do you see a still frame of video?  (If so, this is an autoplay issue in Edge, outside of Shaka Player.)

**Comment by adgllorente** [comment]
It's a weird situation because it doesn't happen always. I've run several tests with the new code from "master" branch and I've found it happens to me every time I open a new "InPrivate tab". These are all the tests I've run and the result obtained.

```
--- Open browser
1. NOK (Play button shown, nothing happened when clicked.)
--- UNLOAD & LOAD
2. OK
--- UNLOAD & LOAD
3. OK
--- UNLOAD & LOAD
4. OK
--- REFRESH
5. OK (8seg waiting)
--- UNLOAD & LOAD
6. OK
--- UNLOAD & LOAD
7. OK
--- New InPrivate tab
8. NOK (Play button shown, nothing happened when clicked.)
--- UNLOAD & LOAD
9. NOK (Play button shown, nothing happened when clicked.)
--- UNLOAD & LOAD
10. OK
--- UNLOAD & LOAD
11. OK (Time to play: 6s.)
--- New InPrivate tab
12. NOK (Play button shown, nothing happened when clicked. I've clicked Pause/Play several times and nothing happened)
--- UNLOAD & LOAD
13. NOK (Play button shown, nothing happened when clicked.)
--- UNLOAD & LOAD
14. OK
--- UNLOAD & LOAD
15. OK
--- UNLOAD & LOAD
16. OK
--- New InPrivate tab
17. NOK
--- UNLOAD & LOAD
18. NOK
--- UNLOAD & LOAD
19. NOK
--- REFRESH 
20. OK
--- REFRESH
21. OK
--- REFRESH
22. OK
```

I've also prepared a video with the bug happening because maybe it gives you more information.

<a href="https://streamable.com/xklvv"><img width="891" alt="shaka-player-test" src="https://user-images.githubusercontent.com/1067480/48768585-acfa7480-ecb9-11e8-8d0e-d8c1e8cfe29e.png"></a>

**Comment by joeyparrish** [comment]
Okay.  I'll try again in Edge's private mode.

**Comment by joeyparrish** [comment]
I can't reproduce in private mode.  I am getting an [error 6007 (LICENSE_REQUEST_FAILED)](https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html#value:6007) that is out of my control.  Your server is rejecting the license request.

I'm getting back an HTTP status 500 with the following body (formatted for your convenience):

```
<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <soap:Body>
    <soap:Fault>
      <faultcode>soap:Server</faultcode>
      <faultstring>Internal service error</faultstring>
      <faultactor>http://msplayreadydrm.labs.gvp.telefonica.com/rightsmanager.asmx</faultactor>
      <detail>
        <Exception>
          <StatusCode>0x8004c600</StatusCode>
          <DebuggingData>Server record locator = f148ccc1-3603-4c8b-a868-c65c280151c2</DebuggingData>
        </Exception>
      </detail>
    </soap:Fault>
  </soap:Body>
</soap:Envelope>
```

**Comment by joeyparrish** [comment]
Oh, and I definitely still have your request filter installed.  I'm using exactly this:

```js
  player.getNetworkingEngine().registerRequestFilter((type, request) => {
    if (type == shaka.net.NetworkingEngine.RequestType.LICENSE) {
      request.headers = {
        'content-type': 'text/xml',
        'x-authentication': 'AU_ZGAE6U_ULGyONgCgYVX238wZ1hKH_7pHaqdUB8PPFveH4J8dvH8W4qNlMN-AE8sle_gRNaO1ka49Li5GnFdUn3THgeRMEDRO0QZy_womUMUH-E0neFowUNh6PMLim4AkFvNVEHWHtixNSM7ChsgK8tqOKvTA80vnVG6z5MQfcvbVYJKtBmgYczJvsmJM4mEBi1I0XpPRliTiC_z-RrU5mjAQn9D9soHoBeQIfwnaW2D7svsT3U',  // eslint-disable-line max-len
      };
    }
  });
```

**Comment by adgllorente** [comment]
My fault, the token has expired, here you have a new one

```
AU_ZGAE6U_leWdjkARXhUbcTAp4HpEpiW6hEFKSE_nPBFMHeQ9-PQwKe8CGldjHbCKQ_4n2HKS5Vdl2z1P2ZYtEOQH_jejpMPsXC6M2edUaz_QJR0-IqnevrjrxImRVsETeqo1Uq-FpwlUeaf87yagX4mmhfuorDvU2iVBuHDWX4onz7Lx3PXfbrh1_f_VaV1kynFwRXWgK8xrvo30jJQq9w3gtoRax75fdLxk_sTwgj8nwVLHz6k
```

I'm sure you already know but you should use it like this:

```
  player.getNetworkingEngine().registerRequestFilter((type, request) => {
    if (type == shaka.net.NetworkingEngine.RequestType.LICENSE) {
      request.headers = {
        'content-type': 'text/xml',
        'x-authentication': 'AU_ZGAE6U_leWdjkARXhUbcTAp4HpEpiW6hEFKSE_nPBFMHeQ9-PQwKe8CGldjHbCKQ_4n2HKS5Vdl2z1P2ZYtEOQH_jejpMPsXC6M2edUaz_QJR0-IqnevrjrxImRVsETeqo1Uq-FpwlUeaf87yagX4mmhfuorDvU2iVBuHDWX4onz7Lx3PXfbrh1_f_VaV1kynFwRXWgK8xrvo30jJQq9w3gtoRax75fdLxk_sTwgj8nwVLHz6k',  // eslint-disable-line max-len
      };
    }
  });
```

**Comment by theodab** [comment]
I looked into this some, but I got a `6007` error also. Has your token expired again?

**Comment by adgllorente** [comment]
I've created a new one with an expiration of a month (Until 03/01/2019)

```
AU_ZGAE6U_DsdIZJkbeFkPHLrlC8nrmCKJhuPwy5OP4wQkxMVGJgy6fgnsD_GNWrlFkgnEfJdz7gET2XXzdDZiJegvFuMSLkTTUsisGRqkdTBLotG8OfpAwgXdEIq7lFvbUyh2J8J6bLmaMaja8DDjbnM_FEmaZRkRggzb1-fY_DoPs0dgnUFSTxzXlKq5iYvXVAjoYPNGe_TocPuawPcRuajd0xp6ycRbxMOlsV3YiaEgIxyslIM
```

**Comment by theodab** [comment]
Thanks for the new key.
I was able to reproduce the problem again, using the code from master. So it definitely does seem to still be a problem.
And then it takes several tries to get it to play, but once it does play it suddenly works fine every time, even after reload. I was able to get it to play without enabling `jumpLargeGaps`, so I don't think it's related to that.

**Comment by adgllorente** [comment]
Have you tried with other kind of streams? Just to confirm it is something related with the browser and not with the stream.

**Comment by theodab** [comment]
Well, all of our livestreams seem to work as expected on Edge. All of the PlayReady-encrypted assets work too.
We don't have any PlayReady-encrypted livestreams in our samples, though. So it's possible that is the root of the problem?
I tried looking for PlayReady-encrypted livestreams to check that, but all I found from Microsoft's PlayReady resources were in SmoothStreaming format. Well, I guess I'll have to keep looking.

**Comment by joeyparrish** [comment]
@adgllorente, can you please provide us with a new key for testing?

**Comment by adgllorente** [comment]
Here you have another one for a month, let me know if it doesn't work

```
AU_ZGAE6U_ZdrfcZYdZLb8IYcWvWOqDdxIECT7Ksn0oc5v2MDwkx5BuYlo6t0kIsqskYerpc97IuWwVebkSCo1lc_Y4Gq4mmVrLdJ4eIvd4EdNG5-0GOnuAJf1zub6z7f7p3A2ZMh57Ib9SH6JRHL-I6C9DLD3aXfjrlura4eOUWDtWhvbkqRyV50vsanxcvgrBiKhpqwgg1w0Wpec_JWYFKyTBgxPzeV0aCDjIE0clSjGda27MnXldpwC_jx4RzrU2toFEsQR
```

**Comment by adgllorente** [comment]
Yep, our QA team was able to reproduce it in a physical Windows machine

**Comment by joeyparrish** [comment]
I was able to reproduce it until just a few minutes ago, both with and without private browsing mode.  Now, two things seems to have changed at the same time:

1. There is a CORS error accessing the license server, so no license was fetched
2. The video plays anyway

I verified that there are no keys available according to the `MediaKeys` API.  So this stream appears to be in the clear.

Questions for you, @adgllorente:

1. Is this an actual encrypted stream?
2. If yes, is it always encrypted, or are there programs in the stream which are not encrypted?
3. Is some other kind of maintenance happening right now that could be interfering with my testing?

**Comment by joeyparrish** [comment]
Also, please let me know what your time zone is so that I can coordinate better with you.  I can be flexible on work hours to help speed up resolution of this issue.

**Comment by adgllorente** [comment]
I've checked with all teams working in the testing environment and they have confirmed me they've been enabling/disabling the DRM issuer these days. I guess that's why you were able to play the stream without a proper license.

I'm currently at GMT+1 but I've been a little occupied these days. Anyway I'm going to give this issue a higher priority in order to give you feedback ASAP.

**Comment by adgllorente** [comment]
I've checked right now and environment is working with DRM and token is still valid, so you should be able to play again.

**Comment by joeyparrish** [comment]
We've had a very hard time reproducing this issue.  Are you still able to reproduce it with the latest updates to Edge & Windows?  Are you able to reproduce the issue with any of the publicly available test content in our demo app?

**Comment by adgllorente** [comment]
I've tried our stream with new shaka-player version from master, Edge 18 and Insider Preview and I'm able to reproduce it.

I've also tried with your live stream named Big Buck Bunny (DASH-IF and Wowza) and they work fine, they don't get frozen during startup.

May it be related with DRM? Do you have another kind of live streams with DRM to test?

**Comment by joeyparrish** [comment]
Can you please try this again on the latest Shaka Player?  I'd also be interested to know if it's still reproducible in the new Chromium-based Edge.  If this is still an issue, will we need an updated auth token to reproduce it?
