### ISSUE TITLE
Javascript's number overflow for timescale 10000000 (PlayReady/SmoothStreaming default)

### ISSUE THREAD

**Issue by agelun** [google/shaka-player#1667]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:
Yes

**What version of Shaka Player are you using?**:
commit 1831ce95e272790c288516f6319f07b70d768a9a

**Can you reproduce the issue with our latest release version?**:
Yes

**Can you reproduce the issue with the latest code from `master`?**:
Yes

**Are you using the demo app or your own custom app?**:
Demo app

**What browser and OS are you using?**:
Chrome, LG WebOS SmartTV, Samsung Tizen SmartTV

**What did you do?**
Trying to play content with timescale = 10,000,000 (10 millions) and chunk template with "$Time$" placeholder. 

It's a "default timescale" for SmoothStreaming and it is required by several legacy TV models (Samsung Tizen 2015, for example). 

The problem is caused by:
1) JS number overflow for SegmentTemplate+SegmentTimeline content
2) _(theoretically – not tested, found in sources)_  error with rounding "seconds * timescale" values for SegmentTemplate (without timeline) content.

**What did you expect to happen?**
Play content normally

**What actually happened?**
Shaka generates invalid chunk name -> 404 from the server.

**Comment by agelun** [comment]
Example fix based on https://github.com/peterolson/BigInteger.js attached.

**Comment by joeyparrish** [comment]
I'm sorry, but we are not going to add a BigInteger library to support extremely large timescales.  This additional dependency would not be optional and would increase the size of Shaka Player by ~20%.

I know this is probably disappointing to hear, but we won't support content that creates Numbers too large to be exact integers in JavaScript (2^53).  Please fix your timescale to something more reasonable.

**Comment by joeyparrish** [comment]
We will update our README and FAQ to document this.  I apologize for the inconvenience.

**Comment by chrisfillmore** [comment]
This may be interesting to all parties: https://github.com/tc39/proposal-bigint
