### ISSUE TITLE
Relative MPD/Location URLs not work.

### ISSUE THREAD

**Issue by agelun** [google/shaka-player#1668]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:
Yes
**What version of Shaka Player are you using?**:
commit 1831ce95e272790c288516f6319f07b70d768a9a

**Can you reproduce the issue with the latest code from `master`?**:
Yes

**Are you using the demo app or your own custom app?**:
Demo app

**What browser and OS are you using?**:
Chrome 

**What did you do?**
Trying to play content with relative URL in Location tag.

**What did you expect to happen?**
Content plays normally.

**What actually happened?**
Shaka's URL using as a base URL for next playlist and chunks requests. Content playback doesn't work.
Relative URLs are not supported in Location tag now – only absolute ones.

**Comment by joeyparrish** [comment]
Hi @agelun.  I see you've already made a fix in your fork: https://github.com/smartlabstv/shaka-player/commit/f0b47d244b0ec9e9b51ed515fe5fe9c4eb56a3c6

Could you please add a unit test in test/dash/ and submit a pull request?  Thanks!

**Comment by joeyparrish** [comment]
Fix cherry-picked for v2.4.6.
