### ISSUE TITLE
Add More Accessible Track-Change Controls

### ISSUE THREAD

**Issue by vaage** [google/shaka-player#1669]
This is an offshoot from #1071.

The request is for more extensive and context-specific controls for getting and setting which tracks are played.

Right now the options for changing tracks is to use the core Tracks API:

- `getVariantTracks`
- `selectVariant`
- `getTextTracks`
- `selectTextTrack`

or use the current set of "other" methods:
- `selectAudioLanguage`
- `selectTextLanguage`
- `getAudioLanguagesAndRoles`
- `getAudioLanguages`
- `getTextLanguagesAndRoles`
- `getTextLanguages`

Right now we don't allow a friendlier way to select variants on anything other than language and role, and how the "search" works is not obviously clear. When someone is looking to pick a variant they could feasibly want to select a variant based on any subset of:

- language
- role(s)
- channel count
- video width
- video height
- video frame rate

We should look at supplying a method to select variants based on these search parameters and make sure that the strictness of the search is clearly communicated.

This all this can be done via the core Tracks API, the new searching methods should not need access to anything other than those methods.

**Comment by joeyparrish** [comment]
Obsoleted by #1339.
