### ISSUE TITLE
Manifest issue with webview

### ISSUE THREAD

**Issue by Amohwesh** [google/shaka-player#1670]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:

**What version of Shaka Player are you using?**:

**Can you reproduce the issue with our latest release version?**:

**Can you reproduce the issue with the latest code from `master`?**:

**Are you using the demo app or your own custom app?**:

**If custom app, can you reproduce the issue using our demo app?**:

**What browser and OS are you using?**:

**What are the manifest and license server URIs?**:

**What did you do?**

**What did you expect to happen?**

**What actually happened?**

**Comment by joeyparrish** [comment]
@Amohwesh, there is no information in this issue.  Your title does not describe the problem, and you left our issue template blank.  Can you please fill in the requested information so that we can reproduce and address your issue?
