### ISSUE TITLE
UI: Add picture-in-picture button

### ISSUE THREAD

**Issue by ismena** [google/shaka-player#1682]

**Comment by joeyparrish** [comment]
We will need to add "picture-in-picture" to our localizations as well.

**Comment by avelad** [comment]
I tested the button on Opera and it does not work.

**Comment by avelad** [comment]
@beaufortfrancois , There are not video when the user clicks on PiP button. The video is remplaced by splash with a text indicating thaht is in PiP but there are not external window with the video. 

Note: In Chrome works perfectly.

**Comment by beaufortfrancois** [comment]
Can you share a screenshot?

**Comment by avelad** [comment]
@beaufortfrancois , you can find the video attached.
[1682.zip](https://github.com/google/shaka-player/files/2663655/1682.zip)

**Comment by beaufortfrancois** [comment]
Thank you @avelad!
Which version of Opera do you use?

**Comment by beaufortfrancois** [comment]
Did you enable some flags?

**Comment by avelad** [comment]
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 OPR/57.0.3098.76 over Ubuntu 18.04

**Comment by avelad** [comment]
I have the default configuration,  I didn't modify any flag on opera://flags

**Comment by ismena** [comment]
I created #1724 to track progress on pip experience on Opera.
@beaufortfrancois could you add updates to it as your conversation with the Opera folks progresses?

**Comment by beaufortfrancois** [comment]
@avelad As you can see at #1724, A stable version of Opera with the Picture-in-Picture fix included was released yesterday: https://blogs.opera.com/desktop/2018/12/opera-57-0-3098-102-stable-update/
