### ISSUE TITLE
Multiple DASH video and Audio only DASH synchronization.

### ISSUE THREAD

**Issue by trustfarm-dev** [google/shaka-player#1690]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:
yes
**What version of Shaka Player are you using?**:
latest 1weeks ago master
**Can you reproduce the issue with our latest release version?**:
yes
**Can you reproduce the issue with the latest code from `master`?**:
yes
**Are you using the demo app or your own custom app?**:
custom app
**If custom app, can you reproduce the issue using our demo app?**:
yes
**What browser and OS are you using?**:
chrome / win10
**What are the manifest and license server URIs?**:

**What did you do?**
multi tile synchronous play  and divided audio only mpd and video mpd synchronisation.

**What did you expect to happen?**

**What actually happened?**

audio is not played and sound not come out.
how to set video sync by external time source?

reference code from https://github.com/Eyevinn/ott-multiview 
and customizing.

**Comment by joeyparrish** [comment]
@trustfarm-dev, we are not the authors of https://github.com/Eyevinn/ott-multiview .  If you need help with ott-multiview, please file issues on that project: https://github.com/Eyevinn/ott-multiview/issues/new

Thanks!
