### ISSUE TITLE
Issues with text during rapid period transitions

### ISSUE THREAD

**Issue by akosogova** [google/shaka-player#1698]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:
Yes

**What version of Shaka Player are you using?**:
2.3.0 - 2.5.0-beta2

**Can you reproduce the issue with our latest release version?**:
Yes

**Can you reproduce the issue with the latest code from master?**:
-

**Are you using the demo app or your own custom app?**:
demo app

**If custom app, can you reproduce the issue using our demo app?**:

**What browser and OS are you using?**:
Google Chrome, Windows 10

**What are the manifest and license server URIs?**:
The manifest with segments: [manifest and segments](https://drive.google.com/open?id=1Qu1lArtXyBJISl4UR2o7hFnPRNioxNQg)

**What did you do?**
We are trying to play multi-period live DASH stream with subtitles.

**What did you expect to happen?**
Subtitles should show after CC button clicked.

**What actually happened?**
When the "CC" button on Shaka player clicked: 
 - subtitles stop to appear for a few seconds after "CC" turned on or did not start at all;
 - for a few seconds later the playback will be stopped for about 10 to 30s then continue to play.

After investigation we found that the problem started from shaka-player version 3.0.0. In this version was added the feature "Do not stream captions until they are shown".

So after turning on the "CC" button in shaka-player versions 2.3.0 and later we get some assertion failures:
![console log - assertion failed](https://user-images.githubusercontent.com/45285977/48939595-60af6e80-ef1d-11e8-86fd-e344c9be3e29.jpg)

We found that the problem is relate to the different video and text period numbers. 
The problem arises when we start to load the text from current period: [lib/player.js#L1935](https://github.com/akosogova/shaka-player/blob/f274e94dc8f4e6810f5b892e88716d90cffe7d5b/lib/player.js#L1935)
Another problem has arisen with the text stream updating after the start of subtitles loading. The period of playheadTime is compared with zero mediaState.resumeAt property:  [lib/media/streaming_engine.js#L1314](https://github.com/akosogova/shaka-player/blob/f274e94dc8f4e6810f5b892e88716d90cffe7d5b/lib/media/streaming_engine.js#L1314)
So we find the period of Text stream for playheadTime but it is less then the period of current Video stream and we get an assertion failure here: [lib/media/streaming_engine.js#L2007](https://github.com/akosogova/shaka-player/blob/f274e94dc8f4e6810f5b892e88716d90cffe7d5b/lib/media/streaming_engine.js#L2007)

**Comment by TheModMaker** [comment]
Can you provide a sample asset that reproduces your error?  The zip file you provided doesn't work (probably since it's live and the segments don't exist).

I also think your PR isn't the correct fix.  The intent is to load the text streams from the current playhead position; if this is close to a Period transition, it should automatically handle a Period transition once it has buffered enough.  I don't think it is a good idea to use the "active" Period to start streaming at because it means that we won't display captions for a while.

**Comment by akosogova** [comment]
This is the link to manifest: https://origin-hkv-silver-01.nebula.video/Content/DASH_dash.wv/Live/channel(58f8e99a-b016-a14c-23fb-0845aa4db62c)/manifest.mpd . Unfortunately it will be working only for 3 days. But if it will not enough to reproduce the problem, I could set it up again.

**Comment by akosogova** [comment]
Thank you for response!

**Comment by joeyparrish** [comment]
Deferring this bug until v2.6, where I believe some planned work on period flattening will solve it.
