### ISSUE TITLE
Cant compile shaka-player

### ISSUE THREAD

**Issue by Kogoruhn** [google/shaka-player#1700]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:
Yes
**What version of Shaka Player are you using?**:
2.5.0-beta2
**Can you reproduce the issue with our latest release version?**:
Yup
**Can you reproduce the issue with the latest code from `master`?**:
**Are you using the demo app or your own custom app?**:
not applicable
**If custom app, can you reproduce the issue using our demo app?**:
**What browser and OS are you using?**:
Windows 7 Professional
**What are the manifest and license server URIs?**:
not applicable
**What did you do?**
try to compile shaka according to https://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html
**What did you expect to happen?**
shaka compiled
**What actually happened?**
error during compilation, in /dist presents only `deps.js, .lintstamp, .htmllintstamp`

I use standard cmd with administrator rights. About a month ago compilation was OK.

![image_2018-11-26_18-32-25](https://user-images.githubusercontent.com/26676714/49024703-28bd5b00-f1ab-11e8-9196-62d740218e7c.png)

**Comment by Kogoruhn** [comment]
Honestly, I try to compile both - with & w/o adm. rights, got same result... Thanks for response!

**Comment by Kogoruhn** [comment]
YAY! Shaka compiled! @TheModMaker U were right!

`build/shakaBuildHelpers.py`:
```
def get_source_base():
  """Returns the absolute path to the source code base."""
  source_base = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
  # In the build files, we use '/' in the paths, however Windows uses '\'.
  # Although Windows supports both, the source mapping will not work with '\'.
  # So we use Linux-style paths for everything.
  return source_base.replace('\\', '/')
```
set return `source_base`. Thats it. And for pass the check in `compiler.by`
```
assert source_base[-1] == '\\', 'Source base format changed!'
```

**Comment by joeyparrish** [comment]
@Kogoruhn, thanks for the feedback!  Please confirm with the change we just released so that we know the official fix works for you, as well.

**Comment by Kogoruhn** [comment]
@joeyparrish 
![shaka2](https://user-images.githubusercontent.com/26676714/49499237-82deb000-f87e-11e8-946a-f34fbd927234.png)

Same error that was in my "repair"... 

in /dist: shaka-player.compiled.debug.js, shaka-player.ui.debug.js (+ .map, .externs)
But anyway, now i got what i want:)
