### ISSUE TITLE
Official support for Xbox One

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#1705]
I have the player running on the Xbox One. I have seen that things related to the Xbox have been answered in the past(eg: https://github.com/google/shaka-player/issues/1395). Are there plans to officially support it?

**Comment by TheModMaker** [comment]
We actually already have an Xbox One device, we just haven't setup automated testing yet.  We have an internal bug to add some kind of test framework to allow us to test it.  If anyone has suggestions on how to run automated tests (through Karma) it would be appreciated.  But it has been low priority; supposedly it is just the Windows 10 Edge browser, but there are likely subtle platform differences.

**Comment by chrisfillmore** [comment]
We would probably also be interested in this.

**Comment by avelad** [comment]
@joeyparrish / @TheModMaker , Could the support be added to the README.md although it is not integrated automatically yet?

**Comment by joeyparrish** [comment]
We don't actually know that everything is still working on XB1, even though it was at one time.  We haven't done any manual test passes on the device in a while, so we can't say we officially support it.

You'll notice that WebOS isn't listed in the README, either, for the same reasons.  Even though you've sent us reports about WebOS and contributed code related to WebOS, it's not one of our official platforms yet.

**Comment by joeyparrish** [comment]
Xbox One will soon become an officially-supported platform.  If anyone is interested to see how, check out this PR for our new test infrastructure tools for Xbox: https://github.com/google/generic-webdriver-server/pull/12

**Comment by avelad** [comment]
@joeyparrish What status is this issue in? Is the Xbox already fully supported? If not, what problems are there?

**Comment by joeyparrish** [comment]
Basically, yes.  I have a couple of test failures for which fixes are in review as of today, but the failures are only due to poorly-written test expectations.  The library is fully working on Xbox One as far as we can tell, and will be tested nightly on Xbox One as soon as these last fixes are merged.

**Comment by joeyparrish** [comment]
And by the time I wrote that message, I already had approvals I hadn't seen yet.  Thanks, @michellezhuogg, for the code review!

It is now official:  We support Xbox One.  :tada:
