### ISSUE TITLE
Live DASH + HLS packaging doesn't match stream content

### ISSUE THREAD

**Issue by BobCu** [google/shaka-player#1717]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:
Yes

**What version of Shaka Player are you using?**:
Git tip

**Can you reproduce the issue with our latest release version?**:
Yes

**Can you reproduce the issue with the latest code from `master`?**:
Yes

**Are you using the demo app or your own custom app?**:
Not sure what you mean by "demo app" or "custom app".

**If custom app, can you reproduce the issue using our demo app?**:
See above.

**What browser and OS are you using?**:
None, yet.  Packager broken!

**What are the manifest and license server URIs?**:

N/A

**What did you do?**
Looped multi-resolution video over udp to packager.

**What did you expect to happen?**
The .m4s segment for each video resolution should have different content and size.

**What actually happened?**
All segments for a given time contained identical content.

I took Big Buck Bunny at 1080p and encoded it at 720p@2Mbps, 480p@1Mbps and 350p@0.5Mbps into a single TS using the following ffmpeg command:

    ffmpeg -i "BBB_1080p.mov" -threads 16 \
        -map 0:a -map 0:v -map 0:v -map 0:v \
        -c:a aac -ac 2 -b:a 128k \
        -force_key_frames "expr:eq(mod(n,300),0)" -max_interleave_delta 0 \
        -x264opts rc-lookahead=300:keyint=600:min-keyint=300 \
        -pix_fmt yuv420p -preset veryslow -tune film -vsync cfr -x264-params "nal-hrd=cbr" \
        -s:v:0 1280x720 -c:v:0 libx264 -b:v:0 5000k -minrate:v:0 2000k -maxrate:v:0 2000k -bufsize:v:0 4000k \
        -s:v:1  854x480 -c:v:1 libx264 -b:v:1 1500k -minrate:v:1 1000k -maxrate:v:1 1000k -bufsize:v:1 2000k \
        -s:v:2  640x360 -c:v:2 libx264 -b:v:2  500k -minrate:v:2  500k -maxrate:v:2  500k -bufsize:v:2 1000k \
        -program program_num=1:title=multi_p30:st=0:st=1:st=2:st=3 \
        -f mpegts "BBB_720p_480p_360p.ts" -y

The resulting file was then looped (with updated timing for each loop) using the following VLC command:

    cvlc BBB_720p_480p_360p.ts --sout udp:127.0.0.1:9876 --repeat --loop --sout-all --sout-keep -quiet

The resulting UDP stream was checked:

    $ packager in=udp://127.0.0.1:9876 --dump_stream_info
    [1130/092630:INFO:demuxer.cc(88)] Demuxer::Run() on file 'udp://127.0.0.1:9876'.
    [1130/092630:INFO:demuxer.cc(160)] Initialize Demuxer for file 'udp://127.0.0.1:9876'.
    
    File "udp://127.0.0.1:9878":
    Found 4 stream(s).
    Stream [0] type: Video
     codec_string: avc1.640032
     time_scale: 90000
     duration: 9223372036854775807 (102481911520608.6 seconds)
     is_encrypted: false
     codec: H264
     width: 1280
     height: 720
     pixel_aspect_ratio: 1:1
     trick_play_factor: 0
     nalu_length_size: 4
    
    Stream [1] type: Video
     codec_string: avc1.64001f
     time_scale: 90000
     duration: 9223372036854775807 (102481911520608.6 seconds)
     is_encrypted: false
     codec: H264
     width: 640
     height: 360
     pixel_aspect_ratio: 1:1
     trick_play_factor: 0
     nalu_length_size: 4
    
    Stream [2] type: Video
     codec_string: avc1.640028
     time_scale: 90000
     duration: 9223372036854775807 (102481911520608.6 seconds)
     is_encrypted: false
     codec: H264
     width: 854
     height: 480
     pixel_aspect_ratio: 1:1
     trick_play_factor: 0
     nalu_length_size: 4
    
    Stream [3] type: Audio
     codec_string: mp4a.40.2
     time_scale: 90000
     duration: 9223372036854775807 (102481911520608.6 seconds)
     is_encrypted: false
     codec: AAC
     sample_bits: 16
     num_channels: 2
     sampling_frequency: 48000
     language:
    
    Packaging completed successfully.

Then the packager was started:

    packager \
    'in=udp://127.0.0.1:9878,stream_selector=3,bandwidth=0,stream=audio,init_segment=audio_init.mp4,segment_template=audio_$Number$.m4s,playlist_name=audio.m3u8,hls_group_id=audio,hls_name=ENGLISH' \
    'in=udp://127.0.0.1:9878,stream_selector=0,bandwidth=2000000,stream=video,init_segment=720p30_init.mp4,segment_template=720p30_$Number$.m4s,playlist_name=720p30.m3u8' \
    'in=udp://127.0.0.1:9878,stream_selector=2,bandwidth=1000000,stream=video,init_segment=480p30_init.mp4,segment_template=480p30_$Number$.m4s,playlist_name=480p30.m3u8' \
    'in=udp://127.0.0.1:9878,stream_selector=1,bandwidth=500000,stream=video,init_segment=360p30_init.    mp4,segment_template=360p30_$Number$.m4s,playlist_name=360p30.m3u8' \
    --hls_master_playlist_output master.m3u8  --hls_playlist_type LIVE \
    --mpd_output manifest.mpd \
    --time_shift_buffer_depth 10 --preserved_segments_outside_live_window 1 --segment_duration 10 --fragment_duration 10

For each time period I expected to see video segment files (.m4s) that doubled in size from small to large.  That's not what happened:  For each time period the files had their expected names but identical content.

Both the 3-resolution file and the looped UDP stream each were viewed with VLC.  The expected resolutions with the expected bitrates were verified to be present and correct.

I've done my best to validate the packager command, but I see nothing obviously wrong with it.

**Comment by joeyparrish** [comment]
This is the bug tracker for Shaka Player.  Please file this on Shaka Packager, which is a separate project: https://github.com/google/shaka-packager/issues/new
