### ISSUE TITLE
UI: broken link in docs

### ISSUE THREAD

**Issue by Kogoruhn** [google/shaka-player#1719]
https://nightly-dot-shaka-player-demo.appspot.com/docs/api/tutorial-ui.html

> See the docs on [UIConfiguration](https://shaka-player-demo.appspot.com/docs/api/shaka.extern.html#.UIConfiguration) for more information

need to be replaced by

> See the docs on [UIConfiguration](https://nightly-dot-shaka-player-demo.appspot.com/docs/api/shaka.extern.html#.UIConfiguration) for more information

**Comment by vaage** [comment]
Just submitted the fix, should be up on the nightly soon.
