### ISSUE TITLE
Amazon Fire TV widevine support in webview

### ISSUE THREAD

**Issue by simhavenkat** [google/shaka-player#1722]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:
Yes
**What version of Shaka Player are you using?**:
Latest
**Can you reproduce the issue with our latest release version?**:
Yes
**Can you reproduce the issue with the latest code from `master`?**:
Yes
**Are you using the demo app or your own custom app?**:
Demo app
**If custom app, can you reproduce the issue using our demo app?**:
NA
**What browser and OS are you using?**:
Fire TV android Web View (firefox)
**What are the manifest and license server URIs?**:
**What did you do?**
Play widevine content
**What did you expect to happen?**
Not sure :)
**What actually happened?**
Shaka Error DRM.REQUESTED_KEY_SYSTEM_CONFIG_UNAVAILABLE ()

It looks like Amazon fire TV does not support Widevine in web view - per this https://forums.developer.amazon.com/questions/46188/will-drm-for-firetv-html5-webapps-be-available-in.html. This is from 2016 and the official documentation doesn't seem to say one way or another for web view. 

Anyone had success playing Widevine on webview on Fire TV? I created a sample app with a web view pointing to the shaka demo app and i got DRM.REQUESTED_KEY_SYSTEM_CONFIG_UNAVAILABLE. Looks like the 2016 comment is still applicable - but looking for confirmation.

**Comment by ismena** [comment]
Hi, 
To the best of our knowledge, the comment you reference is still applicable.

**Comment by simhavenkat** [comment]
Turned out my sample webview app was missing PROTECTED_MEDIA permissions. Setting that fire tv is able to play shaka demo app DRM content.

**Comment by chovy** [comment]
How did you set it?

**Comment by simhavenkat** [comment]
https://stackoverflow.com/questions/49187659/android-webview-drm-content-playback
