### ISSUE TITLE
Picture-in-Picture not working on Opera

### ISSUE THREAD

**Issue by ismena** [google/shaka-player#1724]
This came up in comments to #1682 and seems to be an external (Opera) problem.
Creating this issue to track Pip+Opera experience specifically.

**Comment by beaufortfrancois** [comment]
Opera folks told me it will be fixed in next stable (58).
They're not sure if it will make it to next stable update (57).

For info, Opera internal bug id is DNA-74390. It may be helpful if you contact them so that they know what you're talking about.

**Comment by ismena** [comment]
Awesome, thanks for following up, @beaufortfrancois

**Comment by beaufortfrancois** [comment]
A stable version with the Picture-in-Picture fix included was released yesterday: https://blogs.opera.com/desktop/2018/12/opera-57-0-3098-102-stable-update/.

> 57.0.3098.102 – 2018-12-13 blog post
> - DNA-74033 Crash at BrowserProcessImpl::Unpin()
> - DNA-74077 Crash at base::Value::Value(base::flat_map const&)
> - DNA-74180 [Mac] Crash at opera::BrowserSidebarItemViewViews::UpdateTooltip()
> - DNA-74245 [O57] web3.js downloaded with flag disabled
> - DNA-74346 Fix performance problems with extensions blocking feature
> - DNA-74390 Disable official PiP (picture-in-picture) or implement a UI for it
>

**Comment by beaufortfrancois** [comment]
I don't.
Maybe @bratell-at-opera knows.

**Comment by bratell-at-opera** [comment]
I don't know but I assume it's a question of time. We just didn't keep much of an eye on this project since we had our video popup feature that solved a similar problem.

**Comment by bratell-at-opera** [comment]
Tracked in DNA-74470 in our internal bug database if you need to reference something.

**Comment by joeyparrish** [comment]
Closing this stale external (non-Shaka) issue. If you disagree, please reply with @shaka-bot reopen, and it will be automatically reopened.
