### ISSUE TITLE
HLS manifest version 7 is not playing in Shaka Player

### ISSUE THREAD

**Issue by asingla-ninja2** [google/shaka-player#1730]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**: yes

**What version of Shaka Player are you using?**: latest

**Can you reproduce the issue with our latest release version?**: yes

**Can you reproduce the issue with the latest code from `master`?**: yes

**Are you using the demo app or your own custom app?**: demo

**If custom app, can you reproduce the issue using our demo app?**: yes

**What browser and OS are you using?**: Chrome

**What are the manifest and license server URIs?**:
https://timesmmdod-mmd-cust.lldns.net/v1/gaana/mp4/26/1836026/21206608/stream.ismd/master.m3u8?stream=21206608_128;21206608_16

**What did you do?** 
I played this manifest under custom asset

**What did you expect to happen?**
Mp3 file should render and play the song

**What actually happened?**
Getting the below error:

main.js:695 Player error shaka.util.Error {severity: 2, category: 4, code: 4023, data: Array(1), handled: false, …}category: 4code: 4023data: ["URI"]handled: falsemessage: "Shaka Error MANIFEST.HLS_REQUIRED_ATTRIBUTE_MISSING (URI)"severity: 2stack: "Error: Shaka Error MANIFEST.HLS_REQUIRED_ATTRIBUTE_MISSING (URI)↵    at new shaka.util.Error (https://shaka-player-demo.appspot.com/lib/util/error.js:89:13)↵    at Function.shaka.hls.HlsParser.getRequiredAttributeValue_ (https://shaka-player-demo.appspot.com/lib/hls/hls_parser.js:1781:11)↵    at shaka.hls.HlsParser.createStreamInfoFromMediaTag_ (https://shaka-player-demo.appspot.com/lib/hls/hls_parser.js:808:23)↵    at shaka.hls.HlsParser.<anonymous> (https://shaka-player-demo.appspot.com/lib/hls/hls_parser.js:545:17)↵    at Array.map (<anonymous>)↵    at shaka.hls.HlsParser.createVariantsForTag_ (https://shaka-player-demo.appspot.com/lib/hls/hls_parser.js:544:28)↵    at shaka.hls.HlsParser.<anonymous> (https://shaka-player-demo.appspot.com/lib/hls/hls_parser.js:452:19)↵    at Array.map (<anonymous>)↵    at shaka.hls.HlsParser.<anonymous> (https://shaka-player-demo.appspot.com/lib/hls/hls_parser.js:451:40)"__proto__: Object
shakaDemo.onError_ @ main.js:695
(anonymous) @ asset_section.js:370
Promise.then (async)
shakaDemo.load @ asset_section.js:339

Error Code : 4023

HLS_REQUIRED_ATTRIBUTE_MISSING | 4023 | number | One of the required attributes was not provided, so the HLS manifest is invalid. error.data[0] is the missing attribute's name.
-- | -- | -- | --

**Comment by ismena** [comment]
Looks like we are treating uri attribute of the media tag as required, which is wrong unless the tag describes subtitles.
From the HLS spec:
 
> The URI attribute of the EXT-X-MEDIA tag is REQUIRED if the media
>    type is SUBTITLES, but OPTIONAL if the media type is VIDEO or AUDIO.
>    If the media type is VIDEO or AUDIO, a missing URI attribute
>    indicates that the media data for this Rendition is included in the
>    Media Playlist of any EXT-X-STREAM-INF tag referencing this
>    EXT-X-MEDIA tag.  If the media TYPE is AUDIO and the URI attribute is
>    missing, clients MUST assume that the audio data for this Rendition
>    is present in every video Rendition specified by the EXT-X-STREAM-INF
>    tag.

**Comment by rgc** [comment]
@ismena - I have a fix for this, which branch label should I use in my pull request?

Thanks,

Rob

**Comment by ismena** [comment]
@rgc feel free to use master.

**Comment by rgc** [comment]
@ismena See: https://github.com/google/shaka-player/pull/1732

Thanks,

Rob

**Comment by joeyparrish** [comment]
The commit message in adde0bd is malformed, but this issue was fixed by that commit.
