### ISSUE TITLE
UI: add clearBuffer option to configure

### ISSUE THREAD

**Issue by Kogoruhn** [google/shaka-player#1733]
This will allow the player to change the quality without playback blinking.

`ui/controls.js:`
```
shaka.ui.Controls.prototype.onTrackSelected_ = function(track) {
  // Disable abr manager before changing tracks.
  let config = {abr: {enabled: false}};
  this.player_.configure(config);
  let clearBuffer = this.player_.getConfiguration().clearBuffer; // <-- changed
  this.player_.selectVariantTrack(track, clearBuffer); // <-- changed
};
```

**Comment by ismena** [comment]
Hi @Kogoruhn,
shaka.extern.PlayerConfiguration does not have a clearBuffer field. 
Could you walk me through the use case for this? Is it that playback stalls for a sec while we're buffering the new resolution?

**Comment by ismena** [comment]
Oh, are you proposing we add a clearBuffer config?
Sorry, I'm slow today :)

It would make more sense to be part of the UI config, but can certainly do it if that was the suggestion.

**Comment by Kogoruhn** [comment]
@ismena Yep, just an enhancement request, sorry for unclear start message... Im slow anytime X)
Playback is blinking now, as on youtube. But in our project we want soft transition after resolution changes.
So we should keep current buffer info and wait for the next chunks with new resolution.

**Comment by ismena** [comment]
Gotcha!
Spasibo, we'll work on it.

**Comment by ismena** [comment]
Ahh, we completely lost track of this :(
@joeyparrish Could you schedule? I don't think this is a UI enhancement also, but a player one.

**Comment by ismena** [comment]
Sorry this took forever :(
uiConfig.clearBufferOnQualityChange setting is at your service!
