### ISSUE TITLE
Stream doesn't load at 0 seconds, but it loads at 2s or more

### ISSUE THREAD

**Issue by amity177** [google/shaka-player#1738]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:

**What version of Shaka Player are you using?**: 2.5.0 beta 2

**Can you reproduce the issue with our latest release version?**:

**Can you reproduce the issue with the latest code from `master`?**:

**Are you using the demo app or your own custom app?**:

**If custom app, can you reproduce the issue using our demo app?**:

**What browser and OS are you using?**:

**What are the manifest and license server URIs?**:

**What did you do?**

**What did you expect to happen?**

**What actually happened?**

**Comment by vaage** [comment]
@amity177 Please fill in the issue template.

**Comment by amity177** [comment]
I'll provide stream separately in email.
