### ISSUE TITLE
Player doesn't work with multi periods dash stream.

### ISSUE THREAD

**Issue by amity177** [google/shaka-player#1739]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:

**What version of Shaka Player are you using?**: 2.5.0 beta2

**Can you reproduce the issue with our latest release version?**: 

**Can you reproduce the issue with the latest code from `master`?**:

**Are you using the demo app or your own custom app?**:

**If custom app, can you reproduce the issue using our demo app?**:

**What browser and OS are you using?**:

**What are the manifest and license server URIs?**:

**What did you do?**

**What did you expect to happen?**

**What actually happened?**

**Comment by amity177** [comment]
I'll provide stream separately in email.

**Comment by vaage** [comment]
@amity177 Please fill in the issue template.

**Comment by ismena** [comment]
This is a bug from the Chromecast team. Reopening, as it is still ongoing. We're in communication with them via email.

**Comment by joeyparrish** [comment]
This issue doesn't have any content, so **closing**.  We need an actual issue description, not just a placeholder number, regardless of what's in an email thread.  Please file a complete issue, and just leave out the content URIs.  The rest **must** be public.
