### ISSUE TITLE
Cannot read property 'length' of null

### ISSUE THREAD

**Issue by sanbornhnewyyz** [google/shaka-player#174]
I'm getting this error showing up in our logs. As far as I can tell it's not actually causing a problem but I'm not certain of this.

This error is getting thrown in shaka.player.StreamVideoSource.prototype.onKeyStatusesChange() at this point: 

for (var i = 0; i < streamInfos.length; ++i) {
      var streamInfo = streamInfos[i];
      var originalAllowed = streamInfo.allowedByKeySystem;
...

StreamInfos is null and keyStatusByKeyId is Object {2b62f97d718c460f8b64a2c20fd9b26c: "usable"}

I only get this error when using the malformed content that I sent you guys a while back to debug a different issue. When I use good content I don't get this error, but it's also the case that the onKeyStatusesChange() handler never fires in these cases. 

Do you know why this bad content could be triggering a keystatuseschange event and why when it does trigger this event, streamInfos would be null? I will continue to look into this for more information but I thought you might have useful input.

**Comment by tdrews** [comment]
The `if` at https://github.com/google/shaka-player/blob/4cc4e96dbd5d2fd1b47e622eb8505d3ab4848cc0/lib/player/stream_video_source.js#L922 should not include `!COMPILED`.

Does your good content have `cenc:default_KID` in the MPD? Or is it unencrypted?

**Comment by sanbornhnewyyz** [comment]
The good content is encrypted but it does not have the default_KID. The presence of this property triggers the keystatuseschange event?

**Comment by tdrews** [comment]
The browser (specifically the EME layer) fires the `keystatuseschange` event. The player uses the MPD's `cenc:default_KID` attributes to correlate key statuses to Representations (the player could not accomplish this without `cenc:default_KID` attributes as there's no key-system-agnostic mechanism to extract key IDs from actual content).

The browser should fire a `keystatuseschange` event when it begins playback of any encrypted content. So, I would expect StreamVideoSource to encounter `Uncaught TypeError: Cannot read property 'length' of null` for any encrypted content without `@cenc:default_KID` in compiled mode before d0b8c68b04288bc879943dc84db16e85144f775e.

If you run in debug mode (with debug logging) do you see `onKeyStatusesChange_` reported in the console for both your good and bad content? Or, perhaps your good content has an (unencrypted) clear-lead?

**Comment by tdrews** [comment]
We will land fixes for #170 and #182 for v1.5.0. After those land, let me know if you're seeing any different behavior here.

**Comment by tdrews** [comment]
Closing... Please reopen if you still see this issue.
