### ISSUE TITLE
Shaka browser plugin fetches live stream manifest mpd but not streams m4s files

### ISSUE THREAD

**Issue by c7borg** [google/shaka-player#1740]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:Yes

**What version of Shaka Player are you using?**:2.4.1

**Can you reproduce the issue with our latest release version?**:Yes

**Can you reproduce the issue with the latest code from `master`?**:Yes

**Are you using the demo app or your own custom app?**:Demo I think

**If custom app, can you reproduce the issue using our demo app?**:n/a

**What browser and OS are you using?**:Chromium 56.0.2924.84

**What are the manifest and license server URIs?**:
0.http://servername/stream/out.mpd
1.http://servername/stream/out.mpd
2.http://servername/stream/out.mpd
3.http://servername/stream/out.mpd
http://servername/stream/init-stream1.m4s
http://servername/stream/chunk-stream1-08999.m4s
http://servername/stream/init-stream0.m4s
http://servername/stream/chunk-stream0-08999.m4s
http://servername/stream/chunk-stream1-09000.m4s
http://servername/stream/chunk-stream0-09000.m4s
4.http://servername/stream/out.mpd
http://servername/stream/chunk-stream1-09001.m4s
http://servername/stream/chunk-stream0-09001.m4s

**What did you do?**
Just opened my browser page as usual
**What did you expect to happen?**
the video to start playing
**What actually happened?**
it kept fetching the mpd file but not any of the stream (m4s) files it can do this for a while then suddenly start.

I have attached the mpd manifest files and my script file, would it be possible to advise if there is anything I can add to my script to give more output on why it is not fetching the m4s files

Thanks in advance

[out0.txt](https://github.com/google/shaka-player/files/2694131/out0.txt)
[out1.txt](https://github.com/google/shaka-player/files/2694132/out1.txt)
[out2.txt](https://github.com/google/shaka-player/files/2694133/out2.txt)
[out3.txt](https://github.com/google/shaka-player/files/2694134/out3.txt)
[out4.txt](https://github.com/google/shaka-player/files/2694135/out4.txt)
[script.txt](https://github.com/google/shaka-player/files/2694136/script.txt)

?

**Comment by c7borg** [comment]
These are my two ffmpeg scripts the problem can occur on either:

Description: receives input from multicast stream and produces a dash output

`ffmpeg -i udp://@239.192.4.5:1234?overrun_nonfatal=1&fifo_size=50000000 -acodec aac -strict -2 -vcodec libx264 -vf yadif -af aresample=async=1 -x264opts keyint=25:scenecut=-1 -window_size 10 -extra_window_size 10 -loglevel fatal -f dash /var/www/html/stream/out.mpd`

Description: receives input from multicast stream and produces a dash output with subtitle overlay

`ffmpeg -i udp://@239.192.6.11:5000?overrun_nonfatal=1&fifo_size=50000000 -acodec aac -strict -2 -vcodec libx264 -af aresample=async=1 -filter_complex [0:v][0:s]overlay -x264opts keyint=25:scenecut=-1 -window_size 10 -extra_window_size 10 -loglevel warning -f dash /var/www/html/stream/out.mpd`

**Comment by TheModMaker** [comment]
Do you see console logs looking like `looking up segment: presentationTime=### currentPeriod.startTime=###`?  Can you try with the latest code from `master` or with the nightly: https://nightly-dot-shaka-player-demo.appspot.com/
