### ISSUE TITLE
Playback jams and repeats frames when subtitles enabled on Samsung TV

### ISSUE THREAD

**Issue by pawelgliwinski** [google/shaka-player#1745]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:
Yes
**What version of Shaka Player are you using?**:
2.4.5 (debug and non debug version)
**Can you reproduce the issue with our latest release version?**:
2.5.x yes
**Can you reproduce the issue with the latest code from `master`?**:
didn't check
**Are you using the demo app or your own custom app?**:
custom app
**If custom app, can you reproduce the issue using our demo app?**:
didn't check
**What browser and OS are you using?**:
Samsung TV: Tizen version 3 and 4
**What are the manifest and license server URIs?**:
will send that separately

**What did you do?**
Starting the player with the subtitles enabled by default.
**What did you expect to happen?**
Start of the playback should happen relatively smoothly, like it is happening when I'm starting without subtitles enabled.
**What actually happened?**
start of the playback jams and has repeats chunks around 3 times.

Find the logs attached:
[start of the title with subtitles enabled.txt](https://github.com/google/shaka-player/files/2703181/start.of.the.title.with.subtitles.enabled.txt)

**Comment by pawelgliwinski** [comment]
any help much appreciated

**Comment by vaage** [comment]
@pawelgliwinski Did you send the manifest(s)? I was looking through our records and I can't find an email for this issue. Could you send them again and reference the issue number in the subject line?

Could you also check if this is happening with our demo app? It will be hard to help if we don't have a reliable way to reproduce the issue.

**Comment by pawelgliwinski** [comment]
I have sent an email. please check if you can see it

**Comment by vaage** [comment]
@pawelgliwinski Thank you. I just saw it arrive in our shared email. However since you sent the actual manifest we won't be able to reproduce the issue, only evaluate the contents of the manifest.

I should I have been more special, that is my fault. Is this stream hosted anywhere? If you send us the link to where it is hosted we can try to repro this with our Tizen TV.
