### ISSUE TITLE
VOD playback problems (player starts to download all segments)

### ISSUE THREAD

**Issue by ababin** [google/shaka-player#1746]
Hello, guys ! I hope, You will answer, because, I have no idea about this problem.... I changed manifest many many times, with varies parameters..It doesn't work! (but works in VLC). Well, this is the VOD-record, prepared from-live stream. VOD: https://test-origin.beeline.kz/catchup/English_club/shaka/index-1545591600-1800.mpd . I tried it to playback in https://shaka-player-demo.appspot.com/demo/ . What is wrong in my MPD-manifest ? (VOD-record is got from live-stream: https://test-origin.beeline.kz/dash_open_english_club_202/english_club_202.mpd) Thank you for your response, beforehand !

**Comment by vaage** [comment]
@ababin could you fill in the issue template? It will ensure we have all the information we normally need before looking into the issue. To make it easier on you, I have inserted the template below:



**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:

**What version of Shaka Player are you using?**:

**Can you reproduce the issue with our latest release version?**:

**Can you reproduce the issue with the latest code from `master`?**:

**Are you using the demo app or your own custom app?**:

**If custom app, can you reproduce the issue using our demo app?**:

**What browser and OS are you using?**:

**What are the manifest and license server URIs?**:


**What did you do?**

**What did you expect to happen?**

**What actually happened?**

**Comment by ababin** [comment]
**Have you read the FAQ and checked for duplicate open issues?:**
Yes, shure. I didn't find anything about my problem

**What version of Shaka Player are you using?:**
I use for testing this:  https://shaka-player-demo.appspot.com/demo/

**Can you reproduce the issue with our latest release version?:**
I use player: https://shaka-player-demo.appspot.com/demo

**Can you reproduce the issue with the latest code from master?:**
I use https://shaka-player-demo.appspot.com/demo

**Are you using the demo app or your own custom app?:**

**If custom app, can you reproduce the issue using our demo app?:**
Problem is reprodused on https://shaka-player-demo.appspot.com/demo/ for VOD-stream: https://test-origin.beeline.kz/catchup/English_club/shaka/index-1545591600-1800.mpd

**What browser and OS are you using?:**
I use Calculate-linux (4.18.14-calculate), browser: chromium-70.0.3538.110

**What are the manifest and license server URIs?:**
Stream is clear. Manifest URI: https://test-origin.beeline.kz/catchup/English_club/shaka/index-1545591600-1800.mpd

**What did you do?**
I implement catchup-feature for DVR-server. As a base for non-worked record is used live-stream: https://test-origin.beeline.kz/dash_open_english_club_202/english_club_202.mpd

**What did you expect to happen?**
I expect the player https://shaka-player-demo.appspot.com/demo/ will start to playback stream correctly for mentioned VOD-stream.

**What actually happened?**
I open developer-panel in browser, and see what is going on: after click 'Load'-button, it starts to download segments correctly, in order to start segment's index (parameter startNumber for SegmentTemplate). But segment's downloading is continued too long, something about 200 segments. After that happen nothing.

**Comment by TheModMaker** [comment]
The problem is the manifest specifies the segments go from 0 to 1800 seconds; but your segments have a media time of 446130+ seconds.  You need to use `presentationTimeOffset` to adjust the media times so they appear at the time specified in the manifest.  See [this doc](https://github.com/google/shaka-player/blob/master/docs/design/dash-manifests.md) for more info on the presentation timeline.

**Comment by ababin** [comment]
Jacob, many thanks for your response! I made changes (added presentationTimeOffset). But it is not affected. I read mentioned doc, but I don't understand what is wrong (( I tried use timeLine tag, but without any results) Can you provide the worked version of the manifest for my case ? Thank you, beforehand !!!

**Comment by TheModMaker** [comment]
The `presentationTimeOffset` is in `timescale` units, so you need to multiply by that.  Changing the `presentationTimeOffset` value to 40151700000 works for me.

**Comment by ababin** [comment]
Jacob, it really works ))  Thank you very much!
