### ISSUE TITLE
Timestamp correction not being applied on startup

### ISSUE THREAD

**Issue by bhh1988** [google/shaka-player#175]
I believe this is just a one-character typo in *lib/media/stream.js:527*

**`var bufferStart = this.started`** should be
**`var bufferStart = this.started_`**

The symptom is, for videos that don't start at a pts of 0, bufferedAheadOf() is always being computed as 0, therefore the bufferingGoal is never reached and therefore playback does not begin until everything's completely buffered.

Here's a set of test dash'ed audio-files that repro: https://cloud.box.com/s/3ep0vemzp1y21tdotd0byyj9yxjdce1s

**Comment by tdrews** [comment]
Thanks, good catch!
