### ISSUE TITLE
setClockOffset (when player loading) it looks no effects.

### ISSUE THREAD

**Issue by trustfarm-dev** [google/shaka-player#1752]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:
yes
**What version of Shaka Player are you using?**:
latest
**Can you reproduce the issue with our latest release version?**:
yes
**Can you reproduce the issue with the latest code from `master`?**:
yes
**Are you using the demo app or your own custom app?**:
custom app
**If custom app, can you reproduce the issue using our demo app?**:
can not try in demo app.
**What browser and OS are you using?**:
windows10
**What are the manifest and license server URIs?**:

**What did you do?**
when playing multiple tile (divide from one large video),  sequential play button delay. I've add first loading stream, add setClockOffset = some value (ms) .

**What did you expect to happen?**
make sync with each tile.

**What actually happened?**
offset value to over 1000, it doesn't effects on MPD presentation.

When , What time , Where I call setClockOffset ? it makes effects.

Thanks.

**Comment by chrisfillmore** [comment]
Are you using multiple instances of shaka.Player to play this video?

**Comment by TheModMaker** [comment]
The only method called `setClockOffset` is on `PresentationTimeline`, which shouldn't really be used by the app.  You shouldn't call this method at all, it is called automatically during manifest loading.  This is used to ensure the server and the app have the same clock times.

Are you talking about playing one MPD file that has multiple parts, or loading multiple MPD files?

**Comment by trustfarm-dev** [comment]
@chris yes. 16 instances in same time

**Comment by trustfarm-dev** [comment]
@chris yes. 16 instances in same time

@themodmaker yes multiple instances same time.
It is can be called in mpd is problem I think.
Is there runtime setting the pts timing ?

**Comment by TheModMaker** [comment]
We don't really provide a cross-video synchronization mechanism.  You'll probably need to do something in your app.  Assuming the different streams are generated on the same server and have the same `availabilityStartTime` (i.e. they started at the same time), you could probably just set the `video.currentTime` for each video to the same time and they should be synchronized.

Alternatively you'll need to provide some offset from each stream to your app.  For example, if you set `video1.currentTime` to 45, you may need to set `video2.currentTime` to 50.  You would need to send this info to your app and handle it yourself.  We don't provide a way to synchronize two videos.  Remember that each video is an independent video stream from our perspective.

**Comment by trustfarm-dev** [comment]
@TheModMaker  @chrisfillmore @shaka-bot 
Move to New issues. on #1756
