### ISSUE TITLE
Discussion: improving issue reports for embedded devices

### ISSUE THREAD

**Issue by chrisfillmore** [google/shaka-player#1753]
There are a lot of Tizen/WebOS/etc issues reported these days. Unfortunately many of these industry vendors do not provide any public support for firmware or media playback issues. There is no place to report bugs or get feedback. This is made worse by the fact that firmware updates are infrequent.

But, we may be able to improve our situation. It's possible that we can write more actionable issue reports by including more information, specifically device model number and firmware version. The issue template could be updated to ask for this information.

The goal is to produce a corpus of reports which may be more valuable to industry vendors and their engineering teams.

There may be other ways we can help each other. I know, for instance, that Tizen's media stack is based on [GStreamer](https://gstreamer.freedesktop.org/), which is open source and appears to have a very active community. An enterprising developer may opt to test their media against GStreamer to see if they can reproduce an issue.

Does anyone else have ideas or suggestions on how to help document issues on embedded platforms?

**Comment by joeyparrish** [comment]
I will update the issue template to ask for model number and firmware versions on embedded devices.

**Comment by joeyparrish** [comment]
We've had the new field in the issue template for several months.  Since nobody else has had any suggestions in this area, I will go ahead and close this issue.  Thanks!
