### ISSUE TITLE
C:/Program Files/shaka-player/demo/cast_receiver/receiver_app.js:19: ERROR - required "goog.asserts" namespace never provided

### ISSUE THREAD

**Issue by shanedetsch** [google/shaka-player#1759]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:
Yes
**What version of Shaka Player are you using?**:
https://github.com/google/shaka-player.git
commit 2924d906f59e503900b6b6adfa368e422917b61c (HEAD -> master, origin/master, origin/HEAD)

**Can you reproduce the issue with our latest release version?**:
Yes

**Can you reproduce the issue with the latest code from `master`?**:
Yes

**Are you using the demo app or your own custom app?**:
Demo

**If custom app, can you reproduce the issue using our demo app?**:
N/A

**What browser and OS are you using?**:
Chrome, Windows 10 Pro version 1803 build 17134.472

**What are the manifest and license server URIs?**:

N/A

**What did you do?**
C:\Program Files\shaka-player>python build\all.py
[INFO] Generating Closure dependencies...
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated boom@4.3.1: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated boom@2.10.1: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated cryptiles@2.0.5: This version is no longer maintained. Please upgrade to the latest version.
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

[INFO] Linting JavaScript...
[INFO] Linting HTML...

   Config loaded: C:\Program Files\shaka-player\.htmlhintrc

   Config loaded: C:\Program Files\shaka-player\.htmlhintrc

   Config loaded: C:\Program Files\shaka-player\.htmlhintrc

Scanned 3 files, no errors found (22 ms).
[INFO] Checking that the build files are complete...
[INFO] Checking the tests for type errors...
[INFO] Building the docs...
[INFO] Compiling the library (ui, debug)...
[INFO] Compiling the library (compiled, debug)...
[INFO] Compiling the demo app (debug)...
C:/Program Files/shaka-player/demo/cast_receiver/receiver_app.js:19: ERROR - required "goog.asserts" namespace never provided
goog.require('goog.asserts');
^^^^^^^^^^^^^^^^^^^^^^^^^^^^

1 error(s), 0 warning(s)
[ERROR] Build failed

**What did you expect to happen?**
Build Shaka and have npm bring in all the dependencies in the package.json

**What actually happened?**
Got an npm package required error.  I tried fixing this with npm audit fix without sucess.

**Comment by shanedetsch** [comment]
Sorry forgot to mention my OS:
Windows 10 Pro version 1803 build 17134.471

**Comment by trustfarm-dev** [comment]
temporal workaround is , use v2.4.5 
`git checkout -b v2.4.5`
and build it.

**Comment by shanedetsch** [comment]
Branch v2.4.4 worked for me, I got the same error with v2.4.5, thanks for the tip it pointed me in the correct direction.

**Comment by shanedetsch** [comment]
@trustfarm-dev Thanks for your help!

**Comment by joeyparrish** [comment]
The error is not an npm package error.  It appears to be an error from the compiler about a missing compile-time dependency within our sources.  I'm attempting to reproduce now.

**Comment by joeyparrish** [comment]
I can reproduce on Windows, but the same doesn't occur on Mac or Linux.

**Comment by joeyparrish** [comment]
This seems to be a bug in our build scripts regarding how path names are handled.  It should be fairly easy to fix.

**Comment by joeyparrish** [comment]
Fix cherry-picked for v2.4.6.
