### ISSUE TITLE
CastReceiver errors on first stats update when updated to new code

### ISSUE THREAD

**Issue by theodab** [google/shaka-player#1760]
If we update the cast receiver to the current master, there's an error on the first stats update.
This happens when getting the video stream; this happens because `activeStreams_.hasPeriod` returns true if there's a text track, but `StreamUtils.getVariantByStreamIds` gets variants by the video and audio stream Ids. So if we have a text track in a period but no video or audio yet, the returned variant is null. Our code in `getStats` does not account for that possibility.

**Comment by joeyparrish** [comment]
Fix cherry-picked for v2.4.6.
