### ISSUE TITLE
secured content is not playing on android device with Firefox and returns 6001

### ISSUE THREAD

**Issue by SaraMohamedSamir** [google/shaka-player#1763]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:

**What version of Shaka Player are you using?**:
2.4.5
**Can you reproduce the issue with our latest release version?**:

**Can you reproduce the issue with the latest code from `master`?**:

**Are you using the demo app or your own custom app?**:
custom app
**If custom app, can you reproduce the issue using our demo app?**:
No
**What browser and OS are you using?**:
Firefox with android phone
**What are the manifest and license server URIs?**:

**What did you do?**
try to play content using https request in offline mode without any internet access. The content plays on the computers fine but not on the phones.

**What did you expect to happen?**
the content plays successfully
**What actually happened?**
I received 6001 error with no error message:

Error code 6001 object Object { severity: 2, category: 6, code: 6001, data: [], handled: false }

**Comment by joeyparrish** [comment]
Firefox on Android does not support Widevine.  This is outside the control of Shaka Player, Android, and Widevine.  Please file a bug with Mozilla to request support: https://bugzilla.mozilla.org/

Offline content works on Android with Chrome, which supports both Widevine and persistent licenses.

Thanks!
