### ISSUE TITLE
License URL not played in shaka latest version 

### ISSUE THREAD

**Issue by gurusoftgit** [google/shaka-player#1767]
Can you please help me my query how to play that? but license request is success 
See below 

Hello all,

I am using Shaka Player v2 to run a playback test. It is Dash content, generated .mpd file by Shaka Packager with Widevine DRM.

I tired to playback with Shaka Player, then I got the following error at console log.

cast_receiver_framework.js : [cast.framework.media.ShakaPlayer] category: 6 code: 6008

It seems 6012 means "LICENSE_RESPONSE_REJECTED". The license response was rejected by the CDM. The server's response may be invalid or malformed for this CDM. 
error.data[0] is an error message string from the browser.

*Attached is shaka js and proxy python file.

**Comment by gurusoftgit** [comment]
Hello all,

I am using Shaka Player v2 to run a playback test. It is Dash content, generated .mpd file by Shaka Packager with Widevine DRM.

I tired to playback with Shaka Player, then I got the following error at console log.

cast_receiver_framework.js : [cast.framework.media.ShakaPlayer] category: 6 code: 6008

It seems 6012 means "LICENSE_RESPONSE_REJECTED". The license response was rejected by the CDM. The server's response may be invalid or malformed for this CDM. 
error.data[0] is an error message string from the browser.

*Attached is shaka js and proxy python file.

**Comment by joeyparrish** [comment]
@gurusoftgit, you did not fill out the issue template which provides us with the necessary information to provide you with support.  But I notice that you reference `cast.framework.media.ShakaPlayer`.  That sounds like you are using the [Cast Application Framework](https://developers.google.com/cast/docs/caf_receiver/).  CAF uses Shaka Player, but is not developed or maintained by this team.  Please refer to that project's [Cast Support Page](https://developers.google.com/cast/docs/support) for details on how to get help with CAF.
