### ISSUE TITLE
Offline storage demo not working

### ISSUE THREAD

**Issue by danmo** [google/shaka-player#1768]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes.

**What version of Shaka Player are you using?**
Latest.

**Can you reproduce the issue with our latest release version?**
Yes.

**Can you reproduce the issue with the latest code from `master`?**

Yes.
**Are you using the demo app or your own custom app?**

Demo app.
**If custom app, can you reproduce the issue using our demo app?**

-
**What browser and OS are you using?**
Chrome on Mac

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
-

**What are the manifest and license server URIs?**
-

**What did you do?**
![image](https://user-images.githubusercontent.com/3957234/51072815-08b8fc80-1670-11e9-9526-3100ee77b2c7.png)
When using the online shaka demo https://shaka-player-demo.appspot.com/demo/#asset=https://content.uplynk.com/847859273a4b4a81959d8fea181672a4.mpd?pr.version=2&pr.playenabler=B621D91F-EDCC-4035-8D4B-DC71760D43E9&pr.securitylevel=150;lang=en-US;build=uncompiled and trying to store/download a DRM encrypted asset I get above error.

I also have a production application that has not changed in months and now is failing with the same error, on DRM license request, seems the license server is rejecting the license request.

So this is happening in two unrelated applications using unrelated license servers etc.

**What did you expect to happen?**
be able to store drm asset.

**What actually happened?**
crashed with 6007 1001 errors.

**Comment by theodab** [comment]
All of the Verizon Digital Media Services assets seem to be un-storable. Odd. I'll look into it.

**Comment by danmo** [comment]
Getting same error with an Azure Media Services license server on a production application. It fails exactly like the demo but AMS doesn't provide any error message besides the 400 bad request response. Non-persistent license requests are successful.

**Comment by joeyparrish** [comment]
@TheJohnBowers, is it intentional that requests for persistent licenses are denied by the VDMS license server?

Since license servers generally are allowed to deny requests for persistent licenses, I think we may need to flag which of our encrypted demo assets permit storage offline.  The ones we (Shaka) control all permit storage, but we can't control the policy settings of third parties.

**Comment by TheJohnBowers** [comment]
We have a default widevine policy for our license server.  This policy is to issue non persistent licenses, so this is not unexpected.  Our license server can issue persistent licenses, but we do not do that by default.  For the purposes of the demo player we can issue a persistent license though.  That would probably avoid people re-submitting this bug over and over.   If we simply add rmp.policy_overrides.can_persist=True to the mpd url as a parameter, then our license server should issue a persistent license and storing will then be possible.

**Comment by joeyparrish** [comment]
I don't think we care if these particular assets can get a persistent license or not, so feel free to change it or not as you see fit, @TheJohnBowers.  But I think this highlights the need to flag certain third-party assets as not storable, so that the demo app doesn't offer a capability it can't provide.

**Comment by theodab** [comment]
Ok, this CL will mark which assets are storable online and which aren't. It's just a field in the asset structure, so it won't be able to tell for custom assets, but it should prevent more misunderstandings in the future.

**Comment by joeyparrish** [comment]
Offline storage restriction in demo app cherry-picked for v2.4.6.
