### ISSUE TITLE
Clear Key Encryption in IOS and MAC

### ISSUE THREAD

**Issue by MonoGO** [google/shaka-player#1773]
Hi, 

I am able to encrypt the mp4 content using clear key and was able to play the encrypted content offline without internet in my local system and as well as in android devices through LAN and WiFi. But when i tried to consume the same in IPhone or Mac it was failing with following error:

![image](https://user-images.githubusercontent.com/31884755/51468577-5e3e8900-1d95-11e9-92af-33707ad35b7a.png)

When i went through shaka-player community, i found that mpd cannot be played but m3u8 hls streaming can be used along with mux.js to play in ios devices. I tired to convert mp4 into m3u8 dash format and tried it but still it was giving the same error. 

Please provide the suggestion for work around to play the encrypted video content in apple devices. Thanks in advance

**Comment by TheModMaker** [comment]
We don't support iOS (see #997) and Safari doesn't support clear key.  It should work with Chrome or Firefox on Mac.  Take a look at the [support matrix](https://github.com/google/shaka-player/blob/master/README.md#drm-support-matrix) in the README.

**Comment by MonoGO** [comment]
Thanks for the Information.
