### ISSUE TITLE
Why not add 'loadCastFramework=1' when use chromecast sdk?

### ISSUE THREAD

**Issue by oldmtn** [google/shaka-player#1776]
In google cast official page, it shows that we need to use below code to reference cast_sender library.
`<script src="//www.gstatic.com/cv/js/sender/v1/cast_sender.js?loadCastFramework=1"></script>`

But shaka-player don't add 'loadCastFramework=1', it use below code to reference cast_sender library.
<script src="//www.gstatic.com/cv/js/sender/v1/cast_sender.js"></script>

Why?

**Comment by joeyparrish** [comment]
@oldmtn, can you please point me to the doc you're referring to?

**Comment by joeyparrish** [comment]
Actually, I think I found it: https://developers.google.com/cast/docs/chrome_sender/integrate

It says:
> Add the loadCastFramework URL query parameter to load the Cast Sender Framework API as well.

The docs then mention that both a high-level Framework API and a low-level Base API exist.  At the time we created our Cast support, only the Base API existed.  That is what we use to implement the classes in the `shaka.cast` namespace.

On the receiver side, the Cast Application Framework actually depends on Shaka Player.  But CAF uses a completely different messaging protocol between sender and receiver, and uses Shaka as a tool to do DASH playback.  It doesn't expose the full Shaka Player API.

**Comment by joeyparrish** [comment]
Does this answer your question?

**Comment by oldmtn** [comment]
Besides, you also add a reference to cast_sender with blow code:
<script src="chrome-extension://pkedcjkdefgpdelpbcmbmeomcjbeemfm/cast_sender.js"></script>
What does it means?
Why google cast official doc don't menthion it?

**Comment by joeyparrish** [comment]
We don't add that.  The Chrome Cast extension adds that.  You will see that line in the debugger, but not in the source.  That's because it's added by the browser extension at runtime.

Does this answer your question?

**Comment by oldmtn** [comment]
@joeyparrish Yes, Thanks.:)

**Comment by oldmtn** [comment]
@joeyparrish 
http://demo.theoplayer.com/chromecast can show chromecast icon.
https://demo.theoplayer.com/chromecast can show chromecast icon.

So, I think chromecast can only work normal on player deployed on a https server.
