### ISSUE TITLE
No text tracks when loading DASH streams with WebVTT, CEA-608 or TTML closed captions

### ISSUE THREAD

**Issue by kevinscroggins-youi** [google/shaka-player#1778]
Hi! I have been experimenting with Shaka player on the Tizen TV web platform, and after trying several test streams with various types of closed captions / subtitle formats, the player always reports that there are no closed captions. Not sure if I'm overlooking something obvious or not, or if there's an issue with these streams and I've also tried several different things to try and get this working including enabling closed captions and using different functions such as getTextTracks(), getVariantTracks() and getTextLanguages(). Here are some of the test streams that I've used:
Child of the 90s DASH TTML CC: http://amssamples.streaming.mediaservices.windows.net/bb34a723-f69a-4231-afba-dc850f9e3da8/ChildOfThe90s.ism/manifest(format=mpd-time-csf)
Tears of Steel DASH WebVTT CC: http://amssamples.streaming.mediaservices.windows.net/bc57e088-27ec-44e0-ac20-a85ccbcd50da/TearsOfSteel.ism/manifest(format=mpd-time-csf)
Monterey Pop CEA-608: https://d2rghg6apqy7xc.cloudfront.net/dvp/test_dash/005/unencrypted/montereypop_16_min_2265099.mpd

Note that these issues are not specific to Tizen, as I see the same behaviour in Google Chrome as well. I have tried this on version 2.5.0-beta2, 2.4.6 and master. If this is indeed a bug, I can open an issue instead, just wanted to check first.

**Comment by ismena** [comment]
Thanks for the report! Let me get the local closed caption expert.
@michellezhuogg, can you take a look?

To the best of my knowledge, we only have support for CEA in terms of closed captions (Michelle, am I right?), so we're likely unable to detect them. (We just landed CEA support, like a month ago :) ) We'll take a look at the CEA stream, though!

**Comment by michellezhuogg** [comment]
I am able to see CEA-608 closed captions in our demo. Do you have mux.js loaded?
https://nightly-dot-shaka-player-demo.appspot.com/demo/#asset=https://d2rghg6apqy7xc.cloudfront.net/dvp/test_dash/005/unencrypted/montereypop_16_min_2265099.mpd

**Comment by kevinscroggins-youi** [comment]
Thanks for the reply! I definitely do have mux.js.min version 5.0.1 included in my main template. Is there any extra setup that needs to be done to integrate this with Shaka? I did manage to get some tracks to appear in the list with this asset:
https://vm2.dashif.org/dash/vod/testpic_2s/cea608_and_segs.mpd
But not any of the aforementioned WebVTT / TTML assets. Is there something I'm overlooking?

**Comment by kevinscroggins-youi** [comment]
Here is a fiddle: https://jsfiddle.net/zyg0bf8m/6/

**Comment by kevinscroggins-youi** [comment]
No worries! Oh, gotcha! I didn't realize that embedded TTML / VTT aren't supported specifically, that makes more sense. Thank you for clarifying!

The manifest that I linked in the fiddle should have embedded DASH CEA-608 CCs though, and it works in the demo Shaka player, but not in my code snippet. Any idea why that might be? Is it perhaps because they're subtitles and not closed captions or something? I'm not a DASH expert, so I'm still learning, haha.

**Comment by kevinscroggins-youi** [comment]
Oh, fair enough. Thank you for clarifying that.

Right, ok. Noted!

Woops, not sure how I managed that. It loads the page in an iframe, so it should be okay, but points taken! Ahhhh, okay! For my app I have mux.js loading from a local file as well, but it's likely that I switched from 2.5.0-beta2 to 2.4.6. I checked the commit history on Github and it looked like 2.4.6 included all of the 2.5.0-beta2 features and more, but I guess I was mistaken. In that case, do you happen know a rough timeline for the next beta release that includes all of these features? Thank you so much for your help! @TheModMaker

**Comment by ismena** [comment]
@kevinscroggins-youi Did you mean full release? 2.5.0-beta includes all the features!

If what you meant was 2.5.0 (not beta, full release) then, hopefully, some time in Feb! We're a bit behind on it :(

**Comment by kevinscroggins-youi** [comment]
@ismena I did mean that, yes! As far as I understand there's some playback issues and other things that have been fixed with version 2.4.6 so I've opted for that version instead of 2.5.0-beta2 for the moment. That's excellent news though, no worries! Thanks so much again for all the help!
