### ISSUE TITLE
Is there a way to force the player to use a specific DRM type?

### ISSUE THREAD

**Issue by kevinscroggins-youi** [google/shaka-player#1779]
Hi! I'm currently trying to load a manifest that contains both PlayReady and Widevine DRM, and have it default to playing using one or the other but Shaka seems to require that licensing servers be specified for all DRM types and not just one or the other. The player outputs a 6012 / NO_LICENSE_SERVER_GIVEN error for the Widevine DRM type, and this seems to happen even when I specify a server for both. I've briefly experimented with ignoreDrmInfo, customScheme handling and writing a custom manifest parser but these attempts have been mostly unsuccessful so far. Ideally I'd like to be able to tell the player which DRM type to use, but I'm not sure if this is possible. I'm currently developing for the Tizen TV web platform, but I see this issue on Chrome as well. Currently tested using Shaka version 2.5.0-beta2, 2.4.6 and master. I can provide a manifest sample if needed.

**Comment by chrisfillmore** [comment]
Yes, you can force which DRM you want to use, by configuring Shaka for the key system you want (and excluding the ones you don't want). I know this because I also do this on Tizen to force PlayReady.

This sounds a bit fishy, either there could be a new Shaka bug or you are misconfiguring the player. Could you share your code where you configure the player?

**Comment by joeyparrish** [comment]
@kevinscroggins-youi, how is it that you have this issue on Chrome?  Chrome only supports Widevine, so there is no opportunity to force a particular DRM as far as I know.

For Tizen, you have two ways to force the choice of Widevine or Playready.  There is no built-in priority order in Shaka Player.  If you configure a license server for one, but not the other, we will use the one you configured.  If you configure both, we will try them in the order they appear in the manifest.

Does this help?

**Comment by kevinscroggins-youi** [comment]
@chrisfillmore That's what I thought, but it still seems to be erroring out. Perhaps I'm not doing it correctly, I did experiment with a few different approaches but didn't have much luck.

@joeyparrish Thanks for the follow up! Ahh sorry, I must have been mistaken. I'm getting a 6001 error in Chrome now that I try it again. On Tizen I'm definitely still getting a 6012 error despite having only specified the license server for PlayReady and I confirmed that it's erroring on playback because it can't find a license server for Widevine. The documentation also backs up this behaviour by indicating that licensing servers for all DRM types in the manifest must be specified, is this not the case? Here is an example fiddle: https://jsfiddle.net/Ljqa5t3d/1/ I unfortunately don't have a copy of Edge or IE11 on anything > Win7 to test against, since Tizen TVs aren't easy to debug on, but it should be correct. Auth token is also redacted, but shouldn't be required.

**Comment by kevinscroggins-youi** [comment]
After updating my code and testing using Microsoft Edge on Windows 10, this appears to now find the correct license server, but there is a cross-origin error when retrieving the manifest that I was unable to previously see on Tizen. I believe this issue is resolved, and is now a backend server issue. Thanks for the help!
