### ISSUE TITLE
Player factory?

### ISSUE THREAD

**Issue by palmerj3** [google/shaka-player#178]
I am wondering if there is currently the ability for Shaka to detect the type of video requested to play and then instantiate or return the proper Player Source type?

**Comment by tdrews** [comment]
The Player itself does not do this, but your application can just inspect the media's URL: if the URL ends with `.mpd` then use `DashVideoSource`; otherwise, use `HttpVideoSource`.

**Comment by tdrews** [comment]
Does this answer your question, or have I misinterpreted your question?
