### ISSUE TITLE
HLS Parser Handling Aborted Operations as "No Partial HLS Segment Support"

### ISSUE THREAD

**Issue by vaage** [google/shaka-player#1788]
This is an off-shoot of #1785.

**What version of Shaka Player are you using?**
2.5.0-beta2

**Can you reproduce the issue with our latest release version?**
Reproduced with 2.5.0-beta2

**Can you reproduce the issue with the latest code from `master`?**
Reproduced with 2.5.0-beta2

**Are you using the demo app or your own custom app?**
Custom App

**If custom app, can you reproduce the issue using our demo app?**
The current demo app does not have the mechanism to change streams fast enough to easily reproduce the issue.

**What browser and OS are you using?**
Chrome 71.0.3578.98 on OSX

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**
Custom manifest. However this can be reproduced with any HLS content.

**What did you do?**

1. Load HLS manifest (manifest A)
2. Load HLS manifest (manifest B)
3. Repeat steps 1 and 2 multiple times.

In order for this to work, there needs to be some delay between calls to load.

**What did you expect to happen?**
Calls to `load` should interrupt previous calls to `load` with no errors and the last call to `load` should produce playback.

**What actually happened?**
When the HLS Parser is shutting down and aborting its in-progress networking requests, it will misinterrupt the aborted operation as "Unable to fetch a partial HLS segment! Falling back to a full segment request, which is expensive!"

**Comment by vaage** [comment]
After talking it over with @joeyparrish the current plan of action is:

**For 2.5:**
1. Create a unit test for the HLS parser to show this behaviour. This test will be used as a regression test once the fix is created.
2. Implement a short-term (less invasive change) that will allow the test mentioned above to pass.

**For 2.7**
1. As part of the greater HLS changes, this fix should be built into the design of the parer in a more sustainable way than was done for 2.5.

**Comment by vaage** [comment]
Updates on this issue:
- A test for reproducing the issue has been created. The test is in code review.
- A fix for the issue has been created. The fix is in code review.

Many members of the team have been out-of-office lately, so reviews have been taking longer than normal. Thank you to everyone for their patience.

**Comment by vaage** [comment]
We have completed all the work for 2.5. The only work remaining is the work listed for 2.7. I am going to remove this from the 2.5 milestone so that it does not block the release. When we scope out 2.7 it should be added to that milestone.

@joeyparrish I am tagging you here since this has to do with release planning for 2.5 and 2.7.

**Comment by joeyparrish** [comment]
25710b6 seems to have introduced a regression that prevents us from accessing Microsoft IIS by unconditionally including `range` headers in segment requests.  I should have a fix soon.

**Comment by joeyparrish** [comment]
This issue has gotten stale.  I'm not aware of this as a current issue.
