### ISSUE TITLE
Cannot read property 'segmentIndexSource' of

### ISSUE THREAD

**Issue by sanbornhnewyyz** [google/shaka-player#179]
Using the most up-to-date build off the master branch:

1. Open the sample app and play "Oops" Multi-DRM
2. Set the minBandwidth to filter out some tracks (e.g. 702000)
3. Click the Load Stream button again, to reload the "Oops" video

I get the following errors: 

Assertion failed: Each StreamSetInfo should contain at least one usable StreamInfo
Uncaught TypeError: Cannot read property 'segmentIndexSource' of null

**Comment by tdrews** [comment]
`StreamVideoSource` is applying the restrictions to the audio tracks, which it should not be. We'll have a patch up shortly.

However, we'll defer handling the case where no audio or video tracks are available (during playback or at startup) until later (similar issue to #170).
