### ISSUE TITLE
When will closure-compiler dependency be updated?

### ISSUE THREAD

**Issue by hbofolts1** [google/shaka-player#1792]
Are there any plans on updating the third party closure-compiler shaka-player is using to a more recent version?

I believe shaka-player is currently inheriting this issue

https://github.com/google/closure-compiler/issues/3080

**Comment by hbofolts1** [comment]
It looks like the closure provided polyfills were recently introduced for IE11.

https://github.com/google/shaka-player/commit/53a8383df5db8ee4b281d2a2fb648b59cc38fa63

**Comment by vaage** [comment]
@hbofolts1 thank you for being so patient. We are planning 2.6 to focus on Code Health, which should include a pass over all our dependencies, including Closure. I've opened an [issue](https://github.com/google/shaka-player/issues/1852) specifically for updating Closure and scheduled it for the milestone. We are wrapping up 2.5 now, so we should be tackling 2.6 shortly.

If you feel your question has been answered, please feel free to close the issue.
