### ISSUE TITLE
Duplicate Requests for Widevine License Server

### ISSUE THREAD

**Issue by waxidiotic** [google/shaka-player#1794]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

Yes, I have read the FAQ. I have also searched for duplicate open issues and found one to be _similar_ but for PlayReady (https://github.com/google/shaka-player/issues/1618).

**What version of Shaka Player are you using?**

Production - v2.3.5

**Can you reproduce the issue with our latest release version?**

Yes (v2.4.6).

**Can you reproduce the issue with the latest code from `master`?**

Yes (v2.5.0-beta.2).

**Are you using the demo app or your own custom app?**

Both.

**If custom app, can you reproduce the issue using our demo app?**

Yes, I can reproduce it in both.

**What browser and OS are you using?**

Chrome 74.0.3694.0 canary
Firefox 65.0
macOS Mojave 10.14.3

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

n/a

**What are the manifest and license server URIs?**

I am able to reproduce with multiple Widevine-encrypted DASH streams but the one I am using is the following:

*Manifest:* https://d2jl6e4h8300i8.cloudfront.net/drm/dash/netflix_meridian/mbr/stream.mpd
*License Server:* https://widevine.licensekeyserver.com

**What did you do?**

1. Open https://s3.amazonaws.com/bob.jwplayer.com/~alex/shaka_widevine_req/demo/widevine/index.html 
2. Open the Network tab in DevTools
3. Filter for 'widevine' (without quotes)
4. Refresh the page
5. Witness four requests, two OPTIONS and two POST.

**What did you expect to happen?**

At most, I would expect two requests, one OPTIONS and one POST.

**What actually happened?**

Four requests are being made for the license server, two OPTIONS and two POST.

**Comment by chrisfillmore** [comment]
@waxidiotic I get the following CORS error when I try to load the page you linked to:

```
Access to fetch at 'https://widevine.licensekeyserver.com/' from origin 'https://s3.amazonaws.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

This appears to be a CORS misconfiguration on your server. See the response to the OPTIONS request below:

![screen shot 2019-02-08 at 4 11 25 pm](https://user-images.githubusercontent.com/7190265/52506330-3c7a3a00-2bbc-11e9-894a-510029ae9a0e.png)

**Comment by mborecki** [comment]
Something is wrong between vertions 2.4.4 and 2.4.6.

In 2.4.4 : I see 2 licence requests (cert + license)
In 2.4.6 : I see 10 requests

**Comment by BucherTomas** [comment]
Just FYI @waxidiotic

As @mborecki outlined , two POST requests to Widevine license proxy (plus two OPTIONS depending on the circumstances) can be common nowadays.

Since Widevine has introduced so-called Verified Media Path into its CDM module, user agent generates first a certificate request and only then actual license request. If your first POST request is just two bytes, then this is the request for certificate.

Shaka supports setting `serverCertificate` in its DRM config to use locally stored server certificate in order to avoid such certificate request.

**Comment by waxidiotic** [comment]
Thanks @mborecki and @BucherTomas - I'll look into `serverCertificate`.
