### ISSUE TITLE
behaviour when chunk unavailable

### ISSUE THREAD

**Issue by kuznetcoff777** [google/shaka-player#1798]
Hi! For example we have playlist/manifest (hls/dash) with 3 bitrates: lq/sd/hd.
If we do manipulation such as removing HD segments (deleting it from file system, or just stopping to generate it), then in native hls player it gets 404 error for sement and instantly attempt to get sd chunk. If it also unavailable, then lq chunk. If not lq, then error

Is it possible to do the same in shaka player?

**Comment by chrisfillmore** [comment]
This looks the same as #1542

**Comment by kuznetcoff777** [comment]
Thanks, waiting for enhancement!
