### ISSUE TITLE
import shaka as es6 module doesn't expose all APIs

### ISSUE THREAD

**Issue by FrancescoBorzi** [google/shaka-player#1802]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

Yes, this is nothing about what's currently in the FAQ and I couldn't find a similar issue.

**What version of Shaka Player are you using?**

`"shaka-player": "^2.4.3",`

**Can you reproduce the issue with our latest release version?**

Yes

**Can you reproduce the issue with the latest code from `master`?**

I haven't tried because I import it just as a node module.

**Are you using the demo app or your own custom app?**

I'm importing the npm package `shaka-player` and trying to use it in my app.

**If custom app, can you reproduce the issue using our demo app?**

N/A

**What browser and OS are you using?**

Chrome

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

N/A

**What are the manifest and license server URIs?**

N/A

**What did you do?**

I import the shaka debug module using `import { shaka } from 'shaka-player/dist/shaka-player.compiled.debug';`

**What did you expect to happen?**

Being able to access `shaka`'s fields like:

-` shaka.log.*`
- `shaka.media.DrmEngine.*`
- etc...

just like I can do when I import it as a js file in my `index.html` (without using es6 modules).

**What actually happened?**

Some fields of `shaka` are exposed, but not all of them (for example the one I mentioned are not exported).

**Comment by joeyparrish** [comment]
This is working as intended.  The library only exports certain APIs.  The ones you mentioned are not exported from a production build.  For example, `shaka.log` is compiled out in production, and `shaka.media.DrmEngine` is an internal class that applications are not meant to interact with directly.

To access the internals, you can use a debug build or an uncompiled build, but we make no guarantees about backward compatibility of those interfaces.  They may change at any time, in any release.

If you have a specific need for those internal methods in your application, I may be able to help you find a supported way to accomplish the same thing.

Does this help?
