### ISSUE TITLE
Player Fails to Start Stream with MPD

### ISSUE THREAD

**Issue by chevonc** [google/shaka-player#1804]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes. I think it's a timeshift issue but I'm not sure from where

**What version of Shaka Player are you using?**
2.4.6 - latest

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**

Yes
**Are you using the demo app or your own custom app?**
Both

**If custom app, can you reproduce the issue using our demo app?**

yes
**What browser and OS are you using?**

Chrome/Mac
**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What did you do?**
Tried's to play the MPD below.

```
<?xml version="1.0" encoding="utf-8"?>
<MPD xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="urn:mpeg:dash:schema:mpd:2011"
	xmlns:xlink="http://www.w3.org/1999/xlink"
	xsi:schemaLocation="urn:mpeg:DASH:schema:MPD:2011 http://standards.iso.org/ittf/PubliclyAvailableStandards/MPEG-DASH_schema_files/DASH-MPD.xsd"
	profiles="urn:mpeg:dash:profile:isoff-live:2011"
	type="dynamic"
	minimumUpdatePeriod="PT2S"
	suggestedPresentationDelay="PT2S"
	availabilityStartTime="2019-02-14T21:50:13Z"
	publishTime="2019-02-14T21:50:39Z"
	timeShiftBufferDepth="PT20.0S"
	minBufferTime="PT4.0S">
	<ProgramInformation>
		<Title>Guilded Stream</Title>
	</ProgramInformation>
	<Period id="0" start="PT0.0S">
		<AdaptationSet id="0" contentType="video" segmentAlignment="true" bitstreamSwitching="true">
			<Representation id="0" mimeType="video/mp4" codecs="avc1.4d401e" bandwidth="779407" width="640" height="480" frameRate="30/1">
				<SegmentTemplate timescale="15360" initialization="init-stream$RepresentationID$.m4s" media="chunk-stream$RepresentationID$-$Number%05d$.m4s" startNumber="5">
					<SegmentTimeline>
						<S t="157184" d="30720" r="9" />
					</SegmentTimeline>
				</SegmentTemplate>
			</Representation>
		</AdaptationSet>
		<AdaptationSet id="1" contentType="audio" segmentAlignment="true" bitstreamSwitching="true">
			<Representation id="1" mimeType="audio/mp4" codecs="mp4a.40.2" bandwidth="128000" audioSamplingRate="44100">
				<AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2" />
				<SegmentTemplate timescale="44100" initialization="init-stream$RepresentationID$.m4s" media="chunk-stream$RepresentationID$-$Number%05d$.m4s" startNumber="5">
					<SegmentTimeline>
						<S t="450560" d="88064" r="4" />
						<S d="89088" />
						<S d="88064" r="3" />
					</SegmentTimeline>
				</SegmentTemplate>
			</Representation>
		</AdaptationSet>
	</Period>
</MPD>
```

**What did you expect to happen?**

Video to start playing
**What actually happened?**
Player never starts and outputs the following 
![image](https://user-images.githubusercontent.com/684657/52820206-37a40300-3060-11e9-8043-4d36854e4f44.png)

**Comment by theodab** [comment]
The error "Cannot compute timeline live edge without start time" happens when `availabilityStartTime` is not provided. The other error, about it not matching our model, also comes from the same problem. Your manifest obviously does contain `availabilityStartTime`, though, so I'm not quite sure what the problem could be just by looking at it.

It'd help if I could see this problem myself. Can you provide a manifest URI so I can try to reproduce this? You can send it to <shaka-player-issues@google.com> if it's not public information.

**Comment by chevonc** [comment]
Yes, let me work on getting that to you later today. The segments get deleted when the session ends, so will need to regenerate them

**Comment by TheModMaker** [comment]
Can you please provide us with a playable link to the manifest?  Also please try with `v2.5.0-beta3`, it contains changes to live edge calculations that will help with time-sync issues.

**Comment by chevonc** [comment]
I will try the new beta and report back, thanks

**Comment by chevonc** [comment]
I tried the new beta and things seem better. Gonna close for now and will re-open another issue if need be
