### ISSUE TITLE
Safari on IOS with HLS Download

### ISSUE THREAD

**Issue by damianmiles** [google/shaka-player#1807]
Hi, we can successfully download HLS on Safari, and we can play back HLS in safari on IOS , however we get an error when we try to download to the device for local playback. Does anyone know if this should work ? The stream is not encrypted at the moment. It works on an android device with a Dash MPD with DRM no problem.

**Comment by damianmiles** [comment]
@joeyparrish I see this might relate to #997 I see it was from 2017, is there any updates on this? I assume because we are only able to load the HLS using the native player is that why we cant download  it to offline storage?

**Comment by theodab** [comment]
We don't support playback on iOS at the moment, as iOS browsers do not have the MediaSource framework that we are based on. #997 is currently in progress; we're hoping for it to be done by the end of March, but it's a complicated enough change that that's not a guarantee.

**Comment by joeyparrish** [comment]
With #997, we will be able to pass HLS content through to Apple's native HLS implementation for you, but we will not be in charge of playback in that scenario.  It is a convenience feature only, so that applications don't have to write special cases for iOS.  This will not result in offline playback, though, because of the lack of MediaSource support from Apple.

**Comment by damianmiles** [comment]
Hi @joeyparrish and @theodab thanks for the information, I was just a little unclear, but now it's clear. Would something like modernizr help on the IOS Safari browser?

**Comment by theodab** [comment]
We don't really have troubles with feature detection, no. And we try not to add third-party dependencies unless absolutely necessary, to keep our size down.

**Comment by joeyparrish** [comment]
Yes, modernizr would not add the missing MediaSource feature to an iOS browser.
