### ISSUE TITLE
Docker build pipeline

### ISSUE THREAD

**Issue by molszanski** [google/shaka-player#181]
Since shaka requires specific java versions for build and run, and an end user may not have a proper version, the build will fail. 

Moving a build process to docker will solve the issue once and for all and will provide a consistent build between all dev teams.

**Comment by joeyparrish** [comment]
If you want to build from source, you will need Java to run the compiler.  Java is only required to compile the sources, but not to run them.

If you want to run an uncompiled version from github, you only need Python to run ./build/gendeps.sh.

If you want a pre-built binary, we supply those via [npm](https://www.npmjs.com/package/shaka-player) and [cdnjs](https://cdnjs.com/libraries/shaka-player).

**Comment by molszanski** [comment]
I know. Docker could liberate people who want to run the compiler/build but have an incompatible java stack.

**Comment by joeyparrish** [comment]
Thanks for your suggestion.  We'll keep it in mind, and may reconsider in future if there is demand for it.
