### ISSUE TITLE
Stilted playback of DRM Adaptive stream on Tizen

### ISSUE THREAD

**Issue by stuartflanagan** [google/shaka-player#1812]
I am seeing some playback that halts every few seconds on Tizen 4 TV.

I am testing with ABR set to disabled but am still seeing very consistent interrupted playback.

I have seen some discussion about various issues with Tizen and Shaka. I am just wondering if you have found any configurations that help to resolve this playback issue with Tizen so far?

Any help you have would be appreciated.

**Comment by stuartflanagan** [comment]
Sorry I do not think my test was correct. I can confirm the playback is smooth when I switch ABR to disabled with configuration:

```
abr: {
enabled: false
},
```

**Comment by stuartflanagan** [comment]
I did try setting the `switchInterval` to a higher value but this did not help.

It seems to be hit and miss actually. Sometimes it plays back smoothly and other times it jumps or halts every few seconds. If you are happy to have a look I can email a test file with a test manifest and key.

Kind regards,

Stuart

**Comment by stuartflanagan** [comment]
Any chance of some information regarding this?

Please let me know if I should create a bug instead.

**Comment by joeyparrish** [comment]
@stuartflanagan, yes, please file a bug with information we can use to reproduce the issue.  Please make sure to mention in the report whether this is live or VOD content.  Thanks!
