### ISSUE TITLE
Widevine request payload is empty

### ISSUE THREAD

**Issue by dusan-turajlic** [google/shaka-player#1814]
Hi,

I'm trying to implement Widevine playback using Shaka. I had no problem with Playready I just followed the [documentation](https://shaka-player-demo.appspot.com/docs/api/tutorial-drm-config.html) and it worked. But Widevine not so much.

This is what I do.

```javascript
if (drm) {
    config.drm = {
        "servers": {
            "com.widevine.alpha": widevineLicenseServerURL,
            "com.microsoft.playready": playReadyLicenseServerURL
        }
    };

    this._player.getNetworkingEngine().registerRequestFilter(function(type, request) {
        if (type === shaka.net.NetworkingEngine.RequestType.LICENSE) {
            request.headers["my-header"] = "headerData";
            request.headers["my-second-header"] = "headerData";
        }
    });
}
```
This workes fine for Playready. But when I try it for widevine it docent fail, it docent give me any errors it just docent play anything. I checked the network tab in my chrome inspector and I saw that the second request to the license server is missing request payload. I don't know how and I don't know why.

I tested the same code but with a demo widevine encrypted stream and that worked just fine the request payload was there and everything.

**Comment by joeyparrish** [comment]
Is the Widevine license server on another domain?  If so, it's a cross-origin request, and the server must explicitly allow the headers you're adding.  You can find detailed docs on Cross-Origin Resource Sharing (CORS) on MDN: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

In short, the addition of request headers triggers an `OPTIONS` request (not `GET` or `POST`), and the server's response dictates what headers should be allowed.  If your headers aren't on the list provided by the server (or no list was provided), then the license request will be blocked by the browser.

Look more closely at the "empty" requests in the network tab.  Is this what's happening?

**Comment by dusan-turajlic** [comment]
Hi @joeyparrish thank you for your quick reply. Basically what I have done is disabled security on my chrome so I can test without Cross-Origin errors appearing in the console. The server I am making the request to does allow for the headers and requires them to authenticate and provision. I have looked very closely at the request. The weird thing is the DRM server actually replies `status: "OK"` but the payload is empty.

If you are wondering if the disabled security thing may be an issue I can assure you it is not because I deployed the same code to a server with a valid SSL certificate and the same problem occurs (empty request payload).

**Comment by dusan-turajlic** [comment]
@joeyparrish I noticed I did not fully answer your question. Yes, the `OPTIONS` request does happen and it does have my headers as allowed headers. The issue is in the `POST` request that happens after the `OPTIONS` request. The `POST` is supposed to have a request payload with some binary information that makes Widevine work, that request payload is completely empty.

**Comment by joeyparrish** [comment]
Do you have any request filters that alter `request.body`?  A bug in a request filter could cause this.

You can also debug in `DrmEngine`, in `sendLicenseRequest_`.

https://github.com/google/shaka-player/blob/d2069dcd7642e788164d52a56bc6103df86a396b/lib/media/drm_engine.js#L1176-L1181

If the request body is non-empty at that point, but empty later, we can further narrow down the cause.  If it *is* empty at that point, though, we can point the blame to the Widevine CDM instead of the JavaScript code.

**Comment by dusan-turajlic** [comment]
@joeyparrish Thank you for your help. Please don't close this question yet. I am not currently working on this for this sprint but I will start with this as soon as my tasks are done. I will get back to you by Friday at the latest

**Comment by dusan-turajlic** [comment]
@joeyparrish I have tested this and it looks like the body is not empty. I put a breakpoint in the code and it seas this 
<img width="316" alt="screenshot 2019-03-02 at 16 41 46" src="https://user-images.githubusercontent.com/45139784/53683513-3fbf9c00-3d0a-11e9-9013-9709e76e36ad.png">
Is that what it is supposed to have in it?

**Comment by joeyparrish** [comment]
Yes, that's correct.  The 2-byte POST is a valid request from the Widevine CDM.  It should be followed by another request from the CDM with a longer payload.

Can you confirm that the license server is responding to this request?  And that the CDM accepts the response without generating an error through Shaka Player?

**Comment by dusan-turajlic** [comment]
@joeyparrish Hi I stepped through the code in using the chrome inspector and I noticed that the request is made but in this part
https://github.com/google/shaka-player/blob/d2069dcd7642e788164d52a56bc6103df86a396b/lib/media/drm_engine.js#L1190-L1191
it runns the `Promise.reject();` what does that mean? I am a bit confused because there are no errors in the chrome inspector and the CDN team say that my request to the licence server is not visable in the log.

**Comment by TheModMaker** [comment]
That means the `DrmEngine` instance is destroyed (or thinks it's destroyed).  Can you set a breakpoint in `DrmEngine.prototype.destroy` to verify it isn't called?  If it is called can you post the stack trace?  Also how are you interacting with the Player?  Are you just calling `configure` and `load` and playing content?  Do you ever call `load` a second time or call `unload`, `detach`, or `destroy`?

Alternatively can you host your demo or a simple repro page so we can debug it?  It would be much easier if we could step through it ourselves.  You can send it privately to shaka-player-issues@google.com if you prefer.

**Comment by dusan-turajlic** [comment]
@TheModMaker I sent an email to shaka-player-issues@google.com and hope to hear back from you soon.

**Comment by TheModMaker** [comment]
Your license server returns a response containing JSON.  You need to create a response filter to unwrap it before it is sent to the browser.  The initial request is 2 bytes, not empty.

If I add an `error` event handler to the Player object, I immediately get a `DRM.LICENSE_RESPONSE_REJECTED` error indicating the bad response data.  Take a look at the [license wrapping tutorial](https://shaka-player-demo.appspot.com/docs/api/tutorial-license-wrapping.html) for more info.

```js
this._player.getNetworkingEngine().registerResponseFilter((type, response) => {
  if (type == shaka.net.NetworkingEngine.RequestType.LICENSE) {
    const json = shaka.util.StringUtils.fromUTF8(response.data);
    response.data = shaka.util.Uint8ArrayUtils.fromBase64(JSON.parse(json).license);
  }
});
```
