### ISSUE TITLE
Version 2.5.0-beta3 compiled release reports v2.5.0-beta3-uncompiled

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#1816]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.0-beta3

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
No tested

**Are you using the demo app or your own custom app?**
Demo app

**If custom app, can you reproduce the issue using our demo app?**
Demo app

**What browser and OS are you using?**
Chrome 72 / Ubuntu 18.04

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What did you do?**

Open https://v2-5-0-beta3-dot-shaka-player-demo.appspot.com/demo/#asset=https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd;lang=es-ES;build=compiled

**What did you expect to happen?**
The header reports Shaka Player v2.5.0-beta3

**What actually happened?**

The header reports Shaka Player v2.5.0-beta3-uncompiled

With v2.4.7 works correctly https://v2-4-7-dot-shaka-player-demo.appspot.com/demo/#asset=https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd;lang=es-ES;build=compiled

**Comment by joeyparrish** [comment]
You are correct!  Thank you for pointing this out.

I compared the results on appspot with a local build.  The effect is seen locally, so it's not an issue with our deployment process.

**Comment by joeyparrish** [comment]
Our build script had a regression in 6b1ca2d229b855e4064d7d13dc0918bd020eab43, which was a complicated merge from a private branch.  It should be easy to fix.
