### ISSUE TITLE
VAST, VPAID, VMAP, Google IMA and Pip support.

### ISSUE THREAD

**Issue by amanrajveer** [google/shaka-player#1818]
Hello, I found this player amazing among all. Wanted to know that does it support VAST, VPAID, VMAP, Google IMA?
And
Does it has Picture-in Picture feature to keep a minimized player in the corner of the screen when user scroll too far? (This keeps the Player visible to users in any case.)

**Comment by TheModMaker** [comment]
> Hello, I found this player amazing among all. Wanted to know that does it support VAST, VPAID, VMAP, Google IMA?

We don't have anything built-in to do it, but you could probably build something on top of Shaka Player to do it.  You could create a second video element to use with a specific ad API and pause the Shaka Player video while an ad is playing.

We also have plans to add something to the UI involving ads, but haven't planned it or scoped what it will cover.  You can also follow #1169 for a tutorial to help with that.

> And
> Does it has Picture-in Picture feature to keep a minimized player in the corner of the screen when user scroll too far? (This keeps the Player visible to users in any case.)

The UI has an option to add a PIP button for the out-of-page browser-based PIP.  This is provided by the browser to show a window on top of other windows.  We do not provide an option for in-page PIP.
