### ISSUE TITLE
Audio tracks getting filtered out

### ISSUE THREAD

**Issue by sanbornhnewyyz** [google/shaka-player#182]
Calling player.getAudioTracks() is not returning the full set of audio tracks listed in the manifest. This content (http://cdn-origin94-dit1-vod.quickplay.com/vod/product/s/qpmezzdisneycomocddashcontentfeature/master.ism/master.mpd)  is protected but it's enough to reproduce this issue. There two audio tracks but only one gets returned when that method is called.

**Comment by sanbornhnewyyz** [comment]
Quick follow up: This content: (http://cdn-origin94-dit1-vod.quickplay.com/vod/product/u/qpmezzdisneycomocdclearfeature/master.ism/master.mpd) shows two audio tracks but they show up as the same language even though in the manifest they don't.

**Comment by tdrews** [comment]
Thanks for the report. I believe these are both consequences/bugs of `@group` support.

For (1), if you log `player.videoSource_.streamSetsByType.getAll('audio')` do you see that some StreamInfos have `allowedByKeySystem` set to `false` (from the `StreamSetInfo` that doesn't show up in `getAudioTracks`)?

For (2), do you see the warning `AdaptationSet groups should have the same language.`? We could (probably should) lift this restriction.

**Comment by sanbornhnewyyz** [comment]
(1) Looking at `player.videoSource_.streamSetsByType.getAll('audio')` I see that there are two `shaka.media.StreamInfo` objects and the one is not showing up in `player.getAudioTracks()` has `allowedByKeySystem` set to `false`. 

I also noticed that the language is specified as 'th' on the `shaka.media.StreamSetInfo` even though only one track is thai and the other is punjabi. I suppose that's related to (2). 

Finally, I'm curious why when I call `this.videoSource_.streamSetsByType.getAll('audio')` the array returned includes a `shaka.media.StreamSetInfo` with `contentType` = `video`

(2) Yes that shows up in the log.

**Comment by tdrews** [comment]
Thanks for confirming (1) and (2). The bug is that the player squashes multiple AdaptationSets with different languages (and the same group) into a single StreamSetInfo. The player should only squash AdaptationSets together if the languages are the same. 

> Finally, I'm curious why when I call this.videoSource_.streamSetsByType.getAll('audio') the array returned includes a shaka.media.StreamSetInfo with contentType = video

I should have wrote `get('audio')`.

**Comment by sanbornhnewyyz** [comment]
O, okay, that makes more sense. Thanks for the update.
