### ISSUE TITLE
DASH CPIX support for PlayReady

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#1827]
I tried to found if ShakaPlayer support CPIX but I don't find any informacion. Is it supported?

https://dashif.org/docs/CPIX2.1/PDF/Index.pdf

**Comment by joeyparrish** [comment]
CPIX is not part of DASH clients.  It is for encoders and packagers and DRM license servers to exchange keys at content preparation time.

Section 3 of the CPIX doc states (emphasis added by me):

> There is no assumption on the entities exchanging this information but **it is not expected that a client device will use this exchange format**. The goal is to allow entities involved in the **content preparation workflow** to get the content protection information so that, for example a DASH MPD can be generated with all content protection information.

Does this answer your question?

**Comment by avelad** [comment]
Thanks @joeyparrish
