### ISSUE TITLE
preload: metadata

### ISSUE THREAD

**Issue by odedhutzler** [google/shaka-player#1829]
hi,

I saw you are planning on a preload API.

is there a way to only load manifest using shaka? (something similar to preload: metadata on the video element).

Thank,
Oded

**Comment by TheModMaker** [comment]
No, we have not worked on the preload API at all yet.  You should follow #880 for any updates.

**Comment by vaage** [comment]
@odedhutzler, thanks for asking. To build off of what @TheModMaker said, we are still thinking through how a preload API will work.

With everything else going on (Shaka Embedded, Shaka UI, src=) we have not had time to scope-out what the requirements for pre-loading need to be. For example, we don't know if we only need to support pre-loading one piece of content or multiple pieces of content. @joeyparrish and I have casual conversations about the requirements, but have not sketched out what they will be yet.

What I can tell you is that some foundational work is being done. The work for #816 is providing us with a framework to handle loading, the plan is to later extend it to provide the "path" for pre-loading. In 2.6, we are going to take-on some large refactorings, after that we should be in a better position to add more ambitious features.

It this answers your question, please feel free to close the issue and follow the conversations in #880.

**Comment by odedhutzler** [comment]
thanks , i will follow #880
