### ISSUE TITLE
Exception after destroying shaka player

### ISSUE THREAD

**Issue by carcharodoncarcharias511** [google/shaka-player#183]
I am playing a single .mpd stream. I have modified the player code to bubble up the 'ended' event when the stream finishes playing. My application taps this 'ended' event to destroy the player. However, I hit the following exception after the destroy call successfully returns. 

Uncaught TypeError: Cannot read property 'currentTime' of null
 
After some investigation I noticed when the stream ends, the 'ended' event is fired. However, there is also a 1 sec timer started - update timer. In my case, this timer seems to run even though there is no content left to play. When the 'onUpdate_' callback is invoked, somewhere it hits the exception mentioned above. 

My question, is what is the ideal way to invoke 'destroy' i.e. when should I invoke it - the following events are not really ideal Adaptation, Buffering, Error, SeekChange. 

Also, why is that timer still running ? If there is no more content to play, shouldn't it stop ( and this is not live content) ?

P.S. I am not doing rapid create/destroy of the player as was done in #151. Also, the exceptions reported there seem different from what I am seeing.

**Comment by tdrews** [comment]
The `'ended'` event is an internal event and is fired when a stream (audio or video) is "finished" fetching data and not when the video is actually over. You can just use the `'ended'` event fired from the video element itself (http://www.w3.org/TR/2011/WD-html5-20110113/video.html#event-media-ended) to detect when the video is over.

**Comment by carcharodoncarcharias511** [comment]
Ah thanks. The 'ended' is working for me on the video element.
