### ISSUE TITLE
Chromecast button does not become visible on http (works fine on https)

### ISSUE THREAD

**Issue by frhi** [google/shaka-player#1830]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.4.7

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Not sure

**Are you using the demo app or your own custom app?**
Both

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Chrome on Windows

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What did you do?**

see below

**What did you expect to happen?**
see below

**What actually happened?**

Chromecast does not appear to work when using the shaka player on a web page loaded via http. The chromecast caststatuschanged event never seems to fire, and the chromecast button never becomes visible. (You can still use Chrome's "Cast ..." menu though, and it works fine.) If you change to using https then the chromecast button appears and works fine.

I was hoping the chromecast button would be displayed and work fine over both http and https.

Looks like the shaka demo site forces https, so it always works there. I've copied the demo to my own site, and when I load it over http, the chromecast button never appears (same as when I use my custom app).

**Comment by TheModMaker** [comment]
Can you try with the latest from `master`?  It may have already been fixed by d02759bdeaac88d4cda16389281fd707093229f4.

**Comment by joeyparrish** [comment]
It could be that some API used by the Cast SDK requires a secure origin.  This is the case for EME, but I'm not familiar with the underlying APIs used by Cast.

**Comment by frhi** [comment]
@TheModMaker I'm not setup to compile the shaka player (i've always just grabbed compiled versions). Is there a way to get a compiled version of the latest that would include the change you mentioned?

**Comment by TheModMaker** [comment]
To just try it out, you could just pull the version from our nightly hosted demo <https://nightly-dot-shaka-player-demo.appspot.com/dist/shaka-player.ui.debug.js>.

**Comment by frhi** [comment]
@TheModMaker The nightly build appears to have the same issue. On https the chromecast button appears like you'd expect, but when loaded using http, the chromecast button does not appear.

**Comment by frhi** [comment]
So I noticed the following webpage: https://developers.google.com/cast/docs/chrome_sender/
says: "Warning: Chrome sender apps need to support HTTPS to maintain Cast compatibility, as Chrome is deprecating support for the Presentation API on insecure origins."
... which I think is what joeyparrish was getting at. Assuming that page is applicable to this situation, then I guess that explains it?

**Comment by joeyparrish** [comment]
Yes, that's right.  Our cast support is dependent on the Cast SDK, which is dependent on that API and its restrictions in Chrome.
