### ISSUE TITLE
python build/all.py gets stuck

### ISSUE THREAD

**Issue by Anirudh58** [google/shaka-player#1835]
I am using Ubuntu 16.04. I am trying to set up shaka player following these steps. 
https://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html

running python build/all.py gets stuck after a few lines. 

[INFO] Generating Closure dependencies...
npm WARN deprecated istanbul@0.4.5: This module is no longer maintained, try this instead:
npm WARN deprecated   npm i nyc
npm WARN deprecated Visit https://istanbul.js.org/integrations for other alternatives.
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated boom@4.3.1: This version is no longer maintained. Please upgrade to the latest version.

I've tried explicitly mentioning python2 as well but observed same result.  Please let me know if there is something i'm missing.

**Comment by joeyparrish** [comment]
@Anirudh58, I assume you found a solution.  Can you share what you found, in case others have a similar issue and come across this later?

**Comment by Anirudh58** [comment]
Yes sure. I think I had 2 problems. 
1) I had used sudo in my earlier commands which seemed to have locked certain files. 
2) My default python version was set to 3,  so running `python build/all.py` might have caused some problems because shaka required 2.7. Not sure about this. 

Resolve steps:
1) Fresh clone `git clone https://github.com/google/shaka-player.git` & cd into shaka-player.
2) Run `./build/all.py`

**Comment by Anirudh58** [comment]
Hello Mr Joey

I have an idea for a project with shaka-player. I need more specifics. I am
not getting enough clarity from the documentation. Is it possible to get in
touch with you and discuss further?

Regards,
Anirudh

**Comment by joeyparrish** [comment]
Is this a conversation you would feel comfortable having publicly on GitHub?

**Comment by Anirudh58** [comment]
It wouldn't really benefit anyone. I wouldn't mind but preferably not
public.

**Comment by joeyparrish** [comment]
You can find my email address in the CONTRIBUTORS file.

**Comment by Anirudh58** [comment]
Sure thanks. I'll drop you a mail there.
