### ISSUE TITLE
Shaka Error DRM.FAILED_TO_GENERATE_LICENSE_REQUEST when trying to play Playready encoded content

### ISSUE THREAD

**Issue by cristioltean** [google/shaka-player#1837]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

**What version of Shaka Player are you using?**

v2.4.7-uncompiled
**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `master`?**

**Are you using the demo app or your own custom app?**
yes

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
Edge , Windows 10

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What did you do?**

Tried to played the dash content with playready encryption but it fails.

**What did you expect to happen?**
Playback to be normal

**What actually happened?**

I receive this message when trying to play the content .

Shaka Error DRM.FAILED_TO_GENERATE_LICENSE_REQUEST (SystemCode:0x80041301,TypeError: SystemCode:0x80041301,) 

If I click the link I am sent to this message:

FAILED_TO_GENERATE_LICENSE_REQUEST | 6006 | number | The CDM was unable to generate a license request for the init data it was given.  The init data may be malformed or in an unsupported format.  error.data[0] is an error message string from the browser.  error.data[1] is the error object from the browser.  error.data[2] is a string with the extended error code, if available.
-- | -- | -- | --

**Comment by avelad** [comment]
I can reproduce the issue with v2.5.0-beta3 
According the drm provider in v2.0.3 the issue doesn't happen due to changes in the pssh.

**Comment by johnsim** [comment]
@avelad I would be interested in knowing more about the pssh changes you mention. Could you reach out to me? johnsim@microsoft.com

**Comment by avelad** [comment]
I just tested with Edge 18 in v2.02, v2.0.3 and v2.5.0-beta3 and It doesn't work.
With Edge 15 works in 2.02, v2.0.3 but not in v2.5.0-beta3
It a bit curious...

**Comment by avelad** [comment]
Note: the same manifest with Widevine in Chrome/Firefox/Opera work without problem.

**Comment by avelad** [comment]
The stream works with http://reference.dashif.org/dash.js/v2.9.3/samples/dash-if-reference-player/index.html 

So, I think that is not a browser error

**Comment by cristioltean** [comment]
Hello  , 

I have sent an email to shaka-player-issues@google.com  with more data : mpd link , license serve url.
Also a screenshot with the decode initData used when doing a session.generateRequest call.
It will help us allot if you can provide some information of how this initData is generated , I believe that the player crashes because it cannot get exact structure it needs to create it.
Regards, 

Cristian

**Comment by johnsim** [comment]
@cristioltean - The error code indicates that the init data is incorect. If you could provide me with the information you sent to shaka-player-issues@google.com we can help determine the root cause

**Comment by cristioltean** [comment]
Hi @johnsim if you can provide me an email address or another way to send you the info I will do it ASAP.

**Comment by avelad** [comment]
@cristioltean in a previous comment 

> @avelad I would be interested in knowing more about the pssh changes you mention. Could you reach out to me? [johnsim@microsoft.com](mailto:johnsim@microsoft.com)

@cristioltean ,in this comment you have the mail.

**Comment by cristioltean** [comment]
@avelad Thanks Alvaro , I have forwarded the email to you @johnsim

**Comment by johnsim** [comment]
Thanks, @cristioltean, @avelad - the Microsoft PlayReady team is evaluating the data now. I will update this issue with our findings.

**Comment by avelad** [comment]
@johnsim , do you have any update?

**Comment by cristioltean** [comment]
Hello Alvaro, 

I was talking with John via email and currently we are trying to understand  why the initData  used to generate a license request is not compatible for Shaka.

Latest question from him was if this Star channel is working with Widevine , as far as I know in your tests Widevine is working fine.

**Comment by avelad** [comment]
@cristioltean , Yes, Widevine is working without problem in Chrome, Firefox and Opera.

**Comment by TheModMaker** [comment]
The `pssh` data in the media is bad.  It contains a valid Widevine `pssh` box, but the `pssh` box for PlayReady has an invalid System ID.  The correct System ID is "9a04f079-9840-4286-ab92-e65be088**5**f95" but you have "9a04f079-9840-4286-ab92-e65be088**9**f95".

**Comment by avelad** [comment]
@TheModMaker, Would it be possible to add a more explicit error code for when the content does not have a valid system ID?

**Comment by cristioltean** [comment]
Hi Alvaro , what I can see it's that the the System id in the init segment indeed is not  9a04f079-9840-4286-ab92-e65be0889f95

<ProtectionSystemHeaderBox Size="696" Type="pssh" Version="0" Flags="0" Specification="cenc" Container="moov moof" SystemID="0x9A04F07998404286AB92E65BE0889F95">

I will check this with R&D. 

Thanks @TheModMaker

**Comment by TheModMaker** [comment]
@avelad We don't like assuming init data formats or System IDs.  That could be a valid System ID for some unknown key system, so we don't want to throw an error for it.  We just give the data to the browser and let it handle it.  But we could use the data in the manifest to validate the expected System IDs (at least for the ones we know about).  You could file a feature request for that.

**Comment by cristioltean** [comment]
Hello , indeed the system id was not correctly set in the init segment which was causing this , after fixing the typo playback is working ok .Closing ticket for now.
thanks for the help.
