### ISSUE TITLE
Recognize and reject AES-128 HLS content with meaningful error

### ISSUE THREAD

**Issue by macoybarayan** [google/shaka-player#1838]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5-Beta

**Can you reproduce the issue with our latest release version?**
No

**Can you reproduce the issue with the latest code from `master`?**
No

**Are you using the demo app or your own custom app?**
Both Custom and Demo

**If custom app, can you reproduce the issue using our demo app?**
https://shaka-player-demo.appspot.com/demo/#asset=https://s3-ap-southeast-1.amazonaws.com/vdyopublic/6109_593164a006664/play.m3u8;lang=en-US;build=uncompiled

**What browser and OS are you using?**
Firefox

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**
https://s3-ap-southeast-1.amazonaws.com/vdyopublic/6109_593164a006664/play.m3u8

**What did you do?**
I created an offline download but fails to download. I also tested the manifest in the demo app but same error I got.

**What did you expect to happen?**
I should be able to download offline.

**What actually happened?**
I tried to use the offline download with manifest in hls but I got 4030 error, Shaka Error MANIFEST.HLS_COULD_NOT_PARSE_SEGMENT_START_TIME ()

**Comment by vaage** [comment]
Hello @macoybarayan, it looks like our parser is failing to parse your content (therefore neither offline nor online playback will be possible).

It looks like we are failing at the sync byte while parsing the start time from `https://s3-ap-southeast-1.amazonaws.com/vdyopublic/6109_593164a006664/800k-00000.ts`, we are seeing `0x5F` when we expect to see `0x47`.

How did you generate your content?

**Comment by TheModMaker** [comment]
It looks like your content is encrypted and we don't support AES-128 (see #850).  For some reason, we aren't detecting it as encrypted.

**Comment by joeyparrish** [comment]
The media playlists have `#EXT-X-KEY:METHOD=AES-128,URI="800k.key"`, so we should be able to recognize and reject that as unsupported.  #850 is already filed to track adding AES-128 support.  So we'll make this issue about correctly recognizing and rejecting the content until #850 is implemented.

@macoybarayan, I'm sorry for the confusion.  We'll correct the parsing and surface a more meaningful error code until we *do* support it.

**Comment by kevinscroggins-youi** [comment]
Related to https://github.com/google/shaka-player/issues/1782
