### ISSUE TITLE
Where can I consult roadmap due dates?

### ISSUE THREAD

**Issue by adgllorente** [google/shaka-player#1840]
Hi,

I've been looking for information about roadmap due dates and I haven't found anything related. In the milestones page (https://github.com/google/shaka-player/milestones) they aren't configured neither. Is there any public page where I can consult release dates? Moreover, where is version 2.5.0 expected to be released? Where can I get more information related with this topic?

Thank you so much.

**Comment by joeyparrish** [comment]
We have not yet published a roadmap, but I am working on that.  We expect to release v2.5.0 around the end of March.

**Comment by adgllorente** [comment]
Good to know! Thank you so much for the information 👍

**Comment by javiSBP** [comment]
Hi! Any news about v2.5.0 release date?

Thank you!

**Comment by vaage** [comment]
@javiSBP for information about the 2.5 release, please consult #1480 (The 2.5 release issue) and #816 (the main issue blocking 2.5).
