### ISSUE TITLE
Seeking in live streams

### ISSUE THREAD

**Issue by vikasbnsl** [google/shaka-player#1848]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
2.4.7

**Can you reproduce the issue with our latest release version?**
yes

**Are you using the demo app or your own custom app?**
demo

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
osx chrome

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
no

**What are the manifest and license server URIs?**
if asked then will share on shaka-player-issues@google.com

**What did you do?**
play and you will see that the seek bar does not show the dvr lenght

**What did you expect to happen?**
seek bar should show dvr content in it

**What actually happened?**

I am trying to play dvr enabled live stream video on shaka player.
DVR is 2 hours long and it is not showing into the seek bar of shaka player as show in the screen shot below. However the manifest has the dvr content (also attached) please help.

<img width="644" alt="Screenshot 2019-03-19 at 5 45 33 PM" src="https://user-images.githubusercontent.com/10242300/54605265-d90ee200-4a6e-11e9-8d57-bcc14c7dd914.png">

[manifest.txt](https://github.com/google/shaka-player/files/2983217/manifest.txt)

**Comment by joeyparrish** [comment]
The browser's native controls are not able to correctly display the seek bar for live content.  For this, you will need custom controls (the only option in `v2.4.x`) or the Shaka Player UI library (in `master` branch & `v2.5.0-beta3`, also soon to be in `v2.5.0`'s final release).  Here's a tutorial on the UI to get you started: https://nightly-dot-shaka-player-demo.appspot.com/docs/api/tutorial-ui.html

Does this help?

**Comment by vksbansal** [comment]
**that sure helps a lot. many and many thanks, @joeyparrish**

**Comment by vksbansal** [comment]
Just a quick question 

i am trying to get the available seek time of the live stream. e.g. i have a stream with 2 hours of DVR recording so how can I get the start time of the stream.

please help... 

Many thanks,

**Comment by vaage** [comment]
@vikasbnsl I will be happy to help. In the future, please do not hesitate for opening new issues for questions. Having issues focus on one question allows others in the communicate the opportunity to find the issue when it matches their question.

On `shaka.Player` there is an method called `seekRange`. It will allow you to get _"the seekable range for the current stream"_. [Here](https://shaka-player-demo.appspot.com/docs/api/shaka.Player.html) are the docs for Player, if you search for "seekRange" you will find the documentation for it.

**Comment by vksbansal** [comment]
@vaage many thanks, will keep your suggestion in mind for future. many thanks again :)

Shaka fan,
Vikas Bansal
