### ISSUE TITLE
Update Closure In Build Tools

### ISSUE THREAD

**Issue by vaage** [google/shaka-player#1852]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
 Yes

**Is your feature request related to a problem? Please describe.**

This is related to the problem described in #1792 but more over, a newer version of closure will contain updated polyfills and stricter type detection/enforcement.

**Describe the solution you'd like**

If possible, updating to the newest stable version would be ideal. But if not possible, updating to a newer version number would provide more-than-minor benefits in terms of polyfils and type-checking.

**Describe alternatives you've considered**

We have regularly talked about alternative solutions for type-checking (such as using typescript) but so far they would require too many resources and would not necessarily resolve polyfill issues.

**Additional context**

**Comment by joeyparrish** [comment]
This has been completed for some time already, but we forgot to tag & close the issue.

We now pull Closure Compiler and the Closure Library from npm, and updating is relatively easy.  We are no longer years behind.
