### ISSUE TITLE
Using Widevine L1 in Android WebView

### ISSUE THREAD

**Issue by yethie** [google/shaka-player#1854]
Hello!
I'm using the Shaka Player to play Widevine protected content in Chrome on Android. I need to use HW_SECURE_ALL to enforce HDCP and it works fine in Chrome. However when I switch to Android System WebView (using cordova) the only robustness level that seems to be supported is SW_SECURE_CRYPTO. Have you ever see this behavior in your experience? Do you know where I can search for documentation or support on this?
Thanks!

**Comment by joeyparrish** [comment]
I don't know any reason it shouldn't work, but we're at the mercy of Chrome's implementation of WebView for Android.  I would recommend filing a Chrome issue (http://crbug.com/), or commenting on one of these existing issues I found, which may be related:

"requestMediaKeySystemAccess for "com.widevine.alpha" fails" - https://crbug.com/797914
"AwPermissionManager::GetPermissionStatus() always returns denied" - https://crbug.com/489454
"embedded surfaceview for L1 embedded content in WebView" - https://crbug.com/607622

Does this help?

**Comment by yethie** [comment]
Thank you Joey!
