### ISSUE TITLE
Emsg Event not triggering

### ISSUE THREAD

**Issue by phildupuis** [google/shaka-player#1856]
Hi !
I'm presently having some trouble with EventStream that does not seem to be triggering any event. By adding an eventListener on the player for `emsg` event type with the manifest below, I was expecting two events to be triggered at seconds 2 and 5 after the beginning of the video. After numbers of different manifests I tried, nothing seems to do the trick to trigger any `emsg` event. I even tried to take exact examples from Dash documentation : https://standards.iso.org/ittf/PubliclyAvailableStandards/c065274_ISO_IEC_23009-1_2014.zip 

This manifest is triggering `emsg` events on other Dash players. Maybe I don't get the exact syntax for Emsg Box and something is wrong with this manifest, but I can't figure out what it is.

```<?xml version="1.0" encoding="UTF-8"?>
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" 
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" maxSegmentDuration="PT1.003S" mediaPresentationDuration="PT23M34.109792S" minBufferTime="PT0S" profiles="urn:mpeg:dash:profile:isoff-live:2011" type="static">
   <Period id="1" start="PT0S">
      <BaseURL>https://my-base-url</BaseURL>      
      <EventStream schemeIdUri="urn:mpeg:dash:event:callback:2015" timescale="1" value="1">
         <Event id="2" messageData="https://some-reporting-urn1" presentationTime="2"/>
         <Event id="3" messageData="https://some-reporting-urn2" presentationTime="5"/>
      </EventStream>
      <AdaptationSet bitstreamSwitching="true" contentType="video" group="1" id="1" maxFrameRate="30000/1001" maxHeight="1080" maxWidth="1920" mimeType="video/mp4" par="16:9" segmentAlignment="true" startWithSAP="1">
         <SegmentTemplate initialization="S!d0FEQVNIVP7...8Bnw__/QualityLevels($Bandwidth$)/Fragments(video=Init)" media="S!d0FEQVNIVP7...8Bnw__/QualityLevels($Bandwidth$)/Fragments(video=$Time$)" timescale="10000000">
            <SegmentTimeline>
               <S d="10010000" r="9"/>
               <S d="2000000" r="0"/>
            </SegmentTimeline>
         </SegmentTemplate>
         <Representation bandwidth="325950" codecs="avc1.4d4015" frameRate="30000/1001" height="270" id="dzE--QSf" sar="1:1" width="480"/>
         <Representation bandwidth="631425" codecs="avc1.4d401e" frameRate="30000/1001" height="360" id="dzGBogmf" sar="1:1" width="640"/>
         <Representation bandwidth="1236504" codecs="avc1.4d401e" frameRate="30000/1001" height="480" id="dzEY3hKf" sar="1:1" width="720"/>
         <Representation bandwidth="1939045" codecs="avc1.4d401f" frameRate="30000/1001" height="540" id="dzFllh2f" sar="1:1" width="960"/>
         <Representation bandwidth="3747150" codecs="avc1.64001f" frameRate="30000/1001" height="720" id="dzFOLTmf" sar="1:1" width="1280"/>
         <Representation bandwidth="4945982" codecs="avc1.64001f" frameRate="30000/1001" height="720" id="dzE-eEuf" sar="1:1" width="1280"/>
         <Representation bandwidth="5555565" codecs="avc1.640028" frameRate="30000/1001" height="1080" id="dzFtxVSf" sar="1:1" width="1920"/>
      </AdaptationSet>
      <AdaptationSet bitstreamSwitching="true" contentType="audio" group="2" id="2" lang="und" mimeType="audio/mp4" segmentAlignment="true">
         <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
         <SegmentTemplate initialization="S!d0FEQVNIVP7...8Bnw__/QualityLevels($Bandwidth$)/Fragments(audio_482_und=Init)" media="S!d0FEQVNIVP7...8Bnw__/QualityLevels($Bandwidth$)/Fragments(audio_482_und=$Time$)" presentationTimeOffset="14" timescale="32000">
            <SegmentTimeline>
               <S d="32767" r="0" t="14"/>
               <S d="31744" r="0"/>
               <S d="31745" r="0"/>
               <S d="32767" r="0"/>
               <S d="31745" r="0"/>
               <S d="31744" r="1"/>
               <S d="32767" r="0"/>
               <S d="31745" r="0"/>
               <S d="31744" r="0"/>
               <S d="7168" r="0"/>
            </SegmentTimeline>
         </SegmentTemplate>
         <Representation audioSamplingRate="32000" bandwidth="40000" codecs="mp4a.40.2" id="dyHiAZ8."/>
      </AdaptationSet>
   </Period>
</MPD>
```

Do you know what is wrong with this manifest or can you point me a manifest with EventStream and sub Event that should be triggering `emsg` events ?

Thank you :)

**Comment by vaage** [comment]
@phildupuis thank you for reaching out to us for help. Few on the team are Dash Manifest experts and stepping through the manifest parser is the best way for us to understand how your content is being treated. By chance do you have your manifest and content hosted somewhere we reach using the demo page?

**Comment by TheModMaker** [comment]
We do not fire `emsg` events for `EventStream` elements.  Instead we fire `timelineregionenter` and `timelineregionexit` events for when we enter and leave a region respectively.  We fire an `emsg` event when we see an `emsg` box in the segments, but only if it is signaled in the manifest with an `InbandEventStream` element.

**Comment by phildupuis** [comment]
Thank you so much @TheModMaker, that was exactly it. I think what mixed me up is that I'm presently trying to catch these events on chromecast with CAF Receiver and the only event type that seems good for my case in this framework is the `EMSG_EVENT`. Maybe CAF should be implementing `timelineregionenter` and `timelineregionexit` or maybe I'm not listening to the right event there too.

I don't know if you have any idea on that, but I'll close this issue. Thx !
