### ISSUE TITLE
Apply playRangeStart after playback has started?

### ISSUE THREAD

**Issue by jkringen** [google/shaka-player#1863]
We've got a client that is requesting a video to start playback normally at 0 starting position, but when it loops they want it to loop over a specific range instead of over the entire video.

I tried to apply a new play range configuration after playback started, but upon looping, the player went back to the actual start of the clip instead of what I specified in my playRangeStart value.

My config command that I applied after playback started was:
shakaPlayer.configure({playRangeStart: 135, playRangeEnd: Infinity});

Is it currently possible to achieve this desired behavior of letting a video start normally but then altering the config after playback starts to define a different playRangeStart to alter the looping behavior?

**Comment by vaage** [comment]
@jkringen Thank you for reaching out to us with your question. Shaka player does not handle the looping behavior, we leave that to the browser. As a general practice, if we can leave something to the browser, we do.

You use case feels unique to me, so I am not sure how easily it would have resources allocated to it. But, if it is something you feel strongly about, you can always file a feature request for it.

In the mean time, what I can suggest is adding an event listener to the video element (e.g. [timeupdate](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/timeupdate_event)) and watch for when the video element is about to reach the end of the presentation. At that point, you can perform a seek back to the looping range. 

@jkringen does that help?

**Comment by jkringen** [comment]
Thanks for the info, @vaage. I had thought about monitoring the timeupdate event to do that ourselves, if we had to, but was hoping there was a handy API feature for that. No worries, for now. I'll look into the manual approach or see if we can work around this another way.

Thanks!
