### ISSUE TITLE
Livestream player config

### ISSUE THREAD

**Issue by DvorinM3** [google/shaka-player#1865]
Hello, please could anybody help me how to configure my player? 

I need it to behave like YouTube livestream (watch live with option to watch history) or like demo DASH-IF Live sim (2s segments). My source can be DASH as well as HLS with 1s fragments with endless playlist (my livestreams have variable length). LAN livestreaming.

Now I use sample source code. Stream is live but timeline button is on the start of timeline and I cannot move it.

![shaka-test](https://user-images.githubusercontent.com/48368883/55627729-2f8a5900-57af-11e9-8642-1b3d4849c4d8.PNG)

Thank you in advance!

**Comment by TheModMaker** [comment]
That is the default browser controls, which don't work well for live streams.  You either need to create your own custom controls or use our UI.  Here's a tutorial on how to use our UI: https://nightly-dot-shaka-player-demo.appspot.com/docs/api/tutorial-ui.html

**Comment by DvorinM3** [comment]
@TheModMaker Thanks for your reply!

@shaka-bot  Yes, you can close the issue, thank you!
