### ISSUE TITLE
Does shaka-player supported offline playback a stream with persistent widevine information?

### ISSUE THREAD

**Issue by oldmtn** [google/shaka-player#1869]
RT

**Comment by TheModMaker** [comment]
Yes we support persistent licenses.  If you follow our [offline tutorial](https://shaka-player-demo.appspot.com/docs/api/tutorial-offline.html), we will store the content offline and request a persistent license.  This will allow playing the protected content while offline.  This is only allowed on browsers that support it.  For example, Chrome on Linux doesn't support offline licenses currently.

**Comment by oldmtn** [comment]
Yes, Thanks.
