### ISSUE TITLE
Support SAMPLE-AES scheme in HLS with Widevine

### ISSUE THREAD

**Issue by Jason239** [google/shaka-player#1871]
As I know, Chrome supports SAMPLE-AES (cbcs) scheme for Widevine in HLS.
But the HLS-Widevine content which is packaged as cbcs scheme can not playback with the following error.

```
hls_parser.js:2033
Widevine in HLS is only supported with SAMPLE-AES-CTR and SAMPLE-AES-CENC (deprecated), not SAMPLE-AES
```

Chrome version is  73.0.3683.103 and player version is v2.4.7.
Is the media with cbcs scheme still not supported?

**Comment by ismena** [comment]
@Jason239 Could you try the latest master: https://nightly-dot-shaka-player-demo.appspot.com/demo/
If that's not working, please send us the manifest info. I would expect SAMPLE-AES to work, but we'll take alook if something's not right.

**Comment by Jason239** [comment]
it works well, thanks !
