### ISSUE TITLE
Best way to calculate Live Latency

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#1872]
Right now I am using: (new Date () - player.getPlayheadTimeAsDate ()) + 'ms'.

It is the best way?

I want something like:

![live-latency](https://user-images.githubusercontent.com/8983024/55810797-65e61200-5ae8-11e9-9bf1-dc0a354752e6.png)

**Comment by TheModMaker** [comment]
For the time from the live edge, you can use `player.seekRange().end - video.currentTime`.  That would be the difference between the current playhead time and the most recent content available.  But that won't include latency for generating the segments.

A slightly better option would be below.  This will calculate the latency from the expected "now" on the server from the live edge.  I think this will account for the time it takes to generate segments but won't account for the distance to the live edge (above).  You can change things on the player to get closer to the live edge, but you cannot pass it.

```js
const now = player.getPresentationStartTimeAsDate().valueOf() +
            player.seekRange().end * 1000;
const latencyMs = Date.now() - now;
```

**Comment by avelad** [comment]
Is it possible to create a method in the player that returns the correct value of the latency? (only apply to Live and MSE)

**Comment by TheModMaker** [comment]
Sure, we can add that to `getStats`.
