### ISSUE TITLE
Captions hidden behind video element

### ISSUE THREAD

**Issue by ismena** [google/shaka-player#1878]
See #1859 for details and history.

**Comment by ismena** [comment]
@michellezhuogg Halp!

**Comment by joeyparrish** [comment]
The text container appears to be at z-index -1, while the controls and video are both at z-index 0. So the text is not only behind the controls, but the video.  So captions are broken everywhere.

**Comment by ismena** [comment]
@joeyparrish oh. Trust me to fix a small bug :|

I actually think, all of this might be solved by moving the text container inside the controls container. Let me sync with Michelle and see if I'm right.

**Comment by ismena** [comment]
Update: Yup, that does it, no z-index necessary for either play button or the text container.
Will sync with @michellezhuogg on the fix.
