### ISSUE TITLE
Casting video in electron app

### ISSUE THREAD

**Issue by alexandrricov** [google/shaka-player#1881]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
2.5.0-beta2

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `master`?**
N/A

**Are you using the demo app or your own custom app?**
both

**If custom app, can you reproduce the issue using our demo app?**
yes

**What browser and OS are you using?**
electron 4.1.1, macOS 10.14.5

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**

N/A

**What did you do?**

- build electron app with shaka player
- play video (works fine)
- trying cast to TV

**What did you expect to happen?**
- cast starting on TV

**What actually happened?**

I'm using shaka player in electron app.
Trying to implement cast feature.

Shaka cast init fails here:
`!window.chrome`
https://github.com/google/shaka-player/blob/master/lib/cast/cast_sender.js#L186
There are no `window.chrome` object, and it seems that chrome cast library should be add separately.
I've tried to add cast functionality to electron app using `electron-chromecast` lib, now I got 6007 error `code`.
Playing video in electron app using shaka player works perfect, the problem only with casting video to TV.
This feature is not supported or problem is on my end?

**Comment by TheModMaker** [comment]
We have little to no experience with electron.  This sounds more like a problem with electron itself.  All we do is use the browser's APIs for communicating with the Chromecast.  If those APIs aren't available, we can't do anything about it.  Note that in our demo we load a [sender library](https://github.com/google/shaka-player/blob/4334f1956b77c529df7772c87f837370b0f16be1/demo/index.html#L36), which you will probably need to do in your app too.

With the 6007 error, is that coming from the Chromecast?  Does it work with clear content?  Are you using PlayReady or Widevine?  Are you using a custom receiver app?  Does your license server require [wrapping the request](https://shaka-player-demo.appspot.com/docs/api/tutorial-license-wrapping.html)?  What is the value of `error.data[0]`, it should be another Shaka Error object with the error that caused it.

**Comment by alexandrricov** [comment]
@TheModMaker thank you for the answer. Yeah, the problem is in electron itself: it doesn't support cast. I've tried `electron-chromecast` as a polyfill, but it is not enough. I'll not investigate deeper, going with other solution.
