### ISSUE TITLE
How Shaka player obtains  decryption keys in clearkey DRM 

### ISSUE THREAD

**Issue by ksuhiyp** [google/shaka-player#1883]
Have you read the FAQ and checked for duplicate open issues?
yes

What version of Shaka Player are you using?
latest

Can you reproduce the issue with our latest release version?
yes

Can you reproduce the issue with the latest code from master?
Didn't tried

Are you using the demo app or your own custom app?
[custom app](https://github.com/ksuhiyp/shakaEMETest)

If custom app, can you reproduce the issue using our demo app?

doesn't apply

What browser and OS are you using?

Chrome/latest on UBUNTU

What are the manifest and license server URIs?
s3://dash-hls-adaptive/h264.mpd
clear key 

What did you do?
During a test of Clear Key DRM, Shaka player was able to decrypt  Clear Key protected content even though it has the wrong keys!

Supposedly I am messing something, but the content get's encrypted when produced by the packager, and yet the player is able to play them back with wrong keys!

 I've packaged the manifest using Shaka packager with the following args:

which produces audio and three different rates  **all encrypted** using the following args  
   ```
packager \
 in=vp9_360p_300.webm,stream=audio,output=audio.webm,drm_label=AUDIO \
 in=vp9_360p_300.webm,stream=video,output=vp9_360p_300_protected.webm,drm_label=SD \
 in=vp9_720p_1500.webm,stream=video,output=vp9_720p_1500_protected.webm,drm_label=HD \
 in=vp9_1080p_3000.webm,stream=video,output=vp9_1080p_3000_protected.webm,drm_label=HD \
 --clear_lead 6 \
 --enable_raw_key_encryption \
 --keys label=AUDIO:key_id=f3c5e0361e6654b28f8049c778b23946:key=a4631a153a443df9eed0593043db7519,label=SD:key_id=abba271e8bcf552bbd2e86a434a9a5d9:key=69eaa802a6763af979e8d1940fb88392,label=HD:key_id=6d76f25cb17f5e16b8eaef6bbf582d8e:key=cb541084c99731aef4fff74500c12ead \
--mpd_output h264.mpd
```
and the manifest looks like this: [Manifest](s3://dash-hls-adaptive/h264.mpd).

The protected content get's decrypted and everything seems to work well with the correct keys.

```
player.configure({
    drm: {
      clearKeys: {
        // correct keys
         'abba271e8bcf552bbd2e86a434a9a5d9': '69eaa802a6763af979e8d1940fb88390', 
         '6d76f25cb17f5e16b8eaef6bbf582d8e': 'cb541084c99731aef4fff74500c12ea0',
         'f3c5e0361e6654b28f8049c778b23946': 'a4631a153a443df9eed0593043db7510'
      }
    }
  })
```
what is really weird that Shaka is able to decrypt the content also with incorrect keys 

```
player.configure({
    drm: {
      clearKeys: {
        // wrong keys
              'wrongkeywrongkeywrongkey':'abcd1234abcd1234abcd1234',
      }
    }
  })
```
To help reproducing this here is a [git repo](https://github.com/ksuhiyp/shakaEMETest) and to make life easier the manifest and all the content files declared in lives in s3 bucket with base_urls set.
Clear inputs in case you need them:
 s3://dash-hls-adaptive/vp9_1080p_3000.webm
 s3://dash-hls-adaptive/vp9_360p_300.webm 
 s3://dash-hls-adaptive/vp9_480p_500.webm
What did you expect to happen?
seek at 00:00:02:920, the video's picture is the first video's picture.

What do you expect?
Wrong keys in player configuration results in decryption failure

**Comment by TheModMaker** [comment]
You pass `--clear-lead 6` to the packager, so there is 6 seconds of clear content before the content is encrypted.  So you'd need to seek past 6 seconds to see any encrypted content, which your content doesn't have.  If you pass `--clear-lead 0`, there won't be a clear lead and you'll see the problem.

I get a LICENSE_RESPONSE_REJECTED error first since your wrong key isn't the correct size.  If I use a correct length key, I get an UNPLAYABLE_PERIOD error because we detect we have the wrong keys and throw the error.  We may still play, but the browser will stop playback once we get to the end of the clear lead since it doesn't have the keys available.

**Comment by ksuhiyp** [comment]
@TheModMaker 

I actually didn't understand what it meant to do since it says in [docs](https://google.github.io/shaka-packager/html/documentation.html) 

> 

Clear lead in seconds if encryption is enabled.
--
Ok, didn't expected to have a response that quick, you guys are awsome thanks a bunch
