### ISSUE TITLE
Automatically set VOD start time based on Period start

### ISSUE THREAD

**Issue by TheModMaker** [google/shaka-player#1885]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Is your feature request related to a problem? Please describe.**

As was brought up in #1884, we always assume that VOD content starts at 0.  This means that if the first Period starts at a non-zero value, we'll have odd behavior.  What I think we'll do is append the first segment and then jump the "gap" to where the first segment actually starts at.  The seek range will be reported from 0 so there will be a large region we can't actually play.

**Describe the solution you'd like**

We should report the seek range based on the segments in the manifest, similar to how Live works with our drift detection.

**Describe alternatives you've considered**

We could also shift the segments so they are closer to 0, but this complicates manifest parsing.  This also changes the video time from the presentation time.

**Additional context**

Section 3.10 of the DASH IOP suggests setting the `Period@start` to the availability time similar to Live.  So there may be a large gap at the start of VOD content using the live profile.

**Comment by joeyparrish** [comment]
Shifting segments could have other benefits, such as working around platform bugs in Tizen where live streams break with timestamps above 2**32 milliseconds.  But I agree that it complicates parsing.

Perhaps in v2.6 we could explore an intermediate layer that time-shifts content between the manifest parser and StreamingEngine.  If it could be isolated, that would help reduce complexity.

In the mean time, I completely agree with giving an accurate seek range start.  That should be easier to do.

**Comment by TheModMaker** [comment]
This may be a spec-compliance issue.  Relabeled #1884 and going to handle there so we can see the discussion.
