### ISSUE TITLE
Calls to selectVariantTrack() make the playback hang

### ISSUE THREAD

**Issue by ismena** [google/shaka-player#1886]

**Comment by ismena** [comment]
Ok, that's not the UI, that's the API. SelectVariantTrack() hangs the playback. New streams get buffered, but playback doesn't start.

**Comment by joeyparrish** [comment]
This was introduced in Change-Id: Id462cda2c5eb82c3713237341424b91891bd38ea, commit 40212ec43e340d288fcb74a3db921522ea1f2786.

PlayRateController is getting stuck in a state where it forces playbackRate to 0.

**Comment by joeyparrish** [comment]
This bug did not affect any release or beta versions.

**Comment by joeyparrish** [comment]
It was broken for one week, and it took only a couple clicks to reproduce manually.  We should have caught this sooner.
