### ISSUE TITLE
Duplicate GET request for the same resource

### ISSUE THREAD

**Issue by chavoosh** [google/shaka-player#1892]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.4.7

**Can you reproduce the issue with our latest release version?**
I did not test any other version.

**Can you reproduce the issue with the latest code from `master`?**
I did not check it out.

**Are you using the demo app or your own custom app?**
Demo app

**If custom app, can you reproduce the issue using our demo app?**
---

**What browser and OS are you using?**
Chrome / Linux

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
---

**What are the manifest and license server URIs?**

**What did you do?**

Run [http-server](https://www.npmjs.com/package/http-server) on an AWS machine to serve a sample video
From my laptop I tried to watch a video
I realized my laptop sends multiple duplicate requests for the same resource to `http-server`

**What did you expect to happen?**
One request per resource

**What actually happened?**

Here is a screenshot from the server that runs 'http-server'. As it is show we have 2 or 3 GET request for the same resource (e.g., audio/1.m4s)
<img width="1516" alt="Screen Shot 2019-04-24 at 2 10 10 PM" src="https://user-images.githubusercontent.com/7352881/56694044-b50c7500-669a-11e9-8b40-5a6b87f227bc.png">

**Comment by TheModMaker** [comment]
This is indented.  When using HLS, we need to determine the start time of the first segment, so we fetch the first few bytes of it so we can parse the start time out of it.  We need to do this so we can create the index initially.  Otherwise we have no way to start playing at 30 seconds since we don't know which segment that is.  See also #1558.

**Comment by chavoosh** [comment]
Then why do we need to express duplicate requests for the same media segment? E.g., if we need to learn the start time of the first segment then all we need is sending 1 GET request out for it, not 3.

**Comment by TheModMaker** [comment]
If you enable logging, do you see logs with `Unable to fetch a partial HLS segment! ...`?  If so we try to get a partial segment, the try with the full segment, then we download it again to actually append it.  The third one we could remove, but they come from different parts of the project so we cannot do this easily.  Plus the browser usually should cache the request.

**Comment by chavoosh** [comment]
No, I do not see the message in the console. I attached a screenshot of the console output, though.

<img width="887" alt="Screen Shot 2019-04-24 at 3 26 35 PM" src="https://user-images.githubusercontent.com/7352881/56698067-8942bc80-66a5-11e9-9658-152f4b3653ca.png">

**Comment by TheModMaker** [comment]
My guess would be that the same video stream appears in different variants and so we fetch it multiple times.  We probably just iterate over the variants and fetch the first segment from their audio and video.  If that's the case, we could avoid these for the same streams in #1558.  If you try with a manifest with just one variant, I would expect there to only be two requests for the first segment (the first one being a partial request).

**Comment by chavoosh** [comment]
Make sense. I guess we have to wait for #1558 to get merged!
