### ISSUE TITLE
Playback not work in chrome but working in the Firefox and Microsoft Edge

### ISSUE THREAD

**Issue by IRFANKhan3513** [google/shaka-player#1894]
Hi,
I am new to Shaka Player and i am using the shaka Player to load the webM file, Which is working fine in Microsoft Edge and firefox browser. But not working in the chrome even not able to face any kind of the exception also.
Can anyone can able to guide me on this.

**Comment by joeyparrish** [comment]
What version of Shaka Player are you using?  How are you using it?

**Comment by IRFANKhan3513** [comment]
Hi Joey
we are tried with two version, first we are using the v2.4.4 and then we updated with 2.4.7. 

We are using the mpd file. MPD file contains the periods tags which consist of audio and video API, based on that we will consume the data in the form of WEBM file. In back-end we are maintain the form of bytes. I am also attaching the sample mpd file. Please look into this and suggest us.
![Capture](https://user-images.githubusercontent.com/49988337/56804853-b8dbfb00-6844-11e9-91a4-6213a01ce2c2.PNG)

**Comment by IRFANKhan3513** [comment]
Hi Joey,
Any suggestion from your end?

**Comment by joeyparrish** [comment]
Hi @IRFANKhan3513,

We will need more information to help you with this.  Can you please file a bug using our bug template instead?  There is a form that you can fill out which will prompt you for all the necessary details.  Here's a link:

https://github.com/google/shaka-player/issues/new?template=bug_report.md

**Comment by joeyparrish** [comment]
I see you filed #1904, but you deleted the issue template instead of filling it out.  I'm going to close this issue now and we'll continue on #1904.
