### ISSUE TITLE
Advertising module/plugin

### ISSUE THREAD

**Issue by raulqf** [google/shaka-player#1895]
Hi all,

I would like to know if there is any advertising module or plugin for inserting in-stream ads (pre, mid and post rolls). I've read the documentation in the web page but there is not any point related with advertising.

Kindly regards.

**Comment by joeyparrish** [comment]
Hi @raulqf,

We do not provide one at this time, but integration with an ads SDK is fairly straightforward.  We do not hide or replace any HTML5 video APIs behind our interface, so the ads SDK can monitor a video element directly.

We plan to provide a demo using the IMA SDK, currently scheduled for v2.6, but may slip to v2.7.  See #1169 for more details.  Thanks!

**Comment by raulqf** [comment]
Yes, thanks for your support!
