### ISSUE TITLE
Number of rebufferings

### ISSUE THREAD

**Issue by chavoosh** [google/shaka-player#1901]
Does Shaka Player have any mechanism by which we can determine how many times end users experience rebuffering? If not, how can I extract this information from the player?

_P.S. Rebuffering happens when video player does not have enough frames buffered so it needs to stop playback and buffer more frames and then continue streaming the video._

**Comment by TheModMaker** [comment]
First, there is a `buffering` event that you can listen to to track when we enter and exit buffering states.  Second, you can call `player.getStats()` to get the current stats.  The `stateHistory` field tracks the times we spent in buffering and playing states.  See the [docs](https://shaka-player-demo.appspot.com/docs/api/shakaExtern.html#.Stats).

**Comment by chavoosh** [comment]
Great. I can easily look at `stateHistory` and see how many buffering events are there. It shows the total number of reb-bufferings (including the startup buffering). `stateHistory` provides really useful information! Thanks for your help.

**Comment by ismena** [comment]
@chavoosh Anything else we can help you with? Are we good closing the issue?

**Comment by chavoosh** [comment]
@ismena Sure. Please go ahead and close the issue.
