### ISSUE TITLE
Subtitles are not working with pip

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#1903]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes

**What version of Shaka Player are you using?** 2.5.0-beta3

**Can you reproduce the issue with our latest release version?** Yes

**Can you reproduce the issue with the latest code from `master`?** Yes

**Are you using the demo app or your own custom app?** Demo app

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
Chrome 74, Ubuntu 18.04

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What did you do?**

https://v2-5-0-beta3-dot-shaka-player-demo.appspot.com/demo/#asset=https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd;lang=es-ES;build=uncompiled
Load
Select a subtitle
Select PiP option

**What did you expect to happen?**
Subtitles are shown in the PiP window

**What actually happened?**

Subtitles are shown in browser tab and the video in the PiP window.
![pipissue](https://user-images.githubusercontent.com/8983024/56901079-9261ce00-6a97-11e9-8111-6f9d518d0b5b.png)

Notes:
I think that the problem is related to use a custom textDisplayFactory
Idea, Is it possible switch to SimpleTextDisplayer when the user is in PiP mode?

**Comment by theodab** [comment]
Chrome PiP mode does not currently support subtitles. See [this issue](https://bugs.chromium.org/p/chromium/issues/detail?id=854935) on the chromium bug tracker. So we can't really put captions into the PiP window in any efficient way; until then, I think that keeping the captions in the video element is the best we can do.

**Comment by ismena** [comment]
Ahh, this will be trouble in the future, though (custom displayer + pip) and we'll have to address it once the capability is added.

**Comment by joeyparrish** [comment]
I just confirmed that native text display from the browser does not solve this, either.  So disabling our custom text display won't help at the moment.

**Comment by joeyparrish** [comment]
Marking as "infeasible" for now.  If the Chrome bug is solved and native text display works with PiP in the future, we could switch to that.

**Comment by theodab** [comment]
The PiP team is also working on PiP mode with [arbitrary (potentially non-video) elements](https://bugs.chromium.org/p/chromium/issues/detail?id=953957). Once that's in, we could enter PiP mode with the `video-container` div rather than the `video` div, and we would still be able to use our custom text displayer.
