### ISSUE TITLE
Playback not work in chrome but working in the Firefox and Microsoft Edge

### ISSUE THREAD

**Issue by IRFANKhan3513** [google/shaka-player#1904]
we are tried with two version, first we are using the v2.4.4 and then we updated with 2.4.7.

We are using the mpd file. MPD file contains the periods tags which consist of audio and video API, based on that we will consume the data in the form of WEBM file. In back-end we are maintain the form of bytes. I am also attaching the sample mpd file. Please look into this and suggest us.

![Capture](https://user-images.githubusercontent.com/49988337/56907723-82abaf00-6ac2-11e9-906a-b5b8e068ca9d.PNG)

**Comment by joeyparrish** [comment]
@IRFANKhan3513, you did not fill out our issue template and you have not provided the information we require to work on this issue.  Please try again:

```
<!-- NOTE: If you ignore this template, we will send it again and
ask you to fill it out anyway. -->

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for
duplicate open issues?**


**What version of Shaka Player are you using?**


**Can you reproduce the issue with our latest release version?**


**Can you reproduce the issue with the latest code from `master`?**


**Are you using the demo app or your own custom app?**


**If custom app, can you reproduce the issue using our demo app?**


**What browser and OS are you using?**


**For embedded devices (smart TVs, etc.), what model and firmware
version are you using?**


**What are the manifest and license server URIs?**
<!-- NOTE:
  You can send the URIs to <shaka-player-issues@google.com> instead,
  but please use GitHub and the template for the rest.
  A copy of the manifest text or an attached manifest will **not** be
  enough to reproduce your issue, and we **will** ask you to send a
  URI instead.  You can copy the URI of the demo app to send us the
  exact asset, licence server, and settings you have selected there.
-->


**What did you do?**
<!-- Steps to reproduce the bug -->


**What did you expect to happen?**


**What actually happened?**
<!-- A clear and concise description of what the bug is -->
<!-- If applicable, you may add screenshots to help explain your problem. -->
```

**Comment by TheModMaker** [comment]
Specifically we also need the manifest URL, having the manifest text (or in this case a screenshot of some text) isn't enough to debug.  We also need to know what is going wrong, is there an error code?

In chrome you can get extended media logs from `chrome://media-internals`.  When you start playing, you can open a new tab with that and select the respective video element.  It is usually the one at the bottom, but you can go to DevTools and check `video.src` to make sure it is the same one.  Can you post the logs from that too?
