### ISSUE TITLE
Change DRM config for serverCertificate to serverCertificateUri

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#1906]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Instead of the app needing to request the server cert, DrmEngine should be capable of doing it for you on demand.  The serverCertificate config should be changed into serverCertificateUri.

**Describe alternatives you've considered**
None come to mind, other than the status quo.

**Comment by TheModMaker** [comment]
The server certificate is optional, if not given, the browser should request one if it needs it.  The reason to set a server certificate is to avoid the extra network request if the app already has it.  I assume this is coming from Fairplay, which requires the server certificate first?  For Widevine, if it needs a server certificate, it will send a license request for one first, so we don't need to handle server certificates at all.

**Comment by joeyparrish** [comment]
Yes, this comes up with FairPlay, and with the demo app, which takes a URI but configures the player with the actual cert.

**Comment by mseeley** [comment]
Hi folks. Just leaving a note that a `serverCertificateUri` drm config option is a great idea. It's straightforward to fetch the server certificate before configuring Shaka but it does require adding an async step before configuring Shaka.

Hiding the async certificate loading behind the already async `player.load` activity would make for a cleaner client implementation.

**Comment by mseeley** [comment]
Updated to 2.5x -> 3.0.5 enabled our app to eliminate the `fairPlayTransform` bool and `initDataTransform` helper from our FairPlay configuration. A code comment referenced back to this issue.

Just leaving a note that handling the server certificate load within Shaka would eliminate async sequencing in clients. Absolutely only an incremental nice-to-have, but, still nice to have.

Thanks for everything you all do. :)

**Comment by valotvince** [comment]
I'll work on a PR on that matter 👍

**Comment by mseeley** [comment]
@joeyparrish looks like 9b4502cc5d04fc1634d63dfdaa5e864fa4a7e341 missed the 3.1 cut. Are there plans to release an update including this change before 3.2 is minted?
