### ISSUE TITLE
subtitle show on top instead of bottom when set ::cue { background-color: transparent}

### ISSUE THREAD

**Issue by hongfeih** [google/shaka-player#1907]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.3.8

**Can you reproduce the issue with our latest release version?**
Yes, 2.4.7 also has this issue

**Can you reproduce the issue with the latest code from `master`?**
No

**Are you using the demo app or your own custom app?**
Custom app

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Chrome 74 on windows/mac

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
n/a

**What are the manifest and license server URIs?**

https://shaka-player-demo.appspot.com/demo/#asset=https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd

**What did you do?**

Add ::cue { background-color: transparent} in demo.css

**What did you expect to happen?**
Subtitle should be displayed on the bottom of video element

**What actually happened?**

From Chrome 74.0.3729.108, subtitles are displayed on the bottom of video element when set ::cue { background-color: transparent}, while Chrome 72/73 was good.
![issue](https://user-images.githubusercontent.com/2166532/56942523-d3b4b500-6b4d-11e9-97c9-df422ac22159.png)

**Comment by michellezhuogg** [comment]
Hello @hongfeih ,
Thank you for report this! For Shaka v2.4.7, we feed cues to the TextTrack API and let the browser handle the display of the cues, so this css format issue is related to Chrome.
If you're interested in customizing text css styles, please checkout our latest version with the UITextDisplayer.
https://nightly-dot-shaka-player-demo.appspot.com/demo/#asset=https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd;lang=en-US;build=uncompiled
https://github.com/google/shaka-player/blob/master/ui/text_displayer.js

**Comment by hongfeih** [comment]
@michellezhuogg did you have chance to ask to chrome team about this issue? 
And yes, we're considering to use customized text displayer.
