### ISSUE TITLE
Synchronize clock does not take into account caching of fragments

### ISSUE THREAD

**Issue by kfwerf** [google/shaka-player#191]
Hey guys,

We noticed an issue with the ajax request, it takes in the date from our cdn, however that date reflects when the fragment was cached, not current time. An improvement could be to take the age into account as well.

We had to outcomment it for now and probably rely on our own api to give a reliable timing as this implementation threw our clock of by more than 30 minutes.

https://github.com/google/shaka-player/blob/master/lib/util/ajax_request.js#L447-L458

**Comment by tdrews** [comment]
Thanks for the report. This is a bug: `Date` gives the time when the content was created; not when it was transported (see https://tools.ietf.org/html/rfc7231#section-7.1.1.2).
