### ISSUE TITLE
In src= audio selector is not updated with the chosen language

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#1910]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes

**What version of Shaka Player are you using?** Master

**Can you reproduce the issue with our latest release version?** N/A

**Can you reproduce the issue with the latest code from `master`?** Yes

**Are you using the demo app or your own custom app?** Demo app with the url https://nightly-dot-shaka-player-demo.appspot.com/demo/#audiolang=es-419;textlang=es-419;uilang=es-419;panel=HOME;build=uncompiled

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
Safari over iOS 12.2 
Safari 12.1 over macOS Mojave

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

https://storage.googleapis.com/shaka-demo-assets/angel-one-hls/hls.m3u8

**What did you do?**

1. Load the previous stream
2. Play
3. Change the audio language

**What did you expect to happen?**
The new audio language has a tick (current selected)

**What actually happened?**

The new audio language hasn't a tick, and the tick is in the previous language

**Comment by joeyparrish** [comment]
Confirmed.
