### ISSUE TITLE
While casting, the volume slider jumps around when changing the volume.

### ISSUE THREAD

**Issue by londonshliach** [google/shaka-player#1913]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

**What version of Shaka Player are you using?**
2.4.7

**Can you reproduce the issue with our latest release version?**
Yes.

**Can you reproduce the issue with the latest code from `master`?**
Yes.

**Are you using the demo app or your own custom app?**
Custom app.

**If custom app, can you reproduce the issue using our demo app?**
Yes.

**What browser and OS are you using?**
Chrome on windows and android.

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Chromecast G3.

**What are the manifest and license server URIs?**

**What did you do?**

Cast Shaka video to chromecast and then drag the volume slider up and down.

**What did you expect to happen?**
The volume would change smoothly.

**What actually happened?**
As I was sliding the volume slider up, the volume jumped up, then back down and then up again a few times.

At first I thought this may be an issue with my app/volume slider, but I tried it on the Shaka player Demo page and was able to reproduce the problem.

I attached a video of the the issue on the Shaka player Demo page.

The issue is not that prominent on the Shaka player Demo page as the volume slider is very small and doesn't display  the volume number.
It's much more noticeable when using a large volume slider which displays the number.

[Shaka Player demo volume slider.zip](https://github.com/google/shaka-player/files/3145048/Shaka.Player.demo.volume.slider.zip)

**Comment by ismena** [comment]
@londonshliach 
Thanks for the report, we'll take a look!

**Comment by joeyparrish** [comment]
There is a similar issue with seeking and the timecode that we've already solved.  The solution for volume should be similar.  When the user is in the middle of changes, we should display and format for what the user has input, not what we're getting as feedback from the remote device (which may lag).
