### ISSUE TITLE
Fairplay license request data base64 transform

### ISSUE THREAD

**Issue by bcupac** [google/shaka-player#1915]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

**What version of Shaka Player are you using?**
master

**Can you reproduce the issue with our latest release version?**
/

**Can you reproduce the issue with the latest code from `master`?**
yes

**Are you using the demo app or your own custom app?**
custom

**If custom app, can you reproduce the issue using our demo app?**
/

**What browser and OS are you using?**
OSX Safari

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What did you do?**

send a license reqest to the DRM server

**What did you expect to happen?**
it should have returned the license

**What actually happened?**

Am currently testing the Fairplay DRM with our DRM license server and using master shaka player build,  and for it to work i have to change the 
```
shaka.media.DrmEngine.prototype.formatFairPlayRequest_
```
it needs encodeURIComponent,
 ```
  request.body = shaka.util.StringUtils.toUTF8(encodeURIComponent(params));
```
as it doesn't support spc: AAAAAQAAA... format and needs  spc = AAAAAQAAA...
The other thing is, it doesn't work with  
shaka.util.Uint8ArrayUtils.toBase64.

 which will output something like this:
```
AAAAAQAAAAAfoO7GlwW20_-OXN14tvmro-m
```
And the other function that am using and which works has this output:
```AAAAAQAAAAAfoO7GlwW20/+OXN14tvmro+m...```

This is the transformer function that works for our DRM server:

```
   const Uint8ToBase64 = function (u8Arr) {
        const CHUNK_SIZE = 0x8000; //arbitrary number
        let index = 0;
        let length = u8Arr.length;
        let result = '';
        let slice;
        while (index < length) {
            slice = u8Arr.subarray(index, Math.min(index + CHUNK_SIZE, length));
            result += String.fromCharCode.apply(null, slice);
            index += CHUNK_SIZE;
        }
        return btoa(result);
    };
```
Not sure why is this line:
```
  let base64 = window.btoa(bytes).replace(/\+/g, '-').replace(/\//g, '_');
```
in 
shaka.util.Uint8ArrayUtils.toBase64 ?

**Comment by joeyparrish** [comment]
There are two alphabets used in base64 encoding.  One is the standard alphabet from `btoa()`, and the other is the so-called "URL-safe" alphabet.  Our utility is doing the URL-safe version.  We should be able to fix that.

**Comment by joeyparrish** [comment]
But without an accessible URI for your content and your license server, we can't test any fix we put in place.  Can you either provide us with content for testing or a PR to modify DrmEngine?  Thanks!

**Comment by bcupac** [comment]
Will submit a PR, thanks!

**Comment by avelad** [comment]
I just checked the change, it break all my contents.

@joeyparrish , I think that each license server of Fairplay has different form of interactuate. I think that the best is allow to all apps customizate formatFairPlayRequest_ method. Note that the  formatFairPlayRequest_ should manage the sessionId in some servers, and now is missing.

**Comment by joeyparrish** [comment]
@avelad, I understand.  It sounds like we will have to remove all formatting and allow applications to format the raw data with request/response filters.  We can also do a better job documenting this and other details of FairPlay usage in a dedicated doc.  I'm filing a new issue for this now.

**Comment by joeyparrish** [comment]
See #1951 for plans to remove formatting.  @bcupac, @avelad, I apologize for any inconvenience this will cause you.  If you see an alternative, please recommend one in #1951.
