### ISSUE TITLE
Support for cuechange events in HLS playback via src=

### ISSUE THREAD

**Issue by chrisfillmore** [google/shaka-player#1917]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Is your feature request related to a problem? Please describe.**
Not related to a problem.

**Describe the solution you'd like**
I'd like Shaka to publish `metadata` track `cuechange` events for HLS playback via `src=`. I assume this isn't supported yet, my cursory search didn't turn up anything. This works roughly like this:

```
videoElement.textTracks.addEventListener('addtrack', (event) => {
  const track = event.track;
  if (track.kind !== 'metadata') {
    return;
  }

  track.addEventListener('cuechange', () => {
    const activeCues = track.activeCues;
    // Publish cue data to application. This would include startTime / endTime,
    // though exact behaviour may need to be very minimal to allow the application
    // to do what it wants.
  });
});
```

**Describe alternatives you've considered**
We currently have this behaviour in our project already through a wrapper we wrote around Safari's native player. But if we can get the same behaviour through Shaka then I may like to trim the redundant code.

**Additional context**
N/A

**Comment by joeyparrish** [comment]
This seems reasonable.  I'd be happy to accept a PR for this.
