### ISSUE TITLE
UI: Seek bar doesn't work on iOS

### ISSUE THREAD

**Issue by ismena** [google/shaka-player#1918]
Reproes on the nightly build

**Comment by joeyparrish** [comment]
This is a bit more subtle than I realized.  The seek bar works on iOS, but it's much pickier.  You have to click on the "ball" part of the slider, hold it, then drag.

We should find some way to fix this so that it works by touch event anywhere on the "bar" part of the slider.

**Comment by matvp91** [comment]
I've noticed this too, iOS requires you to grab the handle. Wouldn't it work with a custom `touch(start/move/end)` implementation in `shaka.ui.RangeElement`? If you want, I can have a play with this and support a PR.

**Comment by ismena** [comment]
@matvp91 We'd love a PR, thank you :)
