### ISSUE TITLE
Can Shaka detect the key license server from the init segment?

### ISSUE THREAD

**Issue by ShanePhelan** [google/shaka-player#1922]
We have live content that contains content protection info for Widevine and PlayReady.  

The license server url is passed in to Shaka for Widevine but for PlayReady, the license server url is in the init segment.

When the browser is MS Edge and we don't specify a drm:servers object, Shaka dispatches a 6012 error NO_LICENSE_SERVER_GIVEN. Shaka only reads the manifest in this scenario and doesn't download the init segments.

Is there an option to force shaka to look for the url in the init segment? I've tried using "ignoreDrmInfo" but that has no effect.

I've attached an example manifest.

Thanks.
[manifest.xml.zip](https://github.com/google/shaka-player/files/3157748/manifest.xml.zip)

**Comment by TheModMaker** [comment]
We only support providing license server URLs in the configuration or in the manifest.  We don't look in the init segments since that would require parsing the key-system specific init data and we don't want to provide too much work for individual key systems.  Our system works (mostly) independent of which key system is used and there is no generic way of specifying the license URL in the init segment.

**Comment by joeyparrish** [comment]
It is also a feature of Shaka Player that the configured license servers dictate which key systems we will use, overriding what's in the manifest.  So waiting to get the license server from the init segment would conflict with that.

You _could_ make it work through a combination of a phony license server URI and a request filter.  The way it would work is that the filter would delay license requests until it sees an init segment.  It could then parse the init segment, extract the license server URI, and then replace the server URI in all license requests with the one it extracted.

But this could be a lot of work, and it might be easier to find another way to get this information.

What encoder/packager do you use?  Why does your application not know its own license server?

**Comment by ShanePhelan** [comment]
Hi @joeyparrish @TheModMaker Thanks very much for the feedback.

The application does know the license server when the content is ClearKey / Widevine. But when it's PlayReady, this is defined in the init segment so we've never needed it.

The reason it's defined in the init segment for PlayReady (I think) is because the packager originally setup the work flow with dashjs in mind. Dashjs looks in the init segment for key server urls. We've recently moved from dashjs to shaka for simulcast playback in our application.

It's not a problem as we can get the key server url but it involves a back end change for it to be passed through to the application.  I thought I would see if there was a setting / config for Shaka to do this before we go ahead and make the change.

Anyway, it's all good. Thanks for your feedback!

**Comment by joeyparrish** [comment]
Thanks for being flexible, and understanding the trade-offs we made in design.
