### ISSUE TITLE
v2.5.0 DEMO not working on firefox

### ISSUE THREAD

**Issue by Canta** [google/shaka-player#1925]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
2.5.0

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `master`?**
idk, just went to the online instance

**Are you using the demo app or your own custom app?**
demo

**If custom app, can you reproduce the issue using our demo app?**
-

**What browser and OS are you using?**
Firefox 66.0.4 / Ubuntu 18.04

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
-

**What are the manifest and license server URIs?**

Not relevant. The issue happens without the manifest / license.

**What did you do?**

Just go to https://shaka-player-demo.appspot.com using up-to-date firefox.

**What did you expect to happen?**
To be able to play. 
If possible, also to recognize my saved URL parameters.

**What actually happened?**

The UI doesn't work on Firefox. 

There seems to be an UI overhaul for new demo version, as yesterday I was able to work fine with shaka player demo and had the classic UI.

I use shaka player demo to test several of our streams in shaka tech from time to time, so I have some bookmarks with URL parameters pointing to our streams and key servers. Seeing the UI change today, I've also tested the new demo version on Google Chrome, where it actually let me use the UI widgets: but there it doesn't take the URL parameters anymore for my custom content. 

Here are two screenshots of the UI in Firefox. Note how the UI is not the same as in chrome, and the settings menu is empty.

![Image of demo after loading](https://i.imgur.com/eWiOWVd.png)

![The empty settings menu](https://i.imgur.com/wBeH8mB.png)

The "custom content" button (and the others) shows the animation on click, but doesn't do anything else.

Thanks.

**Comment by theodab** [comment]
Looking at the error code you showed, this seems to be a storage error. You mentioned custom content; did you happen to have that custom content stored online? I believe we've changed the internal structure of how storage works since v2.4, so if you have any assets stored from the old demo they may no longer be valid.
If the storage instance errored during load-time, it would cause the rest of the UI to fail to finish loading; I didn't consider this use-case when adding offline support. We should probably be flushing storage in that case, or something.
Thanks for the report.

**Comment by joeyparrish** [comment]
Storage is designed to be backward compatible, so the upgrade from v2.4 to v2.5 shouldn't cause an issue with previously-stored assets.

**Comment by Canta** [comment]
@theodab 
Thank you actually, as I was afraid to report this, thinking I may be doing something wrong. 

That storage error was there before this version. 
I don't have any custom content stored offline, and never used storage for any shaka use case: I use custom content manifest and license URLs (on remote servers). But that legend appeared there since v2+ if I remember correctly. I just never bothered to find out what it was talking about, as it was a verbose demo webpage and also could work fine with Shaka that way.

Here's a new screenshot, with the console errors. Just entering the base url for the demo triggers that.
![Console output](https://i.imgur.com/ResN1zW.png)

**Comment by joeyparrish** [comment]
In that case, we can fix the demo easily enough.  Could you file another issue for the Storage problem? 
 Because Storage is supposed to work on Firefox, and there may be an edge case we didn't account for.  Thanks!
