### ISSUE TITLE
[BUG] In android chrome incognito mode, Widevine DRM content is not playing and giving an error 6001

### ISSUE THREAD

**Issue by vksbansal** [google/shaka-player#1928]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.0

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `master`?**
yes

**Are you using the demo app or your own custom app?**
custom

**If custom app, can you reproduce the issue using our demo app?**
yes

**What browser and OS are you using?**
android 7.0; Lenovo Chrome 74.0.3729.136

**What are the manifest and license server URIs?**

URL has shortly expired token, however, our website is public www.airtelxstream.in/movie/in-the-heart-of-the-sea/HOOQ_MOVIE_68234

**What did you do?**

1. open chrome in incognito mode on android phone
2. play widevine DRM content
3. it will give error 6001

above error happens only in android incognito, it works fines in a normal window

**What did you expect to happen?**
DRM content should play in android chrome incognito mode

**What actually happened?**
In android chrome incognito mode, Widevine DRM content is not playing and giving an error 6001

please use India VPN to access the website

**Comment by vksbansal** [comment]
Dear Shaka Team, 

Please help.

**Comment by TheModMaker** [comment]
Chrome doesn't allow using Widevine in an incognito tab on Android.  This was a deliberate decision since offline licenses won't work properly in incognito mode.  On Desktop you can request Widevine support so long as you don't use persistent state.  I would link to some Chrome bugs I found, but they are all restricted.

This is a Chrome issue and there is nothing we can do about it.

**Comment by joeyparrish** [comment]
Your app should still be able to function in incognito mode if it doesn't use the offline storage features.

**Comment by vksbansal** [comment]
Thanks @TheModMaker for explaining, I understood that there is no way to play widevine on chrome in android in the incoginato mode. 

@joeyparrish, I am not using any offline storage features of shakaplayer and showing an error screen for this case.

**Comment by JohnStokes02** [comment]
I have been using incognito mode in android chrome after the last update. It is very helpful for any one, but I have faced a lot of problems like confirm form resubmission, turn off confirm form resubmission, etc. Then I stopped browsing it. I have solved that issue after browsing [url=https://browsertechnicalsupportnumbers.com/blog/disable-confirm-form-resubmission-popup-chrome/]confirm form resubmission[/url], if you feel the same. Then you can also browse here. I am sure that you will get a valid solution.

**Comment by JohnStokes02** [comment]
I have been using incognito mode in android chrome after the last update. It is very helpful for any one, but I have faced a lot of problems like confirm form resubmission, turn off confirm form resubmission, etc. Then I stopped browsing it. I have solved that issue after browsing [confirm form resubmission](https://browsertechnicalsupportnumbers.com/blog/disable-confirm-form-resubmission-popup-chrome/), if you feel the same. Then you can also browse here. I am sure that you will get a valid solution.

**Comment by OrenMe** [comment]
If anyone is looking for official confirmation it is stated here in developers.google.com: https://developers.google.com/web/updates/2017/09/chrome-62-media-updates

> Note: Widevine support is disabled in Incognito mode in Android. That way users do not inadvertently lose paid licenses when closing Incognito tabs.

**Comment by joeyparrish** [comment]
Thanks!
