### ISSUE TITLE
build.py default output path has changed

### ISSUE THREAD

**Issue by asmirsabanovic** [google/shaka-player#1929]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.0

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
custom app

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Chrome (74.0.3729.131), OSX 10.14.2 (18C54)

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd

**What did you do?**

Run `python build/build.py +@complete -@dash --force`

**What did you expect to happen?**
`dist/shaka-player.compiled.js` to be built without dash support

**What actually happened?**

It was built with dash support and I could play a dash manifest. This used to work when I was using v2.4.7

**Comment by joeyparrish** [comment]
Because the demo app is built on top of the new Shaka Player UI, the default build has changed to the UI build in `shaka-player.ui.js`.  To get the old behavior, you need to specify the name as "compiled" (default is "ui") and exclude the UI components (`@ui`).  Try this:

```sh
python build/build.py +@complete -@dash -@ui --name compiled --force
```

**Comment by asmirsabanovic** [comment]
It works now, thanks for the help and quick feedback! It might be a good idea to update the docs for v2.5.0: https://github.com/google/shaka-player/blob/master/build/README.md

**Comment by joeyparrish** [comment]
Yes!  Thanks for pointing that out.  I'll reopen this issue until we've corrected the docs.
