### ISSUE TITLE
Player gets stuck when playing on multiple tabs after a while

### ISSUE THREAD

**Issue by arikkrol1** [google/shaka-player#193]
To reproduce play the manifest below in shakaplayer on 3 different tabs.
after about 20 minutes one of them will freeze.

http://vm2.dashif.org/livesim/mup_300/tsbd_500/testpic_2s/Manifest.mpd

**Comment by tdrews** [comment]
Unable to repro after ~30 minutes of playback with 3 tabs.
We had a memory issue (#184) in v1.5.0, perhaps this issue is causing the problem for you.
Can you reproduce on master?

**Comment by joeyparrish** [comment]
@arikkrol1 Can you reproduce on master?  We believe this may have been caused by #184, which has been fixed.

**Comment by arikkrol1** [comment]
I'll check on Sunday. Thanks.

**Comment by joeyparrish** [comment]
@arikkrol1 Any updates on this?

**Comment by joeyparrish** [comment]
If this is still an issue for you, please feel free to reopen.
