### ISSUE TITLE
Cannot read property 'setBytes' of undefined

### ISSUE THREAD

**Issue by pszemus** [google/shaka-player#1930]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
2.5.0
https://ajax.googleapis.com/ajax/libs/shaka-player/2.5.0/shaka-player.compiled.debug.js

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `master`?**
don't know

**Are you using the demo app or your own custom app?**
custom

**If custom app, can you reproduce the issue using our demo app?**
yes

**What browser and OS are you using?**
Chrome 74.0.3729.131, Fedora 29

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What did you do?**
I configured player like this:
```
player.configure({
	streaming: {
		retryParameters: {
			timeout: 7000
		}
	}
});
```
Then I started playing a DASH stream and, after a while, I throttled my network to **1Mbps**.

**What did you expect to happen?**
I expect that after 7000ms downloading will abort, new network bandwidth will be computed and player will start downloading lower bitrate rendition (like described in https://github.com/google/shaka-player/issues/1051)

**What actually happened?**
After 7000ms downloading a chunk JS error occured:
```
Uncaught (in promise) TypeError: Cannot read property 'setBytes' of undefined
    at networking_engine.js:514
    at $jscomp.generator.Engine_.program_ (http_fetch_plugin.js:154)
    at $jscomp.generator.Engine_.nextStep_ (generator_engine] :795)
    at $jscomp.generator.Engine_.next_ (generator_engine] :699)
    at $jscomp.generator.Generator_.next (generator_engine] :833)
    at b (execute_async_generator] :48)
```
![image](https://user-images.githubusercontent.com/13220781/57455529-9ba72380-726b-11e9-9460-3d21dc54b604.png)

**Comment by theodab** [comment]
I was unable to reproduce this bug myself, but I am fairly sure that this CL should fix it. If it does not, feel free to re-open the issue.

**Comment by pszemus** [comment]
I can confirm that now it's fixed. Thank you.
