### ISSUE TITLE
DEMO: lost functionality of custom content since v2.5.0

### ISSUE THREAD

**Issue by Canta** [google/shaka-player#1933]
Hi there.

Yesterday v2.5.0 was rolled out to shaka-player-demo.appspot.com , and I found a few issues that brought here (#1925 and #1926).

There's another thing, that I don't know if it's a bug or just a desired change (and that's why I create this issue as question and not bug/feature-request): I can no longer load shaka player demo app pointing to a custom content. 

I was able to do that through URL parameters, like this:

https://shaka-player-demo.appspot.com/demo/#asset=https://mysite.com/manifest.mpd;license=https://mysite.com/license?parameters;lang=en-US;noadaptation;build=uncompiled

That way, I could save a few URLs for use on different machines in private mode.
Since v2.5.0 the custom content functionality is different, and it's now expected so save loaded custom contents on local storage in order to be able to play them later again. And I don't see the URL parameters working as before. This way, I have 3 different new problems:
  1) Can't share URLs between machines.
  2) Must add configurations manually on every machine I want to test my streams using the shaka player demo.
  3) There seems to be some quirks on the storage usage in private mode (see #1926), so I'm kinda forced to use non-private mode in order to save my stream configurations.

So, I create this issue as question in order to ask: is this change intended, or is just some kind of unwanted loss of functionality?

I believe that if this wasn't wanted, then it could be considered bug/regression.

I also believe many people will be happy with the use of storage. With that in mind: is there any chance to have both, the new way of handling custom contents, but also the previous URL way?

Thanks in advance.

**Comment by theodab** [comment]
I got a CL through yesterday that re-added loading custom content through URL parameters.

**Comment by joeyparrish** [comment]
The restored functionality will appear in v2.5.1.
