### ISSUE TITLE
Playback not starting after offline content is loaded

### ISSUE THREAD

**Issue by CACUser** [google/shaka-player#1937]
I followed the Offline video playback sample. But would like to load and play the content once it is downloaded. The video plays if the "Play" button created by the sample is clicked. but it does not start if I simply call video.play() 👍 

```js
window.player.load(content.offlineUri).then(
          function() {
           video.play();
            console.log('Offline content: ' + content.offlineUri +
                  ' ready for playback.');
          });
```

The player goes into pause. If I run video.play(); from console - the video starts playing. 
Is there anyway to start playing the video after download?

**Comment by joeyparrish** [comment]
This is part of the browser's autoplay restrictions.  In brief, video.play() might not work outside of a user interaction event, such as a click event.

Here are some useful links to explain the browser's behavior:

https://faq.dailymotion.com/hc/en-us/articles/360000102908-Browser-rules-that-determine-autoplay
https://developers.google.com/web/updates/2017/09/autoplay-policy-changes
https://www.howtogeek.com/326532/safari-now-disables-auto-playing-videos.-heres-how-to-allow-them-for-certain-sites/

**Comment by CACUser** [comment]
Thanks! Plays with muted audio on desktop Chrome.
