### ISSUE TITLE
setTextTrackVisibility bug

### ISSUE THREAD

**Issue by bcupac** [google/shaka-player#1938]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
master branch

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `master`?**
yes

**Are you using the demo app or your own custom app?**
custom

**If custom app, can you reproduce the issue using our demo app?**
n/a

**What browser and OS are you using?**
Chrome, MacOS

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What did you do?**

There is embedded english CC and other English CC is externally added:
```
player.addTextTrack(closedCaptionsUrl, 'eng', 'caption', 'text/vtt')
					.then(track => {
						player.selectTextTrack(track);
						player.setTextTrackVisibility(false);
					});
```

then after the CC toggle button is clicked, the below triggers:
```
const textTrackVisible = !player.isTextTrackVisible();
				player.setTextTrackVisibility(textTrackVisible);
```
**What did you expect to happen?**
it should show external CC.

**What actually happened?**
it did not show it. But after the toggle CC is pressed 3 times, it will show CC aka after 

player.setTextTrackVisibility(true) then
player.setTextTrackVisibility(false) then
player.setTextTrackVisibility(true)

On the other hand. If I start with this:

```
player.addTextTrack(closedCaptionsUrl, 'eng', 'caption', 'text/vtt')
					.then(track => {
						player.selectTextTrack(track);
						player.setTextTrackVisibility(undefined);
					});
```
then i get a warning 'text visibility has fallen out of sync' but the button works as it should and shows CC on first click.

**Comment by ismena** [comment]
Hey @bcupac thanks for reporting!
Could you provide a manifest and text for us to reproduce this?
Feel free to send them privately to shaka-player-issues@google.com if you're concerned about posting publicly.

**Comment by bcupac** [comment]
can't share the manifest or sub, will find a way to either recreate or further debug, thanks!:)

**Comment by joeyparrish** [comment]
I can reproduce with our demo and the content in it.  Steps:

1. Load "Big Buck Bunny: The Dark Truths", which has no subtitles.
2. In the debugger, add subtitles from "Angel One": `shakaDemoMain.player_.addTextTrack('https://storage.googleapis.com/shaka-demo-assets/angel-one/s-en.webvtt', 'en', 'captions', 'text/vtt')`
3. Use the UI to enable subtitles. Nothing happens.
4. Disable and re-enable subtitles. They are finally shown.

**Comment by joeyparrish** [comment]
After addTextTrack() is called, there is one text track, which is marked "active".  A network request for the subs has been made.  The text displayer has a list of cues.  isTextTrackVisible() on the player agrees with the internal state of the text displayer.

After selecting English from the UI, isTextTrackVisible() and the internal state of the text displayer both show that text should be visible, but it's not.

**Comment by joeyparrish** [comment]
Ah, because "cues" is empty after enabling the display of text.

**Comment by joeyparrish** [comment]
`setTextTrackVisibility` calls `StreamingEngine`'s `loadNewTextStream`, which clears the text buffer through MediaSourceEngine.

**Comment by joeyparrish** [comment]
It's unclear which is the fault: either that `loadNewTextStream` doesn't detect that it's the same stream and ignore it, or that the buffer doesn't refill after being cleared.  I tend to think the former, since we'd prefer not to fetch anything twice if it's already in buffer.

**Comment by bcupac** [comment]
So, when 
```
addTextTrack
```
is called, it calls
```
 await this.streamingEngine_.loadNewTextStream(stream);
```
which runs this
```
 if ((this.textStreamSequenceId_ == currentSequenceId) &&
        !this.mediaStates_.has(ContentType.TEXT) &&
        !this.unloadingTextStream_) {
      const presentationTime = this.playerInterface_.getPresentationTime();
      const needPeriodIndex = this.findPeriodForTime_(presentationTime);

      const state = this.createMediaState_(stream,
          needPeriodIndex,
          /* resumeAt= */ 0);

      this.mediaStates_.set(ContentType.TEXT, state);
      this.scheduleUpdate_(state, 0);
    }
```
Now, when we select a text track, we again call
```
loadNewTextStream
```
but now :
```
 !this.mediaStates_.has(ContentType.TEXT)
```
is false, so the code block does not trigger.
Then after turn off the subtitles
```
          this.streamingEngine_.unloadTextStream();
``
gets called and it triggers
```
      this.mediaStates_.delete(ContentType.TEXT);

```
so the next time we turn on the subtitles:
```
!this.mediaStates_.has(ContentType.TEXT)
```
is true so the if code block is executed and it starts working and displaying subtitles.

**Comment by ismena** [comment]
This should be working now, please feel free to reopen if you're still seeing the issue.

**Comment by michellezhuogg** [comment]
On our demo page, I tried to play 'Angle One (HLS, MP4, multilingual,
Widevine)' with captions, and then play 'Shaka Player History', and I can
see 'text visibility has fallen out of sync' from console. Not sure if it's
the same cause.

**Comment by ismena** [comment]
Honestly, I'm not 100% sure about that console message. I've seen it show up in different situations, but it's never related to any root cause as far as I can tell ¯\_(ツ)_/¯

This particular bug was for external text not showing up when it's enabled. I don't think the console message is related.

**Comment by michellezhuogg** [comment]
Thank you for your input! I'll look into that :)

>
