### ISSUE TITLE
Babel triggers error EMFILE while running tests

### ISSUE THREAD

**Issue by RahmatAdiPutra** [google/shaka-player#1939]
$ ./build/test.py --browsers Chrome
[INFO] Generating Closure dependencies...
[INFO] Compiling the library (ui, release)...
[WARNING] No changes detected, skipping. Use --force to override.
[WARNING] No changes detected, skipping. Use --force to override.
[WARNING] No changes detected, skipping. Use --force to override.
[INFO] Running test (1 / 1)...
14 05 2019 13:50:32.275:ERROR [preprocessor.babel]: EMFILE: too many open files, open '/home/cyber/public_html/playground/test/shaka-player/package.json'
 at /home/cyber/public_html/playground/test/shaka-player/test/test/util/canned_idb.js
14 05 2019 13:50:32.278:ERROR [preprocessor.babel]: EMFILE: too many open files, open '/home/cyber/public_html/playground/test/shaka-player/package.json'
 at /home/cyber/public_html/playground/test/shaka-player/test/test/util/dash_parser_util.js
14 05 2019 13:50:32.278:ERROR [preprocessor.babel]: EMFILE: too many open files, open '/home/cyber/public_html/playground/test/shaka-player/package.json'
 at /home/cyber/public_html/playground/test/shaka-player/test/test/util/fake_media_source_engine.js
14 05 2019 13:50:32.279:ERROR [preprocessor.babel]: EMFILE: too many open files, open '/home/cyber/public_html/playground/test/shaka-player/package.json'
 at /home/cyber/public_html/playground/test/shaka-player/test/test/util/fake_networking_engine.js
14 05 2019 13:50:32.279:ERROR [preprocessor.babel]: EMFILE: too many open files, open '/home/cyber/public_html/playground/test/shaka-player/package.json'
 at /home/cyber/public_html/playground/test/shaka-player/test/test/util/jasmine_fetch.js
14 05 2019 13:50:32.280:ERROR [preprocessor.babel]: EMFILE: too many open files, open '/home/cyber/public_html/playground/test/shaka-player/package.json'
 at /home/cyber/public_html/playground/test/shaka-player/test/test/util/simple_fakes.js
14 05 2019 13:50:32.330:ERROR [preprocessor.babel]: EMFILE: too many open files, open '/home/cyber/public_html/playground/test/shaka-player/package.json'
 at /home/cyber/public_html/playground/test/shaka-player/lib/abr/simple_abr_manager.js
14 05 2019 13:50:32.385:ERROR [preprocessor.babel]: EMFILE: too many open files, open '/home/cyber/public_html/playground/test/shaka-player/package.json'
 at /home/cyber/public_html/playground/test/shaka-player/lib/dash/segment_list.js
14 05 2019 13:50:32.386:ERROR [preprocessor.babel]: EMFILE: too many open files, open '/home/cyber/public_html/playground/test/shaka-player/package.json'
 at /home/cyber/public_html/playground/test/shaka-player/lib/media/manifest_parser.js
14 05 2019 13:50:32.386:ERROR [preprocessor.babel]: EMFILE: too many open files, open '/home/cyber/public_html/playground/test/shaka-player/package.json'
 at /home/cyber/public_html/playground/test/shaka-player/lib/media/presentation_timeline.js
14 05 2019 13:50:32.387:ERROR [preprocessor.babel]: EMFILE: too many open files, open '/home/cyber/public_html/playground/test/shaka-player/package.json'
 at /home/cyber/public_html/playground/test/shaka-player/lib/media/playhead.js
14 05 2019 13:50:32.387:ERROR [preprocessor.babel]: EMFILE: too many open files, open '/home/cyber/public_html/playground/test/shaka-player/package.json'
 at /home/cyber/public_html/playground/test/shaka-player/lib/media/segment_index.js
14 05 2019 13:50:32.388:ERROR [preprocessor.babel]: EMFILE: too many open files, open '/home/cyber/public_html/playground/test/shaka-player/package.json'
 at /home/cyber/public_html/playground/test/shaka-player/lib/media/webm_segment_index_parser.js
14 05 2019 13:50:32.388:ERROR [preprocessor.babel]: EMFILE: too many open files, open '/home/cyber/public_html/playground/test/shaka-player/package.json'
 at /home/cyber/public_html/playground/test/shaka-player/lib/media/video_wrapper.js
14 05 2019 13:50:32.439:ERROR [preprocessor.babel]: EMFILE: too many open files, open '/home/cyber/public_html/playground/test/shaka-player/package.json'
 at /home/cyber/public_html/playground/test/shaka-player/lib/offline/indexeddb/storage_mechanism.js
14 05 2019 13:50:32.497:ERROR [preprocessor.babel]: EMFILE: too many open files, open '/home/cyber/public_html/playground/test/shaka-player/package.json'
 at /home/cyber/public_html/playground/test/shaka-player/lib/offline/storage_muxer.js
14 05 2019 13:50:32.498:ERROR [preprocessor.babel]: EMFILE: too many open files, open '/home/cyber/public_html/playground/test/shaka-player/package.json'
 at /home/cyber/public_html/playground/test/shaka-player/lib/polyfill/mediasource.js
14 05 2019 13:50:32.526:ERROR [preprocessor.babel]: EMFILE: too many open files, open '/home/cyber/public_html/playground/test/shaka-player/package.json'
 at /home/cyber/public_html/playground/test/shaka-player/lib/text/text_engine.js
14 05 2019 13:50:32.527:ERROR [preprocessor.babel]: EMFILE: too many open files, open '/home/cyber/public_html/playground/test/shaka-player/package.json'
 at /home/cyber/public_html/playground/test/shaka-player/lib/text/vtt_text_parser.js
14 05 2019 13:50:32.528:ERROR [preprocessor.babel]: EMFILE: too many open files, open '/home/cyber/public_html/playground/test/shaka-player/package.json'
 at /home/cyber/public_html/playground/test/shaka-player/lib/util/abortable_operation.js
14 05 2019 13:50:32.528:ERROR [preprocessor.babel]: EMFILE: too many open files, open '/home/cyber/public_html/playground/test/shaka-player/package.json'
 at /home/cyber/public_html/playground/test/shaka-player/lib/util/ebml_parser.js
14 05 2019 13:50:32.528:ERROR [preprocessor.babel]: EMFILE: too many open files, open '/home/cyber/public_html/playground/test/shaka-player/package.json'
 at /home/cyber/public_html/playground/test/shaka-player/lib/util/manifest_filter.js
14 05 2019 13:50:32.553:ERROR [preprocessor.babel]: EMFILE: too many open files, open '/home/cyber/public_html/playground/test/shaka-player/package.json'
 at /home/cyber/public_html/playground/test/shaka-player/lib/util/player_configuration.js
14 05 2019 13:50:32.570:ERROR [preprocessor.babel]: EMFILE: too many open files, open '/home/cyber/public_html/playground/test/shaka-player/package.json'
 at /home/cyber/public_html/playground/test/shaka-player/ui/localization.js
14 05 2019 13:50:32.571:ERROR [preprocessor.babel]: EMFILE: too many open files, open '/home/cyber/public_html/playground/test/shaka-player/package.json'
 at /home/cyber/public_html/playground/test/shaka-player/ui/resolution_selection.js
14 05 2019 13:50:32.571:ERROR [preprocessor.babel]: EMFILE: too many open files, open '/home/cyber/public_html/playground/test/shaka-player/package.json'
 at /home/cyber/public_html/playground/test/shaka-player/ui/text_displayer.js
14 05 2019 13:50:32.572:ERROR [preprocessor.babel]: EMFILE: too many open files, open '/home/cyber/public_html/playground/test/shaka-player/package.json'
 at /home/cyber/public_html/playground/test/shaka-player/ui/text_selection.js
14 05 2019 13:50:32.572:ERROR [preprocessor.babel]: EMFILE: too many open files, open '/home/cyber/public_html/playground/test/shaka-player/package.json'
 at /home/cyber/public_html/playground/test/shaka-player/ui/ui.js
14 05 2019 13:50:32.607:ERROR [karma]: { Error: listen EMFILE: too many open files 0.0.0.0:9876
    at Server.setupListenHandle [as _listen2] (net.js:1253:19)
    at listenInCluster (net.js:1318:12)
    at doListen (net.js:1451:7)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  code: 'EMFILE',
  errno: 'EMFILE',
  syscall: 'listen',
  address: '0.0.0.0',
  port: 9876 }
(node:27277) [DEP0079] DeprecationWarning: Custom inspection function on Objects via .inspect() is deprecated
14 05 2019 13:50:32.679:ERROR [preprocessor.babel]: EMFILE: too many open files, open '/home/cyber/public_html/playground/test/shaka-player/package.json'
 at /home/cyber/public_html/playground/test/shaka-player/test/test/util/util.js
14 05 2019 13:50:32.680:ERROR [preprocessor.babel]: EMFILE: too many open files, open '/home/cyber/public_html/playground/test/shaka-player/package.json'
 at /home/cyber/public_html/playground/test/shaka-player/lib/cast/cast_proxy.js
14 05 2019 13:50:32.680:ERROR [preprocessor.babel]: EMFILE: too many open files, open '/home/cyber/public_html/playground/test/shaka-player/package.json'
 at /home/cyber/public_html/playground/test/shaka-player/lib/cast/cast_sender.js
14 05 2019 13:50:32.727:ERROR [preprocessor.babel]: EMFILE: too many open files, open '/home/cyber/public_html/playground/test/shaka-player/package.json'
 at /home/cyber/public_html/playground/test/shaka-player/lib/dash/mpd_utils.js
14 05 2019 13:50:32.727:ERROR [preprocessor.babel]: EMFILE: too many open files, open '/home/cyber/public_html/playground/test/shaka-player/package.json'
 at /home/cyber/public_html/playground/test/shaka-player/lib/dash/segment_template.js
14 05 2019 13:50:32.728:ERROR [preprocessor.babel]: EMFILE: too many open files, open '/home/cyber/public_html/playground/test/shaka-player/package.json'
 at /home/cyber/public_html/playground/test/shaka-player/lib/net/networking_engine.js
14 05 2019 13:50:32.728:ERROR [preprocessor.babel]: EMFILE: too many open files, open '/home/cyber/public_html/playground/test/shaka-player/package.json'
 at /home/cyber/public_html/playground/test/shaka-player/lib/offline/indexeddb/v1_storage_cell.js
14 05 2019 13:50:32.818:ERROR [preprocessor.babel]: EMFILE: too many open files, open '/home/cyber/public_html/playground/test/shaka-player/package.json'
 at /home/cyber/public_html/playground/test/shaka-player/lib/util/stream_utils.js
14 05 2019 13:50:32.820:ERROR [preprocessor.babel]: EMFILE: too many open files, open '/home/cyber/public_html/playground/test/shaka-player/package.json'
 at /home/cyber/public_html/playground/test/shaka-player/third_party/language-mapping-list/language-mapping-list.js
[INFO] Run complete
[INFO] Result (exit code): 1

**Comment by gele0o0ra** [comment]
I have the same problem. I guess it's something has to with babel, I've found a similar error https://github.com/babel/babel/issues/4582

**Comment by joeyparrish** [comment]
We haven't run into this error ourselves.  @RahmatAdiPutra, @gele0o0ra, what OS are you running?

**Comment by gele0o0ra** [comment]
I'm running Fedora 29. I also tried to compile on Windows 10, but I had a problem with character deciding when running build/all.js

**Comment by joeyparrish** [comment]
On Linux, you can configure the system's maximum number of open files.  What value do you get with this command?

```sh
cat /proc/sys/fs/file-max
```

I get 1048576, or 2<sup>20</sup>.

**Comment by gele0o0ra** [comment]
I get 788884

**Comment by joeyparrish** [comment]
Okay, so you have a lower system-wide limit than I do.  Now let's check how many open files there are on your system.  Try this (requires `lsof`, which you may need to install):

```sh
lsof | wc -l
```

I get 198129, or about 18.9% of my system-wide max.

**Comment by gele0o0ra** [comment]
I get 96874

**Comment by joeyparrish** [comment]
Hrm... that's well below your system-wide max.

It seems that Linux also has limits applied to each shell.  Try this:

```sh
ulimit -Sn  # "soft" limit
ulimit -Hn  # "hard" limit
```

For me, these are both 32768.

Also, I think the `lsof` command earlier is only getting a count of files that your user can "see".  Try it again with `sudo`:

```sh
sudo lsof | wc -l
```

For me, this is 343362, or 32.7% of my system-wide limit (up from the 18.9% I could see as a normal user).

**Comment by gele0o0ra** [comment]
That's what I get:

[leonid@leonid-laptop ~]$ sudo lsof | wc -l
[sudo] password for leonid: 
lsof: WARNING: can't stat() fuse.gvfsd-fuse file system /run/user/1000/gvfs
      Output information may be incomplete.
120666

[leonid@leonid-laptop ~]$ ulimit -Sn  # "soft" limit
1024

[leonid@leonid-laptop ~]$ ulimit -Hn  # "hard" limit
4096

**Comment by joeyparrish** [comment]
Then it appears that it's your ulimit settings that are causing the issue.  Try raising the limits for `nofile` in your system's /etc/security/limits.conf ([manual page](https://linux.die.net/man/5/limits.conf)).  Since you're on Fedora, here's an article by Red Hat on the subject: https://access.redhat.com/solutions/61334

Does this help?

**Comment by gele0o0ra** [comment]
Thank you, but there is no nofile entry in my case and can't edit it: 

#<domain>      <type>  <item>         <value>
#

#*               soft    core            0
#*               hard    rss             10000
#@student        hard    nproc           20
#@faculty        soft    nproc           20
#@faculty        hard    nproc           50
#ftp             hard    nproc           0
#@student        -       maxlogins       4

# End of file

**Comment by joeyparrish** [comment]
The problem seems to be related to your system's limits on the number of open file descriptors.  I can't think of anything else to suggest to help with that.

The underlying behavior of the babel dependency in our tests has been fixed in babel v7 such that it should never hit this limit, but we can't upgrade to babel v7 yet.  We use babel in our karma test runner through a karma plugin, and I haven't been able to make that plugin work with babel v7 yet.  We may have to wait for updates to the plugin which will allow a complete upgrade of babel.

In the mean time, reconfiguring your system limits seems to be the only viable solution.  My best advice now is to google "ulimit" "nofile" "fedora" and maybe "EMFILE" to see what you can find to raise these limits.  If your computer is owned or administered by an organization, you may be able to ask for support from them.

I found one last thing you may want to try, but I have no direct experience here and I can't vouch for this.  According to this serverfault answer (https://serverfault.com/a/377795), you could try this:

```sh
echo "* hard nofile 102400" >> /etc/security/limits.conf
echo "* soft nofile 102400" >> /etc/security/limits.conf
sudo reboot
```

**Comment by gele0o0ra** [comment]
Thank you a bunch, I'll try it.

**Comment by RahmatAdiPutra** [comment]
> We haven't run into this error ourselves. @RahmatAdiPutra, @gele0o0ra, what OS are you running?

Ubuntu 18.10

**Comment by joeyparrish** [comment]
@RahmatAdiPutra, can you please try updating `/etc/security/limits.conf` or `/proc/sys/fs/file-max` to see if that helps?

**Comment by RahmatAdiPutra** [comment]
> @RahmatAdiPutra, can you please try updating `/etc/security/limits.conf` or `/proc/sys/fs/file-max` to see if that helps?

im try update but same error

**Comment by joeyparrish** [comment]
Well, this is definitely a Linux system configuration issue.  The open file limits (per shell and/or system-wide) need to be raised.  I'm sorry that I was unable to coach you through those changes, but I hope that the links and information we dug up will help you find a solution for your systems.

Unfortunately, I've reached the limit of what I can do to help with an issue that's firmly outside of Shaka Player.  Good luck, and thanks for your interest in Shaka Player.
