### ISSUE TITLE
Shaka debug scope and call stack obfuscated

### ISSUE THREAD

**Issue by jfalameda** [google/shaka-player#194]
Hi,

I am having some issues debugging shaka. I include the debug version referencing to the source map. It works fine referencing the code, but when dropping a breakpoint, and when the debugger stops in it, the scope variables and the stack trace show me obfuscated variables. I am not allow to watch expressions, since it will not recognise them.

Has someone had the same problems? Is this a problem with the compiler?

Thanks in advance.

Shaka version: 1.5.0.
Test on chrome dev channel and canary.

![image](https://cloud.githubusercontent.com/assets/287670/10188727/f9882d32-6761-11e5-882a-f53d4990b318.png)

**Comment by joeyparrish** [comment]
The source map only maps compiled code back to the file and line number of the uncompiled code.  It does not unobfuscate variable, function, or member names.  This is a limitation of source maps and the compiler, and can't be addressed by the library.

I strongly recommend debugging in uncompiled mode whenever possible.
