### ISSUE TITLE
ChromeCast remote control

### ISSUE THREAD

**Issue by bojant987** [google/shaka-player#1941]
I'm having a tough time getting the Shaka player UI to control both local player and remote ChromeCast player.
I'm using `castProxy.getPlayer()` and `castProxy.getVideo()` for pretty much everything but UI controls are working only for local player. I can call methods manually, ie `proxyVideo.pause()`, etc, and it works. But i figure that it should probably work out of the box, i just can't figure out how to get it working.
Basically i instantiate `CastProxy`, get player and video and use them for setting up shaka and UI controls. Only place where i couldn't use `proxyVideo` is when instantiating `shaka.ui.Overlay` since it throws and error `Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.`
So, i'm not sure whether this is the reason controls are not working for both players out of the box, or it's just not possible and should be done manually, or i'm missing something.
Any help would be appreciated.

**Comment by ismena** [comment]
Hi @bojant987 

Are you using our UI with auto setup? (via data attributes in HTML)
Do you have a Chromecast receiver app?
Could you post the code sample for how you're using/accessing the UI on your receiver.

Please take a look at our [demo receiver app](https://github.com/google/shaka-player/blob/master/demo/cast_receiver/receiver_app.js) for an example of accessing the UI.

**Comment by bojant987** [comment]
I'm using your demo receiver app as a starting boilerplate, so far i just added some network request filters for license server calls, the rest is the same. So the problem shouldn't be in the receiver i guess.
As for instantiating UI, i'm not using auto setup with data attributes in HTML, i do this:
`const ui = new shaka.ui.Overlay(proxyPlayer, videoContainer, localVideo); 
  ui.configure(uiConfig);`
I'm passing `uiConfig` with a list of `controlPanelElements` to render.
I can't pass `proxyVideo` to `Overlay`, it throws error i mentioned in the comment above.
I'm not sure whether controls should work for both players when used like this.
Right now i'm using my own custom UI where i call `proxyVideo` methods manually, so it works.
But it would be nice if default UI worked.

**Comment by joeyparrish** [comment]
Ah, I see.  With the UI library, it will create the proxy for you.  Try this instead:

```js
const ui = new shaka.ui.Overlay(localPlayer, videoContainer, localVideo);
uiConfig.castReceiverAppId = 'FILL_IN_YOUR_APP_ID_HERE';
ui.configure(uiConfig);

const proxyPlayer = ui.getControls().getPlayer();
```

There seems to be a bug here, in that `ui.getPlayer()` always returns a local player.  I'll get that fixed.  In the mean time, `ui.getControls().getPlayer()` returns the proxied player as it should.

**Comment by joeyparrish** [comment]
We made a change to clarify `getPlayer()` in `ui` and make it always return the proxied one.  This will appear in v2.5.1.  In the mean time, you can use `getControls().getPlayer()` to get the proxy, pass the local player to `Overlay`, and configure it with your app ID.

Does this answer your question?

**Comment by bojant987** [comment]
Yeah, it does. Thanks for the quick response and fix.
I'll try it out later today, closing the issue now.
