### ISSUE TITLE
Life Stream: v2.4.6 vs v2.5.0 regarding  the ose of UTCTiming schemeIdUri="urn:mpeg:dash:utc:http-xsdate:2014"

### ISSUE THREAD

**Issue by Userin1974** [google/shaka-player#1942]
Hi, 
noticed the with v2.5.0 for life streams the UTCTiming source isn't called any more. 
The UTCTiming source is mentioned in the MPD. 
With v2.4.6 UTCTiming source is called, but not with v2.5.0. Is this behavior on purpose? 
So far i couldn't see any playback problems, I am just curious if this is planed this way. 

Kind regards

**Comment by TheModMaker** [comment]
In v2.5 we do automatic drift protection.  This means we use the segment list in the manifest to determine where to start playing at, so we don't need to have a synchronized clock.  If you want the old behavior of using the `availabilityStartTime` to determine the start time, you can set the `manifest.dash.autoCorrectDrift` configuration to `false`.

**Comment by Userin1974** [comment]
Thanks
