### ISSUE TITLE
shaka player error code 2000

### ISSUE THREAD

**Issue by clotairemarmignon** [google/shaka-player#1945]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
YES

**What version of Shaka Player are you using?**
Shaka 2.0.5

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
our own custom app

**If custom app, can you reproduce the issue using our demo app?**
This is the same result

**What browser and OS are you using?**
Chrome  74.0.3729.157

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

```


**What did you do?**
<!-- Steps to reproduce the bug -->
We just linked our mpd file to the player and added the content to our app.

**What did you expect to happen?**
We just wanted to be able to play the videos

**What actually happened?**
<!-- A clear and concise description of what the bug is -->

<!-- If applicable, you may add screenshots to help explain your problem. -->

**Comment by TheModMaker** [comment]
In the manifest, the text stream has `mimeType="text/vtt"`, it should be `mimeType="application/ttml+xml"`.  We are trying to parse the stream as VTT, when the content is really TTML.

As a side note, your `serverCertificate` configuration is wrong.  First it needs to be an `Uint8Array` and second it is way too small to be a certificate.  That is just a UUID, you need to pass a certificate.

**Comment by TheModMaker** [comment]
Does this answer all your questions?  Can we close the issue?

**Comment by clotairemarmignon** [comment]
yes thank you
