### ISSUE TITLE
NIGHTLY DEMO: dialog polyfill problem in Firefox

### ISSUE THREAD

**Issue by Canta** [google/shaka-player#1947]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
2.5.0-61

**Can you reproduce the issue with our latest release version?**
N/A

**Can you reproduce the issue with the latest code from `master`?**
N/A

**Are you using the demo app or your own custom app?**
Demo

**If custom app, can you reproduce the issue using our demo app?**
N/A

**What browser and OS are you using?**
Firefox 66.0.5 / Ubuntu 18.04

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**

N/A

**What did you do?**

Just enter the current nightly build of shaka player demo with firefox:
https://nightly-dot-shaka-player-demo.appspot.com/

**What did you expect to happen?**
To NOT see the error.

**What actually happened?**

There's an error regarding a polyfill. Please take a look at the screenshot:

![Polyfill error](https://i.imgur.com/oO1saUR.png)

The problem seems to be a simple 404 for a library: https://nightly-dot-shaka-player-demo.appspot.com/node_modules/dialog-polyfill/dialog-polyfill.js
I understand this is not stable code, but created the issue anyways so it doesn't gets to the next release.

After the error appears, I can not play a custom content (neither by adding one, or by using URL parameters). Other functionalities (like search) seems to work, but didn't fully test them.

Thanks.

**Comment by joeyparrish** [comment]
Something must have gone wrong with our appspot deployment.  It's working in the release version v2.5.0, so it must be something that happened since then.  Let me take a look.

**Comment by joeyparrish** [comment]
We just upgraded the node modules, and the location of that file seems to have moved in the latest version of the module.  We didn't notice on Chrome, because the polyfill isn't used on Chrome.  Sorry about that!

**Comment by joeyparrish** [comment]
The nightly demo has been updated and should now be fixed on Firefox.  Thanks!
