### ISSUE TITLE
Call to ui.configure should not create a new controls object

### ISSUE THREAD

**Issue by ismena** [google/shaka-player#1948]
Might be related to #1941 

Every time ui.configure is called,we recreate the shaka.ui.Controls object.
This means, the apps can no longer rely on the object they got from ui.getControls() prior to the config call and the castProxy object also is different.

Controls and castProxy need a way to change without being re-created.

**Comment by joeyparrish** [comment]
@ismena, should we close this bug now?  Or is there more to do?

**Comment by ismena** [comment]
I think, we can close this one and open another to track the progress on our casting saga.
