### ISSUE TITLE
CAF v3 / Shaka embedded version ?

### ISSUE THREAD

**Issue by tbaylet** [google/shaka-player#1950]
Hello Shaka team,

From this ticket Google issue ticket https://issuetracker.google.com/issues/130630687, it seems than Cast Application Framework (v3) is based on Shaka.
https://developers.google.com/cast/docs/mpl/streaming_protocols
There are no unfortutenately no references here.

It would really help to understand which Shaka version we are reffering to, for troubleshooting purposes.
Can you please provide this information ?

-BR
Thomas

**Comment by ismena** [comment]
Hi Thomas,
They use 2.5.0-beta3 to the best of my knowledge.
Let me ping them to confirm.

They only use Shaka for DASH, btw.

**Comment by tbaylet** [comment]
Hi,
Many thanks for the speedy feedback.
Confirmation would be top !
Our problem is indeed with DASH, 
Thomas

**Comment by ismena** [comment]
UPD: I was wrong, they use 2.4 at the moment, and are going to upgrade to 2.5 their next release

**Comment by chrisfillmore** [comment]
@ismena I would assume the upgrade schedule is determined by the CAF team and not Shaka team. Is that correct?

**Comment by ismena** [comment]
@chrisfillmore That's correct. They update on their own release schedule.
I could probably ask them if there's a public roadmap/schedule that you can consult, if you'd like! :)

**Comment by mimse** [comment]
@ismena a roadmap would be really nice to have :-)

**Comment by ismena** [comment]
Your local CAF-insider here :)
They try to release every ~6 weeks. The next one is planned to go out some time early June. The preliminary date is 6/3, but it can change a bit depending on bugs etc.

**Comment by tbaylet** [comment]
Thanks !
Do you have the forecast scope of the CAF release, meaning the versionning of each component ?
i.e. will Shaka version be 2.5.1  or another one ?
Thomas

**Comment by ismena** [comment]
We will advise 2.5.1 as it has latest bug fixes. I think it's reasonable to assume that it will be the latest minor release unless they find it not working for them for some reason. We're not aware of the other components.
I'm going to close the Q&A with the Cast team for now before they get annoyed and send me on my way :-)
