### ISSUE TITLE
Can't test chromecast on new shaka-player demo page.

### ISSUE THREAD

**Issue by oldmtn** [google/shaka-player#1966]
Here is the chromecast demo page:
https://shaka-player-demo.appspot.com/demo/#clockSyncUri=;uilang=zh-CN;asset=https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd;panel=SEARCH;build=uncompiled

I can't find the cast button, so I can't to test the cast feature.

**Comment by theodab** [comment]
This is a known issue with the Shaka Player UI. The UI is creating and destroying the cast sender multiple times during setup, which seems to be preventing it from detecting devices. See #1948.
We're working on a fix for this at the moment.

**Comment by oldmtn** [comment]
Thanks
