### ISSUE TITLE
VTT subtitles synchronization for live HLS 

### ISSUE THREAD

**Issue by Romain-Bernier** [google/shaka-player#1968]
In my company we generate VTT subtitles with absolute timestamps,
To make it work on shaka, I have to modified the  
`let offset = time.segmentStart;` to `let offset = 0;`
in the vtt_text_parser.js
Other player like hls.js or Exoplayer work find with absolute timestamps.
have you planned to support absolute timestamps, and if not, why ?

**Comment by TheModMaker** [comment]
See #1563.

**Comment by Romain-Bernier** [comment]
Yes, I hope you will find time to fix this in the v2.6.
This mean support of empty VTT segment and absolute timestamps support for live HLS.
