### ISSUE TITLE
It should be possible to change the cast application id through controls.configure()

### ISSUE THREAD

**Issue by ismena** [google/shaka-player#1978]

**Comment by joeyparrish** [comment]
@ismena, isn't this fixed now?  If so, please tag the commits and close.

**Comment by ismena** [comment]
Not the way the name of this issue is phrased.
Going from no cast app id to having a cast app id works well now, though and I'm leaning towards disregarding the "change one id to the other" use case until I actually see an app that does this.
If you don't have strong objections, I'll close this issue.

**Comment by ismena** [comment]
...or I can change the name of the issue and tag the commit, if you need it for release tracking or something?

**Comment by joeyparrish** [comment]
> Going from no cast app id to having a cast app id works well now

Awesome!

> I'm leaning towards disregarding the "change one id to the other" use case until I actually see an app that does this.

Sounds good.  Let's close.
