### ISSUE TITLE
UI tests failing on IE11 and Tizen

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#1979]
As of last night, the following UI tests are failing on IE 11 and Tizen 3:

 - UI resolution selection selecting Auto via UI enables ABR
 - UI resolution selection selecting specific resolution disables ABR
 - UI language selections caption selection choosing caption language through UI has effect on player
 - UI language selections caption selection turning captions off through UI has effect on player
 - UI language selections audio choosing language through UI has effect on player
 - UI controls resolutions menu clears the buffer when changing resolutions

I haven't had the time to do a bisect on the changes that landed yesterday.

**Comment by TheModMaker** [comment]
Git bisect reveals f67df3d7ad77a86a18f1feac7d4768cf8a18a784 is at fault.
