### ISSUE TITLE
css renaming

### ISSUE THREAD

**Issue by hochhaus** [google/shaka-player#1980]
We are upgrading from shaka v2.4.7 to v.2.5.1 and would like to use the shaka provided controls. We run shaka compiled into a larger closure style codebase which uses CSS renaming. Therefore, it would be helpful if all of the class names under shaka's `ui/` directory were wrapped in calls to `goog.getCssName(...)`. If we sent such a pull request would the authors consider it?

**Comment by ismena** [comment]
I don't see why not! Feel free to create a PR, we'll take a look.

**Comment by joeyparrish** [comment]
We don't use the complete Closure Library, so that may be an issue.

**Comment by hochhaus** [comment]
@joeyparrish Would you be open to me adding a stub identify function implementation of `goog.getCssName(...)`? In the shaka codebase it would be a noop. In our code we use the full closure-library so it would sub as expected with our full renaming map.

```
goog.getCssName = function(className) {
  return className;
};
```

**Comment by joeyparrish** [comment]
That would work for me.  Perhaps in lib/debug/.

The only trouble is that we could easily miss one, and none of our test automation would catch that, because it's a no-op in the context of our project as a standalone.

Maybe you could help us understand what goog.getCssName gets you.  Perhaps there's another way to get the same thing, in a way that's easier to avoid mistakes.

**Comment by hochhaus** [comment]
Thanks Joey.

> The only trouble is that we could easily miss one, and none of our test automation would catch that, because it's a no-op in the context of our project as a standalone.

This is a really compelling point. If it isn't tested / enforced in the shaka code, it is likely to break and then we will need to fix it later. Since css renaming might not be generally useful, we should likely add the `goog.getCssName(...)` calls when we import shaka into our code base.

**Comment by joeyparrish** [comment]
Okay.  If ever there's something problematic about our CSS class names, please let us know so we can fix it.  Thanks!
