### ISSUE TITLE
error code 2000 - shaka player

### ISSUE THREAD

**Issue by clotairemarmignon** [google/shaka-player#1982]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** yes

**What version of Shaka Player are you using?** shaka 2.0.5

**Can you reproduce the issue with our latest release version?** yes 

**Can you reproduce the issue with the latest code from `master`?** yes 

**Are you using the demo app or your own custom app?** our own custom app, and tried too with the demo app 

**If custom app, can you reproduce the issue using our demo app?** yes

**What browser and OS are you using?** Chrome 74.0.3729.169

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?** Not concerned

**What are the manifest and license server URIs?** SENT TO THE EMAIL ADDRESS
 sent by e-mail

**What did you do?**

I converted some new videos in order to broadcast them on my app. Since several months, some films  are not working at all, it's hard to launch the video, it launches the 10 last seconds or not at all when it's nice, or it's not launching at all. 

The error code is 2000. I tried to find some solutions on the internet but didn't find any concrete solution.

**What did you expect to happen?**
I wanted to be able to stream the content.

**What actually happened?** error 2000 
 The file is recognized by the player, I can see it, the duration etc. The player begins the video at the 5 final seconds. If I try to stream it from the beginning, the player shows a problem, play icon changes each second to pause and it's doing it without stopping... 

@google @joeyparrish @TheModMaker

**Comment by TheModMaker** [comment]
Error 2000 is [INVALID_TEXT_HEADER](https://nightly-dot-shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html#value:2000).  Your WebVTT text file doesn't have a valid header in it.  The segment needs to start with `WEBVTT` and two newlines before the first cue.  So it should look like:

```
WEBVTT

1
00:00:05,049 --> 00:00:08,570
capacitors on the other hand are
```

**Comment by clotairemarmignon** [comment]
Thank you, so the problem comes from the 
Subtitles or can we correct it with the player?

Thanks,

**Comment by TheModMaker** [comment]
The subtitles are incorrect and do not represent valid WebVTT.  You need to fix your subtitles for them to be playable.

**Comment by clotairemarmignon** [comment]
Thank you. How can I be sure that they are ok ? Some of them are good and some of them are not but the way to do it is the same... 

Thank you

**Comment by TheModMaker** [comment]
I'm thinking that your captions that have a type of `text/vtt` are actually `.srt` files, not WebVTT.  Although the formats are similar, they are incompatible with each other.  We do not support `.srt` captions.  The asset you gave us that works uses TTML, it contains valid TTML.
