### ISSUE TITLE
Is the order of <Location> based redirects guaranteed?

### ISSUE THREAD

**Issue by chrisfillmore** [google/shaka-player#1984]
DASH IOP v4.3 in the section on **MPD Location and Reference Resolution** says the following:
> **3.2.15.3. Client Requirements and Recommendations**
> Based on these descriptions, a DASH client operating on MPD updates and segment requests is expected to operate as follows:
> * For MPD update requests (when due) according to clause 5.4, the DASH client requests the MPD according to the following priority
>   * If at least one MPD.Location element is present,
>     * any the value of any MPD.Location element is used as the MPD request URL

The phrasing "any of the value of any MPD.Location element is used" sounds to me like the order of those Location elements is not considered.

In fact I see Shaka's implementation follows the order of the manifest. I can't really imagine why any implementation would not respect the order, but I don't think it's actually guaranteed. I suspect that content providers would want the order respected, for failover scenarios.

Do you think it's ambiguous? I will file a recommendation with IOP to update this section, but I'm curious if you agree.

**Comment by joeyparrish** [comment]
Yeah, that seems unhelpfully ambiguous.  If there's room for clients to choose at random for load-balancing (or if that's recommended), then that should be stated somewhere and referenced from that spot.

**Comment by chrisfillmore** [comment]
Good point, I hadn't even considered the load-balancing case. I'll include that in my ticket.

Thanks for replying.

**Comment by chrisfillmore** [comment]
I have filed https://github.com/Dash-Industry-Forum/DASH-IF-IOP/issues/333
