### ISSUE TITLE
Invalid aspect ratio

### ISSUE THREAD

**Issue by Angels-group** [google/shaka-player#1987]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
- Yes

**What version of Shaka Player are you using?**
- 2.5.2

**Can you reproduce the issue with our latest release version?**
- Yes

**Can you reproduce the issue with the latest code from `master`?**
- Yes

**Are you using the demo app or your own custom app?**
- Demo and custom

**If custom app, can you reproduce the issue using our demo app?**
- Yes

**What browser and OS are you using?**
- Chrome 75.0.3770.80

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
- none

**What are the manifest and license server URIs?**

- Sent to shaka-player-issues@google.com

**What did you do?**

- Try to play stream

**What did you expect to happen?**
- I expected the video resolution to be correct =)

**What actually happened?**

When viewing some of the HLS streams, there is an inappropriate aspect ratio in the ShakaPlayer. The image is stretched vertically (or compressed horizontally).

The same stream is correctly displayed on the jwPlayer and hls.js players. Also i test it with Android ExoPlayer.

ShakaPlayer 2.5.2
<img width="665" alt="Screenshot at Jun 11 13-11-32" src="https://user-images.githubusercontent.com/1552042/59264037-f0fb9980-8c4a-11e9-88cd-1914599479e0.png">

hls.js v0.12.1-23a07d9
<img width="740" alt="Screenshot at Jun 11 13-11-47" src="https://user-images.githubusercontent.com/1552042/59264072-0244a600-8c4b-11e9-86b2-88b1f080e523.png">

**Comment by joeyparrish** [comment]
I'm getting an HTTP 404 error trying to fetch the manifest URL you sent, so I can't reproduce your issue.  Please send another URL that we can use to reproduce the issue.

In the mean time, is your content TS or MP4?  If it's TS, then this could be a transmuxing bug in which some critical info for the aspect ratio is lost.  We use mux.js for transmuxing, whereas hls.js does not.  (And jwPlayer uses hls.js internally IIRC.)  There is a PR on mux.js right now related to aspect ratio issues in transmuxing, so if your content is TS, I think a mux.js upgrade (after the PR lands) would be the likely fix.

**Comment by joeyparrish** [comment]
In case it's relevant, see https://github.com/videojs/mux.js/pull/275

**Comment by Angels-group** [comment]
> I'm getting an HTTP 404 error trying to fetch the manifest URL you sent, so I can't reproduce your issue. Please send another URL that we can use to reproduce the issue.
> 
> In the mean time, is your content TS or MP4? If it's TS, then this could be a transmuxing bug in which some critical info for the aspect ratio is lost. We use mux.js for transmuxing, whereas hls.js does not. (And jwPlayer uses hls.js internally IIRC.) There is a PR on mux.js right now related to aspect ratio issues in transmuxing, so if your content is TS, I think a mux.js upgrade (after the PR lands) would be the likely fix.

Update stream. Try again please.
We use MP4 content.

**Comment by Angels-group** [comment]
Update stream. Try again please.

вт, 11 июн. 2019 г. в 19:13, Joey Parrish <notifications@github.com>:

**Comment by chrisfillmore** [comment]
You may be encountering this bug:
https://bugs.chromium.org/p/chromium/issues/detail?id=843150

Try turning hardware acceleration off in Chrome and see if you can still reproduce.

Per the ticket, Google's recommended solution is to include a PASP box in your init segment.

**Comment by Angels-group** [comment]
> Try turning hardware acceleration off in Chrome

Wow! Cool!!! Thank you! Now it work correct!!
It remains to understand how to fix the flow (PASP box) =)))

**Comment by Angels-group** [comment]
> include a PASP box in your init segment

But how hls.js work with hardware acceleration turned on?

**Comment by chrisfillmore** [comment]
I don't know... maybe related to transmuxing?

**Comment by joeyparrish** [comment]
Yeah, I don't know how hls.js works. @johnbartos, does hls.js manipulate init segments for MP4 content?  If an init segment were missing the PASP box, would hls.js somehow compensate for this to correct the aspect ratio?

**Comment by Angels-group** [comment]
As i understand - hls.js generate PASP box if init segment missing it.

https://github.com/video-dev/hls.js/commit/6cd80a6c30b68a3937a11303f1e1403826bd1e8b

**Comment by johnBartos** [comment]
@joeyparrish We do not -  the code @Angels-group linked applies only to MPEG-TS transmuxing. Our fmp4 manipulation is limited to timestamps.

**Comment by Angels-group** [comment]
@joeyparrish
Yes, I am sorry, misled.
We use TS segments and this is the problem mux.js
I tried to apply some fixes (something similar as in hls.js) to mux.js and compile it from sources. Everything turned out and works correctly.

I attached a corrected version for testing (if you need it)
[mux.js.zip](https://github.com/google/shaka-player/files/3280956/mux.js.zip)

**Comment by Angels-group** [comment]
What about DASH? Try to change **m3u8** to **mpd** in my URI - same problem) Invalid aspect ratio

**Comment by joeyparrish** [comment]
If a box is missing in the MP4, and it is needed to properly initialize a hardware decoder, then you will need to fix the content itself.  Shaka Player does not manipulate or fix content on-the-fly (except for TS=>MP4 transmuxing through mux.js).
