### ISSUE TITLE
ChromeCast appData callback for customData

### ISSUE THREAD

**Issue by bojant987** [google/shaka-player#1989]
Me again with some ChromeCast inquiries :)

I found this issue: https://github.com/google/shaka-player/issues/722
@joeyparrish mentioned here that "The customData field of the Load message will be given to shaka.util.CastReceiver's opt_appDataCallbackopt."

I imagine something like `this.appDataCallback_(mediaInfo.customData)` just next to contentIdCallback.

Now i noticed that is not the case, and i figured it would be pretty helpful, since that way my android sender can just use default namespace and not be aware of shaka namespace at all.
Is there a reason this wasn't implemented? Cause if there aren't any blocking reasons, i'd like to contribute and add that or make a feature request.

**Comment by joeyparrish** [comment]
I went back through the history, and you're right.  There's no point where we ever passed the `customData` field of the standard `LOAD` command to the receiver's `appDataCallback`.

This should be very easy to fix.
