### ISSUE TITLE
Update EME usage to match latest spec & Chrome implementation

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#199]
The EME spec has changed in several ways, as has Chrome's implementation.  As Chrome is the only implementation of EME tracking the spec, we will update our usage of EME and our polyfills to match Chrome 46.

**Comment by joeyparrish** [comment]
No changes necessary right now.

**Comment by tdrews** [comment]
At some point we will need to change how we handle the `output-restricted` key status. If the key system indicates the `output-restricted` key status then we should not raise an error or restrict the key's associated track(s), as the key system may still be able to use that key for different tracks. See http://www.w3.org/TR/encrypted-media/#idl-def-MediaKeyStatus.output-restricted

**Comment by joeyparrish** [comment]
Updated key status forEach argument order in b1141d5
