### ISSUE TITLE
Cast option not available using Shaka Player

### ISSUE THREAD

**Issue by MayreLew** [google/shaka-player#1999]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
The shaka player demo page

**Can you reproduce the issue with our latest release version?**
Don't know, instructions for running this test says to use specific URLs on the Chrome browser.

**Can you reproduce the issue with the latest code from `master`?**
Don't know, again, the instructions for the test case states to use a specific URL on the Chrome browser to play a video.

**Are you using the demo app or your own custom app?**
Demo App

**If custom app, can you reproduce the issue using our demo app?**
NA

**What browser and OS are you using?**
Chrome Browser on mobile device of Pixel XL
Android version 9

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
NA

**What are the manifest and license server URIs?**

"https://shaka-player-demo.appspot.com/demo/?#asset=https://storage.googleapis.com/wvtest/dexter/media/staging/latest/derived_key/h264_cenc/llama.mpd;license=https://proxy.staging.widevine.com/proxy?provider=widevine_test;lang=en-US;logtoscreen;trickplay;play;noinput;build=compiled" 

"https://shaka-player-demo.appspot.com/demo/?#asset=https://storage.googleapis.com/wvtest/dexter/media/staging/latest/derived_key/h264_cenc/llama.mpd;license=https://proxy.staging.widevine.com/proxy?provider=widevine_test;lang=en-US;logtoscreen;trickplay;play;noinput;build=compiled"

"https://shaka-player-demo.appspot.com/demo/?#asset=https://storage.googleapis.com/wvtest/dexter/media/staging/latest/derived_key/h264_cenc/llama.mpd;license=https://proxy.staging.widevine.com/proxy?provider=widevine_test;lang=en-US;logtoscreen;trickplay;play;noinput;build=compiled"

"https://shaka-player-demo.appspot.com/demo/?#asset=https://storage.googleapis.com/wvtest/dexter/media/staging/latest/key_rotation_entitlement/h264_cenc/llama.mpd;license=https://proxy.staging.widevine.com/proxy?provider=widevine_test;lang=en-US;logtoscreen;trickplay;play;build=compiled;noinput" 

"https://shaka-player-demo.appspot.com/demo/?#asset=https://storage.googleapis.com/wvtest/dexter/media/staging/latest/entitlement/h264_cenc/llama.mpd;license=https://proxy.staging.widevine.com/proxy?provider=widevine_test;lang=en-US;logtoscreen;trickplay;play;build=compiled;noinput"

**What did you do?**

Pre-Condition:
1. Set both the TV, mobile device, and Chromecast Ultra to our testing network.
2. Set up Chromecast Ultra device on Google Home app and make sure all is connected

TO REPRO:
1.  On the mobile device, load each URL one at a time into a Chrome Browser window.
2.  On the test video which is on the top of the screen, click on the three-dot icon, located on the lower right of the video screen which is playing where a pop-up menu will appear after clicking.

**What did you expect to happen?**
After clicking on the three-dot icon on the lower right corner of video, there should appear a "cast" option.

**What actually happened?**

The "cast" option is missing.  Therefore not able to cast from the mobile device onto the TV screen.

**Comment by theodab** [comment]
At the moment there's two bugs that are breaking casting.
Firstly, there's #1948, which is fixed. But apparently not all of the parts of the fix are in the most recent release? One of the CLs must have been missed when v2.5.2 came out. So it should work properly on [nightly](http://nightly-dot-shaka-player-demo.appspot.com). This is the issue you are seeing here.
Secondly, there receiver app has an issue in it at the moment that causes it to break on startup. This I have [pushed a CL for](https://github.com/google/shaka-player/commit/0fa00ddf62acec3d22613ccace361e5bb70e3888), but we haven't uploaded a new receiver app based on that code yet. I should probably do that now, while I'm thinking about it.
