### ISSUE TITLE
MediaKeys.isTypeSupported is deprecated

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#2]
We currently rely on MediaKeys.isTypeSupported, which is deprecated and has been removed from recent drafts of the EME spec.  This should not be used to check for key system support.

This will only cause problems IF:
  1) you are running Chrome 41 (canary)
  2) AND you have flipped the "Enabled Encrypted Media Extensions" flag
  3) AND you have flipped the "Disable prefixed Encrypted Media Extensions" flag

Users running a typical configuration of Chrome will not see any issues with this.

**Comment by ddorwin** [comment]
The scenario above generates an exception that completely breaks the player. Thus, the player's unprefixed EME support can't be used at all. Does it make sense to just remove the isTypeSupported() calls and replace them with some reasonable assumptions until a more permanent fix can be implemented?

**Comment by joeyparrish** [comment]
We could code those assumptions into a polyfill specifically for MediaKeys.isTypeSupported, and reasonably get that into our bugfix release v1.1.  This is tentatively scheduled for release on Jan 15.

The real fix is to quit relying on the concept of isTypeSupported, and instead to use the supportedConfigurations parameter of navigator.requestMediaKeySystemAccess.  This will require the refactor of several internal classes, which won't be ready until v1.2.

I will file another issue to track the polyfill which will provide a fake isTypeSupported for v1.1.
