### ISSUE TITLE
minBufferTime delays video startup?

### ISSUE THREAD

**Issue by bwidtmann** [google/shaka-player#2000]
Hi all.

After testing shaka-player a little bit more in depth, we realised that we have quite a big delay between first chunk seen and playback started. The cause is minBufferTime=10PTS in our VOD manifests. We never experienced this with other players (dash.js, bitmovin, Exo). And honestly we never understood this value to delay the startup. Before changing thousands of manifests, we are asking ourselves if you have miss interpreted this value. Regarding DASH-IF IOP:

> the value of the minimum buffer time does not provide any instructions to the client on
how long to buffer the media. The value however describes how much buffer a client should have under ideal network conditions. As such, MBT is not describing the burstiness or jitter in the network, it is describing the burstiness or jitter in the content encoding. Together with the BW value, it is a property of the content. Using the "leaky bucket" model, it is the size of the bucket that makes BW true, given the way the content is encoded.

@haudiobe maybe can help there?

thanks

**Comment by TheModMaker** [comment]
We interpret the `minBufferTime` to represent the minimum amount of content to buffer to maintain smooth playback.  That is part of the `burstiness or jitter in the content encoding`.  We buffer at least that amount to ensure we get smooth playback and don't enter a buffering state again immediately.  In the DASH spec, section A.2 it even suggests as an example DASH client to buffer at least `minBufferTime` before playing.

> 4. The client buffers media of for at least value of @minBufferTime attribute duration before starting
the presentation.

**Comment by joeyparrish** [comment]
For now, we stand by our interpretation of `minBufferTime`.  This is necessary to avoid buffering in cases where the bandwidth estimate is very close to the bandwidth requirement for a given stream.

However, for cases where you don't control or can't easily update the manifests, we offer a configuration that you can use to ignore `minBufferTime`, at which point your configured `rebufferingGoal` will rule instead.  For example:

```js
player.configure('manifest.dash.ignoreMinBufferTime', true);
player.configure('streaming.rebufferingGoal', 1 /* second */);
```

Does this help?

**Comment by bwidtmann** [comment]
I know about these settings and that is how we mitigated it for now. But I am pretty sure there are other clients as well which will wonder why their playback is delayed by `minBufferTime`. In my opinion that is too conservative. Maybe you should explicitly write it somewhere in the docu so it is clear for everyone.

**Comment by TheModMaker** [comment]
We'll add an entry to the FAQ.
