### ISSUE TITLE
Snap event picture in picture for custom button

### ISSUE THREAD

**Issue by ivansteff** [google/shaka-player#2002]
What function to attach to a custom button, so that by clicking on it a picture in a picture appears?

**Comment by ismena** [comment]
You mean the [picture in picture](https://googlechrome.github.io/samples/picture-in-picture/) API?
Are you using our UI? If yes, we have a pip button for supporting browsers in the overflow menu (click the button with three vertical dots on the controls panel, it will be in the menu that will appear id your browsers supports it).

If you want to create a custom button for it, take a look at [our implementation](https://github.com/google/shaka-player/blob/master/ui/pip_button.js) of the button. You can do something similar.

The key parts are onPipClick_(), onEnterPictureInPicture_(), and  onLeavePictureInPicture_().

Does this help?

**Comment by ivansteff** [comment]
@ismena Yes! Thanks!
