### ISSUE TITLE
Question for Customizing the UI

### ISSUE THREAD

**Issue by Atercatus** [google/shaka-player#2005]
I followed the tutorial and got a question.

Could not be found in [Customizing the UI](https://shaka-player-demo.appspot.com/docs/api/tutorial-ui-customization.html) the `myapp`
```
// skipButton.js

// Use shaka.ui.Element as a base class
myapp.SkipButton = class extends shaka.ui.Element {
  constructor(parent, controls) {
    super(parent, controls);

    // The actual button that will be displayed
    this.button_ = document.createElement('button');
    this.button_.textContent = 'Skip current video';
    this.parent.appendChild(this.button_);

    // Listen for clicks on the button to start the next playback
    this.eventManager.listen(this.button_, 'click', () => {
      let nextManifest = /* Your logic to pick the next video to be played */
        myapp.getNextManifest();

      // shaka.ui.Element gives us access to the player object as member of the class
      this.player.load(nextManifest);
    });
  }
};

// Factory that will create a button at run time.
myapp.SkipButton.Factory = class {
  create(rootElement, controls) {
    return new myapp.SkipButton(rootElement, controls);
  }
};
// Register our factory with the controls, so controls can create button instances.
shaka.ui.Controls.registerElement(
  /* This name will serve as a reference to the button in the UI configuration object */ 'skip',
  new myapp.SkipButton.Factory());
```

What does `myapp `mean?

And in 'Changing seek bar progress colors' ,
seek bar color is undefined.
how can i change this color?
```
console.log(shaka.ui.Controls.SEEK_BAR_BASE_COLOR_) // undefined
```

 
```
shaka.ui.Controls.SEEK_BAR_BASE_COLOR_ , 
shaka.ui.Controls.SEEK_BAR_PLAYED_COLOR_, and 
shaka.ui.Controls.SEEK_BAR_BUFFERED_COLOR_ in ui/controls.js
```

**Comment by ismena** [comment]
Hi @Atercatus 
The tutorial is an example of something you could create with your custom logic. It's not a real button and won't work out of the box!
 "myapp" is a placeholder for you application namespace.

For an example of an existing button that already works, please take a look at one of the buttons in https://github.com/google/shaka-player/blob/master/ui/ like the [mute button](https://github.com/google/shaka-player/blob/master/ui/mute_button.js).

If you're interested in creating a custom button, i could coach you through it, though! Did you have a specific button in mind?

For the seek bar color, looks like we did not update the tutorial after the structure of our code changed a bit. I will do that now, thank you for bringing this up!
The new constant for the color is shaka.ui.Constants.SEEK_BAR_BASE_COLOR in [ui/constants.js](https://github.com/google/shaka-player/blob/master/ui/constants.js)

**Comment by Atercatus** [comment]
I'm really appreciate for reply!
i wanna make next video button , but i don't know how to serve the video from node.js server to shaka player.  So, I'll study more and get help again later.

thanks!
