### ISSUE TITLE
WebVTT Subtitles not displayed after first period for DASH VOD asset

### ISSUE THREAD

**Issue by lyjimmy** [google/shaka-player#2006]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.2

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Both

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Chrome 75.0.3770.100 / macOS Mojave

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**
Will send to shaka-player-issues@google.com

**What did you do?**

1. Start playback
2. Turn on closed captions
3. Seek past the first period (~21:46)

**What did you expect to happen?**
The subtitles should still be displaying.

**What actually happened?**

The subtitles are not displayed. 

Notes:
I have a multi-period DASH VOD asset with segmented WebVTT subtitles. We were seeing that the Shaka player stopped displaying the subtitles after the first period.

After digging a bit deeper, I was seeing that the issue was with the cue startTime value calculation (https://github.com/google/shaka-player/blob/master/lib/text/mp4_vtt_parser.js#L223).

It looks like the Shaka player expects the tfdt box base media decode time to start at 0 at the beginning of each period. With this stream, the base media decode time does not reset at the period boundaries. As a result, the cue startTime values are much higher than they should be past the first period. The cues end up being ignored since they are outside the period boundaries.

The video and audio streams similarly do not reset the base media decode time after each period, but the Shaka player doesn't have any issue with this. I also tried playing the stream using the DASH IF Reference Client 2.9.3, and the subtitles were displayed correctly beyond the first period.

Would it be reasonable to instead calculate the cue startTime as the segmentStart value plus the trun sample_time_offset value? Or would that not have the same intended value?

I've seen some similar GitHub issues about the WebVTT timestamps being relative to the segments, but didn't see anything about the segment base media decode times being relative to the period.

Thanks!

**Comment by joeyparrish** [comment]
The other issues about WebVTT being relative to segments has to do with text-based WebVTT segments, not MP4-based WebVTT segments, so please disregard those.

If dash.js does it differently, it would be reasonable for us to assume we were doing it wrong.  But it would be best if we could find the relevant part of the spec and be able to quote it in a comment to ensure we are making the right change.

We should look into the DASH spec, DASH IOP, and VTT-in-mp4 spec to see if we can find exactly what we should be doing.  In the mean time, if you're interested in sending a PR with the change, a regression test, and a spec quote, we would be very happy to review it.  Thanks!

**Comment by TheModMaker** [comment]
I'm not sure if the DASH IF player is doing the right thing.  The DASH IOP section 6.4.2 says:

> TTML and WebVTT Media Segments shall be referenced by Representation elements in MPDs, downloaded, initialized, and synchronized for multimedia presentation the same as audio and video Segments. 

Which seems to suggest that we should treat the WebVTT segments the same as video segments, so they should be relative to the Period.  Also, for WebVTT in MP4, the ISO/IEC 14496-30 seems to suggest that the sample times are relative to the segment, similar to video segments.  So again, I think they should be Period-relative.

@lyjimmy do you have a place in one of the specs where the times would be presentation-absolute?  Most of DASH is all about being Period-relative so you can inject Periods without changing media content.

Note you can also use the `presentationTimeOffset` value to adjust the media times back to 0 for each Period.

**Comment by lyjimmy** [comment]
Thanks for the replies!

@TheModMaker We're in agreement that the WebVTT segments should be treated the same as the video segments. But I think this is where some of the confusion started since our video and audio segments have the same behavior as our WebVTT segments where the tfdt decode time values don't start at 0 at the beginning of each period. However, the Shaka Player looks to be handling the video and audio presentation timestamps without issue.

The current approach to calculating the cue start time in the mp4_vtt_parser is to sum the period start time, the tfdt decode time, and the trun sample composition time offset. With the assumption that the tfdt decode time starts at 0 at the beginning of each period, it seems to me that summing the period start time and the tfdt decode time is done to get the segment start time. However, the segment start time has already been calculated and is available in the `time` argument in the `parseMedia` method. That's why I was thinking `time.segmentStart` plus the trun sample composition time offset could be used instead of the current calculation. Alternatively there could be a decode time offset for each period based on the tfdt value of the first segment in the period, but this would be extra work.

It also doesn't look like the `presentationTimeOffset` value in the manifest is factored into cue start time calculation for the mp4_vtt.

I was initially hesitant to label this as a bug vs. a question since I couldn't find a particular place in the specifications that mentions whether the tfdt value needs to necessarily start at 0 at the start of each period. I ended up going with bug since the text segments were consistent with the audio/video segments and the subtitles were working with dash.js. However, I thought maybe there was something in the specs that I missed.

**Comment by TheModMaker** [comment]
The problem is that your video segments do reset their `tfdt` and `sidx` times.  So the single file has segments that go from 0 to the Period duration, then reset to 0 and go back up.  This is why the video stream works by itself.  The text segments don't reset at each Period so the times are wrong.

The way you do multi-Period with single-file is to have the media times go from 0 to duration like a normal single MP4 file, but have the second Period use `presentationTimeOffset` to adjust the second Period's segments back to 0.  But in your content, the segments have their media times reset.

I think this is a bug on the dash.js player.  They should be using the `tfdt` times to calculate the media times.  We should not use the `time.segmentStart` since we need to use the *media's* time, not the manifest's time.  Times in the manifest are expected to be inaccurate and the times in the media take precedence.  We should only use the Period start and the `presentationTimeOffset` to adjust the times within the media segments.

**Comment by lyjimmy** [comment]
@TheModMaker Big apologies! I definitely made a mistake when double-checking the tfdt values for the video segments at the period starts. I've reached out to the folks that work on the stream. Thanks so much for taking the time with this issue.
