### ISSUE TITLE
*Talk-Radio usecases* Minimize the Http Overhead of Single-file Content-ranges and CORS OPTIONS impact

### ISSUE THREAD

**Issue by jnorthrup** [google/shaka-player#2008]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
been following along and did not see this addressed.

**Is your feature request related to a problem? Please describe.**

shaka player is sending *Access-Control-Request-Headers:range* headers for single file adaptive stream media.

this triggeres the browser to send seperate OPTIONS method req to comply with CORS.

99% of the time  our media plays start at chunk 0 and proceed contiguously without rate jitter.

this needlessly increases the overheads and our storage bucket API costs as compared to non-adaptive streams. 

**Describe the solution you'd like**

in the case where the stream starts at byte 0, can the capabilities model of any browsers (chrome is all that matters) be checked for buffered reading at the desired rate without explicit chunk requests on contiguous chunks starting at 0?

we use single-file streams as a fallback option to efficiently provide the audio content to IOS and other primitive html media players via downloadable source tags.

the DASH solution actually becomes less efficient overall for the benefits of adaptive rate we can provide.  

**Describe alternatives you've considered**

we will gladly send a player hint if such a thing exists as well, but i dont see it listed in the issues.  

we can gladly share the particulars of ffmpeg encoding dahs/hls non-live transcodes to single-file streams. 

while not all viewers and streams "simply" play audio from chunk 0 and fixate on a  bandwidth, in our case we are modernizing an older CMS with new player capabilities and presumably this is a common usecase enabling near-perfect entropy mobile streams with older mp3/mpeg content stores that only need a hi and lo setting; so we see very little back and forth for talk-radio genre's and we're fine-tuning the server overheads.

the content and the media buckets live on different vhosts, granted, and we could reverse proxy all of this, adding more points of failure/billing,  but this  feature can be named and implemented if it isn't already.

**Comment by jnorthrup** [comment]
an alternative to recognizing the chunk 0 contiguous blocks might be to attempt to cache CORS OPTIONS for a given host for a given period, such that a 200 for one set of headers is assumed to be an all-clear for that host with the same set of headers.  but wait, it's up to the browser not the js code.

... so it seems to fall back to  virtualizing a chunk sequence with a simpler request when all the conditions are perfect, e.g. must be CORS, must be chunk 0, manifest must signal seek-points, etc. and discarding the virtualized sequence for the existing method when signals creation imperfect download conditions

**Comment by TheModMaker** [comment]
We don't controls CORS requests, so the only option would be to make a "simple request" to avoid the OPTIONS request.  This would only be possible by requesting the whole file, which won't be possible for large files.

One possible option would be a streaming download, but that would only be possible for supported servers and browsers.  But this is excessively complicated and won't work with seeking and not all content will support that.  So that isn't something we would want to support.

**Comment by joeyparrish** [comment]
@jnorthrup, I'm sorry we are not able to help you with this, but as @TheModMaker points out, CORS is outside of our control, and Shaka Player is built for segmented streaming.  I'm going to go ahead and close this issue, but please feel free to open another one if there's anything else you need.
