### ISSUE TITLE
Error codes

### ISSUE THREAD

**Issue by sanbornhnewyyz** [google/shaka-player#201]
Can we add error codes to the major Shaka errors so that they are easy to map? We are in a position where we want to funnel Shaka errors through our own application error pipeline so that we can have a consistent error interface. But it's difficult to map to our own error codes because the errors only contain messages which might change.

**Comment by joeyparrish** [comment]
This is a great idea.  We'll be sure to add this to the design for v2.0.

**Comment by joeyparrish** [comment]
Finished in 6231488.  All reported errors in v2.0 are shaka.util.Error type.  They have a category (network, media, drm, etc.) and a specific error code, both of which are numerical and fully-documented.

**Comment by sanbornhnewyyz** [comment]
This great. The hard work is much appreciated.

**Comment by sanbornhnewyyz** [comment]
Now that I'm looking at this more closely I do have a quick question. You mention a DRM category in your comment but there isn't a DRM category in the `Error.Category` object. Is there a plan to add error codes for this in the future? One of the problems that we have had is recognizing DRM errors because no codes are provided and error messages seem to be changing often. Do you have any thoughts on this?

**Comment by joeyparrish** [comment]
The new DrmEngine is still a work-in-progress and hang been published yet.  But we will have a DRM error category and specific codes for various errors.

There are not standard error codes for CDMs in the EME spec, but we will try to divine as much as we can when we can.  For the rest, we will include error strings from the CDM.  Hopefully, we can get the important stuff.

What situations are important to you?

**Comment by sanbornhnewyyz** [comment]
Okay, great. 

The lack of standard error codes is something we have been trying to determine how to handle.

We are interested in stuff like:

* DRM is disabled
* License is expired
* License can’t be installed

But I'm not even sure if these are all possible to recognize or if error messages are the best we will get.

Do you have an idea about what the cross browser support will be for these? Is it possible to determine these things consistently across browsers?

**Comment by joeyparrish** [comment]
* I'm not sure we can know from JS that DRM is disabled.  At most, we could know that none of the application's requested key system configurations are available.  (Unavailable may mean disallowed by the user in the case of persistent licenses, but we won't know the difference.)
* License expiration is easy and cross-browser.
* What does it mean that a license "can't be installed"?  Malformed data or something otherwise rejected by the CDM?

**Comment by sanbornhnewyyz** [comment]
Yeah, basically, you get something back from the license server but it's rejected by the CDM.

**Comment by joeyparrish** [comment]
That should be trivial and cross-platform.  The Promise returned by update() would be rejected in that case.
