### ISSUE TITLE
Custom UI control not working because property names get changed by minification.

### ISSUE THREAD

**Issue by shvelo** [google/shaka-player#2011]
I'm trying to make a custom UI controller, but because minification changes all the object property names in Shaka libraries, I cannot access any of them. The example in https://shaka-player-demo.appspot.com/docs/api/tutorial-ui-customization.html does not work at all because `this.parent` is undefined, having changed to `this.l`, I can't even find what `this.eventManager` is changed to.

Is there anything I can do besides using the uncompiled player?

**Comment by ismena** [comment]
Hi @shvelo 
Thanks for bringing this up, I will update the tutorial!

Try adding your custom button to [build/types/ui](https://github.com/google/shaka-player/blob/master/build/types/ui) and then running [build/all.py](https://github.com/google/shaka-player/blob/master/build/all.py).

You can also forgo extending shaka.UI.Element if you don't need it's members and just implement shaka.extern.IUIElement like the [close button](https://github.com/google/shaka-player/blob/master/demo/close_button.js) does on our demo page.

**Comment by joeyparrish** [comment]
You *should* be able to extend `shaka.UI.Element` and take advantage of things like `this.eventManager` without adding your custom button to the library.  We'll take this as a bug and try to fix it in the next release.  In the mean time, adding it to the library as @ismena described should be a usable workaround. 
 Thanks for reporting!

**Comment by ismena** [comment]
Ok, this should be working in the latest master now even without the above workaround. Please, let us know how it goes!
