### ISSUE TITLE
Cast button dont work

### ISSUE THREAD

**Issue by ivansteff** [google/shaka-player#2012]
(Use vueJS).
I add a `onCastClick_ ` function to the button.
On click should work.

`<button  @click="onCastClick_()">cast</button>
`

```
 async onCastClick_() {
                if (this.castProxy_.isCasting()) {
                    this.castProxy_.suggestDisconnect();
                } else {
                    try {
                        this.castButton_.disabled = true;
                        await this.castProxy_.cast();
                        this.castButton_.disabled = false;
                    } catch (error) {
                        this.castButton_.disabled = false;
                        if (error.code != shaka.util.Error.Code.CAST_CANCELED_BY_USER) {
                            this.controls.dispatchEvent(new shaka.util.FakeEvent('error', {
                                detail: error,
                            }));
                        }
                    }
                }
            },
```
The following error is returned in the console:

```
myComponent.vue?9ebd:339 Uncaught (in promise) TypeError: Cannot read property 'isCasting' of undefined
    at VueComponent._callee$ (myComponent.vue?9ebd:339)
    at tryCatch (runtime.js?96cf:62)
    at Generator.invoke [as _invoke] (runtime.js?96cf:296)
    at Generator.prototype.<computed> [as next] (runtime.js?96cf:114)
    at asyncGeneratorStep (asyncToGenerator.js?3b8d:5)
    at _next (asyncToGenerator.js?3b8d:27)
    at eval (asyncToGenerator.js?3b8d:34)
    at new Promise (<anonymous>)
    at new F (_export.js?d13f:36)
    at VueComponent.eval (asyncToGenerator.js?3b8d:23)
```

What am I doing wrong?

**Comment by joeyparrish** [comment]
Inside `onCastClick_`, put a break point in the debugger.  What is the value of `this`?  It's probably not what you think it is.

**Comment by ivansteff** [comment]
@joeyparrish 

VueComponent {_uid: 46, _isVue: true, $options: {…}, _renderProxy: Proxy, _self: VueComponent, …}
$attrs: (...)
$children: (20) [VueComponent, VueComponent, VueComponent, VueComponent, VueComponent, VueComponent, VueComponent, VueComponent, VueComponent, VueComponent, VueComponent, VueComponent, VueComponent, VueComponent, VueComponent, VueComponent, VueComponent, VueComponent, VueComponent, VueComponent]
$createElement: ƒ (a, b, c, d)
$el: div.player__main
$listeners: (...)
$options: {parent: VueComponent, _parentVnode: VNode, _parentElm: null, _refElm: null, propsData: {…}, …}
$parent: VueComponent {_uid: 45, _isVue: true, $options: {…}, _renderProxy: Proxy, _self: VueComponent, …}
$refs: {main: div.player__main, tvControlsSwiper: Array(10)}
$root: Vue {_uid: 3, _isVue: true, $options: {…}, _renderProxy: Proxy, _self: Vue, …}
$scopedSlots: {}
$slots: {}
$store: Store {_committing: false, _actions: {…}, _actionSubscribers: Array(0), _mutations: {…}, _wrappedGetters: {…}, …}
$vnode: VNode {tag: "vue-component-194-TvPlayer", data: {…}, children: undefined, text: undefined, elm: div.player__main, …}
bufferEvent: ƒ ()
buffered: (...)
buttonNext: (...)
buttonPrev: (...)
canFullscreen: (...)
computedBuffer: (...)
controlsOpacity: (...)
end: 1500
endVideo: ƒ ()
epg: Array(10)
filteredPrograms: ƒ ()
flowWorker: (...)
fullScreen: ƒ ()
fullScreenObj: (...)
getTime: (...)
getTimeFormat: ƒ ()
getTimeLineProgress: ƒ ()
hideChannelInfo: ƒ ()
hideControls: ƒ ()
initActions: ƒ ()
isFullscreen: (...)
live: (...)
loading: (...)
middleControlsOpacity: (...)
mouseWait: (...)
mute: ƒ ()
muted: (...)
next: ƒ ()
nextVideo: (...)
onCastClick_: ƒ ()
onEnterFullscreen: ƒ ()
onEnterPictureInPicture_: ƒ ()
onExitFullscreen: ƒ ()
onKeydown: ƒ ()
onLeavePictureInPicture_: ƒ ()
onMouseMove: ƒ ()
onPipClick_: ƒ ()
playVideo: ƒ ()
played: (...)
player: (...)
prev: ƒ ()
programCalendar: (...)
progressLoading: (...)
qwe: (...)
range: (...)
selectChannel: ƒ ()
selectProgram: ƒ ()
selectedProgramDay: (...)
selectedProgramDetail: (...)
selected_tv_category: (...)
selected_tv_channel: (...)
showBuffer: ƒ ()
showControls: ƒ ()
showHideEpgFullscreen: ƒ ()
showProgress: ƒ ()
showSOME: (...)
showSOME: ƒ ()
showSOME: (...)
start: (...)
startLoading: ƒ ()
stopLoading: ƒ ()
stopVideo: ƒ ()
subChange: ƒ ()
subList: ƒ ()
swiper: (...)
swiperOption: (...)
thenBuffer: ƒ ()
video: (...)
volume: (...)
waitBuffer: ƒ ()
waitParams: ƒ ()
waitVideoLoading: ƒ ()
_c: ƒ (a, b, c, d)
_computedWatchers: {swiper: Watcher, getTime: Watcher}
_data: {…}
_directInactive: false
_events: {switchProgram: Array(1), getChannelFromFullscreenMode: Array(1), 
_hasHookEvent: false
_inactive: null
_isBeingDestroyed: false
_isDestroyed: false
_isMounted: true
_isVue: true
_name: "<Player>"
_props: {…}
_renderProxy: Proxy {_uid: 46, _isVue: true, $options: {…}, _renderProxy: Proxy, _self: VueComponent, …}
_routerRoot: Vue {_uid: 3, _isVue: true, $options: {…}, _renderProxy: Proxy, _self: Vue, …}
_self: VueComponent {_uid: 46, _isVue: true, $options: {…}, _renderProxy: Proxy, _self: VueComponent, …}
_staticTrees: null
_uid: 46
_vnode: VNode {tag: "div", data: {…}, children: Array(5), text: undefined, elm: div.player__main, …}
_watcher: Watcher {vm: VueComponent, sync: false, lazy: false, user: false, deep: false, …}
_watchers: (5) [Watcher, Watcher, Watcher, Watcher, Watcher]
$data: (...)
$isServer: (...)
$props: (...)
$route: (...)
$router: (...)
$ssrContext: (...)
get $attrs: ƒ reactiveGetter()
set $attrs: ƒ reactiveSetter(newVal)
get $listeners: ƒ reactiveGetter()
set $listeners: ƒ reactiveSetter(newVal)
get buffered: ƒ proxyGetter()
set buffered: ƒ proxySetter(val)
get canFullscreen: ƒ proxyGetter()
set canFullscreen: ƒ proxySetter(val)
get computedBuffer: ƒ proxyGetter()
set computedBuffer: ƒ proxySetter(val)
get controlsOpacity: ƒ proxyGetter()
set controlsOpacity: ƒ proxySetter(val)
get count: ƒ proxyGetter()
set count: ƒ proxySetter(val)
get currentTheme: ƒ proxyGetter()
set currentTheme: ƒ proxySetter(val)
get currentTime: ƒ proxyGetter()
set currentTime: ƒ proxySetter(val)
get flowWorker: ƒ proxyGetter()
set flowWorker: ƒ proxySetter(val)
get fullScreenObj: ƒ proxyGetter()
set fullScreenObj: ƒ proxySetter(val)
get isFullscreen: ƒ proxyGetter()
set isFullscreen: ƒ proxySetter(val)
get loading: ƒ proxyGetter()
set loading: ƒ proxySetter(val)
get middleControlsOpacity: ƒ proxyGetter()
set middleControlsOpacity: ƒ proxySetter(val)
get mouseWait: ƒ proxyGetter()
set mouseWait: ƒ proxySetter(val)
get muted: ƒ proxyGetter()
set muted: ƒ proxySetter(val)
get played: ƒ proxyGetter()
set played: ƒ proxySetter(val)
get programCalendar: ƒ proxyGetter()
set programCalendar: ƒ proxySetter(val)
get progressLoading: ƒ proxyGetter()
set progressLoading: ƒ proxySetter(val)
get qwe: ƒ proxyGetter()
set qwe: ƒ proxySetter(val)
get range: ƒ proxyGetter()
set range: ƒ proxySetter(val)
get selectedProgramDay: ƒ proxyGetter()
set selectedProgramDay: ƒ proxySetter(val)
get showTvCategories: ƒ proxyGetter()
set showTvCategories: ƒ proxySetter(val)
get show_epg_fullscreen: ƒ proxyGetter()
set show_epg_fullscreen: ƒ proxySetter(val)
get start: ƒ proxyGetter()
set start: ƒ proxySetter(val)
get swiperOption: ƒ proxyGetter()
set swiperOption: ƒ proxySetter(val)
get theme: ƒ proxyGetter()
set theme: ƒ proxySetter(val)
get video: ƒ proxyGetter()
set video: ƒ proxySetter(val)
get videoTracks: ƒ proxyGetter()
set videoTracks: ƒ proxySetter(val)
get volume: ƒ proxyGetter()
set volume: ƒ proxySetter(val)
__proto__: Vue

**Comment by joeyparrish** [comment]
So when your callback invokes `this.castProxy_.isCasting()`, the error `Cannot read property 'isCasting' of undefined` means that `this.castProxy_` is `undefined`.  And indeed, if `this` in the callback is the `VueComponent` you posted above, there is no `castProxy_` member on it.

Does this answer your question?

**Comment by ivansteff** [comment]
I did it differently, nothing happens when I press the button. 
I did it differently, nothing happens when I press the button, how can I make sure that when I click it shows available devices for translation?
Maybe I'm doing something wrong?

```
import ShakaControls from "../../../common/controls"

 CastClick_() {
 ShakaControls.prototype.onCastClick_();
 },

```
### **controls**

```
export default function ShakaControls() {
  /** @private {boolean} */
  this.enabled_ = true;

  /** @private {shaka.cast.CastProxy} */
  this.castProxy_ = null;

  /** @private {boolean} */
  this.castAllowed_ = true;

.......................................

/** @private */
ShakaControls.prototype.onCastClick_ = function () {
  
  if (!this.enabled_) return;

  console.log("cast");

  if (this.castProxy_.isCasting()) {
    this.castProxy_.suggestDisconnect();
  } else {
    this.castButton_.disabled = true;
    // Disable the load/unload buttons, to prevent the users from trying to load
    // an asset while the cast proxy is connecting.
    // That can lead to strange, erratic behavior.
    document.getElementById("loadButton").disabled = true;
    document.getElementById("unloadButton").disabled = true;
    this.castProxy_.cast().then(
      function () {
        document.getElementById("loadButton").disabled = false;
        document.getElementById("unloadButton").disabled = false;
        this.castButton_.disabled = false;
        // Success!
      }.bind(this),
      function (error) {
        this.castButton_.disabled = false;
        document.getElementById("loadButton").disabled = false;
        document.getElementById("unloadButton").disabled = false;
        if (error.code != shaka.util.Error.Code.CAST_CANCELED_BY_USER) {
          this.onError_(error);
        }
      }.bind(this)
    );
  }
};

```

**Comment by ismena** [comment]
Hi @ivansteff 
Is there any way we could try your code out?
The first sample you posted seemed to be based on our latest code while the new looks a lot like the sample UI we had before 2.5. I'm having trouble understanding how those can co-exit within the same application and if the problem comes from the piece of code you posted or the larger application.

Are you using our UI library on creating your own? I'd be happy to debug with you, if I can access the app.

**Comment by TheModMaker** [comment]
You can't just call `ShakaControls.prototype.onCastClick_()` since then the `this` value won't be correct.  You need to call that function as a member function with an object instance.  For example:

```js
const obj = new ShakaControls();
obj.onCastClick_();
```

You'll need to store the instance in a global variable to be accessible from the event callback or you can attach the event listener dynamically during setup.  For example:

```js
const obj = new ShakaControls();
const button = document.getElementById('myButton');
button.addEventListener('click', () => obj.onCastClick_());
```

**Comment by ivansteff** [comment]
@TheModMaker return error:
```
Uncaught TypeError: Cannot read property 'isCasting' of null
    at ShakaControls.onCastClick_ (controls.js?51b0:777)
    at HTMLButtonElement.eval (tvControls.vue?9ebd:697)
```

**_controls.js_**
![image](https://user-images.githubusercontent.com/31563237/60438269-f7ad7900-9c18-11e9-9de2-38d9ac112f9e.png)

**_tvControls.vue_**
```
 <button id="castButton" ref="castButton">
                            <v-tooltip top>
                                <v-icon class="controls-white material-icons-outlined" @click="CastClick_()"
                                    slot="activator">cast</v-icon>
                                <span>cast</span>
                            </v-tooltip>
                        </button>
...............................................................................
        methods: {
            CastClick_() {
                const obj = new ShakaControls();
                obj.onCastClick_();
            },
}

```

**Comment by ivansteff** [comment]
@ismena I think, unfortunately, this is impossible, the service with which I work, broadcasts only in Belarus.

**Comment by TheModMaker** [comment]
You need to initialize the `castProxy_` field.  Your constructor sets it to `null` initially, you need to create the cast proxy at some point before the button is pressed.

**Comment by ivansteff** [comment]
@TheModMaker  like this?
```
const obj = new ShakaControls();
obj.init();
obj.castProxy_();
```

**Comment by TheModMaker** [comment]
Yes.  You'll probably want to call `init()` in some central initialization location so it isn't called multiple times.  So you'll need to store the controls object globally so the event handler can see it.

**Comment by ivansteff** [comment]
@TheModMaker Omg....
 `Uncaught TypeError: Cannot read property 'getVideo' of undefined`
On this method `ShakaControls.prototype.init = function (castProxy, onError, notifyCastStatus)`.
Line   ` this.initMinimal(castProxy.getVideo(), castProxy.getPlayer());
`

**Comment by joeyparrish** [comment]
@ivansteff, you seem to be having trouble with `castProxy` being undefined.  Did you pass a value for that argument?

Also, it looks like you're building off of `ShakaControls`, which was part of our demo prior to v2.5 and never a supported part of the library.  If you want to use those demo sources, of course, the license permits this.  But we can't offer you any further technical support for that.  I apologize for any inconvenience.

In v2.5, we released the Shaka UI library, in which we offer fully-supported video controls that overlay the video and can be styled and customized.  If you would like to use those, we can help you with that.  Please check out our [UI tutorial](https://shaka-player-demo.appspot.com/docs/api/tutorial-ui.html) for details, and please open a new issue if you need assistance with that.

For now, I'm going to go ahead and close this issue about the unsupported `ShakaControls` class.
