### ISSUE TITLE
DASH vs. HLS Quality selection 

### ISSUE THREAD

**Issue by ivansteff** [google/shaka-player#2014]
For flow DASH i use field `originalVideoId` but in flow HLS, field `originalVideoId` return null.Because of this, I can not choose the quality, is there any alternative?
I don’t remember the exact name of the method who get  `originalVideoId` field  .

**Comment by ismena** [comment]
Hi @ivansteff 
Let's see if I understood you correctly: you know which video resolution you want and need a way to select it, is that right?

**Comment by TheModMaker** [comment]
The `player.getVariantTracks()` method returns an array of [Track](https://shaka-player-demo.appspot.com/docs/api/shaka.extern.html#.Track) objects that contain that field.  You can also use the `width`, `height`, or `bandwidth` fields to determine the resolution.  Then use `player.selectVariantTrack(track)` to switch to it.

**Comment by ivansteff** [comment]
@ismena yes.

**Comment by ivansteff** [comment]
@TheModMaker Did I understand you correctly, that in the `player.selectVariantTrack (track) `method we pass one objects of the `player.getVariantTracks ()` ?
I tried to do as you wrote. When choosing quality, nothing happens.

**Comment by TheModMaker** [comment]
Correct.  Check the console log (and use a debug or uncompiled build) to see if there are any error logs; the call is ignored if there are errors.  Also note that:

1. This won't change ABR, so ABR may revert your change.  You should disable ABR first.
1. The default is to not clear the buffer, so you'll see the old content until you get to the end of the buffer.  Pass `true` as a second argument to clear the buffer when switching.

**Comment by ivansteff** [comment]
@TheModMaker one more question
                   ```
 this.player.configure({
                        abr: {
                            enabled: false
                        }
                    });
                    this.player.selectVariantTrack(track, true);
                    this.active = id;
```
 ` this.player.selectVariantTrack(track, true);` this line to select a certain quality, and what is the quality selection automatically?
Need to simply delete this line?

  ```
 this.player.configure({
                        abr: {
                            enabled: false
                        }
                    });
                    this.active = id;
```
All right?

**Comment by joeyparrish** [comment]
@ivansteff, I'm not sure I understand your question.  I'll try to explain the difference between the two examples you gave.

The `configure` call will disable ABR (Adaptive BitRate), so that the Player will not make any more automatic decisions to change tracks.  The `selectVariantTrack` call selects a particular track (which you chose by its quality level).  So if you delete the call to `selectVariantTrack`, you will only be disabling ABR and leaving the track as it was.

Does this answer your question?

**Comment by ivansteff** [comment]
@joeyparrish Yes, I understand. 
Many thanks to everyone who helped me deal with this issue!
