### ISSUE TITLE
Error with ignoreMinBufferTime --> Cannot read property 'variants' of null

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#2015]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** yes

**What version of Shaka Player are you using?** 2.5.2

**Can you reproduce the issue with our latest release version?** Yes

**Can you reproduce the issue with the latest code from `master`?** Yes

**Are you using the demo app or your own custom app?** Both

**If custom app, can you reproduce the issue using our demo app?** Yes

**What browser and OS are you using?**
Chrome 75 over macOS Mojave

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

https://livesim.dashif.org/livesim/segtimeline_1/utc_head/testpic_6s/Manifest.mpd

**What did you do?**

Load the next page: https://shaka-player-demo.appspot.com/demo/#audiolang=es-ES;textlang=es-ES;ignoreMinBufferTime=true;uilang=es-ES;asset=https://livesim.dashif.org/livesim/segtimeline_1/utc_head/testpic_6s/Manifest.mpd;panel=SEARCH;build=uncompiled

Stream url: https://livesim.dashif.org/livesim/segtimeline_1/utc_head/testpic_6s/Manifest.mpd
Enable ignoreMinBufferTime param (custom config)

**What did you expect to happen?**
The video start without any problem

**What actually happened?**

There are a error: "Cannot read property 'variants' of null"

<img width="1440" alt="error" src="https://user-images.githubusercontent.com/8983024/60424664-1f88e680-9bf1-11e9-800b-45a6a51e447a.png">

**Comment by theodab** [comment]
Ok, after looking over it, I found a bug in the DASH parser where it can end up setting the `presentationDelay` to `NaN` in some situations. Now that I see it, it's obvious enough that I briefly wondered if that was somehow intended behavior. I'll get a CL out soon. Thanks for the bug report!
