### ISSUE TITLE
DRM Playback Fails on custom compiled build that has audio/video robustness specified in config

### ISSUE THREAD

**Issue by bcupac** [google/shaka-player#2017]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

Yes
**What version of Shaka Player are you using?**

Master
**Can you reproduce the issue with our latest release version?**

N/A
**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Custom

**If custom app, can you reproduce the issue using our demo app?**

Yes
**What browser and OS are you using?**

Chrome,MacOS
**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What did you do?**

made a custom shaka player build:
```
./build.py +@networking +@manifests +@polyfill +@text --name compiled --force
```

**What did you expect to happen?**
DRM Playback should work

**What actually happened?**

DRM Playback startup is failing, error 6002, b.cc.a is not a function...

Turns out that this part of player config is causing it
```
{
...
    advanced: {
      "com.widevine.alpha": {
        videoRobustness: "SW_SECURE_CRYPTO",
        audioRobustness: "SW_SECURE_CRYPTO"
      },
    }
}
```

**Comment by joeyparrish** [comment]
I'm unable to reproduce your results.  Here are my steps:

```sh
./build/build.py +@networking +@manifests +@polyfill +@text --name compiled --force
```

```html
<!DOCTYPE html>
<html>
  <head>
    <script src="dist/shaka-player.compiled.js"></script>
    <script src="myapp.js"></script>
  </head>
  <body>
    <video id="video" width="640" controls autoplay></video>
  </body>
</html>
```

```js
// myapp.js

function initApp() {
  shaka.polyfill.installAll();

  player = new shaka.Player(video);

  drm = {
    advanced: {
      "com.widevine.alpha": {
        videoRobustness: "SW_SECURE_CRYPTO",
        audioRobustness: "SW_SECURE_CRYPTO"
      },
    }
  };

  console.log('RESULT', player.configure({drm}));
}

document.addEventListener('DOMContentLoaded', initApp);
```

When I run this in Chrome, I get "RESULT true" in the JS console.
