### ISSUE TITLE
Seek bar not visible when playing heliocentrism

### ISSUE THREAD

**Issue by TheModMaker** [google/shaka-player#2018]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v2.5.2 and nightly (v2.5.2-master-42-gfe7f4210)

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Demo app

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
Chrome for Linux

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

https://storage.googleapis.com/shaka-demo-assets/heliocentrism/heliocentrism.mpd

**What did you do?**

https://nightly-dot-shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://storage.googleapis.com/shaka-demo-assets/heliocentrism/heliocentrism.mpd;panel=SEARCH;build=uncompiled

**What did you expect to happen?**
Seek bar visible and video is seekable.

**What actually happened?**
No seek bar and no way in the UI to seek the video.

**Comment by joeyparrish** [comment]
I wonder if this has to do with the length of the presentation.  It's a very short clip, and the heuristic for dealing with very small seek ranges might be firing even for this VOD clip.

**Comment by ismena** [comment]
Yup, it's the [shaka.ui.Constants.MIN_SEEK_WINDOW_TO_SHOW_SEEKBAR](https://github.com/google/shaka-player/blob/3bde775c53423c34650ebb26c369ac9690a952ab/ui/constants.js#L61), current set to 5 seconds :)
