### ISSUE TITLE
PIPELINE_ERROR_DECODE error in Chrome with android phones.  What can we do to troubleshoot?

### ISSUE THREAD

**Issue by pineapplejoe** [google/shaka-player#2020]
Formatted as a bug but submitting a question as we dont have a repro and the request is to figure out how we can get one. 

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

Yes.  We saw another item with the same PIPELINE_ERROR_DECODE and that issue seemed to potentially about hardware decoding. We are unable to repro on our various devices 

**What version of Shaka Player are you using?**

Recently updated to 2.5.3 but was previously on 2.5.2. 

**Can you reproduce the issue with our latest release version?**

Just updated so no data yet.  It is random so it takes a while to see it. 

**Can you reproduce the issue with the latest code from `master`?**

Huh?

**Are you using the demo app or your own custom app?**

Custom app

**If custom app, can you reproduce the issue using our demo app?**

We dont have an in house repro with any app. 

**What browser and OS are you using?**

Based on logs various Chrome versions with Android OS versions appear to repro.  

Last one in logs was Chrome 75.0.3770.101 on Android v8.0.0.
One before that was Chrome 70.0.3538.80 on Android v6.0.1
 
**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

NA

**What are the manifest and license server URIs?**

We dont use a license server.  We are using signed cookies. 

What can we do to capture more data when the error occurs so that we may be able to troubleshoot further? 

**What did you do?**

This appears to happen during initialization of the video. The video never reaches the state where it "canplay".

**What did you expect to happen?**

No error.

**What actually happened?**

Again we cant repro this in house but this is what we get in logs when we listen to the "error" event on the Shaka player object.  Once the error happens in the field - that particular user is blocked.  We dont know of a workaround. 

```
shaka.util.Error {
  "severity": 2,
  "category": 3,
  "code": 3016,
  "data": [
    3,
    null,
    "PIPELINE_ERROR_DECODE: video decoder reinitialization failed"
  ],
  "handled": false
}
shaka.util.Error {
  "severity": 2,
  "category": 3,
  "code": 3015,
  "data": [
    {
      "stack": "Error: Failed to execute 'appendBuffer' on 'SourceBuffer': The HTMLMediaElement.error attribute is not null.\n    at ce.p.ce (https://worldalive.tours/scripts/shaka-player/dist/shaka-player.compiled.js:135:430)\n    at le (https://worldalive.tours/scripts/shaka-player/dist/shaka-player.compiled.js:137:269)\n    at ke (https://worldalive.tours/scripts/shaka-player/dist/shaka-player.compiled.js:133:414)\n    at Gi.<anonymous> (https://worldalive.tours/scripts/shaka-player/dist/shaka-player.compiled.js:349:245)"
    }
  ],
  "handled": false
}
shaka.util.Error {
  "severity": 2,
  "category": 3,
  "code": 3015,
  "data": [
    {
      "stack": "Error: Failed to execute 'appendBuffer' on 'SourceBuffer': The HTMLMediaElement.error attribute is not null.\n    at ce.p.ce (https://worldalive.tours/scripts/shaka-player/dist/shaka-player.compiled.js:135:430)\n    at le (https://worldalive.tours/scripts/shaka-player/dist/shaka-player.compiled.js:137:269)\n    at ke (https://worldalive.tours/scripts/shaka-player/dist/shaka-player.compiled.js:133:414)\n    at Gi.<anonymous> (https://worldalive.tours/scripts/shaka-player/dist/shaka-player.compiled.js:349:245)"
    }
  ],
  "handled": false
}
```

**Comment by joeyparrish** [comment]
`PIPELINE_ERROR_DECODE` would seem to indicate that the media pipeline in Chrome on Android has failed to decode your content for some reason.

I would suggest navigating to `chrome:media-internals` for more info at the Chrome level.  Please try it and let us know what you find.

On Android, you may also want to try adb logcat.  I don't have much experience in this area, but I seem to recall that you can see additional information at the Android codec level.

**Comment by pineapplejoe** [comment]
Thanks Joey. 

Unfortunately we don't have repros so the only devices are in the hands of users who have clicked on ads.  I previously looked into whether we could capture chrome://media-internals via javascript but it doesnt appear to be possible. 

Do you think the data from a non reproing device would still be useful? We certainly have those.

**Comment by joeyparrish** [comment]
You're right, there's no way to capture chrome:media-internals in JS.

I'm not sure what else to say.  We've certainly seen examples of hardware decode failures on certain devices.  Usually it is a matter of the encoding profile or other codec-level options that are not supported by that hardware.  You can test this theory by disabling hardware decode on a certain device, but I'm not sure what you can do without a failing device in hand.

As an experiment, you could change the encoding parameters (if it's a live stream and not already long-since encoded) for some subset of users and see if the problem gets better compared to a control group.  I'm not sure what else you can try off the top of my head.
