### ISSUE TITLE
Is it possible to ignore an empty AdaptationSet?

### ISSUE THREAD

**Issue by DmitryZhelnin** [google/shaka-player#2023]
I'm trying to play DASH stream in Shaka Player. Sometimes the stream doesn't have an audio source and its manifest file contains an empty AdaptationSet entry. In this case Shaka Player returns the manifest parsing error:

> | DASH_EMPTY_ADAPTATION_SET | 4003 | number |  The DASH Manifest contained an AdaptationSet with no Representations. |

Is it possible to ignore this error somehow and play the video without audio source?

Example of manifest file:
```
<?xml version="1.0" encoding="utf-8"?>
<MPD xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="urn:mpeg:dash:schema:mpd:2011"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    xsi:schemaLocation="urn:mpeg:DASH:schema:MPD:2011 http://standards.iso.org/ittf/PubliclyAvailableStandards/MPEG-DASH_schema_files/DASH-MPD.xsd"
    profiles="urn:mpeg:dash:profile:isoff-live:2011"
    type="dynamic"
    minimumUpdatePeriod="PT4S"
    suggestedPresentationDelay="PT4S"
    availabilityStartTime="2019-06-24T13:38:04Z"
    publishTime="2019-06-24T13:38:34Z"
    timeShiftBufferDepth="PT14.9S"
    minBufferTime="PT9.9S">
    <ProgramInformation>
        <Title>Media Presentation</Title>
    </ProgramInformation>
    <Period id="0" start="PT0.0S">
        <AdaptationSet id="0" contentType="video" segmentAlignment="true" bitstreamSwitching="true">
            <Representation id="0" mimeType="video/mp4" codecs="avc1.640028" bandwidth="2000000" width="1920" height="1080" frameRate="20/1">
                <SegmentTemplate timescale="10240" initialization="init-stream$RepresentationID$.m4s" media="chunk-stream$RepresentationID$-$Number%05d$.m4s" startNumber="5">
                    <SegmentTimeline>
                        <S t="201697" d="51190" r="2" />
                    </SegmentTimeline>
                </SegmentTemplate>
            </Representation>
        </AdaptationSet>
        <AdaptationSet id="1" contentType="audio" segmentAlignment="true" bitstreamSwitching="true">
        </AdaptationSet>
    </Period>
</MPD>
```

**Comment by joeyparrish** [comment]
Why is there an empty AdaptationSet?  What packager/encoder are you using?

**Comment by DmitryZhelnin** [comment]
The stream is created by `ffmpeg` with explicit adaptation sets count `-adaptation_sets "id=0,streams=v id=1,streams=a"`.
Ffmpeg receives input streams from different cameras: some of them have audio stream and some don't have.
And I can't check if an audio stream is present beforehand.

**Comment by joeyparrish** [comment]
Ah, okay.  I think it would be reasonable to add a configuration for this in `manifest.dash`, perhaps `manifest.dash.ignoreEmptyAdaptationSet`.  We have always preferred to warn about unusual-looking content that may indicate an encoder problem, rather than silently ignoring (for example) an empty AdaptationSet.  But there's no reason we couldn't give the application more control over this.

Would you be interested in creating a pull request for this?

**Comment by DmitryZhelnin** [comment]
> Would you be interested in creating a pull request for this?

Why not, I'll give it a try.

**Comment by joeyparrish** [comment]
Thanks!  Configuration types live in externs/shaka/, and the defaults live in lib/util/player_configuration.js.

**Comment by theodab** [comment]
New configuration values should also be put into the demo config panel, in `demo/config.js`.

**Comment by joeyparrish** [comment]
These changes have been cherry-picked for v2.5.8.
