### ISSUE TITLE
Meaning of "Rejected with system code (19)" 

### ISSUE THREAD

**Issue by danmo** [google/shaka-player#2024]
Recently I've started getting "Rejected with system code (19)"  when trying to playback offline content. What it the meaning of code 19? and will they ever disclose some documentation on this error codes?

**Comment by joeyparrish** [comment]
I will ask the Widevine team to reconsider disclosing the error codes.

From what I can tell, it seems that this code may be associated with a malformed license response, but I'm not 100% certain of that.

Are you seeing this issue when playing content that is already stored offline?  What steps could I take to reproduce the issue?
