### ISSUE TITLE
Spurious 'webkitkeyerror' when using FairPlay

### ISSUE THREAD

**Issue by DamianImrich** [google/shaka-player#2031]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**Is your feature request related to a problem? Please describe.**
Expressplay and EZDRM implementation of fps_1.0 require using Uint16 initData but I think it's not possible in shaka.

**Describe the solution you'd like**
Means for modifying initData before it gets used or some boolean option for using Uint16 initData.

**Describe alternatives you've considered**
Videojs-eme-contrib fairplay implementation is someway using automatically Uint16 initData. But it looks like uint8 type of initdata is there too.
https://github.com/videojs/videojs-contrib-eme/blob/master/src/fairplay.js

**Additional context**
Here is manifest, certificate url and license server url for testing. It is playing well in videojs + eme contrib with nothing more than these three links and keysystem name (com.apple.fps.1_0).
https://goog.compozitive.com/w33/master.m3u8
https://goog.compozitive.com/fairplay.der
https://fp.service.expressplay.com/hms/fp/rights/?ExpressPlayToken=AQASOd0dKdMAAABQF4zh-leYoklHkoM1Vy9gKplqavpP-OBnIZYLYUKelxocJBoOL8pu7cdX1qFRXZ4CDrcBTKMAfsiahOpNaXlRZVtP1jqnwzCLWu_l5wKrZdG9_jWRpnikHWZCZqTqXplLTZCYIg

**Comment by joeyparrish** [comment]
Thanks!  We'll schedule this after we finish with v2.6.

**Comment by TheModMaker** [comment]
Your problem has nothing to do with Uint16Array.  First, your server requires removing the formatting we apply to the request (see #1951).  Second, your server requires setting the `Content-Type` header, even though it should be implicitly set.  Thirdly, we get a spurious `webkitkeyerror` event even though everything succeeds.

**Comment by TheModMaker** [comment]
Now that #1951 is (partially) fixed, there are only two problems left.  Setting the `Content-Type` header can be done with the request filter below.  I'll re-title this for the spurious errors we are seeing, but they appear to be non-fatal.

```js
player.getNetworkingEngine().registerRequestFilter((type, request) => {
  if (type == shaka.net.NetworkingEngine.RequestType.LICENSE) {
    request.headers['Content-Type'] = 'application/octet-stream';
  }
});
```

**Comment by joeyparrish** [comment]
@DamianImrich, I believe this has been fixed recently under a different issue number.  Can you please re-test with the latest release and let us know if the issue persists?
