### ISSUE TITLE
HLS Manifest fails to load with embedded text tracks

### ISSUE THREAD

**Issue by CurtisConway** [google/shaka-player#2037]
Hi, hope all is well! I've noticed an issue today with my HLS Manifests that have embedded text tracks in them. Before I get into the full issue itself, it's totally possible that this is an issue on Vimeo's end, but when I contacted them they refused any actual issue being present.

I'm currently building a custom Vue Component wrapper around Shaka. I have access to a library of ~13k unique videos, all uploaded at varying qualities and bitrates over the years. The only ones I've had an issue with up to this point are the ones with embedded text tracks.

I haven't jumped into the source yet, I thought I'd submit an issue first at least. It appears as though the code is just hitting a point where it's referencing an undefined property on an object. I'll post the errors in the details below.

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes. I see a few different issues for Manifests and VTT, but I didn't see my exact error anywhere.

**What version of Shaka Player are you using?**
2.5.3

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Did not try yet.

**Are you using the demo app or your own custom app?**
Both

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Ubuntu 18.04 - Chrome, Firefox
MacOS 10.14.5 - Chrome, Firefox (Safari seems to parse them fine with src="")

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
Heres 3 from the same course, all should have embedded text tracks

https://player.vimeo.com/external/217849817.m3u8?s=6e22ea5dc4f9aa27833f8c34db178545a64a8d17

https://player.vimeo.com/external/217857009.m3u8?s=88eb26853baaac585f0173df677eb2385157073b

https://player.vimeo.com/external/217872983.m3u8?s=0e52091b98b126df7afeb3107567f98444ceea5f

**What did you do?**
I just loaded the Manifest using the .load() method the same way I have with any other.

**What did you expect to happen?**
The video to load, and be playable.

**What actually happened?**
It seems like an error is being thrown and caught at the .load() method. I'll post the details for each browser below:

Chrome
```
TypeError: Cannot read property 'length' of undefined
    at Pg (text_parser.js:44)
    at oo (vtt_text_parser.js:429)
    at no.push../node_modules/shaka-player/dist/shaka-player.compiled.js.no.parseMedia (vtt_text_parser.js:198)
    at Xd.push../node_modules/shaka-player/dist/shaka-player.compiled.js.Xd.Lc (text_engine.js:173)
    at Gh (hls_parser.js:1894)
    at Ja.b (hls_parser.js:1672)
    at Ma (generator_engine]:795)
    at Na.next (generator_engine]:699)
    at c (execute_async_generator]:48)
```

Firefox
```
TypeError: "b.b is undefined"
    Pg text_parser.js:44
    oo vtt_text_parser.js:429
    parseMedia vtt_text_parser.js:198
    Lc text_engine.js:173
    Gh hls_parser.js:1894
    k hls_parser.js:1672
    Ma generator_engine]:795
    next generator_engine]:699
    c execute_async_generator]:48
    run polyfill.js:4399
    notify polyfill.js:4416
    flush polyfill.js:1501
```

**Comment by theodab** [comment]
Issue reproduced. I'll look into it. Thanks for the report!

**Comment by theodab** [comment]
I think I see the problem. The HLS parser is fetching the first 2048 bytes of the text, so that we can find the first cue and figure out the start time of the text content. But we try to parse all of the cues in that data, even though we don't really need to. This means that, if the file is larger than 2048 bytes, the text parser will try to parse half of a cue and hit an exception.
We didn't notice this before because it looks like none of our test content has captions files big enough. Whoops!

I'll make a CL to fix this. Again, thanks for the report.

**Comment by CurtisConway** [comment]
@theodab - Thanks so much for the extremely swift response! I'm glad the issue looks to be fairly trivial. Feel free to continue using those HLS Manifests for your own internal testing if you need (I don't believe those particular URLs should expire).

**Comment by CurtisConway** [comment]
@theodab - I noticed today an option in the streaming config called "ignoreTextStreamFailures". Is the intended behavior of this option to bypass/ignore the error in my issue or is it related to something else? I've noticed that if I set it to true I still can't get any playback from those sources.

**Comment by theodab** [comment]
`ignoreTextStreamFailures` is a config value for the streaming engine; the failure you are experiencing happens in the HLS parser, before the streaming engine is even made.
I suppose we could make an equivalent configuration for the HLS parser, that would make it pretend the manifest had no captions at all if they failed to load initially? I don't know if that has a lot of demand, though; like, I don't know if there are a lot of content providers who expect for their caption tracks to sometimes be missing. Maybe in an ad insertion context, where you don't trust the content provider as much?

**Comment by CurtisConway** [comment]
@theodab - Thanks for the clarification! In my particular case I hoping to find a workaround. I also have access to all of the text tracks as VTT files, in theory, if the cues are all set at the correct times I can just attach the text track to the shaka player manually and trigger selection/deselection of the subtitles that way, and they will all be in sync with the currentTime of the MediaElement.

It's a bit of a hack though seeing as Shaka as well as the manifest have all of that functionality caked in by default. I'm just going to sit tight until the underlying issue is addressed. I took a bit of time last night to look into it myself but I fear it might be a bit over my head.

I really appreciate all your help, thanks so much!

**Comment by theodab** [comment]
I have a CL out for review right now that, based on my manual testing, fixes your problem. It just needs to go through code review before it can be added to the project. So it hopefully won't be too long.

**Comment by CurtisConway** [comment]
Awesome. Thank you so much for your help!

**Comment by theodab** [comment]
No problem. If you have any further questions, feel free to ask. We're happy to help.

**Comment by CurtisConway** [comment]
@theodab - Thanks for addressing this, I've had some time to revisit this project now. I would assume your commit made it into the 2.5.4 release as the error described above no longer appears. However, I'm still getting player crashes on some of my videos with embedded text tracks.

I've done some more digging and I have a bit more info that might be helpful before I contact Vimeo about this I'd like to get your opinion first:

If you load the following manifest into the demo player you'll notice it plays fine and the captions work as expected. Awesome!
https://player.vimeo.com/external/217879744.m3u8?s=95d405d9b1bfdb66c2a3f760f4efcf0def01110b

If you load this manifest into the demo player we get an error:
`"UNABLE_TO_EXTRACT_CUE_START_TIME"`
https://player.vimeo.com/external/217888285.m3u8?s=31641cf0bf55d7ddd3b94611105c143382a703dd

If we actually download the manifest file we can see that the working video is pointing to a nice clean direct URL:
https://skyfire.vimeocdn.com/1565382203-0x43aaee639e8955649c19c907fb49f64a0fcb7a41/217879744/subtitles/4987498/playlist.m3u8?d=963.879563

If we download the manifest for the video that's not working, we notice the text track playlist has some sort of signed URL with an expiry and a secret:
https://86skyfiregce-vimeo.akamaized.net/exp=1565382187~acl=%2F217888285%2F%2A~hmac=58054ca5433562c6e12b256529ab6a15b57a5016a8e1a6dd6c19f2888043663c/217888285/subtitles/4987499/playlist.m3u8?d=650.107771

While monitoring the network tab as the requests are going through, there's nothing to make me believe the requests are being blocked, I can still see the direct request to the VTT file for both videos, they both return a 200 response, it's just the ones with the weird signed URLs that fail.

It's also worth noting that the VTT files themselves are very similar in size and identical in formatting.

My question is: Do I need to pass some sort of DRM config in this case to handle these text tracks? Or is this something I should just get in contact with Vimeo about?

**Comment by joeyparrish** [comment]
I've never seen encrypted text tracks, and text doesn't get processed through the browser's CDM (Content Decryption Module), so it's not a DRM issue.

It looks like a known issue in our HLS implementation, which happens to have a fix in progress.  In short, we are trying to extract start timestamps from segments, and this doesn't work well on text.  We should be able to avoid this, though, with an upcoming optimization.

You can follow #1563 and #1558 for the fix.

**Comment by TheModMaker** [comment]
That commit did NOT make it into the v2.5.4 release; it was too complicated and risky to make it into a bugfix release.  You'll have to wait until v2.6 for this fix to appear.  The failed asset you listed  above works fine for me on the nightly site (off `master`).

**Comment by CurtisConway** [comment]
Wow, I love how fast you guys are to respond. Thank you!

I've gone ahead and followed the two issues you posted above. I'll make sure to contribute where I can. Thanks again, guys!
