### ISSUE TITLE
Error with encrypted live streams

### ISSUE THREAD

**Issue by MegaLabs1** [google/shaka-player#204]
I've got an error playing widevine encrypted streams on HDReady (width="1280" height="720" frameRate="25/1" bandwidth="3456271") and FullHD resolutions. It doesn't play video, just audio.
Same unencrypted stream plays normally.
Widevine encrypted stream lower resolution, (width="864" height="486" frameRate="25/1" bandwidth="1975688") plays ok.

No specific errors in debug found.

**Comment by tdrews** [comment]
Are you using edash-packager?

**Comment by MegaLabs1** [comment]
No, elemental packager

**Comment by tdrews** [comment]
Can you provide a link to the content that does not work? If you do not want to post the link in public you can send a private email (see CONTRIBUTORS).

**Comment by MegaLabs1** [comment]
I can give you a link but it'll be encrypted one, and you'll coudn't decrypt it. Does it make sense?

**Comment by tdrews** [comment]
Yes, perhaps you can check the content first. The browser may fail to decode certain content if the content does not correctly specify its resolution in its sample description table (which resides in the MP4 container). You can check your content with https://github.com/sannies/isoviewer (note: you may need to use v1.0.0 on Linux):
* Open isoviewer and then open the initialization segment of either your 720p or 1080p stream.
* Navigate to `/moov[0]/trak[0]/mdia[0]/minf[0]/stbl[0]/stsd[0]/encv[0]/avcC[0]`
* Scroll down to `SPS[1]` and note the values of each `frame_crop_*_offset` field.
* Navigate to `/moov[0]/trak[0]/mdia[0]/minf[0]/stbl[0]/stsd[0]/encv[0]` and note the values of `width` and `height`.
* The following should hold true:
  * IF 16 divides `width`
    * THEN `frame_crop_left_offset == 0` AND `frame_crop_right_offset == 0`
    * ELSE `frame_crop_left_offset != 0` OR `frame_crop_right_offset != 0`
* And the similar condition that involves `height` should also hold true.

Let me know what you find.

**Comment by MegaLabs1** [comment]
It looks ok, checked for 1920x1080.
![screen shot 2015-10-20 at 14 14 53](https://cloud.githubusercontent.com/assets/2102317/10620810/d6cbbe1a-7785-11e5-9223-87f6a27d4a86.png)

**Comment by tdrews** [comment]
Thanks for checking. It looks like the encoder/packager is computing the correct values.

To try and get an error message you can try the following:
- Start a fresh instance of Chrome and then navigate to chrome://media-internals, you should see nothing listed under Players.
- Open another tab and navigate to the Shaka demo page or to your own application.
- Start playback, you should see one player listed on chrome://media-internals.
- Check the Log section for any errors.

**Comment by MegaLabs1** [comment]
It seems i've found something interesting:

00:00:00 558	__debug	DecryptingAudioDecoder: failed to init decoder on decryptor__
00:00:00 561	audio_dds	true
00:00:00 561	audio_decoder	FFmpegAudioDecoder
00:00:00 561	debug	Video rendering in low delay mode.
00:00:00 570	video_dds	false
00:00:00 570	video_decoder	DecryptingVideoDecoder
00:00:00 570	pipeline_state	kPlaying
00:00:00 570	seek_target	3571154.25
00:00:00 570	pipeline_state	kSeeking
00:00:00 570	pipeline_state	kPlaying
00:00:00 580	debug	DecryptingDemuxerStream: no key
00:00:00 580	debug	DecryptingVideoDecoder: no key
00:00:01 184	event	PLAY
00:00:12 923	info	Video codec: avc1.4d4028
00:00:12 993	event	PAUSE
00:00:13 336	seek_target	3571166
00:00:13 336	pipeline_state	kSeeking
00:00:13 336	pipeline_state	kPlaying
00:00:13 495	__debug	DecryptingVideoDecoder: no key__

**Comment by tdrews** [comment]
Are you using version 5.x or master? It looks like one of the keys is not valid. In version 5.x or master you should see either an error message or something like `Key status: 0123 4567 89ab cdef 0123 4567 89ab cdef: internal-error` if you enable debug logging.

You can set a breakpoint [here](https://github.com/google/shaka-player/blob/3a552b808fa3fb3ed95fd6ddf87c1f96a2e854ed/lib/media/eme_manager.js#L670) to check the key statuses in `session.keyStatuses`. You can also install [EmeLogger](https://chrome.google.com/webstore/detail/eme-call-and-event-logger/cniohcjecdcdhgmlofniddfoeokbpbpb) to ensure `UpdateSession()` is not returning any errors.

**Comment by MegaLabs1** [comment]
1. We use Shaka 1.5.1 
1. Yes, there is a error message about key ![key_error](https://cloud.githubusercontent.com/assets/2102317/10658890/ec146686-78a3-11e5-9837-09782fd2df93.PNG)

2. EME Logger returns 
__CreateSessionCall__
target: MediaKeys
returned: {
    "type": "MediaKeySession"
}
__GenerateRequestCall__
initDataType: cenc
initData: {
    "type": "ArrayBuffer"
}
target: MediaKeySession
returned: {
    "type": "Promise"
}
__GenerateRequestCall Promise Result__
status: resolved
result: null
__	messageEvent__
type: message
time: Thu Oct 22 2015 09:48:43 GMT+0300 (RTZ 2 (зима))
event: MediaKeyMessageEvent
target element: MediaKeySession
__	UpdateCall__
response: {
    "0": 8,
    "1": 2,
    "2": 18,
    "3": 157,
    "4": 3,
     <…>     
    "708": 83,
    "709": 41,
    "710": 104,
    "type": "Uint8Array"
}
target: MediaKeySession
returned: {
    "type": "Promise"
}
__	UpdateCall Promise Result__
status: resolved
result: null
__	keystatuseschangeEvent__
type: keystatuseschange
time: Thu Oct 22 2015 09:48:43 GMT+0300 (RTZ 2 (зима))
event: Event
target element: MediaKeySession

Is there an error with decrypting or in the key request session? It shows ststus resolved, but result is null.

**Comment by MegaLabs1** [comment]
UPD: Issue solved. The problem was in Google policies for HD content. We decreased recommended security level for HD content in widevine proxy settings and... it works!
