### ISSUE TITLE
UI doesn't enter fullscreen on double-click

### ISSUE THREAD

**Issue by TheModMaker** [google/shaka-player#2043]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v2.5.3 and master (v2.5.3-master-38-gfd326951)

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Demo app

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
Chrome for Linux

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**
Any (tested with first Angel One on home screen)

**What did you do?**

1. Start video
1. Double click video

**What did you expect to happen?**
Video to enter fullscreen.

**What actually happened?**
Video paused and unpaused due to click events.  Did not enter fullscreen.  Video enters fullscreen with Chrome native controls.

**Comment by ismena** [comment]
What, again?! I distinctly remember fixing it a few months ago!
Meh. Thanks for reporting.
