### ISSUE TITLE
Null pointer exception when no period is found

### ISSUE THREAD

**Issue by SemihGk** [google/shaka-player#2045]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes, I checked, but if there is anything similar, please close it.

**What version of Shaka Player are you using?**
master and 2.5.4

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `master`?**
yes

**Are you using the demo app or your own custom app?**
custom app

**If custom app, can you reproduce the issue using our demo app?**
no

**What browser and OS are you using?**
chrome and mac

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Tizen 2017, 2018

**What are the manifest and license server URIs?**
If you require, we can send it.

**What did you do?**
When we call [resetConfiguration](https://github.com/google/shaka-player/blob/master/lib/player.js#L2412) during live playback, it causes null pointer exception at [this line](https://github.com/google/shaka-player/blob/master/lib/player.js#L2339). Because period is returned null from [getPresentationPeriod_](https://github.com/google/shaka-player/blob/master/lib/player.js#L4816) even though there are valid periods . The reason for the null period is [presentationTime](https://github.com/google/shaka-player/blob/master/lib/player.js#L4802) is returned 0 at the beginning of the stream. So, it could not set the [lastPeriod](https://github.com/google/shaka-player/blob/master/lib/player.js#L4811). Eventually, the user is not able to change channels.

**What did you expect to happen?**
The user should be able to change channels.

**What actually happened?**
Explained above. To elaborate on the issue a little bit more, the presentationTime is calculated correctly later on, but the beginning on the stream is calculated as 0. This seems like a race condition and it is not easy to reproduce it. I also attached a screenshot although it is caught in minified shaka player. Could you give us some insight about why presentationTime is return 0? Or what else could it be causing this issue?

Thank you.

![image (2)](https://user-images.githubusercontent.com/5814582/61558360-cc0df980-aa34-11e9-8bf4-9898cce010e3.png)

**Comment by joeyparrish** [comment]
Confirmed.  I've just run across the same issue on Chromecast for another partner.  I believe I have a working fix, and it's in review.
