### ISSUE TITLE
Do everything *but* render video/audio?

### ISSUE THREAD

**Issue by BobCu** [google/shaka-player#2046]
I'm looking to load-test a DASH+HLS multi-resolution streaming server (packaged by Shaka) with 1000+ clients.

During early tests (before DRM was implemented) VLC worked fine in headless mode, easily supporting 2K clients on a single load-test server.  But VLC doesn't handle DRM very well, and a better solution is needed.

I need to know that the stream is "good enough" at all times, including during rate adaptation.  The manifests, video/audio segments and keys all need to be fetched and checked (especially for time sync), but can then be discarded if everything looks "OK to render".

Any hiccups found along the way need to be reported.  It would be nice if the player tried to recover with the next segment, but I'm fine if it dies and needs to be restarted.

Is there a straightforward way for Shaka-player to become the testing tool I need?

**Comment by joeyparrish** [comment]
There's no way to stop it from rendering, other than running your browser in headless mode.  But Chrome and Firefox can both do this IIRC.  On Linux, you can use xvfb-run to run a browser in a headless X session, as an alternative.  But the rendering part is done by the browser, not the player, so we aren't in control of that.

Beyond the part where you'd like to skip rendering, Shaka Player should be able to do everything you need.  It's fully controllable with the library API, and no user interaction is required.  (Note that browsers do restrict autoplay, so your video element will need to be muted to get your automation to work.  Our integration tests set `video.muted = true;` for this reason.)

**Comment by BobCu** [comment]
Thanks for the info!

I'm looking into headless Firefox and Chrome (not Chromium), but initial searches suggest playing DRM content can be an issue.  Do you know of any "known good" recipes for this?

**Comment by joeyparrish** [comment]
We use Firefox and Chrome to play DRM content without issues in our tests, and normally with xvfb on Linux.  For example, `./build/test.py --use-xvfb --drm`.  I don't expect different results with true headless mode, but I could be wrong.

In any case, you can start with our existing automated tests if you like, and modify it to use headless mode.

One caveat: Firefox (possibly just on Linux, not sure) will want to download the Widevine CDM the first time it's used, so you'll need to make sure you use an existing profile where this has already been done.  See also the "media.eme.enabled" preference if you're tweaking the profile manually.

**Comment by BobCu** [comment]
Sorry for the delay replying.  Initial tests indicate xvfb still renders, at a cost similar to the full UI.  Not something that will be expandable to 1K clients.  Any solution that supports taking a screenshot is doing rendering.

I'm now planning to go to a hybrid approach, where 1K "dumb" DASH/HLS loaders are run with a few rendering clients active on each feed to ensure quality and equivalence.

**Comment by joeyparrish** [comment]
Okay.  Is there anything we can help with?  Or should we close this issue?

**Comment by BobCu** [comment]
Closed!
