### ISSUE TITLE
Advisory on how to deal with Loading Errors

### ISSUE THREAD

**Issue by boredom2** [google/shaka-player#2047]
Hi there,

we currently experience Cases, where the Player works fine as always, but suddenly, one or two Chunks are not available (for what Reason ever and return 404). I am not sure, how this is handled correctly. Currently, I get an Error Event, which is probably fine. Is there a Way to tell SHAKA to ignore this and "just continue" or at least, try the next 3-5 Chunks and see, if it works then? And will the Error Event reflect this somehow?
I am sorry, if this is documented somehow, but I couldnt find it (is this jumpGaps maybe?).

Thank you,
Christoph

**Comment by joeyparrish** [comment]
If the event's severity is `shaka.util.Error.Severity.RECOVERABLE`, then playback may be able to continue.  To continue playback, you can call `player.retryStreaming()`, either from the configurable `streaming.failureCallback`, which accepts an `Error` object, or from an `error` event handler on the player.  The default behavior for an unconfigured `streaming.failureCallback` is to retry automatically on certain error codes for live streams, but not on VOD.  See `defaultStreamingFailureCallback_` in `lib/player.js`.

Does this help?

**Comment by boredom2** [comment]
After I wrote this Ticket, I also remembered the failureCallback Handler (which we use already in LIVE Cases). So, if this is the suggested best Way to handle "inaccessable Chunks", I will go with that, thanks.
And - excuse me, if I missed something, but what are these smallGaps/largeGaps und Limits for?

**Comment by joeyparrish** [comment]
The idea of gap jumping is not to handle missing segments, but gaps between segments or periods in the presentation timeline.  When a gap is encountered during playback, a "small" gap is automatically jumped.

You can configure the limit of what is considered "small" with `player.configure('streaming.smallGapLimit', ...)`, and you can also override the behavior for "large" gaps.  

To change large gap behavior, you can set `player.configure('streaming.jumpLargeGaps', true)` to jump all gaps by default.  Then you can also listen to `'largegap'` events from the player and call `event.preventDefault()` to stop any particular gap from being jumped.

**Comment by boredom2** [comment]
Okay, thanks for the Clarification.
I will handle it with failureCallback for now.
Thanks!
