### ISSUE TITLE
Can Opus Mime Type be added also?

### ISSUE THREAD

**Issue by boredom2** [google/shaka-player#2048]
Hi there - as there is already mp3, aac, flac etc in the Mime Type Mapping List and we use OPUS a lot, can opus be added to the Mime Type Mapping also?

**Comment by joeyparrish** [comment]
Are you referring to the list in lib/player.js that is used for single-file playback?  Isn't Opus always in a WebM container?  Wouldn't that just be ".webm" mapped to "audio/webm"?

**Comment by boredom2** [comment]
I am referring to this List, yes.
And - I am not sure, WebM can have an OPUS Audio Track, thats true - mostly used is Vorbis, afaik. Both are also common to be put in an ogg Container for Audio-Only Purposes - so summing it up: i am not sure :) 
Our CDN Servers send audio/opus Mime Types, and Browsers like it. I also read that it could be "audio/ogg, codec=opus" - so, I guess, there might be a little Difference somewhere :)

**Comment by joeyparrish** [comment]
The map goes from file extension to MIME type.  If you have a particular file extension to map, that's fine.  But `.ogg` and `.webm` are too general to map to anything with `codec=opus` in the MIME type.

You can also pass the MIME type to your `load()` call, like so:

```js
player.load('/foo/bar.ogg', /* startTime */ 0, 'audio/ogg; codec="opus"');
```

So the mapping is not completely necessary if you know what the MIME type is.

**Comment by boredom2** [comment]
Ok, thanks, I will handle it like that.
