### ISSUE TITLE
Clock syncing with CDN servers make the player go out of sync

### ISSUE THREAD

**Issue by kfwerf** [google/shaka-player#205]
The attempt in the ajax request to sync the player with date headers from the fragment servers causes issues when cdn servers are using the date header to indicate the time of the caching.

https://github.com/google/shaka-player/blob/master/lib/util/ajax_request.js#L457

For us that means that we have to outcomment this line as it makes our video player run out of sync. Is there a way to fix this easily?

**Comment by joeyparrish** [comment]
Hrm... based on my understanding of the Date header, it should always be the time at which the response is sent.  Am I mistaken?  It seems that the CDN is at fault on that.

While we debate the validity of what the CDN is doing, unfortunately, you'll have to comment out the clock sync code to work around it.

**Comment by joeyparrish** [comment]
My colleague has just pointed me to his comment on #191:

```
Date gives the time when the content was created; not when it was transported (see https://tools.ietf.org/html/rfc7231#section-7.1.1.2).
```

So it looks like my Date-based sync may be fundamentally flawed.  We will need to decide internally what to do about it.  Sorry for the inconvenience.

**Comment by joeyparrish** [comment]
The current plan is to abandon Date-based sync in v2.0.  Since some CDNs seem to behave differently on this, and since we don't have an alternative clock sync mechanism ready, we will leave the current behavior for v1.x.  Until v2.0 is ready, you may wish to customize your build of the library and remove Date-based sync.
