### ISSUE TITLE
[Shaka UI] [Android] Full screen closed captions over-sized in profile mode

### ISSUE THREAD

**Issue by fcolley** [google/shaka-player#2051]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
Build: Shaka v2.5.4 (uncompiled)

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Shaka Player Demo

**What browser and OS are you using?**
Environment: Android mobile (Q build QD1A) Chrome browser

**What did you do?**
Steps:
1. Navigate to: https://shaka-player-demo.appspot.com
2. Launch video asset and select (we used Angel One)
3. Select Overflow menu and turn on Closed Captions
4. Select the Fullscreen button while in profile mode

Actual Result: 
The Closed Captions are so large that the text is cut off screen

Expected: 
Closed captions text would not flow off screen while in Fullscreen and profile mode

**Comment by michellezhuogg** [comment]
We'll fix that.
For now, you can customize the font size of shaka-text-container .
