### ISSUE TITLE
Using shaka.ui.TextDisplayer without video or videoContainer

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#2056]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

**What version of Shaka Player are you using?** 2.5.4

**Can you reproduce the issue with our latest release version?** Yes

**Can you reproduce the issue with the latest code from `master`?** Yes

**Are you using the demo app or your own custom app?** Custom app

**If custom app, can you reproduce the issue using our demo app?** 

**What browser and OS are you using?**
Chrome 75 in macOS Mojave

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

Any stream with subtitles

**What did you do?**

Load the video and unload+destroy

**What did you expect to happen?**
No errors in the console

**What actually happened?**

Error shown in the console:

```
shaka-player.ui.js?:formatted:18944 Uncaught (in promise) TypeError: Cannot read property 'appendChild' of null
    at new mq (shaka-player.ui.js?:formatted:18944)
    at new eval (player-control.js:1081)
    at Ha.eval [as b] (shaka-player.ui.js?:formatted:12356)
    at Ma (shaka-player.ui.js?:formatted:498)
    at Na.next (shaka-player.ui.js?:formatted:529)
    at eval (shaka-player.ui.js?:formatted:334)
    at new Promise (<anonymous>)
    at ma (shaka-player.ui.js?:formatted:330)
    at t (shaka-player.ui.js?:formatted:339)
    at fl (shaka-player.ui.js?:formatted:12349)
    at eval (shaka-player.ui.js?:formatted:11972)
    at Object.vf (shaka-player.ui.js?:formatted:12015)
    at Ha.eval [as b] (shaka-player.ui.js?:formatted:11545)
    at Ma (shaka-player.ui.js?:formatted:498)
    at Na.next (shaka-player.ui.js?:formatted:529)
```

![screenshot-error](https://user-images.githubusercontent.com/8983024/61769451-9bd6aa00-adea-11e9-9b69-7273152f85be.png)

**Comment by joeyparrish** [comment]
I noticed you skipped the question "If custom app, can you reproduce the issue using our demo app?"  I tried in our demo, v2.5.4, and I can't reproduce the issue.  Here are my steps:

1. Load the compiled version of the demo app (since I see compiled code referenced above).
2. Click "Play" under "Angel One".
3. Use the controls UI to turn on subtitles.
4. Open the JS debugger and run:

```js
player = shakaDemoMain.controls_.getPlayer();
// I assume this is what you mean by "unload+destroy"?
player.unload();  player.destroy();
```

Can you be more specific about how you're reproducing this error?  What particular methods are you calling on the player object?

**Comment by avelad** [comment]
I'm using the Shaka Player UI but only the Text displayer. The rest is custom (my app is written in angularjs) and the problem is reproduced the destroy the component.

```
const videoContainer_ = document.getElementById('videoplayer');
const video_ = document.getElementById('video');
const player_ = new shaka.Player(video_);
player_.configure(
  'textDisplayFactory',
  () => {
    return new shaka.ui.TextDisplayer(video_, videoContainer_);
  }
);
```

I found that the TextDisplayer it not checking that video and videoContainer exists in the constructor. With the next lines the issue it's not longer reproduced:
![fix](https://user-images.githubusercontent.com/8983024/61854719-f80afe00-aebe-11e9-8cd9-66f1701b8b89.png)

**Comment by joeyparrish** [comment]
> I found that the TextDisplayer it not checking that video and videoContainer exists in the constructor.

These are required arguments, so I think you are using `shaka.ui.TextDisplayer` wrong.  If there's no video element, for example, we can't time the display of captions to the video.  And if there's no video container, we have nowhere to place the DOM elements that display the captions.

**Comment by avelad** [comment]
I'll try to find another solution. Thanks
