### ISSUE TITLE
Get PlayReady PSSH from <ms:pro> in DASH

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#2058]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.4

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Both

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Edge 18 Windows 10

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

I'll send a email with the url and the license server

**What did you do?**

Tried to played the dash content with playready encryption but it fails.

**What did you expect to happen?**
Playback to be normal

**What actually happened?**

I receive this message when trying to play the content .

Shaka Error DRM.FAILED_TO_GENERATE_LICENSE_REQUEST (SystemCode:0x80041301,TypeError: SystemCode:0x80041301,)

I reviewed the issue https://github.com/google/shaka-player/issues/1837 but the pssh in the init segment is valid:
![pssh](https://user-images.githubusercontent.com/8983024/61856042-9b5d1280-aec1-11e9-9514-8eff3d471b88.png)

**Comment by chrisfillmore** [comment]
Is this the same as #1837 ? SystemCode is the same.

**Comment by TheModMaker** [comment]
I agree the init data looks valid.  After some testing, I see the init data we get has duplicate elements, but removing those doesn't seem to fix it.  If I reorder the `pssh` elements so that PlayReady is first, the `generateRequest` call succeeds, but the license server rejects it with a `Service Specific Error`.  It also works if I remove the other key systems' init data and only pass PlayReady, but I again get the same license server error.

**Comment by avelad** [comment]
I checked the stream in DashIF Player and works without problem...

**Comment by TheModMaker** [comment]
When I try in the DashIF Player, I get a 500 error from the license server, the same as Shaka Player.

One thing I notice that may help is DashIF generates a `pssh` box based on the `<mspr:pro>` record in the manifest.  This avoids the problems from the `pssh` boxes in the media.  We may want to consider adding this to our DASH parser to (a) avoid this error, and (b) request the license earlier.

**Comment by joeyparrish** [comment]
We have support for `<mspr:pro>` to get the license server URI (`getPlayReadyLicenseUrl` in `lib/dash/content_protection.js`).  So we could probably add support for to override the `pssh` box based on that in the DASH parser, too.

**Comment by avelad** [comment]
@TheModMaker , I want contribute to add the support, if you can guide me, i can made the changes this week.

I check the file `ib/dash/content_protection.js` and i thing that the modications should be done in parseElement_.

Parse `<mspr:pro>` it's easy with `const proNode = shaka.util.XmlUtils.findChildrenNS(elem, 'urn:microsoft:playready', 'pro') .map(shaka.util.XmlUtils.getContents);` But if I include the field as it is by overwriting the value of psshs, this does not work.

Note: Error 500 is because the license is not valid, but it is a good development.
Sorry for the delay in answering, but I was on vacation.

**Comment by TheModMaker** [comment]
I think it would be better to do it in [convertElements_](https://github.com/google/shaka-player/blob/1ea3ca49dcb17d620395327314ac327a883c206b/lib/dash/content_protection.js#L348).  The `<mspr:pro>` element would be a fallback if there is no other init data available.

That contains a PRO object and you need to convert it to a `pssh` box.  Just put the PRO data into the data section of the `pssh` box (use this [system_id](https://github.com/google/shaka-player/blob/1ea3ca49dcb17d620395327314ac327a883c206b/lib/dash/content_protection.js#L542)):

```
[4 bytes] total size
[4 bytes] 'pssh'
[4 bytes] flags (0)
[16 bytes] system_id
[4 bytes] data_size
[data_size bytes] data
```
