### ISSUE TITLE
Load is interrupted when subtitle fails to load

### ISSUE THREAD

**Issue by thecuriousdev** [google/shaka-player#2065]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
YES

**What version of Shaka Player are you using?**
2.5.4

**Can you reproduce the issue with our latest release version?**
YES

**Can you reproduce the issue with the latest code from `master`?**
YES

**Are you using the demo app or your own custom app?**
demo app

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
chrome 78, MacOS 

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

https://shaka-player-demo.appspot.com/demo/#audiolang=en-GB;textlang=en-GB;uilang=en-GB;asset=https://storage.googleapis.com/shaka-demo-assets/angel-one-hls/hls.m3u8;panel=SEARCH;build=uncompiled

**What did you do?**

Block the VTT URL from dev tools

**What did you expect to happen?**
Ideally, the playback should happen without the subtitle, no need to interrupt the playback altogether.

**What actually happened?**
The playback is failing with code 1002

**Comment by joeyparrish** [comment]
By default, any streaming failure will cause playback to fail.  But for text, try this before you call load:

```js
player.configure('streaming.ignoreTextStreamFailures', true);
```

In the demo app, this can be set by clicking the menu button in the top left, then expanding the "streaming" section of the config, then clicking the toggle labeled "ignore text stream failures".

Does this help?

**Comment by thecuriousdev** [comment]
Thanks @joeyparrish, that's helpful.

**Comment by thecuriousdev** [comment]
Hey, I tried doing the same

**Comment by TheModMaker** [comment]
It looks like that configuration value is only used in StreamingEngine, but this error comes from the HLS parser when it tries to parse the start time.  We should respect this configuration value in the HLS parser too.  (this is also related to #1563 where we won't request text segments anymore)
