### ISSUE TITLE
Redundant calls being made to HLS child manifest

### ISSUE THREAD

**Issue by thecuriousdev** [google/shaka-player#2066]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
YES

**What version of Shaka Player are you using?**
2.5.4

**Can you reproduce the issue with our latest release version?**
YES

**Can you reproduce the issue with the latest code from `master`?**
YES

**Are you using the demo app or your own custom app?**
Demo App

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
Chrome 78, MacOS

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**
https://shaka-player-demo.appspot.com/demo/#audiolang=en-GB;textlang=en-GB;uilang=en-GB;asset=https://storage.googleapis.com/shaka-demo-assets/angel-one-hls/hls.m3u8;panel=SEARCH;build=uncompiled

**What did you do?**

Redundant calls being made to child manifest

**What did you expect to happen?**
We only need to fetch a specific manifest only once instead, we can observe multiple calls. And increasing the video's start lag.

**What actually happened?**
Check the network tab, and search for `playlist_a-eng-0128k-aac-2c.mp4.m3u8` you can see that a total of 5 calls being made to the same child manifest.

**Comment by joeyparrish** [comment]
You are correct, we shouldn't have to fetch the audio playlist 5 times during startup.  Thanks for the report!

**Comment by thecuriousdev** [comment]
Thanks for the response, also what is the ETA for v2.6?

**Comment by joeyparrish** [comment]
v2.6 is blocked on #1339 and a number of bugs.  This is marked "bug", so we will try to cherry-pick the fix to v2.5.x.  You won't have to wait for v2.6 to get this fixed.

**Comment by michellezhuogg** [comment]
This should be fixed with Hls refactor soon.
