### ISSUE TITLE
High framerate restrictions for Tizen 5 (2019)

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#2068]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes

**What version of Shaka Player are you using?** 2.5.4

**Can you reproduce the issue with our latest release version?** Yes

**Can you reproduce the issue with the latest code from `master`?** Yes

**Are you using the demo app or your own custom app?** Both

**If custom app, can you reproduce the issue using our demo app?** Yes

**What browser and OS are you using?** Tizen 5

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Samsung QE49Q60RATXXC with the firmware 1303.7

**What are the manifest and license server URIs?**

https://storage.googleapis.com/shaka-demo-assets/sintel-mp4-only/dash.mpd

**What did you do?**

Load the previous stream

**What did you expect to happen?**
Stream play correctly.

**What actually happened?**

Stream is playing but the currenttime is always the same and there a no video (black) and no audio.

**Comment by avelad** [comment]
I think that the issue is related to the framerate of the video. Samsung has the next limitation on 4K
https://developer.samsung.com/tv/develop/guides/multimedia/4k-uhd-video

Is it possible add the limitations to configuration?
Now there are limitation for bandwidth, widht, height, but not framerate.

**Comment by joeyparrish** [comment]
Yes, I think it would be reasonable to add framerate to the Restrictions object in the configuration.  Would you be willing to send a PR?

Note that there are two instances of that type in the config: one for ABR (restricts ABR choices, but other tracks can still be selected explicitly), and one at the top level which restricts all playback.  Both use the same type definition, so your new field would affect both.  But for your situation, you'd use the top-level one to restrict playback of high framerate video.

**Comment by ismena** [comment]
I don't see why not. Let me schedule that as an enhancement!

**Comment by joeyparrish** [comment]
These changes have been cherry-picked for v2.5.8.
