### ISSUE TITLE
Multiple video tracks in PiP view

### ISSUE THREAD

**Issue by dbukhan** [google/shaka-player#2069]
If a video has two video tracks would it be possible to use two MediaElements to render the two tracks simultaneously? An exact video syncing is not required, a drift of a second or two is acceptable. One use case is streaming videoconferencing media that has more than often contains multiple video tracks (video+content).

**Comment by ismena** [comment]
Hi @dbukhan 
The mention of PiP confused me. Do you mean, play one track in the main media element and another - in the small PiP window? Or something else?

Not considering PIP, the best I can think of is creating two player instances each with it's own media element and staring simultaneous streams with desired tracks.
@joeyparrish do you have other ideas?

**Comment by joeyparrish** [comment]
I would suggest loading the same manifest in two `Player` instances in two `<video>` elements, then select different video tracks.  It's not terribly efficient, but what you're trying to do (video conferencing) isn't really what Shaka Player was designed for.  You may be able to make it work anyway.

For sync, you could probably use a timer that checks to see how far out of sync the two videos are, then vary playbackRate to get them gently back in sync.  For example (untested):

```js
onTimer() {
  const behindVideo = video1.currentTime < video2.currentTime ? video1 : video2;
  const aheadVideo = behindVideo == video1 ? video2 : video1;
  const delta = aheadVideo.currentTime - behindVideo.currentTime;
  if (delta > 2) {
    behindVideo.playbackRate = 1.1;
    aheadVideo.playbackRate = 1;
  } else if (delta > 0.5) {
    behindVideo.playbackRate = 1.05;
    aheadVideo.playbackRate = 1;
  } else {
    behindVideo.playbackRate = 1;
    aheadVideo.playbackRate = 1;
  }
}
```

**Comment by dbukhan** [comment]
Yes
