### ISSUE TITLE
Different language preferences 

### ISSUE THREAD

**Issue by sanbornhnewyyz** [google/shaka-player#207]
It would be quite reasonable to have one language preference for audio and a different language preference for CC/Subtitles. However there is only a single global preferredLanguage configuration option. I'd like to request the option to set audio and text language preferences separately through the player.configure() method.

**Comment by joeyparrish** [comment]
That doesn't sound too difficult.

Can you help me understand the use case?  As a user watching content in various languages, why would I prefer audio in one language and text in another?

Also, this raises several behavior questions for me.  If my preferred audio isn't available, would I choose the 'main' language or an audio track that matches my text language?  If my preferred audio is available, and my preferred text is too, would I automatically enable text?  etc.

**Comment by sanbornhnewyyz** [comment]
One example that immediately comes to mind is that its quite common for someone who is learning or not as proficient in a second language to want the audio in the language they are learning and the text in their native language. This way they can try to listen for the audio but still catch what's going on when they do not fully understand the audio.

As for those two behaviour questions, I'm not sure and it's probably worth a discussion. I'm not sure about the first. For the second I don't think there is a need to change the current behaviour. If the user wants to toggle on text tracks then they can do that.

**Comment by joeyparrish** [comment]
Ah, I see.  Okay, let me spend a little time deciding how to define the behavior, and I'll post details here before we implement.

**Comment by joeyparrish** [comment]
The new language preferences for audio and text will be used independently to select audio and text streams.

If the user's preferred audio isn't available, the will hear whatever is tagged as the 'main' language.  Text will be automatically shown if the preferred text language is available and it does not match the preferred audio language.

For applications that want the old behavior, both language settings can be set to the same value.

This will be available in the v2 beta.
