### ISSUE TITLE
Seeking back after enabling captions does no longer loads captions

### ISSUE THREAD

**Issue by physicsforpoets** [google/shaka-player#2070]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.2 (could also repro with 2.4.7)

**Can you reproduce the issue with our latest release version?**
2.5.3 and 2.5.4 are throwing unreadable manifest errors that are not getting thrown with the debug player.

**Can you reproduce the issue with the latest code from `master`?**
See above.

**Are you using the demo app or your own custom app?**
Custom app.

**If custom app, can you reproduce the issue using our demo app?**
No.

**What browser and OS are you using?**
Chrome, macOS

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

I don't believe our manifests are accessible publicly - I can mail them to you or potentially get one opened up if my description does not suffice.

**What did you do?**

1. Started playback on a title with captions disabled - configure() was called with isTextVisible set to false
2. Enabled captions - called player.setTextTrackVisibility(true)
3. Seeked to a time before captions were enabled

**What did you expect to happen?**
Captions to display as normal

**What actually happened?**
No new ismt files were loaded, no active cues were triggered

Using shaka player 2.5.2 - DASH manifest, widevine & playready DRM with external ISMT captions files

Starting playback with captions disabled and then enabling captions and seeking back in the title does not appear to load the proper caption segments and no captions are displayed until you seek past the initial playback point. Starting playback with captions enabled does not seem to cause this issue, neither does starting playback with captions disabled and then seeking forward. When seeking back, I'm not seeing the ismt files getting loaded, which means I'm not seeing any active cues.

My very uninformed guess was that when captions are enabled, the player loads all captions from that point forward, but if playback is started from further into the title with captions enabled, seeking back does not appear to cause the same issue.

We use the textDisplayFactory's append method to pass the cues to the video's textTracks, and then watch for those in our UI layer and display captions ourselves. 

The only difference I can see between starting with captions enabled and captions disabled, is that player.configure(settings) is getting called with isTextVisible returning true, otherwise false. Starting with captions disabled will configure player with isTextVisible returning false, and enabling them later will call player.setTextTrackVisibility(true);

**Comment by michellezhuogg** [comment]
Hello @physicsforpoets ,
Are you using SimpleTextDisplayer or shaka.ui.TextDisplayer?
Since this can only be reproduced in your custom app, can you share any app-level code with us? That would be helpful. Thanks!

**Comment by physicsforpoets** [comment]
Hi @michellezhuogg -
I'm using textDisplayFactory in the player.config() - not sure which of those text displayers that utilizes -

`playerConfiguration.textDisplayFactory = function() {
                        return {
                            append: function(cues) {
                                cues.forEach(function(cue) {
                                    var textCue = new VTTCue(cue.startTime, cue.endTime, cue.payload);
                                    video.textTracks[0].addCue(textCue);
                                });
                            },
                            destroy: function() {},
                            isTextVisible: function() {
                                var captionsVisible = ccEnabled; // true || false
                                return captionsVisible;
                            },
                            remove: function(start, end) {
                            },
                            setTextVisibility: function() {
                                return;
                            }
                        }
                    };`

After seeking back, as mentioned, no additional ismt files are loaded via network requests, and the "append" method here is not getting called, until seeking back past the point where captions were enabled

**Comment by physicsforpoets** [comment]
This may be an issue with our specific implementation - if I always set "isTextVisible" to return true, since we're showing and hiding on our own, everything seems to work as intended. However it still seems odd that calling setTextVisiblity AFTER playback begins and then seeking back in time doesn't load the previous caption segments.

**Comment by TheModMaker** [comment]
We only stream text when it is being displayed.  So if the text isn't visible, we won't download it.  We also assume that all text display changes happen through the top-level API; so changing the return value of `isTextVisible` from under us might break things.  Make sure to change the value of your `ccEnabled` variable inside the `setTextVisibility` function.  Or you can try setting the `streaming.alwaysStreamText` configuration value to `true`; this will make us always download the text cues even if we think they aren't being displayed.

**Comment by physicsforpoets** [comment]
@TheModMaker I think the 'alwaysStreamText' config is what I was looking for - is there any decent documentation for overriding textDisplayFactory? Or using 'alwaysStreamText' or 'ccEnabled'?

**Comment by TheModMaker** [comment]
`alwaysStreamText` is found in the [streaming configuration object](https://shaka-player-demo.appspot.com/docs/api/shaka.extern.html#.StreamingConfiguration).  The `textDisplayFactory` field is documented in the [player configuration object](https://shaka-player-demo.appspot.com/docs/api/shaka.extern.html#.PlayerConfiguration) and the function needs to return something that implement the [shaka.extern.TextDisplayer](https://shaka-player-demo.appspot.com/docs/api/shaka.extern.TextDisplayer.html) interface.  You can get to this from the [player.configure](https://shaka-player-demo.appspot.com/docs/api/shaka.Player.html#configure) call documentation.  `ccEnabled` is just a variable you put in your code example.
