### ISSUE TITLE
Customization of mime type value?

### ISSUE THREAD

**Issue by jkringen** [google/shaka-player#2072]
I am curious if there is any possible way with the current Shaka player to allow for a customization of the mimeType that is provided to the video playback source?

We are integrating on a custom LG commercial platform, and one of the options they expose can only be configured as their docs show here:

`var options = {};`
`options.mediaTransportType = "WIDEVINE";`
`options.option = {};`
`options.option.someVariousOption = "VALUE";`
`var mediaOption = encodeURIComponent(JSON.stringify(options));`
`var source = document.createElement("source");`
`var dataURL = "http://example.com/test.mp4";`
`source.setAttribute('src', dataURL);`
`source.setAttribute('type', 'video/mp4;mediaOption=' + mediaOption);`
`video = document.getElementById('myVideo');`
`video.appendChild(source);`

Their example shows modifying the **type** attribute of the video element source node directly. I have no idea how we would supply that when using the shaka player, as I am not in control of how/if Source nodes are even created, and how the mimeType value is provided, etc.

Any thoughts?

**Comment by joeyparrish** [comment]
Is this for single mp4 files as in your example?  Or would you also need to add this information to the MIME types of content in DASH or HLS manifests?

**Comment by jkringen** [comment]
ah yes, sorry about that, that's an important detail! We are streaming MPEG-DASH content for this scenario.

**Comment by joeyparrish** [comment]
If you query the platform with something like this, what does it return?

```js
MediaSource.isTypeSupported('video/mp4; codecs="avc1.42E01E"; mediaOption=' + mediaOption);
```

**Comment by jkringen** [comment]
Just ran a test for that and it did return true

**Comment by joeyparrish** [comment]
Good.  That's what Shaka Player uses to filter out parts of the manifest and decide what's playable.

-----

Here's one option for you:

1. Listen for the player's [`manifestparsed`](https://shaka-player-demo.appspot.com/docs/api/shaka.Player.html#.event:ManifestParsedEvent) event
2. When the event fires, use the player's [`getManifest`](https://shaka-player-demo.appspot.com/docs/api/shaka.Player.html#getManifest) method to get a copy of the manifest structure
3. Iterate through that and append the necessary "; mediaOption=" string to the end of each

**NB**: This is not a stable structure across minor versions, so v2.5.x and v2.6.x and so on may have different internal manifest structures.  You'll need to upgrade your MIME-type-modifying code when you upgrade Shaka Player.

-----

Here's another option:

Write a polyfill that patches `MediaSource.isTypeSupported` and `MediaSource.prototype.addSourceBuffer` to add the necessary info there.  Install that polyfill on the LG devices that need this info.  Something like:

```js
const originalIsTypeSupported = MediaSource.isTypeSupported;
MediaSource.isTypeSupported = (mimeType) => {
  return originalIsTypeSupported(mimeType + 'mediaOption=' + mediaOption);
};

const originalAddSourceBuffer = MediaSource.prototype.addSourceBuffer;
MediaSource.prototype.addSourceBuffer = function(mimeType) {
  return originalAddSourceBuffer.call(this, mimeType + 'mediaOption=' + mediaOption);
};
```

**NB**: Be careful that you don't install that polyfill more than once!

**Comment by jkringen** [comment]
Awesome, thank you so much for the quick replies and suggestions! I'll give these a try and reply/close this issue once I resolve.

**Comment by joeyparrish** [comment]
Happy to help!
