### ISSUE TITLE
Question: How does the demo app decide content is live?

### ISSUE THREAD

**Issue by gscragg** [google/shaka-player#2074]
I am attempting to test HLS Live playback in shaka player, and I cant get the time display or seek bar to show a Live Content state.

[Example.](https://bl.ocks.org/gscragg/ab48d5b493e84a582b6eabf556837d23)

Note* that is referencing controls.css, muxjs, and skaka-player.ui.js from the demo site.

Viewing the same content on the demo site does show a Live state as I would expect.

[Demo site.](https://shaka-player-demo.appspot.com/demo/#audiolang=en-NZ;textlang=en-NZ;uilang=en-NZ;asset=https://akamai-axtest.akamaized.net/routes/lapd-v1-acceptance/www_c4/Manifest.m3u8;panel=SEARCH;build=compiled)

I have compared the player and ui configurations, and other than a close button and a dash.clockSyncUrl in the demo site, I can't see any differences.

**Comment by joeyparrish** [comment]
In your example, you constructed a new player:

```html
  <div id="player-container" data-shaka-player-container>
    <video data-shaka-player></video>
  </div>
```
```js

    window.addEventListener('load', function(){
      shaka.polyfill.installAll();

      var p = document.querySelector('video');
      var player = new shaka.Player(p);

      player.configure({
        "preferredAudioLanguage": "en-NZ",
        "preferredTextLanguage": "en-NZ",
      });

      player.load('https://akamai-axtest.akamaized.net/routes/lapd-v1-acceptance/www_c4/Manifest.m3u8');
    });
```

But the UI library had already created a Player instance and attached it to the video.  You essentially forced it to detach and hijacked the video element with a player that's not connected to the UI controls.

Instead, you should use the player instance constructed by the UI library:

```js
  document.addEventListener('shaka-ui-loaded', function() {
    controls = document.querySelector('video').ui.getControls();
    player = controls.getPlayer();
    player.load('https://akamai-axtest.akamaized.net/routes/lapd-v1-acceptance/www_c4/Manifest.m3u8');
  });
```

**Comment by gscragg** [comment]
That worked a treat, thank you @joeyparrish

**Comment by joeyparrish** [comment]
My pleasure.  Glad we could help!
