### ISSUE TITLE
Duplicate CEA-608 caption lines

### ISSUE THREAD

**Issue by sath33sh** [google/shaka-player#2076]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v2.5.4

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Custom app

**If custom app, can you reproduce the issue using our demo app?**
Did not try the demo app

**What browser and OS are you using?**
Chrome 75.0.3770.142 on Mac OS 10.14.5

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**

https://www.philo.com/manifest-dai-test/vod/8ee733eef854021a0189826a8dfe1a2c2358bf74/manifest.mpd?content_host=prod.cdn-vdms.philo.com

**What did you do?**

Play a VOD asset with multiple periods and seek between periods

**What did you expect to happen?**
CEA-608 captions are displayed correctly

**What actually happened?**

Sometimes captions are duplicated on the screen. It seems to happen when playhead is closer to period boundaries. I used ffmpeg to confirm that the video segments do not contain duplicate captions. I Also played the same stream using a different DASH player (ExoPlayer) and it does not exhibit this issue which makes me think it's a bug in Shaka.

![image](https://user-images.githubusercontent.com/2730026/62330422-82c69c80-b46d-11e9-8171-5afede488320.png)

**Comment by joeyparrish** [comment]
I've seen this before in segmented text content from Shaka Packager, and I've been advised by @kqyang that it is our fault, and not the fault of the Packager.

**Comment by TheModMaker** [comment]
The asset you listed is encrypted and you didn't provide a license server.  Could you please provide the license server URL or a clear asset that reproduces the issue?  Thanks.

**Comment by tylerdaines** [comment]
I just emailed a URL for a stream that exhibits similar behavior.

**Comment by sath33sh** [comment]
Is there going to be a minor release v2.5.6 with this fix? What's the timeline for the next release, whether it is v2.5.6 or v2.6?

**Comment by joeyparrish** [comment]
This fix appears to be elligible for cherry-pick to v2.5.x.  We'll try to get a new release out (v2.5.6) next week.
