### ISSUE TITLE
Export object with pointers to all instantiated players

### ISSUE THREAD

**Issue by shaharmor** [google/shaka-player#208]
Hi,

We need a way to track which players have been added to a page without knowing the ID of the DOM element that was used.

Is it possible to expose an object that will have pointers to all Player instances or a global Shaka event that will be fired whenever a new one is created?

Thanks

**Comment by joeyparrish** [comment]
If the application creates multiple Player instance, I see no reason the application couldn't just track them.  The application is already responsible for managing a Player's lifetime and calling unload() or destroy() on it, so even a one-Player app should maintain a reference to the Player.  A multi-Player application should do the same, in my opinion.

If you disagree with this, please feel free to reopen and we can discuss further.

**Comment by shaharmor** [comment]
I agree with your answer, but my situation is a little bit different.

I am not the owner of the application, but instead i am writing a plugin for shakaplayer, and in order for it to work seamlessly i need to bind to some events of the player.

Asking the application to do that by it self is indeed possible, but will cause the implementation of the plugin to be more complicated.

If i will have a single place where i can either find all instantiated players, or bind to a global event that will let me know when one is being instantiated, the plugin implementation will be just to include the script instead of having to add additional code.

Hope it makes sense.

**Comment by joeyparrish** [comment]
Sorry, that's not supported today.  Can you not ask the owner of the application to simply supply a Player instance to the plugin?  Or shim shaka.player.Player?  For example:

(function() {
  console.assert(shaka.player.Player, 'load Shaka first!');
  var originalPlayer = shaka.player.Player;
  shaka.player.Player = function(video) {
    var player = new originalPlayer(video);
    // do something with player.
    return player;
  }
})();
