### ISSUE TITLE
Add dynamically rel=preconnect for the current video

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#2081]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes

**Describe the solution you'd like**

Add dynamically rel=preconnect for the current video
Ej:

- before load video:
No rel=preconnect

- Load the video https://example.com/index.mpd

- After load the video 
`<link rel="preconnect" href="https://example.com">`

- Unload the video 
No rel=preconnect

Info about rel=preconnect and examples in:
https://web.dev/preconnect-and-dns-prefetch/

I think that the feature can improve the performance when the player is downloading segments.

What do you think?

**Comment by TheModMaker** [comment]
That's an interesting feature.  We could add it, but there are some problems.  First, there is a limit on the number of preconnects that are allowed.  So if there are multiple Player instances, we could run out of these connections; also, if the app uses them too, we can run out.  Secondly, segments can come from different servers and with DASH there can be multiple fallback servers.  We should probably only add one preconnect tag so we would either need to pick one or not add a preconnect if there are multiple servers.

We'll look into this in the future when we have time.

**Comment by joeyparrish** [comment]
I think the solution described wouldn't add any value.  If you wait to add `<link rel=preconnect...>` until the video is loaded, you aren't **pre**-connecting.  The video playback would already establish the connection.

@avelad, I would like to close this with the "will not implement" label, but I'll wait for you to confirm.  We can, of course, continue to discuss it if I've missed something.

**Comment by avelad** [comment]
After having been testing, the behavior I need is only necessary in older versions of Chromium used on SmartTV. In Chrome 63+ it is not necessary because the browser implements it correctly and does not re-establish the connection when changing connectivity type (Wifi to Ethernet or vice versa).

I think the behavior I need can be implemented using filters, so I agree to close this enhancement.

Thank you so much for everything.
