### ISSUE TITLE
Q: HLS Live Stream - Why we are fetching the 1st segment to determine the startTime

### ISSUE THREAD

**Issue by thecuriousdev** [google/shaka-player#2083]
Referring to https://github.com/google/shaka-player/issues/740

Noticed that we are fetching the first segment to get the start time. This is introducing a significant start lag. Can you help me understand why we are doing this and is there a way to avoid this?

**Comment by TheModMaker** [comment]
See #1558.  We need to determine when the first segment starts at to determine the timeline.  We need to know when to start playing at and there is little to no signaling in the manifest for when the segments appear at.  We need to know that segment 1 goes from A-B and 2 goes from B-C so we can handle seeking and determine what time to start playing at.

**Comment by thecuriousdev** [comment]
Thanks for the response @TheModMaker

But this is where I am confused. We cannot determine the timeline based`#EXT-X-TARGETDURATION` and `#EXTINF`? One thing is that unlike the timing in the segment file, we won't have the absolute values. Is that the reason? or there is something else?

**Comment by TheModMaker** [comment]
Those attributes only give the duration, not the start time.  We nee to know the absolute times of the segments.  When we append the segment to the browser, the browser places that media in its absolute time.  So we need to seek to an absolute time to view that segment's data.

**Comment by thecuriousdev** [comment]
Got it thanks @TheModMaker!
