### ISSUE TITLE
Buffering spinner misaligned on IE

### ISSUE THREAD

**Issue by TheModMaker** [google/shaka-player#2084]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v2.5.4

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Demo app

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
IE11

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**
Any asset.

**What did you do?**
1. Force buffering state:
```js
shakaDemoMain.controls_.getLocalPlayer().isBuffering = function() { return true; }
shakaDemoMain.player_.dispatchEvent(
    new shaka.util.FakeEvent('buffering', {buffering: true}));
```

**What did you expect to happen?**
Buffering spinner should appear over play/pause button.

**What actually happened?**
Spinner was on the right side of the page.

**Comment by joeyparrish** [comment]
We've broken and fixed this so many times, it's crazy.  Is it definitely still broken on both the latest release and nightly?  Can you double-check on older v2.5.x releases to see if we had it right at any point in this branch?

**Comment by TheModMaker** [comment]
It was working in v2.5.0 and v2.5.1, but broken in v2.5.2-v2.5.4 and on the nightly.

**Comment by joeyparrish** [comment]
I haven't looked at the commit log yet, but... I'll bet you a tasty drink of your choice we'll find out I'm the one who broke it.  :-)
