### ISSUE TITLE
Live HLS - Incorrect Seekrange

### ISSUE THREAD

**Issue by thecuriousdev** [google/shaka-player#2086]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.4

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Demo app

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Chrome 78, MacOS

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

https://shaka-player-demo.appspot.com/demo/#audiolang=en-GB;textlang=en-GB;uilang=en-GB;asset=https://storage.googleapis.com/shaka-live-assets/player-source.m3u8;panel=SEARCH;build=uncompiled

**What did you do?**

Verify the seekRange, the seek's start & end time is same (eg `{start: 461692.08633327484, end: 461692.08633327484}`) even though the manifest says otherwise.

**What did you expect to happen?**
seekRange should be correct (first available segment's startTime to last one's endTime)

**What actually happened?**
Incorrect seekRange

**Comment by TheModMaker** [comment]
By default, we follow the same behavior of the native Safari player when playing HLS.  This means that live HLS is unseekable by default.  If you want HLS to be seekable, you can change this with the `manifest.availabilityWindowOverride` configuration (which will be the new seek window duration).

```js
player.configure('manifest.availabilityWindowOverride', 300);
```

**Comment by thecuriousdev** [comment]
Thanks, @TheModMaker. that helps.
