### ISSUE TITLE
Does timestampOffset apply the logic of DASH 7.2.1 Media Presentation timeline?

### ISSUE THREAD

**Issue by chrisfillmore** [google/shaka-player#2087]
We're running into some issues with negative DTS on Tizen. Samsung has confirmed to us that the devices use an older version of Chromium that doesn't have negative DTS support. Some of our content has large values for `presentationTimeOffset`, and thus `timestampOffset` gets passed a large negative number.

I want to be sure I understand the behaviour correctly. `timestampOffset` is calculated here, as `Period@start - presentationTimeOffset`:
https://github.com/google/shaka-player/blob/1d417ff5ed658a6cf5c54f08991c37e21c181eb7/lib/media/streaming_engine.js#L1750-L1751

The DASH spec says:
> **7.2.1 Media Presentation Timeline**
> ... The presentation times within each Period are relative to the PeriodStart time of the Period minus the value of the @presentationTimeOffset, TO, of the containing Representation. This means for an access unit with a presentation time TP signalled in the media stream, the Media Presentation time relative to the PeriodStart is TM=TP - TO.

So, is `timestampOffset` an application of this rule from DASH 7.2.1? The [MSE spec](https://www.w3.org/TR/media-source/#dom-sourcebuffer-timestampoffset) is generic and says `timestampOffset` is a value applied to timestamps in media segments. It doesn't know anything about DASH of course.

Thank you for the confirmation, and any insight.

**Comment by TheModMaker** [comment]
You are correct.  The `timestampOffset` specifies how to adjust the media times after they are appended.  So if the `timestampOffset` is 10 and the segment's media start time is 20, then the segment will appear at 30 within the video element's timeline.  The PTO is used to adjust a segment time backwards towards 0, so it is negative; and we add the Period start so the times in the video element are absolute.

Usually that error happens when the DTS is before PTS (as it should be for some content).  So when we adjust PTS to appear at 0, then DTS is now negative and the browser chokes.  One option would be to reduce the `presentationTimeOffset` to adjust DTS to 0 instead; this will introduce a gap before the start, but we jump small gaps automatically anyway.

**Comment by chrisfillmore** [comment]
Thank you for the explanation. I have checked in with our content team about reducing PTO to avoid these negative values.

I am trouble figuring out how/where PTS is specified. The ISOBMFF spec (14496-12) in **8.6 Track Time Structures** describes decoding times (DT) and composition times (CT), not presentation times. Is presentation time just inferred from these two values? That is, when we talk about PTS, we are talking about the `ctts` values added to the `stts` values?

**Comment by TheModMaker** [comment]
I believe so, I think the PTS is the composition time of the frame.

**Comment by joeyparrish** [comment]
Would it be useful to have a configuration field with a number to add to all timestamps to avoid negative values on older browsers?

**Comment by chrisfillmore** [comment]
@TheModMaker thanks. I realize this is rather outside the scope of Shaka so I appreciate you taking the time to reply.

@joeyparrish I'm not sure what the impact of such a configuration would be. At any rate, I can't feasibly predict what the DTS of any given content will be ahead of time. It seems I would need to inspect segments + manifest to do so. Probably better to just change the content. What do you think?

**Comment by joeyparrish** [comment]
You can definitely change the content, and I think that could even be the most expedient solution for you right now.  I was thinking that a configuration for the player would allow you to ask that a certain offset be added to the timestamps through MediaSource.  Currently, SourceBuffer's timestampOffset is `period.start - presentationTimeOffset`, but we the config would make it `period.start - presentationTimeOffset + configOffset`.  If you're getting negative DTS in the range of 0.1s, you would add 0.15s through the config.

**Comment by chrisfillmore** [comment]
Ok I'll keep that in mind. I'd need to do some more testing to see what the DTS values actually are.

For now I'll close. If such a config could prove useful then I'll reopen. Thanks again!
