### ISSUE TITLE
Served demo page will not work with http

### ISSUE THREAD

**Issue by justinruggles** [google/shaka-player#209]
The docs give the demo page link as http://shaka-player-demo.appspot.com/ but it actually only serves over https. This changed at some point in the last month or two. I previously was able to test a localhost playlist and media server over http, but it no longer works. The console log shows:
```
Mixed Content: The page at 'https://shaka-player-demo.appspot.com/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://localhost:8090/134173961/video/395578714,395578706,395578712,395580174/master.mpd?_=1445292210920'. This request has been blocked; the content must be served over HTTPS.
```
It would be nice to have the demo page served over http if requested as such.

**Comment by joeyparrish** [comment]
The EME spec will require HTTPS in the future, so the demo app was changed to be ready for that change.

If you need to test content locally over HTTP, you should be able to run Shaka Player from localhost over HTTP as well.  Let me know if you have any difficulties with this, and I'll be happy to help.

**Comment by joeyparrish** [comment]
We have had more complaints about this, and we have changed our appspot config to permit plain HTTP again.
