### ISSUE TITLE
Options for Multi-Period streaming on certain devices (WebOS and Tizen TV)

### ISSUE THREAD

**Issue by karthiksivaram** [google/shaka-player#2099]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Is your feature request related to a problem? Please describe.**

We use Shaka player for playing DASH streams with SSAI (Server Side Ad Insertion). These streams have multi-period DASH where Ad Periods are not encrypted, but Content periods are encrypted with DRM (Widevine or Playready).

We have encountered a bit of a blocking problem on new devices (LG WebOS TV and Samsung Tizen TV), and upon in-depth investigation, it appears that at least on WebOS, the media source does not like "re-initialisation" for the next Period (Period 1). This causes playback to fail abruptly while the period transition occurs. Additionally since Shaka also buffers and appends to the media buffer in advance of the actual playhead reaching the end of the ad, this actually occurs about 9-12 seconds before the end of the Ad Period (Period 0). 

**Describe the solution you'd like**

We would like an optional setting to teardown and re-stream when changing periods for multi-period dash rather than continuing with the same media source session.

We are also willing to look at this ourselves and contribute a PR, but would need guidance in order to be able to execute this.

**Describe alternatives you've considered**

We have been able to successfully use dash.js on these devices because it appears that in dash.js the media source is torn down and rebuilt when transitioning across periods. Our preference is to use Shaka player and so we have been trying to investigate how to bring a similar behaviour, i.e. signal that a teardown and rebuild has to happen for Period changes. 

**Additional context**

**Comment by chrisfillmore** [comment]
We have had several issues related to playing clear SSAI ads on Tizen devices:
#1094
#1294
#1567

Can you explain some more about your issue? Do you have a problem when you start playback during protected content? Or during an ad (clear) content? We have found we have issues when starting with clear content. The device has trouble transitioning to encrypted content, even if we initialize DrmEngine at playback start.

**Comment by karthiksivaram** [comment]
After stripping it down to just MSE level appendBuffer (no higher level dash support), the device balks when sent a secondary INIT segment. If the init segment is skipped then it continues merrily along (obviously when the content is encrypted it cannot decode it correctly). Without the INIT segment it does not generate the "encrypted" event as well. So it appears that the devices do not handle a secondary INIT segment in the stream / buffer. 

It appears that dash.js actually tears down the media source and creates a new one for each period and hence it does not have the same problem (agreed that the UX is not the best outcome, where there is a pause/buffer during the tear down + re-create).

**Comment by joeyparrish** [comment]
If the device doesn't accept a second init segment, then it's not compliant with the MSE spec.  That's a bug on WebOS, not Shaka Player.  We would strongly recommend filing a bug against LG for this.

WebOS is not an officially-supported platform yet, but we have plans to add it later this year once we are able to set up the infrastructure for test automation on that platform.  Until then, we can't really do anything to debug this issue.  When we finally get WebOS set up in our test lab, we will be able to investigate and potentially offer a solution or workaround, if one can be found.

At this time, we stand by our architecture of having a single playback session for multi-period content.  You could always choose another player like dash.js if you believe that tearing down playback between periods is necessary and/or correct.

We apologize for any inconvenience.

**Comment by joeyparrish** [comment]
Closing this stale external (non-Shaka) issue. If you disagree, please reply with @shaka-bot reopen, and it will be automatically reopened.
