### ISSUE TITLE
isBrowserSupported for iOS

### ISSUE THREAD

**Issue by orange4glace** [google/shaka-player#2100]
I've tested `Player.isBrowserSupported` with iOS version 12 on [BrowserStack](https://live.browserstack.com) to check whether the ShakaPlayer supports it or not, and it turns out either Safari and Chrome says 'false'.
I'm curious that does ShakaPlayer actually supports it since base on the documentation and the [CHANGELOG](https://github.com/google/shaka-player/blob/master/CHANGELOG.md#254-2019-07-19), it seems work on iOS but I'm getting `false` for the `isBrowserSupported`. 
Why `Player.isBrowserSupported` returns false on iOS > 9? Is this something problem with BrowserStack?

**Comment by joeyparrish** [comment]
It should return true on iOS.  What version of Shaka Player are you using in this test?  We only added iOS support in v2.5.

**Comment by orange4glace** [comment]
@joeyparrish I've just tested again and it returns `true`. The reason is that sometimes `window.MediaKeySystemAccesss` returns 'undefined' for some reason. It might be the problem of the BrowserStack. Thanks for the answer!

**Comment by joeyparrish** [comment]
Happy to help!

For what it's worth, we had a lot of issues with hosted VMs for browser testing in the past.  We eventually built our own lab with physical devices on a Selenium grid for automated testing.  I know our solution is not for everyone, but also I'm not surprised that you get some occasional inconsistencies with a hosted solution.

If you ever discover in your investigations that there's something we can change to make results more consistent on VMs and hosted virtualized browsers, please let us know!  We are always happy to improve things, even for scenarios that don't apply to us.
