### ISSUE TITLE
VTT captions in HLS are mis-timed.

### ISSUE THREAD

**Issue by theodab** [google/shaka-player#2101]
When VTT captions are in an HLS stream, they are timed incorrectly.
For example, see [this Unified Streaming asset](https://demo.unified-streaming.com/video/tears-of-steel/tears-of-steel-multiple-subtitles.ism/.m3u8) or [this Apple sample asset](https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_fmp4/master.m3u8) (NOTE: The Apple asset will require running Chrome in no-CORS mode to test). Both of those assets have captions timed as expected if run directly in Safari, but their captions are mis-timed or missing when run with Shaka Player.

**Comment by TheModMaker** [comment]
Probably a duplicate of #1563.

**Comment by michellezhuogg** [comment]
Also, the Unified Streaming asset skips the first ten seconds in shaka player.

**Comment by theodab** [comment]
Testing this again now, I can no longer reproduce this issue. Perhaps it really was a duplicate of #1563?
