### ISSUE TITLE
Integration Console:  Gools > Shaka Player: Microsoft Edge - Playback no working for many of the videos

### ISSUE THREAD

**Issue by MayreLew** [google/shaka-player#2104]
Short Description of problem:
Tools > Shaka Player: Microsoft Edge - Playback not working for many Shaka Player videos

Build of Integration Console: https://integration.staging.widevine.com/player
Browser version: Microsoft Edge 44.17763.1.0
Environment: Staging
Device:  Surface laptop
OS:  Windows 10 Home
Version: 1809
OS Build: 17763.678

Steps to Reproduce:
1. Using Micorsoft Edge as the browser, navigate to:  https://integration.staging.widevine.com
In User Mode on the Integration Console, navigate to:  Tools > Shaka Player
2. From the upper left corner, go to the field called:  Content List
3. Select a video from the drop down list box. (See the list of videos below which are having issues.
4. Click on the "Play" button located on the upper right corner.
5.  Repeat attempted playback of all the videos from the drop down list box.

Expected results:
All the videos should play back without any issues.

Actual results:
An error message appears stating the following:
Playback error 
category: 6
code: 6001
data:

Error occurs on the following videos from the drop down list:
H264 - All (Widevine), SD (Widevine), HD (widevine), UHD (Widevine)
VP9 - All (Widevine), SD (Widevine), HD (widevine), UHD (Widevine)
HEVC - All (Widevine), SD (Widevine), HD (widevine), UHD (Widevine)
CBC1 - H264 (30fps - SD/HD),  H264 (30fps - UHD)
CBCS - H264 (30fps - SD/HD), H264 (30fps - UHD)
CENC - H264 (30fps - SD/HD), H264 (30fps - UHD)
CENC - H264 (60fps - SD/HD), H264 (60fps - UHD)
CENC - HEVC (30fps - SD/HD), HEVC (30fps - UHD)
CENC - HEVC (60fps - SD/HD), HEVC (60fps - UHD)
CENC - VP9 (30fps - SD/HD), VP9 (30fps - UHD)
CENC - VP9 (60fps - SD/HD), VP9 (60fps - UHD)
CENS - H264 (30fps - SD/HD), H264 (30fps - UHD)

Additional information:
Please see the attached video

![Videos not playing on Shaka Player tool on integration console](https://user-images.githubusercontent.com/51837636/63307152-361ef600-c2a2-11e9-918b-4572d5eb18cb.png)

**Comment by joeyparrish** [comment]
First, please do not file Widevine Integration Console bugs against Shaka Player.  That is a separate project, and we don't maintain it.

Second, Microsoft Edge does not have Widevine support, so those Widevine clips are not going to play on Edge.
