### ISSUE TITLE
Player Error occured when trying to play an encrypted content

### ISSUE THREAD

**Issue by weiyuefei** [google/shaka-player#2105]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
I am using the shaka-player on the integration website.

**Can you reproduce the issue with our latest release version?**
not test

**Can you reproduce the issue with the latest code from `master`?**
not test 

**Are you using the demo app or your own custom app?**
I am using the shaka-player on integration website.

**What browser and OS are you using?**
Chrome 76.0.3809.100 and Windows7

**What are the manifest and license server URIs?**
Already sent to shaka-player-issues@google.com

**What did you do?**

1. Open integration website: https://integration.widevine.com/player
2. Input the content url and license url accordingly.
3. press the Play button

**What did you expect to happen?**
Load the mpd and then request the license and plays ok.

**What actually happened?**
Shaka-player just download the manifest.mpd and then stop and displays "Player Error". It never request the license from our proxy. The following snapshot is an overview of this issue.

**Comment by theodab** [comment]
The console is outputting a CORS error. We can't really do much about that on our end; if the server's headers are not set up properly, Chrome will simply not allow applications to make use of downloaded data, not even the manifest.

Do you control that content? If so, you could set its `Access-Control-Allow-Origin` headers to mention the Widevine integration console. Here's [more info](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin) on MDN.

Alternately, if you just need to test your content on a temporary basis, or you are not willing or able to change the server's headers, you could load Chrome in no-CORS mode. Here's a [StackOverflow question](https://stackoverflow.com/questions/3102819/disable-same-origin-policy-in-chrome) about that process.

Does that help?

**Comment by weiyuefei** [comment]
I think we have already set the CORS correctly, The following is the response headers from the content server:

![image](https://user-images.githubusercontent.com/15873219/63318374-d891b480-c348-11e9-8d4e-5233447df64c.png)

**Comment by TheModMaker** [comment]
The video plays fine in the [Shaka Player demo](https://shaka-player-demo.appspot.com/demo/) if I disable CORS (you only allowed CORS access for the integration console).  This is an issue with the Widevine Integration console, not with Shaka Player.  Please talk to the Widevine team about this.
