### ISSUE TITLE
Possible to download video to local file?

### ISSUE THREAD

**Issue by lisayan** [google/shaka-player#2107]
The Offline Storage and Playback tutorial seems to address saving the video with shaka.offline.Storage, but I can't find any information on downloading it locally.

**Comment by joeyparrish** [comment]
Hi Lisa,

In short, you can't do that.  At least, you can't do that in a consistent, standard way.  There's no standard API for filesystem access across browsers, so you can't save content to the filesystem and then play it back with MediaSource.

If you have a specific use case in mind, we would be happy to discuss it and help you find the best solution.
