### ISSUE TITLE
HLS parser stops execution if it encounters a file format it can't parse the start time from

### ISSUE THREAD

**Issue by ismena** [google/shaka-player#2108]
**Can you reproduce the issue with our latest release version?**
Y

**Can you reproduce the issue with the latest code from `master`?**
Y

**Are you using the demo app or your own custom app?**
Demo

**What did you do?**

Load an hls manifest that has webm content. 

**What did you expect to happen?**
It's either played or filtered out

**What actually happened?**
We're unable to parse the start time from webm segments and the execution stops.

FWIW, Wemb isn't an officially supported hls format and I've never seen webm+hls combination out there.
@joeyparrish can decide whether we want to support this, for now we should just skip the webm variants with a warning log and play what we can play.

**Comment by ismena** [comment]
Awesome @michellezhuogg volunteered to fix this!

**Comment by joeyparrish** [comment]
I believe this was fixed in 1ee32849e4eea94553baaeec94e3ac9bfdf7f1b1.
