### ISSUE TITLE
Safari HLS MP4 profil switch

### ISSUE THREAD

**Issue by Romain-Bernier** [google/shaka-player#2109]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
Demo page

**Can you reproduce the issue with our latest release version?**
N/A

**Can you reproduce the issue with the latest code from `master`?**
N/A

**Are you using the demo app or your own custom app?**
Demo

**If custom app, can you reproduce the issue using our demo app?**
N/A

**What browser and OS are you using?**
Safari 12.1.2 (14607.3.9) macOS 10.14.6

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
The 2 demo example for Live HLS MP4
(Shaka Player History and Clear, Live HLS)

**What did you do?**
Start the player

**What did you expect to happen?**
To have the possibility to change the resolution.

**What actually happened?**
The resolution button is not display and if the player change the resolution by itself, the video freeze.
<img width="1440" alt="Capture d’écran 2019-08-21 à 15 30 15" src="https://user-images.githubusercontent.com/48755954/63437654-33034180-c42b-11e9-8ce1-b4f23de33fbd.png">

**Comment by ismena** [comment]
@joeyparrish it's the src= thing, isn't it? 
Here is the best I remember about the way it works, I tagged Joey who worked on the implementation, so he can come and set things straight if give you a goofy explanation :)

Safari has it's own implementation when it comes to hls and does not have great support for Media Source Interface, which is what we interact with in other supported browsers.
If we see an hls manifest, we just give it to Safari to do its own thing, and don't really have control over which tracks it plays, hence the lack of the resolutions button: we can't tell Safari what to play.

The fact that the Shaka livestream hangs after the first few seconds is an unrelated problem - the stream itself is down at the moment :(

**Comment by joeyparrish** [comment]
Yes, the Shaka Player History live stream is down.  I told @vickymin13 somebody would notice eventually.  :-D

We don't use src= for all HLS on Safari.  We use src= for all playback on iOS, though, where MediaSource doesn't exist.  For desktop Safari, we can still use MediaSource, so we prefer that, IIRC.

**Comment by joeyparrish** [comment]
@ismena just corrected me privately: this is using src= for HLS on desktop Safari after all.  I must have misremembered the logic for choosing between src= and MediaSource on desktop Safari.

**Comment by ismena** [comment]
Here's #2116 to look into using MediaSource on desktop Safari.

**Comment by Romain-Bernier** [comment]
Ok, thanks, 
Hls.js find a way to allow the user to change resolution, using a similar solution is possible ?

**Comment by TheModMaker** [comment]
> Hls.js find a way to allow the user to change resolution, using a similar solution is possible ?

hls.js is parsing the HLS manifest and playing it back using MediaSource.  That is what we do for other platforms and browsers, but we default to using native `src=` on Safari for FairPlay support.  That is what #2116 is trying to change.  You can force us to use the MediaSource version with:

```js
player.load('manifest.m3u8', null, shaka.hls.HlsParser);
```

**Comment by TheModMaker** [comment]
Now there is a configuration to not use `src=` on Safari.  You can set the `streaming.useNativeHlsOnSafari` configuration to `false` to be able to select tracks; but this won't work if you want to play FairPlay content.

Does this answer all your questions?

**Comment by Romain-Bernier** [comment]
Yes, thanks a lot, I close the issue
