### ISSUE TITLE
Is shaka-player support Basic Auth to query MPD

### ISSUE THREAD

**Issue by babyChou** [google/shaka-player#211]
I found a function "shaka.util.AjaxRequest.Parameters".
It seem could add parameters to Header. but I don't know how to use it
Is shaka-player support customs header or Basic Auth Authorization??

thank you

**Comment by joeyparrish** [comment]
In your DRM callback, you need to set the 'withCredentials' flag to true and set a license request pre-processor callback.  In the pre-processor callback, set the request header 'Authorization' to the value of 'Basic ' + btoa('username:password').

I hope that helps.  If not, please reopen and we can discuss further.  Alternately, you can direct questions like this to the mailing list as well.

References:
http://stackoverflow.com/questions/1652178/basic-authentication-with-xmlhttprequest
https://shaka-player-demo.appspot.com/docs/tutorial-player.html (section "Protected Content")
https://shaka-player-demo.appspot.com/docs/tutorial-network.html
