### ISSUE TITLE
Buffering spinner not visible against a black background

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#2110]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
master

**Can you reproduce the issue with our latest release version?**

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Demo

**What browser and OS are you using?**
ChromeOS stable

**What are the manifest and license server URIs?**
https://nightly-dot-shaka-player-demo.appspot.com/demo/#audiolang=de;textlang=de;uilang=de;asset=https://storage.googleapis.com/shaka-live-assets/player-source.m3u8;panel=HOME;build=uncompiled

**What did you do?**
This live stream is currently down, so it will play the last several seconds, then buffer forever.

**What did you expect to happen?**
When the player enters a buffering state, I would expect to be able to see the spinner against any background.

**What actually happened?**
The spinner is black, and the video frame is mostly black, so it is very hard to see.  If the controls are shown, it is even harder to see against the outline of the pause button.

It might be nice if there were a white shadow around the black spinner.  Not sure if Chrome native controls are any better in this regard.  I haven't tested that.

**Comment by joeyparrish** [comment]
Adding `filter: drop-shadow(0 0 5px white)` on the spinner container in the debugger looks pretty decent.  Not sure if 5px is a bad idea, though.  Perhaps some relative unit would make more sense, but I'm not sure what.

**Comment by ismena** [comment]
I... um... don't like the way that filter looks very much :no_mouth:

I checked what the Native controls do, and their spinner is even more black than hours, I can't see it at all.
Will keep thinking :|
