### ISSUE TITLE
Latest Shaka Player build does not use first segment for VOD Asset

### ISSUE THREAD

**Issue by apblack96** [google/shaka-player#2111]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
No

**What version of Shaka Player are you using?**
v2.5.4-master-60-ge2103d23 and v2.5.4 (uncompiled)

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Demo and Nightly Demo

**If custom app, can you reproduce the issue using our demo app?**
N/A

**What browser and OS are you using?**
Chrome and MacOS

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**

**What did you do?**

Created a custom content stream for a VOD asset. Filled out Manifest URL, Name, Custom License Server URL. 
Went to play the asset using the nightly Shaka Player build and the player is requesting a segment that is not the first segment of the video. 
So playback does not work for the first x amount of time in the video.

I am able to correctly stream this same asset using the normal Shaka Player Demo page.

**What did you expect to happen?**
Asset to Playback properly

**What actually happened?**

When attempting to play an asset on the latest build of Shaka Player (https://nightly-dot-shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;) the player is requesting a manifest segment that is not the first segment of the asset. Therefore the  asset starts playing at 10:40 seconds rather than the beginning of the asset. When playing the same asset using the Shaka Demo Player (https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;panel=CUSTOM%20CONTENT;build=uncompiled) I am able to properly stream the asset. So it seems something between the version of the Shaka Demo Player and the Nightly Shaka Demo Player version the player is grabbing the wrong first segment.

**Comment by joeyparrish** [comment]
It's working in v2.5.4, but failing in the nightly.  My suspicion is that I broke it during the period flattening refactors somewhere.  I haven't debugged this beyond inspecting the manifest with @apblack96.

In this particular case, the manifest he sent via email should be enough to reproduce the issue without the license server URL, which he was unable to easily share due to authentication issues.

**Comment by joeyparrish** [comment]
`startNumber` in the manifest is `1`, `presentationTimeOffset` is `0`.  v2.5.4 starts streaming at segment 1, but the nightly does not.

**Comment by TheModMaker** [comment]
This was broken by 08cec995c998fa41b7c7da4560f3a88211402c4b, which wasn't cherry-picked for v2.5.4.

**Comment by joeyparrish** [comment]
I had a strong feeling it was me who broke it.  :-)  Thanks, Jacob, for tracking that down!

**Comment by joeyparrish** [comment]
This is still broken in the master branch as of today.

**Comment by apblack96** [comment]
I just want to confirm that if I continue pulling from the v2.5.x branch that this is not an issue.

**Comment by joeyparrish** [comment]
That's correct.  The release branch should not be affected.

**Comment by joeyparrish** [comment]
This should be fixed now in `master`.  It never affected `v2.5.x` releases as far as we can tell.  Let us know if you need anything else!
