### ISSUE TITLE
General feature inquiry

### ISSUE THREAD

**Issue by iqradada** [google/shaka-player#2113]
Wanted to ask a few questions about feature support:
- is there in-built tracking?
- what audio types are supported?
- are there thumbnail previews?
- mirroring/ over-the-air support?
- i18n?
- VR?
- PiP
- Logging?
- what's the bundle/library size?
- is it extendable?
- what external videos are supported? vimeo, dailymotions, etc?

**Comment by theodab** [comment]
> is there in-built tracking?

As in, analytics? We don't have any analytics support.

> what audio types are supported?

Audio is handled by the browser. So we handle whatever the browser says it supports.

> are there thumbnail previews?

We do not yet have thumbnail track support. See #559.

> mirroring/ over-the-air support?

We have ChromeCast support. No Apple TV support, though.

> i18n?

Our UI is localized into multiple languages (both the visual parts, and the screen reader text). Our demo page isn't yet, but we hope to get it all translated at some point in the future. And we will present whatever text and audio tracks are listed in the manifest to the user, of course.

> VR?

I'm not sure what you mean by VR. Do you mean 360 degree video, that kind of thing? We don't have support for that at the moment. Something like that would be a transformation on the drawing surface, which we considered to be outside the scope of our library for a while. Now that we have a UI library though, I suppose that could be a reasonable feature request for the UI.

> PiP

We do have PiP support. Our UI library has a PiP button as part of its default button layout, for instance.

> Logging?

We have logging with multiple log levels. It just logs to the browser console, so if you are specifically interested in collecting the logs onto some server, that isn't supported at the moment, though that sounds like a reasonable feature request to me.

> what's the bundle/library size?

With the UI, Shaka Player is currently about 390kb when fully compiled. Without the UI, it's 330kb.

> is it extendable?

Shaka Player has a plugin interface for a number of internal components. You can provide custom manifest parsers, network scheme plugins, etc. Also, we're an open source project, and we try to keep our code well-documented, so it should be pretty 

> what external videos are supported? vimeo, dailymotions, etc?

We should be able to support anything that comes in an HLS or MPEG-Dash manifest. And, like, has its cross-origin headers set to allow us to download their content and stuff, obviously.
We have a bunch of sample assets on our demo page. They're from services like [Axinom](https://www.axinom.com/), [Unified Streaming](https://www.unified-streaming.com/), [Wowza](https://www.wowza.com/), and a bunch of others. Basically, whichever services we could find that had chosen to provide sample assets online for us to test with.
I don't know about vimeo or dailymotion in particular. I poked at their sites a bit; dailymotion seems to use some form of HLS manifest, and I couldn't find any manifest for vimeo (so either they have some custom format, or they hid their manifests well enough that I couldn't find them). If you have some manifests from those services, I guess we could test them. I would assume that neither wants people to be playing their content on external via third-party players though, but I don't really know their policies regarding that kind of thing so I could be wrong.

**Comment by iqradada** [comment]
Thank you so much for all the information. It was incredibly helpful!
