### ISSUE TITLE
Safari HLS Variant Track handling?

### ISSUE THREAD

**Issue by orange4glace** [google/shaka-player#2114]
I just found out that `getVariantTracks` and `selectVariantTrack` does not work as expected in Safari.

So I looked into the source and the comment says 
```
// Safari's native HLS won't let you choose an explicit variant, though
// you can choose audio languages this way.
```

Does this mean ShakaPlayer uses `audioTracks` to workaround the resolution selection OR Safari handles it with its bulit-in ABR and we can't do manual resolution selection?

Thanks :)

**Comment by orange4glace** [comment]
Actually can't we parse the set of resolutions from the master m3u8 file? 
https://stackoverflow.com/a/53617416

**Comment by matvp91** [comment]
Safari's HTML5 video element does not have an API to restrict resolutions / force video tracks, you'd have to rely on their internal ABR algoritms.

**Comment by ismena** [comment]
@matvp91 is right.

Safari has its own implementation for handling hls and thus is not very invested into their MediaSource API support (which is how we work with other browsers).

There seems to be quite a bit of interest in this from the community, so let me file a separate issue for us to revisit our codebase on HLS+Safari and see if we can route it through Safari's MediaSource on Desktop after all. I remember running into bugs in their MediaSource implementation before, but we can see what state it's currently in.

**Comment by ismena** [comment]
Here's #2116 to look into this.
