### ISSUE TITLE
Shaka 2.5.4 - No subtitle displayed when loading DASH static stream

### ISSUE THREAD

**Issue by hdodev** [google/shaka-player#2115]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Maybe linked to #1778, where are described Shaka capabilities ("Note that we support both TTML and VTT in two different formats..."), but not sure.

**What version of Shaka Player are you using?**
2.5.4

**Can you reproduce the issue with our latest release version?**
YES

**Can you reproduce the issue with the latest code from `master`?**
YES

**Are you using the demo app or your own custom app?**
CUSTOM

**If custom app, can you reproduce the issue using our demo app?**
YES

**What browser and OS are you using?**
Chrome 70 on Ubuntu

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
Manifest in attached file
[Manifest.zip](https://github.com/google/shaka-player/files/3530452/Manifest.zip)

**What did you do?**
Playback o a static DASH stream, and display of available audio an subtitles tracks, using the getXXXTracks() methods.

**What did you expect to happen?**
3 Audio tracks displayed, and 1 subtitle track

**What actually happened?**
3 Audio tracks displayed, and 0 subtitle track

**Comment by TheModMaker** [comment]
Your content specifies `contentType="subtitle"`, which is against the DASH spec.  The correct content type is `text`.  See #1900.

**Comment by hdodev** [comment]
Hello @TheModMaker . Actually it's a very apparent error ! So, according to the 1900 case, we should provide:
- At AdaptationSet level : contentType="text"
- At Role sublevel : value="subtitle"
Thanks for this very quick feedback. I close the case.
