### ISSUE TITLE
Try playing HLS on desktop Safari through MediaSource, not src=

### ISSUE THREAD

**Issue by ismena** [google/shaka-player#2116]
When hls manifests are routed through src=, it takes away the app's ability to select variant tracks and users' ability to select resolutions through the UI (Safari's native hls does not allow it).
We should see if we can route it through MediaSource on desktop Safari to keep this functionality.

I remember running into bugs in Safari's MediaSource implementation before we had the src= feature, but maybe things have changed since then.

**Comment by ismena** [comment]
Here's #2116 to look into using MediaSource on desktop Safari.

**Comment by avelad** [comment]
Note: for FairPlay is necessary use src=

**Comment by ismena** [comment]
Ahhh, that's probably why! @joeyparrish and I were trying to figure out why we use scrc= on desktop yesterday, but couldn't remember.

**Comment by avelad** [comment]
Would it be possible to add a configuration for this?

**Comment by ismena** [comment]
Yeah, I'll discuss with joey once he's back in office. 
Essentially, if you're using FairPlay, you'll want Safari's native hls, right? And MediaSource otherwise?

Is there another use case I'm not thinking of?

**Comment by avelad** [comment]
Airplay only works with src= so I prefer a configuration where the application can decide what to use.

For FairPlay I always want to use src=.

**Comment by matvp91** [comment]
@ismena, exactly. `com.apple.fps.1_0` is established by Safari emitting the `webkitneedkey` event on the video element. Using MediaSource is possible with `com.apple.fps.2_0` but Apple does not provide any publicly available documentation. If I'm not mistaken, Netflix serves FairPlay DASH with MediaSource.

**Comment by chrisfillmore** [comment]
This is an old PR now:
https://github.com/google/shaka-player/pull/1199

I was able to generate a license challenge with MSE-EME, but had an issue getting a response from my license server. I wasn't sure if it was an issue with our proxy or with the Fairplay server. Eventually I ran out of time and had to work on other things. Someone with some bandwidth could take up this work if they were interested.

**Comment by ismena** [comment]
Okay. So. Here's what seems to be happening on our side:
We'll try to connect with developers at Apple, see if we can get the documentation for supporting FairPlay via MediaSource. If that happens, we'll take on finishing @chrisfillmore's PR.

In the meantime, we'll work on adding the config suggested by @avelad.

**Comment by ismena** [comment]
A `useNativeHlsOnSafari` field has been added to `streamingConfiguration`.
Note that t's true by default and will need to be reconfigured to get the behavior change.
