### ISSUE TITLE
HLS playback get stalled on last 1 second

### ISSUE THREAD

**Issue by orange4glace** [google/shaka-player#2117]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
2.5.4

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `master`?**
yes

**Are you using the demo app or your own custom app?**
custom
Here's the link to download
[https://drive.google.com/file/d/1wA0_-g5TkbK6Qp8H2JC27vs0MY3Fs9RA/view?usp=sharing](https://drive.google.com/file/d/1wA0_-g5TkbK6Qp8H2JC27vs0MY3Fs9RA/view?usp=sharing)

**If custom app, can you reproduce the issue using our demo app?**
yes

**What browser and OS are you using?**
MacOS Mojave Safari 12.1
MacOS High Sierra Safari 11.1
macOS Sierra Safari 10.1

**What are the manifest and license server URIs?**
https://drm-media.s3.ap-northeast-2.amazonaws.com/dash/samplehlstest1.m3u8
No license server needed

**What did you do?**
Just play the hls media with ShakaPlayer

**What did you expect to happen?**
It should be played normally

**What actually happened?**
video get stalled on last 1 second.
clicking play button / pause button do nothing

Both with FPS and without FPS has same bug

`shaka.html`
![Honeycam 2019-08-23 20-04-18](https://user-images.githubusercontent.com/17820596/63588480-93d47a80-c5e1-11e9-87fc-0178b2131114.gif)

`video.html`
![Honeycam 2019-08-23 20-07-46](https://user-images.githubusercontent.com/17820596/63588525-b5356680-c5e1-11e9-8a6f-bf236dcca3f6.gif)

**Comment by orange4glace** [comment]
So [this](https://github.com/google/shaka-player/blob/master/lib/player.js#L4984) was the problem.
```javascript
    // Because Safari's native HLS reports slightly inaccurate values for
    // bufferEnd here, we use a fudge factor.  Without this, we can end up in a
    // buffering state at the end of the stream.
    // TODO: Try to remove the fudge here once we no longer manage buffering
    // state above the browser with playbackRate=0.
    const fudge = 0.1;  // 100 ms
    return bufferEnd >= this.video_.duration - fudge;
```
My m3u8 file is more inaccurate than 100ms so the fake buffer event is dispatched.

Can we give more than 0.1 second to `fudge`? like 1 second since m3u8 can have time inaccuracy maximum 1 second.

**Comment by theodab** [comment]
I see. At first I thought I was unable to reproduce the problem, but actually this problem only happens with the default Safari controls.
I'll get a CL out for this. Thanks for the report!
