### ISSUE TITLE
Support DASH "forced_subtitle" role

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#2122]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Is your feature request related to a problem? Please describe.**
Content can have "forced" subs, for example, when characters are speaking a language other than the main language and the content's creators want subtitles to be shown to the audience for that one part.

**Describe the solution you'd like**

Shaka Player should support the "forced_subtitle" Role in DASH, mentioned here as part of Amd. 5 for 23009-1: https://github.com/Dash-Industry-Forum/DASH-IF-IOP/issues/165#issuecomment-378193268

The Player should then default to show these subtitles if no others are being shown.  The UI should say something like "English (forced)" to represent the forced subs for English.  The user should still be able to turn subs off completely if they wish.

**Describe alternatives you've considered**
None come to mind.  The status quo is that we don't understand the "forced_subtitle" Role, and we don't tag the tracks with appropriate metadata.

**Comment by avelad** [comment]
This has already been resolved with: https://github.com/google/shaka-player/commit/01998f3b99990afa54cfe5ae5632c265e23fbd66
