### ISSUE TITLE
Question about segment size

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#2124]
Is there any way to get the size of the segment that is being used for audio, video and text?

**Comment by avelad** [comment]
Would it be possible to only get the one that is currently playing or the last one that has been downloaded?

**Comment by avelad** [comment]
`manifest.presentationTimeline.getMaxSegmentDuration()` is not exported, but if it is exported I can access to the value with `player.getManifest().presentationTimeline.getMaxSegmentDuration()`
And it's enough for now.

**Comment by ismena** [comment]
@avelad Oh, I have actually just landed that same change. See if it works for you now!

**Comment by avelad** [comment]
Now it works!
