### ISSUE TITLE
export shaka.util.FakeEvent

### ISSUE THREAD

**Issue by gscragg** [google/shaka-player#2125]
`shaka.Player` has a public (exported) function `dispatchEvent` that is not callable from outside code due to it needing an instance of `shaka.util.FakeEvent`.

Would it be possible to export this type? Or should we use our own custom event dispatch code instead of shakas?

**Comment by TheModMaker** [comment]
We don't listen for events on Player, we only raise events for the benefit of the app.  Are you trying to raise an event to avoid duplicating your listeners?  It would probably be better to use your own event handling to avoid depending on our implementation (and encouraging people to use our fake handlers).  We didn't intend the `FakeEventTarget` and `FakeEvent` types to be used by apps.  But we could export it if it makes things much easier of if you have an important use case for it.

**Comment by gscragg** [comment]
Yeah it was just to minimise event handlers and deciding which target (video element, or shaka player) to attach a listener too. I later learned that shaka only duplicates `error` events from the video tag, and none of the others, so this change won't help me anyway.
Thanks.

**Comment by TheModMaker** [comment]
We handle the `error` event a bit different; we will listen for it from the video element and raise our own error object with a `code` of `VIDEO_ERROR`.  So you don't have to listen for video errors yourself, you can just listen for Player errors.

Other than `error`, you are correct, we don't copy any other events.  We assume you interact with the video element like normal (similar to `src=` playback) and you use the Player instance for some extended behavior (like track selection).
