### ISSUE TITLE
Auto fullscreen with change orentation & wrong plug shaka

### ISSUE THREAD

**Issue by ivansteff** [google/shaka-player#2127]
I have a problem switching to full screen mode when I rotate the device (phone). On a site with a [demo](https://shaka-player-demo.appspot.com/demo/#audiolang=ru-RU;textlang=ru-RU;uilang=ru-RU;asset=https://storage.googleapis.com/shaka-demo-assets/sintel-widevine/dash.mpd;panel=HOME;build=uncompiled), I don’t have such a problem, maybe I'm connecting something wrong?

I plug shaka in my index.html by cdn:
`<script src="https://cdnjs.cloudflare.com/ajax/libs/shaka-player/2.5.5/shaka-player.compiled.js" integrity="sha256-HmOZIJNxKvdI9D7Iu/c2VFEOV3cczdsRADIjmzhioqI=" crossorigin="anonymous"></script>`

I use Vue.js. I init shaka in mounted, like this: 
```
        mounted(){
            this.video = this.$refs.video;
            this.player = new shaka.Player(this.video);
            this.player.addEventListener('error', err => console.error(err));
            shaka.polyfill.installAll();
            if (!shaka.Player.isBrowserSupported()) {
                console.error('Browser not supported');
                return;
            }
}
```
` this.video = this.$refs.video;
`
this is link to video tag:
            `<video ref="video" id="video" autoplay  controls></video>`

Also shows the wrong time for live video (in the demo there is no time for live video)
If I put the same stream link in a demo example, then everything is fine.
I think that i wrong plug shaka.

**Comment by joeyparrish** [comment]
Hi @ivansteff,

It's nothing you're doing wrong.  This feature of Shaka Player is part of the UI, so it is built into our UI library.  You're using the non-UI version of the library.  The UI library includes a customizable video controls UI, which is where the rotate-to-fullscreen feature is implemented.

If you'd like to try the UI library, switch `shaka-player.compiled.js` to `shaka-player.ui.js`, include our CSS file `controls.css` (missing from CDNJS, but present in npm-based CDNs and on [Google's own](https://ajax.googleapis.com/ajax/libs/shaka-player/2.5.5/controls.css)), and change your video element to this:

```html
<video ref="video" id="video" autoplay playsinline data-shaka-player></video>
```

You can find more details in our UI tutorial:
https://shaka-player-demo.appspot.com/docs/api/tutorial-ui.html

Does this help?

**Comment by joeyparrish** [comment]
Oh, and I forgot to mention, in your JS code, instead of this:

```js
            this.video = this.$refs.video;
            this.player = new shaka.Player(this.video);
```

Do this:

```js
            this.video = this.$refs.video;
            this.player = this.video.ui.getControls().getPlayer();
```

The player is automatically constructed for you with the UI library's declarative setup through HTML.

**Comment by ivansteff** [comment]
@joeyparrish Thanks for the quick response.
I connect syle.css file, rewrote the code as you recommended above. I caught a two erros:
1-`Error in mounted hook: "TypeError: Cannot read property 'getControls' of undefined"
`
2-`TypeError: Cannot read property 'getControls' of undefined`

**Comment by joeyparrish** [comment]
Please check out the UI tutorial here and adapt it to your needs: https://shaka-player-demo.appspot.com/docs/api/tutorial-ui.html

It could be that you need to wait for the event that says the UI library is fully loaded before you get a player reference.

**Comment by ivansteff** [comment]
@joeyparrish  Okay, Thanks for the answer, I will try to remake.
