### ISSUE TITLE
Hls live stream stuck after start playing

### ISSUE THREAD

**Issue by michellezhuogg** [google/shaka-player#2128]
The live stream gets stuck after about 10 seconds playing.

https://nightly-dot-shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://storage.googleapis.com/shaka-live-assets/player-source.m3u8;panel=HOME;build=uncompiled

**Comment by joeyparrish** [comment]
It's currently down while we are replacing the live streaming tools behind that content.  It should be back up next week.  Sorry!
