### ISSUE TITLE
Is there an event we can listen for when text tracks are enabled/disabled?

### ISSUE THREAD

**Issue by sanbornhnewyyz** [google/shaka-player#213]
When text tracks are enabled/disabled, their 'enable' property is toggled but it doesn't seem like any event is firing that can tip us off that there has been an update to the track object. Is this correct?

**Comment by joeyparrish** [comment]
Sorry for the delay in my reply.  That's correct, there are no events for this at the moment.

Any change in enabled text tracks either driven through your app, in which case you already know, or it's done through the built-in controls in the browser, in which case there is no native event and we would have to poll to discover this for you.

I don't think polling HTMLTrackElement.mode is something I want to do right now.  Do you have any ideas for other ways we could solve this?

**Comment by joeyparrish** [comment]
Since there's no better options on the table other than polling, I'm going to close this.  The same polling could be done at the app level if desired.
