### ISSUE TITLE
WEBM_CUES_ELEMENT_MISSING for webm audio with opus codec

### ISSUE THREAD

**Issue by MenilikBelay** [google/shaka-player#2132]
Hi, I have been encoding an audio file using ffmpeg. I prefer to use opus codec (tested with 96k bit rate) and webm container. I have then packaged it up using shaka-packager and when I try to stream it over HTTP (DASH), it shows 'ERROR code 3007 category 3'. [actually, it start to play when I refresh the page on Google Chrome but not on Firefox]. Error code of 3007 means WEBM_CUES_ELEMENT_MISSING in your documentation. Can you help me where I can fix this [maybe commands in ffmpeg or packager]? Thank you. Here is the command I have used.
![image](https://user-images.githubusercontent.com/25073507/64156500-92a31900-ce3d-11e9-8622-c66ec70d48b9.png)

**Comment by joeyparrish** [comment]
@MenilikBelay, please file an issue using the bug report template: https://github.com/google/shaka-player/issues/new?template=bug_report.md

That will give us enough information to reproduce the issue, diagnose it, and either fix a bug in the player or advise you further on your content preparation.  Thanks!
