### ISSUE TITLE
DRM license request refused with Chrome but not Firefox

### ISSUE THREAD

**Issue by hdodev** [google/shaka-player#2133]
On my environment (Kubuntu), with Shaka 2.5.4:
- I manage to make a Widevine DRM stream works with Firefox 68.
- I didn't manage to make the same Widevine DRM stream works with Chrome 70.

The response of the licencer is:
     HTTP/1.1 200 OK ...
     {"status":"ACCESS_DENIED","supported_tracks":[],"internal_status":127,"client_info":[],"content_owner":"XXX","content_provider":"XXX"}

The "Widevine_DRM_Proxy_Integration 2.18" described the ACCESS_DENIED, but with no detailed description.

What is surprising is the fact that I'm sure it was working about one month ago.
Maybe you have some information or ideas about this? Thanks in advance.

**Comment by TheModMaker** [comment]
I believe Widevine has stopped supporting some older versions of Chrome recently.  You should try with the latest Chrome to see if the error goes away.
