### ISSUE TITLE
Uncaught TypeError in hls_parser onUpdate

### ISSUE THREAD

**Issue by rez** [google/shaka-player#2138]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

Yes

**What version of Shaka Player are you using?**

2.4.7

**Can you reproduce the issue with our latest release version?**

Yes

**Can you reproduce the issue with the latest code from `master`?**

Yes

**Are you using the demo app or your own custom app?**

Custom

**If custom app, can you reproduce the issue using our demo app?**

Yes

**What browser and OS are you using?**

Chrome: 76.0.3809.132, MacOS

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

N/A

**What are the manifest and license server URIs?**

N/A

**What did you do?**

Destroy Shaka Player while it is loading manifest segments.

**What did you expect to happen?**

Not see Javascript errors and the player is released successfully.

**What actually happened?**

A null error occurs in `onUpdate` https://github.com/google/shaka-player/blob/c0e7a9b62a57f73ef26d511e3d40d2dd0f014cb6/lib/hls/hls_parser.js#L2077

There is a check to make sure `playerInterface` is non null but the issue is that there is an await in which the player can be destroyed and become null before the error is passed to it.

To reproduce this error with the demo app: Load the HLS demo, in the network inspector slow connection speed to 3G and while loading segments press play on another demo. It may take a couple of attempts to destroy the player at the right time.

As a side note there was a previous issue about uncaught error AbortableOperation (https://github.com/google/shaka-player/issues/1323). When I unwrap the actual error it is the same error and in versions prior to 2.4.7 the error exist as this.

<img width="1351" alt="Screen Shot 2019-09-06 at 9 52 44 AM" src="https://user-images.githubusercontent.com/198146/64438150-dc069900-d0c7-11e9-8237-d42b5ecea924.png">

**Comment by joeyparrish** [comment]
Cherry-picked to v2.5.9.
