### ISSUE TITLE
Using default UI causes text tracks to display incorrect 'enabled' value

### ISSUE THREAD

**Issue by sanbornhnewyyz** [google/shaka-player#214]
If you are using the default <video> UI and you turn on CC, the current text track will still show as enabled===false. This can be reproduced in the sample app by playing the Angel One content and enabling default controls on the <video> tag. Click the CC button and then call app.player_.getTextTracks(). English subtitles will be showing on the screen but 'enabled' will still be false.

**Comment by joeyparrish** [comment]
Sorry, I can reproduce with the browser's built-in controls.  I missed that part of the report initially.
