### ISSUE TITLE
where to get prebuilt shaka player

### ISSUE THREAD

**Issue by azhar5678** [google/shaka-player#2140]
where can i get prebuilt shaka player and .js file

**Comment by 3bodyZZ** [comment]
here https://cdnjs.com/libraries/shaka-player

**Comment by joeyparrish** [comment]
And also:
https://developers.google.com/speed/libraries/#shaka-player
https://github.com/google/shaka-player#important-links

Does this answer your question?

**Comment by azhar5678** [comment]
OK

**Comment by azhar5678** [comment]
player not playing local manifest.mpd file

with address http://localhosr:8000/manifest.mpd

in myapp.js 
var manifestUri =
    'http://localhosr:8000/manifest.mpd';
here is my manifest.mpd

<?xml version="1.0"?>

<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" minBufferTime="PT1.500S" type="static" mediaPresentationDuration="PT0H28M17.865S" maxSegmentDuration="PT0H0M22.022S" profiles="urn:mpeg:dash:profile:isoff-live:2011,http://dashif.org/guidelines/dash264">
 <ProgramInformation moreInformationURL="http://gpac.io">
  <Title>H:\fileenc1\Union41.dt\manifest.mpd generated by GPAC</Title>
 </ProgramInformation>

 <Period duration="PT0H28M17.865S">
  <AdaptationSet segmentAlignment="true" maxWidth="1920" maxHeight="1080" maxFrameRate="29970/1000" par="16:9" lang="und" startWithSAP="1">
   <SegmentTemplate media="vedio_dash$Number$.m4s" initialization="vedio_dashinit.mp4" timescale="29970" startNumber="1" duration="449550"/>
   <Representation id="1" mimeType="video/mp4" codecs="avc1.42C028" width="1920" height="1080" frameRate="29970/1000" sar="1:1" bandwidth="4199445">
   </Representation>
  </AdaptationSet>
  <AdaptationSet segmentAlignment="true" lang="und" startWithSAP="1">
   <SegmentTemplate media="audio_dash$Number$.m4s" initialization="audio_dashinit.mp4" timescale="48000" startNumber="1" duration="720000"/>
   <Representation id="2" mimeType="audio/mp4" codecs="mp4a.40.2" audioSamplingRate="48000" bandwidth="186718">
    <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
   </Representation>
  </AdaptationSet>
 </Period>
</MPD>

**Comment by TheModMaker** [comment]
You probably misspelled `localhost` in the URL above.  Assuming you typed it correctly in your app, please file a separate issue using the bug template and include extra info like a usable link to the manifest, what browser/OS you are using, and a description of the error.

**Comment by azhar5678** [comment]
it play the file,   'https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd'
ok but not  http://localhost:8000/manifest.mpd

**Comment by joeyparrish** [comment]
@azhar5678, if you need help beyond your original question "where to get prebuilt shaka player", please file a new, complete bug report using the appropriate template.  Thanks!
