### ISSUE TITLE
Has a event to listen which video fragment is playing?

### ISSUE THREAD

**Issue by gzlock** [google/shaka-player#2141]
Look like this [hls.js](https://github.com/video-dev/hls.js/blob/master/docs/API.md#runtime-events) event: 
> Hls.Events.FRAG_CHANGED - fired when fragment matching with current video position is changing
data: { id : demuxer id, frag : fragment object }

But dash.js not supported this event, [this is the issue link](https://github.com/Dash-Industry-Forum/dash.js/issues/1908#issuecomment-372364396): 
> Sorry, there is not such an event type in dash.js.

So, if the shaka-player can support this event both on the hls and mpeg-dash video types, that is awesome.

**Comment by joeyparrish** [comment]
We don't have this event currently.  There is an open feature request #857 to add it, though.  For now, I'll close this as a duplicate of #857.  I suggest you subscribe to that issue to receive updates.
