### ISSUE TITLE
DRM Mixed Segment with Encrypted and Unencrypted Chunks Example

### ISSUE THREAD

**Issue by ggnull35** [google/shaka-player#2142]
Hi Everyone,

I am looking for a mpd archieve with has encrypted and unencrypted chunks on same stream, such like in below issues:

https://github.com/google/shaka-player/issues/775
https://github.com/Dash-Industry-Forum/dash.js/issues/1615

In other saying:
A content having first few segments encrypted followed by few unencrypted segments followed by encrypted segments.

Can anyone help ?

Thank you,

**Comment by TheModMaker** [comment]
If you're looking for anything with both encrypted and clear content, most encrypted content will have that (and all our non-Live sample assets do).  Most VOD encrypted content has a clear lead (usually 10 seconds) where the first few seconds will be clear before switching to encrypted for the rest of the stream.

If you are looking for switching from encrypted to clear, we don't have any sample content on hand.  But you could probably create it fairly easily with multi-Period DASH.

**Comment by joeyparrish** [comment]
The Axinom multi-period content (in the demo app) has certain languages clear in certain periods.  So you can get that transition to/from clear by choosing a certain language.
