### ISSUE TITLE
In Samsung Tizen 2018 TV, Content is not playing. It's in seeking state for infinite time

### ISSUE THREAD

**Issue by Himanshu-kSingh** [google/shaka-player#2149]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
Checked on 2.5.2 and 2.5.5 version

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `master`?**
yes

**Are you using the demo app or your own custom app?**
on Both

**If custom app, can you reproduce the issue using our demo app?**
yes

**What browser and OS are you using?**
Tizen 2018 model TV

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Model Code : UA43NU7470
Software Version : T-KTM2UABC-1270.6, BT - S
Sub-micom Version: T-KTM2INTV - 1005

**What are the manifest and license server URIs?**
https://hssportsprepack.akamaized.net/videos/cricket/savsind2019/07_09_2019/1260010093/eng/V1/master.m3u8?123&hdnea=st=1568812666~exp=1569676666~acl=/*~hmac=a2a12c18183f5f6a945e28326154aad0f2b33ccba1b8a70f96afe0476f412961

Note: This url will valid till 27-sept-2019.

**What did you do?**
Simply hardcode the url in Shaka player, you can check in TV. This is working fine in chrome browser. This issue is only in Samsung Tizen TV.

**What did you expect to happen?**
Content should play normally. Because same content is playing in Shaka Player on the rest of places. 

**What actually happened?**
Firstly we got the play event  then it moved to seeking state for infinite time.

**Comment by pushkardk** [comment]
Facing the same issue here.

**Comment by akmv** [comment]
It seems like my problem https://github.com/google/shaka-player/issues/2154. I did hack, I commented the check `if (msUntilExpiration < 0 ||...` in /lib/media/drm_engine.js about 1344 line. After that video began to play. Or try to change server configuration. Maybe it is helpful for you.

**Comment by Himanshu-kSingh** [comment]
This content is not protected. It's non-drm HLS content.

**Comment by riksagar** [comment]
I've observed that sometimesm while seeking,  Samsung  TVs don't transition from seeking to seeked (at the HTMLMediaElement level).  I assume it's an issue in the bowels of their media playback pipeline.  Workaround (for me atleast) as to reattempt the seek a few hundreds mS later if the seeked event never appears.  It's a hack but ... tizen o_O
