### ISSUE TITLE
Use Blob URL for TTML images

### ISSUE THREAD

**Issue by kumarashu123** [google/shaka-player#2150]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

Yes

**What version of Shaka Player are you using?**

v2.5.5

**Can you reproduce the issue with our latest release version?**

YES

**Can you reproduce the issue with the latest code from `master`?**

YES

**Are you using the demo app or your own custom app?**

Demo and Custom both

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**

Chrome , OS - Window

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What did you do?**

For bit map based subtile , image src data schema is being used.
eg - data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAXAAAABICAYAAADvR65LAAAACXBIWXMAAAsTAAALEwEAmpwYAAANIUlEQVR4nO2d/5GjSA+GNVVfALMh4EyucAIXxDiGCWFiwKnguk

**data: Allows data: URIs to be used as a content source. This is insecure; an attacker can also inject arbitrary data: URIs. Use this sparingly and definitely not for scripts.**

Please go through the link for more details
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/img-src

**What did you expect to happen?**

Remove data schema and use as blob
blob: Allows blob: URIs to be used as a content source.

**What actually happened?**

**Comment by TheModMaker** [comment]
We could switch to using Blob objects instead of a `data:` URI.  But I don't really see how that is any more secure than what we're doing now.  An attacker could also just change the URI to point to their own Blob just like they could change the data URI to point to whatever they wanted.  The idea of that header is to allow/disallow certain domains for sources of images, but any dynamic images would probably be a security risk and there's no way to partially restrict them no matter how they are specified.

For implementers, it would involve changing this: https://github.com/google/shaka-player/blob/9c15e80b7cb621604b8b9617903735b0a62e5036/lib/text/ttml_text_parser.js#L584

**Comment by kumarashu123** [comment]
@TheModMaker In developer.mozilla document They have mention data: as unsecure but for 
blob: they have not mentioned any security related issues

**Comment by joeyparrish** [comment]
@kumarashu123, I think you misunderstand the advice on MDN.  Using data URIs in the way we are does not pose any security risk I can see.  If you can explain the threat model, I'd be happy to reconsider.

If your TTML content contains a base64-encoded image, and we use that as a data URI, then the data is trusted from the point of view of the content owner and streaming service provider.  There's no risk here I can see.  And transitioning that to a blob URI would change nothing of substance.

As such, I'm going to close this issue now, as everything here is working as intended.  Please feel free to reply again if you have specific security concerns that arise from the base64-encoded images in your own content, and we can discuss further.

**Comment by kumarashu123** [comment]
The TTML content need not necessarily come from a trusted source, as there are aggregators as well who source the content from external providers.

More importantly, by enabling data: in CSP **just for subtitles, we are enabling this for all other <img> tags in the application**.

This includes images, for e.g.:
- Posters, Channel Logos
- Ad Posters

These are provided completely by external outsourced vendors, and the application cannot simply trust images from these sources.

Hence the risk still remains.

While we are investigating how using a 'blob:' is more secure than using a 'data:', kindly request you not to close this request and consider incorporating in Shaka.

**Comment by joeyparrish** [comment]
> While we are investigating how using a 'blob:' is more secure than using a 'data:', kindly request you not to close this request and consider incorporating in Shaka.

Until 'blob:' has been shown to be more secure than 'data:', it would not make sense for us to expend significant engineering time in switching to blob.

If your investigations indicate that blob is more secure, I would be happy to reopen the issue and either schedule the work or discuss a PR.

Thanks!
