### ISSUE TITLE
Encrypted video plays only 5 seconds on Tizen OS

### ISSUE THREAD

**Issue by akmv** [google/shaka-player#2154]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
master branch, ver. 2.5

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `master`?**
yes

**Are you using the demo app or your own custom app?**
demo

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
TV with Tizen OS v4 and PC with Ubuntu + Mozilla Firefox

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Samsung TV UE32N5300, firmware T-KTSNDEUC-1270.6

**What are the manifest and license server URIs?** I can provide it.

**What did you do?**

I used Shaka Player on Samsung TV. I installed this example on TV https://shaka-player-demo.appspot.com/docs/api/tutorial-basic-usage.html and tried to play video.

**What did you expect to happen?**
I expected the video to play well.

**What actually happened?**
When I played encrypted by WideVine DRM video on TV, video played only 5 seconds and started from the begining. I did not have that problem on my PC. When I debugged the application, I found that shaka player got incorrect value of msUntilExpiration, eg -10203820. On the PC this value is positive, eg 599236. I found, that  mediaKeys objects are different. Code `const mediaKeys = await mediaKeySystemAccess.createMediaKeys()`. On the PC this object had parameter keySystem: "com.widevine.alpha", but on the TV did not. Objects `session = this.mediaKeys_.createSession();` had different values of expiration on the TV and the PC. On the TV it was NaN, on the PC it was  1569234295000. If I removed the check `if (msUntilExpiration < 0 ||...`, video played well. I had this bug, when I changed the configuration of the server from:
```
"{ "content_id": "3d6c5ee808261ad9c758a93dd0e4726a",
"rules": {
       "allowed_track_types": "SD_HD",
       "sd_only_for_l3": false,
       "policy_overrides": {
         "can_play": true,
         "can_persist": false,
         "can_renew": true,
         "rental_duration_seconds": 1000000,
         "playback_duration_seconds": 1000000,
         "license_duration_seconds": 1000000,
         "renewal_delay_seconds": 1000
       }
     }
}"
```
to 
```
"content_id": "3d6c5ee808261ad9c758a93dd0e4726a",
     "rules": {
       "allowed_track_types": "SD_HD",
       "sd_only_for_l3": false,
       "policy_overrides": {
         "can_play": true,
         "can_persist": false,
         "can_renew": true,
         "rental_duration_seconds": 100000,
         "playback_duration_seconds": 100000,
         "license_duration_seconds": 600,
         "renewal_recovery_duration_seconds": 300,
         "renewal_delay_seconds": 10,
         "renewal_retry_interval_seconds": 60
       },
       "use_policy_overrides_exclusively": true
     }
   }"
```

**Comment by joeyparrish** [comment]
From your description, it looks as if your license is expiring.  Perhaps a 10-second renewal delay is not a good idea.

I'm no Widevine policy expert, but I don't see from the policy you listed why the license would expire so soon.  The license duration of 600 seconds is what I would expect to see take effect here.  Perhaps there is a bug in the Tizen implementation of Widevine, but I can't be certain.

I am certain that you should adjust your license policy, though.  Renewing every 10 seconds is extreme, and unhelpful.

I would advise you to contact Widevine directly if you need assistance with your license policy, as Widevine policy specifics are well outside the responsibilities of this team.

Thanks!
