### ISSUE TITLE
Do you have slack channel?

### ISSUE THREAD

**Issue by vksbansal** [google/shaka-player#2155]
Hi Shaka Team,

I am a admirer of your work and would love to join your slack channel. So, do you have one?

Regards,
Vikas Bansal

**Comment by theodab** [comment]
We don't, sorry.

**Comment by joeyparrish** [comment]
You might be interested in the video-dev slack channel: https://video-dev.slack.com/

It's much more general than Shaka Player, but you will find a good community there.

Does this help?

**Comment by vksbansal** [comment]
thanks @joeyparrish and @theodab for the answer, hope one-day shaka has its own public slack channel.

**Comment by vksbansal** [comment]
@joeyparrish I am not able to join this channel, is it a private channel? or do I need an invite?

**Comment by joeyparrish** [comment]
@vksbansal, I don't know.  I'm not involved in the administration of the group.  But I found this link from a Google search: https://video-dev.herokuapp.com/  Does this help?

**Comment by vksbansal** [comment]
thanks, that helped a lot
