### ISSUE TITLE
HLS Manifest requests shown up in requestFilter as having "undefined" type

### ISSUE THREAD

**Issue by tri170391** [google/shaka-player#2156]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v2.5.5

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Custom app so I can add a request filter

**If custom app, can you reproduce the issue using our demo app?**
How can I add a request filter on the demo app?

**What browser and OS are you using?**
Chrome 76.0.3809.132 on Windows 10

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Not applicable for this issue.

**What are the manifest and license server URIs?**
https://storage.googleapis.com/shaka-demo-assets/bbb-dark-truths-hls/hls.m3u8

**What did you do?**
```
<html>
    <head>
        <script src="https://cdn.jsdelivr.net/npm/shaka-player@2.5.5/dist/shaka-player.compiled.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/mux.js@5.3.0/dist/mux.js"></script>
        <script>
            window.addEventListener("DOMContentLoaded", function() {
                shaka.polyfill.installAll();
                if (shaka.Player.isBrowserSupported()) {
                    var videoElement = document.getElementById('video');
                    var player = new shaka.Player(videoElement);
                    player.getNetworkingEngine().registerRequestFilter(function (type, request) {
                        console.log(type, request.uris);
                    });
                    player.load('https://storage.googleapis.com/shaka-demo-assets/bbb-dark-truths-hls/hls.m3u8');
                }
            });
        </script>
    </head>
    <body>
        <video controls autoplay muted id="video" width="640" height="380"></video>
    </body>
</html>
```

**What did you expect to happen?**
Manifest requests should have type `0`, as logged to console.

**What actually happened?**
Actual test shows they have type `undefined`. Manifest requests property have type `0` when I play a DASH content.

**Comment by theodab** [comment]
It looks like if you load `shaka-player.compiled.debug.js` instead of `shaka-player.compiled.min.js`, it works as expected. So this looks like it might be a problem with how we are compiling.

> How can I add a request filter on the demo app?
There's no good way at the moment; the demo resets the filters every time it loads an asset, so adding one manually via the developer console is a no-go. I tried this out by modifying the code of the demo page, though, and it reports the correct type.

**Comment by CHaNGeTe** [comment]
This issue is happening to me as well.
Always getting type undefined for HLS.
As loading the `debug` version is not an option. Is there any workaround for this?
Or in which version the bug was introduced?

**Comment by ismena** [comment]
@CHaNGeTe Does it still happen for you in the latest master?

(e g, if you try your content on our [nightly demo page here](https://nightly-dot-shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd;panel=CUSTOM%20CONTENT;build=uncompiled): use the "+" button to try your manifest), are you still seeing the bug?

**Comment by TheModMaker** [comment]
This should be fixed on `master` and will appear in v2.5.6 once I release it either today or later this week.

**Comment by CHaNGeTe** [comment]
@ismena is there any quick way to install nightlies via npm?

**Comment by CHaNGeTe** [comment]
Thank you! it works on 2.5.6

**Comment by joeyparrish** [comment]
Sorry, we only ship release builds (including betas) to npm, but not the nightly build.  But I'm glad the new release is working for you!
