### ISSUE TITLE
Configuring UI in NodeJS with ReactJS

### ISSUE THREAD

**Issue by amit08255** [google/shaka-player#2159]
Cannot configure UI in NodeJS app with ReactJS. Cannot find UI classes. I want to add quality change button.

```js
import React from 'react';

import shaka from 'shaka-player';

class Tutorial extends React.PureComponent{

    constructor(props){

        super(props);

        this.video = React.createRef();
    }

    componentDidMount(){

        var manifestUri = 'https://storage.googleapis.com/shaka-demo-assets/sintel-widevine/dash.mpd';
        var licenseServer = 'https://cwip-shaka-proxy.appspot.com/no_auth';
        
        let video = this.video.current;

        var player = new shaka.Player(video);

        player.configure({
            drm: {
              servers: { 'com.widevine.alpha': licenseServer }
            }
          });


        const onError = (error) => {
            // Log the error.
            console.error('Error code', error.code, 'object', error);
        }

        player.load(manifestUri).then(function() {
            // This runs if the asynchronous load is successful.
            console.log('The video has now been loaded!');
          }).catch(onError);  // onError is executed if the asynchronous load fails.
    }

    render(){

        return(
            <video id="video" ref={this.video}
            width="640"
            poster="//shaka-player-demo.appspot.com/assets/poster.jpg"
            controls autoplay></video>
        );

    }
}

export default Tutorial;
```

**Comment by amit08255** [comment]
Worst documentation I ever found. Cannot understand a single implementation its just confusing.

**Comment by joeyparrish** [comment]
@amit08255, I'm a little confused about what you're trying to accomplish.  I see code that resembles the "Basic Usage" tutorial for the non-UI build of Shaka Player.  (eg, `player = new shaka.Player(video);`)  Have you seen our UI-specific tutorial?  https://shaka-player-demo.appspot.com/docs/api/tutorial-ui.html

Because the Shaka Player UI is an optional component, you need to opt-in by loading the correct build, and you need to add the correct data attributes to the video element.  Instead of constructing the `Player` object, you get a reference to it from the video element.  You'll find all of this in the tutorial.

Though the library is designed to auto-setup the UI based on a scan of the DOM, you can also create the components explicitly after the DOM is set up if needed.  (I am not familiar with ReactJS, so I'm guessing you might need this.)  This is not mentioned in the tutorial, but you could use this API instead of the declarative setup:

```js
  // Here "videoContainer" is a simple div that wraps the video element.
  // Add this to your HTML, and make sure you drop the "controls" attribute from video.
  // UI controls will be created inside videoContainer and overlay video.
  player = new shaka.Player(video);
  ui = new shaka.ui.Overlay(player, videoContainer, video);
  controls = ui.getControls();
```

We aren't experts in ReactJS, so you'd be on your own to determine how best to fit this into the ReactJS paradigm.

Does this help?

**Comment by amit08255** [comment]
Hello Joey,
Thank you for your quick response.
I am working on a project in ReactJS, for which I need to implement saka player. I have been looking around the docs and tutorials, but couldn't find the exact solution which to help me configure saka player with UI configuration.
The NPM page doesn't explain how to configure it in NodeJS and also there is no information in README or in docs.
After spending all day, and experimenting for several hours, I found the solution (which was taken from different issues).
Finally, its working. Thank you for your help.

Can I please request you to add a docs or tutorial for NodeJS users, so that it could help them? 
I will love to help with this. I love shaka player, but I think its NodeJS implementation need to be documented for newbies like me.

**Comment by joeyparrish** [comment]
Shaka Player isn't meant to run in NodeJS at all.  It runs in a browser, because it depends heavily on things provided by browsers and not by NodeJS (HTML5 video, MediaSource, EME, etc.)

**Comment by amit08255** [comment]
Yes I agree. I was using shaka player in ReactJS and yes it was used to be executed on client-side. I mistakenly tried to execute it on server side which didn't work.
I learnt a lot about shaka player today. I was just requesting to add docs or tutorials for implementing Shaka player for frameworks like ReactJS since there isn't much solution available (especially with things like UI configuration).

**Comment by joeyparrish** [comment]
I filed #2163 to track the creation of a tutorial for Shaka+ReactJS.  Note that my team has no experience with ReactJS, and docs concerning other frameworks have never been in scope of this project.  So I can't promise when we will work on this.

In the mean time, I highly recommend you spend time with the docs for ReactJS and the docs for Shaka Player itself.  If you can understand how to use the APIs of both projects, then you should be able to fill in the gap between the two.

Thanks!

**Comment by amit08255** [comment]
Thanks. Sure, I will work on this so that it can help other beginners.

**Comment by amit08255** [comment]
https://github.com/amit08255/shaka-player-react-with-ui-config
This is still work under progress. 
It explains how to configure shaka player for ReactJS using simple projects. 
It also explains basic UI configuration of shaka player with ReactJS.
