### ISSUE TITLE
The first chunk is not played - DASH stream

### ISSUE THREAD

**Issue by sproutdebisa** [google/shaka-player#2166]
Hey guys,
Raw key encrypted DASH stream packaged using [shaka-packager](https://google.github.io/shaka-packager) is jumping the first chunk. In the console got this `Jumping forward 10.977633 seconds because of gap before start time of 10.977633`.
Help me out.
check it [here](https://sproutdebisa.github.io/dash-test/)
this is the [error](https://conformance.dashif.org/conformance/current/Conformance-Frontend/temp/id5296893480/Period0/Adapt0rep0log.html) i get when trying to [validate](https://conformance.dashif.org/) the manifest file

```php
# shaka-packager command used to generate the stream
[
  0 => "/usr/bin/packager"
  1 => "in=test-video.mp4,drm_label=AUDIO,stream=audio,init_segment=audio_1.m4s,segment_template=audio_$Number$.m4s"
  2 => "in=test-video.mp4,drm_label=SD,stream=video,init_segment=sd_1.m4s,segment_template=sd_$Number$.m4s"
  3 => "--enable_raw_key_encryption"
  4 => "--keys"
  5 => "label=AUDIO:key_id=f3c5e0361e6654b28f8049c778b23946:key=a4631a153a443df9eed0593043db7519,label=SD:key_id=abba271e8bcf552bbd2e86a434a9a5d9:key=69eaa802a6763af979e8d1940fb88392,label=HD:key_id=6d76f25cb17f5e16b8eaef6bbf582d8e:key=cb541084c99731aef4fff74500c12ead,label=FHD:key_id=6d76f25cb17f5e16b8eaef6bbf582d8e:key=cb541084c99731aef4fff74500c12ead,label=QHD:key_id=6d76f25cb17f5e16b8eaef6bbf582d8e:key=cb541084c99731aef4fff74500c12ead"
  6 => "--generate_static_mpd"
  7 => "--base_urls"
  8 => "http://localhost:8000/1/"
  9 => "--mpd_output"
  10 => "dash_stream.mpd"
]
```

manifest [here](http://sproutdebisa.github.io/dash-test/dash_stream.mpd)

thanks

**Comment by sproutdebisa** [comment]
@joeyparrish please help me

**Comment by joeyparrish** [comment]
Hi @thema-d.  I assume you figured this out, but there's no connection between raw-key encryption and seeking on start.  We seek over gaps in the content, so if your content starts at 0, we won't do that.  You can also disable gap-jumping in the configuration.  Hope that helps!

**Comment by thema-d** [comment]
Yeah, the reason it skipped the first chunk was because of the overlapping between the init segment and the first segment names (my fault). @joeyparrish thanks a lot. I see you are dedicated to helping others.
