### ISSUE TITLE
Add new test for offline storage without manifest init data

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#2168]
PR #2164 introduces support for offline storage of encrypted content without init data in the manifest.  We need a new test case to cover this.

**Comment by TheModMaker** [comment]
Be sure to include tests for multiple key systems.

**Comment by avelad** [comment]
@theodab after https://github.com/google/shaka-player/commit/db8ad31bfbe1c2b9a372daad893d900e77d5e484 this can be closed?

**Comment by joeyparrish** [comment]
Thank you for catching this!  Yes, I think it can be closed.
