### ISSUE TITLE
is it possible to prevent screen recording of widevine DRM protected stream?

### ISSUE THREAD

**Issue by vksbansal** [google/shaka-player#2170]
Hi Team,

Sorry to bother you, I am trying to find a way to prevent videos protected by Widevine to be stolen by screen recorders, is it possible?

Thanks
Vikas Bansal

**Comment by joeyparrish** [comment]
Hi Vikas,

That would be a question for the Widevine team.  That is outside of the scope of what a JavaScript application can control.  From JavaScript, we wouldn't even have a way to determine if screen recording is allowed by the system or not.

Sorry we couldn't help with that!  Please visit https://www.widevine.com/contact to reach out to Widevine.

**Comment by vksbansal** [comment]
thanks @joeyparrish
