### ISSUE TITLE
Error on initPlayer if protocol http is UPPERCASe

### ISSUE THREAD

**Issue by backslash451** [google/shaka-player#2173]
It may seems weird but I have tested many times. If you init the player using the load function using a manifest URI with the http protocol uppercase it won't work. Just use the 'http' lowercase and it will work like magic...

this is the code:

this.player_ = new shaka.Player(this.video_);
this.player_
    .load(manifestUri)
.....

**Comment by joeyparrish** [comment]
The URL scheme is spec'd to be case insensitive according to https://tools.ietf.org/html/rfc3986#section-3.1

So this is a bug on us.  When we look up a scheme in our scheme-to-plugin map, we should convert it to lowercase.  Thanks for reporting this!
