### ISSUE TITLE
Make bottom control opaque

### ISSUE THREAD

**Issue by thema-d** [google/shaka-player#2176]
Hello guys,
I am customizing shaka UI and I want the bottom controls to be opaque (be visible) all the time. 
Is there a way to do that?

thanks

**Comment by matvp91** [comment]
Add `opacity: 1` to the `.shaka-controls-container` class and make sure it takes precedence over the css definition that ships with shaka ui.

**Comment by thema-d** [comment]
Yeah thanks a lot @matvp91

**Comment by joeyparrish** [comment]
Thanks, @matvp91, that's correct.  We intend for you to replace or override the CSS for cases like this.

@thema-d, does this answer your question?  May we close the issue?

**Comment by thema-d** [comment]
Yes, closing it now.
