### ISSUE TITLE
Dash audio track name support

### ISSUE THREAD

**Issue by zuzzurro** [google/shaka-player#2178]
**Purpose**

Allow "Label" to be passed into the DASH manifest AdaptationSet. This will allow human readable labels for things like caption tracks and audio tracks.

See DASH IOP 4.3 here https://dashif.org/docs/DASH-IF-IOP-v4.3.pdf (page 35)

Sample manifest: https://s3-us-west-1.amazonaws.com/sev-a-g/ed.mpd

This functionality has been implemented in dash.js in February 2019. Can Shaka adopt it too?

https://github.com/Dash-Industry-Forum/dash.js/pull/2929

**Comment by TheModMaker** [comment]
I believe we support this already, the Track structure has a `label` field for this.  You can see this from `player.getVariantTracks()` or `player.getTextTracks()`.  Also, that manifest link doesn't work, so I can't test to see if I'm correct.

**Comment by zuzzurro** [comment]
That's interesting news, thanks. However I just tried one video that has audio tracks with Labels but they don't surface in the test harness. I imagine the shaka player has the support but it is not exposed yet in the demo player?

**Comment by TheModMaker** [comment]
Can you provide a working manifest URL to test with?

**Comment by zuzzurro** [comment]
So we have checked the code, and it seems to us from the comment in there (and the fact that it doesn't work) that the "label" implementation is specific to Kaltura and it does not correspond to the standard I mentioned previously "See DASH IOP 4.3 here https://dashif.org/docs/DASH-IF-IOP-v4.3.pdf (page 35)".
We will provide more details and a video for testing tomorrow. Regards

**Comment by zuzzurro** [comment]
Actually, this demo file from AMS seems to contain the Label tags (as they added support for it some months ago).

https://amssamples.streaming.mediaservices.windows.net/f1ee994f-fcb8-455f-a15d-07f6f2081a60/Sintel_MultiAudio.ism/manifest(format=mpd-time-csf)

**Comment by TheModMaker** [comment]
Ok, it looks like our label handling comes from an attribute on the `AdaptationSet`, while this is an element in the `AdaptationSet`.  We can look into adding this, maybe through the same Track field.

**Comment by zuzzurro** [comment]
Thanks very very much for this. We tested and it works as you probably intended. Unfortunately it only fix one half of our problem but we are going to create another issue for that with the full disclosure of our use case.
