### ISSUE TITLE
Any plans to support SVT-AV1 

### ISSUE THREAD

**Issue by ksuhiyp** [google/shaka-player#2181]
Not related to a problem

https://medium.com/@ewoutterhoeven/av1-is-ready-for-prime-time-svt-av1-beats-x265-and-libvpx-in-quality-bitrate-and-speed-31c1960703db

**Comment by TheModMaker** [comment]
We don't handle codecs, all we do is pass the data to the browser.  So if the browser supports it, we should too.  It also looks like that is an encoding scheme that is compatible with AV1, so it seems like this is more about the encoder creating the content.  Did you mean to file this for [Shaka Streamer](https://github.com/google/shaka-streamer/)?

**Comment by ksuhiyp** [comment]
>  Did you mean to file this for Shaka Streamer?
No
