### ISSUE TITLE
TTML Subtitles not working without the UI Library

### ISSUE THREAD

**Issue by damjtoh** [google/shaka-player#2182]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.5

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Custom app.

**If custom app, can you reproduce the issue using our demo app?**
No, but I tried building a custom app with the UI library and it works as expected.

**What browser and OS are you using?**
Ubuntu, Chrome v77

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What did you do?**

I followed the basic usage tutorial. But we are not looking to use the UI Library.

**What did you expect to happen?**
TTML subtitles to work without the UI Library.

**What actually happened?**

The subtitles doesn't show up instead it shows a little black box as showed in the image.
![New Project (4)](https://user-images.githubusercontent.com/4992074/66587911-c28ebc00-eb61-11e9-9374-29cb56a4bfda.png)

**Comment by avelad** [comment]
Are you using SMPTE-TT or image format?

**Comment by damjtoh** [comment]
Hey @avelad, sorry for the late response, we are using image format.

**Comment by joeyparrish** [comment]
If you're using images in your subtitles, the browser's native text display can't support that.

**Comment by joeyparrish** [comment]
If you'd like to use images in your subtitles without using the UI library, you can create your own implementation of the TextDisplayer interface.  You can use our two implementations as examples, or you can fork the one from the UI and integrate it into your application without the rest of the UI library.

**Comment by damjtoh** [comment]
I forked the UI textDisplayer class and it worked like a charm! Thanks for the quick response.

**Comment by joeyparrish** [comment]
Happy to help!
