### ISSUE TITLE
Error when destroying an in-progress store operation

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#2183]
I've been looking at the API but I don't see a clear way to abort a download that is in progress.

Any idea how it should be done?

**Comment by TheModMaker** [comment]
You can call `storage.destroy()` to destroy the object.  This will cancel the in-progress store and delete any partially-stored content.

**Comment by avelad** [comment]
I tried it today and I think it doesn't work as I would expect. This cancels and removes the asset, but forces the user to download it whole, does not cancel the segment download operations.

**Comment by joeyparrish** [comment]
What version of Shaka Player are you using?  Have you tried with v2.5.5 or the latest in `master`?

**Comment by avelad** [comment]
I'm tested with 2.5.5 and with the latest master i have the next error: `{"severity":2,"category":6,"code":6002,"data":["b.Ec.a is not a function"],"handled":false}`

**Comment by joeyparrish** [comment]
Thanks!  That's an interesting error.

[6002](https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html#value:6002) is `FAILED_TO_CREATE_CDM`, which is meant to indicate an error from the browser, but the specific `"b.Ec.a is not a function"` indicates what may be a compiler-related issue, such as a problem with minification.

Can you try with the latest code from `master` and see if it's reproducible there?

**Comment by TheModMaker** [comment]
I was unable to reproduce anything.  Could you try again from `master` and try with the Debug compiled version (to maybe get a function name or stack trace).  Could you create a sample page that reproduces this?
