### ISSUE TITLE
Store TS stream in rolling buffer

### ISSUE THREAD

**Issue by johneakin** [google/shaka-player#2184]
Hi,
I want to store a TS stream in a 60 second rolling buffer. Is this possible with Shaka?

Reason being I want to continually OCR the video and if text is detected then I want to upload the 60second clip to a website.

**Comment by joeyparrish** [comment]
Sorry, I think Shaka Player might be the wrong tool for that.  We fetch media and feed it to the browser for demux & decode.  We don't store or buffer anything in the way you're describing.

The MediaSource API is not very hard to use, though.  You might consider building directly on the browser's APIs for this.

Does this help?
