### ISSUE TITLE
Dynamically determining whether to load an HLS or DASH manifest

### ISSUE THREAD

**Issue by chenein** [google/shaka-player#2185]
I am looking to stream m4a audio on demand on both desktop and iOS browsers using shaka player. I have generated two manifests (mpd and master m3u8) for each stream, however I cannot figure out how to select between them when loading shaka.

Is there a probe I can use at runtime to determine which manifest shaka will play on the user's current browser? Or is it the case that I should just try to load the mpd, and if that fails then try to load the m3u8?

For example, is there a simple javascript test of the form:

if (player.PROBE) {
     var manifest = "manifest.mpd";
} else {
    var manifest = "manifest.master.m3u8";
}
player.load(manifest);

**Comment by theodab** [comment]
Internally, we have a "platform" utility that determines if MediaSource can be used, via the call `shaka.util.Platform.supportsMediaSource()`.
This could be used to identify if you're on a platform that has to use src= playback, like iOS browser.
Unfortunately, that utility is not exported, and thus is not available in the compiled output. It'd be simple enough to export it, though, if that would be useful.

**Comment by joeyparrish** [comment]
The probe method you're looking for is `[shaka.Player.probeSupport()](https://shaka-player-demo.appspot.com/docs/api/shaka.Player.html#.probeSupport)`:

```js
const support = await shaka.Player.probeSupport();
if (support.manifest.mpd) {
  url = 'foo.mpd';
} else {
  url = 'foo.m3u8';
}
```

You can see the full output of probeSupport for a given device by loading this page: https://shaka-player-demo.appspot.com/support.html

But you can also do a simple fallback if the MPD fails to load:

```js
try {
  await player.load('foo.mpd');
} catch (e) {
  await player.load('foo.m3u8');
}
```

Does this help?

**Comment by chenein** [comment]
Yes, thank you this is helpful.
