### ISSUE TITLE
Error 4001 for 1h+ DASH videos on Xbox One

### ISSUE THREAD

**Issue by arturparkhisenko** [google/shaka-player#2186]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
V2.5.5 Compiled (Release)

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Custom app

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
N/A

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Xbox One, OS v.10.0.18363.7194 October 2019

**What are the manifest and license server URIs?**

N/A, but any DASH manifest which is big enough (1K+ lines) will work

**What did you do?**

I tried to play the video with a duration of over 1h on the Xbox One. In our case, our manifests include `SegmentTimeline` tag.

**What did you expect to happen?**
The video will start playback.

**What actually happened?**

Player throws an error when we try to play the video: 
```
Can not load manifest: shaka.util.Error { "severity": 2, "category": 4, "code": 4001, "data": [ "https://example-site.com/master.mpd" ], "handled": false }
```
Which is `DASH_INVALID_XML, 4001, The DASH Manifest contained invalid XML markup`.

It works well on `v2.5.2` and it does not on `v2.5.3`.
We looked deeper and found that it’s playing fine if we change string utility `fromCharCode` back to the implementation of what it was in `v2.5.2`.
Also, we found that this issue is only reproducible with Compiled (Release) code, it’s playing fine in the Compiled (Debug) and Uncompiled modes.

**Comment by joeyparrish** [comment]
Thanks for the report, and especially for digging into the various versions and builds.  We'll take a look.

**Comment by arturparkhisenko** [comment]
@joeyparrish anything we can do to help with triage?

**Comment by TheModMaker** [comment]
I can reproduce this with the latest version and with `master`.  Be sure to use the compiled version and use the following manifest URL (note that it won't play since the segments are incorrect, but you should get the 4001 error on Xbox One):

https://storage.googleapis.com/wvtemp/modmaker/long-segment-timeline.mpd

**Comment by arturparkhisenko** [comment]
Looks like the closure compiler version update and milestone 2.6 is far, I wanted to find a better solution earlier, and found that:
Looks like the issue is in the spread operator polyfill, spread operators were introduced in [v2.5.3](https://github.com/google/shaka-player/commit/7bbca076aabdd22b7b5766ac7f63b7cce5c72bed#diff-9af04d25db78e2368865abc0e60a4d2dR229) with a change to the`shaka.util.StringUtils.fromCharCodeImpl_`.

So I decided to find a replacement, there are actually two approaches (there's two places where we need to replace the spread operator), examples:
- es6: `const foo = String.fromCharCode['apply'](null, Array.from(buffer));` (no polyfill was applied)
- es5: `const foo = String.fromCharCode['apply'](null, [].slice.call(buffer));`

Tested on:
- The latest version and `master`
- The same device but new firmware: Xbox One, OS v.10.0.18363.8131 November 2019

**Comment by arturparkhisenko** [comment]
@joeyparrish Thanks! Any estimations when it will be released? 🚀

**Comment by joeyparrish** [comment]
I'll make the arbitrary decision to start assembling the v2.5.9 release on Monday Feb 3.  :-)  It isn't always completed in the same day, but you can expect it some time next week.

**Comment by joeyparrish** [comment]
Cherry-picked to v2.5.9.
