### ISSUE TITLE
Non-shaka error caught in streaming_engine when loading HLS manifest in the presence of mux.js

### ISSUE THREAD

**Issue by chenein** [google/shaka-player#2187]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.5

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Unknown - I am using the google hosted very

**Are you using the demo app or your own custom app?**
Custom

**If custom app, can you reproduce the issue using our demo app?**
N/A - depends on my manifest

**What browser and OS are you using?**
Safari and Firefox on Mac OS X 10.13.6

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**

Manifest:
https://cod.ckcufm.com/cgi-bin/stream-server?broadcast_id=45185&program_id=31&streamtype=hlsmaster

Player as embedded:
https://cod.ckcufm.com/programs/ondemand-player.html?id=31356&token=O}6]sg\2(wUsgXPIcT7%2600%2C6UztHNm\HE`1msAt~b%2Bm'0sJp~u

License server: N/A

**What did you do?**
Playback of an HLS playlist in the presence of mux.js 5.5.1

**What did you expect to happen?**
Audio!

**What actually happened?**
Audio player loaded media but failed to start playing, with errors in the console that I was not able to figure out even in debug mode (see image). The error appears to be a non-Shaka error that Shaka is not happy to catch at this point in the code.

<img width="1246" alt="Screen Shot 2019-10-14 at 17 11 30" src="https://user-images.githubusercontent.com/16447128/66783460-ee81a880-eea5-11e9-8ce9-69e4da1ddce5.png">

Note that if I remove the mux.js library from the head element, then as expected Shaka generates error code 4032 for this HLS stream. I am not an expert in deploying js projects, so it is possible that I have got something wrong with my mux.js build. However, I can't tell what this is because Shaka is eating the error.

**Comment by joeyparrish** [comment]
Thank you for the report!  We will try to reproduce the issue with the manifest URL you included.

**Comment by TheModMaker** [comment]
It looks like the check for captions isn't valid and we try to append embedded captions for the stream.  Since there isn't any video stream, we can't find its `timestampOffset`.  [This](https://github.com/google/shaka-player/blob/6ab4e68ff2170a9eea65ccfb820f69eb47d4a179/lib/media/media_source_engine.js#L488) is the culprit line, caused by the if statement checking for truthy values instead of checking for a non-empty list.
