### ISSUE TITLE
Failed to display the SMPTE-TT bit map subtitles intermittently during the playback. 

### ISSUE THREAD

**Issue by yvashar** [google/shaka-player#2188]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** - Yes

**What version of Shaka Player are you using?** - ^2.5.0

**Can you reproduce the issue with our latest release version?** - yes

**Can you reproduce the issue with the latest code from `master`?** - yes

**Are you using the demo app or your own custom app?** - our own custom app

**If custom app, can you reproduce the issue using our demo app?** - yes

**What browser and OS are you using?** - Chrome

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?** NA

**What are the manifest and license server URIs?**
https://live.v2p.bgl.ytv.io/live-livecleardaf/1004/second-screen.mpd

**What did you do?**
When we play a linear stream, we could see some subtitles being skipped and continue to display the subsequent subtitles after some time.

**What did you expect to happen?**
Player should be able to render the subtitles without skipping them. 

**What actually happened?**
We are enabling the shaka's TextDisplayer to display the bitmap based subtitles where we found some subtitles being skipped during the playback. After inspecting the shaka's code base we understood that the player is able to decode the base64 image format at the right time when the corresponding subtitle has to displayed but it failed to render in the DOM and it renders the subsequent subtitles after a delay.

From the code, we could see the captionsStyle.backgroundImage of setCaptionStyles_() having the current bitmap subtitle images but the "span" element of the "shaka-text-container"  is empty at that time.

**Comment by joeyparrish** [comment]
> From the code, we could see the captionsStyle.backgroundImage of setCaptionStyles_() having the current bitmap subtitle images but the "span" element of the "shaka-text-container" is empty at that time.

Ah, very interesting.  This could be the culprit.

However, you neglected to provide a manifest URL that we could use to reproduce the issue.

Here's the template once more, with the comment in it visible:

> **What are the manifest and license server URIs?**
> NOTE:
>   You can send the URIs to <shaka-player-issues@google.com> instead,
>   but please use GitHub and the template for the rest.
>   A copy of the manifest text or an attached manifest will **not** be
>   enough to reproduce your issue, and we **will** ask you to send a
>   URI instead.  You can copy the URI of the demo app to send us the
>   exact asset, licence server, and settings you have selected there.

Thanks!

**Comment by yvashar** [comment]
Hi, Please find the below manifest url (added it also in the comment section) for further investigation
https://live.v2p.bgl.ytv.io/live-livecleardaf/1004/second-screen.mpd

I would like to add one more observation regarding this issue that it is observed only in Chrome but not in FireFox.

**Comment by yvashar** [comment]
@joeyparrish  please find the manifest url mentioned above where the subtitle missing issue is reproducible

**Comment by ismena** [comment]
@yvashar 
Sorry, Joey's on vacation and the issue escaped our attention.
Let me get the local subtitle expert to take a look! @michellezhuogg

**Comment by yvashar** [comment]
@michellezhuogg is there any update on this issue?

**Comment by joeyparrish** [comment]
@yvashar, sorry this has gone unanswered for so long.  Is this still an issue for you?  If so, can you please send us an updated manifest URL for testing purposes?  The one you sent before is currently giving us a 404 error.
