### ISSUE TITLE
Support PlayReady on videofutur box

### ISSUE THREAD

**Issue by fadomire** [google/shaka-player#2189]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.5

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
demo app

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
chromium 55 custom build on a videofutur box (based on linux)

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What did you do?**

it is reproducable only on a box that is not yet out on the market

**What did you expect to happen?**
no error is thrown

**What actually happened?**

Basicly, in drm_engine.js line 1289, there is a condition for playready drm and specific bug on Edge with key IDs as little-endian UUIDs. This condition also check shaka.util.Platform.isTizen() and if true dont execute the code following
In our case, with this box, we are in the same case as Tizen, it should not try to transform little-endian into big-endian. 
When it does, we then have an error 4012 RESTRICTIONS_CANNOT_BE_MET
But this error should not be thrown as the content is playing correctly.

**Comment by joeyparrish** [comment]
> **What did you do?**
> it is reproducable only on a box that is not yet out on the market

> Basicly, in drm_engine.js line 1289, there is a condition for playready drm and specific bug on Edge with key IDs as little-endian UUIDs. This condition also check shaka.util.Platform.isTizen() and if true dont execute the code following

If this is the case, and it's a device that we can't use to debug or reproduce the issue, you will have to contribute a PR yourself to fix this.  There would be no way for us to develop and test a fix for you.

You could add a new detection routine in `shaka.util.Platform` and use it in `DrmEngine` to skip the byte-swap for the key IDs.

**Comment by fadomire** [comment]
Thanks, i'll try to think of a good PR
but maybe the condition in drm_engine.js line 1289 should just check for ```keySystem``` is playready ```byteLength``` is 16 and ```Platform``` isEdge ?

**Comment by joeyparrish** [comment]
Sounds good to me.  Let's try it.  I'll be happy to review a PR for that.

**Comment by joeyparrish** [comment]
@fadomire, @LanaIV, can this issue be closed now?  Are there other support issues beyond the one fixed in #2368?

**Comment by fadomire** [comment]
it can definitly be closed
i thought it would be automaticaly after merge
Thanks !
