### ISSUE TITLE
Grouped adaptation sets with the same default_KID are ignored

### ISSUE THREAD

**Issue by sanbornhnewyyz** [google/shaka-player#219]
As per the discussion on #67:

>We are using cenc:default_KID but this has the same value for each of the Adaptation Sets within the >same group and it seems that Shaka then ends up ignoring the adaptation sets with the higher >bandwidths onkeystatuseschanged.

You can use this manifest to to reproduce the issue: https://www.dropbox.com/s/vhct6tunwe3z1vu/groupedAdaptation.mpd?dl=0

**Comment by joeyparrish** [comment]
@sanbornhnewyyz I have the manifest, but I'm unable to access the actual segments, and I don't think I can reproduce without them.  Can you send me enough data to reproduce?

**Comment by joeyparrish** [comment]
Never mind, I think I can do this without the content, actually.

Just looking at the output of the manifest parser/processor, I see that every StreamInfo has the same key ID, "41133709B21548B794EB000A2BF8A817", which matches what's in the manifest's default_KID.  So the default_KID seems to have nothing to do with it.

I do, however, see some StreamInfos which are disabled:

```
app.player_.videoSource_.manifestInfo.periodInfos[0].streamSetInfos[2].streamInfos.map(function(s) { return JSON.stringify({allowed: s.allowedByKeySystem, id: s.id, width: s.width, height: s.height}); });
```

[
  {"allowed":true,"id":"video=77000","width":256,"height":144},
  {"allowed":true,"id":"video=137000","width":288,"height":160},
  **{"allowed":false,"id":"video=217000","width":320,"height":176},**
  **{"allowed":false,"id":"video=317000","width":360,"height":208},**
  {"allowed":true,"id":"video=505000","width":640,"height":360},
  {"allowed":true,"id":"video=705000","width":640,"height":360},
  {"allowed":true,"id":"video=1194000","width":848,"height":480},
  {"allowed":true,"id":"video=1790000","width":1280,"height":720},
  {"allowed":true,"id":"video=2190000","width":1280,"height":720},
  {"allowed":true,"id":"video=2590000","width":1280,"height":720}
]

If I fake a key status event:

```
shaka.log.setLevel(shaka.log.Level.V1);
app.player_.videoSource_.onKeyStatusesChange({'41133709B21548B794EB000A2BF8A817': 'usable'});
```

I get these logs:

```
Permitting stream video=217000. 
Permitting stream video=317000. 
```

And now everything seems to be enabled:

[
  {"allowed":true,"id":"video=77000","width":256,"height":144},
  {"allowed":true,"id":"video=137000","width":288,"height":160},
  **{"allowed":true,"id":"video=217000","width":320,"height":176},**
  **{"allowed":true,"id":"video=317000","width":360,"height":208},**
  {"allowed":true,"id":"video=505000","width":640,"height":360},
  {"allowed":true,"id":"video=705000","width":640,"height":360},
  {"allowed":true,"id":"video=1194000","width":848,"height":480},
  {"allowed":true,"id":"video=1790000","width":1280,"height":720},
  {"allowed":true,"id":"video=2190000","width":1280,"height":720},
  {"allowed":true,"id":"video=2590000","width":1280,"height":720}"
]

The only way I can see that my test scenario here is unrealistic is that I'm faking the keystatuses event.  If the actual key status event had a different key ID, that would definitely explain the behavior you're reporting.  However, that would also imply that your manifest has a different key ID than your license.

Perhaps the manifest is wrong?  Or perhaps there's an issue with your license server that is causing it to return a different key ID than expected?

In any case, the actual logic to enable streams by key ID appears to be working correctly.  I'll mark this as 'unable to reproduce' for now, but leave it open until you have a chance to get back to us.

**Comment by sanbornhnewyyz** [comment]
@joeyparrish Thanks for taking the time to work through this and provide detailed information. I'll go back to the drawing board and see what is going on our end that is causing this.

**Comment by joeyparrish** [comment]
@sanbornhnewyyz Were you able to find a bug on your end?
