### ISSUE TITLE
Couldn't get initDataTransform working for Fairplay

### ISSUE THREAD

**Issue by jpiechowiak** [google/shaka-player#2190]
Hi,

I'try to use FairPlay in Shaka, and right now I'm not able to get it working when it comes to initDataTransform method.
I've following piece of code (only interesting part): 
```javascript
player.configure('drm.initDataTransform', (initData) => {
    const processedData = String.fromCharCode.apply(null, new Uint16Array(initData.buffer)).substring(1);
    const contentId = new URL(processedData.substring(1)).hostname;
    const cert = player.drmInfo().serverCertificate;
    serverProcessSPCPath = processedData.substring(1).replace('skd://', 'https://');
    return shaka.util.FairPlayUtils.initDataTransform(initData, contentId, cert);
});

player.configure({
    drm: {
        servers: {
            'com.apple.fps.1_0': licenseServerUrl
        },
        advanced: {
            'com.apple.fps.1_0': {
                serverCertificate: new Uint8Array(cert),
            },
        },
    },

});
```
When I try to play something then I'm receiving error 6015. Actually I'm able to assign result of this method to variable and see, the result but in general Shaka throws error which points to this method. I've also investigated values from all variables and everything looks just fine.

Any suggestions, what might be wrong?

**Comment by jpiechowiak** [comment]
I've already got this part in other place in my code. 
Here is the whole code, I've only erased URLs and sensitive data (I can send full, uncensored version via email/PM):
```javascript
import * as shaka from 'shaka-player';

let customData = null;
let serverProcessSPCPath = null;
const initializeShaka = () => {
    shaka.polyfill.installAll();

    if (shaka.Player.isBrowserSupported()) {
        const player = new shaka.Player();
        player.getNetworkingEngine().registerRequestFilter((type, request) => {
            if (type == shaka.net.NetworkingEngine.RequestType.LICENSE) {
                request.headers['DrmChallengeCustomData'] = customData;
                request.url = serverProcessSPCPath;
            }
        });
        window.player = player;
        player.addEventListener('error', shakaOnErrorEvent);
    } else {
        alert('Browser not supported!');
    }
};

const shakaOnErrorEvent = (event) => {
    shakaOnError(event.detail);
};

const shakaOnError = (error) => {
    alert(error);
    
    console.error('Error code', error.code, 'object', error);
    if (window.player) {
        window.player.detach();
    }
};

const play = async () => {
    const url = 'my_url';
    const licenseServerUrl = 'license_server_url';
    customData = 'my_custom_data';
    
    const response = await fetch('url_to_certificate');
    if (!response.ok) {
        alert('Could not get certificate!');
        return;
    }
    const cert = await response.arrayBuffer();
    window.player.attach(document.getElementById('video'));
    window.player.configure('drm.initDataTransform', (initData) => {
        const processedData = String.fromCharCode.apply(null, new Uint16Array(initData.buffer)).substring(1);
        const contentId = new URL(processedData.substring(1)).hostname;
        const cert = player.drmInfo().serverCertificate;
        serverProcessSPCPath = processedData.substring(1).replace('skd://', 'https://');
        return shaka.util.FairPlayUtils.initDataTransform(initData, contentId, cert);
    });

    window.player.configure({
        drm: {
            servers: {
                'com.apple.fps.1_0': licenseServerUrl
            },
            advanced: {
                'com.apple.fps.1_0': {
                    serverCertificate: new Uint8Array(cert),
                },
            },
        },

    });

    try {
        await window.player.load(url);
        console.log('The video has now been loaded!');
    }
    catch (exception) {
        shakaOnError(exception)
    };
}


document.addEventListener('DOMContentLoaded', async () => {
    initializeShaka();
    await play();
});
```

**Comment by joeyparrish** [comment]
So to clarify, you're getting `SERVER_CERTIFICATE_REQUIRED` even with the code to set the server certificate?

**Comment by jpiechowiak** [comment]
You’re right. I’ve made a mistake in my question. Right now I’m receiving 6016 (INIT_DATA_TRANSFORM_ERROR), not 6015. But it also looks like, that everything in this method is working..

**Comment by joeyparrish** [comment]
Ah, okay.  That makes more sense now.  In that case, the docs for [6016](https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html#value:6016) give you another hint:

> INIT_DATA_TRANSFORM_ERROR | 6016 | number | An error was thrown while executing the init data transformation.error.data[0] is the original error.

So you'll want to look at `error.data[0]` to see what error was thrown, which should lead you to the problem in your transform function.

**Comment by jpiechowiak** [comment]
Yes, I know. I’ve already read the docs:) This error points to line:
const cert = player.drmInfo().serverCertificate;

But this line actually is working, and even the last line of this method is called - like I said in my question - I was able to assign result of this last line call to variable.

Therefore I’m a little bit confused, where to look for an error.

**Comment by joeyparrish** [comment]
Well, since I can't see the error, I can't really give you much more advice than that.  If the error points to this line:

```js
const cert = player.drmInfo().serverCertificate;
```

My best guess at why this would throw would be if drmInfo() returned null for some reason.

It's also possible that the line number might be wrong (such as might happen with minification or transformations that don't provide source maps). So you may want to ignore line numbers and add console.log statements throughout the transform function to see how far you get.

**Comment by jpiechowiak** [comment]
Already tried that, but tried now one more time:
```javascript
window.player.configure('drm.initDataTransform', (initData) => {
    console.log('a');
    const processedData = String.fromCharCode.apply(null, new Uint16Array(initData.buffer)).substring(1);
    console.log('b');
    const contentId = new URL(processedData.substring(1)).hostname;
    console.log('c');
    const cert = player.drmInfo().serverCertificate;
    console.log('d');
    serverProcessSPCPath = processedData.substring(1).replace('skd://', 'https://');
    console.log('e');
    const retValue = shaka.util.FairPlayUtils.initDataTransform(initData, contentId, cert);
    console.log('f');
    return retValue;
});
```
all the letters a,b,c,d,e,f are in console and after there is, error occured.
Also are variables have data;)

I've already spent on this issue couple of hours, before asking:)

**Comment by joeyparrish** [comment]
Thanks for being patient with me.

What version of Shaka Player are you using?  (`shaka.Player.version`)

How many times is the init data transform callback invoked?

What exactly does the error contain?  (Full object, including `error.data` and a backtrace.)

**Comment by jpiechowiak** [comment]
2.5.5
Ok I see this issue now.
First time it works perfectly. After this, method is called for the second time and in variable processedData I've characters which looks like a chineese characters.. 

And therefore script is not able to process this..

**Comment by joeyparrish** [comment]
Excellent!  I'm glad we were able to help you track it down.

Is there anything else we do for you?

**Comment by jpiechowiak** [comment]
Thank you for your help.
I'll try now investiagate, why this method is called twice, and why the results are so strange.

**Comment by joeyparrish** [comment]
Sounds good.  If you need to reopen this issue, just put `@shaka-bot reopen` in a comment.  Thanks!

**Comment by victordidenko** [comment]
@jpiechowiak how did you managed to fix this? Looks like related to #2214 to me

**Comment by jpiechowiak** [comment]
@victordidenko Actually right now I'm not using shaka for Fairplay.. I'm using standard approach (No additional libraries) which works like a charm.

**Comment by abdevnet** [comment]
@jpiechowiak I'm having the same issue as well.
