### ISSUE TITLE
shakaplayer full-width or cinema mode

### ISSUE THREAD

**Issue by clotairemarmignon** [google/shaka-player#2192]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**Is your feature request related to a problem? Please describe.**

I would like to broadcast in fullscreen (or in a bigger size than the normal one) and add a questions/answer functionnality

**Describe the solution you'd like**

The ability to make the questions/answer appear on the screen (not behind the video) or to create a "cinema mode" which could allow to broadcast videos on 80% of the screen or in full width

**Describe alternatives you've considered**

No one at the moment except allowing this in a normal mode (little video size and text under it)

**Additional context**

We would like to add the live-questions functionality. It means our users will be able to answer the questions on films while they are watching it.
![image](https://user-images.githubusercontent.com/42754005/66996665-6c75c780-f0d1-11e9-8c50-ab161ab5419d.png)

Once we want to play a film in full screen mode, questions don't appear and we didn't find any way to make it appear in front of the video. 

I think we should do a sort of "cinema mode" as We can find on YouTube.

![image](https://user-images.githubusercontent.com/42754005/66996769-962eee80-f0d1-11e9-9ba6-b35036e8639c.png)

![image](https://user-images.githubusercontent.com/42754005/66996788-9e872980-f0d1-11e9-97c0-2117bdafd249.png)

It would allow us to propose questions as we want (bigger size for the video and a little free space for our questions, and responsive):
![image](https://user-images.githubusercontent.com/42754005/66996849-b5c61700-f0d1-11e9-8b13-93e0e5cff1f3.png)

Do you know if this is possible to "add" or configure a "cinema mode" or to make an intermediary size between normal and full screen mode ? 

Thanks a lot, 
All the best, 

@google-admin @joeyparrish

**Comment by joeyparrish** [comment]
This sounds like an application-level CSS problem.  You can place the player anywhere you want, at any size, really.  You can place whatever you want next to it.

What is it that you want us to provide you to facilitate this?

**Comment by clotairemarmignon** [comment]
Joey, thank you for your feedback, is it possible to get an example of a modified screen size ? Or a template or guide ? 
Thanks

**Comment by joeyparrish** [comment]
I'm not sure what you mean.  What do you mean by an example of a modified screen size?

Are you familiar with CSS?

**Comment by clotairemarmignon** [comment]
Yes, we just would like to see how we can modify the fullscreen format or if we could add another "mode" for watching such as a "theater mode" with a full-width format for the player. 

We just want to see how we can make it possible 

Thanks

**Comment by joeyparrish** [comment]
Yes, you can definitely position and size the player any way you like using CSS.  For example, if you're using our UI, you can position the player container div anywhere you like, and give it any size you like.  You can change the size dynamically at runtime, as well.

For example, in our demo app, the class `shaka-video-container` is styled with `width: 640px; max-width: 100%;`, and is positioned in the horizontal center of the page with `margin: auto;`.  If you change the `width` value, you can change the max width of the video.  The height scales automatically with respect to the content's aspect ratio.  You can move the video container using the `left`, `right`, `margin`, and `position` attributes in CSS.

Does this answer your question?

**Comment by clotairemarmignon** [comment]
Thank you Joey,

We already have the default size. We want the full screen not taking all the screen. 

Or 

Is it possible to add a new button with a specific mode (theater mode etc...) 

Thank you

**Comment by joeyparrish** [comment]
Yes, you can add buttons as you like, and you can make them do whatever you want to.  If you want to change the CSS of the elements in full screen mode, use the :fullscreen pseudo-class.  https://developer.mozilla.org/en-US/docs/Web/CSS/:fullscreen

We will not be adding a theater mode button to the library as a standard offering, since this mode is specific to an application and is tightly coupled to the styles of the app itself.  But you can add a custom button to the UI and change the CSS however you like.

Does this answer your question?
