### ISSUE TITLE
Stream never starts in demo player v2.5.5

### ISSUE THREAD

**Issue by raskri** [google/shaka-player#2193]
I have a clear stream that never seems to start. It looks like Shaka's not able to find out where to start playing.

I tested it out in demo player v2.5.5 (uncompiled).

Media Internals in Chrome says: 
00:00:00.951 | info | Dropping video frame (DTS 1979990040000us PTS 1979990240000us,1979990280000us) that is outside append window [0us,10802000000us).
...
00:00:18.106 | debug | ISO-BMFF container metadata for video frame indicates that the frame is a keyframe, but the video frame contents indicate the opposite.

MPD URL: http://213.167.98.92/wh7f454c46tw2614630567_1924671448/TVOD/88888888/224/3221226641/3221226641.mpd?playseek=20191017070000-20191017100000&timezone=UTC

Any pointers are appreciated, thanks!

**Comment by joeyparrish** [comment]
I haven't tested this content yet, but based on what media-internals says, it seems that there is something wrong with your content.  For example, it says the append window (end of the period) is at 10802000000 us (10802 s), but your DTS was 1979990040000 us (1979990.04 s), which is nearly 200x the period end.  You may want to to double-check that your media timestamps are inside the range of the period/presentation.  You can adjust those timestamps to fit inside the period by using the `presentationTimeOffset` field.  If this manifest was produced by an off-the-shelf encoder or packager, you may want to file an issue with whoever produced that piece of software.

Does this help?

**Comment by raskri** [comment]
OK, thanks! I'm pretty sure there is something non-standard stuff going on with the packager.

But you think it would be possible to fix this on the client side? 

I've tried to manipulate the MPD content in the responseFilter, adding presentationTimeOffset to the SegmentTemplate (startNumber * duration). So that this will be sent to the player: presentationTimeOffset=26042300000000. But it does not work for this MPD.

Our ExoPlayer eats this stream without any problems. I can get the stream to play in shaka if i set the mediaPresentationDuration to Number.MAX_SAFE_INTEGER, and enable the jumpLargeGaps. But then the timeline will be all messed up.

**Comment by joeyparrish** [comment]
It's complex enough to support the DASH standard, so we really can't devote resources to supporting a wide variety of non-standard manifests.  A fix for one non-standard manifest could break another, and beyond the chaos of managing that, we are a small team with a lot of important new features planned already.

ExoPlayer is a radically different project with direct access to decoders, whereas Shaka Player depends on restrictive browser APIs for that.

Sorry we can't do more to support you on this.  You may find some success with a response filter if you can alter the manifest in a sensible way.  But I would very strongly recommend that you file a bug to get your encoder/packager fixed to generate valid content instead.

**Comment by raskri** [comment]
OK makes sense. Thanks for the response Joey.

**Comment by joeyparrish** [comment]
My pleasure.  Thanks for your interest in Shaka Player!
