### ISSUE TITLE
Allow disable the audio parsing/decoding/.. in DASH/HLS with a config

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#2195]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes

**Describe the solution you'd like**

I want disable the audio for reuse the same streams for ads and other purposes, but in the ads I don't need the audio.

**Describe alternatives you've considered**

I would like to add a configuration for DASH / HLS to disable audio (at parser level).

**Additional context**

If you agree I can do a PR. The change would be to add in `StreamingConfiguration` a new field called `forceDisableAudio` (by default false)

**Comment by joeyparrish** [comment]
This seems like it would be fairly simple.  I'm okay with it.  Feel free to send a PR with a new test case covering this.  It can be a full integration test in player_integration, if that's simpler.  (StreamingEngine tests are hard to read & modify at the moment.)
