### ISSUE TITLE
Erro charmap

### ISSUE THREAD

**Issue by Luananayara** [google/shaka-player#2206]
Can someone please help me with this error? I am using python 3.8 and windows 10. Thanks

return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1380: character maps to <undefined>

**Comment by michellezhuogg** [comment]
Hello @Luananayara , thank you for reaching out! Please follow our github issue template and describe your issue in English. Thank you!
https://github.com/google/shaka-player/issues/new?assignees=&labels=&template=bug_report.md&title=

**Comment by Luananayara** [comment]
I'm trying to follow the tutorial, shaka-player version 2.5, when I put to compile in python 3.8 gives the error and I can't move on ... follow the description of the error;
this step gives the error below:

Compile the library and generate the docs
python build/all.py

[WARNING] No changes detected, skipping. Use --force to override.
Traceback (most recent call last):
  File "build/all.py", line 150, in <module>
    shakaBuildHelpers.run_main(main)
  File "C:\Users\shaka-player\build\shakaBuildHelpers.py", line 322, in run_main
    sys.exit(main(sys.argv[1:]))
  File "build/all.py", line 92, in main
    if not localizations.generate(parsed_args.force):
  File "C:\Users\shaka-player\build\compiler.py", line 472, in generate
    not self._locales_changed()):
  File "C:\Users\shaka-player\build\compiler.py", line 451, in _locales_changed
    for line in f:
  File "C:\Users\AppData\Local\Programs\Python\Python38\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1380: character maps to <undefined>

**Comment by TheModMaker** [comment]
My guess is the default locale for Windows is not UTF8, so when it tries to read the file, it gets an error.  We should either read as bytes and decode explicitly as UTF8, or we can set the [default locale](https://docs.python.org/3/library/locale.html#locale.setlocale) to UTF8.

**Comment by Luananayara** [comment]
I installed python 2.7 and it now works without charmap errors. I have already tested with other versions of python and have the same charmap error. So using python 2.7 works perfectly, thanks

**Comment by joeyparrish** [comment]
Let's see if we can fix this for Python 3.  Users should not need such an old version of Python to build Shaka Player.

@TheModMaker, setting the default locale sounds good to me, so that we don't regress in future calls to decode().  Especially since we don't test this regularly on Windows.  But if there is a good reason to prefer setting decoding explicitly in utf8 every time, I would trust your judgement.

**Comment by Luananayara** [comment]
I tested with python 3.5, 3.6, 3.8 and everyone in windows has the same problem, my text editor is already set to UTF8.
