### ISSUE TITLE
Different values for rebufferingGoal for initial vs playing?

### ISSUE THREAD

**Issue by VictorChen** [google/shaka-player#2217]
Is there a way to set **different** values for the following cases?

1. The minimum number of seconds to buffer before starting to play the video
1. The minimum number of seconds to buffer before continuing playback after it has entered into a buffering state (while video is playing)

I see we have the `rebufferingGoal` param but that seems to control both cases. I tried updating the `rebufferingGoal` to a different value after video has started playing but that doesn't seem to work. It still uses the original value.

**Comment by TheModMaker** [comment]
It looks like when we refactored `Playhead`, the new `BufferingObserver` doesn't see updates to the `rebufferingGoal`.  We should make sure to use the latest value.

**Comment by levymoreira** [comment]
@VictorChen I downgraded to "v2.4.4" to get it working while the issue is not fixed.
