### ISSUE TITLE
delayLicenseRequestUntilPlayed configuration breaks offline storage of protected assets

### ISSUE THREAD

**Issue by pilipicus** [google/shaka-player#2218]
Hi there,

I have developed a Shakaplayer player prototype to use “delay license request”. However, I get an error "Cannot read property 'paused' of null at Xc.p.Fe " even using the manifest file and licence taken from your Shalkaplayer demo page (https://shaka-player-demo.appspot.com/demo/#audiolang=en-GB;textlang=en-GB;uilang=en-GB;panel=HOME;build=uncompiled).

https://test-dds-pwa-bucket.s3-eu-west-1.amazonaws.com/player/index.html.

Please let me know. Thank you in advance

**Comment by theodab** [comment]
It looks like the `delayLicenseRequestUntilPlayed` parameter causes storage of protected assets to fail. We should probably just be ignoring that parameter when storing for offline anyway, it doesn't make much sense in that case.
Thanks for bringing this to our attention!

**Comment by pilipicus** [comment]
I would like to allow the user to download only the manifest file and saved it locally. The license, downloaded separetely, would be valid only for a specific amount of time. Once it is expired the user would have to just download a new license without having to download the manifest file again.
In the best scenario, it would be possible to set up the validity of the license also for a specific range in the future.
Is there any way to reach it even partially with Shakaplayer?

**Comment by TheModMaker** [comment]
You can set the `offline.usePersistentLicense` configuration to `false` when storing to ignore the persistent license.  Then when you load the asset, we'll require a network connection for the license request, but the content will be loaded offline.

If you store the license offline, then there is no way to renew it.  See #1347 for a feature request to allow this, but it is on the backlog and the PR hasn't been updated recently.

We have no control over how long the license is good for.  Your license proxy sets the license duration settings.  You can control for how long a user can watch the content, but that is done with the license proxy.  You should contact Widevine (or PlayReady, or another DRM provider) for more info on that.
