### ISSUE TITLE
Extra languages from to the default ones mapped in LanguageUtils.js

### ISSUE THREAD

**Issue by pilipicus** [google/shaka-player#2219]
Hi, I would like to know if it's possible to add extra languages to the ShakaPlayer (audio, text) from those mapped in the LanguageUtils.js and in case how? For instance, If I want to add an other Spanish language that is not currently supported how can I do it? Thank you in advance.

**Comment by ismena** [comment]
Hi @pilipicus,
Did you mean adding languages to your content (e g another text track an Spanish or an audio) or adding another language for the localization of our UI (e g, names of the buttons etc)?
