### ISSUE TITLE
About how `player.load` works.

### ISSUE THREAD

**Issue by chavoosh** [google/shaka-player#2221]
As I understood in version `2.5.5`, in **Safari**, by calling `load` method, the player does not immediately let the network plugin handle the manifest URI. Instead, it first checks whether the resource exists or not and then passes the URI to the network plugin.

For instance, if my manifest URI is `https://foo.net/x/y/z/playlist.m3u8` and this playlist does not exist, Safari does not even call network plugin and shows `Failed to load resource` error.

How can I change this pipeline and let Shaka Player call the network plugin before checking the resource URI. 

BTW, I do not have this problem on Chrome or Firefox, just Safari.

**Comment by TheModMaker** [comment]
By default, we use `src=` playback on Safari.  This means we don't use the network plugins at all (except for FairPlay requests).  If you want to use MSE playback and use the network plugins, set the `streaming.useNativeHlsOnSafari` configuration to `false`; but with this you can't play FairPlay content.

**Comment by chavoosh** [comment]
Now I see... Where should I put `streaming.useNativeHlsOnSafari`? In `app.js`? Or my network plugin?

**Comment by theodab** [comment]
You can apply it using the `shaka.Player.configure` method. See our [tutorial on configuring the player](https://shaka-player-demo.appspot.com/docs/api/tutorial-config.html). You'd do something like:
```js
myPlayer.configure('streaming.useNativeHlsOnSafari', false);
```

**Comment by chavoosh** [comment]
I suppose this attribute (i.e., `useNativeHlsOnSafari`) is not supported in `v2.5.5` because I get the following error on Safari:

`Invalid config, unrecognized key .streaming.useNativeHlsOnSafari`

Right?

**Comment by theodab** [comment]
Yes, that configuration is newer than `v2.5.5`. The change that introduced it was pushed about a week after `v2.5.5` was released.

**Comment by chavoosh** [comment]
Got it, I found the commit (`8d4f9a492bb55c87`). Thank you both for your help.
