### ISSUE TITLE
Ad UI + CS IMA MVP progress tracker

### ISSUE THREAD

**Issue by ismena** [google/shaka-player#2222]
We're starting our IMA SDK integration with HTML 5 Client Side IMA SDK (SS will come next).
This is the issue for me to track what's done and what still needs doing (about half the work is done and I arrogantly thought I could keep track of everything in my head, but things start slipping :|)

So.
**What's done:**
- basic design and CS IMA integration
- ad panel layout (for the UI)
- Ad counter integration
- Making controls interact with the ad (play button, volume etc)
- Fix fade out/fade for controls in ad mode
- Ad panel needs dark background
- Find out if there are other ad UI elements that are legally required to be present before we can launch MVP ("Why this ad' button or something).

**In progress:**
- Integrate skip button, find content to test it
- Ad x of y tracker

**Needs doing:**
- Advertiser info
- Tests
- Tutorial
- Full integration for the demo.

**Comment by ismena** [comment]
Yes! There's a bunch of commits, but there's in a bit of a mess at this stage, so don't hold it against me :p 

(Newer commits at the top on the list, older commits at the bottom)
02847e3b1ff51e2db85be64fa99e411cff087efe
110c0bb485e71a1b6babdd270c39b0cb8ae5aa02
04cf0133e3303eae7345bcd3ab9d590ac9ea92b2
7da5dc91b7a45238659fe9afa4314f9bc5c73452
7afac89bc2c53c6372e2fe30e4d2cba32fdb8e99
f485772b6dde5bae60a297d4b47951531dab21a0
c2105a362b65d5f6eb725d5ba69789ab715b091d

**Comment by avelad** [comment]
@ismena, [DAI](https://developers.google.com/interactive-media-ads/docs/sdks/html5/dai) will be supported?

**Comment by ismena** [comment]
@avelad 
Yes! But in the second development wave, probably in Q1 2020.

**Comment by avelad** [comment]
@ismena Thanks for the info!

About the first wave, I would like to be able to configure [PPIP](https://developers.google.com/interactive-media-ads/docs/sdks/html5/v3/reference/js/ima.ImaSdkSettings#setPpid), will it be possible?
Will this work in Tizen? The last time I tried (more than a year ago) it didn't work.

**Comment by ismena** [comment]
@avelad Mm, I can probably expose the whole configuration object to the users, let me look into it.
What's the expected behavior for this that you weren't seeing on Tizen?

**Comment by avelad** [comment]
IMA SDK doesn't load in Tizen 3.0

**Comment by ismena** [comment]
Ah, okay :)
Let me get back to you on that once I have an end-to-end demo I can run on Tizen. If it's not working, I can try to bug the IMA team.

**Comment by avelad** [comment]
I just checked with the nightly build and the demo page is broken if the user has an ad-blocker extension.

Eg: https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm

![Captura de pantalla 2019-12-02 a las 16 57 32](https://user-images.githubusercontent.com/8983024/69974094-dda7f780-1524-11ea-8416-d92159943723.png)

**Comment by ismena** [comment]
Interesting. That probably means our logic to exclude ads from the build is gonna fail, too.
Let me take a look.

**Comment by ismena** [comment]
@avelad  Alright, so what it does is it blocks network requests for some of our source files  in **uncompiled build only**.
This does not affect the compiled build and thus won't be a problem for the end user.
The ad-less build is also not affected.
For development/testing, please use compiled mode or ("build=compiled" in the url) or temporarily disable the ad blocker to use the demo page in uncompiled mode.

**Comment by avelad** [comment]
Maybe a reminder in the readme or faq could help to other people.

**Comment by ismena** [comment]
Yes, great idea, will do.

**Comment by avelad** [comment]
@ismena , I saw all commits about this funcionality, for my use case I need that all events fired by the IMA can be access by the app (https://developers.google.com/interactive-media-ads/docs/sdks/html5/v3/reference/js/ima.AdEvent#.Type) Do you think that is possible?

**Comment by avelad** [comment]
Is it possible to add statistics on the ads played?
I would like it to be reflected in `player.getStats()`

**Comment by joeyparrish** [comment]
What ad-related stats would you need us to add?  Please file a new feature request for that and we'll discuss it there.

Same for access to IMA events.

Because this issue says MVP ("Minimum Viable Product"), it seems like we should track these additions separately.  Thanks!

**Comment by ismena** [comment]
@avelad yes, I can give you access to the IMA ad manager so you can listen for events you're interested in, would that work for your app? (Or are the events you need thrown from the ad object?)

Exposing it will let users tamper with the IMA ad manager object, but if they don't want ads, they'll probably just use an ad blocker to rip out IMA altogether.

Anyway, let's not get me in trouble with Joey and open separate issues for additional ad requests :)

**Comment by avelad** [comment]
Ok, no problem I'll raise some issues with the features required. Thanks!

**Comment by avelad** [comment]
I found a error, if you use `https://imasdk.googleapis.com/js/sdkloader/ima3_dai.js`, `google.ima` exits but not the functions of ima client side.

**Comment by ismena** [comment]
@avelad 
Are you using it as part of your custom application?
We only have support for CS at the moment, so from out standpoint it's ok that DAI messes things up at this stage. But if it's interfering with your custom logic, we'll address it (a PR is also welcome, it will just need some way to disambig between CS and DAI).

**Comment by avelad** [comment]
I created the PR https://github.com/google/shaka-player/pull/2375
