### ISSUE TITLE
Is the HTML5 track element supported for webvtt captions?

### ISSUE THREAD

**Issue by gregmsanderson** [google/shaka-player#2224]
Hello,

Not sure if this is a bug report (ie it should work, but doesn't), or a feature request. Feel free to edit accordingly.

I see in the docs that WEBVTT is supported for captions.

Sure enough, I tried your demo app and watched the 'Angel one' demo which I see loads a .vtt file, and it works perfectly.

So I tried adding a HTML5 `<track>` element in my player by putting it within the video element (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/track) and while the .vtt captions do appear ... they aren't controlled by the Shaka UI and indeed look different to the ones in the 'Angel one' demo. From what I can see, that appears to be because they are being played using the browser's native track support, rather than being played by Shaka player. Since when I look at the DOM, at the content of the 'shaka-text-container' div for 'Angel one', that is filled as expected with span elements. However when using my track element, it is _empty_. Hmm.

I looked at where the 'Angel one' demo video was getting its WEBVTT from. And indeed it appears to be from the HLS .m3u8 file. _Not_ in a separate `<track>` element. If possble I'd rather use a track element to allow captions to be added, removed etc without having to remake the m3u8/mpd.

If HTML5 track elements are _not_ supported for providing captions, how would I go about adding that? Would I do it by editing the actual Shaka js files and building a new version myself, or could I do it in my app.js file? If you can point me in the right direction that would be great.

**Comment by TheModMaker** [comment]
You can add external text tracks with the following after you call `load`:

```js
await player.addTextTrack('https://example.com/foo.vtt', 'en', 'caption', 'text/vtt');
```

Adding a `<track>` element will make it handled by the browser, not by us.  I'm not sure if there is a way to disable this behavior, so we may not be able to support that case.  But you can use the above call to add them in JavaScript.

**Comment by gregmsanderson** [comment]
Ah, perfect. Thanks.

No worries about the track element. I'll just not use one. Solved.
