### ISSUE TITLE
Sometimes catch errors after refresh page VueJs

### ISSUE THREAD

**Issue by ivansteff** [google/shaka-player#2225]
Sometimes, after refresh page, i catch diffrent erros, sometimes video loading.
I use lib from cdn.

`<script src="https://cdnjs.cloudflare.com/ajax/libs/shaka-player/2.5.5/shaka-player.ui.js" integrity="sha256-o7NyrnbLZboR7Pfh5aP52xImctrTdlcx6WImPrmKLF0=" crossorigin="anonymous"></script>`

### Code:
```
<template>
<div>
......
<div data-shaka-player-container data-shaka-player-cast-receiver-id="7B25EC44">
    <video autoplay data-shaka-player ref="video" id="video"controls></video>
</div>
......
</div>
</template>

<script>
export default {
		name: 'name',
		data() {
			return {
				player: undefined,
				video: undefined,
			}
		},
               mounted(){

               var url = "https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd"
               this.player = new shaka.Player();
	       this.video = this.$refs.video;
	       this.player.addEventListener('error', err => console.error(err));
	      shaka.polyfill.installAll();
	      if (!shaka.Player.isBrowserSupported()) {
	          console.error('Browser not supported');
	      	  return;
	      }
	      this.player.attach(this.video);
	      this.player.load(url).catch(err =>
	      console.error(err));
               },
}

</script>

```

Video loading, without cast option, i have tv on my network.

### Error :
```

DOMException: Failed to execute 'addSourceBuffer' on 'MediaSource': The MediaSource's readyState is not 'open'.
    at https://cdnjs.cloudflare.com/ajax/libs/shaka-player/2.5.5/shaka-player.ui.js:150:282
```

**or :**
 error `code: 7002` try fix like
[this](https://github.com/google/shaka-player/issues/1649#issuecomment-436084363), it is doesn't help. All controls move under the player

Maybe i doing wrong?

**Comment by joeyparrish** [comment]
The 'attach' method is async, so try something like:

```js
this.player.attach(this.video).then(() => {
  return this.player.load(url);
}).catch(err => {
  console.error(err);
});
```

**Comment by ivansteff** [comment]
@joeyparrish  method catch error
`  console.error(err);
`
New error:
````
Cannot read property 'addEventListener' of undefined
 at new qc (event_manager.js:181)
    at M.m (event_manager.js:71)
    at hl (player.js:1147)
    at player.js:259
    at Object.xf (player.js:307)
    at Ha.b (walker.js:342)
    at Ma (generator_engine] :795)
    at Na.next (generator_engine] :699)
    at execute_async_generator] :68
    at new Promise (<anonymous>)

`
```
And 7002 error;

**Comment by theodab** [comment]
Could you load the debug build? Replace `https://cdnjs.cloudflare.com/ajax/libs/shaka-player/2.5.5/shaka-player.ui.js` with `https://cdnjs.cloudflare.com/ajax/libs/shaka-player/2.5.5/shaka-player.ui.debug.js`. That will make the stack trace a bit more human-readable.

**Comment by ivansteff** [comment]
@theodab yes, ofcourse.
![image](https://user-images.githubusercontent.com/31563237/67979203-d8594380-fc2c-11e9-9d7f-cde1063fd5fb.png)

![image](https://user-images.githubusercontent.com/31563237/67979234-e6a75f80-fc2c-11e9-826a-c8f17c645d82.png)

**Comment by TheModMaker** [comment]
It looks like `this.video` is `undefined` when you call `this.player.attach`.  Double check you are passing the correct value.

**Comment by ivansteff** [comment]
@TheModMaker Yes you are right!
This is my mistake =)
Shaka team thank you very much for the quick reply!

**Comment by theodab** [comment]
Also, on further inspection, you are loading the UI library and putting UI tags onto HTML objects, but making a player manually. I don't think this will break anything, but it does mean that a player instance with UI will be created and then and not used, which is pointlessly wasting system resources.
If you don't want to use the UI, you can just load the non-UI library (`https://cdnjs.cloudflare.com/ajax/libs/shaka-player/2.5.5/shaka-player.compiled.js`, or `https://cdnjs.cloudflare.com/ajax/libs/shaka-player/2.5.5/shaka-player.compiled.debug.js` for debug), and remove the `data-shaka-player` tags.

**Comment by joeyparrish** [comment]
> you are loading the UI library and putting UI tags onto HTML objects, but making a player manually. I don't think this will break anything,

In fact, it will break something.  The UI will be connected to a Player instance that is not the one controlling the video element, so the UI will be broken/non-functional/confusing.

Instead, you should get a player instance from the video:

```js
player = videoElement.ui.getPlayer();
```

**Comment by ivansteff** [comment]
@theodab Ok, I understand you.
I'm studying right now ui library opportunities and try to put them into practice. If you have questions, I will certainly ask them.
