### ISSUE TITLE
How to detect video started playing?

### ISSUE THREAD

**Issue by VictorChen** [google/shaka-player#2230]
I have the following player configuration with a `rebufferingGoal` so that it won't start until enough content has been buffered:

```js
player.configure({
  manifest: {
    dash: {
      ignoreMinBufferTime: true
    }
  },
  streaming: {
    rebufferingGoal: 59,
    bufferingGoal: 60
  }
});
```

I tried listening to the video's `playing` event, but that triggers before the video actually started playing, eg:

```js
video.addEventListener("playing", () => {
  // doesn't work, video hasn't started playing yet
  alert("started playing");
});
```

demo: https://codesandbox.io/s/heuristic-satoshi-nt6cl

Is there an event I can listen to for when the video starts playing? Or do I have to rely on events like `timeupdate` (which is not great since it triggers multiple times)?

**Comment by joeyparrish** [comment]
`timeupdate` on the video element would work, and you can always stop listening after the first one.  But this can also trigger when we do a seek, which may happen before playback if you specify a non-zero start time or if the content has a gap at the beginning.

You could also listen to the `buffering` event from the `Player` object and notice when `event.buffering` is false.  That one would also trigger multiple times, though, any time the player's buffering state changes.  But the first time `event.buffering` is false, you are definitely playing content.

If you just want to know that the manifest has been fully loaded, and that streaming will now begin, you could wait for the `Promise` returned from `player.load()`.  This won't resolve when frames are being displayed, but when we start fetching content.  So I'm not sure that this would meet your needs.  On the plus side, this is not an event, so it only happens once.

My advice would be to just listen for the `timeupdate` event or `buffering` event and just stop listening once you see an event that meets your criteria.  It's not too difficult to stop listening to events.

You can also use `shaka.util.EventManager` to simplify things for you:

```js
const eventManager = new shaka.util.EventManager();
eventManager.listenOnce(videoElement, `timeupdate`, () => {
  console.log('Stuff is happening!');
});
```

Or:

```js
const eventManager = new shaka.util.EventManager();
eventManager.listen(player, `buffering`, (event) => {
  if (event.buffering == false) {
    console.log('We're playing!');
    eventManager.unlisten(player, 'buffering');
  }
});
```

Does this help?

**Comment by VictorChen** [comment]
Was hoping for a `playing` event from Shaka, but I can workaround it for now. Thanks for the quick response!

**Comment by riksagar** [comment]
Interesting!  Is this the playing event from the htmlmediaelement?  What are the circumstances in which that is fired yet the player isn't playing?  The only situation I can think is if there's a pending license/EME request.

**Comment by joeyparrish** [comment]
The `playing` event from the media element is what we're discussing above, yes.  It fires when the element goes into a playback state, but the player can hold back playback as part of our buffering system.  We do this by setting `video.playbackRate = 0` today.  We're considering ways to remove this in the future and rely on feedback from the video element to know when it's buffering natively, instead of managing buffering at a higher level as we do today.
