### ISSUE TITLE
Build cannot -@ads

### ISSUE THREAD

**Issue by fadomire** [google/shaka-player#2231]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.6

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `master`?**
yes

**Are you using the demo app or your own custom app?**
na

**If custom app, can you reproduce the issue using our demo app?**
na

**What browser and OS are you using?**
na

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

na

**What did you do?**

1. git clone shaka repo
2. run `python build/build.py -@ads` 

**What did you expect to happen?**
build to succeed

**What actually happened?**

build fail
apparently `ads` plugin is required in core but not listed in types/core
the best would be to make it an independent module that we can remove in the custom build

command and trace:
$ python build/build.py -@ads
[INFO] Compiling the library (ui, release)...
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/shaka-player/third_party/closure/compiler.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
/shaka-player/lib/player.js:22: ERROR - required "shaka.ads.AdManager" namespace never provided
goog.require('shaka.ads.AdManager');
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

1 error(s), 0 warning(s)
[ERROR] Build failed

**Comment by ismena** [comment]
Ah, dang.
Let me see how big of a mess it would be to make the ad-related logic optional.

**Comment by ismena** [comment]
Alright, I think I found a way :)
It should work now.
