### ISSUE TITLE
Caststatuschanged catch error: "Cannot read property 'newStatus' of undefined"

### ISSUE THREAD

**Issue by ivansteff** [google/shaka-player#2235]
I catch error, when set `addEventListener`.

![image](https://user-images.githubusercontent.com/31563237/68765190-43434b00-062d-11ea-8f12-073d34c14c91.png)

Init, and call like this [question](https://github.com/google/shaka-player/issues/2233).

**shaka.pl.js**
```
export default class ShPlayer {

	async changeUrl(newUrl) {
		const video = document.getElementById('video');
		const videoContainer = document.getElementById('videoContainer');
		const player = new shaka.Player(video);

		const ui = new shaka.ui.Overlay(player, videoContainer, video);
		const controls = ui.getControls();

		controls.addEventListener('caststatuschanged', this.onCastStatusChanged());

		try {
			await player.load(newUrl);
		} catch (error) {
			console.error(error);
		}
	}
	
	onCastStatusChanged(event) {
		const newCastStatus = event['newStatus'];
		// Handle cast status change
		console.log('The new cast status is: ' + newCastStatus);
	}
	
	onPlayerErrorEvent(errorEvent) {
		// Extract the shaka.util.Error object from the event.
		this.onPlayerError(event.detail);
	}

	onPlayerError(error) {
		// Handle player error
		 console.error('Error code', error.code, 'object', error);
	}

	onUIErrorEvent(errorEvent) {
		// Extract the shaka.util.Error object from the event.
		this.onPlayerError(event.detail);
	}

	initFailed() {
		// Handle the failure to load
		console.error('Unable to load the UI library!');
	}
}
```
**Player.vue**
```
<template>
    <div>
        <div  ref="main" data-shaka-player-container data-shaka-player-cast-receiver-id="7B25EC44">
            <video data-shaka-player ref="video" id="video"
                autoplay controls></video>
        </div>
    </div>
</template>

<script>
    import ShakaPlayer from '../shaka.pl.js';
    export default {
        name: "Player",
        data() {},
        mounted() {
            var a = new ShakaPlayer ();
            a.changeUrl(someUrl);

        },
    };
</script>
```

**index.html**

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width,initial-scale=1.0"/>
    <title>
        Player
    </title>
    <link href="https://fonts.googleapis.com/css?family=Rubik:300,400,500" rel="stylesheet"/>
    <script defer src="https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"></script>
    <script src="./shaka-player.ui.debug.js"></script>
    <link rel="stylesheet" href="./controls.css"/>
</head>
<body>
<div id="app"></div>
<script src="/mux.js"></script>
</body>
</html>
```
If remove line `controls.addEventListener('caststatuschanged', this.onCastStatusChanged());
`
video play. Controls appear, but there are no cast buttons among them.
![image](https://user-images.githubusercontent.com/31563237/68767487-cbc3ea80-0631-11ea-8141-ae894c46e7e7.png)

And incorrect time. (when i change url, i set url to live stream)
I did everything according to the[ example](https://shaka-player-demo.appspot.com/docs/api/tutorial-ui.html)

If i set my url to shaka [demo page](https://shaka-player-demo.appspot.com/demo/#audiolang=ru-RU;textlang=ru-RU;uilang=ru-RU;asset=https://storage.googleapis.com/shaka-demo-assets/sintel-widevine/dash.mpd;panel=HOME;build=uncompiled) . Always ok, i can select tv to cast, cast was working.

Why doesn’t the cast button appear?
What could I do wrong?

**Comment by TheModMaker** [comment]
First, like your previous issue, you don't use a lambda for the event listener, so it calls the `onCastStatusChanged` immediately.  You should do:

```js
controls.addEventListener('caststatuschanged', (e) => this.onCastStatusChanged(e));
```

Secondly, those are the native controls, so there is no cast support.  Try removing the `controls` attribute from the `<video>` element.

**Comment by ivansteff** [comment]
@TheModMaker Now there is no way to check the chrome cast, check a little later. As for the controls, I removed the controls from the video tag, nothing happened. The video is on, there are no controls.

**Comment by joeyparrish** [comment]
As I mentioned in the other issue you filed, you should not recreate the player & UI every time the playback URL changes.  You're doing this:

```js
	async changeUrl(newUrl) {
		const video = document.getElementById('video');
		const videoContainer = document.getElementById('videoContainer');
		const player = new shaka.Player(video);

		const ui = new shaka.ui.Overlay(player, videoContainer, video);
		const controls = ui.getControls();
```

Instead, that should happen in the constructor or initialization of the component.  Then, when the URL changes, just call player.load() on the existing player instance.

**Comment by ivansteff** [comment]
@TheModMaker I fixed my mistakes. Video when changing the stream, loaded correctly.
**shaka.pl.js**

```
export default class ShPlayer {
	
	constructor() {
		this.video = document.getElementById('video');
		this.videoContainer = document.getElementById('videoContainer');
		this.player = new shaka.Player(this.video);
		this.ui = new shaka.ui.Overlay(this.player, this.videoContainer, this.video);
		this.controls = this.ui.getControls();
		this.controls.addEventListener('caststatuschanged', (e) => this.onCastStatusChanged(e));
	}
	async changeUrl(newUrl) {
		try {
			await this.player.load(newUrl);
		} catch (error) {
			console.error(error);
		}
	}
	onCastStatusChanged(event) {
		const newCastStatus = event['newStatus'];
		// Handle cast status change
		console.log('The new cast status is: ' + newCastStatus);
	}

...............

}
```

**Player.vue**
```
<template>
    <div>
        <div  ref="main" data-shaka-player-container data-shaka-player-cast-receiver-id="7B25EC44">
            <video data-shaka-player ref="video" id="video"
                autoplay controls></video>
        </div>
    </div>
</template>

<script>
    import ShakaPlayer from '../shaka.pl.js';
    export default {
        name: "Player",
        props:{
            'videoInfo': Object, //link to stream
        },
        data() {},
        watch() {
            videoInfo(info) {   // NOTE: when link was change, i catch new flow, and call changeUrl method
                    var a = new ShakaPlayer();
                    a.changeUrl(url);
            },
        },        
        mounted() {
            new ShakaPlayer();

        },
    };
</script>
```

**Comment by joeyparrish** [comment]
Glad we could help!  And thanks for posting again with the corrected code for others who may find this issue in a search in the future.

**Comment by ivansteff** [comment]
@joeyparrish  Oops, I mean that the video plays in the browser. But do not cast.
@TheModMaker I tested, removing the `controls `attribute from the `<video>` element. Nothing happened, there are no controls at all.

**Comment by joeyparrish** [comment]
The cast button only appears if:

1) You include the Cast SDK
2) You configure a Cast receiver ID
3) You have a Chromecast device powered up and on the same network as your browser

You can see details on the Cast SDK in the UI tutorial: https://shaka-player-demo.appspot.com/docs/api/tutorial-ui.html

That tutorial also shows how to set the receiver ID through the DOM-based setup, but not through the API.  To configure that via the API, use the `configure()` method on `this.ui`, documented here: https://shaka-player-demo.appspot.com/docs/api/shaka.ui.Overlay.html

The format for the configuration is documented here (and linked from the Overlay docs): https://shaka-player-demo.appspot.com/docs/api/shaka.extern.html#.UIConfiguration

The field you want is the `castReceiverAppId` field.

Finally, make sure your Cast device is turned on and on the same network.  The button only shows up if there are devices available to cast to.

Does this help?

**Comment by ivansteff** [comment]
@joeyparrish i check `castReceiverAppId ` the field is empty.
![image](https://user-images.githubusercontent.com/31563237/68885663-9fd66100-0726-11ea-8a2e-dcfd84eb352e.png)

I insert the code like this:
```
 <div id="videoContainer" 
            data-shaka-player-container   data-shaka-player-cast-receiver-id="7B25EC44">
            <video data-shaka-player id="video"  autoplay></video>
 </div>
```

**Comment by joeyparrish** [comment]
The DOM-based setup won't work for you if you don't have the elements statically in the HTML.  If you're using the API to construct `Overlay`, you need to call configure() on it to set the receiver app ID.  Please see the links I sent.

**Comment by ismena** [comment]
@ivansteff Is this the same application as you reference above or a different one? :)

Using the code you posted above:
`
export default class ShPlayer {
	
	constructor() {
		this.video = document.getElementById('video');
		this.videoContainer = document.getElementById('videoContainer');
		this.player = new shaka.Player(this.video);
		this.ui = new shaka.ui.Overlay(this.player, this.videoContainer, this.video);
                this.controls = this.ui.getControls();
                // Try this!
                this.ui.configure('castReceiverAppId', '7B25EC44');
		this.controls.addEventListener('caststatuschanged', (e) => this.onCastStatusChanged(e));
	}
	async changeUrl(newUrl) {
		try {
			await this.player.load(newUrl);
		} catch (error) {
			console.error(error);
		}
	}
	onCastStatusChanged(event) {
		const newCastStatus = event['newStatus'];
		// Handle cast status change
		console.log('The new cast status is: ' + newCastStatus);
	}

}
`

**Comment by ivansteff** [comment]
@ismena Finally, I get it! Many thanks to your team for such a detailed explanation!
