### ISSUE TITLE
Multiple issues with CEA-608 captions

### ISSUE THREAD

**Issue by sath33sh** [google/shaka-player#2238]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v.2.5.6

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Did not try master

**Are you using the demo app or your own custom app?**
Custom app

**If custom app, can you reproduce the issue using our demo app?**
Did not try the demo app

**What browser and OS are you using?**
Chrome 78.0.3904.97 on Mac OS 10.14.5

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**

https://philo-static.s3.us-east-2.amazonaws.com/test-streams/shaka/vod/a85827e447b1e26482a8e723afa92fa864356c2d/manifest.mpd

**What did you do?**

Play a VOD asset with multiple periods, seek to random locations across period boundaries. Our assets typically have ads inserted. Ads are presented as separate periods. Periods in a manifest have the following structure:
A - C - A - C - A - C
where A represents an Ad period and C represents a content period. Captions are optional in Ad segments, but content segments always have captions.

**What did you expect to happen?**
Captions are displayed correctly.

**What actually happened?**

Noticed the following issues:
1. Sometimes caption lines are duplicated. It does not always happen at the same location. It seems to happen around period boundaries, but again it is not consistently reproducible.
2. Sometimes captions disappear altogether and then reappear after an Ad period is played. Again, not consistently reproducible.

The test stream attached above have multiple content periods. I believe it is sufficient to repro the problem. If not I can create additional test streams with Ad periods.

**Comment by TheModMaker** [comment]
The asset you linked doesn't appear to have captions in it.  I don't see any captions and we aren't getting any captions from `mux.js`.

Also, are you sure you tested with v2.5.6 and not v2.5.5?  This sounds like #2076, which was fixed in v2.5.6.  Could you also test with `master`?

**Comment by sath33sh** [comment]
> Also, are you sure you tested with v2.5.6 and not v2.5.5? This sounds like #2076, which was fixed in v2.5.6. Could you also test with `master`?

I tested v2.5.6. It used to happen more often in the previous builds. Looks like #2076 addressed some of the issues, but there are still some lingering ones which are harder to repro. Our original content is encrypted so it is extra effort to create unencrypted test streams. Are you open to the idea of logging in to our system so you can use the original encrypted streams for repro? I can create a test account for you. After you log in you can use your own Shaka player on the same browser.

**Comment by michellezhuogg** [comment]
Hello @sath33sh ,

Please send us the account info so that we can look into your test case with more details. Thank you!

**Comment by sath33sh** [comment]
@michellezhuogg Please use the following steps:
1. Goto https://tv-staging7.philo.com, select the "Email Address" tab and sign-in as user ingest@philo.com
2. You'll need a sign-in code to proceed. I can forward you the code here in this thread or have it sent to your email address (I'll need your email for that)

I'm listing a few assets where the problem was noticed by our QA team. They also mentioned that the problem happens more often on Windows.
https://tv-staging7.philo.com/player/player/vod/Vk9EOjYwODU0ODg5OTY0ODUyNTU5Nw
https://tv-staging7.philo.com/player/player/vod/Vk9EOjYwODU0ODg5OTY0ODUxOTM0Nw

**Comment by joeyparrish** [comment]
You can send any private details, including credentials, to `shaka-player-issues@google.com`.  This way, the whole team will have access to it.  The information you send there will not leave the team.

**Comment by sath33sh** [comment]
@joeyparrish That's better. I have created a new account with shaka-player-issues@google.com as the username. Also updated my previous comment.

**Comment by joeyparrish** [comment]
@sath33sh, I haven't seen any temporary sign-in codes at the issues alias.  Should we have that already?

**Comment by sath33sh** [comment]
@joeyparrish It will be sent when you sign in at https://tv-staging7.philo.com. Did you try that already?

**Comment by sath33sh** [comment]
@joeyparrish I found that the duplicate captions bug can be consistently reproduced using the following steps.

Example asset:
https://tv-staging7.philo.com/player/player/vod/Vk9EOjYwODU0ODg5OTY0ODUzNzcwNw

It has the following structure:
Start-----AdBreak1-----AdBreak2-----AdBreak3-----End

Repro steps:
1. Seek to a point between AdBreak3 and End. Play for a few seconds.
2. Seek to a point between AdBreak2 and AdBreak3. Play for a few seconds.
3. Repeat the above steps few times and you'll notice duplicate captions.

**Comment by joeyparrish** [comment]
I've taken a look at the workaround you added in https://github.com/PhiloInc/shaka-player/commit/194e4e9adfed190c39e8f30e8dc4a9afae7d67ef .  I'm not convinced that this is the right fix in all cases, but I'm glad you are able to workaround it for now.

As far as I can tell from analyzing `TextEngine` and `MediaSourceEngine`, the only way to wind up with duplicates at the point you modified (`storeAndAppendClosedCaptions`) is if we fetch and append a segment which is already in the buffer.  Otherwise, I expect that the `TextDisplayer` instance would have been cleared (on seek) before the call to `MediaSource.appendBuffer`, which calls `TextEngine.storeAndAppendClosedCaptions`.

Do you have a custom `AbrManager` implementation that calls the switch callback with the `safeMargin` parameter?  Do you ever call `selectVariantTrack` in your app with the `safeMargin` parameter?

**Comment by joeyparrish** [comment]
Still hoping to get answers to this question to help us understand possible causes:

> Do you have a custom `AbrManager` implementation that calls the switch callback with the `safeMargin` parameter?  Do you ever call `selectVariantTrack` in your app with the `safeMargin` parameter?

**Comment by gingervitis** [comment]
Hi @joeyparrish , sorry for the delay. I just happened to revisit this thread today and totally hadn't noticed the updates until now.

So we did find that the workaround was not good enough as it sometimes completely skipped displaying captions altogether, often after a seek.
Yes we are currently using an ABR manager.. let me look into a bit more to see what we're doing with it.

**Comment by joeyparrish** [comment]
Thanks.  I would expect that this could only happen with the use of safeMargin, which wasn't designed with CEA in mind.  If this can be confirmed, it might lead us to a reasonable work-around.

**Comment by gingervitis** [comment]
Ok nope, we are not passing any `safeMargin` param with in our switch callback. We are not using `selectVariantTrack` either. 
I've also tried disabling the ABR manager altogether and the issue still happens.

**Comment by joeyparrish** [comment]
Hrm... That is really strange.  What I think I know says that it shouldn't happen, so I am not sure why it does.  We need to dig deeper and figure out what's going on here.

It's possible that this could be solved as a side-effect of the refactors in #1339, which is nearly complete.  Would you be willing to test that theory with an update to a pre-release version once #1339 is closed?

I would still like to figure this out in a way that can be applied to v2.5.x, but we won't realistically be able to dig deep enough on this until after #1339 is done and v2.6 is ready to ship.  If v2.6 solves it, it will at least be a very useful data point in determining what can be done for a v2.5.x bugfix release.

**Comment by gingervitis** [comment]
Yes we'll definitely give the pre-release a test.

**Comment by gingervitis** [comment]
Some extra info may or may not have come up already ..  We've also noticed that we can "fix" the situation by toggling the captions off-then-on-again when it starts to double up. Hopefully that bit of info might help?

**Comment by joeyparrish** [comment]
@sath33sh, @gingervitis, we have completed the refactoring in #1339.  Could you try with the latest code on `master` and let us know if things have improved at all?

**Comment by michellezhuogg** [comment]
Tested with: https://tv-staging7.philo.com/player/player/vod/Vk9EOjYwODU0ODg5OTY0ODUxOTM0Nw and https://tv-staging7.philo.com/player/player/vod/Vk9EOjYwODU0ODg5OTY0ODUzNzcwNw with seeking forward and backward before and after the ads, and saw captions displaying before and after the ads without duplication.
Tested with https://tv-staging7.philo.com/player/player/channel/Q2hhbm5lbDo2MDg1NDg4OTk2NDg0Mzg2MTI and captions werer displaying.
@sath33sh Could you please let us know if you still see any caption issus?
