### ISSUE TITLE
New test assets

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#224]
Load Sintel (4k) on IE11.  Video will buffer 30 seconds and then stop.  The audio stream will fetch and appendBuffer every segment, but only the first one (0-10s) shows up in the SourceBuffer's buffered property.  None of the appendBuffer calls fail, all of them result in an 'updateend' event, but the operation seems to have no effect past the first segment.

The result is that video.buffered only shows 10s (the intersection of audio & video) and so the player goes into a buffering state at the 10s mark.  The stream never recovers.

@jonoward Did you not have issues with IE11's MSE implementation with your content?  I can't find anything wrong with how I'm interacting with the SourceBuffer.

**Comment by jonoward** [comment]
@joeyparrish nope I didn't run into issues like this. I gave this a try here, and I get different, but mixed results:

- WinServer2012 + IE11 - Plays from start to about 1m50s then goes into permanent buffering state (on highest bitrate). It consistently stalls at the same point.
- Win8.1 + IE11 - Doesn't play at all for me (see JS errors in the console, need to investigate further)
- Win10 + Edge: Plays from start to about 1m30s then crashes the tab!

Since this is 4k (and the segments are quite large), perhaps it's exceeding some kind of internal memory limit for the buffer? As we're seeing different behaviour, maybe related to hardware differences? I'm guessing a bit though.

**Comment by joeyparrish** [comment]
I don't think it's about 4k content running us out of memory.  I get the same results if I disable adaptation and run video at 426x182.

I checked, and appendBuffer() is neither throwing an exception, causing an 'error' event to fire, nor actually appending the audio buffers.  It would seem IE11 is not doing the right thing here.  If it can't accept the content, some kind of error would be appropriate.

I don't see anything I can do about it other than change the test content.  It's unfortunate that we will not be able to rely on IE's MSE implementation to behave in a way that is consistent with other browsers.

**Comment by joeyparrish** [comment]
I'm going to leave this open until next week.  If anyone has any ideas, I'd be happy to hear them.

**Comment by joeyparrish** [comment]
Moving to 2.0 and renaming.  Not sure why IE11 won't decode our assets, but it's out of our hands.  What we will have to do is find test assets that IE11 will decode.

**Comment by jonoward** [comment]
The content that comes out of Azure Media Services works with IE11 (as you'd expect!), here's an unencrypted sample that I know works - http://wams.edgesuite.net/media/MPTExpressionData02_SeekDemo/BigBuckBunny_1080p24_IYUV_2ch.ism/manifest(format=mpd-time-csf). 

I realise you probably can't just take something like this and include it as a test asset in the repo, but it may help to try see the differences between them and the encoding generated from Azure Media Services.

**Comment by joeyparrish** [comment]
Thank, Jono!  I can certainly add the URL to the repo.  We don't need to mirror the asset itself.

**Comment by joeyparrish** [comment]
Hrm... I'm having the same problem with that asset.  IE11, for me at least, ignores all the audio segments past t=9 for some reason.

**Comment by jonoward** [comment]
That's really weird. What version of windows are you using? Physical or virtual?

**Comment by joeyparrish** [comment]
I've got IE 11.0.9600.18053 (update version 11.0.24) Windows 8.1 Enterprise, inside VMWare hosted on Ubuntu Linux.

**Comment by joeyparrish** [comment]
We will have a new set of test assets in v2.0, and IE11/Edge testing will now be done on real hardware.  (I still can't understand why the browser would behave so differently on a VM.)

**Comment by joeyparrish** [comment]
A new set of demo/test assets from a variety of sources has been added for v2.  Cross-browser compatibility has not yet been vetted.  Ultimately, all test assets will be included in automated testing across all supported browsers.
