### ISSUE TITLE
Why is shaka.media.StallDetector.MediaElementImplementation.hasContentFor_ using a hardcoded value ?

### ISSUE THREAD

**Issue by karthiksivaram** [google/shaka-player#2240]
We have had an issue with Stalls on some of our streams / devices and have enabled stall detection. While this worked in some instances we ran in to a strange situation where the stall detection was not working. Debugging this through to the stall detector we found this piece of code in lib/media/stall_detector.js:

```
static hasContentFor_(buffered, timeInSeconds) {
    const TimeRangesUtils = shaka.media.TimeRangesUtils;
    for (const {start, end} of TimeRangesUtils.getBufferedInfo(buffered)) {
      if (timeInSeconds < start) {
        continue;
      }
      if (timeInSeconds > end - 0.5) {
        continue;
      }
      return true;
    }
    return false;
  }
```

There is no explanation as to why hasContentFor tests for a boundary condition where timeInSeconds > end - **0.5** . 

In our case the currentTime was 1312.19 and buffered range end was 1312.499 which caused it to assume that hasContentFor was false. We have temporarily resolved this by changing the line to read 
`if (timeInSeconds > end - 0.05) {`
but without any context or explanation to why the code was written this way, we dont want to submit a PR for this fix yet (either to make it configurable or set to 0.05)

**Comment by michellezhuogg** [comment]
0.5 was chosen experimentally by us that worked for most of the cases we tested with, and it is better to be configurable. You're welcome to submit a PR for this issue. Thank you!
