### ISSUE TITLE
Example of customizing the number and order of controls 

### ISSUE THREAD

**Issue by ivansteff** [google/shaka-player#2241]
I can't understand how to customise number and order of controls.

> Customizing the number and order of controls
> For example, let's say that all you care about for your app is rewinding and fast-forwarding. You could add the following line to init(), right before creating the UI overlay. This will configure UI to ONLY provide these two buttons:
> 
> uiConfig['controlPanelElements'] = ['rewind', 'fast_forward'];
> This call will result in the controls panel having only two elements: rewind button and fast forward button, in that order. If the reversed order is desired, the call should be:
> 
> uiConfig['controlPanelElements'] = ['fast_forward', 'rewind'];

From [shaka docs](https://shaka-player-demo.appspot.com/docs/api/tutorial-ui-customization.html)

I initialize the player as in my previous question.

```
export default class ShPlayer {
	
	constructor() {
		this.video = document.getElementById('video');
		this.videoContainer = document.getElementById('videoContainer');
		this.player = new shaka.Player(this.video);
	        this.ui = new shaka.ui.Overlay(this.player, this.videoContainer, this.video);
                this.controls = this.ui.getControls();
                this.ui.configure('castReceiverAppId', '7B25EC44');
		this.controls.addEventListener('caststatuschanged', (e) => this.onCastStatusChanged(e));
	}
	async changeUrl(newUrl) {
		try {
			await this.player.load(newUrl);
		} catch (error) {
			console.error(error);
		}
	}
	onCastStatusChanged(event) {
		const newCastStatus = event['newStatus'];
		// Handle cast status change
		console.log('The new cast status is: ' + newCastStatus);
	}
}
```

As I understand it, this line `uiConfig['controlPanelElements'] = ['fast_forward', 'rewind'];`   needs to be inserted before  ` this.ui = new shaka.ui.Overlay(this.player, this.videoContainer, this.video);`
If I do this, an error appears.

```
TypeError: Cannot set property 'controlPanelElements' of undefined
    at new ShPlayer (shaka.pl.js?5d87:13)
```
Can I see an example of initialization?

**Comment by ismena** [comment]
@ivansteff 
Hm, that's good feedback, let me see if I can update the tutorial to be easier to understand.

In the meantime: which buttons do you want to add? We have two places for buttons: control panel (where the mute button & the fullscreen buttons are) and the overflow menu (where the cast button is).

In the tutorial example, we're adding fast forward and rewind buttons to the button panel (and not adding anything else). You would do this:

```
this.ui = new shaka.ui.Overlay(this.player, this.videoContainer, this.video);
this.controls = this.ui.getControls();
var (or const/let, whatever convention you're using) config = {};
config['controlPanelElements'] = ['fast_forward', 'rewind'];
config['castReceiverAppId'] = '7B25EC44';
this.ui.configure(config);

```

Does this help?

**Comment by ivansteff** [comment]
Can I add controls in the following order:
Switch track back, pause, Switch track forward, enable / disable sound, time, quality selection, pip, cast, fullscreen.
For example, like so:
![image](https://user-images.githubusercontent.com/31563237/68965826-c4494080-07ed-11ea-90f4-ebd83797db86.png)
Do I understand correctly, first I need to initialize all these buttons, then change their css styles?

**Comment by ismena** [comment]
First of all, you'll need to create your own "switch track back/forward" buttons as we don't have them out of the box (but I'll help you if need it :)).

Mute, time, and fullscreen buttons we have as part of the library, so that's easy.

We also have cast, pip, and quality buttons, but only as part of the overflow menu (under the "..." button, where you saw them in your prev issue).

So, now you can do:
```
this.ui = new shaka.ui.Overlay(this.player, this.videoContainer, this.video);
this.controls = this.ui.getControls();
var (or const/let, whatever convention you're using) config = {};
config['controlPanelElements'] = ['play_pause', 'mute','time_and_duration', 'spacer', ''fullscreen', 'overflow_menu'];
config['castReceiverAppId'] = '7B25EC44';
this.ui.configure(config);

```
See what you end up with, hopefully, once you see the result, it will be even easier to see how the config works.

**Comment by ivansteff** [comment]
@ismena Thanks so much for the example!

**Comment by ivansteff** [comment]
@ismena I still need your help adding custom buttons :)
If I want to create a button, do I need to create a new file and mount it? For example, switching between films, there is a list of films, I want to include the next movie by pressing the button. I don’t quite understand what I need to do for this.

> Creating custom elements and adding them to the UI
> It's possible to add custom application-specific buttons to the UI. Each element has to have it's own class that implements the shaka.extern.IUIElement interface and register with shaka.ui.Controls. All our elements use shaka.ui.Element as a base class. Take a look to see if it's right for your custom buttons.
> 
> Let's say, we want to create a button that allows user to skip the currently playing video and go to the next one.
> ```
> 
> // skipButton.js
> 
> // Use shaka.ui.Element as a base class
> myapp.SkipButton = class extends shaka.ui.Element {
>   constructor(parent, controls) {
>     super(parent, controls);
>     // The actual button that will be displayed
>     this.button_ = document.createElement('button');
>     this.button_.textContent = 'Skip current video';
>     this.parent.appendChild(this.button_);
> 
>     // Listen for clicks on the button to start the next playback
>     this.eventManager.listen(this.button_, 'click', () => {
>       let nextManifest = /* Your logic to pick the next video to be played */
>         myapp.getNextManifest();
> 
>       // shaka.ui.Element gives us access to the player object as member of the class
>       this.player.load(nextManifest);
>     });
>   }
> };
> 
> // Factory that will create a button at run time.
> myapp.SkipButton.Factory = class {
>   create(rootElement, controls) {
>     return new myapp.SkipButton(rootElement, controls);
>   }
> };
> 
> // Register our factory with the controls, so controls can create button instances.
> shaka.ui.Controls.registerElement(
>   /* This name will serve as a reference to the button in the UI configuration object */ 'skip',
>   new myapp.SkipButton.Factory());
> ```
From [Shaka docs.](https://shaka-player-demo.appspot.com/docs/api/tutorial-ui-customization.html)

**Comment by ismena** [comment]
Yes, you'll need to create your own button.
Do you have your logic to get the manifest for the next movie? What does it look like? (It doesn't matter that much, but I have a feeling it will be easier to understand, if I give you an example with your own code).

**Comment by ivansteff** [comment]
@ismena I get an array of stream links from api. For example, you need two buttons to click on which the link to the stream changes, we switch to the next stream or to the previous one, depending on which button we selected.
As I understand it, it is necessary to add the following code to the class of the shaka:

```
ShPlayer.prototype.onLeftControlClick_ = function () {
  const prevVideo= store.getters['tvplayer/prevVideo']; //Link to the stream of the previous video in the list
this.changeUrl(prevVideo);
};

ShPlayer.prototype.onRightControlClick_ = function () {
  const nextVideo= store.getters['tvplayer/nexVideo']; //Link to the stream of the next video in the list
this.changeUrl(nextVideo);
};
async changeUrl(newUrl) {
try {await this.player.load(newUrl);} catch (error) {console.error(error);}}
```
And add to constructor:
`config['controlPanelElements'] = ['onLeftControlClick_ ','onRightControlClick_ ' ];

Did I understand correctly?
`

**Comment by ismena** [comment]
Almost. Your buttons will have to be classes, inheriting from shaka.ui.Element or implementing the shaka.extern.IUIElement interface.

Adopting the example from our tutorial:

```
NextMovieButton = class extends shaka.ui.Element {
  constructor(parent, controls) {
    super(parent, controls);
    // The actual button that will be displayed
    this.button_ = document.createElement('button');
    this.button_.textContent = 'skip_next';
    this.parent.appendChild(this.button_);

    // Listen for clicks on the button to start the next playback
    this.eventManager.listen(this.button_, 'click', () => {
      const prevVideo= store.getters['tvplayer/prevVideo']; //Link to the stream of the previous video in the list
        this.changeUrl(nextVideo);
    });
  }
};

// Factory that will create a button at run time.
NextMovieButton.Factory = class {
  create(rootElement, controls) {
    return new NextMovieButton(rootElement, controls);
  }
};

// Register our factory with the controls, so controls can create button instances.
shaka.ui.Controls.registerElement(
  /* This name will serve as a reference to the button in the UI configuration object */ 'next_movie',
  new NextMovieButton.Factory());
```
And then once you're configuring the UI:
```
this.ui = new shaka.ui.Overlay(this.player, this.videoContainer, this.video);
this.controls = this.ui.getControls();
const config = {};
config['controlPanelElements'] = ['next_movie', 'play_pause', 'mute','time_and_duration', 'spacer', ''fullscreen', 'overflow_menu'];
config['castReceiverAppId'] = '7B25EC44';
this.ui.configure(config);
```

Does this make sense?

**Comment by ivansteff** [comment]
@ismena Understood, thank you so much!

**Comment by kaharman** [comment]
> Almost. Your buttons will have to be classes, inheriting from shaka.ui.Element or implementing the shaka.extern.IUIElement interface.
> 
> Adopting the example from our tutorial:
> 
> ```
> NextMovieButton = class extends shaka.ui.Element {
>   constructor(parent, controls) {
>     super(parent, controls);
>     // The actual button that will be displayed
>     this.button_ = document.createElement('button');
>     this.button_.textContent = 'skip_next';
>     this.parent.appendChild(this.button_);
> 
>     // Listen for clicks on the button to start the next playback
>     this.eventManager.listen(this.button_, 'click', () => {
>       const prevVideo= store.getters['tvplayer/prevVideo']; //Link to the stream of the previous video in the list
>         this.changeUrl(nextVideo);
>     });
>   }
> };
> 
> // Factory that will create a button at run time.
> NextMovieButton.Factory = class {
>   create(rootElement, controls) {
>     return new NextMovieButton(rootElement, controls);
>   }
> };
> 
> // Register our factory with the controls, so controls can create button instances.
> shaka.ui.Controls.registerElement(
>   /* This name will serve as a reference to the button in the UI configuration object */ 'next_movie',
>   new NextMovieButton.Factory());
> ```
> 
> And then once you're configuring the UI:
> 
> ```
> this.ui = new shaka.ui.Overlay(this.player, this.videoContainer, this.video);
> this.controls = this.ui.getControls();
> const config = {};
> config['controlPanelElements'] = ['next_movie', 'play_pause', 'mute','time_and_duration', 'spacer', ''fullscreen', 'overflow_menu'];
> config['castReceiverAppId'] = '7B25EC44';
> this.ui.configure(config);
> ```
> 
> Does this make sense?

Hi @ismena 

I use this example from tutorial with shaka-player UI but still not working.

Here is my implementation:
```
  async function init() {
    // When using the UI, the player is made automatically by the UI object.
    const video = document.getElementById('video')
    const ui = video['ui']
    const elements = {
      controlPanelElements: [
        'play_pause',
        'rewind_10',
        'mute',
        'volume',
        'time_and_duration',
        'spacer',
        'overflow_menu',
        'fullscreen',
      ]
    }
    ui.configure(elements)
    const controls = ui.getControls()
    const player = controls.getPlayer()
  
    // Listen for error events.
    player.addEventListener('error', onPlayerErrorEvent)
    controls.addEventListener('error', onUIErrorEvent)
  }
```

I got console warning ```Unrecognized control panel element requested: rewind_10``` and the button did not appear.
Did I make a mistake?

**Comment by joeyparrish** [comment]
We don't see your code for `rewind_10`, nor the registration of it.  So it's hard to say what went wrong.

**Comment by kaharman** [comment]
@joeyparrish here is my complete code

rewindButton.js
```
require('shaka-player/dist/shaka-player.ui.debug')

// Use shaka.ui.Element as a base class
rewindButton = class extends shaka.ui.Element {
  constructor(parent, controls) {
    super(parent, controls)

    // The actual button that will be displayed
    this.button_ = document.createElement('button')
    this.button_.textContent = 'Rewind 10 seconds'
    this.parent.appendChild(this.button_)

    // Listen for clicks on the button to start the next playback
    this.eventManager.listen(this.button_, 'click', () => {
      console.log('Rewind 10 second')
    })
  }
}

// Factory that will create a button at run time.
rewindButton.Factory = class {
  create(rootElement, controls) {
    return new rewindButton(rootElement, controls)
  }
}

// Register our factory with the controls, so controls can create button instances.
shaka.ui.Controls.registerElement('rewind_10', new rewindButton.Factory())
```

index.js
```
require('shaka-player/dist/shaka-player.ui.debug')
require('./rewindButton')

...

  async function init() {
    // When using the UI, the player is made automatically by the UI object.
    const video = document.getElementById('video')
    const ui = video['ui']
    const elements = {
      controlPanelElements: [
        'play_pause',
        'rewind_10',
        'mute',
        'volume',
        'time_and_duration',
        'spacer',
        'overflow_menu',
        'fullscreen',
      ]
    }
    ui.configure(elements)
    const controls = ui.getControls()
    const player = controls.getPlayer()
  
    // Listen for error events.
    player.addEventListener('error', onPlayerErrorEvent)
    controls.addEventListener('error', onUIErrorEvent)
  }
```
