### ISSUE TITLE
Stream update and upload it to chrome cast

### ISSUE THREAD

**Issue by ivansteff** [google/shaka-player#2243]
Faced with the problem that when selecting and broadcasting a movie through chrome castes, when changing a stream, an old link to the stream will remain. I don’t understand how to update the chrome cast. For this, you need to add listening to events and when changing the link to the stream, send a new link to the chrome cast?
How to send a new link?

**Comment by TheModMaker** [comment]
Sorry for not replying sooner.  I don't really understand your problem.  Do you mean the server changed the content for the stream or you want to play at a new URL?

If you are using the `CastProxy` type, you can just call `player.load()` again with the new stream to start playing it instead.

**Comment by ivansteff** [comment]
@TheModMaker Yes, that’s what I meant, thanks!
