### ISSUE TITLE
HTTP Cookies not being send on some calls.

### ISSUE THREAD

**Issue by matejpolak** [google/shaka-player#2244]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
YES

**What version of Shaka Player are you using?**
v2.5.5

**Can you reproduce the issue with our latest release version?**
YES

**Can you reproduce the issue with the latest code from `master`?**
YES

**Are you using the demo app or your own custom app?**
Custom app, so I can add a Request/Response filter hook

**If custom app, can you reproduce the issue using our demo app?**
YES

**What browser and OS are you using?**
Crome 78.0.3904.97, MacOS Mojave

**What did you do?**

I have a player following this flow:
1. Adding a stream url into the player. This URL returns 302 redirect to the manifest location.
2. Manifest location being loaded
url: `http://s1-h4-wowza-c-sign-cookie.tbocdn.ab.sk/vodo/.../index.m3u8`

Response contains following headers:
> Accept-Ranges: bytes
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Range
Access-Control-Allow-Methods: GET, OPTIONS
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Date, Server, Content-Type, Content-Length
Access-Control-Expose-Headers: Location
Cache-Control: max-age=5
Connection: keep-alive
Content-Length: 323
Content-Type: application/vnd.apple.mpegurl
Date: Mon, 18 Nov 2019 14:40:55 GMT
Server: nginx/1.15.10
Set-Cookie: Path=/
Set-Cookie: Domain=s1-h4-wowza-c-sign-cookie.tbocdn.ab.sk
Set-Cookie: value=123
X-Proxy-Cache: MISS
X-Proxy-Key: upstreams_wowza-c-sign-cookie.tbocdn.ab.sk/vodo/.../index.m3u8?

3. Returned chunklist being loaded, with `request.allowCrossSiteCredentials = true`
Example chunklist url: `http://s1-h4-wowza-c-sign-cookie.tbocdn.ab.sk/vodo/.../chunklist_b5000000.m3u8`

Request Headers:
> Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: cs-CZ,cs;q=0.9,en;q=0.8
Cache-Control: no-cache
Connection: keep-alive
Host: s1-h4-wowza-c-sign-cookie.tbocdn.ab.sk
Origin: http://...com
Pragma: no-cache
Referer: http://...com/
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36

4. Individual chunk being loaded, with `request.allowCrossSiteCredentials = true`
Example chunk url: `http://s1-h4-wowza-c-sign-cookie.tbocdn.ab.sk/vodo/.../media_b5000000_0.ts`

Response headers:

> Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: cs-CZ,cs;q=0.9,en;q=0.8
Cache-Control: no-cache
Connection: keep-alive
Cookie: Path=/; Domain=s1-h4-wowza-c-sign-cookie.tbocdn.ab.sk; value=123
Host: s1-h4-wowza-c-sign-cookie.tbocdn.ab.sk
Origin: http://...com
Pragma: no-cache
Referer: http://...com/
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36

**What did you expect to happen?**
I need to have a `Cookie` header on chunklist request as well as on chunks.

**What actually happened?**
Chunklist request doesn't contain a `Cookie` header, which is causing the server verification not working. (Server verification temporarily switched of to be able get chunks and play the stream)

Can you please take a look on that? I can of course provide full manifests, test domain, HARs, etc.. To help you take a look into it. Thanks a lot in advance.

**Comment by joeyparrish** [comment]
Please read the "Cookie Authentication" section of our [License Server Authentication Tutorial](https://shaka-player-demo.appspot.com/docs/api/tutorial-license-server-auth.html).  It should apply equally well to non-license requests.  In short, you need a request filter to flag that cookies should be sent cross-origin.

Does this help?

**Comment by matejpolak** [comment]
Hey, well that's exactly what I did. But even though I've added the `request.allowCrossSiteCredentials = true;` flag, it is works only like in 10% of all cases. Weird thing is that for individual chunks `Cookie` header is always send, but Chunklist doesn't contain it in most cases. Don't know if this is directly shaka related.. :/

**Comment by matejpolak** [comment]
But if using for example Native MPEG-Dash + HLS Playback chrome extension (https://chrome.google.com/webstore/detail/native-mpeg-dash-%20-hls-pl/cjfbmleiaobegagekpmlhmaadepdeedn) all HTTP Cookies are added just fine and the verification itself works as expected.

**Comment by joeyparrish** [comment]
JavaScript applications don't get to directly send individual cookies.  All we can do is request that cross-origin cookies do or don't get sent.  Beyond that, the decision is made by the browser using the CORS rules, which are influenced by the server's headers.

CORS may not apply to a Chrome extension, though.  So that might explain the difference.

You can read more about CORS here: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

I would advise you to read that article and compare with the response headers.  In particular, if any given OPTIONS request doesn't get back the response header [`Access-Control-Allow-Credentials: true`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Credentials), then cookies will not be sent by the browser in the corresponding GET request.
