### ISSUE TITLE
Don't read video segments if the player is attached to an <audio> element.

### ISSUE THREAD

**Issue by btsimonh** [google/shaka-player#2246]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**Is your feature request related to a problem? Please describe.**

I have a requirement where I have the same audio used in two instances if Shaka - one playing audio and video with a <video> element, and the other playing audio only with and <audio> element (this is used to perform 'audio scrubbing' when frame-stepping video).

**Describe the solution you'd like**

I'd like to be able to load the same MPD in both players, and for the audio only player to NOT load the video segments.
The drive here is just to save bandwidth when video is clearly not actually going to be displayed.

**Describe alternatives you've considered**

Creating a second MPD (just delete the video <AdaptationSet> section) - this works fine.
This indicates that the player could just ignore the video portion of the MPD if it is attached to an audio element.

**Additional context**

**Comment by michellezhuogg** [comment]
Hello @btsimonh ,

Thank you for your input, and we're planning to implement this in the future! Meanwhile, you're also welcome to submit a PR. Thank you!
