### ISSUE TITLE
DASH/MPD Manifest differences IE/Chrome doubts

### ISSUE THREAD

**Issue by alexandercerutti** [google/shaka-player#2248]
Hi,
I'm facing the support of IE 11 of our player that uses Shaka. I'm tracing the requests we are doing to get the Dash stream through a proxy program.

I've encountered a problem in IE: it does a request to a file `manifest.mpd` that goes on HTTP 404 and that we don't know where it comes from. Since it goes on 404, we cannot reproduce the stream because Shaka goes on error.

I've tested it in Chrome, and the request to `manifest.mpd` doesn't get performed, but it may or may not work (it may give 404 on a file called `1.mpd`).

1.mpd is an XML file with this structure:

![image](https://user-images.githubusercontent.com/5442545/69160820-77fe4900-0aea-11ea-84b1-3d9946286a6c.png)

1.mpd request gets done also on IE once, but on Chrome the request against a `1.mpd` are a LOT.

Sadly the url changes every time, because we are using a service for Server Side Advertising Insertions, but the situation is the same for in Chrome and IE, so I cannot post it here.

I've no skills in Dash/MPD structure etc., so I have few "noob" questions:

1) How the manifest request is done? I mean, how does Shaka know that it has to do a request against a specific url? (Like `/csm/Content/..../channel/manifest.mpd`). This because I found some urls in the MPDs but none containing "manifest"
2) How Shaka determines if the request to the manifest should be done?
3) In which occasions the manifest is needed? Can it be replaced by "1.mpd" or IS 1.mpd itself a manifest?

Thank you very much!

**Comment by joeyparrish** [comment]
Sounds like a strange issue.  Let me see if I can answer your general questions, and we'll go from there.

> 1. How the manifest request is done? I mean, how does Shaka know that it has to do a request against a specific url? (Like /csm/Content/..../channel/manifest.mpd). This because I found some urls in the MPDs but none containing "manifest"

The initial manifest URL is provided by you, the app developer, in `player.load("foo.mpd")`.  After that, if it's a live stream, we will periodically update the manifest.  The update period is specified by the manifest itself, and by default, we will fetch from the exact same URL every time.

However, if a `<Location>` element appears in the manifest, that will direct the player to update the manifest from a different URL.  For example, if you call `player.load("foo.mpd")` and foo.mpd contains `<Location>bar.mpd</Location>`, then the next update will be from bar.mpd.

This can also be influenced by an application's request filters.  If your app registers a request filter, that filter can arbitrarily modify request URLs before the requests are sent.

> 2. How Shaka determines if the request to the manifest should be done?

The initial request is done when you call `player.load()`, and additional manifest requests are done only for live streams, and based on a timer.  The period of that timer is set by the `minimumUpdatePeriod` attribute on the `<MPD>` element.

> 3. In which occasions the manifest is needed? Can it be replaced by "1.mpd" or IS 1.mpd itself a manifest?

".mpd" is the typical extension for DASH manifests, so I assume that "1.mpd" in your case is a DASH manifest.

Does this help?  If we are going to do any further debugging for you, we will need specific steps to reproduce the issue and access to the content.  You can provide that access privately via email to `shaka-player-issues` `at` `google.com`.

**Comment by alexandercerutti** [comment]
Thank you very much @joeyparrish! Your explanation were useful, expecially the one about `<Location>`
Actually we discovered that our SSAI provider, gives us the `manifest.mpd` that goes on 404 for some kind of reason (maybe their sdk?). If we don't pass through it, it works on IE like on Chrome.

So, thank you very much again! I'll update or close this issue as soon as I'll have further infos or questions. 😄

**Comment by alexandercerutti** [comment]
Currently, at work, this problem lost priority, so I'm gonna close this at the moment. I'll reopen it later if needed. Thank you again!
