### ISSUE TITLE
PiP button name doesn't fit in Russian

### ISSUE THREAD

**Issue by ivansteff** [google/shaka-player#2249]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
2.5.5

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `master`?**
yes

**Are you using the demo app or your own custom app?**
demo app

**If custom app, can you reproduce the issue using our demo app?**
-

**What browser and OS are you using?**
Google Chrome

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

--

**What did you do?**

open overflow menu on the contols panel

**What did you expect to happen?**

In the version with the Russian language, should appear: "Картинка в картинке"

**What actually happened?**
In the version with the Russian language, the last letter of the text does not fit: "Picture in Picture"
![image](https://user-images.githubusercontent.com/31563237/69226558-658b1a80-0b91-11ea-959a-a7188018fc89.png)

**Comment by ismena** [comment]
Ah, that's a CSS issue, looks like the "e" got cut off. Let me take a look.

**Comment by ismena** [comment]
"е" спасена :)

Alright, the "e" has been rescued and should appear in the latest master.

**Comment by ivansteff** [comment]
@ismena perfect! Thanks, or "Спасибо" :)
