### ISSUE TITLE
Standard HTTP Redirect

### ISSUE THREAD

**Issue by sam2007** [google/shaka-player#225]
Hi Guys,

Does shaka player supports standard HTTP Redirect (301, 302). I am testing the player against a loadbalancer that does standard http redirect and I can see that for the inicial mpd request it follows the redirect directives:

HTTP/1.1 302 Found
Location: http://xxxx/manifest.mpd

But the succeeding mpds and chunk request are still being requested from the old URL. Which of course doesn't exist in the old URL.

Is there any parameters or setting that can be configured in the player to make it do the succeeding request on the URL specified in the http redirect directives (Location)?

Regards,

Ferdinand

**Comment by joeyparrish** [comment]
Unfortunately, XMLHttpRequest doesn't give us any way to know that our manifest request was redirected.  This means that relative URLs will still be relative to the original location.

The Fetch API would allow us to know that a redirect has happened, and to where.  However, Fetch is only available on Chrome, Firefox, and Opera.  IE and Safari don't have it yet.

If we were to start using Fetch and polyfill it with XHR, the result would be redirects that behave differently on different browsers.  I believe that would only cause more confusion for application developers.

**Comment by rgc** [comment]
XMLHttpRequest does give us a way to determine where the manifest file was downloaded, but this has only been implemented in certain browsers:
https://xhr.spec.whatwg.org/#the-responseurl-attribute

I've committed a pull request here that will fix this issue:
https://github.com/google/shaka-player/pull/263

**Comment by lusteenh** [comment]
What about adopting the  MPD.location attribute in DASH manifests to get around this ?  In that case the server needs of course to support that too.

**Comment by joeyparrish** [comment]
This issue was closed 10 months ago.  We currently support the location attribute in the manifest as well as HTTP redirects.
