### ISSUE TITLE
Can we use hls js for parsing the url to play on shaka player?

### ISSUE THREAD

**Issue by ramakanthkoigura** [google/shaka-player#2251]

**Comment by joeyparrish** [comment]
hls.js and Shaka Player are parallel projects.  It would not make sense to use them together.  It's not clear what you mean about "parsing the URL to play".  In Shaka Player, you pass the master playlist URL to `player.load()`.  There's no parsing to be done for that.

Does this help?

**Comment by ramakanthkoigura** [comment]
yes . Thank you
