### ISSUE TITLE
drm content inside iframe on android chrome 

### ISSUE THREAD

**Issue by andrewmnlv** [google/shaka-player#2253]
is it possible play drm content inside iframe on android chrome?

**Comment by TheModMaker** [comment]
It should be supported, but sandboxing may not allow it.  See https://dev.chromium.org/Home/chromium-security/deprecating-permissions-in-cross-origin-iframes.  You may need to add `allow="encrypted-media"` to the `<iframe>`.

**Comment by andrewmnlv** [comment]
hi, @TheModMaker 
allow="encrypted-media" works fine for desktop chrome, but on android chrome i get 6003 error

**Comment by TheModMaker** [comment]
What is the value of `error.data[0]`?

**Comment by andrewmnlv** [comment]
sorry for the delay
it seems that reason was parent site hosted over http instead https, and now it works
@TheModMaker thanks
