### ISSUE TITLE
Symbol.iterator error on demo page on Edge browser

### ISSUE THREAD

**Issue by selcukgun** [google/shaka-player#2254]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
N/A

**Can you reproduce the issue with our latest release version?**
N/A

**Can you reproduce the issue with the latest code from `master`?**
N/A

**Are you using the demo app or your own custom app?**
Demo

**If custom app, can you reproduce the issue using our demo app?**
Issue is about demo page. 

**What browser and OS are you using?**
Win 10/Edge 42.17134.1038.0 

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
N/A

**What did you do?**

1. Try to load https://shaka-player-demo.appspot.com/demo/#build=compiled
2. UI to enter stream information does not show up

**What did you expect to happen?**
UI shall show up

**What actually happened?**
Looks like Symbol needs to be polyfilled for Edge. I am getting the following error on the console:
Object doesn't support property or method Symbol.iterator

**Comment by joeyparrish** [comment]
Does this happen on older versions of the player demo?

https://index-dot-shaka-player-demo.appspot.com/

**Comment by selcukgun** [comment]
https://2-4-7-dot-shaka-player-demo.appspot.com/demo/ works fine.

**Comment by TheModMaker** [comment]
Can you try again with the latest version of Edge?  I cannot reproduce with Edge 44.18362.449.0.
