### ISSUE TITLE
Getting 2 TypeErrors with Shaka player using React and Typescript

### ISSUE THREAD

**Issue by sonicka** [google/shaka-player#2255]
Hey there!

I'm very new to shaka player and I'm trying to use it in a simple app. Followed the official tutorial, but I'm using _React_ with _Typescript_ and I can't get it to work. I'm getting these two errors:
> TypeError: Cannot read property 'textTracks' of null

> TypeError: this.target.addEventListener is not a function

I'm unable to tell where the second one happens, the first one is marked in the code, which looks like this:

```
const Video: React.FC<RouteComponentProps> = props => {
  let video = React.createRef<HTMLVideoElement>();

  useEffect(() => {
    const initPlayer = () => {
      let player = new shaka.Player(video);

      if (player) {
        player.addEventListener("error", function(event: any) {
        });
        player
          .load(manifestUri)
          .then(function() {
            console.log("The video has now been loaded!");
          })
          .catch((error: any) =>
            console.error("Error code", error.code, "object", error) // first error thrown here
          ); 

        (window as any).player = player;
      }
    };

    function initApp() {
      shaka.polyfill.installAll();

      if (shaka.Player.isBrowserSupported()) {
        initPlayer();
      } else {
        console.error("Browser not supported!");
      }
    }

    if (document) {
      document.addEventListener("DOMContentLoaded", initApp);
    }
  }, [video, videoUrl]);

  return (/* video element here*/);
};
```

What am I doing wrong here? 
Thanks.

Details of errors here:
```
index.js:1375 Error code undefined object TypeError: Cannot read property 'textTracks' of null
    at new Dk (shaka-player.compiled.js:11604)
    at new Tk.c.textDisplayFactory (shaka-player.compiled.js:13556)
    at Ga.b (shaka-player.compiled.js:12437)
    at Ma (shaka-player.compiled.js:511)
    at Na.next (shaka-player.compiled.js:541)
    at shaka-player.compiled.js:354
    at new Promise (<anonymous>)
    at ka (shaka-player.compiled.js:349)
    at t (shaka-player.compiled.js:359)
    at Xk (shaka-player.compiled.js:12432)
    at shaka-player.compiled.js:12039
    at Object.Be (shaka-player.compiled.js:12081)
    at Ga.b (shaka-player.compiled.js:11572)
    at Ma (shaka-player.compiled.js:511)
    at Na.next (shaka-player.compiled.js:541)
    at shaka-player.compiled.js:354
    at new Promise (<anonymous>)
    at ka (shaka-player.compiled.js:349)
    at t (shaka-player.compiled.js:359)
    at Ck (shaka-player.compiled.js:11567)
    at Ga.b (shaka-player.compiled.js:11556)
    at Ma (shaka-player.compiled.js:511)
    at Na.next (shaka-player.compiled.js:541)
    at c (shaka-player.compiled.js:342)
```

```
Uncaught (in promise) TypeError: this.target.addEventListener is not a function
    at new cc (shaka-player.compiled.js:2110)
    at K.push../node_modules/shaka-player/dist/shaka-player.compiled.js.K.w (shaka-player.compiled.js:2064)
    at Vk (shaka-player.compiled.js:12335)
    at shaka-player.compiled.js:12027
    at Object.Be (shaka-player.compiled.js:12081)
    at Ga.b (shaka-player.compiled.js:11572)
    at Ma (shaka-player.compiled.js:511)
    at Na.next (shaka-player.compiled.js:541)
    at shaka-player.compiled.js:354
    at new Promise (<anonymous>)
    at ka (shaka-player.compiled.js:349)
    at t (shaka-player.compiled.js:359)
    at Ck (shaka-player.compiled.js:11567)
    at Ga.b (shaka-player.compiled.js:11556)
    at Ma (shaka-player.compiled.js:511)
    at Na.next (shaka-player.compiled.js:541)
    at c (shaka-player.compiled.js:342)
```

**Comment by ismena** [comment]
Hi @sonicka 
We don't have much react experience on the the team, but here's a couple of tutorials our users have written for Shaka+react:
1) https://github.com/matvp91/shaka-player-react
2) https://github.com/amit08255/shaka-player-react-with-ui-config
Please check them out and see if it helps. (The authors will probably accept questions as well)

Now, with the disclaimer that I know nothing about React, what is the value of |video| and |manifestUri| in your useEffect()?
```
    const initPlayer = () => {
      let player = new shaka.Player(video);
      // ADD THIS
      console.log(video);
      console.log(manifestUri);
      if (player) {
        player.addEventListener("error", function(event: any) {
        });
        player
          .load(manifestUri)
          .then(function() {
            console.log("The video has now been loaded!");
          })

```

**Comment by sonicka** [comment]
Hi @ismena,
thanks for the reply. Those 2 variables should be okay, manifestUri points to a link to m3u8 file I got together with the assignment (tell me if you want to check that but I think that should be in correct format) and video returns the video element 
```
current: video
   accessKey: ""
   assignedSlot: null
   attributeStyleMap: StylePropertyMap {size: 0}
   attributes: NamedNodeMap {0: width, 1: height, 2: poster, 3: controls, 4: autoplay, 5: src, width: width, 
   height: height, poster: poster, controls: controls, autoplay: autoplay, …}
   autocapitalize: ""
   autoplay: true
   ...
   ...
```
That should be correct I think.

Thanks for the links as well, I think I came across those when I searched for resources for React but I check again and probably forward my problem there. 

In case you have any other idea what could be wrong with my code let me know! 

One more thing - I notices that it behaves a little strange - the first time I load the page which contains the video, I don't get the errors, just warnings about _Cross-Origin Read Blocking (CORB)_, which I don't fully understand yet. Is that necessary to resolve before it can work? (I'm using YouTube videos as source.) And the errors appears after I reload the page.

**Comment by matvp91** [comment]
When you define a ref with `React.createRef`, the value is present as `ref.current`. What you're doing is, you're passing along a React ref object to shaka-player and not the video element. See https://github.com/matvp91/shaka-player-react/blob/master/src/index.js#L24

As for the errors you're getting now, you're using a stream that is not working. The `OPTIONS` call to the first segment (seq-0.ts) returns you a 501 status code and not a 200.

Can you try with one of the demo HLS streams available in the shaka demo page?

**Comment by sonicka** [comment]
Thanks @matvp91 for your response.

Seems like my assignment doesn't require changing the source so I am probably okay with how it works right now.

Although I have one more question - l'm trying to fullscreen the video automatically when it starts playing using `requestFullscreen()`, and it sometimes works and sometimes it throws 

> TypeError: fullscreen error: Failed to execute 'requestFullscreen' on 'Element': API can only be initiated by a user gesture.

You think you could briefly explain how come it sometimes works and sometimes doesn't? And if it is possible to make it work _always_? That might sound dumb but from what I've read it should never work so I'm kinda confused.

**Comment by TheModMaker** [comment]
On Chrome (and probably other browsers), certain actions like playing a video and entering fullscreen require a user action.  So you can only call `requestFullscreen()` as a result of a user action; for example, inside the `click` event listener.  If you just randomly call it (e.g. using `setTimeout`), the browser will reject it.

**Comment by sonicka** [comment]
Got it. Now I call `requestFullscreen()` when clicking on button together with playing the video with Shaka player and it works. Thanks.
