### ISSUE TITLE
Live session: seekRange value not updated against manifests updates ?

### ISSUE THREAD

**Issue by jrosener** [google/shaka-player#2261]
I have a question related to the update of the seekRange value while getting new manifests in case of a live session.

# Setup
1. A big audio file (let's say 10h of audio) which is (based on user/webserver request) transcoded and encapsulated into MP4 DASH by FFMPEG like that:
`ffmpeg -i audio.mp3 -y -acodec aac -f dash -use_template 1 -single_file 1 -seg_duration 10 -streaming 1 manifest.mpd`
2. A web site including Shaka Player which should render as soon as possible (even if the transcoding is not finished on server side) the audio for the user. The goal is to have a seekRange growing based on new manifest updates, so the user can jump everywhere into what's is already transcoded.

# What happen
* FFMPEG is generating and regularly updating a type="dynamic" manifest during the processing which is considered as a live session in Shaka Player (so it will ask for a new manifest every 10sec to the server), such as:
```
<MPD xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	type="dynamic"
	minimumUpdatePeriod="PT10S"
	suggestedPresentationDelay="PT10S"
	availabilityStartTime="2019-11-28T14:06:04Z"
	publishTime="2019-11-28T14:06:06Z"
	minBufferTime="PT20.0S">
	<ProgramInformation>
	</ProgramInformation>
	<Period id="0" start="PT0.0S">
		<AdaptationSet id="0" contentType="audio" segmentAlignment="true" bitstreamSwitching="true">
			<Representation id="0" mimeType="audio/mp4" codecs="mp4a.40.2" bandwidth="128000" audioSamplingRate="44100">
				<AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2" />
				<BaseURL>manifest-stream0.m4s</BaseURL>
				<SegmentList timescale="1000000" duration="10007800" startNumber="1">
					<Initialization range="0-744" />
					<SegmentURL mediaRange="745-208595" />
					[...]
				</SegmentList>
			</Representation>
		</AdaptationSet>
	</Period>
</MPD>
```
* When the whole transcoding process is done, the last/final manifest switches to type="static" which is considered as a VOD session by Shaka Player, such as:
```
<MPD xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	type="static"
	mediaPresentationDuration="PT38M36.6S"
	minBufferTime="PT20.0S">
	<ProgramInformation>
	</ProgramInformation>
	<Period id="0" start="PT0.0S">
		<AdaptationSet id="0" contentType="audio" segmentAlignment="true" bitstreamSwitching="true">
			<Representation id="0" mimeType="audio/mp4" codecs="mp4a.40.2" bandwidth="128000" audioSamplingRate="44100">
				<AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2" />
				<BaseURL>manifest-stream0.m4s</BaseURL>
				<SegmentList timescale="1000000" duration="10007800" startNumber="1">
					<Initialization range="0-744" />
					<SegmentURL mediaRange="745-208595" />
					[...]
				</SegmentList>
			</Representation>
		</AdaptationSet>
	</Period>
</MPD>
```
* During the processing (and the playback of the beginning of the audio) Shaka Player handles this change between live and VOD nicely, however the seekRange is not updated each time it gets a new manifest. Indeed on the client side this is what I get:
```
Load first manifest
seekRange: 0 -> 1000  // Live mode: indeed there are 1000sec of audio in the manifest
 [10 sec...]
Updating manifest
seekRange: 0 -> 1010 // Live mode: in fact, it just added 10 sec because it is
                     // considering a live session (but in this manifest there
                     // are 2000sec of audio available)
 [10 sec...]
Updating manifest
seekRange: 0 -> 1020 // Live mode: I would actually expect to get a seekRange
                     // based on what's in the current manifest, something
                     // like [0 -> 3000]
 [many sec until the end of the processing...]
seekRange: 0 -> 36000 // VOD mode: when it switches from live to VOD the
                      // seekRange become the correct value
```

# Question
The seekRange is updated against the clock and not against what's in the updated manifests in case of a Live session.
- Is it the expected behavior or a bug ?
- If it is the expected behavior, how can I "force" Shaka Player to deliver the seekRange that is actually in the current manifest ?

**Comment by joeyparrish** [comment]
Yes, that's correct.  The seek range updates at 1x wall clock time, and that's intended.  If your encoder goes faster than that, it's not a realistic live event.  :-)

We use the contents of the manifest to compute the timestamp of the "edge" of a live stream when it is first loaded.  After that, it's all incremental updates on a timer.

Since you're actually encoding a VOD clip, but ffmpeg initially calls it live, you get this odd behavior as a consequence of the manifest attributes.

What might meet your expectations better is if type starts as "dynamic", but with a fixed "mediaPresentationDuration" of the whole clip.  Then your segment list eventually matches the duration, at which point "dynamic" goes to "static" and we stop fetching updates.  I believe this will give you the behavior you want in Shaka Player, but you might have to modify ffmpeg to get that.

**Comment by jrosener** [comment]
>  If your encoder goes faster than that, it's not a realistic live event. :-)

Indeed, I would like to take advantage of FFmpeg that is considering the manifest as a live one during transcoding to let the user to get access to the section that is already transcoded. But I agree, it's VOD :-)

> What might meet your expectations better is if type starts as "dynamic", but with a fixed "mediaPresentationDuration" of the whole clip.

OK, that's easy, it is not a problem to hack the manifest each time Shaka is requesting it.

> Then your segment list eventually matches the duration, at which point "dynamic" goes to "static" and we stop fetching updates.

However, I don't understand what you mean with that. Do you mean that the segment list should always match the final mediaPresentationDuration value (so with kind of fake segments until the end of the transcoding) ?
For the moment I actually just added "mediaPresentationDuration" with the duration of the whole final clip during the transcoding phase (type = "dynamic"), but I did not get a different behavior in Shaka than I described in my previous post.

Another idea : if I modify the FFmpeg behavior by constantly generating a type="static" manifest (which will grow during the transcoding), can I force Shaka to regularly fetch and update the manifest without resetting the whole playback engine (I did not find such an API in the doc, but maybe I missed something) ?

**Comment by joeyparrish** [comment]
> For the moment I actually just added "mediaPresentationDuration" with the duration of the whole final clip during the transcoding phase (type = "dynamic"), but I did not get a different behavior in Shaka than I described in my previous post.

> Another idea : if I modify the FFmpeg behavior by constantly generating a type="static" manifest (which will grow during the transcoding), can I force Shaka to regularly fetch and update the manifest without resetting the whole playback engine (I did not find such an API in the doc, but maybe I missed something) ?

No, there is no API for that.  If type=dynamic and there is an update period, we will update it, even if it's VOD.  We call this an "in-progress recording".  If you're doing it the way we would expect, you'll see `player.isLive() == false` and `player.isInProgress() == true`, and there will be no assertion complaining about our VOD model.

What do you get from `isLive()` and `isInProgress()`?  Do you still see the assertion?

**Comment by jrosener** [comment]
I performed a test with a file which lasts 7h15m3s (= 26143 sec). In case I add `mediaPresentationDuration="PT7H15M43.3S"` in the `type="dynamic"` manifest, I can see `player.isLive() == false` and `player.isInProgress() == true`. However the update of the seek range is still wall clock time based.

**Case type="dynamic" only.**
```
The audio has now been loaded!
seekRange: 0 => 2828.5 isLive: true isInProgress: false
Updating manifest...
seekRange: 0 => 2833.6 isLive: true isInProgress: false
Updating manifest...
seekRange: 0 => 2840.1 isLive: true isInProgress: false
Updating manifest...     (Transcoding is done, type switched to "static")
seekRange: 0 => 26143.3 isLive: false isInProgress: false
```

**Case type="dynamic" + mediaPresentationDuration="PT7H15M43.3S"**
```
The audio has now been loaded!
seekRange: 0 => 2689.8 isLive: false isInProgress: true
Updating manifest...
seekRange: 0 => 2695.5 isLive: false isInProgress: true
Updating manifest...
seekRange: 0 => 2701.6 isLive: false isInProgress: true
Updating manifest...     (Transcoding is done, type switched to "static")
seekRange: 0 => 26143.3 isLive: false isInProgress: false
```
Shaka is also generating a lot of warnings like `Refusing to rewrite original references on update!` after it fetched and update the manifest. I don't know if it is important or not in this discussion.

**Comment by joeyparrish** [comment]
Yeah, that makes sense.  You're transcoding faster than real-time, and Shaka Player only understands real-time live streams and static VOD streams.  So Shaka Player will update the seek range one second per second until you say it's complete.

I think what you're doing is just not what Shaka Player was designed for, unfortunately.
