### ISSUE TITLE
cannot get tracks of cea608/708 on CAF reiceiver

### ISSUE THREAD

**Issue by kevinbol** [google/shaka-player#2262]
hi, when I load a link which includes cea608/708 tracks on CAF receiver, TextTracksManager.getTracks() cannot get the cea608/708 tracks.
is there any else method to get cea608/708 tracks and activate it ?

test link: https://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8
or https://vm2.dashif.org/dash/vod/testpic_2s/cea608.mpd

BTW, webvtt tracks can be get by TextTracksManager.getTracks()

**Comment by theodab** [comment]
This is the Shaka Player team. We do not make or maintain the CAF. You will have to contact the Google Cast team for support: https://developers.google.com/cast/support

If you were using Shaka Player directly, I would suggest you set the `forceTransmuxTS` config value, [as suggested by our FAQ](https://shaka-player-demo.appspot.com/docs/api/tutorial-faq.html). However, I do not know how you would do that through the interface of the CAF; you'll have to rely on the Cast team for that info.
