### ISSUE TITLE
native text display fails to render nested TTML cues

### ISSUE THREAD

**Issue by jkyto** [google/shaka-player#2263]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.6

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Custom app

**If custom app, can you reproduce the issue using our demo app?**
 

**What browser and OS are you using?**
Chrome on a laptop, Tizen and WebOS

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
webOS 3.2-4.7 and Tizen 3-5

**What are the manifest and license server URIs?**
Will be provided by email.

**What did you do?**
Watched the video and sometimes the subtitles are not showing.

**What did you expect to happen?**
The subtitles to be rendered.

**What actually happened?**
The first and last paragraphs are rendered but the rest are not. The rendering works with the same manifest on version 2.5.5 but not on 2.5.6. Couldn't see anything unusual on the logs.
````
<p begin="00:04:46.680" end="00:04:49.360" region="r0" style="p">
    Lorem ipsum dolor,<br/>
    consectetur adipisicing elit.
   </p>
   <p begin="00:05:25.560" end="00:05:29.240" region="r0" style="p">
    <span tts:fontStyle="italic">-Excepteur sint.</span><br/>
    <span tts:fontStyle="italic">-Duis aute.</span>
   </p>
   <p begin="00:05:33.360" end="00:05:36.040" region="r0" style="p">
    <span tts:fontStyle="italic">Excepteur sint...</span>
   </p>
   <p begin="00:05:36.200" end="00:05:39.800" region="r0" style="p">
    <span tts:fontStyle="italic">Aliquip ex ea commodo,</span><br/>
    <span tts:fontStyle="italic">Officia Deserunt.</span>
   </p>
   <p begin="00:05:41.520" end="00:05:44.520" region="r0" style="p">
    <span tts:fontStyle="italic">Mollit</span> Fugiat Nulla Pariatur?
   </p>
````

Possibly related to this https://github.com/google/shaka-player/pull/1962 ?

**Comment by michellezhuogg** [comment]
Tested with the file you sent us, and all the captions are displaying. Let us know if you still have any issue! Thank you!

**Comment by jkyto** [comment]
Thanks for reply and the fix. I tested with the latest version using the demo app. The problematic parts are now visible but are aligned oddly to the left and font size is smaller than on the other parts.

**Example**

Normal:
```
<p begin="00:04:46.680" end="00:04:49.360" region="r0" style="p">
    Lorem ipsum dolor,<br/>
    consectetur adipisicing elit.
   </p>
```

Aligned to the left and font size pretty small:
```
   <p begin="00:05:25.560" end="00:05:29.240" region="r0" style="p">
    <span tts:fontStyle="italic">-Excepteur sint.</span><br/>
    <span tts:fontStyle="italic">-Duis aute.</span>
   </p>
```

**Comment by jkyto** [comment]
Looking more into this. Actually 2.5.8 did not fix the issue. All the subs work when using Shaka Controls in the demo app but after switching to native controls (build=compiled;nativecontrols), the problem is there and `cue.text` is empty for those problematic parts.

**Reproduce:**
- `https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=fi-FI;uilang=en-US;asset=<PROVIDED_MANIFEST_THERE>;panel=CUSTOM%20CONTENT;build=uncompiled;nativecontrols`
- Seek to around 5:26

We use native controls in our app. Subtitles work fine on 2.5.5 but does not on 2.5.6-2.5.8. I believe this problem is affecting ChromeCast users as well since the ShakaPlayer was updated to version 2.5.6 in January.

Let me know if you need more information.

**Comment by joeyparrish** [comment]
I've updated the title of the issue to reflect the fact that this is a problem specifically for native text display.  This does not yet support nested cues.

**Comment by joeyparrish** [comment]
SimpleTextDisplayer should iterate through nestedCues and flatten them out.  This will not accurately represent TTML nested cues, but it will be as close as we can get with the VTTCue and TextTrackCue APIs in browsers today.
