### ISSUE TITLE
MPEG2-TS HLS video not playing on Chinese browsers

### ISSUE THREAD

**Issue by implicit-invocation** [google/shaka-player#2264]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.6

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Both

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
Windows 10, QQ (https://browser.qq.com/) and 360 (https://browser.360.cn/) browser

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What did you do?**

Load a MPEG2-TS HLS playlist on Chrome, QQ and 360 browsers.

**What did you expect to happen?**
The video plays on all browsers

**What actually happened?**

Video only playing on Chrome, not QQ and 360.

**Comment by theodab** [comment]
[According to caniuse.com](https://caniuse.com/#feat=mediasource), QQ browser does not implement the Media Source Extensions API, which is a requirement for Shaka Player to work. They don't have any info on 360 browser, but it might have the same problem.
If a browser doesn't support MSE, there's not much we can do; we default to using the browser's builtin media playback if MSE isn't available, but that only helps if the browser natively supports MPEG2-TS.

**Comment by implicit-invocation** [comment]
I tested again with the same video, the same browser but using videojs, the video loads and plays fine. How did they do that?

**Comment by theodab** [comment]
videojs is mostly a wrapper on a number of different players. So presumably one of their builtin player modules can render MPEG-2 TS content without using MediaSource.
I'm not a videojs expert, so I couldn't tell you exactly which one is working on qq browser. It looks like one of their defaults is an Adobe Flash-based plugin; that might be it.

**Comment by joeyparrish** [comment]
Please visit this page in QQ and copy the results here:

https://shaka-player-demo.appspot.com/support.html

That will give us a detailed list of what is and is not supported by QQ.  Then we can decide whether it makes sense to add it to our list of supported browsers.  Thanks!

**Comment by joeyparrish** [comment]
Closing this stale external (non-Shaka) issue. If you disagree, please reply with @shaka-bot reopen, and it will be automatically reopened.
