### ISSUE TITLE
possibility of seamlessly playing queued videos

### ISSUE THREAD

**Issue by jell0nek** [google/shaka-player#2265]
Hi All,

I'd like to build a solution based on shaka-player which is required to play videos one after another in a completely seamless way. When I'm trying to switch between two shaka-players (playing video A and then video B) a small delay can be seen. When I set in a player video source to B after A video has ended playback, also a gap is visible.

I'd like to be able during video A to append somehow video B at the end of the source buffer to see totally seamless video AB.

I'd like to ask if this is feasible with shaka-player or what should be done to make it possible.

(*A and B can be raw mp4 files but preferably DASH/HLS).

Thank you in advance for the answers.
Best Regards,
Jakub

**Comment by TheModMaker** [comment]
There is no way to do it currently, but #764 and #880 may fit your case.

As a workaround, you could create a second `<video>` element and a second `shaka.Player` instance, load the next content, and keep it paused.  Once you get the `ended` event from the first video, swap the `<video>` elements.

**Comment by jell0nek** [comment]
Hi, 
thank you for your answer. 

I've already tried that solution:
- two shaka players, `P1` with video `A`, `P2` with video `B`;
- `P1` is started, `P2` is already prepared to be played
- video `A` from `P1` sends `ended` event, I switch in DOM `P1` visibility to false, `P2` to true and start playing `B`;
As a result, there is no blink on the page - which is great, but it seems that `B` is slowing down a little bit at the beginning of the playback and getting to normal speed in a few animation frames. This gives me a bad and visible effect in a place where I stitch the videos.

As an alternative solution, I used rendering a video on a canvas to avoid html video elements swapping in DOM. So till `P1` is playing I draw `P1.getMediaElement()` on the canvas, when received `ended` event I start drawing `P2.getMediaElement()`. It gives me same effect as above.

I achieve the best/ultimate effect when I use appendBuffer() directly on a source buffer in a simple solution (without any player) created by me.
I'd love to use shaka player to take advantage of all its features but this stitching part is crucial in my project.

Please let me know if you maybe have some other solution in your mind which I could test.

Thank you and regards,
Jakub

**Comment by joeyparrish** [comment]
Hi Jakub,

#764 is exactly what you're asking for.  That is currently blocked on a large refactor, #1339.  But once we have flattened the manifest structure, it should become possible to append new segment references to the end of existing content.

Does this help?

**Comment by jell0nek** [comment]
Hi Joey,

thank you for your answer, yes it helped, so in this case, I'm going to wait for that feature and in the meantime, I will try to apply a non-shaka solution in my project ;)

Thank you one more time.
Jakub
