### ISSUE TITLE
preferredAudioLanguage and preferredTextLanguage are not working in src mode (Safari - HLS)

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#2269]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes

**What version of Shaka Player are you using?** 2.5.6

**Can you reproduce the issue with our latest release version?** Yes

**Can you reproduce the issue with the latest code from `master`?** Yes

**Are you using the demo app or your own custom app?** Both

**If custom app, can you reproduce the issue using our demo app?** Yes

**What browser and OS are you using?** Safari 13.0.3, macOS 10.14.6

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

Manifest: https://storage.googleapis.com/shaka-demo-assets/angel-one-hls/hls.m3u8

**What did you do?**

Set a different combinations of preferredAudioLanguage and preferredTextLanguage
And load the previous stream

**What did you expect to happen?**
The preferredAudioLanguage and preferredTextLanguage are used to choose the audio and subtitle.

**What actually happened?**

The preferredAudioLanguage and preferredTextLanguage are ignored

Note: If i don't use src mode, it's working well.

**Comment by joeyparrish** [comment]
That makes sense.  We use those preferences in the logic for our initial track selection for MediaSource-based playback.  We don't have any logic that would apply those to src= HLS playbacks.

It may be possible, so I'll mark it as "enhancement".  But we haven't looked into it yet.
