### ISSUE TITLE
HLS 4023: Bandwidth is required but on Safari works correctly without it

### ISSUE THREAD

**Issue by alexandercerutti** [google/shaka-player#2270]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

Yes

**What version of Shaka Player are you using?**

2.5.6

**Can you reproduce the issue with our latest release version?**

Yes

**Can you reproduce the issue with the latest code from `master`?**

Didn't tested.

**Are you using the demo app or your own custom app?**

Custom App

**If custom app, can you reproduce the issue using our demo app?**

Yes (see more below for details)

**What browser and OS are you using?**

Chrome and Safari, macOS 10.15

**What are the manifest and license server URIs?**

-

**What did you do?**

See the description for more details.

**What did you expect to happen?**

Bandwidth HLS attribute not to be required

**What actually happened?**

Error on Bandwidth HLS attribute.

___

So, I was testing for VOD HLS contents and discovered this: our content provider serves us HLSs without BANDWIDTH attribute.

So this is the specific steps that I made to discover this:

1) I took a VOD HLS url and used custom app to reproduce it on Safari. It went fine.
2) I tried with the same URL, on Chrome: it failed with error 4023 (HLS_REQUIRED_ATTRIBUTE_MISSING) and data reporting attribute **BANDWIDTH** is missing.
3) I tried again on Safari with configuration `streaming.useNativeHlsOnSafari => false` and got the same error.
4) Tried all again on the demo app and got the same results.

Also, this is the same result I got when I tested for https://github.com/google/shaka-player/issues/2267 and is linked (because part of the same investigation) to https://github.com/google/shaka-player/issues/2268 - just to have more context.

So, what seems to be the problem, is that Safari doesn't require BANDWIDTH attribute while Shaka does. Is there a specific reason for this or is it just a mistake in the code?

I'm going to send you via email one of the URLs with some instructions, so you can test by yourself.

Thank you!

**Comment by alexandercerutti** [comment]
The URL I've sent you might have been fixed with BANDWIDTH value, so it might not be working anymore. You have to try with a manifest without the BANDWIDTH attribute.

**Comment by TheModMaker** [comment]
We require it because it is the backbone of how ABR works.  Without it we have no way of guessing which streams to pick.  This may work with only a single stream, but with multiple streams, it becomes difficult to impossible to determine what streams we have enough bandwidth to play.

Also, according to the HLS spec, this is a required attribute:

    4.3.4.2.  EXT-X-STREAM-INF

    ...
    Every EXT-X-STREAM-INF tag MUST include the BANDWIDTH attribute.

**Comment by alexandercerutti** [comment]
@TheModMaker Okay, that's good to know. Thank you.
So, you mean that probably Safari internal implementation allows playing without the BANDWIDTH attribute because it may know when it has enough bandwidth?

**Comment by TheModMaker** [comment]
Yes.  It may parse the init segment or fetch the first segments from the streams to guess the bandwidth.  There are other ways of guessing how much bandwidth is needed to play a stream, but the best way is explicitly with the BANDWIDTH attribute.

**Comment by alexandercerutti** [comment]
Okay, thank you for the explanations!
