### ISSUE TITLE
Changing default video quality

### ISSUE THREAD

**Issue by amit08255** [google/shaka-player#2272]
I want to set custom default video quality on player load. Please help me how this can be done.
Thank you very much.

**Comment by theodab** [comment]
The video quality we pick on load is based on bandwidth estimates. Our ABR code will calculate a bandwidth estimate based on download rates it sees, but you can change the default estimate we use before we have enough data with the `abr.defaultBandwidthEstimate` configuration value. This will cause it to start at a different quality; if you want the quality it starts at to be high, you can set a high default bandwidth, and vice-versa.
```js
myPlayer.configure('abr.defaultBandwidthEstimate', myDefaultBandwidth);
```

**Comment by amit08255** [comment]
Yes please.
