### ISSUE TITLE
Feature Request: expose video/audio/text http request handler

### ISSUE THREAD

**Issue by leandromoreira** [google/shaka-player#228]
**Good case for it**: a dev could provide a p2p (webrtc) implementation. Maybe this could be something to consider to 2.0

> I was quickly looking at the code to find the spot where this `extension` could be done but I couldn't find. :(
```javascript
shaka.player.Player.prototype.load
shaka.player.StreamVideoSource.prototype.load 
shaka.player.StreamVideoSource.prototype.attach
shaka.player.StreamVideoSource.prototype.onMediaSourceOpen_
shaka.player.StreamVideoSource.prototype.createAndStartStreams_ 
shaka.player.StreamVideoSource.prototype.createStreams_ 
shaka.player.StreamVideoSource.prototype.startStreams_
```

**Comment by joeyparrish** [comment]
We will offer plugins for networking in 2.0.  You will be able to implement any URI scheme you like any way you want.  We'll be publishing details soon.

**Comment by leandromoreira** [comment]
Thanks :+1:

**Comment by joeyparrish** [comment]
We landed the new NetworkingEngine with this functionality in ab127e6.

**Comment by leandromoreira** [comment]
Thank you so much @joeyparrish :congratulations:
