### ISSUE TITLE
missing license request when Shaka runs on Edge

### ISSUE THREAD

**Issue by kjyoun** [google/shaka-player#2281]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
2.4.7

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `master`?**
yes

**Are you using the demo app or your own custom app?**
demo app

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
Edge 44.18362.449.0
Windows 10 Pro

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
manifest url: https://storage.googleapis.com/gtvchrome-public/data/manifest.mpd
license url: https://drm-stage.apis.anvato.net/cenc?eqp=TKEUCUaR15BlGgzAcu7YA2rUhwZ6

**What did you do?**

1. load demo player on Edge browser
https://v2-4-7-dot-shaka-player-demo.appspot.com/demo/#asset=https://storage.googleapis.com/gtvchrome-public/data/manifest.mpd;license=https://drm-stage.apis.anvato.net/cenc?eqp=TKEUCUaR15BlGgzAcu7YA2rUhwZ6;lang=en-US;build=uncompiled
2. click "load"

**What did you expect to happen?**
video starts playback

**What actually happened?**

video doesn't start

Note
- shaka player sends license request only for audio track, not sending a license request for video track
- if you listen to 'encrypted' event on video tag, 'encrypted' event is fired only once.
- With manifest with only video tracks (SD + HD)[1], video can play and shaka player sends license requests twice (at the beginning for SD track and afterwards HD track)
- looks like that there is some race condition, since I saw once video play once when network delay was high. (still trying to reproduce it)
- on Chrome browser, you can see video play with the same manifest/license url, using WV DRM

---
[1] 
manifest: https://storage.googleapis.com/gtvchrome-public/data/manifest.video-only.mpd
license: https://drm-stage.apis.anvato.net/cenc?eqp=TKEUCUaR15BlGgzAcu7YA2rUhwZ6

**Comment by kjyoun** [comment]
found why I saw video played once.
- with hacked manifest[1], now I could play video on Edge
- hacked manifest has SD representation twice at different bandwidth (SD1 at 500k. SD2 at 1500k), which makes shaka player/Edge browser sends license request for SD2 video track,  when it switch representations from SD1 to SD2. Since SD1 and SD2 representations use same key, it enables playback of SD1 representation, though shaka/Edge browser misses the license request for SD1 respresentation.

---
[1] 
manifest: https://storage.googleapis.com/gtvchrome-public/data/manifest.hack.mpd
license: https://drm-stage.apis.anvato.net/cenc?eqp=TKEUCUaR15BlGgzAcu7YA2rUhwZ6

**Comment by kjyoun** [comment]
found out that a workaround for this issue is to embed pssh data in manifest.
With the manifest that has pssh embedded[1], video plays on Edge browser.


---
[1]  https://storage.googleapis.com/gtvchrome-public/data/manifest.pssh.mpd

**Comment by joeyparrish** [comment]
Thanks for all the hard work you've done to diagnose the problem!

It would seem that the PSSH in the content itself is wrong.  The DASH Inter-Op Points (DASH-IOP) recommend that you always embed a PSSH in the manifest anyway.  Since this seems to fix your issue, I would recommend that you follow the DASH IOP guidelines on this whenever possible.

Does this help?

**Comment by kjyoun** [comment]
Thanks for the comment.

Can you provide more details about why pssh is not valid?

I think that pssh data is valid, since
- asset plays after successful license acquisition, when I put either only audio or only video in manifest. (so that all init data has same pssh)

**Comment by joeyparrish** [comment]
I don't know for a fact that the PSSH is invalid.  I'm just guessing based on your results when you embed the PSSH in the manifest.

It could be that we're doing something wrong, but I'm not sure what that might be.

**Comment by kjyoun** [comment]
update title to describe the issue clearly.

**Comment by joeyparrish** [comment]
I'm getting a CORS error when I try to reproduce this issue.  It seems that the MPD is not available cross-origin to nightly-dot-shaka-player-demo.appspot.com.  Can you make it available to all origins so I can test on various versions of Shaka Player?

Alternately, can you please test a newer version?  I see now that your report specifies v2.4.7, but we're no longer patching v2.4.x.  We keep an index of all releases so you can more easily try various versions: https://index-dot-shaka-player-demo.appspot.com/

**Comment by kjyoun** [comment]
This is an issue on Edge browser.
With the new Edge browser (chromium-based), the problem does not happen.

The workaround that we found on (old) Edge browser is to put pssh under ContentProtection in Manifest. Then Shaka player sends all necessary license request.
