### ISSUE TITLE
Configuring serverCertificate not working

### ISSUE THREAD

**Issue by mraavi** [google/shaka-player#2282]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
YES

**What version of Shaka Player are you using?**
2.5.3

**Can you reproduce the issue with our latest release version?**
YES

**Can you reproduce the issue with the latest code from `master`?**
YES

**What browser and OS are you using?**
MAC / Chrome

**What did you do?**
Try to set the ServerCertificate though configuration

```js
mPlayer.configure({
            drm: {
                ...
                advanced: {
                    'com.widevine.alpha': {
                    serverCertificate: cert1, 
                        'videoRobustness': 'SW_SECURE_CRYPTO',
                        'audioRobustness': 'SW_SECURE_CRYPTO'
                    }
                }
            }
        });
```

Got following Error
```
{"severity":2,"category":6,"code":6004,"data":["Failed to execute 'setServerCertificate' on 'MediaKeys': Rejected with system code (17)"],"handled":false,"message":"Shaka Error DRM.INVALID_SERVER_CERTIFICATE (Failed to execute 'setServerCertificate' on 'MediaKeys': Rejected with system code (17))"
```

If the Certificate is requested though proxy license server then it works fine. 
```js
mPlayer.getNetworkingEngine().registerResponseFilter(function (type, response) {
                    if (type == shaka.net.NetworkingEngine.RequestType.LICENSE) {
                      var wrappedString = shaka.util.StringUtils.fromUTF8(response.data);
                      var lRspJson = JSON.parse(wrappedString);
                      response.data = new Uint8Array(0);
                      response.data = shaka.util.Uint8ArrayUtils.fromBase64(lMsgJson.license);
                    }
                  });
```
I have tried to configure same Uint8Array (response.data) as Server Certificate. But it returns 6004 error.
I wanted to avoid Certificate request each time playback started.
I have refereed following issues, But could not get to solution here.
https://github.com/google/shaka-player/issues/810
https://github.com/google/shaka-player/issues/1794

Any help / suggestion is appreciated.

**Comment by joeyparrish** [comment]
Widevine's server certificate format in a license response differs from the format passed to `setServerCertificate`.  I apologize for the inconvenience.

Please reach out to Widevine for support on getting the cert in the correct format.  In the mean time, I will raise an issue internally to see if we could get Widevine to accept both formats in `setServerCertificate` in the future.

**Comment by joeyparrish** [comment]
Widevine

**Comment by joeyparrish** [comment]
The Widevine team has just informed me that the correctly-formatted cert for their cloud-hosted license server can be retrieved publicly from:

UAT: https://storage.googleapis.com/wvmedia/cert/cert_license_widevine_com_uat.bin
Prod: https://storage.googleapis.com/wvmedia/cert/cert_license_widevine_com_prod.bin

If the service provider runs their own custom license server (full server, not a Widevine license proxy), then you will need to get the correct data from them.

Does this help?

**Comment by mraavi** [comment]
Thanks. It worked.

**Comment by joeyparrish** [comment]
It seems this was resolved. If you disagree, please reply with @shaka-bot reopen, and it will be automatically reopened.
