### ISSUE TITLE
Tagging/modifying/filtering logs

### ISSUE THREAD

**Issue by alexandercerutti** [google/shaka-player#2284]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

Yes

**Is your feature request related to a problem? Please describe.**

I'd like to filter and see the logs only of uncompiled shaka. Currently they are miscellaneous and they cannot be filtered (our application logs very much, so we have to filter them!).

**Describe the solution you'd like**

I'd like internal logging methods to accept the message to print but to prepend to it an identifier (like "[SHAKA]", maybe?) through which we can filter in browsers console.

For example:

```
shaka.log.info('Using Apple-prefixed EME');
```

should output something like:

```
[SHAKA-PLAYER] Using Apple-prefixed EME
[SHAKA] Using Apple-prefixed EME
<SHAKA> Using Apple-prefixed EME
...
```

**Describe alternatives you've considered**

-

**Additional context**

-

**Comment by joeyparrish** [comment]
I would recommend that you monkey-patch the uncompiled build for this:

```js
shaka.log.info = (...args) => {
  console.info('[SHAKA]', ...args);
};
```

This simplistic way of doing it will remove any checks against the log level, but I assume since you want to do your own filtering, you would be okay with this.

Here's a snippet that should do the job for all log methods:

```js
const logMap = {
  'alwaysError': 'error',
  'alwaysWarn': 'warn',
  'error': 'error',
  'warning': 'warn',
  'info': 'info',
  'debug': 'debug',
  'v1': 'debug',
  'v2': 'debug',
};

for (const shakaLogMethod in logMap) {
  const consoleLogMethod = logMap[shakaLogMethod];
  shaka.log[shakaLogMethod] = (...args) => {
    console[consoleLogMethod]('[SHAKA]', ...args);
  };
}
```

Does this help?

**Comment by alexandercerutti** [comment]
I think this is acceptable 😄 Thank you @joeyparrish!
P.s. Shaka logging V2 is not printing all the logs I was expecting and that debugging guide told!

**Comment by joeyparrish** [comment]
The specific examples in the debugging guide may have been copied from an older version of the library.  A lot has changed in the last 2-3 release cycles.
