### ISSUE TITLE
BufferingGoal of 0 doesn't work?

### ISSUE THREAD

**Issue by VictorChen** [google/shaka-player#2285]
Using Shaka Player v2.5.6, my use case is to render a video with no prefetching. However, once the play button is clicked, wait until there's at least 4 seconds of content buffered before playing.

I did this by setting the bufferingGoal to be 0 initially and then updating it later:

```js
player.configure({
  manifest: {
    dash: {
      ignoreMinBufferTime: true
    }
  },
  streaming: {
    rebufferingGoal: 0,
    bufferingGoal: 0
  }
});

video.addEventListener("playing", () => {
  player.configure({
    streaming: {
      rebufferingGoal: 4,
      bufferingGoal: 8
    }
  });
});
```

This does not work... video never plays and shows a constant spinner. Is there a better way to achieve this?

Reproducer:
https://codesandbox.io/s/laughing-bartik-p92oq

**Comment by joeyparrish** [comment]
If your buffering goal is zero, you've met that goal without fetching any segments.  So it won't fetch any segments with a buffering goal of zero.

Try a small non-zero number, such as 0.1.  That should cause the first segment to be fetched only.

To avoid autoplay, just don't set the `autoplay` attribute on the video element or call `video.play()` after `player.load()`.  In your play button's click handler, you can increase the buffering goal and call `video.play()`.  If you're using our UI or the native UI of the browser, you can listen for the `playing` event to increase the buffering goal.

Does this help?

**Comment by VictorChen** [comment]
@joeyparrish it still doesn't achieve what I want. By setting it to a small non-zero number (0.1), it will still fetch the first segment of the video (eg: 2 seconds, including audio). I have a page with multiple videos and I don't want each video to start downloading any video content on page load unless the user has clicked play.

I don't have `autoplay` enabled, what I want to do is once the user has clicked play, start downloading video content until there's enough (eg: 4 seconds), and THEN start playing the video (don't start playing immediately). Let me know if that doesn't make sense.

**Comment by joeyparrish** [comment]
Ah, I see.  You don't want anything downloaded at all until the user clicks play?  In that case, just wait to call `player.load()`.

**Comment by VictorChen** [comment]
hmm that's going to be more complicated. Are you proposing that I render a `<video>` and then once the user clicks play, I then initialize shaka and call `player.load()`?

The problem is that if I set the `src` on the video, it will start playing the native video and then when shaka is loaded, it resets the video...

If I don't set the `src` on the video, then the play button is disabled.

**Comment by joeyparrish** [comment]
So you're using browser native controls, then?  I didn't see that mentioned before.

`player.load()` loads not just the manifest, but media segments, too.

You might have been close to correct with your first attempt, though.  Try using the `play` event instead of the `playing` event.  That might fire even when there's nothing buffered, allowing you to change the config and get the player to stream.  I suspect the `playing` event only fires when playback actually starts, which can't happen with a goal of `0`.

Does this help?

**Comment by VictorChen** [comment]
ah I see, that works! The only minor thing is that it shows a constant spinner initially (before clicking play), any idea why? eg:

https://codesandbox.io/s/angry-feynman-bnug6

**Comment by joeyparrish** [comment]
If you're using the browser's native controls, you have no control over that spinner.  It's built-in, and based on the "ready state" of the element.  It has a source, but no data, so it's buffering.

If you use the Shaka Player UI library, you can style the spinner to hide it during this pre-playback state and re-enable it after the user clicks play.

**Comment by VictorChen** [comment]
got it, thanks!

**Comment by VictorChen** [comment]
@joeyparrish even though the video won't buffer until you click play, it still makes requests for the video, why is that? See:

![Screen Shot 2019-12-11 at 4 55 13 PM](https://user-images.githubusercontent.com/1408813/70663797-1a67a300-1c37-11ea-8023-e689c3be5679.png)

eg: `v-0576p-1000k-vp9.webm`

You can see this here:
https://p92oq.csb.app/

**Comment by theodab** [comment]
That's Shaka Player making `OPTIONS` requests (to ask for permission for cross-site access), and then getting the init segments. It's not actually loading any media.
