### ISSUE TITLE
Changing abr.defaultBandwidthEstimate does not change video quality in Auto.

### ISSUE THREAD

**Issue by amit08255** [google/shaka-player#2287]
I am using Shaka player in a project. I want to use a feature like Youtube in shaka player (where quality auto set to your last video quality).
I have tried setting **abr.defaultBandwidthEstimate** but it didn't work.

```js

//Link to MPEG-DASH video
		var manifestUri = 'video MPD link here';

		//Initialize shaka player
		var player = new shaka.Player(videoPlayerElement);

		player.configure({
            drm: {
              servers: { 'com.widevine.alpha': "widevine URL" }
			},
			abr: {
				defaultBandwidthEstimate: 10000000
			}
          });

```

I was trying to set 720p using defaultBandwidthEstimate when video start for testing.

**Comment by theodab** [comment]
If you want Shaka Player to remember the quality that it was at previously, it kind of does that already. Unless you are making a new player instance for each playback, the ABR system will remember its previous readings, and will stick to an appropriate automatic quality based on that.

When you said that `defaultBandwidthEstimate` isn't working, what do you mean? Like, does it pick a lower-quality variant by default, even when after you've set the `defaultBandwidthEstimate` high? Or is it picking a higher-quality version then adapting down, once it sees your actual bandwidth?
You can track when it adapts by listening to `adaptation` events:
```js
player.addEventListener('adaptation', () => {
  const activeTrack = player.getVariantTracks().filter((t) => t.active)[0];
  console.log('player adapted, new bandwidth=' + activeTrack.bandwidth);
});
```

**Comment by amit08255** [comment]
@theodab 
Thank you for explaining how it works. Let me give you an overview of what I need.
I need a functionality like this -
User visit my video listing page on app and plays a video. When he switches video quality of a video, that quality is saved to localstorage and next time he plays another video, the player automatically start video with that quality, Can you please guide me how this can be done? It will be a huge help.

When I tried `defaultBandwidthEstimate` with a value `10000000` which I expected it to start video at higher quality, the video player started playing at lower quality (in auto mode).

Please guide me how I can achieve the functionality mentioned above.
Thank you.

**Comment by theodab** [comment]
When you call `player.getStats()` while playing, what does the `switchHistory` value say? That should contain a list of adaptation events, and info at each point (bandwidth estimate, etc). This would be helpful to find out if `defaultBandwidthEstimate` is being ignored, or if it's being quickly replaced with a more accurate bandwidth estimate, or whatever.

It sounds, though, like `defaultBandwidthEstimate` might not actually be the right tool for you to begin with. If you want the user to select specific video qualities and have the app re-apply those qualities later, it might make more sense to disable ABR entirely (by setting the config value `abr.enabled` to `false`), and pick variants manually using `player.selectVariantTrack()`; you can get a list of variant tracks using `player.getVariantTracks()`.

**Comment by amit08255** [comment]
Thank you very much @theodab  for the solution.
