### ISSUE TITLE
LOAD_INTERRUPTED should be a bug not an exception

### ISSUE THREAD

**Issue by mihaiav** [google/shaka-player#2289]
The player seems to throw an exception with code `LOAD_INTERRUPTED` if the loading process is interrupted.
I've read several issues and it seems the advice is to call unload and wait for it to resolve. My question is why shaka is not "handling" that exception ? Why would I care that the loading was interrupted ? Obviously I know it was interrupted because I did that(i.e. I load a new manifest before the loading on the previous one is completed).

My use-case is an audio playlist and usually clients like to shuffle it quite fast(using arrow keys). If the internet connection is slow or the video/audio content is just loading slow I get a lot of exceptions like this.  As far as I'm concerned I need the latest item from "session"(i.e. last item that was called into "load" method) to load as soon as the player can do that. The load of the previous item(s) should be aborted. How am I supposed to do this?

**Comment by joeyparrish** [comment]
> I've read several issues and it seems the advice is to call unload and wait for it to resolve. My question is why shaka is not "handling" that exception ? Why would I care that the loading was interrupted ? Obviously I know it was interrupted because I did that(i.e. I load a new manifest before the loading on the previous one is completed).

Shaka is **generating** the exception, so it's not a matter of not handling it.

You may not necessarily care that it was interrupted, and hopefully you do know it was interrupted.  But resolving the Promise returned from load() would imply that it loaded successfully.  It did not, so we reject it instead.  To make sure you know why it was rejected, we use LOAD_INTERRUPTED, which we intend to be a meaningful error code you can use to differentiate this from a real error.

The third option, beyond resolving or rejecting the promise, is to do neither, but this could hang any logic that was `await`ing the result.  So this is out of the question.

I hope this helps explain!
