### ISSUE TITLE
Getting a shaka.ui.Controls instance

### ISSUE THREAD

**Issue by yvashar** [google/shaka-player#2292]
Imported using, const shaka = require("shaka-player/dist/shaka-player.ui.js") but could not access shaka.ui.Controls.isCastAllowed()  and getting error as isCastAllowed not a function.

**Comment by theodab** [comment]
Could you please provide more information about this problem?
What version of Shaka Player are you using? What are you using to load Shaka Player? A repro page would be ideal.

**Comment by joeyparrish** [comment]
`isCastAllowed()` is an instance method.  You referred to it in your original post as `shaka.ui.Controls.isCastAllowed()`, which would only work for static methods.  Try this instead:

```js
video.ui.getControls().isCastAllowed();
```

Does this help?

**Comment by yvashar** [comment]
@joeyparrish we are using a custom ui. When I tried video.ui.getControls().isCastAllowed(), ui is undefined.

**Comment by theodab** [comment]
The `ui` property on the video is added by the creation of the Shaka Player UI. If you aren't using our UI, it won't be present.
Also, the `isCastAllowed` method doesn't expose anything useful if you aren't using the UI. It just returns whether the UI is allowed to show the cast button or not.
If you're interested in figuring out whether casting is _possible_, then once you make a `CastProxy` you can call the `canCast` instance method on it.
