### ISSUE TITLE
Shaka Player does not support the latest DD+JOC signaling for DASH

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#2296]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** yes

**Is your feature request related to a problem? Please describe.**

ShakaPlayer does not support the latest DD+JOC signaling for DASH. The spec is https://www.etsi.org/deliver/etsi_ts/103400_103499/103420/01.02.01_60/ts_103420v010201p.pdf , annex D (page 80).

```
D.2.2.1 Extension type
Presence of the enhanced AC-3 extension as defined in the present document is signalled with a DASH supplemental
property descriptor using the schemeIdUri tag:dolby.com,2018:dash:EC3_ExtensionType:2018.
The value of this DASH descriptor shall be the three character string JOC. 
```

**Additional context**

Link to test:
http://d9zmmjtv72w5o.cloudfront.net/OnDelKits_dev/DDP/Dolby_Digital_Plus_Online_Delivery_dev_portal/Test_Signals/muxed_streams/DASH/Live_MPD/ChID_voices_1280x720p_25fps_h264_6ch_640kbps_ddp_joc.mpd

Note: Tizen will support it in 2020 (https://review.tizen.org/git/?p=platform/framework/web/chromium-efl.git;a=commit;h=0a9361ac8f02361eb52cc13155e920bc19c8fddd )

**Comment by avelad** [comment]
Related to https://github.com/google/ExoPlayer/issues/6636

**Comment by theodab** [comment]
I'm not sure what platforms support E-AC3 JOC content yet, so I wasn't able to actually test it in a practical way, but I think that CL is to-spec.
