### ISSUE TITLE
Shaka player is not working on iPhone device 

### ISSUE THREAD

**Issue by ramakanthkoigura** [google/shaka-player#2298]
working on android device browsers and desktop but not working on ios?
video is not loading ?

please suggest any changes needed to play video on ios?

**Comment by theodab** [comment]
What version of Shaka Player are you running? We only added iOS support in v2.5. And what version of iOS are you running? We don't support iOS 9 (see #1920).

**Comment by TheModMaker** [comment]
We only support playing HLS and direct MP4 playback on iOS (through `src=`).  We don't support DASH on iOS since we can't use `MediaSource`.  If you're playing HLS and getting an error, there may be nothing we can do since it is the browser that handles playing it.

**Comment by ramakanthkoigura** [comment]
Hi, @theodab @TheModMaker 
We are using v2.4.4. tested on IOS 13.HLS content
Video is not loaded displays blank screen.

**Comment by TheModMaker** [comment]
We only support iOS on v2.5+.  Be sure to call `shaka.Player.isBrowserSupported()` before creating the player; if you did, it would return `false` because that version of Shaka Player doesn't support iOS.
