### ISSUE TITLE
Support of Media playlists?

### ISSUE THREAD

**Issue by index23** [google/shaka-player#2300]
Why do you support only reading of Master playlist (https://github.com/google/shaka-player/issues/1580#issuecomment-422065560)? By the standard both playlists are valid, https://tools.ietf.org/html/rfc8216#page-10
`A Playlist is a Media Playlist if all URI lines in the Playlist
   identify Media Segments.  A Playlist is a Master Playlist if all URI
   lines in the Playlist identify Media Playlists.  A Playlist MUST be
   either a Media Playlist or a Master Playlist; all other Playlists are
   invalid.`

**Comment by joeyparrish** [comment]
Good question.  A lot of the metadata we need to play content via MediaSource is only ever available from a master playlist, not a media playlist.

It's possible that we could redesign our HLS support to overcome this some day, but for now, this is not something we plan to support.

We apologize for the inconvenience.
