### ISSUE TITLE
Manifest load errors in production

### ISSUE THREAD

**Issue by VictorChen** [google/shaka-player#2301]
Running Shaka Player in production, but we're seeing around 7% usage failing to load the manifest.

The error we see is:
```
shaka.util.Error.Severity.CRITICAL
shaka.util.Error.Category.PLAYER
shaka.util.Error.Code.LOAD_INTERRUPTED
```

From our logs, we can see that the error is coming from here:
https://github.com/google/shaka-player/blob/02fa8c687685c7a895e8b14ed9b6eaff6c52643b/lib/player.js#L1017

I'm not familiar with the code there. Could someone explain what the error means and whether or not it's normal to see them? Thanks!

**Comment by theodab** [comment]
That error is issued when the load process is interrupted by, say, another load. It's totally expected to see them in production, and for the most part it's safe to ignore or suppress them.
If you're seeing these errors when you're not trying to load two things in rapid succession, or load something then unattach from the video element, or whatever, then that might be an actual genuine bug.

**Comment by VictorChen** [comment]
Thanks, can confirm loading the video twice at the same time will cause an error with the same code
