### ISSUE TITLE
Might be doing this wrong but I can't seem to set the minBandwidth

### ISSUE THREAD

**Issue by pineapplejoe** [google/shaka-player#2304]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes.

**What version of Shaka Player are you using?**
2.5.6

**Can you reproduce the issue with our latest release version?**

Yes.

**Can you reproduce the issue with the latest code from `master`?**

Huh?

**Are you using the demo app or your own custom app?**

Custom app

**If custom app, can you reproduce the issue using our demo app?**

Haven't tried - dont know how. 

**What browser and OS are you using?**

Chrome and Firefox on Mac OS - Latest.  

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
NA

**What are the manifest and license server URIs?**

Manifest: https://cdn.worldalive.tours/dash/us-east-1:fcaded1f-0911-4071-a4d8-8c047c7e3648/Louvre YT/vimeo hawaii pace of formation.mpd

Licenses are signed cookies through https://staging.worldalive.tours/

**What did you do?**

player.configure({streaming: {bufferingGoal: 600, bufferBehind: 30, rebufferingGoal: 2}},{ abr: { restrictions: { minBandwidth: 2000000 }}});

This is called before load();

Note - we cant remove the lower variants as they are needed in a different mode.

Go to https://staging.worldalive.tours/
Click on "hawaiivimeotest" 
Open console.

observe the "v:#" events such as

v:1096000

These are output on adaptation events and are the value in streamBandwidth. 

player.getStats()['streamBandwidth']

If you restrict bandwidth in the browser you will still see v:# with #'s less than the minimum that is set.

**What did you expect to happen?**

I don't expect variants with less than 2000000 to be chosen.  

**What actually happened?**

I see variants with bitrates lower than 2000000 selected (or whatever min bar I am trying to set).

**Comment by theodab** [comment]
The brackets on your config call aren't balanced correctly.
Spacing it out a bit, what you're doing is this:
```js
player.configure(
  {
    streaming: {bufferingGoal: 600, bufferBehind: 30, rebufferingGoal: 2}
  },
  {
    abr: { restrictions: { minBandwidth: 2000000 }}
  }
);
```
So, you're actually passing in two objects! The second one is being ignored.

Try doing this instead:
```js
player.configure({streaming: {bufferingGoal: 600, bufferBehind: 30, rebufferingGoal: 2}, abr: { restrictions: { minBandwidth: 2000000 }}});
```

**Comment by pineapplejoe** [comment]
Dangit.  

Thanks for spotting that.
