### ISSUE TITLE
How to Overlay logos on Shaka Player?

### ISSUE THREAD

**Issue by viveksanagari** [google/shaka-player#2309]
Hi,
Is it possible to overlay logos on the shaka player?

From the shaka player documentation, I found a "shaka.ui.overlay" class https://shaka-player-demo.appspot.com/docs/api/shaka.ui.Overlay.html

I am a beginner in these. Kindly let me know, If and how can I use that class to overlay logos on the shaka player.

Thank you in advance,
Vivek

**Comment by joeyparrish** [comment]
Yes, you can overlay logos on Shaka Player using plain HTML & CSS.

The "Overlay" class you discovered is unrelated to this.  It is a class which represents a container that is overlayed on top of the video element to display the UI controls.

Try the HTML below.  It uses the Shaka Player UI library for the video controls, and it contains inline styles to position an image on top of the video as well.  If you place this in an HTML file in the root of the Shaka Player sources and compile the player (`./build/all.py`), it will be a complete working example.

Does this help?

```html
<!DOCTYPE html>
<html>
<head>

<link rel="stylesheet" href="dist/controls.css">
<script src="dist/shaka-player.ui.js"></script>

<style>

#container {
  width: 768px;
  height: 576px;
}

/* This is the CSS for your logo, to position it on top of the video. */
#myLogo {
  position: absolute;
  right: 5px;
  top: 10px;
}

</style>

<script>
document.addEventListener('shaka-ui-loaded', function() {
  const controls = video.ui.getControls();
  const player = controls.getPlayer();
  player.load(
      'https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd');
});
</script>

</head>
<body>

<div data-shaka-player-container id="container">
  <video data-shaka-player id="video"></video>

  <!-- This is your logo, a sibling of the video, inside the container. -->
  <img id="myLogo" src="demo/shaka_logo_trans.png">
</div>

</body>
</html>
```
