### ISSUE TITLE
Out of memory error in Firefox after long running video

### ISSUE THREAD

**Issue by jnatalzia** [google/shaka-player#2311]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes, this one seemed similar but not the same: https://github.com/google/shaka-player/issues/1990

**What version of Shaka Player are you using?**
2.5.2

**Can you reproduce the issue with our latest release version?**
Tested the stream below in 2.5.7 and ran into a different issue where the video would go black and playback would halt but no error would be thrown.

**Can you reproduce the issue with the latest code from `master`?**
Had difficulty getting the shaka demo page up and running locally. Happily to test there if I can get some pointers

**Are you using the demo app or your own custom app?**
DASH playback embedded in JW Player. The error however seems to be surfaced directly from shaka player, hence the issue being reported here

**If custom app, can you reproduce the issue using our demo app?**
I run into the above noted issue with playback completely stopping after 10-20 minutes of playback on 2.5.7

**What browser and OS are you using?**
macOSX Mojave 10.14.6  
Firefox 72.0

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
Manifest: https://814bffb9b389f652.mediapackage.ap-southeast-2.amazonaws.com/out/v1/4569cab089e5405b9433a9f8c57d7aff/manifest.mpd

**What did you do?**
1. Set up JWPlayer utilizing shaka-player v2.5.2 for DASH playback with the above manifest
2. Set up a time event handler to seek to the start of the video when nearing the end (this ensures the above 5min clip lasts long enough to repro without reloading the manifest)
3. Wait anywhere from 45-90 minutes.
4. See firefox bottom out with the following messaging:

```
GetMessage: NS_ERROR_OUT_OF_MEMORY (0x8007000e) provider.shaka.js:10:210151
```

JWPlayer notes that the error code coming from shaka is `3016` which is `VIDEO_ERROR` based on the docs.

**What did you expect to happen?**
I expect Firefox to be able to consistently play long running content without issuue.

**What actually happened?**
After the above 45-90 minutes of waiting, on 2.5.2 Firefox throws an out of memory exception.

It seems as though in version 2.5.7, there is a different issue where playback completely halts and a black screen is given after 10-20 min or so.

**Comment by joeyparrish** [comment]
Do you have the dev tools open during this test?  Leaving dev tools open causes the browser to keep all network responses in memory so you can inspect them in the debugger.  I have crashed Chrome _many_ times this way.

Try clicking the "pause" button on the network tab in Firefox's debugger before you start the test.  The equivalent in Chrome is to click the red "record" button to turn it gray.

Does this help?

**Comment by jnatalzia** [comment]
Giving it a shot!

**Comment by jnatalzia** [comment]
Still got the same error even with the network requests fully disabled

**Comment by theodab** [comment]
I'll see if I can reproduce this.

**Comment by theodab** [comment]
I ran on Firefox 71.0 (on a Mac Pro running macOSX Mojave 10.14.6) for about an hour and a half.
I never saw any memory errors in that time. However, according to the activity monitor, it looked like the memory that Firefox was using was slowly increasing over time. So we might have a memory leak.
Are you testing on a Macbook or something? If you are on a platform with less memory, it could explain you running out of memory in 45-90 minutes when I was still doing fine.

If you want to test yourself on our demo player, try out [this link](https://nightly-dot-shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://814bffb9b389f652.mediapackage.ap-southeast-2.amazonaws.com/out/v1/4569cab089e5405b9433a9f8c57d7aff/manifest.mpd;panel=CUSTOM%20CONTENT;build=uncompiled). I used the following code snippet to seek backwards when nearing the end of the video:
```js
setInterval(() => {
  if (shakaDemoMain.video_.currentTime > 3.5 * 60) {
    shakaDemoMain.video_.currentTime = 0;
  }
}, 1000);
```

For now, I'll mark this as a bug.

**Comment by jnatalzia** [comment]
Hey @theodab ,

I'm on a Macbook with 16 gigs of memory, so I don't believe my machine would be memory constraining things.

I just updated to Firefox 72.0b9 so I'll spend some time loading up in shaka and seeing if I can nail anything down in the newer update.

Appreciate the triage here!

**Comment by jnatalzia** [comment]
Is there a way to get demo app links for older versions? I'm running into the full playback stall issue on 2.5.7 I noted above where playback just completely halts after a period of time so I don't ever get to the memory issue noted (pause/play does not appear to recover in this state)

**Comment by theodab** [comment]
You can see a list of old versions [here](https://index-dot-shaka-player-demo.appspot.com/), for reference. If you press the "all versions" button it will show a more exhaustive list.

**Comment by jnatalzia** [comment]
It's possible that this was an issue directly in Firefox. After updating to `72.0b9` I could no longer reproduce in long running videos.

**Comment by joeyparrish** [comment]
Good news!  Thanks for getting back to us.  Should we go ahead and close it?

**Comment by jnatalzia** [comment]
I'm doing a little more work to verify and will get back to you. Thanks for the quick comms!

**Comment by joeyparrish** [comment]
You're welcome.  Happy new year!
