### ISSUE TITLE
video caching issue in shaka player

### ISSUE THREAD

**Issue by amit08255** [google/shaka-player#2313]
When a video is updated (page has same URL) and video is played after update, shaka player plays old video already cached. Please explain how this can be fixed.

**Comment by theodab** [comment]
Do you mean how the demo loads whatever asset was playing previously when you reload?
If so, that's an intentional feature. And it's part of the demo, not part of Shaka Player, so it won't affect your app.

**Comment by joeyparrish** [comment]
Or do you mean that the video itself is cached?  As in, you update the content on your server, but the client plays the older version?

If it's that, you should fix your server to prevent caching by the browser.  It's not a feature of the player or app, it's actually done by the browser based on response headers sent by your server.

**Comment by amit08255** [comment]
@joeyparrish Sorry for late response. Yes you got it right. That's the issue. I update the video on the server, but client plays older version of video (only part that is cached).
You mean caching done by shaka player is handled by browser not by player itself?

**Comment by joeyparrish** [comment]
That's correct.  Shaka Player does not cache your videos, but browsers cache potentially everything they fetch from the network.  The headers sent by the server can influence or control the caching behavior of the browser.

Caching is not a boolean feature that's either on or off.  There are many parts to caching that you can control from the server.  You can even require browsers to check for changes before they use the cached response, which it sounds like would be ideal for you.  Here are some articles from MDN that may help:

 - Docs for the `Cache-Control` response header: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control
 - Docs for ETags, which can identify versions of a resource: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag
 - A general article about caching on the web: https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching

Does this help?

**Comment by amit08255** [comment]
Thank you very much for solution @joeyparrish
