### ISSUE TITLE
Shaka with React-ES6

### ISSUE THREAD

**Issue by sridhard** [google/shaka-player#2317]
Hi,

I am building shaka player in debug mode with the following command:
python build/all.py --force --debug

Build is success. But if I import shaka-player then I am getting error shaka.Player is not a constructor. If I do the release build everything works fine.

Can you please tell me whether we need to do anything else to build in debug mode? I think in debug mode the symbols are missing

**Comment by sridhard** [comment]
I think it is something related to wrapper code 

    if is_debug:
      closure_opts += debug_closure_opts + debug_closure_defines
      # The output wrapper is only used in the release build.
      closure.add_wrapper = False
    else:
      closure_opts += release_closure_opts + release_closure_defines

In debug builds, ES6 export is having issues.

**Comment by joeyparrish** [comment]
We can't support both module loaders and native ES6 modules in the same build.  The "export" keyword can only exist in a native ES6 module.  So currently, our build output only supports module loaders.

That said, if you import the compiled bundle as an ES6 module, we will attach the "shaka" namespace to "window".  So you should still be able to use the "shaka" namespace globally after importing the module at runtime.

If React is not importing the module at runtime, but rather using import syntax for its own build system to produce a singular bundle, I would not expect this to work.  Instead, I would suggest you load Shaka Player separately from your React component and just refer to the global "shaka" from there.  That way, you should be able to use the compiled or debug bundle and switch between them for debugging without any other changes.

Does this help?

**Comment by sridhard** [comment]
ok..thanks
