### ISSUE TITLE
onstatechange and onstateidle is not being fired

### ISSUE THREAD

**Issue by El-Vishy** [google/shaka-player#2318]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.6 and 2.5.7

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Yes

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Chrome 79.0.3945.88 and Mac OS 10.14.6

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
NA

**What are the manifest and license server URIs?**

- http://rdmedia.bbc.co.uk/dash/ondemand/testcard/1/client_manifest-events.mpd

- http://vm2.dashif.org/livesim/mup_30/testpic_2s/Manifest.mpd

These dont require license.

**What did you do?**
I use shaka-player.ui.js, which creates shakaplayer instance. I use following code to access player instance and add listeners for "onstatechange" and "onstateidle" events.

```
      video = document.getElementById('video');
      const ui = video['ui'];
      const controls = ui.getControls();
      shakaPlayer = controls.getPlayer();
      shakaPlayer.addEventListener("onstatechange",onStateChanged);
      shakaPlayer.addEventListener("onstateidle",onStateIdle);

      function onStateChanged(event) {
          console.log("onStateChanged Event ", event.state);
     }

    function onStateIdle(event) {
          console.log("onStateIdle Event ", event.state);
    }
```

**What did you expect to happen?**
I expected onStateChanged() and onStateIdle() methods to be called, with different events like

- onStateChanged Event  attach
- onStateChanged Event  media-source
- onStateIdle Event  media-source
- onStateChanged Event  manifest-parser
- onStateChanged Event  manifest
- onStateChanged Event  drm-engine
- onStateChanged Event  load
- onStateIdle Event  load
- onStateChanged Event  unload
- onStateChanged Event  detach

**What actually happened?**
If I use shaka-player.ui.js and add listener for "onstatechange" and "onstateidle" events. The callback methods are not called. 

But if I manually create an instance shaka player and add listeners for "onstatechange" and "onstateidle" events, they seem to work.

[SamplePlayers.zip](https://github.com/google/shaka-player/files/3997720/SamplePlayers.zip)
This has two players

- shakaplayerBug.html -> Event is not fired
- shakaplayerWorking.html -> Event is fired

I have also hosted the player to following location:

- **Events are fired:**  https://79423.analytics.edgekey.net/Unit_Testing/visy/shakaSample/shakaplayerWorking.html 
- **Events are not fired:**  https://79423.analytics.edgekey.net/Unit_Testing/visy/shakaSample/shakaplayerBug.html
-

**Comment by joeyparrish** [comment]
Confirmed.  Thanks for the report!

Here's what's broken:

When you call getPlayer() on the UI controls, you get a proxy object created by our CastProxy class.  This allows you to proxy the API & events to/from the Chromecast.  It seems that the proxy isn't handling these events as it should.

It will be fairly easy to fix, but as a workaround in the mean time, you can use getControls().getLocalPlayer().  This is the actual Player instance, rather than a proxy object.  I've confirmed in your demo that listening for the events on this object works as expected.

**Comment by joeyparrish** [comment]
The fix is now in the master branch, and can be cherry-picked to our next v2.5.x bug-fix release.  Until then, you can either use the master branch or the `getLocalPlayer()` workaround I mentioned.

Thanks again for the report!

**Comment by El-Vishy** [comment]
Thanks for the fixing it and also providing a work around!

**Comment by joeyparrish** [comment]
Happy to help!

**Comment by joeyparrish** [comment]
These changes have been cherry-picked for v2.5.8.
