### ISSUE TITLE
Dolby Vision

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#2322]
Is Dolby Vision supported by ShakaPlayer?

Spec:
https://www.dolby.com/us/en/technologies/dolby-vision/dolby-vision-streams-within-the-mpeg-dash-format-v2.0.pdf

Edge based in Chromium supports Dolby Vision: https://techcommunity.microsoft.com/t5/discussions/dev-channel-update-to-80-0-361-5-is-live/m-p/1070730

Sample Stream:
https://dash.akamaized.net/dash264/TestCasesMCA/dolby/6/DashIf-HDR10_UHD.mpd

**Comment by joeyparrish** [comment]
Codec support is a matter of the browser, not the player.  The decoders are always below the level of JavaScript.  So if the browser supports a codec, Shaka will discover this and may choose to play the corresponding tracks.

Does this help?

**Comment by avelad** [comment]
In the stream https://dash.akamaized.net/dash264/TestCasesMCA/dolby/6/DashIf-HDR10_UHD.mpd
```
<!-- Video -->
	<AdaptationSet mimeType="video/mp4" subsegmentAlignment="true" subsegmentStartsWithSAP="1" frameRate="24">
	  <Representation id="base-layer" codecs="hev1.2.4.H153.b0" bandwidth="29200362" width="3840" height="2160">
		<BaseURL>BL_DashIf_BL-HDR10_UHD.mp4</BaseURL>
		<SegmentBase indexRange="687-862">
		 <Initialization range="0-686"/>
		</SegmentBase>
	  </Representation>
	  <Representation id="enhancement-layer" dependencyId="base-layer" codecs="dvhe.07.03" bandwidth="9320458" width="1920" height="1080">
		<BaseURL>EL_DashIf_BL-HDR10_UHD.mp4</BaseURL>
		<SegmentBase indexRange="723-898">
		 <Initialization range="0-722"/>
		</SegmentBase>
	  </Representation>
	</AdaptationSet>
```

The attribute `dependencyId`, what is it for?
How can you prevent ShakaPlayer from adapting between HDR and non-HDR tracks?

**Comment by joeyparrish** [comment]
I'm not familiar with `dependencyId`.  We don't seem to use it.

The way we prevent adapting between HDR and non-HDR tracks is by the `codecs` string.  We would see `hev1` as different from `dvhe` and only use one or the other.

When we start using the `MediaCapabilities` API and `MediaSource`'s `changeType` method, we would enable adaptation between codecs if the browser supports the transition.

Does this help?

**Comment by avelad** [comment]
Yes, this is enough for now. thanks!
