### ISSUE TITLE
Incomplete fullscreen on Android

### ISSUE THREAD

**Issue by zarmhast** [google/shaka-player#2324]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.7

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Both

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Chrome on Android 6, 7, 8, 9 + with onscreen navigation bar

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What did you do?**

- Start video
- Go fullscreen

**What did you expect to happen?**
The video to go fullscreen

**What actually happened?**

Navigation bar stays on screen preventing the video from going fullscreen

**Suggested fix**
`controls.js` should request fullscreen with UI hidden:

```javascript
requestFullscreen({ "navigationUI": "hide" })
```

This change has been tested on desktop (Firefox, Chrome / Linux, Windows) as well as mobile and allows the video to go fullscreen without the navigation bar getting in the way.

**Comment by joeyparrish** [comment]
These changes have been cherry-picked for v2.5.8.
