### ISSUE TITLE
Two player instances doesn't work on Samsung or LG TV

### ISSUE THREAD

**Issue by janliska** [google/shaka-player#2331]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
YES

**What version of Shaka Player are you using?**
2.5.0

**Can you reproduce the issue with our latest release version?**
YES

**Can you reproduce the issue with the latest code from `master`?**
YES

**Are you using the demo app or your own custom app?**
custom app

**If custom app, can you reproduce the issue using our demo app?**
Didn't try

**What browser and OS are you using?**
Samsung Tizen, LG webos - doesn't work
Version 79.0.3945.88 (Official Build) (64-bit) - works

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Samsung UE43RU7092UXXH, version T-MSLDEUC-1335.0

**What are the manifest and license server URIs?**
will send it via email

**What did you do?**
When I run the code from https://github.com/janliska/shaka-issue at browser, it works correctly and I see two player instances playing correctly the stream.

When I run the code on TV, only second player is running. First one is doing nothing. No errors or warnings in console

**What did you expect to happen?**
I would expect same behavior on TV and PC

**What actually happened?**
There is only one player streaming video on TV, but there should be two.
![alt text](https://raw.githubusercontent.com/janliska/shaka-issue/master/issue.jpeg "issue")

**Comment by TheModMaker** [comment]
Some embedded platforms like smart TVs set restrictions on the number of concurrent video playbacks.  Not all of them allow having two video elements playing at the same time.  So this is probably a platform restriction.

**Comment by avelad** [comment]
Tizen and WebOS only allow one video concurrent at 2019. If I remember correctly, in the Tizen 5.5 code I have seen something that allows two players, but I have not tried it yet.

**Comment by joeyparrish** [comment]
If the platform only allows one video element at a time, we can't do anything about that.  Sorry!
