### ISSUE TITLE
Period missing a content type present in other periods

### ISSUE THREAD

**Issue by mmedhekar** [google/shaka-player#2335]
I am working on implementing adding dash multi-period support for live content and as audio/video are not aligned due to various reasons, sometimes i get empty SegmentTimeline for one of the streams in first/last period in the manifest. Shaka player complains about this and wanted to know the exact reason. As per my understanding there is a good chance that audio/video fragments are not time-aligned (start-timestamps will not match) which will contribute to above said problem. My question is what is the expected behavior from server in this case? What should server put in the MPD if there are no segments available for one of the streams in a period? Remove entire adaptation set? or segmentTemplate? Signal empty SegmentTimeline by setting some attribute on any of the above element?

**Comment by TheModMaker** [comment]
Periods need to be continuous over the content.  So you need to specify Periods that cover the entire content.  Additionally, each Representation MUST specify segments for the entire Period.  You cannot have a Representation that is empty or doesn't have enough segments to fill the whole Period.

You can remove the Representation/AdaptationSet for those streams in those Periods; but you need to specify at least one stream for audio+video for each Period, or we'll have nothing to play.  Alternatively, you could have the encoder produce empty content and use that for the missing input.

**Comment by mmedhekar** [comment]
For the combination of live event with rolling window + jagged edge (or splice conditioning with SSAI) isnt the empty segmentTimeline more possible. This should only happen with of the first period in mpd (from which we are removing fragments as they are rolling off) and last period where new fragments are still coming in.

**Comment by joeyparrish** [comment]
If the SegmentTimeline is empty because everything has fallen outside of the rolling window, just drop the Period.  The other Period elements will have stable IDs and start times, so the player will still be able to match things up and keep going.

**Comment by mmedhekar** [comment]
Hey JoeyParrish thanks for the reply. I am trying to handle scenario with the jagged edge/splice conditioning not being precise (by that i mean it is possible for audio/video start times to be few millis apart from each other).
 Due to this there is a possibility that we might end up with a period containing, empty segmentTimeline for either of the stream. This can only happen for first period due to rolling window or last period as the content is live and new fragments are coming in.

I tried removing the adaptationSet for such stream where SegmentTimeline is empty for a particular period but now shaka player complains about missing adaptation set (Error 5005).
So i am not sure what should be the server behavior if it finds out that one of the SegmentTimelines are empty. Is there any setting on shaka player to turn check for missing adaptation set off?

**Comment by TheModMaker** [comment]
For the first Period, you could just drop the Period early.  Why keep the Period if there is less than a second of content in it?  For the last Period, you could just wait to add the new Period until you have both audio and video.

**Comment by mmedhekar** [comment]
@TheModMaker : I understand for the first period and removing the first period little bit early as you suggested will not have any adverse effect. But delaying creation of last period might have issues in case of discontinuous audio/video streams. 

I am also seeing assertion failures in console,
segment_index.js:169 Assertion failed: This should be an update of the last segment in a period
shaka.media.SegmentIndex.merge @ segment_index.js:169
shaka.dash.SegmentTemplate.createStream @ segment_template.js:96

Do you know what can cause this?

**Comment by TheModMaker** [comment]
Sorry for the delay.  For a long time we only supported continuous content, and other players may not support gaps in the content well.  We do support gap jumping, so we may be able to play over the discontinuous content, but we won't play the content that has only one stream.  We may just jump over the times where there was only one stream.  But that also means we'll just wait buffering at the end of the audio+video content until we see another time when there is both.  And as you saw, we'll throw an error if the next Period is audio-only or video-only.

We can't switch from audio+video to video-only smoothly.  We could do it by resetting the whole media pipeline, but that would be really complicated for us and the transition would be visible.  So if we start playing audio+video, we will only play that for the whole playback session.

As for that error, that may be a bug on our part, or it may be that you are changing segment times.  Once a segment or a Period appears in a manifest, it cannot change.  So you can't change the Period start or the times of a segment.  What version are you using, or are you using `master`?

**Comment by joeyparrish** [comment]
If you're using `master`, we just fixed a multi-period DASH bug last week.  This bug was never in a release version, but may have affected your work from the `master` branch, if any.

**Comment by mmedhekar** [comment]
Thanks for the replies @TheModMaker and @joeyparrish.

I was more worried about the buffering part at the live edge due to missing adaptation set (audio only or video only). i understand your concern about switching from audio+video to only one stream and i see that player starts buffering when it sees only one adaptation however it never comes back from that state even though with manifest update mpd starts having both the adaptation sets for the last period.

Here is the flow,
1. Download mpd 
2. player starts playing contnet
3. player keeps downloading 1 audio, 1 video fragment and then mpd
4. last period contains only 1 adaptation set
5. player shows error and keeps downloading manifest again and again
Even though manifest gets updated and now have both the adaptation set, player cannot resume the playback.

I am using release version of shaka.

**Comment by joeyparrish** [comment]
This kind of content is not supported by Shaka Player at this time.  We don't reinitialize the media pipeline, so we can't play through a DASH period which is missing a content type (audio or video) that is present in the other periods.  I apologize for the inconvenience.
