### ISSUE TITLE
Can we set the player aspect ratio param for a certain stream?

### ISSUE THREAD

**Issue by zhulduz** [google/shaka-player#2336]
Hi team!

I have questions about a player aspect ratio config:

1. Is it possible to set a custom value for the player?
2. How shakaplayer works with an aspect ratio: couldn't find in docs any info?

Thanks in advance)

**Comment by TheModMaker** [comment]
We cannot control the aspect ratio of the media; it is controlled by the media.  You can control this when you encode the content.  We just play whatever is in the media.  We also play in whatever video element you set on the page.  You can resize the video element on the page with CSS, but I don't think it will change the aspect ratio of the video frames, I think the browser adds black bars to fit the video.

Did you mean to post this on [google/shaka-streamer](https://github.com/google/shaka-streamer)?

**Comment by zhulduz** [comment]
@TheModMaker, thank you for the response.

I will look at google/shaka-streamer, maybe I will find some solution.
Also, will try to resize the video element through CSS.

**Comment by joeyparrish** [comment]
Sounds good.  Let us know if you need any more help.

**Comment by zhulduz** [comment]
Hi!
I have prepared a rough example with setting a custom aspect ratio through CSS. https://jsfiddle.net/zhulduz/c843zmn5/

Do you have a chance to look at and make any feedback?

Thanks in advance)

**Comment by zhulduz** [comment]
@joeyparrish , @TheModMaker, 
I would be appreciated If you have an opportunity to check and give feedback 😃
