### ISSUE TITLE
TTML subtitles embedded in MPEG does not work or show

### ISSUE THREAD

**Issue by madsva** [google/shaka-player#2338]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes. There might be a duplicate issue (https://github.com/google/shaka-player/issues/2256), but I'm not completely sure, hence creating a new one.

**What version of Shaka Player are you using?**
2.5.6

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Own custom

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
MacOS, Chrome

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Chromecast 

**What are the manifest and license server URIs?**
Link to manifest send to shaka-player-issues@google.com

**What did you do?**

1. Started the stream
2. Enabled the subtitles programmatically
Works in 2.5.5 but fails in 2.5.6 and up. Attached samples of 2.5.5 and 2.5.6 which demonstrates the issue.

**What did you expect to happen?**
The embedded TTML subtitles would show

**What actually happened?**
Nothing, but a small square was visible
[Archive.zip](https://github.com/google/shaka-player/files/4053176/Archive.zip)

**Comment by michellezhuogg** [comment]
Hello @madsva ,
Thank you for reaching out! I verified that the captions are shown in 2.5.5 but not in 2.5.6, however, our lastest build seems to have it fixed. Could you please verify that?
https://nightly-dot-shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://rr.ew.waoo.tv/__cl/s:storage-aarhus-1,storage-skanderborg-1/__c/v/b/3/8/v_eg_14015tr_b38a57989e01779a430fc8432806a818/__op/dash-default/__f/manifest.mpd;panel=CUSTOM%20CONTENT;build=uncompiled

**Comment by madsva** [comment]
@michellezhuogg Yes! It looks like it's working again! Thanks 👍 

Do you happen to know if there are there any timelines on when the next release of master will be tagged and added to the Chromecast CAF?

**Comment by joeyparrish** [comment]
The fix has already made it into the latest tagged release (v2.5.8), but updates in CAF are up to the Cast team.  I can ask them about it in our next internal meeting.

**Comment by joeyparrish** [comment]
The Cast team says that v2.5.8 will ship in their next release.  I don't have an exact date.

Does this help?

**Comment by madsva** [comment]
Yes that's fine - I'll check up on the CAF release notes instead then. It get's updated relatively often. Thanks a lot for your help!

**Comment by ivenms** [comment]
Our CAF receiver also facing the same issue after the latest Shaka Player update. The issue appears only for Arabic subtitles, english works fine. The closed captions on our system is using mpd textstreams, encoded in ANSI.

**Comment by joeyparrish** [comment]
@ivenms, not sure what you mean about ANSI encoding.  AFAIK, ANSI was not an Arabic encoding.  Besides this, all the subtitle formats we use mandate a UTF-8 encoding (both VTT & TTML).

It's also not clear what is meant by "mpd textstreams".  We support 4 different text formats within an MPD (VTT or TTML, in plain text or embedded in MP4).

If you're having an issue with CAF, please wait for the next CAF update to see if that fixes it.  If not, please file a support request with the Cast team specifically.  This team doesn't directly support CAF, which is written and maintained by a different team who have their own bug tracker.

If you have an issue with Shaka Player directly, or if your CAF issue can be reproduced in the latest release version of the [Shaka Player Demo app](https://shaka-player-demo.appspot.com/demo/), then please file a new issue against Shaka Player.

Thanks!
