### ISSUE TITLE
frame accurate seeking in paused DASH playback

### ISSUE THREAD

**Issue by mephillips423** [google/shaka-player#234]
I am using the example WowzaStreamingEngine-4.3.0 MPEGDASHPlayer.
I am trying to implement seeking frame by frame in a paused DASH stream.

When I set a new position using currentTime of the video element the
video does not move to the new frame. If I increment frame by
frame for many frames eventually after 20 to 40 frames a new
frame will be displayed.

Is there a setting on the wowza server or the shaka javascript
library that can be used to get frame accurate seeking to work?

Example: setting the HTML5 video element current time to three different frames
  this.vidElement.currentTime = 19.566666666666666;
  this.vidElement.currentTime = 19.6;
  this.vidElement.currentTime = 19.633333333333333;

Example: shaka and video setup
<script type="text/javascript" src="js/shaka-player.compiled.js"></script>
...

    <script type="text/javascript">
      var video1;
      var shakaPlayer;

      $(document).ready(function(){
         var html5VidElem = document.getElementById("video1");

        // Install polyfills for legacy browser support.
        shaka.polyfill.installAll();

        // Construct a Player to wrap around it.
        shakaPlayer = new shaka.player.Player(html5VidElem);

        // Attach the player to the window so that it can be easily debugged.
        window.player = shakaPlayer;

        // Listen for errors from the Player.
        shakaPlayer.addEventListener('error', function(event) {
          console.error(event);
          });

        // see if my player can still control video
        // Construct a DashVideoSource to represent the DASH manifest.
        var mpdUrl = 'http://192.168.200.31:1935/vod/mp4:sample.mp4/manifest.mpd';
        var estimator = new shaka.util.EWMABandwidthEstimator();
        var source = new shaka.player.DashVideoSource(mpdUrl, null, estimator);

        // Load the source into the Player.
        shakaPlayer.load(source);
      });
      
    </script>
...
Example: HTML5 video element
      <video id="video1" onloadeddata="video1.onLoadedDataEvent()" onpause="video1.onPauseEvent()" onplay="video1.onPlayEvent()" ontimeupdate="video1.onTimeUpdateEvent()" controls crossorigin="anonymous" >

**Comment by joeyparrish** [comment]
Hi @mephillips423,

I don't believe the player can do anything to influence this.  Frame-accurate seeking depends on the browser and the video encoding.

For example, if every frame were a key frame, then I have no doubt every frame would be directly seekable in every MSE-capable browser.  This would be a terrible idea, though, since it would ruin compression and therefore quality.

Seeking to non-keyframes is something a browser would have to support by seeking first to the previous keyframe, then decoding subsequent non-keyframes until the target frame has been decoded.  It is entirely possible that browsers may choose to avoid this when the video is paused.  I don't know for sure.

I would bet that the reason you get frames displayed every 20-40 frames is that your content's keyframe interval is between 20 and 40.

Your application seeks directly on the video element by setting currentTime.  The only time the player gets involved when you seek is if this time has not been buffered yet.  In that case, we would have to fetch the appropriate segments and feed them to the browser.

I would suggest that you make sure the range in which you want to frame-accurately seek is actually buffered.  ```html5VidElem.buffered``` is where you would get this information.

If the content is buffered, and seeking while paused still does not display frames, then it is a browser implementation issue.  In this case, I would advise you to file a feature request with your browser vendor to support frame-by-frame display while paused.

I just did a quick check with the "car" video from our demo app, and Chrome does allow seeking while paused with ```video.currentTime += 1/23.97```.  It appears to do interesting things with b-frames or maybe with PTS/DTS differences, but that is another matter.

**Comment by mephillips423** [comment]
What do you mean by chrome does allow seeking while paused. I have 
videos with the timecodes burnt in.
I get the same behavior from firefox, chrome and IE. I can set the 
currentTime, but the video frame displayed with
the burnt in timecode never matches. I am assuming I have the correct 
video buffered available, because all I
do is pause the video, after is stops I attempt to add one frame to the 
currentTime attribute, but like I
said the video displayed seldom moves as I add more time to currentTime.

**Comment by joeyparrish** [comment]
I tested in Chrome 47 on ChromeOS, with the "car" video from our demo app, and it does allow seeking while paused.  Perhaps there is a per-platform difference, or a difference with the content.  Could you test with the same content I am using?  That would eliminate one of the differences.

http://shaka-player-demo.appspot.com/assets/car_cenc-20120827-manifest.mpd

**Comment by mephillips423** [comment]
This URL: 
http://shaka-player-demo.appspot.com/assets/car_cenc-20120827-manifest.mpd
had some digital rights issues in my test setup

Html5VideoPlayer.html:33 CustomEvent {isTrusted: false, srcElement: 
null, currentTarget: V, target: V}(anonymous function) @ 
Html5VideoPlayer.html:33yb @ shaka-player.compiled.js:40H.dispatchEvent 
@ shaka-player.compiled.js:39(anonymous function) @ 
shaka-player.compiled.js:173
shaka-player.compiled.js:155 Uncaught (in promise) Error: No DrmInfo 
exists!(…)

I went to the following URL: http://shaka-player-demo.appspot.com/

and found an alternate URL:
http://shaka-player-demo.appspot.com/assets/car-20120827-manifest.mpd

Yaay!  This seems to display different frames as I request them.
This is on chrome 46 windows 7.1

We are using wowza 4.3 as the stream server. Do think it could be the 
server, or do I need  encode our h264 mp4 video with
a particular codec.

I attached our non working manifest and the working manifest




On 11/23/2015 7:57 PM, Joey Parrish wrote:
>
> I tested in Chrome 47 on ChromeOS, with the "car" video from our demo 
> app, and it does allow seeking while paused. Perhaps there is a 
> per-platform difference, or a difference with the content. Could you 
> test with the same content I am using? That would eliminate one of the 
> differences.
>
> http://shaka-player-demo.appspot.com/assets/car_cenc-20120827-manifest.mpd
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/google/shaka-player/issues/234#issuecomment-159143653>.
>


<MPD xmlns="urn:mpeg:DASH:schema:MPD:2011" mediaPresentationDuration="PT0H3M1.63S" minBufferTime="PT1.5S" profiles="urn:mpeg:dash:profile:isoff-on-demand:2011"
type="static">
  <Period duration="PT0H3M1.63S" start="PT0S">
    <AdaptationSet>
      <ContentComponent contentType="video" id="1" />
      <Representation bandwidth="4190760" codecs="avc1.640028" height="1080" id="1" mimeType="video/mp4" width="1920">
        <BaseURL>//yt-dash-mse-test.commondatastorage.googleapis.com/media/car-20120827-89.mp4</BaseURL>
        <SegmentBase indexRange="674-1149">
          <Initialization range="0-673" />
        </SegmentBase>
      </Representation>
      <Representation bandwidth="2073921" codecs="avc1.4d401f" height="720" id="2" mimeType="video/mp4" width="1280">
        <BaseURL>//yt-dash-mse-test.commondatastorage.googleapis.com/media/car-20120827-88.mp4</BaseURL>
        <SegmentBase indexRange="708-1183">
          <Initialization range="0-707" />
        </SegmentBase>
      </Representation>
      <Representation bandwidth="869460" codecs="avc1.4d401e" height="480" id="3" mimeType="video/mp4" width="854">
        <BaseURL>//yt-dash-mse-test.commondatastorage.googleapis.com/media/car-20120827-87.mp4</BaseURL>
        <SegmentBase indexRange="708-1183">
          <Initialization range="0-707" />
        </SegmentBase>
      </Representation>
      <Representation bandwidth="686521" codecs="avc1.4d401e" height="360" id="4" mimeType="video/mp4" width="640">
        <BaseURL>//yt-dash-mse-test.commondatastorage.googleapis.com/media/car-20120827-86.mp4</BaseURL>
        <SegmentBase indexRange="708-1183">
          <Initialization range="0-707" />
        </SegmentBase>
      </Representation>
      <Representation bandwidth="264835" codecs="avc1.4d4015" height="240" id="5" mimeType="video/mp4" width="426">
        <BaseURL>//yt-dash-mse-test.commondatastorage.googleapis.com/media/car-20120827-85.mp4</BaseURL>
        <SegmentBase indexRange="672-1147">
          <Initialization range="0-671" />
        </SegmentBase>
      </Representation>
      <Representation bandwidth="100000" codecs="avc1.4d4015" height="144" id="5" mimeType="video/mp4" width="256">
        <BaseURL>//yt-dash-mse-test.commondatastorage.googleapis.com/media/car-20120827-160.mp4</BaseURL>
        <SegmentBase indexRange="671-1146">
          <Initialization range="0-670" />
        </SegmentBase>
      </Representation>
    </AdaptationSet>
    <AdaptationSet>
      <ContentComponent contentType="audio" id="2" />
      <Representation bandwidth="127236" codecs="mp4a.40.2" id="6" mimeType="audio/mp4" numChannels="2" sampleRate="44100">
        <BaseURL>//yt-dash-mse-test.commondatastorage.googleapis.com/media/car-20120827-8c.mp4</BaseURL>
        <SegmentBase indexRange="592-851">
          <Initialization range="0-591" />
        </SegmentBase>
      </Representation>
      <Representation bandwidth="255236" codecs="mp4a.40.2" id="7" mimeType="audio/mp4" numChannels="2" sampleRate="44100">
        <BaseURL>//yt-dash-mse-test.commondatastorage.googleapis.com/media/car-20120827-8d.mp4</BaseURL>
        <SegmentBase indexRange="592-851">
          <Initialization range="0-591" />
        </SegmentBase>
      </Representation>
      <Representation bandwidth="31749" codecs="mp4a.40.2" id="8" mimeType="audio/mp4" numChannels="1" sampleRate="22050">
        <BaseURL>//yt-dash-mse-test.commondatastorage.googleapis.com/media/car-20120827-8b.mp4</BaseURL>
        <SegmentBase indexRange="592-851">
          <Initialization range="0-591" />
        </SegmentBase>
      </Representation>
    </AdaptationSet>
  </Period>
</MPD>

**Comment by joeyparrish** [comment]
I'm sorry, we are not affiliated with Wowza.  If you need help with your Wowza stream server, you should contact [Wowza support](https://www.wowza.com/support).

Since we've determined that your use-case works in Shaka Player running on Chrome, I'm going to close this issue now.  Thanks for using Shaka, and please feel free to open a new issue if you have any Shaka-related problems.

**Comment by mephillips423** [comment]
Thanks for your help!

Is there a forum that you know of that might have a knowledge base about 
the issues I am having.

**Comment by joeyparrish** [comment]
Have you tried Wowza?  http://www.wowza.com/forums/forum.php

**Comment by mephillips423** [comment]
Thanks, I posted it there, no one has a reply.
