### ISSUE TITLE
Nightly demo app "report bug" button has no text in it

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#2340]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
nightly / master

**Can you reproduce the issue with our latest release version?**
no

**Can you reproduce the issue with the latest code from `master`?**
yes

**Are you using the demo app or your own custom app?**
demo

**What browser and OS are you using?**
ChromeOS stable

**What are the manifest and license server URIs?**
Not applicable

**What did you do?**
Load the demo app

**What did you expect to happen?**
There should be a "report bug" button on the top right of the page, to the left of the version number

**What actually happened?**
There is no text in the button.  You can find it by mousing over it, but it's otherwise invisible.

**Comment by theodab** [comment]
Oh. I guess that's why nobody has been using it.
