### ISSUE TITLE
License and decoder errors in MS Edge for PlayReady DRM playback

### ISSUE THREAD

**Issue by glhvta** [google/shaka-player#2342]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v2.3.3

**Can you reproduce the issue with our latest release version?**
Yes 

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Using a custom app, but can reproduce on demo app as well

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
OS Name Microsoft Windows 10 Enterprise
Version 10.0.17134 Build 17134

Microsoft Edge.
Version 81.0.389.0 (Official build) canary (64-bit)

**What are the manifest and license server URIs?**
(you can send the URIs to shaka-player-issues@google.com instead, but please use GitHub and the template for the rest)
Manifest sample, license  request  and response payloads were sent in email

**What did you do?**

I'm trying to play DRM protected media

**What did you expect to happen?**
Playback was started without any error

**What actually happened?**
Sometimes playback fails with 6008 and 3016 errors;

**Aditional data**:
License request was send (request and response payloads were sent in email). PlayReady DRM playback fails with 6008 and 3016, 3015 errors (please see attached screens )

![err1](https://user-images.githubusercontent.com/31937370/72329596-17dceb00-36c6-11ea-852c-fd0f5bc35108.PNG)
![err2](https://user-images.githubusercontent.com/31937370/72329597-18758180-36c6-11ea-9099-d01fece7cb0a.PNG)

The issue is not always reproduced and sometimes playback starts without any errors;

Note: This issue is applicable only for PlayReady DRM playback. Playback was also tested with Widevine DRM ( as now MS Edge (Canary) supports Widevine DRM) and no errors were observed.

All the notes above are applicable and were reproduced on the latest version of MS EDGE (Canary).

But the issue with PlayReady DRM playback is also actual for :
Microsoft Edge 42.17134.1098.0
Please see screens with errors
![edge-err](https://user-images.githubusercontent.com/31937370/72332156-93d93200-36ca-11ea-9995-6d02a67c560c.png)
The error is either 6008 or 3016 with system error - 8004c009

**Comment by michellezhuogg** [comment]
Hello Tanya, 

Thank you for reaching out! We got your email with your test files.
1. Have you tried with our latest version?
2. Could you please send manifest urls (like in .mpd or .m3u8 format), and license server urls to us? It would be easier for us to test and investigate with the urls instead of the actual payloads. 
https://nightly-dot-shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;panel=CUSTOM%20CONTENT;build=uncompiled

**Comment by glhvta** [comment]
@shaka-bot reopen 

Hi, @michellezhuogg 

1. Tested on the latest version of shaka player and the issue is still reproduced.
2. A demo page with test streams to reproduce this issue was sent to  shaka-player-issues@google.com 

Thank!

**Comment by glhvta** [comment]
@shaka-bot reopen

**Comment by TheModMaker** [comment]
The error you listed had a system code of 0x8004c009, which is DRM_E_LICENSEEXPIRED.  It looks like the license we got from the server was expired or reached the number of play counts allowed.

**Comment by glhvta** [comment]
Hi, @TheModMaker 

We couldn't find 0x8004c009 error code description, so now we can continue the investigation of this issue with the provided information.

Thanks a lot!

**Comment by TheModMaker** [comment]
This code comes from the browser, and PlayReady doesn't have great documentation.  Here is where I found the code:

https://docs.microsoft.com/en-us/windows/desktop/wmdm/error-codes

**Comment by glhvta** [comment]
yes, we've been trying really hard to find any reference to this error code in PlayReady or Microsoft documentation,

now with this description (_license we got from the server was expired or reached the number of play counts allowed)_ it is clear why the issue was not always reproduced and sometimes playback was started without any errors;

many thanks your help and for sharing this link which really helped us a lot
