### ISSUE TITLE
v2.5.7 not available on cdnjs

### ISSUE THREAD

**Issue by TheModMaker** [google/shaka-player#2343]
cdnjs hasn't been updated to include v2.5.7, it only has up to v2.5.6.

https://cdnjs.com/libraries/shaka-player

**Comment by joeyparrish** [comment]
Their auto-update process seems to be broken.  Others are complaining on their github page.

I have a PR in to add the CSS to what they serve, and they asked me to wait, saying that they have to refactor their whole service.

https://github.com/cdnjs/cdnjs/pull/13452

I would recommend we remove cdnjs from our docs.  Other CDNs are able to directly mirror NPM releases and do it without configuration.
