### ISSUE TITLE
bug in docs/tutorials/fairplay.md

### ISSUE THREAD

**Issue by jonasevcik** [google/shaka-player#2344]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
master

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `master`?**
yes

**Are you using the demo app or your own custom app?**
custom

**If custom app, can you reproduce the issue using our demo app?**
most likely yes

**What browser and OS are you using?**
that's irrelevant

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What did you do?**

used sample code for FairPlay DRM

**What did you expect to happen?**
have FairPlay protected content working

**What actually happened?**

completely missed the typo in documentation. It says:
player.getNetworkingEngine().registerResponseFilter((type, request) => {

while it should be:
player.getNetworkingEngine().registerResponseFilter((type, response) => {

**Comment by theodab** [comment]
Yeah, looks like a typo. Thanks for pointing it out!
