### ISSUE TITLE
Can't select audio track by "role"

### ISSUE THREAD

**Issue by salmoro** [google/shaka-player#2346]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.8

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Haven't tried

**Are you using the demo app or your own custom app?**
Both

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Windows-10/Chrome-81

**What are the manifest and license server URIs?**
Email will be sent shortly to shaka-player-issues@google.com

**What did you do?**
Try selecting English track  with role "main"
(`player.selectAudioLanguage("en", "main")`)

**What did you expect to happen?**
Audio track should switch from English "alternate" to English "main"

**What actually happened?**
Selected track remained English "alternate"

**Notes**

- With this MPD You can know that the currently playing track is the alternate by either
    1.  Seeking 2 minutes in and hearing children speaking or
    2. Opening the network tab and seeing the "...128_eng_children_opus_eng_alternate.webm" file 
    being  fetched.
- Dash-If reference player ([v3.0.1](https://reference.dashif.org/dash.js/v3.0.1/samples/dash-if-reference-player/index.html)) successfully switches tracks by roles with this MPD.

**Comment by joeyparrish** [comment]
Thanks for the report.  This issue was triggered by having the "main" role appear in both video and audio streams.  The fix will be cherry-picked for v2.5.9.

**Comment by joeyparrish** [comment]
Cherry-picked to v2.5.9.
