### ISSUE TITLE
Support WebRTC MediaStream

### ISSUE THREAD

**Issue by jimmywarting** [google/shaka-player#2347]
**Is your feature request related to a problem? Please describe.**
A problem I got with my old chromecast gen 2 is that some video formats aren't supported but plays well on my browser. Therefore I would like to fallback to `video.captureStream` and let my computer transcode the video/audio to my chromecast throught WebRTC. As a bonus you would also be able to cast your Canvas, Screen, WebCam and Microphone and other things.

Now Cast Application Framework (CAF) don't support integrating with the media player somehow(?). 
You are just only able to change the source? I guess it uses `player.load(manifestUri)` internally (i don't know) but anyway i would be nice if shaka player where able to load streams coming from WebRTC too

(related #1620)

**Describe the solution you'd like**

```js
pc2.onaddstream = (evt) => {
  // video.srcObject = evt.stream
  // video.play()
 
  // MediaStream (WebRTC), could also be something from eg `canvas.captureStream`
  player.load(evt.stream)
}
```

**Comment by joeyparrish** [comment]
That's interesting, but a WebRTC stream is not a stream where we can pause, seek, change tracks, control buffering, decrypt, or anything else this project does.  Even our UI offers no particularly interesting features for WebRTC beyond what you'd get in the browser's native controls.

So I would advise you to use HTML5 video and WebRTC directly.  You can build a custom cast receiver for this, as well.  It's not very difficult to handle messaging using the Cast SDK, and you can use our source as a reference for the interesting touch points.  You could relay WebRTC-related messages over this channel and potentially get remote streams to show up on the ChromeCast.  (This is, of course, assuming that WebRTC is implemented on that platform, which I have not verified.)

Does this help?

**Comment by jimmywarting** [comment]
> (This is, of course, assuming that WebRTC is implemented on that platform, which I have not verified.)

I have verified that WebRTC works on chromecast (at least the DataChannel, so MediaStreams probably works too)

----

> but a WebRTC stream is not a stream where we can pause, seek, change tracks, control buffering, decrypt, or anything else this project does. Even our UI offers no particularly interesting features for WebRTC beyond what you'd get in the browser's native controls.

I get that and i would be willing to put in a extra effort into handling those controls on both the sender and the receiver device.
- like switching track on the sender
- handeling pauseing on maybe both sender and reciver (resuming might just jump to the live moment)
- changing buffer is somewhat possible with [playoutDelayHint](https://stackoverflow.com/questions/56510151/change-playout-delay-in-webrtc-stream) and i think you might be able to adjust it from either the sender and the receiver 

----

> So I would advise you to use HTML5 video and WebRTC directly. You can build a custom cast receiver for this, as well. It's not very difficult to handle messaging using the Cast SDK, and you can use our source as a reference for the interesting touch points. You could relay WebRTC-related messages over this channel and potentially get remote streams to show up on the ChromeCast. 



Based on this thread:
https://stackoverflow.com/questions/51010910/creating-a-custom-caf-receiver-with-video-element

>  --  Currently, custom players are not supported yet for the CAF receiver
> -- Should I revert to v2 receiver then? The cast.receiver.media.Player seems to have a lot of the same functionality. Any idea if I will be able to use a custom <video> element with this class?
> -- V2 does support a custom media player but v2 has been deprecated. 

Means that i can't use a own html5 video element? I want to use CAF so i can't replace the `<cast-media-player></cast-media-player>` for a `<video>` element and do my own thing? I guess i'm only limited to just using the javascript code that i write with `cast.framework`

(believe `cast.receiver` is for v2) and `cast.framework` is for v3.

v3 has other features like controlling stuff with a remote and saying commands with Home mini and more

So far i have only figure out that i can change the playable url by [intercepting messages](https://developers.google.com/cast/docs/caf_receiver/core_features#message_interception) and modifying the request - here i would probably try to establish a p2p connection and try to insert the MediaStream somehow but i have no idea how to interact with the video element inside the `cast-media-player` 
I figured CAF use the shaka player and just somehow just passes the `loadRequestData.media.contentUrl` to your `player.load()` function internally? But i have no clue of how shaka or the CAF SDK works.

So just maybe if i would set the `loadRequestData.media.contentUrl` to a MediaStream CAF would just call `player.load(mediaStream)` and it would start playing? (just speculations)

**Comment by joeyparrish** [comment]
CAF does use Shaka Player, but that's another team, and we have no control over the details or how Shaka Player is exposed.  If you really want to use CAF, you should file a support request for the Cast team to support WebRTC.

If you want to build your own solution, you could always use the Cast v2 SDK, as we do.  Our cast receiver is a custom receiver, and it has its own video element.

**Comment by jimmywarting** [comment]
ty for quick answer. Remember that i tried out Cast v2 before and i used a own video element back then...
Well, thanks anyway guess i need to investigate further - maybe will be able to hack it somehow
