### ISSUE TITLE
VTT Caption Styles

### ISSUE THREAD

**Issue by bloomtom** [google/shaka-player#2348]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.8

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Both

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Firefox 72 and Chrome 79

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
A test manifest is available [here](https://bloomtest.nyc3.digitaloceanspaces.com/roles/test5.mpd). The French text track contains a style to demonstrate the issue.
[Demo Link](https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://bloomtest.nyc3.digitaloceanspaces.com/roles/test5.mpd;panel=CUSTOM%20CONTENT;build=uncompiled)

**What did you do?**
Produce a DASH manifest containing VTT tracks with style tags like `<b>` and display the styled text track.

**What did you expect to happen?**
The displayed track should render the styles specified in the VTT cue.

**What actually happened?**
Text is displayed as a literal string without styling. The tags are visible to the user.
![EugEyvmY](https://user-images.githubusercontent.com/4093170/72701935-01e48580-3b1f-11ea-85f4-4a890ccaa8ff.png)

This issue was introduced with [4e7eed8b](https://github.com/google/shaka-player/commit/4e7eed8b3509f9f0babba029e109235166610021). I'm unsure if that change necessitates additional configuration for Shaka users to get fully rendered captions.

**Comment by michellezhuogg** [comment]
Hello,
Currently we don't support parsing the html tags inside the payloads.
The caption styles are not rendered because of we set payload as the captions 'textContent' instead of 'innerHTML'.  [Code](https://github.com/google/shaka-player/blob/master/ui/text_displayer.js#L230)
Here's the difference between them:
"Element.innerHTML returns HTML, as its name indicates. Sometimes people use innerHTML to retrieve or write text inside an element, but textContent has better performance because its value is not parsed as HTML. Moreover, using textContent can prevent XSS attacks."

Let us know if you have any further questions! Thank you!

**Comment by bloomtom** [comment]
@michellezhuogg Not rendering VTT style tags makes the project non-compliant with the specification, so that's a little disappointing. I understand though, the VTT spec is totally nontrivial. Using the browser to render the cue text with innerHTML isn't generally a valid solution anyway, as there are things like voices. The hundred little things in VTT is why Mozilla's [vtt.js](https://github.com/mozilla/vtt.js) has 44 releases and is 48KB minimized.

Is work on this area expected any time soon? If not, I may end up writing my own `TextDisplayer` to make styled cues more presentable for end users.

**Comment by joeyparrish** [comment]
You can certainly build your own `TextDisplayer` for this.  But would you be willing to contribute to the project to enhance `shaka.ui.TextDisplayer` instead?

I don't know what your specific goals are in terms of support, but it seems that you could start by parsing the `<b>`, `<i>`, and `<u>` tags while stripping out the others.  That would be fairly straightforward, I think.  We already support things like positioning, so it really just comes down to the mark-up.

It seems like classes would also not be too tough.  We could add the class names to the relevant DOM elements, and the application could choose to style them accordingly.  (Though not with `::cue` as it would with native text rendering.)

**Comment by bloomtom** [comment]
Sure. Allowing bold, underline, and italic while stripping everything else was going to be my first pass at it anyway. I can turn this work into a pull request.

**Comment by joeyparrish** [comment]
Thank you so much!  We really appreciate it.
