### ISSUE TITLE
CORS configuration issue is shake-player-demo server?

### ISSUE THREAD

**Issue by charlie-ht** [google/shaka-player#2351]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes. The mention of CORS in the FAQ, and the various CORS-related issues I found in the issue tracker, all hint that the server administrator needs to change the `Access-Control-Allow-Headers` HTTP header, but in this case the servers are hosted by the Shaka project (I think).

**What version of Shaka Player are you using?**

v.2.5.8 (uncompiled)

**Can you reproduce the issue with our latest release version?**
The demo player does not look like it lets me test that.

**Can you reproduce the issue with the latest code from `master`?**
N/A

**Are you using the demo app or your own custom app?**
Demo app

**If custom app, can you reproduce the issue using our demo app?**
N/A

**What browser and OS are you using?**
WebKitGTK/Debian

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**

I don't know, I am trying to play the only ClearKey test available on the demo page. It's URL is https://shaka-player-demo.appspot.com/demo/#audiolang=en-GB;textlang=en-GB;uilang=en-GB;asset=https://storage.googleapis.com/shaka-demo-assets/angel-one-clearkey/dash.mpd;panel=SEARCH;build=uncompiled

**What did you do?**

Go to the above URL, the Fetch API fails because it hits a CORS issue fetching https://cwip-shaka-proxy.appspot.com/clearkey?_u3wDe7erb7v8Lqt8A3QDQ=ABEiM0RVZneImaq7zN3u_w

**What did you expect to happen?**
https://cwip-shaka-proxy.appspot.com/clearkey?_u3wDe7erb7v8Lqt8A3QDQ=ABEiM0RVZneImaq7zN3u_w is fetched fine.

**What actually happened?**
CORS errors

I do not understand CORS, but from what I've made out so far, I think the administrator of `cwip-shaka-proxy.appspot.com` should modify `Access-Control-Allow-Headers`  so that `cwip-shaka-proxy.appspot.com` can fetch resource from it?

![image](https://user-images.githubusercontent.com/14251608/73001094-cb965700-3df9-11ea-97f3-3faf667dbbeb.png)

**Comment by joeyparrish** [comment]
We own `cwip-shaka-proxy.appspot.com`, which we use as a license proxy for demo, testing, and training purposes.  So you were right to bring this to us.

But this content is working fine for me using the link you gave: https://shaka-player-demo.appspot.com/demo/#audiolang=en-GB;textlang=en-GB;uilang=en-GB;asset=https://storage.googleapis.com/shaka-demo-assets/angel-one-clearkey/dash.mpd;panel=SEARCH;build=uncompiled

It's possible that there was a temporary outage of some kind for the license proxy.  Can you please try again?

**Comment by joeyparrish** [comment]
I should also clarify that I tested this on ChromeOS.  I don't have WebKitGTK handy right now.  Can you please try again on both a typical desktop browser such as Chrome or Firefox and WebKitGTK, in case it turns out to be a browser-implementation-specific issue?

**Comment by charlie-ht** [comment]
Thanks for the information @joeyparrish , I should have thought to check other browsers. Chrome does indeed work well for me, and I assume it's configured to enforce CORS :-)

It looks then like an issue with WebKitGTK that I will investigate, sorry for the noise and thanks again.

**Comment by joeyparrish** [comment]
No worries.  Is your WebKitGTK-based browser homebrewed, or from a debian package?  I tried epiphany just now, and it doesn't even have the ClearKey CDM enabled.

**Comment by charlie-ht** [comment]
@joeyparrish I'm running with a trunk version of WebKitGTK, and in fact I'm working on the ClearKey support there :-). By default EME is not enabled in WebKitGTK releases, but thanks for trying it!

**Comment by joeyparrish** [comment]
Ah, okay, that explains it.  :-)

Let us know if there's anything else we can do to help.
