### ISSUE TITLE
Select audio language doesn't show the check icon

### ISSUE THREAD

**Issue by michellezhuogg** [google/shaka-player#2353]
After selecting an audio language, there should be an icon indicating the language is selected.

https://nightly-dot-shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://storage.googleapis.com/shaka-demo-assets/bbb-dark-truths-hls/hls.m3u8;panel=HOME;build=uncompiled

**Comment by joeyparrish** [comment]
Cherry-picked to v2.5.9.
