### ISSUE TITLE
Shaka-player and WASM

### ISSUE THREAD

**Issue by oScape** [google/shaka-player#2354]
I am actually working for rewrite a part of this repository in Rust-lang for compile it in Web Assembly. The part I am rewriting is the HLS parser in first, I want to benchmark the performance. If there is some gain I will continue to work on it.

Is there a working group which had worked on it, or is working on, or will work on?

**Comment by joeyparrish** [comment]
We have no plans to rewrite Shaka Player in Rust at this time.  But as long as you're adhering to the Apache license terms, you can certainly do that in your fork.

I do not believe we would accept a PR for any portion of Shaka Player written in Rust at this time, but if you find significant performance issues in the library or significant performance gains from your rewritten portions, please do let us know your results.  This could inform our decisions in the future.

Thanks!

**Comment by oScape** [comment]
Thanks for the reply.

I understand about the PR in Rust on Shaka Player, my goal is to benchmark it yet. I will send it to you the result when it's done.

Best regards.

**Comment by joeyparrish** [comment]
Thanks!

**Comment by oScape** [comment]
@shaka-bot, yes it's alright. Thanks.
