### ISSUE TITLE
FLAC in fMP4 via HLS in Safari fails

### ISSUE THREAD

**Issue by enjikaka** [google/shaka-player#2355]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.6

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `master`?**
haven't tried

**Are you using the demo app or your own custom app?**
own

**If custom app, can you reproduce the issue using our demo app?**
yes

**What browser and OS are you using?**
macOS 10.15.1 Beta (19B77a), Safari Version 13.0.3 (15608.3.10.1.3)

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**

**What did you do?**
Tried to play a HLS master playlist with FLAC in fMP4

**What did you expect to happen?**
It plays

**What actually happened?**
Running shaka in debug mode I see it correctly recognizes codecs and mime types and the player both in our app and in shaka demo app starts playing and everything looks fine, but there is no sound output.

**Comment by TheModMaker** [comment]
On Safari, we use native `src=` playback for HLS.  This means we just give the manifest to the browser and it plays it.  So there is probably nothing we can do about this.  Probably what is happening is the browser is just playing the video since it doesn't support FLAC.

**Comment by enjikaka** [comment]
@TheModMaker Hmm. Could it maybe be that they just support normal FLAC in MP4 then? And not fragmented or via HLS? 🤔Version 89 of Safari Tech Preview says they "Fixed support for FLAC-in-MP4": https://developer.apple.com/safari/technology-preview/release-notes/#r89

**Comment by joeyparrish** [comment]
It's always possible that there's a difference between what native HLS supports and what is supported for playback of single files or through MediaSource.

If you're on desktop Safari and not using FairPlay, try configuring Shaka Player to prefer MediaSource and see if that changes your results:

```js
player.configure('streaming.useNativeHlsOnSafari', false);
```

**Comment by enjikaka** [comment]
@joeyparrish Aha, didn't know there would be a difference in support there. When I throw the test stream I had, HLS without Fairplay, into HTMLVideoElement Safari errored out with a generic error. 
I'll create a ticket in WebKits bug tracker for this!

Shaka pretended it was playing and that everthing is fine though... Maybe there is some error handling missing in shaka-player for this case? I don't remember getting any errors at all from Shaka. 
I'll re-check that tomorrow just to be sure!

**Comment by joeyparrish** [comment]
Shaka Player should filter out unplayable streams, so if none of the audio can be decoded by the browser, I would expect to see video-only playback.  Does this match what you're seeing?
