### ISSUE TITLE
Is it possible to download subtitles?

### ISSUE THREAD

**Issue by Inoreen** [google/shaka-player#2359]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.5

**Please ask your question**
I've been trying to build an app using shaka-player and am at the finishing stages. Currently I'm working on the selection of options for the user that he can choose from to download.
So far I managed to let the user pick a combination of audio/video to download. However, some media files also include subtitle tracks, which I'd like the user to be able to choose to download as well.
So far I couldn't find out how to do that. Am I missing something?

**Comment by ismena** [comment]
Hi @Inoreen 
It's definitely possible to download subtitles and we actually do this by default with no specific action required from your side (you can try this out on our [demo page](https://nightly-dot-shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;panel=SEARCH;build=uncompiled) by filtering assets that are both "Downloadable" and have subtitles).

Just follow our [offline tutorial](https://github.com/google/shaka-player/blob/c996dfbb15b65e0ece522517ee50ef5ab0e26060/docs/tutorials/offline.md) and you should be all set.

**Comment by ismena** [comment]
Oh, a teammate just pointed out to me that if you're already providing a callback to select tracks for offline, you might not get the default behavior of selecting all subtitle tracks.

Let me point you to the code that does the track selection in for our defaults, so you can copy the parts that are relevant for your app.
[This is](https://github.com/google/shaka-player/blob/ad9e5b9ecd020cadc277fa52db536f5f23aae01f/lib/util/player_configuration.js#L255) our default callback and [here](https://github.com/google/shaka-player/blob/ad9e5b9ecd020cadc277fa52db536f5f23aae01f/lib/util/player_configuration.js#L337) is the bit that deals with adding subtitles to the stored tracks.

Let me know if that helps!

**Comment by Inoreen** [comment]
Thanks for your reply @ismena !
I already worked through the offline tutorial and therefore used a callback like you mentioned.
Therefore, as far as I understood, I used the function **initStorage**, which in return has a callback to **selectTracks**.

Now, I already modified the **selectTracks** function to have the functionality as mentioned before. So looking at the links you provided, I assume that, in theory, I could basically copy the [defaultTrackSelect](https://github.com/google/shaka-player/blob/ad9e5b9ecd020cadc277fa52db536f5f23aae01f/lib/util/player_configuration.js#L255) function in order to have the default behavior of the demo page right?
If that is so, then I'll just use the defaultTrackSelect function and modify it to my needs. 

I just want a confirmation that I actually understood it correctly, so I can further develop my application without any issues.

**Comment by TheModMaker** [comment]
Yes, you could just copy it, or you could build your version from scratch.  The part you care about is the [last few lines](https://github.com/google/shaka-player/blob/ad9e5b9ecd020cadc277fa52db536f5f23aae01f/lib/util/player_configuration.js#L337) where it selects the text tracks.  You can just add all the `TEXT` tracks to the returned array.
