### ISSUE TITLE
IE11 promises working when compiled

### ISSUE THREAD

**Issue by sarge** [google/shaka-player#236]
Running the compiled version on IE11 does not find the resolve and reject methods on the promise polyfill

Load in IE11 and attempt play anything
https://shaka-player-demo.appspot.com/?compiled

The promise implementation only appears to work when compiling using -O SIMPLE -D COMPILED=false

Probably a simple fix for someone who knows their way around the closure compiler.

Cheers

Mark

**Comment by joeyparrish** [comment]
Thanks, Mark.  We made a mistake there for sure.

My first thought was that we should have exported the static methods, but that doesn't seem to work without exporting the constructor as well.  Instead, it looks like we will have to assign the static methods in the polyfill's installer.

Shouldn't take long to publish a fix, which we will roll into v1.6.1.
