### ISSUE TITLE
Mobile detection on iPad may be broken

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#2360]
According to @gregwfreedman, iPad OS 13+ has a user agent that doesn't say iPad, so our mobile detection may be broken there.

**Comment by ismena** [comment]
There appears to not be good way to 100% detect it.
The best-looking hack [I was able to find](https://stackoverflow.com/questions/57765958/how-to-detect-ipad-and-ipad-os-version-in-ios-13-and-up) is this ugly block of code:
```
if ((/\b(iPad)\b/.test(navigator.userAgent)
    && /WebKit/.test(navigator.userAgent)
    && !window.MSStream)
    || (navigator.platform === 'MacIntel'
    && navigator.maxTouchPoints
    && navigator.maxTouchPoints === 5)
  ) {
        return true;
    }
```

**Comment by joeyparrish** [comment]
Ah, I see.  Check for iPad in the UA string, or alternately look for maxTouchPoints.  Should be okay until there's a touch-screen Mac out there.

I'll put together something similar, but less picky.

**Comment by joeyparrish** [comment]
Cherry-picked to v2.5.9.

**Comment by niklaskorz** [comment]
Out of interest, what's the point of differentiating between iPadOS and macOS Safari? I thought Apple intentionally made it hard to tell them apart so web applications treat them as normal desktop browsers.

**Comment by joeyparrish** [comment]
In the current `master` branch and the upcoming v2.6 release, our default UI configuration depends on whether a device is mobile or not.  That's the only reason to detect iPadOS.

For mobile devices (which are primarily touch-based), we put a large play/pause button in the middle of the frame.  For desktop devices (which are primarily mouse-based), we put a small play/pause button next to the current time.

These are only the defaults, and apps can configure the UI however they wish, on any platform.  We provide `video.ui.isMobile()` for convenience if you want to have a mobile-dependent config like our default.
