### ISSUE TITLE
Regarding Fairplay

### ISSUE THREAD

**Issue by sridhard** [google/shaka-player#2361]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
Latest version from master

**Please ask your question**
Does shaka-player support persistent licenses for fairplay on safari(mac and ios)? Is the persistent license handling is same as widevine/playready?

**Comment by ismena** [comment]
@joeyparrish @TheModMaker fairplay experts input, please!

**Comment by TheModMaker** [comment]
I'm not that familiar with persistent licenses in FiarPlay.  But the answer is probably we don't support it.  We only support FairPlay in src= content, where we don't do much.  We also don't support storing/playing offline with src=.

**Comment by sridhard** [comment]
ok
