### ISSUE TITLE
Add loop and playbackrate controls to UI

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#2362]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes

**Is your feature request related to a problem? Please describe.**

Add loop and playbackrate controls to UI.

**Describe the solution you'd like**

Add loop button to the UI
Add playbackrate selector to the UI. The list of the playback rates should be configurable.

**Comment by ismena** [comment]
Loop as in play current video over and over again?

A definite yes for the playback rate control, the loop one sounds a bit too niche. Let me discuss with @joeyparrish (who might want my time spent elsewhere). If it doesn't happen, I'll be happy to guide you through creating a custom loop control.

**Comment by joeyparrish** [comment]
There's a loop attribute in HTML5 video, both in HTML & JS, and native browser controls sometimes include a loop option when you right-click the video.  It's not too niche, and implementing it should be as simple as setting the loop property to true/false on the video when the button is toggled.

I expect both of these should go in the overflow menu.

I'd be open to feedback from @avelad if he'd prefer the loop button in the button panel, as opposed to the overflow menu.  We could also create both overflow & button versions of the loop control if it's useful for developers to have the choice between the two.

**Comment by avelad** [comment]
Thanks for your responses. For me it's enough that both option are shown in the overflow menu
