### ISSUE TITLE
Add integration with IMA DAI for Live and VOD

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#2367]
Information about DAI: https://developers.google.com/interactive-media-ads/docs/sdks/html5/dai

For Live I need to be able to customize the following parameters:
- adTagParameters (Object)
- assetKey
- apiKey
- backup stream

For VoD I need to be able to customize the following parameters:
- adTagParameters (Object)
- contentSourceId
- videoId
- apiKey
- backup stream

I also need the following events to be exposed to the application:
- AD_BREAK_STARTED
- AD_BREAK_ENDED
- AD_PROGRESS (expose adProgressData, eg: `event.getStreamData().adProgressData`)
- STARTED
- FIRST_QUARTILE
- MIDPOINT
- THIRD_QUARTILE

Things I have found that can be useful for integration:
For live stream it's necessary setup some metadata information:
https://developers.google.com/interactive-media-ads/docs/sdks/html5/dai/timed-metadata
- Native HLS in Safari:
```
video.textTracks.addEventListener('addtrack', (event) => {
  const track = event.track;
  if (track.kind === 'metadata') {
    track.mode = 'hidden';
    track.addEventListener('cuechange', () => {
      for (const cue of track.activeCues) {
        const metadata = {};
        metadata[cue.value.key] = cue.value.data;
        if (streamManager) {
          streamManager.onTimedMetadata(metadata);
        }
      }
    });
  }
}
```
- HLS managed by ShakaPlayer
I think there is a lack of data to be able to notify DAI. It would be necessary to notify with ID3, but I have not seen a way to obtain it, maybe something is missing with mux.js (https://github.com/videojs/mux.js/#metadata)

- DASH
```
player.addEventListener('timelineregionadded', (event) => {
  const detail = event.detail;
  if (detail && detail.schemeIdUri === 'urn:google:dai:2018') {
    const type = detail.schemeIdUri;
    const data = detail.eventElement ? detail.eventElement.getAttribute('messageData') : null;
    const timestamp = detail.startTime;
    if (streamManager) {
      streamManager.processMetadata(type, data, timestamp);
    }
  }
}
```

And one thought, does UI make sense of ads for Live?

**Comment by avelad** [comment]
@ismena, Is it possible integrate DAI (SS) with preroll (CS) ?

Example: https://github.com/googleads/googleads-ima-html5-dai/blob/master/dai_preroll/dai.js

I think the current architecture does not allow this, but I would like to be sure of it.

**Comment by ismena** [comment]
We don't have an explicit path for this, but there's nothing prohibiting this in the current design, so I think (I haven't tried) it should work through a flow like this (pseudocode, LMK if something's unclear):
initServerSide();
initClientSide();
loadSSStream(ssRequest);
requestCSAds(csRequest);

If you have autoplay on your video, you might have to disable it, so the video doesn't start before the ad (if there's a race).

Does it make sense?

**Comment by avelad** [comment]
@ismena I think that this issue is covered with all change in the master. Can you close it and put the version 2.6?

**Comment by ismena** [comment]
LIVE HLS still needs some work on integrating with mux.js parsing in ID3 tags.
I can open a new targeted issue for that though.
