### ISSUE TITLE
Shaka can read the Start TimeCode embedded into video mp4 h264?

### ISSUE THREAD

**Issue by matiaszumbo** [google/shaka-player#2369]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**

**Please ask your question**
If the video Start  TimeCode is for example 03:00:00:00 the player can read this value?

**Comment by ismena** [comment]
Yes! But I might need more context to help you better. What does your use case look like?

We rely on the start time provided by the manifest for DASH and we retrieve it from the MP4 itself for HLS.

**Comment by matiaszumbo** [comment]
Can the player extract the embedded timecode information, and show this to the end-user?
In this case, the video is a non-zero timecode, meaning the starting point is not 00:00:00:00 but rather 00:57:30:00.  This is supported by the player? 
The video is a mp4/h264.

I need a player just to visualize the local content (lowres) in a web page, but showing the time in brodast format hh:mm:ss:ff (the video has a embedded timecode)

**Comment by ismena** [comment]
Oh, like the time code on security cameras?
Or do you mean that the video feed itself starts at 0, but you need it to start playing from 00:57:30:00 and skip everything before it?
Do you want to keep showing startTime + elapsedTime to the user, dynamically updating it?

@joeyparrish do you remember if any of the easy properties like video.currentTime will reflect the time code?

**Comment by matiaszumbo** [comment]
It's a local video mp4 ok?
And the video has the embedded time code, this timecode starts at 04:00:00:00..
I want that the player shows the current time like this 04:00:10:27 (after 10 seconds for example)
and not 0:10 

EXAMPLE:
![image](https://user-images.githubusercontent.com/35058174/73579562-7abdd880-4461-11ea-880b-c377d664526c.png)

**Comment by joeyparrish** [comment]
If you're playing a single mp4, the timestamps in the file are what will show in the UI for the current time.  This will be true whether you're using our UI or the browser's native controls.

**Comment by matiaszumbo** [comment]
But i need to see the timecode of the video not the current time.

Maybe the video tc start is 02:00:00:00

When playing 10 seconds i need to see
02:00:10:24 and not 0.10

it's possible?

Thanks!

**Comment by joeyparrish** [comment]
I think the "current time" of the video is what you're looking for.  In JavaScript, that's `videoElement.currentTime`.  It's not the "wall clock time", as in "8:32 pm".  It's a timestamp in seconds.  Just try it out and see.

**Comment by matiaszumbo** [comment]
When you have a Master film for example.
You need to Edit and cut it into chapters from 1 to 6 For example.

The chapter 1 start at time 0 hours 0 minutes 0 seconds 0 frames. But
chapter 4 Start at 1 hour 23 minutes 12 seconds 29 frames.
That information is embedded into the video.

So if I play the chapter 4 from The begining I want to see 01:23:12:29 not
0.0 seconds

The request will be:
I want to see the timecode embedded into the video hh:mm:ss:ff not the
current time.

**Comment by joeyparrish** [comment]
It sounds like what you want is a timestamp embedded in some format in the mp4.  I don't know what format that is, but if it's chapter metadata from an editor, I'm sure that's not being read by the browser and that there's no API in a browser to get that for you.

I'm sorry that we aren't able to help you with this.
