### ISSUE TITLE
Clarification on customizing "drm.initDataTransform"

### ISSUE THREAD

**Issue by salmoro** [google/shaka-player#2370]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.8

**Please ask your question**
I recently reported an [issue](https://github.com/google/shaka-packager/issues/696) on the Shaka Packager issue tracker regarding an error I get for Fairplay content packaged with Shaka Packager and played with Shaka Player: `Shaka Error DRM.INIT_DATA_TRANSFORM_ERROR (RangeError: Malformed FairPlay init data)`. 

They brought in @joeyparrish asking if he knew what it might be and he responded with referencing the [Tutorial](url) for customizing the init data.

The issue I'm facing is that It's not clear to me how to go about implementing a custom `initDataTransform`. The tutorial show a code sample using a function called `getMyContentId` with no further elaboration.

Also, the tutorial states `If you don't use the default content ID derivation, you need to specify a custom init data transform:` Which seems to imply that it's not required.

Any help would be appreciated. Thank you.

**Comment by ismena** [comment]
Tagging our drm experts @joeyparrish @TheModMaker

**Comment by TheModMaker** [comment]
My guess is your transform is being called twice, the second time fails.  This is probably #2214 or #2364.  Does it work if you ignore the second call?

The content ID is used by your license server to determine which keys to give out.  If you use default settings for content encryption, you should be able to use the default transform.  Otherwise you will need to update however you determine your content ID from your content.

**Comment by salmoro** [comment]
@TheModMaker Looking at the network tab both requests return 500.

This is in contrast to [JW player](https://www.jwplayer.com/developers/stream-tester/) which gets a 200 and plays well.

[Here](https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://temp-for-testing-shlomo.s3.amazonaws.com/fairplay-shaka-issue/shaka/master.m3u8;license=https://fps.ezdrm.com/api/licenses/0f3f9b02-2163-4fed-bc84-657ce217a3e9;certificate=https://jem-ccdb-media.s3.amazonaws.com/video/static/fairplay.cer;panel=CUSTOM%20CONTENT;build=uncompiled)'s a link to Shaka Demo with all the urls (m3u8, cert, license-server).

**Comment by TheModMaker** [comment]
Getting a 500 response is different from `DRM.INIT_DATA_TRANSFORM_ERROR`.  The `DRM.INIT_DATA_TRANSFORM_ERROR` means the init data transform function threw an exception; a 500 response means the init data transform worked fine but the license server rejected the request.

My guess is there are two errors here.  First is #2214 where we call the init data transform twice.  The first works fine, and the second gives a `DRM.INIT_DATA_TRANSFORM_ERROR`.  The other error is the first transform call works but is rejected by the server.  What is probably happening is the server doesn't recognize the data.  The data could be invalid from the browser, the server may expect you to wrap/transform the data before sending it, or your content ID may be invalid.

If JW Player works out-of-the-box, we may need to look at how they are handling the license to see why we get a 500 from the server.

**Comment by TheModMaker** [comment]
After fixing #2214 this seems to play fine.  Could you try with the latest `master`, or the [nightly](https://nightly-dot-shaka-player-demo.appspot.com/demo/)?

**Comment by TheModMaker** [comment]
Also, we'll probably cherry-pick the fix for v2.5.10; in that case, you need to set `drm.fairPlayTransform` configuration to `false`.

**Comment by salmoro** [comment]
@TheModMaker Yup that fixed it. TYVM!
