### ISSUE TITLE
Add a presentationDelay setting for HLS live

### ISSUE THREAD

**Issue by rdglge** [google/shaka-player#2373]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes.

**What version of Shaka Player are you using?**
2.5.8

**Please ask your question**

I would like to be able to set the delay of a live stream via an API call so that the audio is up to 5 seconds behind the live source. 

(Eventually I might want to use a custom control for this.)

Is there an API call to set the delay or latency? 
What resolution can the delay be set in, tenths of a second? Milliseconds?

(The only delay I have found so far is for setting a delay is baseDelay which seems related to retryParameters and is not what I am looking for.)

**Comment by chrisfillmore** [comment]
Are you playing DASH? This sounds like `suggestedPresentationDelay`, which is a value you can supply in your manifest to tell the player how far back it should play from the live edge.

Alternately, you can provide Shaka with a [defaultPresentationDelay](https://github.com/google/shaka-player/blob/02db99f567f0552e76dfaddd3f9e940c321c8cc8/lib/util/player_configuration.js#L92), which will be used if there is no `suggestedPresentationDelay` in the manifest.

**Comment by rdglge** [comment]
I am using HLS.

Will setting the suggestedPresentationDelay affect HLS playback?

I will look into suggestedPresentationDelay. What class is it part of? And is there a setter function?

**Comment by ismena** [comment]
@rdglge What @chrisfillmore is talking about is only applicable to DASH. In HLS the default presentation delay is 3xtarget duration.

I don't see any reason not to add the same configuration to our HLS parser.
Let me schedule this as an enhancement.

**Comment by rdglge** [comment]
My original question comes from my goal to be able to set an adjustable delay in an audio only hls stream. I am not sure if a presentationDelay is the best way to do this. I will leave that to you all to decide. 

I see that the UI controls allow you to move the play head with a slider so I figured there must be a way to start playing at a specific time code. Ideally, I would like more fine grained control than what can be done with a slider. That is why I am looking for an API to start playing at a specific delay from the live edge.

To clarify, is there an API to set such a delay in shaka player currently?

**Comment by joeyparrish** [comment]
There are several things inter-related at work here.

1. The presentation delay decides how close to the edge you can get in a live stream.  By default, we start playback there.  This delay is hard-coded to 3 segment lengths in our HLS parser.  For DASH, it is taken from the manifest and overridable by config.  We proposed to add a similar config for HLS.
2. You can choose a playback start time by passing a presentation timestamp to player.load.  For example, `player.load('foo.m3u8', 1234);` will start playback at time 1234.  This is subject to seek range limitations, so if you pick a time outside the seek range, we will bump it back into that range.
3. The seek range, like the presentation delay, is hard-coded in HLS to match Apple's implementation.  In DASH, this is taken from the manifest (called the availability window).  By default, it's a 0-width range in HLS, which effectively disables seeking.  There is a config to override this for both DASH & HLS.  Try `player.configure('manifest.availabilityWindowOverride', 60);` if you want a seek range of 60 seconds in live streams.

Does this help?

**Comment by joeyparrish** [comment]
Starting with the v2.6.0 release and now in the `master` branch, you can use this configuration to change the presentation delay for HLS and DASH both:

```js
player.configure('manifest.defaultPresentationDelay', 1.0 /* seconds */);
```

If left unconfigured or set to 0, the default will be:
  - 1.5 * `minBufferTime` for DASH
  - 3 * segment duration for HLS

**Comment by udayravuri** [comment]
@joeyparrish any idea when v2.6.0 would be coming out? 
We badly need this flag.

**Comment by joeyparrish** [comment]
We discovered an issue late in the release process (#2528) that must be resolved before the release can be completed.  The compiler was generating bad code in one of the ES6 polyfills.  The compiler upgrade requires us to update type info in many places, and has been in progress for several days.  We hope to have this resolved soon.

**Comment by udayravuri** [comment]
Thanks for the update. Just want to double check, v2.6.0 will have this config for both DASH & HLS but does v2.5.10 have it already for DASH?

**Comment by joeyparrish** [comment]
Correct.  We've had this configuration for DASH for a long time.

**Comment by udayravuri** [comment]
Thank you very much

**Comment by udayravuri** [comment]
Hi @joeyparrish ,
I made the following changes to shaka config to reflect the overrides including 'defaultPresentationDelay'.
Our live manifest has these values and the attempt here is to override them and see if we improve VST (video start time):
suggestedPresentationDelay="PT6.0S" … minBufferTime="PT6.0S"

Shaka config changes:
				"live": {
					"restrictions": {
						"minHeight": 360,
						"minWidth": 640
					},
					"manifest": {
						"defaultPresentationDelay": 1.0,
						"retryParameters": {
							"maxAttempts": 2,
							"baseDelay": 1000,
							"backoffFactor": 2,
							"fuzzFactor": 0.5,
							"timeout": 5000
						},
						"dash": {
							"ignoreMinBufferTime": true
						},
						"availabilityWindowOverride": null
					},
					"streaming": {
						"retryParameters": {
							"maxAttempts": 2,
							"baseDelay": 1000,
							"backoffFactor": 2,
							"fuzzFactor": 0.5,
							"timeout": 10000
						},
						"bufferingGoal": 6,
						"rebufferingGoal":1,
						"bufferBehind": 6,
						"smallGapLimit": 0.5,
						"jumpLargeGaps": false,
						"startAtSegmentBoundary": false
					},
					"abr": {
						"enabled": true,
						"defaultBandwidthEstimate": 1000000,
						"switchInterval": 12,
						"restrictions": {
							"maxBandwidth": 5500000
						}
					},
					"preferredAudioChannelCount": 2
				},

For some reason I'm not seeing the VST change that much in spite of the above mentioned shaka config changes. I even set this to lowest to force Shaka to pick the lowest resolution to begin with:  "defaultBandwidthEstimate": 1000000, ( less than 1 Mb/sec).

Our VST is roughly this duration: (PLAYER_STATE.PLAYING - PLAYER_STATE.LOADED) - Buffering time

Any suggestions on how to troubleshoot this would greatly help. Also, I'm not sure how I could turn on Shaka player logging on v2.5.10 - so please advise.

Thank you.

**Comment by joeyparrish** [comment]
In v2.5, the `defaultPresentationDelay` field is in `manifest.dash`, not `manifest`.  If you check the JavaScript console, you'll see an error message about it, even in a compiled version of Shaka Player.  `configure()` also returns false when you supply an invalid field.  (All other fields are still applied.)  For example:

```js
player.configure('manifest.defaultPresentationDelay', 1)
config_utils.js:54 Invalid config, unrecognized key .manifest.defaultPresentationDelay
false

player.configure('manifest.dash.defaultPresentationDelay', 1)
true
```

Starting in v2.6, we move `defaultPresentationDelay` to `manifest`, since it will no longer apply only to DASH content.  We will still accept `manifest.dash.defaultPresentationDelay`, but issue a warning that you should update to `manifest.defaultPresentationDelay`.  In v2.7, we will only accept `manifest.defaultPresentationDelay`.

Does this help?

**Comment by udayravuri** [comment]
Yes, absolutely. I'm trying now with manifest.dash.defaultPresentationDelay in the above config & checking to see if it improves our VST. 
Thanks so much!!

**Comment by joeyparrish** [comment]
Always happy to help!  Sorry for the confusion.
