### ISSUE TITLE
Why are player.seekRange start and end the same?

### ISSUE THREAD

**Issue by rdglge** [google/shaka-player#2374]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.8

**Please ask your question**

I have an audio only HLS stream. When I call player.seekRange() the start and end time are the same.

Why is this? Shouldn't the player be able to seek at least as long as the current media segment? So let's say the segments are 4 seconds long, shouldn't shaka player be able to seek back 4 seconds at least?

player.seekRange()
{start: 79796.76316428185, end: 79796.76316428185}

**Comment by joeyparrish** [comment]
This is to emulate the behavior of Apple's native HLS implementation, in which you are not permitted to seek in live streams.  This will be different in VOD content, where you can seek anywhere, or in DASH live content, where the content indicates how much you are allowed to seek.

**Comment by rdglge** [comment]
I am using HLS.

If I use the shaka UI controls will I be able to seek in an HLS stream?

If the duration of the media segment is 4 seconds shouldn't I be able to at least seek 4 seconds?

**Comment by joeyparrish** [comment]
> If the duration of the media segment is 4 seconds shouldn't I be able to at least seek 4 seconds?

In HLS, not by default.  By default, your seek range is effectively 0, by design, to emulate Apple's native HLS.  You can override this range for both HLS & DASH with a config, though.

Try `player.configure('manifest.availabilityWindowOverride', 60);` if you want a seek range of 60 seconds in live streams.

Does this help?

**Comment by rdglge** [comment]
That is helpful. Thank you. 

I plan to try player.configure('manifest.availabilityWindowOverride', 60); soon and see what effect it has.

**Comment by rdglge** [comment]
I put a call to  player.configure right before player.load.

What I noticed is that the playlist is repeatedly downloaded. Only one segment file is downloaded. Stream playback doesn't start when the playbutton is pressed.

![playlistDownload](https://user-images.githubusercontent.com/6098314/73790520-3b93ce00-4766-11ea-8972-4c6d54f6e429.png)

**Comment by rdglge** [comment]
Also the seek range doesn't seem to be affected.
![seekTime](https://user-images.githubusercontent.com/6098314/73790674-77c72e80-4766-11ea-8401-b71fb49e2400.png)

**Comment by michellezhuogg** [comment]
Hello @rdglge ,

I tested on our demo page https://nightly-dot-shaka-player-demo.appspot.com/ v2.5.9 and setting the availabilityWindowOverride works for me. 
shakaDemoMain.player_.seekRange()
{
  "start": 1721445.566333294,
  "end": 1721490.566333294
}
Could you please try again with the latest version, and let us know if it works?

**Comment by rdglge** [comment]
I loaded 2.5.9 from the cdn as follows:
<!DOCTYPE html>
<html>
  <head>
    

    <script src="https://cdn.jsdelivr.net/npm/shaka-player@2.5.9/dist/shaka-player.compiled.min.js"></script>
    
    <script src="js/shaka-player-app.js"></script>
    <script defer src="node_modules/mux.js/dist/mux.js"></script>
  </head>
  <body>
    <video id="video"
           width="640"
           poster="//shaka-player-demo.appspot.com/assets/poster.jpg"
           controls autoplay></video>

     


  </body>
</html>

I am still seeing the start and end times the same even after calling the override.
function initPlayer() {
  // Create a Player instance.
  var video = document.getElementById('video');
  var player = new shaka.Player(video);

  // Attach player to the window to make it easy to access in the JS console.
  window.player = player;

  // Listen for error events.
  player.addEventListener('error', onErrorEvent);

  if (player.configure('manifest.availabilityWindowOverride', 4)){
    console.log('override set');
  }

  // Try to load a manifest.
  // This is an asynchronous process.
  player.load(manifestUri).then(function() {
    // This runs if the asynchronous load is successful.
    console.log('The video has now been loaded!');
  }).catch(onError);  // onError is executed if the asynchronous load fails.
}

player.seekRange()
{start: 61069.87604236603, end: 61069.87604236603}

**Comment by michellezhuogg** [comment]
Could you please provide a test file or a demo page link for us to test with?

**Comment by joeyparrish** [comment]
I just double-checked, and `player.configure('manifest.availabilityWindowOverride', 60);` is working as expected on HLS live streams.  So there doesn't seem to be any change required here.
