### ISSUE TITLE
Some demo app buttons must be double-clicked on iPad

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#2376]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
master

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Demo app

**What browser and OS are you using?**
Chrome 79 (stable)  & Safari 13 on iOS 13.3.1 on iPad

**What are the manifest and license server URIs?**
N/A

**What did you do?**
Touch the "dismiss" or "play" or "report bug" buttons on the demo page.

**What did you expect to happen?**
They should react to a click/touch, as the "home", "search", "custom content", and drawer buttons do.

**What actually happened?**
The button is highlighted as though hovered, but doesn't click until you touch it twice rapidly.

**Comment by theodab** [comment]
It looks like this is a problem with `mdl-js-ripple-effect` on iOS 13.
It's a known problem; see [this issue](https://github.com/google/material-design-lite/issues/5281) on the MDL github. However, apparently they're no longer maintaining MDL, so they won't fix it.
Some of the people in that github issue posted possible workarounds. I'll try those out.
