### ISSUE TITLE
Output multiple manifest files with track selection

### ISSUE THREAD

**Issue by hariszukanovic** [google/shaka-player#2384]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Is your feature request related to a problem? Please describe.**
My problem is that some players (out of my control) are unable to recognise a track they are unable to decode and render correctly... ending up in an error state when they have switched to it... 
A simple example would be a mix of interlaced and progressive video tracks when de-interlacing is not supported on some devices. Player is usually playing but it does not de-interlace... which of course is very ugly.
Another example would be to serve to some clients only lower resolution bitrates, others again (like Smart TV) serve only higher resolutions.

**Describe the solution you'd like**
I would like to generate multiple manifest files (Dash) where I would make a selection of tracks to carry in each of them. The point of multiple manifests is that I want to avoid packaging multiple times and producing different chunk files for any combination and thus waisting a lot of storage.

I would like to package each track only once and then decide whether to include it in each of the generated manifests...

**Describe alternatives you've considered**

- packaging multiple times for any combination of tracks (cannot work, waist of space)
- resolving problem player side (it is out of my control)

**Additional context**
In fact, I have done this myself using on-the-fly dynamic HLS playlist generator, but it seems not be as easily doable with Dash

**Comment by joeyparrish** [comment]
That sounds interesting, but not like a Shaka Player feature so much as a feature of how you generate and package the content.  Did you mean to file this on [google/shaka-packager](https://github.com/google/shaka-packager) instead?

**Comment by hariszukanovic** [comment]
I apologise. Indeed I meant to post this on the packager issue list :)

**Comment by hariszukanovic** [comment]
I opened the issue in correct project now
https://github.com/google/shaka-packager/issues/709

**Comment by joeyparrish** [comment]
No worries!  Thanks for your interest in Shaka Packager.
