### ISSUE TITLE
Some document pages are missing

### ISSUE THREAD

**Issue by ozc** [google/shaka-player#2385]
This is actually not a bug with the player, but the webpage. Some of the JSDoc pages are missing and displaying 404 error.

eg. 
https://shaka-player-demo.appspot.com/docs/api/shaka.Controls.html#.event:ResolutionSelectionUpdatedEvent

**Comment by joeyparrish** [comment]
Thanks for the report!  On what page of the docs did you find that broken link?

**Comment by ozc** [comment]
On API docs page.

https://shaka-player-demo.appspot.com/docs/api/index.html

**Comment by joeyparrish** [comment]
Excellent.  Thanks!  We'll see if we can fix the docs generation.
