### ISSUE TITLE
Seeking to video end ends up 1 second backward

### ISSUE THREAD

**Issue by leonchen** [google/shaka-player#2391]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
2.5.9

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `master`?**
yes

**Are you using the demo app or your own custom app?**
both

**If custom app, can you reproduce the issue using our demo app?**
yes

**What browser and OS are you using?**
firefox 72/chrome 80 on macOS 10.15.3

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
not tested

**What are the manifest and license server URIs?**

The `Sintel` video on the demo page

**What did you do?**

in browser console:
```
v = document.getElementById("video")
v.duration // returns 888.042
v.currentTime = 888.042 // seek to video end
v.currentTime // display video current time
887.042 // <<--- 1 second off
v.currentTime = 888.041 // seek to 1 ms before the end
v.currentTime
888.041 // correct
```

**What did you expect to happen?**
video.currentTime should be the same as video duration when seeking to duration

**What actually happened?**

video.currentTime is one second backward to the video end/duration time

**Comment by TheModMaker** [comment]
This is expected behavior, although we may want to seek backward for the 1ms before case too.  Some browsers have problems when seeking to duration; they will buffer forever, stall, or not report as ended correctly.  To provide a consistent cross-browser experience, we seek slightly backward and play to the end.  See #979.  This can be configured with:

```js
player.configure('streaming.durationBackoff', 0);  // Or 0.1, etc.
```

**Comment by leonchen** [comment]
Thanks for the explanation! Although it looks weird to me that this configuration is needed to make the normal cases working rather than a fix when it's not working..
