### ISSUE TITLE
HLS - support manifest with several #EXT-X-MAP tags

### ISSUE THREAD

**Issue by ppatlolla-turner** [google/shaka-player#2397]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Is your feature request related to a problem? Please describe.**
All our content has program segments and each program segment starts with a different init file. One of the primary reason to have multiple EXT-X-MAP tags. 

**Describe the solution you'd like**

**Describe alternatives you've considered**
Dash version does work but won't be able to use dash manifest in our workflows. 

**Additional context**
Will send sample streams with multiple #EXT-X-MAP tags via email.

<img width="1489" alt="hls playback multiple media init segments" src="https://user-images.githubusercontent.com/22914181/74566157-b52a7980-4f27-11ea-835d-12263381874e.png">

**Comment by TheModMaker** [comment]
This isn't about having multiple `EXT-X-MAP` tags, but because you use `EXT-X-DISCONTINUITY`, which we don't support.  See #1335.

**Comment by michellezhuogg** [comment]
Hello @ppatlolla-turner ,

I tested with your sample file, however it looks like it doesn't have multiple EXT-X-MAP tags, and I didn't see any error message. Could you please send us another file that has multiple EXT-X-MAP tags? Thanks!

**Comment by ppatlolla-turner** [comment]
Are you testing HLS version or DASH version? DASH should work fine.
There should be 6 EXT-X-MAP tags.
#EXT-X-MAP:URI="_169610_0_0.mp4"
#EXT-X-MAP:URI="_169610_0_1.mp4"
#EXT-X-MAP:URI="_169610_0_2.mp4"
#EXT-X-MAP:URI="_169610_0_3.mp4"
#EXT-X-MAP:URI="_169610_0_4.mp4"
#EXT-X-MAP:URI="_169610_0_5.mp4"

**Comment by michellezhuogg** [comment]
Got it. Thanks!

**Comment by joeyparrish** [comment]
This will be fixed as part of our discontinuity work.

**Comment by michellezhuogg** [comment]
Hello @ppatlolla-turner ,

This code change is on our latest nightly build https://nightly-dot-shaka-player-demo.appspot.com/ .
However, we're seeing "Shaka Error DRM.LICENSE_REQUEST_FAILED" error on our demo app. 
Could you please test again with your manifest, and let us know if it works?
Thank you!

**Comment by ppatlolla-turner** [comment]
I was able to play the stream sent via the above player. 
I guess you are not copying the license url correctly.
The license url should not have "https://urldefense.*".
Don't copy the url's using right click.  Copy the content of the email into a text file and then fetch the url's.

**Comment by ppatlolla-turner** [comment]
Hi @michellezhuogg 
I was able to play the multi_init segment stream using the above player. 

Just emailed the url's in a text file. Please try and confirm. 

If it still doesn't work I need to check if geo-location is turned on. Are you checking form outside US?
Thanks

**Comment by ppatlolla-turner** [comment]
Sorry I was too fast. Stream wouldn't continue playing after the first program segment. 
Earlier playback wouldn't even start. 
Thanks

**Comment by michellezhuogg** [comment]
Thank you! Will look into that.

**Comment by ppatlolla-turner** [comment]
Yes it continues it play after 3:25 but only after a long period off buffering.
