### ISSUE TITLE
player.isTextTrackVisible() throws an error while loading a new manifest.

### ISSUE THREAD

**Issue by londonshliach** [google/shaka-player#2399]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes.

**What version of Shaka Player are you using?**
2.5.8 and 2.5.9

**Can you reproduce the issue with our latest release version?**
Yes.

**What browser and OS are you using?**
Chrome 80 on Windows 10.

**What are the manifest and license server URIs?**
Manifest 1: https://jem-ccdb-media.s3.amazonaws.com/video/dist/jobs/522b3991-79cf-4651-becb-e85bb3a013b5/dash_vp8/master.mpd
Manifest 2: https://jem-ccdb-media.s3.amazonaws.com/video/dist/jobs/3661e2e3-cb5f-4c44-8411-4cd4ae1c36eb/dash_vp8/master.mpd
Licence: https://widevine-dash.ezdrm.com/proxy?pX=96B958

**What did you do?**
I played one Manifest, and then I loaded a different Manifest.
While the second manifest was loading I called `player.isTextTrackVisible()`.

**What did you expect to happen?**
The function would return true / false.

**What actually happened?**
The function throw an error:
Uncaught TypeError: Cannot read property 'g' of null
    at X.ic (media_source_engine.js:1081)

You can see it on this page:
https://elchonon.com/shaka/switch/
Open the console and then switch between Manifest 1 and Manifest 2 by clicking on the buttons on top of the page.
The error should show up in the console.

**Comment by joeyparrish** [comment]
Confirmed.  Thanks for the report!  We should be able to have this fixed for v2.5.10.
