### ISSUE TITLE
PlayReady IE11 issue

### ISSUE THREAD

**Issue by pajong** [google/shaka-player#240]
Hello,
I am having trouble getting PlayReady to work on IE11.
This is the drm listener that I am using:

new shaka.player.DrmSchemeInfo(
                        'com.microsoft.playready' /* keySystem */,
                        licenseServerUrl,
                        false /* withCredentials */,
                        null /* initData */,
                        null /* licensePostProcessor */);

On IE11, I get a console error saying:
The key system specified is not supported.

Is this not the correct way to setup the player?
If not, is there a working example of PlayReady?

Thank you so much!

**Comment by joeyparrish** [comment]
Hi @pajong.

What version of Shaka Player are you using?  PlayReady & IE11 support were added in v1.6.0, and only through polyfills.

Are you using shaka.polyfill.installAll()?  Do you see log messages in an uncompiled build like 'Using EME v20140218' or 'EME not available'?

What version of Windows are you using?  If I remember correctly, IE11 only supports MediaSource in Windows 8+, and only supports EME in Windows 8.1+.

**Comment by pajong** [comment]
Hello @joeyparrish .
I just realized that I am using v1.5.1, instead of v1.6.0.

Thank you for the answer!
