### ISSUE TITLE
How to get & set available qualities in safari browser for DRM protected content?

### ISSUE THREAD

**Issue by JeffrinManovaPrabahar** [google/shaka-player#2402]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v2.5.9

**Please ask your question**
I use `getVariantTracks` method to get available video qualities & `selectVariantTrack` method to set video quality in DRM protected content. I am able to get & set video qualities in all browsers except safari. In safari when I try to get video qualities, it returns an array with an object and that object has null values in all its fields.

How to get & set available qualities in safari?

**Comment by joeyparrish** [comment]
This is not possible on iOS, where we use Apple's native HLS playback and have no control over track selection.  On desktop Safari, however, you can configure Shaka Player to use MediaSource-based HLS playback instead.  Try `player.configure('streaming.useNativeHlsOnSafari', false);`

Does this help?

**Comment by JeffrinManovaPrabahar** [comment]
When I use `player.configure('streaming.useNativeHlsOnSafari', false);` I am getting 4026 error. But when I remove that line it seems to work with native fairplay implementation.

![Screenshot 2020-02-19 at 11 40 38 AM](https://user-images.githubusercontent.com/38453271/74806765-debf1880-530c-11ea-9d92-7d7d5f43f1da.png)

![Screenshot 2020-02-19 at 11 40 46 AM](https://user-images.githubusercontent.com/38453271/74806767-e088dc00-530c-11ea-85e1-a1d15f3b59a8.png)

Any reason for this?

**Comment by joeyparrish** [comment]
Sorry, I overlooked the fact that it's DRM content.  On Safari, at the moment, the only way we can access Fairplay is through Apple's native HLS.  So in this scenario, there's no way for us to offer a quality selection.  Apple simply doesn't give us that level of control.
