### ISSUE TITLE
Gradual profil selection in ABR

### ISSUE THREAD

**Issue by hdodev** [google/shaka-player#2405]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
YES (I serach by filtering on ABR)

**What version of Shaka Player are you using?**
2.5.9

By default for a DASH stream, without any Player configuration, it seems the profil selection strategy is to choose the one with the closest bandwitdh to the network available bandwidth. The zapping duration so depends on it. Is it possible to make the Player choose the lowest bandwidth profil (that should decreases the zapping duration), and then go up gradually? Maybe using ABR.defaultBandwidthEstimate or ABR.bandwidthUpgradeTarget?
Thanks in advance.

**Comment by joeyparrish** [comment]
I see two main options for you:

1. At the application level, use the configuration for [abr.restrictions](https://shaka-player-demo.appspot.com/docs/api/shaka.extern.html#.Restrictions) to gradually increase the bitrates/resolutions that ABR is allowed to select from.
2. At the application level, use the configuration [abrFactory](https://shaka-player-demo.appspot.com/docs/api/shaka.extern.AbrManager.html#.Factory) to provide your own AbrManager implementation with your own logic.  This could be from scratch or delegate to our default implementation, `SimpleAbrManager`.

Does this help?

**Comment by matvp91** [comment]
Since you're talking about zapping duration, I assume you're trying to lower the time it takes to start playback. If that's the case, wouldn't it be enough to assign a very low value to `abr.defaultBandwidthEstimate` in order for shaka to select the lowest quality rendition? Abr can then select a corresponding rendition based on it's bandwidth estimations.

@joeyparrish is shaka able to preload the manifest?

**Comment by joeyparrish** [comment]
We are not yet able to preload the manifest.  We have an open feature request for that (#880), and it's on our [roadmap](https://github.com/google/shaka-player/blob/master/roadmap.md) for this year.

`abr.defaultBandwidthEstimate` is only used when we don't have an estimate.  If you're calling `load()` for the second time on the same `Player` instance, it will already have an estimate.  If you're playing in Chrome, Chrome gives us a bandwidth hint via the [NetworkInformation API](https://developer.mozilla.org/en-US/docs/Web/API/NetworkInformation), so we don't have to rely on the `defaultBandwidthEstimate`.

So all in all, `defaultBandwidthEstimate` is not going to be the best tool for this in most cases.  But `abr.restrictions` can be set when you call `load()`, and will restrict the choices made by `AbrManager` without affecting what's available in the track APIs or the track selection UI if you're using our UI.

**Comment by hdodev** [comment]
Hi, thank you for your answers. I confirme I'm trying to lower the time it takes to start playback.

But ideally, I would like the time it takes to select another resolution/bandwidth during the playback to be not impacted (I mean with a WIFI connection, if during playback the bandwith decreases /increases for any reason).

I will explore the two suggested solutions and make you a feedback asap.

**Comment by joeyparrish** [comment]
If you don't want to affect normal ABR decisions, just changing channels, you should set `abr.restrictions` right before `load()`.  After `load()` resolves, you can set it back to normal.  For example:

```js
player.configure('abr.restrictions.maxHeight', 1);  // Force the use of the lowest resolution
await player.load('otherChannel.mpd');
player.configure('abr.restrictions.maxHeight', undefined);  // Reset to default
```

Does this help?

**Comment by hdodev** [comment]
Hello @joeyparrish . Yes I think it's exactly what I need.

I close the question.
