### ISSUE TITLE
UTCTiming is ignored when using SegmentTimeline even when autoCorrectDrift is off 

### ISSUE THREAD

**Issue by thmatuza** [google/shaka-player#2411]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v2.5.9

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
The demo app

**If custom app, can you reproduce the issue using our demo app?**
N/A

**What browser and OS are you using?**
Chrome, macOS Catalina

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**

https://live.unified-streaming.com/scte35/scte35.isml/.mpd

**What did you do?**

1. Open the demo page
2. Uncheck `Auto-Correct DASH Drift` config
3. Start playing the manifest url above on the demo player.

**What did you expect to happen?**
It will call a request to https://time.akamai.com/?iso

**What actually happened?**

No UTCTiming request is called

**Comment by thmatuza** [comment]
I created a pull request here.
https://github.com/google/shaka-player/pull/2412

**Comment by joeyparrish** [comment]
Thank you for the report and the PR!  After having analyzed the code a bit, I think you are correct that this is a bug.
