### ISSUE TITLE
Tizen TV 2019 VoD Playback does not complete

### ISSUE THREAD

**Issue by rez** [google/shaka-player#2414]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.2 / 2.5.9

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
N/A. Did not have opportunity to try.

**Are you using the demo app or your own custom app?**
Custom app. I also tried to use DASH content from the demo page.

**If custom app, can you reproduce the issue using our demo app?**
N/A

**What browser and OS are you using?**
Tizen TV 2019

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Samsung Tizen TV 2019 Premium `QN43Q60RAFXZA`

**What are the manifest and license server URIs?**
https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd (demo content)

**What did you do?**
Play to end of video and try to replay video.

Seek to end of video and try to replay video.

**What did you expect to happen?**
After the video completed I expected the video to start playback from the beginning `mediaElement.play()`. 

**What actually happened?**
With our content the video became stuck in a `waiting` state. From this state, any `play` request does not do anything. Basically viewer is stuck in this state.

With the Shaka demo playback was stuck also, but it was possible to unstuck after multiple play attempts. To be more precise, with the Shaka demo content the video jumped to a `play` state back to a `paused` state, and from here, I was able to have playback from the start.

Debugging the issue I found that mediaElement.ended does not change to true when content ends even though the media event ended is fired.

**Comment by chrisfillmore** [comment]
What is the difference between `video.currentTime` and `video.duration` when you get stuck in the "waiting" state? (I assume you mean you get a `waiting` event?)

**Comment by rez** [comment]
@chrisfillmore 

Correct, and interestingly enough there does seem to be a discrepancy. 

At the end the times are equal and after the waiting event `video.currentTime` is a few milliseconds behind `video.duration`

**Comment by chrisfillmore** [comment]
I've seen this kind of problem, where sometimes the video element never reaches the `ended` state. I'm not sure if this is definitely browser behaviour, or related to how Shaka used to handle buffer underflow by setting `playbackRate = 0` (I remember @joeyparrish posted an issue on the topic of removing that code a while back, but I can't find it, and I'm not sure if Shaka still has this behaviour.)

@rez if you have some logic which depends on the `ended` event/state, perhaps you can also listen for `waiting`, check if `video.duration - video.currentTime < 1` and consider playback to be done.
