### ISSUE TITLE
Does shaka support ES3?

### ISSUE THREAD

**Issue by alexandercerutti** [google/shaka-player#2416]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes

**What version of Shaka Player are you using?** 2.5.x

**Please ask your question**

Does shaka player support ES3? If not (and I think it doesn't), is there a list of the functions that might be needed to be polyfilled from ES5+? Do someone tried to polyfill it to ES3 and found which are the functions that are needed to be polyfilled?

I'm hoping right now you are not using something like Proxies or WeakMaps, so functions that cannot be polyfilled without problems like memory leaks or that cannot be entirely polyfilled. 😂

We are probably going to develop on ES3-old TVs so, I had this curiosity about if shaka could be used or not.

Thank you.

**Comment by joeyparrish** [comment]
Shaka Player is compiled using the Closure Compiler, and includes all necessary polyfills for basic web APIs.  What we can't polyfill, though, are media-related APIs such as HTML5 Video, MediaSource Extensions, and Encrypted Media Extensions.

If you don't have HTML5 Video, Shaka Player won't work.  If you don't have either MediaSource Extensions or built-in HLS, Shaka Player won't work in this case, either.

In all cases, even ES3, you should be able to load Shaka Player and call `shaka.Player.isBrowserSupported()`.  This should return false on platforms that we fundamentally can't support, so you can still show an appropriate error message or fall back to another method of playback.

If you find a platform where you get a load-time exception from Shaka Player and can't call `shaka.Player.isBrowserSupported()`, that would be a bug, and we would encourage you to file a bug report here on github.  I've just tried this on a VM with IE 9 and found that it's working as expected there.  (I don't have access to IE 8, which would be ES3.)

**Comment by joeyparrish** [comment]
Does this help?

**Comment by alexandercerutti** [comment]
@joeyparrish  Thank you very much for the explanation! This was only a doubt, we'll check later if it will work! I think the platform the apps will run on will be a very old version of webkit.
