### ISSUE TITLE
ShakaPlyaer+youtube

### ISSUE THREAD

**Issue by amirmogaadi1** [google/shaka-player#2418]
**How to play youtube link on shaka player ?**

**Comment by joeyparrish** [comment]
YouTube content is not supported by Shaka Player.  Shaka Player is primarily for generic DASH & HLS content.  Playing YouTube content outside of YouTube would seem to be against [YouTube's terms of service](https://www.youtube.com/static?template=terms):

> Permissions and Restrictions
> You may access and use the Service as made available to you, as long as you comply with this Agreement and applicable law. You may view or listen to Content for your personal, non-commercial use. You may also show YouTube videos through the embeddable YouTube player.

[YouTube's iframe player](https://developers.google.com/youtube/iframe_api_reference) is easy to use and can be embedded into any site.  We recommend you try that instead.
