### ISSUE TITLE
Widevine DASH + microsoft Edge using Shaka player

### ISSUE THREAD

**Issue by MegaLabs1** [google/shaka-player#242]
Hi all! 

Can someone say is it possible to use Shaka to decode and playback content in MS Edge browser? 
Shaka test page (shaka-player-demo.appspot.com) does not support widevine ecrypted content with EDGE. We also get errors in our testpage which is used for Google Chrome.

**Comment by Doolali** [comment]
You can, but for MS Edge you'd have to use PlayReady, not Widevine.

**Comment by MegaLabs1** [comment]
Thanks, Doolali
Is it an Edge or Shaka restriction? (I mean Edge does not support widevine CDM, for example)

**Comment by ScottDavies-EET** [comment]
Edge will only support PlayReady (and as far as I know will only ever support PlayReady).

I believe Shaka supports PlayReady and edge, if it doesn't then you can download the source code and make the updates to add the support.

Regards,
Scott Davies
Digital Media Specialist
Eagle Eye Technology

* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
This e-mail, the information contained in it and any files or attachments transmitted with it are confidential and may be legally privileged. They are intended solely for the use of the intended recipient(s). Access to this e-mail by anyone else is unauthorised.
The content of this e-mail and any files or attachments transmitted with it may have been changed or replaced without the consent of the author, and in circumstances where the content of this e-mail is important you should not rely on its integrity without checking it by telephone or fax. Eagle Eye Technology does not accept any responsibility for any breach of confidence which may arise from the use of e-mail as a means of communication.  If you are not the intended recipient, any review, dissemination, disclosure, alteration, printing, copying, transmission or other use of this e-mail is prohibited and may, in certain circumstances, be a criminal offence, as may any action taken or omitted to be taken in reliance on it.
Please also note that any views, opinions or advice contained in this e-mail are those of the sending individual, except where the sender specifically states them to be the views of Eagle Eye Technology.
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
Eagle Eye Technology Limited
Registered in the UK. Company Registration Number: 04459434<tel:04459434>
Registered Address: 3rd Floor, City View Place, 67, Sydenham Road<x-apple-data-detectors://3>, Guildford, Surrey. GU1 3RY
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

On 2 Dec 2015, at 15:56, MegaLabs1 <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks, Doolali
Is it an Edge or Shaka restriction? (I mean Edge does not support widevine CDM, for example)

-
Reply to this email directly or view it on GitHub<https://github.com/google/shaka-player/issues/242#issuecomment-161343497>.

______________________________________________________________________
This email has been scanned by the Symantec Email Security.cloud service.
For more information please visit http://www.symanteccloud.com
______________________________________________________________________

**Comment by joeyparrish** [comment]
Thanks, Scott.  @MegaLabs1, that's all correct.  Each browser supports a different DRM system, and to date, no mainstream browser supports more than one.  Microsoft's browsers contain Microsoft's DRM system (PlayReady), and Google's browsers contain Google's DRM system (Widevine).

Shaka is agnostic to all of this, and simply queries the browser for the systems requested by the application.  Shaka can be configured to use multiple DRM systems for the same piece of content, and it will select whichever is available on that browser.

There's nothing stopping browsers from supporting more than one DRM system, and if/when that happens, Shaka will still be able to generically query DRM support through the browser's EME API.
