### ISSUE TITLE
Table unused created in IndexedDB

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#2421]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes

**What version of Shaka Player are you using?** 2.5.9

**Can you reproduce the issue with our latest release version?** Yes

**Can you reproduce the issue with the latest code from `master`?** Yes

**Are you using the demo app or your own custom app?** Both

**If custom app, can you reproduce the issue using our demo app?** Yes

**What browser and OS are you using?**
Chrome 80 macOS Catalina

**What did you do?**

Load https://shaka-player-demo.appspot.com/demo/
Check IndexedDB in the devtools
See the database tables

**What did you expect to happen?**
The tables are: manifest-v3, segment-v3

**What actually happened?**

The tables are: manifest-v3, segment-v3, session-ids

The table session-ids is not used, so it shouldn't be created

**Comment by joeyparrish** [comment]
This is working as intended.  The session-ids store is created when we initialize / upgrade our storage system.  It is used to store session IDs that are pending release after deleting offline content.

Some persistent license sessions must have their release confirmed with the license server, and should not be deleted until an acknowledgement message has been received.  But we don't want to keep the full content just to store a session ID, so those pending-release session IDs get their own object store.

IndexedDB only allows you to create object stores on upgrade or creation of the database.  So if we might potentially need the session-ids store, we must create it early.

I hope this helps clarify!

**Comment by avelad** [comment]
Thanks for your explanation!

**Comment by joeyparrish** [comment]
Happy to help!
