### ISSUE TITLE
Fairplay does not work if the video element is too small and adaptive HLS streaming is used

### ISSUE THREAD

**Issue by EyMaddis** [google/shaka-player#2426]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.9

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Custom

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
Safari 13.0.5, MacOS Catalina 10.15.3 

**What are the manifest and license server URIs?**
Sent via Email with example app.

**What did you do?**
* Set up Fairplay with license server
* Intialize set width and height of player to 640x360
* press play

Repeat with 1280x640.

**What did you expect to happen?**
* License should be requested (Network tools)
* Playback should start

**What actually happened?**
* Player is loading endlessly for 640x360

The network tools show that the first load is the 1080p version of the .m3u8 which is then canceled and switched to 360p.m3u8 immediately.
If the 360p.m3u8 is used as a player src, it is working correctly.
Requestfilters of the networking engine are correctly triggered.

My guess is that there is a timing issue with the switch from HD to 360p before the key negotiation is completed.

**Comment by joeyparrish** [comment]
This is interesting, especially given that at the moment, we can only use Fairplay with Apple's native HLS support.  So we don't have any control over adaptation in that scenario, nor what effect the resolution of the video element might have on playback.  We are still responsible for the license exchange, but nothing else.

We'll try to reproduce the issue and see what we can learn, but my guess is that this would wind up as a bug report for Apple.  You may wish to start filing an issue with Apple in parallel.

Vielen Dank!

**Comment by theodab** [comment]
I tried it out, and I can confirm that playback is not happening for the lower-resolution version.
Most of the time. Occasionally (like maybe 1 in 5 playbacks), it does run.

**Comment by EyMaddis** [comment]
I would guess that it is a timing issue between my custom license fetch and the player switching the adaption set.
Maybe the player applies the license to the player after the adaption set switches and we need to wait for another encrypted event or a little bit of buffering.

**Comment by joeyparrish** [comment]
We don't have any control over adaptation or adaptation timing when playing Fairplay.  That's all inside the browser, controlled by Apple.

If it's purely a timing issue, the change in size could potentially change the timing.

Imagine Apple limits adaptation to resolutions no larger than the video element size.  In this case, a smaller video element means segments that have fewer bytes and load more quickly.  So you're more likely to have segments before you have a license.  This would also explain @theodab's results that it **does _sometimes_** play at low res.

We could test this theory by delaying the license response before playback:

```js
let licenseDelaySeconds = 5;

player.getNetworkingEngine().registerResponseFilter((type, response) => {
  if (type == shaka.net.NetworkingEngine.RequestType.LICENSE) {
    return new Promise((resolve) => setTimeout(resolve, licenseDelaySeconds * 1000));
  }
});
```

@EyMaddis, @theodab, can you try this and see what effect it has?  If this is a timing issue, I would expect to see the same results for both large and small video elements with the added delay.

**Comment by theodab** [comment]
I tried that, and it didn't seem to change anything; the lower-resolution content still played occasionally, but not always, and the higher-resolution still played always. I also tried a delay of 10 seconds, just in case.
That suggests this might not be a race condition, or at least not a race condition between content loading and the license loading.

**Comment by EyMaddis** [comment]
Is there a way enforce a default variant? Right now it starts with HD and immediately cancels it, If I can set the player to first try 360 (and maybe increase later), I could potentially work around the issue.

**Comment by joeyparrish** [comment]
Shaka Player can control which variants are played only when we're using MediaSource.  We can't use MediaSource with Fairplay, so adaptation is managed inside the browser, in Apple's native HLS implementation.  We have no control over adaptation or variants in this situation.

**Comment by joeyparrish** [comment]
I recommend you take this issue to Apple here: https://webkit.org/reporting-bugs/

If Apple thinks that there is a web API we're not using or using incorrectly, we'd be happy to make changes in Shaka Player.  But for the moment, there doesn't seem to be anything we can do.

**Comment by EyMaddis** [comment]
I was able to work around it. This is related to https://github.com/google/shaka-player/issues/2214 such that on a small screen I could see that the `drm.initDataTransform` method was called twice, producing a "Malformed Init Data" error the second time. So this is not a platform issue.

In my case the easy workaround is this:

```ts
          let cachedResponse: any
          await player.configure(
            'drm.initDataTransform',
            (initData: any, ans: any) => {
              if (cachedResponse) {
                return cachedResponse
              }
              const contentId = shaka.util.FairPlayUtils.defaultGetContentId(
                initData
              )
              cachedResponse = shaka.util.FairPlayUtils.initDataTransform(
                initData,
                contentId,
                cert
              )

              return cachedResponse
            }
          )
```

Of course, I make sure that the cache is only used for exactly that source. Maybe this can lead to problems down the line, but it is currently working for us.
