### ISSUE TITLE
Export TtmlTextParser to public api

### ISSUE THREAD

**Issue by glhvta** [google/shaka-player#2428]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v2.5.9

**Please ask your question**
Hi,

We are using the default TtmlTextParser for TTML captions. Recently we faced new requirements in the logic of our app that require changes in the parsing TTML captions logic. The default parser almost suits our needs so we still want to use it instead of creating our own plugin. Is it possible to export TtmlTextParser parseMedia and parseInit methods to the public API? So with the help of composition, we can add new logic and still use the existent functionality of TtmlTextParser.

**Comment by joeyparrish** [comment]
Should be no problem to export the text parser plugins.

**Comment by glhvta** [comment]
Great! Thanks!

Is it possible to cherry-pick these changes to shaka v2.5.10?

**Comment by joeyparrish** [comment]
Absolutely.

**Comment by glhvta** [comment]
awesome! thank you
