### ISSUE TITLE
HLS Image Media Playlists 

### ISSUE THREAD

**Issue by mcpv** [google/shaka-player#2429]
Consider supporting HLS Image Media Playlists, which allow seek preview with tiled jpegs (defined by DASH-IF) and/or full-frame jpegs.  

[https://github.com/image-media-playlist/spec](https://github.com/image-media-playlist/spec)

**Comment by joeyparrish** [comment]
Thanks!  We'll consider it in our next round of planning.

**Comment by mcpv** [comment]
more info for reference:

https://developer.roku.com/docs/developer-program/media-playback/trick-mode/hls-and-dash.md
