### ISSUE TITLE
Setting preload attribute to none in video tag disable playback

### ISSUE THREAD

**Issue by aldigun** [google/shaka-player#243]
Hi,

If I set \<video preload="none">, shaka player will not be able to play and it says that the player is destroyed. I found out that the promise never reach "resolved" state.
Having an option to disable preloading is useful to make sure that we do not need to load the entire stream when not needed.

**Comment by joeyparrish** [comment]
The preload attribute on video has no effect on MediaSource playbacks such as those driven by Shaka.  It is only used for progressive playback using video.src='blah.mp4', not with adaptive streaming such as DASH.

**Comment by joeyparrish** [comment]
I also tried adding preload="none" to the video tag in our demo app, and confirmed that there is no difference in behavior.

If you want to control how much data is buffered by Shaka, we have player.configure({'streamBufferSize': ...}) for this.

**Comment by aldigun** [comment]
Thanks for the update. Tested on a clean page and issue can't repro.
