### ISSUE TITLE
Can Shaka Player DRM be configured without license server for ClearKey?

### ISSUE THREAD

**Issue by vishwajeetv** [google/shaka-player#2434]
I am trying to configure shaka player with ClearKeys
Like
```
player.configure({
  drm: {
    clearKeys: {
      'deadbeefdeadbeefdeadbeefdeadbeef': '18675309186753091867530918675309'
    }
  }
});
```
As specified in the documentation.
However, I don't have a valid license server for this.

If I configure **without** "servers" object in DRM
```
drm: {
    servers: {
      'org.w3.clearkey': 'http://foo.bar/drm/clearkey'
    }
  }
```
The shaka player gives error code 6012
```
Error code 6012 object I {severity: 2, category: 6, code: 6012, data: Array(1), handled: false}
```

So is it possible to configure shaka player to play DASH with clearkeys without a licesne server?

**Comment by vishwajeetv** [comment]
I was using it in the wrong way. (I was using  
```
clearKeys: {
      'key': 'keyId'
    }
```

instead of the **correct** way as following, 
```
clearKeys: {
      'keyId': 'key'
    }
```

**Comment by joeyparrish** [comment]
@vishwajeetv, we're glad you were able to figure it out.  Is there anything we could have done better in our docs to help make this feature easier to understand?

**Comment by vishwajeetv** [comment]
I will try to improve the documentation and submit a pull request.

**Comment by joeyparrish** [comment]
That's great!  Thank you so much for the contribution.

**Comment by joeyparrish** [comment]
Thanks for your help!
