### ISSUE TITLE
HLS: "Shaka Error MANIFEST.CONTENT_UNSUPPORTED_BY_BROWSER ()" with "#EXT-X-MEDIA:TYPE=AUDIO"

### ISSUE THREAD

**Issue by pszemus** [google/shaka-player#2435]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
v2.5.9 (uncompiled)

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `master`?**
n/a

**Are you using the demo app or your own custom app?**
demo app

**What browser and OS are you using?**
Google Chrome 80.0.3987.116 on Fedora 31

**What are the manifest and license server URIs?**
n/a

**What did you do?**
Shaka Player Demo -> Custom content -> HLS playlist URL

**What did you expect to happen?**
stream begins to play

**What actually happened?**
Shaka Player reports error: `Shaka Error MANIFEST.CONTENT_UNSUPPORTED_BY_BROWSER ()`

The HLS stream that I'm trying to play is a stream with separate audio chunklist - it has `#EXT-X-MEDIA:TYPE=AUDIO` tag.
`playlist.m3u8`:
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio",LANGUAGE="pl",NAME="polski",DEFAULT=YES,AUTOSELECT=YES,URI="chunklist_b96000_slpl_t64cG9sc2tp.m3u8"
#EXT-X-STREAM-INF:BANDWIDTH=1650000,CODECS="avc1.4d4028",RESOLUTION=1024x576,AUDIO="audio"
chunklist_b1500000.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1210000,CODECS="avc1.4d4020",RESOLUTION=854x480,AUDIO="audio"
chunklist_b1100000.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=825000,CODECS="avc1.4d401f",RESOLUTION=640x360,AUDIO="audio"
chunklist_b750000.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=165000,CODECS="avc1.42c015",RESOLUTION=256x144,AUDIO="audio"
chunklist_b150000.m3u8
```
audio chunklist `chunklist_b96000_slpl_t64cG9sc2tp.m3u8`:
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:6
#EXT-X-MEDIA-SEQUENCE:2751
#EXT-X-DISCONTINUITY-SEQUENCE:0
#EXTINF:4.992,
media-ujzoui0fw_b96000_slpl_t64cG9sc2tp_2751.ts
#EXTINF:4.992,
#AD-BLOCK-START:duration=31950000
media-ujzoui0fw_b96000_slpl_t64cG9sc2tp_2752.ts
#EXTINF:4.992,
media-ujzoui0fw_b96000_slpl_t64cG9sc2tp_2753.ts
#EXTINF:4.992,
media-ujzoui0fw_b96000_slpl_t64cG9sc2tp_2754.ts
#EXTINF:5.056,
media-ujzoui0fw_b96000_slpl_t64cG9sc2tp_2755.ts
```
video chunklist `chunklist_b1500000.m3u8`:
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:5
#EXT-X-MEDIA-SEQUENCE:2753
#EXT-X-DISCONTINUITY-SEQUENCE:0
#EXTINF:5.0,
media-uhihsxxe2_b1500000_2753.ts
#EXTINF:5.0,
media-uhihsxxe2_b1500000_2754.ts
#EXTINF:5.0,
media-uhihsxxe2_b1500000_2755.ts
#EXTINF:5.0,
media-uhihsxxe2_b1500000_2756.ts
#EXTINF:5.0,
media-uhihsxxe2_b1500000_2757.ts
```

When I'm trying to play a HLS stream with audio muxed together with video it plays fine.
`playlist.m3u8`:
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=2296000,CODECS="avc1.77.31,mp4a.40.2",RESOLUTION=1280x720
chunklist_b2096000.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1746000,CODECS="avc1.77.31,mp4a.40.2",RESOLUTION=1024x576
chunklist_b1596000.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1306000,CODECS="avc1.77.30,mp4a.40.2",RESOLUTION=854x480
chunklist_b1196000.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=921000,CODECS="avc1.77.30,mp4a.40.2",RESOLUTION=640x360
chunklist_b846000.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=213000,CODECS="avc1.66.12,mp4a.40.2",RESOLUTION=256x144
chunklist_b198000.m3u8
```

**Comment by joeyparrish** [comment]
> **What are the manifest and license server URIs?**
> n/a

> **What did you do?**
> Shaka Player Demo -> Custom content -> HLS playlist URL

I disagree that the specific content URI is not applicable.  If you can't reproduce the issue with any of the content that's already in our demo app, then we will need you to share the content URI with us before we can reasonably reproduce and debug the issue.

You can send URIs privately to shaka-player-issues@google.com, and they will not be shared beyond the team.

Thanks!

**Comment by pszemus** [comment]
@joeyparrish Until now I wasn't able to share this stream with you. I've just send it to shaka-player-issues@google.com

**Comment by pszemus** [comment]
Problem disappears after adding audio codec id to `CODECS` property in `playlist.m3u8`:
```
[...]
#EXT-X-STREAM-INF:BANDWIDTH=1650000,CODECS="avc1.4d4028,mp4a.40.2",RESOLUTION=1024x576,AUDIO="audio"
chunklist_b1500000.m3u8
[...]
```

**Comment by joeyparrish** [comment]
Yes, the lack of audio codec information would be a problem.  We have to be able to tell the browser the exact codec strings upfront.  It's a requirement of the MediaSource API.
