### ISSUE TITLE
DRM assets not playing in demo compiled mode

### ISSUE THREAD

**Issue by theodab** [google/shaka-player#2438]
At the moment, DRM protected assets don't seem to be playing when the demo is in compiled mode.
For example, take [this](https://nightly-dot-shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://storage.googleapis.com/shaka-demo-assets/angel-one-widevine-hls/hls.m3u8;panel=SEARCH;build=compiled). We're getting a 6002 (FAILED_TO_CREATE_CDM) error.
This is only the case in nightly; [it works as expected in the last release](https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://storage.googleapis.com/shaka-demo-assets/angel-one-widevine-hls/hls.m3u8;panel=SEARCH;build=compiled).

This is hopefully just a demo problem. I'll do a bisect and see if I can figure out what's up.

**Comment by theodab** [comment]
Looks like this is a result of https://github.com/google/shaka-player/commit/3a5d7ac46a5f7ea9dd80ff85dfbc660c0bc0526b. Ironically, a CL meant to fix DRM playback.

**Comment by joeyparrish** [comment]
Does quoting the field names in the demo's DRM config fix it?

**Comment by theodab** [comment]
It doesn't.
Also, on further testing, this problem only happens in compiled release mode, not compiled debug mode.
