### ISSUE TITLE
Cannot import uncompiled library into a service worker

### ISSUE THREAD

**Issue by richardmitic** [google/shaka-player#244]
I'm trying to move the bandwidth estimation component to a service worker, then pass a reference to the bandwidth estimator object to the webpage app via `postMessage()`. However, `goog.require()` does not find the exported classes. 

This example service worker:

    importScripts('third_party/closure/goog/base.js', 'shaka-player.uncompiled.js');
    
    var estimator;
     
    self.addEventListener('install', function(event) {
        estimator = new shaka.util.EWMABandwidthEstimator();
        console.log('Service worker installed with estimator:', estimator);
    });

produces the following error in the log:

`base.js:413    goog.require could not find: shaka.player.DashVideoSource`

This is the first call to `goog.require` in the uncompiled script, and if you remove it you get the same error for the next call, so let's assume that none of the classes are being loaded.

Importing the compiled version works fine seeing as it's a single script with no dependencies, but this is obviously difficult to develop with. What needs to be done in order to import the necessary classes and their dependencies into a service worker?

**Comment by joeyparrish** [comment]
We have not done any work with ServiceWorkers, but I have some guesses about what might cause such a problem. Let me explain a few things about how Closure works in uncompiled mode.

You have to load 'third_party/closure/goog/base.js' before you can goog.require anything.  goog.require (as used in shaka-player.uncompiled.js and elsewhere) is implemented in goog/base.js.  It loads scripts by adding a script tag to the document (through goog.writeScripts_, goog.importScript_, and goog.writeScriptTag_).

The first script it loads is the dependency map (third_party/closure/goog/deps.js) which is created by build/gendeps.sh or build/all.sh.  If that deps map does not exist, goog.require will be unable to locate the required class.  So first, just check to make sure you have the deps map, and if not, run build/gendeps.sh.

The other thing that might cause you problems is if goog.writeScriptTag_ can't function inside a ServiceWorker.  It calls document.write('<script src="blah.js"></script>'), which I expect is not doable from a ServiceWorker.  If this is the problem, you can tell the closure loader to use a different method by setting the global variable CLOSURE_IMPORT_SCRIPT to a function that takes a path name and returns true if it succeeds.  This could probably be mapped to importScripts.  For example:

```
// Must be defined on the same global object used by goog/base.js, so don't use var:
this.CLOSURE_IMPORT_SCRIPT = function(path) {
  importScripts(path);
  return true;
};

importScripts('third_party/closure/goog/base.js', 'shaka-player.uncompiled.js');
```

Let me know if any of these things is helpful.

**Comment by richardmitic** [comment]
Yes, the service worker has no DOM access so it makes sense that `document.write()` has no effect. Opening a debug terminal for any random service worker and entering `document.write('')` gives the error `Uncaught ReferenceError: document is not defined(…)`.

I'll try your CLOSURE_IMPORT_SCRIPT solution tomorrow an report back.

**Comment by richardmitic** [comment]
Using the suggested code raises an explicit `DOMException` instead of failing to install the classes ;)

For now I'll use the compiled version.

**Comment by joeyparrish** [comment]
Can you provide details on the DOMException so that we can better document the failure here?  Perhaps that might be of use to someone who wants to tackle this issue in future.

**Comment by richardmitic** [comment]
The full log is:

    GET https://webserver.com:3000/deps.js net::ERR_INVALID_RESPONSE    deps.js:1
    Uncaught [object DOMException]                           service_worker.js:13

**Comment by joeyparrish** [comment]
Ah, I see.  `goog.findBasePath_` also accesses document to locate base.js and construct deps.js relative to that.

Try this:

```
this.CLOSURE_BASE_PATH = '/third_party/closure/goog/';
this.CLOSURE_IMPORT_SCRIPT = function(path) {
  importScripts(path);
  return true;
};
importScripts('third_party/closure/goog/base.js', 'shaka-player.uncompiled.js');
```

**Comment by richardmitic** [comment]
This fails with the error message 

    ajax_request.js:379 Uncaught (in promise) Error: Network failure (…)shaka.util.AjaxRequest.createError_ @ ajax_request.js:379shaka.util.AjaxRequest.onError_ @ ajax_request.js:473
    ajax_request.js:379 Uncaught (in promise) Error: Network failure.(…)shaka.util.AjaxRequest.createError_ @ ajax_request.js:379shaka.util.AjaxRequest.onError_ @ ajax_request.js:473
    smallapp.js:8 ServiceWorker registration failed:  DOMException: Failed to register a ServiceWorker: ServiceWorker script evaluation failed


The line it crashes on is `importScripts('third_party/closure/goog/base.js', 'shaka-player.uncompiled.js');`. I assume the issue this time is that ajax requests are not available in the ServiceWorker.

**Comment by joeyparrish** [comment]
That could be.  I don't have any experience with ServiceWorkers, and we have never made it an explicit goal to run Shaka in a ServiceWorker.  I can't say if this is even feasible.

**Comment by richardmitic** [comment]
Ok, well anyhow it seems more likely that the issue is with closure rather than shaka. As I said before, the compiled version works with no issues, so let's not worry too much. I'll close.
