### ISSUE TITLE
Shaka player does not works in Android webView (error 6001), but works in chrome app

### ISSUE THREAD

**Issue by Nodrex** [google/shaka-player#2444]
**I read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues**

**Shaka player Version 2.5.9**

**I Can reproduce the issue with latest release version**

**I Can reproduce the issue with the latest code from `master`?**

**I am using my own custom App**

**I can reproduce the issue using demo app( https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://storage.googleapis.com/shaka-demo-assets/sintel-widevine/dash.mpd;panel=HOME;build=uncompiled )**

**Android os 7.1.2    chrome app version 80.0.3987.119**

**Sony Android TV(bravia KDL-50W807C) android os version:  7.0**

**player.configure({
       drm: {
           servers: { 'com.widevine.alpha': "https://amediateka.silktv.ge/wv/" }
       }
    });
https://amediateka.silktv.ge/media//800008501/output.mpd**

**Start play and it shows error 6001, even with shaka demo url**

**It should be playing, because it works in chrome browser app**

**Shaka player does not started playing, instead it shows error code 6001**
While shaka player works in android chrome browser, it does not works in android webView, even shaka player's demo url does not works in webviev and shoes error 6001

![Screenshot_20200305-135355](https://user-images.githubusercontent.com/6556678/75973301-5df84300-5eee-11ea-93cd-9800086bf786.jpg)

**Comment by Nodrex** [comment]
What means needs triage? 
It needs android tv with version 7.0 and i can provide tv apk file if you have device to install
or it needs Xiaomi Redmi 4a with android version 7.1.2 and i can also sent apk for mobile version

**Comment by joeyparrish** [comment]
"Needs triage" is a label applied by our build bot to identify issues which need attention.  Any issue with that label has not been reproduced or diagnosed by the team yet.

I recently learned that WebView on Android has some hooks related to permission prompts, and that those can affect its ability to play DRM content.  If you are responding to permission requests with "deny" or if you are using whatever defaults are there, this may cause the issue you're seeing.

I don't know the WebView API myself, but I was able to track down some resources that I hope will help:

 - [A medium article on geolocation permissions for WebView](https://medium.com/@xabaras/android-webview-handling-geolocation-permission-request-cc482f3de210).  This article talks about what you need to add to WebView to handle permissions generally.
 - That led me to this [API doc for WebChromeClient](https://developer.android.com/reference/android/webkit/WebChromeClient), mentioned in the medium article.  Specifically, it seems that you want to look at `onPermissionRequest(PermissionRequest request)`.
 - From there I found the [API doc for PermissionRequest](https://developer.android.com/reference/android/webkit/PermissionRequest), which defines an object for the permissions request and several constants for specific permissions.
 - One of those permission constants is `RESOURCE_PROTECTED_MEDIA_ID`, which is described as:
   > Resource belongs to protected media identifier. After the user grants this resource, the origin can use EME APIs to generate the license requests.

Please let us know if this is what you needed to get EME & Shaka Player working in WebView.  We don't have much Android app development experience on this team, but with your feedback, perhaps we could put together a tutorial explaining this for all WebView-based apps.  Thanks!

**Comment by Nodrex** [comment]
Thanks @joeyparrish   for responding so quickly.

I am granting RESOURCE_PROTECTED_MEDIA_ID already and it does not works in android tv version 7.0, but current code works in android tv version 8.0, which is weird.

I will try a medium article on geolocation permissions for WebView and will let you know results

**Comment by joeyparrish** [comment]
We don't use geolocation.  That was just the first article I could find on WebView permissions.

**Comment by joeyparrish** [comment]
Another thing you can try is opening https://shaka-player-demo.appspot.com/support.html in the WebView.  That will give a full report of what we can detect from the platform.

**Comment by Nodrex** [comment]
Cool i will try

**Comment by joeyparrish** [comment]
@Nodrex, were you able to resolve your issues with WebView?  From all the research I did on this, it seems that if the application handles and allows the necessary DRM permissions, this should work without any changes in Shaka Player.

**Comment by cavamora** [comment]
hi guys! I am having the same problem, trying to use Shaka Player on Android TV 8! @Nodrex can you give us a hint on how are you using the web view so it worked on android 8?? thanks!

**Comment by cavamora** [comment]
> Thanks @joeyparrish for responding so quickly.
> 
> I am granting RESOURCE_PROTECTED_MEDIA_ID already and it does not works in android tv version 7.0, but current code works in android tv version 8.0, which is weird.
> 
> I will try a medium article on geolocation permissions for WebView and will let you know results

can you help me on making Shaka Player working on android tv 8? I am having the same 6001 error here!

**Comment by joeyparrish** [comment]
There are permissions related to DRM media that must be granted by your application through the WebView.  Specifically `RESOURCE_PROTECTED_MEDIA_ID`.

Please see details in this comment: https://github.com/google/shaka-player/issues/2444#issuecomment-595329859

**Comment by cavamora** [comment]
we already tried this. like bellow... are we doing something wrong?

class CustomWebChromeClient : WebChromeClient() {
    override fun onPermissionRequest(request: PermissionRequest?) {
        super.onPermissionRequest(request)

        Handler().post({
            request?.grant(arrayOf(RESOURCE_PROTECTED_MEDIA_ID))
        })
    }
}

**Comment by joeyparrish** [comment]
I'm sorry, but I don't know.  We don't have expertise with WebView.  Our domain ends at JavaScript. 
 I'm just pointing you at the docs I know of.

**Comment by cavamora** [comment]
just did it! it is working!
however, buffering all the times... do you have the same behavior?

**Comment by joeyparrish** [comment]
We don't test on WebView in particular.  As for buffering, that could be caused by any number of things, including available bandwidth on the device, network latency, WiFi quality, the choice of content, CPU usage, and availability of hardware decoders for a certain codec.
