### ISSUE TITLE
Playready material fails silently on Tizen 2.4

### ISSUE THREAD

**Issue by peternycander** [google/shaka-player#2448]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.9

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Custom

**If custom app, can you reproduce the issue using our demo app?**
Demo app crashes when I try to navigate to it

**What browser and OS are you using?**
Tizen 2.4

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Tizen 2.4 (2016), tried two different models.

**What are the manifest and license server URIs?**

Not sure I am allowed to share this.

**What did you do?**
Play material protected by playready which works on IE11 and Edge.

**What did you expect to happen?**
Playback to start.

**What actually happened?**
Black screen. It works if I set `disableAudio: true`, or `disableVideo: true`.

**Comment by avelad** [comment]
I think that it's related to https://github.com/google/shaka-player/issues/813
