### ISSUE TITLE
Clearkey common encryption problem

### ISSUE THREAD

**Issue by pajong** [google/shaka-player#245]
Hello,
I am trying to play a video with common encryption that requires external key (the key is not in the manifest).
I have set up the interpretContentProtection function similarly to the sample provided for youtube clearkey:
https://github.com/google/shaka-player/blob/master/appUtils.js#L137
I get the key id from cenc:default_KID.

Although the player gives me the duration of the video, the video does not play and buffers forever without throwing any error.

Can I get some help to make the video play?

**Comment by joeyparrish** [comment]
@pajong I would be happy to help you figure this out.  Please provide console logs of a failed playback and the contents of your interpretContentProtection callback (you can omit the specific key, obviously).

**Comment by pajong** [comment]
@joeyparrish 
This is the interpretContentProtection callback:

var Uint8ArrayUtils = shaka.util.Uint8ArrayUtils;

var keyid = Uint8ArrayUtils.fromHex(element.getAttribute('cenc:default_KID'));
var key = Uint8ArrayUtils.fromHex(specificKey);

var keyObj = {
    kty: 'oct',
    kid: Uint8ArrayUtils.toBase64(keyid, false),
    k: Uint8ArrayUtils.toBase64(key, false)
};
var jwkSet = {keys: [keyObj]};
var license = JSON.stringify(jwkSet);
var initData = {
    'initData': keyid,
    'initDataType': 'webm'
};
var base64 = window.btoa(license).replace(/\+/g, '-').replace(/\//g, '_');

licenseServerUrl = 'data:application/json;base64,' + base64;

return [{
    'keySystem': 'org.w3.clearkey',
    'licenseServerUrl': licenseServerUrl,
    'initData': initData
}];

I do not get any console error. It shows me the duration, but then buffers without playing the video.

**Comment by joeyparrish** [comment]
I am able to reproduce your issue on my own assets by either providing the wrong key or the wrong key ID.  Please double-check that your key and key ID are correct for the content.

**Comment by pajong** [comment]
Thank you for the answer. I will check the key and key ID again.

I also noticed that a video with  keys included in the manifest only plays the audio, but the video does not play. I tested on the shaka demo player (http://shaka-player-demo.appspot.com/) with the following manifest: http://html5.cablelabs.com:8100/cenc/ck/dash.mpd

Do I need to set something up to make the video play?

**Comment by joeyparrish** [comment]
There's not enough information in that manifest for the demo app to generically configure DRM.  All it has is this in the video AdaptationSet:

```
<ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011"
    value="cenc"
    cenc:default_KID="20000000-2000-2000-2000-200000000002"/>
```

How do we know that we should use clearkey over any other DRM system?  Or what the key should be for clearkey?

At the application level, your app could provide this information to the library, but the demo app itself can't know these things out of the box.

The reason the audio plays is that it is not encrypted.  The library knows that the video is encrypted, but the video AdaptationSet can't be used because the DRM info has not been provided.  The library filters out unusable AdaptationSets, which is why you get audio-only playback.

I googled the URL you gave me to find the keys.  I found them here: https://github.com/Dash-Industry-Forum/dash.js/commit/2ad046a

Here's a working interpretContentProtection callback for this content:

```
function interpretContentProtection(schemeIdUri, contentProtection) {
  var Uint8ArrayUtils = shaka.util.Uint8ArrayUtils;

  if (schemeIdUri == 'urn:mpeg:dash:mp4protection:2011') {
    // These two values were taken from
    // https://github.com/Dash-Industry-Forum/dash.js/commit/2ad046a
    var keyid = Uint8ArrayUtils.fromBase64('IAAAACAAIAAgACAAAAAAAg');
    var key = Uint8ArrayUtils.fromBase64('5t1CjnbMFURBou087OSj2w');
    var keyObj = {
      kty: 'oct',
      kid: Uint8ArrayUtils.toBase64(keyid, false),
      k: Uint8ArrayUtils.toBase64(key, false)
    };
    var jwkSet = {keys: [keyObj]};
    license = JSON.stringify(jwkSet);
    var initData = {
      'initData': keyid,
      'initDataType': 'webm'
    };
    var licenseServerUrl = 'data:application/json;base64,' +
        window.btoa(license);
    return [{
      'keySystem': 'org.w3.clearkey',
      'licenseServerUrl': licenseServerUrl,
      'initData': initData
    }];
  }

  console.warn('Unrecognized scheme:', schemeIdUri);
  return null;
}
```

**Comment by pajong** [comment]
Thank you so much for the answer!
