### ISSUE TITLE
Playback wrong video length iOS/Windows

### ISSUE THREAD

**Issue by nasufi** [google/shaka-player#2454]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.9

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Demo

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
iOS(Chrome & Safari) and Windows 10 Chrome

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What did you do?**

At the Demo Site -> Search for Manifest = HSL, Container = MP4, Source = Shaka
Play Second Video "Angel One (HLS, MP4, multilingual)".
On iOS browser Chrome and Safari video ends a few frames later than in Windows10. Video length also shows different length, Windows 0:59 and iOS 1:00.

**What did you expect to happen?**
Player should end at the same frame in both platforms Win/iOS.

**What actually happened?**

Video length is wrong on iOS/Win10

**Comment by joeyparrish** [comment]
We suspect a rounding error at the moment.  We'll look into it.

**Comment by joeyparrish** [comment]
`video.duration` for the current version of ["Angel One" HLS](https://shaka-player-demo.appspot.com/demo/#audiolang=en;textlang=en;uilang=en;asset=https://storage.googleapis.com/shaka-demo-assets/angel-one-hls/hls.m3u8;panel=SEARCH;build=uncompiled) on ChromeOS 79 is `59.221`.  The UI rounds this down to 0:59.

**Comment by ismena** [comment]
Ok, it is a rounding error indeed.
As @joeyparrish mentioned, Chrome reports 59-ish for the duration, while Safari reports 60.0.
Since different browsers have different media pipelines, some of them might not be frame-accurate and fractional-second differences are expected.
We - the player - just consume the information from the browser and display it.

Does it make sense?

**Comment by nasufi** [comment]
> Ok, it is a rounding error indeed.
> As @joeyparrish mentioned, Chrome reports 59-ish for the duration, while Safari reports 60.0.
> Since different browsers have different media pipelines, some of them might not be frame-accurate and fractional-second differences are expected.
> We - the player - just consume the information from the browser and display it.
> 
> Does it make sense?

I am not sure if the browser is, i guess OS.
Chrome and safari in iOS shows 1:00, in Windows chrome shows 0:59.

**Comment by joeyparrish** [comment]
Ah, I see the confusion.  On iOS, all browsers are Apple's WebKit engine inside.  This is a requirement Apple puts on the platform as far as I can tell.  So the media playback of all iOS browsers are identical.

**Comment by TheModMaker** [comment]
Does this answer all your questions? Can we close the issue?
