### ISSUE TITLE
HLS m3u8 manifest doesn't load on Safari (works on Chrome)

### ISSUE THREAD

**Issue by naktinis** [google/shaka-player#2458]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.9

**Can you reproduce the issue with our latest release version?**
If you mean 2.5.9, then yes.

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Custom app, demo manifest.

**If custom app, can you reproduce the issue using our demo app?**
Playing the video is not the issue, so demo app wouldn't show that. I am using a demo manifest though.

**What browser and OS are you using?**
MacOS Catalina 10.15.3
Safari 13.0.5

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
https://storage.googleapis.com/shaka-demo-assets/angel-one-hls/hls.m3u8

**What did you do?**
```
var url = 'https://storage.googleapis.com/shaka-demo-assets/angel-one-hls/hls.m3u8';
var player = new shaka.Player(video);
player.load(url).then(function() {
    console.log(player.getManifest());
});
```

**What did you expect to happen?**
The manifest should be printed to console. Works as expected on Chrome 80.

**What actually happened?**
Null is printed instead.

**Additional information**
On Safari debugging prints stop after:
```
[Info] Starting attach... (shaka-player.compiled.debug.js, line 570)
[Info] Starting load of https://storage.googleapis.com/shaka-demo-assets/angel-one-hls/hls.m3u8... (shaka-player.compiled.debug.js, line 576)
```
On Chrome it continues:
```
Starting attach...
Starting load of https://storage.googleapis.com/shaka-demo-assets/angel-one-hls/hls.m3u8...
Fetched start time for audio
First segment a-eng-0128k-aac-2c-s1.mp4 starts at 0
Reusing cached start time for audio
...
```
and so on.

**Comment by TheModMaker** [comment]
The lack of logging is expected, we use native HLS on Safari, so we can't log anything.  This also means the `getManifest` method won't work since playback is handled by the browser.  You can disable this with setting `streaming.useNativeHlsOnSafari` to `false`.

**Comment by naktinis** [comment]
Thank you for a quick explanation. For some reason I still expected it to parse the HLS manifest, but that makes sense.
