### ISSUE TITLE
Standart double-click event

### ISSUE THREAD

**Issue by KentukiS** [google/shaka-player#2459]
Hi, 
I need to disable double-click event. I mean fullscrean functionality.
Can i do this without editing standart functionality? 
Or i can use HTMLMediaElement to do this? 
Thanks for the answer!

**Comment by theodab** [comment]
If you are using the Shaka Player UI, the double click fullscreen is handled by the UI, so modifying the media element isn't going to work.
The UI doesn't have any way of disabling that at the moment, but this is a functionality that we could add.

**Comment by theodab** [comment]
Ok, this commit adds a new configuration option for the UI, `doubleClickForFullscreen`. When set to `false`, it should disable that functionality.
If you didn't mean the Shaka Player UI, and are using native controls instead, you can re-open this issue and ask about that.
