### ISSUE TITLE
Shaka Player draw Canvas

### ISSUE THREAD

**Issue by vicimpa** [google/shaka-player#2461]
Hello. I had a need to use Shaka Player in a game that uses Canvas to display video. When I try to draw a video element on Canvas, nothing happens. If I use a simple video element with a direct link instead of Shaka, then everything works. I suspect that this restriction is not related to Shaka, but I want to clarify. Shaka Player installed with npm.

**Comment by theodab** [comment]
I've had success playing from Shaka Player-controlled videos onto canvases before. It's only prevented if the asset is DRM-protected. What's the exact code you are using?

**Comment by vicimpa** [comment]
> I've had success playing from Shaka Player-controlled videos onto canvases before. It's only prevented if the asset is DRM-protected. What's the exact code you are using?


I just played a source with DRM protection on the video element. Thanks. I suspected that it was DRM protection. The same thing happens with Safari when using HLS. I decided to re-build the player based on JSMpeg. He certainly will not have such problems.
