### ISSUE TITLE
Bad rendering of CS Ads on Safari

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#2462]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes

**What version of Shaka Player are you using?** Nightly

**Can you reproduce the issue with our latest release version?** N/A

**Can you reproduce the issue with the latest code from `master`?** Yes

**Are you using the demo app or your own custom app?** Demo app

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
macOS 10.14.6 (18G3020)
Safari 13.0.5 (14608.5.12)

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

https://nightly-dot-shaka-player-demo.appspot.com/demo/#audiolang=es-ES;textlang=es-ES;uilang=es-ES;asset=https://storage.googleapis.com/shaka-demo-assets/tos-surround/dash.mpd;adTagUri=https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dskippablelinear&correlator=;panel=ALL_CONTENT;panelData=DEMO_ADS;build=uncompiled

**What did you do?**

Load the previous URL

**What did you expect to happen?**
The video size is correct

**What actually happened?**

<img width="1439" alt="Captura de pantalla 2020-03-17 a las 17 14 35" src="https://user-images.githubusercontent.com/8983024/76877023-14571300-6873-11ea-86e4-03755cbcc032.png">

**Comment by joeyparrish** [comment]
My guess it that we rely on an event that doesn't fire on Safari or fires at a different time.

**Comment by theodab** [comment]
I believe this may have to do with the timing of the `loadedmetadata` event on Safari. We use that event to know when we can re-size the ads to fit the actual size of the video (measured via the video's `offsetWidth` and `offsetHeight`).
From some basic investigation, it looks like when that event fires on Chrome, the video is at its final size. On the other hand, when that event fires on Safari, the video is still at its previous default size (of 640 by 480).

I'm fairly certain that the `loadedmetadata` event means that the browser should know what size the video element is meant to be, so this is probably a platform bug. It's a platform bug we could work around pretty easily, though, by introducing a minor delay between hearing the `loadedmetadata` event and changing size.
