### ISSUE TITLE
Mpd files not playing in shaka

### ISSUE THREAD

**Issue by Allwin-Backya** [google/shaka-player#2468]
I try to play mpd files with shaka. Sometimes the video is not playing. But, after sometimes it is playing. Can you please help me with this ?

**Comment by joeyparrish** [comment]
@Allwin-Backya, we would love to help you, but you didn't fill out the form with all the information we need to do that.  Please go back and fill out the bug report form: https://github.com/google/shaka-player/issues/new/choose  That will give us the information we need to start working on your issue.

Thanks!
