### ISSUE TITLE
Shaka does not clear the buffer behind the playhead

### ISSUE THREAD

**Issue by MegaLabs1** [google/shaka-player#247]
Hi, colleagues! 
while testing a Shaka player we have found that it takes system resources and doesn't free them.
![shaka_resources](https://cloud.githubusercontent.com/assets/2102317/11869089/ba73b6a8-a4cd-11e5-9465-e3660f0d73e6.png)
At this pic shaka played for 2 hours SD Live content and it ate more than 1 GB RAM.
Can we set some parameter to reduce the usage of RAM?

**Comment by joeyparrish** [comment]
Perhaps there is a memory leak.  What version of Shaka are you using?  Is the problem reproducible on the demo page on appspot?

**Comment by MegaLabs1** [comment]
We use shaka 1.5. 

>> Is the problem reproducible on the demo page on appspot?
Well, it seems Shaka stores everything in its buffer. Can we clear it with api call? 
![image](https://cloud.githubusercontent.com/assets/2102317/11929910/0fcec1f4-a7f0-11e5-97e2-babf7b74c413.png) it is about 25 minutes, can we reduce this caching level?

**Comment by MegaLabs1** [comment]
UPDATE. I have been watching live video at appspot demo site for 8 hours. Chrome ate 400 MB of RAM. In this case i used lighter profile (264 kbps instead of 7200 kbps and 3 hours), but it seems the problem is still present.

**Comment by joeyparrish** [comment]
Shaka 1 does not remove content from MediaSource buffers during streaming.  The browser has a built-in buffering limit and runs an eviction algorithm on the SourceBuffers when that limit is hit.  From JavaScript, we have no visibility into the eviction logic nor the limits.  Shaka 1 has always depended on the browser to handle eviction.

Shaka 2 will operate differently.  Part of the design for Shaka 2 is to place our own configurable byte limit on the amount of data we buffer at the MediaSource level, as well as a configurable limit on the number of seconds of data kept in buffer behind the playhead.

For example, you will be able to say "buffer 10 minutes ahead, but only leave 30 seconds behind, and stop early if we hit 100MB."

We expect to have a beta version of Shaka 2 out at the end of January.  Thanks for your patience!

**Comment by MegaLabs1** [comment]
>For example, you will be able to say "buffer 10 minutes ahead, but only leave 30 seconds behind, and stop early if we hit 100MB."

This is exatcly what we need! Thanks! Can we walk through the improvements on shaka2?

**Comment by joeyparrish** [comment]
Check out [REDESIGN.md in the preview branch](https://github.com/google/shaka-player/blob/preview/REDESIGN.md) if you want to see the design of Shaka 2, specifically [the configuration section](https://github.com/google/shaka-player/blob/preview/REDESIGN.md#sketch-of-player-configuration).  We are publishing code to the preview branch periodically as we make progress, so you can always browse the code there to see how things are shaping up.

**Comment by joeyparrish** [comment]
Fixed by f8b7b01
