### ISSUE TITLE
Recognize new CMAF file extensions cmfv, cmfa, cmft in HLS

### ISSUE THREAD

**Issue by zoomout** [google/shaka-player#2470]
**What link can we use to reproduce this?**
https://shaka-player-demo.appspot.com/demo/#audiolang=en-GB;textlang=en-GB;uilang=en-GB;asset=https://demo.unified-streaming.com/video/multi-format-drm/master.m3u8;license=https://widevine-proxy.appspot.com/proxy;panel=CUSTOM%20CONTENT;build=uncompiled

**What version of Shaka Player are you using?**
v2.5.10-uncompiled

**What browser and OS are you using?**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36

**What did you do?**
Open the link

**What did you expect to happen?**
Playback should be successful

**What actually happened?**
Error while resolving MIME_TYPE
Shaka Error MANIFEST.HLS_COULD_NOT_GUESS_MIME_TYPE (cmfa)

**Comment by zoomout** [comment]
The same would happen with CMFV, audio just goes first.

**Comment by joeyparrish** [comment]
The MediaSource API provided by the browser requires MIME types, but HLS playlists don't usually give them.  So we guess based on file extensions.

I believe the HLS parser would need to have these new cmfv, cmfa, and cmft file extensions added to its lists: https://github.com/google/shaka-player/blob/fda84c0343b34e1bfbc5581eccf8a12b7c14df37/lib/hls/hls_parser.js#L2337

Would you be willing to send a pull request for this?
