### ISSUE TITLE
Enforcing SD-only playback in Chrome desktop?

### ISSUE THREAD

**Issue by johnluther** [google/shaka-player#2471]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

Yes

**What version of Shaka Player are you using?**

2.5.10 (Shaka Demo Player)

**Please ask your question**

I'm unclear about how/if Widevine restricts HD playback in software CDM environments.

I created a multi-DRM encrypted DASH manifest in Shaka packager with this command:

```
packager \
  in=input/input360.mp4,stream=audio,drm_label=AUDIO,output=enc/audio.mp4 \
  in=input/input360.mp4,stream=video,drm_label=SD,output=enc/h264_360p.mp4 \
  in=input/input540.mp4,stream=video,drm_label=SD,output=enc/h264_540p.mp4 \
  in=input/input720.mp4,stream=video,drm_label=HD,output=enc/h264_720p.mp4 \
  in=input/input1080.mp4,stream=video,drm_label=HD,output=enc/h264_1080p.mp4 \
  --enable_widevine_encryption \
  --key_server_url https://license.uat.widevine.com/cenc/getcontentkey/widevine_test \
  --content_id 7465737420636f6e74656e74206964 \
  --signer widevine_test \
  --aes_signing_key 1ae8ccd0e7985cc0b6203a55855a1034afc252980e970ca90e5202689f947ab9 \
  --aes_signing_iv d58ce954203b7c9a9a9d467f59839249 \
  --protection_systems Widevine,PlayReady \
  --mpd_output enc/labels.mpd
```

I played the manifest in the Shaka Demo Player (using Chrome Mac Beta 81.0.4044.69). My (perhaps incorrect) expectation is that Shaka will only play the SD streams b/c Chrome Mac is a software CDM environment. Instead, it plays the 1080 stream.

My manifest is at https://jluther.s3.amazonaws.com/enc/labels.mpd, license server is https://cwip-shaka-proxy.appspot.com/no_auth

Am I doing something wrong?

**Comment by joeyparrish** [comment]
If the license server sent 1080p keys, Shaka will be fine with playing 1080p content.  Policies like "no HD for software CDM devices" can only be enforced by the license server by deciding which keys to return in the license.

In this case, it would seem that the license server returned HD keys.

**Comment by johnluther** [comment]
Got it, thanks. I was assuming that the server would only return the SD and AUDIO keys based on the DRM labels I used in the packager.
