### ISSUE TITLE
Integrate with Google Cloud Storage/Fireabse

### ISSUE THREAD

**Issue by diwgan32** [google/shaka-player#2472]
Hello!

I was wondering if I could get some guidance on how best to integrate Shaka player with google cloud storage. I have DASH content sitting in a protected Storage bucket, and simply getting the download URL for the MPD and feeding that into Shaka player doesn't work. I'm looking into the best way to modify the library to accept a Google Cloud URI, and resolve that into an actual download url whenever needed. Does anyone have pointers as to the best way to do this?

**Comment by joeyparrish** [comment]
What you want to do is get a public URL for the cloud storage content.  This is how we store the content we created for our demo app.  Here's a cloud storage doc on making data public: https://cloud.google.com/storage/docs/access-control/making-data-public

When you've done that, a link icon appears in the public access column. You can click on this icon to get the URL for the object, and feed that to Shaka Player.

There are alternative approaches if you don't want 100% public access to the files.  You could give out signed URLs that expire, or you could require authentication, or you could use DRM and require authentication for a license to decrypt.

Does this help?

**Comment by diwgan32** [comment]
Thanks for the quick response -- I'm looking for a solution that doesn't make access to files completely public. There is a function in the Firebase SDK `getDownloadURL()` that gives you temporary access to a file via a URL (see [this](https://firebase.google.com/docs/storage/web/download-files)... the function only returns a valid URL if your security rules allow the currently signed in user to access the file). Where would be the best place in the codebase to insert this small piece of logic to convert a given Google Cloud Storage URI into a valid URL using this Firebase construct? The issue I'm running into is that even if I use `getDownloadURL()` to get a valid URL for the MPD file, the dash parser still needs to know to use `getDownloadURL()` again on the URIs it generates for the segment files.

**Comment by joeyparrish** [comment]
In that case, I would suggest you try one of two options:

1. Register a scheme plugin to handle a URL scheme like "gs".  This plugin would take a "Request" object and produce a "Response" object asynchronously, but you could transform the URL in the request and then delegate it to the default plugin for "https".  See [shaka.net.NetworkingEngine.registerScheme](https://shaka-player-demo.appspot.com/docs/api/shaka.net.NetworkingEngine.html#.registerScheme) and [shaka.net.HttpFetchPlugin](https://shaka-player-demo.appspot.com/docs/api/shaka.net.HttpFetchPlugin.html)

2. Register a request filter which can inspect and modify requests before they are handled.  This plugin could simply modify a "Request" object to change the URL from gs:// to https://.  If the plugin is an async function or returns a Promise, then the request will not be processed until the Promise is resolved or the async function terminates.  See [shaka.Player.prototype.getNetworkingEngine](https://shaka-player-demo.appspot.com/docs/api/shaka.Player.html#getNetworkingEngine) and [shaka.net.NetworkingEngine.prototype.registerRequestFilter](https://shaka-player-demo.appspot.com/docs/api/shaka.net.NetworkingEngine.html#registerRequestFilter), as well as the [License Server Authentication Tutorial](https://shaka-player-demo.appspot.com/docs/api/tutorial-license-server-auth.html) which has examples of filters in action.

Does this help?

**Comment by diwgan32** [comment]
Awesome, something like this is exactly what I was looking for. Thanks for the help!

**Comment by joeyparrish** [comment]
Happy to help!  Let us know how if you need anything else.
