### ISSUE TITLE
Subtitles wrong position in Chromecast

### ISSUE THREAD

**Issue by jpintor14** [google/shaka-player#2479]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
YES

**What version of Shaka Player are you using?**
2.5.8 (Included on CC CAF Receiver)

**Can you reproduce the issue with our latest release version?**
NO, because I am using a CC receiver

**Can you reproduce the issue with the latest code from `master`?**
NO

**Are you using the demo app or your own custom app?**
Custom app

**If custom app, can you reproduce the issue using our demo app?**
NO

**What browser and OS are you using?**
Chromecast embedded browser

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
CC CAF receiver

**What are the manifest and license server URIs?**
The urls are dynamic, so I can not send it by email

**What did you do?**
Turn on any subtitle language (English or Spanish) and the text appears on the left screen corner.

**What did you expect to happen?**
Subtitles square centered on the screen

**What actually happened?**
Subtitles in wrong position like this: [Screenshot](https://drive.google.com/file/d/1HQx3ovba1r7glXT27lIoJaW9Zw8IiS8P/view?usp=sharing)

**Comment by joeyparrish** [comment]
If you can't provide content that can reproduce the problem, then we will not be able to work on the issue.

I should also point out that we are not responsible for CAF itself.  I expect this issue will be reproducible using the same browser built-in subtitle rendering that CAF uses, though.  If it turns out that this issue cannot be reproduced in a desktop browser using Shaka Player, we will have to refer you to the Cast team for help.

But first we'll need a content sample.  Without that, we can't possibly debug or fix anything.

**Comment by jpintor14** [comment]
I can provide some samples of ttml, but everything seems works ok with the files.

[test3.txt](https://github.com/google/shaka-player/files/4450891/test3.txt)
[test2.txt](https://github.com/google/shaka-player/files/4450892/test2.txt)
[test1.txt](https://github.com/google/shaka-player/files/4450893/test1.txt)

Thanks in advance for the help

**Comment by joeyparrish** [comment]
I tried these subtitles on ChromeOS with native text display (the same API used in CAF), and they are correctly centered.  This means that the issue must be internal to the Chromecast.  You'll need to reach out to the Cast team about that.

![subs-in-center](https://user-images.githubusercontent.com/6843156/79141120-001d0d80-7d6e-11ea-8320-87dca8fa86fe.png)

**Comment by ismena** [comment]
@joeyparrish Can we tag somebody from the Cast team to help propagate communication? :)
For some reason out current contacts on the team are escaping my mind(

**Comment by joeyparrish** [comment]
I've been tracking that down already this morning, and I just heard back from the Cast team.  They want you to go here:

https://support.google.com/cast-developer/#topic=3547309

And click "Contact our team" under the heading "Need more help".

**Comment by jpintor14** [comment]
I checked that the problem is on Chromecast's media_player.js, when the library try fix subtitles position lost the origin, if I load locally and comment that feature, the subtitles work by default (at bottom center).

So nothing is wrong with Shaka Player 🤙 
Thanks again to all for help!

**Comment by joeyparrish** [comment]
We're glad we could help!

**Comment by riksagar** [comment]
Hi @jpintor14 , can you share a diff of your change.  We also have a CC rendering issue on Chromecast, and would like to see if it's the same root cause.

Thanks,
Rik.

**Comment by jpintor14** [comment]
I added locally "v3/cast_receiver_framework.js" and "media_player.js".
The "media_player" code:

<img width="743" alt="Captura de pantalla 2020-04-16 a las 9 58 18" src="https://user-images.githubusercontent.com/10533447/79430257-f3e0bc80-7fc8-11ea-8593-adb0f62384f2.png">


Is only a way to keep the default behavior.
