### ISSUE TITLE
error code 2005 

### ISSUE THREAD

**Issue by clotairemarmignon** [google/shaka-player#2482]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
2.0.5

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `master`?**
yes

**Are you using the demo app or your own custom app?**
our own - it does the same on the demo one

**If custom app, can you reproduce the issue using our demo app?**
yes

**What browser and OS are you using?**
Chrome 80.0.3987.149 

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What did you do?**

We encoded all our videos, we can play them but one

**What did you expect to happen?**
we wanted to play this video

**What actually happened?**

Video doesn't begin, in the developer console, I have the 2005 error code.

When I try on the demo app, here is what is written: Shaka Error TEXT.INVALID_XML (This page contains the following errors: error on line 1 at column 1: Document is empty Below is a rendering of the page up to the first error.)

We did a test with different CC files, the problem is always the same.

**Comment by theodab** [comment]
That specific player error happens when the browser-provided `DOMParser` generates DOM with a `parsererror` element in it. So, it looks like there's some formatting error or errors in your caption files.

I can't say much more without being able to see them, though. You can send things to <shaka-player-issues@google.com>, if they can't be released publicly. Alternately, you could try running the text of your caption files through a `DOMParser` and see what happens for yourself.

**Comment by theodab** [comment]
Well, first off, your WebVTT is invalid. It should start with a line containing the word `WEBVTT`. See the [WebVTT spec](https://www.w3.org/TR/webvtt1/) for documentation and examples.

But that's a side-problem. The `INVALID_XML` error is only issued by the TTML parser. That means that Shaka Player is trying to parse your VTT as though it were TTML, which would definitely explain the parsing error.

I'm not quite sure why it is using the wrong parser, though. I tried running your content locally (both with master, and with v2.0.5), and (after fixing the formatting problem with the VTT file), it played the captions correctly. Are you loading the captions via `shaka.Player.addTextTrack()` or something?
