### ISSUE TITLE
UI - Playback rate is not updated in src mode

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#2488]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes

**What version of Shaka Player are you using?** Nightly

**Can you reproduce the issue with our latest release version?** No

**Can you reproduce the issue with the latest code from `master`?** Yes

**Are you using the demo app or your own custom app?** Demo
**What browser and OS are you using?** Safari 13.1 macOS Catalina

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

https://storage.googleapis.com/shaka-demo-assets/angel-one-hls/hls.m3u8

**What did you do?**

Load the previous stream in Safari (use native playback)
Change the playback rate in the UI

**What did you expect to happen?**
The playback rate mark is updated to the selection 

**What actually happened?**

The playback rate mark is not updated to the selection but the playback rate in the video is changed

**Comment by joeyparrish** [comment]
@avelad, can you help us debug this?  Try adding a listener to the video element first to see if the `ratechange` event is firing?  That's what our UI listens for.

```js
const video = document.querySelector('video');
video.addEventListener('ratechange', () => console.log('ratechange', video.playbackRate));
```

Thanks!

**Comment by avelad** [comment]
I just tried in Chrome 80 and it doesn't work

**Comment by avelad** [comment]
Url to test in Chrome:
https://nightly-dot-shaka-player-demo.appspot.com/demo/#audiolang=es;textlang=es;uilang=es;asset=https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4;panel=ALL_CONTENT;panelData=HLS;build=uncompiled

<img width="1678" alt="Captura de pantalla 2020-04-07 a las 21 38 58" src="https://user-images.githubusercontent.com/8983024/78712018-3bf04700-7918-11ea-8849-34be67482a93.png">


@joeyparrish the event is fired but the UI is not updated

**Comment by joeyparrish** [comment]
Excellent!  Thanks for the help.  I didn't think to use an mp4 to trigger src= playback in Chrome, and I had assumed this was an issue only with Safari.  But if it's failing in Chrome, too, it's probably not a browser-specific quirk.

I can confirm this issue in ChromeOS 80.

**Comment by joeyparrish** [comment]
I found the issue.  We're actually listening for a secondary `ratechange` event from the Player, since the Player uses playbackRate to manage buffering states.  The setup for that is broken in the src= path specifically.
