### ISSUE TITLE
Disable keydown event on controls

### ISSUE THREAD

**Issue by nasufi** [google/shaka-player#2489]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.10

**Please ask your question**
How can i disable keydown event on controls buttons and slider?

**Comment by theodab** [comment]
We don't have any builtin way to do this. I see two possibilities here:

1. You could cover the video container in a transparent div that intercepts the `click`,  `mousedown`, `touchstart`, `input`, `touchmove`, `touchend`, and `mouseup` events.

1. You could also configure the UI to remove the buttons entirely:
```js
const config = {
  controlPanelElements: [], // No buttons
  addBigPlayButton: false,
  addSeekBar: false,
  doubleClickForFullscreen: false, // If you want to disable this behavior too
};
ui.configure(config);
```


I suppose we could also add some UI configuration or method to disable input. I'm not entirely sure what your specific use-case is though. Are you wanting to disable input temporarily, while some operation happens? Do you want to have Shaka Player controls, but have them not work, for some reason?

**Comment by ismena** [comment]
@nasufi Also, could you tell us a bit more about your use case? What's going on with the keydown events that's bothering you?

If it makes sense (or is a common use case), we might be able to devise a more universal solution for this.

**Comment by nasufi** [comment]
I have disabled the BigPlayButton. The problem is that the keydown events are only active when the focus is on the controls, one click in video keydown events are lost.

**Comment by theodab** [comment]
Oh, sorry, I had misread you. I didn't notice you specifically cared about `keydown`, rather than all input events. Covering the element with another div wouldn't block keyboard events.

I can make a CL that adds a configuration option to disable `keydown` handling. I think that sounds reasonable, similarly to how we added a configuration to control the double tap to fullscreen behavior.

**Comment by theodab** [comment]
Actually, to be clear, which keyboard control behaviors do you care about?
Like, looking at our code for `keydown` and `keyup` events, they currently control:

1. Keyboard playback controls (arrow keys to seek, space to play/pause, etc).

1. The focus trap on the overflow menu, when it's open.

1. Which element gets the blue outline, when navigating via tab.

Which things do you want to be able to disable? I would assume it's the playback controls, but those are technically handled by `keyup` events.

**Comment by nasufi** [comment]
It would be nice if the Keyboard playback controls (arrow keys to seek, space to play/pause, etc) could be deactivated.

Another question, is it possible to disable doubleClickForFullscreen but to have a fullscreen button?

**Comment by theodab** [comment]
Okay, good to know.
And yeah, if you disable doubleClickForFullscreen, any fullscreen button in the UI will still work. That just disables the non-button-based behavior where clicking on the video twice makes it go fullscreen.

**Comment by joeyparrish** [comment]
I think we could offer an option to disable keyboard controls for seeking, pause, etc. when no particular thing is focused.  But tab-based keyboard navigation and keyboard-activation of buttons must still be possible for use by the blind.

**Comment by nasufi** [comment]
Thank you very much! Then cheers to the new release, hope it comes soon.
