### ISSUE TITLE
About shaka.player.Player.isLive() function

### ISSUE THREAD

**Issue by FeiCao** [google/shaka-player#249]
hi, I want to know the function of isLive(), dose it mean that judge the video is playing now ?  Is any function can judge the video is over?

**Comment by joeyparrish** [comment]
The player.isLive() method tells you if the stream you are playing is a live broadcast, as opposed to video-on-demand.

To know if the video is currently playing, check the paused property of the video element.  If false, the video is currently playing.

**Comment by FeiCao** [comment]
thank you!
