### ISSUE TITLE
Widevine license request error using Edge Chromium and Windows 10

### ISSUE THREAD

**Issue by ilFuma** [google/shaka-player#2492]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.10

**Can you reproduce the issue with our latest release version?**
Yes

**Are you using the demo app or your own custom app?**
Custom App

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
MS Edge 80 - Windows 10

**What are the manifest and license server URIs?**
[Link to Demo](https://shaka-player-demo.appspot.com/demo/#audiolang=it;textlang=it;uilang=it;asset=https://dds-cdn-media-test.filmbankconnect.com/ssm/stream/90618355-001/01E3HRN2CKAAWC058MP27WGBES.ism/.mpd?filter=(systemBitrate%3C=3500000);license=https://rng.stage.ott.irdeto.com/licenseServer/widevine/v1/fincons/license?contentId=90618355-001&ls_session=eyJraWQiOiJjMDYwNmZhMi1mZDE3LTRhOGMtYWI4Ny1kZDI3MTEwN2YwMTQiLCJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjb25zdW1lci1wb3J0YWwiLCJzdWIiOiJjZTY5ZjE0MC02MjI1LTQ3ZmQtOTdhNi0yMjYzZTk4OWFlMzAiLCJleHAiOjE4OTM0NTU5OTksImlhdCI6MTU4NjI0Njg5OCwiYWlkIjoiZmluY29ucyIsImp0aSI6ImE3ZTAzNjE3LWUwZDgtNGY1Yi1iZGQ1LWI3OWNlNTRkN2UyMSIsImVudCI6W3siZXBpZCI6ImVudC1wb2xpY3ktcXVhbGl0eWNoZWNrLWRlZmF1bHQiLCJiaWQiOiJCOTA2MTgzNTUtMDAxIn1dfQ.tz7uNoOhOTBZ6aUQYH3SRnN_NCEVf8bb_jPqRcOzbPM;panel=CUSTOM%20CONTENT;build=uncompiled)

**What did you do?**
Play Widevine DRM protected content on Edge 80 (Chromium) on Windows 10

**What did you expect to happen?**
Video should be played correctly

**What actually happened?**
LICENSE_REQUEST_FAILED | 6007 due to CORS error

---
The problem seems related to MS Edge 80 on Windows 10, the provided content works correctly on 
- Chrome on Windows / MacOs 
- Firefox on Windows & MacOs
- Edge 80 on MacOs

**Comment by joeyparrish** [comment]
We can't do anything about a CORS error.  CORS is an agreement between the server and the browser, based on headers sent by the server.  If the server doesn't allow cross-origin access from the page's origin, the browser will reject the response and fail the request.

Please check out MDN's article on CORS for more info on how CORS works: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

Does this help?

**Comment by ilFuma** [comment]
Hi @joeyparrish thanks for your quick reply.

CORS behaviour is pretty clear but, since the error occurs only on Edge 80 on Windows 10 and other browsers including the very same version of Edge on MacOS (80.0.361.111 64-bit) works well, is it possible that the problem is related to the way in which Shaka is calling the licenser?

CORS error is caused by the presence of the “soapaction” value in the “access-control-request-headers” request header while the licenser do not admit this value in the "access-control-allow-headers" response.

Why this isn't happening on other browsers?

**Comment by joeyparrish** [comment]
My guess is that the server doesn't support preflight requests: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Preflighted_requests

It's probably the case that Microsoft PlayReady requires a certain request header that other DRM systems don't need, and that this header triggers a preflight request that your license server doesn't allow the headers for.  PlayReady isn't available in Chrome or Firefox, so that would explain the difference there.

I'm not sure why it would behave differently in Edge on Mac, but I only just learned from you that Edge on Mac exists.  :-)  If we need to dig into the differences and debug it, I can offer some suggestions on that.

But my best guess is that your CORS error is triggered specifically by Microsoft PlayReady, and that your license server will need to add the appropriate CORS header to accept PlayReady license requests cross-origin.

Let us know if you still have issues after you fix the CORS headers on the license server.

**Comment by ilFuma** [comment]
Hi @joeyparrish , 
 you pointed me in the right direction, thanks 😃

Let me explain the workaround I found to solve the problem.

MS Edge 80 is based on Chromium, for this reason support both PlayReady and Widevine DRMs.

While using PlayReady everything works well with Widevine I face the error reported in the ticket.

My player is configured in this way:
```
player.configure({
	drm: {
		servers: {
		'com.widevine.alpha': licenseUrl,
		'com.microsoft.playready': licenseUrl
		}
	}
});
```
This configuration works well with all the following combinations:
- Chrome / Widevine
- Firefox / Widevine
- Edge Legacy / PlayReady
- Edge Chromium / Playready

**But not with Edge Chromium / Widevine  that is the combination I need to use.**

It seems that, on Edge Chromium, Shaka automatically selects PlayReady over Widevine therefore the license server is invoked in the wrong way.

Since I know the DRM Type before configuring the player, changing the code in this way it works as expected (supporting all the browser/DRM combinations I need):
```
if(drmType==="widevine"){
	player.configure({
		drm: {
			servers: {
			'com.widevine.alpha': mediaReq.licenseUrl
			}
		}
	});
}else if(drmType==="playready"){
	player.configure({
		drm: {
			servers: {
			'com.microsoft.playready': mediaReq.licenseUrl
			}
		}
	});
}else{
	// Unsupported DRM
}
```

**Comment by joeyparrish** [comment]
Ah, I see.  Well, we don't actually prefer one over the other.  Instead, the outcome depends on the manifest.  See the section "Choosing a Key System" in our DRM Configuration tutorial: https://shaka-player-demo.appspot.com/docs/api/tutorial-drm-config.html

Does this help?

**Comment by ilFuma** [comment]
I cannot change the DASH manifest because videos are packaged just in time and the manifest needs to contain both the "ContentProtection" tags for PlayPlayready and Widevine.

Anyway I can control the DRM choice using Shaka player configs.

Thanks for the support.

**Comment by joeyparrish** [comment]
We don't have another way, but perhaps we should.  If you'd like, we can convert this into a feature request for a way to set a preference order for key systems.
