### ISSUE TITLE
UI config to enable/disable fullscreen-on-rotate

### ISSUE THREAD

**Issue by sebastiancoteanu** [google/shaka-player#2494]
Hi, I am using shaka player 2.5.9. I have multiple videos in the same page and when I switch from portrait to landscape it will trigger fullscreen for all videos. I don't know if this is a bug or another feature to start with, but is there a chance to trigger the fullscreen on landscape on a specific video and not for all of them?

You can reproduce it by switching from portrait to landscape. This will trigger the fullscreen and if you close video by using minimize icon you'll see another video below which was also fullscreened.

**Comment by joeyparrish** [comment]
I think we could reasonably add a UI config to control the fullscreen-on-rotate feature.  Then you could disable it generally, but enable it on one specific video in your video wall if you choose.

Would that help?

**Comment by sebastiancoteanu** [comment]
Yeah, it will be great if the fullscreen would be more configurable in terms of screen rotation. I just want to avoid going in fullscreen with multiple videos (at the same time). So, if I am switching to landscape, even block the full screen there, or limit the number of fullscreened videos to one.

**Comment by sebastiancoteanu** [comment]
Hi,
I saw the comment for this. Is this scheduled to enter in the next release?
If yes, when it will be?

În joi, 9 apr. 2020 la 19:30, Joey Parrish <notifications@github.com> a
scris:

**Comment by joeyparrish** [comment]
I'll try to cherry-pick it for v2.5.11 later this week.

**Comment by sebastiancoteanu** [comment]
Many thanks!
