### ISSUE TITLE
Set default volume

### ISSUE THREAD

**Issue by Kotekczu** [google/shaka-player#2496]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes.

**What version of Shaka Player are you using?**
2.5.10.

**Please ask your question**
Hello. I'd like to know if there's a way to set a specific volume when the player loads, instead of the default 100%.

**Comment by TheModMaker** [comment]
The browser controls the volume through the `<video>` element.  See the [HTMLVideoElement.volume](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/volume) property.  We never change this value, so it will persist between loads.

**Comment by Kotekczu** [comment]
Thank you!
