### ISSUE TITLE
Text engine is duplicating some cues

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#2497]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes

**What version of Shaka Player are you using?** master

**Can you reproduce the issue with our latest release version?** Yes

**Can you reproduce the issue with the latest code from `master`?** yes

**Are you using the demo app or your own custom app?** Both

**If custom app, can you reproduce the issue using our demo app?** Yes

**What browser and OS are you using?**
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.92 Safari/537.36"

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

Not attached due to restrictions with our provider

**What did you do?**

- Load and asset 
- Select one subtitle track

**What did you expect to happen?**
The subtitles are displayed correctly

**What actually happened?**

The subtitles are not displayed correctly

TTML file with which the error occurs:
`<?xml version="1.0" encoding="utf-8"?><tt xml:lang="en" xmlns="http://www.w3.org/ns/ttml" xmlns:ttm="http://www.w3.org/ns/ttml#metadata" xmlns:tts="http://www.w3.org/ns/ttml#styling"><head><styling><style xml:id="defaultSpeaker" tts:fontSize="25px" tts:fontFamily="arial" tts:fontWeight="normal" tts:fontStyle="normal" tts:textDecoration="none" tts:color="white" tts:backgroundColor="black" tts:textAlign="center" tts:origin="10% 85%" tts:extent="80% 10%"/><style xml:id="defaultCaption" tts:fontSize="25px" tts:fontFamily="arial" tts:fontWeight="normal" tts:fontStyle="normal" tts:textDecoration="none" tts:color="white" tts:backgroundColor="black" tts:textAlign="center" tts:origin="10% 85%" tts:extent="80% 10%"/></styling><layout><region style="defaultSpeaker" xml:id="speaker"/></layout></head><body style="defaultCaption" xml:id="thebody"><div xml:lang="en"><p begin="00:08:42.50" end="00:08:45.77" region="speaker">La Corte Imperial es tan mala<br/>que los hombres prefieren...</p><p begin="00:08:45.77" end="00:08:47.53" region="speaker">...que nosotros<br/>hagamos justicia.</p><p begin="00:08:47.97" end="00:08:49.20" region="speaker">Es una vergÃ¼enza.</p></div></body></tt>`

Current behaviour:
![Captura de pantalla 2020-04-13 a las 15 45 31](https://user-images.githubusercontent.com/8983024/79125415-70438780-7d9e-11ea-9692-1c9219312471.png)

Note: The console show the variable https://github.com/google/shaka-player/blob/master/lib/text/text_engine.js#L162

Expected behaviour:
![Captura de pantalla 2020-04-13 a las 15 44 34](https://user-images.githubusercontent.com/8983024/79125448-82bdc100-7d9e-11ea-9ea0-d47bebd32c56.png)

Note: The console show the variable https://github.com/google/shaka-player/blob/master/lib/text/text_engine.js#L162

I changed https://github.com/google/shaka-player/blob/master/lib/text/text_engine.js#L162-L165 by
```
const cuesToAppend = allCues.filter((cue) => {
      return cue.startTime >= startTime &&
          cue.startTime < endTime;
    });
``` 
and the expected behaviour is produced

My knowledge of the text engine is limited, would this change be correct? If so, would you accept a PR for this?

**Comment by michellezhuogg** [comment]
Hello @avelad , this issue may be related with either TextEngine or TextDisplayer. Could you please send us this sample manifest, so that we can reproduce and confirm the fix?

**Comment by avelad** [comment]
@michellezhuogg, I sent an email with the details.

**Comment by avelad** [comment]
Note: I used the native displayer and it doesn’t work so I think that the problem is related to TextEngine

**Comment by joeyparrish** [comment]
@avelad, I'm confused by what you said earlier:

> I changed https://github.com/google/shaka-player/blob/master/lib/text/text_engine.js#L162-L165 by
> 
> ```
> const cuesToAppend = allCues.filter((cue) => {
>       return cue.startTime >= startTime &&
>           cue.startTime < endTime;
>     });
> ```
> and the expected behaviour is produced

It sounds like you're saying you found a fix, but the code you pasted looks identical to what we have.  Can you clarify?

**Comment by avelad** [comment]
The current code is (https://github.com/google/shaka-player/blob/master/lib/text/text_engine.js#L162-L165):
```
const cuesToAppend = allCues.filter((cue) => {
      return cue.startTime >= this.appendWindowStart_ &&
          cue.startTime < this.appendWindowEnd_;
    });
```
If I change it by:
```
const cuesToAppend = allCues.filter((cue) => {
      return cue.startTime >= startTime &&
          cue.startTime < endTime;
    });
```
The behaviour is the expected.

Note: I change `this.appendWindowStart_` by `startTime` and `this.appendWindowEnd_` by `endTime`

**Comment by avelad** [comment]
Ahh, I see, post the comment, but I made a mistake and when updating it seems that it has not been reflected in the emails, sorry!

**Comment by joeyparrish** [comment]
No worries!  It's a subtle difference, and I probably overlooked it even when looking at the edited version.
