### ISSUE TITLE
Updating availabilityWindowOverride value after load

### ISSUE THREAD

**Issue by Kotekczu** [google/shaka-player#2498]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes.

**What version of Shaka Player are you using?**
2.5.10.

Hello, I'm trying to set the availabilityWindowOverride value on click with a button, and it's changed with success, but it isn't really updated on the player. this.player.getConfiguration().manifest.availabilityWindowOverride shows the new value but the seekbar remains the same. Not sure if I need to use any other function to "update" it.

**Comment by joeyparrish** [comment]
I believe that value is used when the content is first loaded.  Changing it mid-playback may not have an effect until you load another piece of content.

**Comment by Kotekczu** [comment]
There's no way of changing it with real effect once the live stream is loaded then?

**Comment by joeyparrish** [comment]
The intent of the config is to allow you to override part of the manifest that you may not have control over.  For example, HLS live does not allow seeking by default (or at all in Apple's implementation), so that gives you a way to allow seeking in HLS live.  Or if the DASH packaging software doesn't allow you to change `timeShiftBufferDepth`, and you want to shrink or grow it in the client.

But in all of those cases, we assume you know in advance that you want to change it, before you start playing the content.  So the value is applied in the manifest parser (DASH or HLS) early in the parsing process and never again.

Why do you want to change it during playback?  What's your goal?

**Comment by Kotekczu** [comment]
I'm testing a start-over function with a DASH live stream. I've set availabilityWindowOverride for 2 hours, so if the program started 3 hours ago the player can't jump to that point if availabilityWindowOverride value isn't increased first.

**Comment by joeyparrish** [comment]
I'm not sure I see the value in it, but if you're willing to play with some of the internals, you can modify the manifest directly:

```js
player.getManifest().presentationTimeline.setSegmentAvailabilityDuration(2 * 60 * 60);
```

The manifest structure is not guaranteed to stay the same between minor number releases, so beware.  But that should work for what you're trying to do, and we have no plans to change that part of the structure at this time.

Does this help?

**Comment by Kotekczu** [comment]
It seems working. One more question, how can I check the current value set for setSegmentAvailabilityDuration?

**Comment by joeyparrish** [comment]
This was never intended as an application-facing API.  The best we have in a release version is getSegmentAvailabilityStart() and getSegmentAvailabilityEnd().  You can also make changes to the source if you wish.  See [`lib/media/presentation_timeline.js`](https://github.com/google/shaka-player/blob/09895652b3ae8b2f692d31bd4a8c4e20ea95cfa7/lib/media/presentation_timeline.js#L163).

Does this help?

**Comment by Kotekczu** [comment]
I just set a variable for setSegmentAvailabilityDuration at the beginning of the code and solved. Thank you so much for your help!

**Comment by joeyparrish** [comment]
> Could you please explain me what you meant with this?
> 
> > The manifest structure is not guaranteed to stay the same between minor number releases, so beware.

For example, the manifest structure returned by `player.getManifest()` in v2.5.x will not be the same as the structure returned by the same method in v2.6.x.  Between minor-number releases (where the second number in the version changes), internal structures like that can change.

**Comment by Kotekczu** [comment]
I understand. I'll beware. Thank you again.

**Comment by joeyparrish** [comment]
Glad we could help!
