### ISSUE TITLE
Sintel missing final audio segment

### ISSUE THREAD

**Issue by pajong** [google/shaka-player#250]
Hello,
I am playing clearkey encrypted stream. 
It plays fine until I try to seek.

This is the stream that I am trying to play:
file: http://bitdash-a.akamaihd.net/content/sintel-ck/stream.mpd
keyId: 121a0fca0f1b475b8910297fa8e0a07e
key: a0a1a2a3a4a5a6a7a8a9aaabacadaeaf

When I seek, I get the following console error, and the video stops playing:
shaka.compiled.js:107 GET http://bitdash-a.akamaihd.net/content/sintel-ck/audio/und/seg-443.m4f?_=1450714744630 404 (Not Found)

Can I get some help to debug this?
Thank you.

**Comment by joeyparrish** [comment]
The manifest has a duration of 14:48 and segment size 2s on both audio and video.  Therefore, with startNumber 0, there should be segments numbered 0-443.

It seems that audio segment 443 (the final audio segment) is not on the server (HTTP 404).

Seeking and clearkey actually have nothing to do with the issue.  You can just let the video stream all the way to the end and see the same thing.

There doesn't seem to be a Shaka bug here, so please ask the content owner to provide the missing segment (audio/und/seg-443.m4f) or to fix the manifest (shrink duration to the 14:46, the minimum of the available audio & video durations).
