### ISSUE TITLE
Error 4001 DASH flow

### ISSUE THREAD

**Issue by ivansteff** [google/shaka-player#2502]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
Latest

**Please ask your question**

Good afternoon!
I caught error 4001, tried to fix it, it fails. I can’t figure out where this problem appears on the backend or frontend.
What can I provide you, so that you can help me figure out where the error is?
I can provide a link to the stream, but there is one but it is a regional restriction.

**Comment by theodab** [comment]
You can send confidential URLs and files to <shaka-player-issues@google.com>.

Normally, we would say that just sending a manifest over is not enough, and that to actually diagnose a bug we would need to be able to play your stream. However, the `4001` error (`DASH_INVALID_XML`) means that the DASH manifest file is not parsing properly; to figure out that problem, an example manifest is probably enough.

**Comment by joeyparrish** [comment]
> **What version of Shaka Player are you using?**
> Latest

Can you please be more specific?  It's always possible you are mistaken about what version the latest is.  Or you could mean "latest" code from the master branch, or "latest" release version.

**Comment by ivansteff** [comment]
@theodab i send email. manifest  is empty.
@joeyparrish i mean 2.5.10 verison.

**Comment by theodab** [comment]
Uh, when you say "manifest is empty", do you mean that the regional restriction will cause the manifest to be empty for me? Or do you mean that the manifest file is meant to be empty?
Because the DASH parser will definitely fail if you provide it with an empty manifest. Because... there's nothing to parse.

**Comment by ivansteff** [comment]
For example, the same link that I sent to the email works on android (using ExoPlayer).

@theodab I downloaded the manifest and it turned out to be empty.
I understand this is configured on the backend?

**Comment by theodab** [comment]
I am reasonably certain that this isn't some bizzare bug with the Shaka Player network stack; I tried plugging your URL into the [dash.js reference player](https://reference.dashif.org/dash.js/v3.1.0/samples/dash-if-reference-player/index.html), and they also got an empty manifest.

So yes, this sounds like a backend problem. If it is serving empty manifests to desktop browsers, but working manifests to Android devices, then something is presumably wrong with it. I'm not a backend expert, though, so I can't speak to any probable causes.

**Comment by joeyparrish** [comment]
If ExoPlayer accepts an empty manifest, it might be interesting to know why, and how it is interpreted.  Does "empty" here mean "0-byte file" or "DASH MPD without any Representation elements"?

**Comment by theodab** [comment]
It's a 0-byte file.

**Comment by joeyparrish** [comment]
A 0-byte file is not a valid MPD, so this is working as intended in Shaka Player.  Sorry we can't do more to help you with your backend!
