### ISSUE TITLE
RESTRICTIONS_CANNOT_BE_MET error for multiple periods using different DRM keys

### ISSUE THREAD

**Issue by lyjimmy** [google/shaka-player#2503]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.8

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
This was originally reported by our customer when casting to a Chromecast receiver app

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Chrome on MacOS

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
I was also able to reproduce using a 1st generation Chromecast

**What are the manifest and license server URIs?**
Sending the URIs to shaka-player-issues@google.com

**What did you do?**
Let the content play through the preroll ad break (60 seconds).

**What did you expect to happen?**
The playback transitions from the preroll ad break to the content.

**What actually happened?**
For versions 2.5.6-2.5.10, the playback gets stuck at the end of the preroll ad break. The console includes a 4012 MANIFEST.RESTRICTIONS_CANNOT_BE_MET error due to missing keys. Then there is an error message saying "invalid Streams chosen: missing audio Stream". Finally there is a 5005 STREAMING.INVALID_STREAMS_CHOSEN error in the console.

The behavior is different using the latest code from `master`. The 4012 error is still thrown but the playback does not get stuck at the period boundary, which is much better. I've been able to trace the issue back to https://github.com/google/shaka-player/commit/0e1e1a04911d4b9e7e0d911dafb6ae83103552c5. Previous to this change (e.g. version 2.5.5 and before) there is no 4012 error when playing the same asset.

The issue seems to be limited to our multiperiod ad-stitched assets where the ads are encrypted with different DRM keys than the content. The `ContentProtection` tags in the content periods have `cenc:default_KID` values, but the `ContentProtection` tags in the ad periods do not. When `onKeyStatus_` is called at the start of the preroll ad break, the `keyStatusMap` only contains keys for the ads. The variants related to the content have the `allowedByKeySystem` property set to `false` since the content keys are not in the `keyStatusMap` yet. In `checkRestrictedVariants_`, the player doesn't find any variants with keyId values that have the `allowedByKeySystem` property set to `true` so the player throws the 4012 error. Do you know if this should be the intended behavior? Or do you know if there could be a future change that would stop throwing the 4012 error since that error wasn't thrown previously for these assets?

Thanks!

**Comment by joeyparrish** [comment]
Without the key IDs for the ad streams, we don't know if we **can** play that part of the content.  That's why the "restriction" error fires.

Can you fix the content to include key IDs for ads?  Do the ads need to be encrypted at all?

**Comment by lyjimmy** [comment]
The data included with the 4012 restriction error indicate that the missing key IDs are associated with the content streams, which was the initially confusing part. I'm inquiring with the backend team about whether the ad periods that get stitched in can include the key IDs as well. The ads need to be encrypted on some platforms, but I don't remember which off the top of my head.

**Comment by joeyparrish** [comment]
If you can find out which platforms require encrypted ads, please let us know.  This could be important for our own testing.

At the moment, I'm not aware of any web browsers or web-based platforms that require this.

**Comment by lyjimmy** [comment]
The sample asset that I had sent to shaka-player-issues@google.com has been updated to include the key IDs for the ad periods as well. Unfortunately I'm still seeing the 4012 error for versions 2.5.6-2.5.10 as well as the latest from master. For version 2.5.5 I don't see the 4012 error still.

I'm seeing at https://github.com/google/shaka-player/blob/master/lib/player.js#L4277 that the audio and video stream of each variant have two keyIds associated with them: one from the ads and one from the contents. Since onKeyStatus_ is first called with just the key IDs from the ads, the allowedByKeySystem values are all getting set to false because the content key IDs that are associated with the streams are not found in the keyStatusMap. I think this is why the 4012 error indicates that the content keys are missing.

Aside from using unencrypted ads, do you happen to have any advice/suggestions about this since things were fine back in 2.5.5? Perhaps there aren't any web based platforms that require encrypted ads at this point. It requires more testing on our side. Thanks!
