### ISSUE TITLE
Performance info

### ISSUE THREAD

**Issue by harishnb** [google/shaka-player#2507]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
2.5.10

**Please ask your question**

Where can find performance info about the player such as:
Download bit rate (min, max)
Time to start the video (video startup time)
No of stalls 
etc

**Comment by theodab** [comment]
There's a method on player, called `getStats`. It has the (current) stream bandwidth, the number of dropped frames, etc. You can determine the start time and the number of stalls by examining the `stateHistory` (which lists the timestamps of each change in state, e.g. between playing, paused, buffering, etc).

**Comment by harishnb** [comment]
Thank you so much for the info.

**Comment by theodab** [comment]
Okay. It sounds like everything is settled then.
If you have any further questions about performance issues, you can re-open this.
