### ISSUE TITLE
Is there any way to pause Shaka player when it is loaded, at certain duration?

### ISSUE THREAD

**Issue by vishwajeetv** [google/shaka-player#2510]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.6.10

**Please ask your question**
Is there any configuration that I can pass so that the Shaka Player pauses itself at certain duration/point in the video? , for e.g. I want to pause player on 300 seconds.

One way is to change `playRangeEnd` configuration, but that messes the user experience Is there any alternative?

https://stackoverflow.com/questions/61301420/how-to-pause-shaka-player-after-it-is-loaded

**Comment by TheModMaker** [comment]
You could use the [timeupdate](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/timeupdate_event) event from the video and wait until the current time reaches that time:

```js
video.addEventListener('timeupdate', () => {
  if (video.currentTime >= 300)
    video.pause();
});
```

**Comment by vishwajeetv** [comment]
Hi @TheModMaker , thanks for the answer. This solves the problem. So this is related to the native video element itself, not with the shake player.
@shaka-bot I am closing the issue.
