### ISSUE TITLE
Accessing SourceBuffers of an mp4 Manifest Uri

### ISSUE THREAD

**Issue by sacredvoid** [google/shaka-player#2514]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes, I have checked the FAQ and did not find relevant questions/answers. 

**What version of Shaka Player are you using?**
Shaka Player v2.5

**Please ask your question**
Hi, my project requires me to understand the path that SourceBuffers take, and understand how to change/manipulate them. With some shaka.log statements I was able to find that Buffers are handled in the media_source_engine.js (used the default Manifest URI provided). When I changed the manifest URI to an MP4 file sitting in the cloud, I found out that it used **src=** mode. Needed some clarity on what happens when we provide a direct MP4 stream and how to possibly access those bufferArrays and save them onto my local machine. 
Thanks.
@joeyparrish

**Comment by TheModMaker** [comment]
When using `src=` mode, we only give the browser the URL and the browser handles everything.  We don't use MediaSource/SourceBuffer since everything is handled by the browser.  We cannot play "plain" MP4 using MediaSource since many MP4 files cannot be streamed and need to be formatted correctly to support streaming.

**Comment by sacredvoid** [comment]
Thanks @TheModMaker , that's clear. Could you tell me how to access and save the source Buffers when using the **Load** mode? My colleague @anilnakka tried taking the uInt8bufferArray values of the first segment (by printing it on the browser) and then recreated an image with a simple python code but got a noisy image that doesn't resemble what's being displayed(on the shaka player). What could be the error?

![new](https://user-images.githubusercontent.com/33939902/79790461-5ccd8900-8369-11ea-9182-2ac1895c4cdf.png)

**Comment by sacredvoid** [comment]
@TheModMaker Are buffers getting decoded after being appended? Because when matching the byte length of the video segment (576p) with the size of a 576p frame, video segment is generally smaller. Also, are the buffers RGB/YUV?

**Comment by joeyparrish** [comment]
The buffers are not images, they are encoded video segments in a container.  For example, if you're streaming MP4-based content, then what is appended to the buffer is a fragmented MP4.

Decoding and rendering of frames happens inside the browser.  If you want access to the frames of a video, you can do this with `<canvas>`, assuming the video is not protected by DRM.  This will work for plain MP4s in src= mode, too.  See this MDN article to get started on that path: https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Manipulating_video_using_canvas

Does this help?

**Comment by sacredvoid** [comment]
Yes! That did help, thank you @joeyparrish ! Closing the issue for now.
