### ISSUE TITLE
Fade out bottom controls

### ISSUE THREAD

**Issue by nasufi** [google/shaka-player#2515]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.10

**Please ask your question**
If the mouse is over the bottom controls, is it possible not to fade out them?

**Comment by joeyparrish** [comment]
> If the mouse is over the bottom controls, is it possible not to fade out them?

This is already the behavior.  If you move your mouse over the bottom controls, they will not fade away.  If you move your mouse to the empty middle area of the video, the controls will fade away after 3 seconds.  If you move your mouse out of the video area, the controls will fade away immediately.

Does this answer your question?

**Comment by nasufi** [comment]
But if the mouse doesn't move over the bottom controls, the controls fade away after 3 seconds.
I want to show them allways if the mouse is over the bottom controls.

**Comment by TheModMaker** [comment]
What browser with version are you using? Where are you hovering?  I can reproduce with hovering over the bottom of the faded region, but not when over the slider itself.  Depending on exactly where the mouse is, we may fade.  We only keep them shown when over a control, not the whole faded region.

**Comment by joeyparrish** [comment]
> But if the mouse doesn't move over the bottom controls, the controls fade away after 3 seconds.
I want to show them allways if the mouse is over the bottom controls.

This sounds like a contradiction.  "If the mouse **doesn't move over the bottom controls**" ... "if the mouse **is over the bottom controls**".  Is there a typo somewhere causing confusion?  Or is the ambiguous use of the word "over" in English, where you could mean "Y-axis" (over the controls, higher up in the video frame) or "Z-axis" (over the controls, directly on top of, hovering over)?

**Comment by nasufi** [comment]
Oh sorry, my mistake. I mean if the mouse is over the slider or play button and doesn't move.

**Comment by joeyparrish** [comment]
Over as in z-axis?  Pointing at the slider or play button?

**Comment by nasufi** [comment]
Yes.

**Comment by nasufi** [comment]
I can see in the demo site is not the case. I think I have some mistake in the player integration.

**Comment by joeyparrish** [comment]
That's possible.  Are you using our UI, or the native one in the browser?  In Chrome, they look very similar.

The native UI is enabled by using `<video controls>` in HTML or `video.controls = true;` in JavaScript.  Our UI is enabled as seen in this tutorial: https://shaka-player-demo.appspot.com/docs/api/tutorial-ui.html

**Comment by joeyparrish** [comment]
Actually, I see the same fade-out behavior on both Chrome native controls and our UI controls.  But another browser's native controls might behave differently.

**Comment by nasufi** [comment]
Yes I am using shaka-player UI. My implementation looks like this:
<div data-shaka-player-container class="video-container">
     <video data-shaka-player autoplay playsinline onloadstart="this.volume=0.5" id="video" style="width: 100%; height: auto;" />
</div>


const video = document.getElementById('video');
const ui = video['ui'];
const controls = ui.getControls();
const player = controls.getPlayer();
const uiConfig = ui.getConfiguration();
uiConfig.addBigPlayButton = false;
uiConfig.doubleClickForFullscreen = false;
// some own buttons
uiConfig['controlPanelElements'] = ['time_and_duration_custom', 'fast_rewind', 'play_pause', 'fast_forward', 'play_speed', 'seek_frame_bw', 'seek_frame_fw', 'spacer', 'volume', 'mute', 'overflow_menu', 'fullscreen'];

**Comment by joeyparrish** [comment]
Are you loading our UI's compiled CSS?  Are you overriding any of it?  What browser are you using?

**Comment by nasufi** [comment]
I am using shaka-player.ui.debug.js and controls.css, browser is Chrome 81.0.4044

**Comment by joeyparrish** [comment]
I'm sorry, but I can't reproduce your results.  If I mouse over the controls, they stay on the screen for me until I mouse away from them.  If I leave the mouse in the middle of the video, the controls fade after 3 seconds.  If I mouse out of the video element, the controls fade right away.

**Comment by nasufi** [comment]
I think the problem is in shaka-player.ui.js.
I can reproduce it with your example https://shaka-player-demo.appspot.com/docs/api/tutorial-ui.html.
Is there any demo similar to the code in the example?
