### ISSUE TITLE
Hiding default control buttons (volume bar, time, zoom,settings)

### ISSUE THREAD

**Issue by harishnb** [google/shaka-player#2520]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.10

**Please ask your question**
With the simple app (https://shaka-player-demo.appspot.com/docs/api/tutorial-basic-usage.html)  I am trying to hide the controls with the below code:

```
const config = {
  addSeekBar: false
};
ui.configure(config);
```

I was able to hide seekbar but I could not hide settings and other native controls with following code. Hence please advice if there is a simple way to hide all the controls.

```
const video = document.getElementById('video');
  const ui = video['ui'];
  const controls = ui.getControls();
  const player = controls.getPlayer();
    
  
  // Hide the controls
  window.player = player;
  window.ui = ui;
  window.player.ui = false;
  ui.getControls().hideSettingsMenus();
  ui.getControls().setEnabledNativeControls(false);
```

**Comment by ismena** [comment]
Hi @harishnb 
Thanks for reaching out. What's the end result you want? Which controls (if any) would you like to be present for your app? Do you want the play/pause button?

If you don't want any controls whatsoever, you can follow [this tutorial](https://nightly-dot-shaka-player-demo.appspot.com/docs/api/tutorial-basic-usage.html) and remove the `controls` param from the video element:
`
<video id="video"
           width="640"
           poster="//shaka-player-demo.appspot.com/assets/poster.jpg"
           autoplay></video>
`
This will give you an absolutely control-less video element :)
If you want _some_ controls, but not others, let us know which and we'll help you configure the UI!

**Comment by joeyparrish** [comment]
If you expected this to remove all controls:

```js
const config = {
  addSeekBar: false
};
ui.configure(config);
```

You may not have known that any missing fields are left alone.  To remove controls, specify the ones you want to keep, which could even be an empty array:

```js
const config = {
  addSeekBar: false,
  addBigPlayButton: false,
  controlPanelElements: [],
};
ui.configure(config);
```

You can also control the presence of absence of overflow menu items:

```js
const config = {
  addSeekBar: false,
  addBigPlayButton: true,
  controlPanelElements: ['overflow_menu'],
  overflowMenuButtons: ['cast'],
};
ui.configure(config);
```

Do these examples help?

**Comment by harishnb** [comment]
Thank you so much for the response, @joeyparrish your code was really helpful. I was exactly looking for the same.!!!
