### ISSUE TITLE
Autoplay does start playback 

### ISSUE THREAD

**Issue by harishnb** [google/shaka-player#2521]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.10

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
yes

**Are you using the demo app or your own custom app?**
demo app mentioned at (https://shaka-player-demo.appspot.com/docs/api/tutorial-basic-usage.html)

**If custom app, can you reproduce the issue using our demo app?**
NA

**What browser and OS are you using?**
Windows 10 and chrome browser

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
NA

**What are the manifest and license server URIs?**

**What did you do?**

Using the demo code, created index.html and myapp.js, when launched the mpd file is loaded but have to click on video play. I want the video to play without pressing any button.

**What did you expect to happen?**
With the autoplay option, I was expecting the video to play without pressing any button.

**What actually happened?**
Video load but playback does not start.

**Comment by chrisfillmore** [comment]
Take a look at Chrome's autoplay policies:
https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

Most likely you need to set the `muted` attribute on the video element. But you should see the article for details.

**Comment by joeyparrish** [comment]
The browser controls and restricts autoplay.  See the article Chris mentioned for details.  Apple has similar policies for Safari.

In Chrome, a site you're accessing for the first time will not autoplay, but once you've demonstrated a certain level of "engagement", it will remember that and autoplay content in future sessions.

As Chris mentioned, muting the video element will allow autoplay in Chrome.
