### ISSUE TITLE
Subtitles are not working in HLS-Safari with src mode

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#2523]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes

**What version of Shaka Player are you using?** master

**Can you reproduce the issue with our latest release version?** No, because the regression is not in any release yet

**Can you reproduce the issue with the latest code from `master`?** Yes

**Are you using the demo app or your own custom app?**  Demo

**What browser and OS are you using?**
Safari 13.1 macOS 10.15.4 and iPadOS 13.4

**What are the manifest and license server URIs?**
https://storage.googleapis.com/shaka-demo-assets/angel-one-hls/hls.m3u8

**What did you do?**

Load the previous stream

**What did you expect to happen?**
The subtitles are shown in the UI

**What actually happened?**

The subtitle are not shown due a regression in https://github.com/google/shaka-player/commit/ad3d4604af69d70855fd80bbdc2fdf42c62370f4

Example in demo app: https://nightly-dot-shaka-player-demo.appspot.com/demo/#audiolang=es;textlang=es;uilang=es;asset=https://storage.googleapis.com/shaka-demo-assets/angel-one-hls/hls.m3u8;panel=ALL_CONTENT;build=uncompiled
![image](https://user-images.githubusercontent.com/8983024/80012858-442ab380-84ce-11ea-9302-6c253d9093cf.png)

Some additional info:

In `getTextTracks` the tracks with mode disabled are filtered, https://github.com/google/shaka-player/blob/master/lib/player.js#L2858-L2861

In `selectTextTrack` other tracks are configured with mode disabled https://github.com/google/shaka-player/blob/master/lib/player.js#L2904-L2914

**Comment by joeyparrish** [comment]
My fix for #2516 is causing this issue, so I'm going to revert that change and reopen that issue.

Thanks for the detailed report!

As an aside, I think we need to improve test coverage for native HLS on Safari.  For that, we'll need to use real content URIs like the one in this issue, because we can't use locally-generated or fake content in a non-MediaSource playback.
