### ISSUE TITLE
Playback speed not shown while first playback is buffering

### ISSUE THREAD

**Issue by TheModMaker** [google/shaka-player#2526]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
Nightly

**Can you reproduce the issue with our latest release version?**
No

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Demo app

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
Safari

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**
Demo HLS asset.

https://nightly-dot-shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://storage.googleapis.com/shaka-live-assets/player-source.m3u8;panel=HOME;build=uncompiled

**What did you do?**
Load the site for the first time; play the asset.

**What did you expect to happen?**
In the overflow menu, the "Playback speed" entry should also show the 1x for the current rate.

**What actually happened?**
The rate isn't shown.  If you change the rate, it updates with the new rate.

It also looks like you can't change and the UI doesn't update while the video is buffering.  The Shaka Live Stream seems to buffer a lot so you can try changing while it is buffering.

**Comment by joeyparrish** [comment]
I see the same behavior on ChromeOS as you described in desktop Safari.

I think this is because playback hasn't started, so there has not been a rate event for the UI to use.  Once the thing buffers, it goes correctly to 1x.

We should default the UI to 1x or whatever is returned by the Player instance.
