### ISSUE TITLE
widevine is shit

### ISSUE THREAD

**Issue by microsoftceo2** [google/shaka-player#2529]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
3.0

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `master`?**
yes

**Are you using the demo app or your own custom app?**
demo app

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
chrome, nexus 6, android

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

https://bitmovin-a.akamaihd.net/content/art-of-motion_drm/mpds/11331.mpd

**What did you do?**

why u revoke nexus 6 ?? give keybox to me now .  nvidia shield . 
i am from india my name is ramjeet widevin is shit .!!

**What did you expect to happen?**
get amazon prime sunnxt key

**What actually happened?**

nexus revoked :(.

**Comment by spookyahell** [comment]
You - the person creating this issue @microsoftceo2 is shit btw - not widevine or the player, not even hiding the fact that you're using decryption keys illegally. Shame. It's because of people like you that real device owners and users can't use their devices as expected anymore.

**Comment by joeyparrish** [comment]
This is not Widevine.  This is an open source video player.  You can contact Widevine here to share your complaints: https://www.widevine.com/contact

However, this thread is both off-topic and against our [Code of Conduct](https://github.com/google/shaka-player/blob/master/CODE_OF_CONDUCT.md).

In case you haven't read it, here's a relevant snippet, with **bold** added for emphasis:

> ## Our Standards
> 
> Examples of **behavior that contributes to creating a positive environment**
include:
> 
> *   **Using welcoming and inclusive language**
> *   **Being respectful** of differing viewpoints and experiences
> *   Gracefully accepting constructive criticism
> *   Focusing on what is best for the community
> *   Showing empathy towards other community members
> 
> Examples of **unacceptable behavior** by participants include:
> 
> *   The use of sexualized language or imagery and unwelcome sexual attention or
>     advances
> *   **Trolling, insulting/derogatory comments, and personal or political attacks**
> *   Public or private harassment
> *   Publishing others' private information, such as a physical or electronic
>     address, without explicit permission
> *   **Other conduct which could reasonably be considered inappropriate in a
>     professional setting**

@spookyahell, please refrain from name-calling, even if you feel the OP was out of line.

@microsoftceo2, please do not post something like this again.  This is your warning.  You are welcome in this community if you will follow our [Code of Conduct](https://github.com/google/shaka-player/blob/master/CODE_OF_CONDUCT.md), and we would be happy to help you with any issues you may have with Shaka Player itself.  But if you violate our [Code of Conduct](https://github.com/google/shaka-player/blob/master/CODE_OF_CONDUCT.md) again, you will be permanently banned.

Thanks for listening, everyone!
