### ISSUE TITLE
Achieve Low latency with DASH LIVE

### ISSUE THREAD

**Issue by sridhard** [google/shaka-player#2530]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.10

**Please ask your question**
I have checked issues #1287 and #1355.

As per #1287 to achieve low latency streaming one of the highly recommended setting is to use SegmentTemplate with duration. I am using the same with ffmpeg. When doing live streaming loss of frames is a common scenario. Suppose in a live stream af 10min there is a loss of 10 second frames due to internet connectivity. Since we are using SegmentTemplate with duration, the manifest will not indicate these losses and also manifest will never be updated. So the client tries to fetch the latest segment and get 404. After several retries it will get the required segment and will start playing. But in this case the latest segment is 10 seconds behind live edge. 

So in case of frame loss we will always show to the user as he is behind 10s. But the user is actually at live edge and due to 10s media loss client is not able to detect it.

Can you please tell us how to handle this scenario? Loss of media is common and also we should not show to user that he is behind 10s live-edge always.

If we use segment timeline then the issue is there is always a manifest fetch and also we are not able to achieve 2s-3s latency. 

Also when using segment-timeline with duration how can we detect when the live stream is completed?

**Comment by joeyparrish** [comment]
> Can you please tell us how to handle this scenario? Loss of media is common and also we should not show to user that he is behind 10s live-edge always.

I'm not aware of a way to handle this differently in terms of streaming or parsing the manifest, but it sounds like at its core, the issue is really a UI issue.  You want to show the user that they are not behind the live edge.  Is that correct?  Are you using the browser's built-in controls, or our UI, or your own custom controls?

> Also when using segment-timeline with duration how can we detect when the live stream is completed?

As soon as the manifest has a finite presentation duration and is marked as "static" instead of "dynamic", we will consider it VOD and it can end.  So long as the presentation timestamps, period starts, and timestamp offsets do not change during this transition, playback will not be disrupted.

**Comment by sridhard** [comment]
Hi @joeyparrish ,

Yes. When there is loss of media number of segments will be less. So in this case when the user is at liveedge we dont want him to show that is is behind liveedge. We are using our custom controls. But even with shaka UI the issue remains same.

**Comment by joeyparrish** [comment]
The problem from our perspective is that there is no indication in the manifest that anything is missing.  The calculations we perform based on the manifest indicate that we are behind, so we display it as such.  Unless ffmpeg will modify the manifest in some way to indicate the issue, there's nothing we can do to change that in the player.

If seeking is not allowed in your UI, you could just _not_ indicate that the user is behind live, and hide it.

If seeking _is_ allowed in your UI, and you have some way to know how far behind the ideal live edge ffmpeg has gotten, you could adjust things on the front-end.  You could do something like:

```js
const timeline = player.getManifest().presentationTimeline;
const currentDelay = timeline.getDelay();
timeline.setDelay(currentDelay + 30 /* or whatever adjustment you want to make */);
```

But we can't do this for you without some adjustment provided by ffmpeg through the manifest.

Does this makes sense?

**Comment by Userin1974** [comment]
Just a question:"How low can be Low-latency with MPEG DASH if Media Source Extensions (MSE) is used?

**Comment by joeyparrish** [comment]
@Userin1974, I assume you are referring to LL-DASH, which we haven't implemented yet.  Since we haven't implemented it, we don't have any measurements or data for it.

**Comment by Userin1974** [comment]
@joeyparrish : I ask, because I think, I read somewhere that MSE by himself needs at least a buffer of 2 seconds - but this might be wrong.

**Comment by joeyparrish** [comment]
I'm not aware of any such restriction.  DASH and HLS are generally implemented on top of MSE all over the web.  (Safari's native HLS is an exception to this.)

The way it will work is to pipeline a `ReadableStream` object from the network directly to a `SourceBuffer`.  In low-latency mode, the JavaScript application will not have access to the media data, and the browser can parse it without waiting for an entire segment.

**Comment by sridhard** [comment]
@joeyparrish thanks. I think we need to do something in ffmpeg side. Thanks for your help
