### ISSUE TITLE
Setup preferredVariantRole and preferredTextRole in src mode

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#2531]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**  Yes

**Is your feature request related to a problem? Please describe.**

Setup preferredVariantRole and preferredTextRole in src mode

**Describe the solution you'd like**

Take into account https://github.com/google/shaka-player/pull/2506 and expand to the kind in the src mode.

Note: I will send a PR this week with the necessary change.

**Comment by avelad** [comment]
@joeyparrish , I have seen that it has been backported to 2.5.x, Are there any ETA for 2.5.11?

**Comment by joeyparrish** [comment]
I expect to push out v2.5.11 this week.
