### ISSUE TITLE
Unable to hide subtitle in Safari

### ISSUE THREAD

**Issue by JeffrinManovaPrabahar** [google/shaka-player#2536]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v2.5.9-debug

**Please ask your question**

Unable to hide subtitle in safari on onload. Tried setting `player.setTextTrackVisibility(false)` in success response of player.load() and tried setting it in `videoTag.addEventListener('timeupdate')`, but none worked. This happens only in safari and not in chrome. And It is working fine on button click in safari. (used `player.setTextTrackVisibility(false)` to hide subtitle on button click). Any reason for this?

**Comment by joeyparrish** [comment]
It may have something to do with native HLS playback in Safari, as opposed to MediaSource-based playback where we would have access to the subtitles directly.

Can you please provide a playlist URI we can use to reproduce the issue?  Thanks!
