### ISSUE TITLE
Stall detected webkit 

### ISSUE THREAD

**Issue by harishnb** [google/shaka-player#2539]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
2.5.10

**Please ask your question**
We were trying to integrate shaka player on webkit for one of our platform. We were able to play video and audio but it stalls in between and not very stable. I have attached the log, let us know if there is any issue with the safari version and webkit. 
Thank you for your wonderful support .
[shaka-box-debug-1.log](https://github.com/google/shaka-player/files/4550329/shaka-box-debug-1.log)

**Comment by joeyparrish** [comment]
We do support the latest versions of Safari (11+ on desktop and 12+ on iOS), as detailed in our [README](https://github.com/google/shaka-player#platform-and-browser-support-matrix).  If your issue can be reproduced on one of our supported browsers/platforms, then we will do what we can to fix it.

To help you further, we'll need more information.  Specifically, we have a [bug template](https://github.com/google/shaka-player/issues/new?assignees=&labels=&template=bug_report.md&title=) that asks for a lot more details:

**Can you reproduce the issue with our latest release version?**


**Can you reproduce the issue with the latest code from `master`?**


**Are you using the demo app or your own custom app?**


**If custom app, can you reproduce the issue using our demo app?**


**What browser and OS are you using?**


**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**


**What are the manifest and license server URIs?**
_NOTE:
  You can send the URIs to <shaka-player-issues@google.com> instead,
  but please use GitHub and the template for the rest.
  A copy of the manifest text or an attached manifest will **not** be
  enough to reproduce your issue, and we **will** ask you to send a
  URI instead.  You can copy the URI of the demo app to send us the
  exact asset, licence server, and settings you have selected there._


**What did you do?**
_Steps to reproduce the bug_


**What did you expect to happen?**


**What actually happened?**
_A clear and concise description of what the bug is_
_If applicable, you may add screenshots to help explain your problem._
