### ISSUE TITLE
Period flattening fails when audio role is the distinguishing factor

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#2542]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
master as of 2020-04-30

**Can you reproduce the issue with our latest release version?**
No, because v2.5 doesn't have period-flattening

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Demo

**What browser and OS are you using?**
ChromeOS 81 (stable)

**What are the manifest and license server URIs?**
Sent privately by email already.  Teammates can look for subject "Shaka Player - PERIOD_FLATTENING_FAILED with DASH stream".

**What did you do?**
Load the content in the nightly demo.

**What did you expect to happen?**
The content should play.  There should be 3 tracks:

1. language: "qaa", roles: ["main"]
2. language: "es", roles: ["main"]
3. language: "es", roles: ["alternate", "description", "main"]

**What actually happened?**
The output streams look as described above, but there is an error thrown from the flattening algorithm because input stream [2] isn't used.  Even though there is an output track based on it, input track [1] was used instead.

**Comment by joeyparrish** [comment]
We already use role in the period-flattening algorithm, but that part may be broken somehow.  It should be fairly easy to write a regression test for this case.

**Comment by ismena** [comment]
It looks like my fix for #2537 has resolved this issue as well.
Let me deploy it to the nightly, so folks can try it out.

**Comment by ismena** [comment]
Ok, @avelad please try the content on the nightly page now. 
It stalls and buffers a lot, but does play.

I realized that my other fix worked for this case kind of accidentally, and there is still work to properly address period flattening with roles.

However, what we have now is still a step forward.
I'll start looking at the proper fix in the meantime.

**Comment by avelad** [comment]
I just tried it and it works without problem! Thanks @ismena
