### ISSUE TITLE
Embedded subtitles not shown in Chromecast

### ISSUE THREAD

**Issue by wojciech-bilicki-oke** [google/shaka-player#2545]
**Have you read the FAQ and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
The latest one available for Chromecast (2.5.8)

**Can you reproduce the issue with our latest release version?**
Yes, I changed the player version in the cast receiver script and the issue was still observable.

**Can you reproduce the issue with the latest code from master?**
N/A                                                                                                                               

**Are you using the demo app or your own custom app?**
Custom receiver app

**What browser and OS are you using?**
Version 80.0.3987.132 (Official Build) (64-bit) 

**What are the manifest and license server URIs?**
https://ngtoslvideolive.solocoo.tv/ngtcleardash/discovery/manifest.mpd?text=wvtt 
No DRM

**What did you do?**
Loaded the stream into Chromecast Receiver App and tried to load subtitles

**What did you expect to happen?**
I was expecting to see the subtitles on the screen

**What actually happened?**
The stream is being played correctly but instead of subtitles, I see an empty black rectangle in a place where subtitles should be.

**Comment by joeyparrish** [comment]
> **What did you do?**
> Loaded the stream into Chromecast Receiver App and tried to load subtitles

Is this:
  - our Chromecast Receiver App, using Shaka Player directly?  https://github.com/google/shaka-player/tree/master/demo/cast_receiver
  - your own receiver app using Shaka Player directly?  
  - some default receiver provided by CAF?

Thanks!

**Comment by wojciech-bilicki-oke** [comment]
@joeyparrish It's our own custom app built using CAF.

**Comment by joeyparrish** [comment]
We don't control CAF, so unfortunately, this is the wrong forum for CAF support.  Please refer to https://developers.google.com/cast/support#report_issues

Sorry we can't help with that!  Hopefully the Cast team will be able to offer a solution.  As an alternative, you can always try using Shaka Player directly in a custom receiver as we do in our demo.
