### ISSUE TITLE
Skip null TS packets in HLS parser

### ISSUE THREAD

**Issue by Romain-Bernier** [google/shaka-player#2546]
**What version of Shaka Player are you using?**
latest

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `master`?**
yes

**Are you using the demo app or your own custom app?**
demo app

**If custom app, can you reproduce the issue using our demo app?**
yes

**What browser and OS are you using?**
windows 10 & chrome

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**
mpd send to shaka-player-issues@google.com

**What did you do?**
try to play a hls stream

**What did you expect to happen?**
that the stream works

**What actually happened?**
I get the error : HLS_COULD_NOT_PARSE_SEGMENT_START_TIME

**Comment by michellezhuogg** [comment]
I was able to play the content in Chrome on MacOS, however I saw the video gets buffering quite often.

**Comment by Romain-Bernier** [comment]
Hello, thanks for your reply. I still have the error HLS_COULD_NOT_PARSE_SEGMENT_START_TIME with the demo app 2.5.11 uncompiled on chrome Version 81.0.4044.129 (Build officiel) (64 bits) with windows 10 Pro edition 1909 os build 18363.778

**Comment by Romain-Bernier** [comment]
I also have the error HLS_COULD_NOT_PARSE_SEGMENT_START_TIME on chrome with Mac os mojave 10.14.6.
The error seems to be triggered by a packet null at the beggining of the segment.

**Comment by Romain-Bernier** [comment]
Hello,

Thanks for your reply.
I still have the error HLS_COULD_NOT_PARSE_SEGMENT_START_TIME with the demo
app 2.5.11 uncompiled on chrome Version 81.0.4044.129 (Build officiel) (64
bits) with windows 10 Pro edition 1909 os build 18363.778.
I also have the error HLS_COULD_NOT_PARSE_SEGMENT_START_TIME on chrome with
Mac os mojave 10.14.6.
The error seems to be triggered by a packet null at the beggining of the
segment.
Do you have some infos about that ?

Regards,

**Comment by Romain-Bernier** [comment]
When I remove the null packet from the stream it's working.
Is there any reason why shaka does not support null packet at the beginning of the ts segment in hls ?

**Comment by joeyparrish** [comment]
What's a null packet?  A zero-byte segment?  Or a TS packet with no audio or video in it?

**Comment by Romain-Bernier** [comment]
A null packet is a TS packet with a PID 8191 and no audio or video in it. On my stream, each ts segment start with a null packet before packets with data.

The error in shaka is triggered inside the file hlsparser.js in getStartTimeFromTsSegment by :          
let flagsAndPacketId = reader.readUint16();
let hasPesPacket = flagsAndPacketId & 0x4000;
if (!hasPesPacket) {fail();}

**Comment by joeyparrish** [comment]
What is the length of the segment with the null packet according to the playlist?  Does it occupy "space" in the timeline?  Is there another packet in the segment with real content?

**Comment by Romain-Bernier** [comment]
It's a 6 seconds duration segment with many other packets with real content.

**Comment by joeyparrish** [comment]
Great, thanks for the details.  I'll label this as an enhancement to skip over these null TS packets when parsing the timestamp, and I'll update the title accordingly.  Thanks!

**Comment by Romain-Bernier** [comment]
Thanks you for adding this to the enhancement list.

**Comment by joeyparrish** [comment]
No problem!  We want to do the best job we can, and we were honestly unaware of this detail of the TS format.
