### ISSUE TITLE
Which version of javascript ES version used mainly

### ISSUE THREAD

**Issue by harishnb** [google/shaka-player#2547]
I would like to know which version of javascript is used in shaka player code ES6,7,8,9?

**Comment by theodab** [comment]
We currently use features up to ES9. However, Shaka Player does use the [Babel compiler](https://babeljs.io/docs/en/) to, in compiled mode, turn ES6 and above code into ES5 equivalents, for backwards compatibility.

**Comment by joeyparrish** [comment]
Babel is actually only used when running tests.  The [Closure Compiler](https://github.com/google/closure-compiler) is used to compile the code into an ES3-compatible syntax, and provides polyfills for ES6+ features.

Shaka Player requires certain features which may not be available on older browsers, but you should at least be able to load the library and call `shaka.Player.isBrowserSupported()` on any browser.  If the browser is missing some required feature, `isBrowserSupported()` will return `false` and you can fall back to some other means or provide an appropriate error message to the user.

You can see our full support matrix here: https://github.com/google/shaka-player/blob/master/README.md#platform-and-browser-support-matrix

And you can see a detailed report of what is supported in any given browser by navigating to this page: https://shaka-player-demo.appspot.com/support.html

We have plans to end IE 11 support in v2.7, and our next planned release is v2.6.

Does this help?

**Comment by harishnb** [comment]
Thank you so much for the clarification. It does help :-)
