### ISSUE TITLE
How to display controls all the time even in full screen

### ISSUE THREAD

**Issue by harishnb** [google/shaka-player#2550]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.10

**Please ask your question**
I want to keep displaying the seek bar, time and duration all the time. Kindly let me know how to do that. On the embedded device at present there is no mouse hover or other events and want to display the default controls.

**Comment by joeyparrish** [comment]
This is easily controlled via CSS.  Try this:

```css
.shaka-controls-container {
  opacity: 1;
}
```

That will override our default styles.  Does this help?

**Comment by harishnb** [comment]
Thank you so much @joeyparrish Can you please elaborate  more . I tried adding css but it did not work.
I used the demo code: https://shaka-player-demo.appspot.com/docs/api/tutorial-basic-usage.html
in the HTML added a tag 
<link rel="stylesheet" type="text/css" href="mystyle.css">

and in mystyle.css
.shaka-controls-container {
  opacity: 1;
}

**Comment by theodab** [comment]
The CSS that @joeyparrish gave you changes the styles on our custom UI. That tutorial you linked, though, is telling you just how to set up the player by itself, without the UI. If you want to use our custom UI, you can follow [the UI tutorial](https://shaka-player-demo.appspot.com/docs/api/tutorial-ui.html).

**Comment by joeyparrish** [comment]
That's right.  With the browser's built-in controls (using the `controls` attribute on the video element), we have no control over styling or behavior.
