### ISSUE TITLE
Nightly Demo deployment broken

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#2551]
Url: https://nightly-dot-shaka-player-demo.appspot.com/demo/#build=uncompiled

![Captura de pantalla 2020-05-05 a las 16 43 25](https://user-images.githubusercontent.com/8983024/81079270-a54f7f80-8eef-11ea-913c-b00a26f1af23.png)

userAgent:
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15`

**Comment by joeyparrish** [comment]
Commit 1076b784 changed our dependency on Google's Closure Library, and our appspot deployment script was not updated to reflect this.  The nightly is broken in all browsers.

**Comment by joeyparrish** [comment]
The deployment of the nightly build has now been fixed.  Sorry for the inconvenience!

**Comment by avelad** [comment]
Thanks!
