### ISSUE TITLE
Shaka player not recognizing dash ec3/dtse audio tracks

### ISSUE THREAD

**Issue by bcupac** [google/shaka-player#2552]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**

    2.5.10
**Can you reproduce the issue with our latest release version?**
   yes

**Can you reproduce the issue with the latest code from `master`?**
  yes

**Are you using the demo app or your own custom app?**
   custom

**If custom app, can you reproduce the issue using our demo app?**
   yes

**What browser and OS are you using?**
   chrome/macOS

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What did you do?**

  loaded our .mpd file
**What did you expect to happen?**
   shaka player should recognise 6 channel audio

**What actually happened?**
   no 6 channel audio track under player.getVariantTracks()

So, we're trying to create an audio track UI switcher, where the user will be able to select,
6channel/2channel audio via a drop down menu. 

We have these 2 AdaptationSets for 6channel audio:
```
<AdaptationSet group="1" contentType="audio" lang="en" segmentAlignment="true" subsegmentAlignment="true" subsegmentStartsWithSAP="1" audioSamplingRate="48000" mimeType="audio/mp4" codecs="ec-3" startWithSAP="1">
    <AudioChannelConfiguration schemeIdUri="urn:dolby:dash:audio_channel_configuration:2011" 
      value="F801"> </AudioChannelConfiguration>
    <Role schemeIdUri="urn:mpeg:dash:role:2011" value="main"/>
    <Representation id="audio_eng_2=384000" bandwidth="384000">
        <BaseURL>audio-3-eng.mp4</BaseURL>
        <SegmentBase timescale="48000" indexRangeExact="true" indexRange="1464-56419">
            <Initialization range="0-1463"/>
        </SegmentBase>
    </Representation>
</AdaptationSet>
```
```
        <AdaptationSet group="1" contentType="audio" lang="en" segmentAlignment="true" subsegmentAlignment="true" subsegmentStartsWithSAP="1" audioSamplingRate="48000" mimeType="audio/mp4" codecs="dtse" startWithSAP="1">
            <AudioChannelConfiguration schemeIdUri="urn:dts:dash:audio_channel_configuration:2012" value="6"> </AudioChannelConfiguration>
                <Role schemeIdUri="urn:mpeg:dash:role:2011" value="main"/>
                    <Representation id="audio_eng_1=384000" bandwidth="384000">
                        <BaseURL>audio-2-eng.mp4</BaseURL>
                        <SegmentBase timescale="48000" indexRangeExact="true" indexRange="1479-56434">
                            <Initialization range="0-1478"/>
                        </SegmentBase>
                    </Representation>
        </AdaptationSet>
```
but player.getVariantTracks() is only showing channelsCount 2 on all tracks.

**Comment by joeyparrish** [comment]
Are you playing on a device that supports the audio codec?  EC3 is not generally supported in desktop browsers, and so EC3 tracks wouldn't show up in the track list.  You can see a detailed dump of what your browser supports by navigating to https://shaka-player-demo.appspot.com/support.html

You left blank the question "What are the manifest and license server URIs?"  We ask that question because if there is an actual bug, without a way to try your content, we very likely can't fix it.  If it's not a matter of codec support in the browser as suggested above, we will need you to send a manifest URI before we can do any debugging.

Does this help?

**Comment by bcupac** [comment]
@joeyparrish thanks for your insights about desktop browser codec support. We tried on a TV device and it's working fine. Closing Issue.
