### ISSUE TITLE
Track selection breaks when tracks share the same language

### ISSUE THREAD

**Issue by saringer** [google/shaka-player#2553]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.9

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Custom

**If custom app, can you reproduce the issue using our demo app?**

The demo app doesn't distinguish tracks with the same language

**What browser and OS are you using?**
OS: Mac OS Catalina 10.15.4
Browser: Chrome 81.0.4044.138, Safari 13.1

**What are the manifest and license server URIs?**
Sent via Email 

**What did you do?**

1. calling `getTextTracks()` and selecting the text track with the unique label  `forced_subs_de`
2. passing the selected track to the player via `selectTextTrack(track)`
3. calling `setTextTrackVisibility(true)`

**What did you expect to happen?**

Only forced subtitles to be displayed for Chrome (DASH) and Safari (HLS)

**What actually happened?**

`The example movie provided by the manifests has a scene using forced subtitles at 2m07s.`

On Safari 

- [ ] the selected track is properly displayed.

On Chrome

- [ ] The player doesn't display the selected track but instead the track providing full subtitles (which includes forced subtitles). These subtitles are available in the same language as the forced subtitles and distinguished by the unique label `subs_de`. When calling `getTextTracks()` the correct track is shown as being set `active:true`, 
 ![Screenshot 2020-05-06 at 16 28 38](https://user-images.githubusercontent.com/7473273/81189961-84526180-8fb7-11ea-8ad3-f38b47ec4180.png)
 but instead the other track with `active:false` is displayed.

**Comment by joeyparrish** [comment]
I tried this with the DASH content URL you provided via email, and I am unable to reproduce the issue in either v2.5.9, v2.5.11 (latest) or the [nightly build from master](https://nightly-dot-shaka-player-demo.appspot.com/demo/).

This is the exact code I'm running in the JS debugger:

```js
player = video.ui.getControls().getLocalPlayer();
player.setTextTrackVisibility(true);

tracks = player.getTextTracks();

player.selectTextTrack(tracks[0]);
console.log(player.getTextTracks().map(t => t.label + ': ' + t.active));

player.selectTextTrack(tracks[1]);
console.log(player.getTextTracks().map(t => t.label + ': ' + t.active));
```

The console output is:

```
(2) ["subs_de: true", "forced_subs_de: false"]
(2) ["subs_de: false", "forced_subs_de: true"]
```

Can you try again and make sure?

Vielen Dank!

**Comment by saringer** [comment]
Hi Joey, thank you for your quick response.
I receive the same output when running your code example.

What I didn't mention in my previous post is that this text track change is triggered right after changing the language via `selectVariantsByLabel()`.

So on every language change, I enable forced subtitles for the respective language if they exist (if there are no full subtitles enabled at this point). 

I think the issue might be caused by my handling of `setTextTrackVisibility`.
When starting the movie, I check for forced subtitles for the default language (german) and 
set the status `setTextTrackVisibility(true)`.

Then I change the language to english, can't find any forced subtitles and set `setTextTrackVisbility(false)`.

Now I change the language back to german, select the existing forced  subtitles and set `setTextTrackVisbility(true)`. At this point when I check `getTextTracks()` the forced subtitles are shown as active, but the full subtitles are displayed.

In the provided screenshot I reproduced my issue in the following order
1. initially only forced subtitles were shown and they set as active 
2. `isTextTrackVisible` is set to true
3. `setTextTrackVisbility(true)`
4. `setTextTrackVisbility(false)`
5. `setTextTrackVisbility(true)`
6. forced subs are still active, but suddenly full subs are displayed
![Screenshot 2020-05-10 at 03 50 02](https://user-images.githubusercontent.com/7473273/81489126-606e7480-9272-11ea-9414-8c6243b1eae9.png)

**Comment by joeyparrish** [comment]
Okay, I'll take another look on Monday with the steps you detailed.  My gut feeling is that this could be a race condition of some kind.

Can you try with the latest code in `master` or the [nightly build of the demo](https://nightly-dot-shaka-player-demo.appspot.com/demo/)?  We've refactored a lot in the last couple months, and if it turns out to be a race condition, it would be interesting to know if it's one that's already solved for v2.6.

**Comment by saringer** [comment]
Sure. I'll test it with the latest code later in the day when I'm home and let you know.

**Comment by joeyparrish** [comment]
I'm able to reproduce the issue on the nightly build with the following code which seems to mimic your application logic.

```js
player = video.ui.getControls().getLocalPlayer();

function changeLanguage(lang) {
    player.selectAudioLanguage(lang);
    const forcedText = player.getTextTracks().find(t => t.label == 'forced_subs_' + lang);
    if (forcedText) {
        console.log('SELECTING TRACK', forcedText);
        player.selectTextTrack(forcedText);
        console.log('ACTIVE TRACK AFTER SELECT', player.getTextTracks().find(t=>t.active));
        player.setTextTrackVisibility(true);
        console.log('ACTIVE TRACK AFTER VISIBLE', player.getTextTracks().find(t=>t.active));
    }
}

changeLanguage('de');
```

The logs from this seem to show that setTextTrackVisibility(true) inexplicably changes the active track.  We'll look into it.  Thanks!

**Comment by joeyparrish** [comment]
The issue has nothing to do with timing, it turns out.  The critical pieces are:

1. The config field `streaming.alwaysStreamText` is `false` (the default)
2. Text visibility is currently `false`
3. Call `selectTextTrack()`
4. Call `setTextTrackVisibility(true)`

`setTextTrackVisibility()` will, if `alwaysStreamText` is false, choose a new track based on the user preferences and current language state.  This is based on the idea that if visibility is `false`, we shouldn't be streaming anything, so we assume you haven't chosen anything.  This is the root of the problem.

If you only have one text track per language, this choice will wind up being the same as what you chose in `selectTextTrack()`.  This is how we did not discover the bug sooner.

We should not choose another track in `setTextTrackVisibility()` if one has already been chosen by the application.

**Comment by joeyparrish** [comment]
This bug appears to be very old.  It has been there in one form or another essentially since the feature was added in Nov 2017.  (156dd3c624e2037fc1e8bc25980533c8717cca00)
