### ISSUE TITLE
Installing polyfill on webos 3 breaks

### ISSUE THREAD

**Issue by aleksandre12** [google/shaka-player#2554]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
2.5.11

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `master`?**
yes

**Are you using the demo app or your own custom app?**
custom app

**If custom app, can you reproduce the issue using our demo app?**
No. It sometimes work, but sometimes not.

**What browser and OS are you using?**
LG Webos 3.

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
LG webOS 3.model: 49UH610V-ZB: firmware: 05.30.85

**What are the manifest and license server URIs?**
https://amediateka.silktv.ge/media//800000548/output.mpd
https://amediateka.silktv.ge/wv/

**What did you do?**

I turned on player and it doesn't play.

**What did you expect to happen?**
I want it to play.

**What actually happened?**
Page loads, and shaka starts to install all polyfills but it throws log:
"McEncryptionSchemePolyfill: MediaCapabilities not found
EmeEncryptionSchemePolyfill: No native encryptionScheme support found. Patching encryptionScheme support." After this i'm trying to play content. It loads some data video and audio mp4 files but it doesn't start playing. After some time it throws error with code 3016 and severity 2. I tried to recover from this error but it throws same error.

**Comment by joeyparrish** [comment]
We don't have a WebOS device we can test with, so WebOS is not an officially-supported platform at this time.  Can you help us debug it by trying a few things for us?

Those EME polyfill log messages look completely normal to me, FWIW.  They are just reporting what the polyfill is doing during setup.  So I don't have any reason to think it's the EME polyfill that's the issue

Please try with a few different versions of Shaka to help identify if this is a regression.  You can use https://index-dot-shaka-player-demo.appspot.com/ to discover the URLs of past releases, but here are a few specific ones I'd like you to try for us:

 - Nightly (preview of upcoming v2.6 release):
    https://nightly-dot-shaka-player-demo.appspot.com/
 - v2.5.11 (latest release):
    https://v2-5-11-dot-shaka-player-demo.appspot.com/
 - v2.5.10 (predates a recent WebOS-related PR):
    https://v2-5-10-dot-shaka-player-demo.appspot.com/
 - v2.5.6 (predates EME polyfill):
    https://v2-5-6-dot-shaka-player-demo.appspot.com/
 - v2.4.7 (last release from previous release branch):
    https://v2-4-7-dot-shaka-player-demo.appspot.com/

Thanks!
