### ISSUE TITLE
Control partial segment loading

### ISSUE THREAD

**Issue by NoChance777** [google/shaka-player#2556]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Is your feature request related to a problem? Please describe.**
For HLS sources, Shaka Player does partial segment loading, this forces XMLHttpRequest to do OPTIONS requests. They could cause failing requests if a streaming host doesn't support such type of requests, it makes a video loading process much longer, even if we set the minimum amount of retry attempts to 1 (example: `player.configure({ manifest: { retryParameters: { maxAttempts: 1 } } });` ). 

**Describe the solution you'd like**
Deep in the code, you already have an option to fallback to full segment loading, but it's not exposed to the outside, see [fetchPartialSegment_](https://github.com/google/shaka-player/blob/285cc73b1d8d24a0b5929f7b255243f79e2678da/lib/hls/hls_parser.js#L1640)

Could you expose a parameter that will allow controlling the described behavior?

**Comment by joeyparrish** [comment]
So, to be clear, you'd like a configuration field to skip the partial segment and always load the entire thing?

**Comment by NoChance777** [comment]
Correct. Actually, our video host backend can vary, so we need more flexibility

**Comment by joeyparrish** [comment]
That seems completely reasonable.  We can add a configuration to the `manifest.hls.` config space.

Would you be interested in submitting a PR for this?

**Comment by NoChance777** [comment]
Yes, I will be happy to help and start working on it soon
