### ISSUE TITLE
Can't choose a point in the seekbar on phone in DASH streaming

### ISSUE THREAD

**Issue by Kotekczu** [google/shaka-player#2558]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes.

**What version of Shaka Player are you using?**
2.5.11.

**Can you reproduce the issue with our latest release version?**
Yes.

**Can you reproduce the issue with the latest code from `master`?**
Yes.

**Are you using the demo app or your own custom app?**
Demo.

**If custom app, can you reproduce the issue using our demo app?**
.

**What browser and OS are you using?**
Chrome on Android phone.

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
.

**What are the manifest and license server URIs?**
https://livesim.dashif.org/livesim/utc_head/testpic_2s/Manifest.mpd

**What did you do?**
1. Open the demo app on your phone.
2. Play "Live sim (2s segments)" DASH live stream.
3. Click on a point in the seekbar to try to go back in time.

**What did you expect to happen?**
The player should go to that exactly point in the live streaming.

**What actually happened?**
The player jumps to the limit, to the left.

**Comment by joeyparrish** [comment]
I back-tested this on several versions of Shaka Player.  I can confirm the bug using Chrome on Android with:
 - nightly (2020-05-11)
 - v2.5.11
 - v2.5.10
 - v2.5.8
 - v2.5.4

But the bug is not present in:
 - v2.5.3
 - v2.5.1

**Comment by joeyparrish** [comment]
This was broken by PR #2036 to fix #1918.  I'm tempted to revert #2036, but I don't have an iOS device available to work on an alternate fix for #1918.

**Comment by joeyparrish** [comment]
After playing around with it on Android and in the device emulator in Chrome, it seems that the calculations in PR #2036 are only correct when the seek bar minimum is 0.  This is not the case for this live stream (and most others).  So instead of reverting the change and re-fixing iOS, I think we can just correct the calculations.
