### ISSUE TITLE
Buffering config for CAF

### ISSUE THREAD

**Issue by krackjack234** [google/shaka-player#2559]
Hi,

We are trying to set autoResumeNumberOfSegments in google cast manager but it throws a warning saying _"AutoResumeNumberOfSegments is not supported for Shakaplayer. Its value will be ignored."_

Is there any other way we can set the initial buffer size before casting starts?

Any pointers will be really helpful.

**Comment by joeyparrish** [comment]
`autoResumeNumberOfSegments` is not part of our configuration system, and to my knowledge, never has been.  Where did you get that name?  What are you trying to accomplish with that config?

**Comment by krackjack234** [comment]
Hi,

This is coming as a warning when we try to set autoResumeNumberofSegments in playerConfig in our custom cast receiver (ref: https://developers.google.com/cast/docs/reference/caf_receiver/cast.framework.PlaybackConfig#autoResumeNumberOfSegments). 

If this is not supported by shaka player which is used during casting, then is there anyway we can set the initial buffer config of the cast player? We want to set the number of seconds/segments, the player should buffer before it can start/resume playback.

**Comment by joeyparrish** [comment]
The document you referenced is about the Cast Application Framework, not Shaka Player.  We are not responsible for CAF.  For CAF support, please see https://developers.google.com/cast/support#report_issues

If you use Shaka Player directly in some other context, we have a similar configuration called `streaming.rebufferingGoal`, which is expressed in seconds (not segments) and is described in this tutorial: https://shaka-player-demo.appspot.com/docs/api/tutorial-network-and-buffering-config.html

Does this help?

**Comment by krackjack234** [comment]
Thanks this helps!!

**Comment by joeyparrish** [comment]
Glad to hear it!  If you need anything related to direct use of Shaka Player, please don't hesitate to file another issue.
