### ISSUE TITLE
The way of loading mux.js

### ISSUE THREAD

**Issue by NoChance777** [google/shaka-player#2562]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Is your feature request related to a problem? Please describe.**
Shaka Player requires Mux.js for some features. Unfortunately, it needs the mux.js library being globally on `window`. It would be better if Shaka supports passing it via options API, in the Player constructor, or via `.configure` or otherwise. In some cases, we can come across version conflicts on third-party integrations and, at least pollute the global namespace. Currently supported method of including the library doesn't correspond to contemporary web dev standards (ReactJS, Vue, etc)

**Describe the solution you'd like**
The most preferable way is passing the mux library with options:
```javascript
import muxjs from 'mux.js';

const player = new Player(videoElement, (playerInstance) => { playerInstance.deps.muxjs = muxjs} );
// ...or...
player.configure({ deps: { muxjs } });
```
and then inject in a constructor whereas it needs, for example:
```javascript
shaka.media.MuxJSClosedCaptionParser = class {
  constructor(muxjs) {
    /** @private {muxjs.mp4.CaptionParser} */
    this.muxCaptionParser_ = new muxjs.mp4.CaptionParser();

```

**Comment by joeyparrish** [comment]
That seems like a reasonable request.  Are you interested in contributing a PR for this?

**Comment by NoChance777** [comment]
Yes, I will be happy to help and start working on it soon

**Comment by NoChance777** [comment]
Hey, guys! Any updates on https://github.com/google/shaka-player/pull/2683 ?

**Comment by joeyparrish** [comment]
Many of us have been on holiday in the US this past week.  Thanks for your patience!

**Comment by NoChance777** [comment]
Hello again! I hope you are all safe and sound! Have time for the next round?
