### ISSUE TITLE
shaka.log undefined on 2.5.11

### ISSUE THREAD

**Issue by maimar-sw** [google/shaka-player#2565]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.11

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
No

**Are you using the demo app or your own custom app?**
Custom app

**If custom app, can you reproduce the issue using our demo app?**
No

**What browser and OS are you using?**
Chrome 81.0.4044.138 / Windows 10.0.18363

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**

N/A

**What did you do?**

I was using `shaka.log` on 2.5.10 loading `shaka-player.compiled.debug.js`, bumped the version to 2.5.11 and `shaka.log` is now `undefined`.

**What did you expect to happen?**
Logging keeps working normally.

**What actually happened?**

Logging isn't working anymore.

**Comment by TheModMaker** [comment]
This is caused by a44ac03f where we use the wrapper in debug builds.  Since log isn't exported, it doesn't appear anymore.
