### ISSUE TITLE
TTML Captions for Live stream not rendering on Chromecast

### ISSUE THREAD

**Issue by stuartflanagan** [google/shaka-player#2567]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
Chromecast so hard to tell.

**Can you reproduce the issue with our latest release version?**
On Chromecast I can

**Can you reproduce the issue with the latest code from `master`?**
No

**Are you using the demo app or your own custom app?**
Own custom Chromecast receiver.

**If custom app, can you reproduce the issue using our demo app?**
N/A

**What browser and OS are you using?**
Chromecast

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What did you do?**

Connected to chromecast and enabled Closed Caption for a live MPEDASH stream

**What did you expect to happen?**
Captions to be rendered

**What actually happened?**

The issue is in our live TTML captions not being displayed on the chromecast device.
We have no issues with our VOD captions but they are served via WEBVTT as a separate file.
Live captions did work before.
Currently when enabling live captions a small background appears and shows and hides whene captions should appear but no text is being rendered.

**Comment by joeyparrish** [comment]
> **What version of Shaka Player are you using?**
> Chromecast so hard to tell.

If you aren't using Shaka Player directly, this is the wrong place to report bugs.  This team is not responsible for the Cast Application Framework.  CAF issues should be reported here: https://developers.google.com/cast/support#report_issues
