### ISSUE TITLE
Player seems to switch to higher resolution adaptation set despite error from license server

### ISSUE THREAD

**Issue by btandy** [google/shaka-player#2568]
I have a manifest with four adaptation sets: AUDIO, and three different resolutions of the

 source video SD, HD, UHD1. Each pssh contains the key id corresponding to the key used to encrypt that audio/video file.

On playback, I see license requests for all of the pssh. If I send back licenses for just the AUDIO and SD pssh, and reject the HD, and UHD1 requests with an error, I would expect the player to stay on the adaptation set with the SD file, but instead it appears to try to play one of the files for which it does not have a key.

Is this expected behavior? If so, does that mean the application should monitor the license response for errors and add constraints to the abr manager to keep it from switching to the unauthorized (but present) adaptation sets?

**Comment by joeyparrish** [comment]
It will be hard to say what the problem is, since you didn't [fill our our issue template](https://github.com/google/shaka-player/issues/new?assignees=&labels=&template=bug_report.md&title=) with all the information we require to investigate issues.

However, here's a guess: does your manifest specify key IDs?  If not, we will have no way to know what can and can't be played.  Only key IDs in a manifest allows us to match AdaptationSets to the keys provided in the license.

**Comment by btandy** [comment]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** 
Yes

**What version of Shaka Player are you using?**
 v2.5.11-master-18-gc998ce27

**Can you reproduce the issue with our latest release version?**


**Can you reproduce the issue with the latest code from `master`?**


**Are you using the demo app or your own custom app?**
The demo app, lightly modified to add a header on license request.

**If custom app, can you reproduce the issue using our demo app?**


**What browser and OS are you using?**
Firefox/MacOS 10.14
Edge/Windows 10
Android/Chrome



**What are the manifest and license server URIs?**

Everything is running locally and is not publicly available. I'll work on getting it hosted on a service if nothing jumps out at you.

**What did you do?**

Pass in manifest url to player, and start playing.
Playback stops after first 12s (clear) chunk

**What did you expect to happen?**
I expected to see the SD stream continue playing, as the license requests for the higher resolution key were rejected with a 403 error.


**What actually happened?**


If authorized for SD and AUDIO keys, the playback stops after the 12s clear chunk at SD resolution. I believe that this is a result of the player moving to a higher resolution without having the key. (This is running on an internal network, where bandwidth is unrestricted). This happens despite the license request for the HD key is rejected.

If authorized for HD resolution, the asset (AUDIO, SD, and HD) happily plays.
If I edit the manifest and leave only the SD and AUDIO streams, then it also plays when authorized for at least SD.

Manifest snippet for SD:
    <AdaptationSet contentType="video" frameRate="60000/1001" height="480" id="0" par="16:9" subsegmentAlignment="true" width="854">
      <ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc" cenc:default_KID="0e3129f5-70b6-5195-6bb6-a599569a58c1" />
      <ContentProtection schemeIdUri="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed">
        <cenc:pssh>AAAAOXBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAABkSEA4xKfVwtlGVa7almVaaWMEiBXN1c2hp</cenc:pssh>
      </ContentProtection>

The PSSH:
pssh-box.py --human --from-base64 AAAAOXBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAABkSEA4xKfVwtlGVa7almVaaWMEiBXN1c2hp
PSSH Box v0
  System ID: Widevine edef8ba9-79d6-4ace-a3c8-27dcd51d21ed
  PSSH Data (size: 25):
    Widevine Data:
      Key IDs (1):
        0e3129f5-70b6-5195-6bb6-a599569a58c1
      Content ID: 7375736869

Message to WV License Server:
{
  "payload": "CAEStA8SQQo/ChkSEA4xKfVwtlGVa7almVaaWMEiBXN1c2hpEAEaIDNFMzRCMjM5NUYzNjdFNjAzQjAwMDAwMDAwMDAwMDAwGAEghMDy9QUwFTi78JS1C0LeDgoSc3RhZ2luZy5nb29nbGUuY29tEhAocDRUwAj2Nhit50Q9tsTIGqAMWYEEUYImzdLvCKWG3tuc64TVlj5sCKOuQ2D0crT7pqTo/zvW7J5mFPOKsUK6F8vvGMysd1gkQ/gRKxtJqhDskmQ2e4IdHR2VDb02lCi8cXIhv+Fpzp8/Jb/whVBZ+tIpEIdncov2VIHYbgculP07+jfPLCe0YRvr0Oxn4+9bSMldky9EB8QKxpDK6/0Z6xqpMQaT2t0DjtAsm0E+R2/Vsgy4cfyNvWbEA1udcmHPrUv5kFb4eE/GcEmlP/WwEaSMzC+QOtt/BU3tL6lie4NFAGmRzD2Zaf9VDisiSDjpnM8vdq0aVzTktwmlABvxJmOYUDOoIOO1Le40uDvpfMG/rWFQr4he34oe/MIniD2htphcH7ogL304ziPuQP7ZAKbG0ygKMP9Q3qAsekmK6gmodauPkTBMsx51erBSOGXPSOQAxEV01K8i86RAJWRsdlslG2kfCcwwQKT4RuiqBuQfvMBZpq7YnkApqoT1GAOWJ9nQIXAgzqB/tUnsnrN0qexdK5ZSGh9HO6VxNpjOVOB3MX3QWZ8deKmJ2LohyQ+CSAeICgGfWpDmwqogG9QHrzG+3/GxWGAXxH0xpSHS5juYCSrpKvtSqjm8JXEBPBUonEtpm6W2+v2lgnDusT+mY/a6M2aU2ztaaQsfU6xp1eMgUcuniU4IT2wuZXZx9eQ6aMJruFFqhKRv2+nx1FbhVkwpIBf5W9Eygwe3cq/3kZzBq+TvtD8UAdGaHMnn1K5GQzibMyQv27Fz/ZOuIg6+HL6NQ5gUxamkk9A1BMxTwxCErgxxh6dMx7zv6PWsIDSUg2QPi9iL+Tm7I2Tf9q4Nmaitwb07kVdvnc0PvqxNBdNx2khLzERixGgi6J7BQoNrll8A5rZKf+jWzsK1EusjmPGyQ1uOSDkiXtFd0iS71rGzRfMkTmbzAr7THrhqHW85RIo2rfwe3eQ2CViM0tY5ikzxmCiWhbPIVkKTqcoYKEmqHeMTCSZvLrGFW3myKt0TwCHOglJVTLjS5hQeLHHXzUo1nzkSTDvHWorjNU7fZrvb4O3PGeLICJsI+7L+nXLTER60JPbiMBjSOtg2BzzO2noTytWQld6w33uK6mPZzX8pt/SBavp+ChUr0l5k+c9QAwnD/L1t1+yOfyGRIhdEJSnQfqBPrBP7R/a+1FBNaJsGBwu8gvgUIVork5BMbf6hoav61I9jZIN7uHcJrfb3dyhvnuCVYL0TGV5oTN/xo/itSmMAc9LHHjrPYtwWhq6ibW7oUIU6FAMubuHhh+vLh6Iyz3cco1SaahPod0CXSbJ+F8z1VsPv0bOTfD2WvBpjyovl9HdaGM5t68wuWtRckojRcDXuCCGoN1rQ0upOl4y/mEnOamDAV+Z1J/Ep5w29w2x6e21sQsdQyx6gQC3v2hRfGjirmUb4L1zBLLSh8Fc5DqnJYzB0GFmC+CEfNPXRygOcXuafKpcNrv5jU4Gk6Wm1QwxUuEcChtuo5mJGmvfQ3ZyPWdtcjIw4W92QeyRhQ29U1wFz3vx9hP90bYRdTMzQUW2KcycuEmLyMig6D1GOjFt0Fmy4+aLvc0fd6F8hmugq2YeUWsfom0Q1XRHf8urOovcqtX6yOzHlw105kmKn3RpPYVqXTT7uL9XDnLuCJmYOczzTO7WRIFYlrxUEQ8V5SOS0zSXTlxhV2y7JtDDCFdiMRZA/Y2S5np2gHRPlTkkkCTGau0yFNbYUuDn8WFQpH6HWWIyXAjTtCj+fB6kESjJpl6udKsaitJBwJPvje4M/N7JGH0qUEmc5cupkYe1K+uLm2gyCaLKkDdbHT5Bm4gnVI0FpO1Pwelgqevz4yPKXPfQTWLCZK1IxW2n8gFDt1Jjq6G0zzmc9ZktZzCQNFWkbWrZ/Oa8LZM9kxUsklPkpGSLIdNC577kgDiK6rOEj614EfkH9FCq4if71hD9C2/ISJNo7fWLDaZYNhIURf38Fyv7guk+8C/5+D6H6vo4bRZKrbKXzVgLN2mMkbuC0u5x+SUJElLjnbTmI6oObG+YVIrWuWvdpABk0D3iDHLGdCQZ1O+2H7ck5aCTmmGRNmeF6zLOlt6UZR85bLx4U6yciEMxC0FR6TEtpNIUH7v+fCNcqgAJv8MK1dG7UmvAJ/kH2IOd96hKs88eaUqq4ec4x7Eqr1U94QSvdhLgTFfnFZ744nDD9n08sekQOyIkBY0nH8NQyYwMIPN9p69IE3a8UvlfsDXu3urmgfroJqWPCBpHPgApK9TuhGBRTZnR+ULKOzgUM70a0+OlNXF8iK5WPFPf6nqpB/s6yXJTrjkdYa9bHGGUz1eORXIwL4neUNHYBf2Kpof2qzeAvp7zd9RiB4I4oF/aA2ctDB6PJo71gUXBsvI+hLE2xvWGHA7lC2ojCczgYCDPmRJbb78lr+YwrYgXPfKXsVL7dzjTyO+jACb7AK40SsiStB4JggZ4YY2w0vaFTGoACV9664pK35zOBw1FOWQPREu4A31v21xde6AgGU7rZrCUulRBe4J1mcH6OM+JOxKnfb3z6SL4FHhuuTGl+YMpE9ZOhdnUuZ+7u5K5U4GxKzzmGvRoon1+Irr8VOxM8DtpURLnO2PK7QnJ83AWQH1p4I8pnhfN1kaD8Y7dvbR71JZKWvqIuzDuMnyCdg9ZpYpxiizHoT3eNG3i/2ZZMov7/Ste8zi3ZtCtYrG6kOyTkUgp8vEy91x2Wp5bZ8WkLwxbI407gmBag8NgR2tVURRwQN7OAdFIKdIybnv9TAyji5gjCpnlc8KAkeYnwaQnEyk/Q8fwpnHUsT4sM0XHKVtzLgA==",
  "content_id": "MjAxNV90ZWFycw==",
  "provider": "<some_provider>",
  "content_key_specs": [
    {
      "key_id": "8GQsPtV48z4ylclpCPNGrw==",
      "track_type": "AUDIO",
      "key": "/1mATEx6XD+TJVyel3cHEQ=="
    },
    {
      "key_id": "DjEp9XC2UZVrtqWZVppYwQ==",
      "track_type": "SD",
      "key": "d2EHZ1xhxSMzeSS2sOf0Dw=="
    }
  ]
}
  
The HD information is similar, with a different default KID that is echoed in the pssh.

**Comment by joeyparrish** [comment]
The player uses `cenc:default_KID` from the manifest as the truth about which key IDs are used for which streams.  It uses the key status from EME (which is in turn based on the license response) to understand which keys are usable.  It will never switch to a higher-res stream unless the corresponding key ID from the manifest is marked as "usable" by EME.

Please check what key IDs you have in the license response (in hex).  Or in a debug build (but not a production build), you can get the key statuses from the browser with:

```js
player.drmEngine_.getKeyStatuses();
```

Compare these key IDs to the ones in your manifest for each stream.  If your manifest, for example, labels all streams with the *same key ID*, when in fact, they need *different keys*, that could explain the behavior.  But without manifest and license server URIs that we can test with, we can only guess.

I'm happy to recommend other things you could check for yourself if you don't want to share access privately, but we really can't investigate this without a way to reproduce the issue.

Does this help?

**Comment by btandy** [comment]
Yes that does help, thanks.

I changed how the license server proxy responds to requests for which the client is unauthorized. If the client can only view SD resolutions, and asks for an HD key, the proxy now does not send an error, but rather send back a license containing the AUDIO and SD key. When I do this, keyStatuses() in the console window shows the AUDIO and SD keys as 'usable', and the video stays on the SD resolution.

When I was returning errors for the HD request, the same keyStatuses command seemed empty.

So I guess that errors should NOT be used to indicate authorization failures for some but not all asset resolutions?

Regardless of whether an error was returned on a license request, I was not able to programmatically see the keyStatuses() result. My event listener for drmsessionupdate executed, but did not see anything for console.log(window.player.drmEngine_.getKeyStatuses()), which I am probably calling incorrectly.

**Comment by joeyparrish** [comment]
For Widevine at least, it would be unusual to make separate license requests for SD and HD keys.  Normally, a Widevine license request is made for a certain content ID, which spans the key IDs for all resolutions.  The proxy would normally decide what subset of the keys to return based on the user's authentication or some device characteristics such as security level.

For more help on how to set up and run your Widevine proxy, or for questions on the Widevine protocol, you should reach out to Widevine support: https://www.widevine.com/contact

Can we call this issue resolved as far as it pertains to Shaka Player?

**Comment by btandy** [comment]
Yes, resolved. Thanks for the help!
