### ISSUE TITLE
AES 128 encrypted stream not playing with shaka player

### ISSUE THREAD

**Issue by krackjack234** [google/shaka-player#2569]
Hi,

I am using CAF v3 framework for google casting which is using shaka player.
When we try to cast a AES 128bit encrypted content, the cast receiver is throwing below error

**[ 43.006s] [cast.framework.media.ShakaPlayer] category: 4 code: 4034** 

I saw in shaka documentation that AES 128 is not supported.

Is there any way we can play such streams?

**Comment by joeyparrish** [comment]
It's not supported at this time.  We have issue #850 to track that.  Feel free to contribute a PR if you're interested in this feature.  We believe decryption could be implemented with WebCrypto APIs instead of EME: https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API

**Comment by krackjack234** [comment]
Ok this is quite strange. As other players like videojs supports AES 128 playback.

Any plan by when this can be supported?

**Comment by joeyparrish** [comment]
As I said, we have issue #850 to track that.  Nobody is working on it currently, but we welcome contributions from the community.  If you're interested, we could discuss designs on that issue.
