### ISSUE TITLE
warning about @availabilityStartTime

### ISSUE THREAD

**Issue by FeiCao** [google/shaka-player#257]
hello，my player work on uncompiled mode and frequently warning like follow: 

@availabilityStartTime seems to be inaccurate; some segments may not be available yet: currentPresentationTime 1362.0009999275208 latestAvailableSegmentEndTime 1376.0666666666666

can you give me some advice? thank you

**Comment by tdrews** [comment]
Hi,

This means that based on `@availabilityStartTime` and the current time, the player did not expect the manifest to specify segments past the time 1362. You can generally ignore this warning when the two values indicated are close. This message is a little verbose, in Shaka 2 we will forego displaying a warning like this.

Depending on what packager you are using, you may be able to add an `@availabilityStartTime` offset. For example, with [edash-packager](https://github.com/google/edash-packager) you can adjust the `availability_time_offset` option.
