### ISSUE TITLE
Renewing expired offline license

### ISSUE THREAD

**Issue by karlg-arris** [google/shaka-player#2572]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.7

**Please ask your question**
Hi,

When an offline license for a downloaded stream expires, this is detected by Shaka and we see an appropriate error.
However, at least with the demo application, there does not seem to be a way to request the relevant license from the DRM server again without deleting the download and re-downloading.

Even though this license instance has expired, the user might still be entitled to view offline so long as they reaffirm their rights status with the server (thinking about some sort of management UI in which user can see which content instances have expired rights and choose to renew )

Maybe this just is not implemented in the demo?

**Comment by joeyparrish** [comment]
I'll mark this as "enhancement".  I don't believe we have a method in the offline API to re-license content.  In fact, we need to check that we have enough information stored with the offline content to do that in the first place.  We would need, at minimum, the init data and license server URI we used to make the original license request.

**Comment by TheModMaker** [comment]
This already exists as #1347, which has a PR #1359, which hasn't been updated recently.
