### ISSUE TITLE
Error code 6006 when playing back DRM encrypted DASH content on Tizen 2.4   Samsung TV

### ISSUE THREAD

**Issue by jariferguson** [google/shaka-player#2574]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes, I could not find a similar item.

**What version of Shaka Player are you using?**
https://cdnjs.cloudflare.com/ajax/libs/shaka-player/2.5.11/shaka-player.compiled.js

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
demo app, with DRM configuration added from the shaka-player-demo appsspot.com guide.

**If custom app, can you reproduce the issue using our demo app?**
not relevant

**What browser and OS are you using?**
Samsung Tizen tv-2.4.0

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Samsung Smart TV UE55KU600
Model CodeL UE55K&6000WXXN Version NoL 04

**What are the manifest and license server URIs?**
Would prefer not to share.

**What did you do?**
- Using Tizen Studio 3.7 I created a new Samsung TV 5.5 application using template,
- Added shaka-player.compiled.js CDN link to bottom of body in HTML.
- Created a new  js file and added code from https://shaka-player-demo.appspot.com/docs/api/tutorial-basic-usage.html
- Modified the main html file from same guide as previous step.
- Added a link to sample content (DASH, clear)
- Uploaded the project to the TV and verified playback works.
- Added  DRM configuration code block, based on the DRM section of the guide,
- Changed content reference to manifest for DRM protected content public facing CDN.
- Added  link to license URL
- Deployed updated application to TV and started in debug mode
- Debugger connected to TV

**What did you expect to happen?**
I was expecting the CDM to generate a license request and send this to license server.

**What actually happened?**
The application failed to start playback. The debugger showed two errors (probably the second one is a repeat of the first one:.
![Capture](https://user-images.githubusercontent.com/65400525/82049586-da5d8e00-96b6-11ea-9463-62c543a421b7.PNG)

Kind regards,
Jari Ferguson

**Comment by joeyparrish** [comment]
Error 6006 docs: https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html#value:6006

That is `FAILED_TO_GENERATE_LICENSE_REQUEST`, which indicates that the PSSH in the manifest is not understood by the CDM on the device.  Can you play this same content on any other device?  Are you configuring Widevine or PlayReady or both?
