### ISSUE TITLE
VMAP option for repeatable ad for live streams

### ISSUE THREAD

**Issue by jakubvojacek** [google/shaka-player#2576]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
latest master

**Please ask your question**
This might be not related directly to shaka player but wasn't really sure where else to ask.

I have been playing with the nightly shaka demo and its IMA SDK support - we got a neverending live stream and we'd like to do a preroll and multiple midrolls - midroll every X minutes for example. The preroll is easy but I am struggling with midrolls.

I guess I could do long VMAP with multiple midrolls and before serving it to the customer, I'd have to calculate the offset from video start to current time and enter many `<vmap:AdBreak timeOffset="XX:XX:XX.XXX" breakType="linear" breakId="midroll-X">`. However, that requires calculating the start time before each VMAP request and it would only play as many midrolls as many I would enter into the XML (not expecting that someone will watch the stream without reloading for days, but still..)

I was wondering whether you're aware of some syntax or some other approach that could be used to have a preroll and then a midroll every 10 minutes since the start of the playback.

Thank you
Jakub

**Comment by ismena** [comment]
Hi Jakub,

I think the best course would be to ask this on the [IMA SDK tech support forum](https://groups.google.com/g/ima-sdk). The IMA team would be most knowledgeable about how best to support your use case.

With their guidance, I'll be happy to work with you to accommodate this with Shaka. 
Please note that we don't officially support VPAID in this release yet (meaning, it might work out of the box, but we're not actively testing for it).

I'll leave the issue open, please come back if you have any questions after receiving guidance from the IMA team.

**Comment by jakubvojacek** [comment]
Thank you, I have posted there, if I hear from them with possible solution, I'll post here. 

Thank you
Jakub

**Comment by jakubvojacek** [comment]
We got an answer from the IMA team, it should be possible via some method of the IMA framework.

We will test it later, as of now, we're just exploring the options of ad playback and we're not yet that far as to call the IMA SDK methods directly.

But I guess this issue can be closed.

Thank you
Jakub
