### ISSUE TITLE
Basic Upscaling of Incoming Stream

### ISSUE THREAD

**Issue by sacredvoid** [google/shaka-player#2577]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.6

**Please ask your question**
I wanted to know if there's a way that we can change the resolution of the incoming stream (like if incoming is 180p and view 360p output using basic Bilinear Upscaling) and view it directly into the same video element? Instead of creating another canvas element? Would be great if you could help out here, thanks!

**Comment by joeyparrish** [comment]
The video stream will be rendered at the resolution of the `<video>` element.  So if you size the `<video>` element to 360p, you'll see all streams rendered at 360p.  The browser will both upscale and downscale as needed.  (Please note that upscaling does not increase the visual quality of the output.  180p video will still look like 180p video, even when rendered at 360p.)

We don't have any information on what scaling algorithm the browser might use.  I imagine it could vary per browser or even per OS.

Does this help?

**Comment by sacredvoid** [comment]
Let's say I want to tap the video tag buffers and apply some mathematical ops on it and then view it in the same video tag element, do you know any way of doing that?

**Comment by joeyparrish** [comment]
No.  The best you can do, as far as I know, is copy the content to a canvas and manipulate it there.  You could position the canvas on top of the video element to obscure it, and the result would be the same in terms of layout.

Does this help?

**Comment by sacredvoid** [comment]
Okay... makes sense. Thank you @joeyparrish!
