### ISSUE TITLE
On safari, getStats method returns switchHistory as an empty array.

### ISSUE THREAD

**Issue by JeffrinManovaPrabahar** [google/shaka-player#2578]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v2.5.9-debug

**Please ask your question**
On using fairplay for DRM protected content on safari, the player returns empty array in switchHistory when calling `player.getStats()`. Is this expected? How can I get switchHistory in safari for DRM protected content?

**Comment by joeyparrish** [comment]
DRM content in Safari is played using Apple's native HLS implementation.  We don't control switching resolutions in JavaScript in that scenario, nor do we get any visibility into the switching that Apple does for us.  So unfortunately, there is nothing we can do about that.

Sorry for the inconvenience!

**Comment by JeffrinManovaPrabahar** [comment]
Yes, that makes sense. Thanks.
