### ISSUE TITLE
Handling redirects for SegmentURI

### ISSUE THREAD

**Issue by solaris7x** [google/shaka-player#2586]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes 

**What version of Shaka Player are you using?**
v2.5.11 installed via npm for ReactJS

**Please ask your question**
How are Redirects handled by ShakaPlayer ?
Thank for your time , I'm Shaka-Packager creates a mpd file with segmentTemplate and my storage backend needs me access files via fileId eg. https://www.mystorage.com/file/[fileId]

I plan to write a express server to get the file name and path from request params , query the storage for file id then redirect to the storage file url

HTTP GET
https://express.hostedbyme.com/videoname/segmentname
Shaka Player --> Express Server 
Response 
HTTP REDIRECT 
https://www.myuni.com/file/someid

Thus how can I add Auth Header to the new URL ?

Any opinions much appreciated

**Comment by TheModMaker** [comment]
Redirects are handled by the browser; we request a URL, and if the server returns a redirect, the browser will make another request to the new URL.  You add the auth header to the original request and the browser should send it to the redirected URL too.
