### ISSUE TITLE
Cannot play HLS stream on safari

### ISSUE THREAD

**Issue by avinash0909** [google/shaka-player#2587]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes.

**What version of Shaka Player are you using?**
2.5.11

**Please ask your question**
Hello everyone,

i recently started working a personal video player app using shaka player. DASH works great  but i could never get HLS with fairplay DRM working on my safari browser :(
I am still learning implementation of HLS streams on video player relative to DASH.

the order i think it works is (Please Correct me if i am wrong.)

1. Client will provide the .m3u8.
2. Player will fetch skd url from HLS playlist (.m3u8) .
3. getckc (LaUrl relative) should be called .  how is it made ? because i could never get it to work. This is where i got stuck.

I was able to fetch contentId from initDataTransform callbackFunction and passed with return function `return shaka.util.FairPlayUtils.initDataTransform(initData, contentId[1], cert);` but nothing seem to work as i neither see network request in `registerRequestFIlter` nor in network tab in safari devtools. Result: Video never plays.

i tried to find the answer from repo issues space but dint get much help.

Help find my rootCause would be much appreciated. Thanks.

only changes between safair and widvine so far are 

`playerInstance.configure({
                drm: {
                    servers: {
                        'com.apple.fps.1_0': props.streamInfo?.licenseUrl
                    },
                    fairPlayTransform: false,
                    initDataTransform: initData => {
                            // 'initData' is a buffer containing an 'skd://' URL as a UTF-8 string.
                            const skdUri = shaka.util.StringUtils.fromBytesAutoDetect(initData);
                            const contentIdRegExp = /(?:contentId=)(.*?)\&/g;
                            const contentId = contentIdRegExp.exec(skdUri);
                            const cert = player.drmInfo().serverCertificate;
                            return shaka.util.FairPlayUtils.initDataTransform(initData, contentId[1], cert);
                    }
                }
            });
`

**Comment by TheModMaker** [comment]
Are you checking for failed `player.load()` promise?  Are you listening for `error` events from the player?  (`player.addEventListener('error', onError)`)  Are you getting any errors?  Is the `initDataTransform` being called?

My guess would be the browser is rejecting the data or the content ID.  You may need to convert the content ID from the regex from hex to binary (assuming it is hex).  Try calling `shaka.util.Uint8ArrayUtils.fromHex(contentId[1])` (or `fromBase64`) before passing to `initDataTransform`.

**Comment by avinash0909** [comment]
i have not tried it yet  due to work nbusy apologize late reply. will try it out today and let you guyz know. thank you recommendations.
