### ISSUE TITLE
HLS discontinuity playback failure on nightly

### ISSUE THREAD

**Issue by jamescahall** [google/shaka-player#2589]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v2.5.11-master-40-g6b11f1ec

**Can you reproduce the issue with our latest release version?**
Playback works on 2.5.11 stable release

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Custom

**If custom app, can you reproduce the issue using our demo app?**
Yes.  Plays in public release but not nightly on browsers where HLS is not natively supported.

**What browser and OS are you using?**
Chrome, webOS, Tizen, and others

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Tizen 2.3, 2.4, 3.0, 3.2, 4.0, 5.0, 5.5

**What are the manifest and license server URIs?**
URLs sent to Joey Parrish via email

**What did you do?**

Load player in app with latest nightly build.  Will send link to test scenario by email.

**What did you expect to happen?**
Video playback without issue

**What actually happened?**
The player is stable on 2.5.11 master for VOD content without discontinuities but we were testing the nightly build to fix support for HLS with discontinuities on live/linear streams.  We have linear streams that constantly stall / fail on discontinuities.  Per suggestion from Joey Parrish, we tested 2.5.11-master-40-g6b11f1ec and playback will not start at all.  Sorry for limited details but content is sensitive and will be sent by email.

**Comment by joeyparrish** [comment]
Does this discontinuity-based HLS stream work on desktop browsers (other than Safari, which uses Apple's native HLS)?

**Comment by jamescahall** [comment]
In other players yes.  It also works on other TVs using native players.  As mentioned, it played in production versions of ShakaPlayer just with failures on discontinuities.  The nightly build won't play start the stream at all.

**Comment by joeyparrish** [comment]
So it fails equally on Tizen and on desktop browsers?  I'm trying to determine if we need to a Tizen device to debug it.  We currently have no access to Tizen for debugging.

**Comment by jamescahall** [comment]
It fails on Chrome as well.  I sent links by email to an HTML5 app you can test in Chrome with auto-play security turned off.  The primary case we are using ShakaPlayer for is Chrome and LG WebOS

**Comment by joeyparrish** [comment]
Great, thanks.  That will simplify things for us.

**Comment by jamescahall** [comment]
For reference, I'm running Chrome in this manner to avoid any typical security blocks that wouldn't exists on a TV.  

open -a Google\ Chrome --args --disable-web-security --user-data-dir=/Users/youruser/ChromeOfflineData --autoplay-policy=no-user-gesture-required

**Comment by TheModMaker** [comment]
@michellezhuogg could you take a look at this?

**Comment by michellezhuogg** [comment]
Sure, looking at it now.

**Comment by michellezhuogg** [comment]
This was broken with commit [Remove position from SegmentReference](https://github.com/google/shaka-player/commit/1ab3f9c6dbf52a2704f0364ebb012c8c0a554260#diff-17637a05c12f996724bf981bd95aeb46) . 
Looking into how we can fix this.

**Comment by jamescahall** [comment]
Hi.  The player now starts but it is having very frequent rebuffering issues in testing on LG WebOS on linear streams.  We aren't seeing this issue on VOD playback.  You should have two test streams from us sent by email previously.  Is there an updated version of mux.js that should be used with this update?

**Comment by jamescahall** [comment]
NOTE:  I pulled master and built using all.py which output shaka-player.compiled.js in dist folder.  Is this the correct way to get the latest change?  I want to make sure that I'm not missing something that would affect this.

**Comment by joeyparrish** [comment]
Yes, that correct.  If you use mux.js, you may also want to "npm install" to make sure that is up-to-date, as well.

**Comment by joeyparrish** [comment]
We currently depend on mux.js as "^5.6.3"

**Comment by jamescahall** [comment]
Ok.  Ran npm install and confirmed that I have the correct version of mux.min.js and still having frequent freeze / buffering.

**Comment by joeyparrish** [comment]
Buffering on a live stream may be reasonably considered a different issue than failure to play.  Can you try some things for us to help us determine if this is a separate issue?

1. Does the same live stream have buffering issues on a desktop browser (not counting Safari, which uses a native HLS implementation)?
2. Does the same live stream behave badly with an increased presentation delay?  That could be a useful clue.  Try this before calling `player.load()`:

```js
player.configure('manifest.defaultPresentationDelay', 30);
```

If you are testing in our demo app, you can set that in the config before clicking "PLAY" on custom content.  Click the "three bars" icon in the top-left, then click "Manifest", then find "Default Presentation Delay".

Thanks!

**Comment by jamescahall** [comment]
1.  Yes, the linear stream is stopping every 10-20 seconds and freezing / buffering even on Chrome 83.  The example was sent via email the other day you can test against.
2.  My understanding was that defaultPresentationDelay was only for MPEG-DASH.  This is HLS.  With that said, I tried it and didn't have any improvement.  Here is our current configuration overrides for reference:

var configuration = { 'abr': { 'defaultBandwidthEstimate' : 500000 }, 'streaming': { 'bufferingGoal' : 10, 'rebufferingGoal': 4 } };

**Comment by joeyparrish** [comment]
In the master branch and upcoming release, presentation delay can now be applied to both DASH & HLS.

If the buffering behavior is not improved by an increased presentation delay, then it is not caused by playback too close to the live edge.  If it's buffering badly in desktop Chrome as well as WebOS, then it's not a performance issue specific to embedded devices.

Can you please open a new issue and send logs?  With the playback failure, we found and fixed a core issue in the our recently-refactored StreamingEngine.  That part of the code doesn't seem to explain the buffering behavior, so I think we should consider this playback failure issue closed and start a new one.

Thanks!

**Comment by jamescahall** [comment]
I don't have an easy way to send details logs as we use the compiled version and would require a significant refactor to use the uncompiled version.  Additionally, getting these logs on TVs is quite difficult.  This buffering issue was not occurring on previous master branch builds (such as 2.5.11).  I've sent examples for you to test on your end which should be sufficient for you to re-create and evaluate.  The issue seems to be caused by recent changes on your end.

**Comment by joeyparrish** [comment]
> The issue seems to be caused by recent changes on your end.

I completely agree.  I'm just asking for a little assistance finding the issue.  If you would please file a new issue for the buffering problem, which appears to be completely independent of the original issue here, that would be helpful.  Thanks!

> Additionally, getting these logs on TVs is quite difficult.

I can empathize with that, but you told us the issue can also be seen on desktop Chrome.  Could you collect logs there?

> This buffering issue was not occurring on previous master branch builds (such as 2.5.11).

v2.5.11 was never a master branch build, and did not support discontinuities.  No release version today supports discontinuities.  So this content with discontinuities could never have played correctly in existing releases.  I'm sure the buffering issue is related to refactoring in prep for what was planned as v2.6 and is now v3.0, but v3.0 will be the first release with HLS discontinuity support.

> we use the compiled version and would require a significant refactor to use the uncompiled version

What about the debug build?  It's a single file, so that should be a drop-in replacement for the fully-compiled build, right?  You don't need the uncompiled version to get logs.

**Comment by jamescahall** [comment]
Ok.  Created this ticket with logs using shaka-player.compiled.debug.js
https://github.com/google/shaka-player/issues/2605

Is there an ETA for a release version with discontinuity support?  This is preventing release of several services on LG TVs.

**Comment by joeyparrish** [comment]
Someone is working on in actively, and we intend to have it fixed in v3.0.  The root of these issues seems to have been introduced in refactors for new v3.0 features (such as discontinuities), so it doesn't affect v2.5.  I'm currently holding v3.0 until we have this fixed, since it seems like a serious issue in a key feature.

**Comment by jamescahall** [comment]
Thank you for the update.  Is there an ETA on this?  Are we talking days or weeks or months?  We are really looking to get these products out this month.

**Comment by joeyparrish** [comment]
You're asking how long it will take to solve a problem we don't know the cause of yet.  We simply don't know.  I'm sure you can relate, as an engineer.

I can say for certain, though, that if it takes more than days, we will release v3.0 without the fix.  We're only holding the release on the assumption that we can address it quickly.  But are, for now, assuming that we can address it quickly.

**Comment by joeyparrish** [comment]
The fix has been made.  See #2605 and e63813c363ce54ac8682c777906b4ba5d96ae33b for details.  The root cause did not affect v2.5.x, so the fix will not be cherry-picked.

**Comment by jamescahall** [comment]
Thanks.  This seems to be streaming well now.  I am noticing "switch" calls more often than I would expect which sometimes leads to brief buffering / audio drop.  The bandwidth measurement seems unchanged when this occurs.
