### ISSUE TITLE
Problem with presentationTimeOffset and mediaPresentationDuration when the playing period crosses more than 1 segment

### ISSUE THREAD

**Issue by ctt828** [google/shaka-player#2590]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
v2.5.11

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `master`?**
yes

**Are you using the demo app or your own custom app?**
demo

**What browser and OS are you using?**
Chrome on macOS

**What are the manifest and license server URIs?**
Sent via email

**What did you do?**
- Original manifest : Total Segments : 2, Segment duration : PT1M0S. 
- Use presentationTimeOffset to skip the first segment for 50 seconds, and let the playing period start from there.
- Set the mediaPresentationDuration to PT0M30S

**What did you expect to happen?**
A 30 seconds of play duration which starts from the first segment with 50 seconds skipped.

**What actually happened?**
- Only the rear part of the first segment (10 Seconds) is played  if "PT0M11S <= mediaPresentationDuration <= PT1M0S"
- It works if "mediaPresentationDuration >= PT1M1S"
- It works with DASH.js reference client 3.1.0

**Comment by TheModMaker** [comment]
So I think this is a bug in our `presentationTimeOffset` handling.  I remember a lot of confusion about how this is handled with segment times and we've had a bunch of bugs with this property and `startNumber` in the past.

 The segment's presentation time should use the PTO to adjust the `S@t` value; right now we ignore it for calculation of presentation time.
