### ISSUE TITLE
Integrate with mux.js ID3 tags parsing to enable IMA LIVE HLS experience 

### ISSUE THREAD

**Issue by ismena** [google/shaka-player#2592]
Parsing ID3 tags is required for LIVE HLS server-side streams with IMA SDK.
mux.js that we're already using for transmuxing has this functionality, so we should be able to integrate with it and using their parsing logic.

**Comment by avelad** [comment]
This has already been deployed and is working. Is there something missing?

**Comment by joeyparrish** [comment]
I can't speak for the implementer, @ismena, who is on leave, but if you're happy with it, I'm happy to close the issue.
