### ISSUE TITLE
PTO doesn't work after the fix of issue #2590

### ISSUE THREAD

**Issue by ctt828** [google/shaka-player#2594]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
The latest master

**What are the manifest and license server URIs?**
Sent via email

**What did you do?**
Let the playing period start with a segment, and since the base media decode time of that segment is 5400000 (timescale=90000), we need to set PTO to 5400000

**What did you expect to happen?**
The video plays from the beginning of that segment.

**What actually happened?**
- The play cannot start.
- If set the PTO to 0, the segment is placed at 01:00 .
- The hosted demo works fine.

**Comment by joeyparrish** [comment]
@ctt828, does this seem to be a regression?  Was this content working correctly for you before the fix for #2590?  Or is this just an independent issue that was not noticed before?

**Comment by TheModMaker** [comment]
The second manifest you sent us has one segment in it with a `S@t` value of 0 and a PTO of 5400000.  This means the start time (in manifest time) is -60 seconds.  The segment has a duration of 60 seconds, so it ends before the start of the manifest.  After adjusting segments, there is no content, so we can't play it.  This represents bad content.

You need to set the `S@t` attribute to match that of the segment time.  So if the segment starts at  60 seconds, it should be 5400000.  Then PTO is used to adjust that time to be 0 in manifest time.

I suggest you take at look at this doc for a full explanation of the timeline and how the numbers in the manifest affect each other: https://github.com/google/shaka-player/blob/master/docs/design/dash-manifests.md

**Comment by ctt828** [comment]
@joeyparrish Yes, this is a regression and it works (I now understand it is actually a workaround) before the fix for #2590.

@TheModMaker Thank you! All my test cases work after adding the`s@t` attribute, and they also work with dash.js.
