### ISSUE TITLE
using web audio api with shaka-player

### ISSUE THREAD

**Issue by MarvinMissingVenlafaxine** [google/shaka-player#2595]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.10 shaka-player.ui.js

**Please ask your question**

Hello,
i am trying to use the web audio api along with shaka player.

the shakaplayer script/css is included in html head.
customizing the ui etc. and dash video playback works fine.

now i wanted to use the web audio api to do some processing on the dash-video's audio.

var audioContext = new AudioContext();
var videoElement = document.getElementbyId('video');  //<- videolement has id="video"
var audioSourceNode = audioContext.createMediaElementSource(videoElement);
audioSourceNode.connect(audioContext.destination);

result is, that when trying to play the video now, it stops playing after view frames (2-6) searching within the timeline is "working" picture shows at new timepostion but again stops playback after view frames 
- when i comment the part
" var audioSourceNode = audioContext.createMediaElementSource(videoElement);
  audioSourceNode.connect(audioContext.destination); " 
- playback is working propper again.

as dash files i used the "angle-one" as well as own files - all with same behavior..

Anyone maybe any idea of what i am doing wrong? Thanks in advance for every Help.

kind regards
tom

**Comment by joeyparrish** [comment]
I'm not very familiar with WebAudio myself, and I'm not certain if anyone else on the team is.  At least, we've never used it in this project.

What you're doing at least seems to follow the broad strokes of the examples on MDN: https://developer.mozilla.org/en-US/docs/Web/API/MediaElementAudioSourceNode

Does anyone in the community have any experience with WebAudio who could maybe take a look and advise?

**Comment by MarvinMissingVenlafaxine** [comment]
Thanks for the quick response - i already checked https://developer.mozilla.org/en-US/docs/Web/API/MediaElementAudioSourceNode - and still now luck :(

so still - if anyone can help  - please :)

the purpose for the audioprocessing would be to render a sort of audiometer that displays the audiolevel of each channel of the audio, aswell as gives the opportunity to mute certian channels of the audio - so maybe if some even has a better idea than to use the web audio api...

Again THAAKS IN ADVANCE!

**Comment by joeyparrish** [comment]
That makes sense to me.  Especially with 6-channel audio, muting a channel is fairly granular.  If you want to hear more music and less vocals, muting the center channels is a great way to do that.  It's much more complicated in stereo content.

We can leave this open as a question and hope that somebody in the community with WebAudio experience can make a suggestion.  Sorry we can't do more!

**Comment by joeyparrish** [comment]
Though this is 1) old, 2) outside of Shaka Player, I now have some WebAudio experience I didn't have when this question was first asked.  So here's a code snippet that I hope you find helpful.  You can paste this into the debugger on the Shaka Player Demo to get a crude visualization of the audio levels for stereo content, as well as sliders that let you adjust the gain for left and right independently.

```js
const container = document.createElement('div');
document.body.prepend(container);

const canvas = document.createElement('canvas');
container.appendChild(canvas);

const gainInput0 = createRangeInput();
container.appendChild(gainInput0);

const gainInput1 = createRangeInput();
container.appendChild(gainInput1);

const context = new AudioContext();

// A source node pulling audio from the video element.
const source = context.createMediaElementSource(video);

// A splitter to break stereo into two separate mono outputs.
const splitter = context.createChannelSplitter(2);
source.connect(splitter);

// Run the two separate channels through gain nodes
// to adjust their volume.
// Adjust each gain with an input element.

const gain0 = context.createGain();
gainInput0.oninput = () => gain0.gain.value = gainInput0.value;
splitter.connect(gain0, /* channel */ 0);

const gain1 = context.createGain();
gainInput1.oninput = () => gain1.gain.value = gainInput1.value;
splitter.connect(gain1, /* channel */ 1);

// Run the gain-adjusted streams through analyzers
// to let us visualize their volume levels.

const dataSize = 2048;  // Number of amplitude samples.

const data0 = new Uint8Array(dataSize);
const a0 = context.createAnalyser();
a0.fftSize = dataSize;
gain0.connect(a0);

const data1 = new Uint8Array(dataSize);
const a1 = context.createAnalyser();
a1.fftSize = dataSize;
gain1.connect(a1);

// Merge the output together into a stereo stream.
const merger = context.createChannelMerger();
a0.connect(merger, /* channel */ 0, /* destinationChannel */ 0);
a1.connect(merger, /* channel */ 0, /* destinationChannel */ 1);

// Connect that to the audio output device.
merger.connect(context.destination);

// Every frame, visualize the audio.
const drawingContext = canvas.getContext('2d');
requestAnimationFrame(draw);

function createRangeInput() {
  const input = document.createElement('input');
  input.type = 'range';
  input.max = 1;
  input.min = 0;
  input.step = 0.01;
  input.value = 1;
  input.style.orient = 'vertical';
  return input;
}

function maxVolume(data) {
  // The data array has many values over time,
  // where 128 is the middle of the sine wave,
  // 0 is the bottom, and 255 is the top.
  // Map these values to an absolute value from the center,
  // then take the maximum.  This is what we graph.
  return Math.max.apply(null,
      Array.from(data).map((x) => Math.abs((x - 128) / 128)));
}

function draw() {
  requestAnimationFrame(draw);

  // Get audio analysis data.
  a0.getByteTimeDomainData(data0);
  a1.getByteTimeDomainData(data1);

  // Compute the max volume in this time slice.
  const max0 = maxVolume(data0);
  const max1 = maxVolume(data1);

  // Draw one column for the left, one for the right.
  drawingContext.clearRect(0, 0, canvas.width, canvas.height);
  drawingContext.fillStyle = 'red';
  drawingContext.fillRect(
      0, canvas.height,
      canvas.width / 2, -max0 * canvas.height);
  drawingContext.fillRect(
      canvas.width / 2, canvas.height,
      canvas.width / 2, -max1 * canvas.height);
}
```

I hope this is helpful!  I'm going to go ahead and close the issue now.
