### ISSUE TITLE
Overlay undefined (wrong build of the library)

### ISSUE THREAD

**Issue by gaurav-bothra** [google/shaka-player#2599]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.11

**Please ask your question**
I am trying to add resolution option in overlay. But I am getting **error Uncaught TypeError: Cannot read property 'Overlay' of undefined**
    at initPlayer
```js
    var manifestUri = 'my .mpd file';
    var licenseServer = 'https://cwip-shaka-proxy.appspot.com/no_auth';

    function initApp() {
        // Install built-in polyfills to patch browser incompatibilities.
        shaka.polyfill.installAll();

        // Check to see if the browser supports the basic APIs Shaka needs.
        if (shaka.Player.isBrowserSupported()) {
            // Everything looks good!
            initPlayer();
        } else {
            // This browser does not have the minimum set of APIs we need.
            console.error('Browser not supported!');
        }
    }

    function initPlayer() {
        // Create a Player instance.
        var video = document.getElementById('video');
        var player = new shaka.Player(video);
        // Make the UI layer.
        const videoContainer = document.getElementById('container-video');
        const ui = shaka.ui.Overlay(player, videoContainer, video)
        player.configure({
            drm: {
                servers: {
                    'com.widevine.alpha': licenseServer
                },
                advanced: {
                    'com.widevine.alpha': {
                        'videoRobustness': 'SW_SECURE_CRYPTO',
                        'audioRobustness': 'SW_SECURE_CRYPTO'
                    }
                }
            }
        });
        // Attach player to the window to make it easy to access in the JS console.
        window.player = player;
        // Listen for error events.
        player.addEventListener('error', onErrorEvent);

        // Try to load a manifest.
        // This is an asynchronous process.
        player.load(manifestUri).then(function() {
            // This runs if the asynchronous load is successful.
            console.log('The video has now been loaded!');
        }).catch(onError); // onError is executed if the asynchronous load fails.
    }

    function onErrorEvent(event) {
        // Extract the shaka.util.Error object from the event.
        onError(event.detail);
    }

    function onError(error) {
        // Log the error.
        console.error('Error code', error.code, 'object', error);
    }


    document.addEventListener('DOMContentLoaded', initApp);
```

**Comment by joeyparrish** [comment]
My guess it that you used the wrong build.  The UI is available in shaka-player.ui.js, as opposed to the legacy, non-UI build in shaka-player.compiled.js.  Does this help?

**Comment by gaurav-bothra** [comment]
Hi @joeyparrish ,

Can you please tell me which build I should use to add resolution option in player and how to customize ui of player.

**Comment by gaurav-bothra** [comment]
Hi @TheModMaker ,

can we add resolution option in shaka-player.ui.js ?

**Comment by joeyparrish** [comment]
Resolution selection already exists in the UI.  It was present in the very first UI release, it is configurable, and it is on by default.  I've added some screenshots below to explain.

Here's the full UI:
![full UI](https://user-images.githubusercontent.com/6843156/83338500-d4041000-a279-11ea-8889-be5b912c3ed0.png)

The "overflow" button is the icon with three vertically-stacked dots.  Here's the overflow menu you get when you click that icon:
![overflow menu](https://user-images.githubusercontent.com/6843156/83338481-ac14ac80-a279-11ea-89f1-78a9728679cc.png)

Here's the resolution submenu:
![resolution submenu](https://user-images.githubusercontent.com/6843156/83338484-b46ce780-a279-11ea-84f6-756ed82ca450.png)

If you want to configure what is in the UI, try the "Configuring the UI" tutorial in our docs: https://shaka-player-demo.appspot.com/docs/api/tutorial-ui-customization.html

Does this help?

**Comment by gaurav-bothra** [comment]
Hi @joeyparrish ,

I tried above link. But I am getting error.

Here is my code


`<script>
    var manifestUri = 'my mpd file';
    var licenseServer = 'https://cwip-shaka-proxy.appspot.com/no_auth';

    function initApp() {
        // Install built-in polyfills to patch browser incompatibilities.
        shaka.polyfill.installAll();

        // Check to see if the browser supports the basic APIs Shaka needs.
        if (shaka.Player.isBrowserSupported()) {
            // Everything looks good!
            initPlayer();
        } else {
            // This browser does not have the minimum set of APIs we need.
            console.error('Browser not supported!');
        }
    }

    function initPlayer() {
        // Create a Player instance.
        var video = document.getElementById('video');
      	const ui = video['ui'];
        const config = {
          addSeekBar: false;
        };
        ui.configure(config);
        var player = new shaka.Player(video);
        player.configure({
            drm: {
                servers: {
                    'com.widevine.alpha': licenseServer
                },
                advanced: {
                    'com.widevine.alpha': {
                        'videoRobustness': 'SW_SECURE_CRYPTO',
                        'audioRobustness': 'SW_SECURE_CRYPTO'
                    }
                }
            }
        });
        // Attach player to the window to make it easy to access in the JS console.
        window.player = player;

        // Listen for error events.
        player.addEventListener('error', onErrorEvent);

        // Try to load a manifest.
        // This is an asynchronous process.
        player.load(manifestUri).then(function() {
            // This runs if the asynchronous load is successful.
            console.log('The video has now been loaded!');
        }).catch(onError); // onError is executed if the asynchronous load fails.
    }

    function onErrorEvent(event) {
        // Extract the shaka.util.Error object from the event.
        onError(event.detail);
    }

    function onError(error) {
        // Log the error.
        console.error('Error code', error.code, 'object', error);
    }

    document.addEventListener('DOMContentLoaded', initApp);
</script>`

![image](https://user-images.githubusercontent.com/29119145/83344596-8db8ba80-a326-11ea-971d-63105df65b69.png)

**Comment by joeyparrish** [comment]
This part of your code:

```js
      	const ui = video['ui'];
```

only works if you set up your HTML correctly, but we can't see your HTML.  And this:

```js
        var player = new shaka.Player(video);
```

would create a new player instance that is not connected to the UI.

Please re-read the UI tutorial here: https://shaka-player-demo.appspot.com/docs/api/tutorial-ui.html

And specifically, pay close attention to the `<div>` container and the `data-` attributes on that and on the `<video>` element, as well as how to get the `Player` instance from the `<video>` element.

Does this help?
