### ISSUE TITLE
TTML captions for livestream not showing

### ISSUE THREAD

**Issue by natamari** [google/shaka-player#2603]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.12

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Custom

**If custom app, can you reproduce the issue using our demo app?**
N/A, due to authentication requirement

**What browser and OS are you using?**
Chrome, MacOS

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**

Manifest and license details emailed. Captions TTML included in manifest.

**What did you do?**

1. Use UI setting to enable/ disable captions. 

Result: Captions are not showing.

Console inspection:
player.isTextVisible_ returns false regardless of UI setting
player.getMediaElement().textTracks returns `activeCues` and `cues` lengths = 0

2. In console, enter player.setTextTrackVisibility(true)

Only then captions are showing and the UI captions enable/ disable is working.

Console inspection:
player.isTextVisible_ returns true
player.getMediaElement().textTracks returns `activeCues` and `cues` lengths > 0

**What did you expect to happen?**
Toggle captions using UI, captions are then displayed immediately.

**What actually happened?**
setTextTrackVisibility(true) must be explicitly invoked to display captions/ load cues into textTracks, UI is not responding.

**Comment by michellezhuogg** [comment]
Hello @natamari ,

I tested with your sample content in your email with our demo page, and got a DRM LICENSE_REQUEST_FAILED error. Could you please verify that your sample content is valid for testing? Thank you!

**Comment by natamari** [comment]
Hi @michellezhuogg, I've responded via email.

**Comment by joeyparrish** [comment]
Sorry for the long time without a reply.  We need a fresh access token to get a license for your content.  Please send one via email and we'll pick this issue up again.

Also, could you please try with our recent v2.5.15 release and let us know if that solves the issue for you?  A lot of other text-related issues have been fixed recently, so it's possible your issue has also been fixed.  Thanks!
