### ISSUE TITLE
Add stats for nerds to UI (in the same way as youtube)

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#2607]
Is it possible add stats for nerds to UI?

Example of Youtube:

Right click:
![image](https://user-images.githubusercontent.com/8983024/83487168-d305f500-a4aa-11ea-8c7b-8d6d7dbde65b.png)

Panel with stats:
![image](https://user-images.githubusercontent.com/8983024/83487122-bcf83480-a4aa-11ea-9f46-2a489f128c7d.png)

**Comment by MilosRasic** [comment]
This would be great, especially if it could be independent of the UI component but still manageable from the UI.

We made a poor man's version for our CE device app so the info and the ability to observe it is definitely there:
![poormansstats](https://user-images.githubusercontent.com/533052/83499063-0c476080-a4bd-11ea-849b-9abe751a3628.png)

Would also probably be a good contribution for someone looking to get into it but not in the nitty gritty of web playback and parsing the manifests.

**Comment by avelad** [comment]
In my app I have this:
![Captura de pantalla 2020-06-02 a las 10 45 07](https://user-images.githubusercontent.com/8983024/83499848-49f8b900-a4be-11ea-88c7-19d1b226e8e1.png)

**Comment by MilosRasic** [comment]
You win the stats measuring contest and I hope you won't mind if we copy shamelessly 😃

**Comment by ismena** [comment]
Ok, let's make sure we are talking about the same thing: you want your **users** to be able to see all that stuff? :)
We have a [player.getStats()](https://github.com/google/shaka-player/blob/master/lib/player.js#L3600) method that returns the [these stats](https://github.com/google/shaka-player/blob/master/externs/shaka/player.js#L137).

We can create a UI element to show this if you'd like. It probably won't win the stat measuring contest against @avelad's app but it does have a lot of info ;)

@MilosRasic when you mention it being independent from the UI component, do you mean Shaka's UI build or something else? Our UI lib is the only way we can manipulate the player's UI, without it all the UI is done by the browser, and we don't really control that.

**Comment by avelad** [comment]
@ismena My panel is too much, I prefer something YouTube style for end users.

**Comment by MilosRasic** [comment]
Personally I don't want it for end users but others may have different ideas. Looks like something a lot of dev teams would need and everyone ends up re-implementing on their own. A common solution wouldn't hurt.

I'd like it to be independent of Shaka UI because someone may not be using it but may still want to trigger the stats panel some other way. For example, we have our own UI but trigger the stats panel using a query string parameter or a remote config feature flag.

**Comment by joeyparrish** [comment]
The only DOM manipulation is in the UI.  We have tried to avoid messing with the DOM in the non-UI library.  We can enhance the stats in `getStats()` and you can render them however you like if you want to use your own UI.  It seems like it would just be a few rows of text.

I don't think it makes sense for us to do just the stats panel and not the rest, potentially conflicting with your UI in some way.

We can offer a UI element that just formats and displays data from `getStats()`, and apps can configure the UI to have it or not, depending on context.  Want it for your end-users?  Configure it to be on all the time.  Only want it for dev?  The turn it on in your debug builds or staging environment only.

Does that make sense?

**Comment by MarlonEngFront** [comment]
Se for possível adicionar algo parecido com a montagem que fiz, vai ficar muito bom, estou trabalhando com customização da UI do shaka-player e me deparei com esta necessidade para os developers, com relação ao método player.getStats(), gostaria de saber como ver ele em ação atravez de uma demo simples com html, carregando os arquivos necessarios, ex: player.js, shaka-player.ui.js,? 
@ismena @joeyparrish 
![stats-01](https://user-images.githubusercontent.com/19827398/84822439-05f3d100-aff3-11ea-8e2d-d358eca39fe1.jpg)

**Comment by ismena** [comment]
Hi @MarlonEngFront 
I trusted the Google translator to translate your post from Portuguese, I hope I got it right :)

Yes, we can try to do something like that! Let me schedule it for the next release. We will also be happy to accept a PR for this if you're (or anybody) up for it.

**Comment by Marlon-Agile** [comment]
Seria de grande ajuda e disponibilizar algo parecido, e sua tradução do google esta perfeita.
com relação ao método player.getStats (), como posso ver ele retornando as stats no console do navegador ? quais arquivos preciso carregar no documento html ?

**Comment by ismena** [comment]
On our demo page, run `shakaDemoMain.player_.getStats();` in the debugger console.
Then expand the object.
You'll see something like this:
```
{
width: 720, height: 576, streamBandwidth: 944898, decodedFrames: 51, droppedFrames: 0, …}
bufferingTime: 0.6160001754760742
corruptedFrames: 0
decodedFrames: 51
drmTimeSeconds: NaN
droppedFrames: 0
estimatedBandwidth: 3827966.609388212
height: 576
licenseTime: NaN
liveLatency: NaN
loadLatency: 0.7950000762939453
manifestTimeSeconds: 0.24300003051757812
maxSegmentDuration: 4
pauseTime: 19.32200002670288
playTime: 1.940999984741211
stateHistory: (4) [{…}, {…}, {…}, {…}]
streamBandwidth: 944898
switchHistory: (2) [{…}, {…}]
width: 720
}
```

**Comment by MarlonEngFront** [comment]
@ismena quais arquivos devo carregar na <head></head> para poder retornar método player_.getStats(); em um exemple básico ? depois quero pegas as informnações deste objeto e mostrar um uma <div></div>
https://codepen.io/MarlonEngFront/pen/JjGbJzq

**Comment by theodab** [comment]
With Shaka Player set up automatically in that way, you can get the player from the `video` element. For your codepen, you could do something like:
```js
const video = document.getElementById('video');
if (video && video.ui) { // Check if the UI has been set up, first.
  const player = video.ui.getControls().getPlayer();
  const stats = player.getStats();
  console.log(stats); // Or format this into DOM, etc.
}
```
This will only be accessible after Shaka Player is set up, so if you want to do this automatically you might want to listen for the `shaka-ui-loaded` event on `document` first.

**Comment by Marlon-Agile** [comment]
@theodab fiz como esta acima, mas retorna o objeto vazio no console, mesmo depois de executado o video, alguma sugestão de como trazer os valores;

https://codepen.io/MarlonEngFront/pen/JjGbJzq

**Comment by ismena** [comment]
@Marlon-Agile 
Try running player.load() first and then requesting stats.
Your stats object is being created first and although it's logged after a few seconds, it's still the same object.
```
const stats = player.getStats(); // This is where you requested the stats
    console.log(
      setTimeout(function(){
          console.log(stats); // This is where you logged them, but it's still the same stats from where you created "const stats," NOT the stats after 5 seconds.
      },5500));
```
Try something like this (pseudocode):
```
const player = video.ui.getControls().getPlayer();
// now wait!
waitFiveSeconds(); // <-- this is not a real function
// Now log
console.log(player.getStats());
```

Does it make sense?

**Comment by MarlonEngFront** [comment]
@ismena fez sentido sim, funcionou. agora o proximo passo é mostrar essas informações no html em uma `<div></div>` e escutar o video e ficar mostrando as alterações das informações. thanks!!!
![getStats](https://user-images.githubusercontent.com/19827398/85174218-4f3e5d80-b24b-11ea-9be9-a2c2a65b7d57.PNG)

**Comment by subodhk01** [comment]
Hey guys, so are we looking for a solution similar to what @MarlonEngFront suggested?

**Comment by jalajcodes** [comment]
I think the approach suggested by @MarlonEngFront is better, as there's no need to add an overlay menu, and its easy to find.
Also, I'd like to work on it.

**Comment by michellezhuogg** [comment]
Hello @jalajcodes , if you'd like to work on it as a participant of GSoC, we are looking forward to your application. Thank you!

**Comment by jalajcodes** [comment]
@michellezhuogg actually I wanted to ask you that this issue is listed as a project idea in the ideas list, are we allowed to work on it even before we get selected? 

I am asking this because I saw a PR by subodh that implements one of the ideas from the list.

**Comment by michellezhuogg** [comment]
> @michellezhuogg actually I wanted to ask you that this issue is listed as a project idea in the ideas list, are we allowed to work on it even before we get selected?
> 
> I am asking this because I saw a PR by subodh that implements one of the ideas from the list.

You'll need to go through the application process and officially accept the applications, to get recognized as a GSoC participant, and also get our guaranteed support and mentorship in summer. We have asked @subodhk01 if he is a potential participant of GSoC, and is waiting on his response.
On the other hand, we welcome contributions from developers all the time. If you're interested in any task and are confident to come up with a concrete solution without our help, please send us your proposal (for a project) or your PR (for a simple task). Thank you!

**Comment by sradhanjan** [comment]
@michellezhuogg So we will get mentor during GSOC program if the proposed project is outside of GSOC idea list right?

**Comment by chanchalpatil** [comment]
I had the same query as @jalajcodes . Is there any communication channel apart from the mailing list where queries related to GSoC can be asked?
I see that people are already working on projects mentioned in the projects list. Can we send proposals with new project ideas as well? @michellezhuogg
