### ISSUE TITLE
WARNING - incomplete alias created for namespace shaka.log

### ISSUE THREAD

**Issue by radiantmediaplayer** [google/shaka-player#2608]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
y

**What version of Shaka Player are you using?**
2.5.12

**Can you reproduce the issue with our latest release version?**
y

**Can you reproduce the issue with the latest code from `master`?**
y

**Are you using the demo app or your own custom app?**
n/a

**If custom app, can you reproduce the issue using our demo app?**
n/a

**What browser and OS are you using?**
n/a

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
n/a

**What are the manifest and license server URIs?**
n/a

**What did you do?**
Try to build 2.5.12 from source
On Windows 10 with Git Bash
git clone https://github.com/google/shaka-player.git
git checkout -b rmp-shaka-2.5.12 v2.5.12
python build/build.py +@core +@networking +@manifests +@text +./node_modules/eme-encryption-scheme-polyfill/index.js +./lib/polyfill/encryption_scheme.js +./lib/polyfill/indexed_db.js +./lib/polyfill/input_event.js +./lib/polyfill/mathround.js +./lib/polyfill/mediasource.js +./lib/polyfill/patchedmediakeys_ms.js +./lib/polyfill/patchedmediak
eys_nop.js +./lib/polyfill/patchedmediakeys_webkit.js +./lib/polyfill/videoplaybackquality.js +./lib/polyfill/vttcue.js

produces 

[INFO] Compiling the library (ui, release)...
C:/wamp64/www/shaka-player/lib/debug/log.js:141: WARNING - incomplete alias created for namespace shaka.log
    goog.exportSymbol('shaka.log', shaka.log);
                                   ^^^^^^^^^

0 error(s), 1 warning(s), 92.2% typed

**What did you expect to happen?**
No warning

**What actually happened?**
Warning happens - warning does not happen while building 2.5.11

**Comment by joeyparrish** [comment]
The warning can be safely ignored.  It is triggered by a bit of code that is only used in a debug build, and addresses an issue that we introduced in (if I recall correctly) v2.5.11.  See also #2565.
