### ISSUE TITLE
Chromecast support in v2

### ISSUE THREAD

**Issue by PyRo1509** [google/shaka-player#261]
To recreate:
Load demo Angel One w/ Subtitles.
Enable Subs, View/test on browser player. (WebVTT is included in manifest)
Choose various audio languages, perhaps cycle tracks

Cast to Chromecast, there are no subtitles and the audio will only be the default 'en' track.

**Comment by joeyparrish** [comment]
The current demo app does not support that yet.  You may notice that those controls are disabled as soon as you cast.

Please note that casting is done completely outside the library and in the application.  So you can already use the full range of Shaka features with the Chromecast in your own application, even though you can't see it in the demo.

With Shaka 2, we will organize the demo app in a way that shows all functionality both locally and on the Chromecast.

**Comment by joeyparrish** [comment]
In addition to showing Cast support in the demo app, we've decided to bring Cast support in-library for v2.  We hope this makes it easier for users to build Cast receiver apps.

**Comment by joeyparrish** [comment]
This is mostly done.  What we have so far will be in v2.0.0-beta3.  What's not done yet, which we hope to finish in the final v2.0.0:
 - Support for casting from the Cast button built into latest Chrome, as opposed to the Cast button on the video controls
 - CSS3 animated buffering spinner appears to perform poorly on Chromecast

**Comment by joeyparrish** [comment]
Split the CSS3 animation performance issue to #505, which will be deferred until after v2.0.0.
