### ISSUE TITLE
Wrong pixelAspectRatio population in DASH

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#2611]
The current implementation of `pixelAspectRatio` in DASH is wrong. `@par` in DASH is "display aspect ratio" so the correct is populate this field with `@sar`

Note: Tomorrow, I'll send a PR for this.

**Comment by joeyparrish** [comment]
Fixed in 1568d28686834e422e3a60ef00e228b8fb01c41b, but we did not tag the issue in the PR when we merged it.
