### ISSUE TITLE
no Streams chosen error

### ISSUE THREAD

**Issue by KFilipchuk** [google/shaka-player#2612]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
I did

**What version of Shaka Player are you using?**
2.5.12

**Please ask your question**
I am developing application for Tizen 2.4 (2016 Samsung model group)
When I'm trying to play the video, i'm getting error `init: no Streams chosen`. If i'm trying to use 2.5.8 version of Shaka Player instead 2.5.12, this error does not appear, but an 3016 error.

I wanted to know how it possible to solve

Thanks!

![image](https://user-images.githubusercontent.com/47752466/83577341-997dca00-a53c-11ea-8950-a82f971ec9e5.png)

**Comment by joeyparrish** [comment]
Do you get errors for this content on other platforms, such as desktop browsers?

**Comment by KFilipchuk** [comment]
> Do you get errors for this content on other platforms, such as desktop browsers?
Thanks for you fast reply!

There is no such error in desktop browsers

**Comment by joeyparrish** [comment]
Can you please try the latest from the master branch or the [nightly demo page](https://nightly-dot-shaka-player-demo.appspot.com/demo/)?

The screenshot of your logs show something about a Period transition, but that part of the code has been completely refactored for our upcoming v3.0 release.  If this is already solved in v3.0, I would advise you to wait and use that.
