### ISSUE TITLE
Cancel in-flight requests on .load() and .destroy() 

### ISSUE THREAD

**Issue by mihaiav** [google/shaka-player#2619]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**Is your feature request related to a problem? Please describe.**

I'm developing a  plugin to fetch the resources (e.g. like http_fetch_plugin). I would like the current in-flight requests cancelled when the player is `destroy()`-ed or a new resource is `load()`-ed so that I can release resources associated with the requests that are no longer used/needed.

**Describe the solution you'd like**

One way to do that would be to pass an `[AbortController](https://developer.mozilla.org/en-US/docs/Web/API/AbortController)` signal in the plugin function (e.g. [http_fetch-plugin ](https://github.com/google/shaka-player/blob/v2.5.x/lib/net/http_fetch_plugin.js#L40 ) and have shaka cancel the signal when the player is `destroy()`-ed or a new resource is `load()`ed. That way I could check if the signal is aborted and/or listen to the  `abort` event and release the resources associated with the in-flight request(s)

**Describe alternatives you've considered**

Listening to shaka `LoadingEvent` and `Detroy` event (though there doesn't seem to be a `Destroy` event) though listening to the player events from within a plugin seems impossible/quite messy. 

**Additional context**

**Comment by theodab** [comment]
We already have a mechanism for canceling network requests. Specifically, the plugins return [AbortableOperation](https://shaka-player-demo.appspot.com/docs/api/shaka.util.AbortableOperation.html) objects. When the player is destroyed, whatever `onAbort` callback you provide will be called; you can use that to call whatever methods abort your current download.

I should probably clarify that in the docs on plugin interfaces.

**Comment by mihaiav** [comment]
That's good to know. Are in-flight network requests cancelled when the player loads a new  resource/uri as well or is there any reason not to cancel them?

**Comment by joeyparrish** [comment]
NetworkingEngine's destroy() will abort all pending requests, and this is called when you destroy the Player instance.

It looks like StreamingEngine's destroy() method should abort any pending requests, but doesn't currently.  That would take care of new load() calls.
