### ISSUE TITLE
Possibility to delay widevine key request until user starts playback

### ISSUE THREAD

**Issue by msokalski** [google/shaka-player#262]
I would like to have an option to delay widevine key request, but keep current shaka behavior of buffering initial segments of video immediately after source is specified.
This is mainly needed to avoid some logics being executed in our drm module until user really presses play button.

**Comment by joeyparrish** [comment]
Hi @msokalski,

That is not a bad idea.  We'll consider it for after v2.0.  Thanks!

**Comment by ismena** [comment]
Hi @msokalski,
We've added the logic to make it possible to delay the license request until playback is started.
Please set delayLicenseRequestUntilPlayed flag of shakaExtern.DrmConfiguration to true to enable this behavior.
