### ISSUE TITLE
Background color only should apply to nested cues in UITextDisplayer

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#2623]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes

**What version of Shaka Player are you using?** 2.5.12

**Can you reproduce the issue with our latest release version?** Yes

**Can you reproduce the issue with the latest code from `master`?** Yes

**Are you using the demo app or your own custom app?** Both

**If custom app, can you reproduce the issue using our demo app?** Yes

**What browser and OS are you using?**
Chrome 83 macOS Catalina

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

Subtitle segment:
[SUB5_00000214.m4s.zip](https://github.com/google/shaka-player/files/4745745/SUB5_00000214.m4s.zip)

```
<?xml version="1.0" encoding="utf-8"?>
<tt xml:lang="en" xmlns="http://www.w3.org/ns/ttml" xmlns:ttm="http://www.w3.org/ns/ttml#metadata" xmlns:tts="http://www.w3.org/ns/ttml#styling">
  <head>
    <styling>
      <style tts:backgroundColor="black" tts:color="white" tts:extent="80% 10%" tts:fontFamily="arial" tts:fontSize="25px" tts:fontStyle="normal" tts:fontWeight="normal" tts:origin="10% 85%" tts:textAlign="center" tts:textDecoration="none" xml:id="defaultSpeaker"/>
      <style tts:backgroundColor="black" tts:color="white" tts:extent="80% 10%" tts:fontFamily="arial" tts:fontSize="25px" tts:fontStyle="normal" tts:fontWeight="normal" tts:origin="10% 85%" tts:textAlign="center" tts:textDecoration="none" xml:id="defaultCaption"/>
    </styling>
    <layout>
      <region style="defaultSpeaker" xml:id="speaker"/>
    </layout>
  </head>
  <body style="defaultCaption" xml:id="thebody">
    <div xml:lang="en">
      <p begin="00:14:36.70" end="00:14:38.93" region="speaker">Es necesario mantener
        <br/>
        el secreto total.</p>
      <p begin="00:14:40.57" end="00:14:42.20" region="speaker">
        <span tts:fontStyle="italic">"¿Está con nosotros?"</span>
      </p>
    </div>
  </body>
</tt>
```

**What did you do?**

Load the subtitle

**What did you expect to happen?**
The subtitle is rendered correctly

**What actually happened?**

The subtitle is badly rendered

![Captura de pantalla 2020-06-08 a las 13 54 52](https://user-images.githubusercontent.com/8983024/84027681-a876d900-a98f-11ea-8389-01ad05c4e25d.png)

The HTML is:

`<p style="width: 80%; white-space: pre-line; background-color: black; color: white; direction: ltr; justify-content: flex-end; align-items: center; display: flex; flex-direction: column; margin: 0px; font-family: arial; font-weight: 400; font-size: 25px; font-style: normal; height: 10%; position: absolute; top: 85%; left: 10%; text-align: center; writing-mode: horizontal-tb;"><span style="white-space: pre-line; background-color: black; color: white; direction: ltr; justify-content: flex-end; max-width: 100%; font-family: arial; font-weight: 400; font-size: 25px; font-style: italic; text-align: center; writing-mode: horizontal-tb;">"¿Está con nosotros?"</span></p>`

I expect that background color only should apply to nested cues in UITextDisplayer

**Comment by michellezhuogg** [comment]
Hello @avelad ,

In this [example](https://www.w3.org/TR/2018/REC-ttml2-20181108/#style-attribute-backgroundColor), is it true that:
1. The region's background color(red) should apply to the <p> element, unless specified
2. The <p> element's background color (purple) should apply to the spans inside it, unless specified?

Thank you!

**Comment by michellezhuogg** [comment]
Found answers here: 
https://www.w3.org/TR/2018/REC-ttml2-20181108/#semantics-style-inheritance-region
Style properties are inherited from a region element, if an inheritable style property is not associated with a content element () or an anonymous span E.

**Comment by avelad** [comment]
@michellezhuogg , While checking this I have seen that the change that was uploaded yesterday has a strange effect:
![Captura de pantalla 2020-11-04 a las 8 33 06](https://user-images.githubusercontent.com/8983024/98082129-86b74a80-1e78-11eb-93a1-cd815f342253.png)

Note: You can use the same stream from https://github.com/google/shaka-player/issues/2962 to reproduce the issue.

**Comment by avelad** [comment]
I have read the specification and you are correct, according to the specification the subtitle is badly generated, I will talk to our content provider. Thank you very much for the investigation!
