### ISSUE TITLE
Support for encrypted and muxed Dash segments.

### ISSUE THREAD

**Issue by suhaskam** [google/shaka-player#2629]
Hi,

I have a question whether Shaka Player currently supports encrypted and muxed segments in DASH.
.ie.
Given a video file containing audio and video.

Generate mpd and m4s files.
The m4s files should have audio and video muxed and also encrypted using using clear key/cenc

Will it possible to play such a content in Shaka player  / EME ?

Thanks in advance

**Comment by suhaskam** [comment]
Shaka player is able to play muxed content like 
http://download.tsi.telecom-paristech.fr/gpac/DASH_CONFORMANCE/TelecomParisTech/mp4-live-mux/mp4-live-mux-mpd-AV-BS.mpd

**But is there any support if the muxed segments are encrypted ?**

On the other hand, Dashif IOP guidelines suggest non-muxed segments.
https://dashif-documents.azurewebsites.net/DASH-IF-IOP/master/DASH-IF-IOP.html#adaptation-set-types

I also came across an old issue (https://github.com/google/shaka-player/issues/359).

**Comment by joeyparrish** [comment]
The DASH IOP recommends non-muxed segments, and we will not make non-trivial changes to support non-IOP-compliant content.  That said, we do not explicitly reject muxed content.  So if the browser supports it, we would expect it to play.  We know muxed content to play in MediaSource on many browsers.  With encrypted content, the muxed segments would also need to be supported by the CDM, which it sounds like would be Clear Key for you.

I would suggest you simply try it and see what happens.
