### ISSUE TITLE
Unable to play the FairPlay DRM content in Safari

### ISSUE THREAD

**Issue by Skakruk** [google/shaka-player#2632]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.11/2.5.12

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Own app

**If custom app, can you reproduce the issue using our demo app?**
No, demo app doesn't have FairPlay DRM video

**What browser and OS are you using?**
Safari v13.1.1 (14609.2.9.1.3), MacOS 10.14.6

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**
```
#EXTM3U
#EXT-X-VERSION:5
#EXT-X-SESSION-KEY:METHOD=SAMPLE-AES,URI="skd://8beb5af3-e40e-4e0b-bf96-3e6c2c6bcd5f/975e928a4a93a2cc9c584dff212d37d9",KEYFORMAT="com.apple.streamingkeydelivery",KEYFORMATVERSIONS="1"

#EXT-X-MEDIA:GROUP-ID="audio0",LANGUAGE="en",NAME="English",TYPE=AUDIO,AUTOSELECT=YES,DEFAULT=NO,URI="hlsmedia5-any-audioeng2ch-aac_96000.m3u8"
#EXT-X-MEDIA:GROUP-ID="audio1",LANGUAGE="en",NAME="English",TYPE=AUDIO,AUTOSELECT=YES,DEFAULT=NO,URI="hlsmedia5-any-audioeng2ch-aac_192000.m3u8"

#EXT-X-STREAM-INF:PROGRAM-ID=1,AUDIO="audio0",RESOLUTION=384x216,CODECS="avc1.64000d, mp4a.40.2",BANDWIDTH=249117
hlsmedia5-any-video-384x216.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,AUDIO="audio0",RESOLUTION=640x360,CODECS="avc1.64001e, mp4a.40.2",BANDWIDTH=440338
hlsmedia5-any-video-640x360.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,AUDIO="audio1",RESOLUTION=1024x576,CODECS="avc1.64001f, mp4a.40.2",BANDWIDTH=881455
hlsmedia5-any-video-1024x576.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,AUDIO="audio1",RESOLUTION=1280x720,CODECS="avc1.64001f, mp4a.40.2",BANDWIDTH=1272941
hlsmedia5-any-video-1280x720.m3u8
```
License URI - https://client-api.magine.com/api/playback/v1/fairplay/license
**What did you do?**
Start playing the asset.

**What did you expect to happen?**
In v2.5.10 everything works as expected. 

**What actually happened?**
In v2.5.11 - `player.load()` Promise never gets resolved
In v2.5.12 - `player.load()` Promise resolves, but the native `video` element doesn't have `audioTracks`, `videoTracks` filled with the actual track from the manifest. `getVariantTracks()` returns empty list.

Request to License URI never gets fired. `drm.initDataTransform` is not being executed.

After 4 retries (for each of the streams) getting an HTMLMedia Error with code 3 - Unable to decode the media.

**Comment by michellezhuogg** [comment]
Hello @Skakruk ,
Could you please send us your sample manifest, so that we can reproduce the issue? You can send the URIs to shaka-player-issues@google.com if it's private.

**Comment by Skakruk** [comment]
@michellezhuogg while I was preparing the codesandbox to demonstrate the whole process, I realized that the issue is somewhere within our custom wrappers around shaka-player. 
Maybe I'm missing some changes between 2.5.10 and 2.5.11.

**Comment by michellezhuogg** [comment]
Glad you found that out! 
Please let us know if you have any further questions. If not, can we close the issue?

**Comment by Skakruk** [comment]
@michellezhuogg yeah, we're listening to `encrypted` event and stoping the propagation if `e.initDataType === 'skd'` due to some issues with shaka-player in past, which was fixed in recent versions.
That's why the whole process of getting license wasn't started.
