### ISSUE TITLE
Shaka Player build 3.0.0-2-ga8318f50 does not use first segment for VOD Asset

### ISSUE THREAD

**Issue by apblack96** [google/shaka-player#2636]
This should be fixed now in `master`.  It never affected `v2.5.x` releases as far as we can tell.  Let us know if you need anything else!

_Originally posted by @joeyparrish in https://github.com/google/shaka-player/issues/2111#issuecomment-582657948_

Can we check if this issue affects the latest version of Shaka Player Demo?

**Comment by joeyparrish** [comment]
I don't understand what you've posted.  It seems like you're just quoting me.  Is there an issue?  If so, please use one of the issue templates we provide: https://github.com/google/shaka-player/issues/new/choose

Thanks!

**Comment by apblack96** [comment]
@joeyparrish This is regarding the same issue that was for issue #2111(which is now closed and was resolved for the 2.5.x branch and was supposed to be resolved in master). I was just curious if this issue is now affecting the 3.x branch as I am seeing it again after upgrading.

**Comment by joeyparrish** [comment]
Then please file an issue using the bug template and we'll look into it.  Thanks!
