### ISSUE TITLE
How to set response type to text on a request filter

### ISSUE THREAD

**Issue by nicolaslareu** [google/shaka-player#2637]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes, but I didn't found a duplicate.

**What version of Shaka Player are you using?**
2.5.11

**Please ask your question**
I need to know how to modify the request made by Shaka when requesting the DRM license to use Fairplay. I need to set the **response type** to **text** but I don't find the way to do it since the request object that the request filter receives does not have any place to override the response type of the request.

Thanks

**Comment by joeyparrish** [comment]
What do you mean by response type?  Are you trying to request a specific response type from the server? Are you trying to interpret the response in a certain way, or parse it as text?  I'm having trouble understanding your question, because response type sounds like part of the response, not part of the request.

**Comment by nicolaslareu** [comment]
Sorry if I am not clear. What I am trying to do is request a specific response type from the server, with type text.

**Comment by joeyparrish** [comment]
I don't know what that means in general terms.  Is there a specific request header you want to send?  Or a specific parameter or other thing the server is expecting?  We can help you customize the request however you need, but I don't yet understand what you need.

**Comment by TheModMaker** [comment]
If you are talking about the `xhr.responseType` field, this is just how the browser interprets the response.  The server always sends the same data, that field is used to auto convert the bytes to a string.  We always accept as bytes and have utilities in `shaka.util.StringUtils` to convert to a string if needed.

**Comment by nicolaslareu** [comment]
@TheModMaker is right. I was confused due to a previous experience with another media player that I used. I was able to make it work without any special configuration. Thank you for the help.

**Comment by joeyparrish** [comment]
Glad we could help!
