### ISSUE TITLE
EME is not initialised for live with unencrypted ads

### ISSUE THREAD

**Issue by diogoazevedos** [google/shaka-player#2645]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v3.0

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Custom app

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Chrome, Firefox, and Chromium Edge on macOS

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Not applicable

**What are the manifest and license server URIs?**
Sent to <shaka-player-issues@google.com>

**What did you do?**
I’m having troubles with v3.0 for live using Yospace, the issue is kinda related to https://github.com/google/shaka-player/issues/1094, and it’s not reproducible in v2.5.

**What did you expect to happen?**
EME is initialised and the playback continues on encrypted content.

**What actually happened?**
EME is not initialised because the first manifests come with periods without content protection.

<img width="1324" alt="Screenshot 2020-06-10 at 18 01 45" src="https://user-images.githubusercontent.com/1440785/84292708-026dcf00-ab47-11ea-9183-cb8ec0c8157a.png">

By removing the `variant.video.encrypted` from https://github.com/google/shaka-player/blob/v3.0.0/lib/media/drm_engine.js#L1739 and `variant.audio.encrypted` from https://github.com/google/shaka-player/blob/v3.0.0/lib/media/drm_engine.js#L1742 seems to work again.

**Comment by michellezhuogg** [comment]
Hello @diogoazevedos ,
Do you have a sample manifest that we can test with? You can send the URIs to <shaka-player-issues@google.com> if it's private.

**Comment by joeyparrish** [comment]
I believe I made a mistake when I filed #2979 today, as it duplicates this.  But #2979 has repro steps that can be executed in the demo and do not require specific or private content.

@diogoazevedos, would you be okay if we closed this issue as a duplicate and CC you on the other one, even though you filed yours first?

**Comment by joeyparrish** [comment]
Actually, I think I may have found a fix already.  I'll just close both issues when the fix lands, because I can see for certain that it fixes the issue with my repro steps.  If your content still doesn't work correctly after the fix, we can reopen this issue and investigate again.

This issue appears to affect v3.0.0 - v3.0.5, but not v2.5.x.

Thanks!

**Comment by diogoazevedos** [comment]
@joeyparrish feel free to close this issue in favor of #2979 😄
