### ISSUE TITLE
MANIFEST.PERIOD_FLATTENING_FAILED on manifest with single period

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#2646]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes

**What version of Shaka Player are you using?** 3.0.0

**Can you reproduce the issue with our latest release version?** Yes

**Can you reproduce the issue with the latest code from `master`?** Yes

**Are you using the demo app or your own custom app?** Both

**If custom app, can you reproduce the issue using our demo app?** Yes

**What browser and OS are you using?**
Chrome 83 macOS 10.15.5

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

Sent by private

**What did you do?**

Load a stream with a single period

**What did you expect to happen?**
The stream plays without problem

**What actually happened?**

The demo app shows `Shaka Error MANIFEST.PERIOD_FLATTENING_FAILED ()`

Note: In 2.5.12 the same stream works.

**Comment by michellezhuogg** [comment]
Verified the error occurred when combining streams.

**Comment by joeyparrish** [comment]
The failure is on text streams which have the following characteristics:

```
{
  mimeType: "application/mp4",
  codecs: "stpp",
  language: "es",
  kind: "subtitle",
  roles: [],
  id: 12,
  originalId: "9",
}
```

and

```
{
  mimeType: "application/mp4",
  codecs: "stpp",
  language: "es",
  kind: "subtitle",
  roles: [],
  id: 11,
  originalId: "8",
}
```

The only difference is the ID, but that is supposed to be enough to distinguish input streams if everything else is the same.

**Comment by joeyparrish** [comment]
The code to match based on ID was only ever added to audio/video matching, not text.  With that fixed, I get CORS errors, but that at least tells me it's trying to stream something.

**Comment by avelad** [comment]
There is a specific problem with the provider of the video, it has told me that they resolve it in a week :( I have other videos in which it happens but I cannot share them, can you upload the change and so I test if the problem is solved?

**Comment by joeyparrish** [comment]
We just merged the fix, and I'm updating the nightly build now.

**Comment by joeyparrish** [comment]
[The nightly demo](https://nightly-dot-shaka-player-demo.appspot.com/demo/) has been updated with the fix.

**Comment by avelad** [comment]
I tested again and it works!

@joeyparrish Do you have any ETA for 3.0.1?

**Comment by joeyparrish** [comment]
I'm cherry-picking changes to v3.0.x and running tests already.  The complete release process, unfortunately, can sometimes take a couple days.  We can tag and push things to GitHub and NPM with approvals from within the team only.  Pushing a copy through our Google-internal systems and processes to the Google-CDN-hosted sometimes requires approvals from other timezones, which can delay this part of the process significantly.

I expect to have the GitHub/NPM side of things done Wednesday or Thursday, depending on who is available for reviews, and hopefully the Google CDN updated by Friday or Monday.
