### ISSUE TITLE
Replace mux.js for CEA parsing

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#2648]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Is your feature request related to a problem? Please describe.**
Using mux.js for transmuxing makes sense, as we do not want to support TS streams long-term.  Using mux.js for CEA captions is different, since broadcast TV caption standards are not going away any time soon.

**Describe the solution you'd like**
We should own our own CEA parser so that apps do not need an additional dependency for caption parsing.  We can keep mux.js as an optional dependency for transmuxing TS content.

**Describe alternatives you've considered**
1. Continue using mux.js for captions (no change from today)
2. Use another existing parser (still a third-party dep, but now multiple)

**Comment by avelad** [comment]
@muhammadharis Do you plan to implement this for TS too? I ask this to know if the `forceTransmuxTS` configuration can be removed

https://shaka-player-demo.appspot.com/docs/api/shaka.extern.html#.StreamingConfiguration

`If this is true, we will transmux TS content even if not strictly necessary for the assets to be played. Shaka Player currently only supports CEA 708 captions by transmuxing, so this value is necessary for enabling them on platforms with native TS support like Edge or Chromecast. This value defaults to false.`
