### ISSUE TITLE
Regression in 3.0.0: offline.progressCallback is not called in release mode

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#2652]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes

**What version of Shaka Player are you using?** 3.0.0

**Can you reproduce the issue with our latest release version?** Yes

**Can you reproduce the issue with the latest code from `master`?** Yes

**Are you using the demo app or your own custom app?** Both

**If custom app, can you reproduce the issue using our demo app?** Yes

**What browser and OS are you using?**
Chrome 83 macOS 10.15.5

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

Any, eg: https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd

**What did you do?**

Load: https://shaka-player-demo.appspot.com/demo/#audiolang=es-ES;textlang=es-ES;uilang=es-ES;panel=HOME;build=compiled
Download the asset `Angel One`

**What did you expect to happen?**
The progress is updated

**What actually happened?**

The progress is not updated

Video:
[video.zip](https://github.com/google/shaka-player/files/4780978/video.zip)

**Comment by joeyparrish** [comment]
It looks like the compiler is renaming the field when the object is accessed in a closure.

**Comment by joeyparrish** [comment]
Oh, no, it's worse than that.  The whole body of that closure is empty somehow.

**Comment by joeyparrish** [comment]
If I add a call to `shaka.log.alwaysWarn` in the callback to make it easier to find in the compiled output, that's the only thing in the compiled output.

```js
    const onProgress = (progress, size) => {
      // Update the size of the stored content before issuing a progress
      // update.
      shaka.log.alwaysWarn('onProgress');
      pendingContent.size = size;
      config.offline.progressCallback(pendingContent, progress);
    };
```

Output:
```js
k=function(){Pa("onProgress")}
```

This is fairly disturbing, since we have to trust the compiler and can't manually check the output for 60k+ lines of code.

**Comment by joeyparrish** [comment]
We've seen instances in the past where the compiler gets confused and loses type info inside certain closures or after await statements.  Based on that experience, I tried hoisting the reference to `config` outside the closure.

```js
    const progressCallback = config.offline.progressCallback;
    const onProgress = (progress, size) => {
      // Update the size of the stored content before issuing a progress
      // update.
      shaka.log.alwaysWarn('onProgress');
      pendingContent.size = size;
      progressCallback(pendingContent, progress);
    };
```

Output:

```js
l=g.offline.progressCallback,m=function(G,I){Pa("onProgress");k.size=I;l(k,G)}
```

Moving the reading of the config outside the closure seems to restore not only the call to the callback, but also the setting of `pendingContent.size`.  I can't explain this.

**Comment by joeyparrish** [comment]
I found that logging the return value of the callback (`undefined`) also causes the closure contents to be left in place.

I see now that `pendingContent` is only used in these progress callbacks, so if the callback itself is optimized away, then `pendingContent` becomes unused, and the line to set `pendingContent.size` becomes dead code.  So that explains why this line disappears along with the callback.  It's still unclear why the compiler thinks the callback has no side-effects and can be removed, or why reading it outside the callback first changes that assumption.

**Comment by joeyparrish** [comment]
I'm unable to reproduce this compiler bug in a simple demo, so it's unlikely I'll get anywhere with the compiler folks.  So I will go ahead with a workaround, a massive comment, and a regression test.
