### ISSUE TITLE
Forcing the screen orientation to horizontal in full screen mode

### ISSUE THREAD

**Issue by Kotekczu** [google/shaka-player#2653]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes.

**Is your feature request related to a problem? Please describe.**

When clicking the full screen button on phone in vertical, the screen orientation remains in vertical so I've to enable the rotation on the device and rotate it to have a "real" full screen.

**Describe the solution you'd like**

If full screen on rotate is enabled, the player should switch the orientation to horizontal automatically when clicking the full screen button. Just the same way it happens when rotating the device. It was commented [here](https://github.com/google/shaka-player/issues/883#issuecomment-309142939) once.

**Describe alternatives you've considered**

**Additional context**

**Comment by theodab** [comment]
That feature must have slipped between the cracks. Thanks for pointing this out!
