### ISSUE TITLE
EAC3 is supported?

### ISSUE THREAD

**Issue by nicolaslareu** [google/shaka-player#2661]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.11 or higher

**Please ask your question**
EAC3 (Doulbe Digital Plus) is supported?
Is it supported for HLS?
Is it supported for DASH?
If yes, on which browsers is supported?

**Comment by joeyparrish** [comment]
Support for EAC3 on any other codec depends entirely on support in the underlying browser.  I don't know which browsers support EAC3, but Shaka Player does not do anything special for codec support.

On any given browser or device, you can load this page to see the results of a probe of what it supports, including AC-3: https://shaka-player-demo.appspot.com/support.html

Does this help?

**Comment by nicolaslareu** [comment]
Yes! And a lot! Thank you!

**Comment by joeyparrish** [comment]
Happy to help!
