### ISSUE TITLE
Question iOS Playback: Error Code 3016

### ISSUE THREAD

**Issue by interpegasus** [google/shaka-player#2664]
**QUESTION**
I would like to know if it is possible to enable video playback on Chrome and Safari for iOS?

**What version of Shaka Player are you using?**
shaka-player/3.0.0

**What browser and OS are you using?**
Chrome iOS 

**What are the manifest and license server URIs?**
let manifestUri = "https://dash.akamaized.net/envivio/EnvivioDash3/manifest.mpd";

**What did you do?**

1. Testing cross browser compatibility
2. Tested playback on Chrome iOS and it does not playback. 
The console returns error 3016
And an INFO  message: "NO MSE implementation available"

**What did you expect to happen?**
Playback should work similar as other web browsers.

**What actually happened?**
No video Playback.

**Code**
```
let manifestUri = "https://dash.akamaized.net/envivio/EnvivioDash3/manifest.mpd";
function initApp() {
    // Install built-in polyfills to patch browser incompatibilities.
    shaka.polyfill.installAll();

    // Check to see if the browser supports the basic APIs Shaka needs.
    if (shaka.Player.isBrowserSupported()) {
        // Everything looks good!
        initPlayer();
    } else {
        // This browser does not have the minimum set of APIs we need.
        console.error("Browser not supported!");
    }
}

function initPlayer() {
    // Create a Player instance.
    var video = document.getElementById("video");
    var player = new shaka.Player(video);

    // Attach player to the window to make it easy to access in the JS console.
    window.player = player;

    // Listen for error events.
    player.addEventListener("error", onErrorEvent);

    // Try to load a manifest.
    // This is an asynchronous process.
    player
        .load(manifestUri)
        .then(function () {
            // This runs if the asynchronous load is successful.
            console.log("The video has now been loaded!");
        })
        .catch(onError); // onError is executed if the asynchronous load fails.
}

function onErrorEvent(event) {
    // Extract the shaka.util.Error object from the event.
    onError(event.detail);
}

function onError(error) {
    // Log the error.
    console.error("Error code", error.code, "object", error);
}
```

**Comment by joeyparrish** [comment]
DASH can only be played through MediaSource, which is the browser API that lets JavaScript applications handle fetching and adapting.  iOS doesn't offer this API, so until Apple changes this policy, we can only use Apple's built-in HLS support on iOS browsers.

Does this help?

**Comment by interpegasus** [comment]
Thanks for the clarification. Very helpful. For now HLS is required on iOS devices. 
I have read that on iPadOS MPEG DASH works. Hopefully Apple will add support soon to iOS.
