### ISSUE TITLE
Can I get which segment is being played in a determined timeline point?

### ISSUE THREAD

**Issue by saalvaa96** [google/shaka-player#2666]
My purpose would be to generate a Javascript variable with the segment being played stored inside.

Structure is: init-video-0-0 (for initial segment) and video-0-0-N (for the following N segments).

For example imagine you start playing a video, well, that variable would store: video0-0-1.mp4, as it is the segment from whom it is reading media information, if you click 10 seconds ahead in the timeline, it will change variable value to, for example, video0-0-3.mp4, if you click back to the beginning, it updates its value to video0-0-1.mp4 again. Not sure if I'm clear.

It should also update itself, not just clicking. Imagine you click play at the beginning, this variable should store video0-0-1.mp4, a few seconds after it should store video0-0-2.mp4 and so on.

I've been inspecting Chrome's Network tab in my web player, and it downloads segments in advance (improving UX with no delays, and of course it stores some in the cache, so when you click back to the beginning, it plays the previously downloaded one, not getting it again).
For this reason, this information would not fit my necessities.

I've been looking into some Shaka classes but I've not found this precise one.

I would also need to show that variable in the web page (display var as text in html), but I think that's easy once you get that information.

Thank you in advance!

**Comment by joeyparrish** [comment]
We don't offer this information because we don't track it.  When we fetch, for example, `/foo/480-1.mp4`, that turns into a byte array, and we feed that to the browser through the `MediaSource` API.  Then we may, for example, adapt up to 1080p and fetch `/foo/1080-2.mp4` next.

We know what time is being played right now (`video.currentTime` on the video element gives this), and we know what stream we're currently playing (1080p), but we don't store in memory what segments we fetched earlier, and the browser doesn't know where those byte arrays came from, so it doesn't have any way to map times to URLs, either.  Furthermore, media can be removed from buffer, both by the player and silently by the browser if it runs low on memory.

So... it's complicated, and there's not an obvious benefit to tracking and providing this information.

**Comment by saalvaa96** [comment]
My Master's Degree Final Project is about assuring video integrity. For that purpose I've coded a JS process that computes fragments hashes when they are ready.

My purpose with Shaka Player would be to verify video integrity while playing segments. Previously computed hashes should coincide with the ones computed "on the fly" thanks to a Shaka Player output which lead us to the segment name. From this point, we only need to read `segmentN.mp4` hash (stored in some database or web server) and compare it to the one computed on the fly.

I know this is a very specific need. If you can think of another way of getting which segment is being played, I would appreciate it.

**Comment by ismena** [comment]
@joeyparrish 
Could this be approached by creating a request/response filters that can catch segment requests and fetches for the app to try and map the downloaded segments to the current time?
Or is it gonna be horribly inaccurate?

@saalvaa96 You project sounds fun ;)

**Comment by TheModMaker** [comment]
I'm confused how you are getting the hashes for the output.  There is no way to get the segment data once we have given it to the browser, so the only thing you could validate in that regard is the network response.  If you are taking screenshots to compare the displayed output, you could just use `video.currentTime` to determine which frame is being displayed and compare that to the expected value.

**Comment by saalvaa96** [comment]
@ismena thank you! I can maybe post a link somewhere here in case it's interesting for anyone once I've finished it.

@TheModMaker my intention is to record live video and broadcast it, but storing hashes of the segments as close to real time as possible (to reduce the possibility to be altered). Then, if you go and watch that video on demand, you should be able to retrieve the hash which was computed at the time of recording (stored in some blockchain). With that information you can compare it to the hash of the segment stored in some server and check if it has been altered since its recording. I found interesting clicking the play button and getting dynamic outputs while checking segments. 

Imagine a player inside a website and below a banner which displays "AUTHENTIC" in green or "FORGED" in red depending on the segment's authenticity.

If only Shaka knew which segment's `mdat` or `moof` boxes is reading at every timeline point, I would be able to do it.

**Comment by TheModMaker** [comment]
As I said, you can't really check the data once it has been given to the browser; but you could check the network response.  This is also the most likely point to be tampered.  You could use a response filter to look at the original URL and the data we got back to see if it is what you wanted.

```js
 player.getNetworkingEngine().registerResponseFilter((type, response) => {
  if (type == shaka.net.NetworkingEngine.RequestType.SEGMENT) {
    const expected = FindHashForUri(response.originalUri);
    const actual = GetHashOfData(response.data);
  }
});
```

But as we've said, we don't expose which segment goes where; so you'd have no way of detecting what time this segment is for.

**Comment by saalvaa96** [comment]
My URL is a relative path to the .mpd file. Does your suggestion involve reading .mp4 segments directly? Or would I just be checking the .mpd integrity?

I've tried that code and it won't enter if condition, so variables remain undefined. Should I check that function periodically? I'm sorry but I don't get it.

**Comment by TheModMaker** [comment]
The URL in this function is an absolute URL, after resolving relative paths.  This will only be called for media segments (.mp4 segments), not the manifest.  The `type` will be `MANIFEST` for manifest requests.  You only need to register this once.  You should call this before loading, but it should work at any time.

Is the function called at all?  What values is it called with?  What version of the library are you using?

**Comment by saalvaa96** [comment]
Yes, it's called inside the script of my html player file.

FindHashForUri and GetHashForData are pre-coded functions getting hashes of a link and a file?

I'm using shaka 3.0.1 compiled cdn (https://cdnjs.com/libraries/shaka-player)

I would like to check that for example: local file and web server file have the same hash for a determined timeline point. Sorry for being that newbie in this programming issue.

**Comment by TheModMaker** [comment]
I was asking if the filter was being called, not if the registration was getting called.  How about doing this:

```js
console.log('!!! Registering filter');
player.getNetworkingEngine().registerResponseFilter((type, response) => {
  console.log('!!! Calling filter with', type, response);
});
```

FindHashForUri and GetHashForData would be functions you would write.  You need to read the `response.data` to get the hash of the real data and use the `response.originalUri` to find the expected hash.
