### ISSUE TITLE
Hide seekbar or time

### ISSUE THREAD

**Issue by cesarlwhoriginal** [google/shaka-player#2667]
Hi, I am using this tutorial https://nightly-dot-shaka-player-demo.appspot.com/docs/api/tutorial-basic-usage.html and I need to hide the seekbar or the time because I will work with a live streaming that no have a time like a VOD streaming.

How can I do this please?

See the image with that I need to hide
![shaka](https://user-images.githubusercontent.com/67196878/85204554-d555b500-b2da-11ea-9f50-f0dcac40885b.png)

**Comment by theodab** [comment]
That tutorial is for using the player by itself, without using our optional UI library. So the video element in this case is the browser's actual video element. You can hide the seek bar with CSS, e.g.:
```css
video::-webkit-media-controls-timeline {
  display: none;
}
```

However, it's probably better to use our UI library instead. The [tutorial for it](https://nightly-dot-shaka-player-demo.appspot.com/docs/api/tutorial-ui.html) is later in the list of tutorials. With the UI library, disabling the seek bar just requires passing in the right configuration value:
```js
const video = document.getElementById('video');
const ui = video['ui'];
const config = {
  addSeekBar: false;
};
ui.configure(config);
```

**Comment by cesarlwhoriginal** [comment]
Thanks a lot. Now is perfect!

I used:

```
video::-webkit-media-controls-timeline {
  display: none;
}
video::-webkit-media-controls-time-remaining-display {
  display: none;
}
video::-webkit-media-controls-current-time-display {
  display: none;
}
```


![image](https://user-images.githubusercontent.com/67196878/85212121-3bf7c480-b315-11ea-8a23-52e6cde63e23.png)
