### ISSUE TITLE
Demo version links do not load if ad-blocker is used

### ISSUE THREAD

**Issue by theodab** [google/shaka-player#2669]
If an ad-blocker is running, and the demo is in uncompiled mode, the player fails to load. This is expected behavior (see #2222); the fix is to run in compiled mode. However, if you are navigating to the demo page in such a situation, most of the demo page does not load: this includes the version links at the bottom, which you would normally use to navigate to the compiled version. This is kind of a problem, since the demo defaults to uncompiled mode!
We should handle such failures better, to make it easier for users to recover from such issues.

**Comment by avelad** [comment]
One solution might be to load the compiled version by default when an ad blocker is detected

**Comment by theodab** [comment]
Maybe. Right now I have a CL out for review that adds a contextual error popup, and fixes the links at the bottom so that they are visible if the load fails. I figure it could be like a learning moment, like showing the developer a good reason why they shouldn't use uncompiled mode in actual production apps? But I could see the argument either way.
