### ISSUE TITLE
Issue when the user activate and deactivate the subtitles.

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#2671]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes

**What version of Shaka Player are you using?** 3.0.1

**Can you reproduce the issue with our latest release version?** Yes

**Can you reproduce the issue with the latest code from `master`?** Yes

**Are you using the demo app or your own custom app?** Both

**If custom app, can you reproduce the issue using our demo app?** Yes

**What browser and OS are you using?**
Chrome 83 macOS 10.15.5

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd

**What did you do?**

Load the asset: https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd
1) Enable English subtitle
2) Disable subtitles
3) Enable English subtitle

**What did you expect to happen?**
1) English subtitles are shown
2) The subtitles are disabled
3) English subtitles are shown

**What actually happened?**

1) English subtitles are shown
2) The subtitles are disabled
3) English subtitles are shown but the selector is not updated

Video with the issue
[issue with subttiles.zip](https://github.com/google/shaka-player/files/4813638/issue.with.subttiles.zip)

**Comment by avelad** [comment]
Related

**What did you do?**

Load the asset: https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd
1) Enable English subtitle
2) Disable subtitles
3) Enable English subtitle
4) Seek to another point out of the current buffer

**What did you expect to happen?**
1) English subtitles are shown
2) The subtitles are disabled
3) English subtitles are shown
4) English subtitles are shown

**What actually happened?**


1) English subtitles are shown
2) The subtitles are disabled
3) English subtitles are shown but the selector is not updated
4) The subtitles are disabled

**Comment by ismena** [comment]
@muhammadharis 
Could you please check if your fix affects this issue and let me know.

**Comment by muhammadharis** [comment]
@ismena It seems to me like https://github.com/google/shaka-player/pull/2672 fixes this issue.

**Comment by muhammadharis** [comment]
@ismena it seems like my fix targets a different issue, and doesn't affect this one.

**Comment by muhammadharis** [comment]
@ismena @avelad https://github.com/google/shaka-player/pull/2674 a fix for captions disappearing on unbuffered seeks after activating, deactivating, then reactivating them.

**Comment by avelad** [comment]
@joeyparrish is it possible migrate it to 3.0.x?

**Comment by joeyparrish** [comment]
Yes.  Generally, issues tagged with "bug" and commits starting with "fix:" are eligible to be cherry-picked to existing release branches.
