### ISSUE TITLE
Shaka player return type error if http request status is 4xx, 5xx or timeout

### ISSUE THREAD

**Issue by qba86** [google/shaka-player#2675]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.13

**Can you reproduce the issue with our latest release version?**
My application isn't compatible with Shaka player 3.x.x yet so the last version on which I was able to catch the error is 2.5.13. The error exist since relase 2.5.0-beta-2
**Can you reproduce the issue with the latest code from `master`?**
Latest master 2.5*

**Are you using the demo app or your own custom app?**
Own app with custom xhr plugin

**If custom app, can you reproduce the issue using our demo app?**
N/A

**What browser and OS are you using?**
Google chrome and Windows 10

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
N/A

**What did you do?**
I run live streaming with mpeg-dash and widevine. I set throttling slow 3g / fast 3g in devTools or mock segments to return 4xx, 5xx or timeout

**What did you expect to happen?**
Return error code from namespace ShakaPlayer.util.Error.Code.

**What actually happened?**
Shaka player 2.4.4 in this case return error code from namespace ShakaPlayer.util.Error.Code.
Shaka player 2.5.0-beta-2 - 2.5.13 return
`typeerror: cannot read property 'bytelength' of undefined`

**Comment by ismena** [comment]
Hi @qba86 thanks for the report.
Let's  make sure I understand what's going on correctly: when streaming LIVE content on a slow network (or emulating one), the player does not return an appropriate error. Is that right?
Does it happen on any content or your specific LIVE content? Are you able to reproduce it with your content on our demo page?

**Comment by joeyparrish** [comment]
My guess is that the custom XHR plugin you mentioned is not compatible with Shaka Player v2.5.  Have you checked the upgrade guide for v2.4 => v2.5?  https://v2-5-13-dot-shaka-player-demo.appspot.com/docs/api/tutorial-upgrade-v2-4.html

It says:

> ### Network scheme plugin changes
> In v2.4, we changed the API for network scheme plugins.
> 
> These plugins now return an instance of shakaExtern.IAbortableOperation. We suggest using the utility shaka.util.AbortableOperation for convenience.
> 
> We also introduced an additional parameter for network scheme plugins to identify the request type.
> 
> All applications which have application-level network scheme plugins MUST update to the new API. Support for the old API was removed in v2.5.

**Comment by qba86** [comment]
ok, my mistake, I didn't pass the progressUpdated function to httpXhrPlugin
