### ISSUE TITLE
Unable to load dash manifests with long media persentation duration in 3.0.X

### ISSUE THREAD

**Issue by Ljugoboss** [google/shaka-player#2677]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v3.0.1, master, and v2.5.12
The bug is not reproducible in v.2.5.12

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Demo and custom app.

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Windows 10 version: 19041.239,
Google chrome Version 83.0.4103.106 (Officiell version) (64 bitar)

**What are the manifest and license server URIs?**
3600s version
https://znipe-video.akamaized.net/streams/test/test-event-2020/test-tournament-2020/28d56e7b-f8c2-40ec-a9b0-5a92e8e5c58e/nhmgvv/11/manifest_a73o2.mpd

7200s version
https://znipe-video.akamaized.net/streams/test/test-event-2020/test-tournament-2020/28d56e7b-f8c2-40ec-a9b0-5a92e8e5c58e/nhmgvv/11/manifest_DID4o.mpd

300s version (Works as intended)
https://znipe-video.akamaized.net/streams/test/test-event-2020/test-tournament-2020/28d56e7b-f8c2-40ec-a9b0-5a92e8e5c58e/nhmgvv/11/manifest_Zj6Iq.mpd

**What did you do?**
Try to play the content in v3.0.1

**What did you expect to happen?**
It should play, as it does in v2.5.13

**What actually happened?**
When trying to load the manifest, the wrong segments are being downloaded and the video fails to start until I seek to a time after the downloaded segments.
The `startNumber` is set to 0 with a `presentationTimeOffset` of 0, but the loweset segment number downloaded is 799.
After pressing play/pause in the demo player, the message `Ignoring large gap at 0 size 1598.033333` is printed. This matches up to the segment number of 799 with a segment duration of 2s. 
If I search to a timestamp in the video larger than 1598.033333, the video plays normally but fails as soon as I seek back to earlier point it fails again.

It should also be noted that the error becomes larger the longer the video is. The video mentioned above is 3600s long, but with a video that is 7200s long the initial segment is 2599 with a message of `Ignoring large gap at 0 size 5198.033333`.

Short videos does not seem to have the same problem.

**Comment by michellezhuogg** [comment]
Verified that player cannot start to play the manifest. Thank you for your report! We will work on a fix.

**Comment by thowfeeq178** [comment]
we are facing the same issue! kindly help

**Comment by RoyBregman** [comment]
We are also facing this. Please try and make this high priority as this is holding us from upgrading to version 3.0.2

**Comment by OrenMe** [comment]
seems to be from https://github.com/google/shaka-player/commit/9f448710bc53d5f1ebb6239cacf01f508218e9f2 (thanks to @RoyBregman from previous comment for noting)
