### ISSUE TITLE
Shaka Player getAdManager is undefined

### ISSUE THREAD

**Issue by tchmaple** [google/shaka-player#2678]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v3.0.1

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Own custom app

**If custom app, can you reproduce the issue using our demo app?**
demo app website is down

**What browser and OS are you using?**
Chrome, Windows 10

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
No

**What are the manifest and license server URIs?**

**What did you do?**

I want to have preroll ads before play video content, I following the guide (https://shaka-player-demo.appspot.com/docs/api/tutorial-ad_monetization.html) for Client Side Ads Insertion, but get player.getAdManager() is return undefined and thus cannot read property 'initClientSide' of undefined.

**What did you expect to happen?**
Ads can play when click video play button

**What actually happened?**

When click video player button, player will call player.init and player.load function.
After that I have an event listener to listen when player going to play, initialize ads and play ads.

player.on('canplay', function(event) {
   initializeIMA();
 });

function initializeIMA() {
   var adManager = player.getAdManager();
    console.log('adManager', adManager)
    var videoElement = document.getElementById("video");
    adContainer = document.getElementById('ad-container');
    adManager.initClientSide(adContainer, videoElement);
}

The console adManager is undefined, hence have error "Uncaught TypeError: Cannot read property 'initClientSide' of undefined".

**Comment by ismena** [comment]
Very interesting. 
Can I see the code sample for when you're creating and initializing the player object?
If you log the player object before calling getAdManager(), what do you get?
```
function initializeIMA() {
console.log('player', player);
}
```

**Comment by joeyparrish** [comment]
Did you include the IMA SDK as well as Shaka Player in your `<script>` tags?

**Comment by tchmaple** [comment]
> Did you include the IMA SDK as well as Shaka Player in your `<script>` tags?

Yes, I did included, initially I try manually add in IMA SDK, but I found out after ads play, shaka player return 6003 error, "Failed to execute 'setMediaKeys' on 'HTMLMediaElement': The existing ContentDecryptionModule object cannot be removed at this time".

After that only I realise shaka player latest version has this part, so I tried on this.

**Comment by tchmaple** [comment]
> Very interesting.
> Can I see the code sample for when you're creating and initializing the player object?
> If you log the player object before calling getAdManager(), what do you get?
> 
> ```
> function initializeIMA() {
> console.log('player', player);
> }
> ```

Thanks @ismena and @joeyparrish for the swift response.

Here is the player console:
![image](https://user-images.githubusercontent.com/38909614/85641879-74572400-b6c2-11ea-8311-b55da2a030b8.png)
 
And here is the code I initializing the player object:
From click video player button, will call `player.init()` and `player.play()`
```
player.init(self._license_server_url, self._ticket, self.token, {
    showNextBtn: self._showNextBtn
});

player.play(self._videoSrc, self._startMin);
```

```
player.init = function (license_server_url, ticket, token, config) {
      self.ticket = ticket;
      self.user_session_token = token;
      self.config = config;
      if(license_server_url)
          self.processLicenseUrl(license_server_url, ticket);
     self.initPlayer();
}

self.processLicenseUrl = function (license_server_url, ticket) {
      var $rootScope = angular.element(document).scope();
      var base_url = $rootScope.getAppConfig().base_url;
      self.license_servers = {
                'com.widevine.alpha': license_server_url,
                'com.microsoft.playready': license_server_url + '?XSSESSION=' + self.user_session_token + '&ticket=' + ticket + '&api=' + encodeURIComponent(base_url + '/mmapi/star'),
      }
}

self.initPlayer = function (video) {
    switch (platform.name) {
               case 'Chrome':
                    self.network_filter = true;
                    self.initShaka();
                    break;
                case 'IE':
                    self.network_filter = false;
                case 'Microsoft Edge':
                    self.network_filter = false;
                    self.initShaka();
                    break;
                default:
                    self.network_filter = true;
                    self.initShaka();
                    break;
            }
}

self.initShaka = function () {
            shaka.polyfill.installAll();
            if (shaka.Player.isBrowserSupported()) {
                self.video = document.getElementById('video');
                var player = new shaka.Player(self.video);
                self.player = player;

                var stream_config = window.playback_config.streaming;
                player.configure({
                    drm: { servers: self.license_servers },
                    streaming: stream_config
                })

                // Load additional config
                if(platform.os.family.toLowerCase() in window.playback_config.browser) {
                    if(platform.name.toLowerCase() in window.playback_config.browser[platform.os.family.toLowerCase()]) {
                        player.configure(window.playback_config.browser[platform.os.family.toLowerCase()][platform.name.toLowerCase()]);
                    }
                }

                player.getNetworkingEngine().registerRequestFilter(function (type, request) {
                    // Only add headers to license requests:
                    if (type == shaka.net.NetworkingEngine.RequestType.LICENSE && self.network_filter) {
                        // This is the specific header name and value the server wants:
                        request.headers['XSSESSION'] = self.user_session_token;
                        var message = window.btoa(String.fromCharCode.apply(null, new Uint8Array(request.body)));

                        // Encode the payload as JSON.
                        var obj = {
                            'ticket': self.ticket,  // Provide some arbitrary data.
                            'payload': message
                        };
                        request.body = JSON.stringify(obj);
                    }
                });
                player.getNetworkingEngine().registerResponseFilter(function (type, response) {
                    // Only manipulate license responses:
                    if (type == shaka.net.NetworkingEngine.RequestType.LICENSE && self.network_filter) {
                        var wrappedArray = new Uint8Array(response.data);
                        // Convert it to a string.
                        var wrappedString = String.fromCharCode.apply(null, wrappedArray);
                        // Parse the JSON string into an object.
                        var wrapped = JSON.parse(wrappedString);
                        // console.log("WRAPPED", wrapped);
                        var rawLicenseBase64 = wrapped.license;
                        // Decode it to a string.
                        var rawLicenseString = atob(rawLicenseBase64);
                        // Convert that string into a Uint8Array and replace the response data
                        // to feed it to the Widevine CDM.
                        response.data = new Uint8Array(rawLicenseString.length);
                        for (var i = 0; i < rawLicenseString.length; ++i) {
                            response.data[i] = rawLicenseString.charCodeAt(i);
                        }
                    }
                });
                player.addEventListener('error', self.onErrorEvent);
            } else {
                // This browser does not have the minimum set of APIs we need.
                console.error('Browser not supported!');
            }
        }

     player.play = function (manifest, startTime) {
            if(!self.plyrInstance)
                self.initPlyr();
            self.player.load(manifest, startTime).then(function () {
                self.plyrInstance.play();
            }).catch(self.onError);
      }

 self.initPlyr = function () {
            if(self.config.linearVod) {
                var options = {
                       // ...
                }
            }
            else if(self.config.embededPlayer) {
                var options = {
                    // ...
                }
            }
            else {
                var options = {
                   // ...
                }
            }
            var plyrInts = plyr.setup(self.video, options);
            self.plyrInstance = plyrInts[0];
 }

```

**Comment by ismena** [comment]
Alright, I don't think your player is our player :)
The player object from your console seems to be your custom wrapper around shaka and other components of your app.
In the initShaka() method, I see you creating a new shaka.Player() object and assigning it to self.player:
```
// This bit
var player = new shaka.Player(self.video);
self.player = player;
```
I assume `self` is your "big" player object in this context (correct me if I'm wrong!).
I also see that at logging time, your `player.player` is `null`.
Can you verify that `initShaka()` gets called before you land inside `initializeIMA()`? (Put a log statement there or something. Ultimately, you want to make sure your `player.player` is a `shaka.Player` instance once you're inside `initializeIMA()`).

Then, what you want to call is not `player.getAdManager()` (this is your "outer" player. not the Shaka one), but `player.player.getAdManager()`.

Does it make sense?

**Comment by tchmaple** [comment]
> Alright, I don't think your player is our player :)
> The player object from your console seems to be your custom wrapper around shaka and other components of your app.
> In the initShaka() method, I see you creating a new shaka.Player() object and assigning it to self.player:
> 
> ```
> // This bit
> var player = new shaka.Player(self.video);
> self.player = player;
> ```
> 
> I assume `self` is your "big" player object in this context (correct me if I'm wrong!).
> I also see that at logging time, your `player.player` is `null`.
> Can you verify that `initShaka()` gets called before you land inside `initializeIMA()`? (Put a log statement there or something. Ultimately, you want to make sure your `player.player` is a `shaka.Player` instance once you're inside `initializeIMA()`).
> 
> Then, what you want to call is not `player.getAdManager()` (this is your "outer" player. not the Shaka one), but `player.player.getAdManager()`.
> 
> Does it make sense?

Actually is shaka player, but I am using own custom wrapper, for others shaka function like `getVariantTracks()` or `selectVariantTrack()` are able to function perfectly. 

I have checked another console before `initializeIMA()`. player is not null.
![image](https://user-images.githubusercontent.com/38909614/85816541-3b8c7d00-b79e-11ea-8550-64e05f82aa9e.png)

This is the player object:
![image](https://user-images.githubusercontent.com/38909614/85816616-6ecf0c00-b79e-11ea-9b7e-8b93d7100ae7.png)

But player.getAdManger() still return undefined, thus I am getting this error.
![image](https://user-images.githubusercontent.com/38909614/85816811-e2711900-b79e-11ea-8d97-15553d8bdfd4.png)

**Comment by ismena** [comment]
Making sure - even player.player.getAdManager() returns undefined?
Is your app hosted somewhere we could take a look at it?

**Comment by tchmaple** [comment]
> Making sure - even player.player.getAdManager() returns undefined?
> Is your app hosted somewhere we could take a look at it?

Apologize, player.player.getAdManager() can play ads. Thanks for helps.

However, I have another issues, the event listener is not working:

```
adManager.addEventListener(
 google.ima.AdEvent.Type.STARTED,
 onAdsStart);

 adsManager.addEventListener(
   google.ima.AdEvent.Type.COMPLETE,
   onAdCompleted);
```

May I know for ads event listener is there any example?

**Comment by tchmaple** [comment]
@ismena, I have found out this worked for me. 

```
adsManager.addEventListener(
        shaka.ads.AdManager.AD_STARTED, 
        onAdsStart);
```

Thanks for your help! Appreciate it much.

**Comment by ismena** [comment]
Glad we could help - please reach out in the future :)
