### ISSUE TITLE
Some Cast receivers tries to load HLS manifest from original URL after getting redirected

### ISSUE THREAD

**Issue by BoneGoat** [google/shaka-player#2679]
First, I don't know if this is a bug or not but the issue template directed me to submit a bug if I wasn't sure. Also, maybe this isn't a problem with Shaka but with the Google CAF receiver.

The general error we see is that some cast receivers tries to load HLS manifests from an incorrect URL after being redirected with 302. Now I haven't personally managed to reproduce the error. Tried all versions of official Google cast receivers. Having said that I am almost sure that this doesn't occur on initial load. We are logging every load request we get and none so far has tried to load an incorrect URL. Still we get errors like below.

So to my questions:
1. Is this a bug?
2. Is there any way of logging actual manifest http requests? Note that we already log all incoming load requests to the CAF receiver.

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes, found a similar problem for Dash which seems to be resolved: https://github.com/google/shaka-player/issues/1367 and https://github.com/google/shaka-player/issues/225

**What version of Shaka Player are you using?**
2.5.8

**Can you reproduce the issue with our latest release version?**
No, but we still get these errors from receivers

**Can you reproduce the issue with the latest code from `master`?**
No, not sure how to

**Are you using the demo app or your own custom app?**
Standard Google CAF receiver

**If custom app, can you reproduce the issue using our demo app?**
No

**What browser and OS are you using?**
Whatever the cast hardware is using

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Whatever the cast hardware is using

**What are the manifest and license server URIs?**
https://sverigesradio.se/topsy/direkt/srapi/164.hls

**What did you do?**
Some cast receivers will get confused when loading HLS-manifests from a server which does 302 to the real URL.
https://sverigesradio.se/topsy/direkt/srapi/164.hls => https://live-cdn.sr.se/pool1/p3/p3.isml/p3.m3u8
I have tried to reproduce this on all official Google cast receiver hardware but failed to do so. This does not happen on initial load but later. I know this because we log every load request we get and none so far has tried to load an incorrect URL.

Still, we get errors from the cast receivers that tries to load the m3u8 from the incorrect URL.

**What did you expect to happen?**
The cast receiver should load the HLS manifest from the redirected URL.

**What actually happened?**
```
Error: {"type":"ERROR","detailedErrorCode":300,"error":{"requestStatus":{"url":"https://sverigesradio.se/topsy/direkt/srapi/p3-audio=192000.m3u8","errorCode":6,"status":404,"responseHeaders":"content-type: text/html\r\ncache-control: private\r\ncontent-length: 16\r\n","response":"404 Not Found"}}}: Error: Error: {"type":"ERROR","detailedErrorCode":300,"error":{"requestStatus":{"url":"https://sverigesradio.se/topsy/direkt/srapi/p3-audio=192000.m3u8","errorCode":6,"status":404,"responseHeaders":"content-type: text/html\r\ncache-control: private\r\ncontent-length: 16\r\n","response":"404 Not Found"}}} at eval (webpack:///./src/receiver.js?:181:77) at https://www.gstatic.com/cast/sdk/libs/caf_receiver/v3/cast_receiver_framework.js:327:244 at Array.forEach (<anonymous>) at Mq (https://www.gstatic.com/cast/sdk/libs/caf_receiver/v3/cast_receiver_framework.js:327:206) at Kq._.h.dispatchEvent (https://www.gstatic.com/cast/sdk/libs/caf_receiver/v3/cast_receiver_framework.js:796:164) at Kq._.h.dispatchEvent (https://www.gstatic.com/cast/sdk/libs/caf_receiver/v3/cast_receiver_framework.js:796:147) at Kq._.h.dispatchEvent (https://www.gstatic.com/cast/sdk/libs/caf_receiver/v3/cast_receiver_framework.js:796:147) at Jr (https://www.gstatic.com/cast/sdk/libs/caf_receiver/v3/cast_receiver_framework.js:345:493) at Kr (https://www.gstatic.com/cast/sdk/libs/caf_receiver/v3/cast_receiver_framework.js:344:429) at Es._.h.Ip (https://www.gstatic.com/cast/sdk/libs/caf_receiver/v3/cast_receiver_framework.js:854:847)
```

We get these errors from cast receivers. I haven't found any way of getting hardware info on them so I don't know what kind of devices this affects. The receiver tries to load https://sverigesradio.se/topsy/direkt/srapi/p3-audio=192000.m3u8 when it should load https://live-cdn.sr.se/pool1/p3/p3.isml/p3-audio=192000.m3u8

**Comment by joeyparrish** [comment]
Sorry, but we can't take responsibility for CAF, since that's managed by the Cast team, and v2.5.8 is outdated.  The latest release from that branch is currently v2.5.13.

Can you reproduce this effect with Shaka Player v2.5.8 in our demo in a browser?  https://v2-5-8-dot-shaka-player-demo.appspot.com/   If not, it may be specific to CAF or the Cast device somehow.

Can you reproduce this effect with Shaka Player v2.5.13? https://v2-5-13-dot-shaka-player-demo.appspot.com/    If not, it is probably an issue we already fixed.  The Cast team should be updating CAF to use the latest Shaka Player soon.

You can also try Shaka Player v3 (https://v3-0-1-dot-shaka-player-demo.appspot.com/) or view our full index of all versions for easy back-testing: https://index-dot-shaka-player-demo.appspot.com/

Does this help?

**Comment by BoneGoat** [comment]
Hi, thank you for the response. I understand, it was a longshot. I will try your suggestions.
