### ISSUE TITLE
Define bitrate value for starting of adaptive streaming.

### ISSUE THREAD

**Issue by tbournez** [google/shaka-player#268]
Hello. 

Is it a way to define the bitrate for starting playback ? 

We want to start our video in good quality and not with the lowest quality.

Thanks and Regards

Thomas

**Comment by joeyparrish** [comment]
We don't have a direct way to do that right now.  I will add a configuration parameter for that in v2.0.

The way it works right now, your default bandwidth estimator has a hard-coded starting estimate that it uses until it collects enough data to make a good estimate.  This is a property of the default estimator, but the estimator can be replaced at runtime with your own.

So here are your options before v2.0 comes out:

1. modify [this.defaultEstimate_ in lib/util/ewma_bandwidth_estimator.js](https://github.com/google/shaka-player/blob/f21a725/lib/util/ewma_bandwidth_estimator.js#L67) (default is a conservative 500kbps)
2. inject your own implementation of [IBandwidthEstimator](https://github.com/google/shaka-player/blob/f21a725/lib/util/i_bandwidth_estimator.js) as the [third argument to DashVideoSource's constructor](https://github.com/google/shaka-player/blob/f21a725/lib/player/dash_video_source.js#L42), which can behave in any way you like
3. [disable adaptation](https://github.com/google/shaka-player/blob/f21a725/lib/player/player.js#L739) during your first playback and [select a track explicitly](https://github.com/google/shaka-player/blob/f21a725/lib/player/player.js#L554) until some time has passed and the estimator has enough data to make a good decision

Also, if your app plays multiple videos without reloading the page, you should also make sure you are [always providing an explicit bandwidth estimator instance to DashVideoSource](http://v1-6-2.shaka-player-demo.appspot.com/docs/tutorial-player.html#sample5).  That way, data collected from the first playback can be used to make an immediate good choice for subsequent playbacks.

**Comment by tbournez** [comment]
Thank you for your answer. I just try the first solution and it works. I'll try the 2 and 3 and choose the best. If we can have this in v2.0 it is great !!
