### ISSUE TITLE
how to find out what player settings in the example?

### ISSUE THREAD

**Issue by EduardWorrk** [google/shaka-player#2681]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
3.0.1 (2020-06-18)

**Please ask your question**

how to find out what player settings in the example?

https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://livesim.dashif.org/livesim/utc_head/testpic_2s/Manifest.mpd;panel=ALL_CONTENT;build=uncompiled

**Comment by ismena** [comment]
Hi @EduardWorrk! Which setting do you mean? If you open the hamburger menu in the top left corner of the demo page and click on different sections, you can see most current player configurations - are those what you wanted?
Programmatically you can run player.getConfiguration() to see the config object
`shakaDemoMain.player_.getConfiguration();` in the console of our demo page, if you want that specifically.

Does that help?
