### ISSUE TITLE
Question: Shaka Player Manifest Validator

### ISSUE THREAD

**Issue by interpegasus** [google/shaka-player#2682]
Hi I would like to know if there is a tool for validating a manifest.mpd file?

Thank you in advance.

**Comment by ismena** [comment]
Hm, there was a talk of doing that, but I don't think it ended up happening.
Am I right? @TheModMaker @joeyparrish

**Comment by TheModMaker** [comment]
We didn't end up making anything, but DASH-IF does have a validator: <https://conformance.dashif.org>

**Comment by interpegasus** [comment]
Perfect. Thank you very much for the update.
