### ISSUE TITLE
Stats event listener

### ISSUE THREAD

**Issue by JeffrinManovaPrabahar** [google/shaka-player#2684]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v2.5.9-debug

**Please ask your question**
Is there any event listener to listen for Stats change? Trying to implement something like "Stats for nerds" in youtube player but couldn't find a matching event listener. Any help on this?

http://v1-6-2.shaka-player-demo.appspot.com/docs/shaka.player.Stats.html

![Screenshot 2020-06-25 at 5 49 00 PM](https://user-images.githubusercontent.com/38453271/85718778-73e37b00-b70c-11ea-83ca-3d4629836f8c.png)

**Comment by joeyparrish** [comment]
You linked to the docs for Shaka v1.  I would recommend you check the docs for v2: https://shaka-player-demo.appspot.com/docs/api/shaka.extern.html#.Stats

Depending on what stats you care about, there are several events, but in general, you could also just poll them on some reasonable interval.

A few examples from the screenshot above:
 - Displayed resolution - get from player.getStats() or video.currentWidth, video.currentHeight.  No event for this is offered by the browser, so you would have to poll.
 - Selected track (may not be displayed yet) - get from player.getTracks(), filter for .active, listen for ['adaptation' events](https://shaka-player-demo.appspot.com/docs/api/shaka.Player.html#.event:AdaptationEvent) on player.
 - Volume - get from video.volume, listen for ['volumechange' events](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/volumechange_event) on video
 - Connection speed - get from player.getStats().estimatedBandwidth, no event available.  This is continuously evaluated as we fetch segments, so you'd have to poll.
 - Buffer - get from video.buffered, no event available from the browser, so you'd have to poll

As you can see, lots of these have to be polled, and where there are events, different pieces of information change on different events.  So my recommendation would be just to poll everything.

**Comment by JeffrinManovaPrabahar** [comment]
Hi @joeyparrish, thanks for the quick reply. Do you mean to add setInterval and listen for stats using getStats()? is that what you mean by poll?

**Comment by michellezhuogg** [comment]
@JeffrinManovaPrabahar , yes, you can use getVariantTracks() for audio/video tracks, and getTextTracks() for captions.

**Comment by joeyparrish** [comment]
Yes, that's correct.  Does this help?

**Comment by JeffrinManovaPrabahar** [comment]
Yes absolutely. Thanks.
