### ISSUE TITLE
Getting NaN & Null values when calling getStats & getVariantTracks functions on safari

### ISSUE THREAD

**Issue by JeffrinManovaPrabahar** [google/shaka-player#2685]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v2.5.9-debug

**Please ask your question**
On calling `player.getStats()`function on safari, I am getting following values.
estimatedBandwidth: NaN
height: NaN
width: NaN
droppedFrames: 0 (doesn't seem to change)

![Screenshot 2020-06-26 at 11 45 40 AM](https://user-images.githubusercontent.com/38453271/85826928-c7080d00-b7a2-11ea-8845-cd22cb881989.png)

On calling `player.getVariantTracks()`function on safari, I am getting following values.
videoId: null
originalVideoId: null,
videoCodec: null,
mimeType: null,
frameRate: null,
pixelAspectRatio: null,
videoBandwidth: null

![Screenshot 2020-06-26 at 11 51 56 AM](https://user-images.githubusercontent.com/38453271/85827295-a1c7ce80-b7a3-11ea-8dd9-6410c2119bfa.png)

I am getting values like this only on safari. In chrome, they seem to work fine. Is that something to do with restriction on DRM protected content on safari?

https://v2-5-13-dot-shaka-player-demo.appspot.com/docs/api/shaka.extern.html#.Stats

**Comment by TheModMaker** [comment]
If you're playing HLS content on Safari, we default to using native `src=` playback.  When doing this, we don't have much info since the browser handles playback.  You can use MSE playback on Safari by setting the configuration `streaming.useNativeHlsOnSafari` to `false` but you can't do this for FariPlay content.
