### ISSUE TITLE
[HLS] Batch resolving subtitles' playlist on start

### ISSUE THREAD

**Issue by interlark** [google/shaka-player#2690]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?** yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** yes

**What version of Shaka Player are you using?** 3.0.1

I've met strange to me behavior when player start to download all available subtitles' playlists from master's playlist on load, any way to get rid of it? Such behavior makes player freeze on start.
![image](https://user-images.githubusercontent.com/20641837/85946180-eb5b1980-b95b-11ea-8904-c2db704486ab.png) 
![image](https://user-images.githubusercontent.com/20641837/85946319-04b09580-b95d-11ea-86f6-3a94574f528d.png)

**Comment by michellezhuogg** [comment]
Hello @interlark , could you please follow our bug report template, and provide us with more details to reproduce your issue? Thank you!
https://github.com/google/shaka-player/issues/new?assignees=&labels=&template=bug_report.md&title=

**Comment by TheModMaker** [comment]
This is working as intended for the moment.  We need all the metadata loaded during startup.  See #1936.

**Comment by interlark** [comment]
Ok, no lazy-load for manifests. Got it, thank you.
