### ISSUE TITLE
Allow TS in Safari when there is no mux.js

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#2695]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes

**Describe the solution you'd like**

Only reject TS content in Safari when mux.js is loaded

**Describe alternatives you've considered**

Keep current behavior

**Comment by TheModMaker** [comment]
I assume you are talking about MSE playback, right?  When using `src=`, we have no control over what content is being played.  Unfortunately, according to MSE, the browser reports that TS isn't supported.  So either Safari doesn't support TS when playing in MSE, or there is a bug in their query support so it returns false.  I'll check to see if we can play even without checking support.

**Comment by avelad** [comment]
Yes, I'm talking about MSE. See https://github.com/google/shaka-player/blob/master/lib/polyfill/mediasource.js#L42

**Comment by TheModMaker** [comment]
Ok, thanks for finding that.  We'll look into removing that or adding a flag.  According to #743, there are problems with playing TS through MSE.  But newer versions of Safari may have fixed this or there may be another workaround.

**Comment by avelad** [comment]
Since in new versions TS still does not work in MSE. I close this issue. Also, TS should stay only for Legacy content.
