### ISSUE TITLE
DASH CMAF with Widevine ERROR IN SHAKA using Azure Media Services 

### ISSUE THREAD

**Issue by MircoFiocchiSW** [google/shaka-player#2696]
**What version of Shaka Player are you using?**
Shaka 3.0.1

**Can you reproduce the issue with our latest release version?**
No

**Can you reproduce the issue with the latest code from `master`?**
No

**Are you using the demo app or your own custom app?**
In both

**What browser and OS are you using?**
Chrome and Firefox with Android

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Android v8+

**What did you expect to happen?**
Reproduce the content

**What actually happened?**
We have an issue we try to reproduce DASH CMAF  with DRM (Widevine).  The issues found in Chrome or Firefox with ANDROID.

**Comment by TheModMaker** [comment]
What error are you seeing?  You say you cannot reproduce with the latest `master`, does this mean it is fixed?  Can you provide a playable manifest URL that reproduces your error?

**Comment by MircoFiocchiSW** [comment]
Hi! I found that DASH require EME to reproduce video but firefox not support. In Chrome worked correctly.
