### ISSUE TITLE
Can't get shaka player to fetch more then the first chunk on live stream

### ISSUE THREAD

**Issue by OF1re** [google/shaka-player#2699]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
2.5.12

**Please ask your question**
Hi,
I'm trying to create a live stream of mpeg-dash with ffmpeg(version 3.4) and shaka-player
I'm streaming the frames to ffmpeg with python through pipe and this is the ffmpeg command I use:
`ffmpeg -re -f rawvideo -pix_fmt bgr24 -video_size 640x360 -i - -vcodec libx264 -preset ultrafast -tune zerolatency -f dash -window_size 10 -use_template 1 -use_timeline 0 -live 1 /srv/http/dash/stream.mpd`

Currently I'm using nginx as a server and I've created a simple index.html with the example from the Basic Usage section in the docs.

The problem I have with this is that I couldn't get it to load and play more then the first chunk. (checked with dev-tools in chrome in the network tab, it only asks for the mpd file, init-stream.m4s and chunk-stream0-00001.m4s)
I've tried to play with the configuration of shaka and the parameters of ffmpeg but could get it to work.
I've also tried using shaka player 3.0.0 and 3.0.1 but both of them don't request any chunk (with no errors in console)

The mpd file ffmpeg created while streaming looks like this:
<code>
&#60;?xml version="1.0" encoding="utf-8"?&#62; &#60;MPD xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="urn:mpeg:dash:schema:mpd:2011" xmlns:xlink="http://www.w3.org/1999/xlink" xsi:schemaLocation="urn:mpeg:DASH:schema:MPD:2011 http://standards.iso.org/ittf/PubliclyAvailableStandards/MPEG-DASH_schema_files/DASH-MPD.xsd" profiles="urn:mpeg:dash:profile:isoff-live:2011" type="dynamic" minimumUpdatePeriod="PT500S" suggestedPresentationDelay="PT10S" availabilityStartTime="2020-06-30T05:09:49Z" publishTime="2020-06-30T05:19:39Z" timeShiftBufferDepth="PT1M40.0S" minBufferTime="PT20.0S"&#62; &#60;ProgramInformation&#62; &#60;/ProgramInformation&#62; &#60;UTCTiming schemeIdUri="urn:mpeg:dash:utc:http-xsdate:2014" value="https://time.akamai.com/?iso"/&#62; &#60;Period id="0" start="PT0.0S"&#62; &#60;AdaptationSet id="0" contentType="video" segmentAlignment="true" bitstreamSwitching="true" frameRate="25/1"&#62; &#60;Representation id="0" mimeType="video/mp4" codecs="avc1.f4001e" bandwidth="57572937" width="640" height="360" frameRate="25/1"&#62; &#60;SegmentTemplate timescale="1000000" duration="10000000" initialization="init-stream$RepresentationID$.m4s" media="chunk-stream$RepresentationID$-$Number%05d$.m4s" startNumber="1"&#62; &#60;/SegmentTemplate&#62; &#60;/Representation&#62; &#60;/AdaptationSet&#62; &#60;/Period&#62; &#60;/MPD&#62;
</code>
Am I missing something with the way I use ffmpeg or shaka-player?
Thanks in advance!

**Comment by michellezhuogg** [comment]
Hello @OF1re ,

Would you please validate your content via https://conformance.dashif.org/ ?
If the content is valid, would you please send us the URL (on Github or email: shaka-player-issues@google.com ), so that we can reproduce the issue?
Thanks!

**Comment by OF1re** [comment]
Hi @michellezhuogg ,

Sorry for the delay, sadly the site for the validation didn't work for some time due to disk space issues and there are some open github issues about it (https://github.com/Dash-Industry-Forum/DASH-IF-Conformance/issues/515 and https://github.com/Dash-Industry-Forum/DASH-IF-Conformance/issues/516).
It works now and I run the validator with the additional tests of 'Segment Validation'  and 'DASH-IF' tests and I get no warning or errors on the manifest file.

Here are the full steps I've done:
1. My machine is Ubuntu 14.04.5 LTS, I'm using python 3.6.5 and ffmpeg 4.3 and nginx 1.4.6 (i guess any other server would work)
2. I've created a simple http server with nginx at /srv/http/dash/
3. I've created a simple python script which read frames from a stream, manipulate the frame and sends the new frame to ffmpeg.
Here is a close enough code to what I do without any manipulation of the frame.
```
import numpy as np
import sys
import cv2
import subprocess as sp
import shlex

command = "ffmpeg -re -f rawvideo -pix_fmt bgr24 -video_size 640x360 -i - -vcodec libx264 -preset \
ultrafast -tune zerolatency -f dash -window_size 10 -use_template 1 -use_timeline 0 -live 1 -utc_timing_url https://time.akamai.com/?iso \
-minimum_update_period 1 -time_shift_buffer_depth 10 /srv/http/dash/stream.mpd"
command = shlex.split(command)

stream_path = '/home/user/dash/example.mp4'

def resize_frame(frame, size):
    return cv2.resize(frame, size, interpolation=cv2.INTER_CUBIC)

def process_frame(frame):
    return frame

def main():
    proc = sp.Popen(command, stdin=sp.PIPE,shell=False)
    
    while True:
        cap = cv2.VideoCapture(stream_path)
        while(cap.isOpened()):
            ret, frame = cap.read()
            if ret:
                new_frame = process_frame(frame)
                new_frame = resize_frame(new_frame, (640, 360))
                proc.stdin.write(new_frame.tostring())
            else:
                break
    
if __name__ == "__main__":
    main()
```
Change 'stream_path' value to a path to any media file you have on your machine

4. This is my index file at /srv/http/dash/index.html 

```
<!DOCTYPE html>
<html>
	<head>
		<!-- Shaka Player compiled library: --> 
		<script src="https://cdnjs.cloudflare.com/ajax/libs/shaka-player/2.5.12/shaka-player.compiled.js"></script>
		<script>
			var manifestUri = 'stream.mpd';
      
			function initApp() {
				// Install built-in polyfills to patch browser incompatibilities.
				shaka.polyfill.installAll();
				// Check to see if the browser supports the basic APIs Shaka needs.
				if (shaka.Player.isBrowserSupported()) {
				// Everything looks good!
					initPlayer();
				} else {
				// This browser does not have the minimum set of APIs we need.
					console.error('Browser not supported!');
				}
			}

			function initPlayer() {
				// Create a Player instance.
				var video = document.getElementById('video');
				var player = new shaka.Player(video);
				// Attach player to the window to make it easy to access in the JS console.
				window.player = player;
				// Listen for error events.
				player.addEventListener('error', onErrorEvent);
				// Try to load a manifest.
				// This is an asynchronous process.
				player.load(manifestUri).then(function() {
					// This runs if the asynchronous load is successful.
					console.log('The video has now been loaded!');
				}).catch(onError);  // onError is executed if the asynchronous load fails.
			}

			function onErrorEvent(event) {
				// Extract the shaka.util.Error object from the event.
				onError(event.detail);
			}

			function onError(error) {
				// Log the error.
				console.error('Error code', error.code, 'object', error);
			}

			document.addEventListener('DOMContentLoaded', initApp);
		</script>
		<style>
			video {
				width: 640px;
				height: 480px;
			}
		</style>
	</head>
	<body>
	<video id="video" width="640" controls autoplay></video>
	<div>
	</div>

	</body>
</html>
```

5. Run the python file and go to the index.html in chrome, you are supposed to get the same results I had, only the first chunk is being loaded and after a while when ffmpeg deletes old chunks it not loading anything when you refresh. (if you'll change player to the latest version, even the first chunk won't be loaded)

6.  Whenever you kill the python process you'll see that you are now able to play the stream (ffmpeg edits the manifest from dynamic to static) but you couldn't play more than the first chunk when it's live streaming. (I've run the validator for both the dynamic and static manifests and they both pass with no errors or warning)


Thanks!

**Comment by OF1re** [comment]
Hi, I've managed to get my intended behavior by adding the flag '-single_file 1' to the ffmpeg command.
I've also changed version to 3.0.1 and it works there too.

I'm not really sure if mpeg-dash protocol wanted live streams to be presented as single file or not, so I don't know if it's cosidered a bug or not.

Also, 3.0.1 and 2.5.12 behave differently in live streaming with the current example I gave but with the flag 'single_file' for ffmpeg.
When looking at the network tab in chrome devtools, 2.5.12 asks the server only for the needed chunks and the status code of the mp4 request is always 206(Partial Content).
In 3.0.1 it seems to do that while asking for the full mp4 file at the same time, which means there is a lot of wasted traffic when using version 3.0.1.

**Comment by TheModMaker** [comment]
If this is still an issue for you, please post a playable manifest URL.  Just using the manifest text or a command-line isn't enough for us to debug this; we'd need to see the whole content to be able to debug this.  You can send it privately to <shaka-player-issues@google.com> if you prefer.
