### ISSUE TITLE
When does Shaka support AAC HE audio codec? 

### ISSUE THREAD

**Issue by MegaLabs1** [google/shaka-player#270]
When does Shaka support AAC HE audio codec? I switched to use AAC-LC audio, but AAC HE is more  preferable.

**Comment by joeyparrish** [comment]
Shaka is codec-agnostic.  It supports whatever the browser supports.  Codec support is checked via MediaSource.isTypeSupported() for all media and navigator.requestMediaKeySystemAccess() for encrypted media.

Shaka treats Representations that the browser can't play as if they don't exist.  So your manifest can have multiple audio codecs, and Shaka will choose one that the browser supports.

Does that answer your question?

**Comment by MegaLabs1** [comment]
Yes, i am satisfied with your answer, thanks.

**Comment by joeyparrish** [comment]
No problem. Always happy to help.
