### ISSUE TITLE
About the current support status of HLS

### ISSUE THREAD

**Issue by st-oka** [google/shaka-player#2700]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.01

**Please ask your question**
Hi,
I'd like to know which browser Shaka Player supports HLS, but I couldn't find it even after checking the tutorial:
https://github.com/google/shaka-player#platform-and-browser-support-matrix
Currently, Is it possible to play with HLS on major browsers (Chrome, IE, Edge, and Firefox) besides Safari,
If not, do you have any plans to support it in the future?
Thanks in advance.

**Comment by michellezhuogg** [comment]
Hello @st-oka ,
Yes, we support HLS playback on major browsers. You can take a look at our demo page with HLS manifests:
https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;panel=ALL_CONTENT;panelData=HLS;build=uncompiled
We're ending support for IE 11 soon. https://github.com/google/shaka-player/issues/2339

**Comment by fingerartur** [comment]
The link leads to a content-less page

**Comment by TheModMaker** [comment]
If you have an ad blocker, that version fails to load.  Try this: https://shaka-player-demo.appspot.com/demo/#build=compiled

**Comment by st-oka** [comment]
Hi michellezhuogg,
Thank you for your prompt reply! I've confirmed that Shaka Player also works on major browsers through the demo page.
One more thing, could you please tell me about the support status of HLS + AES-128.
I got a '4034' when checked it, and guess it's not supported.

**Comment by st-oka** [comment]
I should have seen other Issues before asking you.
As mentioned in https://github.com/google/shaka-player/issues/850, it's not supported due to some issues now, is it?

**Comment by TheModMaker** [comment]
You are correct, we don't support AES-128.  You can follow that issue to get updates and know when we add support.

**Comment by st-oka** [comment]
Thank you for your reply, I understood the current situation.
Incidentally, I'm trying to playback HLS with Widevine or Playready, however it also doesn't seem to support.
I'd like to ask you about the support status of them. As others have pointed out it (https://github.com/google/shaka-player/issues/1145), is this understanding of mine correct?

**Comment by joeyparrish** [comment]
A DRM system must be built into the browser.  Shaka Player supports Widevine in HLS, so long as your browser has a Widevine CDM (Firefox, Chrome, Opera, smart TVs).  Shaka Player does not yet support PlayReady in HLS, but that could be done in the future on browsers with a PlayReady CDM (Edge, smart TVs).
