### ISSUE TITLE
Shaka Player Podding Ads

### ISSUE THREAD

**Issue by tchmaple** [google/shaka-player#2705]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v3.0.1

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Own custom app

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
Chrome, Windows 10

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
-

**What are the manifest and license server URIs?**

**What did you do?**

I need an event listener to track if ads completed, will need to remove the ads container. However, for podding ads, using `shaka.ads.AdManager.AD_COMPLETE`, it will remove the ads container after first ads completed, without playing the second ads. 

**What did you expect to happen?**
Play all the podding ads, after all ads complete, only remove the ads container.

**What actually happened?**

Shaka player ads event listener do not have `ALL_ADS_COMPLETED`. (Fired when the ads manager is done playing all the ads.)
Google IMA source: https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/reference/js/google.ima.AdEvent

Without this, I cannot remove my custom ads container. If I use `shaka.ads.AdManager.AD_COMPLETE`, it will remove my ads container after first ads completed. I need the `ALL_ADS_COMPLETED `event listener in order for me to play podding ads. 

Example of podding ads: https://pubads.g.doubleclick.net/gampad/ads?iu=/21764785206/Responsive/Responsive_Dimsum/Responsive_Dimsum_SanlihBVOD/Responsive_Dimsum_SanlihBVOD_Pre_ISV&description_url=https://www.dimsum.my/&env=vp&impl=s&correlator=&tfcd=0&npa=0&gdfp_req=1&output=vast&sz=400x300|640x480&unviewed_position_start=1

There is no ads error event listener too, can you help to add that as well? (google.ima.AdErrorEvent.Type.AD_ERROR)
Google IMA source: https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/reference/js/google.ima.AdErrorEvent

Thanks for your help!

**Comment by tchmaple** [comment]
Hi, I found AD_STOPPED actually working for all ads completed and ads error event listener.
Thanks!

Source: https://shaka-player-demo.appspot.com/docs/api/shaka.ads.AdManager.html

**Comment by ismena** [comment]
Glad it's working for you with AD_STOPPED.

Just a quick note that we've added the [ALL_ADS_COMPLETED event](https://github.com/google/shaka-player/blob/2386d4ea99b9be8e6ffd592b6f3d87d586c2b230/lib/ads/ad_manager.js#L821), and it will appear in the next release.
