### ISSUE TITLE
Demo page breaks when uBlock Origin extension is on

### ISSUE THREAD

**Issue by naktinis** [google/shaka-player#2706]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes.

**What link can we use to reproduce this?**
https://shaka-player-demo.appspot.com/demo/#audiolang=en-GB;textlang=en-GB;uilang=en-GB;panel=HOME;build=uncompiled
https://shaka-player-demo.appspot.com/demo/

**What version of Shaka Player are you using?**
v3.0.1-uncompiled

**What browser and OS are you using?**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36

**What did you do?**
Open Firefox 78, navigate to https://shaka-player-demo.appspot.com/demo/.

**What did you expect to happen?**
The demo page to load.

**What actually happened?**
The page didn't finish loading and there was an exception in the console (TypeError: shaka.ads.AdManager is undefined).
<img width="658" alt="image" src="https://user-images.githubusercontent.com/657600/86359829-6cbaf080-bc69-11ea-8f67-de8adaae35c3.png">

**Comment by michellezhuogg** [comment]
Hello @naktinis ,

This version fails to load with an ad blocker. You can use the compiled version.
https://shaka-player-demo.appspot.com/demo/#build=compiled

**Comment by joeyparrish** [comment]
The reason, as far as we can tell, is that the ad blocker stops any URL with "ad" in it, which includes part of the Shaka Player source code.  Shaka was never designed to run with arbitrary pieces of its source missing.

In compiled mode, the demo loads a single bundle which is not stopped by the ad blocker.

**Comment by TheModMaker** [comment]
This was also fixed recently to show a helpful error and load the footer so you can switch to compiled mode.
