### ISSUE TITLE
stream 4K HEVC live doesn't respond on LG WEBOS 4

### ISSUE THREAD

**Issue by Yuvalke** [google/shaka-player#2707]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

Yes

**What version of Shaka Player are you using?**

v3.0.1 and v2.15.2

**Can you reproduce the issue with our latest release version?**

Yes

**Can you reproduce the issue with the latest code from `master`?**

**Are you using the demo app or your own custom app?**

custom app with shaka debug v2 log.

**If custom app, can you reproduce the issue using our demo app?**

Yes

**What browser and OS are you using?**

Webos 3.5 and Webos 4

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

05.10.40

**What are the manifest and license server URIs?**

sent to email - manifest and logs.

**What did you do?**

play the source.

**What did you expect to happen?**

the stream will play.

**What actually happened?**

stream doesn't respond after play.

**Comment by OrenMe** [comment]
Hi Shaka team - a few more notes on the issue:
Stream is playing correctly on dash.js, not sure what is the difference.
If you limit the representations then playback works correctly on Shaka, meaning if you take the manifest and erase 2 out of 3 representations playback will start so it is something related to the switching.

The logs don't show any errors so it is a bit hard to understand where to start debugging, so even a hint here will maybe help us understand where to start. Would greatly appreciate your help.

**Comment by joeyparrish** [comment]
We don't have a WebOS device in our lab yet, so WebOS is officially a community-supported platform.  There's not much we can do directly.

You could try using the `abr.restrictions` configuration in the player to limit the resolution to <4K.  Does that change things?

**Comment by Yuvalke** [comment]
Hi @joeyparrish - I found out that the LG TV clock doesn't sync with a server time clock. 
I also found out that it's not possible to use `autoDrift=true` with external clock sync - in dash_parser.js `usingPresentationStartTime` will always be false when `autoDrift=true` and `setClockOffset` won't set, doesn't clock sync suppose to work in this case?

**Comment by joeyparrish** [comment]
If your live stream DASH content does not include a `<UTCTiming>` element, you should definitely supply a `manifest.dash.clockSyncUri` configuration to compensate.

Clock syncing is always used with DASH content that uses `<SegmentTemplate duration=...>`.

If the content uses `<SegmentList>` or `<SegmentTimeline>`, then clock syncing is not necessary.  With `manifest.dash.autoCorrectDrift` set to `true` (the default), we will ignore `availabilityStartTime` and base the live edge calculations on the list of segments instead.

If you set `manifest.dash.autoCorrectDrift` to `false`, then you will need to include a `<UTCTiming>` element or `manifest.dash.clockSyncUri` configuration for all live DASH content.

Does this help?

**Comment by Yuvalke** [comment]
Thanks @joeyparrish, it helps but I don't understand if the manifest includes`<SegmentTemplate>` and `<SegmentTimeline>` then clock syncing is not necessary as well?

**Comment by joeyparrish** [comment]
That's correct.  Assuming `manifest.dash.autoCorrectDrift` has its default setting of `true`, `<SegmentTemplate>`+`<SegmentTimeline>` means we have enough information in the manifest without an accurate clock.  This is different from `<SegmentTemplate>` with a fixed `duration=` attribute, in which case we must have an accurate clock to compute the available segments.

**Comment by joeyparrish** [comment]
Quick update, though I'm sorry it's not more helpful:

We still don't have access to a WebOS TV, and we can't officially support this platform, so we can't work on this ourselves.

Here's one suggestion for debugging:

Since 4k resolution is failing, and you suspect it has something to do with switching resolutions, try setting this config before playback to see what happens:

```js
player.configure('abr.restrictions.minHeight', heightOf4kStreams);
```

This will force the player to begin playback at 4k and will also disable switching (assuming 4k is the largest stream you have).  If this works, it must be something to do with switching resolutions.  If it fails, the 4k stream itself may be the problem.

**Comment by joeyparrish** [comment]
@Yuvalke, does this mean you have resolved the issue on your side?

**Comment by Yuvalke** [comment]
> @Yuvalke, does this mean you have resolved the issue on your side?

@joeyparrish we upgraded to 3.0.4 and it resolved the problem, thanks for your help

**Comment by joeyparrish** [comment]
Thanks for the update!
