### ISSUE TITLE
[HLS] Load master manifest from string

### ISSUE THREAD

**Issue by interlark** [google/shaka-player#2713]
According to API, Shaka-player can load manifest urls, but what if I don't have master url?
How can I load stream with self-generated master manifest?
Like that,
```javascript
const masterPlaylistContent = `
#EXTM3U
#EXT-X-STREAM-INF:CODECS="avc1.4d401f,mp4a.40.2"
http://localhost/chunks.m3u8
`;
const video = document.createElement('video');
let player = new shaka.Player(video);
player.load(masterPlaylistContent);
```

**Comment by joeyparrish** [comment]
You should be able to encode that into a [data URI](https://en.m.wikipedia.org/wiki/Data_URI_scheme), which Shaka Player supports by default.  Be sure to set the MIME type in the URI to indicate that it's HLS.

Does this help?
