### ISSUE TITLE
Stopping when seeking while playing Video in full screen on Mobile Safari

### ISSUE THREAD

**Issue by taka-sho25** [google/shaka-player#2715]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.1

**Please ask your question**
Hi.

When the video is full screen in Safari on iPhone, the playback stops when you seek the playback time.

Manifest got Fragment, but when seeking, type=keyframes is added and Keyframes are displayed instead of Fragment.

Error etc. were not displayed in the console.

Can't I play it back after Seek is finished?
The same video was possible with Azure Media Player.

Thank you.

**Comment by michellezhuogg** [comment]
Hello @taka-sho25 ,
We support iOS 12+ through Apple's native HLS player. We provide the same top-level API, but we just set the video's src element to the manifest/media. So we are dependent on the browser supporting the manifests.

**Comment by taka-sho25** [comment]
@michellezhuogg 

Thanks!

We decided to style the full screen screen ourselves!
