### ISSUE TITLE
Looking for Current Segment Length

### ISSUE THREAD

**Issue by adrianmui** [google/shaka-player#2717]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.11

**Please ask your question**
Is there a way to get the current segment lengths? Currently we're using `this.shaka.getManifest().presentationTimeline.getMaxSegmentDuration()`, but i'm not sure it's entirely accurate as segment lengths may not always be the same. Thanks so much!

**Comment by michellezhuogg** [comment]
getMaxSegmentDuration() returns the max segment duration among all segments, so it's not the same as the current segment length.
Are you looking for the current segment duration being played? Or the duration for every segment that gets fetched?
If it's the current segment duration being played:
-- We fetch the segments the append the buffer to MediaSource, so we don't track which segment is being played at the current time.
If it's the duration for every segment that gets fetched:
-- [StreamingEngine](https://github.com/google/shaka-player/blob/ec3bf7aaa5cca66325a002439df2b9cdc5352959/lib/media/streaming_engine.js#L1180) logs the start time and end time of the segment that gets fetched, and you can calculate the segment duration based on that. 
Would that help?
