### ISSUE TITLE
Preferred IDE for ShakaPlayer Developement

### ISSUE THREAD

**Issue by ravi01** [google/shaka-player#2718]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**

YES
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
YES

**What version of Shaka Player are you using?**
N/A

**Please ask your question**
I am trying to locally build and test shaka player. I have the codebase cloned, I am interested in knowing if I can use VSCode for local development. Is there some documentation around which IDE's can be used and how to set them up for development ?

**Comment by michellezhuogg** [comment]
Hello @ravi01 ,

You can use any IDE you like to edit, and VSCode works. 
The steps in the [tutorial](https://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html) is everything you need to setup Shaka Player.
