### ISSUE TITLE
Getting drm info from player

### ISSUE THREAD

**Issue by pajong** [google/shaka-player#272]
Hello,
I am trying to get drm info, but since EmeManager is a private property in player (https://github.com/google/shaka-player/blob/c103cf70d8fde2363d6ebfd15ab1142cd5e3f0cb/lib/player/player.js#L95), it is not possible to get the drm info.

Can I get some suggestions?

Thank you!

**Comment by tdrews** [comment]
For protected content, you provide a callback to `DashVideoSource` that the library invokes each time it encounters a `<ContentProtection>` element in your manifest. Each time that callback is invoked you return a `DrmInfo.Config` object for that `<ContentProtection>` element. The `DrmInfo` objects inside `EmeManager` contain the information that your application should have provided itself, so you shouldn't really need to access them.

See https://shaka-player-demo.appspot.com/docs/tutorial-player.html, specifically the "Protected Content" section for an example.

**Comment by pajong** [comment]
@tdrews Thank you for the response.
In my content protection callback, I handle both widevine and playready. In the case where the manifest contains both of these content protections, it is not possible to know which one is used to play the video unless I look into the drmInfo.

**Comment by tdrews** [comment]
I see. So you want to support both Widevine and Playready without your application explicitly choosing one, but you want to know which one the library chose? Is this right?

**Comment by pajong** [comment]
Yes, that is correct.

**Comment by tdrews** [comment]
Well, there's no explicit mechanism at the moment. However, on Chrome the key system will be Widevine, and on IE the key system will be Playready; you could determine this via `navigator.userAgent`. Would that work as an interim solution while we look into what we might want to do for Shaka 2?

**Comment by pajong** [comment]
@tdrews Yes, that will work for an interim solution. Thank you so much!

**Comment by joeyparrish** [comment]
We will consider exposing a key-system ID after 2.0.  If there are more people interested in this feature, please speak up here and let us know.

**Comment by vincentma** [comment]
@tdrews By checking `navigator.userAgent`, it might be workaround here. However, if we are going use Shaka player in Chromecast (replace its own MediaPlayerLibary), then it might be a problem here because Chromecast support both playready and widevine.

https://developers.google.com/cast/docs/media#delivery-methods-and-adaptive-streaming-protocols

**Comment by tdrews** [comment]
Good point. I'm going to bump this up to a v2.0.0 goal.
