### ISSUE TITLE
Stream playing on DASH.js but not on latest Shaka-player

### ISSUE THREAD

**Issue by pajong** [google/shaka-player#2720]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v2.5.2, but also verified that the issue is not fixed on the latest version (v3.0.1)

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
No

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
MacOS v10.14.4, Chrome 83.0.4103.116

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**
https://bitdash-a.akamaihd.net/content/sintel/sintel.mpd

**What did you do?**

1. Go to https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://bitdash-a.akamaihd.net/content/sintel/sintel.mpd;panel=CUSTOM%20CONTENT;build=uncompiled
2. Try playing thee stream

Notice that the stream is not playing, and buffering infinitely.

Please also note that this works fine in DASH.js (https://reference.dashif.org/dash.js/v3.1.1/samples/dash-if-reference-player/index.html)

**What did you expect to happen?**
Stream playing normally, from the start to the end (14m48s long)

**What actually happened?**
The player is frozen, infinitely buffering.
Screenshot:
<img width="1050" alt="a" src="https://user-images.githubusercontent.com/13631194/87177342-7f58a980-c2a9-11ea-9b26-0dbd10123043.png">

**Comment by TheModMaker** [comment]
This content isn't spec compliant.  Cue 22 only has two digits in the timestamp (i.e. `00:01:41.00` should be `00:01:41.000`).  We could be more permissive, but this is technically bad content (see the [spec](https://www.w3.org/TR/webvtt1/#webvtt-timestamp)).  We'd need to update [this regex](https://github.com/google/shaka-player/blob/e5d1068f9639bf2b17c56a5b36d8558736c8e5b8/lib/text/vtt_text_parser.js#L407) to be more permissive.
