### ISSUE TITLE
Skip 10 seconds button

### ISSUE THREAD

**Issue by Srikrishna-Adiga** [google/shaka-player#2721]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

**What version of Shaka Player are you using?**
3.0.1

**Please ask your question**
I want to add a 10 seconds skip feature button inside my shake player video. I am using plain javascript for my website. Is there a way to do this? Any help in the right direction is appreciated

**Comment by ismena** [comment]
Hi @Srikrishna-Adiga 
Just to confirm - are you using our shaka UI build? (Does you shaka script tag looks like `<script src="dist/shaka-player.**ui**.js"></script>` vs `<script src="dist/shaka-player.**compiled**.js"></script>` )
