### ISSUE TITLE
Shaka 2.5 is not raising DASH manifest timed metadata during period boundaries

### ISSUE THREAD

**Issue by TheSouryaRoy** [google/shaka-player#2723]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5

**Can you reproduce the issue with our latest release version?**
Not reproducible in Shaka 3.0.1

**Are you using the demo app or your own custom app?**
Own custom app (link below)

**If custom app, can you reproduce the issue using our demo app?**
Could not extract timed metadata from the demo app

**What browser and OS are you using?**
Chrome 83, MacOS 10.15.5

**What issue are you facing?**
We are playing a DAI stream on Shaka Player 2.5 with IMA SDK. This is a multi-period manifest with one ad in each period. During period boundaries (i.e. transition from current ad to next ad), we are observing that the first timed metadata event of the next period, or the last event of the current period fails to get raised.

This issue happens 50-60% of the time.

We tried to reproduce the issue on Shaka 3.0.1, but were unsuccessful.

**What did you do?**
1. Went to demo app: https://storage.googleapis.com/gvabox/sanils/h5/dai/shaka_test/dai_shaka.html
2. Entered `0ndl1dJcRmKDUPxTRjvdog` on the Asset Key field, if not already filled
3. Hit "Request Live"
4. Wait a few minutes if the issue is does not happen at the get go (we are able to observe the issue 50-60% of the time)

The timed metadata raised by Shaka player is shown in the console log. We compare that with the timed metadata events in the manifest file.

For reference, here is the manifest link: https://dai.google.com/linear/dash/pa/event/0ndl1dJcRmKDUPxTRjvdog/stream/24aa41be-f95c-4cb8-aab8-a73d1f717a59:ATL/manifest.mpd

**What did you expect to happen?**
All timed metadata events in the manifest are raised.

**What actually happened?**
During period boundaries, the last timed metadata of the current period or the first timed metadata of the next period is not raised.

**Additional screenshots & logs**
Sent to shaka-player-issues@google.com

**Comment by ismena** [comment]
@TheSouryaRoy 
We generally don't work on issues that manifest in previous releases, but not the latest one, and encourage people to upgrade to the latest release instead. I understand that v3.0.1 also needs attention in terms of DASH event reporting, and we're in the process of looking into those. 

Is that why you've gone back to using v2.5 or are there other reasons for it?

**Comment by TheSouryaRoy** [comment]
@ismena the reason we are exploring 2.5 is due to the issue in 3.0.1. If we can get 3.0.1 fixed, it should be fine for us. Thanks!

**Comment by ismena** [comment]
v3 is what the majority of users are gonna go with, so let us give fixing it our best shot before considering alternatives.
#2716 might take a bit of time to figure out due to its inconsistency and the length of the repro cycle, but we are committed to trying to get to the bottom of it, and there are still things we can look at to track it down.

I'm gonna close this issue for now. Let's get back to it in case we're completely at a dead end with #2716
