### ISSUE TITLE
How to get remaining time of the display ads

### ISSUE THREAD

**Issue by hooili** [google/shaka-player#2726]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
version : 3

**Please ask your question**
we have follow https://shaka-player-demo.appspot.com/docs/api/tutorial-ad_monetization.html and implemented streaming with client side ads insertion (google ima), but we do not know how to get remaining time of the display ads, could you please advise us on how to do it in shaka player.

here we share a gist regarding our ads implementation for your reference.
https://gist.github.com/hooili/b6614428a3d68cae1eb419efd80af253

thank you.

**Comment by ismena** [comment]
Hi @hooili 
If you listen to the ad manager's [AdStarted event](https://github.com/google/shaka-player/blob/606457488f77e9cf5cac2c82e94bb4ce35d50e2a/lib/ads/ad_manager.js#L30), you can get the ad object for the currently playing ad:

```
adsManager. addEventListener(shaka.ads.AdManager.AD_STARTED, (e) => {
    const ad = e['ad'];
    // For the ad's full duration
    const duration = ad.getDuration();
    // For the time remaining to play in the ad (like, if it's a 10 second ad and 5 seconds already played through, this value will 
    // be 5)
    const remainingTime = ad.getRemainingTime();
 });
```
Looking at your code, I think that you're already listening to the AdStarted event, so you might just want to extend that listener to look at the ad's duration or remaining time.

Does that help?

**Comment by hooili** [comment]
yes, we are able to get ad remaining time now. thank you.
