### ISSUE TITLE
Offline playback of already stored content

### ISSUE THREAD

**Issue by sarahachem** [google/shaka-player#273]
I have been checking the code for offline playback and what I understood is that we need to store the content first and then play it. Is it possible to play locally stored content directly without going through the storing process? I have a Widevine encrypted mp4 video file on the sd card of an android phone, is it possible to decrypt/play it using Shaka?
Thank you

**Comment by joeyparrish** [comment]
To play Widevine encrypted content, you still need a license to decrypt it.  Licenses are requested through the CDM and issued by the content provider.

It doesn't sound like your use-case is what Shaka was designed for.  You can't just grab a copy of an encrypted MP4 and play it back in a browser without considering the rest of the infrastructure that makes DRM work.

Does that answer your question?

**Comment by sarahachem** [comment]
Thank you for your reply.
Indeed a license is needed and will be provided through a licensing server, and then the video will be decrypted and played offline. 
As you mentioned, Shaka does not seem to be the appropriate solution for my use-case.

**Comment by joeyparrish** [comment]
If you're planning to fetch a temporary license for playback, but the content is stored offline, then it's not "offline" in the sense that Shaka uses the term.  For us, that would be a streaming or VOD playback.

The issues then become: can you access the content via a URL, and do you have a manifest for the video?  If both answers are "yes", then Shaka should be able to do this.
