### ISSUE TITLE
Best practices for mpd generation

### ISSUE THREAD

**Issue by Srikrishna-Adiga** [google/shaka-player#2732]
Suppose i have an admin who uploads an mp4 file and there users who view this videos. How do i convert this to mpd in the backend for adaptive streaming?

**Comment by ismena** [comment]
Please take a look at our sister project, [Shaka Packager](https://github.com/google/shaka-packager) that helps package content into mpd and m3u8 formats.

Also, for your mp4 files, do you already have them in all the resolutions/codecs that you need? If not and you want to re-encode your content in addition to packaging, you might be interested in [Shaka Streamer](https://github.com/google/shaka-streamer) instead.

**Comment by Srikrishna-Adiga** [comment]
Thank you for your answer. My use case is to take a mp4 from user and give an mpd and m3u8 for the shaka player. This is a web application module (built with PHP). Could you please guide me on how to use shaka packager and streamer. Thanks in advance.

**Comment by joeyparrish** [comment]
Here is where you start with Shaka Streamer:
 - https://github.com/google/shaka-streamer/blob/master/README.md
 - https://google.github.io/shaka-streamer/overview.html
 - https://google.github.io/shaka-streamer/prerequisites.html

Hope this helps!
