### ISSUE TITLE
IMA SDK Integration using FairPlay on Safari

### ISSUE THREAD

**Issue by hooili** [google/shaka-player#2733]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
version: 3

**Please ask your question**
Hi, we want to do IMA SDK integration using FairPlay on Safari, may i know how do we do streaming with client side ads insertion (google ima)? please advise, thank you.

**Comment by ismena** [comment]
Interesting question. I don't see why there would be any difference between the regular ad flow and the Safari one.
I don't think we have any FairPlay demo assets, but from my understanding of how Client Side IMA works, I don't think you have to do anything special to make it work.

Have you tried integrating your FairPlay assets with our ad API and run into any problems?

**Comment by hooili** [comment]
yes, thank you.
