### ISSUE TITLE
DASH no discrimitation of Accessibility subtitles for some combinations

### ISSUE THREAD

**Issue by hdodev** [google/shaka-player#2734]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes, it's directly related to item #2060, and the associated evolution made in 2.5.5 release.

**What version of Shaka Player are you using?**
2.5.10

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Custom App

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Firefox, on W10 and Ubuntu

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
NA

**What are the manifest and license server URIs?**
Manifest sent to shaka-player-issues@google.com with the ticket reference

**What did you do?**
Playback a DASH stream with some subtitles, and try to displays and use subtitles tracks using getTextTracks()/selectTextLanguage(). Here is an extract of my subtitles tracks supposed to be conform to ETSI TS 103 285 V1.2.1 (2018-03):

1)
```xml
<AdaptationSet id="6" group="8" bitstreamSwitching="true"
    segmentAlignment="true" contentType="text"
    mimeType="application/mp4" lang="fre">
<Role schemeIdUri="urn:mpeg:dash:role:2011" value="main" />
```
            
2)
```xml
<AdaptationSet id="7" group="8" bitstreamSwitching="true"
    segmentAlignment="true" contentType="text"
    mimeType="application/mp4" lang="fre">
<Accessibility schemeIdUri="urn:tva:metadata:cs:AudioPurposeCS:2007" value="2" />
<Role schemeIdUri="urn:mpeg:dash:role:2011" value="main" />
```

**What did you expect to happen?**
Subtitles are displayed with discrimination in getTextTracks() response:
For the 1st: "language": "fr", "roles": ["main"], "kind": "subtitle"
For the 2nd: "language": "fr", "roles": ["main"], "kind": "2"

**What actually happened?**
Subtitles are displayed without discrimination in getTextTracks() response:
For the 1st: "language": "fr", "roles": ["main"], "kind": "subtitle"
For the 2nd: "language": "fr", "roles": ["main"], "kind": "subtitle"

And even with the right "kind, I don't see how to use it in the selectTextLanguage() on wich "kind" is not an accepted  parameter...

Best regards

**Comment by hdodev** [comment]
Hi,

Any news about this item? Thanks in adavnce.

**Comment by hdodev** [comment]
Hi Joey,

OK let me just get all the information about this to clarify the cases, and then you'll could decide if you consider it as an interresting evolution.

**Comment by TheModMaker** [comment]
For text tracks, the way you set the kind is with a role of `caption` or `subtitle`.  For example, `<Role schemeIdUri="urn:mpeg:dash:role:2011" value="caption" />`.  You can have multiple Role tags to specify both main and the kind.  If you want some other identification for theses, I suggest a custom role tag (e.g. `<Role value="foobar" />`).

If you do either of them, you should be able to select by role value: `player.selectTextLanguage('fre', 'caption')`.

**Comment by hdodev** [comment]
Hi @TheModMaker  , thanks for the suggestions.

Let's consider that we will try this in packager side and I so close the ticket. If we manage to estimate that some norm can justify an evolution, I'll reopen the item.
