### ISSUE TITLE
Forcing usage of a specific codec

### ISSUE THREAD

**Issue by mikemerritt** [google/shaka-player#2735]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.13

**Please ask your question**
I'm transcoding both H.264 and H.265 in the same manifest. On a device that has proper support for H.265 Shaka Player is filtering out the H.265 variants and only using H.264. Is there a way to force the use of a specific codec (H.265 in this case) if there is support?

My specific use case is in a Vizio TV app that can only stream higher than 1080p if the H.265 codec is used, however, both H.264 and H.265 variants are needed for wide support of 4k and non-4k TVs. This was previously working when I was using a higher H.264 Profile Level but lowered some variants for better TV compatibility and now shaka player is always choosing H.264.

**Comment by ismena** [comment]
There isn't an "official" way to do it, although we have an open feature request for this: #2179 
I might be able to suggest a workaround to accomplish this though.

We use the initial stream choice to lock in the selected codec. If you manually select a track with the codec you want through our selectVariantTracks() API before we got a chance to pick anything, your selected codec will be the one locked in! :)

You can listen to our [streaming event](https://github.com/google/shaka-player/blob/master/lib/player.js#L302) to select the initial track before we started streaming.
Call [player.getVariantTracks()](https://github.com/google/shaka-player/blob/943bdb2b35e6d23d4fd3dfb7bad1b6524fd2abc7/lib/player.js#L3077) to get all the tracks, then select any one of them that has the [videoCodec](https://github.com/google/shaka-player/blob/943bdb2b35e6d23d4fd3dfb7bad1b6524fd2abc7/externs/shaka/player.js#L261) you want, and call [player.selectVariantTrack()](https://github.com/google/shaka-player/blob/943bdb2b35e6d23d4fd3dfb7bad1b6524fd2abc7/lib/player.js#L3223) with it.

Does this make sense?

 #2179 isn't scheduled yet, but I think it might get worked on in Q4

**Comment by mikemerritt** [comment]
Makes perfect sense. Thanks for the workaround.

**Comment by mikemerritt** [comment]
@ismena Testing this workaround and it appears that the variant tracks are already filtered when the streaming event is fired. I'm only seeing tracks for a single (h264) codec.

**Comment by ismena** [comment]
@mikemerritt Ah, sorry. Try the '[manifestparsed](https://github.com/google/shaka-player/blob/master/lib/player.js#L271)' event instead!

**Comment by ismena** [comment]
Hmm. That was my best idea :(
Let's get the big bros, see if they have more thoughts :)
@joeyparrish @TheModMaker any thoughts on what else might be a good stopping point to force a variant before the initial stream set is selected?

**Comment by joeyparrish** [comment]
Sorry, there does not seem to be a way to force the selection of a codec through the Shaka Player API at this time.  #2179 will track the feature request for that.

One (ugly) way you could hack it to do what you want would be to patch `MediaSource.isTypeSupported`.  For example, to disable AAC, you could do this:

```js
const origIsTypeSupported = MediaSource.isTypeSupported;
MediaSource.isTypeSupported = (type) => {
  if (/codecs="mp4a.40.2"/.exec(type)) {
    return false;
  }
  return origIsTypeSupported.call(MediaSource, type);
};
```

That will then affect all filtering operations done by Shaka Player.  It's not ideal, but we don't have a mechanism for this yet.

**Comment by mikemerritt** [comment]
@joeyparrish This works, thanks!.

For anyone else in this situation, here is what I ended up doing.

```javascript
      const origIsTypeSupported = MediaSource.isTypeSupported;
      const isHvcSupported = origIsTypeSupported.call(MediaSource, 'video/mp4;codecs="hvc1.1.6.L153.B0"');

      MediaSource.isTypeSupported = (type) => {
        if (isHvcSupported && /codecs="avc/.exec(type)) {
          return false;
        }
        return origIsTypeSupported.call(MediaSource, type);
      };

```
I check for HVC (H.265) support. Then patch `MediaSource.isTypeSupported` with a function that filters out all `avc` (H.264) types if HVC is supported.
