### ISSUE TITLE
About Video Audio sync part.

### ISSUE THREAD

**Issue by superbderrick** [google/shaka-player#274]
HI I am Derrick in korea, I have a one question. :)
I am making simple web dash player refer to shakaplayer.
While I was analyzing source code I have a one question about audio video sync.
I am testing with a dash content that composed of Segments Template audio video separates.
I guess that It will be compose of each source buffer into mediasource , But I wonder of how to sync between source buffers.

where can I see the source part in shakaplayer    and 

How to sync between video and audio ,  It seems to  decord just with segment referece start and end time , Isn't it?

Thanks Best Regards  

Derrick.

**Comment by joeyparrish** [comment]
Synchronization is handled by the browser's MediaSource implementation.  It uses the timestamps in the media segments themselves, combined with SourceBuffer's timestampOffset attribute.  Aside from applying the correct timestampOffset (which may not be needed, depending on your content/manifest), there is nothing JavaScript applications/libraries need to do to synchronize audio & video buffers.

Does that answer your question?

**Comment by superbderrick** [comment]
Thank you for your response. Yeah It is helpful.
Derrick.
