### ISSUE TITLE
Closed Captions default (ON, English) utilizing shaka.player.ui containter

### ISSUE THREAD

**Issue by ed-wosleger** [google/shaka-player#2744]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?** yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** yes

**What version of Shaka Player are you using?** 3.0

**Please ask your question**
We upgraded a support player from using 2.3.x to 3.0 taking advantage of the expanded shaka.utils library for Uint8ArrayUtils
Upgrading, broke our native player ui captions. Therefore we added new functionality with the shaka.ui lib:
`var video = this.videoElem;
  var playerContainer = document.getElementById('player-container');
 
  var player = new shaka.Player(video);
  var ui = new shaka.ui.Overlay(player, playerContainer, video);` 

This works correctly, however we (me) having difficulty auto enabling english captions on.

in the config I added the: 
`streaming: {
         alwaysStreamText: true
       }`

previously we had just set:
`if(toggleCaptions == true){
    var tracks = this.videoElem.textTracks;
    if(tracks.length > 0){
      tracks[0].mode = "showing";
    }
  }`
to auto enable captions.

**Comment by joeyparrish** [comment]
I believe you should be using `player.setTextTrackVisibility(true);` instead.  That will work in all cases.

Since you are using the UI, the captions will be displayed in DOM elements in the UI, not through the video element's `textTracks` interface.

Does this help?

**Comment by ed-wosleger** [comment]
I over thought that one. Thanks. Works perfect.
