### ISSUE TITLE
Returning to ABR mode not working

### ISSUE THREAD

**Issue by hooili** [google/shaka-player#2747]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
version: 3.0

**Please ask your question**
We are having an issue with re-enabling adaptation once user switches to a given quality manually and then attempts to switch back to auto.

steps to reproduced:
1. Start playing any content with multiple qualities.
2. Select some lower quality manually before the player adapts automatically to the highest possible one
3. Re-enable adaptation by enables ABR again

Expected behavior would then be that the player enables ABR again and adapts in a short while to the highest possible quality based on network conditions. But this does not happen, playback is stuck on the manually chosen quality.

We attempted to call in our player player.configure({ abr: { enabled: true } }); , but no difference on the chosen quality, ABR does not kick in.

Here i shared a gist on our implementation.
https://gist.github.com/hooili/43b6ac552fe0d01196f487bd35c9a1af

Please advise. Thank you.

**Comment by TheModMaker** [comment]
There are two things to note here: first, we don't replace existing segments when we enable ABR.  So if the video isn't playing, you won't see the resolution change.  Second, if we have buffered a lot ahead, then it will take a while for the change to be visible.  So if you set a large `streaming.bufferingGoal`, then it will take until the end of the buffer to see the new chosen resolution.

If you are playing the video, does the video eventually change to the new resolution?  Does ABR select the high resolution if you don't disable ABR (i.e. do we think we have enough bandwidth play it)?

**Comment by hooili** [comment]
@shaka-bot reopen
