### ISSUE TITLE
Flussonic and Wowza not working. 4000 error on .ism and .isml files 

### ISSUE THREAD

**Issue by Aremyre** [google/shaka-player#2749]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.1

**Please ask your question**
I created an application and it is loading DASH streams. At the moment we wanted to start using Flussonic or Wowza. These streams are using .isml and .ism. My question is can I stream these streams with the ShakaPlayer? I looked at https://github.com/google/shaka-player/issues/1328 and there @joeyparrish is saying dat ShakaPlayer only supports DASH and HLS. But when i tryed the link of Techerbium i got a .webm stream from the ShakaPlayer. I olso looked at https://github.com/google/shaka-player/issues/703 and smooth streams are not possible yet.

Is it possible to load .isml and or .ism streams with ShakaPlayer?

Error:
![image](https://user-images.githubusercontent.com/33829613/88177973-f2f3a280-cc29-11ea-8a7a-e938eef49577.png)

**Comment by joeyparrish** [comment]
Shaka Player has built-in support for DASH and HLS.  We don't support other formats directly.

You can add support for other formats by writing a ManifestParser plugin, but this is a very involved process.  A quick search confirms that both Wowza and Flussonic support both DASH and HLS content, so there's no reason you should have to add support for any other format.

If your "/manifest" URL is, in fact, a DASH manifest, it could just be that Shaka Player can't deduce this fact from the URL.  You may simply need to tell Shaka Player that it's DASH.  Try this:

```js
player.load(url, /* startTime */ null, "application/dash+xml");
```

Does this help?

**Comment by Aremyre** [comment]
Thank you @joeyparrish. For the fast response and for the explanation. 

I think I need to find a new way or need to write a custom ManifestParser plugin (https://shaka-player-demo.appspot.com/docs/api/tutorial-manifest-parser.html).

**Comment by joeyparrish** [comment]
@Aremyre, most people don't need a custom ManifestParser plugin.  Can we clarify a few points to save you the trouble?

1. Is the URL in your example (....isml/manifest) a DASH manifest URL?  (I've seen Azure URLs that look _exactly_ like this and _are_ DASH)
2. Does specifying the DASH MIME type in `load()` help at all?

**Comment by Aremyre** [comment]
Yes thanks. Am not using DASH or HLS and Shaka is not suporting that at the moment.
