### ISSUE TITLE
StreamVideoSource's setPlaybackStartTime not working

### ISSUE THREAD

**Issue by rohitpal99** [google/shaka-player#275]
Hi,
I have been trying to start Dash playback from a particular time and setPlaybackStartTime on stream source is not working. Playback always starts from 0.

I have explicitly checked for WebM files only.

Best Regards,
Rohit

**Comment by joeyparrish** [comment]
When do you call setPlaybackStartTime?  If you call it after streaming begins, it will have no effect.  Streaming begins when the MediaSource object sends a 'sourceopen' event, which happens some time after player.load() is called and before the returned Promise is resolved.

In Shaka 1, we recommend that you call this method before player.load().  In Shaka 2, playback start time will become an argument to player.load(), which should eliminate any confusion about timing.

Does this help?

**Comment by superbderrick** [comment]
Thank you for your response. Yeah It is helpful.
Derrick.
