### ISSUE TITLE
Controls UI  visibility discrepancy between shaka-player-ui.js & shaka-player.ui.debug.js

### ISSUE THREAD

**Issue by ed-wosleger** [google/shaka-player#2751]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?** yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** yes

**What version of Shaka Player are you using?** 3.0x

**Please ask your question**
After updating major shaka versions, we upgrade to shaka-player.ui 3.0x. 
We have made the additional implementation of the container-ui for the controls and captions
Initially for dev testing and building we were using the shaka-player.ui.debug.js, however as we moved closer to internal QA testing, I replaced the shaka-player.ui.debug.js, with the standard shaka-player.ui.js, of the same build deployment.
The controls panel & "bigPlayButton" disappeared.  Using browser tools "inspect element" I see the invisible container, however I do not see the UI elements.

Reiterating, everything works correctly when using the .debug version. The only difference is switch from .debug library to standard library.

controls.css is correctly linked.

player instantiation 👍 
```js
  var video = this.videoElem;
  var playerContainer = document.getElementById('video-container');
  var player = new shaka.Player(video);
  
  var ui = new shaka.ui.Overlay(player, playerContainer, video); 
  var controls =  ui.getControls();

  player.setTextTrackVisibility(true);
  window.player = player;
  window.ui = ui;
```

HTML code:
```html
<div data-shaka-player-container id="video-container">
	<video autoplay data-shaka-player id="shoany-player" style="width:100%;height:100%"></video>
</div>
```

**Comment by theodab** [comment]
So to be clear, you are doing something along these lines:
```html
<script src="../dist/shaka-player.ui.js"></script>
<link rel="stylesheet" href="../dist/controls.css">
<div data-shaka-player-container id="video-container">
	<video autoplay data-shaka-player id="shoany-player" style="width:100%;height:100%"></video>
</div>
<script>
  var video = document.getElementById('shoany-player');
  var playerContainer = document.getElementById('video-container');
  var player = new shaka.Player(video);
  var ui = new shaka.ui.Overlay(player, playerContainer, video);
  var controls =  ui.getControls();

  // Load an asset, etc.
</script>
```

I tried that code snippet, and I saw the controls just fine, with both the debug and non-debug version.

Now, you are making two overlays with this method; the `data-shaka-player-container` and `data-shaka-player` tags tell the UI library to make an overlay there, and then you make one manually inside the code. You should remove the tags, if you want to make an overlay manually. But I don't think that will cause the problems you are seeing.

**Comment by ed-wosleger** [comment]
I removed the redundant dataset tags : data-shaka-player-container and data-shaka-player
Noticed UI improvement, however - interchanging between using shaka-player.ui.js vs shaka-player.ui.debug.js
there is still a problem of no UI controls when not using debugging library.
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <script src="../../../../../../common/shaka/shaka-player.ui.js"></script>
    <link rel="stylesheet" href="../../../../../../common/shaka/controls.css" />
    <script src="dash-player-init.js"></script>
  </head>
  <body style="margin-top: 0px; margin-right: 0px; margin-left: 0px; background-color: #000000">
    <div id="live-player-container" class="live-player-container">
      <video autoplay id="live-shoany-player" style="width:100%;height:100%"></video>
    </div>
  </body>
</html>
```
```
function initApp() {
  // Install built-in polyfills to patch browser incompatibilities.
  shaka.polyfill.installAll();
  //shaka.log.setLevel(shaka.log.Level.V1);
  // Check to see if the browser supports the basic APIs Shaka needs.
  manifestUri = getUrlParameter('manifestUri');
  licenseUri = getUrlParameter('licenseUri');
  video = document.getElementById('live-shoany-player');
  auth = getUrlParameter('auth');
  playerContainer = document.getElementById('live-player-container');
  player = new shaka.Player(video);
  var ui = new shaka.ui.Overlay(player, playerContainer, video); 
  var controls =  ui.getControls();

  player.setTextTrackVisibility(true);
  window.player = player;
  window.ui = ui;

  if(shaka.Player.isBrowserSupported()){
    
      initPlayer();
  }else{
    console.log("browser no supported.")
  }

}

document.addEventListener('shaka-ui-loaded', initApp);
```

<img width="1588" alt="Screen Shot 2020-07-23 at 4 01 58 PM" src="https://user-images.githubusercontent.com/61878804/88333488-53ecaa80-ccfe-11ea-8baf-72d7ee0fd198.png">
<img width="683" alt="Screen Shot 2020-07-23 at 11 17 54 AM" src="https://user-images.githubusercontent.com/61878804/88333502-58b15e80-ccfe-11ea-873e-99cbe93212da.png">

**Comment by theodab** [comment]
Okay, I tried that exact code you posted (except replacing the `initPlayer` function you didn't provide with a `player.load` call), and I'm still not seeing the problem you are reporting.

What platform are you using? I've tested this on Chrome, Safari, and Firefox for macOS.
Do you see this problem in our demo? Or is it only happening in your app?

**Comment by ed-wosleger** [comment]
I copy pasted parts of relevant code to illustrate the simplicity.
I am not sure what I can post publicly without violating corp policies. 
The UI controls do not display on with shaka-player.ui library. However simply swapping in shaka-player.ui.debug library, the controls ui displays correctly. I tested both Chrome and FF. Safari we use a simpler HLS framework based on code from Apple.

**Comment by theodab** [comment]
If there are things you can't post publicly, you can send them to our <shaka-player-issues@google.com> mailing group, and only we will see it.

**Comment by joeyparrish** [comment]
We are unable to reproduce the issue with the information you've given us.  If this is still a problem, please send details either publicly or privately and ask the issue to be reopened by commenting `@shaka-bot reopen`.  Thanks!
