### ISSUE TITLE
/build/types/core file is missing in NPM package

### ISSUE THREAD

**Issue by Anonym-tsk** [google/shaka-player#2752]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes

**What version of Shaka Player are you using?** 3.0.1

**Can you reproduce the issue with our latest release version?** From 2.5.11

**Can you reproduce the issue with the latest code from `master`?** No

**Are you using the demo app or your own custom app?** No

**If custom app, can you reproduce the issue using our demo app?** No

**What browser and OS are you using?** Any browser

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What did you do?**

I try to build player from NPM
`python build/build.py --force +@complete`

**What did you expect to happen?**
Successful build

**What actually happened?**

I got error
`[ERROR] Build file not found: core`
It's because `/build/types/core` is missing in NPM from 2.5.11

in the release on github this file is present

**Comment by Anonym-tsk** [comment]
It looks like `npm` bug, because:
`npm i -D https://github.com/google/shaka-player/tarball/v3.0.1` works
`npm i -D git+https://github.com/google/shaka-player.git#v3.0.1` doesn't
`yarn install git+https://github.com/google/shaka-player.git#v3.0.1` works

**Comment by joeyparrish** [comment]
That's really odd.  Perhaps at some point, "core" was added to some ignore-list for NPM or git, on the assumption that it was a Linux core dump.  It's not in our .npmignore file, though.

I find that it's present in v2.5.10, but not v2.5.11 or later.

Aha!  Yes, that's the cause indeed.  This appears to be the issue: https://github.com/npm/npm-packlist/issues/24

This comment suggests a workaround we can use in our repo: https://github.com/npm/npm-packlist/issues/24#issuecomment-464860179

But I don't think there's any way to re-publish npm packages with the same version once they are out, so the fix will only affect future releases of Shaka Player.

**Comment by joeyparrish** [comment]
The packages for v2.5.14 and v3.0.2 have the npm workaround.  You should see build/types/core in those releases.
