### ISSUE TITLE
Using hard-coded namespaces in TTML parser

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#2756]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
master

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Demo

**What browser and OS are you using?**
ChromeOS stable 84

**What are the manifest and license server URIs?**
Not available (pointed out by a partner, confirmed by reading source)

**What did you do?**
The TTML parser uses hard-coded namespaces in some places.  For example:
 - `tts:extent`
 - `xml:space`
 - `xml:id`
 - `smpte:backgroundImage`

This prevents someone from using different namespace names in their XML.  For example, this would be typical:
```xml
<tt xmlns="http://www.w3.org/ns/ttml"
    xmlns:tts="http://www.w3.org/ns/ttml#styling">
  <head>
    <styling>
      <style xml:id="backgroundStyle"
          tts:fontFamily="proportionalSansSerif"
          tts:fontSize="1.5c"
          tts:textAlign="center"
          tts:origin="5% 70%"
          tts:extent="95% 28%"/>
```

But this should also be valid:
```xml
<tt xmlns="http://www.w3.org/ns/ttml"
    xmlns:s="http://www.w3.org/ns/ttml#styling">
  <head>
    <styling>
      <style xml:id="backgroundStyle"
          s:fontFamily="proportionalSansSerif"
          s:fontSize="1.5c"
          s:textAlign="center"
          s:origin="5% 70%"
          s:extent="95% 28%"/>
```

In some cases, we use `getAttribute` directly with a hard-coded namespace name in the attribute name:
```js
extent = tt.getAttribute('tts:extent');
```

Instead, we should match by namespace URL, as we do in most other cases.

```js
const ttsNs = TtmlTextParser.styleNs_;  // "http://www.w3.org/ns/ttml#styling"
extent = XmlUtils.getAttributeNS(tt, ttsNs, 'extent');
```

It's possible that we could write a compiler conformance rule or linter rule to ban the direct use of getAttribute() with a hard-coded namespace name.

**Comment by ashakespeare-google** [comment]
Hi Joey,

Is this fix due to be backported to the 2.5.x branch as well?

Many thanks,

Alex

**Comment by michellezhuogg** [comment]
Fixed with commit 7e4280fab4bb29f346cac1a6da5120236a61457b .

**Comment by joeyparrish** [comment]
There are still instances of hard-coded namespaces in the parser.  For example, `smpte:backgroundImage`.

**Comment by michellezhuogg** [comment]
Got it. Working on a fix.
