### ISSUE TITLE
How to attach a separated audio to a video without audio?

### ISSUE THREAD

**Issue by montogeek** [google/shaka-player#2757]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
Latests

**Please ask your question**
Currently my video (mp4) don't have any audio this is by design, and its audio (.m4a) is provided separately.

It is possible to use both things in a Shaka player like it is a normal video with audio?
So for example if the user pauses the video, the audio should be paused too or if the muted icon is clicked the audio should be unmuted too, etc.

Thanks!

**Comment by TheModMaker** [comment]
We only support playing a single media file or playing streaming manifest formats like HLS or DASH.  If you want to combine separate audio and video tracks, you should package them into a streaming manifest format.  You can use [Shaka Packager](https://github.com/google/shaka-packager) to create DASH or HLS content and we should be able to play that.

**Comment by montogeek** [comment]
@TheModMaker Thanks for the info!
