### ISSUE TITLE
[ViacomCBS] [XBOX] Clear preroll period to first encrypted content period failure.

### ISSUE THREAD

**Issue by dsparacio** [google/shaka-player#2759]
Have you read the FAQ and checked for duplicate open issues?
Yes completely.

What version of Shaka Player are you using?
Tested Master branch,  2.5.14, 2.5.10, 2.4.7, 2.3.10 and 2.2.10 All of which had the exact same result. Could not get out of clear pre roll to content protected period.

Can you reproduce the issue with our latest release version?
Yes

Can you reproduce the issue with the latest code from master?
Yes

Are you using the demo app or your own custom app?
Demo raw simple setup. Page urls included in support email with content and la urls.

If custom app, can you reproduce the issue using our demo app?
yes

What browser and OS are you using?
XBOX Win/10 Spartan (2014–2019 Edge) non chromium build of edge which is what XBOX dev offers at this time.

For embedded devices (smart TVs, etc.), what model and firmware version are you using?

```
Sandbox ID: XDKS.1
OS version: 10.0.19041.3068 (rs_xbox_release_2006.200610-0000)
OS edition: June 2020
Xbox Live device ID: FD00A956242E1869
Console ID: 74f233ae.f9265a03.c4fee763.851eb008.01
Serial number: 210633693016
Console type: Xbox One S
Model: 1681
Devkit type: Universal Windows App Devkit
```
```
Sandbox ID: XDKS.1
OS version: 10.0.19041.3068 (rs_xbox_release_2006.200610-0000)
OS edition: June 2020
Console ID: A7DCC4D8.6B218CCF.694B68FC.0D3DB308.01
Model: 1681
Console type: Xbox One S
Devkit type: Universal Windows App Devkit
```
```
Sandbox ID: XDKS.1
OS version: 10.0.19041.3068 (rs_xbox_release_2006.200610-0000)
OS edition: June 2020
Xbox Live device ID: FD00812AA7534FE0
Console ID: 4c279407.7e461c98.d56bb52f.dfb64007.01
Serial number: 051235192517
Console type: Xbox One X
Devkit type: Universal Windows App Devkit
```

What are the manifest and license server URIs?
Same as this ticket https://github.com/google/shaka-player/issues/2620
Sent over on shaka-player-issues@google.com

What did you do?

Play from 0 start time and let preroll finish, on the first transition to a content period player stalls.

Non zero test are interesting.
If you skip the pre-roll with a non zero start time, all mid-roll DAI period transition thereafter works as expected.

What did you expect to happen?
The first content period initializes and plays out.

What actually happened?
The content period fails to init and play properly.

**Comment by dsparacio** [comment]
XBOX it is failing 100% on all boxes. We tested many versions and all fail exactly the same way.

I tried to apply some of your Tizen fixs I saw in master for Edge as well to just test on XBOX. For instance this block

 // on one of these platforms.  Instead, default stallSkip to 0 to force the
    // stall detector to pause and play instead.
    if (shaka.util.Platform.isWebOS() ||
        shaka.util.Platform.isTizen() ||
        shaka.util.Platform.isEdge() ||
        shaka.util.Platform.isChromecast()) {
      streaming.stallSkip = 0;
    }
and the Endianness changes I did for comcast just to test..... All of which made no difference for XBOX.

**Comment by dsparacio** [comment]
Here is an image from xbox, much like the other samsung issue
![Image from iOS](https://user-images.githubusercontent.com/7864462/88853347-6e160500-d1a4-11ea-90b9-8e435a78ba40.jpg)

**Comment by dsparacio** [comment]
We had to devs test on two of the mentioned XB1 above and here are the logs. 
[xbox_shaka_2514.txt](https://github.com/google/shaka-player/files/4997470/xbox_shaka_2514.txt)

[2.5.14-xbox.txt](https://github.com/google/shaka-player/files/4997478/2.5.14-xbox.txt)

**Comment by dsparacio** [comment]
> If the ad periods are inserted at a segment boundary without modifying/splitting any of the segments
Confirmed with our All Access team DAI does not modify any encrypted content segments at all.

**Comment by davidbohunek** [comment]
I am seeing the same issue with our streams, when there is unencrypted preroll before encrypted content. This only happens on Edge with PlayReady and Xbox One. 
Anything I can try or provide to help with this issue?

**Comment by joeyparrish** [comment]
Hi everyone,

Sorry for the long delay with no updates.

We still don't have any bright ideas for how to debug this or what might be causing it.  Our best guess is that something specific to DAI triggers a bug in the XBox or its browser or its PlayReady implementation, but we have no way to test that idea or dig deeper at the moment.

It would be ideal if Microsoft could debug this somehow, since they would have access to information from the browser and OS that we could never see.

**Comment by davidbohunek** [comment]
Thanks @joeyparrish. I am talking to Microsoft about it, so will let you know if anything useful comes out of that.

**Comment by davidbohunek** [comment]
Microsoft are saying that this is a limitation on their side. They determinate the decoding pipeline method by first appended fragment to each source buffer. So if a stream starts with an unencrypted fragments (pre-roll advert for example) all encrypted content after after the unencrypted part won't be decoded correctly. But no errors throw, just green screen and no audio...

The way we are fixing this in our fork is that we find an init fragment of an encrypted period and when the stream starts from an unencrypted period, we append the encrypted init fragment first, then the straight after that the correct unencrypted init fragment and as usual. This fixes the problem, but obviously it is a bit unusual solution.

@joeyparrish  Please let me know if you are interested in a PR with this or if you'd rather stay away from this :)

**Comment by joeyparrish** [comment]
Yes, please send a PR!  With appropriate comments, I'm sure there's a relatively clean way to make it work.

**Comment by dsparacio** [comment]
@davidbohunek David great info and news! We can test our content as well once PR is up.  Thanks for sharing.

**Comment by dsparacio** [comment]
@davidbohunek Hi, hope you are well? Wondering if there was ever a PR for this or just a fix in your fork.  Wondering If I could scope the change and try to test it with our content.

**Comment by MilosRasic** [comment]
Looks like I duplicated this issue here https://github.com/google/shaka-player/issues/2974

Sorry. I was searching for hours and didn't find anything.

In our case though, it's working fine on Tizens but we have something similar in roughly 50% playbacks on LG webOS.

@davidbohunek if you don't have the time to PR this fix, do you mind if someone else does? We're not using our own fork of shaka-player and would prefer not to have to start now 🙂

**Comment by bcupac** [comment]
Am seeing the same issue with Tizen 3.0/2017/Widevine. When there is an ad before drm content, decoding is bad. Tizen 2018 and up looks ok. 

Looking into shaka player code, seems like streaming_engine.js goes like this:
```
start
	initStreams_
		scheduleUpdate_
			onUpdate_
				update_
					fetchAndAppend_
						initSourceBuffer_
                                                       mediaSourceEngine.appendBuffer
```

 So it seems fetchAndAppend_ or initSourceBuffer_
is where the fix can be applied. 

@joeyparrish any idea how to check if a segment is encrypted?

Also when I load a stream that has a pre-roll ad, and don't play it at all,  I can see that all variants in this.manifest_ have drmInfo meaning they are encrypted. Are these variants somehow normalized across the entire stream? because if it loaded just variants from the first unencrypted/ad period, drmInfos should be empty?

**Comment by bcupac** [comment]
One other solution that comes to mind for VOD without the need to alter shaka-player is that if CuePoint start/end times are known, setup a listener for the `encrypted` event on the video element and pick a random time where the stream in encrypted as the start time when loading the stream ```player.load(contentUrl, timestampWhereStreamEncrypted)```
and when the `encrypted` event is raised meaning that the decoding pipeline is correctly set, just revert back to the regular start time with 
```videoElement.currentTime = realStartupTime```
This should all happen reasonably fast so the user would not notice.

**Comment by bcupac** [comment]
This workaround works, but listener for returning to the proper position needs to be set-up on the first `timeupdate` event.

**Comment by dsparacio** [comment]
Happy New Year! Just checking in if there any ideas here?  I could do some dev and testing but a bit lost where to start and was hoping on having @davidbohunek PR for reference or use.

We are starting to see this being escalated on Samsung as well as Xbox

**Comment by joeyparrish** [comment]
@dsparacio, I'm consulting with an expert internally on how we could work around this in the player.  In short, I would guess that it should be feasible to modify a clear init segment in memory to indicate encryption.  If the player is configured for encrypted content, and the init segment doesn't indicate encryption, and it's a platform that we know has this issue, we would modify it before appending it.

We're going to work out what whether this is feasible and what it would take to implement.  If it's feasible, and not too complicated, we could manually test the change on Tizen and XBox, and if we're successful, ship the fix in our next release.

Your next question is probably "when's you next release?"  We're not on a fixed schedule at this time, but this is a big enough issue that I would start the release process right away, even if there's nothing else to cherry-pick for that release.

**Comment by dsparacio** [comment]
@joeyparrish Great info as always! Thanks for the update. We can test this in any branch and help out where needed. We have a failing Samsung model and XB on hand. Let me know I'll stay tuned.

**Comment by joeyparrish** [comment]
Good news and bad news.  The good news is that there is a workaround in review right now.  The bad news is that our Xbox One has died, so we have no way to confirm it there.

We will confirm the workaround on Tizen 3.0 using the content provided by @dsparacio, though, and then hopefully someone else can confirm on Xbox before we cherry-pick the workaround into a release.

**Comment by dsparacio** [comment]
@joeyparrish awesome and sorry to hear!  We can test it on Xbox and on our one Tizen that has this issue.  What branch do I build?  May take us to end of week to build and retest.  We are dealing with a ton of prep work for an upcoming live event... But this is very important to us.... so we will get it done.

**Comment by joeyparrish** [comment]
The workaround has not quite cleared our code review yet, but I hope it will be on github soon.  I'll be sure to update this issue as soon as it's out.

**Comment by joeyparrish** [comment]
Your content appears to play on our Tizen device both with and without the fix, so our device must not be one of the ones affected.  I tried in both a PlayReady-only config and a Widevine-only config.

**Comment by joeyparrish** [comment]
@dsparacio, the workaround is now on the `master` branch.  Please take a look when you have time!

**Comment by dsparacio** [comment]
@joeyparrish We schedule this testing for monday.  Get back to you soon with results

**Comment by joeyparrish** [comment]
Excellent.  Thanks!

**Comment by joeyparrish** [comment]
I'm cherry-picking this to v3.0.x and doing another test pass, in preparation for v3.0.8.  If everything looks good here, I'll push to v3.0.x.  If your tests are not successful, I can still revert the commit before we push the release.  Thanks!

**Comment by dsparacio** [comment]
@joeyparrish pulling now and building sending to our QA.  get back to you with any question/ results asap.  If this works and goes into 3.0.8 we may just pick that up instead of 3.0.7 which we just picked for this sprint.  All depends on outcome and timelines.   Talk to you soon

**Comment by dsparacio** [comment]
@joeyparrish on change on the one Samsung we have that has this issue.  Still gets to Enc periods and green screen. 

XB1,  we are getting dash manifest parse errors now and cannot get to to log lines for Fake Encryption steps.  I will have our lead QA jump on here and add logs.  I am hoping the XB1, the main focus here, is just a XML issue and the DRM part will work once we clear that up.

**Comment by agajassi** [comment]
**3.0.7 Logs from Xbox:**

[shaka_xbox.txt](https://github.com/google/shaka-player/files/5869810/shaka_xbox.txt)

**Comment by agajassi** [comment]
As Dan mentioned I am getting Invalid XML issue regardless of if I try drm protected or drm-less .mpd.

**"Fatal media error, no option for recovery : DASH_INVALID_XML / 4001",**

**Comment by bcupac** [comment]
getting the same error on our app, dash_parser, parseManifest_  , shaka.util.XmlUtils.parseXml fails, 
```
try {
      const string = shaka.util.StringUtils.fromUTF8(data);
      return shaka.util.XmlUtils.parseXmlString(string, expectedRootElemName);
    } catch (exception) {
      return null;
    }
    ```
'Text Decoder' is not defined exception

**Comment by joeyparrish** [comment]
With the URL in the log, playing in ChromeOS, I don't see an XML parsing error.

@bcupac, thank you for mentioning this!  If you are using the `master` branch, you will need a `TextDecoder` polyfill for Xbox.  We suggest https://www.npmjs.com/package/fastestsmallesttextencoderdecoder  This is not needed for the `v3.0.x` branch or v3.0 releases, but will be needed in v3.1+.

Now that I look again at the logs from @agajassi, I see that the version number is reported as `v3.0.7-master-22-g49d611f6`, so y'all must have made the same mistake.

You can try again with a polyfill added for TextDecoder, or you can try building from the v3.0.x branch instead.

**Comment by dsparacio** [comment]
@joeyparrish we are loading the polyfill in page now and testing again.  Standby

**Comment by agajassi** [comment]
@joeyparrish 
Getting same 4001 XML Error even with TextDecoder polyfill added to the page.

**Comment by agajassi** [comment]
@joeyparrish 
We tried Shaka version: **v3.0.7-20-g66cdd44e-debug** on Xbox. The one that does not require polyfill. 

Got this error:
```MEDIA_SOURCE_OPERATION_FAILED 3014 number. A MediaSource operation failed. error.data[0] is a MediaError code from the video element.```

Full logs:
[shaka_logs_new.txt](https://github.com/google/shaka-player/files/5870565/shaka_logs_new.txt)

**Comment by dsparacio** [comment]
I built 3.0.x that resulted in v3.0.7-20-g66cdd44e-debug in logs.  @joeyparrish Does all this look correct from your perspective?  Does this log help at all. Let us know if you need us to collect or debug anything specifically.

**Comment by joeyparrish** [comment]
Thank you for the logs.  I wish I could see what the MediaSource error was in error.data[0], but it doesn't appear to get logged.  Is that something you can log for us?

I'm not sure what to do next.  I think it's best if I revert the change in v3.0.x until we have this sorted out, and go ahead with the v3.0.8 release without this change.

I've started trying to replace our Xbox so we can deal with this in a more hands-on way, but apparently the original XB1 consoles are not being made or serviced, and the new ones are out of stock almost everywhere because of supply chain issues and import quarantines.

**Comment by dsparacio** [comment]
@joeyparrish if I can arrange an xbox to loan you for a few weeks would that help?

**Comment by joeyparrish** [comment]
I managed to find a used one that could be shipped to me by the end of the week.  But thank you for the offer!

It will take some time to get set up for anything more useful than opening the browser, but I'll try to set up Visual Studio and dev mode soon.

**Comment by joeyparrish** [comment]
I have a hacky way to manually connect the Xbox to the Shaka automated tests.  I found, to my disappointment, that the built-in browser doesn't seem to have PlayReady enabled.  But I was able to build a UWP app with WebView and add a capability to the manifest to enable PlayReady there.  Through that, I can run our automated tests and get console logs.  But it's painful.  I don't have time to build this all the way into our test lab with https://github.com/google/generic-webdriver-server yet, but I've got most of the pieces in place and it's good enough to allow me to do some basic debugging on the device.

I'm about out of time for today, but I may be able to get some useful info tomorrow.

That said, I think I still need to revert the workaround in the v3.0.x branch and get v3.0.8 out the door.  I meant to have it done sooner.  There are other fixes that need to be in an official release ASAP.

**Comment by joeyparrish** [comment]
My dev mode Xbox One refuses to play your content with my workaround, and the MS error code attached to the failure is 0x80004005, which seems to translate simply to E_FAIL.  Not too helpful.  :-)

But with the workaround disabled, it at least **begins** playback.  So that means if I can figure out what is wrong with the manipulated init segments, I should get immediate feedback.

**Comment by riksagar** [comment]
Hey @joeyparrish , sorry if you already took this into account.  You mentioned your Xbox1 is in DevMode.  For DevMode you need to set you PR license to SL150.

**Comment by joeyparrish** [comment]
@riksagar, I'm not in control of the PR licenses coming from CBS's license service, but they seem to be fine in that regard.

Flipping the order of "encv"/"enca" and "avc1"/"mp4a" boxes seems to make my Xbox happy, although Chrome doesn't like it.  Since this is a platform-specific workaround, that might not matter in the long run.  However, I found that even with the workarounds disabled, the sample content sent to me by @dsparacio seems to play anyway.

So, it's possible that my Xbox simply doesn't exhibit the problem to begin with.  @dsparacio, @agajassi, please try this small edit to the master branch in lib/media/content_workarounds.js to see if it helps:

```diff
-    const sourceBoxEnd = sourceBox.start + sourceBox.size;
+    const sourceBoxEnd = sourceBox.start;
```

For me, it at least fixes the `E_FAIL` error I saw before, but since I can't seem to reproduce [the blocky-green artifacts of a failed decrypt](https://github.com/google/shaka-player/issues/2759#issuecomment-665926992) either way, you'll have to let me know what that small change does for your devices.

**Comment by dsparacio** [comment]
Thanks @joeyparrish  Will try in AM

**Comment by bcupac** [comment]
@joeyparrish @dsparacio 
This issue is also reproducible for our streams when using Chromium Edge or old Edge with PlayReady or Windows 10 UWP which is basically old Edge.

**Comment by bcupac** [comment]
Tested windows 10 uwp, Xbox and chromium edge With this change.
```
-    const sourceBoxEnd = sourceBox.start + sourceBox.size;
+    const sourceBoxEnd = sourceBox.start;```

Stream works OK in windows10 UWP and Xbox, but throws 3014 error on chromium edge.

with using old
const sourceBoxEnd = sourceBox.start + sourceBox.size on chromium edge, no 3014 error but still has decoding green artifacts

**Comment by joeyparrish** [comment]
> Stream works OK in windows10 UWP and Xbox, but throws 3014 error on chromium edge.

This workaround won't be applied on Chromium Edge, only on Xbox One and Tizen.

I'm glad to hear this fixes it for you on Xbox.  I'll get this rolled into the next release.

**Comment by joeyparrish** [comment]
The existing workaround works on Tizen, but not Xbox One, and the modified workaround works on Xbox One, but not Tizen.  So the next change to the code will have to be to make it platform-specific which order these boxes go in.

I've verified that with the new forthcoming workaround and the current platform rules for applying it (Xbox One & Tizen only), the content from CBS plays through at least 90s (preroll, one content period, midroll) for me on:

1. Chrome 88 on Windows 10 (workaround skipped)
2. Chromium-based Edge 88 on Windows 10 (workaround skipped)
3. Xbox One firmware 19041.5496 (November 2020) in UWP WebView (Legacy Edge 18) (workaround applied, encv box first)

In earlier test, these were also working:
1. Tizen 3 w/ PlayReady config (init segment workaround applied, avc1 box first)
2. Tizen 3 w/ Widevine config (init segment workaround applied, avc1 box first)

However, I can't reconfirm those, as our Tizen test infra seems to be broken at the moment.  I can't load any external assets for some reason, and it complains about cross-origin access in spite of everything having explicit CORS headers allowing access.  Not sure if it was broken by a TV firmware update or what, but the test infra itself hasn't changed.

**Comment by agajassi** [comment]
@joeyparrish 

This is Agajan. I work with @dsparacio. I just tried your recent changes in v3.0.8-master and wanted to confirm that the underlying issue works on Xbox. Thank you for your help addressing this.

**Comment by joeyparrish** [comment]
We're very happy that we could address it at all.  The change went out in the official v3.0.8 release, in case you want to stay on the release branch.  Thanks for your feedback and for helping verify the work!

**Comment by dsparacio** [comment]
@joeyparrish much appreciated.  Thanks for sticking with this one!

**Comment by joeyparrish** [comment]
Xbox One will soon become an officially-supported platform.  If anyone is interested to see how, check out this PR for our new test infrastructure tools for Xbox: https://github.com/google/generic-webdriver-server/pull/12

**Comment by avelad** [comment]
@dsparacio Do you know if this problem is exclusive to Xbox One or also happens in the Xbox Series S|X? I see that @joeyparrish 's code only applies to Xbox One.

**Comment by dsparacio** [comment]
@av

**Comment by dsparacio** [comment]
@avelad not that far with new Xbox so not sure. It does happen on a certain Samsung versions.

**Comment by joeyparrish** [comment]
The workaround is applied based on the UA string, so it's possible that it's too narrowly-targeted.

For what it's worth, I developed the workaround on a refurbished Xbox One X model.  There, the workaround appeared to be unnecessary, but not harmful.  I expect that excluding it from Series X and Series S models will be okay.  If I'm wrong, it's a ~1-line fix.
