### ISSUE TITLE
TTML nested cues should be supported at multiple levels of nesting

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#2761]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v2.5 and v3.0 and master

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Demo

**If custom app, can you reproduce the issue using our demo app?**
N/A

**What browser and OS are you using?**
ChromeOS 84 stable

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
N/A, though I should find more diverse TTML samples for testing and verification

**What did you expect to happen?**
The TTML spec and the IMSC1 renderer both show nested elements at more than two levels of nesting.  For example:

```xml
<?xml version="1.0"?>
<tt xmlns="http://www.w3.org/ns/ttml"
    xmlns:tts="http://www.w3.org/ns/ttml#styling"
    xml:lang="en">
  <head></head>
  <body>
    <div begin="0s" end="60s">
      <p>
        <span>span1</span> <span>span2</span>
      </p>
    </div>
  </body>
</tt>
```

**What actually happened?**
<s>Shaka Player does not show anything for the spans above.  TTML parsing output seems to stop at the second level (`<p>` element).</s>  _(Edit: I was wrong about that.  See comments below.)_

Furthermore, the TextDisplayers don't recurse into nestedCues beyond one level.

**Comment by joeyparrish** [comment]
IMSC1 renderer: http://sandflow.com/imsc1_1/

After reading more carefully through the TTML spec, I see that `<div>` can only contain `<p>`, which can only contain text or `<span>`, which can contain text or other `<span>`s.

So this would be a better example:

```xml
<?xml version="1.0"?>
<tt xmlns="http://www.w3.org/ns/ttml"
    xmlns:tts="http://www.w3.org/ns/ttml#styling"
    xml:lang="en">
  <head>
    <styling>
      <style xml:id="bg-black" tts:backgroundColor="black" />
      <style xml:id="bg-blue" tts:backgroundColor="blue" />
      <style xml:id="fg-red" tts:color="red" />
      <style xml:id="fg-green" tts:color="green" />
      <style xml:id="fg-yellow" tts:color="yellow" />
    </styling>
  </head>
  <body>
    <div begin="0s" end="60s">
      <p style="bg-black">p content
        <span style="fg-red">span1 in p</span>
        <span style="fg-green">span2 in p</span>
        <span style="bg-blue">span3 with <span style="fg-yellow">span4 inside it</span></span>
      </p>
    </div>
  </body>
</tt>
```

**Comment by joeyparrish** [comment]
I must have made some kind of big mistake in the TTML when I tested this the first time, since I wasn't seeing anything for the spans.  With the exact TTML in the last comment above, I _do_ see the spans rendered.

However, I see all the content of the `<p>` element crammed into a single nested cue in the output of the TTML parser:

```
p contentspan1 in pspan2 in pspan3 withspan4 inside it
```

This renders all white on black without honoring the style attributes.

**Comment by joeyparrish** [comment]
It seems that the TTML spec specifies that text content at the `<p>` element level not inside an explicit span is meant to inhabit an "anonymous span", which for obscure reasons would not be rendered.  So the output should be something like:

```
span1 in pspan2 in pspan3 with span4 inside it
```

The spaces between sibling spans are also in "anonymous spans" that don't render, but the space inside span3 before span4 would render.

The output from the parser should be something like:

```js
{
  nestedCues: [
    {
      payload: 'span1 in p',
    },
    {
      payload: 'span2 in p',
    },
    {
      payload: 'span3 in p ',  // trailing space!
      nestedCues: [
        {
          payload: 'span4 inside it',
        },
      ],
    },
  ],
}

**Comment by joeyparrish** [comment]
Although perhaps I misunderstood the spec.  I see that the `<p>` element text and inner spaces render in [the IMSC1 renderer](http://sandflow.com/imsc1_1/):

![OtbFYFQficF](https://user-images.githubusercontent.com/6843156/88939849-dfed5d80-d23b-11ea-96bc-64764eaae67e.png)

**Comment by joeyparrish** [comment]
I found the source of my confusion.  I missed this in the spec:

https://www.w3.org/TR/2018/REC-ttml1-20181108/#timing-time-intervals
> if the parent time container is a sequential time container, then the implicit duration is equivalent to zero.

So the `<p>` content would only be hidden if I used `<p timeContainer="seq">`.  A quick search shows that `timeContainer` is not implemented by Shaka Player to begin with.

**Comment by michellezhuogg** [comment]
In the example above,
```
<?xml version="1.0"?>
<tt xmlns="http://www.w3.org/ns/ttml"
    xmlns:tts="http://www.w3.org/ns/ttml#styling"
    xml:lang="en">
  <head>
    <styling>
      <style xml:id="bg-black" tts:backgroundColor="black" />
      <style xml:id="bg-blue" tts:backgroundColor="blue" />
      <style xml:id="fg-red" tts:color="red" />
      <style xml:id="fg-green" tts:color="green" />
      <style xml:id="fg-yellow" tts:color="yellow" />
    </styling>
  </head>
  <body>
    <div begin="0s" end="60s">
      <p style="bg-black">p content
        <span style="fg-red">span1 in p</span>
        <span style="fg-green">span2 in p</span>
        <span style="bg-blue">span3 with <span style="fg-yellow">span4 inside it</span></span>
      </p>
    </div>
  </body>
</tt>
 ```

The ideal generated html would be:
 ```
<div>
    <p backgroundColor="black">
        <span>p content</span>     <!-- anonymous span in p -->
        <span color="red">span1 in p</span>
        <span color="green">span2 in p</span>
        <span backgroundColor="blue">     <!-- a container for spans -->
            <!-- flatten span3 and span4 -->
            <span>span3 with </span>
            <span color="yellow">span4 inside it</span>
        </span>
    </p>
</div>
 ```
