### ISSUE TITLE
TTML empty line in between cues

### ISSUE THREAD

**Issue by mattiaspalmgren** [google/shaka-player#2762]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.12 and 3.2.0

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Custom app, where I've just implemented the [basic usage](https://shaka-player-demo.appspot.com/docs/api/tutorial-basic-usage.html) example.

**If custom app, can you reproduce the issue using our demo app?**
N/A

**What browser and OS are you using?**
Chrome, MacOs, Catalina

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
N/A

**What did you do?**

We've a TTML caption formatted as:
```
<div>
    <p begin="00:00:01.800" end="696:15:11.521" xml:id="s0" region="r" style="p">
        <span style="style1">Hej, lilla gumman.</span>
        <br/>
        <span style="style2">– Vilket fint italienskt hus ni har!</span>
    </p>
</div>
```

**What did you expect to happen?**
That it should render two caption lines, with no empty line in between.

**What actually happened?**
See attached image., it renders three lines, with an empty line in between from the `<br/>` tag. 

I haven't been able to understand from the spec what should happen in this scenario and if the formatting is wrong, but I can see that dash.js, rx-player and the IMSC1 Renderer (which I'm not familiar with but saw it linked in another issue) renders the captions without the line in between.

![image](https://user-images.githubusercontent.com/2861815/88891081-d4516500-d242-11ea-9dd3-1a3f201a7843.png)

What do you think?

**Comment by joeyparrish** [comment]
You are correct.  I'm working on other TTML parsing and rendering fixes, so I'll work on this, too.  Thanks for filing!
