### ISSUE TITLE
addTextTrack for a VTT sidecar doesn't work for standalone MP4 video source

### ISSUE THREAD

**Issue by somnaderi** [google/shaka-player#2765]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.2 (also 2.5.14)

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Have not tried -- not sure this is actually a bug.

**Are you using the demo app or your own custom app?**
Custom app.

**If custom app, can you reproduce the issue using our demo app?**
Have not tried -- not sure this is actually a bug.

**What browser and OS are you using?**
MacOS + Chrome (also fails on Ubuntu + Chrome)

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What did you do?**
Loaded a standalone MP4 URI and then attempted to addTextTrack a separate WebVTT URI.

**What did you expect to happen?**
Expected the text track to load and display over the video.

**What actually happened?**
Player fails to load track with "Error code undefined object Error: State error!
    at T.push../node_modules/shaka-player/dist/shaka-player.ui.js.p.addTextTrack (shaka-player.ui.js:9055)"

This is on the line that errs with "Cannot add text when loaded with src=", but we're not using "src=". 

The addTextTrack is called in the promise resolver, so the player should be loaded.

The same code / text track file works with an MPD video source URI.

I'm guessing this is known/expected behavior, but I wasn't able to find anything that said that explicitly. Was going to file as a "Question", but the question template said that if it *might* be a bug, do this template instead. I can add more details/code samples with confirmation that this isn't expected behavior and might actually be a bug.

**Comment by TheModMaker** [comment]
This is expected, we don't support extra text tracks when running in `src=` mode.  Since you specified a single MP4 file, we run in `src=` mode.  It may be possible for us to add WebVtt support for this by adding a track element, but that wouldn't work with our UI text displayer.  Most of the library only works in MSE mode, which is why we don't allow side-loaded text streams in `src=` mode.

**Comment by somnaderi** [comment]
That's what I suspected, thank you for the response!
