### ISSUE TITLE
Safari - Auto retry streaming after network recovered from an offline event does not work 

### ISSUE THREAD

**Issue by bcupac** [google/shaka-player#2767]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

**What version of Shaka Player are you using?**
3.1.0

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Both

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
MacOS Catalina - Safari 13.1.1

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What did you do?**

Play Big Buck Bunny: the Dark Truths (HLS .m3u8) on Safari - Shaka demo, 
disconnect from the internet,
wait for the  buffered content to expire, and until the loader indicator appears
reconnect to the internet.

**What did you expect to happen?**
expected the player to recover and continue playback

**What actually happened?**
playback does not continue.

Noticed this test:
`
// Since we are not in-charge of streaming, calling |retryStreaming| should
  // have no effect.
  it('requesting streaming retry does nothing', async () => {
    await loadWithSrcEquals(SMALL_MP4_CONTENT_URI, /* startTime= */ null);
    expect(player.retryStreaming()).toBeFalsy();
  });
`
Does this mean this is by design on Safari, and are there any possible workarounds to recover playback after the network has recovered from an offline event.

**Comment by TheModMaker** [comment]
I don't think we handle retries with `src=`.  I think the only thing we do is tell the browser to play the video, so it is up to the browser to retry when it reconnects.  If you aren't using FairPlay, you could set `streaming.useNativeHlsOnSafari` configuration to `false` to use MSE mode and we should handle retries.

**Comment by bcupac** [comment]
Tried with demo stream and it doesn't work. Seeking manually also doesn't resume playback when the internet is back online and playback got stuck due to it being offline.

Native Safari player which supports .m3u8 out of the box behaves the same, so I guess there is no way around it.

**Comment by joeyparrish** [comment]
I'm sorry we weren't able to help with this!  But it does seem like a limitation of native HLS in Safari.

If anyone ever does come up with a workaround, we'll be more than happy to use it in Shaka Player!
