### ISSUE TITLE
Segmented WebVTT in MP4

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#277]
Write a plugin for WebVTT in MP4.

**Comment by kfwerf** [comment]
i have a PR that implemented segmented webvtt. Maybe it is of some use to this project,

https://github.com/google/shaka-player/pull/291

**Comment by joeyparrish** [comment]
@kfwerf, #291 doesn't address the same feature.

#277 is about WebVTT embedded in MP4.  #291 adds segmented WebVTT to v1 by parsing WebVTT cues.

We have already implemented segmented WebVTT in v2 (#150) and do not plan to backport to v1.  v1 is in maintenance.

Please see the [`preview`](https://github.com/google/shaka-player/tree/preview/) branch for the v2 work in progress.  Thanks!

**Comment by joeyparrish** [comment]
MIME type 'application/mp4', codecs 'wvtt'
