### ISSUE TITLE
Stream keeps stalling on period change in DASH

### ISSUE THREAD

**Issue by jtrelak-vewd** [google/shaka-player#2773]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What link can we use to reproduce this?**
https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://livesim.dashif.org/livesim/utc_head/periods_60/testpic_2s/Manifest.mpd;panel=ALL_CONTENT;panelData=source:DASH_IF,DASH,MP4;build=uncompiled

**What version of Shaka Player are you using?**
v3.0.2-uncompiled

**What browser and OS are you using?**
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36

**What did you do?**

1. Start URL on browser
2. Click Play

**What did you expect to happen?**
The material should be played properly, playback should last for a long time (e.g. several minutes)

**What actually happened?**
Video is playing only for the first period. When the next period is expected to appear, the playback stops (each period lasts 60 seconds, so it is really easy to reproduce). The reproduction rate of this issue is 100%. I didn't noticed any particular error logs in devtools.
This URL is part of the dashif test vectors. It works fine on other players I tested (e.g. DASHIF Reference Client 2.9.1 http://reference.dashif.org/dash.js/v2.9.1/samples/dash-if-reference-player/index.html , I tested this player on the same version of Chrome browser)
This issue is very similar to this one, reported for HLS discontinuity:
https://github.com/google/shaka-player/issues/2687
but I'm not sure if root cause is the same.

**Comment by TheModMaker** [comment]
It looks like we're setting a too-large value for `appendWindowStart`.  I think it has something to do with SegmentTemplate generating segments outside the Period.

**Comment by joeyparrish** [comment]
Still reproducible in v3.0.7.

**Comment by joeyparrish** [comment]
Still reproducible in v3.0.8.

**Comment by joeyparrish** [comment]
I'm still able to reproduce this issue, but it looks like I might have been "lucky" before.  It doesn't reproduce at every period transition.

My preliminary investigation shows that it does not appear to be an issue with appendWindowStart as suggested earlier.  Still confirming, though.

**Comment by joeyparrish** [comment]
When this _does_ happen, I see a lot of HTTP 404 errors fetching segments that appear to be perfectly valid and should be accessible.  Still confirming this, too, though.

**Comment by joeyparrish** [comment]
Just played for 40 minutes straight without issue.  I'm wondering if we are really doing something wrong, or if there is an intermittent server-side issue.  I'll have to catch it again at least once to be able to say for sure.

**Comment by joeyparrish** [comment]
I've tried this one several more times, and I can't seem to reproduce it.  When I did manage it earlier, it was accompanied by HTTP 404 responses from the server.  So I'm inclined to assume it was a temporary outage on the server for now.
