### ISSUE TITLE
DASH video doesn't play

### ISSUE THREAD

**Issue by Kotekczu** [google/shaka-player#2775]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes.

**What version of Shaka Player are you using?**
Demo.

**Can you reproduce the issue with our latest release version?**
Yes.

**Can you reproduce the issue with the latest code from `master`?**
Yes.

**Are you using the demo app or your own custom app?**
Demo.

**If custom app, can you reproduce the issue using our demo app?**
Yes.

**What browser and OS are you using?**
Firefox.

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
.

**What are the manifest and license server URIs?**

I'm sending it by e-mail.

**What did you do?**

Just playing.

**What did you expect to happen?**
The video should play.

**What actually happened?**
I'm having issues to reproduce a DASH video. The player downloads the chunks and shows up the duration properly, but video and audio don't play. I don't see any error on debug, it just keeps loading while downloading the chunks. I can play it on VLC.

**Comment by joeyparrish** [comment]
> **What version of Shaka Player are you using?**
> Demo.

Can you specify the version number of the library, though?  This appears in the top-right corner of the demo app.

**Comment by Kotekczu** [comment]
Demo 3.0.2. Also tested in 2.5.14 with the same result.

**Comment by joeyparrish** [comment]
I can confirm that this video does not play.  There are no errors or warnings, and nothing is buffered.  The video has a duration (1:12:25), and 8 variants (2 audio languages x 4 video resolutions).  The content is DASH, there is only one period, and no presentationTimeOffsets are used.

**Comment by joeyparrish** [comment]
I got a reference to the first segment in the debugger with:

```js
player = video.ui.getControls().getLocalPlayer();
player.manifest_.variants[0].video.segmentIndex.references[0].getUris()[0];
```

I then analyzed that segment in thumbcoil (https://thumb.co.il/) and found that the base media decode time (the timestamp inside the MP4) is `4505309733`.  I then got the init segment URI in the debugger with:

```js
player.manifest_.variants[0].video.segmentIndex.references[0].initSegmentReference.getUris()[0];
```

I analyzed that init segment in thumbcoil, too, and found that the timescale in the `mdhd` box is `25`, while the timescale in the `mvhd` box is `1`.

So the timestamp of the first segment in seconds is either `4505309733` or `4505309733 / 25 = 180212389.32`, both of which are much larger than the content duration of `4345.730`.

So this is bad content.  To align the timestamps of the underlying media to the period, you need to use the `presentationTimeOffset` attribute in the DASH manifest.

I hope that helps!
