### ISSUE TITLE
Segmented TTML in MP4

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#278]
Write a plugin for TTML in MP4.

**Comment by joeyparrish** [comment]
MIME type 'application/mp4', codecs 'stpp'

**Comment by sanbornhnewyyz** [comment]
I know you guys are working hard on getting v2 out. Just curious if you have an estimate on this or if it's on the back burner for now.

**Comment by tdrews** [comment]
We are planning to complete this by the end of June.

**Comment by sanbornhnewyyz** [comment]
Great, thanks for the estimate.

**Comment by dougdoe** [comment]
Quickplay has a lot of interest in this feature, so we would be willing work early development branches or beta quality, if possible. Specifically, this is for supporting Closed Captions for live content, which will be provided to us as segmented TTML.
