### ISSUE TITLE
Compiled code from GitHub releases differs from NPM

### ISSUE THREAD

**Issue by bulkinav** [google/shaka-player#2782]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.14

**Please ask your question**

I found out that package/dist/shaka-player.compiled.js from https://github.com/google/shaka-player/releases/download/v2.5.14/shaka-player-2.5.14.tgz has differences in code unlike the version located in https://cdnjs.cloudflare.com/ajax/libs/shaka-player/2.5.14/shaka-player.compiled.js

After code reformat the shaka-player.compiled.js from CDNjs has about 100 lines less.

I'm curious to know why the files are different?

![Webstorm](https://i.ibb.co/0XK3qHK/Screenshot-2020-08-12-at-17-55-19.png)

**Comment by joeyparrish** [comment]
What's on CDNJS is pulled from NPM automatically.  What's attached to the v2.5.14 release was done manually, and it's possible I made some kind of mistake.  Or it's possible that something is missing from our NPM releases, and nobody has discovered it yet.

In your screenshot, I note that there is a reference to [EncryptionSchemePolyfills](https://github.com/google/eme-encryption-scheme-polyfill/).  Perhaps that is part of the problem.

For reference, see also #2738, where someone asked us to start attaching archives of the compiled releases on GitHub.  We never did this before v2.5.14, and it's still not automated.

I'll convert this to a bug report and we'll look into it.

**Comment by joeyparrish** [comment]
We just pushed v2.5.15 and v3.0.3 to NPM.

For both releases, I did the following:

1. `git clean -f -x -d`
2. Release via NPM and push tags to GitHub
3. `npm pack`
4. Attach the resulting tgz file to the GitHub release

Please let us know if you see a difference once the new releases hit CDNJS.

**Comment by bulkinav** [comment]
@joeyparrish yes, I confirm that the versions of these files are the same now.

**Comment by joeyparrish** [comment]
Then I expect the previous version was wrong because of a mistake I made in the pack & upload process.  I'll redo the tarballs for v2.5.14 and v3.0.2 and hopefully that will take care of it.

**Comment by joeyparrish** [comment]
I redid the tarballs from the previous two releases.  Unfortunately, these attachments were only very recently requested by our users, we haven't had time to invest in automation for this yet.  I'll be more careful about the process until then.  Please let us know if you see any other issues with the attachments.  Thanks!
