### ISSUE TITLE
Add note about CEA-608/708 support in DASH/HLS

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#2783]
The README file only mentions CEA-608/708 support for HLS, but not for DASH. It is also not mentioned that for HLS and DASH it is necessary to have mux.js. (in v3.1 it will not be necessary for DASH)

Is it possible to add this info to the README?

**Comment by avelad** [comment]
Maybe a table like this can help: https://exoplayer.dev/supported-formats.html

**Comment by avelad** [comment]
I am also seeing that mux.js still doesn't support CEA-708 (see https://github.com/videojs/mux.js/pull/346) but the README mentions that there is support.

In v3.0.x and earlier, the DASH parser allows parsing and exposing CEA-708 tracks, but is not actually supported.

**Comment by joeyparrish** [comment]
Thank you for pointing out these issues in the docs!
