### ISSUE TITLE
Incorrect KEYID format on Widevine protected HLS stream

### ISSUE THREAD

**Issue by chrisfillmore** [google/shaka-player#2789]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
Latest from master

**Can you reproduce the issue with our latest release version?**
Have not checked but I assume so

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Custom

**If custom app, can you reproduce the issue using our demo app?**
Probably but did not check

**What browser and OS are you using?**
Chrome 84 on macOS Catalina

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
Not necessary

**What did you do?**
Tried to load an HLS stream with the following `EXT-X-KEY` tag (some values modified/removed here):
```
#EXT-X-KEY:METHOD=SAMPLE-AES,URI="data:text/plain;base64,...",KEYID=0X634...,KEYFORMAT="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed",KEYFORMATVERSIONS="1"
```

**What did you expect to happen?**
Shaka should accept the KEYID

**What actually happened?**
Failed assertion "Incorrect KEYID format".

The problem is the uppercase `X`. Shaka does not accept `0X`, but does accept `0x`. I will write a PR to check to add a call to `toLowerCase()`. Is this ok?

**Comment by joeyparrish** [comment]
Yes, sounds good.  Thank you!
