### ISSUE TITLE
Large gaps in SegmentTemplate+duration live stream

### ISSUE THREAD

**Issue by torlangballe** [google/shaka-player#2797]
We have a client who has live dash/widevine tv streams. I am doing five minute test plays where I get Key Aquistion URL etc, and start a play. 70% of the time the player never starts, and pressing play doesn't help. Refresh or wigling slider a bit sometimes helps.

I think it might have something to do with the manifest saying it's live but only the publishTime changes.

I get to streaming, drm, and load, and one level of buffering, but it doesn't play, and no errors.

I've been trying everything for days now, having a clockSyncUri, waiting a bit to start play, seeking forward/back a bit and more, but nothing helps.

Manifest:
https://livelinearsddash2.akamaized.net/dash/live/2002852/ch026/master.mpd

Any ideas what the problem can be? Is that a proper way to do the manifest?

**Comment by torlangballe** [comment]
With a License Aquisition URL, I try playing in the Shaka Player Demo site online, and get same behaviour. DashIf reference player plays it fine.

**Comment by michellezhuogg** [comment]
Hello @torlangballe ,
We don't have permission to access your test manifest. Could you get us permission, so that we can reproduce your issue? Thank you!

**Comment by joeyparrish** [comment]
@torlangballe, here's what we see:

![Screenshot 2020-08-19 at 21 58 47](https://user-images.githubusercontent.com/6843156/90718656-5099ff80-e267-11ea-8bce-d6732f45a274.png)

**Comment by torlangballe** [comment]
Hi. I'm trying to get access for you. I confirmed it it ip-geo-blocked to the US at least, by using a free vpn.
It's fine here in Norway.

Will let you if there is a way to get access. Is there any way you can test via VPN?

**Comment by torlangballe** [comment]
Is seems the jumpLargeGaps config setting actually fixed the problem. For some reason it didn't work when I was trying to do it at home on wifi, but worked at work over ethernet. The clockSynUrl wasn't necessary or what helped.
Sorry for the late feedback, and thanks again for the help.
