### ISSUE TITLE
Resume playback after network disconnection

### ISSUE THREAD

**Issue by sanbornhnewyyz** [google/shaka-player#28]
I've noticed that if you lose your network connection during playback and then it reconnects, the player won't continue to buffer new data. However, the video element will still send 'playing' events if you press play. Is there any intention to add support for recovering form a network failure? And if not, is there any recommendation for  determining when playback is actually happening because clearly the 'playing' event is not a reliable indicator of playback.

Thanks for the hard work guys. Cheers.

**Comment by joeyparrish** [comment]
Good point.  Although whether or not to retry after a network failure could be considered an application-level decision, the application currently has no choice.

If we make shaka.media.Stream not only dispatch an error, but also set a timer to retry, then the application would have the choice of whether or not to shut down the Player when it sees the error event.
