### ISSUE TITLE
How does Shaka Player organize the offline media

### ISSUE THREAD

**Issue by olirehacek** [google/shaka-player#2803]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.3

**Please ask your question**

My question is regarding the implementation of "Offline Storage". I am working on an application
that can have multiple users. When the user logs in the application create an offline file that contains a list of "movies" that users bought (As a JSON) and only the movies for the specified user are listed in the GUI. 

These movies are Widevine encrypted and the JSON contains a field with "Manifest URL" and "License server URL". When the application starts the application lists available movies for the current user that can be downloaded when the user is online and can be played when the device is offline as long as the certificate is valid _(Very similar to demo "custom content" tab)_.

How does the shaka player stores these movies in persistent storage? How does it organize downloaded movies and recognizes them in the local storage (by the manifest url ? etc..). 

Can it recognize that the movies were downloaded for different users? 
For example: **User 1 have movie a and c** and **User 2 have only movie b** listed. 
Will it keep track of the downloaded files and its certificates?

Thank you.

**Comment by joeyparrish** [comment]
Content is stored using the browser's [IndexedDB API](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API).  We keep a table of offline content metadata, which includes a URL you use to load the content and custom JSON-encoded metadata from the app developer.  Another table stores segment data, which is linked to the content.

The offline playback URL (of the form `offline:123`) is the unique ID for the stored content.  If you have separate user profiles on top of the browser session, and you want to only show certain content to certain users, you should store some information of your own in the content's app-level metadata.  For example:

```js
  const metadata = {
    title,
    id,
    'downloaded': new Date(),
  };

  // "storage" is an instance of shaka.offline.Storage
  // "storedContent" is an instance of shaka.extern.StoredContent
  const storedContent = await storage.store(manifestUri, metadata);

  // LATER...

  player.load(storedContent.offlineUri);
```

You can list content with `await storage.list()`, which gets you a list of `shaka.extern.StoredContent` objects.  You can filter them using the `appMetadata` field.

See also:
 - StoredContent definition: https://shaka-player-demo.appspot.com/docs/api/shaka.extern.html#.StoredContent
 - Storage API: https://shaka-player-demo.appspot.com/docs/api/shaka.offline.Storage.html
 - Offline tutorial: https://shaka-player-demo.appspot.com/docs/api/tutorial-offline.html

Does this help?
