### ISSUE TITLE
Implementing Chrome Cast on Vue JS

### ISSUE THREAD

**Issue by tawanda14** [google/shaka-player#2805]
**This is an open question and a bit amateur really, i have managed to implement the video player on a Vue application, but i am struggling with implementing the chrome cast option particullary on how to scan for the presence of the devices and getting the ID of the device. If anyone has implemented the option in Vanilla JS or Vue, please point me to some resources or your source code ,**

**Comment by theodab** [comment]
Are you using Shaka Player? If not, this probably isn't the right place to ask. We aren't responsible for vue.js here; they have [their own GitHub page](https://github.com/vuejs/vue).

If you are using Shaka Player, you can make a CastProxy object. It will fire `caststatuschanged` events when a new receiver becomes available, and it has various methods such as `canCast`, `isCasting`, `receiverName`, etc that you can use to query casting status. You can see the entire public interface for the CastProxy object [here](https://shaka-player-demo.appspot.com/docs/api/shaka.cast.CastProxy.html). This stuff is automatically handled by [our UI library](https://shaka-player-demo.appspot.com/docs/api/tutorial-ui.html), too.

If you aren't using Shaka Player... well, the Cast team maintains [a developer tutorial](https://developers.google.com/cast/docs/developers) for making custom Chromecast senders.
On the Vue end... uh, there are various GitHub projects that seem like they might be relevant, like [this one](https://github.com/vrince/vue-chromecast) and [this one](https://github.com/xdemocle/vue-chromecast-plugin). I don't really know much about Vue, myself, so I can't vouch for their usefulness.

Does this help?

**Comment by tmuzanenhamo** [comment]
I am using shaka player, and through the CastProxy, i can use the methods like canCast, the question is how do i enable the casting because calling the cast method is not enabling the casting?

**Comment by theodab** [comment]
One possible problem that comes to mind is that you might not be loading the cast sender API.
```html
<script defer src="https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"></script>
```
But without seeing your code, I can't say for sure if this is the issue or not.

**Comment by tawanda14** [comment]
I have attached the code below for the basic implementation and i am getting an error, cannot read property length of undefined

<!DOCTYPE html>
<html>
  <head>
    
    <script src="dist/shaka-player.ui.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/shaka-player/3.0.0/shaka-player.ui.js" integrity="sha512-fhgAyaxE0AvUPX9WvDlr1r+XSSnpj0pg85Tkj8GyWYlXEROfQ/eCZSxpJEIFGSf17PxAC/+igm9xuzOqMz8NLQ==" crossorigin="anonymous"></script>
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/shaka-player/3.0.0/controls.css" integrity="sha512-TS02yWfWoXp/VbZjCcvC2rRoWY6Op4Q5Ym81+twXJsYBZ12a1M1dxoE0EDBjN6q5qB/L182pWbhIGlT6WLx3Iw==" crossorigin="anonymous" />
    
    <script defer src="https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"></script>
    
    <script src="myapp.js"></script>
  </head>
  <body>
    
    <div data-shaka-player-container style="max-width:40em"
         data-shaka-player-cast-receiver-id="CC1AD845">
       
            <video autoplay data-shaka-player id="video" style="width:100%;height:100%"></video>
    </div>
  </body>
</html>

**Comment by tawanda14** [comment]
`<!DOCTYPE html>
<html>
  <head>
    
    <script src="dist/shaka-player.ui.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/shaka-player/3.0.0/shaka-player.ui.js" integrity="sha512-fhgAyaxE0AvUPX9WvDlr1r+XSSnpj0pg85Tkj8GyWYlXEROfQ/eCZSxpJEIFGSf17PxAC/+igm9xuzOqMz8NLQ==" crossorigin="anonymous"></script>
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/shaka-player/3.0.0/controls.css" integrity="sha512-TS02yWfWoXp/VbZjCcvC2rRoWY6Op4Q5Ym81+twXJsYBZ12a1M1dxoE0EDBjN6q5qB/L182pWbhIGlT6WLx3Iw==" crossorigin="anonymous" />
    
    <script defer src="https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"></script>
    
    <script src="myapp.js"></script>
  </head>
  <body>
    
    <div data-shaka-player-container style="max-width:40em"
         data-shaka-player-cast-receiver-id="CC1AD845">
       
            <video autoplay data-shaka-player id="video" style="width:100%;height:100%"></video>
    </div>
  </body>
</html>`

**Comment by tawanda14** [comment]
https://codepen.io/tmuzanenhamo/pen/YzqGgMY

The code in the pen is returning a cannot read property length undefined in the console when i try to cast

**Comment by theodab** [comment]
The only problem I can see is that you are using the receiver app ID `CC1AD845`, which is the default media receiver. Shaka Player uses a custom receiver (most recent version: receiver app ID `930DEB06`).
However, that wouldn't account for the error you are seeing, I don't think. What platform are you running this on (e.g. Chrome on Windows, Safari on Mac, whatever)? Are you able to cast using our demo app?

**Comment by joeyparrish** [comment]
I also see two different copies of Shaka Player: one from `dist/`, and one from CDNJS.  Try removing one of them and fixing the receiver app ID as @theodab suggested.  When I make those changes in your codepen, it works fine for me when I cast.

I would also suggest updating from v3.0.0 to v3.0.3, the latest release.  We've fixed many bugs in the three releases since v3.0.0.

Apparently I can't save a codepen without an account, so here are the snippets of what I changed in yours:

```js
    <!-- Shaka Player ui compiled library: -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/shaka-player/3.0.3/shaka-player.ui.js"></script>
    <!-- Shaka Player ui compiled library default CSS: -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/shaka-player/3.0.3/controls.css" />
```

...

```js
    <div data-shaka-player-container style="max-width:40em"
         data-shaka-player-cast-receiver-id="930DEB06">
```

Does this help?

**Comment by tawanda14** [comment]
Thank you guys, works like a charm

**Comment by VictorHaine** [comment]
I got that same problem using React. Got it working by using the default cast receiver id on player initial configurations.
