### ISSUE TITLE
Tizen support (question)

### ISSUE THREAD

**Issue by peyoh** [google/shaka-player#281]
Hello,
just to ask if Shaka team have plans to support 
Samsung Tizen web browser?

Thank you,
Peyo

**Comment by joeyparrish** [comment]
Shaka Player supports any platform that supports the necessary web standards.  HTML5 video and MediaSource Extensions are hard requirements, and Encrypted Media Extensions is a requirement for protected content.

Please see http://shaka-player-demo.appspot.com/docs/tutorial-porting.html for more information.  You may also want to try a preview of the more detailed support-testing framework coming soon in Shaka v2: http://support.shaka-player-demo.appspot.com/

**Comment by peyoh** [comment]
Thank you!
