### ISSUE TITLE
Embedded closed captions in DASH removed from text tracks on manifest refresh

### ISSUE THREAD

**Issue by gesinger** [google/shaka-player#2811]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

Yes

**What version of Shaka Player are you using?**

3.0.3

**Can you reproduce the issue with our latest release version?**

Yes

**Can you reproduce the issue with the latest code from `master`?**

Yes

**Are you using the demo app or your own custom app?**

Demo

**If custom app, can you reproduce the issue using our demo app?**

N/A

**What browser and OS are you using?**

Chrome on MacOS

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

N/A

**What are the manifest and license server URIs?**

Problem is not apparent (live manifest doesn't refresh, at least not for 100 years):
https://livesim.dashif.org/livesim/testpic_2s/cea608_and_segs.mpd

vs

Problem is apparent (live manifest refreshes every 5 seconds, problem apparent after first refresh)
https://livesim.dashif.org/livesim/mup_5/testpic_2s/cea608_and_segs.mpd

**What did you do?**

For live manifests with embedded closed captions, Shaka successfully parses and presents the captions as a text track on first load of the manifest, but on subsequent loads the track is removed.

For instance, in the demo app using the second listed manifest above:

1) Open https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://livesim.dashif.org/livesim/mup_5/testpic_2s/cea608_and_segs.mpd;panel=CUSTOM%20CONTENT;build=uncompiled
2) Open the console and run `shakaDemoMain.player_.getTextTracks()`
3) After 5 seconds or more (after the manifest refreshes) run the above again

**What did you expect to happen?**

`getTextTracks()` returns all three text tracks: the subtitles track and the two embedded captions tracks (CC1 and CC3)

**What actually happened?**

On first load Shaka displays all three text tracks, but after the manifest refreshes, the two embedded captions tracks (CC1 and CC3) are no longer returned

**Additional Notes**

Looking into the code, the problem appears to be somewhat related to a TODO: https://github.com/google/shaka-player/blob/e7965fe21962833955a4f98c11e87f8931b721fd/lib/player.js#L1773-L1776

The text streams are created for the captions tracks on load. However, since the captions tracks are only created on first load, once the DASH manifest refreshes, the period combiner has no reference to the created track, and the text streams are overwritten. This seems to happen here: https://github.com/google/shaka-player/blob/e7965fe21962833955a4f98c11e87f8931b721fd/lib/dash/dash_parser.js#L441

I was looking into a possible solution, but wanted your advice and/or your help. I wasn't sure where the best spot was to put the fix, having not worked in the project before. A couple of solutions I was considering were:

1) Move the `createTextStreamsForClosedCaptions_` function into lib/util/periods.js and call it once the variants are created in `combinePeriods`: https://github.com/google/shaka-player/blob/e7965fe21962833955a4f98c11e87f8931b721fd/lib/util/periods.js#L211 . The issue I see there is that the tracks are recreated even if they are pre-existing, and the ID will change since it's using an external stream ID. One potential solution might be to store a reference to the text streams before updating the manifest, try to match up on `originalId`, and keep the pre-existing tracks that match.

2) Have the manifest parser create the text streams from the captions tracks. Since the `createTextStreamsForClosedCaptions_` function only seems to use the video portion of the variants, and the presence of the `closedCaptions` property, it may not be necessary to wait for the variants to be created before creating the text streams.

However, I was not sure if either of these were appropriate fixes.

If you don't have the time to address the issue, let me know what your thoughts are and I can try to put a PR together. But I'd be grateful if you had a fix you wanted to implement yourself.

Please let me know if you need any more information and what you think.

Thank you!

**Comment by theodab** [comment]
Yeah, this looks like a problem. I'll make a bugfix for it. Thanks for the report!

**Comment by gesinger** [comment]
Thank you @theodab !

**Comment by gesinger** [comment]
Thanks again @theodab , but wanted to mention one thing I saw while testing. If you want me to open as a new issue, please let me know, and I don't have an available stream to show the case (though can work on making an available one that if it helps), but it looks like this might fail an assertion and throw an exception when combining periods.

It looks like when the period combiner tries to combine text streams, it'll check for segmentIndex and throw an exception because the segmentIndex is null.

Period combiner:
https://github.com/google/shaka-player/blob/509e7b046a16f11f725fc15dd7d162f6ef0fc6ad/lib/util/periods.js#L721-L730

segmentIndex set to null when stream is created:
https://github.com/google/shaka-player/blob/509e7b046a16f11f725fc15dd7d162f6ef0fc6ad/lib/player.js#L4012

Would it make sense to create an empty segmentIndex when creating the stream? e.g., `new shaka.media.SegmentIndex([])`

Thanks!

**Comment by theodab** [comment]
That seems reasonable to me. I guess the case would be strongest if we knew for sure that these problems actually did happen (we probably don't have enough test content for embedded captions...), but adding an empty segmentIndex is a pretty negligible change in terms of performance, and examining the code in the period combiner I don't think it's going to have any weird side-effects.

**Comment by gesinger** [comment]
I haven't seen the stream remain perfectly stable (in that on new periods it seems to encounter gaps and pauses/breaks playback), but often before breaking this stream demonstrates the issue. I know it's not the best test case, but:

```
// should be a period every 60 seconds (60 times per hour) with a minimumUpdatePeriod of 2s
https://livesim.dashif.org/livesim/periods_60/mup_2/testpic_2s/cea608_and_segs.mp
```

When played in the demo player, even without turning on captions, the error is thrown.

After changing:

lib/player.js around line 4012 in `makeTextStreamsForClosedCaptions_`
```
-              segmentIndex: null,
+              segmentIndex: new shaka.media.MetaSegmentIndex(),
```

It no longer throws the error. In testing I also found that when gaps are encountered and playback stops, seeking past allows playback to resume.

Again, not the best stream for testing, but hopefully it helps in reproducing the issue.

Thanks again.

**Comment by gesinger** [comment]
No worries if you haven't had time to look at it yet, but wanted to @theodab in case closed issue messages got filtered. And thank you again!

**Comment by theodab** [comment]
Yeah, this looks like it works. Sorry it took a bit to get back to you, I ran into a secondary bug during testing, I think.
