### ISSUE TITLE
open source vast ads manager

### ISSUE THREAD

**Issue by mihaiav** [google/shaka-player#2814]
Is there any open source Ads manager that works with shaka?

 I'm trying to serve ads into my electron app and unfortunately Google IMA doesn't seem to work. Trying to debug it it's a nightmare as it seems to be closed source, it's trying to download and execute various "bridge" scripts and who knows what else is doing.

**Comment by joeyparrish** [comment]
I'm not aware of an open source ad manager, but you can try our IMA APIs in Shaka Player v3.0.x.  These APIs are in a beta state, meaning that there may still be API changes based on feedback from developers.  Any changes, including a promotion to "stable", will appear in the change log for future releases.

Please check out the tutorial and let us know if this helps!

https://shaka-player-demo.appspot.com/docs/api/tutorial-ad_monetization.html

**Comment by ismena** [comment]
@mihaiav are you looking for client-side or server side ad experience?
Are you using Shaka player in your app?

If you share more about what's not working, we can try to help or get you in touch with the IMA team to see if they might have some advice. They are pretty good at providing support for the SDK integrations.

**Comment by ismena** [comment]
On the subject of open source ad managers - when I was researching monetization solutions (before settling on the IMA for our integration), it seemed like IMA SDK was by far the most prevalent one out there.

You might be able to find something niche, but I'd try and give IMA my best shot first just for their market share and support/info availability.

**Comment by joeyparrish** [comment]
I think the OP's point about open source is that the IMA SDK isn't open source.  If there's an issue with IMA, they can't debug inside the IMA SDK.

**Comment by ismena** [comment]
@joeyparrish I understand. I don’t think I've heard of any, at least not widely used.

There is https://www.revive-adserver.com/ although I'm not sure if it suitable for media and have zero experience with it.

**Comment by mihaiav** [comment]
@joeyparrish I already tried the shaka / IMA integration using the demo provided in the documentation. As you've said my issue is really that IMA is not open source. With IMA you have a black box and you have no idea what exactly it's doing. It's a shame because the ads are based on standards (i.e. VAST).

Here were/are my integration issues with IMA:
 - It doesn't allow you to bundle the assets. Basically you need to always load IMA remotely only from Google's servers (i.e. https://imasdk.googleapis.com/js/sdkloader/ima3.js). If you don't do that it complains that it was loaded from a different domain name. This may be a big deal if you want reproducible builds or if you have a strict privacy policy.
 - If you load it and then remove the script tag (as it was in my case) IMA stops working. It complains it can't find a parentNode etc...I assume it uses document.currentScript and tries to navigate through the DOM or other such stuff.

IMA also seems to download a whole new player and use it to play the ads instead to use/reuse shaka. This doesn't bothers me too much but seems such a waste.

@joeyparrish Indeed there don't seem to be many open source ad managers. The best I could find is **rmp-vast** so I will have to make a plugin for shaka based on that. 

https://github.com/radiantmediaplayer/rmp-vast
