### ISSUE TITLE
Request filters for manifests don't work with native HLS

### ISSUE THREAD

**Issue by libor-arndt** [google/shaka-player#2815]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
YES

**What version of Shaka Player are you using?**
3.0.3

**Can you reproduce the issue with our latest release version?**
YES

**Can you reproduce the issue with the latest code from `master`?**
YES

**Are you using the demo app or your own custom app?**
custom

**If custom app, can you reproduce the issue using our demo app?**
no

**What browser and OS are you using?**
Safari13.0.3 MacOS Mojave 10.14.6

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

not relevant

**What did you do?**

In order to load the manifest file, I need to enhance the request headers with Authorization header with bearer token.
I registered a request filter to network engine of the shaka player that enhances the request.
It works for the dash iso mpd manifests with widevine DRM, but the filter is not invoked on Safari for HLS m3u manifest with FPS DRM.
It may happen because the HLS playback is native and therefore shaka-player networking engine is not used, but I am not sure and thats why I report it as possible bug as I was advised

thanks for any help or explanation

Add test filter like this

```
player.getNetworkingEngine().registerRequestFilter(function(type, request) {

            console.log("test filter request", request);
          });
```

**What did you expect to happen?**
Request filter is invoked

**What actually happened?**

Request filter was not invoked

**Comment by joeyparrish** [comment]
> the filter is not invoked on Safari for HLS m3u manifest with FPS DRM

> It may happen because the HLS playback is native and therefore shaka-player networking engine is not used, but I am not sure and thats why I report it as possible bug

You're exactly right.  With native HLS, we have no control over the loading of the manifest.  And with FairPlay, native HLS is currently our only option.

Does your service offer an alternative to the header-based authentication?  I don't have direct evidence for this, but I would guess that native HLS would be compatible with cookie-based authentication.

**Comment by libor-arndt** [comment]
Thanks, I probably will autorize HLS with tokenized url
