### ISSUE TITLE
Develop a p2p plugin for jwplayer with shaka engine

### ISSUE THREAD

**Issue by Niharika098** [google/shaka-player#2821]
Hi I wanted to check how to go forward with building a provider with jwplayer which allows p2p streaming similar to the one build by streamroot https://www.jwplayer.com/developers/web-player-demos/peer-accelerated-delivery/ . I could see everything is closed source and there are no resources to get started with.

In case of jwplayer with hls there is a plugin https://github.com/hola/jwplayer-hlsjs which can be attached and used with open source p2p engines. If I want to build similar provider for playing mpeg-dash in jwplayer with shaka engine what would be the way to go forward ?

Any help would be appreciated.

**Comment by joeyparrish** [comment]
Streamroot has support for Shaka Player directly.  Check out these articles (not sure which is more applicable to your case):

 - https://support.streamroot.io/hc/en-us/articles/360000764953-Shaka-Player
 - https://support.streamroot.io/hc/en-us/articles/360008879320-Custom-ShakaPlayer-XMLHttpRequest

Note that in their articles, they reference older versions of Shaka Player (v2.4.6 and v2.5.5).  You should use the latest versions, which are currently v2.5.16 and v3.0.4.

Does this help?

**Comment by Niharika098** [comment]
Thanks joeyparrish for replying. 

Streamroot is a commercial solution. If I would want to develop an open-source solution involving building a provider for jwplayer with shaka engine, can you suggest what could be the way going forward.

**Comment by joeyparrish** [comment]
Ah, I see.  I'm not familiar with JW's API at all.  If you have links to a doc about what the integration points are, we could help you map that to Shaka Player's API.  Would that help?

**Comment by Niharika098** [comment]
Thanks joeyparrish for offering help. I would look into jwplayer api and try to figure how it can be stitched with shaka engine and would update if any progress. Closing the issue for now.
