### ISSUE TITLE
Getting VoD stream total duration from the manifest

### ISSUE THREAD

**Issue by MilosRasic** [google/shaka-player#2822]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
3.0.3

**Please ask your question**
Using `getManifest()?.presentationTimeline.getDuration()` to get total duration of the video from the manifest.
Getting this warning in the console:
player.js:3865 Shaka Player's internal Manifest structure is NOT covered by semantic versioning compatibility guarantees.  It may change at any time!  Please consider filing a feature request for whatever you use getManifest() for.

Is there a better way to do this or should I open a feature request to expose `getDuration()` on a higher level?

**Comment by joeyparrish** [comment]
You should be able to use `mediaElement.duration`, where `mediaElement` is a reference to the `<video>` or `<audio>` tag you're using with Shaka Player.

Does this help?

**Comment by TheModMaker** [comment]
You could also use `player.seekRange()` to determine the end of the video.

**Comment by MilosRasic** [comment]
Thanks. Both options work. I assumed video element would have only the duration of the current buffer. Clearly I have a lot more to learn about this :slightly_smiling_face: 

For future reference:

`player.getManifest()?.presentationTimeline.getDuration()` ⚠️

`mediaElement.duration` ✅

`player.seekRange().end` ✅
