### ISSUE TITLE
trickPlay causing stutter on iOS Safari upon playbackRate change.

### ISSUE THREAD

**Issue by johannds** [google/shaka-player#2823]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.3, but issue also occurs on all other versions I've tested.

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Custom app.

**If custom app, can you reproduce the issue using our demo app?**
No. There is no trick play demo in the demo app that works on iOS.

**What browser and OS are you using?**
Safari and UIWebview iOS 13.6.1

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
Any HLS stream.

**What did you do?**
```
      setInterval(() => {
        player.trickPlay(Math.random() > 0.5 ? 1 : 1.07)
      }, 5000)
```

I created a testbed to troubleshoot this issue. In my code I toggle between playing the video a little faster every 5 seconds. Each time the playback rate changes, there is a stutter in the video. This doesn't happen on Desktop.

This is not production code, but mimics what we do in production to keep the video in line with overlays and data displayed on the screen.

My <video> tag looks like this:

```
 <video id="video" playsinline defaultPlaybackRate="1.0" width="414"
    poster="//shaka-player-demo.appspot.com/assets/poster.jpg" controls></video>
```

The stutter seems to happen as soon as the playbackRate change event fires.

**What did you expect to happen?**
I expect the stream to slow down and speed up like it does on desktop without skips or stutters.

**What actually happened?**
The video stutters and has a ~50-100ms skip.

**Comment by joeyparrish** [comment]
@johannds, can this effect be seen on a plain MP4 in a video element, without Shaka Player?  I don't have an iOS device available at home to test this myself.

Since iOS playback is handled by Safari natively, it's possible that we won't be able to address this, and that you will need to file a bug on Apple/Safari/WebKit.  If it only happens with Shaka Player, though, that would be a good clue that it might be our fault.

**Comment by johannds** [comment]
Hey @joeyparrish Thanks for the quick response! 

I don't think you folks are to blame here. https://bugs.webkit.org/show_bug.cgi?id=163433 I believe that this webkit bug from **2016** probably relates. 

I've tested it in a plain video element and there is definitely a very noticeable glitch whenever I change the playback rate, even without Shaka Player.

The Apple documentation also seems to mention that iOS Safari doesn't actually support this: https://developer.apple.com/documentation/webkitjs/htmlmediaelement/1629746-playbackrate 

I'll close this one. I hope this information helps others who run into this issue.

**Comment by joeyparrish** [comment]
Thanks for the update and helpful links!
