### ISSUE TITLE
Video robustness SW_SECURE_DECODE does not play in Chrome Desktop

### ISSUE THREAD

**Issue by johnluther** [google/shaka-player#2826]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.3

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
My own

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Chrome Windows 84.0.4147.135 Stable
Chrome Mac 85.0.4183.83 Beta

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
n/a

**What are the manifest and license server URIs?**
emailed

**What did you do?**
Tried to play Widevine content with `videoRobustness = SW_SECURE_DECODE` in Shaka config and content key "security_level = 2"(SW_SECURE_DECODE) in the license.

**What did you expect to happen?**
The content to play, based on EME configuration content type and video robustness level promises resolving, (see attached screen grab)

**What actually happened?**
Shaka Error code 4012 with restrictedKeyStatus of 'internal-error' (See attached Console screen grab)

I am able to play the content with video robustness and key security level of SW_SECURE_CRYPTO

Thanks!

![error-4012](https://user-images.githubusercontent.com/114623/91334805-7bbbac00-e79d-11ea-9123-31ebe21e2dd4.png)

![SW_SECURE_DECODE](https://user-images.githubusercontent.com/114623/91334786-7199ad80-e79d-11ea-9df9-2f744aa88468.png)

**Comment by joeyparrish** [comment]
With Chrome 85 stable on Windows, I see error 6001 (`REQUESTED_KEY_SYSTEM_CONFIG_UNAVAILABLE`), rather than 4012 (`RESTRICTIONS_CANNOT_BE_MET`).  If the requested robustness level can't be satisfied, 6001 would be expected.  But it's not clear why you got 4012 instead.

I'll double-check with the Chrome CDM team to see if `SW_SECURE_DECODE` is expected to work for video on desktops.

**Comment by joeyparrish** [comment]
Actually, I see 4012 now.  I was getting 6001 because I was not initially using https on the test page URL you sent.

**Comment by joeyparrish** [comment]
EME logger shows a `usable` key status, followed quickly by an `internal-error` key status on the same session and key ID.  This cycle appears to repeat 8 times.

I have no idea what to make of that.  I'll ask the Chrome CDM team to take a look.  Thanks!

**Comment by joeyparrish** [comment]
I should also note that this issue cannot be reproduced in ChromeOS.

**Comment by johnluther** [comment]
Interesting. I *think* CrOS in verified mode supports an L2-ish robustness but am not 100% sure. I'm working on getting one here for our testing. Thanks, Joey!

**Comment by joeyparrish** [comment]
As I understand it, CrOS shows up as an L1 device unless it's in dev mode.

**Comment by xhwang-chromium** [comment]
John: This is Xiaohan. Nice to meet you here!

Are you using the same audio/video key in the playback? SW_SECURE_DECODE is only supported for video, not audio. If you try to use the SW_SECURE_DECODE key for audio, it'll end up with a "No Key" and the media pipeline will stall. At the same time, the CDM will update the key status to be "internal-error", which is actually not spec compliant. I'll file a bug on that internally.

For your playback, it's strongly recommended to use separate keys for audio and video, and separate keys for different resolutions of video. If you have to use the same key for audio and video, the best security level we can support is SW_SECURE_CRYPTO.

**Comment by johnluther** [comment]
Thanks, Xiaohan, good to hear from you, too! Please say hi to everyone from me.

After more testing yesterday I was worried that the single key was the issue. The partner we are working with currently does not support multi-key. I've been working with them to add support, hopefully they will have it soon. 

I will use SW_SECURE_CRYPTO for now and close this issue. Thanks to you and @joeyparrish !
