### ISSUE TITLE
Offline Storage and Playback demo with custom license server URL

### ISSUE THREAD

**Issue by olirehacek** [google/shaka-player#2827]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**Please ask your question**

I am searching for help with expanding the following demo : 
https://shaka-player-demo.appspot.com/docs/api/tutorial-offline.html 

With option do specify Custom License Server URL.  So I can play and download (for offline playback) widevine DASH from our Azure server?

I have followed this article : https://shaka-player-demo.appspot.com/docs/api/tutorial-license-server-auth.html
But I am still unsure how to store such a certificate to persistent storage for offline mediaplay.

The documentation is pretty clear on how to play DASH and store video, but I can't seem to find any documentation on how to store certificate for offline playback.
Can you please point me in the right direction or maybe post an example that includes such functionality?
Thanks.

**Comment by joeyparrish** [comment]
You configure the Player/Storage instance for your license server as in the DRM tutorials, then call `store()` as in the offline tutorial.  If the `Storage` instance was constructed with a `Player` instance, then the DRM config on the Player will apply to the offline content.  If `Storage` was constructed without a `Player` instance in the constructor, then you configure that, instead.

Does this answer your question?
