### ISSUE TITLE
Regression in how subtitles are displayed with line breaks.

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#2828]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes

**What version of Shaka Player are you using?** 3.0.3

**Can you reproduce the issue with our latest release version?** Yes

**Can you reproduce the issue with the latest code from `master`?** Yes

**Are you using the demo app or your own custom app?** Both

**If custom app, can you reproduce the issue using our demo app?** Yes

**What browser and OS are you using?**
Chrome 84, macOS 10.15.6

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

I will send an email with the details.

**What did you do?**

Load a stream

**What did you expect to happen?**
Subtitles are displayed correctly

**What actually happened?**

Subtitles are displayed incorrectly. In version 3.0.2 they are shown correctly, I think the regression is introduced here: https://github.com/google/shaka-player/commit/6c85c8cbfc1df2a2c8a34ff8b548b2fcf5ff7dea

In 3.0.3
![image](https://user-images.githubusercontent.com/8983024/91464315-bb14f600-e88c-11ea-87fa-fb233d9eb60c.png)

In 3.0.2
![image](https://user-images.githubusercontent.com/8983024/91464362-c9631200-e88c-11ea-9d9e-c73295a0d3d0.png)

```
<?xml version="1.0" encoding="utf-8"?>
<tt ttp:timeBase="media" xml:lang="" xmlns="http://www.w3.org/ns/ttml" xmlns:ttm="http://www.w3.org/ns/ttml#metadata" xmlns:ttp="http://www.w3.org/ns/ttml#parameter" xmlns:tts="http://www.w3.org/ns/ttml#styling">
  <head>
    <styling>
      <style tts:backgroundColor="#00000000" tts:color="#ffffff" tts:fontFamily="proportionalSansSerif" tts:fontSize="68%" xml:id="speakerStyle"/>
      <style tts:color="#ffffff" tts:fontStyle="normal" tts:fontWeight="normal" tts:textDecoration="none" xml:id="style_0"/>
    </styling>
    <layout>
      <region style="speakerStyle" tts:displayAlign="after" tts:extent="68% 16%" tts:origin="14% 80%" tts:textAlign="center" xml:id="speaker_1"/>
      <region style="speakerStyle" tts:displayAlign="after" tts:extent="80% 35%" tts:origin="10% 60%" tts:textAlign="center" xml:id="speaker_2"/>
    </layout>
  </head>
  <body>
    <div>
      <p begin="49572:29:48.916" end="49572:29:49.916" region="speaker_1" xml:id="p_0000">
        <span style="style_0">Ya has mentido</span>
        <br/>
        <span style="style_0">bastante a la poli por mí.</span>
      </p>
      <p begin="49572:29:49.916" end="49572:29:50.916" region="speaker_2" xml:id="p_0001"/>
    </div>
  </body>
</tt>
```

**Comment by theodab** [comment]
Actually, it looks like this has already been fixed, in https://github.com/google/shaka-player/commit/565bb7d88070778dc53e5c8495500b9bedb1b139.

**Comment by avelad** [comment]
@theodab , You are correct, it is fixed in the master but not in the v3.0.x, is it possible to cherry pick the change?

**Comment by joeyparrish** [comment]
Because the fix in `master` involves changes that may affect external TextDisplayer plugins, the best we could do for v3.0.x would be to revert the change that caused this.  It was, perhaps, a mistake to cherry-pick that for v3.0.x in the beginning.

@avelad, what are your thoughts on that?

**Comment by avelad** [comment]
Yes, I think it would be for the best (revert the change)

Other alternatives are:
- Make a fix only in the v3.0.x branch
- Make an exception and introduce a breaking change.

**Comment by avelad** [comment]
@joeyparrish , can you revert the change for the next release of 3.0.x?

**Comment by michellezhuogg** [comment]
Hello @avelad ,

Sorry that we didn't fix it and test with your manifest sooner. Would you please let us know if it's fixed now?

**Comment by avelad** [comment]
@michellezhuogg It is fixed in the master but not in v3.0.x

**Comment by joeyparrish** [comment]
A fix has gone into v3.0.x.  @avelad, can you please confirm at your earliest convenience?

**Comment by avelad** [comment]
Now it's fixed, thanks!

**Comment by joeyparrish** [comment]
Thank you!
