### ISSUE TITLE
Extracting the players codec at a particular instance in time

### ISSUE THREAD

**Issue by rdailey98** [google/shaka-player#2832]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v3.0.2

**Please ask your question**
Looking to extract the codec the player is using at a given instance in time for telemetry event purposes. Is there a function or event that can help achieve this?

- `getStats()` seemed to be useful at first glance but unfortunately contains no info about the current codec.
- There's the `shaka.Player.StreamingEvent`, although for our purposes it would be counter intuitive to parse an event in order to fire off an other event.
- There's the `Stream` object, however this contains a list of codecs not the current one being used.

Any help would be greatly appreciated - please let me know if I'm overlooking anything.

**Comment by TheModMaker** [comment]
We don't support codec switching, so the array will only contain one kind of codec.  They may have different profiles, but they should have the same base codec.  You should use `player.getVariantTracks()` to get the tracks, the `codecs` field will have the array of codecs.  Unfortunately due to Period flattening, there is no  way to determine which is being used.

**Comment by rdailey98** [comment]
> We don't support codec switching, so the array will only contain one kind of codec. They may have different profiles, but they should have the same base codec. You should use `player.getVariantTracks()` to get the tracks, the `codecs` field will have the array of codecs. Unfortunately due to Period flattening, there is no way to determine which is being used.

Appreciate the response, I'll give `player.getVariantTracks()` a go. When you say there is no way to determine which is being used - do you mean which profile? i.e. if the codec is `HEVC` we can't determine whether `Main`, `Main 10`, etc. is being used.

**Comment by TheModMaker** [comment]
Actually looking over our definitions, I don't know why the `codecs` field would be an array, it should be a string.  In the Track definition, it will have two codecs (e.g. `vp09,opus`), for audio+video; but there is also the `audioCodec`/`videoCodec` fields.

**Comment by rdailey98** [comment]
Looking for a bit more clarification - One of the DASH features for example is multi-codec support (suppose I had a manifest with AVC and HEVC tracks). If I were to make a call on `getVariantTracks()` would the returned array have a single unique codec (i.e. AVC or HEVC) or would it still contain both?

**Comment by TheModMaker** [comment]
Until we support codec switching (#1528), we filter out codecs that don't match the initial codec selected.  We pick the initial codec based on browser support and on bandwidth; once we pick a codec, we filter out all other codecs so you'll only see choices for one.
