### ISSUE TITLE
new Configuration - ignore maxSegmentDuration from the manifest

### ISSUE THREAD

**Issue by Yuvalke** [google/shaka-player#2834]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes.

**Is your feature request related to a problem? Please describe.**

Yes, there are streams with incorrect maxSegmentDuration value which I would like to be able to ignore it and see if calculations are fixed. 

**Describe the solution you'd like**

To ignore maxSegmentDuration from the manifest.

**Describe alternatives you've considered**

**Additional context**

**Comment by joeyparrish** [comment]
This sounds very reasonable.  You could add it to config.manifest.dash and use it in dash_parser.js to ignore the maxSegmentDuration value.  Are you interested in sending a PR?

**Comment by Yuvalke** [comment]
@joeyparrish Sure, I'll add it
