### ISSUE TITLE
Encrypted live channel has freezes and get into buffering for a very long time.

### ISSUE THREAD

**Issue by Yuvalke** [google/shaka-player#2835]
Same issue as (https://github.com/google/shaka-player/issues/2707)

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes.

**What version of Shaka Player are you using?**
v3.0.4, the same issue on v2.5.13 as well

**Can you reproduce the issue with our latest release version?**
Yes.

**Can you reproduce the issue with the latest code from `master`?**
Didn't try it.

**Are you using the demo app or your own custom app?**
Standalone page with shaka.

**If custom app, can you reproduce the issue using our demo app?**
Didn't play the demo on TV.

**What browser and OS are you using?**
Webos 3.5 and Webos 4

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
05.10.40

**What are the manifest and license server URIs?**

sent to email - manifest and logs. 

**What did you do?**

play the source.

**What did you expect to happen?**

the stream will play without buffering at all.

**What actually happened?**

the stream play for a few hours/days and it starts buffering for a day.

The issue doesn't easy to reproduce since playback could play for a few days and then enter to buffering and smartTV could handle such a huge printout so I added a listener to the buffering event and change the log from shaka to v2 for 15s(there are gaps on logs because of that).

**Comment by michellezhuogg** [comment]
Hello @Yuvalke ,

Would you please also send us the DRM license info? Thank you!

**Comment by Yuvalke** [comment]
Hi @michellezhuogg,

It's private media, I can open access to this media for static IP. 
do you have static IP?

Thanks

**Comment by joeyparrish** [comment]
The team is all working from home during the pandemic, so I don't think we can guarantee a static IP right now.  Is access only allowed in one particular country or area?  We can VPN through specific countries, if that's helpful.
