### ISSUE TITLE
player fails to start on some dash manifests

### ISSUE THREAD

**Issue by mihaiav** [google/shaka-player#2836]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

yes 
**What version of Shaka Player are you using?**

3.0.4
**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `master`?**
yes

**Are you using the demo app or your own custom app?**
custom and demo app

**If custom app, can you reproduce the issue using our demo app?**
yes

**What browser and OS are you using?**
Chrome and MacOS

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

https://manifest.googlevideo.com/api/manifest/dash/expire/1599499727/ei/bxlWX_W7Jsua1gLm6JXwAg/ip/2a02%3A2f0b%3Aae06%3A2b00%3Af120%3A79a0%3A51f2%3A7c06/id/9Auq9mYxFEE.1/source/yt_live_broadcast/requiressl/yes/tx/23908006/txs/23908006%2C23908007/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/vprv/1/pacing/0/keepalive/yes/beids/9466585/itag/0/playlist_type/DVR/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Ctx%2Ctxs%2Cas%2Cvprv%2Citag%2Cplaylist_type/sig/AOq0QJ8wRQIhALgQDNQU4dOqNWX9_cMRsMgb7leP-4pvAVqBjmNyzjTOAiA3rBQ4Yfe1TA1srhiutePiBOUK987DolMd-ln3TBHx_A%3D%3D

**What did you do?**

tried to play a google video manifest

**What did you expect to happen?**

 play it
**What actually happened?**

Shaka seems to keep updating the manifest but never plays anything 

The debug message in the console is as follows 

```
No Period ID given for Period with start time 26771390.001,  Assigning a default
dash_parser.js:1032 Updating manifest...
dash_parser.js:555 No Period ID given for Period with start time 26771400.001,  Assigning a default
dash_parser.js:1032 Updating manifest...
......

```

Steps to reproduce: 

- Open chrome with CORS disabled 
``` open -na Google\ Chrome --args --user-data-dir=/tmp/`openssl rand -base64 6` --disable-web-security --disable-site-isolation-trials```
 - Open the demo app using the manifest provided above 

 https://shaka-player-demo.appspot.com/demo/#audiolang=en-GB;textlang=en-GB;uilang=en-GB;asset=https://manifest.googlevideo.com/api/manifest/dash/expire/1599499727/ei/bxlWX_W7Jsua1gLm6JXwAg/ip/2a02%3A2f0b%3Aae06%3A2b00%3Af120%3A79a0%3A51f2%3A7c06/id/9Auq9mYxFEE.1/source/yt_live_broadcast/requiressl/yes/tx/23908006/txs/23908006%2C23908007/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/vprv/1/pacing/0/keepalive/yes/beids/9466585/itag/0/playlist_type/DVR/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Ctx%2Ctxs%2Cas%2Cvprv%2Citag%2Cplaylist_type/sig/AOq0QJ8wRQIhALgQDNQU4dOqNWX9_cMRsMgb7leP-4pvAVqBjmNyzjTOAiA3rBQ4Yfe1TA1srhiutePiBOUK987DolMd-ln3TBHx_A%3D%3D;panel=CUSTOM%20CONTENT;build=uncompiled 

Manifest content just incase the URL expires: 

https://www.dropbox.com/s/nitrrj0lzzafw0l/x.mpd?dl=1

**Comment by michellezhuogg** [comment]
Hello @mihaiav ,
I'm got Error 403 (Forbidden) when I loaded the test manifest. It looks like we don't have permission to get the url. Could you please get the permission? Thank you!

**Comment by michellezhuogg** [comment]
Hello @mihaiav ,

I got HTTP 403 (Forbidden) error when I tried to load the manifest. It looks like we don't have the permission to access the url. Could you please get us the permission? Thank you!

**Comment by joeyparrish** [comment]
@mihaiav, can you please send updated URLs?  We can not access the ones you sent before.
