### ISSUE TITLE
Does the src of the video have changed and do I have to reload it when I return?

### ISSUE THREAD

**Issue by taka-sho25** [google/shaka-player#2837]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
3.0.1

**Please ask your question**
Hi All.

I am using google ima client-side on iOS.

After playing ad with mid-roll, the video cannot be played from the continuation.

src of video tag is
Video manifest => google vamp => Video manifest
Will be.

Since other browsers have two video tags, they can be played back without problems.

ad's onContentResumeRequested event fired,
Is there a way to play the rest when the src is changed to the video manifest?

Thanks.

**Comment by joeyparrish** [comment]
This is not supported yet.  Please see #2792.  In short, on platforms like iOS which cannot have multiple video elements, we need to be able to detach from the element, play the ad, the reattach and resume playback.

Does this answer your question?
