### ISSUE TITLE
Why 2 shaka-player versions are released? 2.5.x and 3.0.x?

### ISSUE THREAD

**Issue by sridhard** [google/shaka-player#2838]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.4

**Please ask your question**
When I check the releases, always 2 vesions of player are released. One is 2.5.x and another is 3.0.4. Why there are 2 versions?

**Comment by TheModMaker** [comment]
We are still maintaining the v2.5.x releases for old users who don't want to upgrade to v3.x yet.  We cherry-pick the important bug fixes to the old branch to keep the old behavior/API.  New users should use the highest version available.

**Comment by sridhard** [comment]
ok thanks
