### ISSUE TITLE
Playready DRM failing with error MissingKeys

### ISSUE THREAD

**Issue by sridhard** [google/shaka-player#2840]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
Shaka Hosted Demo. Also tested with latest 3.0.x and 2.5.x

**Can you reproduce the issue with our latest release version?**
Yes. tested with latest 3.0.x and 2.5.x

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Shaka hosted demo

**If custom app, can you reproduce the issue using our demo app?**
Yes. Using demo app

**What browser and OS are you using?**
Windows-10, Microsoft Edge Version 85.0.564.44

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
NA

**What are the manifest and license server URIs?**
Using shaka hosted demo. We are playing the below content which has only playready DRM:
Content: Tears Of Steel (PlayReady)
Note: I am getting the same error with my content also

**What did you do?**
Just play the above content from hosted demo

**What did you expect to happen?**
Play should be success

**What actually happened?**
Play failed with the below error:

player.js:1054 Starting load of https://demo.unified-streaming.com/video/tears-of-steel/tears-of-steel-dash-playready.ism/.mpd...
drm_engine.js:858 Created MediaKeys object for key system com.microsoft.playready
main.js:1653 shaka.util.Error {severity: 2, category: 4, code: 4012, data: Array(1), handled: false, …}
onError_ @ main.js:1653
onErrorEvent_ @ main.js:1631
onErrorEvent @ main.js:371
dispatchEvent @ fake_event_target.js:96
playerProxyLocalEvent_ @ cast_proxy.js:718
(anonymous) @ cast_proxy.js:270
dispatchEvent @ fake_event_target.js:96
onError_ @ player.js:4512
updateAbrManagerVariants_ @ player.js:4237
onKeyStatus_ @ player.js:4658
onKeyStatus @ player.js:1660
processKeyStatusChanges_ @ drm_engine.js:1443
(anonymous) @ drm_engine.js:102
(anonymous) @ timer.js:65
onTick @ delayed_tick.js:56
setTimeout (async)
tickAfter @ delayed_tick.js:60
tickAfter @ timer.js:66
onKeyStatusesChange_ @ drm_engine.js:1417
(anonymous) @ drm_engine.js:1036
main.js:1653 shaka.util.Error {severity: 2, category: 4, code: 4012, data: Array(1), handled: false, …}category: 4code: 4012data: Array(1)0: hasAppRestrictions: falsemissingKeys: Array(1)0: "10000000100010001000100000000001"length: 1__proto__: Array(0)restrictedKeyStatuses: Array(0)length: 0__proto__: Array(0)__proto__: Objectlength: 1__proto__: Array(0)concat: ƒ concat()constructor: ƒ Array()copyWithin: ƒ copyWithin()entries: ƒ entries()every: ƒ every()fill: ƒ fill()filter: ƒ filter()find: ƒ find()findIndex: ƒ findIndex()flat: ƒ flat()flatMap: ƒ flatMap()forEach: ƒ forEach()includes: ƒ includes()indexOf: ƒ indexOf()join: ƒ join()keys: ƒ keys()lastIndexOf: ƒ lastIndexOf()length: 0map: ƒ map()pop: ƒ pop()push: ƒ push()reduce: ƒ reduce()reduceRight: ƒ reduceRight()reverse: ƒ reverse()shift: ƒ shift()slice: ƒ slice()some: ƒ some()sort: ƒ sort()splice: ƒ splice()toLocaleString: ƒ toLocaleString()toString: ƒ toString()unshift: ƒ unshift()values: ƒ values()Symbol(Symbol.iterator): ƒ values()Symbol(Symbol.unscopables): {copyWithin: true, entries: true, fill: true, find: true, findIndex: true, …}__proto__: Objecthandled: falsemessage: "Shaka Error MANIFEST.RESTRICTIONS_CANNOT_BE_MET ([object Object])"severity: 2stack: "Error: Shaka Error MANIFEST.RESTRICTIONS_CANNOT_BE_MET ([object Object])↵    at new shaka.util.Error (https://shaka-player-demo.appspot.com/lib/util/error.js:97:17)↵    at shaka.Player.checkRestrictedVariants_ (https://shaka-player-demo.appspot.com/lib/player.js:4791:13)↵    at shaka.Player.updateAbrManagerVariants_ (https://shaka-player-demo.appspot.com/lib/player.js:4235:12)↵    at shaka.Player.chooseVariant_ (https://shaka-player-demo.appspot.com/lib/player.js:4262:14)↵    at shaka.Player.chooseVariantAndSwitch_ (https://shaka-player-demo.appspot.com/lib/player.js:4299:32)↵    at shaka.Player.onKeyStatus_ (https://shaka-player-demo.appspot.com/lib/player.js:4664:12)↵    at Object.onKeyStatus (https://shaka-player-demo.appspot.com/lib/player.js:1660:14)↵    at shaka.media.DrmEngine.processKeyStatusChanges_ (https://shaka-player-demo.appspot.com/lib/media/drm_engine.js:1443:27)↵    at shaka.util.Timer.onTick_ (https://shaka-player-demo.appspot.com/lib/media/drm_engine.js:102:41)↵    at shaka.util.DelayedTick.onTick_ (https://shaka-player-demo.appspot.com/lib/util/timer.js:65:12)"__proto__: Object
onError_ @ main.js:1653
onErrorEvent_ @ main.js:1631
onErrorEvent @ main.js:371
dispatchEvent @ fake_event_target.js:96
playerProxyLocalEvent_ @ cast_proxy.js:718
(anonymous) @ cast_proxy.js:270
dispatchEvent @ fake_event_target.js:96
onError_ @ player.js:4512
updateAbrManagerVariants_ @ player.js:4237
chooseVariant_ @ player.js:4262
chooseVariantAndSwitch_ @ player.js:4299
onKeyStatus_ @ player.js:4664
onKeyStatus @ player.js:1660
processKeyStatusChanges_ @ drm_engine.js:1443
(anonymous) @ drm_engine.js:102
(anonymous) @ timer.js:65
onTick @ delayed_tick.js:56
setTimeout (async)
tickAfter @ delayed_tick.js:60
tickAfter @ timer.js:66
onKeyStatusesChange_ @ drm_engine.js:1417
(anonymous) @ drm_engine.js:1036

**_NOTE: The above DRM has only playready. When I play for first time we will get 4012 error and the play will not start. If we play again, again we will get 4012 error, but the play starts. This issue was not there in older versions and it is working properly in our production._**

**Comment by valotvince** [comment]
Hi @sridhard,

That #2855 should correct it !

**Comment by joeyparrish** [comment]
Fixed in #2855.  Thanks!
