### ISSUE TITLE
Polyfill needed for TextDecoder/TextEncoder

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#2843]
This commit introduced the use of TextDecoder/TextEncoder: https://github.com/google/shaka-player/commit/a72a1e91023a33c777a6001a64f818ea2e469914

This is not supported in IE, which will soon drop, nor in legacy Edge, which I think we will need to continue supporting in some capacity for the time being.  (At the very least, we still have it in our lab environment.)

Interestingly, this _is_ supported in Tizen 3, which is somewhat of a relief.

We could choose to include a polyfill in Shaka Player, or we could choose to recommend one for apps that intend to support legacy Edge with Shaka Player v3.1+.  In either case, we need to include a polyfill in our karma config for our automated tests, since those are still running on both IE and legacy Edge for the moment.  (We can drop IE from our lab only when we stop supporting the v2.5 and v3.0 release branches.)

Since the commit that introduced this was considered a feature, the addition of this polyfill should also be marked a feature, so we don't try to backport it to v2.5 or v3.0.

This looks like a good option for a polyfill, at only 2.2kB: https://github.com/anonyco/FastestSmallestTextEncoderDecoder

We would welcome opinions about whether the polyfill should be built into Shaka Player or added at the app level.

**Comment by avelad** [comment]
I propose another solution.

In the issue that introduces this change (https://github.com/google/shaka-player/issues/2816) it speaks of tolerating bad text encoding, but because instead of introducing a polyfill, the detection of the functionality and if TextDecoder / TextEncoder is not available, whyt use the old? Given that Edge legacy is to be phased out and Microsoft is promoting it, I don't think it's a bad idea.

**Comment by joeyparrish** [comment]
The old method would effectively revert the fault-tolerance we added to solve #2816, even if only for a few platforms.

The idea behind the polyfill strategy is that when older platforms die out, we can very easily remove the polyfill.  Our main codebase doesn't build up cruft related to the support of those older platforms.

It's worth mentioning, though, that others have questioned the value of our polyfill strategy, and though we aren't changing it right now, we may change it in the future.

**Comment by joeyparrish** [comment]
Fixed in 1405997
