### ISSUE TITLE
shaka.offline.Storage not saving content with WebOs

### ISSUE THREAD

**Issue by mirceaciu** [google/shaka-player#2845]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

There is https://github.com/google/shaka-player/issues/1330 that asks about state of support for WebOs. I already have a working app published with TV and basic functionality is OK. What I can't get to work is offline storage of DASH content.

**What version of Shaka Player are you using?**

3.0.4

**Can you reproduce the issue with our latest release version?**

Yes

**Can you reproduce the issue with the latest code from `master`?**

Have not tried master.

**Are you using the demo app or your own custom app?**

I've build my own custom app around LG's WebOs SDK

**If custom app, can you reproduce the issue using our demo app?**

I can't use any other app as I am testing directly on TV.

**What browser and OS are you using?**

webOs TV 4.8.0-52106 with Chromium 53

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

webOs TV 4.8.0-52106 with Chromium 53

**What did you do?**

I defined the download function as seen in tutorials and examples
```
downloadContent: function(manifestUri, title){
    // Construct a metadata object to be stored along side the content.
    // This can hold any information the app wants to be stored with the
    // content.
    const metadata = {
        'title': title,
        'downloaded': Date()
    };

    return window.storage.store(manifestUri, metadata);
},
```

I pass it the manifest uri and expect the storedContent returned. I used `.then`, I used the `.chain` method recommended in the depreciation warning, I used `await` to get the result of storage but media content is not saved.

```
this.downloadContent(video_manifest_url, 'title')
    .then(function() {
        console.log('do something here);
     })
    .then(function(content) {
        console.log('content', content)
     })
    .catch(function(error) {
        console.log('errpr', error);
    });
```

**What did you expect to happen?**

I expect to reach any of the first functions, and have details about the stored content at

```
    .then(function(content) {
        console.log('content', content)
     })
```

**What actually happened?**

The `.catch` block is run and the `error` parameter is always `undefined`. 

Other notes:

I have no issues playing the url directly with `await shaka_player.load(video_manifest_url)`.

I tried version 2.5.16 and I was able to get 

```
Uncaught (in promise) DOMException: The requested version (4) is less than the existing version (5).
```

This is the only error I could get with any version/code I tried. I've checked the IndexDB version in the TV browser console (I can access that remotely via the SDK) and it's reported as version 5.

I tried the app outside the TV, in my Linux desktop browser, and the same code runs with success and `window.storage.store(manifestUri, metadata)` resolved and I was able to inspect details about the saved content (track, size etc). 

This is what I see in the TV's browser console. Looks like something has started but no data is stored?

![indexdb-webos](https://user-images.githubusercontent.com/9830334/92975443-f4568400-f490-11ea-9d2e-3ab7bbf99cb7.gif)

**Comment by mirceaciu** [comment]
I have loaded the `debug` library, kept the code inspired from the shaka offline tutorial and here is some output

```
shaka.offline.Storage.store.then has been deprecated and will be removed in v4.0 . We are currently at version v3.0 . Additional information: Storage operations now return a shaka.util.AbortableOperation, rather than a promise.  Please update to conform to this new API; you can use the |chain| method instead.
appController.js:1 The video has now been loaded!
shaka-player.compiled.debug.js:1 Starting load of https://exponage-api.com/dash/ad111583943e43b883bbca721d32672d.mp4/manifest.mpd...
shaka-player.compiled.debug.js:1 No Period ID given for Period with start time 0,  Assigning a default
shaka-player.compiled.debug.js:1 codecs avc1-mp4a avg bandwidth 565567
shaka-player.compiled.debug.js:1 Mounting v5 idb storage cell
shaka-player.compiled.debug.js:1 Mounting session ID idb storage cell
shaka-player.compiled.debug.js:1 No Period ID given for Period with start time 0,  Assigning a default
shaka-player.compiled.debug.js:1 Found variant with audio and video content, so filtering out audio-only content.
shaka-player.compiled.debug.js:1 codecs avc1-mp4a avg bandwidth 565567
shaka-player.compiled.debug.js:1 init: completed initial Stream setup
shaka-player.compiled.debug.js:1 No preferred audio language set.  We have chosen an arbitrary language initially
appController.js:1 After await
appController.js:1 _play_video
2shaka-player.compiled.debug.js:1 No pssh box found!
appController.js:1 errpr undefined
shaka-player.compiled.debug.js:1 Calling switch_(), bandwidth=10640 kbps
shaka-player.compiled.debug.js:1 switch_
shaka-player.compiled.debug.js:1 Stall detected at 0 for 1.0329999923706055 seconds.
shaka-player.compiled.debug.js:1 Pausing and unpausing to break stall.
shaka-player.compiled.debug.js:1 Calling switch_(), bandwidth=15576 kbps
shaka-player.compiled.debug.js:1 switch_
shaka-player.compiled.debug.js:1 Calling switch_(), bandwidth=14806 kbps
shaka-player.compiled.debug.js:1 switch_
shaka-player.compiled.debug.js:1 Calling switch_(), bandwidth=15231 kbps
```
At least I can see that v5 is uses. So Indexddb should work, but still,

**Comment by mirceaciu** [comment]
some more details. With `debug` library I see some contents in the IndexedDB

![Screenshot from 2020-09-20 22-55-40](https://user-images.githubusercontent.com/9830334/93720862-a29ab180-fb94-11ea-9db4-2b9dc068e6f5.png)

**Comment by mirceaciu** [comment]
If I do a manual 

```
window.storage.store('https://exponage-api.com/dash/58dc3cf7bcc84460b821debb91bbb05a.mp4/manifest.mpd', {})
```

In the debugger console I get back an AborbableOperation object that contains a rejected Promise.

Calling `.chain(onSucces, onFaillure)` on this objectes resolves with a call to the `onFaillure` function, called with no parameters.

On my server, in nginx I get

```
86.123.213.39 - [20/Sep/2020:20:50:35 +0000] "GET /dash/58dc3cf7bcc84460b821debb91bbb05a.mp4/manifest.mpd HTTP/1.1" 304 "-" "Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.34 Safari/537.36 WebAppManager"
86.123.213.39 - [20/Sep/2020:20:50:35 +0000] "GET /dash/58dc3cf7bcc84460b821debb91bbb05a.mp4/init-a1-x3.mp4 HTTP/1.1" 304 "-" "Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.34 Safari/537.36 WebAppManager"
86.123.213.39 - [20/Sep/2020:20:50:35 +0000] "GET /dash/58dc3cf7bcc84460b821debb91bbb05a.mp4/init-v1-x3.mp4 HTTP/1.1" 304 "-" "Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.34 Safari/537.36 WebAppManager"
```

an nothing more.

I've expanded the `storage` object to look for error, only thing that jumped up is the `-0-` suffix added to the  segments

![Screenshot from 2020-09-20 23-48-25](https://user-images.githubusercontent.com/9830334/93722077-d7ab0200-fb9c-11ea-9c11-76a766a98553.png)

**Comment by joeyparrish** [comment]
If the database is version 5, that means that it was created by a newer version of Shaka Player.

Version 5 was introduced in v3.0, and version 4 was used in v2.5.  So although your issue report says v3.0.4, the symptoms suggest that you're actually using v2.5.

You can check the version of Shaka Player with `shaka.Player.version` in the debug console, and you can upgrade to v3.0 to fix the issue.  To drop the database completely and start over instead of upgrading, you can use `shaka.offline.Storage.deleteAll()`.  See the docs here: https://shaka-player-demo.appspot.com/docs/api/shaka.offline.Storage.html#.deleteAll

If this is only occurring on your test device, because you downgraded Shaka while experimenting, you can delete the database and move on.  If you have users in the field who are in this situation, because you launched v3.0 and then went back to v2.5, you would need to catch the error, (in my opinion) prompt your users for consent, then call `deleteAll()` to wipe out whatever was stored before the version change.

Does this help?

**Comment by mirceaciu** [comment]
It will be at least a week until I get to re-test the issue. 

There seems to be plenty of info from @joeyparrish, IMO you can close the issue.

**Comment by joeyparrish** [comment]
Okay, thanks.  If you need to reopen this issue, just put `@shaka-bot reopen` in a comment.  Thanks!
