### ISSUE TITLE
TrickMode doesn't eliminate representations which use incompatible codecs

### ISSUE THREAD

**Issue by jhnbwrs** [google/shaka-player#2846]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**

v3.1.0-pre (uncompiled)

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `master`?**
yes

**Are you using the demo app or your own custom app?**
demo

**If custom app, can you reproduce the issue using our demo app?**
NA

**What browser and OS are you using?**
Chrome

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
NA

**What are the manifest and license server URIs?**

manifest:
https://content-ausw2-dt-man1.downlynk.com/34c2e8dc7078462a80fcf9c461ba0073.mpd?prettydash=1&ifo=1&vcodec=all
license server:
https://content-ausw2-dt-man1.downlynk.com/wv

**What did you do?**

Enable Trick mode controls and then enagage trick mode:

**What did you expect to happen?**
There are 2 trick mode adaptation sets one HEVC and one AVC -- There are also AVC and HEVC video representations.  Shaka picks the video representation that it can play (avc) but then when you engage trick mode it appears to pick the HEVC trick mode representation.

**What actually happened?**

After engaging trick mode you get:

Shaka Error MEDIA.VIDEO_ERROR (3,,CHUNK_DEMUXER_ERROR_APPEND_FAILED: Append: stream parsing failed. Data size=854 append_window_start=0 append_window_end=434.794)

I can restrict the the codecs included in the manifest using url parameters to my manifest server, and if I simply remove the HEVC representations, trick mode will engage fine:

using:
"https://content-ausw2-dt-man1.downlynk.com/34c2e8dc7078462a80fcf9c461ba0073.mpd?prettydash=1&ifo=1&vcodec=avc"

and the same license server.

**Comment by avelad** [comment]
I created a PR to resolve it: https://github.com/google/shaka-player/pull/2984
