### ISSUE TITLE
Dynamic DASH: sometimes it starts to play at the beginning of the availability window

### ISSUE THREAD

**Issue by JakubRimal** [google/shaka-player#2848]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.4

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Custom

**If custom app, can you reproduce the issue using our demo app?**
N/A

**What browser and OS are you using?**
Tizen 4.0 (but it can happen on every platform/device)

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Full Model=UE32N5302
Firmware=T-KTSNDEUC-1292.1
(but it can happen on every platform/device)

**What are the manifest and license server URIs?**
Some Dynamic DASH

**What did you do?**
Play some Dynamic DASH.

**What did you expect to happen?**
It should start to play according to suggested/default presentation delay.

**What actually happened?**
Sometimes it starts to play at the beginning of the availability window.

You can see the following in the log:
```
16:02:56.047 main.9a313483.js:1 console: (audio:3) checking buffer length
16:02:56.051 main.9a313483.js:1 console: (audio:3) buffer behind okay because nothing buffered: presentationTime=50557.013000011444 bufferBehind=8
16:02:56.063 main.9a313483.js:1 console: (audio:3) appending media segment
16:02:56.095 main.9a313483.js:1 console: Segment downloaded: deltaTimeMs=330 numBytes=65536 lastTimeChosenMs=1593180175435 enabled=false
16:02:56.130 main.9a313483.js:1 console: Playhead before start & start is unbuffered
16:02:56.138 main.9a313483.js:1 console: Jumping forward 50523.81599998474 seconds to catch up with the seek range.
```

**Comment by joeyparrish** [comment]
This looks related to #2748.
