### ISSUE TITLE
Safari reports WebM+VP9 support on macOS Big Sur Safari, but fails to play

### ISSUE THREAD

**Issue by tomaspalmeirim** [google/shaka-player#2852]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v3.0.4 (uncompiled)

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
N/A

**Are you using the demo app or your own custom app?**
Demo app

**If custom app, can you reproduce the issue using our demo app?**
N/A

**What browser and OS are you using?**
**Browser**: Safari Version 14.0 (16610.2.2.4) / Safari Technology Preview Release 113 (Version 14.0.1, WebKit 16610.2.3.1)
**OS**: macOS Big Sur Version 11.0 Beta (20A5364e)

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd

**What did you do?**

Open https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd;panel=HOME;build=uncompiled and try to play demo video.

**What did you expect to happen?**
That the video would play without error.

**What actually happened?**
Failed and tried to fetch webm despite it not being supported, as can be seen with 
`document.getElementsByTagName('video')[0].canPlayType('video/webm')`, which returns `“”`
![image](https://user-images.githubusercontent.com/22453670/93342443-439d0b80-f827-11ea-88a4-db432e2462b7.png)
![image](https://user-images.githubusercontent.com/22453670/93342480-4dbf0a00-f827-11ea-96c6-0c68e997680d.png)

works as intended on:
**Browser**:  Safari Version 13.1.2 (15609.3.5.1.3) / Safari Technology Preview Release 113 (Safari 14.0.1, WebKit 15610.2.3.1)
**OS**: macOS Catalina Version 10.15.6 (19G2021)

**Comment by joeyparrish** [comment]
We don't have Big Sur beta available in our lab.  Can you please visit this page in Safari in both Catalina and Big Sur and copy the output to a comment here?  https://shaka-player-demo.appspot.com/support.html

That will tell us what MediaSource reports as the supported formats and codecs.

**Comment by tomaspalmeirim** [comment]
Sure!

**macOS Big Sur**:

```
Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15
v3.0.4

{
  "manifest": {
    "application/dash+xml": true,
    "video/vnd.mpeg.dash.mpd": true,
    "application/x-mpegurl": true,
    "application/vnd.apple.mpegurl": true,
    "application/x-offline-manifest": true,
    "mpd": true,
    "m3u8": true,
    "application/vnd.ms-sstr+xml": false,
    "ism": false
  },
  "media": {
    "video/mp4; codecs=\"avc1.42E01E\"": true,
    "video/mp4": true,
    "video/mp4; codecs=\"avc3.42E01E\"": true,
    "video/mp4; codecs=\"hev1.1.6.L93.90\"": true,
    "video/mp4; codecs=\"hvc1.1.6.L93.90\"": true,
    "video/mp4; codecs=\"hev1.2.4.L153.B0\"; eotf=\"smpte2084\"": true,
    "video/mp4; codecs=\"hvc1.2.4.L153.B0\"; eotf=\"smpte2084\"": true,
    "video/mp4; codecs=\"vp9\"": false,
    "video/mp4; codecs=\"vp09.00.10.08\"": true,
    "video/mp4; codecs=\"av01.0.01M.08\"": false,
    "audio/mp4; codecs=\"mp4a.40.2\"": true,
    "audio/mp4": true,
    "audio/mp4; codecs=\"ac-3\"": true,
    "audio/mp4; codecs=\"ec-3\"": true,
    "audio/mp4; codecs=\"opus\"": false,
    "audio/mp4; codecs=\"flac\"": true,
    "video/webm; codecs=\"vp8\"": false,
    "video/webm": true,
    "video/webm; codecs=\"vp9\"": false,
    "video/webm; codecs=\"vp09.00.10.08\"": true,
    "audio/webm; codecs=\"vorbis\"": false,
    "audio/webm": false,
    "audio/webm; codecs=\"opus\"": false,
    "video/mp2t; codecs=\"avc1.42E01E\"": false,
    "video/mp2t": false,
    "video/mp2t; codecs=\"avc3.42E01E\"": false,
    "video/mp2t; codecs=\"hvc1.1.6.L93.90\"": false,
    "video/mp2t; codecs=\"mp4a.40.2\"": false,
    "video/mp2t; codecs=\"ac-3\"": false,
    "video/mp2t; codecs=\"ec-3\"": false,
    "text/vtt": true,
    "application/mp4; codecs=\"wvtt\"": true,
    "application/mp4": true,
    "application/ttml+xml": true,
    "application/mp4; codecs=\"stpp\"": true
  },
  "drm": {
    "org.w3.clearkey": null,
    "com.widevine.alpha": null,
    "com.microsoft.playready": null,
    "com.adobe.primetime": null,
    "com.apple.fps.3_0": {
      "persistentState": false
    },
    "com.apple.fps.2_0": {
      "persistentState": false
    },
    "com.apple.fps.1_0": {
      "persistentState": false
    },
    "com.apple.fps": {
      "persistentState": false
    }
  },
  "offline": true
}
```

**macOS Catalina**:

```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.2 Safari/605.1.15
v3.0.4
{
  "manifest": {
    "application/dash+xml": true,
    "video/vnd.mpeg.dash.mpd": true,
    "application/x-mpegurl": true,
    "application/vnd.apple.mpegurl": true,
    "application/x-offline-manifest": true,
    "mpd": true,
    "m3u8": true,
    "application/vnd.ms-sstr+xml": false,
    "ism": false
  },
  "media": {
    "video/mp4; codecs=\"avc1.42E01E\"": true,
    "video/mp4": true,
    "video/mp4; codecs=\"avc3.42E01E\"": true,
    "video/mp4; codecs=\"hev1.1.6.L93.90\"": true,
    "video/mp4; codecs=\"hvc1.1.6.L93.90\"": true,
    "video/mp4; codecs=\"hev1.2.4.L153.B0\"; eotf=\"smpte2084\"": true,
    "video/mp4; codecs=\"hvc1.2.4.L153.B0\"; eotf=\"smpte2084\"": true,
    "video/mp4; codecs=\"vp9\"": false,
    "video/mp4; codecs=\"vp09.00.10.08\"": false,
    "video/mp4; codecs=\"av01.0.01M.08\"": false,
    "audio/mp4; codecs=\"mp4a.40.2\"": true,
    "audio/mp4": true,
    "audio/mp4; codecs=\"ac-3\"": true,
    "audio/mp4; codecs=\"ec-3\"": false,
    "audio/mp4; codecs=\"opus\"": false,
    "audio/mp4; codecs=\"flac\"": true,
    "video/webm; codecs=\"vp8\"": false,
    "video/webm": false,
    "video/webm; codecs=\"vp9\"": false,
    "video/webm; codecs=\"vp09.00.10.08\"": false,
    "audio/webm; codecs=\"vorbis\"": false,
    "audio/webm": false,
    "audio/webm; codecs=\"opus\"": false,
    "video/mp2t; codecs=\"avc1.42E01E\"": false,
    "video/mp2t": false,
    "video/mp2t; codecs=\"avc3.42E01E\"": false,
    "video/mp2t; codecs=\"hvc1.1.6.L93.90\"": false,
    "video/mp2t; codecs=\"mp4a.40.2\"": false,
    "video/mp2t; codecs=\"ac-3\"": false,
    "video/mp2t; codecs=\"ec-3\"": false,
    "text/vtt": true,
    "application/mp4; codecs=\"wvtt\"": true,
    "application/mp4": true,
    "application/ttml+xml": true,
    "application/mp4; codecs=\"stpp\"": true
  },
  "drm": {
    "org.w3.clearkey": null,
    "com.widevine.alpha": null,
    "com.microsoft.playready": null,
    "com.adobe.primetime": null,
    "com.apple.fps.3_0": {
      "persistentState": false
    },
    "com.apple.fps.2_0": {
      "persistentState": false
    },
    "com.apple.fps.1_0": {
      "persistentState": false
    },
    "com.apple.fps": {
      "persistentState": false
    }
  },
  "offline": true
}
```

**Comment by joeyparrish** [comment]
Interesting.  Safari tells us (via `MediaSource.isTypeSupported`) that it can play WebM + VP9: `"video/webm; codecs=\"vp09.00.10.08\"": true`, so it's not wrong of us to try.  If Safari can't actually play it, that may be a Safari bug.  Since this version of the OS is in beta, this may just be a bug that they haven't noticed or fixed yet.

Can you file an issue with Apple either via [WebKit](https://webkit.org/reporting-bugs/) or [Safari](https://www.apple.com/feedback/safari.html) or both?

Thanks!

**Comment by tomaspalmeirim** [comment]
Submited to both - [Webkit Bug Report](https://bugs.webkit.org/show_bug.cgi?id=216652)

**Comment by joeyparrish** [comment]
Thanks for the link!  I'll subscribe to that bug and keep an eye on Apple's feedback.

**Comment by joeyparrish** [comment]
According to Jer at Apple, the failure is a decoder error.

If Apple thinks this is a bug in the decoder, we can close this issue.  If they think the content is badly-encoded, since that's our content, we may try re-encoding it as a fix.

**Comment by joeyparrish** [comment]
Jer says that there is a bug in Apple's WebM parser, so I think we can safely close this issue and follow along on the WebKit bug tracker.  Thanks!
