### ISSUE TITLE
License Server Error Response from NetworkEngine()

### ISSUE THREAD

**Issue by mseo12** [google/shaka-player#2864]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.16

**Please ask your question**

I am using response filter to unwrap the response from license server.
Looks good and working fine.
But if license is expired, license server responses with the message as below..
Is there any way to get the response from NetworkingEngine,
or does event error listener should return this? as of now, it is returning undefined...
Thank you~~

Inspector log:
POST https://<license server url>/1.0/<account Id>/widevine/get_license 400 (Bad Request)
index.js:1 Shaka ERROR XXXX details: undefined undefined

Response in Network:
{"error":"Rights creation failed due to error detected code 1234"}

```js
     /**
     *  Unwap and extract license information for CDM.
     */
    player
      .getNetworkingEngine()
      .registerResponseFilter(function (type, response) {
        if (type == shaka.net.NetworkingEngine.RequestType.LICENSE) {
        ...
       }

      function onError(err) {
        console.error(`Shaka ERROR XXXX details: ${err.details} ${err.code}` );
      }
      player.addEventListener("error", onError);
```

**Comment by theodab** [comment]
Well, the error's details and code both being undefined suggests that this is not a Shaka error. That's probably a bug on our part, since even if you have a bug inside your response filter we should be wrapping it. It's hard to know what the exact issue here is without being able to reproduce your issue, though.
If you put a breakpoint into your error handler, you could see what kind of object it is. If this isn't one of our errors, it's likely to be an [`Error` object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error) instead, which means you could check `err.stack` to see the stack trace for the error, which could be a big clue as to what is going on.

**Comment by mseo12** [comment]
You are right it is not a Shaka error but license server responses with 400 in network layer.
So I was wondering how can I get this message "{"error":"Rights creation failed due to error detected code 1234"}" from NetworkingEngine or error callback...

Tried the code below to know what forwarded from it, but looks getNetworkingEngine.registerResponseFilter() would not be called at that time when get network error.

`    player
      .getNetworkingEngine()
      .registerResponseFilter(function (type, response) {
        if (type == shaka.net.NetworkingEngine.RequestType.LICENSE) {
          console.log("response",response);
          ...
         }
`

What came to know when set a break point is that Shaka knows that error somewhere where Inspector shows like this..

![Screen Shot 2020-09-22 at 5 26 14 PM](https://user-images.githubusercontent.com/33038233/93947680-93814400-fcf9-11ea-8a25-8894e5d57938.png)

LICENSE_REQUEST_FAILED | 6007 | number | The license request failed. This could be a timeout, a network failure, or a rejection by the server.error.data[0] is a shaka.util.Error from the networking engine.

Anything what we can try more?
Thank you

**Comment by joeyparrish** [comment]
What you need to look at is `.data[0]` from the error object.  Try this:

```js
      function onError(err) {
        console.error(`Shaka ERROR XXXX details: ${err.details} ${err.code}`, err.data[0]);
      }
      player.addEventListener("error", onError);
```

When err.data[0] appears in the log, expand it and inspect to find the information you need.

In this case, the 400 HTTP error should have generated a Shaka error with code set to `BAD_HTTP_STATUS`.  This should be what you find in err.data[0].  From [the docs for that code](https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html#value:1001):

> An HTTP network request returned an HTTP status that indicated a failure.
> error.data[0] is the URI.
> error.data[1] is the status code.
> error.data[2] is the response text, or null if the response could not be interpretted as text.
> error.data[3] is the map of response headers.
> error.data[4] is the NetworkingEngine.RequestType of the request, if one was provided.

So if err.data[0] is the BAD_HTTP_STATUS error as I suspect, your error message from the server would be in `err.data[0].data[2]`.  But your error handler should check the code in `err.code` before trying to grab `err.data[0].data[2]`.

Does this help?
