### ISSUE TITLE
Switching audio tracks on dash playback fails in FireFox.

### ISSUE THREAD

**Issue by jhnbwrs** [google/shaka-player#2866]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
I seen some issues related to seeking and firefox, but I don't think they are the same.  It is hard to say for sure though

**What version of Shaka Player are you using?**
2.5.16

**Can you reproduce the issue with our latest release version?**
Actually I cannot reproduce in the 3.x branch, but it would be super awesome if this worked in the 2.5.x branch

**Can you reproduce the issue with the latest code from `master`?**
No

**Are you using the demo app or your own custom app?**
Demo

**If custom app, can you reproduce the issue using our demo app?**
NA

**What browser and OS are you using?**
Firefox 80.0.1 (64-bit) - Macos - Importantly this worked fine in chrome

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
NA

**What are the manifest and license server URIs?**
I will send this via email.

**What did you do?**

Start playback and wait for 10 seconds then switch audio to spanish

**What did you expect to happen?**
I expected to hear some spanish audio

**What actually happened?**

Playback froze and never recovered.

**Comment by joeyparrish** [comment]
I'm working on a test failure that may be related.  I haven't found the root cause yet, nor a workaround that we would be willing to commit, but I have found a hack that somehow changes a race condition related to unbuffered seeking (which clears a stream, as does changing audio languages).

@jhnbwrs, would you be willing to try out this patch and tell me if the problem goes away?  If so, this bug and the test failure probably share a root cause.

```diff
diff --git a/lib/media/streaming_engine.js b/lib/media/streaming_engine.js
index 34100324..88c7bfac 100644
--- a/lib/media/streaming_engine.js
+++ b/lib/media/streaming_engine.js
@@ -1769,6 +1779,7 @@ shaka.media.StreamingEngine = class {
             mediaState.type);
       }
     }
+    await new Promise((r) => setTimeout(r, 100));
     this.destroyer_.ensureNotDestroyed();
 
     shaka.log.debug(logPrefix, 'cleared buffer');
```

**Comment by joeyparrish** [comment]
Here's another patch I'd like you to try when you have time.  It fixes the (possibly related) test failure I'm working on.

```diff
diff --git a/lib/media/streaming_engine.js b/lib/media/streaming_engine.js
index 34100324..1c0f05f7 100644
--- a/lib/media/streaming_engine.js
+++ b/lib/media/streaming_engine.js
@@ -1752,6 +1752,8 @@ shaka.media.StreamingEngine = class {
     mediaState.waitingToFlushBuffer = false;
     mediaState.clearBufferSafeMargin = 0;
     mediaState.clearingBuffer = true;
+    mediaState.lastStream = null;
+    mediaState.lastSegmentReference = null;
 
     shaka.log.debug(logPrefix, 'clearing buffer');
 
@@ -1772,8 +1774,6 @@ shaka.media.StreamingEngine = class {
     this.destroyer_.ensureNotDestroyed();
 
     shaka.log.debug(logPrefix, 'cleared buffer');
-    mediaState.lastStream = null;
-    mediaState.lastSegmentReference = null;
     mediaState.clearingBuffer = false;
     mediaState.endOfStream = false;
     this.scheduleUpdate_(mediaState, 0);
```

**Comment by jhnbwrs** [comment]
So It looks like your diffs are for master.  This bug actually doesn't show up in master, just 2.5.x -- I could easily apply the second patch in 2.5.x, it didn't have any effect.  The first one, it wasn't clear to me if it would still be something to try in 2.5.x.  -- I tried to jam it in, but Build conformance told me not to use it, and it looked kind of like it wouldn't be something to try in 2.5.x anyway, so I didn't fight with it.

So here is what it looks like with debug level logging and the second patch applied
```
switch: Stream (audio:1) already active streaming_engine.js:790:15
(video:9) looking up segment: presentationTime=8.192 currentPeriod.startTime=0 streaming_engine.js:1615:13
(video:9) looking up segment: presentationTime=8.192 currentPeriod.startTime=0 streaming_engine.js:1615:13
switch: Stream (video:9) already active streaming_engine.js:790:15
switch: switching to Stream (audio:3) streaming_engine.js:807:13
(audio:3) clearing buffer streaming_engine.js:2536:13
(audio:3) awaiting buffer clear streaming_engine.js:2553:13
(audio:3) done wating streaming_engine.js:2555:13
(audio:3) cleared buffer streaming_engine.js:2558:13
(audio:3) looking up segment: presentationTime=6.3748949999999995 currentPeriod.startTime=0 streaming_engine.js:1615:13
(audio:3) clear: currently updating streaming_engine.js:998:15
(audio:3) skipping update and clearing the buffer streaming_engine.js:1300:15
(audio:3) clearing buffer streaming_engine.js:2536:13
(audio:3) cleared buffer streaming_engine.js:2558:13
(audio:3) looking up segment: presentationTime=6.3748949999999995 currentPeriod.startTime=0 streaming_engine.js:1615:13
```
It never logs anything after that (at debug level) unless I switch back to the original audio track.  If I do that it keeps humming right along.

**Comment by joeyparrish** [comment]
Ah, okay.  So it's only in the v2.5 branch.  We'll assume, then, that this is a separate issue and cycle back around to it.

We are still making bug fixes to the v2.5 branch for now, so I expect this is something we can still address.

**Comment by joeyparrish** [comment]
Also, this sounds like it could be related to #2427 and https://bugzilla.mozilla.org/show_bug.cgi?id=1618529 .  Does this quote from the FF bug tracker sound like it could be a match to your issue?

> ## Encrypted subsamples with clear ranges near UINT16_MAX can overflow clear ranges during AnnexB conversion
>
> ISO/IEC 23001-7 specifies that the # clear bytes for subsamples are stored in a uint16 and we read that into a uint16. However, we end up expanding that range while performing AnnexB conversion -- which typically takes place on the first sample after we (re) init. If the number of clear bytes is near UINT16_MAX then this expansion can lead to an overflow, which is what is happening here.
> 
> The Widevine interface accepts a uint32_t for the # clear bytes values, possible to mitigate this issue. We should be able to mitigate this by storing the value as a uint32_t internally.

**Comment by JaenalLeeGenMao** [comment]
@joeyparrish Can you help me out on https://github.com/google/shaka-player/issues/2899 I had quite similar issue with my widevine mpd streamUrl but I can play the audio fine on 3.0.x but not on 2.5.x safari works fine (chrome and firefox doesn't) the audio doesn't play

**Comment by TheModMaker** [comment]
@jhnbwrs does that Firefox bug seem related to your issue?  Can you still reproduce with v2.5.17?  Could you provide some logs with V1 level (probably by attaching a file or using pastebin)?

**Comment by jhnbwrs** [comment]
Wow, good call.  I wouldn't have suspect that being the issue since our sub samples are all 100% encrypted.....  Maybe I misunderstand what the bug is, or maybe there is just another bug fixed in 83, but I can say I just tried to playback with 82.0.2 and could NOT switch audio languages (bug exactly the same) -- I updated to the 83 beta (specifically: 83.0b5 (64-bit)) and the issue is gone.
