### ISSUE TITLE
Video-only HLS without codec info

### ISSUE THREAD

**Issue by unnatimane** [google/shaka-player#2868]
manifest URL- https://meditorch.pc.cdn.bitgravity.com/vod/_definst_/smil:1_65557816.smil/playlist.m3u8

Above URL is working on desktop. But not working in shaka player on mobile.

console showing below alerts:

Segment downloaded:
Suggesting Streams...
Still within switch interval...

**Comment by theodab** [comment]
When you say that this isn't working on mobile, what platform do you mean? I just tested your content on iOS, and it looked to be playing there. I mean, probably, I was having a hard time looking at your test content. Are you trying this on an Android browser? What version of Shaka Player are you using?

Incidentally, while testing your content, I found it isn't playing on desktop Chrome. That's likely unrelated to whatever problem you are seeing, though; it looks like we are accidentally assigning the content an audio codec despite it being video-only, and Chrome's implementation of the MediaSource API doesn't tolerate that.

**Comment by joeyparrish** [comment]
Doesn't play for me on Chrome on Android.  Complains about demuxer failure related to AAC codec.

**Comment by joeyparrish** [comment]
@unnatimane, is that the same error you get on mobile?  Or is it something else?  It's unclear from your original post.

**Comment by joeyparrish** [comment]
We noticed that the master playlist has no codec information.  Shaka Player currently assumes this is video+audio multiplexed, but there's no way for us to make a better guess than that.

We could make the `manifest.disableAudio` config work in this situation, to inform our guess based on something the app knows in advance.

**Comment by unnatimane** [comment]
@joeyparrish As a workaround, should we add a dummy audio stream to all our videos that do not have audio? Will that solve the problem for now?

**Comment by theodab** [comment]
You could do that, I suppose, but the better approach would be to just specify what the codecs are in your `EXT-X-STREAM-INF` tags.

**Comment by joeyparrish** [comment]
Yes, I agree.  Adding codec info would be a much better solution than a dummy audio stream.

@theodab has a change in review now that will allow this content to play with the `manifest.disableAudio` config set to `true`.

**Comment by theodab** [comment]
Okay, we've got that new change into master. With it, you could set `manifest.disableAudio` as Joey mentioned, to make your stream play as a video-only stream, if you so wish.
For now I'm closing this issue, but if this doesn't solve your problem, you can file a new issue or re-open this one. I'm still not entirely sure if this Chrome issue is what you were seeing or not, since you didn't mention seeing any errors.

**Comment by unnatimane** [comment]
downloaded latest source code v-3.0.5 from https://github.com/google/shaka-player/releases.
we can see this.config_.disableAudio||b.push("mp4a.40.2"); in the file- shaka-player.compiled.debug.js

added below line to our code-
player.configure('manifest.disableAudio', true);

Still unable to play the video. However, if we do a disable Audio on the Shaka player demo page, it works. I am confused what is happening.

**we are getting below errors:**
![image](https://user-images.githubusercontent.com/21259335/96104274-422e3400-0ef6-11eb-9d1b-a797f9996d87.png)

**playing video on shaka player demo page**
![image](https://user-images.githubusercontent.com/21259335/96104706-caacd480-0ef6-11eb-9d4d-8c7d0ac72675.png)
