### ISSUE TITLE
Changing controls by ui.configure() during Ad break the ad

### ISSUE THREAD

**Issue by krychu90** [google/shaka-player#2869]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.4

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
My own

**If custom app, can you reproduce the issue using our demo app?**
https://jsfiddle.net/w5pxue4h/1/

**What browser and OS are you using?**
Windows 10, Firefox/Chrome

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
 .

**What are the manifest and license server URIs?**
See demo

**What did you do?**
Update ui to hide my custom controls when ad is playing.

**What did you expect to happen?**
Controls are changed, ad still playing.

**What actually happened?**
Ad is closed

**Comment by theodab** [comment]
Yeah, this looks like a bug. Thanks for the report!
