### ISSUE TITLE
CDM detection and playback

### ISSUE THREAD

**Issue by sarge** [google/shaka-player#287]
Hi all,

So recently we noticed on Chrome Win 10 64bit that the CDM was not being downloaded.

This was solved on the device by restarting Chrome and heading to the chrome://components and manually downloading the CDM.

My understanding is that the CDM should be downloaded on demand. Then we need to check back every so often to see if CDM has downloaded and playback is possible. Is this correct, I have just headed to https://shaka-player-demo.appspot.com/ and I have not managed to get this to work.

Chrome bug or am I missing something? 

Update: It seems waiting a while 10 minutes seems to help. 

This is a very loose contract, any recommendations about automating this process?

Related: Given that we have some content that is Widevine encoded and some that is Playready encoded, am I correct that detecting the available mediakeys is the wrong way to detect the browsers EME capability?

Thanks in advance

**Comment by imalex** [comment]
RE: Missing WV CDM

On a fresh install of Chrome desktop browser, the Widevine CDM download
will kick off 6 mins later.  This shouldn't be a problem for existing
Chrome installs, only for a new Chrome installation.  We are looking at
improving this situation and have the CDM immediately available in a near
future version of Chrome.

**Comment by sarge** [comment]
Thanks Alex.

Ok so it is reasonable that requestMediaKeySystemAccess should tell us if the key system is supported. We don't need to attempt to play some content, to trigger the CDM to download at which point requestMediaKeySystemAccess will advertise that the CDM is available.

**Comment by joeyparrish** [comment]
It seems that the CDM download in Chrome is started independent of anything that happens in JavaScript.  Also, the Player can only ask whether or not the CDM is available now, not whether it will be downloaded later.

So until the CDM is downloaded, trying to play protected content on Chrome will fail due to Widevine not yet being available.

Sorry for the inconvenience.

**Comment by sarge** [comment]
@joeyparrish thanks for the clarification:)
