### ISSUE TITLE
Advices on debuging on Tizen 2.4

### ISSUE THREAD

**Issue by matEhickey** [google/shaka-player#2871]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes  

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes  
Might be a duplicate of https://github.com/google/shaka-player/issues/2612 but this one is really old  

**What version of Shaka Player are you using?**
Any version which might work, I'd prefer using the recents one  
(I tried on 2.4.7, 2.5.16, 3.0.1, 3.0.4, and many more by using CDN to tests them more quickly..)  

**Please ask your question**
Can I get help on running the ShakaPlayer for Tizen 2.4 (Samsung TV  2015/2016) ?  
I do understand that it is currently not really supported, but I got one build to work, but I can't reproduce anymore (I think it was on the version 3.0.1, but not even sure anymore, as I can't access a debug mode on already installed apps on these tv models to verify it).  

I spend some time investigating, adding logs and testing differents settings, but I still can't get to have a stream playing.  

The main issue seem to be that the MediaCapabilities API is not present on the web engine (webkit) that the tv use. I can't find any already made polyfills, and mocking it with empty objects don't seem enough (of course it's not, but I had to try.. )   

I have the tv to make every tests needed, I'm just searching for advices on how to progress on my way to get shaka working on these devices.  Any help/guess would be highly appreciated :)

**Comment by joeyparrish** [comment]
> The main issue seem to be that the MediaCapabilities API is not present on the web engine (webkit) that the tv use.

That can't be the problem, since we aren't using MediaCapabilities in Shaka Player yet.  Does it have MediaSource?

Can you visit this page on the device and send a screenshot of the output?  https://shaka-player-demo.appspot.com/support.html

**Comment by krychu90** [comment]
Hi,
I have similar problem. On my TV (Samsung UE40K5572SU, Tizen 2.x) shaka does not start:
![obraz](https://user-images.githubusercontent.com/11661487/94196162-44334300-feb4-11ea-964f-70c948da1084.png)

**Comment by joeyparrish** [comment]
@krychu90, @matEhickey, can you visit this page on the device and send a screenshot of the output?

**[https://shaka-player-demo.appspot.com/support.html](https://shaka-player-demo.appspot.com/support.html)**

That will show us details on what the device actually supports, which will help us understand why Shaka Player doesn't work on the platform.  Thanks!

**Comment by matEhickey** [comment]
Thank you for the quick reply. 

Of course I will, tommorow morning, I don't have this tv at home (french hour here) !

**Comment by joeyparrish** [comment]
No rush!  Thanks for your help.

**Comment by krychu90** [comment]
My TV:
![obraz](https://user-images.githubusercontent.com/11661487/94202781-9a0ce880-febe-11ea-98d1-be97860be774.png)
![obraz](https://user-images.githubusercontent.com/11661487/94202789-9e390600-febe-11ea-82ed-7fbe420fb0b8.png)

**Comment by joeyparrish** [comment]
@krychu90, that's very helpful.  Can you please try the compiled version of the demo page and see if that is working?

https://shaka-player-demo.appspot.com/demo/#build=compiled

**Comment by krychu90** [comment]
I tried but it shows the same message.

**Comment by joeyparrish** [comment]
Then I think we will need to get console logs from the device to know what is wrong.  I don't know how to advise you on that.

**Comment by matEhickey** [comment]
Hello !
I finaly achieve to make shaka working again (at every build, on the 3.0.4, building it myself).  
I don't really get why it work now, I suspect a TV update as I noticed some change in apps behavior.  


For information, MediaSource seem to exist on these models, as I can produce the same logs on chrome and on the TV:  
~~~js
console.info(MediaSource);
// produce:
// isTypeSupported: function isTypeSupported() { [native code] };

const mediaSource = new MediaSource();
console.info(mediaSource);
// produce:
// sourceBuffers: [object SourceBufferList]; activeSourceBuffers: [object SourceBufferList]; duration: NaN; onsourceopen: null; onsourceended: null; onsourceclose: null; readyState: closed; addSourceBuffer: function addSourceBuffer() { [native code] }; removeSourceBuffer: function removeSourceBuffer() { [native code] }; endOfStream: function endOfStream() { [native code] }; setLiveSeekableRange: function setLiveSeekableRange() { [native code] }; clearLiveSeekableRange: function clearLiveSeekableRange() { [native code] }; addEventListener: function addEventListener() { [native code] }; removeEventListener: function removeEventListener() { [native code] }; dispatchEvent: function dispatchEvent() { [native code] };
~~~


also, here are the difference between the support page execution in chrome and in the tv:
("<" lines are chrome, ">" are tizen2.4)

20,24c20,24
<     "video/mp4; codecs=\"hev1.1.6.L93.90\"": false,
<     "video/mp4; codecs=\"hvc1.1.6.L93.90\"": false,
<     "video/mp4; codecs=\"hev1.2.4.L153.B0\"; eotf=\"smpte2084\"": false,
<     "video/mp4; codecs=\"hvc1.2.4.L153.B0\"; eotf=\"smpte2084\"": false,
<     "video/mp4; codecs=\"vp9\"": false,
---
>     "video/mp4; codecs=\"hev1.1.6.L93.90\"": true,
>     "video/mp4; codecs=\"hvc1.1.6.L93.90\"": true,
>     "video/mp4; codecs=\"hev1.2.4.L153.B0\"; eotf=\"smpte2084\"": true,
>     "video/mp4; codecs=\"hvc1.2.4.L153.B0\"; eotf=\"smpte2084\"": true,
>     "video/mp4; codecs=\"vp9\"": true,

29,31c29,31
<     "audio/mp4; codecs=\"ac-3\"": false,
<     "audio/mp4; codecs=\"ec-3\"": false,
<     "audio/mp4; codecs=\"opus\"": true,
---
>     "audio/mp4; codecs=\"ac-3\"": true,
>     "audio/mp4; codecs=\"ec-3\"": true,
>     "audio/mp4; codecs=\"opus\"": false,

39c39
<     "audio/webm; codecs=\"opus\"": true,
---
>     "audio/webm; codecs=\"opus\"": false,



Thank you for your help, I'll add more detail if I can find why it wasn't working !  

@krychu90  Is the problem over from your side too ?

**Comment by krychu90** [comment]
On my tv there is no changes, no updates. What browser version do you have?

**Comment by matEhickey** [comment]
Version 1.1.2.0711052, 
btw, I still have streams not working on this platform but are working on more modern models (for example (dash no-drm): https://ncdn-ba-kairos.pfd.sfr.net/dashcenc/onlytxt4/manifest.mpd )  
I'll invest more, but it seem that on this device, the segments don't have their path redirected and keep trying to download from the manifest server.  

Maybe you can test with the angel-one (star trek example (dash no-drm): https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd

**Comment by evgeniy-legkun** [comment]
I have the same problem with my Tizen 2.4. MediaSource is available but MediaCapabilities API is not present.
Shaka throws the error "message": "Shaka Error MANIFEST.DASH_INVALID_XML (__manifest__url__))". Maybe somebody can advise me on how to debug what is wrong with my manifest? On all other devices, the same manifests work fine.

**Comment by joeyparrish** [comment]
A DASH manifest's XML parsing in Shaka Player is based on the DOMParser API.  If that is broken or more picky on a particular platform, rejecting XML that is accepted on another device/browser, then you could try running your manifest through a very strict XML linter to see what complaints pop up.

Another thing you could try is replacing the native DOMParser with a pure JS version at the level of your application.  For example, https://www.npmjs.com/package/xmldom .  That would alleviate any bugs or restrictions from the platform, at the cost of more JavaScript and slower parsing.
