### ISSUE TITLE
CORS errors

### ISSUE THREAD

**Issue by Forium777** [google/shaka-player#2875]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
Lastest

**Please ask your question**
Hello,
I'm trying to configure Shaka player with a fairplay encryption but when I try to do a request to the license server I get :    
`"Origin http://192.168.0.36:8080 is not allowed by Access-Control-Allow-Origin."`           
I know what this error mean : it's about CORS, but when I'm doing the exact same request on Postman (or Insomnia) the request works, after some researches I found that Postman (and Insomnia) doesn't act like a browser so doesn't care about CORS. So how could I make my javascript act like Postman ? Does create a proxy which does the request would be a working workaround ? If yes, can you provide a example ?      

![image](https://user-images.githubusercontent.com/69720050/94318965-f38e1980-ff89-11ea-922d-4aa8fdbf5584.png)       

Here is my javascript which is almost the doc example :
```js
let contentId;

export async function configureFairPlayDrm() {
    const req = await fetch('cert/test.cer');
    const cert = await req.arrayBuffer();

    player.configure('drm.advanced.com\\.apple\\.fps\\.1_0.serverCertificate',
        new Uint8Array(cert));

    // Content ID
    configureFairPlayContentID();

    // License Wrapping
    configureFairPlayLicenseWrapping();
}

function configureFairPlayContentID() {
    player.configure('drm.initDataTransform', (initData, initDataType) => {
        if (initDataType != 'skd') {
            return initData;
        }

        contentId = shaka.util.FairPlayUtils.defaultGetContentId(initData);
        const cert = player.drmInfo().serverCertificate;
    
        return shaka.util.FairPlayUtils.initDataTransform(initData, contentId, cert);
    });
}

function configureFairPlayLicenseWrapping() {
    player.getNetworkingEngine().registerRequestFilter((type, request) => {
        if (type != shaka.net.NetworkingEngine.RequestType.LICENSE) {
            return;
        }

        const json = // HERE IS MY JSON FOR THE REQUEST
        const wrappedJson = JSON.stringify(json);

        request.headers['Content-Type'] = 'application/json';
        request.body = shaka.util.StringUtils.toUTF8(wrappedJson);
    });

    player.getNetworkingEngine().registerResponseFilter((type, response) => {
        if (type != shaka.net.NetworkingEngine.RequestType.LICENSE) {
            return;
        }

        let responseText = shaka.util.StringUtils.fromUTF8(response.data);
        // Trim whitespace.
        responseText = responseText.trim();

        // Look for <ckc> wrapper and remove it.
        if (responseText.substr(0, 5) === '<ckc>' &&
            responseText.substr(-6) === '</ckc>') {
            responseText = responseText.slice(5, -6);
        }

        // Decode the base64-encoded data into the format the browser expects.
        response.data = shaka.util.Uint8ArrayUtils.fromBase64(responseText).buffer;
    });
}
```

**Comment by joeyparrish** [comment]
> So how could I make my javascript act like Postman ?

You can't, in general.  CORS rules are built into the browser to prevent cross-site scripting attacks.  You can disable them in some browsers via a command line flag or developer setting, you can't disable CORS for everyone else who accesses your site.

> Does create a proxy which does the request would be a working workaround ?

Yes, there are CORS proxies, but the best solution is to add the necessary CORS response headers on the server to allow access to your content from other origins.  You can use "*" to allow access from every origin, or you can make a list of the specific origins you want to allow.

Since `192.168.0.36` in your example is a local IP, I'm assuming this is a server you have some control over.  You can find helpful configuration docs for CORS on a wide variety of web servers here: https://enable-cors.org/server.html

Does this help?
