### ISSUE TITLE
How to use all 6 channels when casting HLS or Dash with aac and dolby?

### ISSUE THREAD

**Issue by raestrada95** [google/shaka-player#2876]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.4.7

**Please ask your question**
Hi @joeyparrish, i have a question regarding to this demo : [https://v2-4-7-dot-shaka-player-demo.appspot.com/demo/#build=uncompiled](url), when i set Configuration-> Preferred audio channel count: 6
and i send it to chromecast dolby 5.1 sounds on my system if i leave it in 2 on chromecast only sound the 2.0 AAC. How do you tell the receiver to use 6 channels instead of two?
I use this library to cast my m3u8 and dash files but I don't understand how to make it work in 5.1 instead of 2.0 in the chromecast
https://github.com/googlecast/CastVideos-android  the same with exoplayer

**Comment by TheModMaker** [comment]
Can you post the manifest URL that causes problems?  You can send it privately to shaka-player-issues@google.com if you want.  Do you set the configuration before loading the content?  Does the 5.1 stream use a different codec?  It's possible the 5.1 stream isn't supported by the device so we filter it out.  If you play it locally, does it play the 5.1 stream?  You can check in the console with `shakaDemoMain.player_.getVariantTracks().filter((c)=>c.active)[0].channelsCount`.

**Comment by raestrada95** [comment]
Hi @TheModMaker, yes the 5.1 audio is in a different codec  is aac for 2.0 and ec3 for 5.1, As I mentioned before in the demo that you have online, the 5.1 works perfect on dolby digital for it to work I configure in the options of that web page 6 channel as preferred, but how I tell the receiver to use 6 channels instead of 2? 

I for example use this library, how could I indicate that it uses 6 channels instead of 2 to the receiver?
https://github.com/googlecast/CastVideos-android

here I leave an example of my m3u8 list, and I will also prepare a stream for you to test and I will send it the email that I indicated. Thanks for the help.

`#EXTM3U
## Generated with https://github.com/google/shaka-packager version v2.3.0-5bf8ad5ed5-release

#EXT-X-MEDIA:TYPE=AUDIO,URI="audio-spa-2/main.m3u8",GROUP-ID="audio_aac",LANGUAGE="es",NAME="SPANISH",DEFAULT=YES,AUTOSELECT=YES,CHANNELS="2"
#EXT-X-MEDIA:TYPE=AUDIO,URI="a-spa-ac3/main.m3u8",GROUP-ID="audio_ac3",LANGUAGE="es",NAME="SPANISH-DD",DEFAULT=YES,AUTOSELECT=YES,CHANNELS="6"

#EXT-X-STREAM-INF:BANDWIDTH=3272602,AVERAGE-BANDWIDTH=3141725,CODECS="avc1.64002a,mp4a.40.2",RESOLUTION=1280x720,AUDIO="audio_aac"
h264_720p/main.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1228362,AVERAGE-BANDWIDTH=1178512,CODECS="avc1.64002a,mp4a.40.2",RESOLUTION=842x474,AUDIO="audio_aac"
h264_480p/main.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=819464,AVERAGE-BANDWIDTH=784426,CODECS="avc1.64002a,mp4a.40.2",RESOLUTION=640x360,AUDIO="audio_aac"
h264_360p/main.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=5910841,AVERAGE-BANDWIDTH=5630814,CODECS="avc1.64002a,mp4a.40.2",RESOLUTION=1920x1080,AUDIO="audio_aac"
h264_1080p/main.m3u8

#EXT-X-STREAM-INF:BANDWIDTH=3520601,AVERAGE-BANDWIDTH=3395185,CODECS="avc1.64002a,ac-3",RESOLUTION=1280x720,AUDIO="audio_ac3"
h264_720p/main.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1476361,AVERAGE-BANDWIDTH=1431972,CODECS="avc1.64002a,ac-3",RESOLUTION=842x474,AUDIO="audio_ac3"
h264_480p/main.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1067463,AVERAGE-BANDWIDTH=1037886,CODECS="avc1.64002a,ac-3",RESOLUTION=640x360,AUDIO="audio_ac3"
h264_360p/main.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=6158840,AVERAGE-BANDWIDTH=5884274,CODECS="avc1.64002a,ac-3",RESOLUTION=1920x1080,AUDIO="audio_ac3"
h264_1080p/main.m3u8

#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=365952,AVERAGE-BANDWIDTH=92682,CODECS="avc1.64002a",RESOLUTION=1280x720,URI="h264_720p/iframe.m3u8"
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=134755,AVERAGE-BANDWIDTH=43403,CODECS="avc1.64002a",RESOLUTION=842x474,URI="h264_480p/iframe.m3u8"
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=81764,AVERAGE-BANDWIDTH=30423,CODECS="avc1.64002a",RESOLUTION=640x360,URI="h264_360p/iframe.m3u8"
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=644369,AVERAGE-BANDWIDTH=151358,CODECS="avc1.64002a",RESOLUTION=1920x1080,URI="h264_1080p/iframe.m3u8"`

**Comment by raestrada95** [comment]
It is possible to see the configuration of the receiver used by this site ?
https://v2-4-7-dot-shaka-player-demo.appspot.com/demo/#asset=https://storage.googleapis.com/shaka-demo-assets/tos-surround/dash.mpd;lang=en;build=uncompiled;build=uncompiled

**Comment by joeyparrish** [comment]
v2.4 is no longer supported.  Please try using a supported version of Shaka Player (v2.5.20 or v3.0.8) and see if you are still having this issue.  The channel-related configs should apply to the receiver.  If they do not work in these versions, we will see if we can fix it.  Thanks!
