### ISSUE TITLE
getVariantTracks returns less tracks than it should from 3.0.3 version

### ISSUE THREAD

**Issue by sbrez** [google/shaka-player#2884]
**What version of Shaka Player are you using?**
Shaka version 3.0.3+

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Not tested

**Are you using the demo app or your own custom app?**
My own custom app and the demo app too

**What browser and OS are you using?**
Tested on Mac/Win Chrome/Firefox

**What are the manifest and license server URIs?**
I send it on your email address

**What did you do?**
Call the getVariantsTrack function and check the array length

**What did you expect to happen?**
50 tracks intead of 20

**What actually happened?**
Only 20 tracks in the array (probably something related to audio language / audio label)

**Comment by joeyparrish** [comment]
@sbrez, is this still the case in our latest release v3.0.6?

**Comment by sbrez** [comment]
> @sbrez, is this still the case in our latest release v3.0.6?

@joeyparrish, yes is still there. Tracks are probably grouped by language instead of by label. 
Just to be clear, I forgot to specify that we are talking about Dash streams.
In attach you can find the zip with 2 json get with getVariantTracks that may help you: one on 3.0.2 and one on 3.0.6.
[getVariantTracks.zip](https://github.com/google/shaka-player/files/5672130/getVariantTracks.zip)

**Comment by sbrez** [comment]
@joeyparrish you can also use the stream you find here [https://github.com/google/shaka-player/issues/2178#issuecomment-540225574](https://github.com/google/shaka-player/issues/2178#issuecomment-540225574)

**Comment by michellezhuogg** [comment]
Introduced by this [commit](https://github.com/google/shaka-player/commit/16e7b9bfbd1bc7a1c10e0756553f7726830a0e39).
