### ISSUE TITLE
Local cache is causing video to play at 1-fps until cookies are cleared

### ISSUE THREAD

**Issue by ThomasSkinner** [google/shaka-player#2890]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
latest

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `master`?**
yes

**Are you using the demo app or your own custom app?**
custom

**If custom app, can you reproduce the issue using our demo app?**
no

**What browser and OS are you using?**
firefox, mac

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**
using dash and widevine, can't share info

**What did you do?**
it plays well the first time, and it stops working on page reload sometimes

**What did you expect to happen?**
the video to play normally

**What actually happened?**
The video has 1 frame per second and no audio. The problem persists until you clear cookies for the site. Then it works normally until a reload causes the cache to become "corrupted" again, then I get 1 FPS again.

Has anyone ever experienced this issue? How can I fix it? Is there a way to turn off offline storage?

**Comment by TheModMaker** [comment]
Without access to the content, it will be hard to diagnose.  My guess is this is a platform bug.  Does this issue happen on Chrome or on a different platform (e.g. Windows)?  In Chrome, you can use DevTools to profile JavaScript to see if there is some errant JavaScript eating all the CPU time (there is probably something similar in Firefox you could check).

Is the problem that the video plays very slowly, or that the current time moves forward normally but the image only updates every second?  Is the player in a buffering state (do you see the buffering spinner or is `player.isBuffering()` true)?  What is the value of `video.playbackRate` when this happens?

If you aren't using `shaka.offline.Storage`, then we don't persist anything offline.  The browser will cache network responses, but there is no way to control this.

**Comment by ThomasSkinner** [comment]
It's reproducible when I seek to the middle of the video then immediately refresh the page. It slows down the playback until cookies are cleared.

player.isBuffering() is false.

video.playbackRate is 0.0625, and setting it to 1 fixes the problem. None of my code sets this value though...

I'm not using shaka.offline.Storage.

I appreciate the reply... any other thoughts on this? I think it's happening on other platforms as well.

This might be unrelated but i'm seeing this error pop up in the console from time to time
`http_xhr_plugin.js:89 GET https://dve-streams.akamaized.net/ns-006/MjAyMA/Nw/M_TM/32ac909a-d42b-47fa-877c-a070181cab52/video/3d2a9023-e632-435f-b1d2-d12b81de4a69/exp=1601757434~acl=%2f*~id=dea1edbc-8e66-42c5-a342-18f88bbb468c~data=hdntl~hmac=be2791751ac46aad212c08cf940b452b1531a92982cfb29b1ecf02248efc5645/1.m4s net::ERR_SSL_PROTOCOL_ERROR 200 (OK)`

**Comment by joeyparrish** [comment]
Cookies are sent by a server to the browser, and are then returned by the browser next time.  Shaka Player doesn't do anything with cookies directly.

Also, I'm very skeptical that cookies have anything to do with it.  Are you clearing your browser cache?  Or _just_ cookies?

**Comment by ThomasSkinner** [comment]
@joeyparrish I think it's the cookies

I click the button immediately to the left of the address in the address bar on chrome, then I click cookies and it opens up this dialogue to remove them
[dialogue picture](https://imgur.com/a/5PgIfH1)

**Comment by joeyparrish** [comment]
That is really very odd.  There's not reasonable explanation for this that I can think of.  Shaka Player does not directly interact with cookies in any way.

As @TheModMaker mentioned, though, we really won't be able to help diagnose this any further without a way to reproduce it.  Since it seems to be specific to this content, you would have to share it with us privately before we could help you.  There is an email address in the issue template where you can share private information if you choose.

**Comment by Eric-Airtime** [comment]
Hi, I work with Thomas and we were gathering some more information about the bug. We found that additionally, the problem occurs with HLS/DASH videos such as those from the following links:

- https://bitmovin-a.akamaihd.net/content/MI201109210084_1/m3u8s-fmp4/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8
- https://bitmovin-a.akamaihd.net/content/MI201109210084_1/mpds/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.mpd

Creating an additional player and loading the other link will produce the issue on that one as well. However, loading an MP4 seems to clear the issue, as does clearing the cookies on the page. To specifically reproduce the issue, we set the page/player to automatically load one of the links and then seeked forward outside the buffered range and reloaded while the video buffered and on reload, the player would play at 1 fps with slowed audio. This is all that we have found so far. Please don't hesitate to reach out if you need additional information.

**Comment by ThomasSkinner** [comment]
> Hi, I work with Thomas and we were gathering some more information about the bug. We found that additionally, the problem occurs with HLS/DASH videos such as those from the following links:
> 
>     * https://bitmovin-a.akamaihd.net/content/MI201109210084_1/m3u8s-fmp4/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8
> 
>     * https://bitmovin-a.akamaihd.net/content/MI201109210084_1/mpds/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.mpd
> 
> 
> Creating an additional player and loading the other link will produce the issue on that one as well. However, loading an MP4 seems to clear the issue, as does clearing the cookies on the page. To specifically reproduce the issue, we set the page/player to automatically load one of the links and then seeked forward outside the buffered range and reloaded while the video buffered and on reload, the player would play at 1 fps with slowed audio. This is all that we have found so far. Please don't hesitate to reach out if you need additional information.

I don't think that last paragraph is relevant to this forum because it's more about our client code and not directly about shaka player.

We are working on creating a MRE and ruling out that the bug is not coming from another source. Will update the thread after that happens. Thanks!

**Comment by ThomasSkinner** [comment]
We think the bug was coming from Plyr integration. I believe we tried to reproduce it in standalone in shaka and we couldn't. Sorry!

**Comment by joeyparrish** [comment]
Understood.  Thanks for the update!
