### ISSUE TITLE
[Ads] allow requesting ads with adsResponse instead of adTagUrl

### ISSUE THREAD

**Issue by DDeis** [google/shaka-player#2892]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Is your feature request related to a problem? Please describe.**

Currently, shaka throw an error if `adTagUrl` is not set in `imaRequest`. 
Though, per [IMA SDK for HTML5 documentation](https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/reference/js/google.ima.AdsRequest#adsResponse), it is possible to specify a VAST document to use as the ads response instead of making a request via an ad tag url.

**Describe the solution you'd like**

I would like to be able to use `adsResponse` field to play ads. 

**Additional context**

This can be useful for people with CORS issues when their ad server is not allowing call with `http://imasdk.googleapis.com` origin and they have no control over the ad server configuration.

I have a working PR ready to be submitted if needed.

**Comment by TheModMaker** [comment]
The docs you link to say that `adTagUrl` is required, so we'd still need to throw if the field isn't set.  We also appear to accept arbitrary objects for that, so you can still set that field.  Lastly, I'm not sure how that will help with CORS errors.  You would still need to make the request and read the response to be able to pass the response in that field anyway.  Lastly, I don't know what kinds of CORS errors you'd see here; the `http://imasdk.googleapis.com` server would be the one setting CORS headers to allow requests, which I assume already sets the correct CORS headers.

**Comment by DDeis** [comment]
Indeed the `adTagUrl` properties is marked as required though in reality it doesn't seems to be.

In Android SDK, [setAdTagUrl()](https://developers.google.com/interactive-media-ads/docs/sdks/android/client-side/api/reference/com/google/ads/interactivemedia/v3/api/AdsRequest.html#public-abstract-void-setadtagurl-string-adtagurl) is also marked as required, though on [IMA Forum an IMA SDK Team member](https://groups.google.com/g/ima-sdk/c/fZ6ZGUyNSlQ/m/Apr2uIGCGyYJ) indicates that we can use `setAdsResponse()` instead of `setAdTagUrl()`.

I haven't found a similar message for the HTML5 SDK (except a dead link in a [videojs-ima issue](https://github.com/googleads/videojs-ima/issues/208) and the corresponding [PR](https://github.com/googleads/videojs-ima/pull/214/files)) but I believe this is the same as it works perfectly without setting an adTagUrl and only setting adsResponse. Also, to prove my point, the [IMA HTML5 SDK Video Suite Inspector](https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/vastinspector) allow testing ads with a VAST XML without setting an ad tag.

I can still use `adsResponse` and set a random string in `adTagUrl` that is not even a valid url as Shaka is throwing when the property is empty. It's working properly because IMA ignores `adTagUrl` and uses `adsResponse` instead, but in my opinion it is not an ideal solution because when using IMA alone without Shaka, I would not have to do this.

About the CORS issue, I have the following error when using `adTagUrl` that I don't have when fetching the VAST myself:
> Access to XMLHttpRequest at 'https://...' from origin 'http://imasdk.googleapis.com' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.

**Comment by TheModMaker** [comment]
In that case, it's probably a harmless enough feature we could add.  I've found many other instances of that error and  the IMA team says (and we agree) that you should file a bug with the ad provider to either add the `Access-Control-Allow-Credentials: true` header or explicitly list the `http://imasdk.googleapis.com` origin in the `Access-Control-Allow-Origin` header (wildcard doesn't work).  It's best to fix CORS errors instead of avoiding them.

**Comment by DDeis** [comment]
I created a PR for this if you want to have a look.

Thank you for your feedback on CORS, I agree with you it would be better if CORS was handle correctly. I raised the problem to our ad provider team in the past, but they didn't want to make a fix because the Android team doesn't have CORS issue when using `setAdsResonse()`. I can try and see if they can change their mind though !
