### ISSUE TITLE
Shaka player stops when jump forward

### ISSUE THREAD

**Issue by BerkayCinarrr** [google/shaka-player#2895]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.4

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Demo app

**If custom app, can you reproduce the issue using our demo app?**
NA

**What browser and OS are you using?**
MacOS Safari

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
NA

**What did you do?**

When I try to jump forward video stops and do not play ever again. If I use default safari player there is not problem.

**What did you expect to happen?**
I expected to Shaka player do not stop and continue to playing as well as default Safari player.

**What actually happened?**

Shaka player stops and do not play ever again.

**Comment by joeyparrish** [comment]
Does this happen with our demo content?  Or only with specific content you have?

If this involves specific content, you will need to provide manifest and license server URIs for us to reproduce, as detailed in the part of the issue template you deleted.

**Comment by BerkayCinarrr** [comment]
Thank you for your quick response.
These are my all files.
https://drive.google.com/drive/folders/1WAjHuZdmASd0wdXm58wnIKeqagRr3Xae?usp=sharing

**Comment by joeyparrish** [comment]
@BerkayCinarrr, I requested access to your files.  But a URL we could load into the player would be more helpful.

Do you have this issue in any other browser?  Or only in Safari?
