### ISSUE TITLE
No way to check if automatic adaptation enabled

### ISSUE THREAD

**Issue by sanbornhnewyyz** [google/shaka-player#29]
I can't see a way to check if adaptation is enabled or not. I think it would be useful to have a method player.getAdaptationEnabled() that just returns the value of adaptationEnabled_.

**Comment by joeyparrish** [comment]
Hrm... It's easy enough to add, and I don't mind doing it.  But out of curiosity, why is it useful?  I had thought that there would be two basic use cases:

1. Adaptation always enabled or disabled, and therefore set once programmatically.
2. Adaptation always controlled by some application UI element, and therefore set on interaction with that element.

When would you want to query the state?  How would your application lose track of whether or not adaptation was enabled?

**Comment by sanbornhnewyyz** [comment]
I agree with you that it is easy enough to keep track of but if it's ever ambiguous what the starting state is or just not known what the starting state is, it seems like there is the potential to get out of sync. To me it seems like it's the responsibility of the player to manage its own state and that way whoever is using it can't ever get out of sync or make the wrong assumption about what state it is in.

Also, I'm happy to submit a pull request so you can concentrate on higher priority stuff.  Maybe this won't be generally considered useful.

**Comment by joeyparrish** [comment]
I'm not sure it would get out of sync, though.  It's easy to set explicitly as soon as Player is created.

In any case, this debate is purely philosophical.  I don't object to the feature.  Please feel free to submit a pull request.

It may be a bit more pain than contributing to the typical open-source project, but Google does require a one-time contributor agreement as outlined in [CONTRIBUTING.md](https://github.com/google/shaka-player/blob/master/CONTRIBUTING.md).

And thanks for offering to contribute.  You're the first!

**Comment by Awais-cb** [comment]
this is the way of checking if abr is enabled or not

> shakaPlayer.getConfiguration().abr.enabled

it returns true or false accordingly.

**Comment by joeyparrish** [comment]
@Awais-cb, this thread was closed 2.5 years ago.  Please try not to reopen very old threads.  Shaka Player looks very different today than it did in 2015.  Thanks!
