### ISSUE TITLE
IE11 Live stream playback issue

### ISSUE THREAD

**Issue by neilRGS** [google/shaka-player#290]
Hi.

I am having trouble with Live stream playback through IE11.  The player loads on screen and then nothing further happens.

**UPDATE**:-----:
Looking in IE developer tools, I can see that the manifest is being read every 10s (approx)
In Edge and Firefox, video and audio chunks are loaded in between the maifest reads.  So it looks as through IE is maybe not parsing the manifest.  I could be wrong in that assumption, but that's what it looks like.
:-----:

VOD playback works fine.

Below is the output from the browser support page, viewed through IE11:

Thanks in advance for any advice you can give.

Neil.

========== Browser Support page output ==============
userAgent Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; InfoPath.3; rv:11.0) like Gecko 
Required Features FAIL 
QoE Stats OK 
Subtitles missing 
Encrypted Content unknown 
Offline Content OK 
Requires Polyfills yes 
===== ===== 
HTMLMediaElement (unprefixed) 
MediaSource (unprefixed) 
Promise (not found) 
Uint8Array (unprefixed) 
VTTCue (not found) 
fullscreenElement ms 
fullScreenElement (not found) 
CustomEvent (not usable) 
indexedDB (unprefixed) 
video/webm; codecs="vp8" (not found) 
video/webm; codecs="vp9" (not found) 
video/mp4; codecs="avc1.42E01E" (supported) 
video/mp2t; codecs="avc1.42E01E" (not found) 
getVideoPlaybackQuality (unprefixed) 
droppedFrameCount (not found) 
decodedFrameCount (not found) 
generateKeyRequest (not found) 
MediaKeys MS 
create (not found) 
isTypeSupported (unprefixed) 
requestMediaKeySystemAccess (not found) 
MediaKeySystemAccess (not found) 
getConfiguration (not found) 
MediaKeySession MS 
org.w3.clearkey (not found) 
com.widevine.alpha (not found) 
com.microsoft.playready (supported) 
com.adobe.access (not found) 
com.apple.fairplay (not found) 

===============  END  ============================

**Comment by peyoh** [comment]
@neilRGS, 
whatrelease number  you are using ? 1.6.2 or 1.6.3 ?

**Comment by neilRGS** [comment]
@peyoh. Hi.  I am using 1.6.3

**Comment by peyoh** [comment]
Please revert to 1.6.2 and try again.

**Comment by neilRGS** [comment]
@peyoh. Will do.  I'll post the result of doing that, here.

**Comment by neilRGS** [comment]
@peyoh.  I have downloaded, built and tried 1.6.2
Unfortunately, no difference in behaviour has been observed.
I will look at it again later today/tomorrow, as I need to jump on to a new task now

Thanks.

**Comment by peyoh** [comment]
@neilRGS Thank you for your time. 
Please be sure, that the browser's cache is cleared before trying the previous version.

BRS,
Peyo

**Comment by neilRGS** [comment]
Hi @peyoh.
I have cleared my browser cache and tried again this morning with v1.6.2
I get a very similar result, in that a blank player loads and then nothing further happens visually.
The manifest loads and then is reloaded every 10s or so.

I had a look at https://html5test.com/ and it shows that IE11 does not support Promise.  As there are plenty of Promises in the Shaka code, perhaps that is a major issue.

If so, I wonder why the Shaka docs suggest that IE11 is ok?

Ultimately, as IE11 is a browser in use by a good many of our clients, I am going to have to find something else which will work without flash being installed.
Do you know of any other libraries that I could try?

Many thanks again for your help and input, it is appreciated.

Neil.

**Comment by neilRGS** [comment]
Hi @peyoh.
A final note.

I have tried using a polyfill and this now shows in the support page that Required Features is 'OK'.
No change in live streaming though.
I used this: [https://github.com/taylorhakes/promise-polyfill](https://github.com/taylorhakes/promise-polyfill)

I can rule out encoding issues, because I get successful playback in Firefox, Chrome & Edge with both live and VOD.  In IE11 only VOD plays successfully.

So, no further on really, but I wanted to add that extra info, for anyone else reading this, experiencing the same problem.


Many thanks

Neil.

**Comment by joeyparrish** [comment]
@neilRGS @peyoh Shaka support for live on IE11 starts with v2, which has not been released yet.

In v1, we expect that we can set `video.currentTime` before appending segments.  This is not true on IE11.  In v2, we no longer have this assumption.

We expect v2 beta to be available in a week or two.  Thanks!

**Comment by neilRGS** [comment]
Hi @joeyparrish 
Thank you for the update.  That's good to hear!
I will await the release of v2 beta with great anticipation.

If it helps any, I have had a certain amount of success with Dash.js and IE11.  It is not production quality though, as it will stream for a while and then seems to get stuck in a loop and then continues etc...
I would obviously prefer to use a single framework if at all possible, and don't want to spend time coercing Dash to work as Shaka is going to be moving in this direction very soon.

Have a good weekend,

Neil.

**Comment by joeyparrish** [comment]
Thanks, Neil.  We are reasonably confident that v2 will solve this for you, since v2's `StreamingEngine` already passes all unit and integration tests on IE11.  Now we just have to complete the rest of v2!  :-)

**Comment by neilRGS** [comment]
Hi Joey.
I hope everything is going well.

Any update on the release of v2 at all?

Thanks in advance,

Neil.

**Comment by joeyparrish** [comment]
We expect a beta by the end of the month, which we will announce on the mailing list.

**Comment by joeyparrish** [comment]
@neilRGS, can you please try with the latest from master?  We just released v2-beta.  If it still does not work for you, can you provide as link to your manifest?

**Comment by neilRGS** [comment]
Will do, Joey
It won't be until Monday, as it is beer o'clock, here in the UK.
Sent from Outlook Mobile<https://aka.ms/blhgte>



On Fri, Apr 8, 2016 at 10:47 AM -0700, "Joey Parrish" <notifications@github.com<mailto:notifications@github.com>> wrote:


@neilRGS<https://github.com/neilRGS>, can you please try with the latest from master? We just released v2-beta. If it still does not work for you, can you provide as link to your manifest?

-

**Comment by joeyparrish** [comment]
🍻

**Comment by neilRGS** [comment]
Hi Joey.
Sorry for the delay.

I have just spun up a demo to play with v2.

I have followed the instructions at http://shaka-player-demo.appspot.com/docs/api/tutorial-basic-usage.html but am unfortunately stumped by this error:
myapp.js:7          Uncaught ReferenceError: shaka is not defined

Has the shaka object been renamed to something else in an update, perhaps?

Many thanks and best regards,
Neil

**Comment by neilRGS** [comment]
UPDATE: Working. ☺  About to do more testing.
I cleared everything out, rebuilt all.py and tried again.

Best regards,

Neil.

**Comment by neilRGS** [comment]
Hi Joey.
In IE11, the console shows everything as working ok.  I am getting video and audio chunks streaming through the player on-screen.  It is just showing the poster image with a loading animation.

The manifest is generated by our Wowza server and is this:

+++++++++++++++++++++++++++++++++++++++++++++++
`<?xml version="1.0" encoding="UTF-8"?>
<MPD xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xmlns="urn:mpeg:dash:schema:mpd:2011"
     xmlns:xlink="http://www.w3.org/1999/xlink"
     xsi:schemaLocation="urn:mpeg:DASH:schema:MPD:2011 http://standards.iso.org/ittf/PubliclyAvailableStandards/MPEG-DASH_schema_files/DASH-MPD.xsd"
     profiles="urn:mpeg:dash:profile:isoff-live:2011"
     type="dynamic"
     minimumUpdatePeriod="PT5.013S" 
     publishTime="2016-04-20T09:18:26Z" 
     availabilityStartTime="2016-04-19T13:31:09Z" 
     timeShiftBufferDepth="PT50.0S"
     suggestedPresentationDelay="PT15.0S" 
     minBufferTime="PT6.0S">
<ProgramInformation>
    <Title>Stream1</Title>
</ProgramInformation>
<Location>http://wowza.rgsit.com/LiveSim/_definst_/Stream1/manifest_w2047453045.mpd</Location>
<Period id="0" start="PT0.0S">
    <AdaptationSet id="0" mimeType="video/mp4" width="512" height="288" par="16:9" frameRate="30" segmentAlignment="true" startWithSAP="1" subsegmentAlignment="true" subsegmentStartsWithSAP="1">
        <SegmentTemplate timescale="90000" media="chunk_ctvideo_cfm4s_rid$RepresentationID$_cs$Time$_w2047453045_mpd.m4s" initialization="chunk_ctvideo_cfm4s_rid$RepresentationID$_cinit_w2047453045_mpd.m4s">
            <SegmentTimeline>
                <S t="6406308000" d="900000"/>
                <S d="900000"/>
                <S d="900000"/>
                <S d="900000"/>
                <S d="900000"/>
            </SegmentTimeline>
        </SegmentTemplate>
        <Representation id="p0a0r0" codecs="avc1.42c015" sar="1:1" bandwidth="601000" />
    </AdaptationSet>
    <AdaptationSet id="1" mimeType="audio/mp4" lang="eng" segmentAlignment="true" startWithSAP="1" subsegmentAlignment="true" subsegmentStartsWithSAP="1">
        <Role schemeIdUri="urn:mpeg:dash:role:2011" value="main"/>
        <SegmentTemplate timescale="48000" media="chunk_ctaudio_cfm4s_rid$RepresentationID$_cs$Time$_w2047453045_mpd.m4s" initialization="chunk_ctaudio_cfm4s_rid$RepresentationID$_cinit_w2047453045_mpd.m4s">
            <SegmentTimeline>
                <S t="3416697856" d="480256"/>
                <S d="480256"/>
                <S d="480256"/>
                <S d="479232"/>
                <S d="480256"/>
            </SegmentTimeline>
        </SegmentTemplate>
        <Representation id="p0a1r0" codecs="mp4a.40.2" audioSamplingRate="48000" bandwidth="96000">
            <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
        </Representation>
    </AdaptationSet>
</Period>
</MPD>`
+++++++++++++++++++++++++++++++++++++++++++++++

**Comment by tdrews** [comment]
Hi, I am able to reproduce the issue on IE11 on Windows 10. I see that the content works on Chrome Linux and Chrome Windows. Also, I see that the default Wowza test asset works fine on IE11 too. Nothing obvious seems wrong, so I'll have to investigate further.

**Comment by joeyparrish** [comment]
I am able to reproduce in both IE11 and Edge, but on a system with known-bad clock-sync.  If I hack a `UTCTiming` element into the manifest for clock sync, my client's clock gets adjusted by ~12 seconds and the content plays on both IE11 and Edge.  @neilRGS, can you configure Wowza to put a suitable `UTCTiming` element into the manifest?

**Comment by neilRGS** [comment]
I'll take a look and see if I am able to do that.

**Comment by joeyparrish** [comment]
@neilRGS, we've added two things to help with this.  One is a warning when UTCTiming is missing, and the other is a config option to specify a clock sync URI outside of the manifest.  Please let us know if this helps.
