### ISSUE TITLE
Application Level Redirects for byte-range requests

### ISSUE THREAD

**Issue by lyjimmy** [google/shaka-player#2901]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.4

**Please ask your question**
Hello,

I've looked through the docs for ALRs (https://shaka-player-demo.appspot.com/docs/api/tutorial-application-level-redirects.html), but do you have any recommendations on how to handle ALRs for byte-range segment requests? For instance, suppose the original segment request has a Range header value. In the response filter, it doesn't look like there's a way to know what the Range header on the request was, so it's hard to tell what the Range header value should be for the redirect request. I see the `uri` in the response object, but I would expect this to be the same for requests with different byte-range requests from the same resource.

Thanks!

**Comment by joeyparrish** [comment]
Since ALRs are *application-specific*, the format of the response can be anything your server and client can agree on.  The example we give in the doc does not include a byte range, but you could certainly include a range in some format in the response, parse it, and set the `Range` header on the chained request.

[There are more ALR formats in heaven and earth, @lyjimmy, than are dreamt of in your philosophy.](http://www.shakespeare-online.com/quickquotes/quickquotehamletdreamt.html)

For example, building on the format from the doc, your response might be a URL with a range appended like this:

```
https://foo.bar/baz;1234-5678
```

This would be the URL `https://foo.bar/baz`, using bytes `1234` through `5678`.  Tweaking the sample content in the doc, you could handle such a scheme with something like:

```js
player.getNetworkingEngine().registerResponseFilter(async (type, response) => {
  const dataView = new DataView(response.data);
  if (response.data.byteLength < 4 ||
      dataView.getUint32(0) != HTTP_IN_HEX) {
    // Our ALRs are detected by a response body which is a URL.
    // This doesn't start with "http", so it is not an ALR.
    return;
  }

  // It's an Application-Level Redirect (ALR).  That requires us to get the new
  // URL and follow it.

  // Interpret the response data as a URL string.
  const responseAsString = shaka.util.StringUtils.fromUTF8(response.data);

  // Split off the byte range, if present.
  const responsePieces = responseAsString.split(';');
  const uris = [responsePieces[0]];

  // Make another request for the redirect URL.
  const redirectRequest =
      shaka.net.NetworkingEngine.makeRequest(uris, retryParameters);

  // Add a Range header for the byte range, if present.
  if (responsePieces.length > 1) {
    redirectRequest.headers['Range'] = 'bytes=' + responsePieces[1];
  }

  const requestOperation =
      player.getNetworkingEngine().request(type, redirectRequest);
  const redirectResponse = await requestOperation.promise;

  // Modify the original response to contain the results of the redirect
  // response.
  response.data = redirectResponse.data;
  response.headers = redirectResponse.headers;
  response.uri = redirectResponse.uri;
});
```

Or you could imagine a scheme in which the URL and byte range are in JSON:

```json
{"url": "https://foo.bar/baz", "range": "1234-5678"}
```

And you could handle it with something like:

```js
player.getNetworkingEngine().registerResponseFilter(async (type, response) => {
  // Interpret the response data as JSON.
  let jsonData;
  try {
    const responseAsString = shaka.util.StringUtils.fromUTF8(response.data);
    jsonData = JSON.parse(responseAsString);
  } catch (error) {
    // Not an ALR.
    return;
  }

  const uris = [jsonData.url];

  // Make another request for the redirect URL.
  const redirectRequest =
      shaka.net.NetworkingEngine.makeRequest(uris, retryParameters);

  // Add a Range header for the byte range, if present.
  if (jsonData.range) {
    redirectRequest.headers['Range'] = 'bytes=' + jsonData.range;
  }

  // ...
});
```

Or if it's somehow 1998 again, you could build an XML-based format:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<ApplicationLevelRedirect url="https://foo.bar/baz" range="1234-5678" />
```

And parse it with:

```js
player.getNetworkingEngine().registerResponseFilter(async (type, response) => {
  // Interpret the response data as XML.
  let xmlData;
  try {
    const responseAsString = shaka.util.StringUtils.fromUTF8(response.data);
    const parser = new DOMParser();
    xmlData = parser.parseFromString(responseAsString, 'text/xml');
    if (xmlData.documentElement.tagName != 'ApplicationLevelRedirect') {
      // XML, but not an ALR.
      return;
    }
  } catch (error) {
    // Not an ALR.
    return;
  }

  const uris = [xmlData.documentElement.getAttribute('url')];

  // Make another request for the redirect URL.
  const redirectRequest =
      shaka.net.NetworkingEngine.makeRequest(uris, retryParameters);

  // Add a Range header for the byte range, if present.
  const range = xmlData.documentElement.getAttribute('range');
  if (range) {
    redirectRequest.headers['Range'] = 'bytes=' + range;
  }

  // ...
});
```

Does this help?

**Comment by lyjimmy** [comment]
Thanks for the quick and detailed reply! Makes sense; I was mainly curious whether or not there was already a built-in way to access the associated request info from the response filter. I think I should be able to so something similar to what you suggested.
