### ISSUE TITLE
No enabled audio or video stream

### ISSUE THREAD

**Issue by wojciech-bilicki-oke** [google/shaka-player#2902]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.5

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Not possible to check

**Are you using the demo app or your own custom app?**
Custom app

**If custom app, can you reproduce the issue using our demo app?**
No, everything works correctly on https://shaka-player-demo.appspot.com/demo/#build=uncompiled

**What browser and OS are you using?**
Chrome and Windows 

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Chromecast NC2-6A5

**What are the manifest and license server URIs?**
Sent to shaka-player-issues@google.com

**What did you do?**
Tried to play live stream

**What did you expect to happen?**
Stream plays without issues

**What actually happened?**
The stream does not load. 
I can see that there's request for the Manifest being made, but there's no request for license or chunks.
The only thing that distinguishes this situation from the case when stream plays normally is information in the console: 

[cast.player.core.MediaSourceManager] no enabled audio or video stream

**Comment by wojciech-bilicki-oke** [comment]
Thank you for your answer! I will provide more detailed info in another email.

**Comment by wojciech-bilicki-oke** [comment]
To elaborate further on the issue: 

After accessing the URL.

 You'll see the json representing the data for the stream. You can ignore the DRM property as we set up this stream to NOT protected. You can check it in Shaka Player Demo ( I sent direct url via email).

We're using CAF but I downloaded cast_receiver_framework.js and changed it to use ShakaPlayer 3.0.5, but also tested this issue with the cast_receiver_framework.js which can be found here:

www.gstatic.com/cast/sdk/libs/caf_receiver/v3/cast_receiver_framework.js"

Issue is occurring for both versions (2.5 and 3.0.5).
The issue occurs only for Chromecast receiver app. I can play the stream without any problem with the Shaka Player Demo test site. 
If you're not located in the EU, we have to ask you for your IP so that we can whitelist your access to the stream. 
If you need any additional info, please contact me.

**Comment by m-scheepers** [comment]
Some more background on the streams. 

The streams are coming from VSPP streaming platform and are token protected. For that reason the request Url was provided to get a new manifest url with a valid token. In production situations we target DASH+Widevine; but for testing a clear DASH stream can be used.

**Comment by joeyparrish** [comment]
As the error message "[cast.player.core.MediaSourceManager] no enabled audio or video stream" does not come from Shaka Player, I believe you should ask for support from the Cast Application Framework.  https://developers.google.com/cast/support

Sorry!
