### ISSUE TITLE
Parsing error for text track roles?

### ISSUE THREAD

**Issue by toschlog** [google/shaka-player#2903]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.5

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Have not tried

**Are you using the demo app or your own custom app?**
My own app

**What browser and OS are you using?**
Electron app on Windows 10.

**What are the manifest and license server URIs?**
The manifest is here:
https://vod-l3c-na-central-1.media.dssott.com/ps01/disney/60a600e8-1306-4118-b96b-b0b1f783871a/regular-ctr-sw-12f799ae-27f0-4ba1-a66c-796f996cb5a6-0cadf278-25b1-483f-83e8-613060ec8558.m3u8

Here is the specific line in question:
`#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="sub-main",NAME="English [CC]",LANGUAGE="en",AUTOSELECT=YES,FORCED=NO,CHARACTERISTICS="public.accessibility.transcribes-spoken-dialog,public.accessibility.describes-music-and-sound",URI="r/composite_en_SDH_8a5caa83-c7d4-4cc8-8a01-e0b423e6e574_049131dd-c29e-4637-b983-d9c42bcc5612.m3u8"`

**What did you do?**
I call getTextTracks() after this manifest has loaded and look at the entry for the English CC track.

**What did you expect to happen?**
I would expect an array with two entries, like this:

```
roles: [
   "public.accessibility.transcribes-spoken-dialog",
   "public.accessibility.describes-music-and-sound"
]

```
**What actually happened?**
I get an array with one entry, like this:

```
roles: [
   "public.accessibility.transcribes-spoken-dialog,public.accessibility.describes-music-and-sound"
]
```

**Comment by avelad** [comment]
PR --> https://github.com/google/shaka-player/pull/2905

**Comment by joeyparrish** [comment]
@toschlog, you are right!  Thanks for pointing this out.  @avelad, thank you for the quick PR!
