### ISSUE TITLE
No way to select a track *without* a particular role

### ISSUE THREAD

**Issue by toschlog** [google/shaka-player#2906]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.5

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Have not tried

**Are you using the demo app or your own custom app?**
My own app.

**What browser and OS are you using?**
Electron on Windows 10

**What are the manifest and license server URIs?**
https://vod-l3c-na-central-1.media.dssott.com/ps01/disney/60a600e8-1306-4118-b96b-b0b1f783871a/regular-ctr-sw-12f799ae-27f0-4ba1-a66c-796f996cb5a6-0cadf278-25b1-483f-83e8-613060ec8558.m3u8

**What did you do?**
This manifest has two English tracks, one with audio descriptions and one without.  I can select the one with audio descriptions like this:

`playerRef.current.selectAudioLanguage("en", "public.accessibility.describes-video")`

but I can't figure out how to switch back to the English track that doesn't have the descriptions.

**What did you expect to happen?**
I would expect there to be a way to selected a video track that has no enumerated roles.

**Comment by joeyparrish** [comment]
Good point!  I'm sorry we hadn't noticed this before.  We can fix the `select*Language()` methods to give you a way to explicitly select no role.

Until then, you can use `getVariantTracks()` and `selectVariantTrack()` to explicitly select any track.  Does this help?
