### ISSUE TITLE
Add Track object to Adaptation events

### ISSUE THREAD

**Issue by toschlog** [google/shaka-player#2907]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.5

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Have not tried

**Are you using the demo app or your own custom app?**
My own app

**What browser and OS are you using?**
Electron on Windows 10

**What are the manifest and license server URIs?**
https://vod-ftc-na-central-1.media.dssott.com/ps01/disney/60a600e8-1306-4118-b96b-b0b1f783871a/regular-ctr-sw-12f799ae-27f0-4ba1-a66c-796f996cb5a6-0cadf278-25b1-483f-83e8-613060ec8558.m3u8

**What did you do?**
I am setting preferred languages, like this:
```
player.configure({
      preferredAudioLanguage: "es",
      preferredTextLanguage: "de"
    })
```
And then I am handling the "adaptation" event to determine what languages were actually selected.

**What did you expect to happen?**
I would expect some useful data in the adaptation event.

**What actually happened?**
Most of the data in the adaptation event is minimized,  I can find the string "es" in the output, but really I'm just guessing on what it means.

![image](https://user-images.githubusercontent.com/25090868/95885573-63065600-0d4b-11eb-8111-79bf460b3b8a.png)

Is there another way to get the current audio and text tracks?  I couldn't find one.

**Comment by joeyparrish** [comment]
The `currentTarget` of an `Event` object is the object on which it was dispatched, which in this case is the `Player` object.  The internals of `Player` are, of course, minimized in a production build.  Those minified fields were never intended for you to access directly, but you can always access the exported methods on the API, for example:

```js
const player = event.currentTarget;
const tracks = player.getVariantTracks();
const activeTrack = tracks.find((t) => t.active);
```

If you check the current docs for `AdaptationEvent` (https://shaka-player-demo.appspot.com/docs/api/shaka.Player.html#.event:AdaptationEvent) you will see that there are no specific fields on that type.  Would it be helpful if we added, for example, a `Track` object to the event showing which `Track` we adapted to?

**Comment by toschlog** [comment]
Returning a Track object might be helpful, but it's not a big deal.  If I can iterate through the variant and text tracks to find the active ones then I've got what I need.

Thanks for your help.

**Comment by joeyparrish** [comment]
We would be very happy to take a PR for this if you are interested to contribute!  In the meantime, we have higher priority features in progress, such as MediaCapabilities and preload.

**Comment by avelad** [comment]
According to the documentation it's already supported: https://shaka-player-demo.appspot.com/docs/api/shaka.Player.html#.event:AdaptationEvent

See: https://github.com/google/shaka-player/commit/795860ffb82fd69a8df8c1c3f5e7a9880b8fb505

@joeyparrish, can be closed?

**Comment by joeyparrish** [comment]
Yes, looks like someone took care of it and didn't tag the issue.  Thanks for pointing this out, @avelad.
