### ISSUE TITLE
Player will select the audio description track by default

### ISSUE THREAD

**Issue by toschlog** [google/shaka-player#2909]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.5

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
My own app

**If custom app, can you reproduce the issue using our demo app?**
Have not tried

**What browser and OS are you using?**
Electron on Windows 10

**What are the manifest and license server URIs?**
https://vod-vzc-na-central-1.media.dssott.com/ps01/disney/60a600e8-1306-4118-b96b-b0b1f783871a/regular-ctr-sw-12f799ae-27f0-4ba1-a66c-796f996cb5a6-0cadf278-25b1-483f-83e8-613060ec8558.m3u8

**What did you do?**
Start the video.  Let ShakaPlayer pick the audio track.

**What did you expect to happen?**
The regular English track would play.

**What actually happened?**
Sometimes the regular English track plays, and sometimes the track with audio descriptions plays.

The default should be the track without the audio descriptions.

Interestingly, setting preferredAudioLanguage to "en" before loading the manifest seems to result in the correct behavior.

**Comment by joeyparrish** [comment]
That is interesting.  I think this could be related to the logic responsible for #2906, but I haven't done enough research to call this a duplicate.

But it's clearly a bug that the player behaves this way.  Thank you for letting us know!

**Comment by joeyparrish** [comment]
Oh, incidentally, we are unable to test any of the content links you've sent because you didn't send a corresponding license server URL.  It would be really helpful to have that info.

You can send that privately to shaka-player-issues at google.com (as mentioned in the issue template) and mention this issue number, and the details will not leave the Shaka Player team at Google.  Thanks!
