### ISSUE TITLE
Chrome works, but Firefox Error code 4032

### ISSUE THREAD

**Issue by xekon** [google/shaka-player#2910]
**Notes**
I suspect the problem is that Firefox does not support the stream type, but I was under the impression that mux.js would take care of that.
I appreciate any help in resolving this, please let me know if you require any more info, I have my entire setup process documented. (I plan to make it a tutorial on my blog)

Also I am not sure if ffmpeg will continue to run indefinitely, I currently have it running, but if it for some reason stops I can restart it.
I have not done a whole lot of testing, I only just got shaka player up and running a couple days ago after having a lot of issues with videojs.

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes the only faq that seemed like it might be relevant is "Why doesn't my HLS content work?"" however I have included mux.js

**What version of Shaka Player are you using?**
The latest from github, I built it yesterday from `git clone https://github.com/google/shaka-player.git`

**Can you reproduce the issue with our latest release version?**
Yes, I am using the latest version

**Can you reproduce the issue with the latest code from `master`?**
Yes, I am fairly certain when I clone the main repo that I am on the master branch.

**Are you using the demo app or your own custom app?**
I used the demo app as a starting point and only changed the supplied manifest

**If custom app, can you reproduce the issue using our demo app?**
No the demo app appeared to work, so it may have something to do with my environment, however it does work in chrome and not firefox, so I would still appreciate some help figuring out if this is indeed a bug or if it is something that I just missed with configuration of my environment

**What browser and OS are you using?**
Both the Server and the Client are using Ubuntu 20.04
Browsers used are both Chrome and Firefox, only Firefox is having an issue.

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
no embedded devices were used

**What are the manifest and license server URIs?**
manifest: https://hls.solosaga.com/dash/cam0.mpd
webpage: https://cams.solosaga.com/

other files, not sure if they matter:
https://hls.solosaga.com/dash/chunk-stream0-000xx.m4s (about 10 of these numbered sequentially)
https://hls.solosaga.com/dash/init-stream0.m4s
https://hls.solosaga.com/dash/master.m3u8
https://hls.solosaga.com/dash/media_0.m3u8

**What did you do?**
The setup is basically the demo + getting started tutorial, the main thing changed was the source to my webcam stream that is being generated by ffmpeg:

`sudo ffmpeg -r 5 -f v4l2 -s 160x120 -i /dev/video0 -vcodec libx264 -use_timeline 1 -use_template 1 -window_size 6 -hls_playlist true -f dash /mnt/tmpfs/dash/cam0.mpd`

you can open the page with both chrome and firefox, and you will see that chrome works, but firefox does not, it reports Error code 4032 to the console.

**What did you expect to happen?**
I expected that the stream would play in firefox like it does in chrome.

**What actually happened?**
In Firefox the video does not play, error code 4032 is shown in the console, the page loads but it just spins and spins in the middle of the video box.

**Comment by xekon** [comment]
I ended up installing motion: https://github.com/Motion-Project/motion

so far everything is working great with motion and the webcam stream is viewable in either firefox or chrome, additionally it has the ability to save the stream permanently to file when motion is detected, I am also seeing far less cpu usage compared to when I used ffmpeg.

Shaka player still worked really good in chrome and if this firefox issue could be resolved I could certainly see myself turning to shaka player in the future for other projects. I am going to keep the stream and manifest viewable for a few days so that it can be useful for this bug report. but I plan disable the stream soon, now that I am happily using motion.

**Comment by BucherTomas** [comment]
Your issue likely stems from the way Firefox handles decoding. It is mostly dependent on what the underlying platform provides while Chrome additionally incorporates its own software decoders based on libav.

Your stream https://hls.solosaga.com/dash/master.m3u8 is created in the yuv 4:2:2 colorspace, which is uncommon and quite a lot of decoders could not handle it. Try forcing conversion to common yuv 4:2:0 in the ffmpeg commandline by using additonal video filter `format`:

`sudo ffmpeg -r 5 -f v4l2 -s 160x120 -i /dev/video0 -vcodec libx264 -vf format=yuv420p -use_timeline 1 -use_template 1 -window_size 6 -hls_playlist true -f dash /mnt/tmpfs/dash/cam0.mpd`

**Comment by xekon** [comment]
Spot On! that worked perfectly, thank you so much for the help :)
