### ISSUE TITLE
Support HLS FORCED attribute

### ISSUE THREAD

**Issue by toschlog** [google/shaka-player#2916]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.3

**Can you reproduce the issue with our latest release version?**
Haven't tried

**Can you reproduce the issue with the latest code from `master`?**
Haven't tried

**Are you using the demo app or your own custom app?**
My own app

**If custom app, can you reproduce the issue using our demo app?**
Haven't tried

**What browser and OS are you using?**
Electron on Windows 10

**What are the manifest and license server URIs?**
https://vod-vzc-na-central-1.media.dssott.com/ps01/disney/60a600e8-1306-4118-b96b-b0b1f783871a/regular-ctr-sw-12f799ae-27f0-4ba1-a66c-796f996cb5a6-0cadf278-25b1-483f-83e8-613060ec8558.m3u8

**What did you do?**
Played a video and called selectAudioLanguage("es")

**What did you expect to happen?**
I expected the "forced" Spanish subtitles to play.

**What actually happened?**
No subtitled played.  And when I turned on subtitles with setTextTrackVisibility(true) they were in, I think, Danish.

I can find the forced subtitles by scanning the list of text tracks and looking for ones with "--forced--" in the label, and then selecting the one with the language that matches the audio track I've selected.  But I think this is something that should happen automatically.

**Comment by michellezhuogg** [comment]
Hello @toschlog ,

I got 'Shaka Error DRM.NO_LICENSE_SERVER_GIVEN (com.widevine.alpha)' error when trying to test with your manifest.
Could you provide us with the DRM license info?

**Comment by joeyparrish** [comment]
I can help with this one.  We don't have built-in support for forced subs at this time.  When we do add it, anything automatic like that needs to be based on the relevant standards (DASH or HLS), not an ad-hoc label-based convention.

HLS appears to have a FORCED attribute that we could use for this purpose.  I have not yet looked into the equivalent for DASH.

There would need to be a role or attribute added to our `Track` object to represent that a sub is forced, and then other components need to be updated to enforce that.

**Comment by joeyparrish** [comment]
I've marked this as an enhancement to add support.  There is already an issue filed for DASH support, and your content is specifically HLS, so I'll rename this issue to specifically target HLS support.

**Comment by joeyparrish** [comment]
DASH support is discussed in #2122
A TTML-specific feature for this is discussed in #1184
