### ISSUE TITLE
HLS subtitles not loading in Safari beyond first language

### ISSUE THREAD

**Issue by ScripterYoda** [google/shaka-player#2919]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.5

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Custom

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Safari 13.1.2 (15609.3.5.1.3), macOS Catalina 10.15.6

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
https://1313403029.rsc.cdn77.org/r/kd7/TOM__JERRY/SINTEL/h264.m3u8

**What did you do?**
When changing to Ukraine text track, they do not appear. Our manifest has segmented subtitles.

**What did you expect to happen?**
Polish subtitles to appear.

**What actually happened?**
Nothing, no manifest for subtitles is loaded, no segment for subtitles is loaded.

**Comment by theodab** [comment]
By default, when playing HLS content on Safari, we actually leave the playback to the browser. This is to allow FairPlay to work out of the box, since the APIs for FairPlay are not accessible at our level.
I tried playing your sample content in Safari 13.1.2 on macOS Catalina 10.15.6, both with native playback enabled and disabled, and the captions play correctly when we are playing them. So this looks like a Safari bug rather than a Shaka Player bug.
In the meantime, you should try setting `streaming.useNativeHlsOnSafari` to `false` when configuring the player. That should help (unless you are using FairPlay, sadly).

**Comment by ScripterYoda** [comment]
What still worries me is HLS Player, which seems to be just Safari native player, handles subtitles properly while Safari native player (opened just by opening manifest directly in browser) also does not display Ukraine subtitles.

Nevertheless, thank you very much for the reply.

**Comment by joeyparrish** [comment]
That's understandable.  I double-checked just now on Safari with the Shaka Player demo, and I found:

1. We're definitely setting src= on the video element, delegating playback to Apple
2. Two text tracks are presented by Apple: Polish and Ukrainian
3. We're selecting and activating the text tracks correctly
4. When we select Polish, the TextTrack's cues field has a non-zero length, and subtitles show up
5. When we select Ukrainian, the TextTrack's cues field has a length of zero, and no subtitles show up

**Comment by joeyparrish** [comment]
I then started listening to network requests in Safari and found that the browser fetches vtt files for Polish when that language is selected, but does not fetch vtt files for Ukrainian when that language is selected.

So next I started looking into the playlist contents.  I found that when I switched to Ukrainian, not only were no vtt files fetched, but the Ukrainian subs playlist was also not fetched.  This led me to look at the master playlist.

There I found that the two subtitle files were in separate groups.  Further, I found that if I edit the master playlist to place both subtitles into the same group ID, the problem vanishes!  Here's a URL for that edited master playlist so you can try it out: https://storage.googleapis.com/shaka-demo-assets/_bugs/2919/fixed.m3u8

So, it seems that this is either a bug in Shaka Packager, or a problem with the arguments you gave to it when the content was created.  

@ScripterYoda, are you using the Packager command-line or are you using it as a C++ library?

@kqyang, are there command-line arguments or API parameters that influence the creation of subtitle group IDs in Packager?  Or is this based purely on language?

**Comment by ScripterYoda** [comment]
@joeyparrish, yes, I am using command-line Packager and I was explicitly setting group ids to be different for each subtitle track.
So, I think that solves the issue. Thank You very much 👍

**Comment by kqyang** [comment]
@joeyparrish Yes, it can be specified using `hls_group_id` stream descriptor. All text streams will be grouped together if it is not specified (i.e. using the same default group id) and likewise for audio streams.

@ScripterYoda Setting the group id to the same value or just omitting it should solve your issue.

**Comment by joeyparrish** [comment]
Excellent.  I'm glad we could all get this figured out!  Thanks, everyone!
