### ISSUE TITLE
Is it possible to customize the seekbar 

### ISSUE THREAD

**Issue by hichem-code-it** [google/shaka-player#2922]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
Master branch (Commit: f7626ff60a8dea7391fb8eab5369634727eb3bf3)

**Please ask your question**
I can see that it is currently possible to add or not a seekbar using the addSeekBar parameter in the UI configuration. But to be able to implement some custom features, I'm trying to use a different class than shaka.ui.SeekBar for my seekbar. Is it possible without changing the current shaka player source code ?

**Comment by joeyparrish** [comment]
Yes, that should be possible.  The `SeekBar` class, like all of our provided UI elements, is a plugin.  You can build your own UI plugins and register and style them.

Though looking more closely it looks like there may be a few small complications we should fix, IMO:

1. We position the other elements based on the presence or absence of the seek bar.  So if you configure the UI to skip ours, the rest of the elements will be positioned lower by default.  You can work around this in your app's CSS by overriding ours and changing the positioning of the other elements.
2. We have a RangeElement base class that is used by the seek bar, and handles browser-specific styling issues and intelligently handles rapid changes to the underlying `<input>` element.  This is exported for apps to use, but the protected fields in it are being renamed by the compiler.  This is clearly a bug, and we should fix it.
3. You could work around these issues to register a replacement seek bar as a generic element, and position it how you like.  But we could make it easier.  If we gave you a way to register a specific class to be used in place of our own seek bar class, and we made a public interface for you to implement, that would make replacing the seek bar much, much simpler for you.

So I propose we make the following changes:

1. Create an external seek bar class interface, so the compiler doesn't rename it
2. Offer a way to configure a seek bar class factory, so apps can ask us to instantiate a custom one
3. Make the RangeElement interface external, so apps can use it as a base class as we always intended

Would this help?

**Comment by joeyparrish** [comment]
See #2923 and #2924 for tracking issues for those fixes and features.

**Comment by hichem-code-it** [comment]
Thks for you quick answer.

I could replace the seekbar using in the instruction in the plugin section documentation as you pointed out, running:

python build/build.py +@complete -ui/seek_bar.js  +hichem/seek_bar.js 

It would definitely help if it could be done without having to rebuild the project, as you suggest in point "2" and with clean exported interfaces, even better !

**Comment by joeyparrish** [comment]
I agree.  You shouldn't have to rebuild to make a plugin.  We really just overlooked the seek bar as a plugin opportunity, and we'll correct that in #2924.  So please subscribe to that issue for updates!

Have we answered all of your questions for now?

**Comment by kocoten1992** [comment]
Coincidentally, I just write this tuts https://github.com/google/shaka-player/pull/2931, before the real fix come in, you could try this:
- extends shaka seekbar
- overwrite it
- reregister it back

When init shaka-player, it will use your code instead of default shaka seekbar.

**Comment by hichem-code-it** [comment]
> Have we answered all of your questions for now?

Yes thank you.

**Comment by theodab** [comment]
If you have any further questions, feel free to ask!
