### ISSUE TITLE
Adaptive Streaming with DRM, HLS and Fairplay using an external monitor

### ISSUE THREAD

**Issue by roenschg** [google/shaka-player#2928]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes!

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes!

**What version of Shaka Player are you using?**
3.0.5

**Please ask your question**
When using HLS in Safari in combination with SAMPLE-AES DRM encryption we encounter a weird issue.

We offer a master playlist (m3u8 file) that contains three streams in different resolutions.

```m3u8
#EXTM3U
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-STREAM-INF:AVERAGE-BANDWIDTH=1000470,BANDWIDTH=1000470,RESOLUTION=1920x1080,FRAME-RATE=60.000,CODECS="avc1.42c01e",CLOSED-CAPTIONS=NONE
video_1080p.m3u8?assetId=7f39f5d80f232438501ce83a9ef52536
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=57478,CODECS="avc1.42c01e",RESOLUTION=1920x1080,URI="video_1080p.m3u8?assetId=7f39f5d80f232438501ce83a9ef52536&iframe"
#EXT-X-STREAM-INF:AVERAGE-BANDWIDTH=583002,BANDWIDTH=583002,RESOLUTION=1280x720,FRAME-RATE=60.000,CODECS="avc1.42c01e",CLOSED-CAPTIONS=NONE
video_720p.m3u8?assetId=7f39f5d80f232438501ce83a9ef52536
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=32472,CODECS="avc1.42c01e",RESOLUTION=1280x720,URI="video_720p.m3u8?assetId=7f39f5d80f232438501ce83a9ef52536&iframe"
#EXT-X-STREAM-INF:AVERAGE-BANDWIDTH=212088,BANDWIDTH=212088,RESOLUTION=348x360,FRAME-RATE=60.000,CODECS="avc1.42c01e",CLOSED-CAPTIONS=NONE
video_360p.m3u8?assetId=7f39f5d80f232438501ce83a9ef52536
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=10269,CODECS="avc1.42c01e",RESOLUTION=348x360,URI="video_360p.m3u8?assetId=7f39f5d80f232438501ce83a9ef52536&iframe"
```

We visit the website with a Mac that has an external monitor connected.

On some requests the video is not playable. (The player only shows a play button that is crossed)

On the requests that are leading to issues we saw that the 1080p playlist was used first, and the decryption of the video
file parts are not successfully. The web console does not show any different messages.
Requests that work use the 360p file first and are able to decrypt all video files.

We tested to feed the playlist with a specific resolution to the player and this works on every request. An example of
the linked files with specific resolution looks like this:

```m3u8
#EXTM3U
#EXT-X-VERSION:5
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-TARGETDURATION:8
#EXT-X-KEY:METHOD=SAMPLE-AES,URI="skd://drm",KEYFORMAT="com.apple.streamingkeydelivery"
#EXTINF:7.733,
video_1080p-1.ts?assetId=7f39f5d80f232438501ce83a9ef52536
#EXT-X-ENDLIST
```

It seems to us that the adaptive streaming has issues, but we are not able to understand the underlying issue.

I also added the screenshots of the console output with enabled debugging.
![working](https://user-images.githubusercontent.com/9590236/96601944-c87db800-12f2-11eb-9e99-578ff08348a7.png)
![with issue](https://user-images.githubusercontent.com/9590236/96601948-c9aee500-12f2-11eb-8c1b-53e37e0764b1.png)
<

Does anyone has an idea why we might encounter this problem?

**Comment by TheModMaker** [comment]
When playing FairPlay content, we just pass the manifest to the browser and Safari handles everything.  There is probably nothing we can do to help.  It's possible FairPlay isn't allowing using an external display due to security restrictions, but I wouldn't know how to control that.  My guess is this is a FairPlay license setting in your server that controls that.

**Comment by mimse** [comment]
Could try using a different HDMI cable. Not all cables handle DRM.

**Comment by roenschg** [comment]
After a deep dive we where able to fix the issue. We changed the order of the playlist to include the high resolution last. 

Safari will then never use the 1080p version, only the 720p or 360p version. I guess that this is due to restriction in the license to now allow high resolutions if the DHCP chain is somehow not working.

Thank you @TheModMaker and @mimse ! You can close the issue now.
