### ISSUE TITLE
How to obtain the displayed bitrate for ABR playbacks?

### ISSUE THREAD

**Issue by ragotiteb** [google/shaka-player#2929]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes. The closest i can see is 
https://github.com/google/shaka-player/issues/857
but this idea/question is a bit less ambitious in scope

**What version of Shaka Player are you using?**
3.0.4

**Please ask your question**

For ABR playbacks (DASH, concretely is of interest to me), is there a way to know accurately the bitrate currently being displayed to the user? 

I see it as perhaps being related to another question/request ( https://github.com/google/shaka-player/issues/857 ), except that here i don't talk about chunk-level details, only to know when the bitrate changes. If i were to be a bit more broad, it would be good to know when the properties on the media stream displayed change (so, aside of bitrate, also framerate, originalId... )

At first i thought the property streamBandwidth might be it, but upon inspection, it seems to be tied to the variant selection (a decision made for loading), not to the rendering end.

If i were to make some sort of comparison with other player stacks and platforms, what I'm looking for is something close to the onVideoInputFormatChanged() event from exoPlayer. We have a solution that spans across platforms (web and android being some)  and I'd like to gather comparable statistics from them. The currently displayed bitrate is an important one for us, and i'm a bit unclear on what would be the way (if there's any) to obtain it from shaka player.

**Comment by joeyparrish** [comment]
Unfortunately, this information is not yet available from the web platform.  It is feasible for an application or library to carefully track this information in JavaScript, but it could be complex.

We would need to track what we append to `MediaSource`, and also keep track of the implications of timestamp offsets and append windows (which trim the appended content).  Add to that the facts that timestamp information from the manifest can be inaccurate, append windows can trim off more than you asked for (up to the next keyframe), and that rounding errors can cause you to make poor estimates of _exactly_ what the browser will do with your data... and it could be very difficult to get it right without tight controls on the content itself.

So I don't think this is something we will be able to offer at the moment.  If/when `MediaSource` APIs allow us to tag the data we append and track it that way, this sort of tracking becomes very doable with the aid of the web platform itself.  And if we had to do it in JavaScript, it would not be especially accurate in all cases.

Does this answer your question?

**Comment by ragotiteb** [comment]
Hi @joeyparrish , thanks for the answer. Yes, this answers the question, and in fact matches quite a bit with our internal investigation on the matter, and we reach similar conclusions regarding the need for tracking what is appended to `MediaSource` to make it happen in the current state of APIs. 

Since we need this for our solution, we will give it a shot at trying the append information and using the playback position to navigate through it. This might be , as you very correctly state, not as accurate, but it will at least get us closer to what we need.

Thanks again!

**Comment by mad-gooze** [comment]
hi @joeyparrish!

I think this might be done via custom hidden metadata text track appended to media element (one for audio and one for video)

MediaSourceEngine may add a cue with segment metainfo and a timestamp when this append was made. Then you may obtain the current segment by querying activeCues property and taking a cue with the latest timestamp.

**Comment by joeyparrish** [comment]
@ragotiteb, thanks for giving it a try!  We look forward to hearing how it turns out, and we would be happy to discuss it as a PR if you'd like to contribute that back to the project when you're done.

@mad-gooze, that sounds reasonable, assuming broad platform support for metadata text tracks.  I know often smart TVs lag in terms of web APIs, but I don't have any data on how widely-supported metadata text tracks are in practice beyond desktop & mobile browsers.

**Comment by ragotiteb** [comment]
@shaka-bot yes, i think so.
