### ISSUE TITLE
 HLS Content stuck at the end if the last ts file is broken

### ISSUE THREAD

**Issue by noaviten** [google/shaka-player#2937]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
3.0.5

**Please ask your question**
Hello,
I'm trying to play this manifest with Shaka player -
https://vms-videos.minutemediaservices.com/01e5k0gyr6853w2xvw/m3u8/01e5k0gyr6853w2xvw.m3u8
On Chrome with including the Mux.js library on Safari (without the Mux.js).

This is the m3u8 file: 
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:4
#EXT-X-MEDIA-SEQUENCE:1
#EXT-X-PLAYLIST-TYPE:VOD
#EXTINF:4,
01e5k0gyr6853w2xvw_1080p_00001.ts
#EXTINF:4,
01e5k0gyr6853w2xvw_1080p_00002.ts
#EXTINF:4,
01e5k0gyr6853w2xvw_1080p_00003.ts
#EXTINF:4,
01e5k0gyr6853w2xvw_1080p_00004.ts
#EXTINF:4,
01e5k0gyr6853w2xvw_1080p_00005.ts
#EXTINF:1,
01e5k0gyr6853w2xvw_1080p_00006.ts
#EXT-X-ENDLIST

On Safari: The content stuck at the end, at 00:19 (the duration is 21 seconds) without any errors from Shaka.
On Chrome with Mux.js: The content stuck at the end, at 00:19 (the duration is 21 seconds) with the following error: code -3018 - Mux.js did not invoke the callback signifying successful transmuxing.

I noticed that the last ts file is broken, I can't play it - https://vms-videos.minutemediaservices.com/01e5k0gyr6853w2xvw/m3u8/01e5k0gyr6853w2xvw_1080p_00006.ts 
 
I try to play this content on native Safari and on Chrome with the Hls.js library, in both of the scenarios the last ts file was ignored, and the duration, as taken from the video tag was 20 seconds (without the broken ts file).

Is there any way that the Shaka player can skip broken ts files?

**Comment by TheModMaker** [comment]
On Safari, we usually use native playback, so it should be the same behavior as if you set `src=` yourself.  Did you change `streaming.useNativeHlsOnSafari`?

What about your content is bad?  The fact that Safari ignores it may mean there is something we're doing wrong or a different way we could handle it.

We usually try to avoid working around bad content.  In many cases, there is nothing we can do about it.  For example, most bad content will cause a decoder error from the browser.  When this happens, not only is there nothing we can do to prevent it, it will stop playback permanently and we can't even recover.  We also don't like hiding errors from apps; we want to inform people of the problems in their content so they can fix it and the content will be more broadly playable.

**Comment by noaviten** [comment]
Hi, thanks for your reply @TheModMaker 
I didn't change the `streaming.useNativeHlsOnSafari`.
I didn't get any indication from Shaka that something is wrong (except for the 3016 error that indicates from Mux.js that the trunsmuxing operation didn't succeed - Chrome only). 
I want to handle this bad content myself, is there a way that I can detect that the playback is stuck? I didn't find any event or other indication for it.

**Comment by joeyparrish** [comment]
If the content is broken, I believe there's not much we can do about it except selectively ignore error 3016.

Does this help?
