### ISSUE TITLE
[Demo] Ads can get shown when playing assets with no ads configured

### ISSUE THREAD

**Issue by DDeis** [google/shaka-player#2943]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.5

**Can you reproduce the issue with our latest release version?**

**Can you reproduce the issue with the latest code from `master`?**

**Are you using the demo app or your own custom app?**
Demo App

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
Mac OS 10.15.7 - Chrome 86.0.4240.80

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What did you do?**
1. On the [demo homepage](https://shaka-player-demo.appspot.com/demo/#build=compiled)
2. Play _Sintel_
3. During the preroll ad, click on _Angel One_ play button
4. Seek to a position after 00:15 **=> The player start the midroll from Sintel ad**
5. During the midroll ad, click on _Big Buck Bunny: the Dark Truths_ play button
6. Seek to the end of the video **=> The postroll ad from Sintel begins to play**

**What did you expect to happen?**
I expect that when switching asset from one with ads to when without ads, no ads get shown when playing an asset that isn't supposed to have some.

**What actually happened?**
It seems that ads doesn't get "canceled" when switching assets.

**Comment by theodab** [comment]
I think this is related to #2869.
