### ISSUE TITLE
Getting Re-Buffering issue on Shaka Standalone player with Samsung Device

### ISSUE THREAD

**Issue by Ragav-Valtech** [google/shaka-player#2944]
We are getting re-buffering issue on shaka standalone playback on Samsung device.
Steps to reproduce the issue:
1. Launch the shaka standalone page with Samsung Tizen app
2. allow the playback to play upto 15 to 20 mins, 
3. after certain time playback is getting buffering very often.
4. Observed that, fragment calls taking time to resolve.
please find the details below:
**Shaka playback version** : 3.0.4, 3.0.5 (tested on both the version)
**DRM** : Playready
**Device** : Samsung,
**Device model** : UA43N5370AUXXL / 2018

Please find the sharable link which contains screenshots for the reference.

https://drive.google.com/file/d/1UfT8_UKqbOm1IHbMTzKHDZXU9sUbUUNy/view?usp=sharing
![image_2020_10_27T14_55_49_413Z](https://user-images.githubusercontent.com/73548585/97334820-28e89880-18a3-11eb-8e9c-d223ec33ce0c.png)

![image_2020_10_27T14_56_46_551Z](https://user-images.githubusercontent.com/73548585/97334797-24bc7b00-18a3-11eb-86e9-7888bae66061.png)

![image_2020_10_27T14_57_59_535Z](https://user-images.githubusercontent.com/73548585/97334817-27b76b80-18a3-11eb-8468-d92bd32a7509.png)

**Comment by GouravSna** [comment]
Hi @joeyparrish , can you please help us on this issue. 
cc @Ragav-Valtech

**Comment by procot** [comment]
Hi. I have a similar problems too. I open [the demo page](https://shaka-player-demo.appspot.com/demo/#audiolang=ru;textlang=ru;uilang=ru;asset=https://storage.googleapis.com/shaka-demo-assets/sintel-mp4-only/dash.mpd;panel=ALL_CONTENT;panelData=DASH,HIGH_DEFINITION;build=uncompiled) on tizen 2018 and after playing 9-10 minutes of video, playback stops, the fps is greatly reduced, and the devtools console begins to respond to commands with delay.

I am using shaka-player v3.0.5.

**Comment by amitsamal** [comment]
This specifically we observed on DASH MPD and not using HLS.

**Comment by procot** [comment]
> This specifically we observed on DASH MPD and not using HLS.

@amitsamal Sorry, i didn't understand) Can you tell more about it?

**Comment by joeyparrish** [comment]
@Ragav-Valtech, @GouravSna, @procot, @amitsamal: We recently resolved a memory leak with certain types of DASH content (issue #3038, PR #3039, released in v3.0.7).  Can you please try again with the latest version of Shaka Player and let us know if these issues are resolved?

Thanks!
