### ISSUE TITLE
Shaka fails to play the trickmode keyframes for the dash contents.

### ISSUE THREAD

**Issue by yvashar** [google/shaka-player#2949]
The secondary instance of shaka is used to display the thumbnails for the primary video where the seek position of the primary video element is mapped to the current time of the thumbnail video element based on which it is expected to display the thumbnail frames for the corresponding position. 

To enable the trick play of keyframes, calling secondaryPlayer.trickPlay(3) inside the callback of secondaryPlayer.load(). However the keyframes are not updated inside the thumbnail container. 
Also, we don't see the keyframe segments getting downloaded in the browser network tab.
Here is the Adaptation set added for trickmode in the dash manifest,

      **<AdaptationSet maxHeight="144" maxWidth="256" mimeType="video/mp4" id="7" segmentAlignment="true" startWithSAP="1">
            <EssentialProperty
            				schemeIdUri="http://dashif.org/guidelines/trickmode"
            				value="1"/>
            <SegmentTemplate duration="6000" initialization="$RepresentationID$/i-frame/init.mp4" media="$RepresentationID$_184201/segment_$Number$.m4s" startNumber="0" timescale="1000" />
            <Representation bandwidth="81216" codecs="avc1.64001F" height="144" width="256" maxPlayoutRate="10" id="3mbps_i-frame.idx~i-frame~481~avc" scanType="progressive" />
        </AdaptationSet>**

**Comment by TheModMaker** [comment]
The `value` of the `trickmode` property is the `AdaptationSet@id` property that this is associated with.  We can only play that trick mode track when we are playing the associated `AdaptationSet` streams.

**Comment by yvashar** [comment]
So how to set this trickmode property in shaka ?

**Comment by yvashar** [comment]
Hi, player.getVariantTracks() does not return the i-frame variant(trick mode variant) in the resultant array. Is there any specific way to retrieve the id of the trickmode variant ?

**Comment by TheModMaker** [comment]
There's no way to select the i-frame track, we select it automatically when we enable trick-play.  You can only select the normal-mode tracks.  Unfortunately there isn't a way to find trick-play tracks from the normal Track object.  If you really wanted to get the ID, you could:

- Use the `track.id` to get the ID of the Variant
- Use `player.getManifest()` to get the manifest
- Find the variant with the same ID
- Use `variant.video.trickModeVideo` to get the trick-play Stream
- Use `stream.originalId` to get the `id` field that was in the manifest

**Comment by aparnarevu** [comment]
We need to Support for scrub bar with thumbnail images like YouTube while casting from iOS and Android. Do we need to set anything from the chrome cast sdk or Shaka Player side to show the thumbnails? 
Below is our request manifest:
<AdaptationSet contentType="image" mimeType="image/jpeg">
            <Representation bandwidth="6892" height="72" width="128">
                <SegmentTemplate duration="368640" media="$Number%08X$.jpg?pbs=1563ac8fe0064e699952d257f6181240&amp;drm=1&amp;cloud=aws" startNumber="0" timescale="90000" />
                <BaseURL>https://x-verizon-fios-vod3-stgec.uplynk.com/ausw/slices/099/5a83ec1bb4db4b739b568ec951b4327c/099d583a08794ebf9c45414f833aed93/</BaseURL>
                <EssentialProperty schemeIdUri="http://dashif.org/guidelines/thumbnail_tile" value="1x1" />
            </Representation>
            <Representation bandwidth="18774" height="144" id="upl256" width="256">
                <SegmentTemplate duration="368640" media="$RepresentationID$$Number%08X$.jpg?pbs=1563ac8fe0064e699952d257f6181240&amp;drm=1&amp;cloud=aws" startNumber="0" timescale="90000" />
                <BaseURL>https://x-verizon-fios-vod3-stgec.uplynk.com/ausw/slices/099/5a83ec1bb4db4b739b568ec951b4327c/099d583a08794ebf9c45414f833aed93/</BaseURL>
                <EssentialProperty schemeIdUri="http://dashif.org/guidelines/thumbnail_tile" value="1x1" />
            </Representation>
        </AdaptationSet>

Please suggest me.

**Comment by joeyparrish** [comment]
We don't support thumbnail tracks yet.  It's on our [roadmap](https://github.com/google/shaka-player/blob/master/roadmap.md), though.  See #559 for DASH thumbnail support.  We're happy to discuss designs there and review PRs.

**Comment by joeyparrish** [comment]
@yvashar, have we answered all of your questions?  Were you able to correct your manifest to make trick play work?
