### ISSUE TITLE
Does shaka support playback of trickmode frames?

### ISSUE THREAD

**Issue by kumarashu123** [google/shaka-player#2950]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
2.5.10 and tested in latest version(3.0.5)

**Please ask your question**

We have Adaptation set for trickmode included in the dash manifest  to enable thumbnails and when we try to playback the mpd file, shaka does not seem to download the keyframe segments. So does shaka support trick mode keyFrame playback ? 

 If shaka has the support already, then what is the configuration or step that has to be followed to enable the playback of keyFrames ?

Please see the below trick mode AdaptationSet used in dash manifest

`<AdaptationSet maxHeight="144" maxWidth="256" mimeType="video/mp4" id="7" segmentAlignment="true" startWithSAP="1">
        <EssentialProperty
        				schemeIdUri="http://dashif.org/guidelines/trickmode"
        				value="1"/>
        <SegmentTemplate duration="6000" initialization="$RepresentationID$/i-frame/init.mp4" media="$RepresentationID$_184201/segment_$Number$.m4s" startNumber="0" timescale="1000" />
        <Representation bandwidth="81216" codecs="avc1.64001F" height="144" width="256" maxPlayoutRate="10" id="3mbps_i-frame.idx~i-frame~481~avc" scanType="progressive" />
    </AdaptationSet>`

**Comment by TheModMaker** [comment]
Yes we support it, but only during trick-mode playback.  You enable this with `player.trickPlay(speed)`.  (Also, is this the same as #2949?)

Also, the `value` of the `trickmode` property is the `AdaptationSet@id` property that this is associated with. We can only play that trick mode track when we are playing the associated `AdaptationSet` streams.

**Comment by kumarashu123** [comment]
Yes, Thanks for the quick reply
