### ISSUE TITLE
Android devices have error "6002" after factory reset

### ISSUE THREAD

**Issue by nomadsus** [google/shaka-player#2952]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.5

**Please ask your question**

I have about 30 different Android devices, and this is a common phenomenon. I am trying to play a DASH file with DRM applied.

Step1. Factory reset the Android phone.

Step2. Connect via WiFi to a private network without Internet. (All Widevine license servers and content exist in this network)

Step3. If I try to play with the latest version of Chrome browser

> Error code: 6002
> Message: Shaka Error DRM.FAILED_TO_CREATE_CDM (Failed to execute'createMediaKeys' on'MediaKeySystemAccess': Cannot fetch origin ID)

Message appears.

Step4. Disconnect from the private network, connect to LTE, and enter www.google.com or any website via a chrome browser.

Step5. Disconnect the LTE and reconnect to the private network (NO internet).

Step6. If I play the video as before, it can play normally.

What is the cause of the symptoms I am experiencing?

**Comment by nomadsus** [comment]
Okay. I have one more question.
In what cases does the device request to be provisioned ?

**Comment by TheModMaker** [comment]
The device should remain provisioned so long as you don't factory reset the device.  I don't even think you can reset it by erasing site data, but I'm not sure.  Also note that provisioning is origin-specific; this means that one domain (e.g. netflix.com) might be provisioned, but another is not (e.g. youtube.com).  The device will make a request once you try to play protected content on that site.

**Comment by nomadsus** [comment]
Thanks for your kind reply. 😊
