### ISSUE TITLE
Potential leak: revoke the MediaSource object URL on sourceopen

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#2953]
I just learned from @wolenetz that we should be using [`URL.revokeObjectURL`](https://developer.mozilla.org/en-US/docs/Web/API/URL/revokeObjectURL) in the `sourceopen` event listener.  Otherwise, we may be leaking a MediaSource object and its resources for some time after detachment from the video element.

Apparently Chrome has a mitigation for this at the browser level to auto-revoke these, but we can't count on that in all browsers, and doing the right thing is pretty easy anyway.

**Comment by wolenetz** [comment]
Good call @joeyparrish 👍 
Note that Firefox has long had autorevocation of MediaSource object URLs (seemingly matching the original behavior of the FILE createObjectURL API before the more recent `createFor` was added to that API). Their retainment of autorevocation behavior thankfully made it much less regressing-to-existing-web-apps to switch Chrome back to doing similar.
