### ISSUE TITLE
VOD DASH Manifest loading in Firefox, but not Chrome

### ISSUE THREAD

**Issue by teamtofu** [google/shaka-player#2954]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v3.0.4

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Custom

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Firefox / Windows (no issue) and Chrome / Windows (issue)

This issue has also been observed on MacOS.

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
https://vcdn.officeparty.co/0768f14b-d422-4f97-9482-3689fff373bb/dash-manifest.mpd

Or check out the [demo player](https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://vcdn.officeparty.co/0768f14b-d422-4f97-9482-3689fff373bb/dash-manifest.mpd;panel=CUSTOM%20CONTENT;build=uncompiled)

(No License)

**What did you do?**

I tried to load a video from the VOD DASH manifest above in Chrome (v86).

**What did you expect to happen?**
I expected it to load for 1-2 seconds and then enable playback.

**What actually happened?**
Unlike Firefox (v82), which was able to playback the video, Chrome continually buffered (displayed loading spinner). Network logs showed that the audio and video were being buffered in correctly. 

The DASH manifest above was autogenerated by ffmpeg.

![Loading Video](https://user-images.githubusercontent.com/4558677/97815403-bb01ef80-1c5b-11eb-8be4-cbd0d2f264df.png)

**Comment by joeyparrish** [comment]
The content you linked to no longer appears to be available.  Is this still an issue for you?

If you need to reopen this issue, just put `@shaka-bot reopen` in a comment.  Thanks!
