### ISSUE TITLE
After disconnecting from chromecast, subtitles stop appearing in player

### ISSUE THREAD

**Issue by ScripterYoda** [google/shaka-player#2964]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What link can we use to reproduce this?**
Your own demo (Star Trek clip)

**What version of Shaka Player are you using?**
v3.0.5-uncompiled

**What browser and OS are you using?**
Chrome 86.0.4240.111, macOS Catalina 10.15.6

**What did you do?**
Turn on subtitles, connect to chromecast, disconnect from chromecast, video in web browser displays that the subtitles are on, but the subtitles are not displayed.

**What did you expect to happen?**
The subtitles are displayed and not affected by connecting and disconnecting to chromecast.

**What actually happened?**
The subtitles are not displayed.

**Comment by joeyparrish** [comment]
@ScripterYoda, are you using the Cast Application Framework?  Or our Cast API that's built into Shaka Player?

**Comment by sonicd300** [comment]
@shaka-bot reopen

I'm trying to side load text tracks on appDataCallback by passing them there (maybe there's a better way) they work sometimes but when disconnecting the cast session the captions picker is gone, in my case im using the built in shaka api, would it be better to open a separate discussion?
