### ISSUE TITLE
Download Complete my video in online but

### ISSUE THREAD

**Issue by tvserial** [google/shaka-player#2967]
Download Complete my video in online but i cant find it my local drive..where i can get my download video?plaese help
![Screenshot 2020-11-06 062623](https://user-images.githubusercontent.com/54730562/98311336-5a770780-1ff9-11eb-87b7-15eddbb867c9.jpg)
Its showing only delete option after download complete..but i need video..where i get this?

**Comment by joeyparrish** [comment]
We don't download videos to files on your hard drive.  They are stored in the browser using IndexedDB.

Does this answer your question?

**Comment by tvserial** [comment]
Then How can i get the video file?Please answer.

**Comment by avelad** [comment]
It looks like you have a copy of a repository that has legally struggled https://github.com/tvserial/widevine-l3-decryptor. Besides, your question I think has to do with this ...

**Comment by tvserial** [comment]
no its not...i download this file in shaka online player...but where i get this file? this is my question...where index file in chrome browser..i have widevine license..i can play it online but i need to download it...shaka online player download this file..but i can not found the video file after download..

**Comment by tvserial** [comment]
![Screenshot 2020-11-07 003618](https://user-images.githubusercontent.com/54730562/98402342-4ed71f80-2091-11eb-9827-d2e96a9faeee.jpg)
check..my video download completed..but i cant find the media file after download...anyone help me for found this?? please reply with a screenshout so that i can found this easily.

**Comment by tvserial** [comment]
how can recover video file from appdata?

**Comment by TheModMaker** [comment]
As stated above, we store it within the browser itself.  The browser stores the data somewhere in your profile folder in a browser-specific format.  There isn't a `video.mp4` file anywhere on your computer to play.  We only support downloading content for playback *within this app*.  You cannot play the downloaded content outside the app and there isn't a normal file on your hard drive to find.  You *must* use Shaka Player to play the downloaded content.  You can read more about that in [our tutorial](https://shaka-player-demo.appspot.com/docs/api/tutorial-offline.html).
