### ISSUE TITLE
6001 error when trying to play protected content on Tizen TV

### ISSUE THREAD

**Issue by MalgoBlock** [google/shaka-player#2968]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes
**What version of Shaka Player are you using?**
3.0.5
**Can you reproduce the issue with our latest release version?**

**Can you reproduce the issue with the latest code from `master`?**

**Are you using the demo app or your own custom app?**
custom app - Shaka works in browser but not on Tizen TV
**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Samsung 7 Series (43) 5.0
MN : UE43RU7179UXZG
FW : T-MSLDEUC-1360.9
FC : SWU-OU_T-MSLDEUC_1360_200618
MI : T-MSLDEUC
DI : EXCKEBBVJUZWI
MA : D0D003626785
SC : 10201_Z_Z_Z
**What are the manifest and license server URIs?**
Sent to your email
**What did you do?**

Try to play the same content as in the web app with the same app on Tizen TV - in the browser everything plays without probelms, but on TV the drm content doesn't play.
**What did you expect to happen?**
All content to play on TV
**What actually happened?**

A web version of the app using Shaka Player plays secured content without issues.
On Tizen TV only unsecured content is playing, secured content fails to play with 6001 error
{“severity”:2,“category”:6,“code”:6001,“data”:[],“handled”:false}
When I add allowCrossSiteCredentials = true to all request it still plays on web but fails with a 1002 (HTTP_ERROR, RequestType 0 - Manifest)

**Comment by joeyparrish** [comment]
Error 6001 means that the CDM isn't available or can't support the content.  But in #2989, we found that AC-3 is misreported on Tizen.  Does this apply to your situation as well?  Does your content use AC-3?

**Comment by joeyparrish** [comment]
A fix for #2989 is in, so if your content uses AC-3, please try the latest code from the `master` branch to see if that fix works for your situation, too.

**Comment by MalgoBlock** [comment]
Joey,

Thank you for your response!
I'll check it out in Monday and let you know!
We also have a theory that it might be down to our development environment
setup and it could be that in production the player would work fine - the
web version in our development goes through https but when it's on an
actual TV (in dev) then it would not be https and I think that's why the
token request is not being sent.

Warm regards,
Malgo

Joey Parrish <notifications@github.com> schrieb am Sa., 14. Nov. 2020,
02:18:

**Comment by MalgoBlock** [comment]
Joey,

I checked and we use mp4a.40.2 so it's not related to AC-3 issue.

Malgo

**Comment by MalgoBlock** [comment]
We have checked with a tunnel and it plays fine so it's our development env issue - so I'm closing this ticket.
