### ISSUE TITLE
[build] missing dist directory except run all.py first

### ISSUE THREAD

**Issue by kocoten1992** [google/shaka-player#2973]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Not related

**What version of Shaka Player are you using?**
v3.0.5

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `master`?**
yes (although current master build is bug right now - so I'm using v3.0.5)

**What did you do?**
```bash
git clone https://github.com/google/shaka-player
cd shaka-player && git checkout v3.0.5 && python3 build/build.py
```

**What did you expect to happen?**
It should work

**What actually happened?**
Except when we run `build/all.py` first and foremost
```python
# Make the dist/ folder, ignore errors.
base = shakaBuildHelpers.get_source_base()
try:
  os.mkdir(os.path.join(base, 'dist'))
except OSError:
  pass
```
If we don't run `all.py` first, we running into bug missing `dist` directory when `build/apps.py`, `build/build.py`, `build/check.py`...

Sometimes people only interested in `build.py` (because it a released version - not much reason to run check.py or to generate docs).

I've a few ideas in mind:
- we have mkdir in every `py` command
- create a placeholder dist and forget about mkdir

Do you have any thoughts ?

**Comment by kocoten1992** [comment]
This is a much deep problem than it seem.

Originally I want to build compiled shaka-player and shaka-player.ui but (`build.py` only build uncompiled UI - why is that :disappointed: ), and right now we consider changing build system  https://github.com/google/shaka-player/issues/1858.

Maybe when done switching to new build system, we could revisit this.

**Comment by joeyparrish** [comment]
Yes, our build system is a mess.  I'm so sorry!

This is a legitimate bug, even in the current system.  Every command should create dist/, and that wouldn't be very difficult to do.

The default build includes everything (equivalent to `build.py @complete`), which means it includes the UI.  So I'm not sure what you mean by:

> `build.py` only build uncompiled UI - why is that 😞

**Comment by kocoten1992** [comment]
@joeyparrish, correct me if I'm wrong, I'm just as confusing.

So the issue is missing `dist` directory ? If I'm create a directory then the build pass, exit code is 0. But **nothing** except shaka.ui uncompiled was build, reproducing as following code:

```bash
git clone https://github.com/google/shaka-player
cd shaka-player && git checkout v3.0.5 && mkdir dist && python3 build/build.py
```

The reason I'm dig into this is because I'm trying to write a plugin for shaka player (and will write docs back contribute back :+1: ).

If this don't work, then the idea
```bash
python build/build.py +@complete +my_plugin.js
```

It should not work (but I don't see anyone complain about it, so I'm guessing it somehow work).

**Comment by joeyparrish** [comment]
I ran your exact commands:

```sh
git clone https://github.com/google/shaka-player

cd shaka-player && git checkout v3.0.5 && mkdir dist && python3 build/build.py
```

And in dist/, I see:

```sh
$ ls dist/
locales.js  shaka-player.ui.externs.js  shaka-player.ui.js  shaka-player.ui.map  wrapper.js
```

That looks correct to me.  The UI-enabled, compiled output is `dist/shaka-player.ui.js`, with a source map in `dist/shaka-player.ui.map` and compiler externs in `dist/shaka-player.ui.externs.js`.  The rest are intermediate files generated, then used in compilation (`locales.js`, `wrapper.js`).

Does this help?

**Comment by kocoten1992** [comment]
Thanks! I've figure out where I got confused.

There are 3 points:
- Back in the day, we have jquery and [jqueryui](https://jqueryui.com/) (when use jqueryui we `MUST` include jquery first), that mindset follow me until now, with shaka-player we don't have to (fact is: shaka-player.ui already include shaka-player) - I agree here, some other library I know also did this, for example in laravel (a php framework), [fortify](https://github.com/laravel/fortify) for core authentication (without ui), and a version combine both core logic and ui [jetstream](https://github.com/laravel/jetstream). It just that, we need document a bit more clear here - for old generation people.
- We have **suffix without explaining** on build document (not all is familiar outside google - like `extern`, `compiled` - that equivalent `min` I know but we need that explaination), then `omg~` we even have `compiled.min` version on CDN like https://www.jsdelivr.com/package/npm/shaka-player and https://cdnjs.com/libraries/shaka-player that add greatly to the confusion.
- Just now we have `shaka-player.ui.js`, if we follow convention - it is suppose to be `shaka-player.ui.compiled.js`, right ? It just small detail but.. 

For now, I'll just create pull request for `dist`, just letting you know.
