### ISSUE TITLE
use Widevine + HLS + MPEG-TS to protected, but can't playback video with error 6001

### ISSUE THREAD

**Issue by lys1737** [google/shaka-player#2981]
I use shaka-packager to generate HLS + TS  and use shaka-player to playback,but it return error 6001.

 Error code 6001 object N {severity: 2, category: 6, code: 6001, data: Array(0), handled: false}

shaka-packager : v2.4.3
shaka-player:2.5.17

```
./packager-linux \
  'in=audio_aac_128k.mp4,stream=audio,segment_template=hls_ts_test/ts_audio_aac_128k_$Number$.aac' \
  'in=h264_main_720p_3000.mp4,stream=video,segment_template=hls_ts_test/ts_h264_main_720p_3000_$Number$.ts' \
  'in=h264_baseline_360p_600.mp4,stream=video,segment_template=hls_ts_test/ts_h264_baseline_360p_600_$Number$.ts' \
  --enable_raw_key_encryption \
  --keys label=**** \
  --pssh **** \
  --clear_lead 0 \
  --hls_master_playlist_output hls_test.m3u8
```

I use  https://github.com/amit08255/shaka-player-react-with-ui-config/tree/master/nextjs-shaka-player to playback,and add mux.js.

```
class MyApp extends App {

  componentDidMount(){
    const script = document.createElement("script")
    script.src = "https://github.com/videojs/mux.js/releases/latest/download/mux.js"
    script.async = true
    document.body.appendChild(script)
  }

  render() {
    const { Component, pageProps } = this.props;

    return (
      <Fragment>
        <Component {...pageProps}/>
      </Fragment>
    );
  }
}

export default MyApp;

```

HLS+TS playback if not encrypt.

**Comment by TheModMaker** [comment]
You should use the bug template and fill out the form.  Here are the questions you should answer:

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

**What version of Shaka Player are you using?**

**Can you reproduce the issue with our latest release version?**

**Can you reproduce the issue with the latest code from `master`?**

**Are you using the demo app or your own custom app?**

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What did you do?**

**What did you expect to happen?**


**What actually happened?**

Specifically the browser would be most useful.  6001 is [REQUESTED_KEY_SYSTEM_CONFIG_UNAVAILABLE](https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html#value:6001).  This means the platform doesn't support the DRM you requested.  For example, if this is Safari, you can't use Widevine since Safari doesn't support Widevine.

**Comment by lys1737** [comment]
Have you read the FAQ and checked for duplicate open issues?
Yes, I use chrome to playback HLS + TS ,but I found  error 6001 are about firebox on issue. 

What version of Shaka Player are you using?
2.5.17

Can you reproduce the issue with our latest release version?

Can you reproduce the issue with the latest code from master?

Are you using the demo app or your own custom app?
 https://github.com/amit08255/shaka-player-react-with-ui-config/tree/master/nextjs-shaka-player 
and add mux.js
If custom app, can you reproduce the issue using our demo app?

What browser and OS are you using?
chrome 70

For embedded devices (smart TVs, etc.), what model and firmware version are you using?
No

What are the manifest and license server URIs?

What did you do?
playback HLS + TS

What did you expect to happen?
playback  HLS + TS

What actually happened?
Error code 6001 object N {severity: 2, category: 6, code: 6001, data: Array(0), handled: false}

my m3u8 is widevine HLS v2 which generated by shaka-packager.

**Comment by lys1737** [comment]
it is my pssh data 000000707073736800000000EDEF8BA979D64ACEA3C827DCD51D21ED000000501210303130323033303430353036303730381210313132323333343435353636373738381210313132323333343435353636373738391A066E656C647476221030313032303330343035303630373038

**Comment by Nutura** [comment]
I have same problem

**Comment by TheModMaker** [comment]
Could you provide a sample manifest URL (not the text)?

My guess is that we don't convert the MIME type from TS to MP4 when checking EME support.  Normally we transmux the TS to MP4 before passing to the browser.  We need to convert the TS MIME type to MP4 before checking if the browser supports it.  I know we do this for [MediaSource](https://github.com/google/shaka-player/blob/ebb1e34ba1fa938349dacbee9922e598e0acb9bf/lib/media/media_source_engine.js#L122), but it looks like we don't do that in [DrmEngine](https://github.com/google/shaka-player/blob/ebb1e34ba1fa938349dacbee9922e598e0acb9bf/lib/media/drm_engine.js#L1606).

**Comment by lys1737** [comment]
main.m3u8
```
#EXTM3U
## Generated with https://github.com/google/shaka-packager version v2.4.3-dd98700-release

#EXT-X-MEDIA:TYPE=AUDIO,URI="stream_0.m3u8",GROUP-ID="default-audio-group",NAME="stream_0",AUTOSELECT=YES,CHANNELS="2"

#EXT-X-STREAM-INF:BANDWIDTH=817506,AVERAGE-BANDWIDTH=758019,CODECS="avc1.42c01e,mp4a.40.2",RESOLUTION=480x270,AUDIO="default-audio-group"
stream_1.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=3429202,AVERAGE-BANDWIDTH=3186565,CODECS="avc1.42c028,mp4a.40.2",RESOLUTION=1280x720,AUDIO="default-audio-group"
stream_2.m3u8
```
stream_1.m3u8
```
#EXTM3U
#EXT-X-VERSION:6
## Generated with https://github.com/google/shaka-packager version v2.4.3-dd98700-release
#EXT-X-TARGETDURATION:7
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-KEY:METHOD=SAMPLE-AES,URI="data:text/plain;base64,AAAAcHBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAAFASEDAxMDIwMzA0MDUwNjA3MDgSEDExMjIzMzQ0NTU2Njc3ODgSEDExMjIzMzQ0NTU2Njc3ODkaBm5lbGR0diIQMDEwMjAzMDQwNTA2MDcwOA==",KEYID=0x31313232333334343535363637373838,IV=0x5F5D41CAF34FA8612A94BF3F56FBD165,KEYFORMATVERSIONS="1",KEYFORMAT="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed"
#EXTINF:6.000,
ts_h264_baseline_360p_600_1.ts
#EXTINF:6.000,
ts_h264_baseline_360p_600_2.ts
#EXTINF:6.000,
ts_h264_baseline_360p_600_3.ts
#EXTINF:6.000,
ts_h264_baseline_360p_600_4.ts
```

network ts_h264_baseline_360p_600_2.ts success but  TS file stop before ts_h264_baseline_360p_600_2.ts with error 6001. and license server can't receive license request. 

when I use DASH + MP4, HLS+MP4, it works.

**Comment by lys1737** [comment]
main.m3u8
```
#EXTM3U
## Generated with https://github.com/google/shaka-packager version v2.4.3-dd98700-release

#EXT-X-MEDIA:TYPE=AUDIO,URI="stream_0.m3u8",GROUP-ID="default-audio-group",NAME="stream_0",AUTOSELECT=YES,CHANNELS="2"

#EXT-X-STREAM-INF:BANDWIDTH=817506,AVERAGE-BANDWIDTH=758019,CODECS="avc1.42c01e,mp4a.40.2",RESOLUTION=480x270,AUDIO="default-audio-group"
stream_1.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=3429202,AVERAGE-BANDWIDTH=3186565,CODECS="avc1.42c028,mp4a.40.2",RESOLUTION=1280x720,AUDIO="default-audio-group"
stream_2.m3u8
```

stream_1.m3u8
```
#EXTM3U
#EXT-X-VERSION:6
## Generated with https://github.com/google/shaka-packager version v2.4.3-dd98700-release
#EXT-X-TARGETDURATION:7
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-KEY:METHOD=SAMPLE-AES,URI="data:text/plain;base64,AAAAcHBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAAFASEDAxMDIwMzA0MDUwNjA3MDgSEDExMjIzMzQ0NTU2Njc3ODgSEDExMjIzMzQ0NTU2Njc3ODkaBm5lbGR0diIQMDEwMjAzMDQwNTA2MDcwOA==",KEYID=0x31313232333334343535363637373838,IV=0x5F5D41CAF34FA8612A94BF3F56FBD165,KEYFORMATVERSIONS="1",KEYFORMAT="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed"
#EXTINF:6.000,
ts_h264_baseline_360p_600_1.ts
#EXTINF:6.000,
ts_h264_baseline_360p_600_2.ts
#EXTINF:6.000,
ts_h264_baseline_360p_600_3.ts
#EXTINF:6.000,
ts_h264_baseline_360p_600_4.ts
```

network ts_h264_baseline_360p_600_1.ts success but TS file stop before ts_h264_baseline_360p_600_2.ts with error 6001. and license server can't receive license request.

when I use DASH + MP4, HLS+MP4, it works.

**Comment by lys1737** [comment]
&nbsp;manifests&nbsp;URL:
TS:&nbsp;&nbsp;https://47.115.7.64:8081/drm/video/encrypt/hls_ts_test/0c76ad23f83543e69b738d15bf9591e4_hls_test.m3u8
fMP4:&nbsp;&nbsp;https:///47.115.7.64:8081/drm/video/encrypt/hls_m4s_aes_test/0c76ad23f83543e69b738d15bf9591e4_hls_test.m3u8




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "google/shaka-player"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月13日(星期五) 凌晨2:19
收件人:&nbsp;"google/shaka-player"<shaka-player@noreply.github.com&gt;;
抄送:&nbsp;"296343318"<296343318@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [google/shaka-player] use Widevine + HLS + MPEG-TS to protected, but can't playback video with error 6001 (#2981)





 
Could you provide a sample manifest URL (not the text)?
 
My guess is that we don't convert the MIME type from TS to MP4 when checking EME support.  Normally we transmux the TS to MP4 before passing to the browser.  We need to convert the TS MIME type to MP4 before checking if the browser supports it.  I know we do this for MediaSource, but it looks like we don't do that in DrmEngine.

**Comment by joeyparrish** [comment]
We'll work on a fix.  Thanks!

**Comment by joeyparrish** [comment]
Also, big thanks to @TheModMaker for pointing out the root cause.  Such a huge help!

**Comment by nnarhinen** [comment]
Hello! I have a customer case where this happens even with a fresh master build. Is there a way to reach out to you privately to share a demo?

**Comment by TheModMaker** [comment]
Please file a new issue and follow the instructions in the bug template.  There will be an email you can send it to.  Please provide a playable manifest URL and not just manifest text or a segment.
