### ISSUE TITLE
Opening settings menu with keyboard doesn't show settings

### ISSUE THREAD

**Issue by TheModMaker** [google/shaka-player#2986]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
Nightly (v3.0.5-master-44-gebb1e34b)

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Hosted demo

**If custom app, can you reproduce the issue using our demo app?**
N/A

**What browser and OS are you using?**
Chrome on Mac

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
N/A

**What did you do?**
- Use Tab and Shift-tab to navigate to settings menu (gear icon).
- Hit Enter

**What did you expect to happen?**
Settings menu open and shows settings.

**What actually happened?**
Menu opened, but is empty.  If I click the menu, it shows settings correctly.

**Comment by joeyparrish** [comment]
There is probably some event other than click which needs to be used to act when the menu is opened.
