### ISSUE TITLE
Shaka does not autoplay when the stream starts with a gap

### ISSUE THREAD

**Issue by lemonwhale** [google/shaka-player#2987]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.5

**Can you reproduce the issue with our latest release version?**
Yes, 3.0.5 is the latest I can find

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Yes, both

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Mac OS 10.15.6 and Chrome. 

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
n/a

**What are the manifest and license server URIs?**
manifest (not encrypted)
"https://lbs-usp-dash-live.cmore.se/group05/debug/live.isml/.mpd?t=2020-11-12T12%3A30%3A00.000-2020-11-12T12%3A45%3A00.000"

**What did you do?**
I start playing it in your demo player and in my own player respectively. Hence, we have jumpLargeGaps = true

**What did you expect to happen?**
I expect the stream to start playing in the demo player, since other streams we have autoplay in the very same player. If we press play the stream starts. In my own player, I notice that the "canplaythrough" event, is not dispatched, and we use this to enable video controls. So our own player is not possible to start.

**What actually happened?**
In the demo player, the stream had to be manually started. In my own player, the controls are never visible. If there is another event from shaka to indicate that the player is ready, I am happy to change canplaythrough to that event, to solve this issue.

**Comment by joeyparrish** [comment]
@lemonwhale, I was just informed by email that this is working in dash.js.  For comparison, and to help us debug, can you please try this stream in dash.js and Shaka Player and compare the buffered ranges presented in each?

```js
const b = videoElement.buffered;
console.log('Buffered ranges: ' + b.length);
for (let i = 0; i < b.length; ++i) { console.log(b.start(i) + ' - ' + b.end(i)); }
```

**Comment by dirk-unified** [comment]
Hi Joey,

Two screenshots as I do not have player versions where I easily can insert code, I hope this helps.

- dashjs (with debug info / buffer length)

![dashjs](https://autoplay-gap.s3.eu-central-1.amazonaws.com/dashjs.png)

- shake (which shows video length of 15:03, download of fragments but no play)

![shaka](https://autoplay-gap.s3.eu-central-1.amazonaws.com/shaka.png)

**Comment by joeyparrish** [comment]
Can you run the following code in the JS console with both players?  You don't need to insert code into the player itself.  This will tell us what the buffered ranges are for the two players, which will help us understand the difference between them.

```js
const b = videoElement.buffered;
console.log('Buffered ranges: ' + b.length);
for (let i = 0; i < b.length; ++i) { console.log(b.start(i) + ' - ' + b.end(i)); }
```

**Comment by dirk-unified** [comment]
Hi Joey,

The videoElement seems undefined



Please run the code your mention on this url

 https://lbs-usp-dash-live.cmore.se/group05/debug/live.isml/.mpd?t=2020-11-12T12%3A30%3A00.000-2020-11-12T12%3A45%3A00.000 <https://lbs-usp-dash-live.cmore.se/group05/debug/live.isml/.mpd?t=2020-11-12T12:30:00.000-2020-11-12T12:45:00.000>

Kind regards,

Dirk

**Comment by joeyparrish** [comment]
I should have been more specific about the video element.  That's whatever the actual video element is, not a literal variable I expect to be predefined.

If there's only one video element on the page, this should do it:

```js
const videoElement = document.querySelector('video');
```

**Comment by dirk-unified** [comment]
Hi Joey,


All I see is ‘undefined’ - which seems the result of the expression (as I find online, ‘console.log(‘hello’) also gives ‘undefined’ but with ‘hello’ as ’side-effect’)

Same happens in Dash.js, 

Can you not yourself paste the url in the player?

 https://lbs-usp-dash-live.cmore.se/group05/debug/live.isml/.mpd?t=2020-11-12T12%3A30%3A00.000-2020-11-12T12%3A45%3A00.000 <https://lbs-usp-dash-live.cmore.se/group05/debug/live.isml/.mpd?t=2020-11-12T12:30:00.000-2020-11-12T12:45:00.000>

Kind regards,

Dirk

**Comment by dirk-unified** [comment]
![skaka2](https://autoplay-gap.s3.eu-central-1.amazonaws.com/shaka2.png)

Same happens in Dash.js, 

![dashjs2](https://autoplay-gap.s3.eu-central-1.amazonaws.com/dashjs2.png)

**Comment by lemonwhale** [comment]
Sorry for being absent in the conversation, been working on other stuff. Thanks both of you for looking at this. I will try the suggestion above.

**Comment by lemonwhale** [comment]
For Shaka player: 
Buffered ranges: 1
1.996 - 63.996

**Comment by lemonwhale** [comment]
For Dash.js
Buffered ranges: 1
1.996 - 23.996

**Comment by lemonwhale** [comment]
@joeyparrish Did you see the logs above?

**Comment by dirk-unified** [comment]
Hi Joey, Any news on this?

**Comment by ismena** [comment]
Hi gentlemen, sorry for the delay!

@TheModMaker Can I drag you into this as a gap expert, if you have some time?

@dirk-unified @lemonwhale if both our gap experts are too busy (as in - if there's no news on this in the next few days), please feel free to ping me next week. It'll be a little slower as I'm not as familiar with our gap logic, but I'll do my best! :)

**Comment by joeyparrish** [comment]
I believe I've found a bug in the GapJumpingController component that has been there since the beginning.  I believe I have a fix that makes autoplay work correctly on this content.

In essence, we don't want to jump ahead while paused.  But when playback starts, the video is automatically in a "paused" state.  With `autoplay` set on the video, as soon as we jump ahead to the first buffered range, playback starts.  So the fix is to allow jumping ahead if we're paused at time 0, but not paused elsewhere.

**Comment by lemonwhale** [comment]
Awesome. That sounds very promising. Any rough estimate when we can get this fix for test and production?

**Comment by joeyparrish** [comment]
The fix got held up in code review, but it just landed in the master branch.  I should be able to push out a v3.0.9 some time next week.
