### ISSUE TITLE
Building fails on Windows 10 through Git Bash with 3.0.6

### ISSUE THREAD

**Issue by radiantmediaplayer** [google/shaka-player#2988]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.6

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
N/A

**If custom app, can you reproduce the issue using our demo app?**
N/A

**What browser and OS are you using?**
Latest Windows 10 

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
N/A

**What did you do?**
git clone https://github.com/google/shaka-player.git
git checkout -b rmp-shaka-3.0.6 v3.0.6
python build/build.py +@networking +@manifests +@text +./node_modules/eme-encryption-scheme-polyfill/index.js +./lib/polyfill/encryption_scheme.js +./lib/polyfill/input_event.js +./lib/polyfill/mathround.js +./lib/polyfill/mediasource.js +./lib/polyfill/patchedmediakeys_ms.js +./lib/polyfill/patchedmediakeys_nop.js +./lib/polyfill/patchedmediakeys_webkit.js +./lib/polyfill/videoplaybackquality.js +./lib/polyfill/vttcue.js

The above commands that did not fail with Shaka player 3.0.5 is now producing an error output with 3.0.6. Note that files in dist/ folder are produced but I want to make sure they are usable. Same issue if adding the --debug flag.

> Traceback (most recent call last):
>   File "build/build.py", line 388, in <module>
>     shakaBuildHelpers.run_main(main)
>   File "C:\wamp64\www\shaka-player\build\shakaBuildHelpers.py", line 353, in run_main
>     sys.exit(main(sys.argv[1:]))
>   File "build/build.py", line 381, in main
>     if not custom_build.build_library(name, locales, force, is_debug):
>   File "build/build.py", line 308, in build_library
>     if not ts_def_generator.generate(force):
>   File "C:\wamp64\www\shaka-player\build\compiler.py", line 249, in generate
>     if shakaBuildHelpers.execute_get_code(cmd_line) != 0:
>   File "C:\wamp64\www\shaka-player\build\shakaBuildHelpers.py", line 161, in execute_get_code
>     obj = execute_subprocess(args)
>   File "C:\wamp64\www\shaka-player\build\shakaBuildHelpers.py", line 150, in execute_subprocess
>     return subprocess.Popen(args, **kwargs)
>   File "C:\Python38\lib\subprocess.py", line 854, in __init__
>     self._execute_child(args, executable, preexec_fn, close_fds,
>   File "C:\Python38\lib\subprocess.py", line 1307, in _execute_child
>     hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
> OSError: [WinError 193] %1 is not a valid Win32 application

**What did you expect to happen?**
No error

**What actually happened?**
Error

**Comment by TheModMaker** [comment]
The problem is [this line](https://github.com/google/shaka-player/blob/c33dd7e95ceb11c94c475f4ce0bb45a77466f76b/build/compiler.py#L244) where we try to execute a Python file.  We need to use `sys.executable` to invoke Python instead of the file itself.
