### ISSUE TITLE
How I can Install shaka player on Lg WebOS smart tv

### ISSUE THREAD

**Issue by amanpoplify** [google/shaka-player#2991]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

**What version of Shaka Player are you using?**

**Please ask your question**

**Comment by theodab** [comment]
Shaka Player is a browser-based API. We should be able to play on any browser that supports the APIs we are based on; we don't have a WebOS device to test on ourselves, but our users have verified that it works (see issue #1330). Anyway, it's not something you need to install, per se, more something that is loaded by a website.
You can consult [our getting-started guide](https://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html) if you want to learn how to use Shaka Player in your website.

**Comment by amanpoplify** [comment]
Yes, please close this issue :)

**Comment by theodab** [comment]
If you have any further questions, feel free to ask.
