### ISSUE TITLE
Put URIs into text track objects.

### ISSUE THREAD

**Issue by Faizranas** [google/shaka-player#2994]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

**What link can we use to reproduce this?**
https://shaka-player-demo.appspot.com/demo/#audiolang=en-GB;textlang=en-GB;uilang=en-GB;panel=HOME;build=uncompiled

**What version of Shaka Player are you using?**
v2.5.11-compiled

**What browser and OS are you using?**
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36

**What did you do?**
getTextTrack() OR getManifest() not returning text/vtt URIs which comes with in MPD file.

**What did you expect to happen?**
How to get VTT URI from shaka player API? Is there any API or way to get web VTT URI on language basis. I want to fetch that URI for analytics purpose. 

**What actually happened?**
getManifest() OR getTextTrack() API not giving web vtt uri.

**Comment by theodab** [comment]
At the moment, you could get it out of the `segmentIndex` property inside the individual text streams.
```js
// Generate the segment index, if it has yet to be generated.
await textStream.createSegmentIndex();
// Get the URIs of the first reference inside the first segment index.
const uris = textStream.segmentIndex.references[0].getUris();
```
However, this method relies on some internal implementation details that we can't guarantee will remain stable between releases. So, while this would technically work, it's not recommended.

Instead, I'll make a CL that puts this information into the text tracks, in a more stable manner.

**Comment by Faizranas** [comment]
It will be really great if you add URIs in text track Object in upcoming release.
Thanks for your suggestion. It is working in the latest build.

**Comment by joeyparrish** [comment]
> Instead, I'll make a CL that puts this information into the text tracks, in a more stable manner.

I am concerned about this, since a track in v3 can be comprised of many URIs in multi-period content, one per period.

As far as I can tell, the best way to explore the content's properties in unsupported ways is through the manifest interface.

> Your suggested approach is working fine with uncompiled debug 3.0.6 version but it is not working with compiled version. Why it is like that. Please suggest.

In what way is it not working?  Can you be more specific?  Thanks!

**Comment by joeyparrish** [comment]
We discussed a bit internally, and this seems like something we are not willing to commit to supporting in Shaka Player at this time.  It doesn't fit our streaming model in v3, in which a DASH track can be composed of multiple Representations across periods, and an HLS track can be composed of many segments with or without discontinuities.

If you want to do some analytics on text tracks, I would suggest using track metadata like language, role, ID, etc. if you can.  If you absolutely need the URI, and you know you only have one period or no discontinuities, then the getManifest() API is the thing to use.

With getManifest(), you have to accept a small amount of risk in that we could make changes to the structure between minor release versions (such as v3.0 to v3.1).  But I don't anticipate any changes that would impact you getting a segment URI for a certain track.

With that said, if there's something wrong with the code snippet provided by @theodab, please let us know what's wrong (error message, etc) and we'll help fix it.  Thank you!

**Comment by Faizranas** [comment]
Thank you Joey Parrish for your response. It will be good to add these VTT URIs in upcoming release in track Object or any new Object with text track language if it doesn't break your streaming model.  You understand your structure far better than us so It is up to you how to plan it further. Yes, @theodab suggested code was working fine in 3.0.6 debug version but the same code was throwing error in compiled minified version. I further investigated the code and observed that the reference of object property has changed in compiled version code.  Now, I am getting URI in the following method in the compiled version
**textStream[0].segmentIndex.a[0].c()**

It is fine for debug version **const uris = textStream.segmentIndex.references[0].getUris();**

textStream[0].segmentIndex
U {a: Array(1), b: null, c: 0}
textStream[0].segmentIndex.a[0]
Uf {startTime: 0, endTime: 888.053, b: 0, a: null, c: ƒ, …}a: nullappendWindowEnd: 888.053appendWindowStart: 0b: 0c: ƒ ()arguments: nullcaller: nulllength: 0name: ""prototype: {constructor: ƒ}__proto__: ƒ ()[[FunctionLocation]]: shaka.js:219[[Scopes]]: Scopes[5]endTime: 888.053f: nullstartTime: 0timestampOffset: 0__proto__: Object
textStream[0].segmentIndex.a[0].c()
["https://storage.googleapis.com/shaka-demo-assets/sintel-widevine/s-dut.webvtt"]

Thank you very much for your help and prompt response. We can use this approach for now.

**Comment by joeyparrish** [comment]
Sorry for failing to respond to this in a timely manner.

`segmentIndex.references` is not a public field, which is why it does not appear in a debug build.

I hope this helps to clarify.
