### ISSUE TITLE
Yet another CORS issue despite AWS config 😔

### ISSUE THREAD

**Issue by HandsomeMedia** [google/shaka-player#2995]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yep

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yep

**What version of Shaka Player are you using?**
3.0.5

**Please ask your question**
Any tips on getting the player to work on localhost?  I tried pulling all the AWS access-control levers I could, and even attempted localhost on SSL.  Wondering if there's a setting within Shaka to help me cross the finish line?

The player appears to work as expected in prod.

I usually get 4 each of the following errors:

`Access to fetch at 'https://mydomain.tv/Pro_Res_1.26.19.mpd' from origin 'http://localhost:8089' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

`shaka-player.ui.js:formatted:15046 GET https://mydomain.tv/Pro_Res_1.26.19.mpd net::ERR_FAILED`

Headers:
<img width="917" alt="Screen Shot 2020-11-18 at 10 19 28 AM" src="https://user-images.githubusercontent.com/14863500/99571540-48e21800-2988-11eb-964a-2c61e108fcb9.png">

Thanks in advance for the help 🙌

**Comment by HandsomeMedia** [comment]
Just re-reading my own question and brainstorming here -- thanks for coming along for the ride:

I notice that `Access-Control-Allow-Origin` is absent from the Response Headers, despite me setting them in AWS.  I wonder if the issue is with Cloudfront not sending them in the response?  Is that the smoking gun: to see `Access-Control-Allow-Origin: localhost` or similar in the Response Headers?

**Comment by joeyparrish** [comment]
The browser will follow the directives of the response headers it receives.  So I would check into Cloudfront on that.  If you want access to be allowed from anywhere, set Access-Control-Allow-Origin to `*`.

**Comment by HandsomeMedia** [comment]
Revisiting the same link without doing anything, I'm now seeing the proper `Access-Control-Allow-Origin` headers sporadically.  This seems to be an issue with Cloudfront cache -- maybe my invalidation didn't apply to response headers 🤷‍♂️ 

Thanks @joeyparrish for the assistance.

**Comment by joeyparrish** [comment]
Glad we could help!
