### ISSUE TITLE
Shaka Error 2008 when switching multi-language CC

### ISSUE THREAD

**Issue by slukowsky** [google/shaka-player#2996]
**Have you read the FAQ and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v2.5.16 and v3.0.4

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from master?**
N/A

**Are you using the demo app or your own custom app?**
Demo App and Chromecast Receiver

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Chromecast

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**
Provided to Andres Gomez at Google

**What did you do?**
Load the content, select a subtitle language. Switch to another subtitle language several times during playback.

**What did you expect to happen?**
The subtitles are able to be switched between languages as many times as needed.

**What actually happened?**
The subtitles are able to switch a couple of times but after enough attempts the shaka error 2008 appears:
mp4_vtt_parser.js:114 No init segment for MP4+VTT!
streaming_engine.js:1793 (text:2) failed fetch and append: code=2008

**Comment by joeyparrish** [comment]
I believe we fixed this in v2.5.19 and v3.0.7 (in commits 3ad70b4e02a2ce6771d4125bb7b55abaca77c8b0 and e40cdd0f9d8801bc8915c0b616ed540cb316d0b3).

Please try these new releases.  If you need to reopen this issue, just put `@shaka-bot reopen` in a comment.  Thanks!
