### ISSUE TITLE
Incorrect version number in player.js

### ISSUE THREAD

**Issue by allenevans** [google/shaka-player#30]
player.js still reports as v1.2.0

Line 118:
goog.define('GIT_VERSION', 'v1.2.0-debug');

This should be v1.2.1.

**Comment by joeyparrish** [comment]
Whoops!

This bug affects both the v1.2.1 tag in github and the 1.2.1 release on npm.

Both show up as v1.2.0-debug in uncompiled mode.  The npm release reports as v1.2.0-13-gfd26657, while the github release reports as v1.2.0-12-g77b7c7e.

**Comment by joeyparrish** [comment]
1. removed v1.2.1 from npm (since we can't change it)
2. tightened up our release procedures and added some scripting to help us catch these problems before release
3. published v1.2.2 on both github and npm with all of the version numbering fixed
