### ISSUE TITLE
Where is The compiled version !

### ISSUE THREAD

**Issue by balbarak** [google/shaka-player#3001]
Hello, Guys

Thanks for the awesome project. 

I cannot find the destination files 

Do I have to install python !!!?? in order to build the project !!!

**Comment by TheModMaker** [comment]
You can use the pre-built versions on [NPM](https://www.npmjs.com/package/shaka-player), [JSDelivr](https://www.jsdelivr.com/package/npm/shaka-player), or [Google hosted libraries](https://developers.google.com/speed/libraries/#shaka-player).  You can also follow #2738 where we intend to add these to the releases on GitHub too.  If you want to built it yourself, you need Python, Node/NPM, and  Java.

**Comment by balbarak** [comment]
@TheModMaker Thanks for the answer

@shaka-bot  yes close it
