### ISSUE TITLE
How to get video analytics from shaka player

### ISSUE THREAD

**Issue by kesavkolla** [google/shaka-player#3007]
I'm trying to get some video analytics about how much time user has spend in watching video, what is the average bitrate specially with adaptive playback is on, whether user watched in fullscreen vs normal etc...

Is there any way to get this sort of analytics from the player?

**Comment by michellezhuogg** [comment]
Hello @kesavkolla ,

You can see statistics and info about the current video playback via [player.getStats()](https://nightly-dot-shaka-player-demo.appspot.com/docs/api/shaka.extern.html#.Stats) , however that may not contain all the info you are looking for.
