### ISSUE TITLE
TTML subtitles - ttp:tickRate is ignored

### ISSUE THREAD

**Issue by Karmel0x** [google/shaka-player#3009]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
3.0.6 (latest) release and master

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `master`?**
yes

**Are you using the demo app or your own custom app?**
both

**If custom app, can you reproduce the issue using our demo app?**
yes

**What browser and OS are you using?**
Firefox 83.0 (latest) / Chrome 87.0 (latest)

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**
https://gist.githubusercontent.com/Karmel0x/fc4b648a69ca999a3a2e3ae3c3fd914e/raw/c2df87918308bcf5dbd0d9b225242c7cf4fd8208/wwww.mpd

**What did you do?**
Go to this link and choose english captions: [demo link](https://shaka-player-demo.appspot.com/demo/#audiolang=pl;textlang=pl;uilang=pl;asset=https://gist.githubusercontent.com/Karmel0x/fc4b648a69ca999a3a2e3ae3c3fd914e/raw/c2df87918308bcf5dbd0d9b225242c7cf4fd8208/wwww.mpd;panel=HOME;build=compiled)

**What did you expect to happen?**
([subtitles link](https://gist.githubusercontent.com/Karmel0x/f698630a87b0fbb0755f81055b262711/raw/027fca1e2c04b3fe5e454ebefdbf736a1f9e9705/qqqq.ttml)) tickRate is set to 10, subtitles are on 10t and 30t
so subtitles should appear on 1 second and 3 second

**What actually happened?**
Subtitles appears on 10 second and 30 second

**Comment by Karmel0x** [comment]
Probably it's bad solution but it's fixing the problem using this trick:

At https://github.com/google/shaka-player/blob/master/lib/text/ttml_text_parser.js#L87 insert this piece of code:
```
ttpNs = tt.attributes.find(element => element.value.indexOf('#parameter') != -1)?.value || ttpNs;
```

**Comment by joeyparrish** [comment]
It seems that the root cause is your TTML using a different namespace URI than what we are expecting.  Can you give us any context on that?

If you load the namespace URIs in your browser, you'll see the following:

https://www.w3.org/ns/ttml/
> This is a placeholder for a namespace document that permits dereferencing the Timed Text Markup Language (TTML) 1.0 namespace URIs:
> 
> ...
> 
> This namespace is **stable!**

https://www.w3.org/2006/10/ttaf1/
> This is a placeholder for a namespace document that permits dereferencing the Timed Text (TT) Authoring Format V1.0 Distribution Format Exchange Profile namespace URIs:
> 
> ...
> 
> This namespace is **not stable**!

Is TTAF a predecessor to TTML?

**Comment by Karmel0x** [comment]
You can check provided links with demo or subtitles.
It's ttaf1
