### ISSUE TITLE
Emit error when the wrong keys are retrieved

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#301]
We don't currently detect if the wrong keys are retrieved.  In this scenario, a license has been requested and retrieved, but the license does not contain the keys that the browser needs to decode the content.

We could detect this in many cases and emit an error.  During integration and debugging, this would help point out issues with the license server/proxy.

**Comment by joeyparrish** [comment]
I believe this would involve two events, `waitingforkey` and `canplay`, to enter and exit the "waiting on keys" state, respectively.  Needs investigation to confirm.

**Comment by ddorwin** [comment]
Do you want to detect the wrong key based on ID or the actual key? In the latter case, you may just get a decode error.

**Comment by joeyparrish** [comment]
We're already able to detect decode errors, but in cases where we have the wrong key IDs for the content, we currently just wait forever.  This happens sometimes during early app development due to mistakes in the player configuration or the license server.

If we can detect this, we can save people debugging time and effort.
