### ISSUE TITLE
Test HLS+TS(widevine) again After 2981 fixed, playback failed with error 3016.

### ISSUE THREAD

**Issue by lys1737** [google/shaka-player#3010]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v3.1.0-pre (uncompiled) 

**Please ask your question**

After bug https://github.com/google/shaka-player/issues/2981 fixed， I use v3.1.0-pre (uncompiled) demo test HLS+TS again，
add manifestUri、licenseServer in demo/common/assets。
```
new ShakaDemoAssetInfo(
      /* name= */ 'Widevine HLS TS Test',
      /* iconUri= */ 'https://storage.googleapis.com/shaka-asset-icons/art_of_motion.png',
      /* manifestUri= */ '***',
      /* source= */ shakaAssets.Source.BITCODIN)
      .addKeySystem(shakaAssets.KeySystem.WIDEVINE)
      .addFeature(shakaAssets.Feature.HLS)
      .addFeature(shakaAssets.Feature.MP2TS)
      .addFeature(shakaAssets.Feature.HIGH_DEFINITION)
      .addFeature(shakaAssets.Feature.OFFLINE)
      .addLicenseServer('com.widevine.alpha', '***'),
```

widevine drm get license success ，After all ts file  download it playback fail with 3016。 Is  my  config  error in demo ?

main.js:1674 shaka.util.Error {severity: 2, category: 3, code: 3016, data: Array(3), handled: false, …}
Shaka Error MEDIA.VIDEO_ERROR (4,,DEMUXER_ERROR_COULD_NOT_OPEN: MediaSource endOfStream before demuxer initialization completes (before HAVE_METADATA) is treated as an error. This may also occur as consequence of other MediaSource errors before HAVE_METADATA.)

**Comment by lys1737** [comment]
chrome version: 83.0.4103.106

**Comment by lys1737** [comment]
shaka.util.Error {severity: 2, category: 3, code: 3016, data: Array(3), handled: false, …}
category: 3
code: 3016
data: (3) [4, undefined, "DEMUXER_ERROR_COULD_NOT_OPEN: MediaSource endOfStr…of other MediaSource errors before HAVE_METADATA."]
handled: false
message: "Shaka Error MEDIA.VIDEO_ERROR (4,,DEMUXER_ERROR_COULD_NOT_OPEN: MediaSource endOfStream before demuxer initialization completes (before HAVE_METADATA) is treated as an error. This may also occur as consequence of other MediaSource errors before HAVE_METADATA.)"
severity: 2
stack: "Error: Shaka Error MEDIA.VIDEO_ERROR (4,,DEMUXER_ERROR_COULD_NOT_OPEN: MediaSource endOfStream before demuxer initialization completes (before HAVE_METADATA) is treated as an error. This may also occur as consequence of other MediaSource errors before HAVE_METADATA.)↵    at new shaka.util.Error (http://127.0.0.1:5500/lib/util/error.js:97:17)↵    at shaka.Player.videoErrorToShakaError_ (http://127.0.0.1:5500/lib/player.js:4972:12)↵    at shaka.Player.onVideoError_ (http://127.0.0.1:5500/lib/player.js:4984:24)↵    at HTMLVideoElement.onError (http://127.0.0.1:5500/lib/player.js:1223:39)"
__proto__: Object

**Comment by joeyparrish** [comment]
Sorry for the long delay in our reply.

Without a content URL, it would be hard to say what is wrong.  Error 3016 is a decoder error, so the browser doesn't like something about your content.  I would suggest you use chrome://media-internals/ to get more information.

Also, without an accessible content URL, we can't do anything more than guide you in your own investigations.
