### ISSUE TITLE
TTML span within a span has its text decoration ignored

### ISSUE THREAD

**Issue by dhmmNagra** [google/shaka-player#3012]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v3.0.6

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Both

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Win & Mac
Chrome v87, Firefox v83, Edge v87

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
https://dash.akamaized.net/dash264/CTA/imsc1/IT1-20171027_dash.mpd

**What did you do?**
1. Play this stream
1. Enable the English subtitle stream
1. Seek to 2m38s.
1. Observe the subtitles until approx 2m52s

**What did you expect to happen?**
The words `Blue UL` should be in blue and __underlined__.

**What actually happened?**
All text white, without any text decoration.

(CSS placement adjusted screenshot to show issue)
![image](https://user-images.githubusercontent.com/75128117/100456775-d45e5600-30b8-11eb-850e-fc492d04320b.png)

XML snippet:
![image](https://user-images.githubusercontent.com/75128117/100457011-28693a80-30b9-11eb-9998-b4479f3bfd4e.png)

> Note the whitespace missing between `The`,  `Blue UL`  and `Mid-Row Code` is actually a side effect of a separate issue: #3011

**Comment by dhmmNagra** [comment]
Note our custom player's Text Displayer overcomes other basic styling issues observed in the Shaka Demo App.

**Comment by michellezhuogg** [comment]
Hello @dhmmNagra ,

Displaying nested cues with the text decorations has been fixed in the [nightly demo app](https://nightly-dot-shaka-player-demo.appspot.com/demo/#audiolang=es;textlang=es;uilang=en;asset=https://dash.akamaized.net/dash264/CTA/imsc1/IT1-20171027_dash.mpd;panel=CUSTOM%20CONTENT;build=uncompiled).
Let us know if you're still seeing the wrong behavior. Thank you!

**Comment by dhmmNagra** [comment]
Hi @michellezhuogg 
This nightly build is good and solves the issues reported here... thanks very much!
I'll close this issue as it looks like the solution to #2761 is the answer here too.
cheers
Dave
