### ISSUE TITLE
Unnecessary background coverage due to TTML `br` handling within `span`

### ISSUE THREAD

**Issue by dhmmNagra** [google/shaka-player#3013]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
v3.0.6

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Both

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Win & Mac
Chrome v87, Firefox v83, Edge v87

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
http://rdmedia.bbc.co.uk/dash/ondemand/elephants_dream/1/client_manifest-all.mpd

> Note I do not know of a https hosted variant of this stream, so appropriate localhost playback or otherwise will be required.

**What did you do?**
1. Play this stream
1. Enable the English subtitle stream
1. seek to 4m31s
1. Observe the solid background of the text

**What did you expect to happen?**
The black background would wrap the text only.

**What actually happened?**
The black background would not be covering unnecessary portions of video i.e. a single background covers all lines of text as they are treated as one `span`.

![image](https://user-images.githubusercontent.com/75128117/100457879-bc87d180-30ba-11eb-8fdf-38b26005a6fa.png)

My initial analysis is that the treatment of the `<br>` tag within the middle of the `span` should cause the separation of the lines to separate spans so their background colour can will be around just the words and not squared off.
```javascript
            <p begin="00:04:30.80" end="00:04:34.68" xml:id="sub37">
                <span style="s1">Pulp Emo!<br/>Is that what you want? Pulp?</span>
            </p>
```

**Comment by michellezhuogg** [comment]
Hello @dhmmNagra ,

Sorry for our late reply. Would you please provide us a manifest link with https? Thank you!

**Comment by joeyparrish** [comment]
@michellezhuogg, in the original post, @dhmmNagra says:

> Note I do not know of a https hosted variant of this stream, so appropriate localhost playback or otherwise will be required.

You can use your localhost version of the Shaka Player demo to play this http link.
