### ISSUE TITLE
`lowLatencyMode` is not recognized as a valid configuration parameter 

### ISSUE THREAD

**Issue by agconti** [google/shaka-player#3014]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
I'm using v3.0.6 from https://cdn.jsdelivr.net/npm/shaka-player@3.0.6/dist/shaka-player.compiled.min.js

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes. I tried doing this by using this shaka player source: `https://nightly-dot-shaka-player-demo.appspot.com/shaka-player.uncompiled.js`. Please let me know if this is the correct approach. 

**Are you using the demo app or your own custom app?**
Custom app.

**If custom app, can you reproduce the issue using our demo app?**
The demo app does not allow me to update the player configuration settings, as far as I'm aware. So I cannot reproduce this issue there. 

**What browser and OS are you using?**
Browser:  86.0.4240.198 
OS: OSX, 10.14.5

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

https://akamaibroadcasteruseast.akamaized.net/cmaf/live/657078/akasource/out.mpd

**What did you do?**

Here's a public codepen that reproduces the issue: https://codepen.io/agconti/pen/abmzJKo.

I added the lowLatencyMode configuration as [prescribed](https://github.com/google/shaka-player/blob/master/docs/tutorials/config.md#low-latency-streaming) by the docs, but I see the following error in the console.

Configuration:
```js
player.configure({
  streaming: {
    lowLatencyMode: true,
    inaccurateManifestTolerance: 0,
    rebufferingGoal: 0.01,
  }
});
```

Error:
```
"Invalid config, unrecognized key .streaming.lowLatencyMode"
```

**What did you expect to happen?**
I expected the player to recognize `lowLatencyMode` as a valid configuration key as the [docs](https://github.com/google/shaka-player/blob/master/docs/tutorials/config.md#low-latency-streaming) state.

**What actually happened?**
The console logged an error of:

```
"Invalid config, unrecognized key .streaming.lowLatencyMode"
```

I do not believe that the player is playing the stream back in lowLatencyMode either.

**Comment by michellezhuogg** [comment]
Hello @agconti ,

Low latency streaming features are not included in v3.0.6.
Currently, low latency streaming features can be tested with our nightly demo app https://nightly-dot-shaka-player-demo.appspot.com/demo/ , and will be launched in v3.1 soon.

Let us know if that helps!

**Comment by TheModMaker** [comment]
Also, using `shaka-player.uncompiled.js` from another site isn't supported.  You should really use a compiled bundle or compile locally and use a local version of `shaka-player.uncompiled.js`.  You could use <https://nightly-dot-shaka-player-demo.appspot.com/dist/shaka-player.ui.js>.

**Comment by agconti** [comment]
Thanks so much for your help @michellezhuogg and @TheModMaker! 💖 

I tried using the nightly build but still saw the same error logged to the console. Here's an updated codepen using the nightly build instead: https://codepen.io/agconti/pen/abmzJKo?editors=1011. 

Can you let me know where I'm going wrong?

**Comment by joeyparrish** [comment]
Your JS code is correct, but your codepen is configured to load "https://cdn.jsdelivr.net/npm/shaka-player@3.0.6/dist/shaka-player.compiled.min.js" explicitly, in addition to the script tag for the nightly build in your HTML.

**Comment by joeyparrish** [comment]
If you remove the explicit v3.0.6 build from your codepen config, the nightly build in your HTML script tag works correctly.

**Comment by agconti** [comment]
Thanks, @joeyparrish. I didn't realize I was loading `v3.0.6` in the external lib UI. I thought it was only it was only loading from the explicit script tags I had in the HTML section. Thanks for clearing this up. 💖 

I'll close the issue now since my question is resolved. 

Out of curiosity, when will do you think`v3.0.7` be released?

**Comment by joeyparrish** [comment]
When we fix a few more bugs compared to v3.0.6.  There are a few high priority issues we're working on.  If those go well this week, we could release v3.0.7 next week.

Is there something specific you're looking for in that release?

**Comment by agconti** [comment]
@joeyparrish thanks for the update! I assumed that this `lowLatencyMode` configuration option would be included in the next release since it's in the nightly build. Is that the case?

**Comment by joeyparrish** [comment]
No, it won't.  Low latency mode, as a new feature, will be in our next feature release, v3.1.  v3.0.7 will be bug fixes only on top of the v3.0.x release branch.  If you aren't familiar with the versioning scheme, we follow "semantic versioning": https://semver.org/

We aren't quite ready to release v3.1 until we fix a few lingering issues in the master branch and we're confident in its stability.

**Comment by agconti** [comment]
Ok, thank you for clarifying! 💖

**Comment by joeyparrish** [comment]
Happy to help!
