### ISSUE TITLE
Can't chromecast from iOS Safari

### ISSUE THREAD

**Issue by Forium777** [google/shaka-player#3015]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.6

**Please ask your question**
I tried to cast to a chromecast from shaka-player on iOS 13 & 14 Safari but there is no "Cast" option in the 3-dot menu (kebab menu). Note that I tried the demo compiled I got the same result.

Tried on iOS 13 & 14.

**Comment by matvp91** [comment]
Safari does not support Chromecast natively. On iOS, providing cast functionality can only be through apps that have the Cast Sender SDK implemented.

**Comment by TheModMaker** [comment]
Chromecast doesn't support iOS Safari.  We need to use the Chromecast SDK, which only supports Chrome.  It also seems that you can't use it on Chrome on iOS either.  If you need Chromecast on iOS, you need to create a native app.  See the [Chromecast docs](https://developers.google.com/cast/docs/developers) for more info.
