### ISSUE TITLE
Error when compiling the demo folder

### ISSUE THREAD

**Issue by Asha-Aradhya** [google/shaka-player#3017]
**What version of Shaka Player are you using?**
3.0.x

**Please ask your question**
I have added few more project related folders inside the "shaka-player/demo" folder and tried to run the build/all.py. While I managed to escape the linting(intentionally) errors unable to understand/fix the compile errors. 

For ex: ERROR - [JSC_UNDEFINED_VARIABLE] variable sessionStorage is undeclared

There are many more such errors.

How do I fix this.

Thanks in Advance.

**Comment by joeyparrish** [comment]
If you modify our demo app by adding your own application sources, you're on your own.  It was never intended that you would throw your application sources into the demo folder.  Ideally, you would build your own app in your own way.

If your app is built with the Closure Compiler, you can use our generated extern files (in the dist/ folder) to reference the Shaka Player library in your app's build.

Does this help?
