### ISSUE TITLE
UITextDisplayer.append or Cue.equal is very slow, especially on Chromecasts

### ISSUE THREAD

**Issue by baseballbrad3** [google/shaka-player#3018]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** 
Yes

**What version of Shaka Player are you using?**
3.0.5 and 3.0.6

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Custom app

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Cast Sender: Chrome 87/Windows 10
Cast Receiver: Chrome 76/Chromecast Ultra

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Chromecast Ultra 1.42.183786 (User agent: `Mozilla/5.0 (X11; Linux aarch64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.81 Safari/537.36 CrKey/1.42.183786`)

**What are the manifest and license server URIs?**

I might be able to provide this via email, but if you have a title with lots of text track cue's (1,000+), I'd expect that to work the same.

**What did you do?**

1. Prior to casting, in the sender's Shaka player instance, select a text track. Alternatively, configure the Shaka player on the Cast receiver's configuration to `streaming.alwaysStreamText` to `true`.
1. Start the Cast session on a Chromecast (I'm using a Chromecast Ultra)
1. Wait between 30 seconds and 1 minute for playback to begin

Note that the longer the content (or one with more dialog), the worse this start up time seems to be. I'm testing on an action movie that has 1275 lines of dialog (basically I mean it's a VTT with 1275 `-->` occurrences).

**What did you expect to happen?**
The video to begin without waiting over 30+ seconds for the text track to parse.

**What actually happened?**

Basically any loading of text tracks on a Chromecast (weather it's selected prior to casting, changed while casting, or having `streaming.alwaysStreamText` to `true`) takes an unreasonably long time on text tracks of a movie length.

I'd assume this would impact non-Cast devices too. Running a performance profile on the debug Shaka demo site for the same content on my Chrome (a desktop Core i7, not the Cast Receiver) took ~600ms. 😬 An underpowered/older Android phone could take seconds (perhaps tens of seconds), but I don't have evidence of this.

Here's a screenshot of the performance tab of the receiver's inspect window after I switched text tracks. I did save Chrome's performance profile, if it's needed.
![chrome_2020-11-30_12-20-24](https://user-images.githubusercontent.com/644025/100648762-04029d80-3307-11eb-8805-44a3c1003ce1.png)

It looks like this this was introduced in [3.0.5](https://github.com/google/shaka-player/releases/tag/v3.0.5) with the changes made to `cue.js` and `array_utils.js`.

**Comment by bcupac** [comment]
the append function looks like this:
```
for (const cue of cues) {
      // When a VTT cue spans a segment boundary, the cue will be duplicated
      // into two segments.
      // To avoid displaying duplicate cues, if the current cue list already
      // contains the cue, skip it.
      const containsCue = this.cues_.some(
          (cueInList) => shaka.text.Cue.equal(cueInList, cue));
      if (!containsCue) {
        this.cues_.push(cue);
      }
    }
 this.updateCaptions_();
```
If external cc is loaded, and has 1000+ cues, shaka.text.Cue.equal will trigger millions of times.

One idea to solve this is to hash cues based on start/end times and then just compare those hashed values between each other. About 99% of 
hashes will contain just a single cue point, so the compare function will not trigger.

```
append(cues = []) {
		const hashedCues = new Map();

		// when using external Captions append is called only once, but when Captions are in the manifest
		// append is called multiple times as playback progresses and this.cues_ is filled in gradually.
		const mergedCues = [...this.cues_, ...cues];
		const normalizedCues = [];
		// When a VTT cue spans a segment boundary, the cue will be duplicated
		// into two segments.
		// To avoid displaying duplicate cues, we remove duplicate cues below.
		// from observation duplicates are most often found in manifest embedded captions.
		mergedCues.forEach(cue => {
			const alreadyHashedCues = hashedCues.get(`${cue.startTime}+${cue.endTime}`);
			if (!alreadyHashedCues) {
				hashedCues.set(`${cue.startTime}+${cue.endTime}`, [cue]);
			} else {
				hashedCues.set(`${cue.startTime}+${cue.endTime}`, [...alreadyHashedCues, cue]);
			}
		});

		hashedCues.forEach(c => {
			const tempComparisonCues = [];

			c.forEach(cue => {
				const containsCue = tempComparisonCues.some(tempCue => cueEqual(tempCue, cue));
				if (!containsCue) {
					tempComparisonCues.push(cue);
					normalizedCues.push(cue);
				}
			});
		});
		this.cues_ = normalizedCues;
		this.updateCaptions_();
	}

```
