### ISSUE TITLE
seek events: detect reason gap jump

### ISSUE THREAD

**Issue by llooz** [google/shaka-player#3019]
**What version of Shaka Player are you using?**
3.0.6

**Please ask your question**
Is there a way to detect that the seeking / seeked events sent by the video tag are caused by a seek executed by shaka-player for gap jumping?

I'm getting seeking / seeked events on some videos at the very beginning and I don't want to report them to the analytics.

e.g. with https://turtle-tube.appspot.com/t/t2/dash.mpd
```
(video:3) finished fetch and append [{"start":0.066733,"end":5.071737}]
Jumping forward 0.066733 seconds because of gap before start time of 0.066733
...
onHTMLMediaElementEvent_ Event {isTrusted: true, type: "seeking", target: video#video1,
...
(all): seeked: buffered seek: presentationTime=0.066733
```

**Comment by TheModMaker** [comment]
There is no way to detect it easily.  You could use `video.buffered` to see if there is a gap nearby.  A better solution may be to ignore the `seeking` event and just use a UI event instead to detect user seeks.  You may want to ignore other seeks too (e.g. seeks for falling outside the live window).
