### ISSUE TITLE
Support timeShiftBufferDepth value of zero

### ISSUE THREAD

**Issue by tdrews** [google/shaka-player#302]
The DASH spec. indicates that a particular segment, S, becomes available at
```
S_start = availabilityStartTime + (start time of Period) +
          (MPD start time of S) + (duration of S)
```
and ceases to be available at
```
S_end = S_start + (duration of S) + timeShiftBufferDepth
```
(note: these calculations may be affected by other parameters, e.g., `@suggestedPresentationDelay`).
This indicates that every segment is available for at least its duration.
In Shaka v1.0 we have issues when `timeShiftBufferDepth` is 0 (#296),
we should handle small `timeShiftBufferDepth` values in v2.0.

**Comment by joeyparrish** [comment]
Due to the complexity of implementation, we will not support timeShiftBufferDepth of zero.
