### ISSUE TITLE
TTML percentage of extent and origin scaled down unnecessarily

### ISSUE THREAD

**Issue by dhmmNagra** [google/shaka-player#3029]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
v3.0.6

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Both

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Win & Mac
Chrome v87, Firefox v83, Edge v87

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
https://dash.akamaized.net/dash264/CTA/imsc1/IT1-20171027_dash.mpd

**What did you do?**
1. Play this stream
2. Enable the English subtitle stream
3. Observe the subtitles throughout

**What did you expect to happen?**
The specific percentage `origin` and `extent` attributes are expected to be honoured for correct placement.

**What actually happened?**
Subtitles appear at top left and off screen.

![image](https://user-images.githubusercontent.com/75128117/100455869-5b123380-30b7-11eb-9a5a-55f3180d2fab.png)

If a percentage is specified then the `region` width and height apply the scaling unnecessarily.  Same issue exists for the `origin` just after.

https://github.com/google/shaka-player/blob/56bb045ff68325d6b9de7cb3d56265ce3162f164/lib/text/ttml_text_parser.js#L365

**Comment by michellezhuogg** [comment]
Hello @dhmmNagra , thank you for your report! Would you like to submit a PR for this?

**Comment by dhmmNagra** [comment]
Hi @michellezhuogg thanks for the opportunity, I am drafting a PR - I'm a first time contributor so there will be a delay whilst my employer sorts out the CLA signing.

**Comment by david-hm-morgan** [comment]
pull request drafted at https://github.com/google/shaka-player/pull/3044

**Comment by avelad** [comment]
I think that it was resolved with https://github.com/google/shaka-player/pull/3044 and https://github.com/google/shaka-player/commit/d3640d1da15b6470deebd663f3f771c03864ab66 so it could be closed, what do you think?

**Comment by david-hm-morgan** [comment]
Yes its all been wrapped up already
