### ISSUE TITLE
Unable to play encrypted mpegts HLS streams - error code 6001

### ISSUE THREAD

**Issue by nnarhinen** [google/shaka-player#3031]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

Yes

**What version of Shaka Player are you using?**

Latest master (and 3.0.6)

**Can you reproduce the issue with our latest release version?**

Yes

**Can you reproduce the issue with the latest code from `master`?**

Yes

**Are you using the demo app or your own custom app?**

Both

**If custom app, can you reproduce the issue using our demo app?**

Yes

**What browser and OS are you using?**

MacOS (Chrome and Firefox (latest))

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

Sent to email

**What did you do?**

I'm trying to play an Widevine encrypted HLS stream that uses mpegts fragments. The code is kinda copy-pasted from shaka player documentation:

```js
const manifestUri =
    '<in email>';

const licenseServerUri = '<in email>'

shaka.polyfill.installAll();

async function initPlayer() {
  const video = document.getElementById('player');
  const player = new shaka.Player(video);

  // Listen for error events.
  player.addEventListener('error', onErrorEvent);
  
  player.configure({
    drm: {
      servers: {
        'com.widevine.alpha': licenseServerUri
      }
    }
  });

  try {
    await player.load(manifestUri);
    console.log('The video has now been loaded!');
  } catch (e) {
    onError(e);
  }
}

function onErrorEvent(event) {
  // Extract the shaka.util.Error object from the event.
  onError(event.detail);
}

function onError(error) {
  // Log the error.
  console.error('Error code', error.code, 'object', error);
}

if (shaka.Player.isBrowserSupported()) {
  // Everything looks good!
  initPlayer();
} else {
  // This browser does not have the minimum set of APIs we need.
  console.error('Browser not supported!');
}
```

**What did you expect to happen?**
The stream to play.

**What actually happened?**

I get the same error as in here: https://github.com/google/shaka-player/issues/2981

<img width="719" alt="image" src="https://user-images.githubusercontent.com/265438/101403595-220b6780-38de-11eb-965c-8c68bd47e932.png">

**Comment by TheModMaker** [comment]
The problem is your content is multiplexed, i.e. you have both audio and video in the same segments.  Chrome is reporting that it doesn't support this with EME.  My guess is Widevine doesn't support multiplexed encrypted content.  You should try encoding your content with separate video and audio streams.
