### ISSUE TITLE
Way to change quality of the video using different links, not abr.

### ISSUE THREAD

**Issue by kovaletsyurii** [google/shaka-player#3035]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes.

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes, a few times.

**What version of Shaka Player are you using?**
3.0.4

**Please ask your question**

Hi there. I need to create something like custom ABR. It's because we store different videos quality at different links and they aren't concatenated in one manifest file. So I need to detect a current bitrate and approximately bitrate that client network can provide. Maybe someone have a ways or ideas how to do this?

**Comment by michellezhuogg** [comment]
Hello @kovaletsyurii ,

Thank you for reaching out!
Are the videos basically multiple manifests? 
If so, currently I am not sure there's a proper way to do this. We'll be able to pre-load multiple manifests once our [Preload API](https://github.com/google/shaka-player/issues/880) is implemented, and choose one of the manifests to start playback. 
Does this help?

**Comment by kovaletsyurii** [comment]
> Hello @kovaletsyurii ,
> 
> Thank you for reaching out!
> Are the videos basically multiple manifests?
> If so, currently I am not sure there's a proper way to do this. We'll be able to pre-load multiple manifests once our [Preload API](https://github.com/google/shaka-player/issues/880) is implemented, and choose one of the manifests to start playback.
> Does this help?

Yes it helps, thanks :)
