### ISSUE TITLE
Memory leak when creating segment references from a timeline

### ISSUE THREAD

**Issue by danylhebreux** [google/shaka-player#3038]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v3.0.6-master

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Both

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Chrome Version 87.0.4280.88 (Official Build) (x86_64) 
MacOS 11.0.1

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Chromecast (2nd generation)

**What are the manifest and license server URIs?**

**What did you do?**
Playing our Dash live stream that contains 90 minutes of buffer.

**What did you expect to happen?**
No buffering like v2.5.x version.

**What actually happened?**
We found the issue within our app with the latest Chromecast CAF receiver update (November 22, 2020) that use Shaka 3.0.x. With our live stream containing 90 minutes of buffer, we notice high level of buffering issue with our customer. 

![production-issue-caf3 0 085](https://user-images.githubusercontent.com/475632/101783824-bafdd680-3ac8-11eb-9d20-abbc5db4326f.png)

With some investigation, I found that Shaka player leak memory with Dash live manifest.
![shaka-demo-app-leak](https://user-images.githubusercontent.com/475632/101784016-f8626400-3ac8-11eb-9c93-21e7b73e504b.png)

Into my Chromecast receiver app, I logged the `usedJSHeapSize` and the heap size never stop growing.
```Javascript
09:49:15.562 Shaka test /// usedJSHeapSize: 97.607819 MB  /// lower usedJSHeapSize: 27.552935 /// higher usedJSHeapSize: 98.064532
09:49:15.564 Shaka test /// usedJSHeapSize increased 70 MB in 344 seconds since beginning of live playback session
```

It seems that we are not alone with this issue - https://issuetracker.google.com/issues/173897425

**Comment by Yuvalke** [comment]
Hi @joeyparrish, when this fix will be released?
It makes us crashes we would appreciate if it'll be released before the planned date.
Thanks!

**Comment by joeyparrish** [comment]
It has been cherry-picked for v3.0.7.  We're short-handed right now, on top of which we have holidays at the moment.  I will plan to release v3.0.7 in the week of January 5 at the latest.

**Comment by OrenMe** [comment]
Hi @joeyparrish, hope you all had great holidays! would you still be able to release a version this week?

**Comment by joeyparrish** [comment]
Yes.  I was doing test passes yesterday, and had some issues crop up with the v2.5 cherry-picks that I still 
need to resolve.

**Comment by OrenMe** [comment]
Thanks @joeyparrish, we ran some initial tests on the master branch from a week ago.
While it was extremely basic it shows the memory leak was indeed solved and basic playback operations are ok.

**Comment by joeyparrish** [comment]
Excellent!  Thanks for the update.

**Comment by Yuvalke** [comment]
Thanks @joeyparrish, when we saw the issue I tried to test with your master, I pulled the master and execute `python build/all.py --force`, used the generated dist and it worked well and still working on the master today.
Now, we're testing the 3.0.7 and I see leaking when I'm using webpack and mode=production, I haven't seen leaking when I tested it like I mentioned even if webpack in mode production. After few checks it seems like it come from minimize proccess in webpack but it didn't happen when I create the dist with your bundle script, could you please help us understand what is the difference between tag dist and the dist genereated by script? why doesn't the tag dist work with webpack minimize? Thanks!

**Comment by joeyparrish** [comment]
@Yuvalke, I have no idea, but we can continue to discuss that in #3092 you filed.  It's likely webpack's fault, or one of your webpack plugins.
