### ISSUE TITLE
 cannot find segment lookupTime: 885

### ISSUE THREAD

**Issue by mihaiav** [google/shaka-player#3045]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
3.0.6

**Can you reproduce the issue with our latest release version?**

yes
**Can you reproduce the issue with the latest code from `master`?**
didnt try

**Are you using the demo app or your own custom app?**
demo app
 

**What browser and OS are you using?**
chrome 87, MacOS
 

**What are the manifest and license server URIs?**
https://bitmovin-a.akamaihd.net/content/sintel/sintel.mp

 https://shaka-player-demo.appspot.com/demo/#audiolang=en-GB;textlang=en-GB;uilang=en-GB;asset=https://bitmovin-a.akamaihd.net/content/sintel/sintel.mpd;panel=CUSTOM%20CONTENT;build=uncompiled

I've tried to play the manifest above but shaka seems stuck in a loop
``streaming_engine.js:1143 (audio:1) cannot find segment lookupTime: 885 presentationTime: 887``

The same manifest plays just fine with other players such bitmovin own player. I believe Shaka played this manifest  in some older versions b/c I had it in my tests.

**Comment by TheModMaker** [comment]
This appears to be the same as #3139, so I'm going to close this as a duplicate.  If this is still an issue after that is fixed, feel free to reopen or open a new issue.
