### ISSUE TITLE
Events Play and buffering are not reliable on  Firefox 44.0.2 windows7

### ISSUE THREAD

**Issue by basharam** [google/shaka-player#305]
Though its works on Linux firefox-v44.0.2, The bufferingStart, bufferEnd and playing event are not consistent on win7 Firefox44.0.2. although the minBufferTime is 10sec,  playing is resumes on every 2 secs of buffered data on a network throttled say 120kbps.  During buffering no pacman icon is displayed.

Steps to repoduce
1. Firefox v44.0.2 on Win7
2. Load custom manifest "https://a510avoddashs3us-a.akamaihd.net/d/1$AOAGZA014O5RE,D55F4215/videoquality$1080p/ondemand/175a/cda2/f539/45c6-b6e2-7c61ebb90c23/62bdd751-807d-4503-90af-f6a8514758eb_corrected.mpd
" in  http://shaka-player-demo.appspot.com/
Expected: 
 Wait to buffer data as specified in manifest file(minBufferTime).
Current results:
Player plays on every 2 sec of buffered data before entering into buffer state with no pacman icon.. 

Console logs :http://pastebin.com/raw/Pmiixrnv

**Comment by joeyparrish** [comment]
Sounds like a difference in the media stacks on Firefox for Windows and Linux.  According to Mozilla's release calendar, Firefox 45 became the current stable release a few days ago.  Could you please try with Firefox 45?

**Comment by basharam** [comment]
Thanks for the Firefox 45 info. Events are firing as expected :)
