### ISSUE TITLE
can we used source tag for alternative video which the browser may choose from, based on browser support using shaka player ?

### ISSUE THREAD

**Issue by gawdeaniket** [google/shaka-player#3054]
can we used source tag for alternative video which the browser may choose from, based on browser support using shaka player ?

**Comment by joeyparrish** [comment]
Yes!  Shaka's UI offers many convenience features, one of which is a DOM-based initialization which supports `<source>` tags for automatic fallback.  Here's an example taken from our UI tutorial (https://shaka-player-demo.appspot.com/docs/api/tutorial-ui.html):

```html
<div data-shaka-player-container style="max-width:40em"
     data-shaka-player-cast-receiver-id="930DEB06">
  <video autoplay data-shaka-player id="video"
      style="width:100%;height:100%">
    <!-- Try this first -->
    <source src="https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd"/>
    <!-- Try this if the first one has failed -->
    <source src="https://storage.googleapis.com/shaka-demo-assets/angel-one-hls-apple/master.m3u8"/>
  </video>
</div>
```

This will prefer the DASH content, which is listed first.  On iOS, it will fall back to playing the HLS content.

To try this yourself, please check out the entire UI tutorial from the beginning: https://shaka-player-demo.appspot.com/docs/api/tutorial-ui.html

Does this help?

**Comment by gawdeaniket** [comment]
> Yes! Shaka's UI offers many convenience features, one of which is a DOM-based initialization which supports `<source>` tags for automatic fallback. Here's an example taken from our UI tutorial (https://shaka-player-demo.appspot.com/docs/api/tutorial-ui.html):
> 
> ```
> <div data-shaka-player-container style="max-width:40em"
>      data-shaka-player-cast-receiver-id="930DEB06">
>   <video autoplay data-shaka-player id="video"
>       style="width:100%;height:100%">
>     
>     <source src="https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd"/>
>     
>     <source src="https://storage.googleapis.com/shaka-demo-assets/angel-one-hls-apple/master.m3u8"/>
>   </video>
> </div>
> ```
> 
> This will prefer the DASH content, which is listed first. On iOS, it will fall back to playing the HLS content.
> 
> To try this yourself, please check out the entire UI tutorial from the beginning: https://shaka-player-demo.appspot.com/docs/api/tutorial-ui.html
> 
> Does this help?

@joeyparrish  Thanks for the reply ,was really helpful. One last question how can we detect if the video is playing using shaka player or using normal video tag

**Comment by theodab** [comment]
If you are setting up the player this way, you can check for the presence of the `ui` property on the video element.
```js
const video = document.getElementById('video');
if (video && video['ui']) {
  // This player has a UI instance, so it was set up by Shaka Player.
}
```
You can also use that `ui` object to access various UI methods as needed, such as `configure` or `getControls`.

**Comment by joeyparrish** [comment]
And if it _is_ Shaka Player, you can get the exact version with:

```js
video.ui.getControls().getLocalPlayer().constructor.version
```
