### ISSUE TITLE
TextStream buffer behind question

### ISSUE THREAD

**Issue by interlark** [google/shaka-player#3055]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?** Yes.

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes.

**What version of Shaka Player are you using?** 3.0.6

**Please ask your question**
There's a case: I got a video of 30 minutes. When I put the video on pause and seek to the 15:00, the video and subtitles are starting to buffer ahead.
What I need is to get a little bit of previous subtitles (like 10 seconds, say, from 14:50 till current time 15:00) loaded.

The source code looks tricky for me, I tried something like
```javascript
button.addEventListener('click', e => {
        // load last 10 seconds of subtitles to buffer
        var currentTime = player.video_.currentTime;
        var startTime = currentTime - 10;
        var streamingEngine = player.streamingEngine_; 
        var textMediaState = streamingEngine.mediaStates_.get('text');
        var segRefs = streamingEngine.getSegmentReferenceNeeded_(textMediaState, startTime, currentTime);
        streamingEngine.fetchAndAppend_(textMediaState, startTime, segRefs);
});
```
But got error
```javascript
Assertion failed: (text:11) did not expect update to be scheduled
``` 
Seems like I got to schedule somehow and somewhere text mediastate's ```updateTimer```.
Could you give me a hint about this problem?

**Comment by interlark** [comment]
I fixed it getting current text stream among of ```let currentTextStream = player.getManifest().textStreams;``` and fetching desired chunks with ```currentTextStream.segmentIndex.references[index].getUris()```, parsing it and sending to own ```TextDisplayer```.
The only thing I can't fix is that assertation that happens every time I call ```player.getManifest()```:
```
Shaka Player's internal Manifest structure is NOT covered by semantic versioning compatibility guarantees.  It may change at any time!  Please consider filing a feature request for whatever you use getManifest() for.
```
So, is there any plan to provide access to streams/segment's URLs with their start/end times?

**Comment by TheModMaker** [comment]
Why do you need the previous segment buffered?  When we seek to a time, we make sure to download that segment so we have that time buffered.  We should have text cues for the current time.  We also sometimes fetch the previous segments to account for inaccurate manifests.  If the manifest says it starts at 15:00, it means it should have cues displayed at that time, so there should be no need to fetch the previous one.

If your manifest is really inaccurate (i.e. a segment at 15:00 actually starts at 15:10), then you can set the
`streaming.inaccurateManifestTolerance` value to a larger value (in seconds).  This will make us fetch the previous segment to account for inaccurate manifests.

**Comment by interlark** [comment]
I have extra nifty functionality that allows you to watch subtitles history any time without rewinding, like a couple of previous cues.
Usually I take them from buffer (thanks to the ```bufferBehind```) but when you seek to some place you don't have buffered subtitles behind you. That's why I need to fetch some segments manually on demand.

**Comment by TheModMaker** [comment]
I would suggest using `getManifest()` and fetching the segments yourself.  All the text parsers are exported, so you can leverage them to help parse the results instead of trying to pass them through our media pipeline.  Note that because of #3096, you won't be able to use this in compiled mode.

```js
const stream = player.getManifest().textStreams[0];
await stream.createSegmentIndex();  // Not needed if currently streaming.
const refs = Array.from(stream.segmentIndex);
const uris = refs[0].getUris();
```

**Comment by interlark** [comment]
@TheModMaker, thanks for that and that you mentioned that bug.
