### ISSUE TITLE
Incorrect choose codec for 4K video

### ISSUE THREAD

**Issue by hcodes** [google/shaka-player#3056]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
lastest

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Custom app

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
Any

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Any

**What are the manifest and license server URIs?**

**What did you do?**

avc codec has 24 variants (not support 4k), vp9 - 32 variants (24 + 8 with 4K).
[https://github.com/google/shaka-player/blob/master/lib/util/stream_utils.js#L32](chooseCodecsAndFilterManifest) method returns avc.

**What did you expect to happen?**
should returns vp9

**What actually happened?**

Average bandwidth H.265 (24 variants + 8 variants with 4K) variants larger than H.264 (24 variants).
[https://github.com/google/shaka-player/blob/master/lib/util/stream_utils.js#L32](chooseCodecsAndFilterManifest)
[manifest.txt](https://github.com/google/shaka-player/files/5729764/manifest.txt)

**Comment by hcodes** [comment]
https://github.com/google/shaka-player/pull/3072

**Comment by joeyparrish** [comment]
Thank you for putting together a PR for this!

**Comment by joeyparrish** [comment]
Closed in #3072
