### ISSUE TITLE
Sentry conflict with Widevine

### ISSUE THREAD

**Issue by toschlog** [google/shaka-player#3064]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.6

**Can you reproduce the issue with our latest release version?**
Haven't tried

**Can you reproduce the issue with the latest code from `master`?**
Haven't tried

**Are you using the demo app or your own custom app?**
Custom app

**If custom app, can you reproduce the issue using our demo app?**
Haven't tried

**What browser and OS are you using?**
Electron

**What did you do?**
I'm using Widevine with the Castlabs fork of Electron.  I'm also using Sentry for crash reporting.  I have found that if Sentry is enabled and Widevine encounters an error (a 404 getting the license, for example) the render process of my app hard locks.

I'm assuming that this has something to do with the anti-debugging measures in Widevine CDM.  I don't know if you're the right people to be asking about this, but if you're not perhaps you can point me in the right direction.

I'm looking for any information on what's going on that I can pass the Sentry folks so they can address the issue.

Thanks.

**Comment by joeyparrish** [comment]
For Widevine support in general, you will need to contact Widevine at https://widevine.com/contact .

I hope I can save you some small amount of time by saying that I would expect anti-debugging measures on Widevine CDM implementations.  I don't anything about Sentry or crash reporting in general, so I don't know if you can configure the product in some way to avoid this issue.

If you need to help to get crash-reporting to work with the Widevine CDM, you would need to contact Widevine directly to ask for support on that.  The Shaka Player team, working mainly in JS, is not in a position to help with that.  Sorry we can't do more!

**Comment by toschlog** [comment]
I'll contact Widevine.  Thanks!
