### ISSUE TITLE
is there any external package help to convert (audio/aac ) to any audio format that shaka support ? or any solution to play acc/audio ?

### ISSUE THREAD

**Issue by tareq-rezk** [google/shaka-player#3066]

**Comment by kocoten1992** [comment]
Not aware of any simple plugin like that.

You could try a full ffmpeg transcode on browser https://github.com/ffmpegwasm/ffmpeg.wasm.

**Comment by joeyparrish** [comment]
Please subscribe to #2337 for support for "containerless" formats like raw AAC or raw MP3.  We don't support them yet, but we are very much open to community contributions from anyone who is motivated to help add this feature.
