### ISSUE TITLE
DASH content on single page application is not playing after moving to next page

### ISSUE THREAD

**Issue by OfirShlifer** [google/shaka-player#3070]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.5

**Please ask your question**
We have a player using Shaka with DASH manifest on this single page application website: 
https://www.hometalk.com/44339609/concrete-pumpkins?fc=10854&disableIVT

Bug flow:

1. Entering the website (on Chrome)
2. The DASH content is playing as expected (after the ads are done)
3. Moving to the next article by clicking on the big next button in the middle right side of the screen
4. The content is not playing (after the ads are done)

The Shaka loaded event is triggered as expected and all the other events as well (same as on the first page).
After the call to load the video src, the video tag events onCanPlay or onCanPlayThrough are not triggered (only onWaiting event is triggered).

HLS content on the same scenario is playing both on Chrome and Safari. 

Do you know what causes this issue or have any suggestions for resolving it? 
Is this bug relates to the fact that the src on the video tag is a Blob URL when playing DASH content on chrome? 

Thanks for your reply!

**Comment by TheModMaker** [comment]
Sorry for the delays.  It is hard to find what video you are talking about on that page (if it is still valid).  If you're talking about the "Trending videos" section, it plays fine for me.  Can you please try to reproduce with a smaller demo, preferably with easier JavaScript access.

It is intended to be using a Blob URL, that is how we handle playback.  If you could tell us how your calls into Shaka Player work, that would help.  For example, do you create a new `shaka.Player` object for new pages, or do you reuse them?  Do you reuse video elements, or are those recreated on new pages?  Remember you need to call `await player.unload()` or `await player.destroy()` on an old Player instance before you can use the video element for something else.  Or you can call `player.load(...)` with the new URL to start playing some new content.
