### ISSUE TITLE
Controls

### ISSUE THREAD

**Issue by okidokios** [google/shaka-player#3074]
Hello,

Can someone help me how to add controls with Shaka ui I found this site which was helpful for me http://www.bok.net/svn/Bento4/trunk/Documents/Websites/www.bok.net/dash/players/html5/shaka-player/index.html but I want to add controls to change bitrate lang and the live option, I read the shaka docs but the app.js is different than the example provided on shaka tutorials, if someone can help me to add the controls options please.

**Comment by okidokios** [comment]
I added the shaka ui to the html and the code:

` <div data-shaka-player-container style="max-width:40em"
         data-shaka-player-cast-receiver-id="930DEB06">
       
      <video autoplay data-shaka-player id="video" style="width:100%;height:100%"></video>
    </div>`

And the controls appear on the player, but I'm not available to see the captions bitrates and langs I think I need to modify the app.js to invoke shaka ui controls:

`app.initPlayer = function() {
    // Create a Player instance.
    app.video = /** @type {!HTMLVideoElement} */ document.getElementById('video');
    app.player = new shaka.Player(app.video);

    // Attach player to the window to make it easy to access in the JS console.
    window.player = app.player;

    // Listen for error events.
    app.player.addEventListener('error', app.onPlayerError, false);` 

can someone help me please.

**Comment by TheModMaker** [comment]
Check out our [UI tutorial](https://shaka-player-demo.appspot.com/docs/api/tutorial-ui.html).  If you use `data-shaka-player-container`, you do not use `shaka.Player` constructor.  See this:

```js
async function init() {
  // When using the UI, the player is made automatically by the UI object.
  const video = document.getElementById('video');
  const ui = video['ui'];
  const controls = ui.getControls();
  const player = controls.getPlayer();
}

// Listen to the custom shaka-ui-loaded event, to wait until the UI is loaded.
document.addEventListener('shaka-ui-loaded', init);
```
