### ISSUE TITLE
Shaka and iPadOS

### ISSUE THREAD

**Issue by boredom2** [google/shaka-player#3075]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
latest

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `master`?**
yes

**Are you using the demo app or your own custom app?**
both

**If custom app, can you reproduce the issue using our demo app?**
yes

**What browser and OS are you using?**
iPadOS 14.3

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**
any

**What did you do?**
I am very sure, that DASH Playback on iPadOS (13+) worked fine, when iPadOS was released. Nevertheless, currently, any DASH Manifest leads to an Exception in Shaka. I am not sure, if Apple changed something or something in Shaka changed. I admit, its been a while, that I last checked that, but I am absolutely sure (and our Code was built for that), that DASH Content was no Problem with iPadOS 13.
Anyway - as I couldnt make any Content work via DASH on iPadOS, I decided to try HLS, which for sure works fine. But still, I cannot force SHAKA to use MSE for that, it always uses the "native" Implementation.
I know, there is a Setting "useNativeHlsOnSafari", but this does not seem to have an effect. At least, the Video src is still the HLS URL itself and no Blob and getVariantTracks() is still empty.

**What did you expect to happen?**
I initially expected, that DASH works on iPadOS.
If thats not possible, I would like to use HLS via MSE .

**What actually happened?**

DASH does not work at all (but maybe thats intended)
HLS always uses native Integration, not EME and ignores "useNativeHlsOnSafari"

**Comment by TheModMaker** [comment]
What error are you seeing?  Do you have any device logs?  It works fine for me on iOS 14.0.  We'll ignore `useNativeHlsOnSafari` if the device doesn't have MSE, so it's possible something happened and MSE is detected as not supported.

**Comment by boredom2** [comment]
@shaka-bot reopen

Hi there and sorry I did not notice that more early :)

We have this Issue a lot again and all kind of Versions.
First of all - DASH should work on iPadOS 13+, or am I wrong?
At least - visiting the SHAKA Demo Player Page with an iPad only shows HLS Links, no DASH at all.
If I try it anyway with a custom Manifest - SHAKA responds with Media Error (4).
But i am 100% sure, that this worked without any Issues - as iPadOS claims to me macOS since v13, it offers all Possibilities, that the macOS Safari offers - including DASH Support.
Or am I wrong here?

Thanks,
Christoph

**Comment by boredom2** [comment]
And then coming back to native HLS on iPadOS:

I start the Player with this Config: 
"{"preferredAudioLanguage":"auto","abr":{"enabled":true,"switchInterval":6},"manifest":{"disableText":true},"streaming":{"smallGapLimit":1,"jumpLargeGaps":true,"ignoreTextStreamFailures":true,"useNativeHlsOnSafari":false}}"

and the Manifest:
https://nq-p01.akamaized.net/5d3a9aac-d32f-48ef-bc83-2f68d8d239c8/1694021_src.ism/Manifest(format=m3u8-cmaf)

and still - the <video> Object uses this Manifest as src, so we use "native HLS" here. as this is a new iPad with latest iPadOS (14.4), MSE should be available there.

**Comment by boredom2** [comment]
And at the very last - I can confirm this Behavious on various iPads on iPadOS 13,14-14.4 on our Players and Shaka Dev. I cannot see the Usage of MSE anywhere, its always native HLS.
Is there anything else I can provide to figure out why this happens? Or am I missing something here?

**Comment by TheModMaker** [comment]
You can check `window.MediaSource` in JavaScript.  This will be present if MSE is supported, otherwise we can't use MSE and only native HLS will be supported.  We can only play DASH content if MSE is available.
