### ISSUE TITLE
Allow Native HLS playback on other Platforms

### ISSUE THREAD

**Issue by stuartflanagan** [google/shaka-player#3077]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Is your feature request related to a problem? Please describe.**

Would like to use devices native HLS decoder when known. Some TVs allow Playback of encrypted HLS but Shaka intercepts the request and throws error `4034` As Shaka does not support encryption as yet. 

**Describe the solution you'd like**

We would like the option to force the use of the Native HLS player via src like it does automatically for Safari.

**Describe alternatives you've considered**

Alternatives are using a separate player for HLS playback on TV devices when DRM is not available. We are trying to reduce maintenance of players and are hoping we can use the Shaka Player API as is possible for playback via src on Safari.

**Comment by joeyparrish** [comment]
The logic that controls this is in `lib/player.js` in `shouldUseSrcEquals_()`.

After all the hard requirements are dealt with, there is a decision between MSE and src= when both are possible.  It currently looks like this:

```js
      // We would prefer MediaSource in some cases, and src= in others.  For
      // example, Android has native HLS, but we'd prefer our own MediaSource
      // version there.  For Safari, the choice is governed by the
      // useNativeHlsOnSafari setting of the streaming config.
      return Platform.isApple() && this.config_.streaming.useNativeHlsOnSafari;
```

How about we create a flag like `streaming.preferNativeHls`?  Then we could change this to:

```js
    if (this.config_.streaming.preferNativeHls) return true;
    if (Platform.isApple()) return this.config_.streaming.useNativeHlsOnSafari;
    return false;
```

What do you think?

**Comment by avelad** [comment]
I can work on this the next week.

**Comment by joeyparrish** [comment]
@avelad, no need.  If the proposal would work for @stuartflanagan, I have the change done already locally.

**Comment by stuartflanagan** [comment]
Thank you all the proposal looks great and will allow us to preference HLS in some cases where both are supported but the EME support is a bit unreliable.

**Comment by ziddey** [comment]
@stuartflanagan in the interim, you could fallback to native/hlsjs when shaka errors:

```
if (err.code === shaka.util.Error.Code.HLS_AES_128_ENCRYPTION_NOT_SUPPORTED) {
  player.unload().then(() => {
    if (video.canPlayType('application/vnd.apple.mpegurl')) {
      console.log('Falling back to native hls support')
      video.src = manifestUri
    } else if (Hls.isSupported()) {
      console.log('Falling back to hls.js')
      const hls = new Hls()
      window.hls = hls
      hls.loadSource(manifestUri)
      hls.attachMedia(video)
    }
}
```

Or you could just try native/hlsjs first if know ahead of time it's aes128 encrypted.

Of course you'll lose out on being able to change the resolution if using shaka ui, but it wouldn't have been available anyway.

**Comment by joeyparrish** [comment]
@ziddey, that all looks great, except that I would suggest using `detach()` instead of `unload()`.  When the player detaches, it gives up control over the media element.  When the player unloads, it stops playback and streaming of content, but retains control over the media element, and gets ready for the next load by creating a new MediaSource object and attaching it to the element.

In practice, you can get away with `unload()` here instead of `detach()`, but it's best if the Player object's state is consistent with what you're doing at the app level.  Using `detach()`, though, requires you to later `attach(video)` before your next `load()` call.

**Comment by ziddey** [comment]
Ah I see how there'd be an issue. The idea for using `unload()` is that it would allow for a uniform player ui experience (shaka ui), even when using hlsjs. However, I imagine native fallback would just fail again, since shaka would pick up the source?
