### ISSUE TITLE
HLS ID3 content tag

### ISSUE THREAD

**Issue by apackouz** [google/shaka-player#3078]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.6

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
custom

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Safari MacOS

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
n/a

**What are the manifest and license server URIs?**

Bug: https://content.uplynk.com/channel/01b2e906788843e89f46f1c5cc031952.m3u8
Works: https://content.uplynk.com/channel/01b2e906788843e89f46f1c5cc031952.mpd

**What did you do?**

add a listener for metadata event to console.log all id3 tags  

**What did you expect to happen?**
all ID3 tags to appear in console

**What actually happened?**
i see output for ID3 tags except for an ID3 content tag.  
when using the debug player there is a warning in console: 
[Warning] ID3 metadata processing was called without initializing server side ad logic. Ad-related metadata will not take effect (ad_manager.js, line 610)

player should send a metadata event with the data from the ID3 tag even though there is no ad manager. 
This functionality works when using a DASH stream, player emits an emsg event with the data.

**Comment by avelad** [comment]
What event are you listening to? The correct one for HLS would be `metadata` (src = in Safari).

**Comment by apackouz** [comment]
i am listening to all events. 
player does not emit metadata event for id3 content tag.  with debug mode i can see the error mentioned above.  i do see other id3 tags through metadata event.

**Comment by TheModMaker** [comment]
If you set `streaming.useNativeHlsOnSafari` configuration to `false`, does it work?  If you are playing on Safari, we'll use native `src=`, so the browser handles everything.  So we may not be able to parse the tags in this case.
