### ISSUE TITLE
Validate custom asset license server parameter format

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#3079]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Is your feature request related to a problem? Please describe.**

Running custom asset tests, it is easy to make a mistake on the custom license server parameter.  This parameter requires the format KEYSYSTEM_ID=LICENSE_SERVER_URL, but I frequently mess this up and just put the license server URL without the key system ID.  This leads to a bad DRM config in the test, which causes the test to be skipped and the test run (which contains only that one test) to fail.

**Describe the solution you'd like**

test.py should validate the format of this parameter, instead of passing it blindly to the tests.

**Describe alternatives you've considered**

You could validate the format in the test itself, but that's less helpful, since it occurs later and after some expensive setup (start test runner, start browsers, connect back, load the code and tests...)

**Comment by chongjunhong** [comment]
yes, I am interested

**Comment by joeyparrish** [comment]
Thanks!

**Comment by chongjunhong** [comment]
> Thanks!

No problem! Excited for my first PR.

**Comment by chongjunhong** [comment]
Please let me know if the implementation aligns with your expectation
