### ISSUE TITLE
Can seek range for live be increased by manipulating buffer?

### ISSUE THREAD

**Issue by kirandcunha** [google/shaka-player#3080]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v3.0.6

**Please ask your question**
I am trying to increase the seek back time of a live DASH stream to 15 mins using Shaka. The stream by default can be rewinded to 5 minutes from current time. Can this be achieved by instructing the player to store buffer for the past 15 mins? I have tried using bufferBehind and setting it to 900 (15 minutes). This does not seem to work and rewind does not go beyond seekRange.

This is the DASH Live URL I am using: https://livesim.dashif.org/livesim/testpic_2s/Manifest.mpd

**Comment by joeyparrish** [comment]
The short answer is yes, you can do this, with some important caveats.

`bufferBehind` is for how we manage what's in kept in buffer once the playhead moves past.  But this is different from what you want.  You really want to override the DASH attribute called `timeShiftBufferDepth`, which defines how wide the availability window is.

The availability window says effectively "this is how much content is on the server that you can request at any time."  You can override this with `manifest.availabilityWindowOverride`:

```js
player.configure('manifest.availabilityWindowOverride', 900);
```

This will ignore the `timeShiftBufferDepth` of the manifest and use a value of 900 seconds (15 minutes) instead.  The seek range in the player will become 900 seconds.

_**However**_, if the server does not actually keep that much content around, requests for content from 900 seconds ago will result in an HTTP 404 error, and playback will stall at that position.  So you can't use this to control the server's behavior in any way, or to make content available that isn't.

When we run live streams (using [Shaka Streamer](https://github.com/google/shaka-streamer)), only a couple of segments are kept outside the availability window.  As we upload new segments to cloud storage, we also delete older ones.

So increasing the size of the availability window in the player would not work in the case of *our* content.  Depending on the encoder/packager you're using, you *may* be able to increase the window size and get away with it.

Does this help?

**Comment by kirandcunha** [comment]
Yes. This helps. Thanks!
