### ISSUE TITLE
Stream with trick mode track can't play with compiled lib in 3.0.7

### ISSUE THREAD

**Issue by bwallberg** [google/shaka-player#3085]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.7

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes and No - it only fails when compiled so it's something with the release build that is broken, it works fine on the demo page in "uncompiled" mode.

**Are you using the demo app or your own custom app?**
Demo app

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
Latest chrome

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**
https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://storage.googleapis.com/shaka-demo-assets/sintel-trickplay/dash.mpd;panel=ALL_CONTENT;panelData=TRICK_MODE;build=compiled

**What did you do?**
Try to play
https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://storage.googleapis.com/shaka-demo-assets/sintel-trickplay/dash.mpd;panel=ALL_CONTENT;panelData=TRICK_MODE;build=compiled

**What did you expect to happen?**
Playback

**What actually happened?**
Error

**Comment by bwallberg** [comment]
PR created.

**Comment by joeyparrish** [comment]
Thanks for filing this issue, and for the PR!

**Comment by bwallberg** [comment]
@joeyparrish thank you for Shaka :)

Might I ask when a new version will be made?

**Comment by avelad** [comment]
It is also happening to me with some production streams, so this prevents me from going to 3.0.7
