### ISSUE TITLE
Ability to Parse sidx in Separate File from Media Segments

### ISSUE THREAD

**Issue by nkam12** [google/shaka-player#3093]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Is your feature request related to a problem? Please describe.**

I am attempting to use Shaka Player to play audio-only DASH content with the Main profile and providing Shaka Player with a sidx box that is in a separate file from the media segments. When using DASH with the Main profile, I would expect Shaka Player not to assume that the media segments would be found in the same file as the sidx. However, Shaka Player currently uses the size of the sidx box to offset the media segments, which is leading to incorrect byte ranges in my case. When the player attempts to retrieve these incorrect byte ranges, the CDN throws an error, eventually leading to the error: "failed fetch and append: code=1002" in Shaka Player.

**Describe the solution you'd like**

For DASH content using the Main profile:
- IndexRange should not be mandatory (since it's a separate file; the entire file should be downloaded)
- Segment positions should be relative to InitSegment, not the sidx box

Also, is there an email address that I can use to discuss this feature in further detail? 

**Describe alternatives you've considered**

**Additional context**

**Comment by joeyparrish** [comment]
@nkam12, is this no longer an issue for you?

**Comment by nkam12** [comment]
Correct, ended up finding an issue with my manifest. No issue on Shaka Player's end. Thanks!
