### ISSUE TITLE
SegmentReference.getUris doesn't appear in compiled bundle

### ISSUE THREAD

**Issue by IbraheemNofal** [google/shaka-player#3096]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v3.0.6

**Please ask your question**
So I'm currently trying to get a list of segment URLS for the stream that's playing. I've managed to get a list of segments by using player.getManifest().variants[14]['video'].createSegmentIndex() and then using stream.segmentIndex. But even then, I've found no way of retrieving a list of segment URLS even though [#1074](https://github.com/google/shaka-player/issues/1074) suggests that it should be possible using segment.createUris(). But, createUris() is deprecated now. Please note, that I'm currently testing this using the video and approach under [basic usage](https://shaka-player-demo.appspot.com/docs/api/tutorial-basic-usage.html), so it's a dash video stream, not a live stream. Ideally, I'd like to be able to do the same for both HLS and Dash, just so I can pre-warm the cache with segment Uris.

**Comment by michellezhuogg** [comment]
Hello,

Would you please try:
stream.segmentIndex.references[0].getUris() ? Let us know if it works for you. Thank you!

**Comment by IbraheemNofal** [comment]
Not working. I'm getting an error:

> myapp.js:73 Uncaught (in promise) TypeError: Cannot read property '0' of undefined
>   at onSegmentCreated (myapp.js:73)
    
 Here's what I'm doing:
     `player.getManifest().variants[14]['video'].createSegmentIndex().then(onSegmentCreated, onSegmentCreationFailed)`

and then in the onSegmentCreated function:
     `console.log(list.references[0].getUris())`

**Comment by TheModMaker** [comment]
Try: `const references = Array.from(stream.segmentIndex); references[0].getUris();`.

**Comment by IbraheemNofal** [comment]
Not working. I'm now getting this error:

> Uncaught (in promise) TypeError: references[0].getUris is not a function
    at onSegmentCreated (myapp.js:75)

**Comment by TheModMaker** [comment]
It looks like the `getUris` function isn't in the compiled bundle even though it is exported.  We'll look into it.
