### ISSUE TITLE
HLS_COULD_NOT_PARSE_SEGMENT_START_TIME for fmp4 segments that play fine if they are wrapped in a dash manifest

### ISSUE THREAD

**Issue by TheJohnBowers** [google/shaka-player#3099]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.7

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Likely, I am using what is on appspot and this hasn't changed for a while

**Are you using the demo app or your own custom app?**
demo app

**If custom app, can you reproduce the issue using our demo app?**
NA

**What browser and OS are you using?**
Chrome on macos

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

These are unencrypted samples -- So no license server is required

HLS with FMP4:
https://content.uplynk.com/3121bfc5840e4ec792eed8a1d9df65b3.m3u8?m4fenctype=cenc
MPD with same FMP4 segments:
https://content.uplynk.com/3121bfc5840e4ec792eed8a1d9df65b3.mpd

**What did you do?**

Playback the above 2 URLs and notice that the HLS manifest errors with the HLS_COULD_NOT_PARSE_SEGMENT_START_TIME error, but the dash manifest plays find

**What did you expect to happen?**
I would expect both to play back.  The error suggests something missing from the actual segments, yet the same segments are fine when using a dash manifest.  If there is somethign missing in the encoded fragments, could you provide insight into what might be missing?

**What actually happened?**

Failed playback

**Comment by joeyparrish** [comment]
We already have a fallback to file extensions in the HLS parser.  But we don't have "m4f" in the mapping.

See `shaka.hls.HlsParser.AUDIO_EXTENSIONS_TO_MIME_TYPES_` and `shaka.hls.HlsParser.VIDEO_EXTENSIONS_TO_MIME_TYPES_` in `lib/hls/hls_parser.js`.

@TheJohnBowers, please try tweaking those mappings.  If that fixes the issue or helps you make progress, we would be happy to accept a PR.

**Comment by avelad** [comment]
I created https://github.com/google/shaka-player/pull/3111 to resolve it

**Comment by TheJohnBowers** [comment]
It definitely plays back with the change @avelad created -- I was to busy to get to checking it out yesterday, and it seems he beat me to it :)
