### ISSUE TITLE
Expose Shaka's MediaSession API instance

### ISSUE THREAD

**Issue by ferferga** [google/shaka-player#3101]
**Is your feature request related to a problem? Please describe.**
Related to #3100

**Describe the solution you'd like**
As not all the streams might contain appropiate metadata, it would be great to expose some method in Shaka to pass our custom MediaMetadata objects, queues (for supported environments) and such

**Describe alternatives you've considered**
Handling MediaSession completely in our own, without Shaka, as seen in #3100

**Comment by joeyparrish** [comment]
We don't create a MediaSession instance in Shaka Player, because we don't know any metadata about your content. You only provide us with a manifest URL.

Our demo app creates a MediaSession instance with metadata about our demo content, but this is done at the level of the demo app, not in Shaka Player itself.

So as far as I can tell, there is no MediaSession instance to expose in Shaka Player.  It has always been our intent that you would use MediaSession yourself at the app level.

Does this help explain things?

**Comment by ferferga** [comment]
@joeyparrish After your reply I noticed that, indeed, all the mentions for MediaSession were under the ``demo`` folder (misstep from my side, sorry).

I'm sure we don't have any handling of MediaSession by our side, so I discared that as well.

Following that, I tried to trace our dependencies to check if some of them are causing the controls to appear - no luck, nothing that indicates that.

Last thing I checked was for hints at MediaSession in our built client - no luck as well.

My last stake at this is that browsers (tested Edge Chromium and Firefox) now detect the <audio> or <video> elements automatically and can interact with it, showing media controls without the need of adding anything by our side. In fact, it seems that it needs to be disabled explicitly as can be seen in https://bugs.chromium.org/p/chromium/issues/detail?id=972051. It's not stated explicitly in this chromium issue, but it makes me wonder even more if this is what I'm experiencing with our app. I googled to see what's the expected default behaviour without any luck.

This seems now unrelated to Shaka, so feel free to close this issue without replying but, in case you do, you know if this is the case and major browsers automatically create mediasessions automatically?

Thank you very much for your time and insight.

**Comment by joeyparrish** [comment]
> do you know if this is the case and major browsers automatically create mediasessions automatically?

I believe you get a pause button in a media controls dialog from Chrome even without using the API.  I think the API only enhances the metadata and choice of buttons in that dialog.  I **think**.

**Comment by ferferga** [comment]
@joeyparrish Okay, thank you very much!

And sorry for the confusion!

**Comment by joeyparrish** [comment]
No worries!  This whole space is often confusing.  :smile:
