### ISSUE TITLE
VTT Cues after styled in #2348 breakLine is not properly set

### ISSUE THREAD

**Issue by sonicd300** [google/shaka-player#3103]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
3.1.0-pre

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `master`?**
yes

**Are you using the demo app or your own custom app?**
custom app

**If custom app, can you reproduce the issue using our demo app?**
haven't tried but already fixed it, wanted to submit the pull request against an issue number

**What browser and OS are you using?**
Chrome OSX Big Sur

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What did you do?**
Loaded a VTT into a video with styling <i> and multi lines like the following:
1
00:00:03.000 --> 00:18:14.000 align:middle line:83%
<i>Κάποιες μέρες,</i>
<i>η παιδική μου ηλικία μοιάζει τόσο μακρινή.</i>

**What did you expect to happen?**
The text Cue breakLine to have the correct styles

<img width="518" alt="Screen Shot 2021-01-14 at 6 01 11 PM" src="https://user-images.githubusercontent.com/1652066/104660035-cf1e9000-5693-11eb-9203-10aed075c756.png">

**What actually happened?**
Text Cues are styled <i> but the "empty" <span> doesnt have the breakLine styles

<img width="349" alt="Screen Shot 2021-01-14 at 4 30 04 PM" src="https://user-images.githubusercontent.com/1652066/104660332-52d87c80-5694-11eb-866b-4d27446e39f1.png">

<img width="620" alt="Screen Shot 2021-01-14 at 6 15 49 PM" src="https://user-images.githubusercontent.com/1652066/104660452-8b785600-5694-11eb-953e-473701d6ff86.png">

**Comment by michellezhuogg** [comment]
Hello @sonicd300 , thank for for filing this bug. Looking forward to your pull request!

**Comment by sonicd300** [comment]
@shaka-bot reopen

I did quite more testing with different combinations of tags in lines but i ended up breaking a bunch of unit tests, i'm updating them, the problem is with the XML Parsing from string, and the css technique to render break lines which is causing weird behavior, i found more after i raised this bug testing things like:

```
- text <i>italic</i> test
```
I ended up replacing `\n` by `br` before getting it into the XML parser

**Comment by theodab** [comment]
I tried artificially inserting the following WebVTT into an asset:
```
WEBVTT

00:00:03.000 --> 00:18:14.000 align:middle line:83%
Κάποιες μέρες,
η παιδική μου ηλικία μοιάζει τόσο μακρινή.
text <i>italic</i> test
```
I've tried this on a variety of different versions of Shaka Player, but the line break was rendered correctly in every version I tried. I did see some odd styling with italics tags right after f42ccd2867f341e89cdf27316fd9bb7e63d22772, but they seem to be fixed by now. Is there any extra context to this that I should be aware of, such as a `STYLE` block in the webVTT or something?

**Comment by sonicd300** [comment]
@theodab the code i've added is in `vtt_text_parser.js` in `parseCueStyles` as follows

```
const xmlPayload =
      `<span>${payload.replace(/(?:\r\n|\r|\n)/g, '<br/>')}</span>`;
```

Im replacing the line breaks with BR tags because the XMLParser doenst really understands break lines and i couldn't detect below in `generateCueFromElement_` wether the node is a break line or not:

```
static generateCueFromElement_(element, rootCue, cues) {
    const nestedCue = rootCue.clone();
    if (element.nodeType === Node.ELEMENT_NODE && element.nodeName) {
      const bold = shaka.text.Cue.fontWeight.BOLD;
      const italic = shaka.text.Cue.fontStyle.ITALIC;
      const underline = shaka.text.Cue.textDecoration.UNDERLINE;
      const tags = element.nodeName.split(/[ .]+/);
      for (const tag of tags) {
        switch (tag) {
          case 'b':
            nestedCue.fontWeight = bold;
            break;
          case 'i':
            nestedCue.fontStyle = italic;
            break;
          case 'u':
            nestedCue.textDecoration.push(underline);
            break;
        }
      }
    }
    const isBreakline = element.nodeName === 'br'; // check if the node is the BR from previous parsing
    const isTextNode = shaka.util.XmlUtils.isText(element);
    if (isBreakline) { // If so then set the lineBreak to true
      nestedCue.lineBreak = true;
      cues.push(nestedCue);
    } else {
      if (isTextNode) {
        nestedCue.payload = element.textContent;
        cues.push(nestedCue);
      } else {
        const VttTextParser = shaka.text.VttTextParser;
        for (const childNode of element.childNodes) {
          VttTextParser.generateCueFromElement_(childNode, nestedCue, cues);
        }
      }
    }
  }
```

I've tested with all sorts of combinations, multi lines, fully styled lines, partially styled lines and this `br` injection has been working good for me so far, although i've forked the player and modified its source to fix this, i will pull latest master and re test to confirm if its still happening

**Comment by sonicd300** [comment]
Sorry for the delay on the response, i've run tests against master and the issue seems to be resolved as shown in this screenshot.

The only thing i had to do was doable with css externally on my consuming app, on the cues container div i had to set it to be `width: 100%; left: 0;` for a very specific case on our vtt file that rendered some subs in a weird position, but the core issue is solved.

Thanks for your time, i'll close.

<img width="447" alt="Screen Shot 2021-03-25 at 6 07 44 PM" src="https://user-images.githubusercontent.com/1652066/112767729-fcfe4a00-8fdd-11eb-9747-ae412a82d2ea.png">
