### ISSUE TITLE
Bug with close captions and selectTextTrack() API

### ISSUE THREAD

**Issue by spyros-uk** [google/shaka-player#3104]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v3.0.7

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes @ commit [edce1899](https://github.com/google/shaka-player/commit/edce1899f98eb7abca27be2acf82ce6eaa95c73f)

**Are you using the demo app or your own custom app?**
Custom app

**If custom app, can you reproduce the issue using our demo app?**
No. The demo app shows the captions "natively", where the custom app relies on the public API.

**What browser and OS are you using?**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Not tested on TVs, just Web 

**What are the manifest and license server URIs?**
manifestUrl: https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd
(The bug is DRM agnostic)

**What did you do?**
- Load the manifest above to the Player
- Enable close captions (for any language)
- Set the captions off and on again (or just select another language)

**What did you expect to happen?**
See the selected close captions appear again (see the selected close captions)

**What actually happened?**
The captions appear when selected the first time only. After turning them off and on again, or selecting a new language they disappear.

**More Info**
This bug introduced when the Shaka upgraded from `2.5.17` to `3.0.7` in the custom app.
It appears to be related to the `selectTextTrack()` API method, as it is called with the correct arguments (passing a track received by the `getTextTracks()` method, exactly the same as in version `2.5.17`), but in version `3.0.7` (and `3.0.6`) causes the described unexpected behaviour.

**Video showing the actual behaviour in v3.0.7:**
https://user-images.githubusercontent.com/15960526/104771219-db751c80-5769-11eb-93b5-6f720225930f.mp4

**Video showing the actual behaviour in v2.5.17:**
https://user-images.githubusercontent.com/15960526/104771375-1bd49a80-576a-11eb-989d-57ad13f7fec2.mp4

**Comment by TheModMaker** [comment]
Can you provide a link to your app?  I cannot reproduce any error when running the hosted demo.  Or if you could reproduce with the demo using the JavaScript console or create a minimal reproduction, that would really help.  For example, I can switch tracks just fine with the following in the demo app in the JavaScript console:

```js
var p = shakaDemoMain.controls_.player_
p.selectTextTrack(p.getTextTracks()[0])
p.selectTextTrack(p.getTextTracks()[1])
p.selectTextLanguage('en')
p.selectTextLanguage('fr')
p.setTextTrackVisibility(false)
p.setTextTrackVisibility(true)
```

**Comment by joeyparrish** [comment]
> The demo app shows the captions "natively", where the custom app relies on the public API.

Also, @spyros-uk, can you please clarify the difference between "natively" and with a "public API"?

The demo app, to be clear, will display captions in our UI by default, where they are drawn in the DOM on top of the video element.

If you are not using our UI library, or if you toggle a setting in the demo app to disable "Shaka Controls", captions will be displayed by the video element itself ("native" to the browser) using a "public API" provided by the browser.  (This is why I am confused about what you mean.)

**Comment by spyros-uk** [comment]
> Can you provide a link to your app? I cannot reproduce any error when running the hosted demo. Or if you could reproduce with the demo using the JavaScript console or create a minimal reproduction, that would really help. For example, I can switch tracks just fine with the following in the demo app in the JavaScript console:
> 
> ```js
> var p = shakaDemoMain.controls_.player_
> p.selectTextTrack(p.getTextTracks()[0])
> p.selectTextTrack(p.getTextTracks()[1])
> p.selectTextLanguage('en')
> p.selectTextLanguage('fr')
> p.setTextTrackVisibility(false)
> p.setTextTrackVisibility(true)
> ```

Unfortunately I can't provide a link to the app. I will check if it's ok to build a simple app that uses the Shaka debug version and share it with you.

> > The demo app shows the captions "natively", where the custom app relies on the public API.
> 
> Also, @spyros-uk, can you please clarify the difference between "natively" and with a "public API"?
> 
> The demo app, to be clear, will display captions in our UI by default, where they are drawn in the DOM on top of the video element.
> 
> If you are not using our UI library, or if you toggle a setting in the demo app to disable "Shaka Controls", captions will be displayed by the video element itself ("native" to the browser) using a "public API" provided by the browser. (This is why I am confused about what you mean.)

@joeyparrish My apologies for the confusion. By "Public API" I mean Shaka's API like the `selectTextTrack()`, `selectTextTrack()` and so on. And by "native" I mean either using any other internal functions of Shaka, or using the [TextTrack](https://developer.mozilla.org/en-US/docs/Web/API/TextTrack) Web API. I didn't know how the demo app works under the hood.


I need to do some more investigation from my side, will keep you posted.

**Comment by spyros-uk** [comment]
I have created a simple app which uses Shaka 3.0.7 to test the reported bug.

**App:** https://lyek8.csb.app/
**Code:** https://codesandbox.io/s/shaka-harness-lyek8?file=/src/index.js

**Outcome:**
The bug was not reproducible, it is probably a bug with the my custom app. Closing the issue, thanks for your time and efforts to look into it.
