### ISSUE TITLE
如何把这个项目编译成一个压缩的js文件

### ISSUE THREAD

**Issue by zhaoyingzi** [google/shaka-player#3106]
如何把这个项目编译成一个压缩的js文件

**Comment by michellezhuogg** [comment]
Hello @zhaoyingzi ,

Please follow our tutorial: https://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html .

Get the source:
```
git clone https://github.com/google/shaka-player.git
cd shaka-player
```
Compile the library and generate the docs:
`python build/all.py
`
The output is:
dist/shaka-player.compiled.js (compiled bundle)
dist/shaka-player.compiled.debug.js (debug bundle)
dist/shaka-player.compiled.externs.js (generated externs, for Closure-based projects)
