### ISSUE TITLE
How to build a debug version of the library without having the variable and function names changed by closure compiler?

### ISSUE THREAD

**Issue by spyros-uk** [google/shaka-player#3107]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.x.x and 3.x.x

**Please ask your question**
How to build a debug version of the library without having the variable and function names changed by closure compiler?

**More info**
I would like to create a debug build which makes debugging easier, in order to investigate and fix bugs in the Player.
In my effort to do so, I found out that the configuration I need to change is located in the file `build/build.py`. More specifically, I have changed the compilation type from `SIMPLE` to `BUNDLE` in `debug_closure_opts`.

<img width="272" alt="cp_options" src="https://user-images.githubusercontent.com/15960526/104905298-0fbf2780-597a-11eb-99e1-4f5af3bba04f.png">

By doing so, the compiler leaves the original variable and function names as I would like to, BUT it doesn't handle the following function calls.

<img width="367" alt="goog" src="https://user-images.githubusercontent.com/15960526/104905505-5c0a6780-597a-11eb-805a-d5d3df080f80.png">

Any help would be appreciated 🙂 

Thanks!

**Comment by TheModMaker** [comment]
You can use `./build/build.py --debug` to create a build with the original names.  You can also use `shaka-player.compiled.debug.js` or `shaka-player.ui.debug.js`  in the pre-built releases.

**Comment by joeyparrish** [comment]
If the renaming of local variables in the debug build is an issue, check out the [debugging tutorial](https://shaka-player-demo.appspot.com/docs/api/tutorial-debugging.html), which has a section called "Advanced: Loading the uncompiled library".  Loading the full, uncompiled library is what the Shaka team does when we are debugging Shaka Player.

**Comment by spyros-uk** [comment]
> You can use `./build/build.py --debug` to create a build with the original names. You can also use `shaka-player.compiled.debug.js` or `shaka-player.ui.debug.js` in the pre-built releases.

Thanks a lot for the suggestion @TheModMaker !
The `player.compiled.debug.js` is the one that I usually use. But all variables are "uglyfied" (not use about 2.x.x versions but for 3.x.x for sure), so this is not an option.


Using `./build/build.py --debug` makes things a bit better but the variable names get replaced.

<img width="983" alt="debug" src="https://user-images.githubusercontent.com/15960526/105876792-370b9980-5ff7-11eb-9421-422896d27bbf.png">


> If the renaming of local variables in the debug build is an issue, check out the [debugging tutorial](https://shaka-player-demo.appspot.com/docs/api/tutorial-debugging.html), which has a section called "Advanced: Loading the uncompiled library". Loading the full, uncompiled library is what the Shaka team does when we are debugging Shaka Player.

@joeyparrish thanks for pointing out the Advanced topic, being able to load the uncompiled library will be great!

Closing the issue to keep the issue tidy, will re-open if needed.
