### ISSUE TITLE
Audio Background Playback Question #2

### ISSUE THREAD

**Issue by baehongjun0212** [google/shaka-player#3113]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
3.0.7

**Please ask your question**
The code was used to play audio only without playing video. 
_**player.configure('manifest.disableVideo', true);**_
However, certain m3up files only play audio well, while mp4 files and other videos do not play both video and audio. What is this reason?

**Comment by joeyparrish** [comment]
You may be running into unsupported audio codecs.  For various reasons, we can't currently play containerless formats like raw AAC, which you sometimes find in HLS content.

Does this help?

**Comment by baehongjun0212** [comment]
thank you. I wonder how to play the video on canvas using the Shaka player. If you have any relevant information, please :)

**Comment by joeyparrish** [comment]
You can't display directly onto `<canvas>`, but you can copy from `<video>` to `<canvas>`: https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Manipulating_video_using_canvas

**Comment by baehongjun0212** [comment]
ou've been a great help. Thank you.

**Comment by joeyparrish** [comment]
Happy to help!
