### ISSUE TITLE
Correlation mediatimestamps with video.currenTime

### ISSUE THREAD

**Issue by duggaraju** [google/shaka-player#3117]
Hi,

I have a DASH VOD manifest with a large presentationTimeOffset  and emsg boxes in the fragments.  While the video plays fine, the video.currentTime seems to be offset by presentTimeOffset  so I get 0 based time.  However the startTime/endTime for the emsg event are absolute presentation times. I want to correlate the events in 'emsg' with the video time and not sure what is the best way to do that.  Is there a way to get presentationTimeOffset from the manifest object?  if not what is the recommended way to do this?

**Comment by joeyparrish** [comment]
The `startTime` field of the emsg event is meant to correlate to presentation times as seen in `video.currentTime`.  Can you please file a full bug report (using the bug template) with sample content so that we can take a look?  Thanks!
