### ISSUE TITLE
Subtitles on IE11

### ISSUE THREAD

**Issue by baseballbrad3** [google/shaka-player#312]
We're in the process of supporting IE11/PlayReady and I noticed that subtitle support is missing on IE11. (https://shaka-player-demo.appspot.com/support.html shows missing support and `getTextTracks()` returns an empty array.) I looked into it and saw that IE11 does not have an implementation of `VTTCue`, but does, however, have a `TextTrackCue` that looks to be compatible. I polyfilled `VTTCue` with `TextTrackCue` and subtitles were selectable, just like in Chrome. For what it's worth, I have seen other projects do something similar.

Are there any known issues with doing this? I do know styling subtitles doesn't work and I'm not sure if it's even possible to style IE's native subtitles.

Would it make sense to apply this polyfill along with the rest of the Shaka polyfills? The only reference to `VTTCue` I see is in the player.js `isTypeSupported(...)` method so updating it with knowledge of `TextTrackCue` may be all that's needed. I know you're working on Shaka v2 so I'm wondering if it even makes sense to address in v1.x or just in v2.

**Comment by joeyparrish** [comment]
Hi Brad,

In Shaka v1, we only supported VTT subtitles, and only if the browser supports VTT directly.  To show text in v1, we added a `<track>` element to the `<video>` and set `track.src` to the VTT URL.  We use the presence of `VTTCue` to determine if the browser supports VTT natively.

In Shaka v2, we parse VTT into individual cues and feed them to the browser using either `VTTCue` or `TextTrackCue`, whichever is available.  Therefore in v2, we can support any subtitle format we can parse in JavaScript, regardless of whether or not the browser supports that format natively.

So you should already be able to see VTT text in Shaka v2 on both IE11 and Edge.

We're getting very close to cutting v2 beta.  Would you be interested in giving the latest from the `master` branch a try?

**Comment by baseballbrad3** [comment]
Hey Joey,

Shaka v2 sounds great. We'll be sure to give that a shot when we get some time. I'm glad that this has already been addressed in v2.

Thanks for the reply!

**Comment by joeyparrish** [comment]
I'm going to go ahead and close this as working in v2 and working-as-intended (VTTCue checks) in v1.  Please let us know if it's not working for you in v2 and we will reopen and investigate.  Thanks!

**Comment by baseballbrad3** [comment]
Hey Joey, we're just now getting Shaka v2 implemented and I noticed a slight issue with IE/Edge's implementation of `TextTrackCue`. We have some poorly formatted subtitles that would appear to have the same start and end times (or a duration of zero). When IE/Edge try to create a new `TextTrackCue`, the object creation throws an exception of "Syntax Error" and halts all playback. 

Now, we certainly are to blame for the malformed VTT track, but I was wondering if it'd make sense to check that `end > start` prior to creation of the Cue. Since, in our case, the duration is zero and it'd never show up (even if the Cue was created correctly), we could simply skip the creation. Alternatively, we could wrap the `ret = new TextTrackCue(start, end, payload);` in a try/catch that doesn't halt playback if the creation fails.

What do you think? I'd be happy to create a pull request for the change. On the surface, this seems simple enough.

**Comment by joeyparrish** [comment]
I'm torn on that.  On the one hand, we could skip those and keep playback going.  On the other, wouldn't you want to find and fix that bad content instead of hiding the problem?

**Comment by joeyparrish** [comment]
Gotcha.  Well, we now support TTML, too, if that's helpful.

I filed #501 to track this issue.  We'll try to get it fixed.
