### ISSUE TITLE
Extra textTrack added

### ISSUE THREAD

**Issue by stuartflanagan** [google/shaka-player#3120]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
https://github.com/google/shaka-player/issues/2516

**What version of Shaka Player are you using?**
3.0.7

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
No I have not tried

**Are you using the demo app or your own custom app?**
Custom App

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Tizen 5.5

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What did you do?**

When enabling captions we see that only the mode of the textTrack of kind subtitles labeled `ShakaPlayer TextTrack` is set to Showing the other track is set to disabled. The disabled track is the one we want to see as it has a SRC reference to an external VTT file.

**What did you expect to happen?**
To see our text track loaded from the src attribute and displayed.
This is not an issue on Tizen 3&4 Just Tizen5&5.5 They use later versions of Chrome.

**What actually happened?**

**Comment by michellezhuogg** [comment]
Hello @stuartflanagan ,
Are you also seeing the issue with Shaka UI enabled (showing multiple text language selections), or only with native controls(showing "ShakaPlayer TextTrack") ?
Would you please share a manifest and text track with us, so that we can reproduce the issue?

**Comment by stuartflanagan** [comment]
HI @michellezhuogg I was using the Track element only. We are not using the UI as we need custom UI for the platform this is on. TV. I think we have found a solution to this and that is to not create the dom element but to use the Shaka supplied API for creating the track element. This is now working as expected. Thank you for your response.
