### ISSUE TITLE
Native controls not displaying

### ISSUE THREAD

**Issue by michellezhuogg** [google/shaka-player#3121]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v3.0.7

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Demo app

**What browser and OS are you using?**
Chrome on Mac OS

**What are the manifest and license server URIs?**
https://nightly-dot-shaka-player-demo.appspot.com/demo/#audiolang=es;textlang=es;uilang=en;asset=https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4;panel=ALL_CONTENT;panelData=HLS;build=uncompiled;nativecontrols

**What did you do?**
Disable the Shaka Control and start playback.

**What did you expect to happen?**
The control bar should show on mouse over.

**What actually happened?**
The control bar shows when the playback is starting, and cannot be displayed later.

**Comment by joeyparrish** [comment]
I found that `<div class="shaka-client-side-ad-container">` is blocking mouse events from getting to the native controls.
