### ISSUE TITLE
Subtitles are not displayed 

### ISSUE THREAD

**Issue by saringer** [google/shaka-player#3122]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.19

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Custom

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Chrome (Version 88.0.4324.96) on macOs Big Sur (Version 11.1)

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**
I'll provide the URIs to the Manifests via Email

**What did you do?**

* Select a specific Text Track provided by calling `getTextTracks()`
* There are two tracks(forced/full subtitles) sharing the same language, but they are distinguished by their Labels (forced_subs_de/subs_de)
* Load the track via `selectTextTrack(track)`

**What did you expect to happen?**
The selected Text-Track being displayed

**What actually happened?**
No Text-Tracks are displayed and a TypeError gets thrown

`TypeError: Cannot read property 'length' of undefined`

I was able to reproduce the issue on the latest Shaka-Demo with an 8 minute snippet of the content 

<img width="1673" alt="Screenshot 2021-01-27 at 12 55 16" src="https://user-images.githubusercontent.com/7473273/106014536-de530400-60bd-11eb-8d4a-d78951bf085c.png">

When testing the same Manifest on the Test-Player provided by Bitmovin the subtitle works properly
<img width="1567" alt="Screenshot 2021-01-27 at 12 56 06" src="https://user-images.githubusercontent.com/7473273/106014831-28d48080-60be-11eb-8e2c-df123c939e53.png">

On the Shaka-Demo both Audio- and Text-Tracks are only distinguished by there Language Codes (there are stereo/surround Audio-Tracks and forced/full Text-Tracks), but not by Labels. Maybe this might be related with the issue?

**Comment by michellezhuogg** [comment]
Hello @saringer , thank you for reporting!
We're not seeing the captions because you have empty lines between the time and the text content in vtt, and we assumed an empty line indicated a new cue.
1. Could you point me to any reference that empty lines are allowed between the time and the text content?
2. If not, we should handle the empty lines more explicitly, and display an error message.

> 00:06:53.860 --> 00:06:57.900
> 
> Bitte verzeihen Sie mirdas recht grausame Exempel,
> 
> 00:06:58.680 --> 00:07:01.680
> 
> das ich wegen des Regelbruchsstatuieren muss.
>

**Comment by saringer** [comment]
Hi @michellezhuogg ,

thank you for your quick response.

> Could you point me to any reference that empty lines are allowed between the time and the text content?


Indeed those blank lines should not be in the VTT and we need to look into that. Thank you for pointing that out. Since this is an error from our side, the issue can be closed :)

> If not, we should handle the empty lines more explicitly, and display an error message.

Having a more detailed error message hinting for the blank lines sounds good.

**Comment by joeyparrish** [comment]
We're going to close this as a content issue.  We can follow-up with more detailed error messages in the future, so I'll file a separate issue for that.

**Comment by joeyparrish** [comment]
See #3158 for the follow-up.  Thanks!
