### ISSUE TITLE
I wonder how to play two or three videos using the Shaka player.

### ISSUE THREAD

**Issue by baehongjun0212** [google/shaka-player#3123]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes
**Please ask your question**

Always thank you.
Can I play such a long video vertically on the right using the Shaka player?

When you press the m1 button, the main video on the left becomes a little smaller, and the long video on the right is played vertically.
If you press the m2 button, the main video will be a little smaller, and two vertical videos will be played on the right.
If you press the m3 button, there will be 3 long videos vertically and the main video will be played as a pop-up at the bottom left.

I wonder how the video size can be converted within html.
I wonder if I should use a method that specifies the location of video playback as coordinates, hides it, and represents it.

<img width="1034" alt="스크린샷 2021-01-28 오전 10 11 57" src="https://user-images.githubusercontent.com/55692618/106076572-2c661700-6153-11eb-9222-e6b7dae1576b.png">

**Comment by michellezhuogg** [comment]
Hello @baehongjun0212 ,

You can use Javascript to set the html elements' styles: https://www.w3schools.com/jsref/dom_obj_style.asp
For example, you can set the width of the video container (look for the classname ".shaka-video-container") element to make it smaller. 
You can change the "display" style to show or hide. 
Does that help? Thank you!

**Comment by joeyparrish** [comment]
Sounds like a CSS issue to me.  You can position and style the video element however you like.

**Comment by baehongjun0212** [comment]
> Hello @baehongjun0212 ,
> 
> You can use Javascript to set the html elements' styles: https://www.w3schools.com/jsref/dom_obj_style.asp
> For example, you can set the width of the video container (look for the classname ".shaka-video-container") element to make it smaller.
> You can change the "display" style to show or hide.
> Does that help? Thank you!

It helped a lot. Thank you.
