### ISSUE TITLE
Change playRangeStart and playRangeEnd after playback has started

### ISSUE THREAD

**Issue by floribon** [google/shaka-player#3124]
This is a different use case for the same request as #1863

We have a long DASH video, but only display clips of short durations from this video. For instance the source video is 1 hour long and each clip is 20 seconds long.

When displaying a particular clip, I am using `config.playRangeStart` and `config.playRangeEnd` to only load segments from that clip and not continue buffering beyond.

When the user wants to change clip to another one, I would like to simply seek to the beginning of this new clip. However it may be outside the current playRange, hence I would like to update it before changing the currentTime.

Problem: calling `shakaPlayer.configure({playRangeStart: newValue})` does not update the playRange and it is not possible to seek at the new value without reloading the manifest.

Alternative: Do not use `playRangeStart` and use `streaming.bufferingGoal` and `streaming.bufferBehind` to prevent loading segments outside of the current clip times. This isn't ideal because a clip may be very long and we want to preserve buffering many segments ahead of time.

**Comment by michellezhuogg** [comment]
Hello @floribon ,

Currently we ignore the config change of playRangeStart and playRangeEnd after the playback starts.
You can call `Player.applyPlayRange_()` in `Player.applyConfig_()` to update the timeline.

**Comment by floribon** [comment]
Thanks. Would you consider making one of these methods public (without the underscore in their name) since it seems acceptable to use them in some cases? I want to avoid using internal methods by policy. No worries if that's not planned.

**Comment by joeyparrish** [comment]
I don't think those are methods we should expose, but @michellezhuogg has made it so that play range changes are applied immediately.
