### ISSUE TITLE
Default audio track can't be reselected while playing with AirPlay

### ISSUE THREAD

**Issue by baseballbrad3** [google/shaka-player#3125]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes.

**What version of Shaka Player are you using?**
3.0.7

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
If https://nightly-dot-shaka-player-demo.appspot.com is `master`, then yes.

**Are you using the demo app or your own custom app?**
Custom app

**If custom app, can you reproduce the issue using our demo app?**
Yes, on the https://nightly-dot-shaka-player-demo.appspot.com demo app.

**What browser and OS are you using?**
macOS 10.15.7/Safari 14.0.2

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Apple TV 4k is the AirPlay target.

**What are the manifest and license server URIs?**
https://nightly-dot-shaka-player-demo.appspot.com/demo/#audiolang=en;textlang=en;uilang=en;asset=https://storage.googleapis.com/shaka-demo-assets/angel-one-hls/hls.m3u8;panel=ALL_CONTENT;panelData=HLS;build=uncompiled

**What did you do?**
1. Load an HLS clip on the nightly shaka demo app - https://nightly-dot-shaka-player-demo.appspot.com/demo/#audiolang=en;textlang=en;uilang=en;asset=https://storage.googleapis.com/shaka-demo-assets/angel-one-hls/hls.m3u8;panel=ALL_CONTENT;panelData=HLS;build=uncompiled
2. Start playback on Safari
3. Start the AirPlay playback on an Apple TV 4k
4. Change the audio language from English to a non-English track (such as Deutsch) from the Shaka player in Safari (as in, not from the Apple TV remote)
5. When playback resumes, try to change the audio language back to English (note that this example has two English tracks, but the default audio track appears to be at the bottom, and that's the one I'm attempting to switch back to)

**What did you expect to happen?**
I expected after switching the audio track to Deutsch, selecting English would switch the audio track to English.

**What actually happened?**
The audio track remained on Deutsch and did not switch back to English. When playing in Safari without AirPlay, Safari can change back to this track without any issues. If I copy the HLS manifest (https://storage.googleapis.com/shaka-demo-assets/angel-one-hls/hls.m3u8) into a new Safari tab, AirPlay from this player can switch between all audio tracks with no issues.

It's worth noting that when AirPlay-ing our own content on Shaka Player v3.0.7, our content only has one English track, which simplifies reproducing this error. The demo app doesn't support AirPlay on Shaka 3.0.7, as the change that added support is only in `master` (thus the use of the nightly demo app).

Also, I see some instability in playback on the nightly after switching audio tracks that I'm not seeing in our v3.0.7 app. It gets stuck buffering, from what I can tell. Seeking around the video can "fix" it.

There's also some other weirdness I've seen that may be worth creating their own issue for. Changing languages on the Apple TV do not report the change back, and the `variantchanged` event doesn't fire (not sure if that's even fixable). Also, I've seen times in the demo player where the video is playing on the Apple TV, but the progress bar in Safari doesn't progress along with it until you interact with the player. I've also seen the player sit after initializing AirPlay, and stays there until you click pause/play (either on the Apple TV or on Safari).

**Comment by joeyparrish** [comment]
> Start the AirPlay playback on an Apple TV 4k

Unfortunately, we don't have an Apple TV we can test with.

Also, it's worth noting here that AirPlay and language changes in Safari are both handled by Safari.  If we're calling some browser method incorrectly, that could cause the changes not to go through to the remote side.  But we don't actually interact with AirPlay directly.

Player's `selectAudioLanguage()` in src= playback on Safari will use the video element's `audioTracks` member to find a matching track, then set `track.enabled = true` to activate it.  So the way we pick a track is dirt-simple.  You may want to debug in `selectAudioLanguage()` and the private method `switchHtml5Track_()` to see what selection is made, and how we make it.  If you find an issue with that, please let us know.

The only way I can see that this could go wrong is if:

1. selectAudioLanguage() chose the wrong track to enable somehow
2. selectAudioLanguage() couldn't find a match and did nothing

**Comment by baseballbrad3** [comment]
@joeyparrish, I may have narrowed it down. Inside of `switchHtml5Track_()`, there is an assumption that `track.enabled = true;` will set all of the other `audioTracks` `enabled` value to `false`. When playing on a MacBook Pro with Safari 14.1, this is a correct assumption. However, while AirPlaying, the other tracks are not set to `false` leaving the `audioTracks` array with multiple enabled tracks. If you change the language 4 times to unique languages, you'd have 4 enabled tracks, for example.

 In some limited testing on Shaka 3.1.0, changing `switchHtml5Track_()` to disable the `currentTrack` did seem to fix it, but I'm not sure if that's going to break other things, if the order of changing `enabled` matters, or if looping over the entire `audioTracks` to clean up any track other than the new track is needed.

```javascript
    // This will reset the "enabled" of other tracks to false.
    track.enabled = true;
    currentTrack.enabled = false; // I added this line
```

For what it's worth, while debugging, I noticed I had a new AirPlay device on my network, which is a TCL Roku TV. I was able to recreate this behavior when AirPlaying to the TV as well as the Apple TV 4K, so it may be reproducible if you have any AirPlay capable devices.

**Comment by joeyparrish** [comment]
Brad, that sounds really reasonable.  As long as we're sure (currentTrack != track), and the user isn't changing track properties outside Shaka, then that added line would be sufficient.  Would you like to send a PR for that?

**Comment by baseballbrad3** [comment]
Joey, I'm still waiting to hear back from my company if I'm allowed to sign the CLA. If it makes sense for you or for someone else to make the change in the meantime, that'd probably be good.

And for what it's worth, I agree, we'd want to be sure that currentTrack != track.
