### ISSUE TITLE
How to add skip to 10 seconds forward/backward in video Button around BigPlayButton ?

### ISSUE THREAD

**Issue by sanjampreet-singh** [google/shaka-player#3127]
Any reference to documentation is also appereciated

**Comment by michellezhuogg** [comment]
Hello @sanjampreet-singh ,

Here's the [UI tutorial](https://shaka-player-demo.appspot.com/docs/api/tutorial-ui.html).
You can create [custom elements and add them to the UI](https://shaka-player-demo.appspot.com/docs/api/tutorial-ui-customization.html).

**Comment by sanjampreet-singh** [comment]
Yes, I do watched this example already but was not able to follow same...
Could you please insist providing details of functions or classes provided by shaka say to seek 10seconds forward on button click or something like that...

**Comment by michellezhuogg** [comment]
1. Would you please tell us what didn't work for you? We'd love to know what we can improve on our tutorials.
2. We will add a button to seek 10seconds forward in the future! Meanwhile, we also welcome contributions to implement that from the community.
