### ISSUE TITLE
PSSH box is missing after ffmpeg encryption

### ISSUE THREAD

**Issue by Duna** [google/shaka-player#3129]
I was able to reproduce your results with ffmpeg 4.1.3.  I tried re-encoding audio & video, I tried audio-only, I tried video-only, and I tried with flags to output fragmented mp4.

I got it to work with Shaka Packager for encryption, and playing back through a DASH manifest:

```sh
packager \
  input=SampleVideo_1280x720_1mb.mp4,stream=video,output=video.mp4 \
  input=SampleVideo_1280x720_1mb.mp4,stream=audio,output=audio.mp4 \
  --enable_raw_key_encryption \
  --keys key_id=a7e61c373e219033c21091fa607bf3b8:key=76a6c65c5ea762046bd749a2e632ccbb \
  --clear_lead 0 \
  --mpd_output dash.mpd
```

This plays through DASH & MediaSource w/ ClearKey for decryption, but if I try to play back one of the individual files (video.mp4 or audio.mp4) with src=, playback seems to fail.  I'm not sure why yet.  When this fails, `video.mediaKeys` is null, so I think that Shaka's `DrmEngine` doesn't set up ClearKey with src= for some reason.  It could be a lack of PSSH box in the mp4s.

_Originally posted by @joeyparrish in https://github.com/google/shaka-player/issues/2139#issuecomment-529566212_

**Comment by Duna** [comment]
ffmpeg -i /storage/emulated/0/Download/20210125_193031.mp4 -vcodec copy -acodec copy -encryption_scheme cenc-aes-ctr -encryption_key b42ca3172ee4e69bf51848a59db9cd13 -encryption_kid 09e367028f33436ca5dd60ffe6671e70 /storage/emulated/0/Download/out_enc.mp4

**Comment by Duna** [comment]
How to add the pssh box to the ffmpeg command line? it seems the mp4 output encrypted file does not contain pssh box

**Comment by joeyparrish** [comment]
@Duna, if this is a player question, can you please show us how you are playing this content in Shaka Player?  (configure() & load() calls in particular, but as much of the app as you can share.)

Otherwise, we can move this issue to the Shaka Packager repo for you if you need help with content creation.

**Comment by Duna** [comment]
I am trying to play on exoplayer. And it seems it is a confirmed issue. Pssh box is ignored.

**Comment by joeyparrish** [comment]
Okay, thanks for confirming.  In the future, please file exoplayer issues here instead: https://github.com/google/exoplayer
