### ISSUE TITLE
Any reference code to support Clearkey (cenc:pssh in mpd)?

### ISSUE THREAD

**Issue by amazinglalu** [google/shaka-player#313]
Hi 

I am trying to build an app to support Clearkey with initData in mpd as \<cenc:pssh/\>. I was able to implement Clearkey using 'webm' and 'keyids' initDataType. Are there examples to do the same with `cenc` initDataType? from what I understand, Shaka player can parse \<cenc:pssh/\> if present but there does not seem to be a way to get access it. My application is trying to make an external license request rather than providing the license inline.  
`var licenseServerUrl = 'data:application/json;base64,' + window.btoa(license); `

**Comment by joeyparrish** [comment]
I'm not sure I understand the question.  Are you using a release version of Shaka (v1.x) or the latest code in the `master` branch?

**Comment by amazinglalu** [comment]
I am using v1.6.4 for testing. In v1.6.4, `shaka.player.DrmInfo.config` can be set by implementing ` shaka.player.DashVideoSource.ContentProtectionCallback` and proving the preproccesor and postprocessor functions. I can set `initData` member with initDataType `keyids` and `webm`. I am trying to implement support for `cenc` type for ClearKey content protection scheme. Mpd already includes `cenc:pssh` xml element. As i understand, I do not need to overwrite `initData` as it should be populated from `cenc:pssh` box in mpd.  How can i get keyid information from that box in this callback and use it for license request url construction?

**Comment by joeyparrish** [comment]
Here's the normal path:

If you don't specify init data in the callback, `cenc:pssh` content is used if present.  Init data is passed to the CDM in `generateRequest()`, and the generated request is sent via HTTP POST to the license server URL you configured.

The generated request for clearkey looks like this: https://w3c.github.io/encrypted-media/#clear-key-request-format

So if you want the key IDs, use a license request pre-processor to parse the request:
```
function preprocessClearKey(licenseRequestInfo) {
  var requestBinary = licenseRequestInfo.body;
  var requestText = String.fromCharCode.apply(null, new Uint8Array(requestBinary));
  var request = JSON.parse(requestText);
  var key_ids_base64 = request.kids;
  console.log(key_ids_base64);
}
```

Does that help?

**Comment by amazinglalu** [comment]
Thanks Joey.

I was actually doing the same. But I found the issue with my
implementation. It was related to how I was handling multiple key
systemIds, including Youtube Clearkey system (`org.youtube.clearkey`).
Youtube key system was selected for my test video instead of what I was
expecting and `licenseRequestInfo.body` was empty in
`shaka.player.DrmInfo.licensePreProcessor`call.

Thanks again for the support.

--

*Ashok Lalwani *| Product Manager - Video | m: (469) 877-2067
fastly.com | @fastly <https://twitter.com/fastly> | LinkedIn
<http://www.linkedin.com/company/fastly>

**Comment by joeyparrish** [comment]
Happy to help!
