### ISSUE TITLE
Add setVpaidMode to the ima.js externs file

### ISSUE THREAD

**Issue by lyjimmy** [google/shaka-player#3134]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Is your feature request related to a problem? Please describe.**
I would like to call [google.ima.settings.setVpaidMode](https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/vpaid2js#enabling) in my application, but I get a compile error saying that setVpaidMode is never defined on google.ima.settings since it's not defined in the ima.js externs file.

**Describe the solution you'd like**
Add the google.ima.settings.setVpaidMode method and google.ima.ImaSdkSettings.VpaidMode enum to the externs file.

**Describe alternatives you've considered**

**Additional context**

**Comment by ismena** [comment]
Hi @lyjimmy 
Great catch! Would you be interested in creating a pull request for this?

**Comment by lyjimmy** [comment]
I just created #3135 :)

**Comment by ismena** [comment]
You're one step ahead of me :)
I'll go take a look now!
