### ISSUE TITLE
Shaka losing buffer and stalls to rebuffer although bandwidth estimation shows that there is enough bandwidth

### ISSUE THREAD

**Issue by bcupac** [google/shaka-player#3138]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
3.0.7

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `master`?**
yes

**Are you using the demo app or your own custom app?**
custom

**If custom app, can you reproduce the issue using our demo app?**
not yet

**What browser and OS are you using?**
Tizen 3

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
UN50M530D TIZEN-3.0-TRUNK2017-KantS-RELEASE_20201126.1

**What are the manifest and license server URIs?**

it doesn't seem title specific

**What did you do?**

play video on Tizen 3

**What did you expect to happen?**
smooth playback, with ABR switching to reflect network conditions

**What actually happened?**

When shaka is playing a video in full HD for example, it runs out of buffer, it stays in full HD 
and just buffers to {rebufferingGoal} then plays for the few seconds that it buffered, again stalls for rebuffering to {rebufferingGoal}, and all of the time shaka stats show that there is enough bandwidth to play at the given resolution/bitrate, so seems that something might be off with bandwidth estimation.
Its hard to reproduce, and 2.5.17 version seems to work fine.

**Comment by TheModMaker** [comment]
Can you please provide a playable manifest URL?  This will likely be content-specific.  You can also try to reproduce with the demo content.  Also, how are you telling that there is enough bandwidth?  Are you checking logs?  Please provide logs too.

Can you also try putting the manifest through <https://conformance.dashif.org/> with the `Segment Validation` option set?  This should help tell if your bandwidth attributes in the manifest are correct.

**Comment by caridley** [comment]
On Tizen TVs we have observed this behavior when there is memory pressure that prevents buffering more than a couple of segments. When this occurs we see quota exceeded errors in the debug logging.
