### ISSUE TITLE
GET_STATUS from sender side

### ISSUE THREAD

**Issue by zsoltbokor** [google/shaka-player#3140]
Hey,

I am using on both sender-receiver side shaka player provided proxy and receiver. 
I want to ask you guys if there is a way from sender to obtain the currently casting asset information (GET_STATUS on the generic bus), so what I set on the receiver with `setContentMetadata`.
I need to implement mini controller when the casting is on but I didn't find any way how to obtain that information and the **sender** is private in the `shaka.cast.CastProxy` so I can't send my own evet. 

Thanks in advance!

**Comment by TheModMaker** [comment]
If you are using a `CastProxy` instance, you can use `getPlayer()` to get a proxy Player object.  Then using `player.getAssetUri()` will return the URL of the asset you loaded.  You can also call the other methods on the Player and it will get the respective values from the Chromecast.  Is this what you are talking about?

**Comment by zsoltbokor** [comment]
> If you are using a `CastProxy` instance, you can use `getPlayer()` to get a proxy Player object. Then using `player.getAssetUri()` will return the URL of the asset you loaded. You can also call the other methods on the Player and it will get the respective values from the Chromecast. Is this what you are talking about?

I decided to not use CastProxy and also had to extend the receiver implementation. As I see the Shaka implementation is designed to send directly the manifest url and load that on the receiver but I have to pass a content id only for what on the receiver download the meta data, manifest url etc, init DRM flow and then load the manifest what I got back. I will close this issue. 
Thank you for your response!
