### ISSUE TITLE
a head request is done in Chrome when there is no extension in the URL

### ISSUE THREAD

**Issue by RonaldvB** [google/shaka-player#3142]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What link can we use to reproduce this?**
will provide when needed

**What version of Shaka Player are you using?**
v3.0.7-uncompiled

**What browser and OS are you using?**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36

**What did you do?**
We use an external service to do serverside add insertion into our HLS stream and/or VOD. However what we noticed is that the player is doing an HEAD request in chrome because there's no extension on the segments. I understand that this is done to determine the mime type, but the HEAD fails with a 404 and the streams stops.

**What did you expect to happen?**
I would expect if the HEAD fails, that the stream continues with a GET, OR that there's no HEAD request at all.

**What actually happened?**
The head request only seems to be done on chrome (not on safari and/or firefox).
chrome:
![image](https://user-images.githubusercontent.com/18549945/107063716-fc65e600-67da-11eb-8d68-804ff6103a02.png)
firefox:
![image](https://user-images.githubusercontent.com/18549945/107064362-b3faf800-67db-11eb-8d14-7cfd2224b7cf.png)

**Comment by RonaldvB** [comment]
I will provide a sample stream if needed

**Comment by TheModMaker** [comment]
If you could provide a manifest URL, it would help verify we got it.  But I think the problem is [here](https://github.com/google/shaka-player/blob/2371bd8591b1755f4ef1e1fee400db31e93b2893/lib/hls/hls_parser.js#L2405). 

The problem is that if we make a full request, it will download a large segment that we'll just throw away (and the browser may not cache it correctly).  If we try a partial request, it may not be supported by the web server and require us to make a full request anyway.  Since this seems like an edge case and would require downloading large segments, I'm going to mark this as an enhancement and put it on the backlog.

**Comment by joeyparrish** [comment]
Here's an idea: how about if there's no extension and a HEAD request fails, we fall back to assuming it's MP4?  This will only impact HLS content which is lacking in both MIME type metadata and segment file extensions.  It would be cheap and easy to implement, and could be cherry-picked to v3.0.x and v2.5.x.

**Comment by surajkumar-sk** [comment]
@joeyparrish If I understand this issue correctly, `hlsparser.js` tries to guess the MIME type inside `guessMimeType_(...)`. It starts with checking the extension of URI inside the first found segment type  `EXT-X-MAP`. when it fails to map it to any audio, video, or text it attempts to send a Head request to segment URI, it gets the header of URI as a response. If it fails to get any extension in the header it throws an error. so for a possible solution, you are proposing to replace throwing an error inside if with a return statement of MimeType as MP4 as per the content type.  so,

Replacing this

```
if (!contentMimeType) {
      throw new shaka.util.Error(
          shaka.util.Error.Severity.CRITICAL,
          shaka.util.Error.Category.MANIFEST,
          shaka.util.Error.Code.HLS_COULD_NOT_GUESS_MIME_TYPE,
          extension);
    }
```

with this 

```
if (!contentMimeType) {
      // if the HLS content is lacking in both MIME type metadata and segment file extensions
      // we fallback to assuming its MP4.
      contentMimeType = map[" "];
      return contetMimeType;
    }
```

```
shaka.hls.HlsParser.AUDIO_EXTENSIONS_TO_MIME_TYPES_ = {
  .....

  ' ': 'audio/mp4',

  .....
};

shaka.hls.HlsParser.VIDEO_EXTENSIONS_TO_MIME_TYPES_ = {
  ......

  ' ': 'video/mp4',
};

shaka.hls.HlsParser.TEXT_EXTENSIONS_TO_MIME_TYPES_ = {
 ..... 

  ' ': 'application/mp4',

 .....
};
```

I don't have a file to reproduce this issue and try the solution so posting it here. Should I add a pr with these changes or is there something wrong with this solution?
