### ISSUE TITLE
Sometimes subtitles are stacked on LG SmartTVs

### ISSUE THREAD

**Issue by adgllorente** [google/shaka-player#3151]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes.

**What version of Shaka Player are you using?**
Latest.

**Can you reproduce the issue with our latest release version?**
Yes.

**Can you reproduce the issue with the latest code from `master`?**
Yes.

**Are you using the demo app or your own custom app?**
Own app.

**If custom app, can you reproduce the issue using our demo app?**
Not tried.

**What browser and OS are you using?**
SmartTV

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
LG SmartTV

**What are the manifest and license server URIs?**

**What did you do?**
1. Playback a stream with active subtitles

**What did you expect to happen?**
1. Subtitles are properly shown.

**What actually happened?**
Subtitles are shown stacked. Sometimes one subtitle is shown without removing the previous one.

**Comment by joeyparrish** [comment]
JFYI, Chrome, Edge, and Safari all get this wrong in their native cue rendering.  FF & IE/legacy Edge get it right.

I filed these issues with the browser vendors to make the same/similar fix in the browser for native cue display:
 - https://bugs.chromium.org/p/chromium/issues/detail?id=1178026
 - https://bugs.webkit.org/show_bug.cgi?id=221854
