### ISSUE TITLE
Add DAI examples to DEMO app

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#3154]
Right now in the DEMO application there are no DAI examples.

I would like you to add these: https://developers.google.com/interactive-media-ads/docs/sdks/html5/dai/streams

![image](https://user-images.githubusercontent.com/8983024/107657344-61ab5280-6c85-11eb-8d77-6249309a413b.png)

**Comment by ismena** [comment]
So, we do have a [VOD DAI asset](https://nightly-dot-shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://storage.googleapis.com/shaka-demo-assets/tos/hls.m3u8;panel=ALL_CONTENT;panelData=ADS;build=uncompiled), but we can definitely add at least a LIVE one, so we have examples of both LIVE and VOD.
