### ISSUE TITLE
Packaging without DRM

### ISSUE THREAD

**Issue by FireMasterK** [google/shaka-player#3156]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.8

**Please ask your question**
Is there any way to ship/package shaka-player without any references to DRM / EME?

I would just like to use the Dash functionality.

**Comment by ismena** [comment]
Hi @FireMasterK 
Not at this time, sorry :( we have #1017 to address it, but it hasn't happened yet.

If you only want dash, we can help with excluding HLS from the build, though.
Will this help?

**Comment by FireMasterK** [comment]
Unfortunately not in my case :( I need HLS unfortunately

My concern is that it requests for permission to run drm on Firefox, even if doesn't need drm

I've noticed this behaviour on the demo page

My application is against the concepts of DRMs and believes in FOSS, ideally I would love a way to not include any DRM code :D

**Comment by TheModMaker** [comment]
This is because the demo uses `player.probeSupport` function, which queries EME.  If you don't call this, we won't query EME until we play DRM content.  We don't use any DRM unless you play protected content.

**Comment by joeyparrish** [comment]
Yes, the demo behavior of probing for DRM support is so we can disable DRM-requiring assets if DRM is unavailable.  The library itself will not do this in your app.

As for the "FOSS should not have DRM", DRM support is entirely contained within the browser.  We have logic to engage with the browser-provided DRM API (MediaKeys / Encrypted Media Extensions), but the DRM implementation is entirely inside the browser.  Shaka Player works just fine for clear content in non-DRM-enabled browsers, and DRM support is never a requirement for Shaka.

@FireMasterK, does this answer all of your concerns?
