### ISSUE TITLE
Can't choose a very previous point in the seekbar although segment exists in DASH streaming

### ISSUE THREAD

**Issue by Kotekczu** [google/shaka-player#3157]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes.

**What version of Shaka Player are you using?**
3.0.8.

**Can you reproduce the issue with our latest release version?**
Yes.

**Can you reproduce the issue with the latest code from `master`?**
Yes.

**Are you using the demo app or your own custom app?**
Demo.

**If custom app, can you reproduce the issue using our demo app?**
.

**What browser and OS are you using?**
Firefox on Windows 10.

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
.

**What are the manifest and license server URIs?**

Sent by email.

**What did you do?**

1. Set manifest.availabilityWindowOverride to 7200.
2. Play the DASH live stream.
3. Choose a point in the seekbar before -1:06:00, such as -1:20:00 or -1:40:00, to go back in time.

**What did you expect to happen?**
The player should play the stream.

**What actually happened?**

The player loads the segment but stucks and doesn't play the content. It's working fine on 2.5.x.

**Comment by TheModMaker** [comment]
Make sure to override `manifest.dash.initialSegmentLimit` with a larger value (default 1000).  This controls the number of segments that we'll initially load backwards.  If you have a huge number of segments, we won't load them all since it takes up a large amount of memory.

**Comment by Kotekczu** [comment]
Thank you, that helped!
