### ISSUE TITLE
Cannot read property 'Player' of undefined

### ISSUE THREAD

**Issue by huglester** [google/shaka-player#316]
Hello,

I have just compiled the shaka player, trying first 'example' from here:
https://shaka-player-demo.appspot.com/docs/tutorial-player.html

but getting: Uncaught TypeError: Cannot read property 'Player' of undefinedinitPlayer @ shaka.html:26

Is this a problem with example Or I have built some wrong version of shaka-player?

Thank you

**Comment by Pierpaolo1992** [comment]
Still problem, even if i'm using version 1.6.x. My code is the following:

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>TurtleTube - Basic Test</title>
    
  <script src="third_party/closure/goog/base.js"></script>
  <script src="dist/deps.js"></script>
  <script src="shaka-player.uncompiled.js"></script>
  </head>
  <body>
    <video id="video"
           width="640" height="480"
           crossorigin="anonymous"
           controls>
      Your browser does not support HTML5 video.
    </video>
  </body>
  <script>
    function initPlayer() {
      // Install polyfills.
      shaka.polyfill.installAll();

      // Find the video element.
      var video = document.getElementById('video');

      // Construct a Player to wrap around it.
      var player = new shaka.player.Player(video);

      // Attach the player to the window so that it can be easily debugged.
      window.player = player;

      // Listen for errors from the Player.
      player.addEventListener('error', function(event) {
        console.error(event);
      });

      // Construct a DashVideoSource to represent the DASH manifest.
      var mpdUrl = 'https://turtle-tube.appspot.com/t/t2/dash.mpd';
      var estimator = new shaka.util.EWMABandwidthEstimator();
      var source = new shaka.player.DashVideoSource(mpdUrl, null, estimator);

      // Load the source into the Player.
      player.load(source);
    }
    document.addEventListener('DOMContentLoaded', initPlayer);
  </script>
</html>

**Comment by joeyparrish** [comment]
@Pierpaolo1992, there is nothing obviously wrong with the code, but if you are loading Shaka Player v2, this will not work.  `shaka.player.Player` in v1 became `shaka.Player` in v2.

When you open this page in the browser, open the JS debugger.  Type this to see what version you have loaded:

```js
shaka.player && shaka.player.Player.version || shaka.Player.version
```

That will display the version number, both for v1 and v2 releases.
