### ISSUE TITLE
Live stream is not playing when SAMSUNG TV returns from standby.

### ISSUE THREAD

**Issue by abhisheklalnediya** [google/shaka-player#3161]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
YES

**What version of Shaka Player are you using?**
3.0.7

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `master`?**
not checked

**Are you using the demo app or your own custom app?**
custom app,

**If custom app, can you reproduce the issue using our demo app?**
not checked

**What browser and OS are you using?**
SAMSUNG TIZEN, 

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
SAMSUNG TIZEN 2018, 2020

**What are the manifest and license server URIs?**

**What did you do?**

1.  Start a live stream playback
2. Exit the app
3. let the tv like it for **8hrs**
4. tv will go stand by after some time.
5. Turn on TV avter 8hrs
6. Open the app
7. Start the stream playback

**What did you expect to happen?**
The stream should play

**What actually happened?**

1. The stream is not playing
2. The manifest is getting called frequently.
3. Dash Chunks are called initially, later only manifest is called
4. This is happening only for LIVE streams for Samsung. 

**Network calls attached**
![Screenshot_21](https://user-images.githubusercontent.com/3649024/107897698-c4d80600-6f5f-11eb-82f1-b3838b387a82.png)

![Screenshot_22](https://user-images.githubusercontent.com/3649024/107897699-c6093300-6f5f-11eb-847f-8964f3e1d3c9.png)

![Screenshot_23](https://user-images.githubusercontent.com/3649024/107897693-c1447f00-6f5f-11eb-9931-068cbc2772ae.png)
Mostly observed in high end TVs

**Comment by michellezhuogg** [comment]
Hello, looks like the content were download, and we'd like to get more shaka logs with more details if that's possible.
You may try to set the shaka log level by:
shaka.log.setLevel = shaka.log.Level.V2;

Please let us know if you get more logs. Thank you!

**Comment by joeyparrish** [comment]
Does it help to seek or pause/play after waking up the device from standby?

Is the live stream still available at the same manifest URL after waking up the device, or has the stream ended?

**Comment by abhisheklalnediya** [comment]
The issue is with DRM, I was using  widewine, it's working fine with Playready
