### ISSUE TITLE
Error while initializing data for CENC with Widevine

### ISSUE THREAD

**Issue by subhendusethi** [google/shaka-player#3162]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
``3.1.0-pre``

**Please ask your question**
Hi.

I am trying to initialize a dash manifest file generated by my organization using Shaka Player.

Upon doing so I am getting the following error:  Error code `6006`: `Failed to execute 'generateRequest' on 'MediaKeySession': Initialization data for CENC is incorrect.`. Upon debugging I see that [``generateRequest``](https://github.com/google/shaka-player/blob/master/lib/media/drm_engine.js#L1131) method upon being called with the initDataType of 'cenc' and the Uint8Array representation of the widevine pssh key from the manifest file is failing.

I have talked internally to our Widevine service team and they have mentioned they are using the standard external pssh generator version 1.4.0 and the WidevineSDK version 16.3.1 and as they dont have experience with shaka's client are unsure what is wrong here.

I have tested this with multiple manifest files our org generates and every-time I am getting the same result. I am suspecting there is a discrepancy of what shaka player expects the pssh format to be and what we actually generate.

Is there a private channel by which I can share the manifest file with you so that you can have a look at it and let me know what is wrong?

Thanks in advance for the help.

**Comment by subhendusethi** [comment]
Hi team.

Any help here would be appreciated.

Thanks!

**Comment by michellezhuogg** [comment]
Hello @subhendusethi , you can send your manifest to shaka-player-issues@google.com . Thank you!

**Comment by TheModMaker** [comment]
We haven't received anything from you.  Can you please send us some content to test with if this is still an issue for you.  Please include "#3162" in the subject so it is easy to find what it is for.
