### ISSUE TITLE
Content with large gap sometimes does not work

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#3163]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes

**What version of Shaka Player are you using?** 3.0.7

**Can you reproduce the issue with our latest release version?** Yes

**Can you reproduce the issue with the latest code from `master`?** Yes

**Are you using the demo app or your own custom app?** Both

**If custom app, can you reproduce the issue using our demo app?** Yes

**What browser and OS are you using?**
Chrome 88 over macOS 10.15.7 (In Chrome on any platform the issue is reproduced.)

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

I'll send it separately

**What did you do?**

Enable jumpLargeGaps config.
Load the previous stream
Seek to 1:08:36
Wait to 1:08:39

**What did you expect to happen?**
The stream continues without problem

**What actually happened?**

The stream is stopped without any kind of progress.

I've been researching the problem, and it seems we need a higher gap threshold for the stream to work. I'm going to send a PR so I can make this configurable.

**Comment by caridley** [comment]
We have seen this problem as well. With our streams in Chrome the player freezes prior to gaps about 20% of the time. When we change the gap jump threshold from 0.1 to 1 sec we no longer see the problem. Would prefer to have a configurable gap jump threshold

**Comment by avelad** [comment]
Note: the link that I have sent privately is only available until March 3 because it is an NPVR recording (circular buffer)
