### ISSUE TITLE
shaka-player error angular universal

### ISSUE THREAD

**Issue by tebib91** [google/shaka-player#3164]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
3.0.5
**Can you reproduce the issue with our latest release version?**
No

**Can you reproduce the issue with the latest code from `master`?**
No

**Are you using the demo app or your own custom app?**
custom app

**If custom app, can you reproduce the issue using our demo app?**
No

**What browser and OS are you using?**
chrome 

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Angular 9

**What are the manifest and license server URIs?**

**What did you do?**

add angular universal to my project

**What did you expect to happen?**
angular SSR render project

**What actually happened?**

error  ReferenceError: HTMLMediaElement is not defined

![Screenshot from 2021-02-15 16-15-25](https://user-images.githubusercontent.com/26254350/107963925-093bc400-6fa9-11eb-97cb-90e65b47f709.png)

**Comment by joeyparrish** [comment]
`HTMLMediaElement` is indeed not defined in a server-side node.js environment.  Can you elaborate a bit on what you're trying to do by combining Shaka Player and server-side rendering?
