### ISSUE TITLE
Disable window.__onGCastApiAvailable rewriting

### ISSUE THREAD

**Issue by mkozlov1** [google/shaka-player#3167]
Hi.

I want to implement my own chromecast sender/receiver apps. But on shaka js load it rewrites window.__onGCastApiAvailable handler by its own.
Is it possible to disable __onGCastApiAvailable rewriting?

**Comment by joeyparrish** [comment]
Your best option in current versions is to create a custom build without the Shaka Cast API:

```sh
python build/build.py --name no-cast +@complete -@cast -@ui
```

This will create `dist/shaka-player.no-cast.js`, which will not have the `shaka.cast` namespace or the UI.

Currently, the UI relies on the Cast APIs being available.  If you'd like the rest of the UI to work without the Cast APIs in the build, we can create a feature request ticket for that.

If you'd prefer to leave everything in the build and just disable our Cast code at runtime (by not configuring a receiver app ID in the UI or by not constructing a `shaka.cast.CastProxy` in your app), we can create a feature request ticket for that, too.  (It would probably just involve moving the `__onGCastApiAvailable` handler to inside the `init()` method of `CastSender`.)

Does this help?

**Comment by mkozlov1** [comment]
Hi.

Today we use compiled version without UI and have no needs to recompile. I think this

> If you'd prefer to leave everything in the build and just disable our Cast code at runtime (by not configuring a receiver app ID in the UI or by not constructing a shaka.cast.CastProxy in your app), we can create a feature request ticket for that, too. (It would probably just involve moving the __onGCastApiAvailable handler to inside the init() method of CastSender.)

will be the best option.
