### ISSUE TITLE
Externally accessing xhr property on error object created by shaka.util.AjaxRequest.prototype.createError_

### ISSUE THREAD

**Issue by wader** [google/shaka-player#317]
Hi, i'm trying to display error messages based on the body returned in failed HTTP requests (auth, geo error etc). I see that the `XMLHTTPRequest` object with status and body is available under the `details` property of the error object passed to the error handler. The problem is that in the compiled version the `xhr` property name has been mangled by the closure compiler.

To make it work i guess i have to add something to `externs/` but not sure how. Just a file with `Error.xhr;`? The error object is created in lib/util/ajax_request.js:shaka.util.AjaxRequest.prototype.createError_.

Maybe there is some better way of doing this?

Currently using shaka-player 1.6.4.

**Comment by joeyparrish** [comment]
Sorry, that would be a bug on our part.  The fix is to quote the parameter: `error['xhr'] = xhr;`

We're focusing on v2 now, but if you make a pull-request against against the v1.6.x branch, I'd be happy to review it.

**Comment by joeyparrish** [comment]
Fixed in #319
