### ISSUE TITLE
Error 5005 on play

### ISSUE THREAD

**Issue by rhosny** [google/shaka-player#3171]
Hi,
I get an error 5005 "invalid STREAM) once play this stream 👍 
<?xml version="1.0" encoding="UTF-8"?><MPD xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="urn:mpeg:dash:schema:mpd:2011" xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011 DASH-MPD.xsd" profiles="urn:mpeg:dash:profile:isoff-live:2011" id="dash4k/4k_bbright_v11" type="dynamic" minBufferTime="PT5.000S" maxSegmentDuration="PT2.112S" availabilityStartTime="1970-01-01T00:00:00.000Z" publishTime="2021-02-19T17:50:45.473Z" minimumUpdatePeriod="PT1.920S" timeShiftBufferDepth="PT182.540S"><Period id="6079963961" start="PT1613727455.026S"><AssetIdentifier schemeIdUri="urn:eidr" value="md:cid:EIDR:10.5240%2f075a-8ef4-c981-07f1-C"/><AdaptationSet id="1" contentType="video" mimeType="video/mp4" segmentAlignment="true" startWithSAP="1" maxWidth="3840" maxHeight="2160" maxFrameRate="50" par="16:9"><SegmentTemplate timescale="90000" initialization="$RepresentationID$-Header.m4s" media="$RepresentationID$-0-T-$Time$.m4s" presentationTimeOffset="6079963961"><SegmentTimeline><S t="8726673925" d="172800" r="5"/><S d="183600"/><S d="172800" r="20"/><S d="174612"/><S d="172800" r="65"/></SegmentTimeline></SegmentTemplate><Representation id="v0_121" bandwidth="20000000" codecs="hvc1.2.4.L183.90" width="3840" height="2160" frameRate="50" sar="1:1" scanType="progressive"/></AdaptationSet><AdaptationSet id="2" contentType="audio" mimeType="audio/mp4" segmentAlignment="true" startWithSAP="1" lang="und"><Role schemeIdUri="urn:mpeg:dash:role:2011" value="main"/><SegmentTemplate timescale="90000" initialization="$RepresentationID$-Header.m4s" media="$RepresentationID$-0-T-$Time$.m4s" presentationTimeOffset="6079963961"><SegmentTimeline><S t="8726675196" d="172800" r="5"/><S d="184320"/><S d="172800" r="20"/><S d="174971"/><S d="172800" r="65"/></SegmentTimeline></SegmentTemplate><Representation id="v0_221" bandwidth="128000" codecs="mp4a.40.5" audioSamplingRate="48000"><AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/></Representation></AdaptationSet></Period><UTCTiming schemeIdUri="urn:mpeg:dash:utc:direct:2014" value="2021-02-19T17:50:45.473Z"></UTCTiming></MPD>

The tested versions 2.5.10 & 2.5.20

could you help what is wrong with this stream and what is the supported versions of Shaka player if any?
the Stream URL  is avalable for test if needed.

Best,
RHO

**Comment by michellezhuogg** [comment]
Hello @rhosny ,

Please follow our [bug report](https://github.com/google/shaka-player/issues/new?assignees=&labels=&template=bug_report.md&title=) or [question](https://github.com/google/shaka-player/issues/new?assignees=&labels=question&template=question.md&title=) template so that we can get more details to help you resolve the issue?
You can send the URIs to <shaka-player-issues@google.com> if it's private. Thank you!
