### ISSUE TITLE
Shaka downloads only the first audio track in manifest file.

### ISSUE THREAD

**Issue by olirehacek** [google/shaka-player#3173]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.8

**Please ask your question**
Hi,
I have a widevine manifest file - a video with multiple audio tracks (3). When I try to download the content to local storage only the first audio track gets downloaded. I can see in the console, that other audio tracks URLs are accessed too, but not really downloaded. While stored offline it only contains one (first) audio track from the source manifest. I need all of the audio tracks stored locally with the video.

Is there any way to download locally multiple audio files ?

Any idea what can cause this ?

**Comment by ismena** [comment]
To the best of my knowledge, this is expected behavior. (Offline logic predates me :)) We select a variant and only download it.
Let me tag the offline expert for more information. @TheModMaker am I right about this? What's the thought behind this logic?

**Comment by olirehacek** [comment]
@ismena Thank You, I have managed to solve the issue by specifying the **trackSelectionCallback**.
I see that I have all of the audio tracks downloaded, but it is not possible to switch them in the standard HTML <video> element. 

How are you guys implementing the audio track switcher in the video element in the shaka player demo, is that some sort of customized video element ? Thank You.

**Comment by joeyparrish** [comment]
Video elements have no API for switching audio tracks (except in Safari with Apple's native HLS).

Switching audio tracks is done through a method on the `Player` object, or through our optional UI.

If you're building your own UI, call `player.getAudioLanguages()` and `player.selectAudioLanguage()` or `player.getVariantTracks()` and `player.selectVariantTrack()`.

If you're using browser-native controls (`<video controls>` attribute or `video.controls = true` in JavaScript), then you will not have any UI to change audio tracks.  Browsers don't offer this natively (except Safari with Apple's native HLS).

**Comment by olirehacek** [comment]
> @olirehacek Does this answer all your questions? Can we close the issue?

yes
