### ISSUE TITLE
custom button

### ISSUE THREAD

**Issue by nargesghahremani** [google/shaka-player#3177]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?yes

**What version of Shaka Player are you using?2.5.2

question: how can i add custom button next to the full screen button in straight way?

> Let's say, we want to create a button that allows user to skip the currently playing video and go to the next one.

> // skipButton.js

> // Use shaka.ui.Element as a base class
> myapp.SkipButton = class extends shaka.ui.Element {....
> 

I read the document but did not understand what to do:)))  !! Please help more
i want implement something like this picture(auto play button)...
In my opinion, it would have been better to at least implement a fully custom button in demo or document:)) !!! , or if there was, I couldnt find it.
![Selection_031](https://user-images.githubusercontent.com/51996104/108841912-bf2c9100-75ed-11eb-8835-70173c650cf0.png)

**Comment by ismena** [comment]
Hi @nargesghahremani 
Maybe a [close button from our demo](https://github.com/google/shaka-player/blob/master/demo/close_button.js) would be a suitable example?

Also, let me try and walk you through the tutorial that you mentioned - basically, you create a new file for your custom button. This part of the tutorial is creating a class, based on our shaka.ui.Element class:
```
// "myapp" is your namespace
myapp.SkipButton = class extends shaka.ui.Element {
// This part you can directly copypaste
  constructor(parent, controls) {
    super(parent, controls);

    // This.button is your actual button, the next line is creating it and adding to your class
    this.button_ = document.createElement('button');
    // textContent is the text of the button. Looking at the button you want to create (on the screenshot), sounds like you 
    // don't need it.
    this.button_.textContent = 'Skip current video';
    // This part adds the button to the control panel. This you do need!
    this.parent.appendChild(this.button_);

    // This is a listener that tells the button what to do when the button is clicked
    this.eventManager.listen(this.button_, 'click', () => {
      // Your logic on what to do when the button is clicked will go here!
    });
  }
};
```

Next is creating a factory for your button, so we can use and see it inside the UI lib.
You can copypaste this, just change the name to your button (instead of SkipButton)
```
myapp.SkipButton.Factory = class {
  create(rootElement, controls) {
    return new myapp.SkipButton(rootElement, controls);
  }
};
```

For the last part, you'll need to come up with a name for your button, You will use this name to configure and add your button to the UI.
This code is telling the UI controls that there is a buttom with this name that can be added to the UI.
```
shaka.ui.Controls.registerElement(
  /* This name will serve as a reference to the button in the UI configuration object */ 'skip',
  new myapp.SkipButton.Factory());
```

After all of this is done, in your main code, you can reconfigure UI like this:
```
const video = document.getElementById('video');
const ui = video['ui'];
const uiConfig = ui.getConfiguration();
uiConfig.controlPanelElements.push('yourButtonName');
ui.configure(config);
```

Does this help?

**Comment by nargesghahremani** [comment]
hi @ismena :)

Thanks for the reply
Yes, it was very helpful and thank you
and its my code that works well :))
```
// autoplay_button
var MYAPPLICATION = MYAPPLICATION || {};
MYAPPLICATION.AutoplayButton = class extends (
  shaka.ui.Element
) {
  constructor(parent, controls) {
    super(parent, controls);

    this.button_ = document.createElement("button");

    this.button_.classList.add('material-icons-round');
    this.button_.classList.add('autoplay-button');
    this.button_.setAttribute("title", "پخش خودکار")
    // this.button_.textContent = "autoplay";
    this.parent.appendChild(this.button_);

    this.eventManager.listen(this.button_, "click", () => {
      this.button_.classList.toggle('change');
    });
    
  }
};

MYAPPLICATION.AutoplayButton.Factory = class {
  create(rootElement, controls) {
    return new MYAPPLICATION.AutoplayButton(rootElement, controls);
  }
};
```

```
//main.js
     <script src="autoplay_button.js"></script>
     ....
      const ui = new shaka.ui.Overlay(player, videoContainer, video);
      const controls = ui.getControls();
      shaka.ui.Controls.registerElement(
        'autoplay',
        new MYAPPLICATION.AutoplayButton.Factory()
      );
      const uiConfig = ui.getConfiguration();
      if (!uiConfig.controlPanelElements.includes('autoplay')) {
        uiConfig.controlPanelElements.push('autoplay');
      }
 const config = {
        'controlPanelElements': ["play_pause", "time_and_duration", "spacer", "autoplay", "mute", "volume", "fullscreen", "overflow_menu"]
      };
      ui.configure(config);
```

**Comment by ismena** [comment]
Nice!
Glad we could help 

Out of curiosity - what is the language on the title? Looks like Farsi to me, but I'm not 100% sure :)

**Comment by nargesghahremani** [comment]
> Nice!
> Glad we could help
> 
> Out of curiosity - what is the language on the title? Looks like Farsi to me, but I'm not 100% sure :)

Yes it is farsi:)
