### ISSUE TITLE
Disable loading of previous segment on seeking 

### ISSUE THREAD

**Issue by hcodes** [google/shaka-player#3178]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Is your feature request related to a problem? Please describe.**

We conducted an experiment and got a significant reduction (up to 20%) of stalled on seeking. 
https://github.com/yandex-pcode/shaka-player/pull/6/files

The code in shaka is needed for inaccurate manifests.
https://github.com/google/shaka-player/issues/330

Perhaps a separate setting is needed for this? 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by TheModMaker** [comment]
You can use the `streaming.inaccurateManifestTolerance` configuration.  Setting this to `0` disables downloading the previous segment.  Otherwise it is the number of seconds that the manifest can be inaccurate for (i.e.  5 means the segments will only be off by 5 seconds).
