### ISSUE TITLE
Overlay incorrectly placed

### ISSUE THREAD

**Issue by FireMasterK** [google/shaka-player#3180]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.8

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Haven't tried

**Are you using the demo app or your own custom app?**
custom

**If custom app, can you reproduce the issue using our demo app?**
No

**What browser and OS are you using?**
Windows 10, Brave

**What are the manifest and license server URIs?**
Not the issue

**What did you do?**
```
        <div data-shaka-player-container>
            <video
                data-shaka-player
                controls
                autoplay
                style="width: 100%; height: 100%"
            ></video>
        </div>
```

```
                                           const ui = new shaka.ui.Overlay(
                                                player,
                                                document.querySelector(
                                                    "div[data-shaka-player-container]"
                                                ),
                                                videoEl
                                            );
                                            const config = {
                                                overflowMenuButtons: ["quality"]
                                            };
                                            ui.configure(config);
```
![image](https://user-images.githubusercontent.com/20838718/109108657-f3bd5b80-7759-11eb-8ff9-526f7719795b.png)
(You might have to zoom in, it is very faint)

**What did you expect to happen?**
Overlay placed correctly

**What actually happened?**

You can see two sets of buttons, the overlay is placed above the controls.

**Comment by ismena** [comment]
Hi! Deleting the "controls" attribute on the video element will solve this.
This attribute enables native browser controls, to which you add Shaka controls with your code. This you end up having 2 sets, one on top of the other :)

**Comment by FireMasterK** [comment]
Thanks! That did the trick 👍
