### ISSUE TITLE
Resolutions Higher than 1080p in quality selector

### ISSUE THREAD

**Issue by FireMasterK** [google/shaka-player#3181]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.8

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Not tried.

**Are you using the demo app or your own custom app?**
Yes

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Windows 10, Brave

**What are the manifest and license server URIs?**
I can provide this on request, unfortunately, they last only 6 hours.

**What did you do?**
Load a dash with streams of resolutions > 1080p

**What did you expect to happen?**
Being able to see and select such a resolution.

**What actually happened?**
I'm unable to see resolutions higher than 1080p

![image](https://user-images.githubusercontent.com/20838718/109131356-bcaa7280-7778-11eb-9bab-1e23d3ac64b6.png)

**Comment by TheModMaker** [comment]
There should be nothing in the UI that filters the resolution.  Are the other tracks present in `player.getVariantTracks()`?  Is the content encrypted?    What is probably happening is the content is encrypted and the license server didn't give us the keys for the higher quality.  Another option is the content isn't supported by the browser.  This is probably content-specific, so we'd need a test URL to debug  this.

**Comment by FireMasterK** [comment]
My content does not have any DRM, so that's not an issue here.

I will try your other suggestions and report back. 👍

**Comment by joeyparrish** [comment]
Please try in Chrome.  If the higher resolutions show up in Chrome but not Brave, it is likely an aggressive anti-fingerprinting measure in Brave which reports false information when we query about supported streams.

I have been anticipating this as a possibility in Brave or Duck Duck Go for a long time now, but I still hope this is not the case.  If Brave and other privacy-focused browsers start lying about media capabilities, it will be very difficult to provide a good experience for users in that environment.

**Comment by FireMasterK** [comment]
I tried chrome and chromium to no avail.

I think I may have discovered why this issue exists.

When you have both WEBM and MP4 streams in your dash file, it only shows those formats which have the same resolution for both.

Let say we have these in the dash file:
2160p WEBM
1440p WEBM
1080p WEBM
1080p MP4

I think this is why the 2160p and 1440p formats don't load.

The manifest can be found here: https://bin.snopyta.org/?cabab9a5e15fb170#DQ4PQvL7VZyp9xVk5TVvE52UzavMwh5Ms1D4nKcuRgtu
(please use a data URI when loading it, it expires in 6 hours)

**Comment by FireMasterK** [comment]
Here's my output of:
```
                   player.getVariantTracks().forEach(track => {
                        console.log(track.height);
                    });
```

```
1080
480
240
144
1080
480
240
144
1080
480
240
144
```

It seems like the affected resolutions are not being loaded at all 🤔

**Comment by TheModMaker** [comment]
This is caused by #3056, which was recently fixed.  You can try with the [nightly site](https://nightly-dot-shaka-player-demo.appspot.com/) or with the latest code from `master`.

What happens is we choose an initial container and codec and we can only play those.  So if we choose MP4 initially, then we'll only be able to play those streams.  In the latest `master` we should pick WebM since it has higher resolutions available.

**Comment by FireMasterK** [comment]
Thank you! It seems to be fixed on the nightly site, I will wait for the next release now.
