### ISSUE TITLE
Rewind causes endless rebuffering

### ISSUE THREAD

**Issue by arturparkhisenko** [google/shaka-player#3187]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**

- v2.5.10
- v2.5.19
- v3.0.8

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Demo App

**If custom app, can you reproduce the issue using our demo app?**
N/A

**What browser and OS are you using?**
- macOS Catalina 10.15.7, Google Chrome 88.0.4324.192
- macOS Catalina 10.15.7, Firefox 86.0

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
- Xbox One X, OS v10.0.1941.6288 (xb_flt_2102vb.210218-1230), Web Engine Microsoft Edge 18.19041
- Samsung Tizen TV - TU7000 Crystal UHD 4K Smart TV (2020), model UN43TU8000FXZA, Software T-NKLAKUC-1460.9. BT - S, Web Engine Chromium 69.0.3497.106 

**What are the manifest and license server URIs?**
Demo App content Angel One.

**What did you do?**
- Load the demo content video Angel One by clicking Play on the content tile
- Seek somewhere to the middle of the video
- Start doing rewind actions with a ~10s step until it’s stuck (give every action 0.5-1s of playback to see that current seeking is done and playback is happening)

Notes: 
- After doing it a random amount of times (sometimes it’s instantly, sometimes it’s 2-3 steps, sometimes you need to do it for a couple of minutes) it will eventually get stuck.
- Clicking Play/Pause does not resolve the problem.
- Any seeking - instantly resolves the problem.

**What did you expect to happen?**
Playback continues to play after any seek operation.

**What actually happened?**
The video becomes stuck - a still video image without moving playhead.

**Notes**
We have tried to capture the video element state and custom logs:
The last event before it’ll happen is either `stalled` or `waiting`

```
timeupdate currentTime 24.8134564 ended false, seeking false, paused false, readyState 4
seeking currentTime 14.9023521 ended false, seeking true, paused false, readyState 4
timeupdate currentTime 14.9023521 ended false, seeking true, paused false, readyState 4
timeupdate currentTime 14.9023521 ended false, seeking true, paused false, readyState 4
waiting currentTime 14.9023521 ended false, seeking true, paused false, readyState 4
timeupdate currentTime 14.9023521 ended false, seeking true, paused false, readyState 4
timeupdate currentTime 14.9023521 ended false, seeking true, paused false, readyState 4
timeupdate currentTime 14.9023521 ended false, seeking true, paused false, readyState 4
timeupdate currentTime 14.9023521 ended false, seeking true, paused false, readyState 4
timeupdate currentTime 14.9023521 ended false, seeking true, paused false, readyState 4
stalled currentTime 14.9023521 ended false, seeking true, paused false, readyState 4
timeupdate currentTime 14.9023521 ended false, seeking true, paused false, readyState 4
timeupdate currentTime 14.9023521 ended false, seeking true, paused false, readyState 4
timeupdate currentTime 14.9023521 ended false, seeking true, paused false, readyState 4
timeupdate currentTime 14.9023521 ended false, seeking true, paused false, readyState 4
timeupdate currentTime 14.9023521 ended false, seeking true, paused false, readyState 4
... endless timeupdate events until we do something.
```

This problem sounds similar to  what is described in this comment https://github.com/google/shaka-player/issues/2247#issuecomment-699812334

**Comment by joeyparrish** [comment]
@arturparkhisenko, is there reason to believe it's not a duplicate of #2247?

**Comment by arturparkhisenko** [comment]
@joeyparrish seems right, I'll close this one.
