### ISSUE TITLE
DASH VOD manifest with large offset at the start can't be played.  Seek doesn't work either.

### ISSUE THREAD

**Issue by duggaraju** [google/shaka-player#3189]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.8

**Please ask your question**
the link to Dash MPD is here : https://amsts11mediaarmaccpmxj-ts111.streaming.media.azure-test.net/79d49732-c63e-4506-9d53-c2dac1f5b8e7/test.ism/manifest(format=mpd-time-cmaf,starttime=2021-02-25T18:00:00.000Z,endtime=2021-02-25T18:30:00.000Z).mpd.   This could be MPD authoring issue but would like to clarify.  There is a big gap between the presentationTimeOffset and the first timestamp of first segment in the video (bigger than the duration of the manifest). 

I get this weird seek time range:  585286.3148777778 - 1799.988 where end is less than start (since end is clamped to the duration of the manifest while start is the first timestamp - presentation offset.  So the player just stalls after loading manifest. I tried to manually seek around but that doesn't work either.  Wondering if there is a way to play such content without reauthoring the manifest.

**Comment by TheModMaker** [comment]
That link isn't valid anymore.  Can you post a new URL?

> There is a big gap between the presentationTimeOffset and the first timestamp of first segment in the video (bigger than the duration of the manifest).

Is this VOD?  If so, the `presentationTimeOffset` should be the same as the timestamp of the first segment.  VOD content must start at 0.  This is likely bad content.  You may be able to use a response filter to edit the XML before we get it and fix the `presentationTimeOffset` value.

**Comment by duggaraju** [comment]
Thanks. Yes this can be closed.
