### ISSUE TITLE
TTML: "smtpe:image" tag should have camel case "imageType" attribute, and shaka player looks for lower case.

### ISSUE THREAD

**Issue by Canta** [google/shaka-player#3196]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v3.0.8 (uncompiled)

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Demo

**What browser and OS are you using?**
Firefox 86, Ubuntu 20.04

**What did you do?**

  1. Download a media file with dvb_subtitles ([here's an example](https://drive.google.com/file/d/1Qm6F0z8r3K2DliICep9Dw7cfiaklZ_2T)), and generate a MPEG-DASH using shaka packager, and exporting the subtitles as TTML (in mp4 chunks).
  You can use the following command:
```
packager \ 
'in=ccextractor_bugs_allcaps_29fps_leftjustify.m2ts,stream=video,init_segment=output/640p_init.mp4,segment_template=output/640p_$Number$.m4s' \
'in=ccextractor_bugs_allcaps_29fps_leftjustify.m2ts,stream=audio,skip_encryption=1,init_segment=output/audio_init.mp4,segment_template=output/audio_$Number$.m4s,language=ENG' \
'in=ccextractor_bugs_allcaps_29fps_leftjustify.m2ts,stream=text,skip_encryption=1,format=ttml+mp4,init_segment=output/text_init.mp4,segment_template=output/text_$Number$.mp4,language=ENG' \
--mpd_output output/test.mpd
```
  2. Take a look at the text chunks (just `cat` any of them), to see the TTML XML syntax.

**What did you expect to happen?**
To have an actual well formed and playable TTML inside those text mp4 chunks.

**What actually happened?**
Please take a look at this shaka packager ticket: https://github.com/google/shaka-packager/issues/908
There, I explain that packager generates TTML images from DVBSUB, and the TTML generated has a tiny error: the `imageType` attribute from `smtpe:image` tag should be camel case, and it's not.

Thing is, **when I fix that in shaka packager, shaka player stops rendering the captions**.
The problem is that shaka player also has that tiny bug. Please also take a look at this line:
https://github.com/google/shaka-player/blob/23fe7128494d0678d6fd8e3bc951f303907ec5cf/lib/text/ttml_text_parser.js#L574

I just did a quick search in player's code using github's web UI. I don't know if this requires changes anything more than that line. Yet, I believe this to be a bug, as the spec states camel case for that attribute. If not fixed, shaka player would not play legit TTMLs, and packager TTMLs would most likely not work with other players. So, I created a ticket in both projects.

I believe #3097 may be related.

**Comment by joeyparrish** [comment]
Thanks!  This should be easy to fix.

**Comment by joeyparrish** [comment]
We will fix Shaka Player to accept both versions, so existing Packager-generated content with the lowercase attribute name will still function.
