### ISSUE TITLE
The start/end time for EMSG v1 event is in media time units instead of presentation time units when timestamps do not start at 0.

### ISSUE THREAD

**Issue by duggaraju** [google/shaka-player#3197]
From the JSDOC for EmsgInfo:

 * @property {number} startTime
 *   The time that the event starts (in presentation time).

However in the actual code: (streaming_engine.js:)
      startTime = pts / timescale;

We need to subtract the timestampOffset to get the start time in presentation time instead of media time.

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

**What version of Shaka Player are you using?**
The latest nightly build.

**Can you reproduce the issue with our latest release version?**
No

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Custom app

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Chrome, Windows 10

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What did you do?**
register for 'emsg' event.
    player.addEventListener('emsg', onEmsgEvent, player);  

**What did you expect to happen?**
The event fired with event start time/end time in presentation time units

**What actually happened?**
The event fired with start/end time in media time units which is hard to correlate back to the presentation time without knowing offset.

**Comment by avelad** [comment]
@duggaraju Is it solved with https://github.com/google/shaka-player/commit/fc3afeb267099c535749275f5545ef1ac1ca67f9?

**Comment by duggaraju** [comment]
Yes. That commit fixes it.
