### ISSUE TITLE
Mapping video timestamps back to media timestamps

### ISSUE THREAD

**Issue by duggaraju** [google/shaka-player#3203]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**

Yes
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.8

**Please ask your question**

Is there a way to map the current video time (videoElement.currentTime) back to the media timestamps?  Below is an example of a VOD manifest with non-zero timestamps
https://krishndurpv3-usw22.streaming.media.azure.net/40459df0-a517-4f48-a39a-8c153ff20bef/test.ism/manifest(format=mpd-time-cmaf,starttime=2021-03-05T04:25:00.000Z,endtime=2021-03-05T04:30:00.000Z).mpd

The video.currentTime time always starts from 0 to the duration of the manifest.  Wondering if there is a way to map it back to the timestamp from either the manifest/or the video segment.

**Comment by TheModMaker** [comment]
The timestamps are added by the `Period@start - @presentationTimeOffset` attributes.  Take a look at https://github.com/google/shaka-player/blob/master/docs/design/dash-manifests.md.  At runtime, you can use `SegmentReference.timestampOffset` to get this from the reference.

**Comment by duggaraju** [comment]
Thanks. Is there a way to get the SegmentReference for the current playing segment using the player API?

**Comment by duggaraju** [comment]
Thank you so much. This is very helpful. 
Understood that this could change between release().  A quick question would this work for HLS or it only works for DASH?

**Comment by joeyparrish** [comment]
It's the same for either, but there is one additional issue that may come up for HLS.  With HLS content using TS containers (instead of MP4), the third-party transmuxer (mux.js) may modify the timestamps.  I can't recall offhand.  but with TS content, there's another component in the mix that we didn't write.

**Comment by duggaraju** [comment]
Thanks.  This is really helpful.
