### ISSUE TITLE
codecs.charmap_decode(input,self.errors,decoding_table)[0] UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 310: character maps to <undefined>

### ISSUE THREAD

**Issue by tanish14** [google/shaka-player#3204]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.20

**Can you reproduce the issue with our latest release version?**
YES

**Can you reproduce the issue with the latest code from `master`?**
YES

**Are you using the demo app or your own custom app?**
ERROR ON INSTALLATION

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**

When I cloned the repo and run python build/all.py in the shaka-player directory

**What did you expect to happen?**
dist/shaka-player.compiled.js (compiled bundle)
dist/shaka-player.compiled.debug.js (debug bundle)
dist/shaka-player.compiled.externs.js (generated externs, for Closure-based projects)
docs/api/index.html (generated documentation)

**What actually happened?**

It shows an error:
codecs.charmap_decode(input,self.errors,decoding_table)[0] UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 310: character maps to <undefined>

**Comment by michellezhuogg** [comment]
Hello @tanish14 ,

I just googled it and found a possible [solution](https://stackoverflow.com/questions/9233027/unicodedecodeerror-charmap-codec-cant-decode-byte-x-in-position-y-character). Could you please try it?

**Comment by tanish14** [comment]
Hello @michellezhuogg,
Thankyou for the solution but I looked up for the same solution before and was unable to find the related code line in python script for opening the file. Can you pls tell where I can find it?

**Comment by tanish14** [comment]
@michellezhuogg  found the solution
if we add `encoding='utf8'` to the open(), it does not show any error
https://github.com/google/shaka-player/blob/fc3afeb267099c535749275f5545ef1ac1ca67f9/build/generateLocalizations.py#L251

**Comment by joeyparrish** [comment]
Yes, please!  We would be happy to have a PR for this.

**Comment by sradhanjan** [comment]
@tanish14 after making the changes suggested by you I am facing this issue while compiling the program

![image](https://user-images.githubusercontent.com/56840012/110908316-a255c480-8334-11eb-8253-a2531692c31c.png)

**Comment by surajkumar-sk** [comment]
@sradhanjan  that is an issue which has already been addressed and solved . It might not be an appropriate solution but it does work . check error #2985 for temporary solution .

**Comment by surajkumar-sk** [comment]
@joeyparrish , please help me out here . i am not understanding why my PR is getting reject #3210 . it says cla/google failed .
thank you

**Comment by sradhanjan** [comment]
@surajkumar-sk I have gone through the discussions in #2985 and have made the suggested changes but the output is different from what is given in the tutorial page

![image](https://user-images.githubusercontent.com/56840012/110950973-81a86180-836a-11eb-963f-b43a79f45394.png)

**Comment by surajkumar-sk** [comment]
@sradhanjan  . The output is not much different . there are few extra files which have been loaded along with the shown output files . check the folder "dist/" inside shaka-player folder , all the files shown in output are loaded along with few extra files . Don't bother much about other files. keep reading the jsDOc futher .

**Comment by joeyparrish** [comment]
@sradhanjan, sorry for the difficulty in building on Windows.  You should be able to contribute to the non-CSS parts of the project without the style linter.  Feel free to comment it out as a workaround, as detailed in #2985.  Incidentally, if any Windows user wants to work on #2985, that would be very much appreciated.  I'll leave some additional thoughts on that issue.

@surajkumar-sk, regarding the CLA issue you had, it looks like you've already solved it, but issues with the CLA are usually caused by a mismatch between the email you used to sign the CLA and the email that appears in the commits you're asking to pull into the repo.

**Comment by surajkumar-sk** [comment]
@joeyparrish . I mistyped my email during commit which caused that CLA problem . I deleted the repo and forked it again and then checked my email in cmd before adding a commit , and realised i typed gail.com instead of gmail.com 😅 . 

Thank you for help .
