### ISSUE TITLE
playback failure with streaming playready protected contents created by dash_packager/bento4 on IE11/Edge

### ISSUE THREAD

**Issue by Sean-X** [google/shaka-player#321]
The video packaged by dash packager or bento4 and encrypted using playready.
I have confirmed that audio still could be streamed separately which means no problem about license.
But when trying to streaming video on IE11/Edge, the browser will error out and the error code is invalid argument.
Encryption starts at the beginning(no 10 second clear part by default)
It would be great helpful f anyone has any clue or solution.

**Comment by joeyparrish** [comment]
What version of Shaka are you using?  Can you provide a public link to the content?

**Comment by Sean-X** [comment]
I am using the latest code which is 1.9.9-alpha-debug.
Here is the content link
https://drive.google.com/file/d/0B8fe5Y9nDoZwU0pUSUxWSV95SEk/view?usp=sharing

**Comment by Sean-X** [comment]
Sorry, my dash packager is customized so latest changes isn't included. 
I've verified that this issue is fixed by commit ef81be5f7b5c24fdda779cee272bb45777b7800e
Thanks for all your help.
