### ISSUE TITLE
HLS stream load long because fetch stream files for all bandwith

### ISSUE THREAD

**Issue by lipniarz** [google/shaka-player#3213]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
I was try 3.0.0, 3.0.5 and 3.0.8

**Please ask your question**
I would like to avoid fetch stream file for all bandwitch provided in m3u8 file, to allow start video faster, it is possible to do it by some configuration?
Currently I have:
```
shakaPlayer.configure({
	      abr: {
            defaultBandwidthEstimate: 1978000,
			enabled: true, // True when "Auto" level is selected in JW Player
          },
          streaming: {
          ignoreTextStreamFailures: true,
		  }
```
I'm also able to see the same issue on demo:

https://shaka-player-demo.appspot.com/demo/#audiolang=en-EN;textlang=en-EN;uilang=en-EN;asset=https://moctobpltc-i.akamaihd.net/hls/live/571329/eight/playlist.m3u8;panel=HOME;build=uncompiled

this playlist is loaded quite fast, because stream files are short, but when is in use bigger files I can reach ~30s delay on load.

I'm not sure if it's a bug, wrong configuration or something else.
I will be grateful for your help.

**Comment by TheModMaker** [comment]
We currently don't have the option, but you can follow #1936 where we'll add it at some point.

**Comment by joeyparrish** [comment]
Also, if your server supports range requests, we will be able to load smaller chunks, which will reduce latency.
