### ISSUE TITLE
npm: latest is pointing to 2.5.21

### ISSUE THREAD

**Issue by dulmandakh** [google/shaka-player#3232]
npm: latest is pointing to 2.5.21, instead of 3.0.x

**Comment by joeyparrish** [comment]
That's really odd.  I suppose they are doing that by date rather than by version number.  I released v2.5.21 and v3.0.9 on the same day, but perhaps arbitrarily in the opposite order.

Let me see if this can be fixed without a v3.0.10 release.

**Comment by joeyparrish** [comment]
Looks like `npm dist-tag add shaka-player@3.0.9 latest` fixed it.  Sorry for the trouble!
