### ISSUE TITLE
Seekbar behaves weird when arrow key is pressed for long .

### ISSUE THREAD

**Issue by surajkumar-sk** [google/shaka-player#3234]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

When you select seek bar by navigating through the 'tab' button and keep the arrow key(left or right) pressed it behaves
weird. It does what it is intended to do move 5s forward or backward when the key is released but while the key is kept pressed it works weird. If seek bar is not an active element it works fine.
this behavior only happens when the seek bar is an active element.

The below video shows the bug.

https://user-images.githubusercontent.com/71056993/111308805-606c9d00-8618-11eb-9488-0b00a0234905.mp4

**Describe alternatives you've considered**

I think this happens because when `activeElement.classList.contains('shaka-seek-bar')` is true the browser tries controlling the 
seek bar as per user that is decrease or increase the current time which collides with `this.timeAndSeekRangeTimer_.tickEvery(/* seconds= */ 0.125);`  causing the bug. It's not that big of a deal but it is still a bug. I would like to add a feature to tackle this bug. when the arrow key(left or right) is pressed down and not released for more than 1.5sec then the seek bar keeps reducing its current time by 5sec. Some users prefer using this method to browse the video.

**Additional context**

**Comment by surajkumar-sk** [comment]
@joeyparrish @TheModMaker 
That feature can be added by adding this logic to `onKeyDown_() :
 .writing an if condition to check for key up for 1.5sec.
 .if false add `tickevery()` to `this.seek_` with switch cases
 .and stop when keyup is triggered .

As per my knowledge, this won't create any kind of conflicts and would fix the bug.

I would like to work on a PR for this, but wanted to confirm if i could proceed with this approach.

Thank you.

**Comment by joeyparrish** [comment]
Thanks for the report!  I'm going to fix this in a different way than you suggested in your PR, though.

**Comment by surajkumar-sk** [comment]
@joeyparrish I taught it was better to add code in the existing function rather than creating a new event and adding a separate function. I did listen to key events on windows but added an if condition which would run the code below only if the video container is in focus. After watching your solution my code does seem very complicated and I also kind of feared breaking the code if I change the names of functions 😅 because I haven't fully completed reading this project. I think there was a reason for listening to key-up events because `this.pressedKeys_.delete(event.key);` should only run when the key is released. this definitely should create some kind of bug. I'll check for bugs if any, caused by that change.

**Comment by surajkumar-sk** [comment]
@joeyparrish I guessed it right, removing onKeyUp() does cause few bugs. everything works fine when only the 'tab' key is pressed but when you use 'shift+tab' everything after that doesn't work properly. I am unable to select elements in the overflow menu other than the first and last child. and when I press enter on the first child, instead of opening the setting menu it shifts the focus to the last child element, and also the focus doesn't stay in the overflow menu. the below video shows the bug.

https://user-images.githubusercontent.com/71056993/111869161-2d3d4d00-893b-11eb-84db-7417cf8f27ba.mp4

**Comment by surajkumar-sk** [comment]
This happens because `this.pressedKeys_.delete(event.key);` is inside `onControlsKeyUp()` . when tab key is pressed , key event gets added to `pressedKeys_` array from `onWindowsKeyDown()` and **if that key event is already present** in `pressedKeys_` it gets deleted from that array due to  `onControlsKeyUp()` . now when shift is pressed it gets added to  `pressedKeys_`  due to `onWindowsKeyDown()` and then tab is pressed so even tab key event gets added to `pressedKeys_`  due to `onWindowsKeyDown()` . Now the `pressedKeys_`  has two elements 'tab' and 'shift'. when I release the shift key, it doesn't get deleted from the `pressedKeys_` array. when I press the shift key again it gets added to the array again due to `onWindowsKeyDown()` and the previously existing shift gets deleted. but there is still a shift key inside an array, so once the shift key is pressed it never gets deleted from the array. so, even if I press 'tab' or 'enter' it doesn't matter because due to `keepFocusInMenu_()` if the shift is found and the first element is active it goes to last-child thus no other elements get selected. The focus doesn't stay in the overflow menu because when the last child element is in focus, the `pressedKeys_` array has 'shift' so the else condition which should change the focus to a first child fails, and focus exits the overflow menu.

**I should work on giving small explanations 😂**

I think probably for tackling the addition and deletion of key events onKeyUp() function was created and then it suited for adding seek functionality too.  😊 

It could be fixed by adding a key-up event. I'll add a PR for a possible solution.

**Comment by surajkumar-sk** [comment]
@joeyparrish sorry its onControlsKeyDown() not onControlsKeyUp()

**Comment by joeyparrish** [comment]
> @joeyparrish I taught it was better to add code in the existing function rather than creating a new event and adding a separate function.

Well, I find that "better" usually depends on context.  It can be tough to judge when you're new to a project.

**Comment by joeyparrish** [comment]
Thank you for the fix in PR #3259.  Thankfully, the bug I introduced in my earlier fix is not in any release versions yet.  You fixed it just in time!

**Comment by surajkumar-sk** [comment]
> Well, I find that "better" usually depends on context. It can be tough to judge when you're new to a project.

True.

> Thank you for the fix in PR #3259. Thankfully, the bug I introduced in my earlier fix is not in any release versions yet. You fixed it just in time!

when will this version be released, can I get a date. This feature still has some bugs, I am working on an explanation for it and also a possible solution. I am a bit confused about how to explain it, cause I don't understand the bug properly yet.

**Comment by surajkumar-sk** [comment]
There are two bugs with the seek bar when the arrow key is used for navigation.
1. when an arrow key is used for navigating the video. the seek bar stops updating, I don't know how I missed this before
2. when the video is navigated through arrow keys and the value of the current time exceeds the max time of the video, the video stops loading, the video keeps buffering for an infinite time after clicking on the reset button or changing the time in seek bar. 

The video below shows the problem 


https://user-images.githubusercontent.com/71056993/111944843-c6807680-8a95-11eb-8a45-d6db1019b4d3.mp4


Hopefully, I'll have a PR Before you watch this.

God save us all from the big buck bunny. ;)

**Comment by surajkumar-sk** [comment]
In `changeto()`  function in `range_element.js` file `this.isChanging_` was set to true but never set to false which caused ` updateTimeAndseekRange()` in `controls.js` to fail. this fixes the first bug .

I am still working on the second bug. This bug I think is not caused by your changes, but the previous versions handled it by moving the video 1s backwards when the end key is pressed or when the video is navigated beyond the end by arrow keys. It still wasn't perfect I was able to reproduce the bug in the previous versions too but not as easily as the present one. I think the bug is caused when the value of the video is set to max. because the value of max is not accurate, the value that is beyond the video time limit gets assigned and the video keeps getting data for that time. I haven't worked on it, it's just an assumption seeing the bug.
i have to dig more into the problem. Do you know any possible cause?  
Thank you .

**Comment by surajkumar-sk** [comment]
@joeyparrish the second bug was caused because the `video.currenttime` was set to this.bar.max. I don't know why but the video doesn't get loaded at its max time and after starting to buffer at its max time it never stops buffering. I don't know why it doesn't buffer at its max time but instead of setting  `video.currenttime` to the max value, we could set it to (max-0.125) this wouldn't make any difference because the time difference is very small but it does prevent that bug and video being stuck at buffer state. I'll add the changes to the previous pull. Nothing much changed. Could you please review it?
Thank you.

**Comment by michellezhuogg** [comment]
Hello @surajkumar-sk ,

Please understand that we have our limited capacity now and would not be able to provide close guidance until the GSoC officially starts in the summer. You are welcome to send us a PR once you have a complete, fully-tested, ready-for-review solution as a general contributor, and we'll review it as a general contribution when we are available.

Please be kind and only @us for urgent issues on Github regarding your questions or PRs, since that might spam the other developers, or the team members who are not GSoC mentors. Thank you for your understanding!

We'll have more updates coming soon to our [Google Group](https://groups.google.com/g/shaka-player-gsoc) and [website](https://nightly-dot-shaka-player-demo.appspot.com/docs/api/tutorial-gsoc-ideas-list.html).

**Comment by surajkumar-sk** [comment]
@michellezhuogg this just fixes some issues created by previous change. The present shaka-player has major bugs which are very easy to produce and can be solved by very small changes. So i added them .
