### ISSUE TITLE
Close caption access without UI

### ISSUE THREAD

**Issue by stefanovualto** [google/shaka-player#3241]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.9

**Please ask your question**
I am using shaka without UI and I would like to access the close captions embed in the stream to be able to enable them or to be able to display them relative to the currentTime.

How is it possible to do that?

**Comment by joeyparrish** [comment]
You actually have four options for displaying text streams of all kinds.  It does not matter whether they are subtitles or captions, embedded in the video or not; the display options are independent of the source of the text.

1. The Shaka Player UI renders text in the DOM, without the need for additional configuration.  Our default UI CSS should place it in the correct location and style it correctly.
2. You can use the UI's DOM-based text display plugin without the entire Shaka Player UI.  You only need to provide a div in which to render, and some CSS to position and style it.
3. You can use the browser's native cue rendering.  This requires no CSS and no DOM support.  The browser will display the text cues within the video element.
4. You can develop your own TextDisplayer plugin for Shaka Player.  The player provides the plugin with arrays of text cues, and your plugin decides how to render them.

Again, these are independent of the source of the text.  Whether it's VTT, TTML, or CEA, all text cues go through the same APIs.  The specific text shown is controlled via player methods getTextTracks() / selectTextTrack() / selectTextLanguage() / setTextTrackVisibility().

In Shaka Player v3.0, CEA captions can only be extracted from content via a third-party dependency: [mux.js](https://www.npmjs.com/package/mux.js).  If you don't load this into your page, Shaka Player v3.0 will not be able to extract CEA captions, and they will not appear in getTextTracks().

In Shaka Player v3.1 (forthcoming release), we will be able to extract CEA from MP4 directly without mux.js.  We would still need mux.js to extract CEA captions from TS-formatted content, though.

Does this help?

**Comment by joeyparrish** [comment]
(BTW, I love that "Don't Panic" icon.  Douglas Adams is one of my all-time favorite authors!)

**Comment by stefanovualto** [comment]
Thank you for your quick reply!

After adding muxjs and making the namespace available through muxjs instead of mux by default (thanks to this https://github.com/google/shaka-player/issues/1927#issuecomment-491405459). I am getting some weird errors `Cannot read property 'CaptionParser' of undefined` using this [content](https://d1r80j0ybrkzfe.cloudfront.net/cpac/vod/92bce3c0-ed2a-4cdf-bec3-123fc14a7387/92bce3c0-ed2a-4cdf-bec3-123fc14a7387_nodrm_2c1fdca5-513a-4a10-81fe-0c04017cf466.ism/.mpd). I will investigate it more tomorrow.

There is no need to configure shaka to use mux or enable it? Or should I be aware of some wiring that needs to be done?

(BTW you are the first to link my profile icon with Douglas Adams 😄 , you have sharp eyes 👀 )

**Comment by joeyparrish** [comment]
That error is probably a reference to `muxjs.mp4.CaptionParser`.  If you don't have that, please check that you're using the correct build of muxjs.  I am not deeply familiar with the details, but I know muxjs has multiple builds, and they don't all expose the same namespaces.

Or, alternately, if you're feeling brave, you can adopt the forthcoming v3.1.x branch, in which muxjs is not required for this.  We are getting close to v3.1.0, and the really bleeding-edge development on MediaCapabilities integration is not being cherry-picked to that branch, so it should be relatively safe.

**Comment by stefanovualto** [comment]
Thank you for your help, you pointed exactly to what I needed. It works like a charm!

Because I am using shaka in production, I can't really 3.1.x branch for now. But I am looking forward to using once released 😃 .

Any way for the future TS-formatted content users and for the users of 3.0.9 and below, I will just add the CDN URL of mux.js that worked for me.

`https://cdn.jsdelivr.net/npm/mux.js@${version}/dist/mux.min.js`
