### ISSUE TITLE
Addition of Replay button icon

### ISSUE THREAD

**Issue by aditmehta9** [google/shaka-player#3247]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Is your feature request related to a problem? Please describe.**

Shaka-player can have a replay button icon after the video ends instead of the pause button icon.
![image](https://user-images.githubusercontent.com/35133994/111633470-8b730e80-881b-11eb-85c9-2164851ff882.png)

**Describe the solution you'd like**

![image](https://user-images.githubusercontent.com/35133994/111633477-8f069580-881b-11eb-9a3d-b2deefa19d50.png)
Have replay button icon after video ends.

**Comment by aditmehta9** [comment]
I would like to work on this issue.

**Comment by ismena** [comment]
We actually already replay the video if the play button is pressed once the video ended.
However, something you could do is add logic to replace the icon on the _play_ button to the _replay_ icon once the video has ended and then back to the play/pause if the video was restarted or a new one was loaded.
Would you be interested in that?

**Comment by aditmehta9** [comment]
> We actually already replay the video if the play button is pressed once the video ended.
> However, something you could do is add logic to replace the icon on the _play_ button to the _replay_ icon once the video has ended and then back to the play/pause if the video was restarted or a new one was loaded.
> Would you be interested in that?

Yes, sir I meant that exactly that's why I added photo. However, I forgot to mention word icon while writing the issue. Yes, I would be interested in working.

**Comment by ketangupta34** [comment]
@aditmehta9 Hey, are you working on this issue, or may I give it a shot??

**Comment by aditmehta9** [comment]
Yes I am working on this issue.

**Comment by aditmehta9** [comment]
I am done with the issue I'll send the PR tomorrow.

**Comment by aditmehta9** [comment]
I have sent the PR with another account (username-aditmehta92) that I use at my office because I was at the office and this issue had a minor change.
