### ISSUE TITLE
Embedded captions not displaying in v3.1.X

### ISSUE THREAD

**Issue by theodab** [google/shaka-player#3248]
While trying to reproduce #3199, I noticed this (probably unrelated) problem.
If you run our embedded captions asset, `Live sim TTML Image Subtitles embedded (VoD)`, and try to turn on the captions, you see nothing. The embedded text track is still in the track list, so we are detecting it, it just has no cues. Meanwhile, in v3.0.X, the captions are displaying correctly.

**Comment by BemusedCat** [comment]
@joeyparrish Please assign this issue to me. I am working on the PR
