### ISSUE TITLE
video's duration is fixed

### ISSUE THREAD

**Issue by FeiCao** [google/shaka-player#325]
hello, I use player(v1.6.4) to play static stream, I set different `mediaPresentationDuration` values, but I found video's duration is fixed 302s, follow is my MPD file
`<?xml version="1.0" encoding="UTF-8"?>
<MPD xmlns="urn:mpeg:DASH:schema:MPD:2011" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" xsi:schemaLocation="urn:mpeg:DASH:schema:MPD:2011 DASH-MPD.xsd" xmlns:cenc="urn:mpeg:cenc:2013" minBufferTime="PT2S" type="static" profiles="urn:mpeg:dash:profile:isoff-on-demand:2011" mediaPresentationDuration="PT600S">
  <Period>
    <AdaptationSet id="0" contentType="video" width="1920" height="1080" frameRate="90000/6000" subSegmentAlignment="true" par="16:9">
      <Representation id="0" bandwidth="2000000" codecs="avc1.640028" mimeType="video/mp4" sar="1:1" width="1920" height="1080" frameRate="90000/6000">
        <SegmentTemplate timescale="90000" initialization="15837566644966283070//live-video-sd.mp4" media="15837566644966283070//live-video-sd-$Number$.mp4" startNumber="295">
          <SegmentTimeline>
            <S t="6000" d="180000" r="150"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
    </AdaptationSet>
  </Period>
</MPD>`

why?

**Comment by tdrews** [comment]
It's because the `SegmentTimeline` ends at `302.0666...`:
`(6000 / 90000) + (180000 / 90000)*151 = 302.0666...`
