### ISSUE TITLE
Bug: Change in Resolution

### ISSUE THREAD

**Issue by aditmehta9** [google/shaka-player#3262]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.10

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**What browser and OS are you using?**
Browser-Chrome, Firefox OS-Ubuntu 20.04

**What did you do?**
Create a simple HTML page with myapp.js
Change resolution from auto to 360p not (max. resolution possible change to any resolution but max.)
Change the language from the current language to any new language
See resolution changes to the max. 

**What did you expect to happen?**
Resolution should remain the same as it was before.

**What actually happened?**
Resolution changes after it is set manually (other than max.) to the max. resolution after language is changed.

![image](https://user-images.githubusercontent.com/35133994/111948464-35e17f00-8b05-11eb-919a-6c28d392f409.png)

![image](https://user-images.githubusercontent.com/35133994/111948479-3aa63300-8b05-11eb-9837-bc5a042c3dfa.png)

**Comment by aditmehta9** [comment]
I am not sure if this is a bug or it is supposed to happen. If it is a bug I would like to work on this issue and guidance would be really helpful.

**Comment by surajkumar-sk** [comment]
@aditmehta9 it's a bug, a similar thing happens to playback speed when the video is paused or played. the members confirmed it as a bug, the playback speed is being worked on by someone else, you could try working on resolution.

**Comment by aditmehta9** [comment]
@surajkumar-sk Thanks for the input. I'll start working on it.

**Comment by joeyparrish** [comment]
Based on the PR discussion, it seems like the underlying bug should maybe be handled by someone on the team who understands the nuances of the API.  I would like to propose that we close the associated PR, and that this bug be assigned to a Shaka Player team member. @aditmehta9, would that be okay with you?

**Comment by aditmehta9** [comment]
> Based on the PR discussion, it seems like the underlying bug should maybe be handled by someone on the team who understands the nuances of the API. I would like to propose that we close the associated PR, and that this bug be assigned to a Shaka Player team member. @aditmehta9, would that be okay with you?

Yes, Sir, I am okay with that but I just wanted to say this change in PR(https://github.com/google/shaka-player/pull/3285) in API fixes the bug.

**Comment by joeyparrish** [comment]
This has now been fixed in the master branch.  Thanks for the report, and for the attempts to fix it!
