### ISSUE TITLE
Negative time display and reverse movement of seek bar when paused in live stream

### ISSUE THREAD

**Issue by chanchalpatil** [google/shaka-player#3264]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

**What link can we use to reproduce this?**
https://shaka-player-demo.appspot.com/demo/#audiolang=en-GB;textlang=en-GB;uilang=en-GB;asset=https://storage.googleapis.com/shaka-demo-assets/tos-ttml/dash.mpd;panel=ALL_CONTENT;build=uncompiled

**What version of Shaka Player are you using?**
v3.0.10-uncompiled

**What browser and OS are you using?**
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36

**What did you do?**
1) Played Tears of Steel (live, DASH, Server Side ads)
2) Then Paused

**What did you expect to happen?**
Expected normal play, subtitles also to appear as there is a subtitles icon displayed in the asset card.

**What actually happened?**
-Time flickers when paused
-Negative time display (not sure whether that's intended)
-seek bar blob moves in a reverse direction.
-no subtitles option either.

VIdeo of the issue:
https://drive.google.com/file/d/11_M3jxb6jlkctjn_JhOMW9pHYWjoqpj6/view?usp=sharing

**Comment by joeyparrish** [comment]
> -Negative time display (not sure whether that's intended)
> -seek bar blob moves in a reverse direction.
This is expected while paused in a live stream.  In a live stream, the timestamps in the content are not small or meaningful to the user.  The content goes on indefinitely.  So we show the offset from the "live edge", at which "0" is live content happening right now, and "-5" would be content from 5 seconds in the past.  If you pause the content, the distance from the live edge will increase.

> -no subtitles option either.
Not every piece of content has subtitles.  If there aren't any subtitles in the content, the option will not appear in the UI.

**Comment by chanchalpatil** [comment]
I think the video attached wasn't very clear. Here's how the time flickers  
[https://drive.google.com/file/d/1BM7gwcWKWY3kkvI48uNA_gcQhS-n70so/view?usp=sharing](url)

This happens only over a desktop and not on the mobile phone screens.
I think this has something to do with issue

**Comment by joeyparrish** [comment]
@chanchalpatil, that flicker looks like it may be caused by rounding.  See `buildTimeString` in `ui/ui_utils.js`.  You can try changing `Math.floor` to `Math.round` in the seconds calculation, and see if that helps at all.  If so, feel free to send us a PR.  Thanks!

**Comment by chanchalpatil** [comment]
> @chanchalpatil, that flicker looks like it may be caused by rounding. See `buildTimeString` in `ui/ui_utils.js`. You can try changing `Math.floor` to `Math.round` in the seconds calculation, and see if that helps at all. If so, feel free to send us a PR. Thanks!

Tried it out. It didn't work. I noticed that this happens when there is nothing more to buffer. I tried inspecting it, and think this could be the reason (screenshot below)

![1](https://user-images.githubusercontent.com/44722554/113128199-2ebe1d80-9237-11eb-8856-d5db626d0592.png)

![2](https://user-images.githubusercontent.com/44722554/113128205-3087e100-9237-11eb-9016-2918a80065ee.png)
