### ISSUE TITLE
Integration with JavaScript framework SDK possible ?

### ISSUE THREAD

**Issue by pedrosilvabos** [google/shaka-player#3268]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
YES

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
YES

**What version of Shaka Player are you using?**
3.0.10

**Please ask your question**
I am using a [JavaScript framework](https://github.com/interfaced/zombiebox) that compiles javascript into either Tizen or Webos apps.
Altho, from what I can understand, this JavaScript framework provides a link to initialize the native players from each platform and play.
Due to some requirements , from my side as a user, it was asked if I could integrate shakaplayer, and use it, instead of the native players., altho I have the shaka player sample working, html, and I can work with it pretty well, I am unable to import shaka into this JavaScript framework.

This JavaScript framework works with Strongly typed JavaScript and component based, uses Javascript Templates (JST) and CSS for the front end, with javascript logic file. 
I am unable to use a simple  <script src="shaka-player.compiled.js"></script>

**Comment by TheModMaker** [comment]
We don't have any experience with that (or most) loading frameworks.  We just provide the library and expect people to import it however they can.  We can't really support every framework out there.  If there is a specific issue you are seeing, we can try to help.  But as for "how to I load in framework Y", we expect you to know how to use your loaders.

I think we support loading as a component.  I think we wrap the output in a way that is compatible with many component loaders.  We also recently added TypeScript bindings to the compiled bundles.  Look for `shaka-player.compiled.d.ts` for the TypeScript definitions.

Note that if you want to use mux.js for transmuxing, it either needs to be stored on `window`, or you can register it before creating the Player:

```js
shaka.dependencies.add('muxjs', require('mux.js'));
```

**Comment by pedrosilvabos** [comment]
I managed to integrate shaka
