### ISSUE TITLE
Add hover tooltips to control panel buttons

### ISSUE THREAD

**Issue by nbcl** [google/shaka-player#3269]
Now that the Picture-in-picture, Loop, and other buttons will be soon available in the UI control panel, it would be great to have tooltips indicate the action and current state of a button on hover.

<p align=center>
<img src="https://nbcl.github.io/images/tooltip.png" width=1000>
</p>

I think this could serve as a milestone list for development:

* [x] When hovering over a button, a tooltip shows its name.
* [x] The tooltip also shows their specific hotkey if applicable (ie: "Play (Spacebar)"). 
* [x] The tooltip also shows the current state (ie: "Loop (Off)"). 
* [x] The tooltip is optional and configurable using `ui.config()`.

I would appreciate knowing the opinions of the team on this feature request!

**Comment by TheModMaker** [comment]
Sure, that sounds like a good idea.  If you or someone else will work on this, remember we'll need to localize the strings.  These will need to be added to the translation files and we (the team) will need to update these to the translation team.

**Comment by nbcl** [comment]
> If you or someone else will work on this, remember we'll need to localize the strings. 

Understood!
