### ISSUE TITLE
Future Tizen support

### ISSUE THREAD

**Issue by baseballbrad3** [google/shaka-player#3271]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.10

**Please ask your question**
What’s the status of Shaka Player support on Tizen? I know it is supported right now, but are there any plans to end support?

**Comment by joeyparrish** [comment]
No plans at this time to end Tizen support.  If we did, it would likely be certain older versions, not Tizen completely.

We currently test on Tizen 3.0, and provide no support for older versions of Tizen than that.  Some day, we may stop supporting Tizen 3 and only support newer versions.

But again, no plans to change our Tizen support at this time.
