### ISSUE TITLE
Error code undefined object TypeError: s(...).abr.EwmaBandwidthEstimator is not a constructor

### ISSUE THREAD

**Issue by hiren3897** [google/shaka-player#3273]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.4.4

**Please ask your question**
I am trying to load() my DASH manifest URL directly and also by using DashVideoSource but when I run my code:

for loading DASH Url Directly in player.load() is giving me the following error:

 load Manifest URL: https://equidia-racing4-p9-cdn.hexaglobe.net/e5afcb5da4277149deb8ee0553b7c7e8/605a04a5/equidia/equidia-website-web-1/eqdracing4pri_fre.smil/manifestwidevine.mpd
along with passing drm URL from response to DRM configuration of shaka-player, it is giving me the same error with code 6001

> hexa-shaka-player.js:2 Error code 6001 object 
> Y {severity: 2, category: 6, code: 6001, data: Array(0), handled: false}
> category: 6
> code: 6001
> data: []
> handled: false
> severity: 2

And if I am trying to load the same URL using DashVideoSource it gives me an error which I have already mentioned as the title for this question. i.e. "Error code undefined object TypeError: s(...).abr.EwmaBandwidthEstimator is not a constructor"

Here is my initPlayer code:
```
export const initPlayer = async function () {
    // Create a Player instance.
    const video = document.getElementById('video')

    // shaka.media.ManifestParser.registerParserByExtension("mpd", shaka.dash.DashParser);
    const player = new shaka.Player(video);

    // Attach player to the window to make it easy to access in the JS console.
    window.player = player;

    // Listen for error events.
    player.addEventListener('error', onErrorEvent);

    // Try to load a manifest.
    // This is an asynchronous process.
    try {
        var drmUrl = selectDrm();
        state.drmUrl = drmUrl;
        // model.getDrmConfig(model.state.drmUrl);
        await loadStreams()
        video.setAttribute('poster', `${state.streams.logo}`)
        await loadmanifest()
        // model.state.manifest = Object.assign({...data});
        console.log("manifest API: " + state.manifests.primary)
        getDrmConfig(state);
        player.configure({
            drm: {
                servers: state.config.drm.servers,
                advanced: {
                    'com.widevine.alpha': {
                        'videoRobustness': 'HW_SECURE_ALL',
                        'audioRobustness': 'HW_SECURE_ALL'
                    }
                }
            }
        });
        var estimator = new shaka.abr.EwmaBandwidthEstimator();
    
        var source = new shaka.player.DashVideoSource(state.manifests.primary,
            null, estimator);

        // Finally, begin playback.
        await player.load(source);
        // This runs if the asynchronous load is successful.
        console.log('The video has now been loaded!');
    } catch (e) {
        // onError is executed if the asynchronous load fails.
        onError(e)
    }
    console.log(player.getConfiguration())
}
```

The DASH URL is: https://equidia-racing1-p-cdn.hexaglobe.net/beb6a0bf7d4c62fc24d2bd5e7eb2793f/6059f5c4/equidia/equidia-website-web-1/eqdracing1pri_fre.smil/manifestwidevine.mpd 
Note: it is an API of a live streaming channel named Equidia.

Can you tell me why I am not able to play the video on the video player?
Thank you in advance

**Comment by TheModMaker** [comment]
`DashVideoSource` was removed over 4 years ago when we released v2.0.  You also don't need to create any bandwidth estimator, it is handled internally.  Check out our latest [basic tutorial](https://shaka-player-demo.appspot.com/docs/api/tutorial-basic-usage.html) for how to setup the latest player.

6001 is [REQUESTED_KEY_SYSTEM_CONFIG_UNAVAILABLE](https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html#value:6001).  This means that either the DRM system you wanted isn't supported on this browser or you set a configuration that isn't supported.  `HW_SECURE_ALL` is only supported on phones and some smart TVs, it is not supported on browsers.

**Comment by hiren3897** [comment]
Hello, thank you for the response.
I understood that DashVideoSource is removed and I have now Implemented the player with the latest basic tutorial.
In my project, I am using webpack and have installed shaka player using npm install shaka-player passed as devDependency in my package.json  

I am using the live streams API of Equida channel configured by my company you can see [here](https://equidia-vodce-players.hexaglobe.net/mf_data/20210323.json) 

after fetching the URLs I get Dash Manifest as a response with DRM URL that I configure it in player.configure().
but when I do player.load() is giving me 6002: FAILED_TO_CREATE_CDM 

HERE IS MY LATEST CODE: 

```
import {AJAX} from './helpers.js';
import {UAParser} from 'ua-parser-js';
import shaka from 'shaka-player'
export const state = {
    streams: {},
    manifests: {},
    config: {
        drm: {
            servers: {},
            clearKeys: {},
        },
        manifest: {
            dash: {
                clockSyncUri: String,
                ignoreDrmInfo: Boolean,
                xlinkFailGracefully: Boolean,
                ignoreMinBufferTime: Boolean,
                autoCorrectDrift: Boolean,
                initialSegmentLimit: Number,
                ignoreSuggestedPresentationDelay: Boolean,
                ignoreEmptyAdaptationSet: Boolean
            },
            hls: {
                ignoreTextStreamFailures: Boolean,
                useFullSegmentsForStartTime: Boolean
            }
        },
    },
    drmUrl: String,
}

const createStreamsObject = function (data) {
    const streams = data[58]
    return {
        title: streams.title,
        player: streams.player,
        streamUrl: streams.streamUrl,
        streamUrl_ios: streams.streamUrl_ios,
        streamUrl_android: streams.streamUrl_android,
        logo: streams.logo,
        disabledLogo: streams.disabledLogo,
        channel: streams.channel
    }
}

const getStreamManifest = function (data) {
    const manifests = data
    return {
        primary: manifests.primary,
        primary_drm: manifests.primary_drm,
        backup: manifests.backup,
        backup_drm: manifests.backup_drm,
        status: manifests.status,
        protocol: manifests.protocol,
    }
}

const addZero = function(num) {

    if (num >= 10)
    {
        return num;
    }
    return '0' + num;
}

const getDateToday = function () {

    var today = new Date();
    var date = today.getFullYear() + '' + addZero(today.getMonth()+1) + '' + addZero(today.getDate());
    return date;
}

//getStream infos
export const loadStreams = async function () {
    var streamsInfoUrl = "https://equidia-vodce-players.hexaglobe.net/mf_data/" + getDateToday() + ".json";
    console.log(streamsInfoUrl)
    try {
        const data = await AJAX(`${streamsInfoUrl}`);
        state.streams = createStreamsObject(data);
        // console.log(state.streams)
    } catch (err) {
        // Temp error handling
        console.error(`${err} 💥💥💥💥`);
    }
};

export const getDrmServer = async function (drmServerName, url) {
    const drmServer = {}
    drmServer[drmServerName] = url;
    console.log(drmServer);
    state.config.drm.servers = drmServer;
}

export const getDrmConfig = function (state) {
    return getDrmServer('com.widevine.alpha', state.manifests.primary_drm)
}

export const selectDrm = function () {

    var ua = new UAParser().getResult();

    console.log('device.type=', ua.device.type, ' browser.name=', ua.browser.name, ' os.name=', ua.os.name);

    if (ua.device.type === 'mobile' || ua.device.type === 'tablet')
        return 'hls';

    if (ua.browser.name === 'Chrome' || ua.browser.name === 'Opera' || ua.browser.name === 'Firefox' && parseInt(ua.browser.version) > 51)
        return 'dashwidevine';

    if (ua.os.name === 'Windows' && parseFloat(ua.os.version) >= 8.1 && (ua.browser.name === 'IE' || ua.browser.name === 'Edge'))
        return 'dashplayready';

    if (ua.os.name === 'iOS' || ua.os.name === 'Mac OS' && ua.browser.name === 'Safari' && parseFloat(ua.browser.version) >= 11)
        return 'hlsfairplay';

    return 'hls';
}

export const loadmanifest = async function () {
    var urlStreamInfo = `${state.streams.streamUrl}` + `?format=` + `${state.drmUrl}`
    console.log(urlStreamInfo)
    try {
        const data = await AJAX(`${urlStreamInfo}`);
        state.manifests = getStreamManifest(data);
    } catch (err) {
        // Temp error handling
        console.error(`${err} 💥💥💥💥`);
    }
};
export const initPlayer = async function () {
    // Create a Player instance.
    const video = document.getElementById('video')

    // shaka.media.ManifestParser.registerParserByExtension("mpd", shaka.dash.DashParser);
    const player = new shaka.Player(video);

    // Attach player to the window to make it easy to access in the JS console.
    window.player = player;

    // Listen for error events.
    player.addEventListener('error', onErrorEvent);

    // Try to load a manifest.
    // This is an asynchronous process.
    try {
        var drmUrl = selectDrm();
        state.drmUrl = drmUrl;
        // model.getDrmConfig(model.state.drmUrl);
        await loadStreams()
        video.setAttribute('poster', `${state.streams.logo}`)
        await loadmanifest()
        // model.state.manifest = Object.assign({...data});
        console.log("manifest API: " + state.manifests.primary)
        getDrmConfig(state);
        player.configure({
            drm: {
                servers: state.config.drm.servers,
                advanced: {
                    'com.widevine.alpha': {
                        'videoRobustness': 'SW_SECURE_CRYPTO',
                        'audioRobustness': 'SW_SECURE_CRYPTO'
                    }
                }
            },
        });
        
        await player.load(`${state.manifests.primary}`);
        // This runs if the asynchronous load is successful.
        console.log('The video has now been loaded!');
    } catch (e) {
        // onError is executed if the asynchronous load fails.
        onError(e)
    }
    console.log(player.getConfiguration())
}

function onErrorEvent(event) {
  // Extract the shaka.util.Error object from the event.
  onError(event.detail);
}

function onError(error) {
    console.error('Error code', error.code, 'object', error);
}
```
INDEX.JS FILE CODE
```
const shaka = require('shaka-player');
const model = require('./model');
const manifestUri = "";

function initApp() {
  // Install built-in polyfills to patch browser incompatibilities.
  shaka.polyfill.installAll();

  // Check to see if the browser supports the basic APIs Shaka needs.
  if (shaka.Player.isBrowserSupported()) {
    // Everything looks good!
    model.initPlayer();
  } else {
    // This browser does not have the minimum set of APIs we need.
    console.error('Browser not supported!');
  }
}

document.addEventListener('DOMContentLoaded', initApp);
```

> ERROR:
> device.type= undefined  browser.name= Chrome  os.name= Linux
> hexa-shaka-player.js:2 https://equidia-vodce-players.hexaglobe.net/mf_data/20210323.json
> hexa-shaka-player.js:2 https://equidia-racing1-p-api.hexaglobe.net/34cdc24……/equidia/equidia-website-web-1/racing1/stream_info.php?format=dashwidevine
> hexa-shaka-player.js:2 manifest API: https://equidia-racing1-p7-cdn.hexaglobe.net/2cfc333……/equidia/equidia-website-web-1/eqdracing1pri_fre.smil/manifestwidevine.mpd
> hexa-shaka-player.js:2 
> {com.widevine.alpha: "https://widevine-dash.ezdrm.com/proxy?pX=4B6508&Cu…ng1%23605a180b%2325ca41faf2ca21e8e89da5e7234bec24"}
> **hexa-shaka-player.js:2 Error code 6002 object 
> Y {severity: 2, category: 6, code: 6002, data: Array(1), handled: false}
> category: 6
> code: 6002
> data: Array(1)
> 0: "Failed to execute 'createMediaKeys' on 'MediaKeySystemAccess': EME use is not allowed on unique origins."
> length: 1
> __proto__: Array(0)
> handled: false
> severity: 2
> __proto__: Object**

Can you please help me why I am not able to load the URI:

Note I am using crome browser

**Comment by TheModMaker** [comment]
The error includes `EME use is not allowed on unique origins`, which comes from the browser.  My guess is this is a `file://` URL or an `http://` url, neither of which support EME.  You need to use a real web server that is hosted on `https://` to be able to play protected content (note you can use `localhost` as `http`, but not other sites).

**Comment by hiren3897** [comment]
When I am running on localhost it gives me the following error displayed in the image.

![Screenshot from 2021-03-23 18-51-25](https://user-images.githubusercontent.com/59652404/112194313-01ef8200-8c09-11eb-92bb-b0bbacb93cc2.png)

**Comment by michellezhuogg** [comment]
That's caused by CORS. You can open a browser with web security disabled.

If you are using Mac:
`open -na Google\ Chrome --args --user-data-dir=/tmp/temporary-chrome-profile-dir --disable-web-security --disable-site-isolation-trials
`

If you are using Linux:
Open a Chrome browser with web security disabled. Run command: 
`
google-chrome --disable-web-security --user-data-dir=~/Desktop/tmp/ 
`

Also, in the Chrome DevTools, set "Bypass for network":
Application -> Service Workers -> Select: √ Bypass for network.

Let us know if that works :)

**Comment by TheModMaker** [comment]
That is a CORS error, see the [doc on MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) for more info.  Your manifest and media files need to have the correct response headers to be visible to JavaScript running on another domain.  You either need to add headers to the manifest/media responses or have the player on the same domain as the manifest/media files.

**Comment by hiren3897** [comment]
> That's caused by CORS. You can open a browser with web security disabled.
> 
> If you are using Mac:
> `open -na Google\ Chrome --args --user-data-dir=/tmp/temporary-chrome-profile-dir --disable-web-security --disable-site-isolation-trials `
> 
> If you are using Linux:
> Open a Chrome browser with web security disabled. Run command:
> `google-chrome --disable-web-security --user-data-dir=~/Desktop/tmp/ `
> 
> Also, in the Chrome DevTools, set "Bypass for network":
> Application -> Service Workers -> Select: √ Bypass for network.
> 
> Let us know if that works :)

Nope, I tried from chrome dev-tools but it didn't work. Thank you

**Comment by hiren3897** [comment]
> That is a CORS error, see the [doc on MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) for more info. Your manifest and media files need to have the correct response headers to be visible to JavaScript running on another domain. You either need to add headers to the manifest/media responses or have the player on the same domain as the manifest/media files.

Yes, You are right because when copy and paste this link directly in the browser it gives response but when I try to do player.load() it gives me CORS errors because the headers are not open for another domain on the server-side. I will discuss this with my teammates tomorrow and let you know :)

**Comment by hiren3897** [comment]
Hello as I was trying to load the manifest in the player which was on the localhost domain and not on the same domain as manifest was. Thank you for your help and guidance it helped me a lot :).

before closing,

(I have just one question can we import shaka as ES6 modules?)

If I have any issues I will reach here back for now I am closing this issue.
