### ISSUE TITLE
Shaka Player + Widevine DRM: Livestream keeps buffering and never plays

### ISSUE THREAD

**Issue by elbougly** [google/shaka-player#3282]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
I tested with 3.0.10 and 2.5.21

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
My custom app

**If custom app, can you reproduce the issue using our demo app?**
My DRM license server has custom requirements so I can't do that

**What browser and OS are you using?**
Chrome and Firefox on Windows

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**

Available in the demo link

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Available in the demo link as well

**What did you do?**

Added my manifest link and configured a request filter to make Shaka work with the license server

**What did you expect to happen?**
The video to play

**What actually happened?**

It loads a few segments and then keeps fetching the manifest and the video never loads:
![image](https://user-images.githubusercontent.com/42193957/112480134-02595b80-8d76-11eb-9487-b448520a99fe.png)

Here's a demo link with the latest debug release so you can test it for yourself:
https://shakra-drm.surge.sh/
The license server sometimes fails with a 403 error code, if this occurs just refresh the page, it tends to work on the 2nd or 3rd refresh

**Comment by TheModMaker** [comment]
The manifest you linked to is static, not live.  If I print `video.buffered` and `video.buffered.start(0)` after starting, it shows 4.6.  So what is probably happening is your manifest and segments don't align.  Your segments are probably 4.6 seconds ahead of what they should be.  You should verify the `presentationTimeOffset` values are correct to adjust the media times back to 0.

**Comment by elbougly** [comment]
Your response was timely and I thank you for that, but I forgot that the manifest was time sensitive, sorry about that.

I went ahead and extended the manifest, it should be valid till the 31th. I also got us a license of a commercial provider and a demo with the same config so you can do your debugging.

[A functional demo from a commercial provider.](https://shakra-drm.surge.sh/bitmovin.html)

The live video also has a timestamp on the top left in GMT+2 if that helps.

Thanks in advance!

**Comment by michellezhuogg** [comment]
Hello @elbougly , are we supposed to reproduce buffering issue with the [demo](https://shakra-drm.surge.sh/bitmovin.html)?  It seems working fine.

**Comment by elbougly** [comment]
Hi @michellezhuogg, no that's a different player that works, the demo that relies on Shaka Player is here:
https://shakra-drm.surge.sh

**Comment by michellezhuogg** [comment]
We found a few possible reasons of the issue:
1. The license request sent to "https://p-drmwv.movetv.com/widevine/proxy" failed, because the access to the requested resource is forbidden. The error was "DRM.LICENSE_REQUEST_FAILED".
2. The log shows there is a gap/overlap between Periods. A large gap would cause the video not starting to play, unless we are configured to jump large gaps. To verify that, you can set "streaming. jumpLargeGaps" to true in the config.
However, to solve the root cause, you should check the duration and the start time of the periods in the manifest.

Let us know if that helps :)

**Comment by elbougly** [comment]
wow, setting streaming.jumpLargeGaps to true actually worked, thanks a lot Michelle!
