### ISSUE TITLE
Audio-video out of sync when using a 25 fps video

### ISSUE THREAD

**Issue by aletorrado** [google/shaka-player#329]
Hi, I'm experiencing audio-video out of sync, after aproximately 10 minutes of playback, when using a video with 25 fps. Using 30 fps, everything seems to be ok.

Encoding is ok because when seeking the video, or refreshing the browser, it syncs fine.

Anyway, I'm not sure if this is a shaka-player or browser issue, but I've experienced this on Chrome and Firefox.

**Comment by joeyparrish** [comment]
Hi @aletorrado,

If you can find another JS/MSE player that plays in-sync, it could be a Shaka issue.  Have you tried in [dash.js](https://github.com/Dash-Industry-Forum/dash.js/)?

If the desync is present in both players, it *could* be a browser issue.  But from what I know of MSE, I find it very unlikely that this specific frame rate is incorrectly supported.  So my next suggestion is that you check that the content has been correctly encoded in the first place.

I don't know how you are encoding your content, but it would be easy with ffmpeg, IMO, to make a mistake that produces this desync.  For example, with a 30fps input file, the position of the `-r` option dictates whether your are overriding the input frame rate or specifying an output framerate:

```sh
ffmpeg -i input.mp4   -r 25 frames_dropped.mp4
ffmpeg -r 25 -i input.mp4   bad_sync.mp4
```

Does this help?

**Comment by tdrews** [comment]
Hi, is this still an issue for you?

**Comment by aletorrado** [comment]
Not anymore. I've fixed this adding `-async 1 -vsync 1` to the ffmpeg command. It seems like a browser issue anyways.
