### ISSUE TITLE
Video stops loadng when video is navigated to end using arrow key

### ISSUE THREAD

**Issue by surajkumar-sk** [google/shaka-player#3291]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
Latest

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
demo

**If custom app, can you reproduce the issue using our demo app?**
yes

**What browser and OS are you using?**
chrome, windows 8.1

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**

navigated video to the end using arrow keys.

https://user-images.githubusercontent.com/71056993/112752654-dfeb5c00-8f88-11eb-9b81-2c67b17ffc10.mp4

**What did you expect to happen?**
Video to end. 

**What actually happened?**

the video kept showing the buffering image and the video stopped loading, even when the reset button is clicked or the video
is navigated through seek bar it doesn't load. it goes back to normal when the website is reloaded. a video above describes it better.

**Comment by surajkumar-sk** [comment]
Please refer to pull request comments of #3267 to avoid working on a solution that Members think might not be the right way of approaching it.

**Comment by joeyparrish** [comment]
Unable to reproduce this issue in the latest release.
