### ISSUE TITLE
Widevine licence setup causes glitch is currently playing audio

### ISSUE THREAD

**Issue by enjikaka** [google/shaka-player#3293]
I tried contacting widevine about this but they just responded with:

> Please create an issue at the Shaka Player github page. We have developers who monitor the form regularly and can respond to your question directly: https://github.com/google/shaka-player/issues

So sorry if this is considered a trash issue for the shaka-player project...

I actually think what I'm seeing is a recent Chromium bug, which we think also has existed pre Chrome v72. I tried several old shaka-player versions and I experience this glitch in all of them. I haven't tried any other Widevide JS-player though.

Short summary: Having two shaka instances on the same origin across different tabs, or on the same page. One is playing, the other one is responding to `load()`. Both playing widevine content. When the widevine licence response is handled in the `load()`ing shaka instance, the currently playing shaka instance get audio and video glitches.

More details: https://bugs.chromium.org/p/chromium/issues/detail?id=1193437

At TIDAL we got a lot of user reports on this, [some of them here](https://www.reddit.com/r/TIdaL/comments/mejqnm/sound_lagshiccups_since_the_last_update/). So we had to disable the preloading of next track in a hotfix.

**Comment by TheModMaker** [comment]
Yes, this doesn't really apply to us, this is definitely a Chrome bug.  There probably isn't anything we can do about it.  It looks like all the correct people are on the Chrome bug, so it should get handled soon.  So I'm going to close this issue.

If you want to implement that workaround they suggested, you may be able to hook the `update` method to delay calling into the browser.  I think it work correctly:

```js
const orig = MediaKeySession.prototype.update;
MediaKeySession.prototype.update = async function() {
  await makeDelayPromise();
  return orig.apply(this, arguments);
};
```
