### ISSUE TITLE
Shaka-Player does not recognize left, right, and center positioning for VOD subtitles

### ISSUE THREAD

**Issue by kumarashu123** [google/shaka-player#3296]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
2.5.10

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Custom App

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Chrome Version 89.0.4389.114 (Official Build) (x86_64) and MAC OS Big Sur version - 11.2.3

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
TTML sample response
`<?xml version="1.0" encoding="UTF-8"?><tt xmlns:smpte="http://www.smpte-ra.org/schemas/2052-1/2010/smpte-tt" xmlns="http://www.w3.org/ns/ttml" xmlns:ttm="http://www.w3.org/ns/ttml#metadata" xmlns:tts="http://www.w3.org/ns/ttml#styling" xml:space="default" xml:lang="may" startpts="169751401"><head>
    <metadata>
      <ttm:title/>
    </metadata>
    <styling>
	<style xml:id="style.center.outline" xmlns:tts="http://www.w3.org/ns/ttml#style" tts:fontFamily="Arial" tts:fontSize="100%" tts:fontStyle="normal" tts:fontWeight="normal" tts:backgroundColor="transparent" tts:color="white" tts:textOutline="black 2px" tts:textAlign="center"/>
	<style xml:id="style.right.outline" tts:fontFamily="Arial" tts:fontSize="100%" tts:fontStyle="normal" tts:fontWeight="normal" tts:backgroundColor="transparent" tts:color="white" tts:textOutline="black 2px" tts:textAlign="right"/>
	<style xml:id="style.left.outline" tts:fontFamily="Arial" tts:fontSize="100%" tts:fontStyle="normal" tts:fontWeight="normal" tts:backgroundColor="transparent" tts:color="white" tts:textOutline="black 2px" tts:textAlign="left"/>
    </styling>`
    `<layout>
      <region xml:id="r0" tts:displayAlign="after" tts:origin="10% 69%" tts:extent="80% 26%"/>
      <region xml:id="r1" tts:displayAlign="after" tts:origin="10% 53%" tts:extent="80% 26%"/>
      <region xml:id="r2" tts:displayAlign="before" tts:origin="10% 2%" tts:extent="80% 26%"/>
    </layout>`
  `</head><body><div><p style="style.right.outline" begin="00:31:24.720" region="r1" xml:id="p486" end="00:31:26.879" ><span tts:direction="rtl">Dapat kita lihat<br/>dari raut wajah Rashid.</span></p></div></body></tt>`

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**

Play the asset and observe the subtitle position

**What did you expect to happen?**
The subtitle should respect the position assigned in TTML file

**What actually happened?**

Clearly the subtitle position is not as per the position seen in TTML file.

* Screenshot of the issue as below
![image](https://user-images.githubusercontent.com/10974291/113146266-1658fd80-924d-11eb-9b6b-fd4e2a051d5f.png)

* Screenshot of the expected behaviour 
![image](https://user-images.githubusercontent.com/10974291/113146331-25d84680-924d-11eb-8522-7d7efceea182.png)

**Comment by michellezhuogg** [comment]
Hello @kumarashu123 ,

Would you please send us a sample manifest to reproduce and fix this issue? You can send it to shaka-player-issues@google.com if it's private.
Thank you!

**Comment by joeyparrish** [comment]
Please also try your content in our demo app, which uses our UI for subtitle display.  Not all properties of subtitles are used in native (non-UI/non-DOM) display, as provided by the video element itself.  If this fixes the issue, we can guide you on either using our UI (recommended) or in using our UI's text display module without adopting the full UI.

**Comment by kumarashu123** [comment]
Thanks for the quick reply.
I have tried my content in demo app, Subtitle does not display expected.
<style xml:id="style.right.outline" tts:fontFamily="Arial" tts:fontSize="100%" tts:fontStyle="normal" tts:fontWeight="normal" tts:backgroundColor="transparent" tts:color="white" tts:textOutline="black 2px" tts:textAlign="right"/>

As per style it should display right align but its displaying in center.

In my app i am using UI's text displayer only - Using shaka version **2.5.10**
const textDisplayer = function() {
        return new shaka.ui.TextDisplayer(player.getMediaElement(), document.getElementById("video").parentNode); 
};
PLAYER.configure("textDisplayFactory", textDisplayer);  

and also tried version **3.0.10**
const textDisplayer = function() {
        return new shaka.text.UITextDisplayer(player.getMediaElement(), document.getElementById("video").parentNode); 
};
PLAYER.configure("textDisplayFactory", textDisplayer);  

Issue is seen in both version

I will try to get mpd url

**Comment by joeyparrish** [comment]
> I will try to get mpd url

Thanks!

**Comment by kumarashu123** [comment]
Unfortunately the manifest cannot be shared (it is a paid content and is owned by our customer), but is it possible to debug based on this ttml


```XML
<tt xmlns:smpte="http://www.smpte-ra.org/schemas/2052-1/2010/smpte-tt" xmlns="http://www.w3.org/ns/ttml" xmlns:ttm="http://www.w3.org/ns/ttml#metadata" xmlns:tts="http://www.w3.org/ns/ttml#styling" xml:space="default" xml:lang="may" startpts="169751401">
   <head>
      <metadata>
         <ttm:title/>
      </metadata>
      <styling>
         <style xml:id="style.center.outline" xmlns:tts="http://www.w3.org/ns/ttml#style" tts:fontFamily="Arial" tts:fontSize="100%" tts:fontStyle="normal" tts:fontWeight="normal" tts:backgroundColor="transparent" tts:color="white" tts:textOutline="black 2px" tts:textAlign="center"/>
         <style xml:id="style.right.outline" tts:fontFamily="Arial" tts:fontSize="100%" tts:fontStyle="normal" tts:fontWeight="normal" tts:backgroundColor="transparent" tts:color="white" tts:textOutline="black 2px" tts:textAlign="right"/>
         <style xml:id="style.left.outline" tts:fontFamily="Arial" tts:fontSize="100%" tts:fontStyle="normal" tts:fontWeight="normal" tts:backgroundColor="transparent" tts:color="white" tts:textOutline="black 2px" tts:textAlign="left"/>
      </styling>
      <layout>
         <region xml:id="r0" tts:displayAlign="after" tts:origin="10% 69%" tts:extent="80% 26%"/>
         <region xml:id="r1" tts:displayAlign="after" tts:origin="10% 53%" tts:extent="80% 26%"/>
         <region xml:id="r2" tts:displayAlign="before" tts:origin="10% 2%" tts:extent="80% 26%"/>
      </layout>
   </head>
   <body>
      <div>
         <p style="style.right.outline" begin="00:31:24.720" region="r1" xml:id="p486" end="00:31:26.879" ><span tts:direction="rtl">Dapat kita lihat<br/>dari raut wajah Rashid.</span></p>
      </div>
   </body>
</tt>

Thanks!

**Comment by TheModMaker** [comment]
I created a simple TTML file we can test with.  I can  reproduce with the demo using:

```js
shakaDemoMain.player_.addTextTrack(
    'https://storage.googleapis.com/shaka-demo-assets/_bugs/3296/textAlign.ttml',
    'en', '', 'application/ttml+xml');
```

**Comment by avelad** [comment]
@joeyparrish it was resolved with https://github.com/google/shaka-player/commit/e9df8fb10c3752cb833e89c8ac793241497e29b6

**Comment by joeyparrish** [comment]
Thanks!
