### ISSUE TITLE
Is possible run HLS Fair Play on Safari with useNativeHlsOnSafari: false?

### ISSUE THREAD

**Issue by qba86** [google/shaka-player#3297]
**What version of Shaka Player are you using?**
2.5.21

**Please ask your question**

Native support for HLS on Safari has disadvantages eg. in custom HttpXHRPlugin I can't detect segments requests.

So, is possible run HLS Fair Play on Safari with useNativeHlsOnSafari: false?

If yes, have you any examples?

**Comment by avelad** [comment]
It is not possible to do this. Failed to get FairPlay to work with MSE yet.

**Comment by qba86** [comment]
ok, but generally is it possible for this time? If yes, is it on Shaka Player roadmap?

**Comment by TheModMaker** [comment]
Correct.  We only support FairPlay with `src=` at the moment.  But it seems with #3346, it may be possible in the future.
