### ISSUE TITLE
Subtitles

### ISSUE THREAD

**Issue by stefanovualto** [google/shaka-player#3298]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.10

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Didn't try

**Are you using the demo app or your own custom app?**
Demo app

**If custom app, can you reproduce the issue using our demo app?**
n/a

**What browser and OS are you using?**
MacOS 11.2.3 Chrome  89.0.4389.90 (Official Build) (x86_64)

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
n/a

**What are the manifest and license server URIs?**
- vodDashMultiAudiowithOneText:
"https://d1chyo78gdexn4.cloudfront.net/vualto-demo/elephants-dream/elephants-dream_nodrm.ism/manifest.mpd

- vodDashWithMultiText:
https://d1chyo78gdexn4.cloudfront.net/vualto-demo/sintel/sintel_nodrm.ism/manifest.mpd

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

<details><summary>The default configuration of the demo page</summary>
<p>

  ```json
{
    "drm": {
        "retryParameters": {
            "maxAttempts": 2,
            "baseDelay": 1000,
            "backoffFactor": 2,
            "fuzzFactor": 0.5,
            "timeout": 0
        },
        "servers": {},
        "clearKeys": {},
        "advanced": {
            "com.widevine.alpha": {
                "distinctiveIdentifierRequired": false,
                "persistentStateRequired": false,
                "videoRobustness": "",
                "audioRobustness": "",
                "serverCertificate": {},
                "individualizationServer": ""
            },
            "com.microsoft.playready": {
                "distinctiveIdentifierRequired": false,
                "persistentStateRequired": false,
                "videoRobustness": "",
                "audioRobustness": "",
                "serverCertificate": {},
                "individualizationServer": ""
            },
            "com.apple.fps.1_0": {
                "distinctiveIdentifierRequired": false,
                "persistentStateRequired": false,
                "videoRobustness": "",
                "audioRobustness": "",
                "serverCertificate": {},
                "individualizationServer": ""
            },
            "com.adobe.primetime": {
                "distinctiveIdentifierRequired": false,
                "persistentStateRequired": false,
                "videoRobustness": "",
                "audioRobustness": "",
                "serverCertificate": {},
                "individualizationServer": ""
            },
            "org.w3.clearkey": {
                "distinctiveIdentifierRequired": false,
                "persistentStateRequired": false,
                "videoRobustness": "",
                "audioRobustness": "",
                "serverCertificate": {},
                "individualizationServer": ""
            }
        },
        "delayLicenseRequestUntilPlayed": false,
        "logLicenseExchange": false,
        "updateExpirationTime": 1
    },
    "manifest": {
        "retryParameters": {
            "maxAttempts": 2,
            "baseDelay": 1000,
            "backoffFactor": 2,
            "fuzzFactor": 0.5,
            "timeout": 0
        },
        "availabilityWindowOverride": null,
        "disableAudio": false,
        "disableVideo": false,
        "disableText": false,
        "defaultPresentationDelay": 0,
        "dash": {
            "clockSyncUri": "https://shaka-player-demo.appspot.com/time.txt",
            "ignoreDrmInfo": false,
            "xlinkFailGracefully": false,
            "ignoreMinBufferTime": false,
            "autoCorrectDrift": true,
            "initialSegmentLimit": 1000,
            "ignoreSuggestedPresentationDelay": false,
            "ignoreEmptyAdaptationSet": false
        },
        "hls": {
            "ignoreTextStreamFailures": false,
            "useFullSegmentsForStartTime": false
        }
    },
    "streaming": {
        "retryParameters": {
            "maxAttempts": 2,
            "baseDelay": 1000,
            "backoffFactor": 2,
            "fuzzFactor": 0.5,
            "timeout": 0
        },
        "rebufferingGoal": 2,
        "bufferingGoal": 10,
        "bufferBehind": 30,
        "ignoreTextStreamFailures": false,
        "alwaysStreamText": false,
        "startAtSegmentBoundary": false,
        "smallGapLimit": 0.5,
        "jumpLargeGaps": false,
        "durationBackoff": 1,
        "forceTransmuxTS": false,
        "safeSeekOffset": 5,
        "stallEnabled": true,
        "stallThreshold": 1,
        "stallSkip": 0.1,
        "useNativeHlsOnSafari": true,
        "inaccurateManifestTolerance": 2
    },
    "offline": { "usePersistentLicense": true },
    "abr": {
        "enabled": true,
        "defaultBandwidthEstimate": 10000000,
        "switchInterval": 8,
        "bandwidthUpgradeTarget": 0.85,
        "bandwidthDowngradeTarget": 0.95,
        "restrictions": {
            "minWidth": 0,
            "maxWidth": null,
            "minHeight": 0,
            "maxHeight": null,
            "minPixels": 0,
            "maxPixels": null,
            "minFrameRate": 0,
            "maxFrameRate": null,
            "minBandwidth": 0,
            "maxBandwidth": null
        }
    },
    "preferredAudioLanguage": "en-GB",
    "preferredTextLanguage": "en-GB",
    "preferredVariantRole": "",
    "preferredTextRole": "",
    "preferredAudioChannelCount": 2,
    "restrictions": {
        "minWidth": 0,
        "maxWidth": null,
        "minHeight": 0,
        "maxHeight": null,
        "minPixels": 0,
        "maxPixels": null,
        "minFrameRate": 0,
        "maxFrameRate": null,
        "minBandwidth": 0,
        "maxBandwidth": null
    },
    "playRangeStart": 0,
    "playRangeEnd": null
  }
  ```
</p>
</details>

**What did you do?**
Test 1
- load on the shaka demo page the stream with one subtitle (cf. vodDashMultiAudiowithOneText)

Test2
- load on the shaka demo page the stream with multiple subtitles, but the same language (cf. vodDashWithMultiText)

**What did you expect to happen?**

Test1
- to have one subtitle listed

Test2
- to have 5 subtitles listed with the same language (it might be the cause of the issue, but I am not the actual behavior is a good one)

**What actually happened?**

Test1
- no subtitles are available

Test2
- only 1 subtitle is available

Thank you in advance for your help!

**Comment by michellezhuogg** [comment]
Hello @stefanovualto ,

1. For the vodDashMultiAudiowithOneText manifest, could you please point me to the AdaptationSet of "text" in the manifest?
2. For the vodDashWithMultiText manifest, we filtered the text streams and kept one, since the text streams have the same attributes other than RepresentationIds. The best way to fix that might be having different languages or labels for the text streams.
https://github.com/google/shaka-player/blob/e6108060bd7b185e7d9d6d6ffa66fd05f01e35a7/lib/util/periods.js#L279

**Comment by stefanovualto** [comment]
Hello @michellezhuogg ,

Thank you for you quick answer.

1. I won't insist on that it seems to be a content issue (as often it is 😭 ). As you pointed no adaptionSet are available. And also because I tested first it on dashjs and it displayed a caption, Then I thought that something was wrong in shaka, but after testing this content on bitmovin/theoplayer/videojs/jwplayer none of them were displaying captions. Then I don't know how dashjs do it, but it doesn't seem to be the norm... Then I guess that I can live with that 😄 
2. The piece of code that you pointed looks perfect to me. But I have a concern looking at the adaptationSet that have different Id's which should then make them different in the `filterOutTextStreamDuplicates_`. Am I missing something?

Thanks a lot for helping understanding 🤓

**Comment by michellezhuogg** [comment]
> The piece of code that you pointed looks perfect to me. But I have a concern looking at the adaptationSet that have different Id's which should then make them different in the filterOutTextStreamDuplicates_. Am I missing something?

When we combine the streams across periods, we only have the streams in each period, and don't have the adaptation set ids.  We do have the representation ids stored as the "originalId" for each stream, however we don't use that as distinctions between streams.

**Comment by stefanovualto** [comment]
Thank you for improving my understanding.

Do you think it is something that could be used in the `filterOutTextStreamDuplicates_` at some point?

If not I would be interested about the reason for that. Because again, I am in the learning process and I would love to understand which use cases could create issues and it will help me to argue for the content to be changed.

Thank you again for your answer and work on shakajs! ❤️

**Comment by michellezhuogg** [comment]
If the two streams have the same other attributes but different representation ids, they are different streams. 
However, when displaying the streams to the users, having both the streams with same languages and roles makes it hard for the user to know which to select, and the IDs aren't meant to be displayed to the user.
Thus, we think a better way to distinguish between them would be different languages or roles. 

Let us know if that helps :)

**Comment by stefanovualto** [comment]
It makes sense from a user point of view.

Thank you again for helping!
