### ISSUE TITLE
Audio glitch at period transition

### ISSUE THREAD

**Issue by ronak2121** [google/shaka-player#3300]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.20

**Please ask your question**

We have audio only Dash streams stitched across multiple assets, some drm protected and others in the clear. Although the codec information is the same, since encryption changes across period boundaries, we can't signal period continuity/connectivity.

I've noticed that ShakaPlayer is able to seamlessly transition across this boundary sometimes, but not always.

Does ShakaPlayer do any optimizations to enable the CDM/decryption module but keep the decoder initialized by confirming that the contents of esds are the same in both moovs? And if ShakaPlayer does this, are we still at the mercy of the browser media engine for this?

**Comment by TheModMaker** [comment]
We don't do any processing or reading of the media segments, we just give the data to the browser.  We use info in the manifest to detect which streams to select.  For example, we stick with the same codec between Periods, but we have no way of detecting they are compatible.  We assume that the browser can switch between clear and encrypted content correctly.

What problems are you seeing?  Can you provide an example stream URL? Remember that you need to configure a license server if you expect to see encrypted content later.  This ensures we setup the media pipeline correctly to expect encrypted content later.  See also #3281.

**Comment by ronak2121** [comment]
We see an audio glitch as you switch between the two periods, because it looks like you/the browser are resetting the audio decoder somewhere. The Dash Manifest already includes all 4 fundamental audio properties as well as ContentProtection...so you can compute this without looking at the media.

**Comment by TheModMaker** [comment]
What do you mean?  Do you mean like switching channel count?  Could you provide an example manifest URL?

**Comment by joeyparrish** [comment]
> ... it looks like you/the browser are resetting the audio decoder somewhere.

I am fairly certain we never do this explicitly.  It could be done implicitly somewhere by the browser in response to something in the media or some API call by us.  Chrome's media-internal logs could help shed some light on this.  You can find logs at `chrome://media-internals`.
