### ISSUE TITLE
Major bug with Shaka. Why didn't anyone notice this Before

### ISSUE THREAD

**Issue by surajkumar-sk** [google/shaka-player#3302]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
latest

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `master`?**
yes

**Are you using the demo app or your own custom app?**
yes

**If custom app, can you reproduce the issue using our demo app?**
yes

**What browser and OS are you using?**
Chrome April Edition

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**

Nothing just wrote a catchy Title.

**What did you expect to happen?**
People To open this issue and get pranked.

**What actually happened?**

Donno, you tell me?

![April-fools-wishes](https://user-images.githubusercontent.com/71056993/113297832-f870b480-92af-11eb-99b6-d90182e4dd8c.jpg)

**Comment by surajkumar-sk** [comment]
I'll delete this by tomorrow. 😂

**Comment by joeyparrish** [comment]
🤣  Let's call it "working as intended".

![poster](https://user-images.githubusercontent.com/6843156/113354598-44dde380-92f4-11eb-9c59-4f1a2c99e3f6.gif)

Happy April!
