### ISSUE TITLE
Ad click's management

### ISSUE THREAD

**Issue by dave1981** [google/shaka-player#3304]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.10

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
I don't know

**Are you using the demo app or your own custom app?**
custom app

**If custom app, can you reproduce the issue using our demo app?**
No

**What browser and OS are you using?**
Windows, Firefox or Chrome

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**
I don't know if it's a bug... I have a clickable ad, I want to catch the "clicked" event and do something depending on the destination url; in some cases, I want to stop opening the new tab with the destination url.
To achieve this, I use the "addEventListener(shaka.ads.AdManager.AD_CLICKED..." function, with "event.preventDefault" to stop redirection

**What did you expect to happen?**
I expect two things:
- to know in some way what is the url that should be opened after the click
- to block the opening of the new tab

**What actually happened?**
The event object (screenshot below) is really difficult to be parsed, it has no "sdkAdObject" or "originalEvent" property, so I can't get the destination url. At the same point, event.preventDefault doesn't block the opening of the new tab.
![evento](https://user-images.githubusercontent.com/5500634/113391043-2ed33000-9393-11eb-8f38-2867a7fd942c.PNG)

**Comment by ismena** [comment]
@dave1981 Our fault! Somehow that particular event slipped through the cracks when we were adding the 'originalEvent' fields. I have a CL out to fix it!
Regarding the preventDefault issue - my guess is, you will have better luck setting it on the original event once you have access to that. Our event doesn't redirect to another page, it's the IMA event that does.

**Comment by ismena** [comment]
Okay, please try now with the latest master

**Comment by dave1981** [comment]
I'm working with npm package, so I prefer to wait the next release. Thank you for your help!

**Comment by ismena** [comment]
@dave1981 I meant that you can test it on the master to see if the change covers everything you needed.
For production use - yes, it will be in the upcoming v3.1 release.
