### ISSUE TITLE
Update icon doesn't work for 'muted' attribute.

### ISSUE THREAD

**Issue by Ketan2010** [google/shaka-player#3305]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
Latest

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `master`?**
yes

**Are you using the demo app or your own custom app?**
Custom app

**If custom app, can you reproduce the issue using our demo app?**
yes

**What browser and OS are you using?**
Chrome, Windows

**What actually happened?**

When we set `muted` (optional attribute) in video tag as follow,
`<video autoplay muted data-shaka-player id="video" style="width:100%;height:100%"></video>`
then video starts with muted audio, volume bar is set to level 0 but **mute button icon remains unmuted and doesn't update to muted.**
![image](https://user-images.githubusercontent.com/57591621/113484990-eb7add80-94c8-11eb-8051-f20e2f24a180.png)

**What did you expect to happen?**
when we use `muted` attribute in video tag, icon also should be updated to mute,
![image](https://user-images.githubusercontent.com/57591621/113484962-c6866a80-94c8-11eb-8e1d-25545740f26c.png)

**Comment by prsndp** [comment]
Hi @Ketan2010 Can I work on this issue? Please assign me if it is open.

**Comment by Ketan2010** [comment]
Hello @prsndp,
yes if you or anyone else would like to work on this can work. But I don't have rights to assign the issue.
Before start, I suggest you to let wait for suggestions/guidance from some experts.

**Comment by prsndp** [comment]
> Hello @prsndp,
> yes if you or anyone else would like to work on this can work. But I don't have rights to assign the issue.
> Before start, I suggest you to let wait for suggestions/guidance from some experts.

okay
