### ISSUE TITLE
"Error: State error" while adding external vtt subtitles at IOS safari

### ISSUE THREAD

**Issue by kovaletsyurii** [google/shaka-player#3312]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** 
Yes

**What version of Shaka Player are you using?**
2.5.18

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
My custom app

**If custom app, can you reproduce the issue using our demo app?**
It's pretty hard in my case

**What browser and OS are you using?**
IOS 14 Safari

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
--

**What are the manifest and license server URIs?**
--

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

{
  "drm": {
    "retryParameters": {
      "maxAttempts": 2,
      "baseDelay": 1000,
      "backoffFactor": 2,
      "fuzzFactor": 0.5,
      "timeout": 0
    },
    "servers": {},
    "clearKeys": {},
    "advanced": {},
    "delayLicenseRequestUntilPlayed": false,
    "logLicenseExchange": false,
    "updateExpirationTime": 1
  },
  "manifest": {
    "retryParameters": {
      "maxAttempts": 2,
      "baseDelay": 1000,
      "backoffFactor": 2,
      "fuzzFactor": 0.5,
      "timeout": 0
    },
    "availabilityWindowOverride": null,
    "disableAudio": false,
    "disableVideo": false,
    "disableText": false,
    "defaultPresentationDelay": 0,
    "dash": {
      "clockSyncUri": "",
      "ignoreDrmInfo": false,
      "xlinkFailGracefully": false,
      "ignoreMinBufferTime": false,
      "autoCorrectDrift": true,
      "initialSegmentLimit": 1000,
      "ignoreSuggestedPresentationDelay": false,
      "ignoreEmptyAdaptationSet": false
    },
    "hls": {
      "ignoreTextStreamFailures": false,
      "useFullSegmentsForStartTime": false
    }
  },
  "streaming": {
    "retryParameters": {
      "maxAttempts": 2,
      "baseDelay": 1000,
      "backoffFactor": 2,
      "fuzzFactor": 0.5,
      "timeout": 0
    },
    "rebufferingGoal": 2,
    "bufferingGoal": 10,
    "bufferBehind": 30,
    "ignoreTextStreamFailures": false,
    "alwaysStreamText": false,
    "startAtSegmentBoundary": false,
    "smallGapLimit": 0.5,
    "jumpLargeGaps": false,
    "durationBackoff": 1,
    "forceTransmuxTS": false,
    "safeSeekOffset": 5,
    "stallEnabled": true,
    "stallThreshold": 1,
    "stallSkip": 0.1,
    "useNativeHlsOnSafari": true,
    "inaccurateManifestTolerance": 2
  },
  "offline": {
    "usePersistentLicense": true
  },
  "abr": {
    "enabled": false,
    "defaultBandwidthEstimate": 8750000,
    "switchInterval": 8,
    "bandwidthUpgradeTarget": 0.85,
    "bandwidthDowngradeTarget": 0.95,
    "restrictions": {
      "minWidth": 0,
      "maxWidth": null,
      "minHeight": 0,
      "maxHeight": null,
      "minPixels": 0,
      "maxPixels": null,
      "minFrameRate": 0,
      "maxFrameRate": null,
      "minBandwidth": 0,
      "maxBandwidth": null
    }
  },
  "preferredAudioLanguage": "",
  "preferredTextLanguage": "",
  "preferredVariantRole": "",
  "preferredTextRole": "",
  "preferredAudioChannelCount": 2,
  "restrictions": {
    "minWidth": 0,
    "maxWidth": null,
    "minHeight": 0,
    "maxHeight": null,
    "minPixels": 0,
    "maxPixels": null,
    "minFrameRate": 0,
    "maxFrameRate": null,
    "minBandwidth": 0,
    "maxBandwidth": null
  },
  "playRangeStart": 0,
  "playRangeEnd": null
}

**What did you do?**
I've loaded the m3u8 stream at IOS 14 using something like 
`await this.player.load( this.videoFile )`
where this.videoFile is an external link to my video stream, 
after that I try to add vtt captions to this video with next lines of code
` await this.player.addTextTrack(this.subtitles, 'en', 'subtitle', 'text/vtt')`
`const tracks = this.player.getTextTracks();`
`tracks.length && this.player.selectTextTrack(0);`
`tracks.length && this.player.setTextTrackVisibility(true);`
    
**What did you expect to happen?**
I expect to see the added subtitles over the video content, like it works in another browers

**What actually happened?**
I get an error with text: **"Error: State error!"** at _addTextTrack_ method

**Comment by ismena** [comment]
Hi @kovaletsyurii 
Do you think you can give us the manifest and the subtitle track uri for the repro?
I think only the subtitle uri should work too.

In Safari, we use its native hls implementation unlike in other browsers. My guess is, something might be going wrong with that (either we have a bug or Safari is rejecting the track for some reason), but we'll need a repro to be sure what's going on.

**Comment by kovaletsyurii** [comment]
Hi @ismena, Thanks for replying. Unfortunately I can't provide the manifest and subtitle tracks because of security reasons of my project, but I've also tried with [this subtitles](https://gist.githubusercontent.com/samdutton/ca37f3adaf4e23679957b8083e061177/raw/e19399fbccbc069a2af4266e5120ae6bad62699a/sample.vtt) track from github gist and got the same error.

**Comment by avelad** [comment]
@kovaletsyurii Can you try with 3.0.10 and the master branch? In the master branch I have made several changes related to addTextTrack and the new addTextTrackAsync

**Comment by kovaletsyurii** [comment]
<img width="317" alt="Screenshot 2021-04-09 at 13 33 20" src="https://user-images.githubusercontent.com/15369125/114167862-28672a00-9938-11eb-93b2-dfe4bd66ec3f.png">
@avelad I've try with code from _master_ and **addTextTrack** / **addTextTrackAsync** methods and got another one error. In web browser all still works as before.

**Comment by ismena** [comment]
I can get a repro with the subtitle track provided by @kovaletsyurii 
Here is what I see: the track is added to the video element, but its kind is changed from "subtitles" to "metadata" in the internal structure of the video object, so it doesn't show up when we query for subtitle tracks.

The video DOM element in the console after adding the track:
```
<video data-shaka-player="" autoplay="" playsinline="" id="video" class="shaka-video" poster="https://shaka-player-demo.appspot.com/assets/audioOnly.gif" tabindex="-1" src="https://storage.googleapis.com/shaka-demo-assets/bbb-dark-truths-hls/hls.m3u8">
<track 
src="https://gist.githubusercontent.com/samdutton/ca37f3adaf4e23679957b8083e061177/raw/e19399fbccbc069a2af4266e5120ae6bad62699a/sample.vtt" label="" kind="subtitle" srclang="en">
</video>
```
The textTracks on the video object in the js code at the same time:
```
TextTrackList
0: TextTrack {listeners: Object, id: "", kind: "metadata", label: "", language: "en", …}
```
Sounds like a Safari bug to me.

@TheModMaker @joeyparrish thoughts? Did I miss something? Can we safely work around this or is reporting to Safari the only option?

**Comment by BucherTomas** [comment]
If the vtt file is pulled from another domain, it might be just that the `<video>` element in this scenario requires `crossorigin="anonymous"` as explained here [https://docs.videojs.com/docs/guides/text-tracks.html#subtitles-from-another-domain](url).

Recent Safari versions require presence of this atribute as we found out in our own project, but it affected also desktop Safari, while it seems here that it works for OP on desktop.

**Comment by kovaletsyurii** [comment]
Thanks all for answers, now I've cloned the master branch and build it locally, then I import player build from dist folder and get the same error as I've attached previously, then I've tried to serve vtt file locally to avoid any crossorigin requests and it didn't help(
