### ISSUE TITLE
Initialisation fails with this error: (Failed to execute 'createMediaKeys' on 'MediaKeySy…ccess': EME use is not allowed on unique origins

### ISSUE THREAD

**Issue by danishshard-byjus** [google/shaka-player#3313]
`<!--` NOTE:
  This template is for questions.
  If you suspect that your issue might be a bug, but aren't sure, please file the bug template instead.
  If you want to know whether we will support a feature, please file the feature request template instead.
-->

**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.10

**Please ask your question**
I am trying to open encrypted video in React webview and my webview is not hosted anywhere. Android opens the webview using file url directly for example(file://drivename/foldername/index.html). 
I do not interact with the DRM server directly instead use a middleware api for the same. 
I am able to  play the videos on my localhost but after generating  the build, player initialisation  fails with the following error when using file URL.

```
 {
category: 6
code: 6002
data: ["Failed to execute 'createMediaKeys' on 'MediaKeySy…ccess': EME use is not allowed on unique origins."]
handled: false
severity: 2 
}
```

NOTE: I am able to play unencrypted video with file url though.

**Comment by TheModMaker** [comment]
`EME use is not allowed on unique origins` is an error from the browser.  We can't change this behavior.  EME isn't available when using `file://` URLs.

**Comment by danishshard-byjus** [comment]
Is there any other-way to run the encrypted video on a file URL.

**Comment by TheModMaker** [comment]
No, the only way to play encrypted videos is with EME.
