### ISSUE TITLE
Cast failing while playing encrypted content?

### ISSUE THREAD

**Issue by mbutan** [google/shaka-player#3314]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.1.0

**Please ask your question**
I've been trying to cast encrypted video content on my TV. However, when only try to load encrypted content with DRM, the cast fails with a network error on the license URL (the request is not authorized). My guess is that a local request is not passed entirely to the remote player. I wonder is it possible to redirect my local "registerRequestFilter" handler to a remote one and attach missing headers into the request? Temporary, I still keep using testing receiver ID "930DEB06"

What I tested with my setup so far?
- I've already tested casting a simple (not encrypted) "dash" video - works
- I've already tested encrypted "dash" video on a local player - works

What does not work?
- Casting encrypted "dash" video - does not work

**Comment by TheModMaker** [comment]
If you need a custom request/response filter, then you need to create a custom receiver app to include your filter.  There is no way to send functions across the cast channel to the common receiver.  You can checkout [our cast receiver](https://github.com/google/shaka-player/blob/master/demo/cast_receiver/receiver_app.js) for an example.

**Comment by mbutan** [comment]
@TheModMaker thanks the answer was helpful
