### ISSUE TITLE
Allow banning of certain video codecs from a certain resolution

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#3316]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes

**Is your feature request related to a problem? Please describe.**

I am in the middle of a transition to support H264 and H265 on some devices and I am finding that in 4K (2160p) I have problems with H264 videos in 4K but not in H265.
The specific device is the Xbox One and the Xbox Series

**Describe the solution you'd like**

Add a confirmation to allow the ban of certain video codecs from a certain resolution.

**Describe alternatives you've considered**

Doing this on the server side, but it can be problematic if you are not the owner of the CDN and the origin.

**Comment by TheModMaker** [comment]
This would be really complex to configure and a rare edge case that most won't need.  What problems are you seeing?  If this is consistent, we may want to filter these out in the library.  But in general, I think there are two options you could use in your app to do it.

First would be to hook `MediaSource.isTypeSupported` to return `false` for values you don't want us to use.  We also pass the width/height, so you can use this for filtering (e.g. `video/mp4;codecs="avc1.4d401f";width="1252";height="720"`).

```js
const orig = MediaSource.isTypeSupported;
MediaSource.isTypeSupported = (str) => {
  if (!orig(str)) return false;
  // Parse width/height...
  return shouldPlay(str);
};
```

Second, you could use the `manifestparsed` event.  You can then use `player.getManifest()` to get the manifest and remove any variants you don't want us to play.

```js
player.addEventListener('manifestparsed', () => {
  const manifest = player.getManifest();
  for (let i = 0; i < manifest.variants.length;) {
    if (shouldPlay(manifest.variants[i]))
      i++;
    else
      manifest.variants.splice(i, 1);
  }
});
```

**Comment by avelad** [comment]
I have found that using WebView2 (Edge Chromium) and using MediaCapabilities this problem does not exist. So I'm going to use your second suggestion for the moment, because this will be corrected in a future version and also, as you comment, it would be difficult to implement.

Thanks @TheModMaker !
