### ISSUE TITLE
Improve demo config styles (hover effects, spacing)

### ISSUE THREAD

**Issue by anshgo01yal** [google/shaka-player#3319]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by TheModMaker** [comment]
Can you describe more what you are asking?  I'm not sure what you mean.  If you want to change the configuration in the hosted demo, you can click the gear icon the the top-left of the site.  In your own site, you can change configuration with `player.configure(...)`.  See the docs [for the function](https://shaka-player-demo.appspot.com/docs/api/shaka.Player.html#configure) and [the object](https://shaka-player-demo.appspot.com/docs/api/shaka.extern.html#.PlayerConfiguration).

**Comment by anshgo01yal** [comment]
hello,
actually I am talking about demo-website. Its demo configration does'nt look decent. do I work upon it?

**Comment by michellezhuogg** [comment]
Hello @anshgo01yal, thank you for letting us know that the configs don't look good to you. If you are talking about the attributes of the [configurations](https://shaka-player-demo.appspot.com/docs/api/shaka.extern.html#.PlayerConfiguration), we need to keep them as they are.
If not, please give us an example of your solution to make them look better. Thank you!

**Comment by anshgo01yal** [comment]
hello @michellezhuogg, 
![con1](https://user-images.githubusercontent.com/58463645/114449559-7f982380-9bf2-11eb-96bb-390117d5ef23.PNG)
I can make it better may I try.

**Comment by ismena** [comment]
@anshgo01yal Please describe what do you find confusing about the current configuration and your proposed solution. Include screenshots for visual changes.

**Comment by anshgo01yal** [comment]
hello @ismena, I want to include some hover effects and add some padding in configuration to make it little more spacy.

**Comment by ismena** [comment]
I'm fine with that, you can proceed with a PR.
Make sure to verify your work on all major browsers and OSs.

**Comment by anshgo01yal** [comment]
@ismena can you please assign me to do this task

**Comment by ismena** [comment]
Done
