### ISSUE TITLE
Stereo tracks with captureSteam

### ISSUE THREAD

**Issue by toschlog** [google/shaka-player#3320]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

Yes

**What version of Shaka Player are you using?**

3.0.10

**Can you reproduce the issue with the latest code from `master`?**

Have not tried.

**Are you using the demo app or your own custom app?**

Custom app.

**If custom app, can you reproduce the issue using our demo app?**

Have not tried.

**What browser and OS are you using?**

Chrome, Chromium in Electron

**What did you do?**

I am using mediaElement.captureStream() on the video element specified in the "new shaka.Player()" call while playing a video with stereo sound.

**What did you expect to happen?**

I expected the captured stream to have one video and two audio tracks.

**What actually happened?**

The captured stream has one video and one audio track (which is a combination of the left & right audio).

Is it possible to get both the left and right audio tracks with captureStream()?

Thanks.

**Comment by TheModMaker** [comment]
My guess is the browser is exposing the input streams, which will be combined stereo.  Since the input files are stereo, there is no way to get the original left and right tracks.  You may be able to use the Web Audio APIs and the [ChannelSplitterNode](https://developer.mozilla.org/en-US/docs/Web/API/ChannelSplitterNode) to split the stereo data into mono tracks.

**Comment by toschlog** [comment]
I was mistaken about expecting two tracks.  Instead I would expect one track with two channels.  However, when I look at the dictionary returned by MediaStreamTrack.getSettings() there's no channelCount field so I just don't know if it's stereo or not.

At any rate, this probably isn't a Shaka Player issue.
