### ISSUE TITLE
cannot load browser "chrome"

### ISSUE THREAD

**Issue by anshgo01yal** [google/shaka-player#3324]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

**What version of Shaka Player are you using?**

**Please ask your question**
![errors2](https://user-images.githubusercontent.com/58463645/114425649-e9a2cf80-9bd6-11eb-9cfd-36a8ad1aa0cc.PNG)

hello everyone,
can anyone know when i run ./build/test.py --browsers chrome in vscode it show the error
[INFO] Generating Closure dependencies...
[INFO] Compiling the library (ui, release)...
[WARNING] No changes detected, skipping. Use --force to override.
[WARNING] No changes detected, skipping. Use --force to override.
[WARNING] No changes detected, skipping. Use --force to override.
[WARNING] No changes detected, skipping. Use --force to override.
[INFO] Running test (1 / 1, 0 failed so far)...
(node:10840) Warning: Accessing non-existent property 'VERSION' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created) 
12 04 2021 21:28:08.388:ERROR [launcher]: Cannot load browser "chrome": 
it is not registered! Perhaps you are missing some plugin?
12 04 2021 21:28:08.417:ERROR [karma-server]: Error: Found 1 load error
    at Server.<anonymous> (C:\Users\Ansh Goyal\shaka-player\node_modules\karma\lib\server.js:239:26)
    at Object.onceWrapper (events.js:420:28)
    at Server.emit (events.js:326:22)
    at emitListeningNT (net.js:1350:10)
    at processTicksAndRejections (internal/process/task_queues.js:79:21)[INFO] Run complete
[INFO] Result (exit code): 1

does any body know the cause and solution

**Comment by TheModMaker** [comment]
Try `Chrome` (capitalized).  Also try `--browsers help` to see a list of valid browsers.

**Comment by anshgo01yal** [comment]
@TheModMaker thanks for helping. I did the same and it works. but now I am getting bunch of errors with the execution of time of almost 35 mins
![errors3](https://user-images.githubusercontent.com/58463645/114433433-7487c800-9bdf-11eb-86b4-8c6bacc17f10.PNG)

**Comment by surajkumar-sk** [comment]
@anshgo01yal I cloned the latest version of shaka-player and ran `python ./build/test.py --browsers Chrome` on default cmd of Windows 8.1 chrome version 89.0.4389.114 and all the tests ran successfully within 7 minutes 10 seconds. I guess your issue is similar to #3215. I am not sure but it doesn't hurt to try. the solution that worked was staying on cmd rather than using other applications while all tests are running. I did try to google why karma fails to run a test when cmd is not in focus/selected, but found nothing. please try it, if it works someone from the team might clarify why that happens.

**Comment by anshgo01yal** [comment]
@surajkumar-sk  i tried all the stuff u said i run it in cmd and tried everything written on #3215 but still results are same.
my first error look like Error: Timeout - Async function did not complete within 120000ms (set by jasmine.DEFAULT_TIMEOUT_INTERVAL)
            at <Jasmine>

**Comment by surajkumar-sk** [comment]
@anshgo01yal is the error message same for all your tests. can you repost the screenshot at the point where the Failed starts?

**Comment by anshgo01yal** [comment]
![success](https://user-images.githubusercontent.com/58463645/114447409-026baf00-9bf0-11eb-918f-2bf5ce967fc5.PNG)

i closed each and everything of my pc. and run it again in cmd. this i actually got success but it skipped around 40 files and initially chrome starts with local host and at the end it closes automatically

**Comment by surajkumar-sk** [comment]
@anshgo01yal it's the same for me. staying on cmd while the tests are running does work. I just don't know why. tried googling but nothing, I don't think it's even a thing like karma works only when you stay on cmd. well, it's windows, weird things happen. 😂

**Comment by anshgo01yal** [comment]
@surajkumar-sk are u facing the same issue of skipping around 40 files with no output????
plz look  at the image I send recently.

**Comment by TheModMaker** [comment]
That is expected, we don't run all the tests on every browser.  Some browsers don't support every feature we want to test.  We also don't run certain tests by default that touch the network or use EME.  You can run more tests with `--external --drm`, but they will take a bit longer.

**Comment by surajkumar-sk** [comment]
@anshgo01yal yes even I am facing the issue of skipping 40 tests. I don't think it's a problem, it can be ignored. You can start coding with shaka-player.
