### ISSUE TITLE
Negative Timeline Duration ( 8.57.53 / -14.-8 ) and Live Timline pointer at starting position (WRONG)

### ISSUE THREAD

**Issue by hiren3897** [google/shaka-player#3333]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
^3.0.10

**Please ask your question**
After loading the dash manifest ( LIVE ) in shaka-player I have a bad timeline number in the player you can see in the images attached below and also the timeline pointer is at the starting position of the video player ( if it is life it should be at the end position in timeline and allow the user to trace back the video).  I am using the default configuration. 
I have no idea how I am getting this. can anyone help me in resolving this OR what configuration I should change to make it right

THANK YOU IN ADVANCE :)
TIMELINE IMAGE
![timeline](https://user-images.githubusercontent.com/59652404/114882352-29023380-9e04-11eb-8c39-72ff3754ca8b.png)
 
CONFIG IMAGE
![console](https://user-images.githubusercontent.com/59652404/114883088-dffeaf00-9e04-11eb-8da1-446ff137dbfa.png)
2ae7a5c.png)

**Comment by ismena** [comment]
Hi @hiren3897 
This is expected behavior for native browser controls at the moment. (At least when the player was launched) browsers didn't handle live timeline well. It might've changed since then, and we have [an action item](https://github.com/google/shaka-player/issues/3153) to investigate the current state, but the team haven't had resources to do that yet.

For a smooth UI experience on live streams, consider using our ui build.

**Comment by hiren3897** [comment]
Hello @ismena 
Thank You for your reply. :)
So is it possible to achieve ( Resolve ) it using shaka UI ( For a smooth UI experience on live streams ) and
Does the action item link provided by you can resolve this :/ ?

**Comment by joeyparrish** [comment]
The Shaka UI handles live stream timecodes and seeking appropriately for live streams, but the native controls in the browser do not.

Issue #3153 is to check to see if a new browser API resolves this.  It is meant to, but I just tried it, and it does not appear to work right on seeking.  We'll work with the Chrome team and the spec authors to try to fix this in the browser.  In the meantime, you can use our UI instead.

**Comment by hiren3897** [comment]
Thank you @joeyparrish for your reply :)

Do we have any sample code for handling the live stream timecodes and seeking appropriately live streams? If NOT can you paste it here as a sample that can help me to resolve this. It would be a great help :)

Thank you in advance. :)

**Comment by joeyparrish** [comment]
We have a full tutorial on using our UI in your application: https://shaka-player-demo.appspot.com/docs/api/tutorial-ui.html

That UI will appropriately handle everything.

The API-based way to seek is the same either way, using the media element: `video.currentTime = ...;`

Does this answer your question?

**Comment by hiren3897** [comment]
Yes, Thank you so much :)

**Comment by hiren3897** [comment]
Once Again Thank you so much @ismena @joeyparrish
My problem is resolve and I have a good UI :)
