### ISSUE TITLE
Variants that can be played are being removed when useMediaCapabilties=true 

### ISSUE THREAD

**Issue by caridley** [google/shaka-player#3334]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes 

**What version of Shaka Player are you using?**
master branch commit 4c975621a0110a7e6d21be2b8e2cebeb80e1cb1c

**Can you reproduce the issue with our latest release version?**
no problem does not occur with 2.5.20 or 3.0.10

**Can you reproduce the issue with the latest code from `master`?**
yes

**Are you using the demo app or your own custom app?**
custom app

**If custom app, can you reproduce the issue using our demo app?**
no - not sure how to run demo app with master branch code

**What browser and OS are you using?**
problem was observed on chrome with a mac and on a 2017 Tizen TV

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**
https://dluxvod.spectrum.com/DASH_DRM/XPMV0001609509701001/out.ism/manifest.mpd
https://pi-lite.spectrum.net/licenseServer/widevine/v1/twc/license

Note that license request will fail, but the problem can be detected before the license request occurs. 

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
see player-config.json in the attached shakaMissingVariants7LQN.zip file

**What did you do?**
Play the asset with useMediaCapabilties=true in player config

**What did you expect to happen?**
All 5 variants can be used

**What actually happened?**
Only the 2 lowest bitrate variants can be used

With shaka source code and the debugger I determined that the other variants were being removed by this function shaka.util.StreamUtils.filterManifestByDrm()

When useMediaCapabilties=false the problem does not occure.

config, manifest and log can be found in that attached file shakaMissingVariants7LQN.zip

**Comment by caridley** [comment]
[shakaMissignVariants7LQN.zip](https://github.com/google/shaka-player/files/6320692/shakaMissignVariants7LQN.zip)

**Comment by michellezhuogg** [comment]
Hello @caridley , thank you for reporting that!
The link of the license server URI looks invalid with our [demo app](https://nightly-dot-shaka-player-demo.appspot.com/demo/#audiolang=es;textlang=es;uilang=en;asset=https://dluxvod.spectrum.com/DASH_DRM/XPMV0001609509701001/out.ism/manifest.mpd;license=https://pi-lite.spectrum.net/licenseServer/widevine/v1/twc/license;panel=CUSTOM%20CONTENT;build=uncompiled
). Would you please confirm that's available for testing? Thank you!

**Comment by caridley** [comment]
@michellezhuogg  I don't have an account that I can share with access to that stream at this time, but I think you will find that you can observe the problem without a valid license URL, by setting a break point in shaka.util.StreamUtils.filterManifestByDrm() where the variants are being removed prior to making any license request.

**Comment by michellezhuogg** [comment]
@caridley Thank you! I verified that, and will work on improving that.
