### ISSUE TITLE
Content Play, but there is an error LICENSE_RESPONSE_REJECTED ERROR 6008

### ISSUE THREAD

**Issue by bro14045** [google/shaka-player#3335]
**What version of Shaka Player are you using ?**
Shaka Demo Page

**What version of Shaka Packager are you using ?**
The latest version v2.4.3
https://github.com/google/shaka-packager/releases

**Are you using the demo app or your own custom app?**
Both

**What browser and OS are you using?**
Chrome 89 and Firefox 87 on Windows OS

**What are the manifest and license server URIs?**
Manifest :
https://aptaplay.net/vod/new/drm/vid_4/stream.mpd

DRM Server :
https://widevine-dash.ezdrm.com/proxy?pX=580C85&token=deb80ed9c366f7b999d930fb3247e26e7db8aab778ff606424b6a30a7b82acb083085e5618d4e6bf0dfbad63ad73e2a56a14d3dff8aa89fcb15df56fdeb749acIEl8iEDTkHq2dOuVf3bixwxwlvU%2FHzfkNKJu5F0YL9bflIALcoOZRUcLfXC3BGXl

**What actually happened?**
The content played, but specific after 5 second content stopped. And i've  got an error License_Response_Rejected with code error 6008. I check on this link https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html#value:6008

But i don't know what the error mean and what should i do.

Thanks

**Comment by TheModMaker** [comment]
6008 means the browser rejected the response we got from the server.  Usually this means your license server returned a wrapped response (e.g. JSON data) that you need to unwrap before we can give it to the browser.  See our [license wrapping](https://shaka-player-demo.appspot.com/docs/api/tutorial-license-wrapping.html) tutorial for more info.

Your license server gives a 500 error, so I can't see why the response was rejected.
