### ISSUE TITLE
Widevine Drm content with resolution 720p not playing properly

### ISSUE THREAD

**Issue by krackjack234** [google/shaka-player#3336]
**What version of Shaka Player are you using?**

https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;videoRobustness=HW_SECURE_DECODE;uilang=en-US;asset=https://jiostreamingdash.akamaized.net/content/entry/wvdata/41/61/9921a6509d3c11eb9d701d0d3ea6acd1_voot_androidtv_standard.mpd;license=xxx;panel=CUSTOM%20CONTENT;build=uncompiled

**Please ask your question**
We are trying to play the below drm content

https://jiostreamingdash.akamaized.net/content/entry/wvdata/41/61/9921a6509d3c11eb9d701d0d3ea6acd1_voot_androidtv_standard.mpd

Though the content is playing fine at lower bitrates, only audio playback happens when we switch to 720p

We tried this on chrome browser on Android which has L1 Widevine support

We want to know what is going wrong here which is causing video playback to fail but audio to continue

If we see the manifest, all the bitrates except 720p is having a different KID.
We can share the drm license separately in private email if that helps
We tried different different video robustness level but still see the same issue

Please let us know the root cause of the problem.

**Comment by TheModMaker** [comment]
Without the license server URL, this will be difficult to debug.  You can send it privately to <shaka-player-issues@google.com>.

When this happens, does the video play normally (just with no video)?  Are you using an external display, cast, etc?  Can you check the JavaScript console for logs?  If you are using the demo app, what is the output of `shakaDemoMain.player_.getDrmEngine().keyStatusByKeyId_`?
