### ISSUE TITLE
Gap jumping improvements

### ISSUE THREAD

**Issue by caridley** [google/shaka-player#3338]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**Is your feature request related to a problem? Please describe.**
Frequent stalls when there DAI related gaps in the timelines in our streams.

In our testing we have found the following issues that are not handled optimally by the gap jump controller.

1) At period transitions we sometimes see an offset in the audio /video gaps such there are actually two back to back gaps in the total buffer like this:

video: {0.000-1.000},{1.010-10.000}
audio: {0.000-1.020},{1.030-10.000}
total: {0.000-1.000},{1.010-1.020},{1.030-10.00}

In this case we need to jump both gaps

2) Scheduling of gap checks is done in a 200 ms polling cycle which is wasteful and not accurate.

With a polling approach we have to add a 200 ms safety margin to the gapDetectionThreshold to deal with uncertainty in timing of the gap check, causing us to skip more content than necessary.

Checking for gaps every 200 ms is wasteful, during normal playback the next gap jump check can be scheduled at gapDetectionThreshold prior to the end of current contiguous buffer interval, greatly reducing the number of gap jump checks. 

3) We find that a larger gapDetectionThreshold is needed to handle gaps at transitions between unencrypted and encrypted periods. It would be helpful if the configuration supported a separate gapDetectionThrshold of gap jumps into encrypted periods.

**Describe alternatives you've considered**
We have implemented this approach to gap jumping at the application level and it is working well, but we would prefer to see if done within Shaka player.

**Additional context**
We would submit a PR but we do not yet have a contributors agreement. We can certainly review and test someone else's implementation.

**Comment by joeyparrish** [comment]
> We have implemented this approach to gap jumping at the application level and it is working well, but we would prefer to see if done within Shaka player.

Can you be more specific about what you have implemented?  Are you referring to this?

> during normal playback the next gap jump check can be scheduled at gapDetectionThreshold prior to the end of current contiguous buffer interval, greatly reducing the number of gap jump checks.

> We would submit a PR but we do not yet have a contributors agreement. We can certainly review and test someone else's implementation.

Please let us know if you decide to sign the agreement and contribute to Shaka Player.  Your contributions would be very much appreciated.
