### ISSUE TITLE
Add support for preprocessing dash manifests

### ISSUE THREAD

**Issue by caridley** [google/shaka-player#3339]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Is your feature request related to a problem? Please describe.**
On several occasions we have had to perform pre-processing on DASH manifest, to correct anomalies in the manifest.

Remove empty audio representations
Remove TTML adaptation sets that were causing problems
Change maxSegmentDuration

Currently we do this in a network response filter. This is very inefficient; requiring the following transformation ArrayBuffer -> String -> XmlDocument -> manipulate -> String -> ArrayBuffer, which consumes a lot of CPU and memory resources.

**Describe the solution you'd like**
It would be preferable to intercept the manifest immediately after it has been converted into an XmlDocument usign a new configuration parameter to provide the preprocessing function.

manifest.dash.preprocess(manifestXml: XmlDocument)

**Describe alternatives you've considered**
This can be done at the application level by monkey patching Shaka like this

```
// Monkey patch DashParser to allow manipulation of the manifest as an XMLDocument before it is
// processed by shaka
const originalProcessManifest = getShaka().dash.DashParser.prototype.processManifest_;
const spectrumProcessManifest = async function (this: any, mpd: any, finalManifestUri: any) {
  logger.error('intercepted parser');
  return originalProcessManifest.bind(this)(mpd, finalManifestUri);
};
getShaka().dash.DashParser.prototype.processManifest_ = spectrumProcessManifest;

```
**Additional context**
We think it would be better to have a generic manifest preprocessing capability instead of an ever increasing number of flags to address specific situations (e.g. ignoreEmptyAdaptationSet, ignoreSuggestedPresentationDelay etc..)

**Comment by caridley** [comment]
The application level monkey patching approach does not work with the non-debug build of shaka player.

**Comment by joeyparrish** [comment]
@ismena, what do you think of a configurable callback to let apps manipulate the DASH XML as a tree of elements, rather than needing to manipulate it as text in a network response filter?

**Comment by caridley** [comment]
@joeyparrish we will submit a PR for this enhancement if you think it will be accepted

**Comment by joeyparrish** [comment]
Sounds good to me.  Please add a callback to the config under `manifest.dash.`, and we'll take a look.  The default (in `lib/util/player_configuration.js`) can be a no-op, but please take a look at the comments around `progressCallback` in that file, as there is a subtle issue to work around:

```js
      // Need some operation in the callback or else closure may remove calls
      // to the function as it would be a no-op.  The operation can't just be a
      // log message, because those are stripped in the compiled build.
      progressCallback: (content, progress) => {
        return [content, progress];
      },
```

We use the default values in the config to do type-checking of incoming configs at runtime.  So we have to keep the compiler from changing the number of arguments to the function.  To keep it from stripping unused args, return them to that they are "used".
