### ISSUE TITLE
dist directory is not found

### ISSUE THREAD

**Issue by bhushanudupa** [google/shaka-player#3343]
**I have cloned this repo and started testing index.html. But I found that there is not dist directory in the repo. Please help me out.**

**Comment by surajkumar-sk** [comment]
@bhushanudupa dist folder is created after you run `python build/all.py` command in your locl system .

**Comment by nbcl** [comment]
Hello @bhushanudupa!

That is right, after cloning the repository you will not have the complete `dist/` directory.

To build it, you must compile the library, as follows:

```bash
python build/all.py
```

As the tutorial indicates, this will, among other things, output the compiled.js file you are most likely looking for to test your `index.html`.

> The output is: 
> dist/shaka-player.compiled.js (compiled bundle)
> (...)

Remember that, apart from Python, you will also need other prerequisities.

A complete list of the needed requisites, test instructions and other guides can be found in the [tutorial here](https://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)

**Comment by nbcl** [comment]
I think we answered at the same time @surajkumar-sk 😄

**Comment by surajkumar-sk** [comment]
@nbcl Your comments are always pretty detailed, and I always think, why did I even type 😅. 
@bhushanudupa close the issue if your question has been answered or feel free to ask any other queries you have.

**Comment by bhushanudupa** [comment]
Thank you @surajkumar-sk @nbcl
