### ISSUE TITLE
Add MSE support for FairPlay

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#3346]
I just discovered that Apple has updated all the FairPlay integration documentation including MSE example and how to use the api without prefixes (https://github.com/google/shaka-player/issues/2999).

Attached the relevant part in case someone does not have access:
[FairPlay Streaming in Safari.zip](https://github.com/google/shaka-player/files/6335018/FairPlay.Streaming.in.Safari.zip)

There are examples with key rotation, multi keys, etc.

**Comment by avelad** [comment]
Necessary changes:
- distinctiveIdentifier has to be `not-allowed` (I'll send a PR for it)
- persistentState has to be `not-allowed` (I'll send a PR for it)
- Persistent sessions are not allowed (I'll send a PR for it)
- For the renewal of keys the 'renew' event is listen, which right now is not in the ShakaPlayer code. @joeyparrish Do you have any idea how this should work?
- The contentType when MSE is not used should be 'application/vnd.apple.mpegurl' right now in the ShakaPlayer it gets 'video/mp4' by default (https://github.com/google/shaka-player/blob/master/lib/player.js#L2020) @joeyparrish Do you have any idea how this should work? Why is video/mp4 hardcoded?
- The integration of Media Capabilities should take all of this into account. @michellezhuogg

**Comment by valotvince** [comment]
I think Shaka should also provide a way for developers to be notified of which keySystem has been selected for playback, so that we could fetch/cache the appropriate certificate, and give it back as configuration (could have the same logic that the request/response filters).

**Comment by avelad** [comment]
I have seen Disney + uses HLS manifest with PlayReady, Widevine, and Fairplay using MSE. That would make us have greater efficiency in the CDN, since there would only be one copy (it would not be necessary to maintain DASH and HLS according to the device). @joeyparrish  What is your opinion about this? What priority is this for the ShakaPlayer?

**Comment by joeyparrish** [comment]
> I think Shaka should also provide a way for developers to be notified of which keySystem has been selected for playback

Do you mean in a specific event?  Or just that you should be able to get it in general?

Today you can get this info with `player.keySystem()` at a few different times early on.  You can do it after `load()` resolves or from the `loaded` event (roughly equivalent), or from the `streaming` event (which is earlier in the load process).

Would this suffice, or would you prefer a bespoke event?

> @joeyparrish What is your opinion about this? What priority is this for the ShakaPlayer?

This is really exciting!  I remember spending lots of fruitless hours trying to make MSE+FairPlay work, so it would be amazing to be able to enable it on desktop and MSE-enabled iOS devices.

I will defer to @ismena for priority, as she has taken over as the team lead.

**Comment by avelad** [comment]
I have been doing some testing and I have seen that MediaCapabitilies in Safari does not seem to support the encryption part, so with what is now in the repo it would not work. 

I think it is related to https://github.com/google/eme-encryption-scheme-polyfill/pull/18, @michellezhuogg , can you confirm it?

**Comment by valotvince** [comment]
@joeyparrish I think we should have a `certificateURL` key per advanced config DRM, Shaka would be responsible of fetching the certificate (if `serverCertificate` is NOT provided), allowing developers to catch the event through a request / response filter, and then do our own logic (cache the certificate in my own use case, to give it back as `serverCertificate` for the next load).

That's a thing we already do with the Widevine certificate even if it is not the same exact use case, since we have two license requests triggered by the CDM (the first one to fetch the certificate, the second to fetch the license).

**Comment by avelad** [comment]
@valotvince Maybe https://github.com/google/shaka-player/issues/1906 ?

**Comment by valotvince** [comment]
@avelad Totally !

**Comment by ismena** [comment]
PRs on this are very welcome if anybody's interested, otherwise we'll consider it for the team to work on in Q3/Q4.

**Comment by avelad** [comment]
Important thing I have seen:
- You have to make TS work in Safari because if mux.js is used the encrypted event is not triggered by the browser.
- As Safari works with the encrypted event, you have to change the DRM initialization order because you don't have sessionType until the encypted event is fired. (can be initialized as CENC when it should be SINF / SKD)
- You have to change the drmInfo object to admit a keyURI so that it can be propagated to the drmEngine (FairPlay case)

**Comment by avelad** [comment]
@joeyparrish , you reported https://github.com/google/shaka-player/issues/2337, you say that SourceBuffer into sequence mode can be a solution to support formats without container, you know if this could fix the problem that TS is broken for safari? (using sequence mode for TS) https://github.com/google/shaka-player/blob/master/lib/polyfill/mediasource.js#L42

**Comment by joeyparrish** [comment]
Based on the comments, it seems that the issue with TS in Safari is what happens when you call "abort()" on a SourceBuffer.  I'm not sure I see how sequence mode would change the need to call abort() in some cases.  The Safari bug is still reproducible in Safari 14, and nobody from Apple responded in the 4.5 years that bug has been known.

Perhaps to enable direct TS in Safari (without waiting for Apple to fix bugs in WebKit), we could investigate more deeply what it would take to eliminate calls to abort().  I haven't touched that part of the code in a long time, so I don't recall the details.

**Comment by efysis1** [comment]
So now we will be able to play widevine on Chrome iOS with HLS? 

A bit confusing for me Is HLS+iOS safari + FairPlay. As shaka docs Matrix say "native" i think no, but on bitmovin/prestoplay ive Seen support in Matrix. Is It just their player?

**Comment by joeyparrish** [comment]
> So now we Can play drm content in iOS browser?

We can already play DRM content in iOS browsers, but only through "native" HLS, using `video.src = hlsPlaylistUrl`, as opposed to MediaSource playback using Shaka's pure-JavaScript HLS implementation.

What we're discussing here is how to support our own HLS implementation through MediaSource, while still using FairPlay.  FairPlay is only available in Safari, and MediaSource is not generally available on iOS, except some versions on iPad.  So this would apply only to iPads and macOS.  Hopefully Apple will offer MediaSource on all iOS devices some day.

> A bit confusing for me Is HLS+iOS safari + FairPlay. As shaka docs Matrix say "native" i think no, but on bitmovin/prestoplay ive Seen support in Matrix. Is It just their player?

"Native" there refers to "native HLS", or Apple's built-in HLS implementation in Safari.  Shaka can use that to get FairPlay support.  There is work to be done (and documentation to be written by Apple) to allow us to fully support FairPlay with MediaSource playbacks.  We would prefer to use MediaSource everywhere we can.
