### ISSUE TITLE
How to contol player without default control ui?

### ISSUE THREAD

**Issue by Realitian** [google/shaka-player#3360]
Hi,

I want to control the playing of player without using the default control ui.
for example, I want to call Stop/Play/Pause/Seek in my customized javascript function(called from another user interaction).
How I can do that?

Thanks in advance!

**Comment by nbcl** [comment]
Hello @Realitian!

You can directly call the API of your controls on one of your customized JavaScript functions!

It will depend on your own definitions, but here is an example, assuming there is an `index.html` and `myapp.js` like the ones described in the [tutorial](https://shaka-player-demo.appspot.com/docs/api/tutorial-basic-usage.html).

```js
function realitianPlayFunction() {
    const video = document.getElementById('video');
    const ui = video['ui'];
    const controls = ui.getControls();
    controls.playPausePresentation();
}
```

**Comment by TheModMaker** [comment]
@nbcl, `playPausePresentation` isn't exported, so it won't work in compiled mode.  The preferred way of interacting with the video is through the normal HTML methods.  e.g. `video.play()` or `video.currentTime = 200`.

**Comment by nbcl** [comment]
@TheModMaker thanks for the correction! 

I was using the uncompiled version locally and jumped to a solution focusing only on custom functions and completely forgot about the regular video methods. 😅

I updated my original comment with a correct example and also added a reference to a list of other properties and methods to serve as additional information.

**Comment by Realitian** [comment]
@nbcl, @TheModMaker 
I can play by `video.play()`, but I cannot stop play. How can stop it?

**Comment by nbcl** [comment]
On my local installation, I was able to pause the video using `video.pause()`, with the following custom function.

```js
function pauseVideo() {
   // Find video element
   const video = document.getElementById('video');
   // Pause the video via the HTML pause method
   video.pause();
}
```

Would you mind sharing your implementation to understand where the problem may reside?

Please remember to remove any personal or confidential information if you are willing to share your code here!

**Comment by joeyparrish** [comment]
> @nbcl, @TheModMaker
> I can play by `video.play()`, but I cannot stop play. How can stop it?
> You will say to use `video.pause()`, but actually it don't work on my side.

In what way does it not work?  What happens when you call `video.pause()`?

**Comment by Realitian** [comment]
> > @nbcl, @TheModMaker
> > I can play by `video.play()`, but I cannot stop play. How can stop it?
> > You will say to use `video.pause()`, but actually it don't work on my side.
> 
> In what way does it not work? What happens when you call `video.pause()`?

I will try to upload the code.

**Comment by Realitian** [comment]
> > @nbcl, @TheModMaker
> > I can play by `video.play()`, but I cannot stop play. How can stop it?
> > You will say to use `video.pause()`, but actually it don't work on my side.
> 
> In what way does it not work? What happens when you call `video.pause()`?

@joeyparrish 
Here ( [code:](https://github.com/Realitian/ShakaPlayer), [live:](https://realitian.github.io/ShakaPlayer) ), I have the issue when play the dash stream. It does not work the play/pause/seek all for the first stream url.
Can you check what is the problem?

Thank you in advance.

**Comment by michellezhuogg** [comment]
Hello @Realitian , I played with your [live](https://realitian.github.io/ShakaPlayer) demo and it worked fine in Chrome.
1. In your browser console, do you happen to see "CORS" related error?
2. If not, did you see anything suspicious from the log?

**Comment by Realitian** [comment]
> Hello @Realitian , I played with your [live](https://realitian.github.io/ShakaPlayer) demo and it worked fine in Chrome.
> 
> 1. In your browser console, do you happen to see "CORS" related error?
> 2. If not, did you see anything suspicious from the log?

Yes, I see the "CORS" errors.

**Comment by joeyparrish** [comment]
You can read more about CORS here: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

But in short, the web server must indicate to the browser which "origins" (domains) are allowed to access that resource.  It does this through HTTP response headers.  If the browser is making the request from an origin other than one on the allow list, it will throw away the response and return an error in JavaScript.

This is a fundamental security feature of browsers, and not in our control.  If you can add the necessary response headers, you can solve the CORS errors.  If not, you will need to host the application and content in the same origin so that CORS restrictions do not apply.

Does this help?

**Comment by Realitian** [comment]
@joeyparrish 
It sounds helpful.
But I hosted that on github.com now. so should I fix the client source code? or should I config media server or github page configuration?

**Comment by joeyparrish** [comment]
If your application is hosted at realitian.github.io, and your media content is hosted elsewhere, the server that hosts your media must include CORS headers to authorize realitian.github.io for cross-origin access to it.

Does this help?

**Comment by Realitian** [comment]
@joeyparrish , Thank you so much your guidance.
Btw, If I host my application on my custom server (e.g. aws ec2 or heroku), can I config CORS header without handle the media server?

**Comment by TheModMaker** [comment]
If the app is on the same server as the media, you don't need extra headers.  But if your app and content are on different domains, then you must configure your media server to send the correct headers.  This is a requirement of the browser that cannot be changed in production.

**Comment by Realitian** [comment]
Thank you, all.
