### ISSUE TITLE
Getting type of mpd

### ISSUE THREAD

**Issue by xMalikeNx** [google/shaka-player#3362]
Hi,

How can i get current manifest type(static/dynamic) using shaka player api?
![image](https://user-images.githubusercontent.com/68480258/115703626-02e41280-a373-11eb-8a10-2729b5a04ec5.png)

**Comment by xMalikeNx** [comment]
I got it with responseFilter =)

**Comment by joeyparrish** [comment]
We also have `player.isLive()`, for what that's worth.  Live streams are dynamic in DASH.
