### ISSUE TITLE
HLS performance improvements

### ISSUE THREAD

**Issue by ismena** [google/shaka-player#3363]
We can improve performance of our HLS implementation by 
- reducing startup latency (such as fetching HLS segments to extract timestamps)
- improving bandwidth usage (such as polling all HLS playlists vs just one)
- possibly identifying other areas of inefficient performance

**Comment by michellezhuogg** [comment]
https://github.com/google/shaka-player/issues/1936

**Comment by joeyparrish** [comment]
> We can improve performance of our HLS implementation by
> 
> * reducing startup latency (such as fetching HLS segments to extract timestamps)

This will be solved when #2337 is solved.

> * improving bandwidth usage (such as polling all HLS playlists vs just one)

This is tracked in #1936.

> * possibly identifying other areas of inefficient performance

I'm going to close this issue as redundant.
