### ISSUE TITLE
Shaka custom seek bar implementation

### ISSUE THREAD

**Issue by bmaniar** [google/shaka-player#3374]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.11

**Please ask your question**
Hi,
Could you let us know when can we expect the custom seek bar implementation that is currently on master to be merged to release?

Reference: https://github.com/google/shaka-player/pull/2966

**Comment by joeyparrish** [comment]
In our next feature release, v3.1.0, which is due out today or tomorrow.  Thanks!
