### ISSUE TITLE
Dynamic manifest transition to static is not supported if the DVR window is sliding

### ISSUE THREAD

**Issue by sky-hugolima** [google/shaka-player#3376]
Hey !

It seems that currently Shaka doesn't support a scenario where it's playing a sliding window dynamic MPD with a timeShiftBufferDepth of 2 hours,  and the stream ends after 4 hours by transitioning to static (e.g. the seek range should be  [2hours..4hours]), because  the presentation timeline uses the `mediaPresentationDuration` as the end of the seek range when the manifest is static.

I've made the following change to `presentation_timeline`  that seem to work:
```
   getSegmentAvailabilityEnd() {
     if (!this.isLive() && !this.isInProgress()) {
-      return this.duration_;
+      // It's a static manifest (can also be a dynamic->static conversion)
+      return this.maxSegmentEndTime_ || this.duration_;
     }
+    // Can be either live or "in-progress recording" (live with known duration)
     return Math.min(this.getLiveEdge_(), this.duration_);
   }
```
Is this something that makes sense from your perspective ?

Links to dynamic and static snapshots of the same MPD:
Static MPD: https://drive.google.com/file/d/1kKhmPpdUxZBlYTM3Ra1L4a4VwlN-uJva/view?usp=sharing
Dynamic MPD: https://drive.google.com/file/d/1kMuJT67herziAZuHf1TVnbDL2CvQX4nS/view?usp=sharing

**Comment by OrenMe** [comment]
We at Kaltura are facing same issue now and seems like this is the correct fix.

According to spec
https://dashif.org/docs/DASH-IF-IOP-v4.3.pdf
section :  3.10.2.2.2. MPD Information and  4.6.4. Transition Phase between Live and On-Demand the correct order of timing info should be first mediaPresentationDuration tag and only after that the period duration.

**Comment by OrenMe** [comment]
thanks for the quick turn around and thanks @sky-hugolima for opening this :-)
