### ISSUE TITLE
Sintel 4k (multicodec) is not working in Xbox

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#3380]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes

**What version of Shaka Player are you using?** 3.1.0

**Can you reproduce the issue with our latest release version?** Yes

**Can you reproduce the issue with the latest code from `master`?** Yes

**Are you using the demo app or your own custom app?** Both

**If custom app, can you reproduce the issue using our demo app?** yes

**What browser and OS are you using?**
**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Xbox Series S 
Firmware: 10.0.19041.7339
Browser: Edge 18.19041

**What are the manifest and license server URIs?**

https://storage.googleapis.com/shaka-demo-assets/sintel/dash.mpd

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

N/A

**What did you do?**

Load the previous URL

**What did you expect to happen?**
The stream works without problem.

**What actually happened?**

Sometimes (I think it is due to the ABR and the resolution that is selected), the following error is thrown, and the stream does not work:
{
severity: 2,
category: 3,
code: 3016,
data: [3, 3c00d36b4, null]
}

**Comment by joeyparrish** [comment]
I didn't get any search results for that MS error code ("3c00d36b4") except this issue.  :-(

I haven't been able to reproduce on our Xbox One through the automated playback test we have.  I ran the test 20 times in a row, and it passed every time.

However, that test disables ABR.  I'll edit the test and try again with ABR turned back on.

**Comment by joeyparrish** [comment]
Actually, I now realize that `3c00d36b4` is more than 32 bits long.  Are you sure that's the right error code?

**Comment by joeyparrish** [comment]
Ah, found it!  The first digit was not part of the error code: https://support.xbox.com/en-US/help/errors/xbox-360/error-code-c00d36b4

> This error might mean that the video codec or the audio codec is not supported, so the content might not be supported. However, this message and error code might also mean that a stream in the video file is corrupted.

**Comment by avelad** [comment]
The error is reproduced with the ABR active and when a quality higher than 1080p is chosen

**Comment by joeyparrish** [comment]
> However, that test disables ABR. I'll edit the test and try again with ABR turned back on.

I'm having issues getting our Xbox One to work right now, so I haven't been able to try this yet.

**Comment by joeyparrish** [comment]
Watching the screen via HDMI capture and SSH to our lab, it appears that soon after playback starts, the test app crashes.  I expect that this corresponds with the first switch to high res.  😞  Eventually, a popup on the Xbox mentions error code `80073cf6`.

According to the players logs, it buffered to time 20 and played to time 4.24.  It selected mp4+h264 for video and webm+opus for audio.  webm+vp9 was rejected as unsupported.

If I play sintel-mp4-only instead of sintel, I get buffering to time 40 and playback to time 24.25 before it appears to crash.

Everything plays fine if I keep ABR off and play low res variants.

I may have hit the limit of what I can debug on this device.

@avelad, I wonder if there could be something wrong with the encoding of the high res tracks.  Or if they use a profile or level not supported by the device.  Do you have other high-res content which works on Xbox?  We could perhaps compare the streams to look for differences.

**Comment by avelad** [comment]
I have tried H265 streams in 4K and they work without problem, I have also tried other H264 streams in 4K and they always fail. Could it be a limitation of the Xbox? (H264 content higher than 1080 does not work)

**Comment by avelad** [comment]
@joeyparrish Could H264 support above 1080 be removed on xbox?

**Comment by joeyparrish** [comment]
Definitely.  We could patch MediaSource.isTypeSupported to reject that combination.  We have similar things in a polyfill for MSE: https://github.com/google/shaka-player/blob/65a2cfdd/lib/polyfill/mediasource.js#L134

The MIME types we send through that interface have extended info in them, including resolution.  We could parse the parameters and filter out UHD H264 streams there.

Or perhaps it would be best done further up the stack, such as in `shaka.util.StreamUtils.filterManifestByMediaSource()` and `shaka.util.StreamUtils.filterManifestByMediaCapabilities()`, with a check for `shaka.util.Platform.isXboxOne()`.  A polyfill is a nice way to hide platform-specific hacks, but an MSE polyfill means re-parsing the extended MIME type for resolution.  Doing it in `StreamUtils` means direct access to details about the stream.

Would you like to try it out and send a PR?
