### ISSUE TITLE
6001 error on Tizen 3 and WebOS3.3 when installing polyfills, works when not installing

### ISSUE THREAD

**Issue by OrenMe** [google/shaka-player#3382]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

**What version of Shaka Player are you using?**
latest 3.0.11

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `master`?**
yes

**Are you using the demo app or your own custom app?**
custom

**If custom app, can you reproduce the issue using our demo app?**
N?A

**What browser and OS are you using?**
Samsung TV (Mozilla/5.0 (SMART-TV; LINUX; Tizen 3.0) AppleWebKit/538.1 (KHTML, like Gecko) Version/3.0 TV Safari/538.1)

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Model 32LH604V-ZB
WebOS TV Version 3.3.4-4416(dreadlocks-dharug)

**What are the manifest and license server URIs?**

Will be sent to email with same issue title

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**
load media with Playready DRM on TV

**What did you expect to happen?**
playback starts correctly

**What actually happened?**
getting 6001 error
![Screenshot from 2021-04-29 18-21-26](https://user-images.githubusercontent.com/5461862/116577848-85dc0e80-a919-11eb-81df-fad14462efb8.png)

Additional info:
shaka support page shows both playready and widevine are supported.
If we don't install polyfills then playback works correctly(?!) so I guess it has something to do with the EME patching.

**Comment by OrenMe** [comment]
@joeyparrish any chance that this is a known issue? I don't have access to devices but I suspect that the polyfill is patching the EME incorrectly.

**Comment by joeyparrish** [comment]
I'm testing on a Tizen 3 device in our lab, with our automated integration test called `gets a license and can play encrypted segments`.

 - master branch: pass
 - v3.1.0: pass
 - v3.0.11: pass

So I'm unable to reproduce the issue, and it isn't a known issue for us.  I don't know why you're getting different results.

Can you try commenting out one particular polyfill's `install()` method, in `lib/polyfill/encryption_scheme.js`?  If that works for you, we can transfer this issue to the [google/eme-encryption-scheme-polyfill](https://github.com/google/eme-encryption-scheme-polyfill) repo and dig into the specifics of that polyfill to find a real solution.

**Comment by OrenMe** [comment]
@shaka-bot reopen
I actually haven't gotten yet to re-test cause I need to get access to the tv model again

**Comment by TheModMaker** [comment]
@OrenMe have you had a chance to test?  Could you also try with the latest version of the EME polyfill?
