### ISSUE TITLE
ABR not respect user preferrence resolution

### ISSUE THREAD

**Issue by kocoten1992** [google/shaka-player#3385]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v3.1.0

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Not sure, I'm using demo app to reproduce this

**Are you using the demo app or your own custom app?**
demo app

**What browser and OS are you using?**
Google Chrome

**What did you do?**
1. Go to https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://storage.googleapis.com/shaka-demo-assets/sintel-widevine/dash.mpd;adTagUri=https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpostpod&cmsid=496&vid=short_onecue&correlator=;panel=HOME;build=uncompiled
2. select highest resolution, watch for about 10s
3. open network tab and throttle bandwidth to slow 3G

**What did you expect to happen?**
Video keep playing at user chosen resolution regardless of lagging.

**What actually happened?**
ABR kick in and downgrade resolution (resolution on menu still display the same - but you can see clearly the real video quality is much downgrade).
ABR should not override user preferrence and select different resolution for user, previous version don't do this - maybe this is a regression ?.

**Comment by joeyparrish** [comment]
Sounds like a regression, and it looks to me like it was introduced in https://github.com/google/shaka-player/pull/2663 .  There should be a check there for the `enabled` state of the ABR manager before reacting to the network change event.
