### ISSUE TITLE
Microsoft DASH live stream errors

### ISSUE THREAD

**Issue by br0adcast** [google/shaka-player#339]
I'm trying to paly (shaka player v2.0.0-beta) live DASH stream from Microsoft - http://b028.wpc.azureedge.net/80B028/Samples/a38e6323-95e9-4f1f-9b38-75eba91704e4/5f2ce531-d508-49fb-8152-647eba422aec.ism/Manifest(format=mpd-time-csf), https://azure.microsoft.com/en-us/blog/live-247-reference-streams-available/ , and get following errors:
1. Assertion failed: Calculated $Time$ values must be close to integers!
2. Error: Shaka Error STREAMING.SEGMENT_DOES_NOT_EXIST

1.6.x version plays it without errors

**Comment by tdrews** [comment]
Thanks for the report. We'll take a look.

**Comment by hoimingw** [comment]
Hi @TheModMaker ,

I found the following code at your commit at [cc243fa](https://github.com/google/shaka-player/commit/cc243faac9ea66ffa7b9ab2ebacf1a4a7daeceb7 )

At mpd_utils.js,
+    goog.asserts.assert(Math.abs(time - Math.round(time)) < 0.2,
                          'Calculated $Time$ values must be close to integers!');

Why $Time$ must be close to integer? From DASH spec I couldn't find this constraint.

Thanks,
Hoi Ming

**Comment by TheModMaker** [comment]
`$Time$` refers to the current time in timescale units (for example `SegmentTimeline@t`).  So it must be an integer.  However, since we convert it from timescale units, to seconds, then back to timescale, there are rounding errors.  We have that check to verify that there are only rounding errors.
