### ISSUE TITLE
I can't play a DRM protected HLS contents without refreshing the page a second time

### ISSUE THREAD

**Issue by clotairemarmignon** [google/shaka-player#3390]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
YES

**What version of Shaka Player are you using?**
3.1.0

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `master`?**
yes

**Are you using the demo app or your own custom app?**
our custom app

**If custom app, can you reproduce the issue using our demo app?**
yes

**What browser and OS are you using?**
Mac OS BigSur Version 11.3 (20E232)

iOS 14.4.2

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**

We tried to play the video

**What did you expect to happen?**
the video to begin 

**What actually happened?**

It is working without any problem on Chrome (widevine). Our partners can stream the content on their side (on safari)  but we can't, on Macbook or iPhone...

I found a way to make it work on my MacBook Pro but it is not viable, I just found out that if I reload the page once or twice, I can play the video without any issue.

When it's not loading, there is not any error code, a single MP4 audio file can't be loaded and I think this is the reason why we can't stream the video.

**Comment by joeyparrish** [comment]
> What are the manifest and license server URIs?
> What configuration are you using? What is the output of player.getConfiguration()?

Without these answers, we won't be able to help diagnose your issue.  You can send the content to us privately if you wish.  The email address was in the issue template.
