### ISSUE TITLE
shaka player never triggers 'error' listener

### ISSUE THREAD

**Issue by RaghuMudem** [google/shaka-player#3394]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes

**What version of Shaka Player are you using?** v3.1.0

**Can you reproduce the issue with the latest code from `master`?** yes

**Are you using the demo app or your own custom app?** Demo app 

**What browser and OS are you using?** Chrome in Windows 10

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?** Not applicable

**What are the manifest and license server URIs?** DRM/MPD

**What did you do?**

I have gone through the documentation and found basic program to load player with video manifest url. And it is loading video fine. I need to implement error handing for player. So I am trying to understand, where the 'error' event listener will be firing. Following is the code for listening error. It is not triggering anymore for me.

```
 // Listen for error events.
  player.addEventListener('error', onErrorEvent);
```
Following are the Trails to get it invoked but not triggered: 

Trail 1: Not initialized video variable.
```
  const video = null;
  const player = new shaka.Player(video);
```
Trail 2: Loading an invalid manifest url.
```
try {
    await player.load('https://mydymmy.manifest.url');
  } catch (e) {
    onError(e);
  }
```

**What did you expect to happen?**
`onErrorEvent `method suppose to call when the player has an error. As explained in the trails, i expected the error callback will be triggered. 

**What actually happened?**

`onErrorEvent `function not at all calling with the trail given by me. Is something I need to know more how to/ when to use 'error' listener on player instance. Please guide me.

**Comment by surajkumar-sk** [comment]
@RaghuMudem 
This is the code I used for triggering error events and it is working fine. 
```
const manifestUri =
    'https://mydymmy.manifest.url';

async function initPlayer() {
  // Create a Player instance.
  const video = null;
  const player = new shaka.Player(video);

  // Listen for error events.
  player.addEventListener('error', onErrorEvent);

  // Try to load a manifest.
  // This is an asynchronous process.
  try {
    await player.load(manifestUri);
    // This runs if the asynchronous load is successful.
    console.log('The video has now been loaded!');
  } catch (e) {
    // onError is executed if the asynchronous load fails.
    onError(e);
  }
}

function onErrorEvent(event) {
  // Extract the shaka.util.Error object from the event.
  onError(event.detail);
}

function onError(error) {
  // Log the error.
  console.error('Error code', error.code, 'object', error);
}

document.addEventListener('DOMContentLoaded', initPlayer);
```
For keeping ` video = null ` error code 7002 is thrown in the console log.
For having wrong manifest error code 1002 is thrown in the console log.

Can you please share your code if possible so I could look into why it's not working?
Thank you.

**Comment by joeyparrish** [comment]
@surajkumar-sk, thanks for offering to help, but that's not necessary.

@RaghuMudem, I think I can explain the issue you're having.  There are two ways to receive errors from Shaka Player, for two different situations.

If an error occurs during playback, without being associated with a specific method call, then you will get an error event:

```js
player.addEventListener('error', (error) => {
  // handle error here
});
```

If an error occurs during a specific async method call, such as load(), then the error will come to you through a rejected Promise:

```js
async function foo() {
  try {
    await player.load('/foo.mpd');
    // success
  } catch (error) {
    // handle error here
  }
}
```

In non-ES6 JavaScript (without async/await syntax), this would look like:

```js
player.load('/foo.mpd').then(function() {
  // success
}).catch(function(error) {
  // handle error here
});
```

Does this help?

**Comment by RaghuMudem** [comment]
@surajkumar-sk @joeyparrish thankyou so much for the response.

So can I assume the followings are correct:

1. The type one error as mentioned by joeyparrish cannot be simulated for testing/learning. Those will be received at runtime for the real error from shaka player.
2. And we must need to catch the errors with try/catch for the async method calls.
3. In the 'error' event, event.detail is a error object. (event.detail==error)(???)

I can also confirm that, my both trails are handled by try/catch as mentioned in the 2nd way.

Please correct me, if my understanding is wrong and would be very useful if there any usecase to produce 'error' event with shaka player.

**Comment by joeyparrish** [comment]
> So can I assume the followings are correct:
> 
> 1. The type one error as mentioned by joeyparrish cannot be simulated for testing/learning. Those will be received at runtime for the real error from shaka player.

Do you mean the Promise-based errors?  Are you looking for a way to trigger them to test your error handlers?  If so, this can easily be done with certain invalid inputs.  For example:

```js
  await player.load('foo:bar');
```

This will throw a `shaka.util.Error` with code `1000` (AKA `UNSUPPORTED_SCHEME`).

> 2. And we must need to catch the errors with try/catch for the async method calls.

Correct.

> 3. In the 'error' event, event.detail is a error object. (event.detail==error)(???)

Correct.  The event's detail should always be an instance of `shaka.util.Error`.  In the past, we have sometimes had bugs where a different Error type is thrown and shows up in an error event, but if that happens, it always indicates a bug.  The event's detail field should **always** be an instance of `shaka.util.Error`.

> Please correct me, if my understanding is wrong and would be very useful if there any usecase to produce 'error' event with shaka player.

I'm not sure I understand what you mean by this.  Can you clarify?  Are you just looking for ways to test the error event handler?

If so, you can use a failing request filter to trigger an error event.  Once a manifest loads, the `load()` promise can be resolved, so you want to fail a request for a media segment specifically.

```js
player.getNetworkingEngine().registerRequestFilter((type, request) => {
  if (type == shaka.net.NetworkingEngine.RequestType.SEGMENT) {
    throw new Error('oops');
  }
});

// Now load a valid asset
await player.load('https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd');
```

This will get you an error event with error code `1006` (AKA `REQUEST_FILTER_ERROR`).

I hope I understood your goal correctly.  Does this help?

**Comment by RaghuMudem** [comment]
> > So can I assume the followings are correct:
> > 
> > 1. The type one error as mentioned by joeyparrish cannot be simulated for testing/learning. Those will be received at runtime for the real error from shaka player.
> 
> Do you mean the Promise-based errors? Are you looking for a way to trigger them to test your error handlers? If so, this can easily be done with certain invalid inputs. For example:
> 
> ```js
>   await player.load('foo:bar');
> ```
> 
> This will throw a `shaka.util.Error` with code `1000` (AKA `UNSUPPORTED_SCHEME`).
> 
> > 1. And we must need to catch the errors with try/catch for the async method calls.
> 
> Correct.
> 
> > 1. In the 'error' event, event.detail is a error object. (event.detail==error)(???)
> 
> Correct. The event's detail should always be an instance of `shaka.util.Error`. In the past, we have sometimes had bugs where a different Error type is thrown and shows up in an error event, but if that happens, it always indicates a bug. The event's detail field should **always** be an instance of `shaka.util.Error`.
> 
> > Please correct me, if my understanding is wrong and would be very useful if there any usecase to produce 'error' event with shaka player.
> 
> I'm not sure I understand what you mean by this. Can you clarify? Are you just looking for ways to test the error event handler?
> 
> If so, you can use a failing request filter to trigger an error event. Once a manifest loads, the `load()` promise can be resolved, so you want to fail a request for a media segment specifically.
> 
> ```js
> player.getNetworkingEngine().registerRequestFilter((type, request) => {
>   if (type == shaka.net.NetworkingEngine.RequestType.SEGMENT) {
>     throw new Error('oops');
>   }
> });
> 
> // Now load a valid asset
> await player.load('https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd');
> ```
> 
> This will get you an error event with error code `1006` (AKA `REQUEST_FILTER_ERROR`).
> 
> I hope I understood your goal correctly. Does this help?

Yes, I wanted to produce an error which can trigger the below code.

```
player.addEventListener('error', (error) => {
  // handle error here
});
```
And I tried your code suggesting and was expecting error listener will be getting called. But it is not get triggered. I can confirm, even video is also not playing. And no error/exception has been logged in console.

**Comment by TheModMaker** [comment]
What version are you using?  I'm able to get the error listener to fire in the hosted demo.  Can you post your full code, preferably an HTML page that is hosted somewhere?  This JSFiddle works fine: https://jsfiddle.net/8chksmg0/
