### ISSUE TITLE
Live DRM playback get stuck

### ISSUE THREAD

**Issue by yairans** [google/shaka-player#3395]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes

**What version of Shaka Player are you using?** Latest - demo page

**Can you reproduce the issue with our latest release version?** Yes

**Can you reproduce the issue with the latest code from `master`?**

**Are you using the demo app or your own custom app?** dmo app

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?** Chrome 90 on Mac

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?** NA

**What configuration are you using?  What is the output of `player.getConfiguration()`?** default of demo app

**What did you do?** Play

**What did you expect to happen?** Smooth playback

**What actually happened?** Playback get stuck some after some time 

log and har sent to shaka-player-issues@google.com

**Comment by joeyparrish** [comment]
> What are the manifest and license server URIs? NA
> log and har sent to shaka-player-issues@google.com

I disagree that the manifest and license server URIs are "not applicable".  Without this, we can't reproduce or diagnose your issue.  A log file and HAR file are not enough for us to diagnose the issue or work on a fix.

If you can't share URIs with us privately, then we can offer you suggestions to debug it yourself and send a PR.  But for that, we would also need more a detailed description than "playback stuck".
