### ISSUE TITLE
Playing DASH multiperiod streams with SSAI ads on chromecast results in buffering at each ad break

### ISSUE THREAD

**Issue by zuzzurro** [google/shaka-player#3397]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes, we are particularly interest in resolution of issue #1864 that seem related. We also hoped that #3166 would help but we tried setting gapDetectionThreshold to 1 with no improvements 

**What version of Shaka Player are you using?**
We are now using 3.0.10 since the performance is slightly better than using the default 2.5 version

**Can you reproduce the issue with our latest release version?**
We skipped trying 3.1 since...

**Can you reproduce the issue with the latest code from `master`?**
We can reproduce it using today's master

**Are you using the demo app or your own custom app?**
our own custom app (usign the google cast receiver framework)

**If custom app, can you reproduce the issue using our demo app?**
let's discuss this, being chromecast...

**What browser and OS are you using?**
The issue occurs using Chromecast 2, 3 and Ultra. Chromecast 1 is not supported in this project. We are using the Google receiver SDK.

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
The issue occurs using Chromecast 2, 3 and Ultra. Chromecast firmware version doesn't seem to make any difference

**What are the manifest and license server URIs?**
The URL has been sent via email

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

In this project midrolls are server side and client side tracking is not used, only server side. The issue impacts live linear DASH streams when played **on Chromecast only**.

```abr: {enabled: true, useNetworkInformation: true, defaultBandwidthEstimate: 1000000, switchInterval: 8, bandwidthUpgradeTarget: 0.85, …}
abrFactory: ƒ ()
drm: {retryParameters: {…}, servers: {…}, clearKeys: {…}, advanced: {…}, delayLicenseRequestUntilPlayed: false, …}
manifest: 
availabilityWindowOverride: NaN
dash: {clockSyncUri: "", ignoreDrmInfo: false, disableXlinkProcessing: false, xlinkFailGracefully: false, ignoreMinBufferTime: false, …}
defaultPresentationDelay: 16
disableAudio: false
disableText: false
disableThumbnails: false
disableVideo: false
hls: {ignoreTextStreamFailures: false, useFullSegmentsForStartTime: false}
retryParameters: {maxAttempts: 2, baseDelay: 1000, backoffFactor: 2, fuzzFactor: 0.5, timeout: 30000, …}
__proto__: Object
offline: {usePersistentLicense: true, trackSelectionCallback: ƒ, downloadSizeCallback: ƒ, progressCallback: ƒ}
playRangeEnd: Infinity
playRangeStart: 0
preferForcedSubs: false
preferredAudioChannelCount: 2
preferredAudioLanguage: ""
preferredTextLanguage: ""
preferredTextRole: ""
preferredVariantRole: ""
restrictions: {minWidth: 0, maxWidth: Infinity, minHeight: 0, maxHeight: Infinity, minPixels: 0, …}
streaming: always
StreamText: false
autoLowLatencyMode: false
bufferBehind: 30
bufferingGoal: 10
durationBackoff: 1
failureCallback: ƒ (c)
forceHTTPS: false
forceTransmuxTS: false
gapDetectionThreshold: 0.5
ignoreTextStreamFailures: false
inaccurateManifestTolerance: 2
jumpLargeGaps: true
lowLatencyMode: false
preferNativeHls: false
rebufferingGoal: 2
retryParameters: {maxAttempts: 2, baseDelay: 1000, backoffFactor: 2, fuzzFactor: 0.5, timeout: 30000, …}
safeSeekOffset: 5
smallGapLimit: 5
stallEnabled: true
stallSkip: 0
stallThreshold: 1
startAtSegmentBoundary: false
useNativeHlsOnSafari: true
__proto__:
```

**What did you do?**
Play the stream and wait for midroll ads (server side) to appear

**What did you expect to happen?**
We expect to play the ads with no buffering as it occurs on the web version of the site where we use 3.0.8 and where the video plays well. Keep in mind that the video stream has no issue, buffering only occurs during ads.

**What actually happened?**
Play the stream. Wait until server side midroll ads or slates appear, see that between ads chromecast starts buffering. Look at the console logs and note the messages about skipping gaps and buffering.
Note that 3.1 seem to actually perform worse than 3.0.10 as buffering can last much longer than a couple of seconds and sometimes streaming never recovers.
Here's the log of a session showing the issue captured using chrome://inspect:

[chromecast-test.d3-sinc.com-1620658002444.log](https://github.com/google/shaka-player/files/6453990/chromecast-test.d3-sinc.com-1620658002444.log)

**Comment by joeyparrish** [comment]
The first message I see in the log file that seems significant is `Jumping forward 0.5760130000016943 seconds because of gap starting at 26662.885448 and ending at 26663.03291`.  This gap probably appears at an ad break.

Later, I see messages like `Jumping forward 15.44600029013236 seconds to catch up with the seek range`.  This indicates that the playhead fell back behind the seek range.  If the gap-jumping seek took a very long time to complete, then it may be that this caused playback to fall significantly behind the live edge.  Once we fell out of the seek range, seeking to get back in may have created a kind of seek-loop.

I'm looking into repro now, but I'm having trouble accessing your content.  It's not available cross-origin.  I'm running the content through a local CORS proxy, but this is creating some performance problems.  I'm currently trying to work around this by forcing a lower resolution so that the proxy can respond quickly enough.

I'm also trying to get a baseline for behavior on ChromeOS, before I try anything on Chromecast, where debugging will be significantly more difficult.

So far, I haven't hit any ads yet.  Roughly how often are the ad breaks?

Is there a cross-origin friendly URL you can share with us privately?  This would be easier to debug with.

**Comment by joeyparrish** [comment]
As a workaround, can you try disabling gap-jumping entirely?  This would be a config like:

```js
player.configure({
  streaming: {
    smallGapLimit: 0,
    jumpLargeGaps: false,
  },
});
```

If the ad-break gaps are small enough for the platform to play through them, this should work.  If not, then they will stall essentially forever.

**Comment by joeyparrish** [comment]
Incidentally, I just ran into an ad break on ChromeOS (after 10+ minutes playback), and the player got "stuck" somehow.  Seeking forward 1 second got it moving again.  This corresponded with what I presume is an ad break, although there was no gap reported and no actual ad, just a logo for the channel.

**Comment by joeyparrish** [comment]
I hit another ad break, and this time, I noticed that I was hearing audio for the ads, but the video was stuck on a still frame of the channel logo.  After listening to a couple of ads, I decided to seek backward by 1 second, at which point I was able to see the video of the ad I was listening to.

Based on this, I suspect there is something wrong with the encoding of your ads.  If I see this behavior on ChromeOS, which is essentially a desktop platform with more forgiving decoders, I expect that Chromecast, with its stricter hardware decoders, could easily fail or give up at the same point.

Decoding and rendering are not controlled by the player, but rather the platform, so I don't believe this behavior is something that we can fix in JavaScript.

In the chrome:media-internals logs, I see a lot of messages about video demuxer underflow and audio buffer truncation.  I am not expert enough to interpret these messages, but I suspect at least some of them are important indicators of what the browser is doing with your media.

**Comment by joeyparrish** [comment]
Please try [disabling gap-jumping on Chromecast](https://github.com/google/shaka-player/issues/3397#issuecomment-840023788) to see if that helps.

If is does not, I suggest you investigate the encoding of your ads to ensure that they conform with the Chromecast's hardware decoder requirements.  If you need, I can point you in the direction of Chromecast support to help you with this.

**Comment by smypf** [comment]
Thanks @joeyparrish for your input. I'll pass this onto the team for further investigation to see if disabling gap-jumping does anything.

We'll also look into what's happening with encoding of the ads compared to the rest of the content.
