### ISSUE TITLE
clientHeight doesn't change when going fullscreen

### ISSUE THREAD

**Issue by zoomerbob** [google/shaka-player#3398]
![image](https://user-images.githubusercontent.com/44262518/117746820-a7b77a00-b1d2-11eb-8149-c9e46f38e654.png)
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

**What version of Shaka Player are you using?**
3.0.10

**Can you reproduce the issue with our latest release version?**
Haven't been able to check this.

**Can you reproduce the issue with the latest code from `master`?**

**Are you using the demo app or your own custom app?**
Custom App

**If custom app, can you reproduce the issue using our demo app?**
Haven't been able to check this.

**What browser and OS are you using?**
Google Chrome (64bit) 90.0.4430.93
Windows 10 Home Single Language

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

![image](https://user-images.githubusercontent.com/44262518/117746801-9bcbb800-b1d2-11eb-81b8-7a8da41c8fe6.png)

**What did you do?**
i)we took the media from player
media = player.getMediaElement();
ii)and  player_height  and player_widthare set from the media
player_height =media&&media.clientHeight
player_width=media&&media.clientWidth

The value of  clientWidth changes when it becomes fullscreen but the clientHeight clientHeight  does not change, it always the same value from player.

**What did you expect to happen?**
The height should change when it becomes fullscreen

**What actually happened?**
Height does not change when made fullscreen. showing same value from player

![image](https://user-images.githubusercontent.com/44262518/117746892-c9b0fc80-b1d2-11eb-9da6-9a6859168009.png)

![image](https://user-images.githubusercontent.com/44262518/117746868-bf8efe00-b1d2-11eb-90f4-b888d9e44dc0.png)

**Comment by surajkumar-sk** [comment]
@zoomerbob Could you please give me your Custom app code if possible? 
If i understand your issue properly, the client height is remaining constant in your custom app.
the code i used 
``` 
media = player.getMediaElement();
player_height =media.clientHeight;
player_width = media.clientWidth;
document.addEventListener('fullscreenchange', () => {
    player_height =media.clientHeight;
    player_width = media.clientWidth;
    console.log("Client Height : " + player_height);
    console.log("Client Width : "+player_width);});
```
I was unable to reproduce this issue in windows 8.1, chrome 90.0.xxx.xx, Shaka-player v3.0.x.

![Capture](https://user-images.githubusercontent.com/71056993/117862983-1e428f00-b248-11eb-958e-439b5236dc02.JPG)

![Capture1](https://user-images.githubusercontent.com/71056993/117862992-1f73bc00-b248-11eb-8b16-5020937e2277.JPG)
