### ISSUE TITLE
Add NPM Exports

### ISSUE THREAD

**Issue by palmerj3** [google/shaka-player#34]
I would like for you to create a file index.js in the root of the project that contains the proper module.exports for all of the major classes for shaka-player.

Currently the NPM dependency requires google closure compiler in order to be used and the individual namespaced classes are only available after including the script in head or </body>.

Exposing module.exports would allow this lib to be used in a CommonJS environment more easily.

**Comment by palmerj3** [comment]
I've created a PR for this feature - please review when you have the chance. Thanks!

https://github.com/google/shaka-player/pull/35

**Comment by joeyparrish** [comment]
Closing now that #35 is merged.  Thanks!
