### ISSUE TITLE
Cannot play PlayReady content on Xbox Series S

### ISSUE THREAD

**Issue by radiantmediaplayer** [google/shaka-player#3408]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.1.0

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Did not try

**Are you using the demo app or your own custom app?**
Own custom app

**If custom app, can you reproduce the issue using our demo app?**
N/a

**What browser and OS are you using?**
UWP Javascript app built with Visual Studio 2017. Note that I am deploying an actual UWP WebView app on an actual Xbox for my testing, I am not using the Xbox browser MS Edge or a simulator.

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Xbox Series S OS 10.0.19041.7771

**What are the manifest and license server URIs?**
Your can use the below for testing:
https://github.com/google/shaka-player/blob/87797157af7083e020c29ba84a0a806d2ab1f07b/demo/common/assets.js#L549
https://github.com/google/shaka-player/blob/87797157af7083e020c29ba84a0a806d2ab1f07b/demo/common/assets.js#L671
https://github.com/google/shaka-player/blob/87797157af7083e020c29ba84a0a806d2ab1f07b/demo/common/assets.js#L963

**What actually happened?**
We have been trying to add official support for Xbox with our player. We do not have a Xbox One onsite but we have a Xbox Series S (the last one). 

First I shall mention that there was a requirement for us to make Shaka player work on Xbox Series S. We need to add https://github.com/google/shaka-player/blob/87797157af7083e020c29ba84a0a806d2ab1f07b/demo/index.html#L54 fastestsmallesttextencoderdecoder/EncoderDecoderTogether.min.js or the player will not pass shaka.Player.isBrowserSupported (!!window.TextDecoder return false).

We have been able to play DASH streaming with Shaka player rather well: AVC, HEVC, Multi-audio and Multi-captions. 

We however do not seem to have DASH DRM playready working. Whatever DASH + PlayReady we are trying to play we end up with a fail and the below error:

```
shaka.util.Error {
  "severity": 2,
  "category": 6,
  "code": 6002,
  "data": [
    "NotSupportedError"
  ],
  "handled": false,
  "message": "Shaka Error DRM.FAILED_TO_CREATE_CDM (NotSupportedError)",
  "stack": "Error: Shaka Error DRM.FAILED_TO_CREATE_CDM (NotSupportedError)\n   at shaka.util.Error (ms-appx-web://68c88097-af3f-495b-a0e9-45ee441ed437/rmp/dash/shaka-player.ui.debug.js:156:730)\n   at Anonymous function (ms-appx-web://68c88097-af3f-495b-a0e9-45ee441ed437/rmp/dash/shaka-player.ui.debug.js:703:376)\n   at $jscomp.generator.Engine_.prototype.nextStep_ (ms-appx-web://68c88097-af3f-495b-a0e9-45ee441ed437/rmp/dash/shaka-player.ui.debug.js:43:94)\n   at $jscomp.generator.Engine_.prototype.throw_ (ms-appx-web://68c88097-af3f-495b-a0e9-45ee441ed437/rmp/dash/shaka-player.ui.debug.js:41:228)\n   at [throw] (ms-appx-web://68c88097-af3f-495b-a0e9-45ee441ed437/rmp/dash/shaka-player.ui.debug.js:44:109)\n   at c (ms-appx-web://68c88097-af3f-495b-a0e9-45ee441ed437/rmp/dash/shaka-player.ui.debug.js:45:95)"
}
rmp.debug.js (12,336747)
   {
      [functions]: ,
      __proto__: { },
      category: 6,
      code: 6002,
      data: [ ],
      handled: false,
      message: "Shaka Error DRM.FAILED_TO_CREATE_CDM (NotSupportedError)",
      severity: 2,
      stack: "Error: Shaka Error DRM.FAILED_TO_CREATE_CDM (NotSupportedError)
   at shaka.util.Error (ms-appx-web://68c88097-af3f-495b-a0e9-45ee441ed437/rmp/dash/shaka-player.ui.debug.js:156:730)
   at Anonymous function (ms-appx-web://68c88097-af3f-495b-a0e9-45ee441ed437/rmp/dash/shaka-player.ui.debug.js:703:376)
   at $jscomp.generator.Engine_.prototype.nextStep_ (ms-appx-web://68c88097-af3f-495b-a0e9-45ee441ed437/rmp/dash/shaka-player.ui.debug.js:43:94)
   at $jscomp.generator.Engine_.prototype.throw_ (ms-appx-web://68c88097-af3f-495b-a0e9-45ee441ed437/rmp/dash/shaka-player.ui.debug.js:41:228)
   at [throw] (ms-appx-web://68c88097-af3f-495b-a0e9-45ee441ed437/rmp/dash/shaka-player.ui.debug.js:44:109)
   at c (ms-appx-web://68c88097-af3f-495b-a0e9-45ee441ed437/rmp/dash/shaka-player.ui.debug.js:45:95)"
   }
```

Now that could be just that be the following code returns "playready support ok" when run in the same app.
```
var config = [{
  "initDataTypes": ["cenc"],
  "audioCapabilities": [{
    "contentType": "audio/mp4;codecs=\"mp4a.40.2\""
  }],
  "videoCapabilities": [{
    "contentType": "video/mp4;codecs=\"avc1.42E01E\""
  }]
}];
try {
  navigator.
    requestMediaKeySystemAccess("com.microsoft.playready", config).
    then(function (mediaKeySystemAccess) {
      console.log('playready support ok');
    }).catch(function (e) {
      console.log('no playready support');
      console.log(e);
    });
} catch (e) {
    console.log('no playready support');
    console.log(e);
}
```

Is there any additional steps needed to run DASH PlayReady with Shaka Player on Xbox Series S? I understand my question is about Xbox Series S and not Xbox One but my understanding is that hardware aside the web software is very similar on both (running a WebView based on MS Edge legacy 18). Are you able to run the above samples on Xbox One?
I have attached the support.html (screenshots) output when read from our test app. 
![IMG_4826](https://user-images.githubusercontent.com/18260893/118304702-4dc2f700-b4e7-11eb-9642-3f0096b03fb1.jpg)
![IMG_4829](https://user-images.githubusercontent.com/18260893/118304720-50bde780-b4e7-11eb-97c9-6a6189f5650d.jpg)

**Comment by joeyparrish** [comment]
In our experience, the Xbox's Edge app itself doesn't claim to support PlayReady or any DRM.  In our test environment, which uses [a native app embedding a WebView](https://github.com/google/generic-webdriver-server/blob/main/backends/xboxone/how-it-works.md#the-container-app), we had to add a specific Capability to the app's manifest to enable DRM in the WebView:

https://github.com/google/generic-webdriver-server/blob/826ab24885056591193857cc3c31af98bc60d3b0/backends/xboxone/app-template/Package.appxmanifest#L46-L54

```xml
  <Capabilities>
    <Capability Name="internetClient" />

    <!--
    Added by hand to Enable PlayReady DRM.
    https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/playready-client-sdk#use-playready-drm-on-xbox-one
    -->
    <DeviceCapability Name="6a7e5907-885c-4bcb-b40a-073c067bd3d5" />
  </Capabilities>
```

If there is a way to activate PlayReady in the Xbox's built-in Edge application, I haven't found it.

Does this help?

**Comment by radiantmediaplayer** [comment]
Yes adding the DeviceCapability in the app manifest did the trick for us. Thank you for that.
I believe that whether you are building a Xbox app through generating a WebView from native code or starting a JavaScript UWP app from Visual studio the Xbox will still render the app in an Edge-based WebView. While the browser itself on Xbox does not present support for PR content, the WebView does provide such support. With a bit of luck [MS will port the Chromium based Edge](https://www.theverge.com/2021/3/7/22318050/microsoft-edge-xbox-chromium-browser-testing) engine with an upcoming Xbox update, this might just open new capabilities for developers and Shaka player.
