### ISSUE TITLE
Player Viewable Percentage

### ISSUE THREAD

**Issue by zoomerbob** [google/shaka-player#3416]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

**Is your feature request related to a problem? Please describe.**
We would like to know if the video being played is currently viewable to the user.  Is the tab active, is the player above the scroll point? & how much?

**Describe the solution you'd like**
Return a percentage value describing how much of the player is currently visible in the browser viewport.

**Describe alternatives you've considered**

**Additional context**
MRC specification for Viewability:  http://mediaratingcouncil.org/063014%20Viewable%20Ad%20Impression%20Guideline_Final.pdf

**Comment by michellezhuogg** [comment]
Hello @zoomerbob ,

It sounds like a general question with the html page and the browser window rather than a specific question to Shaka Player. Is it possible to get the DOM element of the video container, and check the visibility with the window via Javascript?

**Comment by joeyparrish** [comment]
This has nothing to do with the player, but here are some links to the web APIs you would use for this:

 - Get the size of the window with window.innerHeight & window.innerWidth: https://developer.mozilla.org/en-US/docs/Web/API/Window/innerHeight
 - Get the scroll position of the window with window.scrollX & window.scrollY: https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollX
 - Get the size and position of the element with element.offsetTop, offsetLeft, offsetWidth, offsetHeight: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetTop
 - Determine how much of the element's rectangle is within the visible rectangle of the window

What's visible is the intersection of the scrolled-into-view window rectangle with the element's rectangle.

Does this help?
