### ISSUE TITLE
Playback fails on unsupported container

### ISSUE THREAD

**Issue by kentuckyfriedtakahe** [google/shaka-player#342]
The Shaka Player demo at doesn't work on Firefox unless you disable WebM support by setting media.webm.enabled=false in about:config

Steps To Reproduce:
* Load Firefox nightly 48
* Navigate to http://shaka-player-demo.appspot.com/demo/ 
* Click on Load

Expected Results:
MP4 video should play

Actual Results:
WebM video attempts to play but fails to do so because Firefox does not support CENC in WebM.

See https://bugzilla.mozilla.org/show_bug.cgi?id=1257716

**Comment by tdrews** [comment]
Hi,

With `48.0a1 (2016-04-18)` and `media.webm.enabled=true`, "Angel One" begins playback (although there seems to be some other issue (perhaps MSE related) that causes playback to stall). Which, piece of content are you having trouble with?

**Comment by cpeterso** [comment]
I filed [Firefox bug 1265512](https://bugzilla.mozilla.org/show_bug.cgi?id=1265512) to track the "Angel One" stall. The "Sintel (multicodec)" video also stalls. This seems like a recent issue in Firefox and/or Shaka because I know I've tested all these videos in Firefox before.

**Comment by tdrews** [comment]
Thanks @cpeterso

**Comment by cpeterso** [comment]
btw, the "Angel One" and "Sintel 4k" stalls are [Firefox bug 1261900](https://bugzilla.mozilla.org/show_bug.cgi?id=1261900), reported by modmaker.

**Comment by kentuckyfriedtakahe** [comment]
Sorry - I should've been more specific. Sintel 4k (multicodec, widevine) doesn't work when media.webm.enable=true and media.mediasource.webm.enable=true because it tries to play Widevine WebM which is not supported.

**Comment by cpeterso** [comment]
Shaka assumes Widevine support implies WebM support. Firefox (Nightly) just landed supported Widevine, but only in MP4 for now.

**Comment by tdrews** [comment]
Yes, I see the problem. We'll look into reworking our support reporting system to handle this scenario.

**Comment by joeyparrish** [comment]
We're currently failing to play encrypted streams on Edge where no capabilities are returned from an EME query.  We'll have to skip this check when the information isn't available.
