### ISSUE TITLE
Cannot read property 'numEvicted' of null

### ISSUE THREAD

**Issue by Dawolee** [google/shaka-player#3423]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes, this is the duplicate issue: https://github.com/google/shaka-player/issues/3323 but I was told by an engineer on our end (JW Player) that Joey had said to file a new issue as we were able to reproduce the behavior consistently.

**What version of Shaka Player are you using?**
3.1.0 (Currently live demo page)

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
N/A

**Are you using the demo app or your own custom app?**
Demo app

**If custom app, can you reproduce the issue using our demo app?**
N/A

**What browser and OS are you using?**
Chrome 90.0.4430.212 in MacOS 10.15.7

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**

demo app URI: https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://cdn-er-test2.online.meo.pt/prd-pcs1/sdash/LIVE$RTP1_HD/index.mpd/Manifest?device=ATV_Live&start=LIVE&end=END;panel=CUSTOM%20CONTENT;build=uncompiled

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**

1) Navigate to [demo app page](https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;panel=HOME;build=uncompiled)
2) Click Custom Content and for manifest URL, enter:
https://cdn-er-test2.online.meo.pt/prd-pcs1/sdash/LIVE$RTP1_HD/index.mpd/Manifest?device=ATV_Live&start=LIVE&end=END (a stream we received from a customer on our end)
3) Click play and the error message should show up.

**What did you expect to happen?**
The stream should play

**What actually happened?**

The stream does not play and Cannot read property 'numEvicted' of null shows up:

**Comment by theodab** [comment]
Yeah, this definitely seems like a bug. Looks like we can't handle multi-period manifests that have trick mode tracks, ever since our changes to how we handled periods in `v3.0`. We didn't notice because our only sample content for trick mode was single-period.
I'll look into the exact bug that's causing this.

**Comment by Dawolee** [comment]
Thank you for confirming!
