### ISSUE TITLE
Support persistent licenses and offline in Shaka v2

### ISSUE THREAD

**Issue by coder477** [google/shaka-player#343]
Found many related issues to this but most of them move around shaka.media.EmeManager 
http://v1-6-2.shaka-player-demo.appspot.com/docs/shaka.media.EmeManager.html which is not found in current version of shaka player.
Was this function completely removed? If so what is the alternative  to have persistent license/licenses stored in shaka player in current API

**Comment by tdrews** [comment]
Hi,

`EmeManager` has been replaced by `DrmEngine` in Shaka v2. However, we have not integrated offline support into Shaka v2 yet. We will support DRM configuration for persistent licenses through `player.configure()` (see [DRM tutorial](http://shaka-player-demo.appspot.com/docs/api/tutorial-drm-config.html) and [Advanced DRM Configuration](http://shaka-player-demo.appspot.com/docs/api/shakaExtern.html#AdvancedDrmConfiguration)) and add a new interface for offline.

**Comment by snehapvs** [comment]
Will the persistent license  or storing license service be availed on chrome desktop ? 

I tried using "persistentstaterequired" parameter in DRM config, with the basic tutorial available from documentation . below is what I have included in player.configure option :
player.configure({
  	  drm: {
  	    servers: {
  	      'com.widevine.alpha': 'url',
	    },
  	    advanced: {
  	        'com.widevine.alpha': {
  	          'persistentStateRequired':true
  	        }
  	      }  
  	  }
  	});
Having advanced in the drm config is giving exception(error 6001). Is it because it is not handled in the current player's version.

**Comment by tdrews** [comment]
Desktop Chrome does not support persistent licenses at this time.

Error 6001 means the key system is not available for your content.
Does your MPD file specify Widevine protection?
If so, and you are on Windows, please check that "WidevineCdm" is listed at chrome://components.

**Comment by snehapvs** [comment]
I am on ubuntu (chrome)..and yes it is widevine protected.
doesnt support persistent licenses means..not supported by widevine or not supported by shaka player?

**Comment by tdrews** [comment]
> Desktop Chrome does not support persistent licenses at this time.

Means Widevine on desktop Chrome does not support persistent licenses at this time.
Shaka v2 will eventually provide APIs to use persistent licenses.

Are you still having difficulties with `player.configure()`?
Are you able to play "Sintel 4K (multicodec, widevine)" from [the demo page](http://shaka-player-demo.appspot.com)?
Are you able to play protected content if you use the default player configuration?

**Comment by snehapvs** [comment]
I was able to play widevine encrypted videos with normal drm configuration on player.configure. as i said earlier, when trying to use advanced options, the video is not being played.

**Comment by tdrews** [comment]
I'm having trouble reproducing the issue. What happens if you add
```
config.drm.advanced = {
  'com.widevine.alpha': {
    'persistentStateRequired': false
  }
};
```
right before https://github.com/google/shaka-player/blob/master/demo/asset_section.js#L150 ?

**Comment by snehapvs** [comment]
Following is the part of code I tried. No error on Windows but giving error on Linux on chrome browser in both cases.
`function initPlayer() {
	var video = document.getElementById('video');
	var player = new shaka.Player(video);
	window.player = player;
	alert("trueee");
	player.configure({
		drm: {
			servers: {
				'com.widevine.alpha': 'license server url',
			},
			advanced: {
				'com.widevine.alpha': {
					'persistentStateRequired':true
				}
			}
		}
	});
	player.load(manifestUri).then(function() {
	})
}
document.addEventListener('DOMContentLoaded', initApp);`

**Comment by tdrews** [comment]
The following works for me on Chrome Linux 50.0.2661.75 and Chrome Linux 51.0.2704.7 with or without "advanced" settings.

app.html:
```html
<!DOCTYPE html>
<html>
  <head>
    <script src="shaka/third_party/closure/goog/base.js"></script>
    <script src="shaka/dist/deps.js"></script>
    <script src="shaka/shaka-player.uncompiled.js"></script>
    <script src="app.js"></script>
  </head>
  <body>
    <video id="video" width="640" controls autoplay></video>
  </body>
</html>
```

app.js:
```javascript
var manifestUri = '//storage.googleapis.com/shaka-demo-assets/sintel-widevine/dash.mpd';

function initApp() {
  shaka.polyfill.installAll();
  shaka.Player.support().then(function(support) {
    if (support.supported) {
      initPlayer();
    } else {
      alert('Browser not supported!');
    }
  });
}

function initPlayer() {
  shaka.log.setLevel(shaka.log.Level.V1);

  var video = document.getElementById('video');
  var player = new shaka.Player(video);

  window.player = player;
  player.addEventListener('error', onErrorEvent);    
  
  player.configure({
    drm: {
      servers: { 'com.widevine.alpha': '//widevine-proxy.appspot.com/proxy' },
      advanced: {
        'com.widevine.alpha': {
          'persistentStateRequired': true
        }
      }
    }
  });
  
  player.load(manifestUri).then(function() {
    console.info('Manifest loaded!');
  }).catch(onError);
}

function onErrorEvent(event) { onError(event.detail); }
function onError(error) { console.error(error); }

document.addEventListener('DOMContentLoaded', initApp);

Does this work? If not, which version of Chrome are you using? What does shaka/support.html say? What log messages do you get in the console after trying the above?

**Comment by coder477** [comment]
Let me try it and before that what do you conclude on persistent license on chrome desktop? Can we expect it in near time?

**Comment by tdrews** [comment]
Persistent licenses on desktop Chrome is a desirable feature; however, I can't give you any expectations of when it would be implemented.

**Comment by coder477** [comment]
Hello the above code is working on Linux (ubuntu) as well.However If I can get a persistent license on chrome Desktop, I doesn’t need persistent parameter there. Thanks

**Comment by tdrews** [comment]
Good to hear that that code works. I'll leave this issue open to track progress for offline support.

**Comment by soualid** [comment]
Sorry but after reading this thread, I am not sure to understand : does the offline support for Widevine is *actually* implemented on Chrome Desktop ? Is it implemented in Shaka Player version 1.6 ? Is it for Shaka Player version 2.0 ?

Many thanks in advance for clarifying this.

**Comment by tdrews** [comment]
* Widevine on desktop Chrome does not support persistent licenses, specifically it does not support `persistent-usage-record` or `persistent-license` [MediaKeySessionType](https://w3c.github.io/encrypted-media/#idl-def-MediaKeySessionType)s.
* Shaka v2 does not provide offline support yet (i.e., APIs to use persistent licenses and to store/load content). 
* Shaka v1 does provide offline support.

We will implement offline support in Shaka v2, but keep in mind that offline support (as defined above) is implemented at the JavaScript level; it is separate from persistent license support, which is implemented at the browser/key-system level.

**Comment by soualid** [comment]
Many thanks. If I understand well and for now, no DRM vendor support persistent license for offline usage on desktop through EME.

And this has, of course, nothing to do with Shaka player. Thank you again for clarifying this.

**Comment by joeyparrish** [comment]
Widevine currently supports persistent licenses on ChromeOS.

This is the bug to track Widevine persistent license support on Chrome for Android: https://bugs.chromium.org/p/chromium/issues/detail?id=493521

The great thing about JavaScript running on top of standard APIs is that if and when a DRM vendor supports persistent licenses on desktop through EME, a Shaka-based application will have access to that capability without any changes.

**Comment by chetanshelake** [comment]
Hello friend,
Shaka player repository is a great repository for html5 player. I have integrate shaka player in my website and it work fine.
I have some issues with that -
1. I am unable to display buffer progress bar.
2. confused about  
     - if video played to some duration like 1 or 2 min and i try to start from first then it start again buffering but this content already buffered from server.
      How can i avoid re-streaming for each video? 
      I have search much more related that but i can't found any solution 
     if any one have solution related that please help me


Thank & regards 
chetan shelake
