### ISSUE TITLE
Add media quality change events

### ISSUE THREAD

**Issue by caridley** [google/shaka-player#3431]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes 

**What version of Shaka Player are you using?**
3.1.0

The problem does not occur with shaka 2.5.x

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Custom app

**If custom app, can you reproduce the issue using our demo app?**
Yes - 
used this code in the console to get player stats 
document.querySelector('video').ui.getControls().getPlayer().getStats()

**What browser and OS are you using?**
Chrome 90.0 on OSX 10.17.7

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**
We will provide streams via e-mail to shaka-player-issues@google.com if needed

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
Please see the attached player-config.json

**What did you do?**
Play multi-period content (live of VOD) with periods that have different bitrate ladders.
Use player.getStats().streamBandwidth to get the current bandwidth.

**What did you expect to happen?**
I expect player.getStats().streamBandwidth to be the bandwidth of the stream that is being played in the current period.

**What actually happened?**
When network bandwidth abundant and we are in a period that does not have the highest bandwidth representation pkayer.getStats().streamBandwidth will report the bandwidth of the highest bandwidth representation form some other period. 

This appears to be a result of period flattening. The flattened manifest representation used for the higher bandwidth representation in some other period uses the highest but still lower bitrate representation within the current period. 

This matters to us because we use bitrate as a quality of experience measure and it is important that it be correct.

Please see the attached player-manifest.xml, player-metrics.json and player-config.json files
[player-manifest.xml.txt](https://github.com/google/shaka-player/files/6556547/player-manifest.xml.txt)
[player-metrics.json.txt](https://github.com/google/shaka-player/files/6556548/player-metrics.json.txt)
[store-settings.json.txt](https://github.com/google/shaka-player/files/6556549/store-settings.json.txt)

.

**Comment by caridley** [comment]
Here is a hypothetical example of the problem
Suppose you have a manifest with period video bitrate ladders like this
period A - 1,2,3,4,5
period B - 1,2,3,3.5,4,5,6

Shaka will create a flattened manifest with these variants that extend through both periods
V1 bitrate 1, period A 1, period B 1
V2 bitrate 2, period A 2, period B 2
V3 bitrate 3, period A 3, period B 3
V4 bitrate 3.5, period A 3, period B 3.5
V5 bitrate 4, period A 4, period B 4
V6 bitrate 5, period A 5, period B 5
V7 bitrate 6, period A 5, period B 6

Variant 4 and 7 are problematic

When variant V4 is used during period A we will report a bitrate of 3.5 but the actual bitrate is 3.

When variant V7 is used during period A we will report a bitrate of 6 but the actual bitrate is 5.

Note that playback seem to work as expected, we just aren't able to report an accurate bitrate.

**Comment by joeyparrish** [comment]
We could adjust how the overall bitrate of the track is computed (for example, take a weighted average by period duration), but with the current architecture, we won't be reporting period-sensitive bitrate information in stats.  The player, at that level, is unaware of the existence of periods.

**Comment by caridley** [comment]
@joeyparrish  I think this might be easy to support. We can capture the bandwidth value in the InitSegmentReference objects and then detect changes in the bandwidth value whenever we append an init segment and emit a new bandwidth changed event.

**Comment by joeyparrish** [comment]
Would you prefer to emit an event with bandwidth info when we start playing the new period, or when we start buffering the new period?

Would you prefer the overall Stream object's bandwidth field to be a max or a weighted average across periods?

**Comment by joeyparrish** [comment]
BTW, these seem like separate enhancements to me, but if we can come up with a concise title and rename this, I would be fine with that.

**Comment by caridley** [comment]
For purposes of measuring the user experience it would be ideal to have this information report at the time of playback.

We would like to see this reported in the same way for all video quality changes; those the occur because of period change and those that occur because of an ABR change. 

Ideally this event would include all information the might be use to measure video quality such as as the bitrate resolution, frame rate.

Can we change the name to "Add media quality change events"

We would be happy to work on a PR for this feature

**Comment by caridley** [comment]
@joeyparrish  here is a sketch of a possible implementation. Please let me know if this looks like a reasonable approach.

We will define a MediaQuality type with these fields (A used for audio, V used for Video)

- A - audioSamplingRate: 44100
- A - codecs: “mp4a.40.2”
- V - codecs: "avc1.640029"
- AV - contentType: “video” | “audio”
- V - frameRate: 59.94
- V - height: 720
- AV - mimeType: “video/mp4” or “audio/mp4”
- A - numChannels: 2
- V - pixelAspectRation: “1:1”
- V - width: 1280


Each InitSegmentReference will have a MediaQuality object associated with it.
The MediaQuality object is passed into the InitSegmentReference constructor.

We add a MediaQualityMonitor class

- It uses MediaQualityChange objects that indicate the position at which a MediaQuality takes effect within the buffered content.
```
MediaQualityChange: {
	mediaQuality: MediaQuality,
	bufferPosition: number,  // end of buffer at time the init segment was appended or better yet the start time of the segment that will next be appended
}

```
- It has an array of MediaQualityChange objects for each stream type video/audio
- When an init segment is appended we add a MediaQualtiyChange object to the array for the stream type
- When an init segment is appended we also emit a BufferingMediaQuailityChange event containing the MediaQuality object
- When the play head crosses the bufferPosition of a MediaQuailtyChange we emit a PlayingMediaQualityChange event 
- We periodically flush MediaQualityChange objects for which the bufferPosition is no longer within the buffered range
