### ISSUE TITLE
Chrome 91 broke widevine playback on cross-origin iframe

### ISSUE THREAD

**Issue by vibhavsinha** [google/shaka-player#3435]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes

**What version of Shaka Player are you using?** 3.1.0 (Latest)

**Can you reproduce the issue with our latest release version?** Yes

**Can you reproduce the issue with the latest code from `master`?** Yes

**Are you using the demo app or your own custom app?** Custom because needs to be cross-origin (copied from demo code)

**If custom app, can you reproduce the issue using our demo app?** No, this only happens within cross-origin iframes

**What browser and OS are you using?** Chrome 91 Android 10

**What are the manifest and license server URIs?**
https://storage.googleapis.com/shaka-demo-assets/sintel-widevine/dash.mpd
https://cwip-shaka-proxy.appspot.com/no_auth

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
Copied code from documentation [Basic Usage](https://shaka-player-demo.appspot.com/docs/api/tutorial-basic-usage.html) and [DRM Usage](https://shaka-player-demo.appspot.com/docs/api/tutorial-drm-config.html)

**What did you do?**
Placed shaka player inside a cross-origin iframe which has been working till Chrome 90. Iframe specifically provided the allow attribute just for this purpose.

**What did you expect to happen?**
Video should play

**What actually happened?**
```
{
  "severity": 2,
  "category": 6,
  "code": 6001,
  "data": [],
  "handled": false
}
```

**Demonstration app**

1. With cross-origin: https://frosty-booth-2b8677.netlify.app/
2. Without cross-origin: https://cocky-bell-b5fbf9.netlify.app

Source code: https://github.com/vibhavsinha/chrome-91-eme-android

I am not sure if this is a bug with Shaka player or Chrome 91. Hence, I am starting here. Below is my understanding so far.

At first, I thought it is related to the robustness setting that Chrome has been giving warning for a long time. However, trying with different robustness levels did nothing to resolve the problem. The older warning about robustness levels is still showing, so it is unlikely to be related. This error is showing up only on Chrome 91 Android. Going through the [logs of change from 90...91](https://chromium.googlesource.com/chromium/src/+log/90.0.4430.212..91.0.4472.77?pretty=fuller&n=10000), there is only one commit that seems to cause this error.

Chrome 91 has this commit "[Block distinctive identifiers for cross-origin frames](https://chromium.googlesource.com/chromium/src/+/59441789da295d001b4f16ff2cf1236b36f83166%5E%21/)". With this change, Chrome browser on android devices ( with L1 support, those where EmeSupport is set to "ALWAYS_ENABLED") aren't able to play widevine within cross-origin iframes. The same videos are playing fine on Firefox android and Edge android.

The test cases in the above commit change seems to show that if the device eme support is always_enabled, then there is no way to play the video in cross-origin iframes. If I am understanding correctly, this is a major breaking change that was applied without any deprecation notice. Is this related to something else that I missed?

Our own automated testing on beta builds of Chrome failed to capture this error because this only applies to devices with L1 support and does not work on emulators.

**Comment by vibhavsinha** [comment]
I am not familiar with Chrome source code to confirm, but this is probably a Chrome bug. However, there might be something that can be done within Shaka player to allow playback by modifying the call to `requestMediaKeySystemAccess`.

**Comment by vibhavsinha** [comment]
Filed a Chrome bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1214327

**Comment by TheModMaker** [comment]
Try changing [this line](https://github.com/google/shaka-player/blob/0579ee77797548c2e91622ef87a6a9b778437c25/lib/util/stream_utils.js#L607) to `not-allowed` (and probably the `persistentState` too).  This may allow the request since it doesn't use distinctive identifiers.  Otherwise there is nothing we can do since this is a Chrome bug.

**Comment by vibhavsinha** [comment]
@TheModMaker I made a matrix which tries all possible combinations of `distinctiveIdentifier`, `persistentState` and `robustness` values. However, none of them worked on Android Chrome 91.

Link to run the matrix on your own devices: https://frosty-booth-2b8677.netlify.app/support-matrix-persistent.html
Source code: https://github.com/vibhavsinha/chrome-91-eme-android/blob/master/iframe/support-matrix-with-persistent.js

![Screenshot_20210603-011017](https://user-images.githubusercontent.com/1254236/120542363-a4e22a80-c408-11eb-9149-f8b3d9291bcb.png)

**Comment by joeyparrish** [comment]
This definitely appears to be a chromium issue, and I can say that the Chrome team is actively working on it.  Since there appears to be no workaround in JavaScript possible, I propose that we close this issue here and focus conversation on https://bugs.chromium.org/p/chromium/issues/detail?id=1214562

Any objections?

**Comment by vibhavsinha** [comment]
Update: Chrome team has fixed this bug and they are planning to release this as a respin of M91.

> The updated version of M91 Chrome for Android should be available next week or the week after that.
