### ISSUE TITLE
Shaka demo click (X) to skip ads - not turn off video

### ISSUE THREAD

**Issue by kocoten1992** [google/shaka-player#3437]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes (I use keyword `ads`)

**What version of Shaka Player are you using?**
demo version, https://shaka-player-demo.appspot.com/

**Are you using the demo app or your own custom app?**
https://shaka-player-demo.appspot.com/

**What browser and OS are you using?**
Google Chrome

**What did you do?**
1. Go to https://shaka-player-demo.appspot.com/
2. Chose Sintel video
3. While ads is playing - there is a little button X at the top, click it

**What did you expect to happen?**
Skip ads

**What actually happened?**
Video turn off

**Comment by kocoten1992** [comment]
Hmm, maybe it was mean to turn off video - but then do we have a skip ads button, or better yet a version without ads.

Because anyone want to debug shaka-player using demo will be force to watch 20s of ads :no_good:.

**Comment by theodab** [comment]
The UI does have a skip ad button, that shows up near the bottom-right corner. Not every ad is skippable; it has to do with the configuration of the ad. For example, our asset `Tears of Steel (multicodec, surround + stereo, single skippable ad)` has an ad that is skippable after 5 seconds.
I don't see anything wrong with having an ad asset on the front page. If you don't want to watch the ads, you could just test with another asset; there are even versions of Sintel with no ads, in the `ALL CONTENT` tab.
