### ISSUE TITLE
3016 - MEDIA_ERR_SRC_NOT_SUPPORTED observed for XBOX on live dash streams

### ISSUE THREAD

**Issue by Nvaneeth** [google/shaka-player#3439]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
3.0.4

**Please ask your question**
We have observed an increase in video start failures in XBOX, we are using dash live streams, error.data[1]: Microsoft extended error code = c0262500, c00d7159. What could be the reason why this happens, how can we resolve this issue?
Thanks

**Comment by TheModMaker** [comment]
It looks like c0262500 is [ERROR_GRAPHICS_OPM_NOT_SUPPORTED](https://www.hresult.info/FACILITY_GRAPHICS/0xC0262500) and c00d7159 is [MF_E_POLICY_UNSUPPORTED](https://www.hresult.info/FACILITY_MEDIASERVER/0xC00D7159).  It looks like PlayReady is having trouble initializing.  Check your HDMI connection and TV support and make sure to install updates.
