### ISSUE TITLE
Shaka V2 any way to get playback rate?

### ISSUE THREAD

**Issue by sanbornhnewyyz** [google/shaka-player#344]
It looks like there is no way to get the current playback rate through Shaka v2 but it would be useful for the same reasons that it was useful in 1.x, namely that Shaka is supporting negative playback rates so we can't read the playback rate straight from the `video` element. Was this API intentionally removed?

**Comment by tdrews** [comment]
Yes, I believe we will need to include this API again.

**Comment by sanbornhnewyyz** [comment]
Okay thanks. So is V2 considered feature complete and you are just working out the bugs or are there features still missing that you plan to include in V2.0.0.

**Comment by tdrews** [comment]
Everything planned for v2 is in the v2.0.0 milestone: https://github.com/google/shaka-player/milestones/v2.0.0. v2 should have feature parity with v1 sans offline.
We will also push some more beta versions before then to appspot.

**Comment by sanbornhnewyyz** [comment]
Alright, thanks.
