### ISSUE TITLE
Couldn't get initDataTransform working for Fairplay

### ISSUE THREAD

**Issue by vivekmishra92** [google/shaka-player#3440]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
3.0.1

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `master`?**
no

**Are you using the demo app or your own custom app?**
custom

**If custom app, can you reproduce the issue using our demo app?**
not entirely sure how to configure a Fairplay example in the demo app

**What browser and OS are you using?**
Safari 14.0.3
Mac Os: big surr 11.2.1

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

manifestUri = 'https://rest-sgs1.ott.kaltura.com/api_v3/service/assetFile/action/playManifest/partnerId/3209/assetId/340117/assetType/media/assetFileId/811223/contextType/PLAYBACK/isAltUrl/False/a.m3u8'
        

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
I will comment with an example code on the bug below. But essentially, I am trying to setup initDataTransform method for fairplay and this method appears to not be working.

**What did you do?**

**What did you expect to happen?**
I expect the initDataTransform method to be called. I have thrown in some console statements and not seeing these resulting in console logs.

**What actually happened?**

As described here https://shaka-player-demo.appspot.com/docs/api/tutorial-fairplay.html
I want to setup the initDataTransform but it doesn't seem to be working.

**Comment by vivekmishra92** [comment]
<!doctype html>
<html>

<head>
    <meta charset="utf-8">

    <title>Fairplay Example</title>
    <script src="https://github.com/videojs/mux.js/releases/latest/download/mux.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/shaka-player/3.0.1/shaka-player.compiled.debug.externs.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/shaka-player/3.0.1/shaka-player.compiled.debug.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/shaka-player/3.0.1/shaka-player.compiled.externs.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/shaka-player/3.0.1/shaka-player.compiled.js"></script>

</head>


<h1>Fairplay Example: Shaka</h1>

<body>

<video id="video"
       width="480" height="270"
       controls autoplay></video>

<script>
    (function (window) {
        console.log("1234321§34321234321");
        if (!window.shaka) {
            throw 'shaka must be loaded';
        }
        let shaka = window.shaka;

        let manifestUri = 'https://rest-sgs1.ott.kaltura.com/api_v3/service/assetFile/action/playManifest/partnerId/3209/assetId/340117/assetType/media/assetFileId/811223/contextType/PLAYBACK/isAltUrl/False/a.m3u8';
        
        let licenseServerUrl = 'licenseServerUrl'

         let cert = 'base64 encoded'

        function setup() {
            console.log('setup running');
            //shaka.polyfill.installAll();
            //if (!shaka.Player.isBrowserSupported()) {
              //  alert('Browser is not supported');
            //}
            initPlayer();
        }

        function initPlayer() {
            let video = document.getElementById('video');
            window.video = video;
            let player = new shaka.Player(video);
            window.player = player;

            player.getNetworkingEngine().registerRequestFilter(requestFilter);
            player.getNetworkingEngine().registerResponseFilter(responseFilter);
            player.addEventListener('error', showErrorEventHandler);

           
            player.configure({
                drm: {
                    servers: {
                        'com.apple.fps.1_0': licenseServerUrl
                    },
                    advanced: {
                        'com.apple.fps.1_0': {
                            serverCertificate: new Uint8Array(cert),
                        },
                    },
                }

            });

            player.configure('drm.initDataTransform', (initData, initDataType) => {
              if (initDataType != 'skd')
                   return initData;
             // 'initData' is a buffer containing an 'skd://' URL as a UTF-8 string.
              const skdUri = shaka.util.StringUtils.fromBytesAutoDetect(initData);
              const contentId = getMyContentId(sdkUri);
              const cert = player.drmInfo().serverCertificate;
              return shaka.util.FairPlayUtils.initDataTransform(initData, contentId, cert);
            });

            player.load(manifestUri)
                .then(showLoadSuccess)
                .catch(showError);
        }

        function responseFilter(type, response) {
            console.error('response filter before license check');
            if (type !== shaka.net.NetworkingEngine.RequestType.LICENSE) {
                return;
            }

            console.error('response filter after license check');
        }

        function requestFilter(type, request) {
            console.error('request filter before license check');
            if (type !== shaka.net.NetworkingEngine.RequestType.LICENSE) {
                return;
            }
            console.log('request filter after license check');
        }

        function showLoadSuccess() {
            console.log('Player loaded successfully');
        }

        function showErrorEventHandler(event) {
            showError(event.detail);
        }

        function showError(error) {
            let message = 'see console';
            if (error.message && error.message.match) {
                let matches = error.message.match(/[^Shaka Error].+?(?=\()/);
                if (matches) {
                    message = matches[0].replace(/\./g, ' ').replace(/_/g, ' ');
                }
            }
            console.error('https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html#value:' + error.code);
            console.error(error);
            alert('ERROR - ' + error.code + ': ' + message);
        }

        setup()
    })(window);


</script>
</body>

</html>

**Comment by vivekmishra92** [comment]
<script> (function (window) { console.log("1234321§34321234321"); if (!window.shaka) { throw 'shaka must be loaded'; } let shaka = window.shaka; let manifestUri = 'https://rest-sgs1.ott.kaltura.com/api_v3/service/assetFile/action/playManifest/partnerId/3209/assetId/340117/assetType/media/assetFileId/811223/contextType/PLAYBACK/isAltUrl/False/a.m3u8'; let licenseServerUrl = 'licenseServerUrl' let cert = 'base64 encoded' function setup() { console.log('setup running'); //shaka.polyfill.installAll(); //if (!shaka.Player.isBrowserSupported()) { // alert('Browser is not supported'); //} initPlayer(); } function initPlayer() { let video = document.getElementById('video'); window.video = video; let player = new shaka.Player(video); window.player = player; player.getNetworkingEngine().registerRequestFilter(requestFilter); player.getNetworkingEngine().registerResponseFilter(responseFilter); player.addEventListener('error', showErrorEventHandler); player.configure({ drm: { servers: { 'com.apple.fps.1_0': licenseServerUrl }, advanced: { 'com.apple.fps.1_0': { serverCertificate: new Uint8Array(cert), }, }, } }); player.configure('drm.initDataTransform', (initData, initDataType) => { if (initDataType != 'skd') return initData; // 'initData' is a buffer containing an 'skd://' URL as a UTF-8 string. const skdUri = shaka.util.StringUtils.fromBytesAutoDetect(initData); const contentId = getMyContentId(sdkUri); const cert = player.drmInfo().serverCertificate; return shaka.util.FairPlayUtils.initDataTransform(initData, contentId, cert); }); player.load(manifestUri) .then(showLoadSuccess) .catch(showError); } function responseFilter(type, response) { console.error('response filter before license check'); if (type !== shaka.net.NetworkingEngine.RequestType.LICENSE) { return; } console.error('response filter after license check'); } function requestFilter(type, request) { console.error('request filter before license check'); if (type !== shaka.net.NetworkingEngine.RequestType.LICENSE) { return; } console.log('request filter after license check'); } function showLoadSuccess() { console.log('Player loaded successfully'); } function showErrorEventHandler(event) { showError(event.detail); } function showError(error) { let message = 'see console'; if (error.message && error.message.match) { let matches = error.message.match(/[^Shaka Error].+?(?=\()/); if (matches) { message = matches[0].replace(/\./g, ' ').replace(/_/g, ' '); } } console.error('https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html#value:' + error.code); console.error(error); alert('ERROR - ' + error.code + ': ' + message); } setup() })(window); </script>

**Comment by vivekmishra92** [comment]
<script>
    (function (window) {
      
        if (!window.shaka) {
            throw 'shaka must be loaded';
        }
        let shaka = window.shaka;

        let manifestUri = 'https://rest-sgs1.ott.kaltura.com/api_v3/service/assetFile/action/playManifest/partnerId/3209/assetId/340117/assetType/media/assetFileId/811223/contextType/PLAYBACK/isAltUrl/False/a.m3u8';

         let licenseServerUrl = ‘licenseServerUrl’
        
	 let cert = ‘base64 encoded’

        function setup() {
            console.log('setup running');
            //shaka.polyfill.installAll();
            //if (!shaka.Player.isBrowserSupported()) {
              //  alert('Browser is not supported');
            //}
            initPlayer();
        }

        function initPlayer() {
            let video = document.getElementById('video');
            window.video = video;
            let player = new shaka.Player(video);
            window.player = player;

            player.getNetworkingEngine().registerRequestFilter(requestFilter);
             player.getNetworkingEngine().registerResponseFilter(responseFilter);
            player.addEventListener('error', showErrorEventHandler);

            player.configure({
                drm: {
                    servers: {
                        'com.apple.fps.1_0': licenseServerUrl
                    },
                    advanced: {
                        'com.apple.fps.1_0': {
                            serverCertificate: new Uint8Array(cert),
                        },
                    },
                }

            });
            

            player.configure('drm.initDataTransform', (initData, initDataType) => {
              
              if (initDataType != 'skd')
                return initData;
  // 'initData' is a buffer containing an 'skd://' URL as a UTF-8 string.
              const skdUri = shaka.util.StringUtils.fromBytesAutoDetect(initData);
              const contentId = getMyContentId(sdkUri);
              const cert = player.drmInfo().serverCertificate;
              return shaka.util.FairPlayUtils.initDataTransform(initData, contentId, cert);
            });

            player.load(manifestUri)
                .then(showLoadSuccess)
                .catch(showError);
        }

        function responseFilter(type, response) {
            console.error('response filter before license check');
            if (type !== shaka.net.NetworkingEngine.RequestType.LICENSE) {
                return;
            }

            console.error('response filter after license check');
        }

        function requestFilter(type, request) {
            console.error('request filter before license check');
            if (type !== shaka.net.NetworkingEngine.RequestType.LICENSE) {
                return;
            }
            console.log('request filter after license check');
        }

        
        function showLoadSuccess() {
            console.log('Player loaded successfully');
        }

        function showErrorEventHandler(event) {
            showError(event.detail);
        }

        function showError(error) {
            let message = 'see console';
            if (error.message && error.message.match) {
                let matches = error.message.match(/[^Shaka Error].+?(?=\()/);
                if (matches) {
                    message = matches[0].replace(/\./g, ' ').replace(/_/g, ' ');
                }
            }
            console.error('https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html#value:' + error.code);
            console.error(error);
            alert('ERROR - ' + error.code + ': ' + message);
        }

        setup()
    })(window);


</script>

**Comment by vivekmishra92** [comment]
```
<!doctype html>
<html>

<head>
    <meta charset="utf-8">

    <title>Fairplay Example</title>
    <script src="https://github.com/videojs/mux.js/releases/latest/download/mux.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/shaka-player/3.0.1/shaka-player.compiled.debug.externs.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/shaka-player/3.0.1/shaka-player.compiled.debug.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/shaka-player/3.0.1/shaka-player.compiled.externs.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/shaka-player/3.0.1/shaka-player.compiled.js"></script>

</head>


<h1>Fairplay Example: Shaka</h1>

<body>

<video id="video"
       width="480" height="270"
       controls autoplay></video>

<script>
    (function (window) {
      
        if (!window.shaka) {
            throw 'shaka must be loaded';
        }
        let shaka = window.shaka;

        let manifestUri = 'https://rest-sgs1.ott.kaltura.com/api_v3/service/assetFile/action/playManifest/partnerId/3209/assetId/340117/assetType/media/assetFileId/811223/contextType/PLAYBACK/isAltUrl/False/a.m3u8';

         let licenseServerUrl = ‘licenseServerUrl’
        
	 let cert = ‘base64 encoded’

        function setup() {
            console.log('setup running');
            //shaka.polyfill.installAll();
            //if (!shaka.Player.isBrowserSupported()) {
              //  alert('Browser is not supported');
            //}
            initPlayer();
        }

        function initPlayer() {
            let video = document.getElementById('video');
            window.video = video;
            let player = new shaka.Player(video);
            window.player = player;

            player.getNetworkingEngine().registerRequestFilter(requestFilter);
             player.getNetworkingEngine().registerResponseFilter(responseFilter);
            player.addEventListener('error', showErrorEventHandler);

            player.configure({
                drm: {
                    servers: {
                        'com.apple.fps.1_0': licenseServerUrl
                    },
                    advanced: {
                        'com.apple.fps.1_0': {
                            serverCertificate: new Uint8Array(cert),
                        },
                    },
                }

            });
            

            player.configure('drm.initDataTransform', (initData, initDataType) => {
              
              if (initDataType != 'skd')
                return initData;
  // 'initData' is a buffer containing an 'skd://' URL as a UTF-8 string.
              const skdUri = shaka.util.StringUtils.fromBytesAutoDetect(initData);
              const contentId = getMyContentId(sdkUri);
              const cert = player.drmInfo().serverCertificate;
              return shaka.util.FairPlayUtils.initDataTransform(initData, contentId, cert);
            });

            player.load(manifestUri)
                .then(showLoadSuccess)
                .catch(showError);
        }

        function responseFilter(type, response) {
            console.error('response filter before license check');
            if (type !== shaka.net.NetworkingEngine.RequestType.LICENSE) {
                return;
            }

            console.error('response filter after license check');
        }

        function requestFilter(type, request) {
            console.error('request filter before license check');
            if (type !== shaka.net.NetworkingEngine.RequestType.LICENSE) {
                return;
            }
            console.log('request filter after license check');
        }

        
        function showLoadSuccess() {
            console.log('Player loaded successfully');
        }

        function showErrorEventHandler(event) {
            showError(event.detail);
        }

        function showError(error) {
            let message = 'see console';
            if (error.message && error.message.match) {
                let matches = error.message.match(/[^Shaka Error].+?(?=\()/);
                if (matches) {
                    message = matches[0].replace(/\./g, ' ').replace(/_/g, ' ');
                }
            }
            console.error('https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html#value:' + error.code);
            console.error(error);
            alert('ERROR - ' + error.code + ': ' + message);
        }

        setup()
    })(window);


</script>

</body>

</html>
```

**Comment by vivekmishra92** [comment]
@joeyparrish @TheModMaker could you please help me in understanding where i'm mkaing mistake

**Comment by joeyparrish** [comment]
When you say "it doesn't seem to be working", can you be more specific?  Is your callback not being called?  Is it throwing an error?  If so, what error?

I notice that in your code, your `initDataTransform` callback refers to `getMyContentId()`, but that is not defined in the sample code you provided.  Could that be the issue?

**Comment by vivekmishra92** [comment]
@joeyparrish I have made some changes to my code(updated above also) and it started playing something, but getting a green screen during playback.

Attaching below the screenshot of the green screen and also console log
<img width="657" alt="Screenshot 2021-06-01 at 21 49 56" src="https://user-images.githubusercontent.com/9200985/120381985-66267480-c323-11eb-90ed-671374fde002.png">
![050C2E89-03C8-41CC-A384-E020250A4C78](https://user-images.githubusercontent.com/9200985/120382125-9241f580-c323-11eb-99fd-8bf51d42cc33.jpg)

**Comment by joeyparrish** [comment]
That kind of video artifact is usually a sign of decrypting with the wrong key, or decoding garbage data through some other means.

In this line, is your content ID correct?

```js
          return shaka.util.FairPlayUtils.initDataTransform(initData, 'e2e-postpackager', cert);
```
