### ISSUE TITLE
Double click to fullscreen throws an error when fullscreen is not supported

### ISSUE THREAD

**Issue by SadiqaliZaveri** [google/shaka-player#3441]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.1.0

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Custom

**What browser and OS are you using?**
Safari - iOS 14.0.1 - iPhone 6s Plus

**What did you do?**
Double-tap the player in safari

**What did you expect to happen?**
Log a warning or silently fail

**What actually happened?**
The fullscreen button is automatically hidden when fullscreen support is not available but the double-tap to fullscreen functionality still runs and throws an error

The error that occurs
`TypeError: a.videoContainer_.requestFullscreen is not a function.`

 **toggleFullScreen** is missing the fullscreenEnabled check.
https://github.com/google/shaka-player/blob/95ba28b5afdb9ca98b6181e06613807acc40044e/ui/controls.js#L548

The fullscreenEnabled check has been used to hide the fullscreen button
https://github.com/google/shaka-player/blob/a0d3e528de04f1b0fe5a33ffcb7844e1414f1b5e/ui/fullscreen_button.js#L38

**Comment by theodab** [comment]
Ah, you're right. Thanks for the report!
