### ISSUE TITLE
How to Customise PlayBackRate or Fast_Forward rate

### ISSUE THREAD

**Issue by hiren3897** [google/shaka-player#3443]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
v3.1.0

**Please ask your question**

I want to customize the playback rate and/or fast forward with personal rates like I want only x0.5, x0.2, x0.4 

Is it possible to use a Shaka player customized UI to do so?

if yes, can you please tell me how to do or give some hint? 

Thank you in advance :)

**Comment by TheModMaker** [comment]
We don't support changing that currently, but we can add it in the future.  It would involve changing [playback_rate_selection.js](https://github.com/google/shaka-player/blob/master/ui/playback_rate_selection.js) and making `playbackRates_` configurable.

**Comment by hiren3897** [comment]
Hello :)
Thank you for your reply,
Yes, it would be great if we can edit those rates. 

I will try my logic to do so in my project and let you know for PR 

Thank you and have a nice week!
