### ISSUE TITLE
selectVariantTrack on streaming event doesn't work anymore

### ISSUE THREAD

**Issue by kocoten1992** [google/shaka-player#3448]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v3.1.0

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Not sure

**Are you using the demo app or your own custom app?**
https://jsbin.com/masatiqare/edit?html,console,output

**What browser and OS are you using?**
Google Chrome

**What did you do?**
I'm trying manually pick resolution, touch https://github.com/google/shaka-player/issues/1119, it was working in 2.4.1.

Now it doesn't work anymore (if you change 3.1.0 with 2.4.1 in jsbin link above, it work again).

**What did you expect to happen?**
In jsbin, I'm picking lowest resolution.

**What actually happened?**
It pick 1440p (not sure because of my monitor or it just pick the highest one).

**Comment by joeyparrish** [comment]
Did you only call selectVariantTrack?  You may also need to disable ABR.  In earlier versions, I seem to recall this was done automatically in select*, but that we received complaints about that and made it so that ABR must be explicitly disabled via the API.

**Comment by kocoten1992** [comment]
in the example above, I did call:
```js
player.configure({abr: {enabled: false}});
```
but it doesn't seem to work
