### ISSUE TITLE
selectVariantTrack doesn't clear buffer if already selected

### ISSUE THREAD

**Issue by AradAral** [google/shaka-player#3450]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes.

**What version of Shaka Player are you using?**
3.1.0

**Can you reproduce the issue with our latest release version?**
Yes. I'm on the latest version.

**Can you reproduce the issue with the latest code from `master`?**
Haven't tested.

**Are you using the demo app or your own custom app?**
Custom app.

**If custom app, can you reproduce the issue using our demo app?**
I think you could do so using the manifest URL below.

**What browser and OS are you using?**
Browser: Chrome v91.0.4472.77
OS: Windows 10 build 19042.985

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
Manifest URL: https://aradaral.github.io/3/manifest.mpd

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
Default. Haven't changed anything.

**What did you do?**
Played the video for a few seconds. Paused it. Checked `player.getStats().height`, it was 720, while `video.videoHeight` was 360, so the video was actually on 360p and not 720p, which you could even tell just by looking at it.

![image](https://user-images.githubusercontent.com/26527405/120937903-75dbf980-c725-11eb-9a22-ada30ca74f83.png)

Note that you may not be able to reproduce this exact scenario; and you don't need to. As long as `abr.enabled` is `true`, and apparently as long as **the quality level of the last downloaded segment is different than the quality level of the current segment** (and by current segment I mean the segment that your `currentTime` is on), you could reproduce an analogous situation.

**What did you expect to happen and what actually happened?**
The definition of the `getStats()` method as written in the docs is as follows:
> Get statistics for **the current playback session**.

So:
- Unless I have misunderstood the definition, `player.getStats().height` should match `video.videoHeight` and the quality of the video at the current playback position. But it doesn't.
- Among `player.getVariantTracks()`, the 720 one is the one that has its `active` property set to `true`, but it isn't the currently-active track. The 360 one is. Unless `active` here means something else; for example if it's referring to the quality level of the last downloaded segment, which if that's the case then it's honestly extremely confusing and unexpected.
- Most importantly, at the same playback position, where the video is at 360p, I do the following to switch to 720p:
```
player.configure({ abr: { enabled: false } });
player.selectVariantTrack([720-track], true);
```
Obviously, you'd expect the buffer to be cleared and the switch from 360 to 720 to happen right away. But it doesn't happen, nothing happens, I suspect this is because Shaka Player thinks we're already on 720, but we aren't, we're on 360.
I'm pretty damn confident that at least this one is a bug

As far as I can tell, this must be a bug. At the very least the last item I explained.

**Comment by ismena** [comment]
Hi @AradAral 
Could you try this on the [nightly build](https://nightly-dot-shaka-player-demo.appspot.com/demo)?
I followed the repro steps with your manifest, and I'm seeing both `player.getStats().height` and `video.videoHeight` at 720p.

![Screen Shot 2021-06-07 at 10 20 38 AM](https://user-images.githubusercontent.com/4951304/121062614-2378f800-c77a-11eb-9913-42bfeff3c9e9.png)

**Comment by TheModMaker** [comment]
`getStats` reports the "selected" track, which is what we'll download for future segments.  It doesn't report what is currently playing.  We don't keep track of existing buffered content.  See #857.

So if ABR has selected a new track, `getStats` will report based on the new track, not what is already buffered.  As you noted, you can use `video.videoHeight` to detect the currently displayed video size, and use `player.getStats().height` or `activeTrack.height` for what is currently selected.

**Comment by AradAral** [comment]
@TheModMaker I understand that now. But none of that justifies the last behavior I described.
The video is currently on 360p, I do a `player.selectVariantTrack([720-track], true, 0);`, which means that I want to force a quality change RIGHT NOW; since I'm setting `clearBuffer` to `true`, and `safeMargin` to `0`. Right?
But Shaka Player looks at the quality of the last downloaded segment which might be 30 seconds later, and sees that it's 720p, then decides to not do anything because it thinks we are 'currently' on the same quality. 😐

**Comment by AradAral** [comment]
@TheModMaker Can you take a look at my last comment? Thanks.

**Comment by TheModMaker** [comment]
This is an odd edge case where you'd want to clear the buffer even though the same stream is already selected.  When you switch to a different track, we ignore it if it is already "selected".  This ensures that if you call twice in a row, we don't waste a lot of effort by doing the same thing again.  The problem here is that track is selected, but you want to clear the buffer explicitly.

I guess we should probably always clear the buffer if the `clearBuffer` argument is set.  This may result in some extra work if the app calls for an already-selected track; but it is probably more correct to trust the app and clear the buffer.  @joeyparrish any problems with that?

**Comment by AradAral** [comment]
> @joeyparrish any problems with that?

@joeyparrish Sorry, would you take a look at this...

**Comment by joeyparrish** [comment]
Sounds good to me.

**Comment by AmirHosseinHmd1** [comment]
@TheModMaker Hi. Any updates? Does this have a straightforward fix?

**Comment by AmirHosseinHmd1** [comment]
I'm having this problem too.
