### ISSUE TITLE
Don't jump over the gap at the beginning before the video is played so that the video poster doesn't disappear.

### ISSUE THREAD

**Issue by AradAral** [google/shaka-player#3451]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes.

**What version of Shaka Player are you using?**
3.1.0

**Can you reproduce the issue with our latest release version?**
Yes.

**Can you reproduce the issue with the latest code from `master`?**
Haven't tried.

**Are you using the demo app or your own custom app?**
Custom. But doesn't matter.

**If custom app, can you reproduce the issue using our demo app?**
You should be able to do so; using the below manifest URL.

**What browser and OS are you using?**
Browser: Chrome v91.0.4472.77
OS: Windows 10 build 19042.985

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
Manifest: https://dash.akamaized.net/envivio/EnvivioDash3/manifest.mpd

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
Default.

**What did you do?**
Use the manifest URL above with a poster on the `<video>` tag. This particular manifest is a good example because there is a gap at the start of the video, and that's relevant.

**What actually happened and what did you expect to happen?**
If you do so, you'll see that the poster immediately disappears. The reason for this, as explained by @TheModMaker [in this comment](https://github.com/google/shaka-player/issues/1643#issuecomment-434055165), is apprently because:
> ...there is a gap at the start. When we start playing, we see the gap at the start and seek over it. Because the time is no longer 0, the browser stops displaying the poster.

And that's in fact true. If you check the video's `currentTime` after the poster has disappeared, you'll see that it's greater than 0. However, I don't see why you would want to jump over the gap BEFORE the video is played, which is what causes the poster to disappear in the first place, why couldn't Shaka Player wait until the user plays the video, and then jump over the gap?
DASH.js, for example, behaves the way I just explained: It jumps over the gap at the start **once the video is played**, but not prior to that, as that would make the poster disappear. Couldn't Shaka Player adopt the same approach?

**Comment by ismena** [comment]
@joeyparrish I know you planned some a revamp og the gap jumping logic. Is this something you would consider as part of that?

**Comment by aahmadi458** [comment]
@joeyparrish Is there a chance this will be solved in the next version? I've been using Shaka Player for a long time now but only recently I noticed this issue. Annoying.

**Comment by TheModMaker** [comment]
It looks like this is caused by f7cc2f94312a970f356e9a1a8f47b9ab2216cef6, the fix for #2987.  Since this was gated on autoplay, we should also check for `this.video_.autoplay` so we stay at 0 if we aren't playing.
