### ISSUE TITLE
How can I unmute and set volume of video when it starts play?

### ISSUE THREAD

**Issue by ssaguiar** [google/shaka-player#3452]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
Latest (Master)

**Please ask your question**

I wish to know how I can unmute the audio for the video and set a volume for it.
The problem is that the video will not play if there is no controls muted="muted" in video Dom.

`<video class="videocontainer" id="video" poster="poster.jpg" controls muted="muted">`

I need to make it work in a smart Tv (Samsung) but can't unmute the audio when the video starts.
Already searched a lot for any info but could'nt find anything.

Any help will be apreciated.

**Comment by AradAral** [comment]
Why don't you use the [`video.muted`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/muted) property and set it to `false` if you want to unmute the video?! You can then use the [`video.volume`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/volume) property to raise or lower the video's volume.

**Comment by ssaguiar** [comment]
I tried, but didn't work. 

It gives this error, when I call it:

`Unmuting failed and the element was paused instead because the user didn't interact with the document before`

Have you some example of how to apply this?

**Comment by AradAral** [comment]
Why do you even have `muted="muted"` on your `<video>` element in the first place?

**Comment by ssaguiar** [comment]
No.
If you don't place muted="muted" the video won't autoplay.
You can see this at:

https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

I tryed to make it play in javascript, but it doesn't work either.

```
            video.play().then(function () {

                video.muted = false;
                video.volume = 0.2;

```

**Comment by AradAral** [comment]
Well if that's the policy browsers follow then you clearly shouldn't be able to programmatically unmute the video immediately after it's played like you're doing in that code snippet; unless the user interacts with the document first, which what the error message you pasted also states. Because doing so would defeat the whole purpose of that policy, users don't want videos with sound to be auto-played.

**Comment by ssaguiar** [comment]
Ok, but this will play in a smart tv without controls and hls.js works fine in the tv.
I will test if this problem happens with shaka in tv (tested only in windows browser).

**Comment by ssaguiar** [comment]
I just tested in tv emulator and with hls.js it works (start and unmuted). With shaka it doesn't.

Hls.js:
![Captura de Tela (42)](https://user-images.githubusercontent.com/5515284/121053865-2c75c380-c792-11eb-8c49-d81490b5c9fb.png)

shaka:
![Captura de Tela (37)](https://user-images.githubusercontent.com/5515284/121053843-27187900-c792-11eb-913d-100d5c26f325.png)

**Comment by ssaguiar** [comment]
Got it!

In tv you just remove the additional configs from dom:

You just remove:
`controls muted="muted"`

```
        <video class="videocontainer" id="video">
            Your browser does not support HTML5 video.
        </video>
```
The Samsung Tv uses chrome and is already prepared to autoplay with audio not muted.

If testing in browser, it will need to have muted="muted" to autoplay, with audio muted, as stated by Google.

**Comment by joeyparrish** [comment]
Unfortunately, there's nothing we can do about any of this in Shaka Player.  Browser autoplay rules are built into browsers.  Autoplay rules generally allow for:

1. Playback with sound from a user gesture
2. Autoplay without sound, with a user gesture required to enable sound again

It seems like the TV doesn't have any of these restrictions, but browsers generally will.

Does this help?

**Comment by ssaguiar** [comment]
In Tv (Tizen) it works fine.
