### ISSUE TITLE
Shaka Player CAF V3 - DASH + WIDEVINE - 6008

### ISSUE THREAD

**Issue by mrosetea** [google/shaka-player#3460]
Good evening, in advance sorry for the inconvenience, I come for your help since I do not know what else to try and I am desperate.
Currently I have an application developed with version 2 of the Chromecast SDK and a WEB application that uses Shaka Player, I want to develop a new application using the CAF V3 version.
We are using DASH + Widevine as encode, I have no problems wanting to get the manifest file, even starting to get the video chunks.
However, when I get to the service in which I obtain the license, it responds with status 200 but the Shaka Player that comes embedded in CAF v3 responds with an error 6008 - LICENSE_RESPONSE_REJECTED.
However, the license details that I send to the player are exactly the same as those that I send in the other applications that work correctly.
Here are some images of the tests I have done and the answers I get from the API.

I reiterate my thanks to you for your support to resolve this issue.
<img width="1792" alt="Captura de Pantalla 2021-06-09 a la(s) 20 40 31" src="https://user-images.githubusercontent.com/11566656/121453280-88914100-c966-11eb-82d8-1e190eb4886c.png">
<img width="1790" alt="Captura de Pantalla 2021-06-09 a la(s) 20 40 41" src="https://user-images.githubusercontent.com/11566656/121453283-89c26e00-c966-11eb-9e49-b7bcbc86d7ca.png">
<img width="1166" alt="Captura de Pantalla 2021-06-09 a la(s) 20 41 42" src="https://user-images.githubusercontent.com/11566656/121453284-8a5b0480-c966-11eb-88c6-855e93f45a95.png">

**Comment by joeyparrish** [comment]
That error means that the license response was rejected by the platform.  So it may have been malformed in some way.

`licenseHandler` and `licenseRequestHandler` are part of CAF, not Shaka Player, so we can't help you debug that.  You may want to check out https://support.google.com/chromecast/contactflow or https://stackoverflow.com/questions/tagged/Google-Cast for support on CAF.  Those both appear to be official support channels.

Since it's the response that is rejected, my guess would be that the way you're handling it may be wrong.  But we're not familiar with CAF, so I can't guess what's wrong.

**Comment by mimse** [comment]
We use this for our DRM license with DRM Today



```
/**
 * Handling license for widevine.
 * @param  {string} licenseData Current license.
 * @return {Uint8Array}             Decoded licenses.
 */
const licenseHandler = licenseData => {
  // This is the wrapped license, which is a JSON string.
  const wrappedString = fromUTF8(licenseData);
  // Parse the JSON string into an object.
  const wrapped = JSON.parse(wrappedString);
  // This is a base64-encoded version of the raw license.
  const rawLicenseBase64 = wrapped.license;
  // Decode that base64 string into a Uint8Array
  // The raw license will be fed to the Widevine CDM.
  return fromBase64(rawLicenseBase64);
};
```

```
function fromCharCode(args) {
  const max = 16000;
  let ret = '';
  for (let i = 0; i < args.length; i += max) {
    const subArray = args.subarray(i, i + max);
    ret += String.fromCharCode.apply(null, subArray);
  }

  return ret;
}

export default function fromUTF8(data) {
  if (!data) return '';

  let uint8 = new Uint8Array(data);
  // If present, strip off the UTF-8 BOM.
  if (uint8[0] === 0xef && uint8[1] === 0xbb && uint8[2] === 0xbf) {
    uint8 = uint8.subarray(3);
  }

  // http://stackoverflow.com/a/13691499
  const utf8 = fromCharCode(uint8);
  // This converts each character in the string to an escape sequence.  If the
  // character is in the ASCII range, it is not converted; otherwise it is
  // converted to a URI escape sequence.
  // Example: '\x67\x35\xe3\x82\xac' -> 'g#%E3%82%AC'
  const escaped = escape(utf8);
  // Decode the escaped sequence.  This will interpret UTF-8 sequences into the
  // correct character.
  // Example: 'g#%E3%82%AC' -> 'g#€'
  return decodeURIComponent(escaped);
}
```

```
/**
 * @param {string} str Input.
 * @returns String.
 */
export default function fromBase64(str) {
  // atob creates a "raw string" where each character is interpreted as a byte.
  const bytes = window.atob(str.replace(/-/g, '+').replace(/_/g, '/'));
  const result = new Uint8Array(bytes.length);
  for (let i = 0; i < bytes.length; i += 1) {
    result[i] = bytes.charCodeAt(i);
  }
  return result;
}
```

Hope this can help you

With regards

Morten
