### ISSUE TITLE
Is there any way to detect CDM version installed in the browser?

### ISSUE THREAD

**Issue by adgllorente** [google/shaka-player#3461]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes.

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes.

**What version of Shaka Player are you using?**
Does not apply.

**Please ask your question**
We know CDM releases are rolled out to users automatically, and Widevine, is blocking some releases that are vulnerable after a grace period.

However, we would like to inform the user showing a popup before launching the playback if the CDM is not updated.

Is there any way to detect which version of the CDMs are installed in the browser using Javascript?

Thanks.

**Comment by joeyparrish** [comment]
Not as far as I know.  At least, there is nothing standardized in EME for this, and existing web APIs are so easily abused for fingerprinting already that I am certain the W3C will not want to add an explicit string for a CDM version.

**Comment by adgllorente** [comment]
Thanks for answering, I think this issue may be closed.
