### ISSUE TITLE
How to change drm server dynamically?

### ISSUE THREAD

**Issue by ssaguiar** [google/shaka-player#3462]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
Master

**Please ask your question**
In our application, every stream will have a Widevine key as (fake, just to show how the server will be):

`'com.widevine.alpha': 'https://keyserver/CHANNELNAME/kjbfknsdkjcnkjafvnjnafskjvafdbvhjfdbv'`

In shaka's configuration, I put:

```
        drm: {
            servers: {
                    'com.widevine.alpha': 'https://keyserver/CHANNELNAME/kjbfknsdkjcnkjafvnjnafskjvafdbvhjfdbv'
             }
        }
```

For every channel the key will be different.
How can I change this parameter (servers), dynamically?  
If I put all drm server's in config just one channel (the latest) will work.

I have done this:

```
player.load(CHANNELADDRESS).then(function () {
	player.configure({
		drm: {
			servers: {
				'com.widevine.alpha': ''https://keyserver/CHANNELNAME/kjbfknsdkjcnkjafvnjnafskjvafdbvhjfdbv''
			}
		}
	});

       video.play().then(function () {
      .
      .
```
It seems to work. Is it the correct way t do it?

Thanks

**Comment by joeyparrish** [comment]
I would suggest doing something like this:

```js
async function changeChannel(manifestUri, licenseUri) {
  player.configure('drm.servers.com\\\.widveine\\\.alpha': licenseUri);
  await player.load(manifestUri);
  await video.play();
}
```

I believe the key thing is to set necessary configuration before calling load().  Some config changes can take effect in the middle of a playback session, but others only affect a subsequent call to load().

Does this help?

**Comment by ssaguiar** [comment]
I will try this way and let you know.
Thanks a lot.

**Comment by ssaguiar** [comment]
@joeyparrish 
Sir, I wish to know if you can help and guide me in the right direction because the shaka's demo is so complex.
I need to implement a player app which will:

- Select any of the audios presents in stream;
- Play Widevine encoded stream (and the above);

I get lots of error code 4012, in some channels:


```
onAdaptationChange
shakainit.js:180 Playerloading finished.
shakainit.js:210 The video has now been loaded!
shakainit.js:213 Configuring key for channel: TNT2_WV keyenable: 1
shakainit.js:165 Buffering...
shakainit.js:376 Error code 4012
onError @ shakainit.js:376
onErrorEvent @ shakainit.js:369
Le.dispatchEvent @ fake_event_target.js:114
Fk @ player.js:5194
cl @ player.js:4877
Qk @ player.js:5340
Dc @ player.js:1712
rf @ drm_engine.js:1559
(anonymous) @ drm_engine.js:106
(anonymous) @ timer.js:65
(anonymous) @ delayed_tick.js:56
setTimeout (async)
rd.U @ delayed_tick.js:60
N.U @ timer.js:66
Qf @ drm_engine.js:1533
(anonymous) @ drm_engine.js:1159
shakainit.js:376 Error code 4012
```

the TELEMAX INT stream plays ok in hls.js but doesn't play in shaka.
TEST_SHAKA_DEMO is from the hls.js demo.
Obs: all channels are for testing purpose.

My code, till now is:

`
let activeTrack = 0;
let trackIndex = 0;
let numberOfTracks = 0;
let tracks = [];
let player = null;
let video = null;
let ui = null;
let controls = null;
let videoContainer = null;
let timer = '';
let channelListLenght = 0;
let channelListIndex = 0;
let channelListIndexOffset = 0;

$(document).ready(function () {

    if (localStorage.getItem("channelIndex") !== null) {
        channelListIndex = localStorage.getItem('channelIndex');

        if (isNaN(channelListIndex)) {
            channelListIndex = 0;
        } else {}

    } else {
        console.log("channelIndex not found");
        channelListIndex = 0;
    }

    document.getElementById("loader").style.visibility = "hidden";
    document.getElementById('videoTracks').innerHTML = "";
    let updateclock = setInterval(getStats, 1000);
    channelListLenght = channelsList.length;
});

let channelsList = [
    ["TELEMAX INT", "http://live-edge01.telecentro.net.ar/live/smil:tlx.smil/chunklist_w1527043435_b1828000_sleng.m3u8?eamogratis?Entretenimiento.m3u8", "https://upload.wikimedia.org/wikipedia/commons/4/4c/Telemax.png", "0"],
    ["NASA TV", "https://ntv1.akamaized.net/hls/live/2014075/NASA-NTV1-HLS/master.m3u8", "https://raw.githubusercontent.com/jnk22/kodinerds-iptv/master/logos/tv/nasatv.png", "0"],
    ["TEST_SHAKA_DEMO", "https://storage.googleapis.com/shaka-demo-assets/angel-one-widevine-hls/hls.m3u8", "images/channel.png", "https://cwip-shaka-proxy.appspot.com/no_auth"],
    ["CHANNEL_WV", "https://somedomain.com/streams/CHANNEL_WV/playlist.m3u8", "images/channel.png", "1"]
];

function initApp() {
    shaka.polyfill.installAll();

    if (shaka.Player.isBrowserSupported()) {
        document.addEventListener('shaka-ui-loaded', () => initPlayer());
    } else {
        console.error('Browser not supported!');
    }
}

async function initPlayer() {

    console.log("initPlayer");

    video = document.getElementById('video');
    player = new shaka.Player(video);

        let configuration = {
            preferredTextLanguage: 'und',
        // clearKeys: {
        // },
        drm: {
            servers: {
                'com.widevine.alpha': 'https://nldnbkdnbkjndskbnjsnbk'
            },
            advanced: {
                'com.widevine.alpha': {
                    'videoRobustness': 'SW_SECURE_CRYPTO',
                    'audioRobustness': 'SW_SECURE_CRYPTO'
                }
            }
        },
        abr: {
            bandwidthDowngradeTarget: 0.95,
            bandwidthUpgradeTarget: 0.85,
            defaultBandwidthEstimate: 500000,
            enabled: true,
            switchInterval: 8
            // enabled: false
        },
        streaming: {
            ignoreTextStreamFailures: true,
            bufferBehind: 30,
            bufferingGoal: 10,
            durationBackoff: 1,
            alwaysStreamText: false,
            jumpLargeGaps: false,
            rebufferingGoal: 2,
            smallGapLimit: 0.5,
            startAtSegmentBoundary: false,
            safeSeekOffset: 5,
            retryParameters: {
                timeout: 10000, // timeout in ms, after which we abort; 0 means never
                timeout: 0, // timeout in ms, after which we abort; 0 means never
                stallTimeout: 5000,  // stall timeout in ms, after which we abort
                connectionTimeout: 10000, // connection timeout in ms, after which we abort
                maxAttempts: 2, // the maximum number of requests before we fail
                baseDelay: 1000, // the base delay in ms between retries
                backoffFactor: 2, // the multiplicative backoff factor between retries
                fuzzFactor: 0.5, // the fuzz factor to apply to each retry delay
            }
        }
    };

    console.log('CONFIG RESULT', player.configure(configuration));

    window.player = player;

    player.addEventListener('error', onErrorEvent);

    player.addEventListener('adaptation', onAdaptationChange);

    player.addEventListener('variantchanged', onAdaptationChange);

    video.onwaiting = function(){
        console.log("Buffering...");
        showSpinner();
    };

    video.onplaying = function(){
        console.log("Not buffering...");
        hideSpinner();
    };

    player.addEventListener('paused', function() {
        console.log("player has paused...");
    });

    player.addEventListener('loaded', function() {
        console.log("Playerloading finished.");
    });

    video.addEventListener("playing", function() {
        console.log("started playing");
        hideSpinner();
    });

    playerPlay();
}

async function playerPlay() {

    try {
        console.log("playerPlay - channelListIndex = " + channelListIndex + " channel name: " + channelsList[channelListIndex][0]);
        document.getElementById('selectedChannel').innerHTML = "Channel: " + channelListIndex + " - " + channelsList[channelListIndex][0];

        player.load(channelsList[channelListIndex][1]).then(function () {
            console.log('The video has now been loaded!');

            if(channelsList[channelListIndex][3] == "1") {
                console.log("Configuring key for channel: " + channelsList[channelListIndex][0] + " keyenable: " + channelsList[channelListIndex][3]);
                
                player.configure({
                    drm: {
                        servers: {
                            'com.widevine.alpha': drmserver + channelsList[channelListIndex][0] + drmkey
                        }
                    }
                });
                
            } else if(channelsList[channelListIndex][3] == "0") {

            } else {
                player.configure({
                    drm: {
                        servers: {
                            'com.widevine.alpha': channelsList[channelListIndex][3]
                        }
                    }
                });
            }

            video.play().then(function () {
                localStorage.setItem('channelIndex', channelListIndex);

                try {
                    let texttracks = player.getTextTracks();
                    console.log("Number of text tracks: " + texttracks.length);
                    player.selectTextTrack(texttracks[0]);
                    player.setTextTrackVisibility(true);
                } catch (e) {
                    onError(e);
                }

                tracks = player.getVariantTracks();
                trackIndex = 0;
                numberOfTracks = tracks.length;

                populateTracksInfoUl();
                showTrackInfo();
                video.volume = 0.2;
            });
        });

    } catch (e) {
        onError(e);
    }
}

function changeStream() {
    trackIndex++;

    if(trackIndex > (numberOfTracks - 1)) {
        trackIndex = 0;
    }

    player.configure({
        abr: {
            enabled: false
        }
    });

    player.selectVariantTrack(tracks[trackIndex], true);

    player.configure({
        abr: {
            enabled: true
        }
    });

    populateTracksInfoUl();
    showTrackInfo();
}

function changeChannel() {
    playNextChannel();
}

function playPreviousChannel() {

    channelListIndex--;
    if (channelListIndex < 0) {
        channelListIndex = channelListLenght - 1;
    }

    channelListIndexOffset = channelListIndex;

    fetchVideoAndPlay();
}

function playNextChannel() {

    channelListIndex++;
    if (channelListIndex > channelListLenght - 1) {
        channelListIndex = 0;
    }

    channelListIndexOffset = channelListIndex;
    fetchVideoAndPlay();
}

function fetchVideoAndPlay() {
    document.getElementById('videoTracks').innerHTML = "";
    showSpinner();
    playerPlay();
}

function showTrackInfo() {
    let track = trackIndex + " " + "[ " + tracks[trackIndex].width + ' x ' + tracks[trackIndex].height + "  Bandwidth: " + tracks[trackIndex].bandwidth + " id: " + tracks[trackIndex].id + " type: " + tracks[trackIndex].type + " label: " + tracks[trackIndex].label + "]";

    document.getElementById('selectedStream').innerHTML = "Track: " + track;
}

function onPlayerErrorEvent(event) {
    // Extract the shaka.util.Error object from the event.
    onPlayerError(event.detail);
}

function onUIErrorEvent(event) {
    onPlayerError(event.detail);
}

function onErrorEvent(event) {
    onError(event.detail);
}

function onError(error) {
    console.error('Error code', error.code); //, 'object', error);
}

function onAdaptationChange(event) {

    console.log("onAdaptationChange");

    var tracks = shakaPlayerInstance.getVariantTracks();
    console.log("tracks size: " + tracks.length);

    for (iterator = 0; iterator < tracks.length; iterator++) {
        //if (tracks[iterator].active) {
            console.log("Bandwidth: " + tracks[iterator].bandwidth);
        //    break;
        //}
    }
}

function populateTracksInfoUl(){
    //Add track info to the DOM.
    var ul = document.getElementById('videoTracks');
    ul.innerHTML = "";

    for (var i = 0; i < tracks.length; ++i) {

        var track = tracks[i];
        if (track.active) activeTrack = track;

        if (tracks[i].active) {
            var text = i + " - [ " + track.width + ' x ' + track.height + " ]";
        } else {
            var text = i + " - [ " + track.width + ' x ' + track.height + " ]";
        }
        text += ' ' + (track.bandwidth / 1024).toFixed(0) + ' kbits/s';
        text += " " + track.label;

        var li = document.createElement('li');
        li.textContent = text;
        ul.appendChild(li);
    }

    ul.style.listStyleType = "none";
    ul.style.padding = 0;

    getStats();
}

function getStats() {
    let stats = player.getStats();

    let width = stats.width; // pixels, current video track
    let height = stats.height; // pixels, current video track
    let streambandwidth = stats.streamBandwidth; // bits/sec, total for all current streams
    let estimatedbandwidth = stats.estimatedBandwidth; // The current estimated network bandwidth (in bit/sec).
    let decodedframes = stats.decodedFrames; // same as v1
    let droppedframes = stats.droppedFrames; // same as v1
    let corruptedframes = stats.corruptedFrames;
    document.getElementById("selectedStreamStats").innerHTML = "Bandwidth: " + streambandwidth + ", frames: decoded: " + decodedframes + ", dropped: " + droppedframes + ", corrupted: " + corruptedframes;
}

function getStreamsInfo() {
    for (var iterator = 0; iterator < tracks.length; iterator++) {
        if (tracks[iterator].active) {
            console.log("[*" + tracks[iterator].width + ' x ' + tracks[iterator].height + "  Bandwidth: " + tracks[iterator].bandwidth + " id: " + tracks[iterator].id + " label: " + tracks[iterator].label + "]");

            var aspectRatio = tracks[iterator].width / tracks[iterator].height;
            video.width = video.height * aspectRatio;

        } else {
            console.log("[ " + tracks[iterator].width + ' x ' + tracks[iterator].height + "  Bandwidth: " + tracks[iterator].bandwidth + " id: " + tracks[iterator].id + " label: " + tracks[iterator].label + "]");
        }
    }
}

function showSpinner() {
    //console.log("showSpinner called.");
    document.getElementById("loader").style.visibility = "visible";
}

function hideSpinner() {
    //console.log("hideMainSpinner called.");
    document.getElementById("loader").style.visibility = "hidden";
}

document.addEventListener('DOMContentLoaded', initApp);

document.addEventListener('shaka-ui-loaded', function(){
    console.log("Shaka UI Loaded.");
});
`
