### ISSUE TITLE
Rapid seek causes CCs to disappear when ignoreTextStreamFailures is true

### ISSUE THREAD

**Issue by iperzic** [google/shaka-player#3463]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.10

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Both

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Chrome on macOS Big Sur

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
n/a

**What are the manifest and license server URIs?**
https://nightly-dot-shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;streaming.ignoreTextStreamFailures=true;uilang=en-US;asset=https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd;panel=HOME;build=compiled

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
See pasted demo app video for further details

**What did you do?**
1. Enable CCs
2. Play video
3. Seek to unbuffered area several times in quick succession

**What did you expect to happen?**
The CCs should always be visible when enabled and present

**What actually happened?**
The CCs are not visible, until you disable and enable them back again.
Here is a video of the issue, reproduced in demo app https://streamable.com/d29sd1

After some investigation, I have figured out that this happening because seek happens while previous seek's text parsing is still in progress so when it gets aborted in favor of newer one, it is treated as an error and due to `ignoreTextStreamFailures: true`. 

The code in question can be found [here](https://github.com/google/shaka-player/blob/master/lib/media/streaming_engine.js#L1293).

One solution would be to move `OPERATION_ABORTED` condition (L1302) earlier in the if-else, but I'm not entirely sure that that is the way to go.

I'd be happy to submit a PR with this change, if this is an ok solution.

**Comment by joeyparrish** [comment]
@avelad has a PR for this that should be merged soon.  Thanks!

**Comment by iperzic** [comment]
Awesome, thank you!
