### ISSUE TITLE
How to change captions, resolution and language audio as in  overflowMenuButtons, programmaticaly?

### ISSUE THREAD

**Issue by ssaguiar** [google/shaka-player#3467]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
Latest - Master

**Please ask your question**

I need to change audios and tracks resolutions and enable captions(subtitles) programatically because I will use this in a TV set and can use only the remote control.

To change track, I was using this code:

```
        trackIndex++;

        if(trackIndex > (numberOfTracks - 1)) {
            trackIndex = 0;
        }

        player.configure({
            abr: {
                enabled: false
            }
        });

        player.selectVariantTrack(tracks[trackIndex], true);

        player.configure({
            abr: {
                enabled: true
            }
        });

```
The trackIndex is used because the channels are in an array and are listed using:

`let tracks = shakaPlayerInstance.getVariantTracks();`

The problem was that changing track this way, it will change to the next track as hls tracks * number of audios.

Now, to change audio, I ill use:

`var audioTracks = player.getAudioLanguages();`

With this I will have, for example:

```
audioTracks: [
    "pt",
    "en"
]
```
Then I can select any of these audios using (for english, as above):

`player.selectAudioLanguage(audioTracks[1]);`

To enable text track (subtitles):

```
try {
    let texttracks = player.getTextTracks();
    console.log("Number of text tracks: " + texttracks.length);
    player.selectTextTrack(texttracks[0]);
    player.setTextTrackVisibility(true);
} catch (error) {
    onError(error);
}
```
Is this the right way to do it?

I also need to select resolutions. How can i do it? I can't find information about it.

Thanks for your help.

**Comment by ssaguiar** [comment]
"I also need to select resolutions. How can i do it? I can't find information about it."
Please?

Thanks.

**Comment by TheModMaker** [comment]
To select audio language and still use ABR, use `player.selectAudioLanguage`.  To switch text track, use `player.selectTextTrack`.  To change resolution, you need to manually select a track with `player.selectVariantTrack`.  There is no way to select a resolution by value.  When using `player.selectVariantTrack`, make sure to disable ABR with `player.configure('abr.enabled', false)`.

**Comment by joeyparrish** [comment]
You may also choose to use the convenience method `selectTextLanguage()` to select a text track by language.

**Comment by ssaguiar** [comment]
Thanks for your kind help.

At this moment, I am doing this:

```

// To get the actual audio track name:

console.log("[updateAudioTrackInfo]");
const audioTrackId = hls.audioTrack;
const len = hls.audioTracks.length;
console.log("[updateAudioTrackInfo] -> hls.audioTracks.length = " + len);
const track = hls.audioTracks[audioTrackId];

let audioTrackName = "";

try {
	// Try to run this code 
	audioTrackName = track.name;
	console.log("Selected audio channel is: " + audioTrackName);
} catch(err) {
	// if any error, Code throws the error
	audioTrackName = "";
} finally {

}


// To change stream:

tracks = player.getVariantTracks();
trackIndex = 0;
numberOfTracks = tracks.length;


function changeStream() {
    trackIndex++;

    if(trackIndex > (numberOfTracks - 1)) {
        trackIndex = 0;
    }

    player.configure({
        abr: {
            enabled: false
        }
    });

    player.selectVariantTrack(tracks[trackIndex], true);

    player.configure({
        abr: {
            enabled: true
        }
    });
}

```
Using the above code, I can list the variant tracks as, for example:
```

0 - [ 192 x 144 ] 476 kbits/s stream_6
1 - [ 192 x 144 ] 476 kbits/s stream_7
2 - [ 192 x 144 ] 476 kbits/s stream_5
3 - [ 192 x 144 ] 476 kbits/s stream_4
4 - [ 192 x 144 ] 476 kbits/s stream_9
5 - [ 192 x 144 ] 476 kbits/s stream_8
6 - [ 768 x 576 ] 1787 kbits/s stream_6
7 - [ 768 x 576 ] 1787 kbits/s stream_7
8 - [ 768 x 576 ] 1787 kbits/s stream_5
9 - [ 768 x 576 ] 1787 kbits/s stream_4
10 - [ 768 x 576 ] 1787 kbits/s stream_9
11 - [ 768 x 576 ] 1787 kbits/s stream_8
12 - [ 640 x 480 ] 1383 kbits/s stream_6
13 - [ 640 x 480 ] 1383 kbits/s stream_7
14 - [ 640 x 480 ] 1383 kbits/s stream_5
15 - [ 640 x 480 ] 1383 kbits/s stream_4
16 - [ 640 x 480 ] 1383 kbits/s stream_9
17 - [ 640 x 480 ] 1383 kbits/s stream_8
18 - [ 320 x 240 ] 771 kbits/s stream_6
19 - [ 320 x 240 ] 771 kbits/s stream_7
20 - [ 320 x 240 ] 771 kbits/s stream_5
21 - [ 320 x 240 ] 771 kbits/s stream_4
22 - [ 320 x 240 ] 771 kbits/s stream_9
23 - [ 320 x 240 ] 771 kbits/s stream_8
24 - [ 480 x 360 ] 1125 kbits/s stream_6
25 - [ 480 x 360 ] 1125 kbits/s stream_7
26 - [ 480 x 360 ] 1125 kbits/s stream_5
27 - [ 480 x 360 ] 1125 kbits/s stream_4
28 - [ 480 x 360 ] 1125 kbits/s stream_9
29 - [ 480 x 360 ] 1125 kbits/s stream_8

```
But, the problem is the same:
How can I select the audio and also select one of the resolutions, as it's done in the shaka's player?

I can select what elements I want in DOM as

```
let uiconfig = {
    addSeekBar: false,
    controlPanelElements: ['play_pause', 'mute', 'volume', 'overflow_menu'],
    overflowMenuButtons: ['captions', 'quality', 'language', 'playback_rate']
};
```
and, then:

` ui.configure(uiconfig);`

This will generate the overflowMenuButtons, in which there's a button to select audio and another to select the resolutions individually.
Using the VariantTracks There will have (resolutions * audios) number of tracks. 
If I have 2 resolutions (for example 720p and 360p) and 2 audios (for example english and portuguese), I will have:

- 720p portuguese;
- 720p english;
- 360p portuguese;
- 360p english.

In the overflowMenuButtons resolution select button, there is only one entry for each of the resolutions. And, for the audio button, there is only one entry for each audio language.

My question is how to make it as in the overflowMenuButtons. I suppose it can be done because it's done in the player:

Am I wrong?

![Captura de Tela (48)](https://user-images.githubusercontent.com/5515284/122915037-af218580-d331-11eb-96e5-f3ed9c4a2498.png)
![Captura de Tela (49)](https://user-images.githubusercontent.com/5515284/122915040-b052b280-d331-11eb-955b-360e7908cfe2.png)
![Captura de Tela (50)](https://user-images.githubusercontent.com/5515284/122915041-b0eb4900-d331-11eb-955c-6e06c9c61668.png)

**Comment by ssaguiar** [comment]
> You may also choose to use the convenience method `selectTextLanguage()` to select a text track by language.

**Comment by TheModMaker** [comment]
`player.getVariantTracks` returns all the tracks for every language.  You need to pick them by `track.language` in addition to the resolution.

**Comment by ssaguiar** [comment]
> `player.getVariantTracks` returns all the tracks for every language. You need to pick them by `track.language` in addition to the resolution.

Ok, but what I need is the resolutions and audios separated, as in the images above.

**Comment by joeyparrish** [comment]
If you want to emulate the calls the UI makes, you can read the source to those UI elements:
 - [resolution_selection.js](https://github.com/google/shaka-player/blob/master/ui/resolution_selection.js)
 - [audio_language_selection.js](https://github.com/google/shaka-player/blob/master/ui/audio_language_selection.js)
 - [text_selection.js](https://github.com/google/shaka-player/blob/master/ui/text_selection.js)
 - [language_utils.js](https://github.com/google/shaka-player/blob/master/ui/language_utils.js)

Ultimately, the UI is calling these methods on [shaka.Player](https://shaka-player-demo.appspot.com/docs/api/shaka.Player.html):
 - getVariantTracks()
 - selectVariantTrack(track)
 - selectAudioLanguage(language, role)
 - getTextTracks()
 - selectTextTrack(track)
 - setTextTrackVisibility(visible)
 - isTextTrackVisible()
 - configure('abr.enabled', enabled)
 - getConfiguration().abr.enabled

You may be interested in these fields from [shaka.extern.Track](https://shaka-player-demo.appspot.com/docs/api/shaka.extern.html#.Track) to make decisions:
 - language
 - roles
 - label
 - kind
 - width
 - height

Does this help?

**Comment by ssaguiar** [comment]
Ok, I will study them.
If this is the way you use to populate the above player selectors, I think this is what I need.
Thank you very much to show the path to follow.

**Comment by joeyparrish** [comment]
Happy to help!  Our UI only relies on exported methods of the Player, so you should be able to replicate any UI functionality you need.  And the UI source is all there under the same license as everything else.

Please feel free to open another issue if you need anything else.  Thanks!
