### ISSUE TITLE
Deprecated libs while compiling shaka player

### ISSUE THREAD

**Issue by ssaguiar** [google/shaka-player#3468]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
Master

**Please ask your question**

When compiling Shaka Player, to implement the corrections to buffering, following what is in https://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html , I get these warnings (as before):

~/shaka-player$ python build/all.py
npm WARN deprecated core-js@2.6.12: core-js@<3 is no longer maintained and **not recommended for usage due to the number of issues**. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated istanbul@0.4.5: This module is no longer maintained, try this instead:
npm WARN deprecated   npm i nyc
npm WARN deprecated Visit https://istanbul.js.org/integrations for other alternatives.
npm WARN deprecated request@2.88.0: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm WARN deprecated har-validator@5.1.5: this library is no longer supported

Doesn't deprecated or no longer maintained libs cause problems?
Can I safely ignore these warnings?

Thanks.

**Comment by TheModMaker** [comment]
We only use NPM packages for building and testing, not at runtime.  So long as it builds, everything is fine.  I think most of these are from other projects that we don't have any control over anyway.
