### ISSUE TITLE
missing removeTextTrack api

### ISSUE THREAD

**Issue by kocoten1992** [google/shaka-player#3469]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Is your feature request related to a problem? Please describe.**
we have `addTextTrack` api,
and `addTextTrackAsync`,
even have event remove texttrack https://github.com/google/shaka-player/blob/1125184bfe08863677cb996b0f13d49e18eeade9/lib/player.js#L2138-L2139

But we don't have `removeTextTrack` api - assuming remove is instant - so no async needed (?)

**Comment by TheModMaker** [comment]
Adding tracks is to side-load external text tracks for situations when you don't control the manifest and want to add external text tracks.  Removing tracks is a bit more complex than adding, and there isn't really a use case for it.  You can just hide those tracks from the UI if you don't want them selected.  If the track isn't selected, it won't have any affect.

If the track was initially loaded using `addTextTrack`, we might be able to just remove it from the manifest structure.  But we capture some of the arrays in places, which could cause synchronization problems.  And if the track was initially from the manifest and the content is Live, then we'll just add it back on the next manifest update.

**Comment by kocoten1992** [comment]
Thanks you! My use case are a bit odd, I'm live editing subtitle online.

First thought is edit on specific cue on specific subtitle, but I quickly realize it will not work - we don't expose any api related to internal subtitle cue for live editing.

Second thought is to edit a whole subtitle and using `addTextTrackAsync`, this will work, but without ability to remove old one, old subtitle will pile up to several hundreds or maybe even thousand subtitles - which I guest a full page reload will solve it.

I'mma close this, just letting you my use case.
