### ISSUE TITLE
When the video file is normal, what are the possible reasons for many gaps?

### ISSUE THREAD

**Issue by dlink-cs-YueXiangling** [google/shaka-player#3470]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes.

**What version of Shaka Player are you using?**
v3.0.0

**Can you reproduce the issue with our latest release version?**
Yes,I can.

**Can you reproduce the issue with the latest code from `master`?**
Yes,I can.

**Are you using the demo app or your own custom app?**
My own custom app.

**If custom app, can you reproduce the issue using our demo app?**
It's troublesome, because I need to play multiple (like 4-20) videos on one page at the same time

**What browser and OS are you using?**
Google, foxes and edge can all reproduce, and safari has fewer gaps.My OS version is 10.14.6, and windows system also has this problem, which seems to have nothing to do with the system.

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
I use web playback.

**What did you do?**

In a page, create 10 players, play,
and printing 'player.getBufferedInfo().video',as shown in the figure below:
![image](https://user-images.githubusercontent.com/49701900/122037502-37ba9600-ce07-11eb-9232-0c0892e15e7e.png)
However, at the same time point, when only the video with multiple gaps is played, there is no gap.
That means the video file is normal, no problem.
I would like to ask, what are the possible reasons for many gaps? Exclude video file exceptions

**Comment by joeyparrish** [comment]
Are you playing individual mp4s?  Or DASH or HLS manifests?

In DASH, there is a feature called periods.  Content in different periods is unrelated, and the player places multiple periods next to each other in the timeline.  If the manifest is inaccurate, this can result in gaps between periods.

In HLS, there is a feature called discontinuities.  Segments on either side of a discontinuity can have discontinuous timestamps.  The player must place them next to one another in the timeline, similar to how DASH periods are done.  But if our information about timestamps is inaccurate, we can once again end up with gaps.

When playing individual mp4s, there is no reason for gaps other than issues with the file itself.  We do not manipulate single mp4s, and instead ask the browser to play them directly with `video.src = mp4Url`.

Does this answer your question?
