### ISSUE TITLE
AirPlay button visible on non-supported browsers

### ISSUE THREAD

**Issue by ProtoScott** [google/shaka-player#3471]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.1.0

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Custom App

**If custom app, can you reproduce the issue using our demo app?**
N/A

**What browser and OS are you using?**
Chrome 91 / Windows

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
```
ui.configure({
            'castReceiverAppId': 'XXXXXX',
            'overflowMenuButtons': ['cast', 'airplay', 'playback_rate', 'quality'],
            'seekBarColors': {
                base: 'rgba(255, 255, 255, 0.3)',
                buffered: 'rgba(0, 154, 218, 0.7)',
                played: 'rgb(0, 154, 218)',
            },
            'controlPanelElements': [
                'play_pause', 'time_and_duration',
                'spacer',
                'mute', 'volume', 'theatre', 'fullscreen', 'overflow_menu'],
            'addBigPlayButton': true
        });
```

**What did you do?**
Open Chrome, observe that the AirPlay button is available (even though this should only be available on Safari)

**What did you expect to happen?**
_airplay: adds a button that opens a AirPlay dialog. **The button is visible only if the browser supports AirPlay.**_

**What actually happened?**
AirPlay button was visible on non supported browser, clicking it provides a console error:
`ERROR TypeError: n.controls.sb(...).webkitShowPlaybackTargetPicker is not a function`

**Comment by michellezhuogg** [comment]
Hello @ProtoScott ,

We should not see the Airplay button in Chrome. You may try the following code to check Airplay support for UI configuration:
```    
// Check AirPlay support
if (window.WebKitPlaybackTargetAvailabilityEvent) {
  config.overflowMenuButtons.push('airplay');
}
```
Please let us know if that works. Thank you!

**Comment by ProtoScott** [comment]
Hello @michellezhuogg 

I agree the AirPlay button should not be seen. The point I was trying to get across is that the shaka documentation states:

> The button is visible only if the browser supports AirPlay.
Reference: https://shaka-player-demo.appspot.com/docs/api/tutorial-ui-customization.html

Whilst the solution you provided may work I believe either the documentation should be update or the shaka code to reflect what the documentation says.

**Comment by theodab** [comment]
This sounds like a bug to me. We hide the fullscreen button when that feature's not available, so I think that hiding the AirPlay button similarly makes sense.
