### ISSUE TITLE
Shaka 2.5.9 disable skip-forward on live HLS when given multiple new fragments?

### ISSUE THREAD

**Issue by KevinEady** [google/shaka-player#3473]
**What version of Shaka Player are you using?** 
2.5.9

**Please ask your question**
In live HLS playback, we noticed that if the player is given **multiple** new fragments in the HLS sliding window (instead of seeing one new fragment every `<fragment duration>` seconds), we see the player ends up **skipping** to more recent fragments in the playlist. Is there a way to not have this behavior, such that the player will continue playback from its current position?

Thanks, Kevin

**Comment by TheModMaker** [comment]
Please provide a sample manifest URL (not just the text).  You can send it privately to <shaka-player-issues@google.com> if you prefer.  Also, does the content play on Safari?  Which browser are you using?

Also, 2.5.9 is fairly old, we just released 2.5.23 and 3.1.1 you should try instead.

**Comment by KevinEady** [comment]
Hi @TheModMaker . Thank you for your help. I have sent an email to the above address with manifest URL and a pre-recorded testing video. Let me know if any additional information is needed.

Thanks, Kevin

**Comment by joeyparrish** [comment]
I believe this could have to do with the size of the seek window.  By default, this is zero for HLS live, which means that seeking is effectively disabled and playback always happens close to the live edge.  I'm guessing based on the symptoms, though I have not reproduced the issue myself yet.

Please try configuring the player with something like this before playback:

```js
player.configure(
    'manifest.availabilityWindowOverride',
    100 /* seconds */);
```

This sets how much the user will be allowed to seek during playback.
