### ISSUE TITLE
Excluding plugins causes build error in the UI files

### ISSUE THREAD

**Issue by hattapoglu-trt** [google/shaka-player#3478]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes.

**What version of Shaka Player are you using?**
3.2.0

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Demo App

**If custom app, can you reproduce the issue using our demo app?**
N/A

**What browser and OS are you using?**
N/A

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What did you do?**
python build/build.py +@complete -@ads

**What did you expect to happen?**
Build succeeded without errors.

**What actually happened?**
The compiler get errors from the UI library as follows:

/Users/username/Desktop/shaka-player/ui/controls.js:13:0: ERROR - [JSC_MISSING_MODULE_OR_PROVIDE] Required namespace "shaka.ads.AdManager" never defined.
  13| goog.require('shaka.ads.AdManager');
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

/Users/username/Desktop/shaka-player/ui/controls.js:16:0: ERROR - [JSC_MISSING_MODULE_OR_PROVIDE] Required namespace "shaka.ui.AdCounter" never defined.
  16| goog.require('shaka.ui.AdCounter');
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by joeyparrish** [comment]
It is not currently possible to exclude ads from the UI, though you can exclude ads from a UI-less Shaka Player.  The UI is not yet as flexible as the rest of the library.
