### ISSUE TITLE
Upgrade guide for 3.1.*

### ISSUE THREAD

**Issue by shanmugapriyak1788** [google/shaka-player#3487]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.12

**Please ask your question**
Can you please provide the upgrade guide to 3.1.*? 
Are there any breaking API changes in it?

**Comment by joeyparrish** [comment]
There are no breaking API changes in v3.1.  Since v3.0, we have kept strict semantic versioning, so there will be no breaking changes until v4.

We will keep this issue open to track reviewing and updating our upgrade docs to make this clear.  Thanks!

**Comment by MilosRasic** [comment]
TextDecoder polyfill needed for pre-Chromium Edge since 3.1.1 might be worth mentioning. Xbox is affected and if you are not calling `isBrowserSupported()` like we don't, it takes quite a bit of time to figure out what went wrong 🙂
