### ISSUE TITLE
Use of usePersistentLicense and linked item "#1956 Persistence license for Live streams"

### ISSUE THREAD

**Issue by hdodev** [google/shaka-player#3490]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes, not directly described.

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes, linked to #1956 Persistent license w/ streaming content enhancement.

**What version of Shaka Player are you using?**
2.5.20

**Please ask your question**
I found "usePersistentLicense" key and tried to use it to reduce my Live license requests, but it has no effect.
So I suppose it's not the way to do this, but maybe it's not available yet? (or maybe I missed something?)
There is also a parallel item related to "play local widevine content offline", but I don't know if this kind of mechansim could be applied to do reduce license request for Live streams. Thanks for your help.

**Comment by TheModMaker** [comment]
The feature in #1956 is not done yet, so you can't get persistent licenses for streaming situations.  You can follow that issue for updates for that feature.  The `usePersistentLicense` configuration is for whether to store the license when storing offline content (see [docs](https://shaka-player-demo.appspot.com/docs/api/shaka.extern.html#.OfflineConfiguration)).  If that is `false`, we won't download the license for offline and fetch one when we try to play.  It doesn't affect streaming playback.

**Comment by hdodev** [comment]
Hello, yes thanks for feedback. OK we'll follow the item.
