### ISSUE TITLE
Tizen 3 - PlayReady - fractals, green screen after pre-roll ad ends and content begins.

### ISSUE THREAD

**Issue by bcupac** [google/shaka-player#3496]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

Yes
**What version of Shaka Player are you using?**
3.1.1

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Custom

**If custom app, can you reproduce the issue using our demo app?**
N/A

**What browser and OS are you using?**
Tizen 3.0

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Samsung UE43MU6102 2017(Tizen 3.0) 
Software Version: T-KTMDEUC-1290.3, BT-S

**What are the manifest and license server URIs?**

sent to mail
**What configuration are you using?  What is the output of `player.getConfiguration()`?**

```
({
	streaming: {
		ignoreTextStreamFailures: true,
		bufferingGoal: 60,
		rebufferingGoal: 3,
		bufferBehind: 30,
		jumpLargeGaps: true,
		stallSkip:  0.1,
		retryParameters: {
			maxAttempts: 10,
			baseDelay: 1000,
			backoffFactor: 1.75,
			fuzzFactor: 0.5,
			timeout: 10000,
		},
	},
	manifest: {
		dash: {
			ignoreMinBufferTime: true,
		},
		retryParameters: {
			maxAttempts: 5,
			baseDelay: 1000,
			backoffFactor: 2,
			fuzzFactor: 0.5,
			timeout: 25000,
		},
	},
	drm: {
		servers: getDrmLicenseServers(),
		advanced: {
			'com.microsoft.playready':{},
		},
		retryParameters: {
			maxAttempts: 5,
			baseDelay: 1000,
			backoffFactor: 2,
			fuzzFactor: 0.5,
			timeout: 10000,
		},
	},
	restrictions: {
		minHeight: 360,
	},
	preferredAudioChannelCount: 6,
});
```

**What did you do?**

Play AVOD Movie that starts with a pre-roll ad.

**What did you expect to happen?**
Smooth playback 

**What actually happened?**

Green screen, fractaled playback after the pre-roll ad ends and content begins.

Seems like the fix for https://github.com/google/shaka-player/issues/2759 is not working on Tizen 3.

**Comment by bcupac** [comment]
This warning triggers:
"Ancestor MP4 box found in the wrong location!  Modified init segment will not make sense!"

**Comment by bcupac** [comment]
When comparing a regular encrypted initSegment and the fake encrypted initSegment, there is a difference in structure.

fake encrypted stsd box contains avc1 and encv boxes, whereas the regular one has only the encv box.

![fakeEncrypted](https://user-images.githubusercontent.com/7647317/124506563-2fcd9080-ddcc-11eb-820b-58994d06794d.png)
![encrypted](https://user-images.githubusercontent.com/7647317/124506569-33611780-ddcc-11eb-9c56-75ca07590a98.png)

**Comment by bcupac** [comment]
Removing the avc1 box on the fake encrypted segment blocks playback, and probably because now it doesen't have the means to decrypt the segment because encv box is fake.

One other thing is that pssh boxes are missing from the fake encrypted segment. Not sure if it matters...

**Comment by joeyparrish** [comment]
> "Ancestor MP4 box found in the wrong location! Modified init segment will not make sense!"

This is concerning.  It is likely the root cause, and indicates that some simplifying assumption we made was not true.  We will need to debug this with your content.

> One other thing is that pssh boxes are missing from the fake encrypted segment. Not sure if it matters...

No, it doesn't.  That is fine.  Some real, encrypted content omits pssh boxes anyway, and only places them in the manifest.

**Comment by bcupac** [comment]
Hi @joeyparrish,

Seems that the manifest expired.
I've sent a new email with a new manifest.

Thanks,

**Comment by bcupac** [comment]
Turns out that was an issue with our DRM config. Closing ticket.
