### ISSUE TITLE
Text segment request get cancelled and never recovers On multiple seek 

### ISSUE THREAD

**Issue by kumarashu123** [google/shaka-player#3499]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
3.1.1

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `master`?**
No

**Are you using the demo app or your own custom app?**
Custom app

**If custom app, can you reproduce the issue using our demo app?**
No, In the demo app i found only one ttml file for the entire content duration

**What browser and OS are you using?**
Chrome - 91.0.4472.114, MAC - Big Sur

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

streaming: {
                rebufferingGoal: 1,
                bufferBehind: 6,
                bufferingGoal: 10,
                durationBackoff: 1,
                ignoreTextStreamFailures: true
}

**What did you do?**

1. playback a content which has multiple text segment
2. Seek +15, 4 - 5 times continuously using
shakaPlayer.getMediaElement().currentTime = shakaPlayer.getMediaElement().currentTime + 15;

**What did you expect to happen?**
I expected the playback to be seeked to the correct duration (this is happening correctly) and the subsequent subtitle should be displayed

**What actually happened?**

1. After seek i dont see the subtitle
2. In the network tab i see the next text segment gets cancelled and subsequent subtitle files are never fetched

**Note** 
**When i changed  ignoreTextStreamFailures: false , text segment request is going and subtitle is getting displayed**

<img width="804" alt="Screenshot 2021-06-30 at 6 44 48 PM" src="https://user-images.githubusercontent.com/10974291/123966733-5017dc80-d9d3-11eb-92c1-7cfdaec235a9.png">

**Comment by avelad** [comment]
Resolved with https://github.com/google/shaka-player/pull/3476 and duplicated of https://github.com/google/shaka-player/issues/3463

**Comment by kumarashu123** [comment]
@avelad thanks! for the quick reply, sorry missed to check same issue is open. Please close this ticket
