### ISSUE TITLE
Switching of video tracks is not smooth (video and audio freezed a very short moment during switching)

### ISSUE THREAD

**Issue by faiyeah** [google/shaka-player#350]
This is a follow up issue in #308.

To reproduce the issue, I am providing 1 sample content:
- https://www.dropbox.com/s/9583c8pta4aow7r/iso_clear.tar.gz?dl=0
 - Content A: Clear DASH content with ISO profile

The Shaka Player which can reproduce the issue:
- http://v1-6-5.shaka-player-demo.appspot.com/

Steps to reproduce the issue:
- Host the content above
- The content contains 3 different video qualities
 - 480 x 270 (500K)
 - 640 x 360 (1M)
 - 1280 x 720 (1.5M)
- Load the player
- Put the mpd URL in "Stream Setup > Custom manifest URL:"
- Leave the field "Stream Setup > Custom WV license server URL: [?]" empty
- Disable the adaptation by unchecking "Stream Info > Enable adaptation?"
 - By observation, it loaded the lowest bitrate (480 x 270) by default with the above contents
- Click "Load Stream"
- Do switching across different qualities in "Stream Info > Available video tracks:"
- Only trigger switch when "Stream Info > Buffered behind:" is larger than "Stream Info > Buffered ahead:"
 - If switching is successful, we should be able to observe resolution changed in "Stream Info > Active resolution:", and the playback should continue, and the playback freeze for a very short moment before it can switch to the desire video tracks.

For more clarification, please definitely let me know.

Ryan Chan

**Comment by TheModMaker** [comment]
In v1, when switching tracks, the default is to clear the buffer.  So when explicitly switching to a new track: it will clear the buffer, enter a buffering state while it downloads the current segment, and then continue once it's downloaded.  In v2, it does not clear the buffer by default (you can still specify whether to do it in the API).

**Comment by tdrews** [comment]
Yes, this is WAI: when you explicitly select a video track, the transition will not be seamless.

**Comment by faiyeah** [comment]
Thanks for your response. So, can I say this is a design limitation in v1, but has been fixed in v2?

Many thanks.

Best regards,
Ryan Chan
- sent from my iPhone

**Comment by TheModMaker** [comment]
This is a limitation of the demo app, which will always clear the buffer.  However, if you use the API, you can specify whether to clear the buffer.

v1: http://v1-6-5.shaka-player-demo.appspot.com/docs/shaka.player.Player.html#selectAudioTrack
http://v1-6-5.shaka-player-demo.appspot.com/docs/shaka.player.Player.html#selectVideoTrack
v2: http://shaka-player-demo.appspot.com/docs/api/shaka.Player.html#selectTrack

**Comment by faiyeah** [comment]
So, does that mean v1 demo app suffer this, because by default it clears it buffer; while v2 demo app does not suffer this, as by default it keeps the buffer?

Many thanks.

Best regards,
Ryan Chan
- sent from my iPhone

**Comment by TheModMaker** [comment]
No, both demo apps do this.

**Comment by faiyeah** [comment]
It is very clear, thanks for the clarification. I would consider this is the limitation of the demo app.

Many thanks.

Best regards,
Ryan Chan
- sent from my iPhone
