### ISSUE TITLE
During resume playback video goes into buffering state and never plays 

### ISSUE THREAD

**Issue by kumarashu123** [google/shaka-player#3500]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.1.1

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**

**Are you using the demo app or your own custom app?**
Custom App

**If custom app, can you reproduce the issue using our demo app?**
In demo app there is no resume option

**What browser and OS are you using?**
Chrome - 91.0.4472.114, MAC - Big Sur

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

streaming: {
rebufferingGoal: 1,
bufferBehind: 6,
bufferingGoal: 10,
durationBackoff: 1,
ignoreTextStreamFailures: true
}

**What did you do?**

Resume a partially watched content 

**What did you expect to happen?**
Resume playback from the last played position

**What actually happened?**

Video entered into buffering state and never recovers

Only the 2 segments from the resume position is seen in the network tab downloaded, followed by the segments from the start.

**For Example:** In the below screenshots I see that that segment no - segment_442.m4a  and  segment_443.m4a are getting downloaded
and subsequently i see that segments from start 1,2,3, ... and so on are getting downloaded. but the video never start playing back

<img width="799" alt="Screenshot 2021-07-02 at 11 08 47 AM" src="https://user-images.githubusercontent.com/10974291/124225948-e9570800-db25-11eb-9810-ee3f7c9832fe.png">

**Comment by TheModMaker** [comment]
What do you mean by "resume"?  Are you talking about setting the initial start time in `player.load`?  When this happens, what is the value is `video.currentTime` and `player.getBufferedInfo()`.

**Comment by kumarashu123** [comment]
@TheModMaker In the shaka-player master i don't see the issue. In shaka-playerv3.1.1 when i took  #3384 PR issue is not reproducible. 

I have a question related to playback time taken by player. was using the shaka-playerv2.5.10 when i updated to shaka-playerv3.1.1 I see playback time has increased.

I am using below streaming config, am i missing any config?

       streaming: {
                    rebufferingGoal: 1,
                    bufferBehind: 6,
                    bufferingGoal: 10,
                    durationBackoff: 1,
                    ignoreTextStreamFailures: true,
                    jumpLargeGaps: false,
                    smallGapLimit: 0.5,
                    startAtSegmentBoundary: false,
                    retryParameters: {
                        timeout: 0, 
                        maxAttempts: 5,
                        baseDelay: 1000,
                        backoffFactor: 3, 
                        fuzzFactor: 0.5
                    }
                }

**Comment by TheModMaker** [comment]
There were many changes internally for v3.0, so there are likely performance differences.  We're working on making some of those things better now.  Unfortunately it is probably some of those changes that made it worse, and there is probably nothing that can be done for now.  We'll continue to try to make the performance better in later releases.

It sounds like your issue is fixed.  Did you have any other problems?

**Comment by kumarashu123** [comment]
@TheModMaker  thanks! for the reply. Yes above issue is resolved.
please close the ticket
