### ISSUE TITLE
On resume playback or start playback multiple video segments is getting cancelled 

### ISSUE THREAD

**Issue by kumarashu123** [google/shaka-player#3501]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
No

**What version of Shaka Player are you using?**
3.1.1

**Please ask your question**
I observed multiple video segments (identical) request are getting canceled and due to this i observed there is a delay in resuming playback.
I have attached screenshot for the above mentioned scenario.
I just wanted to know the reason why so many identical request are getting cancelled ? Has anybody came across the issue

<img width="657" alt="Screenshot 2021-07-02 at 3 03 25 PM" src="https://user-images.githubusercontent.com/10974291/124254435-b2451e80-db46-11eb-8de8-c9363d339390.png">

**Comment by kumarashu123** [comment]
@TheModMaker Can you please clarify above question, why same segments are getting cancelled when i do playback?
Thanks!

**Comment by bmaniar** [comment]
I am also facing a similar kind of issue after updating to v3.1.1. Adding to the issue the player stops playing and gets stuck in the loading state and starts loading segments from the start.

If you require any more details please let me know.

**Comment by kumarashu123** [comment]
@bmaniar so its bug in the v3.1.1, sometimes I see resume playback is working but takes more time to play.
For playback I see there is performance issue in v3.1.1.

**Comment by bmaniar** [comment]
Here we are getting a warning stating that failed to move the playhead to the current time and after this player is stuck in the loading state. 

To change the duration of the video we set the current time on the video element once the player loads, is this the correct way to do it? @joeyparrish @TheModMaker 

![image (7)](https://user-images.githubusercontent.com/10173856/124592667-526ab280-de7b-11eb-8431-46f6ef1512c5.png)
