### ISSUE TITLE
DASH output with CEA-608/708  suffers from decoding error (hardware acceleration enabled)

### ISSUE THREAD

**Issue by wongfei2009** [google/shaka-player#3502]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

Yes.

**What version of Shaka Player are you using?**

v3.1.1.

**Can you reproduce the issue with our latest release version?**

Yes.

**Can you reproduce the issue with the latest code from `master`?**

Yes.

**Are you using the demo app or your own custom app?**

Demo app.

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**

Chrome Version 91.0.4472.114 (Official Build) (x86_64) and macOS 11.4.

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**

Playback a DASH output with CEA-608/708.

**What did you expect to happen?**
Playback correctly, won't stop due to decode error.
 
**What actually happened?**

As soon as, a video segment with H264 emulation start sequence is parsed and then decode. There will be a pipeline decode error and playback stops.  

<img width="1792" alt="Screenshot 2021-06-24 at 5 42 09 PM" src="https://user-images.githubusercontent.com/6023348/124260975-dca4d500-db62-11eb-895e-149865758bff.png">

**Comment by wongfei2009** [comment]
The bug seems to be in sei_processor.js, which should not call removeEmu_  to modify the input buffer directly. Because the modified buffer with H264 emulation start sequence removed will not compliant to H264 syntax. That causes decoding error to hardware decoder (software decoder can tolerate it).

**Comment by TheModMaker** [comment]
Can you provide a sample manifest URL?  It works fine for me with the CEA asset on our demo page.

**Comment by wongfei2009** [comment]
It is because your CEA asset in demo page doesn't actually have any H264 emulation bytes to remove :) i.e. removeEmu_(naluData) always return 0 in your demo asset. I have an asset can hit the issue in 100% manner, but I don't have the content right to share. How can I share the URL with you in private?

**Comment by joeyparrish** [comment]
Anything you share with shaka-player-issues@google.com will not be shared outside the team.  Please reference the issue number in your email to make it easy to find, and then reply here so we know to look for it.  Thanks!

**Comment by joeyparrish** [comment]
@wongfei2009, without content to test, we won't be able to work on this issue right now.  Although this is a high priority issue, I'm going to have to bump this to the v3.3 milestone.  Please let us know when you can share the content privately, so that we can verify the fix and create a regression test.  Thanks!

**Comment by wongfei2009** [comment]
Asset able to trigger this issue has been shared via shaka-player-issues@google.com. 

Thank for the attention.

**Comment by avelad** [comment]
I think the PR https://github.com/google/shaka-player/pull/3610 fixes this!  (@enson-choy)

**Comment by wongfei2009** [comment]
Cool - indeed, this pull request is contributed by my colleague per my
request ;)
