### ISSUE TITLE
player.getThumbnails incorrectly calculates the Y position

### ISSUE THREAD

**Issue by paulJordaan** [google/shaka-player#3511]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.1.1 and master branch 3.2.0-pre

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Custom app

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Chrome + mac OS

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
Tested against 
- https://demo.unified-streaming.com/video/tears-of-steel/tears-of-steel-tiled-thumbnails-timeline.ism/.mpd
- https://dash.akamaized.net/akamai/bbb_30fps/bbb_with_multiple_tiled_thumbnails.mpd

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
Not relevant

**What did you do?**
I've been experimenting with implementing a custom UI that would display the correct thumbnail when scrubbing the seekbar. 
The current logic incorrectly calculates the Y position of the thumbnail in the thumbnail sheet resulting in the incorrect thumbnails being displayed when calling `player.getThumbnails` with the current time.

**What did you expect to happen?**
The correct thumbnail to be displayed for the supplied time.

**What actually happened?**
The `positionY` aka `row` position gets calculated incorrectly. Current implementation uses the following calculation:
```
positionY = (thumbnailPosition % rows) / rows * fullImageHeight;
 ```
 
 For a 4x4 grid of 200X100px
 ```
 [0][1]
 [2][3]
 ```
 
 When calculating the position for thumbnail 1 the position returned would be:
 ```
 positionX = 100;
 positionY = 50;
 ```
 instead of the correct position:
  ```
 positionX = 100;
 positionY = 0;
 ```

I have a PR ready that addresses this bug.

**Comment by joeyparrish** [comment]
We would be happy to review your PR.  Thanks!

**Comment by joeyparrish** [comment]
@avelad, I believe you wrote that thumbnail code, and I have not spent time with those standards.  Does the description here sound correct to you?

> For a 4x4 grid of 200X100px
> 
> ```
> [0][1]
> [2][3]
> ```

If so, I think instead of this:

```js
positionX = (thumbnailPosition % columns) / columns * fullImageWidth;
positionY = (thumbnailPosition % rows) / rows * fullImageHeight;
```

It should be this:

```js
const thumbnailSize
positionX = (thumbnailPosition % columns) * width;
positionY = Math.floor(thumbnailPosition / rows) * height;
```

@avelad, @paulJordaan, do we all agree?

**Comment by avelad** [comment]
@joeyparrish @paulJordaan 
I have created the PR: https://github.com/google/shaka-player/pull/3514

You are right, the logic of the Y calculation was wrong.
