### ISSUE TITLE
During MP4 playback unwanted 'seeking' and 'seeked' events are triggered right after the video has been loaded

### ISSUE THREAD

**Issue by fingerartur** [google/shaka-player#3518]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
3.1.1

**Can you reproduce the issue with our latest release version?**
yes 3.1.1

**Can you reproduce the issue with the latest code from `master`?**
yes 3.2.0-pre (Also I would suggest adding a build script to package.json)

**Are you using the demo app or your own custom app?**
Custom app

**If custom app, can you reproduce the issue using our demo app?**
I don't know, the demo app does not have the necessary logging

**What browser and OS are you using?**
Linux, google chrome

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**
This is not related to manifests, but to plain MP4, I have tried 5 different sources and the player behaves the same every time.

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
default

**What did you do?**

- instantiate shaka
- use shaka to load MP4 video
- make sure it starts playing (unpause / autoplay)

**What did you expect to happen?**
Should play the MP4 source normally

**What actually happened?**
The video plays fine, however unwanted 'seeking' and 'seeked' events were triggered right after the video has been loaded. Also there seems to be an unnecessary 'timeupdate' event but that is a secondary concern.

- video element event: timeupdate 0 ⚠️ probably unwanted
- shaka event: loaded
- **video element event: seeking** ⚠️ unwanted
- video element event: timeupdate 0
- **video element event: seeked** ⚠️ unwanted
- video element event: timeupdate 28.27
- ...

**Comment by joeyparrish** [comment]
We don't control the dispatch of video element events.  We do, however, do things that may trigger certain events.

Timeupdate events are entirely outside of our control.

Seeking is possibly initiated by us.  When you play the mp4, do you use the `startTime` parameter to `player.load()`?  If so, we would be forced to seek to honor that request.  Can you show us how you call `load()`?

**Comment by fingerartur** [comment]
Thank you, you hit the nail on the head, I'm calling load with position 0 `await this.shakaPlayer.load(uri, position)`, which as I now understand forces shaka to seek.

This makes sense, we can close this issue.

I guess I was just confused by the fact that loading HLS and DASH sources in the same way behaved differently and did not trigger seek, however I guess that may be related to how HLS and DASH work compared to MP4.
