### ISSUE TITLE
Handles sleep mode better on Mac

### ISSUE THREAD

**Issue by xhwang-chromium** [google/shaka-player#352]
Repro steps:
1. Start a playback using Widevine on Chrome for Mac
2. Enter sleep mode
3. Wait for a few minutes
4. Exit sleep mode

Observed Result:
Playback stops with "Error code 1002".

Expected Result:
Playback should resume after exiting sleep mode.

**Comment by joeyparrish** [comment]
Error 1002 is because of a failed XHR.  I suspect that the default retry parameters are to blame.  I would guess that this would be resolved if we set the default to at least 2 attempts.  The first request, interrupted by sleep, would fail.  The second request, initiated after wakeup, would succeed.

@xhwang-chromium, can you please test this theory?  Open the [demo app](shaka-player-demo.appspot.com/demo/), then open the JS console.  In the console, run this:

```js
shakaDemo.player_.configure({streaming:{retryParameters:{maxAttempts:2}}});
shakaDemo.player_.configure({manifest:{retryParameters:{maxAttempts:2}}});
shakaDemo.player_.configure({drm:{retryParameters:{maxAttempts:2}}});
```

Then load an asset and repeat your sleep test.  Thanks!

**Comment by xhwang-chromium** [comment]
Thanks joeyparrish for the tips. I tried it but it seems shakaDemo isn't defined:

Uncaught ReferenceError: shakaDemo is not defined(...)

**Comment by joeyparrish** [comment]
What URL are you using?  Are you building and running Shaka locally or using our appspot demo?

**Comment by xhwang-chromium** [comment]
I was clicking the "demo app" link you provided above.

**Comment by joeyparrish** [comment]
I'm sorry, I think I made a mistake in the link.  I edited that comment to correct, but here it is again for convenience:  http://shaka-player-demo.appspot.com/demo/

**Comment by xhwang-chromium** [comment]
Thanks! I tried it. After exiting sleep mode, the video paused for a few seconds, and finally resumes to play. But after a while it stopped again.

So it's improved, but seems still need to polish.

**Comment by joeyparrish** [comment]
Okay, thanks for sanity-checking my guess.  I'm traveling and don't have access to a Mac right now, but we'll try to make time to fix this before we release v2.0.0.  Thanks!

**Comment by TheModMaker** [comment]
Recently we have made some updates to the network stability (#390).  Can you try again from master to see if they fixed your problems?  They helped in my testing.

**Comment by joeyparrish** [comment]
I re-tested this on the nightly build.  Here's what I did:

1. Load [nightly build](http://nightly.shaka-player-demo.appspot.com/demo/) on Chrome on Mac
2. Choose "Sintel 4k" and start playback
3. Wait about 30 seconds
4. Close the laptop
5. Wait 2 minutes
6. Open the laptop

Playback continues, with audio initially playing catching up to a still video frame.  After that, video plays in sync.  (I imagine this catch-up phase has something to do with Chrome's media pipeline on OSX, but it's definitely outside the control of Shaka.)

Playback does not, however, continue to the end of the stream.  At some point, it stops.  Not sure why.  I haven't looked at the Network panel in the developer tools, nor have I tried this with verbose logging.

**Comment by xhwang-chromium** [comment]
Could you please try the latest M52/M53 build which should have a fix
<https://codereview.chromium.org/2072843002> in Chrome on this issue? If it
works well, then this issue should be marked as wontfix :)

**Comment by joeyparrish** [comment]
@ismena, please retest with latest Shaka Player & latest Chrome stable (52).

**Comment by ismena** [comment]
Tried with Shaka nightly build and Chrome 52. Confirm that the issue doesn't repro: after opening the laptop the playback continues and successfully plays to the end.
