### ISSUE TITLE
XML text subtitles (bg)color not applied to doubly nested cues

### ISSUE THREAD

**Issue by david-hm-morgan** [google/shaka-player#3521]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v3.1.1

**Can you reproduce the issue with our latest release version?**
Yes
https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://livesim.dashif.org/dash/vod/testpic_2s/xml_subs.mpd;panel=CUSTOM%20CONTENT;build=uncompiled

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Shaka Demo but also own custom app

**If custom app, can you reproduce the issue using our demo app?**
yes

**What browser and OS are you using?**
Windows 10 & Mac Big Sur
Chrome 91

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**

[Clear] https://livesim.dashif.org/dash/vod/testpic_2s/xml_subs.mpd

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Default configuration

**What did you do?**

Play this stream.
Enable English Captions
View the subtitles rendered at 0h0m1s to 0h0m2s

**What did you expect to happen?**
Should see Blue background Yellow text 
![image](https://user-images.githubusercontent.com/37144605/125459570-e3d390b7-0750-4b13-a323-13c76eeccc0f.png)

**What actually happened?**

White text on black
![image](https://user-images.githubusercontent.com/37144605/125459601-80c45dbe-b041-4744-8a47-7ebaf582efcf.png)

Please assign this to me as I have written a failing UT and have a proposed fix for it.
It is a side effect of changes to XML parsing changes in recent versions.

**Comment by avelad** [comment]
Note: the same issue occurs with font-size

**Comment by david-hm-morgan** [comment]
Hi @TheModMaker 
thanks for the elegant solution to this issue.  I just retested with [the nightly demo](https://nightly-dot-shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://livesim.dashif.org/dash/vod/testpic_2s/xml_subs.mpd;panel=CUSTOM%20CONTENT;build=uncompiled)

I wonder if there is a small tweak needed to deal with the extra piece of background fill that appears to the right of the first of a two line cue.
![image](https://user-images.githubusercontent.com/37144605/140470989-81b25845-7d0c-4c56-b4c8-defbd3d981ad.png)
