### ISSUE TITLE
Subtitle cues nested within a parent cue with infinite time range always displayed regardless of child time ranges

### ISSUE THREAD

**Issue by david-hm-morgan** [google/shaka-player#3524]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v3.1.1

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Both

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Windows 10
Mac Big Sur
Chrome v91

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**

[clear] http://rdmedia.bbc.co.uk/dash/ondemand/elephants_dream/1/client_manifest-snake.mpd
> Note this needs to be played when using demo from localhost as the stream is not https

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Default configuration

**What did you do?**

- Play this stream
- Enable English Captions
- View the subtitles at any point in the stream.

**What did you expect to happen?**
Sentence words appear at intervals according to time cues, when the sentence is complete, it clears and the next sentence appears word by word at the intervals indicated in the stream.

**What actually happened?**
All subtitles dumped on the screen and stay there throughout.

![image](https://user-images.githubusercontent.com/37144605/125613576-31529613-cdc5-4d86-bc62-659895b7ff36.png)

Please assign to me as I have a failing UT and a proposed fix.

**Comment by theodab** [comment]
It looks like we fixed this by accident in https://github.com/google/shaka-player/commit/157bd77be25ea7744d2d905f46dd3ee3eb1a611a. Sorry for not seeing your PR earlier!
