### ISSUE TITLE
Fragment WebM on the fly.

### ISSUE THREAD

**Issue by publicocean0** [google/shaka-player#353]
I saw you are very expert in video webm and mp4.
I ask you for a suggestion. I m going to develop a html page(prototype) in which i load a webm file , it is segmented correctly in chunks (following the webm format matroska)  and passed to MediaSource object for rendering.Does  lib/media/webm_segment_index_parser.js  permit to split file in segments?

**Comment by tdrews** [comment]
Yes, the player supports segmented WebM. However, you must provide the player with a DASH manifest file (i.e., an MPD file). You can create an MPD file from a segmented WebM file using ffmpeg, see http://wiki.webmproject.org/adaptive-streaming/instructions-to-playback-adaptive-webm-using-dash.

**Comment by publicocean0** [comment]
no i mean another thing:
in my case i have to fragmenting webm using javascript on the fly and i pass it directly to Mediasource.

**Comment by tdrews** [comment]
The MPD file specifies the segments' locations.

Normally, a fragmented WebM file is split into an index segment (which contains `<Cues>` data), an initialization segment, and several media segments. The MPD file specifies the URIs of each segment if the segments are split into multiple files, or the byte ranges of each segment if the segments are in one file. lib/media/webm_segment_index_parser.js parses the index segment and initialization segment.

If you want to fragment a WebM file on the fly and feed it into the player you will also need to generate a DASH manifest on the fly and feed it into the player too.

**Comment by publicocean0** [comment]
Thanks for your explanation

**Comment by ockulkarni** [comment]
hey did you find any solution for the on the fly fragmenting file?please do reply(ockulkarni18@gmail.com)

**Comment by JimmyVV** [comment]
if you use mpd files to play webm on dash, the latency is so large. there is some other idea to reduce the latency? not only reduce the length of mpd file. like httpflv, using http chuked to dynamically download mediasegment and play?

**Comment by joeyparrish** [comment]
@JimmyVV, if you have specific issues with latency, please file a new issue.  This issue was closed more than 1.5 years ago, and does not seem to relate directly to latency.  Thanks!
