### ISSUE TITLE
Send Custom Entity to CastReceiver

### ISSUE THREAD

**Issue by stuartflanagan** [google/shaka-player#3535]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.2.0

**Please ask your question**
I would like to send a customUrl or customId to our custom ChromeCast Receiver app.
I have a player working with the ChromeCast proxy but our current receiver expects an API endpoint that it uses to create a playlist and negotiate DRM. Is it possible to modify the current CastProxy to send a different `entity` property to our receiver from the Shaka Player CastProxy?

**Comment by stuartflanagan** [comment]
Checking logs I am seeing:
`"Invalid namespace: urn:x-cast:com.google.shaka.v2"`
Is this indicating that the Shaka Player has to use the Shaka receiver?
Our receiver is using the current `cast-media-player` But we are not setting a custom message name space as suggested above.

**Comment by stuartflanagan** [comment]
I have managed to create a namespace and check the incoming message in the custom receiver.
I can set the AppData with data I need for the API calls too. This helps.
I think this question now comes down to can Shaka Player be used in this way with a custom receiver that does not use the Shaka cast_receiver?

**Comment by joeyparrish** [comment]
You can use your own custom receiver, and custom sender, too, if you like.  Our UI's cast button depends on our CastProxy, and our CastProxy expects our own CastReceiver class on the other end.  So if you're our UI, but not using CastProxy & CastReceiver, you'll want to inject your own cast button into the UI.

We don't really have a way to intercept and interpret the manifest URI, though.  At least, not directly.  You might be able to do it with a request filter on the receiver side, which would block the manifest request until you've done your special negotiation.

Does this help?
