### ISSUE TITLE
Chapters support usage? example?

### ISSUE THREAD

**Issue by hiren3897** [google/shaka-player#3538]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
YES

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
YES

**What version of Shaka Player are you using?**
v3.2

**Please ask your question**

Hello @avelad @joeyparrish.
As the chapter's support has been already released in the shaka-player v3.2. :tada: 

Do we have any tutorials on how to add/get chapters support to the player?

Or do we have to add chapters manually? using addChaptersTrack(uri, language, mimeTypeopt)

And the list of chapters should be present inside the Manifest so that the functions

```
this.player.getChapters('en') 
this.player.getChaptersTracks()
```
will return the list of chapters so that we can use them to populate on the timeline?

Thank you In advance :)

**Comment by avelad** [comment]
I am on vacation until August 8, on my return I can do a tutorial

**Comment by hiren3897** [comment]
Okay @avelad Thank you :)

**Comment by hiren3897** [comment]
Hello @avelad 
I hope you are well and had a great vacation.

Can you please give us the tutorial for chapters usage?

Thank you in advance.

Hav a good day :)

**Comment by avelad** [comment]
This would be an example of use:

```
await player.load(someURL);
await player.addChaptersTrack(chapterURL, 'en');

//Wait 1.5 seconds (approx, browsers need to download url and process it)

const chapters = player.getChapters('en');
```

**Comment by hiren3897** [comment]
Can you please tell me about the `chapterURL`?

What type of URL is it? do we have a defined structure of `chapterURL`? Can you please provide us a sample of `chapterURL`?

**Comment by avelad** [comment]
one example: https://s3.amazonaws.com/demo.jwplayer.com/text-tracks/assets/chapters.vtt

**Comment by hiren3897** [comment]
Thanks,

After we do
```javascript
const chapters = player.getChapters('en');
```

we will have the list of chapters that can be used to populate on the timeline right?

**Comment by avelad** [comment]
Yes, you can see the test in https://github.com/google/shaka-player/blob/master/test/player_integration.js#L926-L949

**Comment by hiren3897** [comment]
Okay, Thank you so much for your help. I will see this with my application and ping you if I have any issues

Have a great day

**Comment by joeyparrish** [comment]
If you need to reopen this issue, just put `@shaka-bot reopen` in a comment.  Thanks!
