### ISSUE TITLE
Subtitles appear as Unrecognized()

### ISSUE THREAD

**Issue by Nimmu93** [google/shaka-player#3539]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.1.1/shaka-player.ui.js

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Own custom app

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
IOS

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
No

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**

**What did you expect to happen?**
Captions Button need to hide if Subtitles are not available.

**What actually happened?**
I'm trying to play a video that doesn't have any embedded subtitles. So the captions button in the overflow menu should hide. That is working fine with chrome. But when try from IOS, the caption menu appears and in the menu, there is a menu item called "unrecognized ()"

![Image from iOS (1)](https://user-images.githubusercontent.com/19269052/126159935-62374825-330c-405a-acf8-317650c32fb9.png)

**Comment by theodab** [comment]
Can you share the content you are using? You can send it to <shaka-player-issues@google.com> if you don't want it to be public. I tried playing our demo content on both iOS Safari and Chrome, and for the reliable only HLS no-captions no-subtitles asset we have right now (the Shaka Player History livestream), I wasn't seeing an erroneous text language selection menus.

**Comment by michellezhuogg** [comment]
Hello @Nimmu93 , are you still having the issue with captions? If not, can we close the issue?
