### ISSUE TITLE
Is it recommended to take v2.5.23-master branch for production release (any master branch)

### ISSUE THREAD

**Issue by kumarashu123** [google/shaka-player#3542]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.10

**Please ask your question**
I wanted to upgrade with shaka player v2.5.23, I see  **Add support for multiple layers of nested cues.** is not present in v2.5.23.
The same **Add support for multiple layers of nested cues.** is present in v2.5.23-master, is it recommended to take master branch v2.5.23.

**Comment by joeyparrish** [comment]
No, the "-master" tags are to indicate where the master branch was at the time of a release from a release branch.  We always recommend official releases from release branches.

Once a branch is created (such as v3.1.x or v3.2.x), only bug fixes are cherry-picked to that branch, and never new features.  This means those branches should only ever increase in stability.  Release tags such as v3.2.0 and v3.1.2 are made from the corresponding release branches.

Once you find the release branch that has the features you need (see CHANGELOG.md), then you should use the most recent release from that branch.

Does this help?

**Comment by kumarashu123** [comment]
Thanks! for the quick reply
I tried upgrading 3.1.1 please see below observation

 I tried playing the same VOD content with Shaka v2.5.10 and v3.1.1, v3.1.2 and found that the video start time is higher in 3.1.1, 3.1.2 compared to 2.5.10.

Same network speed, manifest url and buffering configuration was used for testing the two.

Url used: https://storage.googleapis.com/shaka-demo-assets/bbb-dark-truths/dash.mpd

Statistics:

Network bandwidth at the time of testing: 13Mbps
20 iterations were done
Avg. video start time for 2.5.10 - 2697 ms
Avg. video start time for 3.1.1 - 3090

**Comment by joeyparrish** [comment]
Looks like the same comment you posted in #3508.  Thank you for the report, but let's not mix issues.

Do you have any more questions about releases, tags, and branches?  Or can we close this issue?

**Comment by kumarashu123** [comment]
Thanks! @joeyparrish I don't have any question related to releases
