### ISSUE TITLE
renewal_server_url ignored

### ISSUE THREAD

**Issue by deisenbacher01** [google/shaka-player#3543]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What link can we use to reproduce this?**
https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://wvm.ezdrm.com/demo/dash/BigBuckBunny_320x180.mpd;license=https://widevine-dash.ezdrm.com/clientdebug.aspx?pX=B03B45&customdata=original;panel=CUSTOM%20CONTENT;build=uncompiled

**What version of Shaka Player are you using?**
v3.2.0-uncompiled

**What browser and OS are you using?**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36

**What did you do?**

Played the test stream

**What did you expect to happen?**
Player should read the renewal_server_url and then call that URL for the renewal license,
https://widevine-dash.ezdrm.com/clientdebug.aspx?cd=renew1&rand=58H

**What actually happened?**
 it is calling the base WV Proxy URL and ignoring the renewal_server_url value being passed to the player
calling https://widevine-dash.ezdrm.com/clientdebug.aspx?pX=B03B45&customdata=original

**Comment by joeyparrish** [comment]
> Player should read the renewal_server_url and then call that URL for the renewal license

Where should the player read it from?

**Comment by deisenbacher01** [comment]
This is in the license response,
![renewal](https://user-images.githubusercontent.com/13035052/126817784-1a870cb7-70dc-4139-a248-8be5e6de4145.PNG)

**Comment by joeyparrish** [comment]
The license response is not consumed by the player, but by the CDM.  We don't have access to the fields of a license response.

**Comment by joeyparrish** [comment]
That feature of the Widevine protocol is not available to JavaScript applications running in web browsers.  We apologize for any inconvenience.

**Comment by deisenbacher01** [comment]
But the player can read the response in the HTTP traffic just like the chrome browser is doing, and parse it out. Or are you saying this can only be done in the EXOplayer native app?

**Comment by joeyparrish** [comment]
No, these open-source players do not have the ability to parse the Widevine license protocol.  Android has a native API that exposes these details from the CDM, but browsers do not.

**Comment by deisenbacher01** [comment]
Thank you,
