### ISSUE TITLE
Unable to understand the DRM Server Certificate Request and the Payloads

### ISSUE THREAD

**Issue by WINOFFRG** [google/shaka-player#3546]
**Request 1:** I am trying to debug an application and I found that within few seconds of video playback, 2 differentiable requests are sent from the app. The request is sent to the app backend with my access credentials and query parameters. But I noticed that a 2 Byte data which B64 Encoded or "CAQ=". And this request in response returns something related to widevine licensing.

Here is the screenshot below for reference. 👇

![image](https://user-images.githubusercontent.com/61311751/126861563-304d26cb-a3fb-4673-9415-329fed1c6721.png)

**Request 2:** Once the above request is succeeded, Another request which is exactly the same as above just with a different payload screenshot attached below with Response. I want to ask from where did we got this payload. The first one is considered as it is the same every time. But to receive the actual DRM Licensing which is received from request 2 we need to pass that payload which I am asking. 

![image](https://user-images.githubusercontent.com/61311751/126861774-5721a554-ab55-4498-9c88-9354d7b655b5.png)

**Can anyone please explain to me how do I generate that payload generated to make the actual license request? Moreover, both the requests were made by shaka.js only. I also referred to this [response ](https://github.com/google/shaka-player/issues/2754#issuecomment-665151145) from Joey but he said that we receive that data, And in my case, it is posted.**

**Comment by TheModMaker** [comment]
The first request is a certificate request as explained by Joey in that post.  The second is a license request.  The requests are generated by the browser to request the license; then the license server generates a response that we give back to the browser.  These requests are use to request DRM keys to play protected content.

If you're curious, the request is generated by the browser using [Encrypted Media Extensions](https://www.w3.org/TR/encrypted-media/) API.  The responses are generated (in this case) by the Widevine license server.  The requests are usually sent through a proxy, but is ultimately generated by the Widevine server.

**Comment by WINOFFRG** [comment]
Ok, I understand till here, Talking about the code part. Can you throw some light on it as well, That would be very great as I can them simulate that request. [Here it is](https://shaka-player-demo.appspot.com/docs/api/externs_shaka_player.js.html#line563), What I am referring to till now, I understand the given definition but how do I write the functions and what things other than Server URL are needed to simulate that request.

**Comment by TheModMaker** [comment]
If you just want to play content, you just need to configure the Player, and we'll handle everything for you.  Check out our [tutorial](https://shaka-player-demo.appspot.com/docs/api/tutorial-drm-config.html) for more info.  You only need to set the license server URL and we'll handle everything else.  If your license server wraps the request/response, you may need to set a [network filter](https://shaka-player-demo.appspot.com/docs/api/tutorial-license-wrapping.html).

-----

If you want to manually generate a license request for your own app, you need to use EME as I said.  Our code is a bit complex, so it can be difficult to find the important bits.  [DrmEngine](https://github.com/google/shaka-player/blob/master/lib/media/drm_engine.js) contains the code to make the requests and handle the response.  You can also look at [this EME example](https://www.w3.org/TR/encrypted-media/#example-source-and-key-known), which uses clear-key instead.

The basic idea is to:
1. Call [navigator.requestMediaKeySystemAccess](https://www.w3.org/TR/encrypted-media/#dom-navigator) to get a [MediaKeySystemAccess](https://www.w3.org/TR/encrypted-media/#dom-mediakeysystemaccess) instance.
2. Call `mediaKeySystemAccess.createMediaKeys` to get a [MediaKeys](https://www.w3.org/TR/encrypted-media/#dom-mediakeys) instance.
3. Call `mediaKeys.createSession` to get a [MediaKeysSession](https://www.w3.org/TR/encrypted-media/#dom-mediakeysession) instance.
4. Listen to the `message` event on the session.  This will receive the license request.
4. Call `session.generateRequest` with the init data (usually PSSH data).  Later the session will fire the `message` event.

To be able to play protected content, you then need to send the request to the license server.  The response should be given to `session.update`.  You'll also need to call [video.setMediaKeys](https://www.w3.org/TR/encrypted-media/#dom-htmlmediaelement) after step 2.

**Comment by WINOFFRG** [comment]
Thank You! Understood, Sorry for the late response I was trying to understand more about it, Before I get started with documentation, Could you please answer few more questions mentioned below.

1. To implement this process of EME and DRM Protected content for DASH Streaming which uses the concept of Clear Keys, Apart from the code what things do we need like as much from reading till now I found that we need MPD File, License Url, `initData` which contains the PSSH Data, What else do we need?

2. Could please give me a short difference between Clear Keys, `KID`, `SchemeIdUri `(Talking about that thing which looks like this `urn:uuid:xxxxxxx-xxx....`) Does this `SchemeIdUri `remain constant for all media like something related to server or is it taken from the MPD File?

3. Do we have any assets for testing it and simulating the same process. Like playing a media via **DASH** Process where media is **DRM Protected** and we are given things like **ServerLicense and ServerCertificate**. 

That's it. Sorry, I might sound silly at some points as I am new to this, But a few keywords or articles for reference or where I can practically implement it would be a great help. Thanks a lot for giving time.

**Comment by TheModMaker** [comment]
> Thank You! Understood, Sorry for the late response I was trying to understand more about it, Before I get started with documentation, Could you please answer few more questions mentioned below.
> 
> 1. To implement this process of EME and DRM Protected content for DASH Streaming which uses the concept of Clear Keys, Apart from the code what things do we need like as much from reading till now I found that we need MPD File, License Url, `initData` which contains the PSSH Data, What else do we need?

To just make an EME request, you don't need an MPD file.  That contains the media segment URLs and the init data.  So you could avoid doing all that if you just want to make some requests and have the PSSH data.  To make an EME request, you just need the init data and a license server URL.

> 2. Could please give me a short difference between Clear Keys, `KID`, `SchemeIdUri `(Talking about that thing which looks like this `urn:uuid:xxxxxxx-xxx....`) Does this `SchemeIdUri `remain constant for all media like something related to server or is it taken from the MPD File?

- Clear key is the name of a (mostly test-only) DRM system that uses clear keys for encryption.  These are just AES keys you give to the system as raw hex keys.  That term also can refer to the keys themselves.
- `KID` is the key ID, a unique identifier for which key to use.  This is embedded in the media to determine which key to decrypt with.  The EME API has was to query which keys are available.
- `schemeIdUri` is a constant value used in DASH that is used to determine which DRM system to use.  You can look [here](https://github.com/google/shaka-player/blob/0535e2f35b9c3a4119782abdd6478be76deafb62/lib/util/player_configuration.js#L100) for a list of the supported values in Shaka Player.  You don't need to use this if you are calling EME directly.

> 3. Do we have any assets for testing it and simulating the same process. Like playing a media via **DASH** Process where media is **DRM Protected** and we are given things like **ServerLicense and ServerCertificate**.

You can look at [assets.js](https://github.com/google/shaka-player/blob/master/demo/common/assets.js) for a list of our demo assets.  This includes the license and media URLs.

> 
> That's it. Sorry, I might sound silly at some points as I am new to this, But a few keywords or articles for reference or where I can practically implement it would be a great help. Thanks a lot for giving time.

**Comment by WINOFFRG** [comment]
Thanks a lot for your response.
