### ISSUE TITLE
Testing out Shaka Player with manifests from streaming providers?

### ISSUE THREAD

**Issue by rgainza** [google/shaka-player#3549]
It is definitely a bug in truth, but not as if I get impacted but the Shaka might care.
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes, though I am a big rookie on this.
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes
**What version of Shaka Player are you using?**
3.1.1 Google Chrome 92 WinX64

**Please ask your question**

Is it "okay" to do so to search for upgrades for this project? I've been trying out Shaka with a bunch of manifests (HLS FAIRPLAY/DASH WIDEVINE) to see where it might get a challenge and so I've found some, but no idea if you guys might find it interesting to upgrade Shaka to be more compatible maybe?

**Comment by TheModMaker** [comment]
If you see any problems with your content, feel free to file a bug using the bug template and fill out all the fields.  We'll take a look at why the content doesn't work.  Make sure to provide a playable manifest URL (not the text content) so we can try to play the content.

**Comment by rgainza** [comment]
> If you see any problems with your content, feel free to file a bug using the bug template and fill out all the fields. We'll take a look at why the content doesn't work. Make sure to provide a playable manifest URL (not the text content) so we can try to play the content.

I must have been unclear, sorry about that. In this particular case I'm trying out manifests from the big companies, hence the title of this thread (Amazon Prime, Netflix etc, notice only example). Is it still interesting for Shaka Player team to check why the player fails from other streaming providers rather than from myself? 

I've noticed that dash.js manages to play a lot more dash manifests. The purpose is to hopefully upgrade Shaka to becoming a better player. Or is it in no way doable?

**Comment by TheModMaker** [comment]
First, this would probably be a violation of their terms of service.  Usually these providers require using their player to play their content.  So we won't spend any time to bypassing those requirements.

Secondly, since they can control most pieces of the stack, they don't need to be spec compliant.  I know that YouTube used to use invalid DASH content since they control everything.  So there's a chance that the content may be invalid.

So I don't think it would be worth looking at these kinds of content.  We'll only look at content you control/own.

**Comment by rgainza** [comment]
> First, this would probably be a violation of their terms of service. Usually these providers require using their player to play their content. So we won't spend any time to bypassing those requirements.
> 
> Secondly, since they can control most pieces of the stack, they don't need to be spec compliant. I know that YouTube used to use invalid DASH content since they control everything. So there's a chance that the content may be invalid.
> 
> So I don't think it would be worth looking at these kinds of content. We'll only look at content you control/own.

Yeah, might be that way. It just seemed like an efficient way to test out the capabilities of Shaka. I've seen multiple threads from users that has sent dash manifests from other streaming providers and there has been support for those users right here on Github. So I thought it might be a possibility to fix those bugs. 

That is true, but then again I'm referring to the ones that do comply to the standard. Otherwise I wouldn't notice such a difference between Shaka and dash.js where the latter manages playback better. It would be nice to see this project catch up and broaden it's capabilities.

A sad but understandable judgement. I'll skip reporting the bugs that I've encountered with Shaka then.

**Comment by joeyparrish** [comment]
> I've seen multiple threads from users that has sent dash manifests from other streaming providers and there has been support for those users right here on Github.

Those users generally work for the streaming service providers.  Shaka Player **is** used in many commercial services.

But if you want us to help you play a commercial service's content outside of their service, then we can't help you with that.  Thanks for your understanding!

**Comment by rgainza** [comment]
> > I've seen multiple threads from users that has sent dash manifests from other streaming providers and there has been support for those users right here on Github.
> 
> Those users generally work for the streaming service providers. Shaka Player **is** used in many commercial services.
> 
> But if you want us to help you play a commercial service's content outside of their service, then we can't help you with that. Thanks for your understanding!

Just wanted to add that in those threads there was  **no way** that they work for those streaming operators, but at the same time I can't blame you guys for not having time to througly check everyone's backgrounds before helping them. Also to add. There are projects (on Github) that focus on being to play as much as possible regardless of where the manifest are from so I thought maybe Shaka might gain from that. Thanks for the answers though!
