### ISSUE TITLE
Fast-start when loading another MPD

### ISSUE THREAD

**Issue by aletorrado** [google/shaka-player#355]
I need to be able to start playback quickly after loading another MPD, but Shaka uses the best bandwidth achievable. How can I change this behavior to make it always load a low-bw track at first? Thank you!

**Comment by tdrews** [comment]
Hi, with 058004eb021e626ebeb73eee13d9b8be3e376712 you can re-configure the player with a new AbrManager.
```javascript
player.configure({
  drm: { manager: new shaka.abr.SimpleAbrManager(); }
};
```
This will reset all bandwidth estimations.

**Comment by aletorrado** [comment]
It's basically OK but the correct code is:

```
player.configure({
  abr: { manager: new shaka.abr.SimpleAbrManager() }
});
```

Thank you.

**Comment by joeyparrish** [comment]
Thanks for the correction!  (Original post edited.)
