### ISSUE TITLE
Force shaka-player to always start in the lowest bitrate.

### ISSUE THREAD

**Issue by adgllorente** [google/shaka-player#3550]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
latest

**Please ask your question**
We want to configure shaka-player to always start playback in the lowest bitrate and make time to play faster.

To do this, we have configured these two variables:

- `defaultBandwidthEstimate: 1 // Low value to ensure bandwidth is very low and lowest bitrate is chosen.`
- `switchInterval: 4 // We expect adapting should not occur during first 4 seconds of video playback. Enough to reach rebufferingGoal and start playback.`

However, we have seen, even using the shaka-player demo, that shaka is not starting in the lowest bitrate. It starts in a higher bitrate or switches before reaching the switchInterval value.

Is this behavior correct? How could we configure shaka-player to always start in lowest bitrate?

Thanks.

**Comment by TheModMaker** [comment]
We may be ignoring the `defaultBandwidthEstimate` value if the browser has an API that lets us query the real bandwidth.  One way to do this is to set  the `abr.restrictions` object.  This is a restrictions object that doesn't fail if we can't match anything.  If you set the restrictions to something impossible, we'll pick the lowest bandwidth stream.  Once playback starts, you can set them back to the default.

```js
player.configure('abr.restrictions.maxHeight', 1);

player.configure('abr.restrictions.maxHeight', undefined);  // Reset to default
player.configure('abr.restrictions.maxHeight', Infinity);   // or just infinity
```

**Comment by adgllorente** [comment]
@TheModMaker thanks for the information. We’ve tried to use restrictions and it has worked as expected.
