### ISSUE TITLE
Phrases on the subtitles not displaying properly

### ISSUE THREAD

**Issue by renatosalopes** [google/shaka-player#3552]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
Latest (3.2.0)

**Are you using the demo app or your own custom app?**
Custom app

**If custom app, can you reproduce the issue using our demo app?**
Yes, on "Sintel" at 2:14 the subtitle "A dragon." doesn't rendered at first, on full screen, but I rewind a few seconds and appeared as expected. And at 2:17 "I'm searching for someone." wasn't displayed, without full screen.

**What browser and OS are you using?**
Microsoft Edge 92.0.902.55

**What are the manifest and license server URIs?**
Sent to the email.

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
Sent to the email.

**What did you do?**
Played the movie, watched until missing phrases on the subtitles.

**What did you expect to happen?**
Display all phrases on the subtitles properly.

**What actually happened?**
Sometimes, during a dialog, some sentences are not displayed correctly, either with full screen on or off. Apparently they appear in the HTML (through the browser's developer mode) but they don't actually show up on the screen. This inconsistency was also noticed in some parts of the shaka player demo. After a few seconds backwards it may show up actually.

**Comment by kocoten1992** [comment]
@renatosalopes, have you able to solve this issue ?

I run into it a while ago, my solution (accidentally discoverd) was to put a canvas on top of the subtitle to `force` chrome to render https://github.com/google/shaka-player/issues/3432.

It work for me :shrug: , I hope it work for you too.

**Comment by renatosalopes** [comment]
Hey @kocoten1992, thanks for the suggestion!

I talked to another developer here at the company, he set the z-index at 999 and it worked as expected.

As I didn't see another issue open and I could reproduce this failure in the demo so I thought it was something not cataloged.

Thank you again. I will close the topic.

**Comment by rhyswilliamsza** [comment]
Hello!

I am experiencing the same bug. I've done a bit of investigating, and noticed a few things about affected cues:

1. Frequently, this bug occurs when the endTime of the previous cue is equal to the startTime of the next cue. Perhaps a race condition is present in the chrome rendering library which doesn't re-render the dom if the insertion/deletion happens too quickly in succession?
2. This is irregular and seemingly random. I am not able to reproduce with the same cue repeatedly.
3. This issue appears more frequently when in full-screen mode.

A potential fix may be to prevent adding/removing elements from the dom, and simply updating the text within a core 'subtitle' element. However I'm not convinced that this is an effective way to display captions.

Not sure where to turn to next. Will attempt with the z-index fix :)

**Comment by kocoten1992** [comment]
I'd love to hear more about your experiment!
