### ISSUE TITLE
Destroying UI doesn't remove PIP

### ISSUE THREAD

**Issue by FireMasterK** [google/shaka-player#3553]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.2.0

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Haven't tried

**Are you using the demo app or your own custom app?**
Custom App

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Chromium and Brave, Linux

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
Shouldn't matter

**What did you do?**
- On the demo page, play and video
- Start picture-in-picture mode
- run `document.querySelector("video").ui.destroy()` in the javascript console

**What did you expect to happen?**
The Picture-In-Picture popup to disappear as well.

**What actually happened?**
The picture-in-picture popup stayed, with it being stuck on the last played frame.

**Comment by theodab** [comment]
Seems like a reasonable idea to me.
