### ISSUE TITLE
Mac OS Safari HLS playback does not work (3016)

### ISSUE THREAD

**Issue by jakubvojacek** [google/shaka-player#3554]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.2.0

**Please ask your question**

I have searched the issue list and couldnt find anyone with the same problem - I found issus related to ios or fairplay or wrong content. But I am testing on Mac (big sur) in Safari 14.1.2 with HLS content that I found on shaka player demo page and it works there. The HLS content also works when its just the video with src without shaka player.

Therefore I assume the content is OK and should be playabale via src via shaka player. I used the skeleton demo app from documentation and latest shaka player from cdn. 

For some reason, the playback fails with 3016 as per the screenshot below:

<img width="849" alt="Screenshot 2021-07-28 at 11 29 24" src="https://user-images.githubusercontent.com/3463456/127299111-30784c5d-198b-4611-abe5-dd03b72eac3d.png">

Can you please check the code below, should it work? Am I missing something? I want to play the content via the src option (right now im testing clear hls but the ultimate goal is to have fairplay support). I am sorry if its a duplicate or a stupid question, I just couldnt find the solution anywhere :(

Thank you a lot!
Jakub

```html
<!DOCTYPE html>
<html>
  <head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/shaka-player/3.2.0/shaka-player.compiled.debug.min.js" ></script>
    <script>

const manifestUri =
    'https://storage.googleapis.com/shaka-demo-assets/bbb-dark-truths-hls/hls.m3u8';

function initApp() {
  shaka.polyfill.installAll();

  if (shaka.Player.isBrowserSupported()) {
    initPlayer();
  } else {
    console.error('Browser not supported!');
  }
}

async function initPlayer() {
  const video = document.getElementById('video');
  const player = new shaka.Player(video);

  window.player = player;
  player.addEventListener('error', onErrorEvent);

  try {
    await player.load(manifestUri);
    console.log('The video has now been loaded!');
  } catch (e) {
    onError(e);
  }
}

function onErrorEvent(event) {
  onError(event.detail);
}

function onError(error) {
  console.error('Error code', error.code, 'object', error);
}

document.addEventListener('DOMContentLoaded', initApp);

</script>
  </head>
  <body>
    <video id="video"
           width="640"
           src="https://storage.googleapis.com/shaka-demo-assets/bbb-dark-truths-hls/hls.m3u8"
           controls></video>
  </body>
</html>
```

**Comment by guilleccc** [comment]
Hi jakub, 
I could reproduce this error when I opened your example in a local html file. But before the error you mentioned, I got the following message:
```
Not allowed to load local resource: blob:null/7350b1f9-9c47-4998-b80c-fafeeac8a586
```
So I tried to run this same html file but hosted from a local server (http-server), and that fixed the error to me.

**Comment by joeyparrish** [comment]
Hi @jakubvojacek ,

You should either set the video element's `src` attribute, or call `player.load()`, but not both.  If you're using Shaka Player, `player.load()` will suffice.  If you can set `src` directly without `player.load()`, then you have no need for Shaka Player.

Does this help?

**Comment by jakubvojacek** [comment]
Hello @guilleccc 

thank you, I totally overlooked that you answered (i subscribed to all shaka issues and must have missed this one as i didnt hope for an aswer anymore)

Anyway, I tested the solution to put the file behind webserver and it worked splendidly.

Thanks 👍
