### ISSUE TITLE
API to get live stream position as Date, not relative to video timeline

### ISSUE THREAD

**Issue by aletorrado** [google/shaka-player#356]
Is it possible using Shaka to get the current live playback time, from a live streaming MPD, such as `.timeAsUTC()` of Dash.js?

Thanks!

**Comment by tdrews** [comment]
You can use `player.seekRange().end`. This will give you the effective live-edge in seconds. However, this value will be a number of seconds less than just `now - MPD@availabilityStartTime`. Does that work?

**Comment by aletorrado** [comment]
`.seekRange` doesn't work for me. (Btw, seekRange does not seem to be documented).

I could use the current seek value (for example, getting the HTML Video DOM element, and getting `.currentTime`), but I don't know how to access `MPD@availabilityStartTime` using Shaka either.

**Comment by tdrews** [comment]
If you just need the playhead position then you should use `video.currentTime`; it will correspond to the position in the live stream.

**Comment by aletorrado** [comment]
Nope, I need the real time (UTC) of the playhead, like `MPD.availabilityStartTime+video.currentTime`. But I have no access to the MPD.

**Comment by tdrews** [comment]
Ah, got it. We could add an API for that. You could also try
```javascript
var timeBehindLiveEdge = player.seekRange().end - video.currentTime;
var streamPosition = (Date.now() / 1000) - timeBehindLiveEdge;
```
although, since `player.seekRange().end` is offset a little from the true live-edge, it may not work exactly how you want (seekRange() available from the master branch).

**Comment by aletorrado** [comment]
It may work but it won't be precise. I'm thinking about accesing `.manifest_` to get the availabilityStartTime, but it would be really nice to have `.timeAsUTC()` as dash.js have. Why don't you export the manifest?

**Comment by aletorrado** [comment]
This works great:

`var playHeadDate = new Date(player.manifest_.presentationTimeline.presentationStartTime_*1000 + videoElm.currentTime*1000)`

**Comment by tdrews** [comment]
> Why don't you export the manifest?

Modifications to the manifest by the application could have many unintended consequences.

> `var playHeadDate = new Date(player.manifest_.presentationTimeline.presentationStartTime_*1000 + videoElm.currentTime*1000)`

We could provide an equivalent API for this.
