### ISSUE TITLE
Native iOS player for Safari in web app version

### ISSUE THREAD

**Issue by hiren3897** [google/shaka-player#3565]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
3.2.0

**Please ask your question**
When I run shaka-player on my iOS device (iPhone, iPad)

It is overlapped with the iOS default native controls and I am not being able to use shaka UI in the browser safari or any.

Is there any way to hide or disable the iOS default UI control overlayed on the shaka-player?

**Comment by TheModMaker** [comment]
Remove the `controls` attribute from the `<video>` element; or you can use `video.controls = false` in JS.

**Comment by hiren3897** [comment]
Thanks :tada: it worked
