### ISSUE TITLE
playback error (code 5002) with on-demand profile in shaka player 2.0.0 beta

### ISSUE THREAD

**Issue by ArhiChief** [google/shaka-player#357]
In dashjs 2.1.1, shaka player 1.6.5 both sets of video play without error 5002.

This dataset plays successfully:
succeded_dataset.zip

When i try to play this set of videos, error 5002 appears:
error_5002_dataset.zip

As we need support of multiperiods in our project, we cannot use version 1.6.5 of Shaka Player.
Can you estimate complexity of this bug?
Can you give estimation what is timeframe to fix this bug(how many days)?

I want to post all files here, but they are too large, so, here is links for google drive:

[error_5002_dataset.zip](https://drive.google.com/file/d/0B_9jrmrq02JCM1J5VkxJaDY5TGc/view?usp=sharing)
[succeded_dataset.zip](https://drive.google.com/file/d/0B_9jrmrq02JCai0zTzRtVnVzUnM/view?usp=sharing)

**Comment by tdrews** [comment]
Hi, the issue is the same as #348 (also see #341). We will have a patch up soon.

**Comment by tdrews** [comment]
Hi, we pushed a change to fix #348. Please let us know if that resolves the issue. Thanks.

**Comment by ArhiChief** [comment]
Hi, issue really fixed up! thanks a lot!
