### ISSUE TITLE
Validating the downloaded DASH video file

### ISSUE THREAD

**Issue by olirehacek** [google/shaka-player#3581]
Hello,

Is there any way to get a checksum for the downloaded movie file from the DASH manifest ?

I would love to implement download verification in my app as I have a source file MD5 available.

Thanks :)

**Comment by theodab** [comment]
The DASH specification does not have a checksum field, no. Or at least [the DASH IOP](https://dashif.org/docs/DASH-IF-IOP-v4.3.pdf) doesn't mention anything like that.

**Comment by olirehacek** [comment]
> The DASH specification does not have a checksum field, no. Or at least [the DASH IOP](https://dashif.org/docs/DASH-IF-IOP-v4.3.pdf) doesn't mention anything like that.

Yes. Indeed. 
But the source video and audio files that are linked in the manifest do have an MD5 checksum. Is there any way to access these files stored in the IndexedDB?

**Comment by theodab** [comment]
Ah, I see, I had misunderstood you.

Well, we don't have any interface for loading individual media files from the stored manifests at the moment.
You could instead verify the checksums at download time by registering a response filter (see [the license wrapping tutorial](https://shaka-player-demo.appspot.com/docs/api/tutorial-license-wrapping.html)), that intercepts the media files as they are being downloaded, and verifies them then. You'd just want to watch for responses with the type `shaka.net.NetworkingEngine.RequestType.SEGMENT`.

If that's not the right solution for your use-case, and you absolutely need to be able to get the media files from indexedDB, I could mark this as an enhancement request.
