### ISSUE TITLE
Playback on PlayStation 5

### ISSUE THREAD

**Issue by Beraliv** [google/shaka-player#3582]
Hey!

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

Yes

**Is your feature request related to a problem? Please describe.**

Currently I'm testing `shaka-player` on PS5 and I see `SHAKA_PLAYER_LICENSE_RESPONSE_REJECTED` which probably happens because PS5 doesn't implement `MediaCapabilities.decodingInfo` which shaka tries to use and fails at some point (it's also discussed here – https://github.com/google/shaka-player/issues/2179#issuecomment-824399001)

I checked several streams on https://shaka-player-demo.appspot.com/demo, none of them were working for me

**Describe the solution you'd like**

I want to use `shaka-player` on PS5

PS5 supports:
- DASH manifests
- PS5 supports playready DRM

**Describe alternatives you've considered**

There are several alternatives: hls.js, native API,  maybe something else (I didn't dive it too much)

**Additional context**

**Comment by MilosRasic** [comment]
Shaka works fine on PS5.

We've had a similar problem and it turned out to be due to PS5 PlayReady implementation rejecting licenses from one of our DRM servers when Shaka is set to use temporary licenses.

This fixed the problem for us:
```
	drm: {
		advanced: {
			'com.microsoft.playready': {
					distinctiveIdentifierRequired: true,
					sessionType: 'persistent-license',
			},
		},
	},
```

**Comment by Beraliv** [comment]
> Shaka works fine on PS5.
> 
> We've had a similar problem and it turned out to be due to PS5 PlayReady implementation rejecting licenses from one of our DRM servers when Shaka is set to use temporary licenses.
> 
> This fixed the problem for us:
> ```
> 	drm: {
> 		advanced: {
> 			'com.microsoft.playready': {
> 					distinctiveIdentifierRequired: true,
> 					sessionType: 'persistent-license',
> 			},
> 		},
> 	},
> ```

Ah, okay, I used distinctiveIdentifierRequired, but not sessionType

Let me try it tomorrow

**Comment by Beraliv** [comment]
@MilosRasic  I checked it and seems it's still not working for us

I will have a detailed debugging session on Tuesday, so will leave comments here

**Comment by Beraliv** [comment]
@MilosRasic  Based on what Sony wrote last year, probably that's not enough to make it working

First, we checked it for [shaka-player@3.2.0](https://github.com/google/shaka-player/releases/tag/v3.2.0) but it wasn't working because of `MediaCapabilities.decodingInfo` which is incorrectly polyfilled.

Then we switched to [shaka-player@3.1.1](https://github.com/google/shaka-player/releases/tag/v3.1.1). We activated all logs and looks like everything's fine until [`Updating session`](https://github.com/google/shaka-player/blob/master/lib/media/drm_engine.js#L1358) where it throws the error `Shaka Error DRM.LICENSE_RESPONSE_REJECTED` with or without `distinctiveIdentifierRequired` and `sessionType`

We checked EME request and response and it looks valid from our perspective (as least it's not different from other platforms where we also use DASH + Playready)

**Comment by agajassi** [comment]
> First, we checked it for shaka-player@3.2.0 but it wasn't working because of MediaCapabilities.decodingInfo which is incorrectly polyfilled.

On PS5 I noticed that issue as well and it is same both with 3.2.0 and 3.2.1. _mediaCapabilities.decodeInfo_ function does not exist on PS5. 

Does anybody know if there a workaround for this? I am curious if it is a known issue or needs a separate ticket.

**Comment by velopeshoys** [comment]
Using Shaka 3.1.0 and setting `persistent-license` as `sessionType` seems to fix the problem partially, however when the session is updated the following error  is thrown  `Shaka Error DRM.LICENSE_RESPONSE_REJECTED`.

**Comment by diogoazevedos** [comment]
After an extensive investigation, we found that PS5 doesn't support PlayReady license acknowledge, which causes the CDM to reject the license response. However, by removing the `TrasactionId` from the license response, it should work fine.
