### ISSUE TITLE
Unable to add Headers to Manifest Request

### ISSUE THREAD

**Issue by WINOFFRG** [google/shaka-player#3585]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.1.1

**Please ask your question**

👋🏻 I am trying to add headers when manifest URL is request. But it seems like it has some issue while working with.

**Here is the snippet of Code:** I have made sure that `RequestType` is 0 i.e for `MANIFEST` and that I am registering the `RequestFilter` before loading the `manifestUri`.
 
![image](https://user-images.githubusercontent.com/61311751/130118472-6c6479fb-ba98-44db-9bc1-367c818534c0.png)

**Here is the snippet of Request:** I tried to log the request and I see that it actually added the `headers` in the request object. But if I see the request in Network tab I see that **no such header has been added** which causes my **request to fail**.

![image](https://user-images.githubusercontent.com/61311751/130118864-0c1746b1-3f62-4c3a-a4b0-7fe5824ce86b.png)

**Comment by avelad** [comment]
The header you are trying to add is not allowed to be modified from JS.

See: https://developer.mozilla.org/en-US/docs/Glossary/Forbidden_header_name

**Comment by WINOFFRG** [comment]
Thanks! Understood the obvious reason for this. But then how would I get the manifest URL as website doesn't allow to get it until I add that header. Do you have any idea?

**Comment by joeyparrish** [comment]
Perhaps the service hosting the manifest is intentionally denying you access to their content from a third party site.  This is not something we can help you with.  If you believe you should be able to access the content, try contacting the provider and asking them to allow you access from your site.
