### ISSUE TITLE
Tizen unable to play clear when configured for DRM due to #2620 workaround

### ISSUE THREAD

**Issue by david-hm-morgan** [google/shaka-player#3589]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v3.2.0
(v3.0.11 & v3.1.1 also)

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Own custom demo app at https://otvplayer.nagra.com/demo/content/shakaPlayer/issue2620TizenSideEffect/

**If custom app, can you reproduce the issue using our demo app?**
No because need to customise DRM config

**What browser and OS are you using?**
Tizen Smart TV

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Tizen 3/5/5.5/6

**What are the manifest and license server URIs?**

https://otvplayer.nagra.com/demo/content/bbc/bbc_segmented_snaking_subtitle/dash/ondemand/elephants_dream/1/client_manifest-snake.mpd

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

<details><summary>Click to expand</summary>

```javascript
abr:
bandwidthDowngradeTarget: 0.95
bandwidthUpgradeTarget: 0.85
defaultBandwidthEstimate: 1000000
enabled: true
restrictions:
maxBandwidth: Infinity
maxFrameRate: Infinity
maxHeight: Infinity
maxPixels: Infinity
maxWidth: Infinity
minBandwidth: 0
minFrameRate: 0
minHeight: 0
minPixels: 0
minWidth: 0
switchInterval: 8
useNetworkInformation: true
abrFactory: ƒ ()
drm:
advanced: {}
clearKeys: {}
delayLicenseRequestUntilPlayed: false
initDataTransform: ƒ (a,b,c)
logLicenseExchange: false
preferredKeySystems: []
retryParameters:
backoffFactor: 2
baseDelay: 1000
connectionTimeout: 10000
fuzzFactor: 0.5
maxAttempts: 2
stallTimeout: 5000
timeout: 30000
servers: {com.microsoft.playready: "https://uex3xj0i.anycast.nagra.com/UEX3XJ0I/prls/contentlicenseservice/v1/licenses", com.widevine.alpha: "https://uex3xj0i.anycast.nagra.com/UEX3XJ0I/wvls/contentlicenseservice/v1/licenses"}
updateExpirationTime: 1
manifest:
availabilityWindowOverride: NaN
dash:
autoCorrectDrift: true
clockSyncUri: ""
disableXlinkProcessing: false
ignoreDrmInfo: false
ignoreEmptyAdaptationSet: false
ignoreMaxSegmentDuration: false
ignoreMinBufferTime: false
ignoreSuggestedPresentationDelay: false
initialSegmentLimit: 1000
keySystemsByURI: {urn:uuid:1077efec-c0b2-4d02-ace3-3c1e52e2fb4b: "org.w3.clearkey", urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed: "com.widevine.alpha", urn:uuid:9a04f079-9840-4286-ab92-e65be0885f95: "com.microsoft.playready", urn:uuid:79f0049a-4098-8642-ab92-e65be0885f95: "com.microsoft.playready", urn:uuid:f239e769-efa3-4850-9c16-a903c6932efb: "com.adobe.primetime"}
manifestPreprocessor: ƒ (g)
xlinkFailGracefully: false
defaultPresentationDelay: 0
disableAudio: false
disableText: false
disableThumbnails: false
disableVideo: false
hls: {ignoreTextStreamFailures: false, ignoreImageStreamFailures: false, useFullSegmentsForStartTime: false}
retryParameters:
backoffFactor: 2
baseDelay: 1000
connectionTimeout: 10000
fuzzFactor: 0.5
maxAttempts: 2
stallTimeout: 5000
timeout: 30000
offline: {usePersistentLicense: true, trackSelectionCallback: ƒ, downloadSizeCallback: ƒ, progressCallback: ƒ}
playRangeEnd: Infinity
playRangeStart: 0
preferForcedSubs: false
preferredAudioChannelCount: 2
preferredAudioCodecs: []
preferredAudioLanguage: ""
preferredDecodingAttributes: []
preferredTextLanguage: ""
preferredTextRole: ""
preferredVariantRole: ""
preferredVideoCodecs: []
restrictions:
maxBandwidth: Infinity
maxFrameRate: Infinity
maxHeight: Infinity
maxPixels: Infinity
maxWidth: Infinity
minBandwidth: 0
minFrameRate: 0
minHeight: 0
minPixels: 0
minWidth: 0
streaming:
alwaysStreamText: false
autoLowLatencyMode: false
bufferBehind: 30
bufferingGoal: 10
durationBackoff: 1
failureCallback: ƒ (c)
forceHTTPS: false
forceTransmuxTS: false
gapDetectionThreshold: 0.5
ignoreTextStreamFailures: false
inaccurateManifestTolerance: 2
jumpLargeGaps: false
lowLatencyMode: false
preferNativeHls: false
rebufferingGoal: 2
retryParameters:
backoffFactor: 2
baseDelay: 1000
connectionTimeout: 10000
fuzzFactor: 0.5
maxAttempts: 2
stallTimeout: 5000
timeout: 30000
safeSeekOffset: 5
smallGapLimit: 0.5
stallEnabled: true
stallSkip: 0
stallThreshold: 1
startAtSegmentBoundary: false
updateIntervalSeconds: 1
useNativeHlsOnSafari: true
textDisplayFactory: ƒ ()
```
</details>

**What did you do?**

Player configured for DRM
Play a clear stream

**What did you expect to happen?**
Play clear stream without issue.

**What actually happened?**

3019 error reported
![image](https://user-images.githubusercontent.com/37144605/130221168-ff267ca6-16a1-4e2e-9ff3-7438e6f418ca.png)

Traced this to https://github.com/google/shaka-player/commit/d0da2d49e11a656380662c76c80026a5d99d2e90
where Tizen and Xbox had special case handling added.

**Comment by msavvik** [comment]
It'd seems workarounds are not expecting box other then avc1
https://github.com/google/shaka-player/blob/aded252e40445f4c65565932fb400b35d9a18e59/lib/media/content_workarounds.js#L91

All video content in mpd is avc3
https://otvplayer.nagra.com/demo/content/bbc/bbc_segmented_snaking_subtitle/dash/ondemand/elephants_dream/1/client_manifest-snake.mpd

**Comment by joeyparrish** [comment]
@msavvik, can you send a PR to handle avc3 and its encrypted equivalent?

**Comment by david-hm-morgan** [comment]
Well spotted @msavvik - thanks!
I'll create a PR targetting this.

**Comment by msavvik** [comment]
Will be able to submit PRs once I've cleared it with my organization. In
progress.

czw., 9 wrz 2021 o 17:38 Joey Parrish ***@***.***> napisał(a):

**Comment by joeyparrish** [comment]
@msavvik, we closed this issue with a PR from @david-hm-morgan.  Please see #3625.  But if you want to get permissions from your organization for other contributions in the future, we are always happy to have more people involved.  Thanks!
