### ISSUE TITLE
TextDisplayer is undefined when we try to import shaka-player.ui.debug.js

### ISSUE THREAD

**Issue by yvashar** [google/shaka-player#3592]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?** Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes

**What version of Shaka Player are you using?** 2.5.10

**Please ask your question**

We use TextDisplayer by importing shaka-player.ui.js in our code. But for debugging purpose I tried importing shaka from shaka-player.ui.debug.js but the "textDisplayer of undefined error" is thrown in the console.

 const textDisplayer = function () {
            return new shaka.ui.TextDisplayer(shakaPlayer.getMediaElement(), $("video").parent()[0]); //self._player.video_, self.el);
        };
Printing the shaka object returns an empty function with no ui object inside it.

**Comment by theodab** [comment]
In [this commit](https://github.com/google/shaka-player/commit/562168a1f6cae93f314b748f52e3398568b80bb5), which was part of v2.5.11, `shaka.ui.TextDisplayer` was renamed to `shaka.text.UITextDisplayer`.

So if `shaka.ui.TextDisplayer` exists in one version and not the other... maybe your compiled bundles are from different versions of Shaka Player, or something?

**Comment by yvashar** [comment]
But I don't see shaka.text.UITextDisplayer anywhere in the bundle. it is shaka.ui.TextDisplayer

**Comment by TheModMaker** [comment]
Could you provide a sample page for this?  Looking at the stack trace would also help as this could be a problem with variables being renamed in the compiled bundle.
