### ISSUE TITLE
Firefox not supporting persistent licenses

### ISSUE THREAD

**Issue by sridhard** [google/shaka-player#3593]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
Shaka hosted demo

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
demo app

**If custom app, can you reproduce the issue using our demo app?**
NA

**What browser and OS are you using?**
MAC, Firefox

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
NA

**What are the manifest and license server URIs?**
NA

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
Hosted demo is used

**What did you do?**

Try to download content in firefox browser

**What did you expect to happen?**
Download should work

**What actually happened?**
Download is not working since persistent licenses are not supported.

As per issue #401 firefox support persistent licenses. But not working.

I have checked requestMediaKeySystemAccess in firefox:
config = [{
  "initDataTypes": ["cenc"],
  "persistentState": "required",
  "audioCapabilities": [{
    "contentType": "audio/mp4;codecs=\"mp4a.40.2\"",
    encryptionScheme: 'cenc'
  }],
  "videoCapabilities": [{
    "contentType": "video/mp4;codecs=\"avc1.42E01E\"",
    encryptionScheme: 'cenc'
  }]
}];
var mksa = await navigator.
  requestMediaKeySystemAccess("com.widevine.alpha", config);
JSON.stringify(mksa.getConfiguration());

This config works. But if we add "sessionTypes": ['persistent-license']", then it is not working.

Also in chrome I tested same config with and without "sessionTypes": ['persistent-license']",. In chrome both are working. When we check mksa.getConfiguration(), always it will sessionTypes as temporary only.

In doc https://developer.mozilla.org/en-US/docs/Web/API/MediaKeySystemConfiguration, sessionTypes parameter is not present. But shaka-player code always add "sessionTypes": ['persistent-license'] for persistent licenses. Is it required to add sessionTypes when calling requestMediaKeySystemAccess?

I am not sure about it. But in chrome the  getConfiguration() is always giving sessionType as temporary i thought may be sessionTypes is not required.

**Comment by TheModMaker** [comment]
According to our [support check page](https://shaka-player-demo.appspot.com/support.html), Firefox (91 on Windows) doesn't support persistent licenses.   This is probably a bug in Firefox, or they have removed support for it.  We'll look into it.

**Comment by joeyparrish** [comment]
Last I heard, Mozilla had decided not to support persistent licenses for some reason.  So I believe this is intentional on their part, and that there is nothing we can do about it here other than advocate for them to change their policy.

**Comment by joeyparrish** [comment]
You can file an issue here and ask for their position: https://bugzilla.mozilla.org/

If you do, please link back to it here so we can follow along or participate if needed.  Thanks!
