### ISSUE TITLE
Single component representation with DRM issue

### ISSUE THREAD

**Issue by maxbykov** [google/shaka-player#360]
Hi again,
I've got a feeling that this commit https://github.com/google/shaka-player/commit/50a43ffd551719d6a2b2a6d2ad00973469b4603d broke single representation (audio only/video only) streams.
Sample manifest: https://gist.github.com/maxbykov/9ab6b4cf73ab537ad4b5bdecb4a420b8
The issue might be [here](https://github.com/google/shaka-player/commit/50a43ffd551719d6a2b2a6d2ad00973469b4603d#diff-052c6be0b439274b171a21b6729378b1R443) where if there is no video or audio, corresponding
 `*Capabilities` would be `undefined`and it will result in `DRM.FAILED_TO_CREATE_CDM (Cannot read property 'contentType' of undefined)`

**Comment by tdrews** [comment]
Thanks for the report. We'll take a look.
