### ISSUE TITLE
Mixing different sources

### ISSUE THREAD

**Issue by denissabramovs** [google/shaka-player#3603]
I was looking for a way to mix two video sources.
One live source, h.264 video binary stream coming from websockets connection as chunks.
Another HLS video archive, served over HTTP.
The idea was to load HLS playlist, but when play is pressed, to start playing video from live source (i.e. websockets connection), but when user is requesting video part from the past/archive, then it will switch to HLS mode and work via default mode.
Then if user will move slider to the end/latest, it would automatically switch back to live mode and keep playing video from websockets connection.

Is it doable via current player API?

Thank you.

**Comment by TheModMaker** [comment]
We only support one source at a time.  Plus we only support DASH, HLS, or single file (over HTTP), we don't support websockets.  Switching sources like this would be a really complex thing to do and something we probably won't support.  For this case, I would recommend low-latency DASH or HLS, which will have a similar effect to what you want.
