### ISSUE TITLE
demo error on samsung phone android 11 chrome browser

### ISSUE THREAD

**Issue by ikpark-transbox** [google/shaka-player#3615]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What link can we use to reproduce this?**
https://shaka-player-demo.appspot.com/demo/#audiolang=ko;textlang=ko;videoRobustness=HW_SECURE_ALL;uilang=ko;asset=https://storage.googleapis.com/shaka-demo-assets/angel-one-widevine/dash.mpd;panel=ALL_CONTENT;panelData=drm:WIDEVINE,MP4;build=uncompiled

**What version of Shaka Player are you using?**
v3.2.0-uncompiled

**What browser and OS are you using?**
Mozilla/5.0 (Linux; Android 11; SM-G970N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.166 Mobile Safari/537.36

**What did you do?**
1. opened shaka-demo page on samsung phone S10e(SM-G970N) chrome browser
2. set "DRM > Video Robustness : HW_SECURE_ALL"
3. play "Angel One(multicodec, multilingual, Widevine)"

**What did you expect to happen?**
1. play successfully
2. prevent screen capture from user action like pressing the Power and Volume down buttons

**What actually happened?**
1. video error
2. but DRM and preventing screenshot work successfully on android 7 and 10

![L1-demo-guide](https://user-images.githubusercontent.com/68766027/131634954-bde367da-3c80-4e86-8931-8de592275f2d.JPG)

[media-internal_player-properties.txt](https://github.com/google/shaka-player/files/7089346/media-internal_player-properties.txt)
[media-internals_copy-all-to-clipboard.txt](https://github.com/google/shaka-player/files/7089350/media-internals_copy-all-to-clipboard.txt)
![shaka-demo-error](https://user-images.githubusercontent.com/68766027/131634996-d4dd6eb5-e70d-4c9f-871c-dcd61fe06766.JPG)

**Comment by joeyparrish** [comment]
@ikpark-transbox, this appears to be a content issue or a decoder issue.  We don't control either one.

If the content cannot be decoded, either it is poorly encoded, or the device's decoder is buggy.

Does this help?
