### ISSUE TITLE
Get video and audio samples

### ISSUE THREAD

**Issue by yzalazni** [google/shaka-player#3618]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.2.0

**Please ask your question**
Is there an option to  parse a dash manifest and get the video & audio samples back to the application instead of playing the video on browser?

**Comment by joeyparrish** [comment]
Not exactly, but if you're willing to deal with potential changes to the structure in feature releases, you can use `player.getManifest()` to pull the manifest data.

You could also bootstrap `shaka.dash.DashParser` and use that directly.  It will expect a full `ManifestConfiguration` object and `PlayerInterface` to be provided, and for `configure()` to be called before `start()`.  You'll end up getting the same manifest structure as you would through `player.getManifest()`, but without the need for a video element.

Does this help?
