### ISSUE TITLE
How to skip around video with defined timecodes not using player.load()

### ISSUE THREAD

**Issue by Ben-Chapman** [google/shaka-player#3626]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.2.0

**Please ask your question**
Given a valid timecode for a video, is there a more efficient way to seek to that timecode without a call to `player.load()`?

In my application I have AI-derived attributes for various objects in a video (cat, dog, car, etc) and I would like to be able to skip around the video to view these attributes. So in a single 2:00 video, I might want to skip to 0:21, 0:59, 1:17.

I can achieve this today using player.load() but this reloads/reparses the DASH manifest, and _then_ skips to the provided `startTime`. So it does work, but isn't terribly efficient and results in a user experience of ~0.5 second flash of the posterImage, and then a seek to `startTime`.

Is there a better way to accomplish this?

**Comment by joeyparrish** [comment]
Seeking is done through the video element API:

```js
videoElement.currentTime = 21;
// ...
videoElement.currentTime = 59;
// ...
videoElement.currentTime = 77;
```

See also: https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/currentTime

Does this help?

**Comment by Ben-Chapman** [comment]
Aha! This very much helps, and works perfectly. Thanks @joeyparrish .

**Comment by joeyparrish** [comment]
Happy to help!
