### ISSUE TITLE
The mpd video changed by the server is not applied to the shaka player

### ISSUE THREAD

**Issue by baehongjun0212** [google/shaka-player#3637]
Have you read the Tutorials?
Yes I have read it

Have you read the FAQ and checked for duplicate open issues?
Yes I've read FAQ and couldn't find relevant question. Also looked for duplicate open issues and didn't see any.

What version of Shaka Player are you using?
3.2.0

Please ask your question

The server changed the mpd video, but it is not changed. However, when the cache is clear, the mpd video changes normally.
I added the code below, but the results were the same.
`<meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate"> `
`  <meta http-equiv='expires' content='0'>`
`  <meta http-equiv='pragma' content='no-cache'>`
How can we solve this problem?

**Comment by joeyparrish** [comment]
Those `<meta>` tags only indicate how the HTML page itself should be cached.  The server hosting your MPD decides what HTTP response headers to attach to the MPD, and **those** control how the MPD is cached by the browser.

Are you using a particular CDN or cloud service for hosting, or particular software for a local web server?

**Comment by baehongjun0212** [comment]
> Those `<meta>` tags only indicate how the HTML page itself should be cached. The server hosting your MPD decides what HTTP response headers to attach to the MPD, and **those** control how the MPD is cached by the browser.
> 
> Are you using a particular CDN or cloud service for hosting, or particular software for a local web server?

**Comment by baehongjun0212** [comment]
Thank you for your quick response. I'm using an Apache web server.

**Comment by joeyparrish** [comment]
Here's what I would recommend you read for configuring Apache: https://httpd.apache.org/docs/2.4/caching.html

Hope that helps!
