### ISSUE TITLE
Dimensions of CS Ad are wrong after the first pre roll.

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#3638]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes

**What version of Shaka Player are you using?** 3.2.0

**Can you reproduce the issue with our latest release version?** Yes

**Can you reproduce the issue with the latest code from `master`?** Yes

**Are you using the demo app or your own custom app?** Demo App

**If custom app, can you reproduce the issue using our demo app?** Yes

**What browser and OS are you using?** Chrome 93 macOS 11.5.2

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

They are the video of the demo, in the video I have recorded you can see it.

**What did you do?**

https://user-images.githubusercontent.com/8983024/133556590-e941697a-8099-4c35-8af3-fbf4fccfef46.mov

**What did you expect to happen?**
Dimensions are correct

**What actually happened?**

Dimensions aren't correct

**Comment by theodab** [comment]
Reproduced. Thanks for the report.
This particular bug feels super familiar. I could have sworn I've looked into it before, but it might just be my memory playing tricks on me...
