### ISSUE TITLE
Networking engine does not provide response HTTP status code

### ISSUE THREAD

**Issue by Pavelas** [google/shaka-player#3640]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.2.0

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Irrelevant

**If custom app, can you reproduce the issue using our demo app?**
Irrelevant

**What browser and OS are you using?**
Irrelevant

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Irrelevant

**What are the manifest and license server URIs?**
Irrelevant

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
Irrelevant

**What did you do?**
I was trying to implement "**License Wrapping**", based on the official tutorial, as the result I had the following code:
```js
player.getNetworkingEngine().registerResponseFilter(function (type, response) {
  if (!type == shaka.net.NetworkingEngine.RequestType.LICENSE) return;

  if (response.status === 200) ...One scenario

  if (response.status === 201) ...Another scenario
});
```

Unfortunately, my code did not work and it took some time in order to find out the reason. It seems that _Networking Engine_ does not provide **Response Status** which is weird, because it provides almost all the information.

**What did you expect to happen?**
I was expecting that **response** will include **response.status**.

**What actually happened?**
As I mentioned before, my License Wrapping implementation did not work, because I was not able to compare response.status. I don't know the reason why it was excluded from response object.

**Comment by theodab** [comment]
Yeah, that sounds like a reasonable thing to add to me.
