### ISSUE TITLE
Unable to use thumbnail feature in demo app

### ISSUE THREAD

**Issue by mekptang** [google/shaka-player#3642]
Thumbnail feature cannot enable properly.

**Comment by theodab** [comment]
I'm not entirely sure what you're asking here.
Are you asking for thumbnails to show up in the Shaka UI? If you're interested in that, we are tracking that as issue #3371.
Or is the `shaka.Player.getThumbnails` method malfunctioning in some way for you?

**Comment by mekptang** [comment]
> I'm not entirely sure what you're asking here.
> Are you asking for thumbnails to show up in the Shaka UI? If you're interested in that, we are tracking that as issue #3371.
> Or is the `shaka.Player.getThumbnails` method malfunctioning in some way for you?

I thought the feature has incorporated into the latest version of the demo page. #3371  That's what I'm seeking. Thank you.
