### ISSUE TITLE
TTML subtitles with backgroundImage not shown

### ISSUE THREAD

**Issue by adgllorente** [google/shaka-player#3643]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
Latest

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Demo app

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Chrome + Desktop

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**
Sent to shaka-player-issues@google.com

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
Out of the box

**What did you do?**
I'm playing a stream with TTML subtitles containing a Base64 image.

Our subtitle fragments look like this:

```xml
<?xml version="1.0" encoding="utf-8"?>
<tt xml:lang=""
  xmlns="http://www.w3.org/ns/ttml"
  xmlns:tts="http://www.w3.org/ns/ttml#styling"
  xmlns:smpte="http://www.smpte-ra.org/schemas/2052-1/2010/smpte-tt"
  xmlns:ttm="http://www.w3.org/ns/ttml#metadata">
  <head>
    <metadata>
      <smpte:image xml:id="SMPTE_dvbsub_1" imagetype="PNG" encoding="Base64"><!-- very long Base64 code --></smpte:image>
    </metadata>
    <styling>
      <style xml:id="speakerStyle" tts:fontFamily="proportionalSansSerif" tts:fontSize="0.68c" tts:origin="0% 79%" tts:extent="100% 8%" tts:textAlign="center" tts:backgroundColor="transparent" tts:displayAlign="after" tts:color="white" tts:textOutline="black 2px" />
    </styling>
    <layout>
      <region xml:id="speaker" style="speakerStyle" tts:zIndex="1" />
    </layout>
  </head>
  <body>
    <div>
      <div region="speaker" begin="58815:18:36.900" end="58815:18:38.900" smpte:backgroundImage="#SMPTE_dvbsub_1" xml:id="p_0000"></div>
    </div>
  </body>
</tt>
```

After debugging ttml_text_parse.js my guess is these lines introduced in 3.1.0 are ignoring the cue because it does not have timeAttributes and this is happening because they are nested inside a `div`.

```js
        const hasTimeAttributes =
        cueElement.hasAttribute('begin') ||
        cueElement.hasAttribute('end') ||
        cueElement.hasAttribute('dur');

    if (!hasTimeAttributes && !hasTextContent && cueElement.tagName != 'br') {
      if (!isNested) {
        // Disregards empty <p> elements without time attributes nor content.
        // <p begin="..." smpte:backgroundImage="..." /> will go through,
        // as some information could be held by its attributes.
        // <p /> won't, as it would not be displayed.
        return null;
      } else if (localWhitespaceTrim) {
        // Disregards empty anonymous spans when (local) trim is true.
        return null;
      }
    }
```

**What did you expect to happen?**
Subtitles should be shown.

**What actually happened?**
Subtitles are not shown. It was working in shaka 3.0.13.

**Comment by theodab** [comment]
Reproduced. Thanks for the report, and for your patience with the assets for repro. I'll work on a fix.
