### ISSUE TITLE
It will give error msg Error 6001.why?

### ISSUE THREAD

**Issue by UmeshWOI** [google/shaka-player#365]

**Comment by joeyparrish** [comment]
Error 6001 is 'REQUESTED_KEY_SYSTEMS_UNAVAILABLE', defined in lib/util/error.js and documented at http://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html.  The docs say:

> None of the requested key systems are available. A license server URI is required; so this may also happen if the key systems do not have a license server URI.

I also recommend reading the DRM Configuration tutorial: http://shaka-player-demo.appspot.com/docs/api/tutorial-drm-config.html

Does that answer your question?

**Comment by UmeshWOI** [comment]
Yes,Thank you !!!

-----------------------------------------------
*Umesh Kumath*
Engineer, Software Development
Direct Tel: +91 22 6680 1628
Board Tel: +91 22 6680 1515


201, Tower II,  SEEPZ++, SEZ,
Andheri (East), Mumbai 400 096, INDIA.

www.geemedia.com
