### ISSUE TITLE
[Firefox] - Audio is silent when changing audio language.

### ISSUE THREAD

**Issue by SadiqaliZaveri** [google/shaka-player#3654]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.1.2

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Custom

**If custom app, can you reproduce the issue using our demo app?**
Yes with custom content

**What browser and OS are you using?**
Firefox - Windows / Mac 

**What are the manifest and license server URIs?**
Provided via support email.

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
Provided via support email.

**What did you do?**
Change the audio language

**What did you expect to happen?**
Audio should change to the selected language

**What actually happened?**
The audio is silent.

I noticed that when changing audio in the Firefox browser (V 92.0) the audio stops working. I have tried the same in other browsers and it works fine. I switched on the debug logs and found out that the difference is that the operation is aborted in firefox and in chrome it works properly.

I did try it out on the demo shaka app too with custom content and was able to reproduce the same. The default provided content works properly. Am I missing something?

Attaching a screenshot
Chrome logs
![image](https://user-images.githubusercontent.com/22300204/133982445-5d36dc55-b12a-4e55-a8b2-1d52ec0ed0c6.png)

Firefox logs
![image](https://user-images.githubusercontent.com/22300204/133982582-8b002b4d-5796-4694-b833-5b7c4ad1854f.png)

**Comment by TheModMaker** [comment]
First, you should provide content that has valid CORS headers.  It is especially annoying on Firefox to disable CORS requirements.  Second, I think this is a Firefox bug.  I see we download and buffer audio content; plus the playhead is moving, so it is "playing" the audio (if there was nothing, the video would pause).  Firefox doesn't really offer a way to debug the media pipeline like Chrome does, so we don't have much more info.  Chrome doesn't report any content errors.  My guess is there is something about the content that is either invalid or unsupported and causing it to be ignored.

You could file a bug on Firefox.

**Comment by SadiqaliZaveri** [comment]
Thank you for the reply and sorry for the inconvenience with the CORS issue. 
I have further raised the issue internally in our organization to understand if the content has invalid parts to it, once I receive more information I shall raise it to Firefox if required. I will update here as well.

**Comment by SadiqaliZaveri** [comment]
We have internally solved the issue by fixing the content. The content has been re-transcoded with newer profile settings. Unfortunately, I do not know and cannot retrieve what these new profile settings are 😞. Closing the issue.
