### ISSUE TITLE
How to change subtitle position?

### ISSUE THREAD

**Issue by toschlog** [google/shaka-player#3656]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.1.1

**Please ask your question**
How do I adjust the position of the subtitles?  I'm not using the Shaka Player UI. 

I don't want to mess with individual cues; I just want to change the box into which they're drawn.

**Comment by toschlog** [comment]
I couldn't find anything in ::cue about the position so I ended up modifying the cues directly.  It works like this:

1. Set a cuechange handler for each track in textTracks.
2. On change, loop through the activeCues.
3. If (cue.position === "auto") change it to "start" and set cue.position.

It's not idea, but it works.

**Comment by joeyparrish** [comment]
If you're modifying the cues, you could try subclassing our TextDisplayer implementation and configuring the player to use that.  Your subclass could modify those cues before they are sent to the browser.  This is still not ideal, but it would eliminate the polling mechanism and make sure the changes happen before the cues are rendered.

As an alternative, you could use our UI (or even just the DOM-based TextDisplayer), and have complete CSS control over the box in which the cues are rendered.  Everything would happen in plain DOM.

**Comment by toschlog** [comment]
Joey,

I like the idea of using the DOM-based TextDisplayer.  I think that means adding something to the config like this:

```
    config.textDisplayFactory = () => new shaka.text.UITextDisplayer(videoElement, videoContainer)
```

Is that right?  I have, of course, `videoElement`, but where do I get the `videoContainer`?

And once that works, I think I would do this:

```
    const container = document.getElementsByClassName("shaka-text-container")
```

And then I can do whatever I want with `container.style`.   Correct?
