### ISSUE TITLE
Subtitle alignment issues on latest version

### ISSUE THREAD

**Issue by muqsi** [google/shaka-player#3658]
**What version of Shaka Player are you using?**
Shaka 3.2.0

**Please ask your question**
Subtitles are showing in different positions, few contents are showing the right side of the screen, and a few of them showing in the center. Is there any way to align all the content in the center instead of that different positions?
![Screenshot (2102)](https://user-images.githubusercontent.com/63707516/134487462-4fa5ee07-1849-4fcc-8050-872cf824a115.png)
![Screenshot (2103)](https://user-images.githubusercontent.com/63707516/134487465-4607ea6c-1327-4cad-a7c8-9e485a6342c2.png)

**Comment by joeyparrish** [comment]
Please use our issue template.  You didn't provide enough information for us to answer your question.  We will need some details of the content to explain to you why the subtitles render as they do, as well as information about how you are using Shaka Player (with or without our UI to render those subs).
