### ISSUE TITLE
VOD Playback stuck (Chrome reported page unresponsive) using v2.0.0-beta2 with latest windows chrome browser

### ISSUE THREAD

**Issue by faiyeah** [google/shaka-player#366]
Shaka Player used:
2.0.0-beta2 (2016-05-04)

Chrome version:
Version 50.0.2661.94 m

Test content:
https://www.dropbox.com/s/9583c8pta4aow7r/iso_clear.tar.gz?dl=0

Screenshot of playback stuck:
![stuck](https://cloud.githubusercontent.com/assets/5735739/15041122/2cfd8898-12ec-11e6-9517-c3ff1fec66b8.jpg)

Console log of chrome:
[stuck_10.50.100.161-1462442719916.txt](https://github.com/google/shaka-player/files/250232/stuck_10.50.100.161-1462442719916.txt)

Thanks!
Ryan Chan

**Comment by joeyparrish** [comment]
Thanks for the report.  We'll take a look.
