### ISSUE TITLE
Font size increase for vtt subtitles

### ISSUE THREAD

**Issue by jeev1989** [google/shaka-player#3667]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**  
V3.2.0

**Can you reproduce the issue with our latest release version?** 
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Yes

**If custom app, can you reproduce the issue using our demo app?**
No

**What browser and OS are you using?**
Safari V14.0.1 and OS - MAC OS Big Sur

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
This is the manifest we are using. 

WEBVTT
X-TIMESTAMP-MAP=MPEGTS:297180000,LOCAL:00:00:00.000

 
00:00:00.000 --> 00:00:01.399 line:95%,end size:80% align:center position:50%
...menakluki Vijayanagara, menganggap
keadaan negara lebih...

 

00:00:01.520 --> 00:00:04.280 line:95%,end size:80% align:center position:50%
...penting daripada pembuangan Tenali
dari negara...

 

00:00:04.400 --> 00:00:06.000 line:95%,end size:80% align:center position:50%
...buat masa sekarang. Baginda
bersiap untuk peperangan.

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**
Play a vod content which has vtt subtitles and observe the font size

**What did you expect to happen?**
Font size appears should be normal

**What actually happened?**
Font size appears to be more increase in size than the normal

Earlier we were seeing the normal font size of the subtitle, but now the font size appears to be increased in size.. please find screenshot below.

![Screenshot 2021-09-28 at 11 28 16 AM](https://user-images.githubusercontent.com/3212790/135031546-9b8730b1-8817-4200-8fc7-52e5a0269f87.png)
![Screenshot 2021-09-28 at 11 28 53 AM](https://user-images.githubusercontent.com/3212790/135031575-03fc6d5b-1f6c-4b8d-a226-93bd1c810c34.png)

**Comment by joeyparrish** [comment]
What versions of Shaka Player are you comparing (old, smaller font vs new, bigger font)?

Are you using the Shaka Player UI, or the browser's built-in controls?

**Comment by jeev1989** [comment]
We are using the same Shaka Player version for comparing the same. - V3.2.0

We are using the browser's built in controls here.

**Comment by joeyparrish** [comment]
If you're using the browser's controls, you're seeing the browser's rendering of the subtitles.  We don't actually control that unless you're using our UI.

If the player version didn't change, but one day the font size changes, it's the browser that was updated and changed the rendering.

You can influence the size of browser-native cues with the [CSS pseudoclass `::cue`](https://developer.mozilla.org/en-US/docs/Web/CSS/::cue).

The other thing that changes the cue size is the VTTCue field `size`, which we set in the player.  This is only implemented on some browsers, though, and may be ignored by others.

Does this answer your question?

**Comment by joeyparrish** [comment]
If you're using the browser's built-in controls, we are not in control of rendering.  That is the handled by the browser without our involvement.

I noticed you mentioned Safari on macOS, specifically.  The font size on Safari on macOS may be influenced by your OS settings: https://support.apple.com/lv-lv/guide/mac-help/mh43180/mac

I hope this helps!
