### ISSUE TITLE
No bitrate adaptation with recent Shaka Player v2.0.0-beta2 and manifests from Wowza

### ISSUE THREAD

**Issue by BucherTomas** [google/shaka-player#367]
One of the recent commits, sometime between Shaka Player v2.0.0-beta and Shaka Player v2.0.0-beta2, seems to have disabled bitrate adaptation with manifests provided by Wowza. Should be reproducible with http://w01.quickmedia.tv/mbr/x/manbeast/manbeast.smil/manifest.mpd .

With enabled logging by using the 'vv' URL parameter, the console log in Chrome keeps repeating "Still within switch interval..." and no bitrate adaptation takes place. On the other hand, default multi bitrate content such as "Car" properly reports in console debug log

Calling switch_()... bandwidth=9571 kbps
switch_
switch: Stream (audio:8) already active
switch: switching to Stream (video:1)

and the player switches to higher video bitrate.

Multi bitrate content from Wowza used to work fine until Shaka Player v2.0.0-beta, still can be confirmed when using http://v1-6-5.shaka-player-demo.appspot.com/

**Comment by BucherTomas** [comment]
Actually, after some further testing, this appears to be caused by bandwidth estimation.

If I have ample bandwith available and the chunks are delivered very quickly, the bitrate adaption event is not even triggered and the playback is stuck on the first video track with the lowest quality. However, if I saturate my download speed to the max with some bandwidth-hungry connection like downloading a big file, bitrate adaptation suddenly starts working.

That is also possibly why the bitrate adaptation works for me with default content from Shaka demo as the delivery is a bit slower due to geographical distance to my location, but the connection between our local Wowza server and me is fast and this leads to some likely faulty bandwidth estimation. This also means that my manifest example will not likely exhibit the same behavior, say, in the US, and it might not be reproducible there.

Still, this needs to be influenced by a recent commit, as older Shaka versions behave properly in this regard.

**Comment by joeyparrish** [comment]
Can you try reverting a commit for me locally to see what happens?  I'm suspicious of 60d2944.

**Comment by BucherTomas** [comment]
Yes, that was exactly it. After I reverted the commit, bitrate adaptation started to work from our server as usual. Good call, Joey.

**Comment by joeyparrish** [comment]
Okay, then I'll go ahead and revert that commit and reopen the bug it was supposed to fix.  Thanks for testing!
