### ISSUE TITLE
Avoid 6008 error when detecting licenser response is ko

### ISSUE THREAD

**Issue by hdodev** [google/shaka-player#3671]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.21

**Please ask your question**
I have a custom license response (DASH-WIDEVINE) that I have to unwrap before giving it back to Player (managing response.data in player.getNetworkingEngine().registerResponseFilter).

But when I detect the response is invalid and so that I know playback will not be possible, I make a player.unload(), that seems to work, but in any case it triggers the onError() function and 6008 is raised. Is there another way to stop properly the Player in that case? Or to says to it to not wait for a response anymore?

The goal is to avoid the analytics player trackers, that listen and report every Player errors, to pollute the metrics, because  finally it's not an error relative to Player itself.

Thanks in advance for your help.

**Comment by joeyparrish** [comment]
[Error 6008 is LICENSE_RESPONSE_REJECTED](https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html#value:6008).  This means you fed some data back to DrmEngine that was not valid.

I would suggest that you try something like this (untested) code below.  In the error case of your response handler, you can use a delay to try to make the cancelation happen before the invalid response is returned.

```js
  if (invalid) {
    response.data = '';
    player.unload();
    // Block the response for 100 ms so that unload() can start tearing down internal components.
    // By the time DrmEngine receives this response, it should be in a state to ignore it.
    return new Promise((resolve) => setTimeout(resolve, 100));
  }
```

Does this help?

**Comment by hdodev** [comment]
I've just tried and it seems to work fine. Thank you very much!
Just to be sure, the 100ms delay, can it depend of the device performance? I mean should I adapt this if I want to anticipate the clean unload can take more? Or maybe put the return on the promise of the unload ()?
