### ISSUE TITLE
Play the next audio file without refreshing the page

### ISSUE THREAD

**Issue by EvgeniiKuznetsov** [google/shaka-player#3672]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.2.0

Sorry for my question, but how can I play the following audio file without reloading the page or re-init player? The first audio file is received at the first initialization of the player, but what to do next? After all, i can't just set new manifestUrl with dash.mpd to player.load() and hoping that it will start playing the next audio file from new dash.mpd.

This problem applies to those cases when the first player.load(assetsurl) was launched, but the user abruptly wanted to include the next audio file.

**Comment by joeyparrish** [comment]
> After all, i can't just set new manifestUrl with dash.mpd to player.load()

In fact, you can!  That's exactly what you should do.
