### ISSUE TITLE
Native Windows support for Widevine and screen capture prevention with September update - detection with probeSupport

### ISSUE THREAD

**Issue by jakubkrolikowski** [google/shaka-player#3679]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
3.1.x, 3.2.x

**Please ask your question**

After one of the Windows 10 updates in September (I'm not sure which one exactly) there is a very important change in a native support of screen capture prevention. Now videos encrypted with Widevine cannot be captured with Chrome or Firefox - screenshot is just a black frame. Before it used to work like this only with Edge and Playready.
For me this is crucial. I can finally deliver HD video on Chrome because screen recording with popular software is not that easy anymore.

I cannot find any official information about this change and fix.  Does anybody know what exactly Microsoft did in September? Do they provide a native Widevine decryption module?

And the most important: can I detect with shaka.Player.probeSupport() (or another way) if the screen capture is prevented by Windows nativly?

**Comment by joeyparrish** [comment]
> I cannot find any official information about this change and fix. Does anybody know what exactly Microsoft did in September? Do they provide a native Widevine decryption module?

I don't know about this.  I suggest you [contact Widevine](https://widevine.com/contact) about this.

> And the most important: can I detect with shaka.Player.probeSupport() (or another way) if the screen capture is prevented by Windows nativly?

Unfortunately not.  The browser doesn't provide us with any information about this in JavaScript.
