### ISSUE TITLE
[v2.x] Do not abort on unsupported application/* subtitles Representation

### ISSUE THREAD

**Issue by mctep** [google/shaka-player#368]
Hello!

I have a manifest with an adptation set like this:
```xml
...
<AdaptationSet group="4" mimeType="application/ttml+xml" lang="eng">
  <Role schemeIdUri="urn:mpeg:dash:role:2011" value="subtitle"/>
  <Representation id="sub-0k" bandwidth="138">
    <BaseURL>f03734acf69029d8377c01802b3bc649_8b90ec9cz-sub-0k.ttml</BaseURL>
  </Representation>
</AdaptationSet>
...
```

Shaka v2 throws an error at https://github.com/google/shaka-player/blob/acfb7c6d41f524eb7bd57951729039f95b460262/lib/dash/dash_parser.js#L1001

Shaka v1 works perfectly with this manifest.

**Comment by joeyparrish** [comment]
I suspect the issue is caused by https://github.com/google/shaka-player/blob/acfb7c6d41f524eb7bd57951729039f95b460262/lib/dash/dash_parser.js#L723

We'll see what we can do.  Thanks!

**Comment by tdrews** [comment]
With fe9189e, the player will still require text Representations to specify their content type, but it will not fail playback if they do not.
