### ISSUE TITLE
Subtitle with an unexpected behavior

### ISSUE THREAD

**Issue by muqsi** [google/shaka-player#3683]
**What version of Shaka Player are you using?**
Shaka 3.2.0

**Please ask your question**
Subtitles showing with one overlying background. Is there any way to handle this overlying background?

![IMG_20211006_205715](https://user-images.githubusercontent.com/63707516/136236967-3c8e368c-cae0-4785-b21e-e31fd4396592.jpg)

**Comment by avelad** [comment]
Can you put the subtitle file here? Is it a ttml file?

**Comment by joeyparrish** [comment]
@muqsi, without details on your content, we can't help you with this.  Please file an issue using our bug report template, so that we can capture enough information to help you: https://github.com/google/shaka-player/issues/new/choose
