### ISSUE TITLE
Questions and Feature Request ----> Support MOV video files playback and/or live transcoding

### ISSUE THREAD

**Issue by inglesuniversal** [google/shaka-player#3684]
Is it possible to play MOV files on Chrome and non-Safari Browsers?

Best regards

Great project!

**Comment by joeyparrish** [comment]
No, sorry.  We can only play the container formats that the browser supports, except in the case of using mux.js to support the hopefully-soon-to-die-on-the-web MPEG-TS format.

I would suggest that if you want to play MOV, you can easily convert them to DASH or HLS or both using Shaka Streamer: https://github.com/google/shaka-streamer#readme  I would be happy to take questions over there if you need help using it.

I'm going to close this as "infeasible" for the player, but if you need to reopen this issue, just put `@shaka-bot reopen` in a comment.  Thanks!
