### ISSUE TITLE
Shaka Player canvas drawimage() is not working on webOS

### ISSUE THREAD

**Issue by baehongjun0212** [google/shaka-player#3687]
**Have you read the Tutorials?**
Yes

**Have you read the FAQ and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.2.0

**Please ask your question**
Shaka Player canvas drawimage() is not working on webOS.

mac used Chrome 94.0, WebOS 79.0, and Samsung Browser 69.0.
In mac, draw images are good with video elements, but Chrome 79.0 and 69.0 are black screen canvas.

Do you know how to draw an element of video on canvas?

```html
<div>
        <textarea id="user_Agent" rows="1" cols="110" readonly>user agent</textarea>
        <br>
        <video class="videosample2" id="videosample2" width="500px" height="300px" type="video/mp4" controls webkit-playsinline></video>
        <button id="button1" onclick="btn_click();" style="background: slategray; height: 50px; width: 200px;">버튼</button>
        <p>Clicks: <a id="clicks">0</a></p>
        <canvas id="main-canvas" width="500px" height="300px" style="float:left; border: 3px solid blue;"></canvas> 
    </div>
```

```js
var video = document.getElementById("videosample2");
var canvas = document.getElementById("main-canvas"), context = canvas.getContext("2d"); 
const user_Agent = document.getElementById('user_Agent');

window.onload = function(){
  user_Agent.innerHTML = navigator.userAgent;
}

var clicks = 0;

function btn_click() { 
  clicks += 1;
  document.getElementById("clicks").innerHTML = clicks;
  video.play();
  video.addEventListener('play', function() {
    (function loop2() {
        context.drawImage(video, 0, 0, canvas.offsetWidth, canvas.offsetHeight);
        window.requestAnimationFrame(loop2); 
    })();
  }, 0);
}
```

**Comment by joeyparrish** [comment]
Sounds like an issue with WebOS and Canvas rather than the player.  We don't do anything with Canvas, and anything you do to copy video to a canvas should be the same whether you're using Shaka and DASH or a plain mp4 in a `<video>` element with no player at all.

The only thing I can think of that may cause issues is DRM.  Are you trying to copy the frames of encrypted content?  If so, some browsers or DRM systems may have restrictions on that.
