### ISSUE TITLE
With live streaming, shaka keeps refreshing previous manifest

### ISSUE THREAD

**Issue by aletorrado** [google/shaka-player#369]
After switching between different live streaming manifests using `player.load('manifest.mpd')`, shaka keeps fetching previous manifests indefinitely.

**Comment by tdrews** [comment]
Sounds like a caching issue.

What exact sequence of events are you following? E.g.,
1. `player.load('manifest.mpd');`
2. Pause video
3. Change manifest.mpd
4. `player.load('manifest.mpd');` ?

Does disabling browser caching work? (Network tab in Developer tools.)

**Comment by aletorrado** [comment]
Ok I got it. It's happening because on every player.load call, I'm doing this:

```
player.configure({
	abr: { manager: new shaka.abr.SimpleAbrManager() }
});
```

Now I'm doing abr.stop() on the previous abr instance to avoid this problem.

**Comment by tdrews** [comment]
Ah, good catch. I see the problem in player.js now.

**Comment by joeyparrish** [comment]
@aletorrado This should be fixed in `master` now.  Please retest and let us know if the fix is working for you.
