### ISSUE TITLE
MediaCapabilities.decodingInfo() failed on safari while playing DRM protected content using fairplay

### ISSUE THREAD

**Issue by tkayage** [google/shaka-player#3694]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
3.2.0

**Please ask your question**

I have been trying to play hls content which is DRM protected on safari. I have followed the guide on how to configure fairplay DRM but im still unable to play the content. I enabled the debug version for library. So far these are the logs seen on console:

[Info] Using native ARIAMixin interface. (db7b53cd-5bbeb2013817f7bbf06f.js, line 1)
[Log] mathRound.install (db7b53cd-5bbeb2013817f7bbf06f.js, line 1)
[Log] MediaSource.install (db7b53cd-5bbeb2013817f7bbf06f.js, line 1)
[Info] Patching Safari 13 MSE bugs. (db7b53cd-5bbeb2013817f7bbf06f.js, line 1)
[Info] Using Apple-prefixed EME (db7b53cd-5bbeb2013817f7bbf06f.js, line 1)
[Log] VideoPlayPromise.install (db7b53cd-5bbeb2013817f7bbf06f.js, line 1)
[Info] Using native VTTCue. (db7b53cd-5bbeb2013817f7bbf06f.js, line 1)
[Log] MediaCapabilities: install (db7b53cd-5bbeb2013817f7bbf06f.js, line 1)
[Log] MediaCapabilities: Native mediaCapabilities support found. (db7b53cd-5bbeb2013817f7bbf06f.js, line 1)
[Debug] EmeEncryptionSchemePolyfill: Already installed. (db7b53cd-5bbeb2013817f7bbf06f.js, line 1)
[Debug] McEncryptionSchemePolyfill: Already installed. (db7b53cd-5bbeb2013817f7bbf06f.js, line 1)
[Info] Starting attach... (db7b53cd-5bbeb2013817f7bbf06f.js, line 1)
[Info] Starting load of ---LINK--- ... (db7b53cd-5bbeb2013817f7bbf06f.js, line 1)
[Info] MediaCapabilities.decodingInfo() failed. (2) (db7b53cd-5bbeb2013817f7bbf06f.js, line 1)
"{\"type\":\"media-source\",\"video\":{\"contentType\":\"video/mp4\",\"width\":1,\"height\":1,\"bitrate\":100,\"framerate\":1},\"keySystemConfiguration\":{\"keySystem\":\"com.apple.fps.1_0\",\"initDataType\":\"cenc\",\"persistentState\":\"optional\",\"distinctiveIdentifier\":\"optional\",\"sessionTypes\":[\"temporary\"],\"video\":{\"robustness\":\"\"}}}"TypeError: Type error — db7b53cd-5bbeb2013817f7bbf06f.js:1:119173
[Log] The video has now been loaded! (877-b327eeb19b05c9e52e4c.js, line 1)

Browser version: Safari 15.0
Mac OS Big Sur 11.6

**Comment by theodab** [comment]
Yes, that seems to be the case. @tkayage, if you get the latest code from master, is the problem fixed?

**Comment by tkayage** [comment]
> Yes, that seems likely. @tkayage, if you get the latest code from master, is the problem fixed? A fix for #3530 was pushed just a few hours ago.

Checking that out @theodab
