### ISSUE TITLE
Captions showing with a transparent container. 

### ISSUE THREAD

**Issue by muqsi** [google/shaka-player#3699]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v3.2.0

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Both

**If custom app, can you reproduce the issue using our demo app?**
In the demo app, I can reproduce this issue

**What browser and OS are you using?**
Chrome with Windows

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
NA

**What are the manifest and license server URIs?**

Clear stream for testing: https://akm.cdn.intigral-ott.net/VOD/M0004404_T2/M0004404_T2.ism/manifest.mpd

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Demo App default config

**What did you do?**

Play the manifest (https://akm.cdn.intigral-ott.net/VOD/M0004404_T2/M0004404_T2.ism/manifest.mpd), Continue the playback with captions, there you can see the problem.  Eg: around three minutes you can see that the captions come with a container. Not all the text contents but some specific text comes with a black transparent container( Refer to the attachments ) . In the older shaka version, I didn't notice these issues.

**What did you expect to happen?**
Caption/Subtitle without the container.  

**What actually happened?**

![Screenshot (2179)](https://user-images.githubusercontent.com/63707516/137441148-d9d3b456-609f-41c3-8457-571d73d02df0.png)

![Screenshot (2178)](https://user-images.githubusercontent.com/63707516/137441142-ee6a2af1-b645-44a8-9661-572851bfe1d8.png)

**Comment by theodab** [comment]
I'm getting an error when I try to load your sample content.
```
<HTML><HEAD>
<TITLE>Access Denied</TITLE>
</HEAD><BODY>
<H1>Access Denied</H1>
 
You don't have permission to access "http&#58;&#47;&#47;akm&#46;cdn&#46;intigral&#45;ott&#46;net&#47;VOD&#47;M0004404&#95;T2&#47;M0004404&#95;T2&#46;ism&#47;manifest&#46;mpd" on this server.<P>
Reference&#32;&#35;18&#46;4769c317&#46;1634285442&#46;631220aa
</BODY>
</HTML>
```
