### ISSUE TITLE
Subtitle track changed but deselected track remain on screen

### ISSUE THREAD

**Issue by david-hm-morgan** [google/shaka-player#3701]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What link can we use to reproduce this?**
https://v3-1-3-dot-shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://livesim.dashif.org/dash/vod/testpic_2s/img_subs.mpd;panel=CUSTOM%20CONTENT;build=uncompiled

**What version of Shaka Player are you using?**
v3.1.3-uncompiled
Also v3.2.1

**What browser and OS are you using?**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36

**What did you do?**

Play stream and pause
Enable subtitle track
Enable another subtitle track
Enable another subtitle track

**What did you expect to happen?**
Only one subtitle track is shown at a time.

**What actually happened?**

Deselected tracks' content remains on screen.

<img width="1128" alt="Screenshot 2021-10-16 at 11 59 58" src="https://user-images.githubusercontent.com/37144605/137584722-ff23a378-6cc4-4c00-ba91-887afa682171.png">

**Comment by avelad** [comment]
@theodab , resolved with https://github.com/google/shaka-player/commit/4bdd3bb65a62df3ca91dc340cac5b5d699b56b9c

**Comment by theodab** [comment]
Ah, I hadn't seen these. Thanks for the heads-up!
