### ISSUE TITLE
Changing video current play time

### ISSUE THREAD

**Issue by WINOFFRG** [google/shaka-player#3711]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.2.0

**Please ask your question**
Hello! I am trying to create custom buttons that are able to skip a video `±X` time. So, for that, I decided to look into the existing rewind/forward button.  Upon checking I found that they just changed the `trickPlay` rate. Trick play internally had a [`playRateController`](https://github.com/google/shaka-player/blob/master/lib/media/play_rate_controller.js)  which has some private methods to set the rate. 
At this part, I got a bit confused on how to reuse this existing play rate controller to just skip the video `±X` seconds. 

Later, I found that on the `video` tag object we have a method named `currentTime` and upon changing its value I was able to update the current play time. 

**So, is there any way I could reuse the existing `playRateController` to update the current play time? If not, then is it okay to update the `currentTime` in the new button using the second way as I explained above?** :)

**Comment by TheModMaker** [comment]
`PlayRateController` is an internal component and shouldn't be used by apps.  Trick play is fast forward, which controls the playback rate, not directly the current time.  For positive playback rates, you can just set the `video.playbackRate`; for rewind (or fast forward if you want), you can use `player.trickPlay(2)`.

The correct way to change the current time is setting `video.currentTime`.  For example:

```js
myButton.addEventListener('click', () => {
  video.currentTime += 10;
});
```
