### ISSUE TITLE
MEDIA_ELEMENT_ERROR: Format error 

### ISSUE THREAD

**Issue by hiren3897** [google/shaka-player#3722]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
latest v3.1.2
**Please ask your question**
I have created a plugin that fetches our clients URLs and returns various mp4 VOD URLs.
when I do `player.load(myplugin:http//url, null, "video/mp4")` it throws 3016 error as "MEDIA_ELEMENT_ERROR: Format error"

I have rechecked that the mp4 video URLs are of type MPEG-4 

can you please help me to resolve this?

Thanks in advanced.

**Comment by michellezhuogg** [comment]
Hello @hiren3897 ,

If you got and "VIDEO_ERROR" with code 3016, it means the video element reported an error. 
error.data[0] is a MediaError code from the video element. On Edge, error.data[1] is a Microsoft extended error code in hex. On Chrome, error.data[2] is a string with details on the error.
It would be great if you share your manifest and the platform information you are using with us, so that we can reproduce and help you debug! Thank you!

**Comment by joeyparrish** [comment]
If you created your own scheme plugin, it is likely that you have a bug in that plugin.  Could you share that plugin?  Are you returning MP4 URLs from the plugin, or are you delegating to another request to that URL?

If you "return a URL" from your plugin, then the text of that URL is what is fed to the browser as media.  You probably want to create another request to that target URL, and return the response to that request instead.

**Comment by hiren3897** [comment]
> If you created your own scheme plugin, it is likely that you have a bug in that plugin. Could you share that plugin? Are you 
> returning MP4 URLs from the plugin, or are you delegating to another request to that URL?

```javascript
  static parse(uri, request, requestType, progressUpdate, options) {
    const parts = uri.split(':');
    const path = parts.slice(1).join(':');
    return shaka.util.AbortableOperation.notAbortable(PlayerPlatformPlugin.loadManifest(path, options))
      .chain((manifest) => {  // returns an mp4 URL and we do HttpFetchPlugin.parse 
        return shaka.net.HttpFetchPlugin.parse(PlayerPlatformPlugin.manifestParser(manifest), request, requestType, progressUpdate);
      }).chain((response) => {
        /** @type {shaka.extern.Response} */
        const res = {
          uri: response.uri,
          originalUri: response.uri,
          data: response.data,
          headers: response.headers
        };
        return res;
      });
  }
```

I also tried to pass a mimeType while loading the player but it gives 3016 and without providing mimeType it gives 4000 error code.
```javascript
player.load('myplugin:https//url', null, 'video/mp4')
```


> If you "return a URL" from your plugin, then the text of that URL is what is fed to the browser as media. You probably want > to create another request to that target URL, and return the response to that request instead.

Am I doing it the right way?

**Comment by hiren3897** [comment]
@joeyparrish @michellezhuogg can you please help! me with this error.

Thanks
