### ISSUE TITLE
Shaka Player UI shows wrong caption selection if TextTrackVisibility was changed after UI init

### ISSUE THREAD

**Issue by Dador** [google/shaka-player#3728]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes.

**What version of Shaka Player are you using?**
3.2.1

**Can you reproduce the issue with our latest release version?**
Yes.

**Can you reproduce the issue with the latest code from `master`?**
Considering the cause, probably could reproduce, but I didn't tried.

**Are you using the demo app or your own custom app?**
Custom app.

**If custom app, can you reproduce the issue using our demo app?**
Seems like there is no UI usage in the demo app.

**What browser and OS are you using?**
Chrome 95

**What did you do?**
- Init player with `setTextTrackVisibility(true);`
- Init UI
- Disable captions (change to `setTextTrackVisibility(false);`)
- "Captions" icon becomes gray, but still shows selected language ("English" in this case) instead of "Off"

![image](https://user-images.githubusercontent.com/974924/139566772-6dbdddb5-4e0c-4b3c-a9f4-eb0ad4629699.png)
(if we click on "Captions", "English" is selected inside submenu)

**What did you expect to happen?**
"Captions Off" should be shown:
![image](https://user-images.githubusercontent.com/974924/139566807-5994a9da-8042-4add-9717-ba43a634f1f0.png)
(if we click on "Captions", "Off" should be selected inside submenu)

**Workaround**
Change `setTextTrackVisibility(true);` before UI init (but that's not always possible).

**Cause**
Current selection ("English", "Off", etc) seems to be updated inside `updateTextLanguages_`, but it's not called on `texttrackvisibility` event. Only `onCaptionStateChange_` is called.

I think adding call to `updateTextLanguages_` inside `onCaptionStateChange_` will resolve the issue.\
I thought maybe we can just add `this.currentSelection.textContent = this.localization.resolve(shaka.ui.Locales.Ids.OFF);` to `onCaptionStateChange_`, but that wouldn't update subtitles submenu.

**Comment by joeyparrish** [comment]
Thank you for the detailed report!  Would you be interesting in sending a PR for this?

**Comment by Dador** [comment]
I can do it if it's necessary. My dev env is not ready for shaka player, so I actually prefer if you can just commit it.
