### ISSUE TITLE
Use HDR information (transferFunction) when getting decoding info from Media Capabilities API

### ISSUE THREAD

**Issue by theRealRobG** [google/shaka-player#3729]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes.

**Is your feature request related to a problem? Please describe.**
When we query `decodingInfo` via the `mediaCapabilities` we send the minimal [`VideoConfiguration`](https://w3c.github.io/media-capabilities/#videoconfiguration) possible:
https://github.com/google/shaka-player/blob/v3.2.1/lib/util/stream_utils.js#L542-L549

To receive better information about media capabilities with respect to HDR content we should also pass information on the `transferFunction`.

**Describe the solution you'd like**
We carry the `hdr` information in the `shaka.extern.Stream` available on `shaka.extern.Variant`. The `hdr` property for HLS is derived from the `VIDEO-RANGE` attribute available on the [`EXT-X-STREAM-INF`](https://datatracker.ietf.org/doc/html/draft-pantos-hls-rfc8216bis-09#section-4.4.6.2), and the `VIDEO-RANGE` attribute indicates the _reference opto-electronic transfer characteristic function specified by the TransferCharacteristics code point [ISO/IEC 23001-8]_. Similarly in DASH we currently define `hdr` when we can determine that the variant is compliant with *10.3. DASH-IF IOP HEVC HDR PQ10* (indicating `PQ` value). Going forward we may also support identification of other transfer characteristics on the variant via information carried in essential / supplemental properties, as described in #3726.

Given this, the information for the [`transferFunction` value](https://w3c.github.io/media-capabilities/#enumdef-transferfunction) to be sent in the [`VideoConfiguration`](https://w3c.github.io/media-capabilities/#videoconfiguration) passed to `mediaCapabilities.decodingInfo` is readily available to us when constructing the object and so we should make use of the property when defined.

**Describe alternatives you've considered**

**Additional context**

**Comment by theRealRobG** [comment]
I'm working on a solution 👍

**Comment by joeyparrish** [comment]
Thank you!
