### ISSUE TITLE
Inconstitency between CDN version and NPM version for version 1.6.5

### ISSUE THREAD

**Issue by soualid** [google/shaka-player#373]
Hello,

The versions retrieved from the CDN differs from the one I got from NPM using the following dependency : `"shaka-player": "1.6.5"`. The CDN version I use is : https://cdnjs.cloudflare.com/ajax/libs/shaka-player/1.6.5/shaka-player.compiled.js 

How can I get the same version using NPM ?

Thank you in advance !

**Comment by tdrews** [comment]
Hi, which version do you get when you run `npm install shaka-player`?
You can specify v1.6.5 specifically with `npm install shaka-player@1.6.5`.

**Comment by joeyparrish** [comment]
v1.6.5 on cdnjs appears to actually be v2.0.0-beta.  I'm not sure how this happened.

v1.6.4 on cdnjs is correct.  All versions on npm seem to be correct.

I will contact cdnjs for support on this.  Thanks!

**Comment by joeyparrish** [comment]
This appears to be fixed now:  cdnjs/cdnjs#8234

**Comment by soualid** [comment]
Thanks !
