### ISSUE TITLE
Getting error 4000 when using a redirect URI for MP4

### ISSUE THREAD

**Issue by egalvan10** [google/shaka-player#3738]
Have you read the FAQ and checked for duplicate open issues?
Yes

What version of Shaka Player are you using?
v3.2.1 or latest

Can you reproduce the issue with our latest release version?
Yes

Can you reproduce the issue with the latest code from master?
Yes

Are you using the demo app or your own custom app?
Custom app

What browser and OS are you using?
Any

What configuration are you using? What is the output of player.getConfiguration()?
Default

What did you do?
Set the video source (using player.load(video_uri) ) to a URL that responds with a HTTP 302/303/307 "Temporary redirect" pointing to a new URL containing the actual video resource in MP4 format (https://my-site.com/video.mp4) 

What actually happened?
Player does not load video and returns a "Error code 4000: UNABLE_TO_GUESS_MANIFEST_TYPE".

Note that inspecting the response from the GET to the original resource returns an adequate Content-Type header of "video/mp4". Also, when the original URL redirects to an HLS resource instead of an MP4, (https://my-site.com/manifest.m3u8) the redirection works and the player loads and plays the video properly. Using the MP4 resource directly without redirection also loads and plays the video correctly, only when redirected does the 4000 error happen.

**Comment by hiren3897** [comment]
maybe related to my issues #3722

**Comment by eliezer-pearsports** [comment]
This issue was solved by manually setting the content-type value as follows:

`player.load(video_uri, null, 'video/mp4')`

The player then plays the MP4 using the redirect URL.

**Comment by egalvan10** [comment]
This issue was solved by manually setting the content-type value as follows:

`player.load(video_uri, null, 'video/mp4')`

The player then plays the MP4 using the redirect URL.
