### ISSUE TITLE
MP4 Playback Question

### ISSUE THREAD

**Issue by sanbornhnewyyz** [google/shaka-player#375]
In Shaka 1.x there was an HTTP Video Source you could load instead of a Dash Video Source. My understanding is that was there for testing and dev purposes only so it has been dropped from v2. So I am now looking to modify our library so we can continue to support MP4 playback. To do this I can rely pretty much on just attaching the mp4 url to the `<video>` source. I am just looking for a little guidance on what to do with Shaka in this case. If I have a shaka player already instantiated and then I try to directly attach a url to the `video.src` attribute, it immediately gets overwritten with a local url that Shaka attaches. It looks to me then like I need to first destroy the shaka instance and interact directly with the `<video>` tag. Is this correct or is there a different way that I can start MP4 playback that doesn't require me to destroy the Shaka instance?

**Comment by joeyparrish** [comment]
If you want to stop using Shaka Player temporarily to play a plain MP4, you could use `player.unload()` instead of `player.destroy()`.  `player.unload()` returns a Promise.

**Comment by sanbornhnewyyz** [comment]
Alright, thanks for the response. I had tried that originally and it wasn't working but turns out I wasn't waiting for the promise to resolve first 😕 .
