### ISSUE TITLE
Severity 2 error with no Code: `a.getAttribute is not a function`

### ISSUE THREAD

**Issue by stuartflanagan** [google/shaka-player#3766]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.2.1

**Can you reproduce the issue with our latest release version?**
Locally yes

**Can you reproduce the issue with the latest code from `master`?**
I am not sure I cannot build the master version

**Are you using the demo app or your own custom app?**
Our own custom app

**If custom app, can you reproduce the issue using our demo app?**
The error is not displayed with the Demo App

**What browser and OS are you using?**
Chrome Latest

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

I will email the manifest. I think the issue will be here but cannot see which attribute the manifest parser is failing on.

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Basic Configuration no overrides.

**What did you do?**

**What did you expect to happen?**
Content to play without error as it does in the demo player. I am wondering if the error is handled in some way in the demo player?

**What actually happened?**

Playback starts then a severity 2 error occurs without any Code.
I can ignore the error and playback is fine but our system is set up to close playback on severity 2 errors.
The error reported is:
```
severity: 2
message: "a.getAttribute is not a function"
```

**Comment by theodab** [comment]
The DASH parser contains a lot of `getAttribute` calls. From the sounds of that error, some variable that we expect to contain an `Element` is somehow containing a non-element. Perhaps we got a text node somewhere in the DOM hierarchy where we were expecting an element node? I don't see any obvious problems of that sort in that sample manifest you provided, though.

Would it be possible to run Shaka Player in uncompiled mode and get a full stack trace?

**Comment by bcupac** [comment]
Looks like TTML comments are passed to ttml_parser which is expecting only XML nodes.

TTML to reproduce:
`<smpte:information smpte:mode="Enhanced" />
<styling>
<style xml:id="backgroundStyle" tts:fontFamily="proportionalSansSerif" tts:fontSize="18px" tts:textAlign="center" tts:origin="0% 66%" tts:extent="100% 33%" tts:backgroundColor="rgba(0,0,0,0)" tts:displayAlign="center" />
<style xml:id="speakerStyle" style="backgroundStyle" tts:color="white" tts:textOutline="black 1px" tts:backgroundColor="transparent" />
<style xml:id="textStyle" tts:padding="0px" tts:fontSize="3rh" style="speakerStyle" tts:color="white" tts:textOutline="none" tts:backgroundColor="black" />
</styling><layout>
<region xml:id="full" tts:origin="0% 0%" tts:extent="100% 100%" tts:zIndex="1" />
<region xml:id="speaker" style="speakerStyle" tts:zIndex="1" />
<region xml:id="background" style="backgroundStyle" tts:zIndex="0" />
</layout>
</head><body><div>

</div></body></tt>
<smpte:information smpte:mode="Enhanced" />
<styling>
<style xml:id="backgroundStyle" tts:fontFamily="proportionalSansSerif" tts:fontSize="18px" tts:textAlign="center" tts:origin="0% 66%" tts:extent="100% 33%" tts:backgroundColor="rgba(0,0,0,0)" tts:displayAlign="center" />
<style xml:id="speakerStyle" style="backgroundStyle" tts:color="white" tts:textOutline="black 1px" tts:backgroundColor="transparent" />
<style xml:id="textStyle" tts:padding="0px" tts:fontSize="3rh" style="speakerStyle" tts:color="white" tts:textOutline="none" tts:backgroundColor="black" />
</styling><layout>
<region xml:id="full" tts:origin="0% 0%" tts:extent="100% 100%" tts:zIndex="1" />
<region xml:id="speaker" style="speakerStyle" tts:zIndex="1" />
<region xml:id="background" style="backgroundStyle" tts:zIndex="0" />
</layout>
</head><body><div>

</div></body></tt>`

![Screen Shot 2021-12-27 at 9 36 30 PM](https://user-images.githubusercontent.com/7647317/147506207-2c03415e-4264-466c-863d-700621499337.png)
