### ISSUE TITLE
HLS playback stops after seeking

### ISSUE THREAD

**Issue by denissabramovs** [google/shaka-player#3774]
Using `shaka-player v3.2.1`

Here is a recorded video of playback issues:
https://share.vidyard.com/watch/BcXX5UhK5NsCo2KMXm4CnS?

Sometimes, but not always, after seeking a playback stucks, but time clock on a timeline is ticking.

Some seeking problem is visible in video as well. That jump from 05:17 to 08:02, almost 3 hours jump in just a tiny part of timeline... I have re-checked, there is no gap in actual video, video was properly recorded in that period 05:17 to 08:02.

What could be the root of the problem?
I can publish HLS playlist here.

**Comment by denissabramovs** [comment]
Here are contents of all 3 playlists:
https://gist.github.com/denissabramovs/6c41dd9a5154435699a080e82f61c725
https://gist.github.com/denissabramovs/b408e2dda0f55a2999118f4bca97a94d
https://gist.github.com/denissabramovs/8bc73781a647e4fa73ba100671aba0b1

**Comment by denissabramovs** [comment]
No DISCONTINUITY for the whole time of recording.

**Comment by denissabramovs** [comment]
No additional settings applied, only `await player.load(manifestUri);`

**Comment by TheModMaker** [comment]
Please fill out the bug template and don't erase it.  Also please provide a playable manifest URL, not just the text.  This will probably be content-specific, so the manifest text won't be enough.  You can send the URL privately to <shaka-player-issues@google.com> if it is sensitive.

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**


**What version of Shaka Player are you using?**


**Can you reproduce the issue with our latest release version?**


**Can you reproduce the issue with the latest code from `master`?**


**Are you using the demo app or your own custom app?**


**If custom app, can you reproduce the issue using our demo app?**


**What browser and OS are you using?**


**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**


**What are the manifest and license server URIs?**


**What configuration are you using?  What is the output of `player.getConfiguration()`?**


**What did you do?**


**What did you expect to happen?**


**What actually happened?**
