### ISSUE TITLE
How to create a custom OverflowMenu in shaka player?

### ISSUE THREAD

**Issue by dolphincodes** [google/shaka-player#3777]
I am trying to do some custom UI on the Shaka player. Is there any way to create a custom OverflowMenu in the shaka player?

**Comment by nbcl** [comment]
Hello @dolphincodes!

You can choose which buttons appear in the overflow menu with the use of `ui.configure()`.

For example, adding the Cast and Captions buttons would look as follows:

```js
const video = document.getElementById('video');
const ui = video['ui'];
const config = {
  'overflowMenuButtons' : ['cast', 'captions']
};
ui.configure(config);
```

For a full list of the available buttons, or if you are looking to create custom buttons for your `OverflowMenu` you can check out the [UI customization tutorial](https://shaka-player-demo.appspot.com/docs/api/tutorial-ui-customization.html).

On the other hand, if you are looking to customize the menu styling itself, you could start by editing the styles available on [`overflow_menu.less`](https://github.com/google/shaka-player/blob/master/ui/less/overflow_menu.less).

Let me know if this helps!
