### ISSUE TITLE
support iphone or ipad

### ISSUE THREAD

**Issue by FeiCao** [google/shaka-player#378]
Hi, If I want  shaka-player to support iPhone or ipad , can you give me some advices? thank you!

**Comment by joeyparrish** [comment]
Shaka Player requires Media Source Extensions (MSE) at a minimum, but as of iOS 9, Apple's iOS version of WebKit does not provide that API.

Further, Apple requires their version of WebKit to be used in all iOS browsers.  This means that Shaka Player will not currently work on any iOS browser, including both Safari and Chrome.

We hope that this changes in future, but it would up to Apple to make those APIs available.

**Comment by johnpallett** [comment]
This is related to #997
