### ISSUE TITLE
Published to NPM?

### ISSUE THREAD

**Issue by sanbornhnewyyz** [google/shaka-player#38]
Have the latest change to master been published to npm? Updating/Installing through npm is not picking up the latest changes.

**Comment by palmerj3** [comment]
Not yet. Will likely be published at the end of the month I've been told. In the meantime I you can run ./build/all.sh and utilize the index.js generated file in your project. This file will export all the classes you need.

**Comment by sanbornhnewyyz** [comment]
Alright, thanks. I can wait. Building it manually makes it a bit awkward to maintain in our project. So anything on master that is not on 1.2.x is for the next minor release and only gets published to npm when that release happens? Essentially I'm waiting for 1.3 then? Is that right?

**Comment by palmerj3** [comment]
I believe so.

I'm in a similar boat with my project. For now I have just created a "vendor/shaka-player" folder in my root dir and placed the compiled index.js there.

Once the NPM dependencies are available I'll swap that out with a normal node_modules include. Not ideal but works fine.

**Comment by joeyparrish** [comment]
Yes, Jason has the right of it.  We'll be releasing these changes in 1.3.0.  1.2.x is collecting bugfixes only.  We expect 1.3.0 out by the end of the month, and we'll update the milestones page if that changes.

**Comment by sanbornhnewyyz** [comment]
Great, thanks guys.
