### ISSUE TITLE
Video broken when seek

### ISSUE THREAD

**Issue by soma946** [google/shaka-player#380]
Hi,

I played on demo page and seeking below url, video broke.

![screen](https://cloud.githubusercontent.com/assets/3501520/15310079/8b4d7b58-1c27-11e6-8b67-21a3731eac7e.png)

- demo page's url
http://shaka-player-demo.appspot.com/demo/

- URL
http://tk2-259-39450.vs.sakura.ne.jp/mpd/manifest.mpd

Easy to reproduce when seek to 8:45, but occasionally reproduce some position.

Tested several environments.
- Win8.1/IE11 , chrome  50.0.2661.94 m
- Win10/Edge , IE11 , chrome  50.0.2661.94 m
- OS X 10.9.5/chrome 50.0.2661.86(64-bit)

Are there any way to avoid this issue and why this issue happen?

Best regards.

**Comment by joeyparrish** [comment]
Just based on the image, I'm going to guess your video was not correctly encoded.  I could not reproduce on a Chromebook with a hardware decoder, but that's the only platform available to me at the moment.

I agree with @cpeterso in dailymotion/hls.js#446.  If it looks like a decoder error, and Firefox reports corruption on Mac, and the same corruption manifests on three different players, it is likely a corrupt video and not the fault of the player.

I would advise you to check for updates to your encoder software, to re-encode the video, and/or to report this to the encoder vendor.  Thanks!
