### ISSUE TITLE
HLS live streams have no timeline on UI

### ISSUE THREAD

**Issue by hiren3897** [google/shaka-player#3800]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

No common issues
**What version of Shaka Player are you using?**
lastest 3,2,1

**Please ask your question**
HLS live streams have a hidden timeline

we are not able to navigate in the past because of the hidden timeline 
may I know why the timeline is kept hidden when we load hls live streams?

Is it possible to display the timeline for HLS live streams? 

like we have for the DASH manifest? 

Thank you in advance

**Comment by hiren3897** [comment]
Hello there,
could you please answer my question?

thank you :)

**Comment by joeyparrish** [comment]
Sorry for the delay.  HLS live streams are not seekable by default.  This is consistent with Apple's implementation, and with the lack of seek range information in HLS.

You can override this in the player config, however.  Just set `'manifest.availabilityWindowOverride'` to some number of seconds.

**Comment by hiren3897** [comment]
Thank you it worked! :tada:
