### ISSUE TITLE
I wonder how to change bandwidth every 3 seconds.

### ISSUE THREAD

**Issue by baehongjun0212** [google/shaka-player#3802]
Have you read the Tutorials?
Y

Have you read the FAQ and checked for duplicate open issues?
Y

What version of Shaka Player are you using?
3.1.3

Please ask your question
First of all, thank you for developing a good program.

1. I want to change the bandwidth information every 3 seconds using the setTimeOut function, but is there a related API in Shaka? The bandwidth information of the video was obtained as shown in the code below.

2. I wonder how to change the approximation bandwidth closest to 7.0m using the find() function when pressing the button.

I'm always grateful to you :)

**Comment by joeyparrish** [comment]
I am not sure I understand your question.  Do you want to change the selected track based on the bandwidth requirements of that track?  Or do you want to artificially change Shaka's understanding of the available bandwidth, and force it to choose certain tracks through that?

**Comment by baehongjun0212** [comment]
I relied on a translator and couldn't properly convey my intention. I'm sorry :(

What I want to do is get the chunk size of mpd, and when I get the chunk three times, I want to change it to the next bandwidth track.
If the chunk size is 4, change to the next track in 12 seconds.

1. I wonder if there is an API in the shaka player that receives the chunk size of the mpd image.

2. If I receive the chunk 3 times, can I change it to the next bandwidth track?

So first,The player's bandwidth was created as a list.

var trackList = player2.getVariantTracks();
console.log(trackList);

0: {id: 0, active: true, type: 'variant', bandwidth: 1000000, language: 'und', …}
1: {id: 1, active: false, type: 'variant', bandwidth: 3000000, language: 'und', …}
2: {id: 2, active: false, type: 'variant', bandwidth: 5000000, language: 'und', …}
3: {id: 3, active: false, type: 'variant', bandwidth: 7000000, language: 'und', …}

**Comment by joeyparrish** [comment]
There is not an API to receive the chunk size, but if you know the way your content is encoded, you could hard-code the time interval.  Alternately, you could explore the manifest structure (player.getManifest()) and get the size of the first segment of an arbitrary track, and use that to compute your time interval.

Changing tracks is easy.  After getVariantTracks(), select an item from that list and call selectVariantTrack().  Be sure to disable ABR in the player configuration first, or else ABR will make its own choices periodically.

Does this help?

**Comment by baehongjun0212** [comment]
The answer was helpful.
`console.log(player2.getManifest().variants[0].video)`
The segment could be confirmed. Thank you.

Is there a way to change to the next track every time I receive three chunk?

**Comment by joeyparrish** [comment]
You can change tracks using the API I mentioned before.  To know when you've received three chunks, you could use a network filter.  Our license server authentication tutorial has examples of network filters:

https://shaka-player-demo.appspot.com/docs/api/tutorial-license-server-auth.html

You would want to look for request type of SEGMENT instead of LICENSE, and you won't need to modify anything in the request.  Just observe and count.

Does this help?

**Comment by baehongjun0212** [comment]
It helped me a lot. Thank you!
