### ISSUE TITLE
Multiperiod transition problem in shaka 2.0.0-beta

### ISSUE THREAD

**Issue by ArhiChief** [google/shaka-player#381]
In case of multiperiod manifest playback player stalls at the end of a first period defined in manifest. looks like it happens when there are periods with different byte range values of init range (@range of Initialization tag) in a single manifest file.

All video files, segments and manifests are [here](https://drive.google.com/folderview?id=0B76D-92hJlOCX0ZFYjdMVXIyTDA&usp=sharing).

**Comment by joeyparrish** [comment]
Thanks, we'll take a look.  Odds are good that there is a gap at the start of the second period, which is something we do not currently support.

**Comment by mediadevtech** [comment]
please, tell me what does the gap exactly mean? in case of attached testing datasets each period in manifest has it's own init segment.

**Comment by joeyparrish** [comment]
"Gap" means a discontinuity in the media timeline.  For example, if period 1 is from time `0` to time `9.8`, but period 2 starts at time `10`, then there is a gap of `0.2` for which there is no media.

We haven't analyzed your content yet to see if there is a gap, but that is my guess based on the behavior you are describing.

**Comment by tdrews** [comment]
Yes, there is a gap, but it's actually in the SIDX of the second Period. The SIDX indicates that the first segment of the second Period begins at ~ 0.4 seconds (as it specifies an earliestPresentationTime); however, the actual segment begins at 0. I believe the SIDX may be incorrect here.

**Comment by joeyparrish** [comment]
Please re-encode the content in question or report the bug to the vendor of the encoding/packaging software.
