### ISSUE TITLE
Change quality in ios devices

### ISSUE THREAD

**Issue by zAngelDev** [google/shaka-player#3824]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.2.1

**Please ask your question**
How can i change video quality in ios devices?
I tried the normal way with selectVariantTrack but in ios say this error:
undefined is not an object (evaluating 'a.id')

**Comment by gregmsanderson** [comment]
I _believe_ for that to work, Media Source Extensions has to be supported in the browser. iOS (on an iPhone) at least, does not support MSE so you have to use its native playback for HLS/MP4 video.

https://developers.google.com/web/fundamentals/media/mse/basics

**Comment by zAngelDev** [comment]
But are any way to change quality like youtube page in ios?

**Comment by zAngelDev** [comment]
> I _believe_ for that to work, Media Source Extensions has to be supported in the browser. iOS (on an iPhone at least), does not support MSE so you have to use its native playback for HLS/MP4 video.
> 
> https://developers.google.com/web/fundamentals/media/mse/basics

But are any way to change quality like youtube page in ios?

**Comment by gregmsanderson** [comment]
I don't know how YouTube are doing it.

Since other players report the same limitation with choosing the quality without MSE on iOS e.g:
https://docs.theoplayer.com/faq/07-why-cant-we-select-other-video-quality-on-ios.md
https://bitmovin.com/docs/player/faqs/why-the-quality-cant-be-manually-changed-in-safari

**Comment by zAngelDev** [comment]
Oh ok ty for the information :)
