### ISSUE TITLE
Shakaplayer on web runtime

### ISSUE THREAD

**Issue by ManuelBradicic42** [google/shaka-player#3831]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.2.0

**Please ask your question**
When calling 'player.getStats()' method:
a) on my browser (chrome): I am able to fetch all the specifications( including decoded and dropped frames)
b) I am running Shakaplayer on Web runtime (WRT) based on Chrome 56; I am able to fetch only some specifications; decoded frames stay 0.

In case of b) the player is loaded(video is playing), playing time is getting incremented, there is no console error, however, decoded frames are 0

**Comment by ManuelBradicic42** [comment]
The information I am trying to find is what version of chrome does .getStats() method require?

**Comment by joeyparrish** [comment]
The getStats() method collects information from various places.  The API that provides dropped and decoded frames is VideoPlaybackQuality: https://developer.mozilla.org/en-US/docs/Web/API/VideoPlaybackQuality

This was added in Chrome 23, according to that MDN link.  If your runtime doesn't implement that API (or a prefixed version of it), then Shaka Player will not be able to get information about decoded or dropped frames.

Does this answer your question?
