### ISSUE TITLE
CMCD fields names are being mangled

### ISSUE THREAD

**Issue by littlespex** [google/shaka-player#3839]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.3.0

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
Safari, Chrome, Firefox

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**

Load any stream with the player configured for `cmcd`.

**What did you expect to happen?**
The CMCD data appears in the manifest/segment requests with the correct field names.

**What actually happened?**

The CMCD field names are mangled:

`http://dash.edgesuite.net/akamai/bbb_30fps/bbb_30fps.mpd?CMCD=Ea%3D%22m%22%2CZc%3D1%2CZf%3D1%2Cdf%3D%22CONTENT_ID%22%2Cqg%3D%22d%22%2Crg%3D%227af3be4f-0bfa-4029-80b2-59d0b57e8328%22%2Cvb`

Decoded: 
`CMCD: Ea="m",Zc=1,Zf=1,df="CONTENT_ID",qg="d",rg="7af3be4f-0bfa-4029-80b2-59d0b57e8328",vb`

**Comment by littlespex** [comment]
@joeyparrish It looks like the property names are being mangled when closure compiler's optimization mode is `ADVANCED`. What is the best way to signal the compiler not to minify certain objects or properties?

**Comment by joeyparrish** [comment]
Property names either need to be quoted or defined in externs to avoid renaming.  In this case, I think externs would be appropriate, as the field names are part of an externally-defined interface.

**Comment by joeyparrish** [comment]
Looks to me like `shaka.util.CmcdManager.Data` just needs to be moved to the externs (and taken out of the shaka.util namespace).  Since this is purely external and not part of a plugin or other interface defined by Shaka, I would suggest moving it to `externs/cmcd.js` and naming it `CmcdData` (no namespace).
