### ISSUE TITLE
packager freeze on live profile generation

### ISSUE THREAD

**Issue by medazzo** [google/shaka-player#385]
Hi all , 

I was trying to generate a live mpd using a udp stream but it freeze at :
0518/184243:INFO:demuxer.cc(60)] Initialize Demuxer for file 'udp://0.0.0.0:1234'.

Here are my steaps: 

1. I create a udp stream using ffmpeg :

 ffmpeg -re -i /data/videos/bigbuckbunny.mp4 -f mpegts -vcodec h264 -acodec aac -ac 2 -ab 128k -s 720x432 -r 30  -b 2000k -threads 2   udp://0.0.0.0:1234 
generating a mpegTs udp stream  with H264 video and AAC audio 

2. ffprobe udp://0.0.0.0:1234

Input #0, mpegts, from 'udp://0.0.0.0:1234':
  Duration: N/A, start: 47.012267, bitrate: N/A
  Program 1 
    Metadata:
      service_name    : Service01
      service_provider: FFmpeg
    Stream #0:0[0x100]: Video: h264 ([27][0][0][0] / 0x001B), none, 6 fps, 6 tbr, 90k tbn
    Stream #0:1[0x101]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp, 128 kb/s

3.  packaging

packager  'input=udp://0.0.0.0:1234,stream=video,init_segment=live-video-sd.mp4,segment_template=live-video-sd-$Number$.mp4'    'input=udp://0.0.0.0:1234,stream=audio,init_segment=live-audio-0.mp4,segment_template=live-audio-0-$Number$.mp4'  --profile live --single_segment=false  --vmodule=5 --mpd_output live.mpd -time_shift_buffer_depth 1800

 it freeze at : 
*[0518/190103:INFO:demuxer.cc(60)] Initialize Demuxer for file 'udp://0.0.0.0:1234'.

Can you try to reproduce it ?

**Comment by medazzo** [comment]
it seems to works , in fact i was using mp2 audio format by mistake .
never the less , it take a long time to begin to package .. the ffmpeg command needs to be ameliorated !

**Comment by joeyparrish** [comment]
I think this belongs on https://github.com/google/shaka-packager .  This is the player.  Sorry for any confusion!

**Comment by medazzo** [comment]
yes ,you are completely right ,  sorry for disturb.

**Comment by joeyparrish** [comment]
No problem!
