### ISSUE TITLE
Captions regression in 3.3.0

### ISSUE THREAD

**Issue by FireMasterK** [google/shaka-player#3850]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.3.0

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
I can on the nightly demo

**Are you using the demo app or your own custom app?**
Custom

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Brave, Linux

**What are the manifest and license server URIs?**
https://bin.snopyta.org/?b692293141083c43#7jpXJvfKgK6JMxQ8JZFpHqkmTbtUmm6gV2QkqcZRtxCU

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
Default / Demo

**What did you do?**
```
const player = document.querySelector("video").ui.getControls().getPlayer();
player.addTextTrackAsync("https://...", "EN", "SUBTITLE", "application/ttml+xml", null, "ENGLISH");
```

**What did you expect to happen?**
When the captions have 2 lines, they shouldn't be overlapped.

**What actually happened?**
The captions appear overlapped.
![image](https://user-images.githubusercontent.com/20838718/149040391-ce5f6b9a-f643-473a-84c5-a774593d20f7.png)

**Comment by theodab** [comment]
It looks like this is a result of https://github.com/google/shaka-player/commit/cdeffbb9e6afcc68cb2165bcc0c99be20c9cb153

**Comment by avelad** [comment]
Maybe this related to https://github.com/google/shaka-player/issues/3741?

**Comment by theodab** [comment]
That might be the case, yes. Reverting the line of code that seems to be causing this also looks to fix that issue.

**Comment by avelad** [comment]
@theodab Did you find a solution for this?

**Comment by theodab** [comment]
Yeah, I believe so.
I think the problem is that our TTML text parser, if you assign a region to an element, also assigns that region to all of that element's descendants.
https://github.com/google/shaka-player/commit/cdeffbb9e6afcc68cb2165bcc0c99be20c9cb153, on further inspection, wasn't really the source of the problem; it just exposed the problem, by removing the logic in the displayer that said to ignore regions if there weren't on root elements.
So the fix I am working on right now is to just only assign a region if it's set directly in the element, and ignore inherited regions for the purposes of positioning.

I just want to take some time first to hopefully figure out whether or not this is going to break some other use case.

**Comment by avelad** [comment]
Another example with the same error:
```
<?xml version="1.0" encoding="utf-8"?>
<tt xml:lang="" xmlns="http://www.w3.org/ns/ttml" xmlns:tts="http://www.w3.org/ns/ttml#styling">
	<head>
		<styling>
			<style tts:backgroundColor="transparent" tts:color="white" tts:displayAlign="after" tts:fontFamily="proportionalSansSerif" tts:fontSize="0.68c" tts:textOutline="black 2px" xml:id="speakerStyle"/>
		</styling>
		<layout>
			<region style="speakerStyle" tts:extent="78% 16%" tts:origin="9% 80%" tts:textAlign="center" tts:zIndex="1" xml:id="speaker_1"/>
			<region style="speakerStyle" tts:extent="80% 35%" tts:origin="10% 60%" tts:textAlign="center" tts:zIndex="1" xml:id="speaker_2"/>
		</layout>
	</head>
	<body>
		<div>
			<p begin="61765:29:27.141" end="61765:29:29.061" region="speaker_1">
				<span tts:color="white" tts:fontStyle="normal" tts:fontWeight="normal" tts:textDecoration="none">El testigo</span>
				<br/>
				<span tts:color="white" tts:fontStyle="normal" tts:fontWeight="normal" tts:textDecoration="none">ha desaparecido misteriosamente.</span>
			</p>
			<p begin="61765:29:29.061" end="61765:29:29.141" region="speaker_2"/>
		</div>
	</body>
</tt>
```

**Comment by avelad** [comment]
I have seen that this issue is also related to https://github.com/google/shaka-player/issues/3762
