### ISSUE TITLE
Is it possible to use MPEG-DASH with ogg? 

### ISSUE THREAD

**Issue by hhshih** [google/shaka-player#3857]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
master

**Please ask your question**
Is it possible to use MPEG-DASH with ogg? 
Shaka player works when playing ogg directly, but when putting an ogg file with mimeType "audio/ogg" and codecs "opus" in DASH, it doesn't seem to play. 
Initial investigation shows the variant was filtered out by Media Capabilities. Is there a way to configure it so that ogg could be used with MPEG-DASH?

Thanks!

**Comment by theodab** [comment]
If you play a non-streaming media file (such as an ogg file) directly with Shaka Player, it plays the file via the browser's native playback. On the other hand, if that file is played inside a manifest, it is played via the MediaSource API.
Unfortunately, at the moment, MSE does not support ogg. See https://github.com/w3c/media-source/issues/245

**Comment by theodab** [comment]
Someone has also opened a bug on the Chromium tracker for this. https://bugs.chromium.org/p/chromium/issues/detail?id=1031829&q=ogg&can=2

**Comment by hhshih** [comment]
Thanks for the explanation!
