### ISSUE TITLE
Proper configuration for setting currentTime in mpd stream

### ISSUE THREAD

**Issue by Szefczuk** [google/shaka-player#3871]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.3.0

**Please ask your question**
Hi everyone,

Can you tell me how to set proper configuration to handle currentTime in mpd stream? For now when I pass currentTime, after play, it always back 2-5 seconds, imo to the beginning of downloaded chunk instead of provided time in currentTime.

NOTE: This only occurs on Tizen TV, in web browser everything works fine.

**Comment by Szefczuk** [comment]
This is strict related to that issue but merged solution didnt fixed it

[2831](https://github.com/google/shaka-player/issues/2831)

**Comment by joeyparrish** [comment]
> Can you tell me how to set proper configuration to handle currentTime in mpd stream?

I'm not sure what you mean by that.  Are you asking how to start playback at a certain position in the stream?  Is it VOD or live?

> For now when I pass currentTime, after play, it always back 2-5 seconds, imo to the beginning of downloaded chunk instead of provided time in currentTime.
> NOTE: This only occurs on Tizen TV, in web browser everything works fine.

We don't have a Tizen TV available at the moment (moving into a new building, with many delays in equipment setup), so we can't test on Tizen right now.  Can you clarify what is happening in more detail?  We may have to ask you to file a full bug report for this.

**Comment by Szefczuk** [comment]
@joeyparrish Okay, I will prepare everything today

**Comment by Szefczuk** [comment]
Okay @joeyparrish. There are debug logs directly from that, what shaka do after change of currentTime on Tizen.

This is totally fresh Shaka setup with yours example video.

| TIZEN SCENARIO | WEB BROWSER SCENARIO |
| ------------------- | ----------------------------- |
| ![151019536-8449f42d-4fec-4047-b9f8-3f4a4e3ceb7f](https://user-images.githubusercontent.com/30868365/151024202-ab1cb500-5742-4128-8d62-6ed813cdb8f1.png) | ![image](https://user-images.githubusercontent.com/30868365/151024313-40e1b81c-5ab5-4ff7-97ed-c916752a79c3.png) |

As you can see, after change of current time, some weird stuff happen and shaka automatically move playback couple of seconds back. This always occurs when I try to set currentTime, on start, in middle, or close to end of video. I've debugged the entire player, but without success ( means, player.js, playhead.js, streaming_engine.js, video_wrapper.js and segment_template.js )

Imho it backs always to beginning of segment, but why and where, I don't have an idea.

There are no logs with DEBUG, V1 and V2 log mode. Printed currentTime is from timeupdate event.

Thank's a lot for your help :)

**Comment by joeyparrish** [comment]
Ah, I see.  You're seeking to 2s (`video.currentTime = 2`), but then playback begins again at 0s instead.  Is that accurate?

Is this effect consistent for other segment boundaries, or just for times close to 0s?  For example, if segments are 4s long, can you seek to 14s, or will it play back from 12s instead?

Also, what version of Tizen are you using when you see this?  Does the effect occur on other versions of the platform?

For context, what happens when you set currentTime on the video element doesn't directly involve Shaka Player.  The browser/platform implements that, and we can't control it if they choose to round currentTime to a segment boundary or key-frame instead of using the time you specified.  We can try to help you understand the effect and the implementation of seeking inside Tizen, but I doubt we will be able to fix it or work around it.

**Comment by Szefczuk** [comment]
> Ah, I see. You're seeking to 2s (video.currentTime = 2), but then playback begins again at 0s instead. Is that accurate?

Yes, that's exactly what happens

> Is this effect consistent for other segment boundaries, or just for times close to 0s? For example, if segments are 4s long, can you seek to 14s, or will it play back from 12s instead?

This will always back to start of segment, if segment start is 12s it will start from 12s but if we will start from 15s it will start from 12s also

> Also, what version of Tizen are you using when you see this? Does the effect occur on other versions of the platform?

We've got in office several tizen's with different versions, this occurs on every device

> We can try to help you understand the effect and the implementation of seeking inside Tizen, but I doubt we will be able to fix it or work around it.

Okay, so I will try use their own recommended player `AVPlay` and we'll see if the problem persists.

Tizen is f****d up 🤬

**Comment by joeyparrish** [comment]
Tizen's web media implementation has been a consistent challenge.  And the lack of firmware updates doesn't make it any better.

I'm sorry we couldn't do more to help!
