### ISSUE TITLE
Add separate audio and video MIME types to Track API

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#3888]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Is your feature request related to a problem? Please describe.**

CAF would like to be able to determine the audio and video MIME types separately, and without resorting to the Manifest API.

**Describe the solution you'd like**

Add videoMimeType and audioMimeType fields to shaka.extern.Track.

**Describe alternatives you've considered**

This is already available from shaka.extern.Stream within shaka.extern.Manifest, but getManifest() is discouraged.

**Additional context**

b/114766347 for internal context

**Comment by avelad** [comment]
@joeyparrish I can work on this tomorrow, if you're interested...

**Comment by joeyparrish** [comment]
Thanks!
