### ISSUE TITLE
Stop using "undefined" in EME queries

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#389]
We are filling some fields explicitly with `undefined` when querying EME.  I seem to recall that this was because it was required by the Closure compiler to complete a record type.  However, we have upgraded the compiler many times, so that may not be true any more.  (I also might misremember the reason we started doing that.)

According to https://github.com/w3c/encrypted-media/issues/178#issuecomment-220381909, we should omit fields rather than fill them with `undefined`, as native code may treat explicit `undefined` values as "present", affecting the specified EME algorithms in unintended ways.

**Comment by ddorwin** [comment]
Implementations are correctly treating `undefined` as not present (see https://github.com/heycam/webidl/issues/124#issuecomment-220492410 for details). However, it still seems cleaner not to specify the values if you don't need to.

**Comment by joeyparrish** [comment]
Okay, I stand corrected.  We will consider it a non-priority enhancement, then.
