### ISSUE TITLE
CuesElement does not exist

### ISSUE THREAD

**Issue by nickdesaulniers** [google/shaka-player#39]
Hi there, I'm trying to play back content generated by following along [this](http://wiki.webmproject.org/adaptive-streaming/instructions-to-playback-adaptive-webm-using-dash) tutorial.  I run into the following error:

`CuesElement does not exist. webm_segment_index_parser.js:121`

Is this an element that is missing from my mpd manifest?

```xml
<?xml version="1.0" encoding="UTF-8"?>
<MPD
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="urn:mpeg:DASH:schema:MPD:2011"
  xsi:schemaLocation="urn:mpeg:DASH:schema:MPD:2011"
  type="static"
  mediaPresentationDuration="PT10.033S"
  minBufferTime="PT1S"
  profiles="urn:webm:dash:profile:webm-on-demand:2012">
<Period id="0" start="PT0S" duration="PT10.033S" >
<AdaptationSet id="0" mimeType="video/webm" codecs="vp9" bitstreamSwitching="true" subsegmentAlignment="true" subsegmentStartsWithSAP="1">
<Representation id="0" bandwidth="124382" width="160" height="90">
<BaseURL>video_160x90_250k.webm</BaseURL>
<SegmentBase
  indexRange="132303-132369">
<Initialization
  range="0-429" />
</SegmentBase>
</Representation>
<Representation id="1" bandwidth="266837" width="320" height="180">
<BaseURL>video_320x180_500k.webm</BaseURL>
<SegmentBase
  indexRange="313960-314026">
<Initialization
  range="0-430" />
</SegmentBase>
</Representation>
<Representation id="2" bandwidth="579451" width="640" height="360">
<BaseURL>video_640x360_750k.webm</BaseURL>
<SegmentBase
  indexRange="797366-797432">
<Initialization
  range="0-431" />
</SegmentBase>
</Representation>
<Representation id="3" bandwidth="767450" width="640" height="360">
<BaseURL>video_640x360_1000k.webm</BaseURL>
<SegmentBase
  indexRange="1055472-1055538">
<Initialization
  range="0-431" />
</SegmentBase>
</Representation>
<Representation id="4" bandwidth="1110647" width="1280" height="720">
<BaseURL>video_1280x720_500k.webm</BaseURL>
<SegmentBase
  indexRange="1544015-1544081">
<Initialization
  range="0-431" />
</SegmentBase>
</Representation>
</AdaptationSet>
<AdaptationSet id="1" mimeType="audio/webm" codecs="vorbis" audioSamplingRate="44100" bitstreamSwitching="true" subsegmentAlignment="true" subsegmentStartsWithSAP="1">
<Representation id="5" bandwidth="60219">
<BaseURL>audio_128k.webm</BaseURL>
<SegmentBase
  indexRange="86666-86731">
<Initialization
  range="0-4700" />
</SegmentBase>
</Representation>
</AdaptationSet>
</Period>
</MPD>
```

**Comment by nickdesaulniers** [comment]
hmm, angel one [doesn't seem to have](https://github.com/google/shaka-player/blob/master/assets/angel_one.mpd) Cues elements either.

**Comment by joeyparrish** [comment]
Hi Nick,

The CuesElement is part of the WebM content itself, not the manifest.  It's an index that tells the library where individual segments are in the file.

For each Representation element in your manifest, there is a SegmentBase element with an indexRange property.  This is supposed to be the location of the cues element within the WebM file.

So it would seem that the bytes ranges in your manifest don't agree with your files.

**Comment by nickdesaulniers** [comment]
@joeyparrish , can you reproduce, with this input file and script:

https://www.dropbox.com/s/vw0y6823y6ih5z3/short.mp4?dl=0

```
FILE=short.mp4
VP9_DASH_PARAMS="-tile-columns 4 -frame-parallel 1"

ffmpeg -i ${FILE}
  -c:v libvpx-vp9 -s 160x90 -b:v 250k -keyint_min 150 -g 150                  \
  ${VP9_DASH_PARAMS} -an -f webm -dash 1 video_160x90_250k.webm

ffmpeg -i ${FILE} -c:v libvpx-vp9 -s 320x180 -b:v 500k -keyint_min 150 -g 150 ${VP9_DASH_PARAMS} -an -f webm -dash 1 video_320x180_500k.webm

ffmpeg -i ${FILE} -c:v libvpx-vp9 -s 640x360 -b:v 750k -keyint_min 150 -g 150 ${VP9_DASH_PARAMS} -an -f webm -dash 1 video_640x360_750k.webm

ffmpeg -i ${FILE} -c:v libvpx-vp9 -s 640x360 -b:v 1000k -keyint_min 150 -g 150 ${VP9_DASH_PARAMS} -an -f webm -dash 1 video_640x360_1000k.webm

ffmpeg -i ${FILE} -c:v libvpx-vp9 -s 1280x720 -b:v 1500k -keyint_min 150 -g 150 ${VP9_DASH_PARAMS} -an -f webm -dash 1 video_1280x720_500k.webm

ffmpeg -i ${FILE} -c:a libvorbis -b:a 128k -vn -f webm -dash 1 audio_128k.webm

ffmpeg \
  -f webm_dash_manifest -i video_160x90_250k.webm \
  -f webm_dash_manifest -i video_320x180_500k.webm \
  -f webm_dash_manifest -i video_640x360_750k.webm \
  -f webm_dash_manifest -i video_640x360_1000k.webm \
  -f webm_dash_manifest -i video_1280x720_500k.webm \
  -f webm_dash_manifest -i audio_128k.webm \
  -c copy -map 0 -map 1 -map 2 -map 3 -map 4 -map 5 \
  -f webm_dash_manifest \
  -adaptation_sets "id=0,streams=0,1,2,3,4 id=1,streams=5" \
  manifest.mpd
```

I'm curious now if this is a bug in ffmpeg mpd generation, webm generation, or I'm doing something wrong?

**Comment by nickdesaulniers** [comment]
nvm! user error, missed a damn `\` for the shell script!  I was doing something stupid, thanks for your time.

**Comment by joeyparrish** [comment]
Happy to help!

**Comment by nickdesaulniers** [comment]
Interestingly, I now get this error for 2 of the 5 different resolutions.

**Comment by nickdesaulniers** [comment]
@joeyparrish , if you have time, could you look at this again.  I've worked on improving my reported steps to reproduce.  If you clone this repo: https://github.com/nickdesaulniers/mpd-dash

STR:
1. `git clone https://github.com/nickdesaulniers/mpd-dash.git && cd mpd-dash`
2. `./download_source.sh`
3. `./test.sh`, wait for transcodes to finish, takes about a minute on mid-2012 MBP
4. serve shaka player from localhost, browse to it
5. change test manifest to custom
6. set custom manifest url to served manifest.mpd file
7. click load stream
8. right click on video, check Loop (otherwise video is too short, 10s)
9. click cycle video tracks

Expected:
Player to cycle through various streams.

Actual:
Numerous `CuesElement does not exist.` errors, sometimes stream doesn't start when clicking loading stream, but will after subsequent clicks without page reload.  Only the 320 x 180 stream loads and plays.

This is testing with Opera Beta 29.0.1795.21, and ffmpeg version 2.5.2.

**Comment by nickdesaulniers** [comment]
because there are so many dependencies, I'm not sure if this is a bug in:
* how I'm using ffmpeg, starting with a mp4 -> webm
* ffmpeg's mpd generator
* ffmpeg's webm encoder
* ffmpeg's mp4 decoder
* shaka's CuesElement parser
* Opera/Blink's MSE implementation

**Comment by joeyparrish** [comment]
I am unable to reproduce this error.  When I run your script, I get valid WebM streams with Cues elements, and the byte ranges specified in the manifest are correct.

Can you please send me the exact webm and mpd files you have produced with these steps?  If ffmpeg were to blame, I might fail to repro because I'm using a different version of ffmpeg.

**Comment by nickdesaulniers** [comment]
@joeyparrish , here's the folder: https://www.dropbox.com/sh/kmk5nhwj824xy6q/AAADCZ_zpiWkxpxZ79yDyyxAa?dl=0.  What version of ffmpeg are you using?  I'm not building ffmpeg from source, just installing from homebrew (rather, homebrew might be building from source.  I don't think they maintain mirrors to prebuilt binaries).

**Comment by joeyparrish** [comment]
I periodically update my build of ffmpeg from source.  But ffmpeg doesn't seem to be the problem, since I am unable to reproduce with these exact files you sent me.  I've also double-checked the manifest against the WebM files themselves, and the byte ranges are accurate.

So now we're down to either a Shaka Player bug, or a problem with your browser or your web server.

To check if it's the browser, can you try reproducing in Chrome instead of Opera?

**Comment by nickdesaulniers** [comment]
Interesting, broken in Opera Beta 29.0.1795.21 but not Chrome 43.  Chrome 41 throws [an error](https://pastebin.mozilla.org/8826842) but continues playing.

**Comment by joeyparrish** [comment]
That "endOfStream" error you're referencing from Chrome 41 is a red herring.  That's a Shaka Player which is unrelated.  (Filed as #43.)

I just tried in Opera 28 and 29 on Linux, and I'm unable to reproduce your WebM error on either of those versions, either with the files you sent me or with the ones I produced myself.

I'm going to label this "working as intended".  You may want to make sure your web server is serving the correct files and byte ranges as requested by the client.  I don't see any evidence that the WebM parser in Shaka is to blame.

**Comment by nickdesaulniers** [comment]
unbelievable, switching the static file server did the trick.  I was using `python -m SimpleHTTPServer`, now I'm using [this](https://github.com/indexzero/http-server) and not seeing any issues.  If you can repro (should have python on linux), maybe it would be worthwhile to add a note to the readme that python's simpleserver has issues?

**Comment by nickdesaulniers** [comment]
Thanks for you assistance @joeyparrish , I appreciate it!

**Comment by joeyparrish** [comment]
I don't think there's a place in the docs for listing non-HTTP-compliant or otherwise broken web servers, in my opinion.  That's somewhat outside the scope of the project.

If you can figure out what SimpleHTTPServer doesn't support correctly, maybe they would like to hear about it in their issue tracker.  My first guess would be that it either ignores or incorrectly implements support for the "Range" request header.  But that's just a guess.

Good luck!
