### ISSUE TITLE
Player robustness against network failures

### ISSUE THREAD

**Issue by BucherTomas** [google/shaka-player#390]
Shaka Player v2.0.0-beta2 is missing some countermeasures for situations, where the network is temporarily disconnected, this typically applies to mobile devices when they are, say, disconnected from the carrier, e.g. going through a tunnel in a car with a passenger watching a video, etc.

Steps to reproduce:
1. Start playing any video with Chrome developer tools open.
2. Select offline preset from the list of connectivity simulations in Network tab
3. Shaka throws HTTP Network error (ID 1002) from which it cannot recuperate, even though the network  becomes again available a short while later by switching to No throttling preset.

No amount of standard user interaction (pressing play, or seeking) helps. The media needs to be loaded again.

Shaka v1.6.5 handles this situation by querying last segment indefinitely until the network is available again and then it continues normally. It would be great if Shaka v2 did something similar and even if the error occurs under other circumstances, let it not be so destructive to the playback session.

**Comment by tdrews** [comment]
Yes, we should do this.

**Comment by joeyparrish** [comment]
I think we need two more changes related to this:

1. change the default retry parameters so that more than one attempt is made by default
2. since network errors may not be fatal, we should add a small 'dismiss' button to the error div in the demo app to allow a user of the demo to clear the error message
