### ISSUE TITLE
registerRequestFilter for iOS with `useNativeHlsOnSafari: false`

### ISSUE THREAD

**Issue by mreiben** [google/shaka-player#3912]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
3.3.0

**Please ask your question**
I'm able to register a request filter on an instance of the player in chrome and safari, but for some reason the registration isn't happening for the player in iOS (though it is in iPadOS). I tried setting `useNativeHlsOnSafari` to `false`, but that doesn't seem to have made a difference. I added logging and it appears that the function that I register is never called in iOS when the player loads.

Just some context: I'm trying to access content that is on a CloudFront CDN that requires signed urls. The `src` for the video is signed, but the underlying .m3u8 file just references the child manifests which aren't signed, so I'm trying to replace those uris with signed urls that I already have. As I said this process is working fine in other contexts, but I'm not sure what I'm missing to make it work for iOS devices.

Here's the relevant code:
```
if (shaka.Player.isBrowserSupported()) {
  // Install built-in polyfills
  shaka.polyfill.installAll();
  this.shakaInstance = new shaka.Player(video);
  this.shakaInstance.configure({
    abr: {
       defaultBandwidthEstimate: 800000
    },
    streaming: {
       useNativeHlsOnSafari: false
     }
   });
   if (!this.unsignedUrl) { // hls manifest doesn't include signedUrls, so we need to replace them with the signedUrls on-the-fly
     let videoUrls = this.signedUrls.videos;
     let manifests = this.signedUrls.manifests;
     console.log('signed url needed, registring request filters'); // this never logs on iOS
     this.shakaInstance.getNetworkingEngine().registerRequestFilter((type, request) => {
        const uri = request.uris[0];
        if (type === shaka.net.NetworkingEngine.RequestType.MANIFEST && uri.indexOf('Key-Pair-Id') === -1) { // missing signature
          let url;
          const vidQuality = uri.substring(uri.length - 9);
          if (vidQuality === '_low.m3u8') url = manifests[1];
          else if (vidQuality === '_med.m3u8') url = manifests[2];
          else url = manifests[3];
          request.uris[0] = url;
        } else if (type == shaka.net.NetworkingEngine.RequestType.SEGMENT) {
          let url;
          const vidQuality = uri.substring(uri.length - 7);
          if (vidQuality === '_low.ts') url = videoUrls[0];
          else if (vidQuality === '_med.ts') url = videoUrls[1];
          else url = videoUrls[2];
          request.uris[0] = url;
         }
       });
     }
     this.shakaInstance.load(this.src);
   } else {
     console.log('Browser is not supported!');
}
```

I'm assuming that I'm missing something required for HLS in iOS.

Thank you!

**Comment by joeyparrish** [comment]
On iOS, outside of iPad, native HLS is the only option.  With Apple's native HLS, requests for playlists and segments are made by the native HLS implementation, not by JavaScript.  Therefore, network filters are not feasible in Shaka on iOS.

If Apple ever decides to ship full MSE support on iOS, everything will be able to work the same across platforms.  Until then, we apologize for the inconvenience!

**Comment by mreiben** [comment]
@joeyparrish thanks for the quick response! I think the best path forward will be for me to rethink the signed url pattern to avoid needing to use the network filters in the first place.
