### ISSUE TITLE
Setting up playback rate

### ISSUE THREAD

**Issue by ManuelBradicic42** [google/shaka-player#3922]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
3.0

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `master`?**
yes

**Are you using the demo app or your own custom app?**
yes

**If custom app, can you reproduce the issue using our demo app?**
/

**What browser and OS are you using?**
Linux

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
/

**What did you do?**

run the code:
http://v1-6-2.shaka-player-demo.appspot.com/docs/tutorial-trickplay.html

**What did you expect to happen?**
Fast forward to work

**What actually happened?**

It did not work

I was having problem setting fastforwardrate because the webpage documentation is outdated. Hence I suggest updating the page with the latest methods. The documentation says to use: 
player.setPlaybackRate(2);

when it should've been: 
video.playbackRate = 2;

as it was mentioned here: https://github.com/google/shaka-player/issues/3261#issuecomment-803719031

Documentation link: http://v1-6-2.shaka-player-demo.appspot.com/docs/tutorial-trickplay.html

**Comment by avelad** [comment]
You are using a quite old version of the documentation, I recommend you to see: https://shaka-player-demo.appspot.com/docs/api/shaka.Player.html specifically the method `trickPlay(rate)`

**Comment by ManuelBradicic42** [comment]
Thank you, this solved the issue.
