### ISSUE TITLE
Chrome in IOS device with DASH and widevine

### ISSUE THREAD

**Issue by ilgianfra** [google/shaka-player#3924]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes
**What version of Shaka Player are you using?**
3.1.2
**Can you reproduce the issue with our latest release version?**
Last version got problem with safari and fairplay https://github.com/google/shaka-player/issues/3598
**If custom app, can you reproduce the issue using our demo app?**
yes
**What did you do?**
I am trying to play a video in chrome browser in IOS device with DASH and widevine and it doesn't work.
Is it expected? I get error 3016 category 4 - Unsupported source type

thanks!

**Comment by allanbanis** [comment]
Yes it is expected. On IOS shaka only supports hls natively not dash
https://github.com/google/shaka-player/issues/3509#issuecomment-875687681

**Comment by joeyparrish** [comment]
Unfortunately, Apple doesn't give us the tools to play DASH on iOS generally.  The MediaSource standard needed to implement DASH is only available in Safari on iPad and desktop.
