### ISSUE TITLE
Chrome: encrypted Widevine VoD stream fails, clear is good

### ISSUE THREAD

**Issue by karlovich** [google/shaka-player#394]
Hello,

Using shaka player to steram VoD video content. So, playback of clear stream without encryption is good. The same stream encrypted by DASH-CENC(Widevine) fails with the next errors (log from shaka player):
...
 "message": "Shaka Error MEDIA.VIDEO_ERROR (3,)"
...
  "message": "Shaka Error STREAMING.INCONSISTENT_BUFFER_STATE (video)"
...
  "message": "Shaka Error MEDIA.MEDIA_SOURCE_OPERATION_THREW (InvalidStateError: Failed to execute 'appendBuffer' on 'SourceBuffer': The HTMLMediaElement.error attribute is not null.)"

Full log: https://drive.google.com/file/d/0B1bdskC7PG1WNzZONi1nNWJDYWs/view

Logs from chrome://media-internals:
Player Properties
audio_decoder	FFmpegAudioDecoder
debug	DecryptingDemuxerStream: no key
duration	1799.56
error	media::MediaSourceState::Append: stream parsing failed. Data size=131072 append_window_start=0 append_window_end=1799.63
event	WEBMEDIAPLAYER_CREATED
found_audio_stream	true
found_video_stream	true
info	Video codec: avc1.42E01E
pipeline_error	pipeline: decode error
pipeline_state	kStopped
player_id	9
render_id	727
url	blob:http%3A//shaka-player-demo.appspot.com/a736cb8b-4f96-4454-9bfe-1e85240ca912
video_codec_name	h264
video_dds	false
video_decoder	DecryptingVideoDecoder

Log 

Timestamp	Property	Value
00:00:00 00	pipeline_state	kCreated
00:00:00 00	event	WEBMEDIAPLAYER_CREATED
00:00:00 00	url	blob:http%3A//shaka-player-demo.appspot.com/a736cb8b-4f96-4454-9bfe-1e85240ca912
00:00:00 00	pipeline_state	kInitDemuxer
00:00:01 122	duration	1799.56
00:00:02 48	info	Audio codec: mp4a.40.2. Sampling frequency: 44100Hz. Sampling frequency(Extension): 0Hz. Channel layout: 3.
00:00:02 48	found_audio_stream	true
00:00:02 48	audio_codec_name	aac
00:00:02 113	info	Video codec: avc1.42E01E
00:00:02 113	found_video_stream	true
00:00:02 113	video_codec_name	h264
00:00:02 114	pipeline_state	kInitRenderer
00:00:02 307	debug	DecryptingAudioDecoder: failed to init decoder on decryptor
00:00:02 310	audio_dds	true
00:00:02 310	audio_decoder	FFmpegAudioDecoder
00:00:02 312	debug	Video rendering in low delay mode.
00:00:02 336	video_dds	false
00:00:02 336	video_decoder	DecryptingVideoDecoder
00:00:02 336	pipeline_state	kPlaying
00:00:02 338	debug	DecryptingDemuxerStream: no key
00:00:02 995	error	Failed to prepare video sample for decode
00:00:02 995	error	media::MediaSourceState::Append: stream parsing failed. Data size=131072 append_window_start=0 append_window_end=1799.63
00:00:02 995	pipeline_state	kStopping
00:00:02 995	pipeline_state	kStopped
00:00:02 995	pipeline_error	pipeline: decode error

Full log: https://drive.google.com/file/d/0B1bdskC7PG1WVHF2RTRpVEhVTlE/view

Also I can share privately link to the manifest & license server.

Thank you!

**Comment by joeyparrish** [comment]
This looks similar to a DRM filtering bug we fixed incidentally in a644900.  Can you try again with the latest from `master` and let us know if that fixed your issue as well?

**Comment by joeyparrish** [comment]
@karlovich Is this issue still affecting you?  We believe it should be fixed a while ago.  Please let us know.

**Comment by karlovich** [comment]
@joeyparrish Seems that problem was on Content provider side. After some changes on configuration of CENC encrypted MPEG-DASH VOD streams shaka 2.0,0-beta2 was able to stream without this error. Thanks for your response, please close the issue.

**Comment by joeyparrish** [comment]
Thanks!
