### ISSUE TITLE
Avoid cache busting when getting MPD from a Blob

### ISSUE THREAD

**Issue by esteban-dosztal** [google/shaka-player#395]
In order to do some parse work on some MPDs before Shaka parses them, I need to get (fetch()) the MPD text, doing my parse, and then set the result text as a blob: in the src attribte for my <source> element. For this to work, I need to avoid cache busting when the MPD's URL is of the form "blob:...".

**Comment by joeyparrish** [comment]
Thanks for the report.  I'd be happy to have your PR to fix this in v1.x.  It's worth noting that in v2.x (`master` branch), cache-busting is no longer done at all.

Can you give us some details on which browsers support blob URIs directly in XHR?  This is something I was not aware of, and a quick search of MDN did not turn up any information on this.

**Comment by esteban-dosztal** [comment]
I we trust caniuse.com, it seems that all major browsers but Opera Mini support it. http://caniuse.com/#feat=bloburls

Thanks!
