### ISSUE TITLE
Release process failed when run from release branches

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#3968]
The new automated release process failed when run from the release branches.  This same process has been tested on other projects releasing from `main`, but it failed when the branch name was something like `v3.3.x`.

I tracked it down to the release-please tool, specifically this part:
https://github.com/googleapis/release-please/blob/013891caab3a36570711b9fd62a215c3302ef60d/src/util/branch-name.ts#L102

The branch name is matched against several regex, and the first class whose regex matches is chosen as the class to represent this branch in the release strategy.  However, since the branch starts with "v", the first match is `const AUTORELEASE_PATTERN = /^release-?(?<component>[\w-.]*)?-v(?<version>[0-9].*)$/;`

Once the corresponding class is chosen, the constructor then throws an error because the `version` part of the regex can't be parsed.

Ideally:
  1. a caught exception from the constructor would cause the system to roll to the next class/pattern
  2. `AUTORELEASE_PATTERN` would not match the newer branch style of `release-please--`, and would not treat `please` as a component name

I'll turn this into a bug report for release-please, as well.  I'll fork the project and the associated action, get it fixed, and deploy the fork here in Shaka Player until the changes land in a release upstream.

**Comment by joeyparrish** [comment]
Since the v3.3.2, v3.2.4, and v3.1.6 releases failed in the new automation, they will be finished with our old, internal tools.

**Comment by joeyparrish** [comment]
Logs from one of the failed release jobs:

[2_Run google-github-actionsrelease-please-action@v3.txt](https://github.com/google/shaka-player/files/8090608/2_Run.google-github-actionsrelease-please-action%40v3.txt)

**Comment by avelad** [comment]
@joeyparrish I keep seeing errors...sorry...

There are the tags at https://github.com/google/shaka-player/releases, but there is no changelog.

https://github.com/google/shaka-player/blob/master/CHANGELOG.md is not updated
