### ISSUE TITLE
Starting a live stream a bit before live edge

### ISSUE THREAD

**Issue by alexandercerutti** [google/shaka-player#3986]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?** Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes

**What version of Shaka Player are you using?** 3.3.0

**Please ask your question**

Hello there, we have received an internal requirement of starting a live stream a few seconds, an arbitrary and config-driven amount of time, before the live edge, on both Dash and HLS.

Does Shaka provide an integrated configuration parameter to perform automatically such seek instead of having us to perform manual seek after `.load` completes through, I guess, the usage of seekRange's end? Or, perhaps, do you have any other suggestion about how to accomplish this?

Thank you very much!

**Comment by hiren3897** [comment]
Hello @alexandercerutti 
If I understand you correctly you want to seek back to the live edge after `.load`
if yes, then for that you can use `player.goToLive()` method to seek back to live.

**Comment by alexandercerutti** [comment]
Hey @hiren3897, no that's not what I need, but thank you for your help.

Maybe I didn't express correctly (and I edited my message above in the attempt of making it clearer). We don't need to go back to live-edge, but starting a live playback from `live_edge - N`, where N is an arbitrary amount of seconds or milliseconds.

**Comment by hiren3897** [comment]
Hey maybe you can use the `defaultPresentationDelay` to play live-edge -N seconds 
```
manifest: {
      defaultPresentationDelay: xxx // your N seconds here
}
```

**Comment by alexandercerutti** [comment]
Hey there @hiren3897, using `defaultPresentationDelay` along with `ignoreSuggestedPresentationDelay` seems to be the key to achive this result, at least with Dash, but it should work also for HLS. Thank you! I'm closing this and I'll re-open it if I'll have any other doubts. 😄
