### ISSUE TITLE
python build/all.py - fails with linter error

### ISSUE THREAD

**Issue by LucasPiffer** [google/shaka-player#399]
It is only generating dist.js and there is an error:

Running Closure linter...
----- FILE  :  /var/www/html/shaka2/shaka-player/test/player_unit.js on line 666
Line 666, E:0110: Line too long (81 characters). (But i dont believe it is related to the problem as well).

**Comment by LucasPiffer** [comment]
BTW in the tutorial the following code is suggested:

``` shaka.Player.support().then(function(support) {
      // This executes when the asynchronous check is complete.
      if (support.supported) {
        // Everything looks good!
        initPlayer();
      } else {
        // This browser does not have the minimum set of APIs we need.
        console.error('Browser not supported!');
      }
    }); ```

But looking in the Shaka.player there is no definition to support for the current release. In the demo dir there is a working sample.

**Comment by LucasPiffer** [comment]
Maybe the tutorial should adapt to the current version of shaka. Having a look in demo I found:

```shaka.Player.isBrowserSupported() ```

what seems to be the correct way which should be used in tutorial.

**Comment by joeyparrish** [comment]
We are having issues with our build bot and a linter error snuck in.  We'll have it fixed shortly.  As for support, that's a separate issue.  See #402.

**Comment by LucasPiffer** [comment]
thanks. BTW shaka player is amazing! great job.

**Comment by joeyparrish** [comment]
Thanks!  The linter error should be fixed now.  Please let us know if you have any other issues.
