### ISSUE TITLE
Widevine content freezes on WebKit

### ISSUE THREAD

**Issue by ManuelBradicic42** [google/shaka-player#3990]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0

**Please ask your question**
Hi all,

I am developing a Shakaplayer app for my company for a device that is running on WebKit (Safari 8). I'm currently working on the DRM configuration and I came across an issue, which I am not sure if it is a bug or not. I have a widevine content 'tears-of-steel-dash-widevine' and I run it in two situations:

Situation A: initial load is an empty manifest (player.load("")) and when reloading the player with the widevine manifest, the content freezes at the two exact times every time this scenario was reproduced (188 and 284  - top left corner of the stream)
N.B. this happens when the initial manifest is the widevine content.

Situation B: initial load is a clear manifest (angel-one) and after the player was reloaded with the widevine content, the DRM secured content (same one as before) the stream plays perfectly fine and doesn't freeze and the app doesn't crash at those two time points.

I compared HTMLMediaElements in both cases and there is no difference, nor any difference in player.getConfiguration()

Do you have any ideas what could be the reason for failing, and in what direction should I try to debug the player?
I am able to provide code used if necessary.
Thanks

**Comment by ManuelBradicic42** [comment]
Anyone, please?

**Comment by joeyparrish** [comment]
Safari 8 isn't a supported platform.  It could be that bugs in such an old version of WebKit are responsible for the issue.

**Comment by joeyparrish** [comment]
Looks like we had to ban Safari 8 to support multi-period DASH, based on this comment in the MSE polyfill:

```
      // Safari 8 does not implement appendWindowEnd.  If we ignore the
      // incomplete MSE implementation, some content (especially multi-period)
      // will fail to play correctly.  The best we can do is blacklist Safari 8.
```

A version of that comment can be found all the way back to this commit in 2016:
https://github.com/google/shaka-player/commit/32139729adc7030ea8a49833641d1802ffe5296a

I apologize for the inconvenience, but we are unable to support such an old version of WebKit.
