### ISSUE TITLE
shaka.Player.support is not a function - tutorials need updating

### ISSUE THREAD

**Issue by baljitweb** [google/shaka-player#402]
I did followings [in windows 7 OS]: 

- git clone https://github.com/google/shaka-player.git

- put these in head  section:

    `<script src="third_party/closure/goog/base.js"></script>`
   ` <script src="dist/deps.js"></script>`
   ` <script src="shaka-player.uncompiled.js"></script>`

- put my app.js also

- put video tag in index.html

- start server 

- found following errors in console:
base.js:413 goog.require could not find: shaka.offline.DBEnginegoog.logToConsole_ @ base.js:413goog.require @ base.js:446(anonymous function) @ shaka-player.uncompiled.js:40
base.js:448 Uncaught Error: goog.require could not find: shaka.offline.DBEnginegoog.require @ base.js:448(anonymous function) @ shaka-player.uncompiled.js:40
mediakeys.js:52 Using native EME as-is.
promise.js:94 Using native Promises.
app.js:9 Uncaught TypeError: shaka.Player.support is not a function

no idea, is shaka code base is not stable. I got latest one.
Please give solution.

**Comment by LucasPiffer** [comment]
Have a look on it: https://github.com/google/shaka-player/issues/399

If you have a loon in demo folder you'll find a working example for 2.0.

**Comment by baljitweb** [comment]
still not clear....

**Comment by LucasPiffer** [comment]
did you check the load.js in the demo?

**Comment by joeyparrish** [comment]
We recently changed the API and neglected to update the tutorials.  See #388 for the change.  We'll have the tutorial text fixed shortly.

**Comment by joeyparrish** [comment]
The fix has been pushed to `master`.  If you build the tutorials from source (`build/docs.py`), you will see the corrected text.

Please note that the tutorial text on appspot corresponds to our most recent release, which does not include the changes to `support()`.  Our next release, `v2.0.0-beta3`, will contain these changes.

Please let us know if you have any other questions.
