### ISSUE TITLE
Clearkey license servers not working

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#403]
It is not currently possible to use clearkey + license server without setting a custom scheme callback on the DASH parser.  The simple DRM server config should be enough, and was at one time.

**Comment by joeyparrish** [comment]
Reported via the mailing list: https://groups.google.com/forum/#!msg/shaka-player-users/5nT5ooVRCtw/eCuwkhibAgAJ

The fix should include a demo asset which uses a simple clearkey license server to verify the functionality.

**Comment by johnBartos** [comment]
@joeyparrish What versions does this affect?

**Comment by joeyparrish** [comment]
This was broken in 0530362b on June 3.  It does not affect any release versions, including the betas of v2.  We'll get it fixed before we release v2.0.0-beta3.
