### ISSUE TITLE
'org.w3.clearkey' is missing from default key systems

### ISSUE THREAD

**Issue by maxbykov** [google/shaka-player#406]
Hi,
How ClearKey with license server workflow described [here](https://github.com/google/shaka-player/blob/master/docs/tutorials/drm-config.md#clear-key-licenses) can be implemented after [this](https://github.com/google/shaka-player/commit/0530362b97c74753cf2620f959b0f0beb55e702e#diff-41e08de95a956fe36a8c164274d22b7fL94) change? Or, what is the way to make manifest specify ClearKey now?
Before that, having `schemeIdUri="urn:uuid:1077efec-c0b2-4d02-ace3-3c1e52e2fb4b"` in `ContentProtection` was enough.

thanks in advance,
max

**Comment by maxbykov** [comment]
duplicated https://github.com/google/shaka-player/issues/403

**Comment by joeyparrish** [comment]
Yes, we broke this in a recent change.  When we started checking for license server URLs _after_ choosing key systems, clearkey in the default set would mean the possibility of clearkey being chosen over actual DRM schemes on Chrome or Firefox, even without a clearkey config (keys or license server).
