### ISSUE TITLE
Deprecating Powerful Features on Insecure Origins

### ISSUE THREAD

**Issue by raskri** [google/shaka-player#407]
I have this issue in the back of my head: requiring secure origins for EME(requestMediaKeySystemAccess).
Ref: https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-powerful-features-on-insecure-origins

How should we as developers deal with this deprecation? Since there is no ETA on it. 
Please forgive me if this is not the fora to discuss this.

**Comment by joeyparrish** [comment]
I think it might be worth discussing on the EME spec github.  Shaka Player can't really do anything to affect this.  The platform APIs and their restrictions are what they are (or in this case, will be).

Our demo app, demo content, and Google-owned license servers are all available over https.  Our library and demos work equally well over both http and https, so we've done what we can to be ready.

If https becomes a requirement for EME in future, EME-based applications would have to be served over https.  You can either start migrating now or push back on the spec.

**Comment by joeyparrish** [comment]
https://github.com/w3c/encrypted-media/ is a good place for further discussion.

**Comment by joeyparrish** [comment]
Chrome has announced a deprecation timeline for EME in insecure contexts.  Support will be dropped at the end of March 2017.  In case you missed it on the mailing list, here's the post I made about it: https://groups.google.com/forum/#!topic/shaka-player-users/L0dYA3TcAkA

**Comment by raskri** [comment]
Thanks Joey!
