### ISSUE TITLE
Cannot read property 'setRestrictions' of null

### ISSUE THREAD

**Issue by sanbornhnewyyz** [google/shaka-player#41]
If you try to setRestrictions on a player instance before you provide a video source, you'll get an error: Cannot read property 'setRestrictions' of null.

I propose that we either:

1. Throw a more descriptive error such as 'There is no video source available to set restrictions on.' 
2. Or, check if the video source is defined and if not, don't call videoSource.setRestrictions, and instead make sure that when a videoSource is instantiated it calls setRestrictions on itself. This way if someone tries to setRestrictions before a video source is loaded, they'll get set the way they expect.

**Comment by joeyparrish** [comment]
True story.  I am doing a small refactor on Restrictions right now, and I will have this fixed as part of that.

**Comment by sanbornhnewyyz** [comment]
Alright, great! I don't know what tack you plan to take but I just want to register my support for something along the lines of (2). I think it is desirable to be able to setup the player with restrictions prior to loading content.

**Comment by joeyparrish** [comment]
Yes, it will be along the lines of #2, and will also remove the restrictions parameter from the license post processing callback.  This simplifies some things in EmeManager and makes the restrictions API more consistent.  Restrictions are then always set on the Player and set by the application, even if they are derived from a license response.
