### ISSUE TITLE
Seekbar leaves out last period of multi-period dash manifest

### ISSUE THREAD

**Issue by TheJohnBowers** [google/shaka-player#4103]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.3.2 - The live appspot demo

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
I haven't tried, just from the appspot demo 3.3.2

**Are you using the demo app or your own custom app?**
Demo app

**If custom app, can you reproduce the issue using our demo app?**
NA

**What browser and OS are you using?**
Firefox/Chrome both reproduce the issue

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
NA

**What are the manifest and license server URIs?**

See:
https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://content.uplynk.com/033bd925734e4b7fb6c522bf97869333.mpd?ad.preroll=1&ad=cleardashnew;panel=CUSTOM%20CONTENT;build=uncompiled

https://content.uplynk.com/033bd925734e4b7fb6c522bf97869333.mpd?ad.preroll=1&ad=cleardashnew
https://content.uplynk.com/wv

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Default for demo player

**What did you do?**

See:
https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://content.uplynk.com/033bd925734e4b7fb6c522bf97869333.mpd?ad.preroll=1&ad=cleardashnew;panel=CUSTOM%20CONTENT;build=uncompiled

Scrub near the end.  There is ad inserted right as the sintel credits start, and the asset should come back to content after that (sintel credits), but the scrubbar doesn't include enough length to include the final period, and playback stops after the ads, and doesn't come back to content.

**What did you expect to happen?**
I expect the credits to be the final period, I expect for the scrubbar to reflect the same total duration as the timing element.

**What actually happened?**

The time on the srub bar shows something like (and the exact numbers depend on the ads that get inserted), 17:47-19:40, yet playhead has reached the end of the scrubbar even though the timer says there should be more -- AND playback stops there.
(see screenshot)

**Comment by TheJohnBowers** [comment]
Screenshot
https://www.dropbox.com/s/idol5mejsklbfcs/Screen%20Shot%202022-04-07%20at%2010.59.35%20AM.png?dl=0

**Comment by avelad** [comment]
Can you test with v4.3.4 and main branch? Thanks!
