### ISSUE TITLE
Question: Does iOS 10 support MediaSource yet?

### ISSUE THREAD

**Issue by aletorrado** [google/shaka-player#414]
Hi,

Have anyone tried the iOS 10 Preview, and tested if it supports MediaSource yet?

Thanks :)

**Comment by joeyparrish** [comment]
I had a colleague try [our support test page](http://support.shaka-player-demo.appspot.com) on iOS 10 preview, and it appears that it still does not have MSE support.  We'll keep our fingers crossed for iOS 11.  :-)

**Comment by OrenMe** [comment]
Asked a developer at WWDC. Doesn't seem like it's in the top of their priorities.
Told me to file an enhancement request radar J.

**Comment by neilRGS** [comment]
Tested as at Feb 7th 2017.  IOS still can't use Shaka (Tried Safari and Chrome on iPad).
Shame on you, Apple!

**Comment by Portmansa** [comment]
One question though, how does dashjs play on ios?

**Comment by joeyparrish** [comment]
@Portmansa, does dashjs indeed play on iOS?  I haven't been able to make their [demo page](http://dashif.org/reference/players/javascript/v2.5.0/samples/dash-if-reference-player/index.html) work on iOS at all.

caniuse.com reports that MediaSource is still not available on iOS 10.3: http://caniuse.com/#feat=mediasource

Just searching quickly through dashjs source, I see that [MediaPlayer's initialize() method fails if `MediaSource` is not present](https://github.com/Dash-Industry-Forum/dash.js/blob/bd9cbc08a271def803eca8fe285ab7472a6211c7/src/streaming/MediaPlayer.js#L143).  Further, [the `MediaSource` check allows for a prefixed version called `WebKitMediaSource`](https://github.com/Dash-Industry-Forum/dash.js/blob/be4350883185f22b5f50c3ad6e29c0402c70d584/src/streaming/utils/Capabilities.js#L43).

So it would seem that the only way iOS could be supported in dashjs directly is if `WebKitMediaSource` were available on iOS.  I just checked both Safari & Chrome on iOS 10.3, and WebKitMediaSource is not defined.

**Comment by Portmansa** [comment]
@joeyparrish Yeah, I got it working on iOS with HLS. Live streaming was working too

**Comment by joeyparrish** [comment]
iOS has a native HLS implementation.  Essentially, when you use HLS with dashjs, you aren't using dashjs for playback at all.

**Comment by Portmansa** [comment]
@joeyparrish BTW, can shaka player play HLS on iOS?

**Comment by joeyparrish** [comment]
Shaka Player only uses MediaSource.  If you want to bypass MediaSource, then you don't need Shaka Player.  Just do something like `video.src = '/foo.m3u8';`.  I'm not sure what value Shaka Player could add in that scenario.

**Comment by mayeaux** [comment]
Do we have any idea when Apple plans to support MSE API?

**Comment by joeyparrish** [comment]
Sorry, we don't know anything.  Any authoritative answers about about future MSE support on iOS would have to come from Apple.

However, we will support a fallback to iOS's native HLS support in #997.

**Comment by joeyparrish** [comment]
Oh, and here are links to Apple's bug trackers if you are interested in talking to them:

Apple Bug Reporter: https://developer.apple.com/bug-reporting/
WebKit BugZilla: https://bugs.webkit.org/
