### ISSUE TITLE
play, pause, end and complete events

### ISSUE THREAD

**Issue by baljitweb** [google/shaka-player#416]
How can I track shaka player's play, pause, end and complete events in javascript.
How can I save bookmark [means already played video history] so that when user comes back again shaka start playing where he/she left earlier.

**Comment by tdrews** [comment]
Hi, you can listen to events directly from the video element:
```javascript
video.addEventListener('playing', onPlaying);
video.addEventListener('pause', onPause);
video.addEventListener('ended', onEnded);
```
To save playback position you can save video.currentTime in your application.
The next time you start playback you can pass that time to `load()`, e.g.,
```javascript
var player = new shaka.Player(video);
player.load(manifestUri, lastPlaybackPosition);
```

**Comment by baljitweb** [comment]
thank you
