### ISSUE TITLE
v1.x: InvalidAccessError w/ ClearKey on Chrome

### ISSUE THREAD

**Issue by mohitYogi** [google/shaka-player#417]
##This code is working perfectly fine with FF 47, but it is not working in chrome.
It is showing an error "InvalidAccessError: Invalid Response."
I am attaching the mpd file, xml file used for encrypting and the source code.
I have encrypted the video stream and left audio unencrypted.

[shaka-error.zip](https://github.com/google/shaka-player/files/321761/shaka-error.zip)

 @joeyparrish

**Comment by joeyparrish** [comment]
@mohitYogi I will need access to the content to help you debug this.  Your manifest references oggy_audio_dashinit.mp4 and oggy_encrypt_video_dashinit.mp4, but these are not present in the zip file.

Can you provide these files as an attachment or as a publicly accessible URL?  Either would work equally well for me.

**Comment by mohitYogi** [comment]
@joeyparrish  yes, for sure.
Here they are:

[shaka-test.zip](https://github.com/google/shaka-player/files/331257/shaka-test.zip)

**Comment by mohitYogi** [comment]
the code is also not working on IE 11. So, till tested only FireFox runs it properly.

**Comment by joeyparrish** [comment]
If I recall correctly, IE 11 does not support Clear Key at all.  Only Chrome, Opera, and Firefox support Clear Key at the moment.

There is a simple fix for your sample code.  In addition to the `kid` and `k` fields, you need to add `kty: 'oct'` to your JSON web keys.  This is required by the Clear Key CDM in more recent versions of Chrome.

In Shaka v2, we offer a simplified clearkey configuration interface to help you avoid details like this.  Check out the "Clear Key" section of [v2's DRM Configuration tutorial](http://shaka-player-demo.appspot.com/docs/api/tutorial-drm-config.html) if you're interested.

Let us know if we can do anything else to help.

**Comment by mohitYogi** [comment]
@joeyparrish, I have tried that earlier and tried it now but still not working.
It doesn't show any error, the player displays total time of video, but still doesn't plays the video.
It doesn't even plays the audio which is unencrypted.
Help me with this, it can be a silly mistake but still can't figure it out.

**Comment by joeyparrish** [comment]
Take the sample code you sent me and modify this:

```js
var keyObj = {
  kid: Uint8ArrayUtils.toBase64(keyid,false),
  k: Uint8ArrayUtils.toBase64(key,false)
};
```

to this:

```js
var keyObj = {
  kty: 'oct',
  kid: Uint8ArrayUtils.toBase64(keyid,false),
  k: Uint8ArrayUtils.toBase64(key,false)
};
```

That solves the InvalidAccessError.  But you are right, your content still does not play.  If you open chrome://media-internals and find the player instance that matches your `video.src`, you can see logs of what Chrome's media pipeline is doing.  For me, it has lots of errors decoding your audio:

```
Dropping audio frame which failed decode with timestamp: 0 us, duration: 23219 us, packet size: 285 bytes
Dropping audio frame which failed decode with timestamp: 23219 us, duration: 23219 us, packet size: 286 bytes
Dropping audio frame which failed decode with timestamp: 46439 us, duration: 23219 us, packet size: 285 bytes
Dropping audio frame which failed decode with timestamp: 69659 us, duration: 23219 us, packet size: 291 bytes
Dropping audio frame which failed decode with timestamp: 92879 us, duration: 23219 us, packet size: 303 bytes
```

However you encoded this content, it appears to be broken.  What packager did you use to create this?

**Comment by mohitYogi** [comment]
@joeyparrish I have used Mp4Box to encrypt and encode this content.

**Comment by joeyparrish** [comment]
@mohitYogi Please report the decode failures to Mp4Box.  You should include the repro case you sent me (the fixed version), along with instructions to use `chrome://media-internals` to see the decode errors from Chrome.

**Comment by mohitYogi** [comment]
@joeyparrish  Log cats and fixed version of html file.
[shaka-error.zip](https://github.com/google/shaka-player/files/345643/shaka-error.zip)

**Comment by joeyparrish** [comment]
@mohitYogi  Please file a bug report with Mp4Box.  Chrome cannot decode your content, so this is not a bug in Shaka.  My best guess is that the content is encoded incorrectly, so you should report this bug to Mp4Box.

**Comment by joeyparrish** [comment]
I believe this is the issue tracker for Mp4Box: https://github.com/gpac/gpac/issues

**Comment by mohitYogi** [comment]
@joeyparrish I can understand that there is a problem in encoding the content then how FireFox is able to play it?
and apart from that, can you tell me what other tools I can use to encode the content??? your suggetions will be helpful..

**Comment by joeyparrish** [comment]
Different browsers have different decoders, and some decoders are more flexible and forgiving than others.

There's nothing wrong with using Mp4Box, and I'm sure that if there is a bug, they would probably like to know so they can fix it.  Or perhaps they have already fixed it and you will just need to upgrade.  All software benefits from good bug reports, so please consider filing a report.

Personally, I use ffmpeg to encode into various resolutions and [Shaka Packager](http://github.com/google/shaka-packager) to package the content.  You may have better luck with those.  It is easy to compile ffmpeg with the wrong options or without the encoders you need, so be careful with that.
