### ISSUE TITLE
Improved support for in-progress recording

### ISSUE THREAD

**Issue by baconz** [google/shaka-player#423]
We are having some issues getting our in-progress recordings to play in Shaka2.

We'd like to be able to set a `mediaPresentationDuration` on a dynamic manifest, so that we can create a scrubber bar that shows both the total duration of the recording, and the `availabilityEnd`.

If we set the MPD to the full duration of the recording, and we don't have enough segments to fill it, `fitSegmentReferences` will extend our last reference to the length of the MPD. That wouldn't be an issue, except `getLiveEdge` uses `maxSegmentDuration` in its calculation, and so our live edge (and availability end) calculation gets messed up.

Our solution for now is to treat in-progress-recordings as live and pass the duration out of band, but that feels wrong.

I *think* the right solution might be to add an `isLive()` check to `fitSegmentReferences` that uses `timeShiftBufferDepth` instead of `periodDuration` as a proxy to live.

It seems like the IOP doesn't have a great story for dynamic manifests with a known end-time, so I'm happy to submit an issue to DASH-IF if you think that's a good next step.

**Comment by tdrews** [comment]
> I think the right solution might be to add an isLive() check to fitSegmentReferences that uses timeShiftBufferDepth instead of periodDuration as a proxy to live.

Yes, `fitSegmentReferences()` should only extend the last segment for VOD... It's "live check" should be similar to `PresentationTimeline.isLive()`.

**Comment by joeyparrish** [comment]
Appears to have been fixed by pull #426.  Closing.
