### ISSUE TITLE
Add channelcount information on audio tracks

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#424]
For get the channels count, only it's necessary read the value parametrer on AudioChannelConfiguration node.

Two examples:

1) 2 channels
```xml
<AdaptationSet id="11" contentType="audio" lang="en" subsegmentAlignment="true">
      <Representation id="14" bandwidth="132318" codecs="mp4a.40.2" mimeType="audio/mp4" audioSamplingRate="48000">
        <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
        <BaseURL>a-eng-0128k-aac.mp4</BaseURL>
        <SegmentBase indexRange="745-1844" timescale="48000">
          <Initialization range="0-744"/>
        </SegmentBase>
      </Representation>
    </AdaptationSet>
```

2) 6 channels
```xml
<AdaptationSet
 mimeType="audio/mp4"
 codecs="dtse"
 lang="en"
 audioSamplingRate="48000"
 startWithSAP="1"
 subsegmentStartsWithSAP="1" >
 <AudioChannelConfiguration
 schemeIdUri="urn:dts:dash:audio_channel_configuration:2012"
 value="6"/>
 <ContentComponent id="100" contentType="audio"/>
 <Representation id="a1" bandwidth="192000">
 <BaseURL>dtse_192_dash.mp4</BaseURL>
 <SegmentBase indexRangeExact="true" indexRange="852-920"/>
 </Representation>
 <Representation id="a2" bandwidth="256000">
 <BaseURL>dtse_256_dash.mp4</BaseURL>
 <SegmentBase indexRangeExact="true" indexRange="853-921"/>
 </Representation>
 <Representation id="a3" bandwidth="384000">
 <BaseURL>dtse_384_dash.mp4</BaseURL>
 <SegmentBase indexRangeExact="true" indexRange="852-920"/>
 </Representation>
 <Representation id="a4" bandwidth="510000">
 <BaseURL>dtse_510_dash.mp4</BaseURL>
 <SegmentBase indexRangeExact="true" indexRange="853-921"/>
 </Representation>
 </AdaptationSet>
```

We would expect something like this for audio track:
{active: true, bandwidth: 132318, **channelcount: 2,** hasOutputRestrictions: false, height: null, id: 20, kind: null, language: "en", type: "audio", width: null}

**Comment by joeyparrish** [comment]
Sounds fairly easy.  We'll see if we can fit it into v2.0.0.  One change, though:  I'd prefer the member to be named "channels" instead of "channelcount".  Any objections?

**Comment by avelad** [comment]
Go!! channels name is perfect

**Comment by joeyparrish** [comment]
Actually, now that we've looked into it, this is not so clear.  The DASH spec has some very confusing text about the meaning of the `value` attribute, and we can't convince ourselves that this is supposed to be the number of channels.  The spec text around this also refers to multiple other spec documents, one of which we don't currently have access to.

Because of all this, I am going to defer this enhancement.  We can look again after v2.0.0 is complete.  Sorry!

**Comment by avelad** [comment]
@joeyparrish , do you have any update about this?

**Comment by joeyparrish** [comment]
Sorry, I do not have an update.  I need to track down the relevant spec text again, as I have lost my notes on the topic.  This time, I will leave my notes on github.

**Comment by TheModMaker** [comment]
A while ago, I filed Dash-Industry-Forum/DASH-IF-IOP#124 for clarification.  The DASH-IF have updated their site to be more clear.  However, we still don't have access to the `ISO/IEC 23003-3` spec required.

**Comment by avelad** [comment]
ExoPlayer is using the value attribute for audioChannel: https://github.com/google/ExoPlayer/blob/release-v2/library/dash/src/main/java/com/google/android/exoplayer2/source/dash/manifest/DashManifestParser.java#L708-L717

And a pull request of DolbyLaboratories (https://github.com/google/ExoPlayer/pull/3085) is using the same (https://github.com/DolbyLaboratories/ExoPlayer/blob/a9062ff28378734c0bab7086a6c7664554c37a79/library/dash/src/main/java/com/google/android/exoplayer2/source/dash/manifest/DashManifestParser.java#L689-L700)

**Comment by joeyparrish** [comment]
@avelad, the interpretation of value depends on the scheme ID.  I will be publishing a more detailed plan soon.
