### ISSUE TITLE
problem with close captions

### ISSUE THREAD

**Issue by hexapodo1** [google/shaka-player#4250]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
 2.5.6.

**Please ask your question**
Hi guys,
I'm working on the support of a couple of applications for Disney, these applications use shaka player to show live contents.
We have a problem with the close captions when the user go to another section and return to the live content, we are saving the state of the close caption on the local storage and we restore that state from there, the thing is... when the shaka player is load and we call to the setTextVisibility(...), sometimes we get the expected behavior (should show the CC when CC are on), sometimes is does not work.
We are using the version 2.5.6.
If someone can suggest something to us, we appreciate it.

thank you a lot

**Comment by joeyparrish** [comment]
Unfortunately, we stopped supporting v2.5 in June of last year.

My first advice would be to try the latest release in the v2.5 branch.  We backported fixes to that branch for a long time.  The final release of v2.5 was v2.5.23, and it should be fully backward compatible with v2.5.6.

If that doesn't resolve the issue, the next thing you should try is upgrading.  The branches we are still fixing today are v3.2, v3.3, and our recent branch v4.0.  You should refer to our [upgrade guide](https://shaka-player-demo.appspot.com/docs/api/tutorial-upgrade.html) and take care with API incompatibilities introduced in v3.0 and v4.0.  If you still need IE support for any reason (dropped in v3.1), you will have to polyfill the browser yourself to be able to use a recent release there.

In v3.2, we introduced a new closed caption parser, so if you upgrade, you will no longer need mux.js for closed captions.  (You do still need it for HLS+TS content.)

If you're still having this issue with a release branch we are still supporting, let us know and we'll talk about repro steps and look for a solution.

Thanks!
