### ISSUE TITLE
Demo app UI on Android - click to start playback

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#432]
The demo app controls on Android do not make it clear that a click is required to start playback.  (Autoplay is disabled by Chrome on Android.)  The demo app controls should detect this and show the giant play button as if the video were paused.

**Comment by tranzitwww** [comment]
Hi,
It works if you add "autoplay" and "muted" to the video element.
Also check that the browser has enabled "autoplay" on Android Chrome 
[Settings] - [Site Settings] - [Media] - [Autoplay] and Allow Autoplay.

https://developers.google.com/web/updates/2016/07/autoplay
