### ISSUE TITLE
Sometimes ad UI lingers after ad

### ISSUE THREAD

**Issue by theodab** [google/shaka-player#4341]
I don't think this is a common issue, but I just got a problem where, after an ad run, the ad UI did not go away.

Looking at the logs, it appears this is the result of the server side ad manager not receiving certain events from the IMA SDK. It saw the `adBreakStarted`, `started`, and `adBreakEnded` events, but nothing else. No `complete` event, notably, which is what triggers our ad UI to go away.

Notably, looking at the logs, that particular ad break had only a single ad, when the other ad breaks on this content seem to mostly be delivering 2-3 ads. So this might be some kind of internal failure inside the IMA SDK.

The ad UI had gotten stuck saying it was at `Ad 3 of 3 0:03 / 0:14`, so that suggests the ad was badly lagging, or perhaps ended early somehow.

Perhaps we should also hide the ad UI after the `adBreakEnded` event, if this is a problem that can happen?

**Comment by avelad** [comment]
I tried to reproduce the issue and it doesn't seem to happen anymore so I'll close it.
