### ISSUE TITLE
2.0.0-beta2 ABR always chooses lowest quality representation (constant low-bandwidth estimate)

### ISSUE THREAD

**Issue by mnylen** [google/shaka-player#436]
Hello,

I'm having weird problem when moving from beta1 -> beta2 that ABR in beta2 always chooses and keeps the lowest-quality representation and doesn't even try switching to a higher quality.

This might be because

```
player.getConfiguration().abr.manager.getBandwidthEstimate()
```

is always returning the same, default 500000, bandwidth estimate originally configured, whereas in beta1 the estimate would change between calls to that function as more data was downloaded.

The code used for initializing the player:

    const player = new shaka.Player(video);
    player.load("/stream.mpd");

    // after user click
    video.play();

I'm using the compiled cdnjs build from here:

```
https://cdnjs.cloudflare.com/ajax/libs/shaka-player/2.0.0-beta2/shaka-player.compiled.js
```

One of the MPDs I'm having issues with (unfortunately can't provide the media files for this atm):

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<MPD mediaPresentationDuration="PT29.547S" minBufferTime="PT1.500S" profiles="urn:mpeg:dash:profile:isoff-on-demand:2011" type="static" xmlns="urn:mpeg:dash:schema:mpd:2011">
    <Period duration="PT29.547S">
        <AdaptationSet segmentAlignment="true" subsegmentAlignment="true" subsegmentStartsWithSAP="1">
            <Representation bandwidth="11852042" codecs="avc1.42c028" frameRate="30" height="960" id="VIDEO-1" mimeType="video/mp4" startWithSAP="1" width="1920">
                <BaseURL>video/1920x960.mp4</BaseURL>
                <SegmentBase indexRange="902-1053" indexRangeExact="true">
                    <Initialization range="0-901"/>
                </SegmentBase>
            </Representation>
            <Representation bandwidth="6462764" codecs="avc1.42c028" frameRate="30" height="672" id="VIDEO-2" mimeType="video/mp4" startWithSAP="1" width="1344">
                <BaseURL>video/1344x672.mp4</BaseURL>
                <SegmentBase indexRange="902-1053" indexRangeExact="true">
                    <Initialization range="0-901"/>
                </SegmentBase>
            </Representation>
        </AdaptationSet>
        <AdaptationSet>
            <Representation audioSamplingRate="48000" bandwidth="130110" codecs="mp4a.40.2" id="AUDIO-1" mimeType="audio/mp4" startWithSAP="1">
                <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
                <BaseURL>audio/128k.mp4</BaseURL>
                <SegmentBase indexRange="832-983" indexRangeExact="true">
                    <Initialization range="0-831"/>
                </SegmentBase>
            </Representation>
        </AdaptationSet>
    </Period>
</MPD>
```

In this MPD, the 1344x672 representation would be chosen.

I tried digging around for changes between beta1 and beta2, but couldn't find anything that should affect this - the only thing changed in `SimpleAbrManager` was the addition of track restrictions.

**Comment by mnylen** [comment]
Hmm... have to check again tomorrow, but I'm testing this when serving from localhost and EwmaBandwidthEstimator has in beta2 started ignoring samples that are either less than 64 KB or took less than 200 ms to download... It could be that... though I tried with network throttling in chrome inspector.

**Comment by mnylen** [comment]
Starts looking like a duplicate of this https://github.com/google/shaka-player/issues/367

**Comment by mnylen** [comment]
Yep, closing issue - fixed in master. Same problem as #367

**Comment by joeyparrish** [comment]
Yes, you are right.  Sorry for the trouble, but we will be releasing beta3 from master soon.
