### ISSUE TITLE
Invalid state on MediaSource.endOfStream internal call is causing general exception

### ISSUE THREAD

**Issue by Ross-cz** [google/shaka-player#440]
Hi guys,

I get sometimes general DOMException, when I seek to the end:
Error category: 3, code: 3015
Data: 
DOMException: Failed to execute 'endOfStream' on 'MediaSource': The MediaSource's readyState is not 'open'. at Error (native) at .<anonymous>
Stack trace:
(anonymous function) (VM136975 bundle.js:24286)
(anonymous function) (VM136975 bundle.js:24356)
Promise.resolve (async)
shaka.media.MediaSourceEngine.enqueueBlockingOperation_ ()
shaka.media.MediaSourceEngine.endOfStream ()
shaka.media.StreamingEngine.onUpdate_ ()
setTimeout (async)
shaka.media.StreamingEngine.scheduleUpdate_ ()
shaka.media.StreamingEngine.seeked ()
shaka.Player.onSeek_ ()
shaka.media.Playhead.onSeeking_ ()
seeking (async)
.. video set current time

Related shaka code:
shaka.media.MediaSourceEngine.prototype.endOfStream = function(opt_reason) {
451	  return this.enqueueBlockingOperation_(function() {
452	    // Chrome won't let me pass undefined, but it will let me omit the
…	
456	      this.mediaSource_.endOfStream(opt_reason);
457	    } else {
458	      this.mediaSource_.endOfStream();
459	    }
460	  }.bind(this));

I think there shouldn't be call to endOfStream when readyState equals ended.

**Comment by joeyparrish** [comment]
What browser are you using?  Is this reproducible in the nightly build of the demo app?  http://nightly.shaka-player-demo.appspot.com/demo/

**Comment by Ross-cz** [comment]
This was captured using Chrome 51.0.2704.103 m.
Codebase is same.

I don't have test case for this, but it could be related to DRM expired license key & seeking to the end.

**Comment by joeyparrish** [comment]
The codebase may be the same, but I'm asking if you can reproduce it with our app.  If not, the cause may be in your own application code.

**Comment by Ross-cz** [comment]
Is there demo for short DRM expiring license? (5 min)
Do I need to check, whether I am seeking to the end and whether video ended, before every change to currentTime?

**Comment by joeyparrish** [comment]
We don't have a demo for that, but you can put a custom manifest and license server URL into the demo app.  At the bottom of the list of assets is "(custom asset)".  Select that and boxes will appear to allow you to put in your own manifest and license server URLs.

It's not clear to me why seeking to the end would result in an exception.  As far as I know, no seek should be able to cause this.  But if you can reproduce it on the demo app, we will be much better able to diagnose it.

**Comment by joeyparrish** [comment]
@Ross-cz, were you able to make any progress on this?  Is this still an issue for you?

**Comment by Ross-cz** [comment]
Hi @joeyparrish , I was on holidays.

I just put if statement (if (this.mediaSource_.readyState !== 'ended')) into code:
```
shaka.media.MediaSourceEngine.prototype.endOfStream = function(opt_reason) {
  return this.enqueueBlockingOperation_(function() {
    // Chrome won't let me pass undefined, but it will let me omit the
    // argument.  Firefox does not have this problem.
    // TODO: File a bug about this.
  	if (this.mediaSource_.readyState !== 'ended') {
  		if (opt_reason) {
  			this.mediaSource_.endOfStream(opt_reason);
  		} else {
  			this.mediaSource_.endOfStream();
  		}
  	}
  }.bind(this));
};
```

It could be a fix. I used following info about readyState: https://developer.mozilla.org/en-US/docs/Web/API/MediaSource/readyState

Btw Chrome (and probably other browsers) don't handle DRM expired licenses - video is streaming, no Error state, no ended state, it just don't play decrypted content... I don't want to create issue on this, because I don't have testing license server with short term licenses for you.

**Comment by joeyparrish** [comment]
Checking readyState seems fine in general, but I still can't reproduce your issue.

Please try again with the latest code from `master` or with the nightly build.  We're definitely handling expired licenses through key status events.  With the setup below, I get the error `DRM.EXPIRED`:

Asset: http://storage.googleapis.com/shaka-demo-assets/sintel-widevine/dash.mpd
License server: http://cwip-shaka-proxy.appspot.com/fastexpire
Full demo: http://nightly.shaka-player-demo.appspot.com/demo/?asset=//storage.googleapis.com/shaka-demo-assets/sintel-widevine/dash.mpd;license=//cwip-shaka-proxy.appspot.com/fastexpire;play

**Comment by Ross-cz** [comment]
Thanks, I was not able to reproduce it again.
