### ISSUE TITLE
Request: gitter channel

### ISSUE THREAD

**Issue by ajbeach2** [google/shaka-player#445]
I feel as though gitter channel would be helpful for answerings/asking questions for the community.

**Comment by joeyparrish** [comment]
Our [README](https://github.com/google/shaka-player/blob/master/README.md) points to [our users mailing list](https://groups.google.com/forum/#!forum/shaka-player-users), which is meant for exactly these sorts of community discussions.  Github issues are more appropriate for tracking bugs and feature work.
