### ISSUE TITLE
Impact of 'Allow AbrManager to clear ahead of the playhead' commit on Edge and IE11

### ISSUE THREAD

**Issue by BucherTomas** [google/shaka-player#446]
Recent commit 'Allow AbrManager to clear ahead of the playhead' is very welcome, it will require some additional optimization for Edge and IE11 browsers, though.

Whenever a switch to another bitrate takes place with these browsers, clearing no longer needed data from the buffer and buferring the new bitrate is causing major visible hiccups in playback. Chrome/Opera and Firefox are fine in this regard.

Any multibitrate streams can be used to repro this.

**Comment by joeyparrish** [comment]
Thanks for the report.  Probably has something to do with the MSE optimization we did as part of that change.  We'll take a look.

**Comment by joeyparrish** [comment]
Clearing ahead is causing the hiccup.  On Chrome, Opera, and Firefox, the hiccup is fixed by calling abort() to reset the decoder.  On IE and Edge, the abort() call has no effect.  On Safari, the abort() call causes the decoder to fail completely.  :-(

**Comment by joeyparrish** [comment]
@BucherTomas can you please retest with the latest code from `master` or with the [nightly build on appspot](http://nightly.shaka-player-demo.appspot.com/demo/)?  We believe this is resolved now for Edge and IE11.

**Comment by BucherTomas** [comment]
Yes, I can confirm that the transition when adapting is now smooth on Edge and IE11. Thanks.

I have no means to verify Safari at this moment, though.

**Comment by joeyparrish** [comment]
Please don't worry about Safari.  The Safari issue seems to be separate.
