### ISSUE TITLE
v1.x: Improve DASH parser performance w/ large timeshift depths

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#449]
In #405, we improved DASH parser performance for large timeshift depths by deferring filling URI templates.  Investigate whether or not this can be easily implemented in v1.6.x as well.

**Comment by joeyparrish** [comment]
@torerikal mentioned that this fix was in their fork: vimond@adbcdb5

@torerikal, @janouskovec, any interest in cleaning it up and creating a PR?

I think it's a good start, but the subclass should call the base class's constructor instead of re-creating all of its members.  There also doesn't seem to be any need to make everything protected, just make `urls` non-const.

**Comment by janouskovec** [comment]
In fact no need creating PR for me, because I already fixed the issue in my local repository and push now to my fork: [janouskovec@Deferring filling URI templates](https://github.com/janouskovec/shaka-player/commit/cc95b2c84afcd4159b28aea529af14f9107d55c2).

**Comment by joeyparrish** [comment]
Okay, closing for lack of interest.  If anybody wants to patch v1 for this, please feel free to reply and we can reopen.
