### ISSUE TITLE
EME Editor's Draft Incompatibilities

### ISSUE THREAD

**Issue by dansanders** [google/shaka-player#45]
`EmeManager` creates configurations that are not compatible with the current EME Editor's Draft. In particular, it can create empty lists for `initDataTypes`, `audioCapabilities`, and `videoCapabilities`; these are rejected in the current draft. If there are no requirements, the members should not be present in the configuration dictionary at all.

Somewhat trickier is that `sessionTypes` must now be specified for `createSession()` to operate. This isn't necessary if only `"temporary"` sessions are created, but Shaka will try to create `"persistent-license"` sessions without asking for them.

**Comment by dansanders** [comment]
It's worth noting that the ideal behavior is to always fill in these lists, since it is not a good user experience to fail to play media after calling `requestMediaKeySystemAccess()`. (`requestMediaKeySystemAccess()` could initiate a user prompt or download a CDM, for example.)

**Comment by joeyparrish** [comment]
Reproduced in Chrome 43.0.2353.0.

**Comment by joeyparrish** [comment]
Tested working in Chrome 41, 42, and 43.
