### ISSUE TITLE
Adaption NOT working

### ISSUE THREAD

**Issue by ajbeach2** [google/shaka-player#460]
Here is a JS fiddle that demonstrates the issue. Basically, after the player is loaded, I call a function which reconfigures the player to have a higher default bandwidth estimate.  The stream NEVER updates to the highest bitrate. What is going on here and what am I doing wrong?

https://jsfiddle.net/yh95LL4o/19/

```javascript
var manifestUri = 'https://yt-dash-mse-test.commondatastorage.googleapis.com/media/car-20120827-manifest.mpd';

function jump(to){
	var video = document.getElementById('video');
  video.currentTime = to;
}

function resolution(height){
	var player = window.player
  var tracks = player.getTracks()
  track = tracks.find(function(x){if(x.height === height){return x}});
	player.selectTrack(track, true)
}

window.resolution = resolution;
window.jump = jump;

function initApp() {
  shaka.polyfill.installAll();
  shaka.Player.support().then(function(support) {
    if (support.supported) {
      initPlayer();
    } else {
      console.error('Browser not supported!');
    }
  });
}

function setDefaultBandWidth(){
    var config = {abr: {
	    enabled: true,
  	  defaultBandwidthEstimate: 8e5
    }};
    var abr = new shaka.abr.SimpleAbrManager();
    abr.setDefaultEstimate(8e5);
    config.abr.manager = abr;
    config.abr.defaultBandwidthEstimate = 8e5;
    window.player.configure(config);
}

function initPlayer() {
  var video = document.getElementById('video');
  var player = new shaka.Player(video);
  window.player = player;
  player.addEventListener('error', onErrorEvent);
  player.addEventListener('adaptation', onTrackChanged);
  
  player.load(manifestUri).then(function() {
    console.log('The video has now been loaded!');
    setDefaultBandWidth();
    console.log(window.player.getConfiguration());
  }).catch(onError);  // onError is executed if the asynchronous load fails.
}

function onErrorEvent(event) {
  onError(event.detail);
}

function onTrackChanged(event){
}

function onError(error) {
  console.error('Error code', error.code, 'object', error);
}

initApp();
```

**Comment by op1ekun** [comment]
Well, your Fiddle works just fine for me. The video switches to the highest bitrate around 36th second.
If you want to react to subtle bitrate changes you should probably listen to the "bandwidth" event, and than change the tracks on your own.

**Comment by joeyparrish** [comment]
Works for me, too.  But I notice that your fiddle also loads v2.0.0-beta2 from cdnjs.  The problem is not that it never adapts, but that it does not clear the data it has already buffered when it adapts to a higher resolution, so it may take a while to see the effect.

We fixed this in 6daa7f3b by clearing ahead of the playhead when adapting to a higher resolution.  Please try again with a new build from `master` to confirm.  The fix will appear in v2.0.0-beta3 release.

**Comment by ajbeach2** [comment]
I am going to close this, as the  v2.0.0-beta3 works as expected for me.

**Comment by joeyparrish** [comment]
Great, thanks for letting us know.
