### ISSUE TITLE
Support EventStream

### ISSUE THREAD

**Issue by baconz** [google/shaka-player#462]
Per sections 5.3.2.4 and 5.3.3.7 of the IOP, we should support EventStream in DASH manifests. An EventStream contains Event elements that reference _ranges_ in the timeline. When the playhead hits one of these ranges, the event fires, and delivers the payload of the underlying Event element.

The IOP is not very clear on how this functionality should be implemented, but we have three example use-cases that might inform the behavior:
1. Fire a beacon when a user views an ad
2. Change the page context when an ad is in-progress (eg different banner)
3. Prevent users from scrubbing past ad pods, or take action when they attempt to scrub past ad pods

I can imagine three types of events that Shaka fires, all would contain the payload and the range covered by the event.
1. `timelineeventstart`: fired when the playhead hits a point referenced by an `Event` element. Maybe we can listen to `timeupdate` on the video element for this?
2. `timelineeventend`: fired when the playhead leaves a point referenced by an `Event` element.
3. `timelineeventcreated`: fired when a new event is added to the timeline. This gives us an easy way to track the positions of the events for use-cases like the third listed above.

This is related to, but distinct from EMSG box support, referenced in #259.

If we can agree on a design, I'm happy to put up a PR.

**Comment by joeyparrish** [comment]
This seems pretty reasonable, but I'd like to defer it until after we wrap up v2.0.0.

**Comment by birme** [comment]
One use case I have been working with is to repackage HLS with SCTE35 base encoded data to multi period MPEG DASH [1] where I add 

    xmlns:scte35="urn:scte:scte35:2014:xml+bin" 

to MPD root element and then adds an EventStream with this payload:

```
  <Period id="2470350023" start="PT27448.333589S">
    <EventStream timescale="90000" schemeIdUri="urn:scte:scte35:2014:xml+bin">
      <Event duration="21690000" id="1">
       <scte35:Signal>
         <scte35:Binary>
           /DAlAAAAAAAAAP/wFAUAAAAEf+/+kybGyP4BSvaQAAEBAQAArky/3g==
         </scte35:Binary>
       </scte35:Signal>
      </Event>
    </EventStream>
```

It would be great if this use case also could be supported and I am happy to contribute with a PR if it sounds like a good idea to support.

[1] https://github.com/Eyevinn/hls-to-dash

**Comment by baconz** [comment]
@joeyparrish is this on your roadmap for the near/medium term? If not, we can take a stab at it.

**Comment by joeyparrish** [comment]
We have not scheduled this work.  A PR would be welcome, and I have no issues with the three-event design you laid out in the original post.  Thanks!

**Comment by joeyparrish** [comment]
@baconz, are you working on this at the moment?  If not, I will try to schedule it for our team.

**Comment by baconz** [comment]
@joeyparrish we have not started on it yet. If you could schedule it that would be great.

**Comment by TheModMaker** [comment]
Now we will fire JavaScript events for the EventStream elements.  The design is similar to @baconz design, but the event names are a little different.  The three events are `timelineregionadded`, `timelineregionenter`, and `timelineregionexit`.

We also do not parse the Event node.  So if you want to get the scte35 info (or anything that is in the Event), you have to parse it in the app.
