### ISSUE TITLE
Periods are not being switched automatically during playback (regression)

### ISSUE THREAD

**Issue by Ross-cz** [google/shaka-player#463]
Using Heliocentrism demo on the beta-2 site http://shaka-player-demo.appspot.com/demo/ playback works.
Using Heliocentrism demo on the v2.0.0-beta2-140-g022226c-debug http://nightly.shaka-player-demo.appspot.com/demo/ plays only 1.999201 sec and wheel keeps rotating.

**Comment by joeyparrish** [comment]
Confirmed.  Thanks for the report.

**Comment by joeyparrish** [comment]
Bisect shows it was broken by ab865518.  @baconz as JFYI

**Comment by baconz** [comment]
Sorry about that! Looking

**Comment by baconz** [comment]
Looks like this manifest has no MPD, but is static. I didn't realize that was allowed.

Thoughts on keying off of `type` to determine whether a manifest `isLive`? It seems like that's the best possible indicator.

**Comment by joeyparrish** [comment]
No MPD?

**Comment by joeyparrish** [comment]
Oh, you mean mediaPresentationDuration?  Yes, that's definitely allowed.  The presentation duration can be derived from period durations.

**Comment by baconz** [comment]
Got it. Thoughts on using `type` for this?

**Comment by joeyparrish** [comment]
Your in-progress VOD content has a known, finite duration, correct?  And type="static" or type="dynamic"?  It would be helpful to have a public sample of such content we could use if this type of content is something we want to continue to support.

**Comment by baconz** [comment]
Yep, exactly. Here's a summary of how it is set up right now: https://github.com/google/shaka-player/pull/442#issuecomment-232222000

I can update with a sample mpd in a bit.
