### ISSUE TITLE
Widevine playout seems broken under android

### ISSUE THREAD

**Issue by soualid** [google/shaka-player#470]
Hello,

I used to play widevine protected stream without issue under Android, and I just figured out that the Tears of Steals (widevine) and Sintel 4k (Widevine) on http://shaka-player-demo.appspot.com/demo/ do not play anymore on my device.

In fact, no widevine stream plays on my test android devices.

Thank you in advance for your help.

**Comment by joeyparrish** [comment]
Tears of Steel (widevine) and Sintel 4k (widevine) are both playing fine for me on v2.0.0-beta2 and on the [nightly build](http://nightly.shaka-player-demo.appspot.com/demo/).

What Android device do you have?  Is there an older version of Shaka Player that does work for you?

Here are links to older versions to make it easier for you to test:

[nightly](http://nightly.shaka-player-demo.appspot.com/)
[v2.0.0-beta2](http://v2-0-0-beta2.shaka-player-demo.appspot.com/)
[v2.0.0-beta](http://v2-0-0-beta.shaka-player-demo.appspot.com/)
[v1.6.5](http://v1-6-5.shaka-player-demo.appspot.com/)
[v1.5.2](http://v1-5-2.shaka-player-demo.appspot.com/)
[v1.4.2](http://v1-4-2.shaka-player-demo.appspot.com/)
[v1.3.2](http://v1-3-2.shaka-player-demo.appspot.com/)
[v1.2.4](http://v1-2-4.shaka-player-demo.appspot.com/)

**Comment by soualid** [comment]
Good to hear, must be a problem with my device... which is a Sony Xperia XA (F3111) running latest chrome under Android 6.0, all the versions listed failed to play the widevine protected streams (clear streams are played without issue). 

On my old HTC One running latest chrome under Android 4.2.2, the widevine items are disabled, but this one is a little outdated.

I'll try with another device as soon as I return to work. 

Thank you !

**Comment by joeyparrish** [comment]
Widevine didn't become available to Android Chrome until Android 4.4, so those items are disabled on 4.2.2.  We query the browser to find out which key systems are supported and disable the assets that won't work.

**Comment by soualid** [comment]
This is really weird, I have the exact same behaviour on a brand new Wiki Ufeel (model U FEEL) under Android 6.0 and latest chrome. 

Checked with 2 different connections (Wi-Fi and cellular), and with all the versions linked, the same widevine streams works well on the desktop. Nothing special in the logs, I recorded a screencast of the device remote debug available here : http://www.oualid.net/temp/shaka-issue.mov

Note that I was not able to test the nightly build because the widevine streams appears unavailable  (menu disabled) using this version of shaka player.

Here are some warnings found in the console :

```It is recommended that a robustness level be specified. Not specifying the robustness level could result in unexpected behavior in the future, potentially including failure to play.```

And :

```The last segment should not end before the end of the Period. s…a.m…a.SegmentReference {position: 48, startTime: 240.24, endTime: 242.70116666666667, uris: Array[1], startByte: 12019155…}```

**Comment by joeyparrish** [comment]
I just tried two phones running Android 6.0 and I was unable to reproduce your issue on either of them.

It's curious that the nightly build disables the Widevine streams.  That only happens if Widevine is unavailable on the device.  It seems plausible that a previous build did not correctly disable those streams, but the nightly build *does* disable them because your device *actually can't* play them.

Widevine is only available on official builds of Android from Google.  Do these devices run AOSP or Cyanogen or some other variant of Android?

**Comment by soualid** [comment]
Nope, both are fresh factory install of official Android 6 system provided by the phones vendors (Sony and Wiko). I also tried to factory reset both of them.

The problem is clearly that the Widevine plugin is not enable on these phones, in fact, no plugin at all are enable since `console.log(navigator.plugins);` returns an empty array on both phones.

Also tried to reset DRM on the phones settings.

This is really confusing, I'll try to find another phone today to do further test. I was initially trying to fix a play issue on our "shaka based player" located at : http://artestudio.biz.st/player/demo.html and http://artestudio.biz.st/player/demo-noskin.html which reproduce the same problem under shaka 2.0.0-beta and shaka 2.0.0-beta2.

These warnings appears in the logs on both Android and desktop, but stream plays well on desktop.

> shaka-player.compiled.js:65 
> requestMediaKeySystemAccess() is deprecated on insecure origins in the specification. Support will be removed in the future. You should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.
> 
> shaka-player.compiled.js:65 
> It is recommended that a robustness level be specified. Not specifying the robustness level could result in unexpected behavior in the future, potentially including failure to play.
> 
> contentType strings without codecs will not be supported by requestMediaKeySystemAccess() in the future. Please specify the desired codec(s) as part of the contentType.

**Comment by soualid** [comment]
Closing this issue, tried with a Alcatel one touch idol 3 under Android 6.0 and everything worked as expected, there must be a - huh... confusing - problem with my 2 others devices.

Thank you for your answers.

Simon
