### ISSUE TITLE
element.getAttribute is not a function error in v2 beta3

### ISSUE THREAD

**Issue by mlondon1** [google/shaka-player#473]
Hi,
I am seeing the following error in Shaka player v2.0.0-beta3 that I do not see in beta2 when attempting to play my Widevine-Dash VOD content in Google Chrome

streaming_engine.js:1148 (text:3) failed fetch and append: code=undefined(anonymous function) @ streaming_engine.js:1148
player.js:1614 Assertion failed: Wrong error type!shaka.Player.onError_ @ player.js:1614(anonymous function) @ streaming_engine.js:1149
main.js:182 Player error TypeError: element.getAttribute is not a function(…)

**Comment by joeyparrish** [comment]
Can you please provide a manifest URL with which I could reproduce this error?

**Comment by joeyparrish** [comment]
@mlondon1, we cannot reproduce.  Can you provide a manifest URL that reproduces the error?

**Comment by mlondon1** [comment]
Hi, This is encrypted premium content, is there anything else that I can provide?  Or do you not need to play the content and just want to look at the MPD?

**Comment by joeyparrish** [comment]
We need some way to reproduce your issue before we can solve it.  Can you provide instructions on how to reproduce the issue?

Usually, a good repro involves a manifest URL and license server URL that can be used in the demo app.  If you can't provide those things publicly, you can always send me a private email with the details.  My email address can be found in CONTRIBUTORS.

**Comment by joeyparrish** [comment]
Thanks for the manifest info.  I've tracked the bug down to here:

```js
shaka.media.TtmlTextParser.getInheritedAttribute_ = function(
    element, attributeName) {
  var ret = null;
  while (element) {
    ret = element.getAttribute(attributeName);
```

Now that we have repro, it should be easy to fix.  Thanks!

**Comment by mlondon1** [comment]
You're welcome

**Comment by joeyparrish** [comment]
@mlondon1, please try again with the latest from `master` and let us know if you have any issues.
