### ISSUE TITLE
URL signing API

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#475]
As [reported on the mailing list](https://groups.google.com/forum/#!msg/shaka-player-users/f8Jxb43vbOY/B6khafH_CQAJ), an API for signing segment URLs would be useful for those using Amazon S3 or CloudFront.

This can be done today with a subclass of shaka.dash.DashParser, but a simple API for this would be preferable.  Signing could be done with a more generic manifest-filtering API, but something that only processes segment URLs would be much easier to use.

**Comment by ajbeach2** [comment]
Actually, I am not sure this makes sense anymore.  AWS recommends using signed cookies instead of signed urls when distributing content from cloudfront.  In this case, the shaka player would need to be able to support sending multiple cookie headers for the manifest, and segment urls.

**Comment by joeyparrish** [comment]
We do support cookie authentication.  See the "Cookie Authentication" section of the ["License Server Authentication"](http://nightly.shaka-player-demo.appspot.com/docs/api/tutorial-license-server-auth.html) tutorial.  The filters in the tutorial are looking for license requests, but you could just as easily accept manifest and/or segment requests, too.

Should we go ahead and close this feature request, then?

**Comment by ajbeach2** [comment]
Yeah I would say close it

**Comment by joeyparrish** [comment]
Okay, thanks for your feedback.

**Comment by JLHasson** [comment]
@joeyparrish Is the suggested method above (editing manifest with pre-signed urls) the best way to achieve this at this time? I am attempting to load content from an S3 bucket that is not public, and believe I am running into a similar problem as discussed on the mailing list link above. I am pre-signing the link to the manifest, and feeding that into shaka-player, however when it attempts to load each segment it does not have access as the base urls from the manifest have not been pre-signed.

**Comment by joeyparrish** [comment]
No.  In the year since this issue was closed, we've introduced asynchronous network filters (starting in v2.1, current release is v2.2.1), which are ideal for this type of authentication.  In short, you can delay a request while you fetch an authentication token, then attach the token and let the original request proceed.  There is a tutorial showing how this works:

https://shaka-player-demo.appspot.com/docs/api/tutorial-license-server-auth.html

You should skim through the tutorial to find the section which applies to your form of authentication: parameters, headers, or cookies, whichever is appropriate to your application.  Then pay special attention to the section called "Asynchronous Credentials", which will show how best to fetch auth tokens.

Although it is geared toward license server authentication, you can apply it to any requests, including segment or manifest requests.

Does that help?

**Comment by JLHasson** [comment]
Hey, sorry taking so long to get back to you. I think this could possibly work, but I need to dig into it more. Will be back if it doesn't! Thanks for the help! 😄
