### ISSUE TITLE
Reimplement in-progress recording support

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#477]
We reverted a mostly-complete in-progress recording (IPR) solution in `da03f439` due to #463.  I have been working with @baconz to define requirements and will reimplement with a different model for v2.0.0.

**Comment by joeyparrish** [comment]
@baconz, please try the latest from master and let us know how it's working for you.

**Comment by baconz** [comment]
@joeyparrish lgtm. It works with our content.

The demo player is a bit messed up, though. I think it should either only let you seek to `seekRange.end` or we should introduce a differentiation between the scrubbable range and the width. Right now it will let you seek into an unbufferable range.

**Comment by joeyparrish** [comment]
I think as long as we're using `<input type="range">`, the entire width of the scrubber will always be usable.  I don't believe we can say "size as if it's 0-100, but reject 62-100".

Technically speaking, we could render our own scrubber without using `<input>`, but we are not going to invest a lot into UI changes for the demo right now.

So I think the scrubber's range will just have to grow as the recording progresses, so that the user can't seek to an unavailable position.  You can, of course, do something sleeker for your own app.

Sound reasonable?

**Comment by baconz** [comment]
Yep, sounds perfect.

**Comment by joeyparrish** [comment]
Better?

**Comment by baconz** [comment]
Yes, looks good.

One more small issue: I think IPRs should take the `presentationDelay` into account when calculating the `seekRangeEnd`.

**Comment by joeyparrish** [comment]
Okay, should be fixed now.

**Comment by baconz** [comment]
Sweet, thanks.
