### ISSUE TITLE
Shaka Error DRM.LICENSE_RESPONSE_REJECTED (Rejected with system code (28))

### ISSUE THREAD

**Issue by randeeppr** [google/shaka-player#482]
Hi,

We are trying to use CENC with Fixed key with live channels. 

For packaging we use Envivio JIT Packager. There we have specified Key and Key ID.
Same key and Key id we have specified in content_key_specs in widevine proxy server. 

But when we play from Chrome browser with Shaka player, we get the following error.
```
Shaka Error DRM.LICENSE_RESPONSE_REJECTED (Rejected with system code (28))
```
What could be the reason?
Regards,
Randeep

**Comment by joeyparrish** [comment]
If the license response was rejected by the CDM, you probably made a mistake in your license server proxy somehow.  The system code 28 refers to the reason the response was rejected, but the meaning of these Widevine codes has not been published as far as I know.

If you can provide a hex dump of the license response, I may be able to get someone to analyze it and get back to you.  Would that work?

**Comment by randeeppr** [comment]
@joeyparrish 
We are using Envivio JIT packager to package the dash. In its CENC configuration, we can give only one key and keyid.

Do we need to encrypt video and audio using different keys? Else CDM will reject it?
Can you please send an email to randeep123@gmail.com so that I can reply to you with the license details.

I have created a ticket with widevine also. Some details are there. Hope you have access to that.
Ticket details : [8-1842000012930] CENC with custom Key

**Comment by joeyparrish** [comment]
@randeeppr, I am able to generate system code 28 by using a proxy which passes an invalid key to the license server backend.  Please make sure your keys and key IDs are 128 bits and are encoded in base64.

**Comment by randeeppr** [comment]
@joeyparrish, Thank you. This error was fixed by giving Key ID of 128 bit length. I had to prefix "0"s before encoding with base64.
