### ISSUE TITLE
Can't play without the required codecs

### ISSUE THREAD

**Issue by ajbeach2** [google/shaka-player#486]
https://jsfiddle.net/8b3uvuyx/

This jsfiddle demonstrates the issue. Shaka player does not work on chromium on OS X.
It throws the following errors. This JsFiddle works in chrome and firefox

![Chromium Console](http://i.imgur.com/MtIBgju.png)

I am using version Version 52.0.2743.116 (64-bit)  of Chromium on OS X 10.11.4 (15E65)

**Comment by ajbeach2** [comment]
I am guessing my build of chromium doesn't support mp4/mp3. I would need to rebuild it with support for those codecs.

**Comment by joeyparrish** [comment]
@ajbeach2, this is working as intended.  If you don't have the required codecs, you can't play the content.  If you take a look at the docs for [shaka.util.Error](http://nightly.shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html), you'll see that error 4011 is `UNPLAYABLE_PERIOD`:

> The manifest contains a period with no playable streams. Either the period was originally empty, or the streams within cannot be played on this browser or platform.
