### ISSUE TITLE
MEDIA.VIDEO_ERROR

### ISSUE THREAD

**Issue by randeeppr** [google/shaka-player#489]
Hi,

I am trying to play a widevine modular drm encrypted live stream encrypted using Envivio JIT packager with single key and key id.  I had issues like chrome CDN rejecting the license because of the invalid Key_id. We have corrected it. But right now we are getting following error.  Sometimes on the video we can see random color patterns also.
```
Using native EME as-is.
Using native Promises.
requestMediaKeySystemAccess() is deprecated on insecure origins in the specification. Support will be removed in the future. You should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.
It is recommended that a robustness level be specified. Not specifying the robustness level could result in unexpected behavior in the future, potentially including failure to play.
Updating manifest...
Player error s…a.u…l.Error {category: 3, code: 3016, data: Array[2], message: "Shaka Error MEDIA.
 (3,)", stack: "Error: Shaka Error MEDIA.VIDEO_ERROR (3,)↵    at n…shaka2/shaka-player-master/lib/player.js:1521:17)"}
(audio:3) failed fetch and append: code=3015
Player error s…a.u…l.Error {category: 3, code: 3015, data: Array[1], message: "Shaka Error MEDIA.MEDIA_SOURCE_OPERATION_THREW (In…he HTMLMediaElement.error attribute is not null.)", stack: "Error: Shaka Error MEDIA.MEDIA_SOURCE_OPERATION_TH…yer-master/lib/media/streaming_engine.js:1305:36)"}
Updating manifest...
```
What can be the issue? Shaka/Widevine doesnt allow anything without audio and video encrypted separately? 

Regards,
Randeep

**Comment by joeyparrish** [comment]
`MEDIA.VIDEO_ERROR` corresponds to a decoder failure.  Check `chrome://media-internals` for details on the decoder error.  JavaScript has no visibility into why this failed.

This usually means that your content is not compatible with the browser's decoder in some way.  Often this means the content is broken, but occasionally the same content will play on other platforms.  What OS are you on?  There are some known issues with some content failing in the platform's decoder on Mac.

**Comment by randeeppr** [comment]
@joeyparrish, OS is Windows 8.

**Comment by joeyparrish** [comment]
Please check `chrome://media-internals` for details on the decoder error.

**Comment by randeeppr** [comment]
@joeyparrish, I couldnt see anything in that. And I am not able to reproduce the error also. Now on the chrome there is no error and I can see this. But no errors. 
![shaka_1](https://cloud.githubusercontent.com/assets/2521992/17743382/2ce8f2c6-64c1-11e6-8341-7fbd3d49007d.PNG)

**Comment by randeeppr** [comment]
Not sure this is Shaka's.
```
Property	Value
debug	Dropping audio frame which failed decode with timestamp: 1992089467 us, duration: 0 us, packet size: 284 bytes
player_id	129
render_id	14
Log 
property filter

Timestamp	Property	Value
00:00:00 00	debug	Dropping audio frame which failed decode with timestamp: 1843353467 us, duration: 0 us, packet size: 304 bytes
00:00:00 00	debug	Dropping audio frame which failed decode with timestamp: 1843374800 us, duration: 0 us, packet size: 252 bytes
00:00:00 00	debug	Dropping audio frame which failed decode with timestamp: 1843396133 us, duration: 0 us, packet size: 293 bytes
00:00:00 01	debug	Dropping audio frame which failed decode with timestamp: 1843417467 us, duration: 0 us, packet size: 278 bytes
00:00:00 01	debug	Dropping audio frame which failed decode with timestamp: 1843438800 us, duration: 0 us, packet size: 247 bytes
00:00:00 01	debug	Dropping audio frame which failed decode with timestamp: 1843460133 us, duration: 0 us, packet size: 243 bytes
00:00:00 02	debug	Dropping audio frame which failed decode with timestamp: 1843481467 us, duration: 0 us, packet size: 251 bytes
```

**Comment by joeyparrish** [comment]
The blocks and green bands are caused by a decoder failure.  You can get details from the browser by going to `chrome://media-internals` and clicking the button which corresponds to the value of `video.src` in your app.  When you click that button, you should see logs from the media pipeline.  Report that information to your encoder vendor.

Decode is outside the control of JavaScript and therefore Shaka Player.  If your content can't be decoded, you will need to report that to the maker of the software that encoded your content.

**Comment by joeyparrish** [comment]
@randeeppr Is there anything else we can do for you on this?

**Comment by randeeppr** [comment]
@joeyparrish, Evivio fixed this. Now its playing fine. Thank you Joey. Closing this.
