### ISSUE TITLE
Widevine Classic / subtitles

### ISSUE THREAD

**Issue by roberb04** [google/shaka-player#494]
Does the current version of Shaka Player support Widevine Classic DRM or only Widevine Modular?

I need a player to test the addition of subtitles to Widevine Classic .wvm packages and the way to do that is to reference both the .wvm and the subtitle file within a SMIL file as described in Widevine_SMIL_Specification_1.0.pdf

Many thanks!

**Comment by joeyparrish** [comment]
Shaka Player runs on top of the MSE standard and can only play consent using containers supported by the browser.  No browser supports wvm natively, so this is not possible with Shaka Player.  Sorry.

**Comment by joeyparrish** [comment]
I believe [Shaka Packager](https://github.com/google/shaka-packager) can transmux wvm to DASH, though, so that may be an option for you.

**Comment by roberb04** [comment]
Hi Joey,

Thanks for getting back to me. Unfortunately the transmux option won't work for me because I have to demonstrate subs within Classic/WVM/SMIL package.

The original Shaka Player did support Classic/WVM of course - do you know if it also supported the SMIL manifest? If it did, is there a v1 tag you'd recommend me to download and build for this project?

Thanks again,
Bruce.

**Comment by joeyparrish** [comment]
I'm sorry, but you're mistaken.  Shaka Player has never supported Widevine Classic for the reasons stated above.  We can only support content in containers supported by the browser, and no browser has ever natively supported Widevine Classic content.

You can easily access the demo pages of older versions of Shaka Player if you are skeptical.  Here's a link to [v1.6.5](https://v1-6-5.shaka-player-demo.appspot.com/) .

**Comment by roberb04** [comment]
In that case I am mistaken - sincere apologies! I'm now trying to perform my tests using the demo Widevine (Classic) browser client with the Widevine plugin in Firefox. I've got that working with my WVM packages but haven't yet tested with the SMIL manifest and subtitles. Fingers crossed.

Thanks for putting me straight about Shaka Player!

**Comment by joeyparrish** [comment]
No worries!  We're always happy to help.
