### ISSUE TITLE
Support for Representations with different container types (mp4/webm) in the same AdaptionSet

### ISSUE THREAD

**Issue by rcollins112** [google/shaka-player#503]
Not sure of this is a bug or expected behavior...

- What version of Shaka Player are you using?
Shaka Player v2.0.0-beta3-debug at http://shaka-player-demo.appspot.com/demo/
Using latest Chrome browser (Version 52.0.2743.116 m) on a Windows 7 machine.

- What did you do?
Using Wowza Streaming Engine as the media server, I am trying to play a DASH presentation that contains multiple video and audio renditions, including a mixture of mime/container types, webm (vp9 & opus) and mp4 (avc & aac).  In the MPDs from Wowza, all video renditions are included in the same video AdaptionSet, and all audio renditions are included in the same audio AdaptionSet (which should be legal as far as I can tell).  A sample SegmentTimeline MPD is attached.
[sample.mpd.txt](https://github.com/google/shaka-player/files/445936/sample.mpd.txt)

- Issue
When using the SegmentTimeline MPD format, Shaka will not play begin playback of of the presentation for some reason.  No console errors are reported.  When the MPD is modified to only include webm a/v renditions or only include mp4 a/v renditions then playback is fine.

The SegmentTemplate with @duration and SegmentList MPD formats seem to play fine with all of the renditions included in the MPD, however the demo player does not appear to list all of the renditions available in the Audio/Video Tacks dropdowns.  It seems that it first chooses a preferred container/mime type for each content type (audio/video) and then only provides the renditions available for those types in the respective dropdown.  For example Shaka defaultly chooses the single webm-opus audio rendition and does not show the other renditions (both of which are mp4-aac) in the Audio Tracks dropdown.  This may just be by design in the demo player and that's fine, but thought I should point it out.  The SegmentTimeline behavior is the one I'm more concerned about.

Is Shaka possibly expecting different container/mime types to always be listedin different AdaptionSets?
If so it seems like a bug.  The DASH spec does not levy that requirement (section 5.3.3.1).

I can provide a test stream if desired.

Thanks,
Rich

**Comment by joeyparrish** [comment]
We definitely support multicontainer/multicodec content, but different container types must be in different AdaptationSets.  Please check for updates from Wowza, and if this is still the way manifests are generated in the latest version, you should report this to Wowza as a bug.

We have several examples of this in our demo assets.  Anything under the "Shaka" section in the asset list with "multicodec" in the description contains both WebM/VP9 and MP4/H.264.  All of those assets were created with our sister project, [Shaka Packager](https://github.com/google/shaka-packager).  Shaka Packager always puts different containers into different AdaptationSets.

The meaning of an AdaptationSet is that it is a set of things you can seamlessly adapt between.  That means containers and codecs must be compatible, and that is why they must appear in different AdaptationSets.

The DASH spec does not acknowledge WebM, and WebM DASH is an extension to that spec.  However, [DASH IOP (Inter-Operability Points) v3.0](http://dashif.org/w/2015/04/DASH-IF-IOP-v3.0.pdf), section 3.2.10.2 states:

> Adaptation Sets shall contain Media Segments compatible with a single decoder ... when multiple Representations are present. 

Hope that helps!

**Comment by rcollins112** [comment]
Hmm, ok.  So based on "compatible with a single decoder", does that mean AVC, HEVC, VP8, and VP9 content should all be in separate video AdaptionSets.  And AAC, HE-AAC, AC-3, E-AC-3, Vorbis and Opus content should all be in separate audio AdaptionSets?  But variations of any one of those codecs can be listed in the same AdaptionSet? (eg AVC baseline/main/high or HE-AAC v1/v2)
Thanks in advance!

**Comment by joeyparrish** [comment]
Yes, exactly right.  AAC, Vorbis, Opus are not using the same decoder.  Same for AVC, HEVC, VP8, VP9.  So each of those should get its own AdaptationSet.  Variations in AVC profile are okay in the same AdaptationSet because they use the same decoder.

**Comment by rcollins112** [comment]
Great thanks for the quick feedback!  I'll go ahead and close the issue.
