### ISSUE TITLE
Stream interrupted if TTML <div> is empty

### ISSUE THREAD

**Issue by ewosleger** [google/shaka-player#506]
Note: submitting issue as per earlier correspondence.

We have some assets that have promos without TTML data in the TTML \<div>.
These assets throw the following error:
( I am using uncompiled.js, latest beta btw, for the error verboseness)
Error code shaka.util.Error {
  "category": 2,
  "code": 2001,
  "data": [],
  "message": "Shaka Error TEXT.INVALID_TEXT_CUE ()",
  "stack": "shaka.util.Error@http://localhost:8881/common/shaka/lib/util/error.js:77:13\nshaka.media.TtmlTextParser.parseCue_@http://localhost:8881/common/shaka/lib/media/ttml_text_parser.js:223:11\nshaka.media.TtmlTextParser@http://localhost:8881/common/shaka/lib/media/ttml_text_parser.js:81:17\nshaka.media.Mp4TtmlParser@http://localhost:8881/common/shaka/lib/media/mp4_ttml_parser.js:44:12\nshaka.media.TextEngine.prototype.appendBuffer/<@http://localhost:8881/common/shaka/lib/media/text_engine.js:126:16\n”
}

approx.: Line 212: cueElement.getAttribute('begin'), rateInfo);
Our asset during the intro promo doesn’t have any embedded data in the TTML \<div>. Not until the promo is over and main content starts playing does the proper embedded TTML data begins to be streamed.

Because line 222: if (start == null || end == null) 
This cause the error to be throw since neither start nor end are assigned values until the promo is over and main content begins playback.

Proving my theory,
At the beginning of the method shaka.media.TtmlTextParser.parseCue_ 
I added the simple check:
if(cueElement.hasAttribute('begin') == false)
    Return;

TTML Data:
TTML element that throws errors.
\<tt xmlns="http://www.w3.org/ns/ttml" xmlns:smpte="http://www.smpte-ra.org/schemas/2052-1/2010/smpte-tt" xmlns:m608="http://www.smpte-ra.org/schemas/2052-1/2010/smpte-tt#cea608" xmlns:ttm="http://www.w3.org/ns/ttml#metadata" xmlns:ttp="http://www.w3.org/ns/ttml#parameter" xmlns:tts="http://www.w3.org/ns/ttml#styling" xml:lang="en" ttp:frameRate="24" ttp:frameRateMultiplier="1000 1001" ttp:timeBase="media">
\<head>
\<body>
\<div>\</div>
\</body>
\</tt>

Notice the \<div> element is empty. 
Begin, end and dur attributes are not present and therefore null.

This is the very first TTML element the parser method receives from an asset that has been behaving correctly:
\<tt xmlns="http://www.w3.org/ns/ttml" xmlns:smpte="http://www.smpte-ra.org/schemas/2052-1/2010/smpte-tt" xmlns:m608="http://www.smpte-ra.org/schemas/2052-1/2010/smpte-tt#cea608" xmlns:ttm="http://www.w3.org/ns/ttml#metadata" xmlns:ttp="http://www.w3.org/ns/ttml#parameter" xmlns:tts="http://www.w3.org/ns/ttml#styling" xml:lang="en" ttp:frameRate="24" ttp:frameRateMultiplier="1000 1001" ttp:timeBase="media">
\<head>
\<body>
\<div>
\<p begin="00:00:18.291" end="00:00:20.083" region="pop1" style="basic" tts:extent="45% 5.33%" tts:origin="25% 84.66%">(THUNDER RUMBLING)\</p>
\<p begin="00:00:58.458" end="00:00:59.541" region="pop1" style="basic" tts:extent="20% 5.33%" tts:origin="62.5% 84.66%">(GRUNTS)\</p>
\<p begin="00:00:59.916" end="00:01:01.500" region="pop1" style="basic" tts:extent="52.5% 5.33%" tts:origin="10% 84.66%">Dinner's ready, kids!\</p>
\</div>
\</body>
\</tt>

**Comment by ismena** [comment]
@ewosleger Ahh, I've been hoping to fix this before you have a chance to open the issue :)

The fix is out, please let us know if you have any questions.

**Comment by ewosleger** [comment]
Everything appears to be working correctly. Thanks for the quick collaboration.
