### ISSUE TITLE
When the video is playing ,use the code "shakaDemo.load("another video");" sometime wrong

### ISSUE THREAD

**Issue by jjs1233** [google/shaka-player#507]
hi

 , thank you for solving my problem which is about "CORS header",
but after that time I was ill in hospital,so when I want to thank the Issue has been closed;

but now I encountered a new problem I When the video is playing ,use the code "shakaDemo.load("another video");" to change the video which is playing it makes a wrong

this is the error code

player.js:1635 
Assertion failed: Wrong error type!
   shaka.Player.onError_ @ player.js:1635
   shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:726

main.js:148 
Player error DOMException: Failed to read the 'buffered' property from 'SourceBuffer': This SourceBuffer has been removed from the parent media source.(…)
  shakaDemo.onError_ @ main.js:148
  shakaDemo.onErrorEvent_ @ main.js:134
  shaka.util.FakeEventTarget.dispatchEvent @ fake_event_target.js:109
  shaka.Player.onError_ @ player.js:1638
  shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:726

**Comment by jjs1233** [comment]
It also not happen very often

Often there will be a third was a failure

**Comment by jjs1233** [comment]
In addition to say if the code used in the console of browser it worked never make mistake

Buy if I use the ajax `

            var aj = $.ajax({
                url:'/delete_vtt',
                beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
                data:{
                    start:start,
                    end:end
                },
                // async: false,
                type:'post',
                cache:false,
                dataType:'script',
                succes:function(data){
                },
                error:function(){
                    console.log(2);
                }
            });
`

the ajax return value is the rails format.js
`<% if @symbol.nil? %>

alert('wrong!');

<% else %>

shakaDemo.load("/videolib/three/a/a.mpd");

<% end %>`

**Comment by ismena** [comment]
Hi @jjs1233,
Thanks for reaching out!
Could you please give us a bit more detail about the issue, we have [an issue template](https://github.com/google/shaka-player/blob/master/.github/ISSUE_TEMPLATE.md) that might help.

From what I understand the repro goes as following:
1) Successfully start playback of an asset
2) While the video is playing open console in a browser and execute the command "shakaDemo.load("another video");" where "another video" is a path to the video.
3) An error occurs

Is my understanding correct or did I miss something?
What browser are you using?

**Comment by jjs1233** [comment]
- What version of Shaka Player are you using?
   
the version is 2.0
- Are you using the demo app or your own custom app?
 
this is my own custom app 
I want to achieve the function of online editing subtitles file
- What did you do?

when the video is playing send send a Ajax request the return is script 
which is shakaDemo.load("/videolib/three/a/a.mpd"); //just reload the video address

- What did you expect to happen?

the video load success

- What actually happened?

this is the error code

player.js:1635
Assertion failed: Wrong error type!
shaka.Player.onError_ @ player.js:1635
shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:726

main.js:148
Player error DOMException: Failed to read the 'buffered' property from 'SourceBuffer': This SourceBuffer has been removed from the parent media source.(…)
shakaDemo.onError_ @ main.js:148
shakaDemo.onErrorEvent_ @ main.js:134
shaka.util.FakeEventTarget.dispatchEvent @ fake_event_target.js:109
shaka.Player.onError_ @ player.js:1638
shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:726

**Comment by ismena** [comment]
We are unable to reproduce the problem.
If you're aware of the way to repro it using our demo app, please let us know.

Otherwise, are you able to share your application with us, so we can take a look at what's going on there?

**Comment by jjs1233** [comment]
I forget to say that the ajax request is for editing webvvtt file

after ajax request has been a response the webvtt file will be changed

I also try a test that only send ajax request  without editting webvtt file (maybe like you test),

and it worked fine no wrong no matter how many times I use the code `shakaDemo.load("/videolib/three/a/a.mpd");` in the browser console

but if I changed the webvtt file the first time the shakaplayer worked fine but the second time it wrong 

the app I have put it in my github but it just a beta version

**Comment by jjs1233** [comment]
I hava solve the problem by my friend
but thanks for you help

**Comment by ismena** [comment]
@jjs1233 no worries, glad to hear your problem is fixed. 
Do reach out if you run into issues in future.
