### ISSUE TITLE
InvalidStateError: Failed to execute 'appendBuffer' on 'SourceBuffer' on Google Chrome

### ISSUE THREAD

**Issue by janouskovec** [google/shaka-player#508]
Using Shaka Player v2.0.0-beta3, this stream never starts: 
http://88.103.240.102:80/cdn/uri/get/?contentType=vod&expiry=1757250744&id=59109745109259439&playerType=dash&quality=web&region=1&skipIpAddressCheck=true&userId=100&token=0d9357980baaf91e46d6976e517cb04508e1d068 (this URL is link to CDN so you get link to MPD file via HTTP redirect).

The Shaka Player throws error "Shaka Error MEDIA.MEDIA_SOURCE_OPERATION_THREW (InvalidStateError: Failed to execute 'appendBuffer' on 'SourceBuffer': The HTMLMediaElement.error attribute is not null.)".
On FF and Edge and IE11 the stream works fine. 
The issue occured in Shaka Player v2, in 1.6.5 the stream playing without problems in Google Chrome.

Please see chrome://media-internals:

Property	Value
audio_codec_name	aac
duration	4670.72
error	media::MediaSourceState::Append: stream parsing failed. Data size=131072 append_window_start=0 append_window_end=4670.76
event	WEBMEDIAPLAYER_CREATED
found_audio_stream	true
found_video_stream	true
info	Video codec: avc1.42C015
pipeline_error	chunk demuxer: append failed
pipeline_state	kStopped
player_id	168
render_id	42
url	blob:http://shaka-player-demo.appspot.com/8939bccf-7b60-488a-8c54-54f0126044f5
video_codec_name	h264

Log 

Timestamp	Property	Value
00:00:00 00	pipeline_state	kCreated
00:00:00 00	event	WEBMEDIAPLAYER_CREATED
00:00:00 00	url	blob:http://shaka-player-demo.appspot.com/8939bccf-7b60-488a-8c54-54f0126044f5
00:00:00 00	pipeline_state	kInitDemuxer
00:00:52 231	duration	4670.72
00:00:52 322	info	Audio codec: mp4a.40.2. Sampling frequency: 48000Hz. Sampling frequency(Extension): 0Hz. Channel layout: 3.
00:00:52 322	found_audio_stream	true
00:00:52 322	audio_codec_name	aac
00:00:52 341	info	Video codec: avc1.42C015
00:00:52 341	found_video_stream	true
00:00:52 341	video_codec_name	h264
00:00:52 341	pipeline_state	kInitRenderer
00:00:52 342	error	Failed to prepare AAC sample for decode
00:00:52 342	error	media::MediaSourceState::Append: stream parsing failed. Data size=131072 append_window_start=0 append_window_end=4670.76
00:00:52 342	pipeline_state	kStopping
00:00:52 342	pipeline_state	kStopped
00:00:52 343	pipeline_error	chunk demuxer: append failed

**Comment by joeyparrish** [comment]
Looks like a video segment is being appended to the audio buffer.  Not sure why.  Thanks for the report!

**Comment by joeyparrish** [comment]
This is caused by your audio Representation having the same id as one of your video Representations.  We keep a map internally of ids to segment indexes, which is necessary for us to update manifests for live streams.  Shaka v1 ignored manifest IDs, but that made updates more complicated.  This is why your content plays in v1, but not in v2.

It's not clear yet if your manifest is out of spec.  I will consult the DASH spec.  If this is valid, we will try to fix the library.  Otherwise, you will need to fix your content.

**Comment by joeyparrish** [comment]
This content is out of spec.  Regarding Representation IDs, the DASH spec (ISO/IEC 23009-1:2014) says in section 5.3.5.2:

> specifies an identifier for this Representation. The identifier shall be unique within a Period

In your content, there are two Representations with the same ID in the same Period.  If you are not the author of the encoder/packager, please report this as a bug to your encoder vendor.  Let us know if we can help in any way with your bug report.  Thanks!

**Comment by janouskovec** [comment]
Thank you for your support! I reported the bug to vendor of packager.
