### ISSUE TITLE
Persistent licenses on google chrome desktop

### ISSUE THREAD

**Issue by sridhard** [google/shaka-player#512]
I am using 2.0 version of shaka player.

OS: MAC
Browser: Chrome

I am trying to implement the presistentStorage feature. The content is encrypted with CENC encryption. 

I can play the content using the demo app (Custom feature). 
I want to store the content offline. In demo app the store option itself is not enabled.

manifest: https://s3-ap-southeast-1.amazonaws.com/learnyst/schools/1094/drm_courses/6677/paid/37376/online/vconvrted_f1/stream.mpd

licenseServer: https://wv.service.expressplay.com/hms/wv/rights/?ExpressPlayToken=AQAAAA2dKegAAABQsT_zdk5_kD2V-UtkCyYBDTclo0HOyMQyvs3jG0IHTo9uDTBtlgrmOe63aD1nhMX_yZzjdtZ_nZmS1Q8T9VTgFvyantU3ckQT7WKmEaVKf_RZDqz0cg4AJxo_m78mC7snblsF-w

Can you please let me know the below:
1. Whether the offline storage is supported on desktop chrome
2. If supported is there any demo app
3. If offline storage of content is not supported can we atleast store the license

**Comment by joeyparrish** [comment]
Hi @sridhard,

The demo app supports storing clear and encrypted content, so long as the browser has the necessary features.

Storage of content for offline is supported on all major browsers if I recall correctly.

However, Chrome does not support persistent licenses on desktop platforms at this time.  That is separate from the web API Shaka uses to store content itself, so you can still store clear content on desktop Chrome.  But without the ability to store the license, Shaka Player will not allow you to store encrypted content itself.  Without a license, you would not be able to play the encrypted content anyway.

Chrome currently only supports persistent licenses on Chromebooks.  I do not know when Chrome will start offering persistent license support on desktops, but when they do, Shaka Player will not need to be upgraded to take advantage of it.

There is one other important restriction on offline storage: Shaka Player does not allow you to store live streams offline, because some segments may not be available.

Does that help?

**Comment by sridhard** [comment]
Hi @joeyparrish ,

We are using widevine service from 3rd party. 3rd party service charges us for each time the license is queried from them. But 3rd party service has to option to generate licenses which are valid for one month.

To use license with one month validity we need to cache them and should not query again from 3rd party server. How can we achieve this if chrome browser does not support persistent license? Is there any alternative?

Or is it possible to cache the license in our server and return the license when widevine ask for license? Widevine license request has a opaque body. I am not sure whether it changes for each request..Can we retrun the cached license from our server instead of generating it from 3rd party server every time?

**Comment by sridhard** [comment]
Hi @joeyparrish ,

I have checked widevine website https://www.widevine.com/product_news.html.

_Posted: April 15, 2016

We had a busy year in 2015 launching new and updated products like the iOS SDK; **Shaka Player with offline playback**, captioning and cast support; and key security improvements for Chrome and Android. We have a ton of exciting things planned for 2016 and look forward to sharing more details in the coming months!_ 

There is a mention about offline playback with shaka player. Is it not related to google chrome?

**Comment by joeyparrish** [comment]
License responses cannot generally be cached.  They must match a specific request.

Shaka Player supports offline playback of both clear and encrypted content through standard APIs.  Not all browsers/platforms support persistent licenses *yet*, so those browsers can only do clear content offline at this time.

Currently, Chrome on ChromeOS supports persistent licenses.  Chrome on Android does not yet support persistent licenses, even though native apps on Android do.  Chrome on desktop does not support persistent licenses yet either.

If you are just using persistent licenses to avoid fees, that's not really what that technology is for.  If you really want to avoid the fees, have you considered working with Widevine directly?  Widevine does not charge any license fees.  Quoting the front page at [widevine.com](http://www.widevine.com/):

> *No License Fees* - Google does not assess license fees for the Widevine product.

**Comment by L-P** [comment]
Hi,

I'd like an update on this. While persistent licenses are still missing from
Chrome (and the feature request got archived after a year without any answer)
I'm wondering why the encrypted content itself cannot be stored.
A working Internet connection would still be required to get the license but
the content would already be there.

Would it be possible to store only the content when persistent licenses are not
available?

**Comment by TheModMaker** [comment]
First, persistent licenses are supported in Chrome, but only on ChromeOS.  There is work being done to add this to Android as well (see [crbug/493521](https://bugs.chromium.org/p/chromium/issues/detail?id=493521)).  But what you want is already possible when using Storage:

```js
storage.configure({usePersistentLicense: false});
```

See: <https://shaka-player-demo.appspot.com/docs/api/shakaExtern.html#OfflineConfiguration>

**Comment by joeyparrish** [comment]
Chrome 64, with persistent license support on Mac & Windows, is in beta.  Shaka-based applications will **not** need to be updated to take advantage of this feature in Chrome.

I'm going to go ahead and close this bug, but please feel free to reply with any questions you might have about this.

**Comment by sridhard** [comment]
Hi,

Can you please let me know in which version of Windows Chrome persistent
licenses are  supported in beta

**Comment by imalex** [comment]
See
https://developers.google.com/web/updates/2017/12/chrome-63-64-media-updates#persistent-licenses-windows-mac

**Comment by joeyparrish** [comment]
Persistent licenses are now in Chrome 64 on Windows and Mac.
