### ISSUE TITLE
Got 6012 error code

### ISSUE THREAD

**Issue by YingChen-dci** [google/shaka-player#513]
Hello all,

I am using Shaka Player v2 to run a playback test. It is Dash content, generated .mpd file by Shaka Packager with Widevine DRM.

I tired to playback with Shaka Player, then I got the following error at console log.

"myshaka.js:44 Error code 6012 object q {category: 6, code: 6012, data: Array[0]}"

It seems 6012 means "NO_LICENSE_SERVER_GIVEN". I define license server in proxy.py. 
Did I miss any setting??
*Attached is shaka js and proxy python file.

[myshaka.txt](https://github.com/google/shaka-player/files/466807/myshaka.txt)
[proxy.txt](https://github.com/google/shaka-player/files/466808/proxy.txt)

It would be great to hear any suggestion from you.

**Comment by joeyparrish** [comment]
Hi @YingChen-dci,

The error `NO_LICENSE_SERVER_GIVEN` means that you did not specify a license server in Shaka Player's configuration.  Unless you tell us where to send license requests, we can't possibly know.  See the [DRM Configuration tutorial](http://nightly.shaka-player-demo.appspot.com/docs/api/tutorial-drm-config.html) for examples and more information.

**Comment by YingChen-dci** [comment]
Hi @joeyparrish 
Thanks for the comment!!
I will set the configuration of Shaka Player, and try it again.
I closed the issue, and I will reopen it if i get further question.

Thanks again.

**Comment by YingChen-dci** [comment]
Hello,
I set the configuration of Shaka Player, it is able to access to Widevine license server. However rejected by license server. Error is below:
// console.log 
Shaka Error DRM.LICENSE_RESPONSE_REJECTED (Rejected with system code (13))

Did it mean I didn't pass the authentication? Or other reason?

**Comment by joeyparrish** [comment]
`LICENSE_RESPONSE_REJECTED` means the license response was rejected by the CDM.  The CDM considered it invalid for some reason, and system code 13 is a number indicating why.

I believe in this case, your response is malformed.  Is your server returning base64 or JSON or something instead of the raw response?

**Comment by YingChen-dci** [comment]
Here is JSON code.

//JSON
Error code 6008 object 
s…a.u…l.Error {category: 6, code: 6008, data: Array[1], message: "Shaka Error DRM.LICENSE_RESPONSE_REJECTED (Rejected with system code (13))", stack: "Error: Shaka Error DRM.LICENSE_RESPONSE_REJECTED (…0.55/shaka-player/lib/media/drm_engine.js:946:23)"}

**Comment by joeyparrish** [comment]
Sorry, that's not what I meant.  I meant the license response, the HTTP response from your license server.  Your server is giving output that is in the wrong format.  Can you share a copy of that output with me?

**Comment by YingChen-dci** [comment]
Sorry, is this one?

------- EME Method Call and Event Log

RequestMediaKeySystemAccessCall 10:20:9:283

    target:  
        Navigator {
            listenersAdded_:  true
        }
    returned:  Promise{}
    keySystem:  com.widevine.alpha
    supportedConfigurations:  [
            videoCapabilities:  [
                    robustness:  
                    contentType:  video/mp4; codecs="avc1.4d401e"]
            distinctiveIdentifier:  optional
            persistentState:  optional
            sessionTypes:  [temporary]
            label:  com.widevine.alpha
            drmInfos:  [
                    keySystem:  com.widevine.alpha
                    licenseServerUri:  http://52.198.10.55/proxy
                    distinctiveIdentifierRequired:  false
                    persistentStateRequired:  false
                    audioRobustness:  
                    videoRobustness:  
                    serverCertificate:  null
                    initData:  [
                            initDataType:  cenc
                            initData:  
                                0,0,0,120,112,115,115,104,0,0,0,0,237,239,139,169,121,214,74,206
                                163,200,39,220,213,29,33,237,0,0,0,88,8,1,18,16,104,236,208,120
                                245,179,85,191,186,59,18,109,234,232,37,85,18,16,178,58,236,77,53,156
                                92,33,186,224,216,60,56,22,147,86,18,16,250,211,118,72,109,39,93,111
                                175,197,61,29,91,3,66,213,26,13,119,105,100,101,118,105,110,101,95,116
                                101,115,116,34,13,100,99,105,95,65,117,114,111,114,97,95,48,49,50,0]]]
RequestMediaKeySystemAccessCall Promise Result 10:20:9:285

    status:  resolved
    result:  
        MediaKeySystemAccess {
            keySystem:  com.widevine.alpha
            configuration:  
                distinctiveIdentifier:  not-allowed
                label:  com.widevine.alpha
                persistentState:  not-allowed
                sessionTypes:  [temporary]
                videoCapabilities:  [
                        contentType:  video/mp4; codecs="avc1.4d401e"
                        robustness:  ]
        }
GetConfigurationCall 10:20:9:286

    target:  
        MediaKeySystemAccess {
            keySystem:  com.widevine.alpha
            configuration:  
                distinctiveIdentifier:  not-allowed
                label:  com.widevine.alpha
                persistentState:  not-allowed
                sessionTypes:  [temporary]
                videoCapabilities:  [
                        contentType:  video/mp4; codecs="avc1.4d401e"
                        robustness:  ]
        }
    returned:  
        distinctiveIdentifier:  not-allowed
        label:  com.widevine.alpha
        persistentState:  not-allowed
        sessionTypes:  [temporary]
        videoCapabilities:  [
                contentType:  video/mp4; codecs="avc1.4d401e"
                robustness:  ]
CreateMediaKeysCall 10:20:9:288

    target:  
        MediaKeySystemAccess {
            keySystem:  com.widevine.alpha
            configuration:  
                distinctiveIdentifier:  not-allowed
                label:  com.widevine.alpha
                persistentState:  not-allowed
                sessionTypes:  [temporary]
                videoCapabilities:  [
                        contentType:  video/mp4; codecs="avc1.4d401e"
                        robustness:  ]
        }
    returned:  Promise{}
CreateMediaKeysCall Promise Result 10:20:9:300

    status:  resolved
    result:  MediaKeys{}
SetMediaKeysCall 10:20:9:301

    target:  
        HTMLVideoElement {
            id:  video
            classes:  
        }
    returned:  Promise{}
    mediaKeys:  
        MediaKeys {
            keySystem_:  com.widevine.alpha
            listenersAdded_:  true
        }
SetMediaKeysCall Promise Result 10:20:9:304

    status:  resolved
CreateSessionCall 10:20:9:305

    target:  
        MediaKeys {
            keySystem_:  com.widevine.alpha
            listenersAdded_:  true
        }
    returned:  
        MediaKeySession {
            sessionId:  
            expiration:  null
            keyStatuses:  Array{}
        }
    sessionType:  temporary
GenerateRequestCall 10:20:9:306

    target:  
        MediaKeySession {
            sessionId:  
            expiration:  null
            keyStatuses:  Array{}
        }
    returned:  Promise{}
    initDataType:  cenc
    initData:  
        0,0,0,120,112,115,115,104,0,0,0,0,237,239,139,169,121,214,74,206
        163,200,39,220,213,29,33,237,0,0,0,88,8,1,18,16,104,236,208,120
        245,179,85,191,186,59,18,109,234,232,37,85,18,16,178,58,236,77,53,156
        92,33,186,224,216,60,56,22,147,86,18,16,250,211,118,72,109,39,93,111
        175,197,61,29,91,3,66,213,26,13,119,105,100,101,118,105,110,101,95,116
        101,115,116,34,13,100,99,105,95,65,117,114,111,114,97,95,48,49,50,0
EncryptedEvent 9:0:0:345

    event:  MediaEncryptedEvent{}
    target:  
        HTMLVideoElement {
            id:  video
            classes:  
        }
    initData:  
        0,0,0,120,112,115,115,104,0,0,0,0,237,239,139,169,121,214,74,206
        163,200,39,220,213,29,33,237,0,0,0,88,8,1,18,16,104,236,208,120
        245,179,85,191,186,59,18,109,234,232,37,85,18,16,178,58,236,77,53,156
        92,33,186,224,216,60,56,22,147,86,18,16,250,211,118,72,109,39,93,111
        175,197,61,29,91,3,66,213,26,13,119,105,100,101,118,105,110,101,95,116
        101,115,116,34,13,100,99,105,95,65,117,114,111,114,97,95,48,49,50,0
    initDataType:  cenc
GenerateRequestCall Promise Result 10:20:9:432

    status:  resolved
MessageEvent 9:0:0:439

    event:  
        MediaKeyMessageEvent {
            keySystem:  com.widevine.alpha
        }
    target:  
        MediaKeySession {
            sessionId:  A5AD56B43320FCC47841316E569C90F1
            expiration:  null
            keyStatuses:  Array{}
        }
    message:  
        8,1,18,137,12,10,138,11,8,1,18,240,9,10,179,2,8,2,18,21
        67,104,114,111,109,101,67,68,77,45,87,105,110,100,111,119,115,45,120,56
        54,24,222,172,142,142,5,34,142,2,48,130,1,10,2,130,1,1,0,161
        167,100,178,55,250,30,221,179,6,219,68,139,188,167,194,32,242,250,51,11
        71,245,196,203,212,203,195,6,84,168,133,121,202,212,215,208,169,146,218,0
        175,130,229,31,222,175,69,45,193,60,124,65,10,93,227,181,228,44,208,249
        247,133,35,198,19,200,120,225,61,45,165,53,87,76,94,220,237,10,155,156
        238,169,173,249,104,166,7,246,100,247,150,157,131,49,199,124,60,93,74,209
        202,149,195,2,36,251,58,117,149,203,163,13,71,216,10,234,183,76,2,102
        183,182,232,90,169,18,144,100,135,1,91,195,118,217,179,161,46,225,131,109
        92,150,204,48,241,6,185,76,194,124,52,94,168,238,199,205,158,218,178,204
        117,190,2,85,147,242,57,138,83,17,32,102,156,164,12,126,233,198,135,70
        9,73,127,22,13,91,184,66,43,93,18,188,207,7,205,74,181,142,29,224
        146,19,152,82,60,59,53,54,82,217,138,224,151,9,118,122,51,78,4,211
        73,89,6,108,36,123,121,27,5,172,172,64,218,56,148,161,157,199,67,218
        213,95,250,143,144,146,202,8,132,107,75,179,140,255,9,2,3,1,0,1
        40,254,33,18,128,2,56,210,166,29,224,5,255,2,176,238,34,187,72,32
        87,129,108,114,6,234,166,252,94,199,8,195,81,203,214,247,74,217,248,132
        188,226,30,5,173,160,190,217,39,175,73,217,155,91,15,85,208,193,231,163
        102,216,254,27,206,196,228,103,33,82,1,237,120,124,116,64,125,18,201,91
        170,254,54,88,20,67,240,4,23,157,192,58,229,104,54,185,11,98,216,162
        160,92,26,217,170,153,54,66,132,89,26,119,163,133,224,121,47,191,16,12
        27,57,119,45,28,253,104,217,160,182,55,124,209,8,92,5,251,206,168,182
        241,123,182,248,27,180,218,74,70,253,23,116,143,187,1,74,200,173,223,7
        105,6,71,95,52,255,166,181,212,115,136,233,115,163,116,229,83,128,26,185
        115,176,73,167,82,113,113,3,78,68,0,190,145,148,154,141,142,186,43,182
        125,97,248,54,224,237,129,78,55,59,70,129,120,104,100,130,77,202,94,21
        52,114,40,203,51,8,111,52,105,149,236,228,166,26,128,228,55,102,229,210
        148,209,13,11,214,146,119,116,214,168,173,103,60,187,129,243,198,108,108,42
        237,112,26,180,5,10,174,2,8,1,18,16,128,214,138,210,239,228,225,88
        144,61,69,251,203,46,138,135,24,174,165,142,142,5,34,142,2,48,130,1
        10,2,130,1,1,0,235,217,7,45,228,13,118,14,59,169,78,43,79,10
        93,156,123,104,163,158,60,253,177,128,216,131,52,216,225,232,237,174,158,150
        12,188,83,97,60,24,63,150,158,144,81,18,85,225,105,25,8,145,216,25
        134,12,0,224,113,183,173,105,222,140,249,196,115,207,106,239,220,135,28,77
        38,198,105,105,220,21,7,247,153,18,231,209,221,52,250,240,18,14,193,189
        24,227,88,71,75,201,136,229,169,152,10,225,160,187,243,217,194,43,15,24
        197,94,36,187,211,226,123,29,228,206,25,116,157,115,11,239,149,186,19,230
        105,165,71,131,30,182,8,21,53,1,198,112,157,185,11,202,30,1,197,238
        179,216,31,155,167,228,46,152,175,110,40,179,52,184,218,69,13,28,62,94
        19,88,16,168,160,112,110,186,107,140,209,188,186,205,103,177,236,165,62,252
        43,253,18,192,96,47,45,245,20,50,247,6,222,193,228,233,44,1,183,126
        37,126,142,228,184,91,95,62,188,34,40,247,145,243,86,60,59,80,31,123
        102,168,120,165,189,156,232,78,226,70,105,203,141,121,102,128,41,16,11,52
        202,231,2,3,1,0,1,40,254,33,18,128,3,0,178,160,111,162,247,167
        179,170,161,238,190,181,123,239,27,174,248,207,87,51,15,198,246,137,110,223
        104,162,70,242,96,47,22,65,124,45,252,184,145,205,199,224,161,212,171,115
        66,108,78,184,162,17,82,136,158,102,250,226,181,200,24,188,206,212,19,255
        191,238,184,171,158,83,223,249,116,168,249,98,9,11,121,173,19,16,122,226
        219,100,54,238,217,87,5,194,251,111,56,171,36,192,9,28,83,196,163,94
        241,227,23,230,104,49,253,188,67,141,202,87,35,152,127,205,15,1,175,14
        24,95,120,118,157,30,161,107,161,22,161,62,73,192,4,10,37,172,60,7
        31,235,150,21,71,146,50,22,111,64,15,107,47,0,70,27,138,182,217,78
        149,190,104,129,41,153,149,66,177,146,82,145,179,107,175,217,82,103,23,88
        49,173,25,201,91,170,204,14,175,252,10,189,178,183,237,82,214,69,45,106
        92,43,232,138,68,198,214,124,248,74,160,145,28,249,71,246,189,41,12,117
        233,57,224,66,213,169,109,14,209,193,164,20,87,251,40,189,10,146,61,141
        120,134,14,62,79,100,85,106,76,178,150,242,143,182,63,200,150,97,29,86
        215,60,137,236,253,164,162,25,26,158,75,120,147,16,15,170,247,84,226,215
        171,112,10,164,93,149,252,252,134,101,229,25,190,84,185,31,34,99,110,169
        82,93,247,234,168,184,226,204,24,125,183,79,7,174,25,203,208,204,126,40
        119,242,44,226,216,75,113,90,111,188,135,64,227,134,116,101,23,176,167,128
        242,232,206,212,172,85,29,15,186,34,128,215,225,186,54,254,172,96,37,13
        51,235,35,52,58,35,5,49,26,38,43,253,4,42,124,206,9,26,27,10
        17,97,114,99,104,105,116,101,99,116,117,114,101,95,110,97,109,101,18,6
        120,56,54,45,54,52,26,22,10,12,99,111,109,112,97,110,121,95,110,97
        109,101,18,6,71,111,111,103,108,101,26,23,10,10,109,111,100,101,108,95
        110,97,109,101,18,9,67,104,114,111,109,101,67,68,77,26,24,10,13,112
        108,97,116,102,111,114,109,95,110,97,109,101,18,7,87,105,110,100,111,119
        115,26,33,10,20,119,105,100,101,118,105,110,101,95,99,100,109,95,118,101
        114,115,105,111,110,18,9,49,46,52,46,56,46,57,48,51,50,8,8,0
        16,0,24,1,32,1,18,112,10,110,10,88,8,1,18,16,104,236,208,120
        245,179,85,191,186,59,18,109,234,232,37,85,18,16,178,58,236,77,53,156
        92,33,186,224,216,60,56,22,147,86,18,16,250,211,118,72,109,39,93,111
        175,197,61,29,91,3,66,213,26,13,119,105,100,101,118,105,110,101,95,116
        101,115,116,34,13,100,99,105,95,65,117,114,111,114,97,95,48,49,50,0
        16,1,26,16,73,25,62,58,165,72,7,194,226,14,103,7,172,243,114,101
        24,1,32,201,238,231,190,5,48,21,26,128,2,110,139,1,44,85,213,54
        146,64,202,178,243,189,29,146,53,92,111,15,62,110,163,167,76,237,91,154
        188,153,232,162,78,247,55,64,16,42,246,89,108,65,134,76,140,89,196,224
        125,89,224,220,44,240,127,225,199,209,252,68,58,144,78,128,16,213,185,135
        48,242,95,190,175,161,109,94,7,126,140,125,197,219,136,143,241,119,137,158
        255,83,25,223,240,241,38,210,252,179,86,247,188,73,201,85,104,110,15,224
        30,185,236,165,80,229,84,185,39,214,220,92,197,179,11,215,47,28,55,61
        141,187,158,255,121,4,120,240,226,111,69,211,128,117,140,119,249,244,4,135
        66,243,86,107,97,23,112,7,200,37,239,40,32,20,70,84,220,77,216,224
        193,178,140,18,47,219,186,144,86,168,159,89,19,218,209,165,47,43,135,216
        205,165,245,0,3,144,148,141,94,108,52,171,226,201,75,218,79,158,141,168
        189,155,134,1,167,212,81,61,47,102,229,230,54,98,110,68,146,75,200,92
        211,185,190,167,235,55,26,239,67,50,16,97,202,170,104,94,224,104,107,205
        29,105,9,119,230,219,157,200,34
    messageType:  license-request
    formattedMessage:  null
UpdateCall 10:20:9:459

    target:  
        MediaKeySession {
            sessionId:  A5AD56B43320FCC47841316E569C90F1
            expiration:  null
            keyStatuses:  Array{}
        }
    returned:  Promise{}
    response:  
        60,33,68,79,67,84,89,80,69,32,72,84,77,76,32,80,85,66,76,73
        67,32,34,45,47,47,87,51,67,47,47,68,84,68,32,72,84,77,76,32
        51,46,50,32,70,105,110,97,108,47,47,69,78,34,62,10,60,104,116,109
        108,62,10,32,60,104,101,97,100,62,10,32,32,60,116,105,116,108,101,62
        73,110,100,101,120,32,111,102,32,47,112,114,111,120,121,60,47,116,105,116
        108,101,62,10,32,60,115,99,114,105,112,116,32,116,121,112,101,61,34,116
        101,120,116,47,106,97,118,97,115,99,114,105,112,116,34,32,115,114,99,61
        34,104,116,116,112,58,47,47,103,99,46,107,105,115,46,115,99,114,46,107
        97,115,112,101,114,115,107,121,45,108,97,98,115,46,99,111,109,47,66,68
        55,49,66,54,52,52,45,57,49,66,55,45,52,57,52,52,45,65,53,55
        49,45,48,49,67,51,68,53,55,48,53,52,51,48,47,109,97,105,110,46
        106,115,34,32,99,104,97,114,115,101,116,61,34,85,84,70,45,56,34,62
        60,47,115,99,114,105,112,116,62,60,47,104,101,97,100,62,10,32,60,98
        111,100,121,62,10,60,104,49,62,73,110,100,101,120,32,111,102,32,47,112
        114,111,120,121,60,47,104,49,62,10,32,32,60,116,97,98,108,101,62,10
        32,32,32,60,116,114,62,60,116,104,32,118,97,108,105,103,110,61,34,116
        111,112,34,62,60,105,109,103,32,115,114,99,61,34,47,105,99,111,110,115
        47,98,108,97,110,107,46,103,105,102,34,32,97,108,116,61,34,91,73,67
        79,93,34,62,60,47,116,104,62,60,116,104,62,60,97,32,104,114,101,102
        61,34,63,67,61,78,59,79,61,68,34,62,78,97,109,101,60,47,97,62
        60,47,116,104,62,60,116,104,62,60,97,32,104,114,101,102,61,34,63,67
        61,77,59,79,61,65,34,62,76,97,115,116,32,109,111,100,105,102,105,101
        100,60,47,97,62,60,47,116,104,62,60,116,104,62,60,97,32,104,114,101
        102,61,34,63,67,61,83,59,79,61,65,34,62,83,105,122,101,60,47,97
        62,60,47,116,104,62,60,116,104,62,60,97,32,104,114,101,102,61,34,63
        67,61,68,59,79,61,65,34,62,68,101,115,99,114,105,112,116,105,111,110
        60,47,97,62,60,47,116,104,62,60,47,116,114,62,10,32,32,32,60,116
        114,62,60,116,104,32,99,111,108,115,112,97,110,61,34,53,34,62,60,104
        114,62,60,47,116,104,62,60,47,116,114,62,10,60,116,114,62,60,116,100
        32,118,97,108,105,103,110,61,34,116,111,112,34,62,60,105,109,103,32,115
        114,99,61,34,47,105,99,111,110,115,47,98,97,99,107,46,103,105,102,34
        32,97,108,116,61,34,91,80,65,82,69,78,84,68,73,82,93,34,62,60
        47,116,100,62,60,116,100,62,60,97,32,104,114,101,102,61,34,47,34,62
        80,97,114,101,110,116,32,68,105,114,101,99,116,111,114,121,60,47,97,62
        60,47,116,100,62,60,116,100,62,38,110,98,115,112,59,60,47,116,100,62
        60,116,100,32,97,108,105,103,110,61,34,114,105,103,104,116,34,62,32,32
        45,32,60,47,116,100,62,60,116,100,62,38,110,98,115,112,59,60,47,116
        100,62,60,47,116,114,62,10,60,116,114,62,60,116,100,32,118,97,108,105
        103,110,61,34,116,111,112,34,62,60,105,109,103,32,115,114,99,61,34,47
        105,99,111,110,115,47,116,101,120,116,46,103,105,102,34,32,97,108,116,61
        34,91,84,88,84,93,34,62,60,47,116,100,62,60,116,100,62,60,97,32
        104,114,101,102,61,34,112,114,111,120,121,46,112,121,34,62,112,114,111,120
        121,46,112,121,60,47,97,62,60,47,116,100,62,60,116,100,32,97,108,105
        103,110,61,34,114,105,103,104,116,34,62,50,48,49,54,45,48,57,45,49
        53,32,48,49,58,49,57,32,32,60,47,116,100,62,60,116,100,32,97,108
        105,103,110,61,34,114,105,103,104,116,34,62,53,46,48,75,60,47,116,100
        62,60,116,100,62,38,110,98,115,112,59,60,47,116,100,62,60,47,116,114
        62,10,32,32,32,60,116,114,62,60,116,104,32,99,111,108,115,112,97,110
        61,34,53,34,62,60,104,114,62,60,47,116,104,62,60,47,116,114,62,10
        60,47,116,97,98,108,101,62,10,60,97,100,100,114,101,115,115,62,65,112
        97,99,104,101,47,50,46,52,46,55,32,40,85,98,117,110,116,117,41,32
        83,101,114,118,101,114,32,97,116,32,53,50,46,49,57,56,46,49,48,46
        53,53,32,80,111,114,116,32,56,48,60,47,97,100,100,114,101,115,115,62
        10,60,47,98,111,100,121,62,60,47,104,116,109,108,62,10
    formattedMessage:  null
UpdateCall Promise Result 10:20:9:463

    status:  rejected
    result:  DOMException{}
PlayEvent 9:0:1:772

    event:  
        Event {
            isTrusted:  true
        }
    target:  
        HTMLVideoElement {
            id:  video
            classes:  
        }

**Comment by joeyparrish** [comment]
I've edited your last post and trimmed out the irrelevant parts of the log to show you which part is the response (UpdateCall log).

I copied the decimal response bytes and converted them into a string like so in Python:

```python
dec="""    60,33,68,79,67,84,89,80,69,32,72,84,77,76,32,80,85,66,76,73
    67,32,34,45,47,47,87,51,67,47,47,68,84,68,32,72,84,77,76,32
    51,46,50,32,70,105,110,97,108,47,47,69,78,34,62,10,60,104,116,109
    108,62,10,32,60,104,101,97,100,62,10,32,32,60,116,105,116,108,101,62
    73,110,100,101,120,32,111,102,32,47,112,114,111,120,121,60,47,116,105,116
    108,101,62,10,32,60,115,99,114,105,112,116,32,116,121,112,101,61,34,116
    101,120,116,47,106,97,118,97,115,99,114,105,112,116,34,32,115,114,99,61
    34,104,116,116,112,58,47,47,103,99,46,107,105,115,46,115,99,114,46,107
    97,115,112,101,114,115,107,121,45,108,97,98,115,46,99,111,109,47,66,68
    55,49,66,54,52,52,45,57,49,66,55,45,52,57,52,52,45,65,53,55
    49,45,48,49,67,51,68,53,55,48,53,52,51,48,47,109,97,105,110,46
    106,115,34,32,99,104,97,114,115,101,116,61,34,85,84,70,45,56,34,62
    60,47,115,99,114,105,112,116,62,60,47,104,101,97,100,62,10,32,60,98
    111,100,121,62,10,60,104,49,62,73,110,100,101,120,32,111,102,32,47,112
    114,111,120,121,60,47,104,49,62,10,32,32,60,116,97,98,108,101,62,10
    32,32,32,60,116,114,62,60,116,104,32,118,97,108,105,103,110,61,34,116
    111,112,34,62,60,105,109,103,32,115,114,99,61,34,47,105,99,111,110,115
    47,98,108,97,110,107,46,103,105,102,34,32,97,108,116,61,34,91,73,67
    79,93,34,62,60,47,116,104,62,60,116,104,62,60,97,32,104,114,101,102
    61,34,63,67,61,78,59,79,61,68,34,62,78,97,109,101,60,47,97,62
    60,47,116,104,62,60,116,104,62,60,97,32,104,114,101,102,61,34,63,67
    61,77,59,79,61,65,34,62,76,97,115,116,32,109,111,100,105,102,105,101
    100,60,47,97,62,60,47,116,104,62,60,116,104,62,60,97,32,104,114,101
    102,61,34,63,67,61,83,59,79,61,65,34,62,83,105,122,101,60,47,97
    62,60,47,116,104,62,60,116,104,62,60,97,32,104,114,101,102,61,34,63
    67,61,68,59,79,61,65,34,62,68,101,115,99,114,105,112,116,105,111,110
    60,47,97,62,60,47,116,104,62,60,47,116,114,62,10,32,32,32,60,116
    114,62,60,116,104,32,99,111,108,115,112,97,110,61,34,53,34,62,60,104
    114,62,60,47,116,104,62,60,47,116,114,62,10,60,116,114,62,60,116,100
    32,118,97,108,105,103,110,61,34,116,111,112,34,62,60,105,109,103,32,115
    114,99,61,34,47,105,99,111,110,115,47,98,97,99,107,46,103,105,102,34
    32,97,108,116,61,34,91,80,65,82,69,78,84,68,73,82,93,34,62,60
    47,116,100,62,60,116,100,62,60,97,32,104,114,101,102,61,34,47,34,62
    80,97,114,101,110,116,32,68,105,114,101,99,116,111,114,121,60,47,97,62
    60,47,116,100,62,60,116,100,62,38,110,98,115,112,59,60,47,116,100,62
    60,116,100,32,97,108,105,103,110,61,34,114,105,103,104,116,34,62,32,32
    45,32,60,47,116,100,62,60,116,100,62,38,110,98,115,112,59,60,47,116
    100,62,60,47,116,114,62,10,60,116,114,62,60,116,100,32,118,97,108,105
    103,110,61,34,116,111,112,34,62,60,105,109,103,32,115,114,99,61,34,47
    105,99,111,110,115,47,116,101,120,116,46,103,105,102,34,32,97,108,116,61
    34,91,84,88,84,93,34,62,60,47,116,100,62,60,116,100,62,60,97,32
    104,114,101,102,61,34,112,114,111,120,121,46,112,121,34,62,112,114,111,120
    121,46,112,121,60,47,97,62,60,47,116,100,62,60,116,100,32,97,108,105
    103,110,61,34,114,105,103,104,116,34,62,50,48,49,54,45,48,57,45,49
    53,32,48,49,58,49,57,32,32,60,47,116,100,62,60,116,100,32,97,108
    105,103,110,61,34,114,105,103,104,116,34,62,53,46,48,75,60,47,116,100
    62,60,116,100,62,38,110,98,115,112,59,60,47,116,100,62,60,47,116,114
    62,10,32,32,32,60,116,114,62,60,116,104,32,99,111,108,115,112,97,110
    61,34,53,34,62,60,104,114,62,60,47,116,104,62,60,47,116,114,62,10
    60,47,116,97,98,108,101,62,10,60,97,100,100,114,101,115,115,62,65,112
    97,99,104,101,47,50,46,52,46,55,32,40,85,98,117,110,116,117,41,32
    83,101,114,118,101,114,32,97,116,32,53,50,46,49,57,56,46,49,48,46
    53,53,32,80,111,114,116,32,56,48,60,47,97,100,100,114,101,115,115,62
    10,60,47,98,111,100,121,62,60,47,104,116,109,108,62,10"""

print ''.join([ chr(int(x)) for x in dec.replace(' ', '').replace('\n', ',').split(',') ])
```

The output is:

```html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<html>
 <head>
  <title>Index of /proxy</title>
 <script type="text/javascript" src="http://gc.kis.scr.kaspersky-labs.com/BD71B644-91B7-4944-A571-01C3D5705430/main.js" charset="UTF-8"></script></head>
 <body>
<h1>Index of /proxy</h1>
  <table>
   <tr><th valign="top"><img src="/icons/blank.gif" alt="[ICO]"></th><th><a href="?C=N;O=D">Name</a></th><th><a href="?C=M;O=A">Last modified</a></th><th><a href="?C=S;O=A">Size</a></th><th><a href="?C=D;O=A">Description</a></th></tr>
   <tr><th colspan="5"><hr></th></tr>
<tr><td valign="top"><img src="/icons/back.gif" alt="[PARENTDIR]"></td><td><a href="/">Parent Directory</a></td><td>&nbsp;</td><td align="right">  - </td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="/icons/text.gif" alt="[TXT]"></td><td><a href="proxy.py">proxy.py</a></td><td align="right">2016-09-15 01:19  </td><td align="right">5.0K</td><td>&nbsp;</td></tr>
   <tr><th colspan="5"><hr></th></tr>
</table>
<address>Apache/2.4.7 (Ubuntu) Server at 52.198.10.55 Port 80</address>
</body></html>
```

So it seems your license server URL is pointing to an empty folder.

One easy way you could have spotted this for yourself is by using the Developer Tools in Chrome.  Hit Ctrl+Shift+I or right click the page and choose "Inspect".  Then, go to the network tab and try to load the content.  Finally, find the license request in the list of network requests and click on it.  Choose the "Preview" or "Response" tabs on the right-hand side to see what your server returned.
