### ISSUE TITLE
EXT-X-KEY:METHOD=SAMPLE-AES is not returning identDataType as skd

### ISSUE THREAD

**Issue by celsosantarosa** [google/shaka-player#5133]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.3.5

**Please ask your question**
I am trying to play a fairplay HLS manifest that is a media playlist(no master playlist) with a single audio representation like the one below, but It is always returning the `initDataType` as `sinf`. Looking at the `hls_parser.js`, it seems like we always add a default drmInfo to `sinf`. Is this by design? Is there a way to convert `sinf` to `skd` in the in `initDataTransform` func?

`#EXTM3U
#EXT-X-VERSION:6
#EXT-X-TARGETDURATION:10
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-KEY:METHOD=SAMPLE-AES,URI="skd://skd-id",KEYFORMAT="com.apple.streamingkeydelivery",KEYFORMATVERSIONS="1"`

**Comment by celsosantarosa** [comment]
@avelad Do you have any thoughts on this?

**Comment by avelad** [comment]
@celsosantarosa are you using `useNativeHlsOnSafari = true`?

**Comment by celsosantarosa** [comment]
> @celsosantarosa are you using `useNativeHlsOnSafari = true`?

No, I am not. When I use it the request that safari does to retrieve the HLS manifest does not go to my networking engine request filter. This request needs an Authorization header on it, otherwise it fails.

**Comment by avelad** [comment]
Can you confirm if you are using TS or MP4?
Are you using Modern EME or legacy Apple Media Keys? 
And what keysystem?

**Comment by celsosantarosa** [comment]
> Can you confirm if you are using TS or MP4? 
MP4

> Are you using Modern EME or legacy Apple Media Keys?
Legacy

> what keysystem?
com.apple.fps.1_0

**Comment by avelad** [comment]
@celsosantarosa Using MSE with MP4 and legacy Apple Media Keys is not a supported configuration. See: https://shaka-player-demo.appspot.com/docs/api/tutorial-fairplay.html 
Sorry...
