### ISSUE TITLE
Changing audio tracks changes the text track if the text track was previously changed

### ISSUE THREAD

**Issue by baseballbrad3** [google/shaka-player#514]
- **What version of Shaka Player are you using?** 
2.0.0

  - **Can you reproduce the issue with our latest release version?** 
Yep

  - **Can you reproduce the issue with the latest code from `master`?** 
I have not tried, but I don't see any commits since 2.0.0's release.

- **Are you using the demo app or your own custom app?** 
Custom app

  - **If custom app, can you reproduce the issue using our demo app?**
Yep

- **What did you do?**
I enabled subtitles by clicking the "CC" button on the controls. I selected the "fr (subtitle)" text track. I then changed the audio track to "de" (it was "en" on initial playback). Upon changing the audio track to "de" the text track changed back to "en (subtitle)"
  - **What content did you load?** 
Angel One (multicode, multilingual) on the demo player (and our own content)

    - **If standard demo asset, which one?** 
Angel One (multicode, multilingual)

    - **If custom asset, what manifest and license server URIs?**

  - **How did you interact with the content, if at all?** 
Other than clicking "CC", no. I didn't need to seek or pause or anything like that.

- **What did you expect to happen?**
I expected the text track to remain on the "fr (subtitle)" track.

- **What actually happened?**
The text track changed to the "en (subtitle)" text track when the audio track changed.

---

We're seeing this on Firefox, Chrome, IE, and Edge. Our work around is to query Shaka for the current playing text track, change the audio track to the user's selection, then change the text track back to what it was before. It works well enough, but I wanted to bring this up.

**Comment by ismena** [comment]
Thanks for reporting, Brad, I'll look into it.

**Comment by ismena** [comment]
@baseballbrad3 Should be good now. Please let us know if you have any questions or issues.
