### ISSUE TITLE
Robustness warning in Chrome?

### ISSUE THREAD

**Issue by Feenposhleen** [google/shaka-player#518]
When initiating a stream in shaka2 you get an ominous warning in the console:
`It is recommended that a robustness level be specified. Not specifying the robustness level could result in unexpected behavior in the future, potentially including failure to play.`.

This is probably benign, but if it can be mitigated somehow, that would be great. I saw a PR merged earlier this summer in dash.js that seems to deal with this issue, (https://github.com/Dash-Industry-Forum/dash.js/pull/1446) maybe that could be of interest.

**Comment by joeyparrish** [comment]
We already support robustness settings.  See "Advanced DRM Configuration" in the [DRM Configuration tutorial](http://nightly.shaka-player-demo.appspot.com/docs/api/tutorial-drm-config.html).

We don't set robustness by default because that would require us to hard-code knowledge of valid robustness levels, which are not defined in the EME spec.  Each key system has its own set of valid robustness strings.

**Comment by joeyparrish** [comment]
The message is ominous, though.  For now, the empty string is allowed by the EME spec and is meaningful:

> __*`robustness`*__ of type DOMString, defaulting to ""
>  > The robustness level associated with the content type. The empty string indicates that any ability to decrypt and decode the content type is acceptable.

We'll keep an eye out for changes on this.  Perhaps the message references an older version of the spec in which this was not well defined.

**Comment by ddorwin** [comment]
See also this text (emphasis added) from the note following the normative text above:
> ... If only the empty string is specified, implementations MAY be configured to use the **lowest** robustness level the implementation supports.
>
>Applications SHOULD specify the robustness level(s) they require to avoid unexpected client incompatibilities.

This warning is for the current version of the spec and related to potential changes to Chrome (or other implementations) that could break some apps that do not provide a robustness level. For example, the lowest supported level is often not appropriate for video.

**Comment by joeyparrish** [comment]
Ah, I see.  Thanks for the correction, David.

**Comment by Feenposhleen** [comment]
All right! Thanks for the clarifications. 

While reading I thought of another argument to not provide a default:
Suppose the technical details of a DRM implementation is dictated by rights acquisition terms. Setting a low default level would mask the need to make an explicit choice, leading to a potential breach of contract toward the rights holders. It makes a lot of sense to not mute the warning so that people like me need to look up the details and spec.

**Comment by soualid** [comment]
Just in case someone is looking for the information, to get rid of the warning, I used `SW_SECURE_CRYPTO` for both `audioRobustness` and `audioRobustness`, valid values for widevine are listed here : https://chromium.googlesource.com/chromium/src/+/refs/heads/lkcr/components/cdm/renderer/widevine_key_system_properties.h

**Comment by joeyparrish** [comment]
Have we answered this question to everyone's satisfaction?  Can we close it?

**Comment by Feenposhleen** [comment]
I'm satisfied, thanks. You can close it.

**Comment by Zorig** [comment]
I am using shaka 2.02 and set robustness level to `SW_SECURE_CRYPTO` for audio and video still get warning. Is it because of version? I have been used shaka(2.0.0 beta) before.

```
this.get('player').configure({
    drm: {
        servers: {'com.widevine.alpha': data.token},
        advanced: {
        'com.widevine.alpha': {
            'videoRobustness': 'SW_SECURE_CRYPTO',
            'audioRobustness': 'SW_SECURE_CRYPTO'
        }
        }
    }
})
```

**Comment by joeyparrish** [comment]
@Zorig, are you using the demo app or a custom app?  If custom, are you using `shaka.media.DrmEngine.probeSupport()`?

**Comment by Zorig** [comment]
@joeyparrish I am using custom app(Ember 2.10) also i used probeSupport like this. Is it wrong usage?
```
shaka.Player.probeSupport().then((support) => {
    if (support.drm['com.widevine.alpha']) {
    // this.set('video', document.getElementById('video'));
    // this.set('player', new shaka.Player(this.video));
    } else {
        this.set('error', 'ERROR');
    }
});
```

**Comment by joeyparrish** [comment]
Ah, that makes sense now.  The warning is triggered by `probeSupport()`.  Because it probes for multiple key systems and because we do not hard-code valid robustness strings per key system, the probe does not specify any robustness.

**Comment by Zorig** [comment]
okay, @joeyparrish so how should i set robustness in this case? checking widevine is essential in my case. And some drm songs are not playing because of robustness i think

**Comment by joeyparrish** [comment]
I'm not sure I understand the question.  You don't need to set robustness in any way to call `probeSupport()`.  Is `probeSupport()` not working?  Or are you just trying to silence the warning?

**Comment by Zorig** [comment]
Some of my songs are not playing. So i thought it is because of robustness level according to warning. And when i set robustness level it still gives me robustness warning

**Comment by vinixwu** [comment]
I got the same error on basic code. It's triggered by navigator.requestMediaKeySystemAccess method used to test if certain key system is supported:
```javascript
var config = [{
	"initDataTypes": ["cenc"],
	"audioCapabilities": [{ "contentType": 'audio/mp4;codecs="mp4a.40.2"' }],
	"videoCapabilities": [{ "contentType": 'video/mp4;codecs="avc1.42E01E"' }]
}];
try {
	navigator.
		requestMediaKeySystemAccess("com.widevine.alpha", config).
		then(function (mediaKeySystemAccess) {
			console.log('widevine support ok');
		}).catch(function (e) {
			console.log('no widevine support');
			console.log(e);
		});
} catch (e) {
	console.log('no widevine support');
	console.log(e);
}
```
Add robustness level setting to config object solved the problem:
```javascript
var config = [{
	"initDataTypes": ["cenc"],
	"audioCapabilities": [{ "contentType": 'audio/mp4;codecs="mp4a.40.2"', robustness: 'SW_SECURE_CRYPTO' }],
	"videoCapabilities": [{ "contentType": 'video/mp4;codecs="avc1.42E01E"', robustness: 'SW_SECURE_CRYPTO' }]
}];
```
Besides, this warning only triggered when key system is "com.widevine.alpha". Add robustness setting to other key system causes exception and returns false positive result:
> DOMException: Unsupported keySystem or supportedConfigurations.
