### ISSUE TITLE
Widevine not working on certain Android devices

### ISSUE THREAD

**Issue by hghazzi** [google/shaka-player#519]
Shaka 2.0.0

http://shaka-player-demo.appspot.com/demo/

When selecting a Widevine asset in the demo app using Android Chrome, I would receive this error and it would begin to infinitely buffer.

![screenshot 2016-09-14 12 00 01](https://cloud.githubusercontent.com/assets/584053/18519725/f2e2274c-7a72-11e6-96e9-645caeeaba35.png)

Same thing occurs when I implemented in our codebase.

**Comment by joeyparrish** [comment]
@hghazzi, I am unable to reproduce this on my Nexus phone.  What version of Android and Chrome are you using?  What make/model of Android device are you using?

**Comment by hghazzi** [comment]
I just tested it on Chrome 52.0.2743.98 on Android 6.0.1; Nexus 5X
Build/MTC20F, and got the error while playing Angel One (multicodec,
multilingual, Widevine) after accepting to play premium content.

**Comment by joeyparrish** [comment]
Based on the error code, I would say it's probably a decoder failure.  However, I'm testing on a Nexus 5X as well, with Android 6.0.1, build MTC19T, Chrome 53.0.2785.124, and I still can't reproduce.  There's no obvious reason why we should be getting different results.  You are running an official build of Android, correct?

I'll ask if anyone else in the office here can try on different Android devices.  Perhaps one of them will reproduce your issue and we can start making educated guesses on why.

In the mean time, please try on other devices for yourself.  I do not believe you should get this result, and I expect there is something peculiar about your device.

If we can somehow make Shaka Player more robust on that device, we will.  But depending on what the cause is, there may be nothing we can do.

**Comment by hghazzi** [comment]
Hey Joey, 

I've tried it on 3 more devices, 2 of which are running Nougat. All have the same error. Only the R1 HD is not using a stock version of Android. 

Chrome 53.0.2785.124; Android 7.0.0; Nexus 5X Build/NRD90R
Chrome 53.0.2785.124; Android 7.0.0; Nexus 6P Build/NRD90U
Chrome 53.0.2785.124; Android 6.0.0; R1 HD Build/MRA58K

**Comment by joeyparrish** [comment]
@hghazzi, can you get logs for me to help us figure this out?

Go to the shaka player demo, recreate the error, then open a new tab.  Navigate to `chrome:media-internals`.  On the media-internals page, under the heading "Players", click the button with a label like `blob:https://shaka-player-demo.appspot.com/...` and logs should appear at the bottom.  If you could select all, copy, and then paste here for us, that would be very helpful.

**Comment by hghazzi** [comment]
Hey @joeyparrish, sorry for not getting back to you sooner. Here are the logs and properties

```
Logs

00:00:00 00 pipeline_statekCreated
00:00:00 00 eventWEBMEDIAPLAYER_CREATED 
00:00:00 00 urlblob:http://shaka-player-demo.appspot.com/5d1c0fca-37f4-405f-93ac-fb921fe5ee3c
00:00:00 01 pipeline_statekInitDemuxer
00:00:11 192 duration60.021331
00:00:11 840 found_video_streamtrue
00:00:11 840 video_codec_namevp9
00:00:11 840 found_audio_streamtrue
00:00:11 840 audio_codec_namevorbis
00:00:11 841 pipeline_statekInitRenderer
00:00:11 856 debugDecryptingDemuxerStream: no decryptor
00:00:12 103 audio_ddsfalse
00:00:12 103 audio_decoderMojoAudioDecoder
00:00:12 104 debugDecryptingDemuxerStream: no decryptor
00:00:12 173 errorvideo decoder initialization failed
00:00:12 173 pipeline_errordecoder: not supported
00:00:12 175 pipeline_statekStopping
00:00:12 175 pipeline_statekStopped

Properties

render_id: 4
player_id: 6
pipeline_state: kStopped
event: WEBMEDIAPLAYER_CREATED
url: blob:http://shaka-player-demo.appspot.com/5d1c0fca-37f4-405f-93ac-fb921fe5ee3c
duration: 60.021331
found_video_stream: true
video_codec_name: vp9
found_audio_stream: true
audio_codec_name: vorbis
debug: DecryptingDemuxerStream: no decryptor
audio_dds: false
audio_decoder: MojoAudioDecoder
error: video decoder initialization failed
pipeline_error: decoder: not supported

```

**Comment by joeyparrish** [comment]
Thanks for the logs!  (I reformatted them into markdown.)

I will have to ask for help from someone on Chrome team.  I don't know what to make of this info yet.

**Comment by joeyparrish** [comment]
Can you provide logs from adb?  I've been advised to ask for `adb logcat -v threadtime` or `adb bugreport`.  I assume these logs will be long, so please attach as a file rather than pasting into github.

**Comment by hghazzi** [comment]
Here you go @joeyparrish . Included the output from both commands.

[shaka-android-widevine-bugreport.txt.zip](https://github.com/google/shaka-player/files/559474/shaka-android-widevine-bugreport.txt.zip)
[shaka-android-widevine-logs.txt](https://github.com/google/shaka-player/files/559473/shaka-android-widevine-logs.txt)

**Comment by joeyparrish** [comment]
I am still unable to reproduce this issue myself.  Based on my (amateur) reading of your Android log file, there seems to be a decoder error, which is outside the control of Shaka Player.  I've forwarded your logs to someone at Chrome and I'm waiting on a reply.

**Comment by hghazzi** [comment]
Thanks for following up on this, Joey!

**Comment by bbert** [comment]
Hi,
Do you have some news on this issue?
I have done some tests on 2 different mobiles phones, of the same brand and with the same Android version (4.4.4).
In one case the video is decrypted and played, but in the other case I have the same error (DecryptingDemuxerStream: no decryptor).

**Comment by joeyparrish** [comment]
Sorry, I do not have any news.  I am still unable to reproduce this issue myself.  There seems to be a decoder error, which is outside the control of Shaka Player.  I've forwarded your logs to someone at Chrome and I have not received a reply yet.

My advice to you is to file a bug on Chrome here: http://crbug.com/

When you have done so, please link to the bug report here so that we can track the issue and try to raise the profile of the issue with the Chrome team.

**Comment by joeyparrish** [comment]
@hghazzi, @bbert, has anything changed for you on this issue?  Are you still seeing decoder failures on Android with the latest Chrome and Shaka Player?

**Comment by bbert** [comment]
With chrome 56, the issue is still present and identical.

**Comment by joeyparrish** [comment]
I'm still unable to reproduce it myself.  I will try to get advice from Chrome team again.  I apologize that we have been unable to help you so far.

**Comment by joeyparrish** [comment]
Chrome team has reproduced the error and are investigating.  So far, it appears to be a bug in Chrome for Android, and it appears to be specific to Vorbis content.  I will try to keep you posted as we learn more.

**Comment by joeyparrish** [comment]
@hghazzi, in your screenshot, it appears that you have selected an asset that is MP4 only.  What Chrome team is investigating is specific to Vorbis.  Can you confirm if this issue can be reproduced with the asset "Tears of Steel (Widevine)" specifically?

**Comment by bbert** [comment]
On my side, I reproduced the issue with MP4 assets, especially with "Tears of Steel (Widevine)"

**Comment by hghazzi** [comment]
@bbert thanks for testing it out!

**Comment by anurag42** [comment]
Hi, was this bug resolved? I am not able to play video on chrome on android.

**Comment by joeyparrish** [comment]
This bug was not resolved.  It was tracked down to something outside Shaka Player, either in Chrome or Android, and was given the "external" label to indicate that.  We still do not know the reason for the original poster's issue, and my team is unable to reproduce the issue on any of our Android devices.

**Comment by anurag42** [comment]
ohk. Would you know if a corresponding bug was filed in Chrome? I could follow it up there.

**Comment by joeyparrish** [comment]
I do not know if a bug has been filed with Chrome.  @hghazzi, did you ever file anything at crbug.com?

**Comment by hghazzi** [comment]
@joeyparrish @anurag42 I haven't tested this recently with the devices mentioned above, though it works on my Pixel 2 with the latest version of Chrome. I never created a chromium bug since you mentioned they were able to reproduce it, so figured that they already did.

**Comment by joeyparrish** [comment]
Closing this stale external (non-Shaka) issue. If you disagree, please reply with @shaka-bot reopen, and it will be automatically reopened.
