### ISSUE TITLE
Hiccups when clearing buffer

### ISSUE THREAD

**Issue by yairans** [google/shaka-player#520]
Hi,
I would like to tell shaka do not clear the buffer when it switches between the video track automatically (when adaptation is enabled). The buffer clearing causes hiccups on IE11.
Is there a way to configure this behaviour?

Yair

**Comment by dobrusev** [comment]
I'm using DASH with Widevine and I see the same behavior - hiccuping  in chrome.
Sometimes I see glitches during playback as well. 

When I compare I have a better performance without glitches on the old version of shaka.

I agree with Yair. It will be nice if there is a solution in the default configuration that can be made for better performance.

**Comment by joeyparrish** [comment]
Hi Yair, Dobrin,

We are working on it and hope to release improvements in v2.0.1 as soon as feasible.  Thanks!

**Comment by joeyparrish** [comment]
In a8ac3142ef515c14275f548af6905066b22198c2 we made buffer clearing explicit and more flexibl for calls to selectTrack().  When the ABR manager is making the call, though, it still decides if/when/how to clear the buffer.

**Comment by dobrusev** [comment]
That was fast!

Thanks Joey Parrish.
I will try it now and update you guys here.

**Comment by dobrusev** [comment]
After retesting I don't see any hiccuping in chrome. And the switches between the video tracks is smooth.

Again thanks for the great work!

**Comment by joeyparrish** [comment]
The thing that fixed it was probably when we switched from clearing 10 seconds ahead to clearing 2 segments ahead.  Clearing based on segment size reflects the reality of how MediaSource works, while 10 seconds was only a guess at the segment size anyway.

@yairans, can you confirm that this has improved things for you as well?

**Comment by yairans** [comment]
@joeyparrish 
It plays perfect now.
Thank you.

**Comment by joeyparrish** [comment]
Excellent!  Thank you for retesting.

**Comment by joeyparrish** [comment]
I'm now seeing hiccups on ChromeOS and Chrome Linux.  The hiccup occurs when an upgrade decision is made, specifically caused by clearing content that is ahead of the playhead.

More testing is needed on other browsers/platforms.
