### ISSUE TITLE
Shaka 2.0.0: Simplifying Clearkey Configuration

### ISSUE THREAD

**Issue by hghazzi** [google/shaka-player#524]
The new configuration for ClearKey is
```
// v2:
player.configure({
  drm: {
    clearKeys: {
      'deadbeefdeadbeefdeadbeefdeadbeef': '18675309186753091867530918675309',
      '02030507011013017019023029031037': '03050701302303204201080425098033'
    }
  }
});
```

Given that we could retrieve the Key ID from the manifest, similarly to how it was done in v1, why do we need to even send the Key ID? Couldn't we just have an even simpler config that just takes the key?

**Comment by joeyparrish** [comment]
@hghazzi, it's not clear to me what you're asking for.  Are you asking for the key ID to be extracted from the manifest automatically?  Or to be able to specify keys without key IDs?

**Comment by hghazzi** [comment]
Hey @joeyparrish, yeah, I was wondering why not extract the Key ID from the manifest automatically instead of requiring it to be provided in the configuration.

**Comment by joeyparrish** [comment]
There is a standard way to store key IDs in a DASH manifest.  However, they are optional and may not be present.

Even if key IDs were required, it still wouldn't be enough for the app to provide the keys alone.  Content often has multiple keys.  It is best practice to use different keys for audio and video, or generally to use different keys for any tracks with different security requirements (SD vs HD vs UHD, for example).

So if we extracted key IDs from the manifest, and the app provided keys only, there would be no way for us to match up the keys to their key IDs.

An encrypted segment contains the ID of the key needed to decrypt it.  So the browser's media pipeline must be able to ask the CDM to decrypt using a particular key ID.  Without a mapping of key ID to key in the license, the CDM can't do its job.  Without a mapping of key ID to key from the app, Shaka Player can't construct the license the clear key CDM needs.

Does that make sense?

**Comment by hghazzi** [comment]
Ok, yeah, that makes sense. Thanks, for the info, Joey!
