### ISSUE TITLE
How get available bit rate or change bit rate in video?

### ISSUE THREAD

**Issue by vahid-01** [google/shaka-player#525]
I use the last version and want to know how get available bit rate and how notify when bit rate change.
is there any event for that?
this isn't bug but I can't find better place for asking.

**Comment by joeyparrish** [comment]
See [shaka.Player.getStats()](http://nightly.shaka-player-demo.appspot.com/docs/api/shaka.Player.html#getStats) and [shakaExterns.Stats](http://nightly.shaka-player-demo.appspot.com/docs/api/shakaExtern.html#Stats) in the docs.  You can get the current bandwidth estimate like so:

```js
player.getStats().estimatedBandwidth
```

There is also an [AdaptationEvent](http://nightly.shaka-player-demo.appspot.com/docs/api/shaka.Player.html#event:AdaptationEvent) fired when the player makes an ABR decision.  To listen for the event and see what was chosen, try this:

```js
player.addEventListener('adaptation', function() {
  var tracks = player.getTracks();  // all tracks
  tracks.forEach(function(t) {
    if (t.active) {  // an active track, that is, in use by the player right now
      console.log('ACTIVE:', t.type, t);
    }
  });
});
```

If you have questions and you don't think a github issue is appropriate, you can always write to our users list: https://groups.google.com/forum/#!forum/shaka-player-users

Does this help?

**Comment by joeyparrish** [comment]
@vahid-01, did we answer your question?  Is this still an issue for you, or can we close this?

**Comment by vahid-01** [comment]
Thank you. you can close that.
