### ISSUE TITLE
Executing build\all.py on a clean clone fails

### ISSUE THREAD

**Issue by sandersaares** [google/shaka-player#526]
- What version of Shaka Player are you using?

b61270460cc691eeabb84b4e06f7b26b0eb3e080 (latest master branch)

- What did you do?

Cloned repository.
Executed `npm install`
Executed `python27 build\all.py`

Environment is Windows 10, with "Python 2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)] on win32"

- What did you expect to happen?

A successful build process.

- What actually happened?

```
Generating Closure dependencies...
Running Closure linter...
Traceback (most recent call last):
  File "c:\Source\shaka-player\third_party\gjslint\gjslint", line 29, in <module>
    from closure_linter import gjslint
  File "c:\Source\shaka-player\third_party\gjslint\closure_linter-2.3.13\closure_linter\gjslint.py", line 168
    print '%s: %d' % (path, len(path_errors))
                 ^
SyntaxError: invalid syntax
```

**Comment by joeyparrish** [comment]
Looks like python 3 is being invoked for gjslint.  @sandersaares, can you confirm if `python` invokes python3 in your environment?

We have 'python' hard-coded into the command lines of two of our build steps:

```
check.py:  cmd_line = ['python', cmd] + args + get_lint_files()
gendeps.py:    cmd_line = ['python', deps_writer] + deps_args
```

Perhaps those should say python2, specifically.  @sandersaares, please try changing those to python2 and see if it resolves your issue.

**Comment by sandersaares** [comment]
I confirm modifying these lines to explicitly reference Python 2 does help the build process move forward. As I believe there is no standard way to choose which version of Python to run (they all come as python.exe by default), I imagine the best fix would be to always run the same Python executable that is always running, e.g. from `sys.executable`.

However, now it fails with the following output:

```
Generating Closure dependencies...
Running Closure linter...
162 files checked, no errors found.
Running htmlhint...
Traceback (most recent call last):
  File ".\build\all.py", line 42, in <module>
    shakaBuildHelpers.run_main(main)
  File "C:\Source\shaka-player\build\shakaBuildHelpers.py", line 207, in run_main
    sys.exit(main(sys.argv[1:]))
  File ".\build\all.py", line 30, in main
    code = check.main([])
  File "C:\Source\shaka-player\build\check.py", line 157, in main
    elif not check_html_lint():
  File "C:\Source\shaka-player\build\check.py", line 80, in check_html_lint
    return subprocess.call(cmd_line) == 0
  File "c:\Python27\lib\subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "c:\Python27\lib\subprocess.py", line 711, in __init__
    errread, errwrite)
  File "c:\Python27\lib\subprocess.py", line 959, in _execute_child
    startupinfo)
WindowsError: [Error 193] %1 is not a valid Win32 application
```

I also tried upgrading my Python 2 but this changed nothing. New version is: `Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)] on win32`

**Comment by joeyparrish** [comment]
Window is supported, but we don't test the Windows build often enough.  We'll fix it.  Thanks for the report!
