### ISSUE TITLE
Some DRM providers require default KID in wrapped license requests

### ISSUE THREAD

**Issue by birme** [google/shaka-player#528]
Shaka v2

For caching and content lookup, some DRM license providers require default KID in CENC-section of MPEG DASH manifest (key ID) in wrapped license requests. When available the default KID needs to be exposed to the client application "intercepting" the license request with a request filter. Proposing adding default KID to shakaExtern.DrmInfo object.

**Comment by sandersaares** [comment]
I am curious about the use case - can you explain more? Do I understand it right that the license server you are working with requires the key ID to be supplied as a custom extension to the license request, in addition to the key ID that already exists in the DRM system domain (inside the DRM-technology-specific part of the license request)? If so, how is this data used - is it simply passed to the license server as-is?

**Comment by birme** [comment]
@sandersaares: Yes, correct. It requires in addition to the DRM-technology-specific part this key ID and that is used for internal lookup before it proxies the license request to the license server. I think it is used for caching purposes but that is an area where I don't have the insights in

**Comment by joeyparrish** [comment]
Fixed by #529 (d05b7d5d0ce3b844f193327f5f5fe66d8f70f312)
