### ISSUE TITLE
Demo Stream Error in Edge

### ISSUE THREAD

**Issue by hghazzi** [google/shaka-player#530]
Version: Shaka 2.0.0.0

Browser: Edge on Windows 10

In the Shaka Demo page, "Tears of Steel (multiperiod with segmented subtitles and PTO)" throws Shaka Error 3015 and displays "Shaka Error MEDIA.MEDIA_SOURCE_OPERATION_THREW (InvalidAccessError)" in the player about a minute into the video. The video continues to play for a little while longer before hanging. Seems to be only occurring in IE11/Edge. Is this an issue with the stream or Shaka?

**Comment by joeyparrish** [comment]
It's likely an issue with the stream, but we'll look into it.  Thanks for the report!

**Comment by joeyparrish** [comment]
This appears to be a bug in Edge.  We will file a bug on them and add a workaround until they fix it.

**Comment by hghazzi** [comment]
Thanks, Joey! Can you share the bug ticket when its created so we can keep track of it?

**Comment by joeyparrish** [comment]
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/9127291/

**Comment by joeyparrish** [comment]
There's a workaround in place for now.  You should see everything working at http://nightly.shaka-player-demo.appspot.com/demo/ .  If not, please let us know.
