### ISSUE TITLE
Multi period VOD with gaps in the timeline

### ISSUE THREAD

**Issue by erankor** [google/shaka-player#537]
Hi,

I've been testing several different DASH manifest types - all combinations of:
1. live / vod
2. multi / single period
3. segment timeline / template / list

All combinations worked fine except one - multi period vod that uses SegmentTemplate.
What happens is that the player hangs after the first period - it does not load the init segment nor the fragments of the second period.
This is the stream URL:
http://lbd.kaltura.com:8001/mapped/playlist-saas.php/disc/1/type/vod/manifest.mpd

Oddly, the respective live URL is working:
http://lbd.kaltura.com:8001/mapped/playlist-saas.php/disc/1/type/live/manifest.mpd

The tests were executed on the demo player (v2.0.0-debug):
http://shaka-player-demo.appspot.com/demo/

All tests were performed on Chrome v53.

Thank you,

Eran

**Comment by joeyparrish** [comment]
I have reproduced this on Chrome for Linux.  It appears that your content has gaps in between the periods.  This is not supported.  There should be no gaps in the timeline.  Please report this as a bug to Kaltura.

**Comment by erankor** [comment]
@joeyparrish, thank you for your reply !
I am from Kaltura... :)

Can you please explain what are the gaps you are seeing ?
Because I tested it now, and I don't see any gaps - 
- the duration of the first period in the MPD is 83.049
- the earliest presentation time of the first fragment (in the sidx box) is 0
- the earliest presentation time of the last fragment of the first period (fragment-9-v1-x2.m4s) is 0x006df927
- the sum of frame durations in this fragment is: 0xbbb * 0x58 + 0xb7b = 0x413C3

therefore - <last PTS of first period> - <first PTS of first period> = 0x6df927 + 0x413C3 = 0x720CEA = 7474410.
the timescale in the sidx box is 90000, so we get 7474410 / 90000 = 83.049, which is exactly what is stated in the MPD.
I also checked the PTS delay in the trun atom of the first and last frames of the period, and both have 0x1776, so that shouldn't be a problem either.
I didn't check the other periods, because, as I previously wrote, no fragment of the second period is being pulled from the server.

Thanks again,

Eran

**Comment by PatrikCarlander** [comment]
http://lbd.kaltura.com:8001/mapped/playlist-saas.php/disc/1/type/vod/manifest.mpd
Your stream will play before commit 0df1ab0
Or you can comment out code line 855, 856, 857 and 860 in streaming_engine.js
It's related to bug #545

**Comment by ismena** [comment]
That's right, this had the same problem as #545. 

@erankor I tested your stream with the fix and it seems to be fine.
(I also liked the video :) ).

Let me know if you have any questions.

**Comment by joeyparrish** [comment]
It seems I misdiagnosed your steam.  Sorry about that!

**Comment by erankor** [comment]
No problem, glad this was resolved. 
Thanks everyone !
