### ISSUE TITLE
Live stream with 2 s segment size doesn't play.

### ISSUE THREAD

**Issue by dobrusev** [google/shaka-player#541]
Hello,

I have this live video asset with 2 s segment size https://testlivesport-a.akamaihd.net/out/u/mpd_unencr_2s2s.mpd.

Using [shaka demo app v2.0.0]( http://v2-0-0-beta.shaka-player-demo.appspot.com/demo/) I get error 5002 - Shaka Error STREAMING.SEGMENT_DOES_NOT_EXISTS

Using [shaka demo app v1.6.5](http://v1-6-5.shaka-player-demo.appspot.com/) the video plays fine.

Can someone have a look at this please ?

Thanks in advace!

**Comment by joeyparrish** [comment]
The link to v2 you gave is actually a link to v2.0.0-beta, which is quite old.  Please use the final release of v2.0.0: http://v2-0-0.shaka-player-demo.appspot.com/demo/

Your live stream is broken.  v1.6 had a complex system that managed to "fix" many types of broken manifests, such as this one, but also broke others and did not follow the DASH spec.  v2 is more strict and follows the spec more closely, which means your content must also follow the spec.  This is why it "worked" in v1, but not in v2.

One thing that jumped out at me when I examined your manifest is that `availabilityStartTime` appears to be moving when the manifest is updated.  This makes no sense.  `availabilityStartTime` is critical to determine what is available in a live stream.

I stopped digging into the manifest once I saw moving `availabilityStartTime`.  To start, I strongly recommend getting the latest updates from your encoder vendor to make sure you have any bugfixes they may have made for live streams.

If you still have problems after updating your encoder, I then recommend you file a bug with the encoder vendor to get support from them.  There are lots of vendors who are getting this right.  We firmly believe that the best thing we can do for the DASH ecosystem is to expect everyone to follow specs and interoperability guidelines.  If we hid or worked around encoder bugs like we did in v1, buggy encoders wouldn't get fixed and we'd have a more complex and buggy client to maintain.

**Comment by dobrusev** [comment]
many thanks @joeyparrish for your detailed explanation.

I will forward this to the encoder vendor.
