### ISSUE TITLE
Update docs to state file:/// URLs cannot be used for development

### ISSUE THREAD

**Issue by shintaroid** [google/shaka-player#543]
I followed exactly the same way as in

http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html
http://shaka-player-demo.appspot.com/docs/api/tutorial-basic-usage.html

to build Shaka Player and test playing (the test code is exactly the same as in the above link), and indeed I successfully played the movie clip in my Safari browser. But in the case of Chrome, it failed with the same code, here's what the error like in Chrome's console:
![screen shot 2016-10-07 at 16 36 36](https://cloud.githubusercontent.com/assets/19260845/19182305/816dd8ca-8cad-11e6-803a-40e8f5632d3b.png)
![screen shot 2016-10-07 at 16 36 24](https://cloud.githubusercontent.com/assets/19260845/19182307/85edd08a-8cad-11e6-859e-a13436c3f5d1.png)
My computing environment:
-OS:  Mac OS X 10.11.6
-Chrome: Version 53.0.2785.143 (64-bit)

**Comment by joeyparrish** [comment]
My best guess is that you are not using a web server and instead are using a `file://` URL.  This is something the browser does not allow.

**Comment by joeyparrish** [comment]
It seems we don't state this explicitly in the docs.  We will update the docs to fix this.

In the mean time, you must run a local web server and access the content from `http://localhost/...` instead of `file:///...`

**Comment by shintaroid** [comment]
Sorry I reported something inaccurate: I didn't follow exactly the same way, in fact I used a sample link for ```manifestUri```:

```var manifestUri = "http://yt-dash-mse-test.commondatastorage.googleapis.com/media/car-20120827-manifest.mpd"``` 

Nevertheless, like I reported I indeed can play the video clip by Safari. But with the same html file it fails on Chrome. By the way, I can't find any ```file:///``` URL in the above documents, you mean ```//storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd```?
