### ISSUE TITLE
request mpd file failure

### ISSUE THREAD

**Issue by FeiCao** [google/shaka-player#554]
version:1.6.4

shaka-player request mpd file failure sometimes, shaka-player print error is "http://10.50.63.168:8089/temp//4687170460587928861/live.mpd?_=1476516326982 net::ERR_CONNECTION_RESET" in chrome console and the request header see follow picture.

![cuowu2](https://cloud.githubusercontent.com/assets/12422206/19430728/040eabf6-9488-11e6-87fb-4183b8442c70.PNG)
![cuowu](https://cloud.githubusercontent.com/assets/12422206/19430145/bb8abc46-9485-11e6-9ae0-b4d547183e53.PNG)
![cuowu3](https://cloud.githubusercontent.com/assets/12422206/19430422/be8f1206-9486-11e6-90c0-bcb15b48771d.PNG)

ajax_request.js line 281 report the error.

My http server's IP:10.50.63.168 and my PC's IP: 10.50.63.75, they connected with a 100Mb router.  Can you help me to analyse the reasons? thank you.

**Comment by joeyparrish** [comment]
ERR_CONNECTION_RESET means the TCP connection was reset.  This is below the level of HTTP and could have many root causes.  If no server is listening on the port (8089 in your case), then the OS will send a TCP reset when the client tries to open the connection.  The connection would also be reset after it is established.

I can only guess what is causing it, but you should look at your server first.  Unfortunately, that's the most support I can realistically give for server errors.  If you need help finding resources for further reading, let me know.
