### ISSUE TITLE
Shaka 2.0.0 always chooses lowest quality stream with some manifest files

### ISSUE THREAD

**Issue by waaronking** [google/shaka-player#556]
On Shaka 2.0.0 I'm running into a strange issue where the player consistently loads the lowest quality stream option. I am able to reproduce this error on the [demo player](http://shaka-player-demo.appspot.com/demo/).

Here is a direct link to the manifest file on S3: 
https://s3-us-west-2.amazonaws.com/com.vivintsolar.sites/dash-media/homepage2/stream.mpd

On a fresh page load when the player fetches the video assets, it consistently loads and stays at the 360p quality. Using the demo page, you can look at `Info > Video tracks` and see the 3 separate video qualities. Manually selecting one of them allows them to load fine.

This manifest file was created using mp4box. I also tried using mp4frag and both manifest files had the same behavior. As a side note, if I use videoJS with the dash plugin (an alternative to shaka), these manifest files work great (they load the highest quality video on high bandwidth connections).

It feels like user bandwidth detection is possibly broken for certain manifest files or short video lengths. Is there possibly an issue with the way the manifest file was generated? Do I need to use another tool to re-generate it?

**Comment by joeyparrish** [comment]
Shaka Player uses a default bandwidth estimate before it has enough data to build a real estimate.  That default is configurable, and defaults to 500kbps.  You might want to try customizing that.  See [abr.defaultBandwidthEstimate in the player configuration](http://nightly.shaka-player-demo.appspot.com/docs/api/shakaExtern.html#AbrConfiguration).

Also, we recently made some changes to speed up adaptation decisions.  Can you try again using [our nightly build](nightly.shaka-player-demo.appspot.com) to see if the situation is improved?

**Comment by waaronking** [comment]
The nightly build completely fixes this issue for me! Thank you so much for your help.

Is there a planned release in the near future, or will I need to compile and host the script myself to get this working on my site?

**Comment by joeyparrish** [comment]
We intend to release v2.0.1 with this fix soon, but we are still doing QA to make sure the ABR changes are good ones.  In the mean time, you do not have to wait for release versions if you want to build from `master`.

**Comment by waaronking** [comment]
@joeyparrish perfect. This is now working great for me. Thanks for your help!
