### ISSUE TITLE
License server request body

### ISSUE THREAD

**Issue by Alex6015** [google/shaka-player#557]
Shaka player 2.0.0.0

I'm implementing license server, and trying to make license request from shaka player to the license server following the tutorial on https://shaka-player-demo.appspot.com/docs/api/tutorial-drm-config.html

from the documentation I understood the request should be JSON with key id parameter, 
but the shaka player body of the request (payload) contains the following data that I don't know how to parse:

```
ð	
³ChromeCDM-Windows-x86Þ¬"0
¡§d²7úÝ³ÛD¼§Â òú3GõÄËÔËÃT¨yÊÔ×Ð©Ú¯åÞ¯E-Á<|A
]ãµä,Ðù÷#ÆÈxá=-¥5WL^Üí
î©­ùh¦öd÷1Ç|<]JÑÊÃ$û:uË£
GØ
ê·Lf·¶èZ©d[ÃvÙ³¡.ám\Ì0ñ¹LÂ|4^¨îÇÍÚ²Ìu¾Uò9S f¤~éÆF	I
[¸B+]¼ÏÍJµàR<;56RÙà	vz3NÓIYl${y¬¬@Ú8¡ÇCÚÕ_úÊkK³ÿ	(þ!8Ò¦àÿ°î"»H Wlrê¦ü^ÇÃQËÖ÷JÙø¼â­ ¾Ù'¯IÙ[UÐÁç£fØþÎÄäg!Ríx|t@}É[ªþ6XCðÀ:åh6¹bØ¢ \Ùª6BYw£ày/¿9w-ýhÙ ¶7|Ñ\ûÎ¨¶ñ{¶ø´ÚJFýt»JÈ­ßiG_4ÿ¦µÔsés£tåS¹s°I§RqqND¾º+¶}aø6àíN7;FxhdMÊ^4r(Ë3o4iìä¦ä7fåÒÑ
ÖwtÖ¨­g<»óÆll*íp´
®ÖÒïäáX=EûË.®¥"0
ëÙ-ä
v;©N+O
]{h£<ý±Ø4Øáèí®¼Sa<?QUáiØàq·­iÞùÄsÏjïÜM&ÆiiÜ÷çÑÝ4úðÁ½ãXGKÉå©
á »óÙÂ+Å^$»Óâ{äÎtsïºæi¥G¶5Æp¹ÊÅî³Ø§ä.¯n(³4¸ÚE
>^X¨ pnºkÑ¼ºÍg±ì¥>ü+ýÀ`/-õ2÷ÞÁäé,·~%~ä¸[_>¼"(÷óV<;P{f¨x¥½èNâFiËyf)4Êç(þ!² o¢÷§³ª¡î¾µ{ï®øÏW3Æönßh¢Fò`/A|-ü¸ÍÇà¡Ô«sBlN¸¢RfúâµÈ¼ÎÔÿ¿î¸«Sßùt¨ùb	y­zâÛd6îÙWÂûo8«$À	SÄ£^ñãæh1ý¼CÊW#Í¯_xv¡k¡¡>IÀ
%¬<ëG2o@k/F¶ÙN¾h)B±R³k¯ÙRgX1­É[ªÌ¯ü
½²·íRÖE-j\+èDÆÖ|øJ ùGö½)ué9àBÕ©mÑÁ¤Wû(½
=x>OdUjL²ò¶?ÈaV×<ìý¤¢Kxª÷Tâ×«p
¤]üüeå¾T¹"cn©R]÷ê¨¸âÌ}·O®ËÐÌ~(wò,âØKqZo¼@ãte°§òèÎÔ¬Uº"×áº6þ¬`%
3ë#4:#1&+ý*|Î	
architecture_namex86-32
company_nameGoogle

model_name	ChromeCDM

platform_nameWindows!
widevine_cdm_version	1.4.8.9032 k
i
Sh¬ÌÖ¬SXl1à¿9>ÔazPj"nrÇõÉ·D-`Ò­]î¥Ç>ñÃ
widevine_test"ÎÅ¿õÜ@ÝÉ2ÍÈÀ¦k\{eè´
;Ä çÒÀ0l±ÌtËæØ\%§vtÞ%Âÿ;)öË4èµ	Q'%Ô&õLæúóJüän¯ÃF¯^::ÍªÜ
NÈJÍLdü&òÎ`ü®§ºÌÀH+à7ÏÇíýnqþ%¹®§
_ë`h
híö`ÿ#´QÍ²+ zéãýXMí!åo¨r¹$ Òzl8ôB.é¨¾Ä¤×RúòfÛÓAf©s@ïw't±5óC©OSÑHb½LRóhÍÉ]º#+`÷-òà«(AYçÉ©¥ô0êÄ/ë|ÜLê?µ¸
```

is this the payload I need to pass to widevine? 

Thanks in advance
Alex

**Comment by joeyparrish** [comment]
Hi Alex,

A Widevine license request is not in JSON format.  I apologize if the docs gave you the wrong impression.  If you can point out what part of the docs made you think that, we will be happy to correct them.

Shaka Player will not, by default, make any changes to the format of the license request or response.  The request from the CDM is sent directly to the configured license server, and the response from that license server is given directly back to the CDM.  Both request and response are in a non-readable binary format.

Does that answer your question?

**Comment by Alex6015** [comment]
Hi Joey,
Thanks for the fast response

i have misread the documentation in "DRM Configuration" section, it has "license request format" link, its for clear key license only now i understand.

guess the request shaka player is sending to the license server is the "payload" the license server needs to pass to widevine,
and if i want to pass additional parameters i would need to use "License Wrapping" and add any additional parameters like "content id" for example
is that correct?

**Comment by joeyparrish** [comment]
The raw request coming from the CDM should be sent to the Widevine backend in whatever format the backend requires from the proxy.  I can't comment on what additional parameters you might need, but anything you want to add to the request on the client side will require license wrapping.

**Comment by Alex6015** [comment]
Got it.
Thank you!
