### ISSUE TITLE
Cannot set restrictions on the fly.

### ISSUE THREAD

**Issue by sanbornhnewyyz** [google/shaka-player#57]
Currently, bandwidth restrictions are only effective if they are set prior to loading content. Setting them after content is playing appears to be setting the restrictions object fine but the restrictions are not limiting  which variants are getting played.

Shaka version: v1.2.0-154-g5f063f0

**Comment by joeyparrish** [comment]
This doesn't seem right.  Setting restrictions on the player at any time should result in a call to StreamVideoSource.prototype.setRestrictions(), which sets streamInfo.enabled=false for any stream which fails the new restrictions.

Any stream which has enabled set to false will not be returned by StreamVideoSource.prototype.getVideoTracks(), and therefore not be chosen by AbrManager.

After setting restrictions, does player.getVideoTracks() still return restricted tracks?

**Comment by sanbornhnewyyz** [comment]
Yup, you're right. I don't know what was going on yesterday that I thought it wasn't working.

**Comment by joeyparrish** [comment]
No worries!  Glad it's working.
