### ISSUE TITLE
Cannot autostart DASH stream

### ISSUE THREAD

**Issue by pszemus** [google/shaka-player#579]
- What version of Shaka Player are you using?
Shaka Player v2.0.1-debug

  - Can you reproduce the issue with our latest release version?
YES

  - Can you reproduce the issue with the latest code from `master`?
don't know

- Are you using the demo app or your own custom app?
demo app

- What did you do?
Tried to play stream: http://sds4.wp.tv/2942026-chunked/manifest.mpd

  - What content did you load?
http://sds4.wp.tv/2942026-chunked/manifest.mpd

    - If custom asset, what manifest and license server URIs?
manifest URL: http://sds4.wp.tv/2942026-chunked/manifest.mpd

  - How did you interact with the content, if at all?
no interaction

- What did you expect to happen?
Playing after clicking "Load" button

- What actually happened?
black screen with rotating color circle

I think it's a regression since Shaka Player v.2.0.0-debug plays that video well.
(I had to run Google Chrome browser with --disable-web-security to disable CORS checking)

**Comment by JeffJassky** [comment]
Same thing happened here using a Widevine manifest. I (temporarily) got around it by programmatically setting video.currentTime=0.1 and it kicked right on playing.

**Comment by joeyparrish** [comment]
Confirmed.  This played in v2.0.0, not in v2.0.1.  I'll see what I can do.

**Comment by joeyparrish** [comment]
`video.buffered.start(0)` is 0.023219 with both versions.  That should not keep us in a buffering state.

**Comment by joeyparrish** [comment]
I think I found the problem, and I'm learning to bake cupcakes in Polish!  It's a win-win!
