### ISSUE TITLE
getRestrictions() returns uglified object.

### ISSUE THREAD

**Issue by sanbornhnewyyz** [google/shaka-player#58]
Calling player.getRestrictions() returns a Restrictions object but the type is 'Sa' so it looks as if it's getting uglified in the build process. It works fine right now but it would be nice if the returned object actually was called a Restrictions object.

**Comment by joeyparrish** [comment]
Changing the name of the class is part of how the closure compiler works.  The names of the attributes are unchanged, so this is working as intended.

If the naming of the class itself is a problem for your application, you could always avoid compilation and run the uncompiled sources through the minifier of your choice.
