### ISSUE TITLE
Support PlayReady CustomData field

### ISSUE THREAD

**Issue by AndCycle** [google/shaka-player#581]
Just a note for now, haven't working on this one to make it work,

I am trying to make PlayReady DRM work with Shaka but found it missing the ability to put the CustomeData passing through PlayReady,

as the Microsoft document Content Decryption Module Data (CDMData) says
https://msdn.microsoft.com/en-us/library/dn457361.aspx

MS ver. of MediaKeys.CreateSession have the third arg to passing custom data for business logic,
then I found Orange-OpenSource/hasplayer.js has this implemented

https://github.com/Orange-OpenSource/hasplayer.js/blob/30d428b7e90c3e3c0818ec6a4d241fd5522a30be/app/js/streaming/protection/ProtectionModel_3Feb2014.js#L345

but currently missing in shaka as shaka just passed null on it,
https://github.com/google/shaka-player/blob/894c56d3c948c29cd9134cfcf2bb7b47cbb0e474/lib/polyfill/patchedmediakeys_ms.js#L420

**Comment by joeyparrish** [comment]
Sorry, we only support EME as spec'd.  The customData extension is not part of the standard.

See our [License Wrapping tutorial](http://shaka-player-demo.appspot.com/docs/api/tutorial-license-wrapping.html) for details on a standards-compliant way to accomplish the same thing.
