### ISSUE TITLE
Shaka player does not play video when play button is pressed.

### ISSUE THREAD

**Issue by sridhardvvce** [google/shaka-player#585]
Hi,

We are using shaka player to play DASH streams. Below DASH stream dont start when it is played.

https://s3-ap-southeast-1.amazonaws.com/learnyst/schools/1094/courses/6677/paid/25537/online/11/004_video_youtube_1mb_fdq7pg2zj7la7v7bke29webTrack.mpd

This is Not a DRM video.

I have tested with the demo player also. When the play button is pressed this stream is not starting. The stream starts to play when we seek a little using seekbar. When the video is seeked backed to 0 seconds again it stops playing and doesnot play even when we press the start button.

Note: In this stream there 2 video streams of same bitrate. We have many streams like this(Means where 2 streams have same bitrate and pixelsWidth/Height)

**Comment by joeyparrish** [comment]
Hi @sridhardvvce,

It looks like this was fixed by the same change that fixed #579, so I'm marking this as a duplicate.

**Comment by joeyparrish** [comment]
I like the Beatles video!  I am able to play with the latest code from the `master` branch.  Let us know if you are still having issues once you update.

**Comment by sridhardvvce** [comment]
@joeyparrish 

I have updated the code from git. 

If I play the video 10 times, 9 times it plays successfully.
1 or 2 times it fails to start when the play button is pressed. When we seek a little it starts playing.
