### ISSUE TITLE
What is the difference between using iFrame player api & shaka player? 

### ISSUE THREAD

**Issue by WeiChungChang** [google/shaka-player#586]
Hi:

I am evaluating several usage cases to build my application for MPEG DASH. 

But I am a little confused about the two different ways mentioned at title.

I am not sure if my understanding is correct so need a help here.

For me, the application needs a way to **play movies from YouTube on browser which is compatible with HTML5**. So the problem is I need a MPEG DASH player to do demux.

After surveying, I found it is possible & convenient to use YouTube iFrame player API directly. **But it seems that I CANNOT modify the code to do some customization**. Instead I could merely control the playback by calling APIs.

On the other hand, **if I adopts Shaka player, it is possible to rewrite the functions to match my requirement?**

**Is it the intention Shaka-player for? It represents a customizable JavaScript  player which could be used to demux HTML5's <video> tag in MediaSource Extensions.** 
**If I need to do customization for sure, is Shaka player the correct way instead of iFrame API?**

Thanks~

**Comment by joeyparrish** [comment]
Shaka Player is a generic client for playing adaptive bitrate videos.  We currently support DASH and are working on HLS support.

Shaka Player is not intended for YouTube videos.  If you need to play YouTube videos, you should use [YouTube's iframe player](https://developers.google.com/youtube/iframe_api_reference) instead.

[YouTube's terms of service](https://www.youtube.com/static?template=terms) state:

> You agree not to access Content through any technology or means other than the video playback pages of the Service itself, the Embeddable Player, or other explicitly authorized means YouTube may designate.

I am not a lawyer, but as far as I can tell, playing YouTube content through any third-party player, including ours, is disallowed by the YouTube terms of service.

Shaka Player would be appropriate if you had your own DASH content to serve.  If this is the case, we have [docs](shaka-player-demo.appspot.com/docs/api/index.html) and [tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html) to help you get started, and we are always happy to answer questions.

Thanks!
