### ISSUE TITLE
Xlink support

### ISSUE THREAD

**Issue by mohamednibrahim** [google/shaka-player#587]
Hi,
It seems that the library doesn't support Xlink resolver , I tested using this mpd http://dash.edgesuite.net/fokus/adinsertion-samples/xlink/threeperiods.mpd , I received Error 4004.
Is there are any plans to add xlink support to shaka?

**Comment by joeyparrish** [comment]
Hi @mohamednibrahim,

This is not currently on our roadmap, but we'll consider it when we do our next round of planning.

It may be complicated to support more than one `xlink:actuate` value.  Right now we have a model where manifests are completely parsed and consumed up-front.  Delaying the parsing of a particular Period until right before it's played doesn't fit our current architecture.
