### ISSUE TITLE
help me to protect content with shaka.js 

### ISSUE THREAD

**Issue by cheikhsadbouh** [google/shaka-player#597]
hello ;

i wanna protect my website video and for that i'm using shaka.js , i have done the installation , but i wanna someone to help how can i implements protect content with shaka 
                                                                                                   thnks.

**Comment by joeyparrish** [comment]
Also asked via the mailing list.  Anyone wanting to follow the mailing list discussion can do so here: https://groups.google.com/forum/#!msg/shaka-player-users/cf7QEauVOcQ/guHwdYCwBgAJ

Closing this as a duplicate of the same question on the mailing list.
