### ISSUE TITLE
Differentiate playlist/segment http downloading

### ISSUE THREAD

**Issue by shaharmor** [google/shaka-player#602]
- What version of Shaka Player are you using? latest

When overriding the `httpPlugin`, there is no easy way from within the plugin itself to know if the request is a playlist or a segment request.
It may be required to have different logic based on that info.

The two options are either to pass that info as a parameter to the plugin itself, or have two separate plugins (Which by default will use the same module), and then we will be able to override one or the other.

**Comment by joeyparrish** [comment]
The two parameters to a networking plugin are [`uri` and `request`](http://nightly.shaka-player-demo.appspot.com/docs/api/shaka.net.HttpPlugin.html).  We could easily add [RequestType](http://nightly.shaka-player-demo.appspot.com/docs/api/shaka.net.NetworkingEngine.html#RequestType) to the [Request](http://nightly.shaka-player-demo.appspot.com/docs/api/shakaExtern.html#Request) structure.

Then you could compare `request.type` to `RequestType.SEGMENT` or `RequestType.MANIFEST` in your plugin.  Would that help?

**Comment by shaharmor** [comment]
That would be perfect

**Comment by joeyparrish** [comment]
We're going to pass an additional argument to the plugins instead of adding type to the request structure.
