### ISSUE TITLE
Infinite buffering on CC on startup, regression from 2.0.0 to 2.0.1

### ISSUE THREAD

**Issue by johanhil** [google/shaka-player#603]
- What version of Shaka Player are you using?
2.0.1
  - Can you reproduce the issue with our latest release version?
Yes, when compiled.
  - Can you reproduce the issue with the latest code from `master`?
Yes, but only when compiled.

- Are you using the demo app or your own custom app?
Custom app.
  - If custom app, can you reproduce the issue using our demo app?
No, it seems to have to do with debug turned on / off (it's a timing issue as far as I can tell).

- What did you do?

  - What content did you load?

    - If custom asset, what manifest and license server URIs?
The asset is time senstive, it only exists 48hrs after creation, so please ping me at johan.hilding@gmail.com and I'll give you a manifest.

  - How did you interact with the content, if at all?
N/A

- What did you expect to happen?
The content was supposed to start, like in 2.0.0

- What actually happened?
The content did not start, and when enabling some logging (not all, because then the issue did not occur - see patch
[logging.diff.txt](https://github.com/google/shaka-player/files/605682/logging.diff.txt)) I could tell that it got stuck in some sort of buffering loop.
It doesn't actually buffer more than expected, it's just that when it is done buffering, it doesn't start playing.
So it doesn't properly detect that it's done buffering, I guess. 

I bisected the repo and it seems to me like 4a608ad10c272f36e8f4e57e5ab63e45f82f6e00 is the commit that introduced this regression.

I'm more than happy to help with more info.

**Comment by joeyparrish** [comment]
@johanhil, can you please test something for me?  I have been working on a bug today that may be related.

In lib/media/playhead.js, in the constructor, change `this.startWatchdogTimer_()` to `this.onWatchdogTimer_()`.  I expect this will make the bug more reproducible, even with logging.  Please let me know if this is the case.  If so, I should have a fix out soon.

**Comment by joeyparrish** [comment]
I believe this was fixed by 84fb9d42.  If not, please let me know and we can reopen and investigate.
