### ISSUE TITLE
MSIE 11 fails to play video when hyphen is contained inside manifest Location/BaseUri element

### ISSUE THREAD

**Issue by Ross-cz** [google/shaka-player#608]
Shaka creates incorrect segment url leading usually to 404 errors. This is MSIE 11 known nasty bug that won't be fixed by M$.

When you use:
`new MutationObserver(function() {}).observe(document.body, {childList: true, subtree: true});`
The DOMParser breaks after that. It generates multiple text nodes around each hypen, but Shaka counts only with one inside element.
Related Shaka code:
```javascript
shaka.util.XmlUtils.getContents = function(elem) {
  var contents = elem.firstChild;
  if (!contents || contents.nodeType != Node.TEXT_NODE)
    return null;

  return contents.nodeValue.trim();
};
```
Workaround is to use elem.textContent instead of contents.nodeValue. I'll prepare pull request.

Related MSIE 11 issue source: https://connect.microsoft.com/IE/feedback/details/1398926/ie11-does-not-parse-cdata-containing-hyphens-correctly

**Comment by joeyparrish** [comment]
Marking external since this is a bug in IE11 that we will have to work around.  Looking forward to your PR!
