### ISSUE TITLE
Make shaka 1.6.5 play vtt subs from manifest in Edge

### ISSUE THREAD

**Issue by raskri** [google/shaka-player#609]
- What version of Shaka Player are you using?
1.6.5

  - Can you reproduce the issue with our latest release version?
no
  - Can you reproduce the issue with the latest code from `master`?
no

- Are you using the demo app or your own custom app?
demo/tweak
  - If custom app, can you reproduce the issue using our demo app?
based on http://v1-6-5.shaka-player-demo.appspot.com/ I added playready 
('keySystem': 'com.microsoft.playready') in appUtils.js

- What did you do?
  - What content did you load?
played dash stream with playready and vff subs on Edge
    - If custom asset, what manifest and license server URIs?
NA - restricted access
  - How did you interact with the content, if at all?
clicked on enable subs checkbox in demo UI

- What did you expect to happen?
subtitles are loaded in Edge like in chrome

- What actually happened?
no subs were able to selected as they could not be loaded.

I see in the code:

```
shaka.player.Player.isTypeSupported = function(fullMimeType) {
  var supported;

  if (fullMimeType == 'text/vtt') {
    supported = !!window.VTTCue;
.....
```
For Edge "supported" is false(window.VTTCue is undefined in Edge), can I safely change this to:
```
(!!window.VTTCue||!!window.TextTrackCue)
```
which makes it work in Edge. Or what is the best way to enbale VTT tracks in Edge for shaka 1.6.5? Maybe just run window.VTTCue = true; before loading the player?

Thanks!

**Comment by joeyparrish** [comment]
Good question.  We check for the existence of VTTCue to determine if a browser supports VTT, but clearly that is not enough.

I don't know of an alternative, though.  If you know of another way to detect that Edge supports VTT, I'd be happy to update that support check.  I don't think the existence of TextTrackCue implies VTT support, though.

One solution would be to use Shaka Player v2.  In v2, we support VTT and TTML, and our subtitle support is independent of what the browser supports.  We parse all text tracks in JavaScript now.

**Comment by joeyparrish** [comment]
@raskri, any feedback?  Do you know a way to check for VTT support in Edge?  Or can you upgrade to v2, which supports VTT on all browsers?

**Comment by raskri** [comment]
@joeyparrish, using (!!window.VTTCue||!!window.TextTrackCue) works for my case(for now). 

I'm planning to upgrade to v2, I just need to get the clockSync working for my dash streams.

Thanks
