### ISSUE TITLE
Chromecast is not available when run from packaged app (Cordova)

### ISSUE THREAD

**Issue by dkonovalov** [google/shaka-player#616]
If I use the demo player and pack it in cordova app on android, chromecast becomes unavailable. Technically, Android WebView should be the same as Chrome. I also tried to use crosswalk to wrap the application, with the same result. I understand that this is not something to be implemented by Shaka team, but is it possible to provide some help/guidelines on what should be implemented to allow chromecast functionality in this case?

**Comment by joeyparrish** [comment]
If you look at `lib/cast/cast_sender.js`, you will see how we initialize and determine if Cast is available:

```js
shaka.cast.CastSender.prototype.init = function() {
  // Check for the cast extension.
  if (!window.chrome || !chrome.cast || !chrome.cast.isAvailable) {
    // Not available yet, so wait to be notified if/when it is available.
    window.__onGCastApiAvailable = (function(loaded) {
      if (loaded) {
        this.init();
      }
    }).bind(this);
    return;
  }

  // The API is now available.
  delete window.__onGCastApiAvailable;
  this.apiReady_ = true;
  this.onStatusChanged_();
```

We look for `chrome.cast` and check `chrome.cast.isAvailable`.  If it's not, we register a callback at `__onGCastApiAvailable`, which the cast API will use to notify us if/when Cast becomes available.

Those APIs are only available if we include the cast sender API script in `demo/index.html`:

```html
    <script src="//www.gstatic.com/cv/js/sender/v1/cast_sender.js"></script>
```

Does your app include the cast sender API?

**Comment by dkonovalov** [comment]
Thank you for your answer and the code snippet. Yes, the app includes cast API since I just use demo app which I wrap in an Android WebView. I assume that some sort of cast support is embedded in chrome browser and missing in android webview then.

**Comment by joewoodhouse** [comment]
@dkonovalov Wondering if you ever resolved this? I'm now looking to implement a Cast Sender app in Cordova/Ionic myself. The plugin ecosystem doesn't seem to have moved on much since your last post!

**Comment by dkonovalov** [comment]
Hi @joewoodhouse. I gave up on the idea and implemented native video player with chromecast etc, and then wrapped it into a cordova plugin. Works much better than wrapping Shaka in cordova, also from performance prospective.
