### ISSUE TITLE
undefined "info" object in DashParser

### ISSUE THREAD

**Issue by steve-o** [google/shaka-player#618]
- What version of Shaka Player are you using?

2.0.1-debug and 2.0.0.

  - Can you reproduce the issue with our latest release version?

Yes.

  - Can you reproduce the issue with the latest code from `master`?

Yes.

- Are you using the demo app or your own custom app?

Custom app derived from introduction tutorial, i.e.

http://shaka-player-demo.appspot.com/docs/api/tutorial-basic-usage.html

Hosted here against the appspot hosting:  https://junko.hk/chome/debug.html

- What did you do?

Idea was to use tutorial together with DASH manifest and files from YouTube on a new clean HTTPS server.

  - What content did you load?

Simple 40s clip on YouTube:  https://www.youtube.com/watch?v=94BNgmNYoH8

  - How did you interact with the content, if at all?

n/a

- What did you expect to happen?

Video to load without errors or at least report some form of legible error.

- What actually happened?

Two errors:

1)  Assertion failed: Wrong error type!  player.js:449
2)  Error code undefined object TypeError: Cannot read property 'containsInband' of undefined
    at shaka.dash.DashParser.parsePeriods_ (https://shaka-player-demo.appspot.com/lib/dash/dash_parser.js:658:27)
    at shaka.dash.DashParser.parseManifest_ (https://shaka-player-demo.appspot.com/lib/dash/dash_parser.js:517:33)
    at shaka.dash.DashParser.<anonymous> (https://shaka-player-demo.appspot.com/lib/dash/dash_parser.js:410:21)

**Comment by joeyparrish** [comment]
@steve-o, are you loading a DASH manifest from YouTube?

**Comment by steve-o** [comment]
@joeyparrish I copied the manifest and retargeted each BaseURL to a local copy of each resource.

I presume there maybe something in there off-standard that may break the player, but it does not look too unusual:

https://junko.hk/chome/dash.mpd

**Comment by joeyparrish** [comment]
There's a typo in your manifest:

```xml
<Period,duration
```

That comma should be a space.

**Comment by steve-o** [comment]
Ooh, thank you.  Still looks like a bug in that function though as `var info` is out of scope.

**Comment by joeyparrish** [comment]
Can you be more specific?  I can't reproduce your error in our demo app since your content is not available cross-origin.  If there's a bug, we'd love to fix it.  Please provide repro or submit a pull request.

**Comment by steve-o** [comment]
Working on trying to fix that, there are two lines matching the undefined object:

https://github.com/google/shaka-player/blob/master/lib/dash/dash_parser.js#L659
https://github.com/google/shaka-player/blob/master/lib/dash/dash_parser.js#L665

The only scope for 'var info' is in the 'for' loop on line 613, unless I am missing something?  Is there a globally scoped version?

**Comment by joeyparrish** [comment]
Odd... that does look wrong.  I'm not sure why you get this error and I do not.  Looking at the code, you would expect this error to occur on every manifest.

**Comment by TheModMaker** [comment]
JavaScript has an odd definition of variable scopes, it uses something called [hoisting](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/var#var_hoisting).  The variable is actually "defined" at the beginning of the function.  So at the end of the method it still has the last value stored (from the last Period).  This error only appears when there are no periods and the variable is still set to `undefined`.

**Comment by joeyparrish** [comment]
Logically, `containsInband` should be the "or" of the property from all periods, not the last period parsed.  So the code is subtly wrong, even when it's not causing this `TypeError`.

If there are no periods, we should throw a specific error that says so, instead of dereferencing `null` or `undefined` vars.  So that's another small issue on us.

We will fix both of these issues.

All of that said, when your manifest has valid Periods, your problem goes away.
