### ISSUE TITLE
How change the player's style?

### ISSUE THREAD

**Issue by duanxianze** [google/shaka-player#619]
I want to make the player view more beautiful,what can I do?

**Comment by TheModMaker** [comment]
Shaka Player doesn't do anything with style or UI.  This library only handles the loading and playing of the video segments.  We created a [demo page](http://shaka-player-demo.appspot.com/demo/) that is used to show off our player, but is not itself required to use Shaka Player.  You can follow the [tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html) to start from scratch with your own UI elements.

You are welcome to use your own HTML and CSS code to make your player look however you like with Shaka Player only handing the playing of the videos.  The only thing that Shaka Player does is interact with the `<video>` element by telling it what video content to play.

**Comment by duanxianze** [comment]
Thank you very much!



发自我的小米手机
在 Jacob Trimble <notifications@github.com>，2016年12月13日 上午3:51写道：

Shaka Player doesn't do anything with style or UI. This library only handles the loading and playing of the video segments. We created a demo page<http://shaka-player-demo.appspot.com/demo/> that is used to show off our player, but is not itself required to use Shaka Player. You can follow the tutorials<http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html> to start from scratch with your own UI elements.

You are welcome to use your own HTML and CSS code to make your player look however you like with Shaka Player only handing the playing of the videos. The only thing that Shaka Player does is interact with the <video> element by telling it what video content to play.

**Comment by joeyparrish** [comment]
It seems like this is resolved, so I will go ahead and close it.  If you need any further guidance, please let us know or write to [our mailing list](https://groups.google.com/forum/#!forum/shaka-player-users).
