### ISSUE TITLE
Include app specific data in licenseRequest body.

### ISSUE THREAD

**Issue by sanbornhnewyyz** [google/shaka-player#62]
We're thinking about whether it makes sense to include additional data in the licenseRequest for authentication purposes. Is there a straightforward way to do this at the moment? It looks to me like only the URL and initData can be provided from outside Shaka, but not additional request body attributes separate from custom initData. @joeyparrish do you guys have opinions about this?

**Comment by joeyparrish** [comment]
I was thinking of adding hooks similar to license respond post-processor.  It would be something like a license request pre-processor, to allow you to alter/wrap the request before it is sent to the server.

Would it suffice to modify the request body, or are you looking to control other things as well?  All I can think of is the URL, the body, the request headers, and whether or not to send cookies.

The URL has already been set by the application in DrmSchemeInfo, but is there a need to modify it later with data that wasn't available at the time ContentProtection was interpreted?

**Comment by sanbornhnewyyz** [comment]
No, I think what you have in mind is essentially what I have in mind as well. Specifically the option to add additional data into the request body other than the initData would be great (headers and cookies I anticipate would also be useful), otherwise we would have to add params to the url that we provide to DrmSchemeInfo and that's not ideal.

**Comment by rob-vualto** [comment]
Hi Guys,

My company would like to see this as well. We have extra information we need to send to the license server in the body of the request.

Having a hook similar to the post-processor would be ideal and we would only need to alter the body, the content type of the body (we use json not an array buffer) and the headers. 

In our workflow it would not be necessary to alter the url after the content protection has been interpreted.

**Comment by joeyparrish** [comment]
Okay, then we'll see about providing access to body, headers, and content type.  Thanks for the input!
