### ISSUE TITLE
Re-license mid-stream?

### ISSUE THREAD

**Issue by dakom** [google/shaka-player#624]
Is it possible to re-license mid stream - without user facing any interruption?

For example - say a license expires in 15 minutes, and the client retrieves a new license within 10 minutes, is it possible to continue the playback as though nothing changed?

**Comment by joeyparrish** [comment]
Yes, this is called a license renewal.  Licenses can be renewed without interruption.

Renewal is driven by the CDM and the license itself.  Some licenses specify renewal, and some do not.  If the license specifies renewal on some interval, the CDM periodically sends a 'message' event to the application (in this case, to Shaka Player).  Shaka routes the message to the configured license server, and routes the response back to the CDM.  The expiration time is then extended by the renewal.

Does this answer your question?

**Comment by dakom** [comment]
> Does this answer your question?
And then some! :)

Feel free to close the ticket... though I do have a few followup questions like how I can spin up a licensing server to test this with, and if I can control the frequency of the CDM messaging. Is there a discussion group around this somewhere?

Thanks!

**Comment by joeyparrish** [comment]
Spinning up a license server depends on your DRM provider.

If you want to use Widevine, you can contact Widevine here: http://www.widevine.com/contact.html  Widevine supports renewals and allows you to control both license duration (expiration) and frequency of renewal.

I don't have any information on hand about Microsoft Playready, but their website is here: https://www.microsoft.com/playready/

You can use the [clear key CDM](https://www.w3.org/TR/encrypted-media/#clear-key) for testing and experimentation without depending on any DRM provider, but it appears that clear key does not support renewals or expiration.

Hope that helps!
