### ISSUE TITLE
Setting the preferred language enables the text track visibility. 

### ISSUE THREAD

**Issue by shanmugapriyaEK** [google/shaka-player#626]
- What version of Shaka Player are you using?V2.0.1
  - Can you reproduce the issue with our latest release version?Yes
  - Can you reproduce the issue with the latest code from `master`?Yes
- Are you using the demo app or your own custom app?
  - If custom app, can you reproduce the issue using our demo app?
I could reproduce the issue in both custom and demo application.
- What did you do?
Try playing a multicodec and multilingual content
  - What content did you load?
Angel one
    - If standard demo asset, which one?
Angel one(multicodec and multilingual)
    - If custom asset, what manifest and license server URIs?
  - How did you interact with the content, if at all?
Change the preferred text language. It enables the text track visibility

- What did you expect to happen?
Change the preferred text language should retain the state of the  text T\track visibility

- What actually happened?
It enables the text track visibility by default

Scenario: In our application we had content that has three English audio track with different bit rates. 
As we wanted to provide the user only the audio language access, we then used preferredAudioLanguage

But after using this, we found strange behavior which automatically switches text track. To fix this we determined the current active text track language and set it as preferred language. Now we could see that text track visibility is on when audio switches. 

I could see that https://github.com/google/shaka-player/blob/master/lib/player.js at line number 1512
text track visibility is set to default value( showing) without retaining to the previous value.

**Comment by joeyparrish** [comment]
Thank you for the report.  In a future release, we will only make text track visibility changes when explicitly requested instead of trying to enable it for you based on heuristics.

**Comment by ismena** [comment]
@shanmugapriyaEK we have recently changed the language selection API which seems to have taken care of this issue.
The code is in the latest master. Please feel free to reopen if you are still having problems.
