### ISSUE TITLE
Caching .mpd and streaming file: Shaka Error NETWORK.HTTP_ERROR 

### ISSUE THREAD

**Issue by Pierpaolo1992** [google/shaka-player#641]
Hi everyone, my goal is to setting-up a CDN using nginx container as proxy cache for a streaming service. 
Well, my nginx container is well configured to caching .mpd file, in fact in my browser i can open mpd file (created by shaka-packager) well.

This is example-av.mpd (in .txt for uploading)
[example-av.txt](https://github.com/google/shaka-player/files/680914/example-av.txt)

When i point, in my html page (hosted in backend tomcat, on port 8080) with js code, to the mpd resource (pointed to nginx container, on port 9000):

```
{
    name: 'Sintel 4k (multicodec, Widevine)',
    manifestUri: '//172.17.0.1:9000/example-av.mpd',   // gjslint: disable=110

    encoder: shakaAssets.Encoder.SHAKA_PACKAGER,
    source: shakaAssets.Source.SHAKA,
    drm: [shakaAssets.KeySystem.WIDEVINE],
    features: [
      shakaAssets.Feature.HIGH_DEFINITION,
      shakaAssets.Feature.MP4,
      shakaAssets.Feature.PSSH,
      shakaAssets.Feature.SEGMENT_BASE,
      shakaAssets.Feature.SUBTITLES,
      shakaAssets.Feature.ULTRA_HIGH_DEFINITION,
```

There is cache miss in nginx container, and then it proxy-pass to the backend (a tomcat container, on port 8080):

```
location =  /example-av.mpd {

    proxy_cache my_zone;
    add_header X-Proxy-Cache             $upstream_cache_status;
    proxy_set_header X-Real-IP           $remote_addr;
    proxy_set_header X-Forwarded-For     $remote_addr;

    proxy_set_header Host                $host;

    proxy_pass http://172.17.0.1:8080/shaka-player-master/media/example-av.mpd ;

  }

```
In http://172.17.0.1:8080/shaka-player-master/media there are all the contents created by shaka-packager, so, in this case, audio and video tracks.

There is a 200 OK http response, but content is not reproduced, and Shaka tell me the following error:

Shaka Error NETWORK.HTTP_ERROR (http://172.17.0.1:9000/LynyrdSkynyrdFreebirdAudio.mp4):

![screen](https://cloud.githubusercontent.com/assets/13939351/21590945/3cc06f3e-d100-11e6-8043-d04a272f85c7.png)

This is web.xml configuration file of my tomcat backend container:
[web.txt](https://github.com/google/shaka-player/files/680934/web.txt)

Can anyone help me? I don't know why there is a 405 http response.

[edited] In the js console there is this message:

"crossorigin request blocked (cross-origin): cannot read remote resource http://172.17.0.1:9000/LynyrdSkynyrdFreebirdVideo.mp4. Header CORS “Access-Control-Allow-Origin” missing"

So, when i've read this message, i've updated nginx configuration, adding this, in location= /example-av:

```
location =  /example-av.mpd {

    add_header 'Access-Control-Allow-Origin' '*';
    add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
    add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,Use
r-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Origin';

```

But js console still show me same message.

**Comment by Pierpaolo1992** [comment]
@johanhil i've solved in the following way: in the mpd, in the <URL tag (Lynyrd..mp4) i've wrote 172.17.0.1:9000/Lynyrd...Audio/Video.mp4. In the nginx conf file, i've added two location = /Lynyrd...Audio/Video.mp4 with inside add_header 'Access-Control-Allow-Origin' '*' and Access-Control-Add-Headers 'Range'. And now it works.

**Comment by joeyparrish** [comment]
Sounds like everything is working now, so I'll go ahead and close this issue.  Thanks!
