### ISSUE TITLE
Player hangs in between play

### ISSUE THREAD

**Issue by sridhard** [google/shaka-player#642]
Hi,

I am using the latest shaka player from master. 

I am using the demo player to play the custom content: https://s3-ap-southeast-1.amazonaws.com/learnyst/schools/151/courses/337/paid/7580/online/tst/V2-No-theory-I-prime-verificationwebTrack.mpd

The content will stop playing(Pauses or hangs) at 2:04. If we seek a little using the seekbar then content will start playing again. Similar behaviour we experience for other videos also.

Note: This content was playing successfully with other players.

How to reproduce this issue: Play the content using the demo player. Wait till 2:04. At 2:04 the player hangs. If we seek a little the play will start again

**Comment by sridhard** [comment]
The same issue is observed with the hosted demo shaka player also

**Comment by sridhard** [comment]
@joeyparrish have you got any chance to check this issue. thanks

**Comment by TheModMaker** [comment]
This appears to be bad content.  At time 2:04 there is a frame whose time overlaps another frame.  When you play the video and open `chrome://media-internals` it gives a warning of `Generated splice of overlap duration 4000us into new buffer at 124993333us.`  I also tried this in the Dash IF player and it failed to play also.

This fails to play in Chrome 55 (current stable).  This plays in Chrome 56 and produces a decoder error in Firefox.  You should file a bug with the packager that generated the content.

**Comment by sridhard** [comment]
ok
