### ISSUE TITLE
Is FairPlay DRM supported?

### ISSUE THREAD

**Issue by halibegic** [google/shaka-player#644]
Hello,
I was wondering if FairPlay DRM is supported because on the demo page you can't enter certificate URL.

**Comment by joeyparrish** [comment]
FairPlay is not supported yet.  It's on our roadmap for v2.1 and being tracked in #382.

**Comment by halibegic** [comment]
Ok, thank You.

**Comment by youseframadan933** [comment]
Ok, thank You.
