### ISSUE TITLE
Bug in TTML parsing for div with whitespace

### ISSUE THREAD

**Issue by TobbeEdgeware** [google/shaka-player#646]
- What version of Shaka Player are you using?
Demo v 2.0.2-debug + Latest master (2017-01-05)
  - Can you reproduce the issue with our latest release version?
Yes

  - Can you reproduce the issue with the latest code from `master`?
Yes

- Are you using the demo app or your own custom app?
demo app

We had own content with empty ttml subtitles segment inside mp4 segments.
It contains a a body with an empty div element like

    <body style="s0">
       <div region="r0">
       </div>
     </body>

The demo player shows Shaka Error INVALID_TEXT_CUE.

I've tracked this down to ttml_text_parser and its "Disregard empty elements" which does not allow white-space in an empty div.

I've made a patch and added a unit test for the patch. Will submit them.

**Comment by joeyparrish** [comment]
Thanks!  Looking forward to your PR.
