### ISSUE TITLE
Chrome bug - buffering after seek and pause

### ISSUE THREAD

**Issue by mctep** [google/shaka-player#649]
Hello! 

- What version of Shaka Player are you using?
**2.0.2-debug**
  - Can you reproduce the issue with our latest release version?
**yes**
  - Can you reproduce the issue with the latest code from `master`?
**yes**

- Are you using the demo app or your own custom app?
**demo**

- What browser and OS are you using?
**Chrome/MacOS**

- What did you do?
Ran in console code above:
```js
var video = document.getElementById('video');
video.currentTime -= 2 * 60;
video.pause();
video.play();
```
  - What content did you load?
**Live sim 6s**

- What did you expect to happen?
**That playback has been continued**

- What actually happened?
**Infinity buffering**

It works fine for v2.0.1.

**Comment by theodab** [comment]
This appears to be the result of a chrome bug. The HTMLVideoElement is incorrectly reporting its currentTime after the pause, so Shaka Player loads the wrong segments. I've filed a bug report for it, [https://bugs.chromium.org/p/chromium/issues/detail?id=680256](url).

**Comment by theodab** [comment]
The bug is triggered by pausing directly after seeking backwards into an unbuffered region. For now, you can try to pause before seeking and it should work fine.

**Comment by joeyparrish** [comment]
Fixed in Chrome 56, which is currently in beta.  Stable release of Chrome 56 is estimated for the end of January.

**Comment by joeyparrish** [comment]
Original bug report: https://bugs.chromium.org/p/chromium/issues/detail?id=675556

**Comment by TheModMaker** [comment]
Chrome 56 is now in stable.
