### ISSUE TITLE
Location element in MPD not honored

### ISSUE THREAD

**Issue by TomasBucher** [google/shaka-player#65]
I'm evaluating latest master that already supports live streams and it seems that it is not taking into account Location element present in the manifest. We're using Wowza and requesting the default manifest again to refresh chunk list also creates additional sessions, which then invalidates stream statistics. 

Please see here for further info http://www.wowza.com/forums/content.php?508-How-to-do-MPEG-DASH-streaming#redirects

Thanks,
Tomas

**Comment by joeyparrish** [comment]
We don't support that at the moment, but we will add it to the roadmap.  Thanks for the suggestion!
