### ISSUE TITLE
Chromecast bug - Encrypted HEVC reported as unsupported on Chromecast Ultra, plays anyway if we ask EME for another codec

### ISSUE THREAD

**Issue by jaredmcphillen** [google/shaka-player#651]
- What version of Shaka Player are you using?
v2.0.3
  - Can you reproduce the issue with our latest release version?
yes
  - Can you reproduce the issue with the latest code from `master`?
yes

- Are you using the demo app or your own custom app?
demo app.  at: http://shaka-player-demo.appspot.com/demo/
  - If custom app, can you reproduce the issue using our demo app?

- What browser and OS are you using?
Chrome v.55.0.2883.95 Windows 10

- What did you do?
began casting to my Chromecast Ultra from Shaka player.
Loaded Widevine encrypted DASH content URL and license URL for content.
hit 'play'
I hear the audio play back on Chromecast Ultra, but the video is not showing up.
  - What content did you load?
HEVC encoded video.  Encoded to MAIN10 profile. AAC audio. wrapped in a DASH manifest.

    - If standard demo asset, which one?

    - If custom asset, what manifest and license server URIs?
URL to DASH content:
 http://ec2-54-157-205-121.compute-1.amazonaws.com/test16/JaredTestHDRContent2_v2.mpd

URL to License Server: 
please contact directly to obtain
  - How did you interact with the content, if at all?

- What did you expect to happen?
I expected the PC to not show the HEVC video in the Chrome browser, and for the Chromecast Ultra to use it's HEVC support to play both the HEVC video and AAC audio specified in the DASH manifest.

- What actually happened?
The AAC audio specified in the DASH manifest decrypted and played back successfully, but the Video was never rendered to the screen.

**Comment by joeyparrish** [comment]
It looks like the Chromecast Ultra reports that HEVC is supported for clear content, but not for encrypted.  We filter out unsupported streams, hence audio only.

I will do some testing to find out if it is truly unsupported or if support is being misreported by the platform.

**Comment by joeyparrish** [comment]
It looks like DRM support for HEVC is being misreported.  If you set up DRM as though the content was H264, then set up MediaSource for HEVC and play HEVC content, the content can be decrypted, decoded, and played.

**Comment by jaredmcphillen** [comment]
Ah, sounds sneaky enough : ) .
Do you mind sharing a code snippet of doing just that?

**Comment by jaredmcphillen** [comment]
Ok, I changed the manifest myself.  I changed : 'codecs="hev1.2.4.L123.B90"' to be 'codecs="avc1.640029".'
Oddly enough, the HEVC video showed up on the Chromecast once I did that.  Cool workaround. Thanks!

**Comment by joeyparrish** [comment]
It's not a workaround I would recommend in production, and I can't guarantee it would work on all platforms.  For now, it seems to work for Chromecast.

**Comment by joeyparrish** [comment]
I filed a bug on the Chromecast team here: https://code.google.com/p/google-cast-sdk/issues/detail?id=1084

We will leave this issue open until the platform issue has been fixed.

**Comment by joeyparrish** [comment]
The Chromecast team reports that they have fixed the problem.  It should be released as part of Chromecast firmware v1.23.  I do not know when it will be released, but I would anticipate some time in the next few months.

**Comment by joeyparrish** [comment]
I just enrolled one of my Chromecast devices in the "preview program" and received firmware v1.23.  It does not appear to be out globally yet.

**Comment by johanhil** [comment]
@joeyparrish This has been fixed now, in the 1.23 firmware that was rolled out to Ultra's a few days ago.

**Comment by joeyparrish** [comment]
Thanks!
