### ISSUE TITLE
Cannot create a Shaka Player in Cobalt

### ISSUE THREAD

**Issue by MichaelSweden** [google/shaka-player#6517]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**
Not related.

**What version of Shaka Player are you using?**
v4.8.1

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Own html page.

**If custom app, can you reproduce the issue using our demo app?**
Cannot use your demo app, it's not compatible with Cobalt.

**What browser and OS are you using?**
Cobalt browser (main branch) and Xubuntu.
The problem doesn't appear with Firefox or Chromium

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Not applicable.

**What are the manifest and license server URIs?**
Don't come so far.

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
Default.

**What did you do?**
"var player = new shaka.Player(video)"

**What did you expect to happen?**
Get a shaka player object.

**What actually happened?**
Got an exception: "TypeError: Cannot read property 'toLowerCase' of undefined"

Can be derived to shaka.Player.constructor() -> shaka.util.PlayerConfiguration.createDefault() -> supportsSmoothCodecSwitching() -> isWindows()

I have a fix for it and can create a pull request.

**Comment by avelad** [comment]
@MichaelSweden Please send you PR! I'll review it asap. Thanks!

**Comment by MichaelSweden** [comment]
Yes, navigator.platform doesn't exist in Cobalt browser.
