### ISSUE TITLE
Documentation: Console Output is Out of Date

### ISSUE THREAD

**Issue by jpmedley** [google/shaka-player#653]
[The debugging page](https://github.com/google/shaka-player/blob/master/docs/tutorials/debugging.md) purports to show console output from debugging. What's on the page looks nothing like what's in the console.

**Comment by joeyparrish** [comment]
Hi Joe, can you please be more specific?  What part of that looks wrong to you?

**Comment by jpmedley** [comment]
http_plugin.js:94 HEAD http://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mp 404 ()
(anonymous) @ http_plugin.js:94
shaka.net.HttpPlugin @ http_plugin.js:36
shaka.net.NetworkingEngine.send_ @ networking_engine.js:357
(anonymous) @ networking_engine.js:285
string_utils.js:130 Unable to find byte-order-mark, making an educated guess.
http_plugin.js:69 HTTP error text: 
http_plugin.js:94 HEAD http://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mp 404 ()
(anonymous) @ http_plugin.js:94
shaka.net.HttpPlugin @ http_plugin.js:36
shaka.net.NetworkingEngine.send_ @ networking_engine.js:357
string_utils.js:130 Unable to find byte-order-mark, making an educated guess.
http_plugin.js:69 HTTP error text:

**Comment by jpmedley** [comment]
I also can't seem to get shaka.log.Level to change the output either.

**Comment by joeyparrish** [comment]
When you copy from the JavaScript console and paste into a text editor, you lose all the formatting and it becomes unreadable.  This is why what's in the docs doesn't look exactly like what you pasted.

It looks like there are some updates to make, though.  For example, in the tutorial as it is today, we show examples of debug logs before we get to the part about log levels.

**Comment by joeyparrish** [comment]
I'll also update the part about log levels to be more explicit about where to insert the call to change the level.

**Comment by joeyparrish** [comment]
The tutorial text has been updated.  The updates will appear in the [nightly build](http://nightly.shaka-player-demo.appspot.com/docs/api/tutorial-debugging.html) tomorrow, and will be released in v2.0.4 next week.
