### ISSUE TITLE
Allow for "lost time" in live playback

### ISSUE THREAD

**Issue by baconz** [google/shaka-player#654]
Segments, like time, minds, and keys can get lost. 

We lose segments because of encoder failures, network partitions, and [hand-wavy] buggy software. 

There's been a good bit of discussion about how DASH handles gaps and lossy live playback in the IF, here, and elsewhere, but in the absence of a practical solution, we've taken the following approach:

When there is a gap -- for some definition of gap that is a bit convoluted and irrelevant for this conversation -- in our timeline, we create a new period at the gap boundary. We use the durations of the _available_ segments to calculate the start times (durations) of our periods.

This approach works quite well, except that the live edge slips back by the length of the gap. We *lose* time, and that lost time is not reflected in live edge calculated as `now - presentationStartTime_`, since as it stands `presentationStartTime` is immutable.

The solution to this is quite simple: allow the manifest to adjust the `availabilityStartTime`. This way the manifest generator can adjust AST forward by the length of the gaps that it detects.

I tested this out in our system, and it behaves correctly. I think this patch, would get us most of the way:

```
diff --git a/lib/dash/dash_parser.js b/lib/dash/dash_parser.js
index 17d97a0..f894b4a 100644
--- a/lib/dash/dash_parser.js
+++ b/lib/dash/dash_parser.js
@@ -486,6 +486,7 @@ shaka.dash.DashParser.prototype.parseManifest_ =
   var presentationTimeline;
   if (this.manifest_) {
     presentationTimeline = this.manifest_.presentationTimeline;
+    presentationTimeline.setPresentationStartTime(presentationStartTime);
   } else {
     // DASH IOP v3.0 suggests using a default delay between minBufferTime and
     // timeShiftBufferDepth.  This is literally the range of all feasible
diff --git a/lib/media/presentation_timeline.js b/lib/media/presentation_timeline.js
index cc3cae9..06c8d6b 100644
--- a/lib/media/presentation_timeline.js
+++ b/lib/media/presentation_timeline.js
@@ -97,6 +97,18 @@ shaka.media.PresentationTimeline.prototype.getPresentationStartTime =
   return this.presentationStartTime_;
 };

+/**
+ * Sets the presentation start time, which can be updated in the case of
+ * slippage.
+ *
+ * @param {number} presentationStartTime The new presentation start time
+ * @export
+ */
+shaka.media.PresentationTimeline.prototype.setPresentationStartTime =
+    function(presentationStartTime) {
+  this.presentationStartTime_ = presentationStartTime;
+};
+

 /**
  * Sets the clock offset, which is the the difference between the client's clock
```

If folks agree with this approach, I can clean it up and add some tests.

**Comment by baconz** [comment]
@joeyparrish any thoughts on this?

**Comment by joeyparrish** [comment]
Is it possible to create a simulation of this for integration testing?  Perhaps in the DASH-IF's live sim?

**Comment by baconz** [comment]
I can set up a test stream on our infrastructure, but it won't be super reliable (the only non-DRMed content we have runs off my desk via Chromebit -> VIDIU -> transcoder in our garage). This would probably suffice for demonstration purposes, but not for long term integration testing.

If you have a live RTMP or HLS feed that you have the rights to, we can ingest it through our pipeline and make it available for testing this -- I'll just add some code that drops a few segments every here and there.

**Comment by joeyparrish** [comment]
The simplicity of this solution has a definite appeal, but I'm wary of a solution that is based on changing AST.  This is primarily because we've seen so many broken encoders that vary AST almost nonsensically.

I worry that "standardizing" on this will add to the confusion of DASH implementers in general, in particular when there is no guidance from the DASH IF that this is the recommended approach.

Would your scenario be improved by Shaka Player support for jumping over gaps in the timeline?

**Comment by baconz** [comment]
Your point about "bad" manifests generators unknowingly changing the AST is well taken. What if we put it behind a configuration flag so that users need to explicitly allow the AST to change?

I don't think gap jumping solves this. The problem shows up as a `seekRange()` that includes time at the end that will never be playable. It means that the user could scrub to a region that will always result in buffering.

I think the only other solution is to fill in the lost time with black frames inside of a period, but that seems like more work to implement.

**Comment by TheModMaker** [comment]
I think @joeyparrish's suggestion was that your server introduce gaps in the manifest timeline whenever the content doesn't exist.  So the manifest (and the content) might say there are segments from 0-10, 10-20, 30-40.  With the new design, Shaka Player will jump the 10s gap automatically (based on configs).  Or alternatively introduce a new Period with a `@start` time greater than the end of the previous Period so there is a gap between the Periods.

**Comment by baconz** [comment]
Got it. That would solve this problem!

**Comment by TheModMaker** [comment]
In that case, I'll close this issue.  You can follow gap jumping progress in #180 and #555.
