### ISSUE TITLE
Stuck at end of stream on IE11

### ISSUE THREAD

**Issue by OrenMe** [google/shaka-player#658]
- What version of Shaka Player are you using?
2.0.1, 2.0.2, 2.0.3
  - Can you reproduce the issue with our latest release version?
Yes
  - Can you reproduce the issue with the latest code from `master`?
Yes

- Are you using the demo app or your own custom app?
Demo app
  - If custom app, can you reproduce the issue using our demo app?

- What browser and OS are you using?
IE11 on Win8.1 and Win10

- What did you do?
Start playback and wait till end or seek close to end of stream
  - What content did you load?
Clear dash custom asset and standard
    - If standard demo asset, which one?
Axinom multi and single period
    - If custom asset, what manifest and license server URIs?
[This test MPD](http://qa-nginx-vod.dev.kaltura.com/dash/p/1091/sp/109100/serveFlavor/entryId/0_n916zwym/v/2/flavorId/0_,73pxiyv9,k1j6qxmr,crt7pzof,hsfi74pb,/forceproxy/true/name/a.mp4.urlset/manifest.mpd)

  - How did you interact with the content, if at all?
Playback starts autoplay, wait till end or seek to end (close to end)

- What did you expect to happen?
Playback ends properly, spinner stops spinning

- What actually happened?
Playback stuck on a a second before end with endless spinner

Seems like a regression from 2.0.0 where all links do work.

**Comment by TheModMaker** [comment]
Thanks for the report.  This was a problem with IE/Edge's reporting of buffered ranges.  They were slightly different when at the end of the stream, so we thought we needed more data.  It has been fixed on master.

**Comment by OrenMe** [comment]
Thanks @TheModMaker! will you be tagging v2.0.4 version any time soon?

**Comment by itaykinnrot** [comment]
Thanks!

**Comment by joeyparrish** [comment]
I will plan to roll v2.0.4 next week, and this fix will be easy to cherry-pick to the v2.0.x branch.

**Comment by OrenMe** [comment]
Great, thanks @joeyparrish.
