### ISSUE TITLE
mp4_parser.js in types/text

### ISSUE THREAD

**Issue by rounce** [google/shaka-player#660]
I think +../../lib/util/mp4_parser.js should be located in types/core
example from http://shaka-player-demo.appspot.com/docs/api/tutorial-plugins.html

#python build/build.py +@complete -@polyfill -@text
Compiling the library...
/var/sites/krasview.ru/data/resource/js/shaka-player/lib/dash/dash_parser.js:38: ERROR - required "shaka.util.Mp4Parser" namespace never provided
goog.require('shaka.util.Mp4Parser');
^

/var/sites/krasview.ru/data/resource/js/shaka-player/lib/media/mp4_segment_index_parser.js:25: ERROR - required "shaka.util.Mp4Parser" namespace never provided
goog.require('shaka.util.Mp4Parser');
^

/var/sites/krasview.ru/data/resource/js/shaka-player/lib/util/pssh.js:22: ERROR - required "shaka.util.Mp4Parser" namespace never provided
goog.require('shaka.util.Mp4Parser');
^

3 error(s), 0 warning(s)

**Comment by TheModMaker** [comment]
Thanks for noticing this.  It has been fixed on master.
