### ISSUE TITLE
Error closing session DOMException: The session is not callable

### ISSUE THREAD

**Issue by sanbornhnewyyz** [google/shaka-player#664]
Reproduced using v2.0.3.
I have not tried reproducing with v2.0.4. 

This is reproducible consistently in our app but I have not yet been able to reproduce this in the Shaka sample app.

OSX 10.12, Chrome  55.0.2883.95

This appears to happen when rapidly loading Widevine protected content.

1) Load some WV protected content. Wait for playback to begin.
2) Rapidly load the same content (2-5x)
3) Content is loaded but player stalls and nothing plays. This is unrecoverable.

What appears to be happening is that we can get the player into a state where the `unloadPromise` in `shaka.Player.prototype.load` never resolves and therefore the `load` process never gets initiated. 

I've traced this back to the `drmEngine` not shutting down properly. Occasionally for some reason `activeSession.session.close()` gets rejected with the error: "Error closing session DOMException: The session is not callable". When this happens, `activeSession.session.closed` never resolves and the whole unload chain just hangs.

I made the following change:

```
    activeSession.session.close().catch(Functional.noop);
    goog.asserts.assert(activeSession.session.closed, 'Bad EME implementation');
    return activeSession.session.closed;
```

```
    var p = activeSession.session.close().catch(Functional.noop);
    goog.asserts.assert(activeSession.session.closed, 'Bad EME implementation');
    return p;
```

This seems to solve the issue but it's unclear to me why. I can see that `p` !== `activeSession.session.closed` but I'm not yet familiar with this `activeSession.session.closed` promise or what it is so I'm not sure if it is appropriate to return `p` or not.

I'll try to come up with reliable reproduction steps for the sample app but so far I have not been able to. Something about the specific timing of the `shaka.load()` calls in our app seems to be hitting a sweet spot.

**Comment by TheModMaker** [comment]
I was able to reproduce by modifying the demo app. Using the uncompiled version and making the demo reload inside DrmEngine caused the problem.  Thanks for the report and the solution.

Basically both `session.closed` and `session.close()` both refer to the same event but are different Promise objects.  So in this case they can be used interchangeably.
