### ISSUE TITLE
Whitespace in TTML subtitles is rendered literally although xml:space="default"

### ISSUE THREAD

**Issue by TobbeEdgeware** [google/shaka-player#665]
One of the standard assets for testing subtitles on dash.js is
http://vm2.dashif.org/dash/vod/testpic_2s/xml_subs.mpd

It uses white-space surrounding `<span>` elements in `<p>` elements and this white-space is rendered literally in shaka-player, although it should not, since the xml:space="default" is specified.

The TTML 1.0 spec Section 7.2.3 says that for xml:space="default", white-space should be treated like

   suppress-at-line-break="auto"
   linefeed-treatment="treat-as-space"
   white-space-collapse="true"
   white-space-treatment="ignore-if-surrounding-linefeed"

I made an alternative version of the stream above with suppressed white-space
http://vm2.dashif.org/dash/vod/testpic_2s/xml_subs_no_ws.mpd
which shows how it should look like in Shaka-player.

There are also colors and EBU-TT padding in this example, which dash.js can render, but Shaka-player ignores. That is an acceptable behavior, since no hiccup occurs.

It may be too much work to implement both xml:space="default" and xml:space="preserve", but at least the default mode should be implemented. Currently, the rendering rather follows xml:space="preserve".

I made a small fix for empty subtitles #646 in PR #650, but should have taken a bigger grip to get white space ignored generally as the default.

I may give a shot at a PR, but in that case only for xml:space="default". What is the best way forward?

*Environment*
- What version of Shaka Player are you using?
2.04

  - Can you reproduce the issue with our latest release version?
Yes

  - Can you reproduce the issue with the latest code from `master`?
Yes

- Are you using the demo app or your own custom app?
demo

- What browser and OS are you using?
Chrome on Mac OS Sierra

**Comment by joeyparrish** [comment]
Shaka Player does not render text cues at all.  That is left up to the browser.  So I'm tempted to say that whitespace rendering behavior should be specified as part of the `VTTCue` interface and that Shaka Player should provide the correct setting to the browser.

However, since adding features to the VTTCue spec and waiting for implementation may take a long time, I am open to having Shaka Player's TTML parser handle this in the mean time.

**Comment by TobbeEdgeware** [comment]
I think this is mainly an issue when translating from TTML to WebVTT (VTTCue). WebVTT does not have different white-space modes, and since it is line-based, it is natural to start the text at the beginning of live. It is therefore not likely that the VTTCue API will ever have a white-space API.

I therefore think that your willingness to let this be implemented in the TTML parsing in Shaka Player is the correct choice.

**Comment by ismena** [comment]
@TobbeEdgeware you're very welcome to make a PR if you'd like, otherwise we'll do it when we have a chance.

**Comment by TobbeEdgeware** [comment]
@ismena Sounds good. I let you know, if I start working on it.
