### ISSUE TITLE
Firefox does not support CORS redirects

### ISSUE THREAD

**Issue by Pierpaolo1992** [google/shaka-player#666]
My architecture is composed by a frontend html+js in one container: this container contains all contents in your folder; a nginx container as load balancer (on port 9200); N VM as CDN (on port 9500). 

This is nginx load balancer config file:

```
upstream cdn-audio {
        server 192.168.99.103:9500;
        server 192.168.99.104:9500;
        server 192.168.99.105:9500;
   }

upstream cdn-video {
        server 192.168.99.103:9500;
        server 192.168.99.104:9500;
        server 192.168.99.105:9500;
    }


server {

listen 80;
server_name 172.17.0.1;
access_log /var/log/nginx/acces.log main;

location = /LynyrdSkynyrdFreebirdAudio.mp4 {

             proxy_pass http://cdn-video/LynyrdSkynyrdFreebirdAudio.mp4;
#           proxy_pass http://192.168.99.103:9500;
#           return 301 $scheme://cdn-audio/LynyrdSkynyrdFreebirdAudio.mp4;
            add_header X-Upstream  $upstream_addr;

        }

       location = /LynyrdSkynyrdFreebirdVideo.mp4 {
             proxy_pass http://cdn-video/LynyrdSkynyrdFreebirdVideo.mp4;
#             proxy_pass http://192.168.99.103:9500;
#             return 301 $scheme://cdn-audio/LynyrdSkynyrdFreebirdVideo.mp4;
              add_header X-Upstream  $upstream_addr;
        }

   }
```

When, from my mpd, i point to localhost:9200/LynyrdSkynyrdFreebirdVideo-Audio.mp4, i first have an OPTIONS request, because of cross origins request; this request is correctly managed; then i see, from network console in the browser, some redirect response (i want use load balancer with a redirect approach, redirecting request to localhost:9200/LynyrdSkynyrdFreebirdVideo-Audio.mp4 to one of my upstream server. So the browser, after this redirect response, will contact directly the chosen upstream server without communicating anymore with load balancer. 
Well, what i see in network console in browser is the following;

- some redirect response;

- XMLHttpRequest cannot load http: // localhost:9200/LynyrdSkynyrdFreebirdVideo.mp4. Redirect from 'http: // localhost:9200/LynyrdSkynyrdFreebirdVideo.mp4' to 'http: // cdn-video/LynyrdSkynyrdFreebirdVideo.mp4' has been blocked by CORS policy: Request requires preflight, which is disallowed to follow cross-origin redirect.

- XMLHttpRequest cannot load http: // localhost:9200/LynyrdSkynyrdFreebirdAudio.mp4. Redirect from 'http: // localhost:9200/LynyrdSkynyrdFreebirdAudio.mp4' to 'http: // cdn-audio/LynyrdSkynyrdFreebirdAudio.mp4' has been blocked by CORS policy: Request requires preflight, which is disallowed to follow cross-origin redirect.

Why there is another request that requires preflight?
How could i solve the problem?

**Comment by joeyparrish** [comment]
Looks like you stumbled into one of the darker corners of CORS.  I was unaware of this, but according to this stackoverflow thread, CORS used to disallow redirects.  http://stackoverflow.com/a/39728229

It appears that the spec has changed since then, but that browser implementations have not caught up yet.  

That stackoverflow thread has some suggestions to work around this issue, but ultimately, we will need to push browser vendors to fix their implementations.

What browser are you using?  What others have you tried?

**Comment by Pierpaolo1992** [comment]
I've tried with chrome v.55 and firefox. Reading stackoverflow thread, w3 has updated his standard about CORS in August 2016, but browser vendors require time to implement this new standard.

I resolved this problem using google chrome canary browser.

**Comment by joeyparrish** [comment]
Okay, so to confirm, Chrome Canary (v56) allows redirects cross-origin?

**Comment by joeyparrish** [comment]
I managed to put together a simple repro page for this.  It passes in Chrome 57 and 58, but fails in Chrome 56.

Will test other browsers soon.

**Comment by Pierpaolo1992** [comment]
Yes, redirect after preflight request works with canary (v.58)

**Comment by joeyparrish** [comment]
Complete status of cross-origin redirects with preflight:

|Chrome 56 (stable)|Chrome 57 (dev)|Firefox 51 (stable)|Firefox 52 (beta)|Firefox 53 (aurora)|Edge 14|IE 11|Safari 10 (latest)|
|---|---|---|---|---|---|---|---|
|FAIL|OK|**FAIL**|**FAIL**|**FAIL**|OK|OK|**FAIL**|

Chrome has already fixed it, so you can expect it to be released in Chrome stable in about 6 weeks.  Bugs need to be filed against Firefox and Safari.

**Comment by joeyparrish** [comment]
I filed a bug against Safari here: https://bugs.webkit.org/show_bug.cgi?id=167521

There was already a bug filed against Firefox here: https://bugzilla.mozilla.org/show_bug.cgi?id=1312864

**Comment by Pierpaolo1992** [comment]
Great! I appreciated i've found something new about cors redirect. 
I hope i've give you some help"

**Comment by Pierpaolo1992** [comment]
@joeyparrish cors redirect doesn't working on Firefox Developed Edition, v.53.0a2 (2017-02-1) (64bit).

I've read that you have write [here](https://bugs.webkit.org/show_bug.cgi?id=167521) that it works in "WebKit nightly r211339". Where can i download this webkit from? Thanks!

**Comment by joeyparrish** [comment]
Yes, this bug on Firefox is still open as of today: https://bugzilla.mozilla.org/show_bug.cgi?id=1312864  You can expect that CORS redirect will continue to fail in Firefox until after that bug is closed.

WebKit nightly builds for Mac can be found here: https://webkit.org/nightly/

**Comment by Pierpaolo1992** [comment]
Are WebKit nightly builds available also for Ubuntu? I'd like testing my architecture on a Firefox distro.

**Comment by joeyparrish** [comment]
No, Apple publishes WebKit nightly for OS X only as far as I can tell.  There seems to be a GTK+ port here: https://webkitgtk.org/  I can't really offer any support for you getting/building WebKit on Linux, though.  Good luck!

**Comment by Pierpaolo1992** [comment]
@joeyparrish is there some firefox release that supports this cors-redirect? I.e. nightly?

**Comment by joeyparrish** [comment]
When I checked two weeks ago, the answer was no.  Check the bugzilla link to see if they have fixed it yet.  If not, comment on the bug and let them know it's important to you.

**Comment by joeyparrish** [comment]
The upstream issue is still open, and nobody is looking into it yet.  I pinged the upstream issue to ask for someone to take a look.

**Comment by joeyparrish** [comment]
Firefox just marked their issue "fixed" for Firefox 63, which is currently scheduled for beta on 2018-09-05 and stable on 2018-10-23.  Hope that helps!
