### ISSUE TITLE
Fullscreen polyfill lacks for fullscreenEnabled property

### ISSUE THREAD

**Issue by sgrogov** [google/shaka-player#669]
Is there any reason that `fullscreenEnabled` ignored in `shaka.polyfill.Fullscreen`?
MDN describes it on a par with `requestFullscreen` and other properties, so i guess that support of this property is required. Although `fullscreenEnabled` not used in the shaka library, this may lead to unexpected behaviour.

**Comment by joeyparrish** [comment]
This was an oversight on our part.  It has been fixed in master, and I will cherry-pick it to v2.0.x.  You should see the fix in our upcoming v2.0.6 release.  Thanks!

**Comment by sgrogov** [comment]
Thank you, Joey!
