### ISSUE TITLE
Meaning of System code 13?

### ISSUE THREAD

**Issue by bson** [google/shaka-player#671]
I'm trying to set up a demo with Shaka Player v2.0.0-debug with Widevine CENC enabled using custom content added to demo/asset.js.  git commit b445e46f75d56e3fad2e7653506b535421c83cdc.  No matter what I do I run into "Shaka Error DRM.LICENSE_RESPONSE_REJECTED (Rejected with system code (13))"

The backtrace for the error is:

shakaDemo.onError_ @ main.js:199
shakaDemo.onErrorEvent_ @ main.js:190
shaka.util.FakeEventTarget.dispatchEvent @ fake_event_target.js:118
shaka.cast.CastProxy.playerProxyLocalEvent_ @ cast_proxy.js:529
shaka.util.FakeEventTarget.dispatchEvent @ fake_event_target.js:118
shaka.Player.onError_ @ player.js:2073
(anonymous) @ drm_engine.js:82
(anonymous) @ drm_engine.js:989

If I disable Widevine CENC for both the asset and on the manifest generation side (nginx with the Kaltura VOD packager and on-the-fly AES) it plays fine (in plaintext).  The license proxy is operated by CastLabs, and, well, it works with their DashEverywhere 4.6.6 player.  But we prefer to use Shaka (and Android ExoPlayer on that platform).

It would help tremendously if I knew what system code 13 is...  (Clearly it's not EPERM.)

Running Chrome 56.0.2924.76 (64-bit) on OSX 10.11.4 (15E65).

Built using python build/all.py

**Comment by TheModMaker** [comment]
This is a code given to us by the Chrome CDM, the values are not publicly documented.  This commonly happens when you forget to unwrap a license response or you enter the wrong license server URL and get back a webpage.  I would suggest opening up the DevTools network tab and looking at the license response value.

**Comment by joeyparrish** [comment]
I've seen this system code before with corrupted or malformed responses.  Does the license proxy return a raw license response, or a response that is wrapped in some other format?  If it's wrapped, see this tutorial for examples of unwrapping a response: https://shaka-player-demo.appspot.com/docs/api/tutorial-license-wrapping.html

**Comment by bson** [comment]
Sorry for the delay; haven't had time to investigate in detail.  Indeed, the response is a JSON dict.  I'll investigate and unwrap it - that doc is extremely helpful and I bet this is exactly the problem. *facepalm*

**Comment by nibaboojit** [comment]
{"status":"OK","license":"{base64String}", ......}
decoded license base64String  data return.

**Comment by bson** [comment]
Thanks for the help - it turns out it was indeed wrapped and adding a response filter to unwrap it made playback work.  CastLabs puts it in a key name 'license', so the response filter is specific to their license proxy...

**Comment by jinho-scenappsm** [comment]
I have same error.
Can you please describe in detail hot to response.
If i got the response  like this {"status":"OK","license":"CAIS2AMKKgoQEi+C",....}
Do I have to response only CAIS2AMKKgoQEi+C ?
