### ISSUE TITLE
live+drm - player get stuck while throttling 

### ISSUE THREAD

**Issue by yairans** [google/shaka-player#672]
- What version of Shaka Player are you using? v2.0.5-debug

  - Can you reproduce the issue with our latest release version? yes

- Are you using the demo app or your own custom app? demo app

- What browser and OS are you using? chrome 55/6 on both WIN10 and macOS sierra 10.12

- What did you do?
Load https://shaka-player-demo.appspot.com/demo/?asset=https://klive-a.akamaihd.net/dc-1/live/edash/p/1804331/e/1_1h4m0b66/t/r1LIk_dFcJnVrhH113ndYQ/manifest.mpd;license=https://udrm.kaltura.com/cenc/widevine/license?custom_data=eyJjYV9zeXN0ZW0iOiJPVlAiLCJ1c2VyX3Rva2VuIjoiZGpKOE1UZ3dORE16TVh3cW5ZLUkyQWl5dktxUl9QVkh2RVlmdmUzTERzM2RQaE1VRjNzdG9MT2w1bzFkekNiUFAzUnNDNDFIUVNUQVBBOEtKTXFfNEVRem9IbGFkYlIybktONDVzb2FCM2sxX0MwRFo4YnNKeWNKbFE9PSIsImFjY291bnRfaWQiOiIxODA0MzMxIiwiY29udGVudF9pZCI6IjFfMWg0bTBiNjYiLCJmaWxlcyI6IjFfamJiOGpsOWwsMV8wOG0zOWhreSwxX21yamdpMmxyLDFfYm55eWh1anIifQ%3D%3D&signature=W1Fw0W19%2FTPwJUVxrJ4t6%2BEE5IU%3D;v

  - How did you interact with the content, if at all?  

while playback throttle the bandwidth to Good 3G 1.5Mb/s using chrome DevTools.

- What did you expect to happen?
Smooth playback using the proper bitrate track.

- What actually happened?
1. shaka starts the playback with the top bitrate track (1280*720, ~3M bits/s).
2. I throttle to Good 3G 1.5Mb/s.
3. shaka plays with the top bitrate until the buffer is empty. 
4. the playback stops for 4-5 sec.
5. shaka switches to the second bitrate track (640*360, ~750K bits/s).
6. shaka plays with this bitrate until the buffer is empty. 
7. shaka get stuck for ever, even I disable the throttling.

This is a sporadic issue, sometimes it works ok.

logs attached.

Thanks,
Yair

[shaka-player-demo.appspot.com-1485931765721.txt](https://github.com/google/shaka-player/files/744120/shaka-player-demo.appspot.com-1485931765721.txt)

**Comment by TheModMaker** [comment]
The first delay is a known limitation.  We only adapt after a segment is downloaded.  So if the network drops suddenly, we won't stop the segment from downloading, we will wait until it is finished (which may be 20 seconds).  Then we notice the bandwidth changed and adapt.

The second stall could be a bug, but I don't notice anything from the logs that would indicate why.  The URL you gave doesn't work.  The license server is giving me 403 errors (`error while getting entitlement`).

**Comment by OrenMe** [comment]
@TheModMaker here's a new license for the media: https://udrm.kaltura.com/cenc/widevine/license?custom_data=eyJjYV9zeXN0ZW0iOiJPVlAiLCJ1c2VyX3Rva2VuIjoiZGpKOE1UZ3dORE16TVh4NmdVUHVLS0pVWEpGZk9TNzAxNnRJRVprNDhLU0g3dVJzQkVROWVVS1RRTzIxU3lidDNrc0RxTFRBNG1OR3JQcG1faFFtbDFYblZMWjhvRF9qMjEySGVCSm1Wa1ZLQ1FBSDFvdXNWN3paRWc9PSIsImFjY291bnRfaWQiOiIxODA0MzMxIiwiY29udGVudF9pZCI6IjFfMWg0bTBiNjYiLCJmaWxlcyI6IjFfamJiOGpsOWwsMV8wOG0zOWhreSwxX21yamdpMmxyLDFfYm55eWh1anIifQ%3D%3D&signature=Y%2BOpyr6Jj1tRwr9mquqWf70GzZk%3D&

**Comment by TheModMaker** [comment]
The problem is that the different streams are not aligned.  This means that the segment times of different streams do not have the same times.  So when we adapt and switch to a different stream, we will start appending segments from the new stream starting where we left off.  However, because they are not aligned, there will be a gap that the browser will not jump.  This can be seen by disabling ABR and manually switching tracks (this won't work in the demo app since it clears the buffer when explicitly changing tracks).

We are currently working on adding gap jumping to the Player (see #180 and #555).  However, you should contact your encoder about producing streams with aligned media segments.

**Comment by yairans** [comment]
@TheModMaker 
Thanks a lot

**Comment by TheModMaker** [comment]
Glad to help.  Feel free to reopen if you have any more questions.

**Comment by joeyparrish** [comment]
@yairans, please note that while gap-jumping may help with unaligned Representations, unaligned Representations are not compliant with DASH Interop Points.  Shaka Player does not officially support non-interoperable content.
