### ISSUE TITLE
Electron fails to load the CDM

### ISSUE THREAD

**Issue by dulmandakh** [google/shaka-player#676]
Hello,

I'm developing media player web application using Shaka player, and it works just fine on Chrome/Firefox/Opera. Then tried to convert it to desktop application using Electron, since Electron is based on Chromium and supports Widevine. Bitmovin player detected/plays Widevine encrypted contents on Electron, but Shaka wasn't able to detect Widevine CDM.

- What version of Shaka Player are you using?
2.0.5

  - Can you reproduce the issue with our latest release version?
Yes
  - Can you reproduce the issue with the latest code from `master`?
Yes

- Are you using the demo app or your own custom app?
Shaka demo app and Bitmovin demo (http://bitmovin.com/mpeg-dash-hls-drm-test-player/)

- What browser and OS are you using?
MacOS and Electron (v1.5.0) or Chromium (v54.x)

- What did you do?
Configure Electron to use Widevine CDM (http://electron.atom.io/docs/tutorial/using-widevine-cdm-plugin/), then loaded Shaka demo app and http://bitmovin.com/mpeg-dash-hls-drm-test-player/

- What did you expect to happen?
Both Shaka and Bitmovin detect/support Widevine CDM.

- What actually happened?
Shaka wasn't able to detect Widevine CDM, but Bitmovin detected Widevine CDM support and plays Widevine encrypted content.

**Comment by dulmandakh** [comment]
Dig into Shaka Player source code and found that DRM detection code is in  lib/media/drm_engine.js file. Then copy pasted code from shaka.media.DrmEngine.probeSupport function line by line into Electron console to see where detection fails.

It seems that navigator.requestMediaKeySystemAccess is working just fine, but access.createMediaKeys() is throwing an exception below

> DOMException: Unable to create the CDM for the key system com.widevine.alpha.

I'm wondering how would Bitmovin detecting Widevine CDM.

**Comment by TheModMaker** [comment]
What appears to happen is Electron doesn't fully load the Widevine CDM until you access `navigator.plugins`.  Bitmovin seems to do this which is why it works.  If you enter `navigator.plugins` into the DevTools and reload Shaka Player it works fine.  This is a bug with Electron.

**Comment by joeyparrish** [comment]
Renamed this issue and tagged as external bug.  @dulmandakh, please file a bug against Electron and link to it here.  Thanks!

**Comment by sanbornhilland** [comment]
@dulmandakh This sounds like you are running into this issue here: https://github.com/electron/electron/issues/6516

**Comment by joeyparrish** [comment]
electron/electron#6516 has now been resolved.  Thanks!
