### ISSUE TITLE
getAudioLanguages and getTextLanguages fails when no content loaded

### ISSUE THREAD

**Issue by sanbornhnewyyz** [google/shaka-player#677]
Reproducible on the master branch.

In the Shaka demo app.

1) Load the application
2) Call `shakaDemo.player_.getAudioLanguages()` or `shakaDemo.player_.getTextLanguages()`

Expect: empty array? (At least it shouldn't error out)

Actual: `Uncaught TypeError: Cannot read property 'getCurrentPeriod' of null`

**Comment by joeyparrish** [comment]
Thank you for filing this, and for the PR to fix it!
