### ISSUE TITLE
DRM request failed for Oops multi-DRM video

### ISSUE THREAD

**Issue by yiningc** [google/shaka-player#682]
Fail to play Oops multi-DRM video in YouTube group in shaka-player-demo-site.
The root cause of this issue is that DRM license request failed in playing this specific video. This issue happen on all OS starting 2/2. There is no problem in playing the other DRM videos on shaka player demo site. Can you fix it?
see attached screenshot.
![screenshot 2017-02-02 at 3 42 48 pm](https://cloud.githubusercontent.com/assets/25307173/22605058/2255fb34-ea03-11e6-933f-d699e8c00b13.png)

**Comment by TheModMaker** [comment]
Thanks for noticing this.  It has to do with the recent change to only allow using the demo over https.  That asset uses an embedded URL for the license server that uses http.  This causes problems because the browser rejects mixed content requests.

**Comment by joeyparrish** [comment]
Options:

1. Disable these assets over https
2. Rewrite the license server URIs (in the custom ContentProtection callback) to be https or schemeless
3. Get YouTube to update their asset not to specify a scheme or to specify https

I have contacts at YouTube if option 3 seems like the most sensible.  Not sure how option 1 would work.  Option 2 lets us control our own outcome, so would be most expedient.

**Comment by TheModMaker** [comment]
I just pushed option 2 so the asset is playable now while we wait for YouTube to update their asset.
