### ISSUE TITLE
Casting unexpected stop

### ISSUE THREAD

**Issue by TigerHuang** [google/shaka-player#684]
- What version of Shaka Player are you using?
    2.0.5
- Can you reproduce the issue with our latest release version?
    yes
- Can you reproduce the issue with the latest code from `master`?
    yes
- Are you using the demo app or your own custom app?
    yes
- If custom app, can you reproduce the issue using our demo app?
    yes
- What browser and OS are you using?
    Mac OS 10.12.3 Chrome 55.0.2883.95 (64-bit)
- What did you do?
  - What content did you load?
    - If standard demo asset, which one?
       Cast demo asset: Live sim (2s segments) to my Chromecast ultra about 5 mins.
- How did you interact with the content, if at all?
    nothing.
- What did you expect to happen?
    keep casting.
- What actually happened?
   casting stopped. Console Log display "No Period ID given for Period with start time 0,  Assigning a default"

**Comment by TigerHuang** [comment]
console debug logs
<img width="1426" alt="screenshot 2017-02-08 00 31 24" src="https://cloud.githubusercontent.com/assets/1662405/22700574/1b664612-ed96-11e6-9e8d-960b95bfc749.png">

**Comment by joeyparrish** [comment]
@TheModMaker, can you try to reproduce?

**Comment by TigerHuang** [comment]
I just try the last commit 56f6ef43940a8756e3d77d7fa564cad055dcd1a7 this bug still exist

**Comment by TheModMaker** [comment]
This was a problem with the demo receiver app that runs on the Chromecast.  I did a push to the nightly site so it should be working there.  We will cherry-pick this to the v2.0.x branch and it will appear in the next bugfix release.

<https://nightly-dot-shaka-player-demo.appspot.com/demo/>
