### ISSUE TITLE
Abstract DBEngine

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#688]
To better support alternate storage mechanisms, we should abstract shaka.offline.DBEngine into an interface called shaka.offline.IStorageEngine.  DBEngine will implement this interface, and this will allow the addition of implementations that do not use IndexedDB.

FYI @paullewis

**Comment by TheModMaker** [comment]
This was implemented in 3db0f33.  This isn't intended to be used as a plugin and the API is not guaranteed to be stable.
