### ISSUE TITLE
change audio track force clear of video buffer

### ISSUE THREAD

**Issue by rounce** [google/shaka-player#693]
When I change audio track via selectVariantTrack(track, true) shaka player clear audio AND video buffer

audio:
    at shaka.media.StreamingEngine.clearBuffer_ (shaka-player/lib/media/streaming_engine.js:1762:5)
    at shaka.media.StreamingEngine.switch (shaka-player/lib/media/streaming_engine.js:530:12)
    at shaka.Player.deferredSwitch_ (js/shaka-player/lib/player.js:1714:35)
    at shaka.Player.selectVariantTrack (js/shaka-player/lib/player.js:1125:8)

then video:
    at shaka.media.StreamingEngine.clearBuffer_ (streaming_engine.js:1762)
    at shaka.media.StreamingEngine.seeked (streaming_engine.js:604)
    at shaka.Player.onSeek_ (player.js:1891)
    at shaka.media.Playhead.onSeeking_ (playhead.js:514)

**Comment by TheModMaker** [comment]
A variant track represents a pair of both audio and video.  So when you switch to a different variant, you are changing both audio and video streams, so we clear both buffers.  In v2.1 (latest `master`), you can no longer select individual audio and video tracks, you can only select an audio/video pair.

**Comment by rounce** [comment]
Why remove useful functionality? I'm sure in many cases it's necessary for independent change of tracks. In my case it remains to make a fork or to use the previous version forever.

**Comment by ismena** [comment]
@rounce we had to introduce this change in order to be able to add support for HLS (the way HLS manifest is structured there is no way for us to know certain information about individual streams that is needed to operate on a stream level).
For DASH manifests we are creating variants for all possible audio+video combinations, so if you want to keep current video track, but change the audio you should be able to find the right variant track.

Sorry that this change complicated things for you. If you have a specific use case you're worried about, we'd be happy to advise on how to best accommodate it with v2.1 streaming logic if you do decide to upgrade.

**Comment by TheModMaker** [comment]
In HLS, we are only given audio/video pairs and those are what we can switch between.  So if you wanted to switch to a different audio stream, it might not be compatible with the current video stream.  This would mean that we would either have to throw an error for the change, ignore the change, or also switch video.  These are not good user experiences, so we only allow changing by variants directly.

If all you want to do is change the audio language, there is a new API to do that.  `player.selectAudioLanguage` will change the selected audio language and switch tracks for you.  This will change the current audio track, trying to keep the video track the same.

**Comment by rounce** [comment]
selectAudioLanguage might be useful in some cases. But often I have several different audio tracks of one languarge. Thanks. I will make fork.

**Comment by joeyparrish** [comment]
@rounce, you make a good point.  It would seem at a glance that there's no reason you would have to clear audio when switching to a variant with the same audio stream.  However, there are often strange implementation quirks in MSE on various browsers.  We may be doing this to work around a browser bug.

We will re-evaluate.

**Comment by joeyparrish** [comment]
I can't find any reason we should be clearing the audio as well as video when the audio component of a variant is staying the same.  This seems like a thing we could optimize.

**Comment by ismena** [comment]
Okay, this is done. If the old and the new variants have the same video or audio stream, only the buffer of the type that changed will be cleared.
