### ISSUE TITLE
Allow users to cancel downloads

### ISSUE THREAD

**Issue by paullewis** [google/shaka-player#696]
I'm using `offline.store()` for some fairly sizeable videos, and there's times a user may wish to cancel the download. AFAICT there's no way to directly get access to the download manager (or the download process) once `.store()` is called. Is that correct?

**Comment by TheModMaker** [comment]
You can cancel a `store()` by calling `storage.destroy()`.  This will cancel the store and delete any partially-downloaded content.  `destroy()` also returns a Promise that will resolve once the the abort is done and the object is destroyed.

Unfortunately, you cannot use this instance after calling `destroy()`.  You will need to create a new instance to do another store.
