### ISSUE TITLE
ChromeCast questions

### ISSUE THREAD

**Issue by jorgitoml** [google/shaka-player#701]
We are using Shakaplayer v2.0.5 on our web-app and we need to pass the "Google Cast Test Cases".

-Is there any way to show the volume-bar and the progress-bar in the "cast dialog" (cast minicontroller)?
-Is there any interface to show the "cast introduction overlay"?

Regards.

**Comment by TheModMaker** [comment]
Shaka Player doesn't do any UI work.  It is up to the app to show things like volume-bar.  You can just add this to your receiver app html page.

Our demo page includes an example receiver app that shows an "introduction overlay" and the progress-bar.  It doesn't show the volume-bar, but that could be easily added.

**Comment by jorgitoml** [comment]
Hi! 
Thanks for your reply,  but I'm talking about the sender side.

This dialog: 
![sender-control-end1](https://cloud.githubusercontent.com/assets/1795137/23046898/a5879a0e-f4ac-11e6-84f0-cd211d1276ca.jpg)

And this overlay:
![promting1_a](https://cloud.githubusercontent.com/assets/1795137/23046913/c0e1c860-f4ac-11e6-962a-f40b427d92d1.jpg)

We don't know how to show the volume bar and the progress bar on the dialog...and we don't know what's the best way to detect the very first time that the user can cast using our web to show the overlay (using cookies may be? or if it is an API like in android)

Best regards.

**Comment by TheModMaker** [comment]
The top dialog is from the Chrome extension.  The interface for that changed in the last few months.  We have no control over that.  Volume is primarily controlled on the cast side (e.g. on the TV), but Shaka Player also proxies volume over the app.  So if you adjust the volume bar in our demo app (on the sender side) it will change the Chromecast volume.

The overlay in the bottom screenshot is likely created by that app.  They probably did this with a static image or with some CSS.  One way to detect the first time someone visits your app is to use [local storage](https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API).

**Comment by jorgitoml** [comment]
Thanks a lot.
I've noticed that the requeriments have changed at January 31 and the dialog bars are not required anymore.
https://developers.google.com/cast/docs/design_checklist/sender

Best regards.
