### ISSUE TITLE
How to create my contents list?

### ISSUE THREAD

**Issue by Pierpaolo1992** [google/shaka-player#704]
Hi, i'm studying that awesome library, for realizing a performance analysys of DASH in the context of on-demand streaming.
I know how to create shaka-enable contents (using shaka-packager).
Now, i want to replicate your index.html page for showing, in the Asset line, a list of all my contents... and then linking them, using assect_section.js and asset.js, to my (local) mpd file.

I'm using shaka-uncompiled mode, so for generating your (demo) list i have to execute gendeps.py ... but how can i modify that list?

My contents are encrypted using this command: 
```

(packager input=sintel.mp4,stream=video,output=encrypted_sintel.mp4 \
--enable_widevine_encryption \
--key_server_url "https://license.uat.widevine.com/cenc/getcontentkey/widevine_test" \
--content_id "3031323334353637" \
--signer "widevine_test" \
--aes_signing_key "1ae8ccd0e7985cc0b6203a55855a1034afc252980e970ca90e5202689f947ab9" \
--aes_signing_iv "d58ce954203b7c9a9a9d467f59839249" \
--mpd_output encrypted_sintel.mpd)
```

My goal is to have, for example, a list of "asset" (i.e. modifying names of your "demo" asset list) that points, via asset_section.js and asset.js, to my local mpd).

I don't know where starting from. I'd like if you show me, if it's possibile, the easiest way to watch a content generated by me, starting from .mpd and CDM widevine, starting from "html button clicked". Thanks in advance.
I hope i was clear, and thanks for your effort.

**Comment by Pierpaolo1992** [comment]
I've saw [here](https://github.com/google/shaka-player) (in uncompiled mode section) and [here](http://v1-6-2.shaka-player-demo.appspot.com/docs/tutorial-player.html): this is my code:
```

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>TurtleTube - Basic Test</title>
    <!-- Load the Shaka Player library. -->
  <script src="third_party/closure/goog/base.js"></script>
  <script src="dist/deps.js"></script>
  <script src="shaka-player.uncompiled.js"></script>
  </head>
  <body>
    <video id="video"
           width="640" height="480"
           crossorigin="anonymous"
           controls>
      Your browser does not support HTML5 video.
    </video>
  </body>
  <script>
    function initPlayer() {
      // Install polyfills.
      shaka.polyfill.installAll();

      // Find the video element.
      var video = document.getElementById('video');

      // Construct a Player to wrap around it.
      var player = new shaka.player.Player(video);

      // Attach the player to the window so that it can be easily debugged.
      window.player = player;

      // Listen for errors from the Player.
      player.addEventListener('error', function(event) {
        console.error(event);
      });

      // Construct a DashVideoSource to represent the DASH manifest.
      var mpdUrl = 'https://turtle-tube.appspot.com/t/t2/dash.mpd';
      var estimator = new shaka.util.EWMABandwidthEstimator();
      var source = new shaka.player.DashVideoSource(mpdUrl, null, estimator);

      // Load the source into the Player.
      player.load(source);
    }
    document.addEventListener('DOMContentLoaded', initPlayer);
  </script>
</html>
```

I was expecting that i can see content, but in the network console there is the following error:

```
Uncaught TypeError: Cannot read property 'Player' of undefined
    at HTMLDocument.initPlayer 
``` 

]related to  var player = new shaka.player.Player(video);

**Comment by TheModMaker** [comment]
That tutorial is from a really old version of the player.  The latest is v2.0.5 which has an updated api.  You can follow the latest tutorial:

<https://shaka-player-demo.appspot.com/docs/api/tutorial-basic-usage.html>

**Comment by Pierpaolo1992** [comment]
Thanks, but in that tutorial i don't see example in the context of DRM

**Comment by TheModMaker** [comment]
There are more tutorials on the right side of the page.

<https://shaka-player-demo.appspot.com/docs/api/tutorial-drm-config.html>

**Comment by Pierpaolo1992** [comment]
Perfect. Really thank you!

**Comment by TheModMaker** [comment]
Great, if you have any other questions, be sure to ask.

**Comment by filipepeixinho** [comment]
Pierpaolo1992, have you manage to play your video without supplying the key server url to shaka player like the code you show on top of this discussion?

I also have a dash manifest with LA URL/key server url inside but is there any way to make shaka read this information from manifest instead of me providing it with configure function? Does anyone can show me a sample code if what I need is possible?
I will be much appreciated.

**Comment by ismena** [comment]
Hi @filipepeixinho,
To the best of my knowledge having licence server uri on the manifest isn't compliant with the DASH spec, so your content must be somewhat unconventional. As I mentioned in the email exchange we had on this, we might be able to help you better if you provide an example of the server uri on the manifest.

In the meantime, I think your best bet would be to modify the dash_parser.js for your project to read uri and store it as part of the manifest object. You then could add a call to configure somewhere around this line: https://github.com/google/shaka-player/blob/master/lib/player.js#L530

```
  player.configure({
    drm: {
      servers: { 'com.widevine.alpha': manifest.licenseServerUri }
    }
  });
```
