### ISSUE TITLE
Uncaught TypeError: Cannot set property 'src' of null

### ISSUE THREAD

**Issue by BiasF** [google/shaka-player#708]
- What version of Shaka Player are you using?
Latest

  - Can you reproduce the issue with our latest release version?
yes

  - Can you reproduce the issue with the latest code from `master`?
yes

- Are you using the demo app or your own custom app?
own custom app, installed like descriped in tutorial

  - If custom app, can you reproduce the issue using our demo app?
no

- What browser and OS are you using?
Chrome + Firefox on Windows 10 x64

- What did you do?
trying to debug my MPEG-DASH Stream via using uncompiled shaka-player

  - What content did you load?
demo content from google and own DASH Stream

- What did you expect to happen?

- What actually happened?

I'll get the following error message, if I use the uncompiled version of shaka-player
`IndexedDB.install
mediakeys.js:43 MediaKeys.install
mediakeys.js:52 Using native EME as-is.
mediasource.js:35 MediaSource.install
mediasource.js:49 Using native MSE as-is.
promise.js:118 Using native Promises.
vttcue.js:36 Using native VTTCue.
player.js:632 Uncaught TypeError: Cannot set property 'src' of null
    at shaka.Player.createMediaSource (player.js:632)
    at shaka.Player.initialize_ (player.js:1408)
    at new shaka.Player (player.js:169)
    at initPlayer (myapp.js:28)
    at HTMLDocument.initApp (myapp.js:17)
shaka.Player.createMediaSource @ player.js:632
shaka.Player.initialize_ @ player.js:1408
shaka.Player @ player.js:169
initPlayer @ myapp.js:28
initApp @ myapp.js:17`

myapp.js and the HTML file are from the shaka-player tutorial, the compiled version is working as expected.

**Comment by BiasF** [comment]
sorry my mistake, found Typo in my html file ...

**Comment by ismena** [comment]
No worries, do reach out of you have questions in the future!
