### ISSUE TITLE
better support multi-DRM with one ContentProtection element

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#71]
Currently, shaka.player.DashVideoSource.ContentProtectionCallback only allows the creation of one DrmSchemeInfo object per ContentProtection element.  So although it is possible for a provider to support multiple DRM schemes, the must then use multiple ContentProtection elements as well.

Since ContentProtection can make use of application-specific extensions, there is no reason one ContentProtection element cannot describe, in an app-specific way, multiple DRM schemes.  A future refactor of ContentProtection interpretation should take this into account and provide a natural API for generating multiple DrmSchemeInfos.

**Comment by joeyparrish** [comment]
This could even be needed without app-specific extensions to ContentProtection.  For example:

<ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc"/>

For some apps, this should be enough to supply a list of DrmSchemeInfos with license server endpoints for all the various DRM schemes that content provider uses.

**Comment by kelvinoliveira** [comment]
> Added support for multiple DRM schemes per ContentProtection and simplified DRM scheme configuration.    #71

Could not find shaka.player.DrmInfo class on version 1.5.0 as stated in https://shaka-player-demo.appspot.com/docs/shaka.player.DashVideoSource.html#ContentProtectionCallback

**Comment by tdrews** [comment]
The library does not export `shaka.player.DrmInfo`. Your application should return an array of objects like `shaka.player.DrmInfo.Config` from your `interpretContentProtectionCallback`. For example,
``` javascript
return [{
    'keySystem': 'com.widevine.alpha',
    'licenseServerUrl': LICENSE_SERVER_URL,
    'withCredentials': true
  }];
```

**Comment by kelvinoliveira** [comment]
Thank you, It's is working now.
