### ISSUE TITLE
The player doesn't perform the 'playing' event for second time

### ISSUE THREAD

**Issue by vinnichenko** [google/shaka-player#711]
- What version of Shaka Player are you using? 
_v. 2.0.5_

  - Can you reproduce the issue with our latest release version?
 _I'm using the latest one_

  - Can you reproduce the issue with the latest code from `master`? 
_yes_

- Are you using the demo app or your own custom app? 
_my custom app_

  - If custom app, can you reproduce the issue using our demo app? 
_it's almost impossible_

- What browser and OS are you using?
 _Chrome, Windows 10_

- What did you do? 
_I've opened one video content couple of times, each second time it doesn't start, No errors in the console._

  - What content did you load?

    - If standard demo asset, which one?

    - If custom asset, what manifest and license server URIs? 
_They are different each time. I get them from my backend_

  - How did you interact with the content, if at all? 
_I opened it, made sure that it's playing, sought it forward, then closed the player. After that I opened the player again, but the playback didn't start. Then I closed the player, reopened it and the playback started. I was debugging that process and each second time I saw that I have no 'playing' event returned from the player._

- What did you expect to happen? 
_The playback should start every time_

- What actually happened? 
_The playback starts each odd time_

**Comment by joeyparrish** [comment]
@vinnichenko, can you provide us with any way to reproduce the problem?  It will be very difficult to diagnose if we can't reproduce it.
