### ISSUE TITLE
Custom HTTP response header from license response

### ISSUE THREAD

**Issue by thwlaw** [google/shaka-player#712]
Our Widevine license proxy service needs to return some values to the client app (Shaka Player).
We decided to use a custom HTTP header in the license response message.

I try to use a response filter in the NetworkingEngine to get the custom header field, 
however, Shaka Player does not return the custom header field in the response object.

Does the Shaka Player supports this usage?  Is there an example app for this usage?

**Comment by joeyparrish** [comment]
This sounds like a CORS issue.  Cross-origin, your license server must explicitly expose the header, as well.  Otherwise, the browser will not allow the JavaScript application to see it.

See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers

Does this help?

**Comment by thwlaw** [comment]
Yes, exactly as you said.

Also, the header name is changed to all lower case.

**Comment by joeyparrish** [comment]
Glad to hear it!  Since it sounds like everything's resolved, I'll go ahead and close the issue.
