### ISSUE TITLE
Wrong order of video segments in live streaming

### ISSUE THREAD

**Issue by vinnichenko** [google/shaka-player#714]
- What version of Shaka Player are you using?
_2.0.5_

  - Can you reproduce the issue with our latest release version?
_Yes_

  - Can you reproduce the issue with the latest code from `master`?
_Yes_

- Are you using the demo app or your own custom app?
_own app_

  - If custom app, can you reproduce the issue using our demo app?
_unfortunately no_

- What browser and OS are you using?
_Chrome, Windows 10_

- What did you do?
I started the playback of live content, the player showed the start frame, then it stopped when tried to download the wrong segment.

  - What content did you load?
_live content_

    - If standard demo asset, which one?

    - If custom asset, what manifest and license server URIs?
_They are always different_

  - How did you interact with the content, if at all?
_I didn't interact_

- What did you expect to happen?
_Each segment of video should has incremented index._

- What actually happened?
Sometimes (almost every time) the player tries to download a wrong segment. Look to the attachment. The wrong segment has a wrong index (not incremented)
![94b5e7b19f874f89a28575535b981ec7](https://cloud.githubusercontent.com/assets/4907669/23460831/e65abfc4-fe8f-11e6-973a-080301b1f0f0.png)

**Comment by TheModMaker** [comment]
Can you please provide a manifest that reproduces this error.  You can send it to be privately if you want (my email is in [CONTRIBUTORS](https://github.com/google/shaka-player/blob/master/CONTRIBUTORS) or on my profile).  Without a way to reproduce it, it will be very hard to track down why this happened.
