### ISSUE TITLE
Replacement for useSafariBehaviorForLive

### ISSUE THREAD

**Issue by roberto-sartori-gl** [google/shaka-player#7155]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**

Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

Yes

**If the question is related to FairPlay, have you read the tutorial?**

**What version of Shaka Player are you using?**

4.10.9

**What browser and OS are you using?**
Chrome on Windows.

**Please ask your question**

So, I've been using useSafariBehaviorForLive to be able to use the full "availability window". See here for details:
https://github.com/shaka-project/shaka-player/issues/6521#issuecomment-2089448099

However, this configuration is now deprecated:
https://github.com/shaka-project/shaka-player/commit/aaeafa451c98c0afc6bb5c7bdc7a54319b7402c5

On 4.10.9 it still works but I'm trying to find a solution before it eventually stops working.
I tried to configure 'streaming.liveSync.enabled' but it doesn't make the full window available.

Is there any other solution?

From the thread linked above it seems I could set 'manifest.availabilityWindowOverride', however this is not ideal because the availability window may vary whenever the manifest is updated or it may depend on the specific video.

**Comment by joeyparrish** [comment]
From your linked comment, you're setting it to `false`, and the new behavior is the same as this.  So you shouldn't need to do anything AFAICT.  Did I misunderstand?

**Comment by avelad** [comment]
I don't see any problem with this, the new version remove useSafariBehaviorForLive and the default is equal to useSafariBehaviorForLive = false. With the default behaviour you should have access to the full availability window. I checked the behaviour in the main branch and works as expected with your stream.
