### ISSUE TITLE
How to discover which player instance is making the network request?

### ISSUE THREAD

**Issue by silverbucket** [google/shaka-player#718]
I'm wondering if there's a supported method for getting information about which player instance has made a request, when the registered scheme is called. For example:

```javascript
shaka.net.NetworkingEngine.registerScheme("http", customFetch);
shaka.net.NetworkingEngine.registerScheme("https", customFetch);

var player1 = shaka.Player(video);
var player2 = shaka.Player(video2);

function customFetch(uri, options) {
  if (...player1...) {
    ...
  } else {
    ... 
  }
}
```

Since the registerScheme calls happen outside of any player instance, it does not seem possible to create a separate `customFetch` function for each of the players that are instantiated. Meaning the `customFetch` function has no way of operating with the assumption that it is handling requests only for one player instance and neither does it have any obvious way of determining which player instance the request it receives is for.

**Comment by TheModMaker** [comment]
I'm curious about why it would depend on the Player instance.  Can you describe your use case more?  Usually a scheme plugin would be independent to the Player.  For example, network requests don't depend on the Player.  Does this have to do with bandwidth estimation?

Request/response filters are applied per-Player (actually per-NetworkingEngine).  Could you do this using a filter?

**Comment by silverbucket** [comment]
For example. If we have pre-fetching logic built-in, based on the playlist, there could be some overhead in determining which instance made the request. There could be two instances of a player on a page, with the same playlist, which has seek'd to two different positions. There could be an issue of what adds exist in a playlist and improperly identifying them as belonging to the wrong playlist (if there is more than one playlist that has the add URIs in them).

**Comment by silverbucket** [comment]
@TheModMaker could you point me to some more information on request/response filters and how that might be a solution? I couldn't find anything in the docs, but maybe I'm not looking for the right thing?

**Comment by silverbucket** [comment]
For future reference, I was able to determine the player that the request came from by adding a filter (while in the scope of the player instance) and attaching a custom header to the request which contains a ID value also attached to the player instance. Then creating a Singleton class which manages the registered players and routes to the correct players network request function based on the custom header of the incoming request.
