### ISSUE TITLE
Live streaming not working on some devices (Custom app & Basic Usage implementation)

### ISSUE THREAD

**Issue by timpalander** [google/shaka-player#719]
- What version of Shaka Player are you using?
2.0.6

  - Can you reproduce the issue with our latest release version?
  [Demo page](http://labs.solidtango.com/shaka-demo/)

  - Can you reproduce the issue with the latest code from `master`?
  Yes

- Are you using the demo app or your own custom app?
Custom app as well as "[Basic Usage](https://shaka-player-demo.appspot.com/docs/api/tutorial-basic-usage.html)"-implementation.

  - If custom app, can you reproduce the issue using our demo app?
  No, it seems to work in the demo app.

- What browser and OS are you using?
Android Nexus 9 / 6.0 - Chrome Mobile 55
Android Galaxy Tab 2 / 4.1 - Chrome Mobile 56
Android Galaxy Tab 2 / 4.1 - Firefox Mobile 51
via [crossbrowsertesting.com](https://crossbrowsertesting.com/)

- What did you do?
Attempt to play live content.

  - What content did you load?
 A livestream

    - If custom asset, what manifest and license server URIs?
    https://57ebfb8668c72.streamlock.net/edge/_451iw2h_/451iw2h/manifest.mpd

- What did you expect to happen?
Livestream to play.

- What actually happened?
Livestream is stuck on "waiting" and never plays.

I first discovered this in our custom player environment. After being unable to find a solution i created a [demo page](http://labs.solidtango.com/shaka-demo/) that implements the player according to your [Basic Usage](https://shaka-player-demo.appspot.com/docs/api/tutorial-basic-usage.html) and the issue can be reproduced there. It does however work in your [demo player](https://shaka-player-demo.appspot.com/demo/).

**Comment by joeyparrish** [comment]
Your demo page works for me, so I have a theory about what is going on.

Neither your demo page nor the Basic Usage tutorial configure clock sync.  Our demo app has a clock sync config to work with live streams that don't have their own clock sync elements (`<UTCTiming>`) in the manifest.  The reason your demo page works for me is that my desktop computer's clock happens to be accurate.

Many clients have inaccurate clocks, and clock sync allows Shaka Player to adjust the client's clock to match the server.  This synchronization is critical for live streaming.

If the manifest does not contain any clock sync info (`<UTCTiming>` elements), your application must provide a fallback.  Here's an example:

```js
player.configure({
  manifest: {
    dash: {
      clockSyncUri: '//foo.bar/clock.sync.txt'
    }
  }
});
```

The player will made a `HEAD` request to the clock sync URI and read the `Date` header.  It can be any URI you control.  It will use that as the official current time, and make adjustments to the client's clock any time it needs to perform time calculations for the live stream.

For this to work cross-origin, you must both allow access and expose the `Date` header to the client.  For more information on cross-origin headers, see this MDN article: https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

Pay particular attention to `Access-Control-Allow-Methods` (for preflight), `Access-Control-Allow-Origin` (for both preflight and the `HEAD` request), and `Access-Control-Expose-Headers` (for the `HEAD` request).

Does this help?

**Comment by timpalander** [comment]
I forgot to clarify that it does work on my computer as well. It's only on the specified devices it doesn't work. The problem could however be what you describe so i will give that a try. Thank you!

**Comment by timpalander** [comment]
Problem solved. I updated to Wowza 4.6.0.03 so i could enabled UTCTiming in the manifest. Everything is now working as expected. Thanks a bunch!

**Comment by joeyparrish** [comment]
Happy to help.  Let us know if you need anything else.
