### ISSUE TITLE
Video play will pause when availabilityStartTime is changed for live stream

### ISSUE THREAD

**Issue by KingjZhang** [google/shaka-player#720]
- What version of Shaka Player are you using?
2.0.6
  - Can you reproduce the issue with our latest release version?
Yes

  - Can you reproduce the issue with the latest code from `master`?
Yes

- Are you using the demo app or your own custom app?
I am using the Demo app and custom app.
  - If custom app, can you reproduce the issue using our demo app?
Yes

- What browser and OS are you using?
Chrome, Windows 10

- What did you do?
I using the Wowza as the live stream server.
When the source stream is dead and active again. The Wowza will changed the availabilityStartTime in .mpd file.
Example:
     availabilityStartTime="2017-03-09T17:05:12Z" 
to:
     availabilityStartTime="2017-03-09T17:08:32Z" 

  - What content did you load?

    - If standard demo asset, which one?

    - If custom asset, what manifest and license server URIs?

  - How did you interact with the content, if at all?

- What did you expect to happen?
The Shaka will always pause when the availabilityStartTime is changed. Can you set auto play again?

- What actually happened?

**Comment by TheModMaker** [comment]
This seems like a bug on Wowza.  Changing the `availabilityStartTime` is not valid.  `availabilityStartTime` must remain the same value throughout the stream so we can determine when the segments occur.

**Comment by joeyparrish** [comment]
@KingjZhang, please update Wowza and let us know if that resolves your issue.  Thanks!

**Comment by joeyparrish** [comment]
@KingjZhang, changing availabilityStartTime is not valid in our view, and we believe this will be resolved by updating Wowza.  I'm going to go ahead and close this issue for now.  If an update does not solve your problem, let us know and we can help investigate.
