### ISSUE TITLE
Stream not playing until seek happens

### ISSUE THREAD

**Issue by hghazzi** [google/shaka-player#724]
@joeyparrish @TheModMaker I encountered this exact same issue found in https://github.com/google/shaka-player/issues/600#issuecomment-286866004. It says it was resolved in v2.0.6. Tested it in the demo page, as well as with master on Chrome 57. 

Here's the sample stream: https://akadash0-test.akamaized.net/test/clear/test-multi-audio/master.mpd (this link works fine for me)

Tested the archived demo pages and verified that this started occurring between v2.0.0 and v2.0.1.

**Comment by TheModMaker** [comment]
The link doesn't work for me (still getting 403 errors).  A 403 error is `Forbidden`.  This means that I don't have permission to access to the asset.  My guess would be that either you have a cookie that allows you to access it or that server does IP filtering.

Try accessing the URL from an Incognito window to see if you have cookies.  Also try accessing it from another location to see if it is being filtered by IP or location.

**Comment by hghazzi** [comment]
You're right. Sorry about that. Will try to get you a working one soon.

**Comment by hghazzi** [comment]
Resolved in v2.0.7

**Comment by joeyparrish** [comment]
Excellent.  Thank you for letting us know!

**Comment by hghazzi** [comment]
Thank you! it was fixed by this.

https://github.com/google/shaka-player/commit/03f9c60020a781e323447b69216b7019adc763f2
