### ISSUE TITLE
Remove useRelativeCueTimestamps option

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#726]
In v2.0.1, we introduced the useRelativeCueTimestamps option to control the behavior of our WebVTT parser.  We decided in https://github.com/google/shaka-player/issues/480#issuecomment-251256814 that we would remove this option in v2.1.0.  All WebVTT timestamps in v2.1.0 will be relative to the segment time.

**Comment by TheModMaker** [comment]
We also have a custom asset `Tears of Steel (multiperiod with segmented subtitles and PTO)` which uses Period-relative timestamps (IIRC).  This was added to specifically test the old behavior and should be updated  to match the new behavior.  (I was the one who created this asset, so I can help)

**Comment by joeyparrish** [comment]
That asset is still referenced by existing versions, so any updates should be made by forking that asset for v2.1.0 and leaving the existing one where it is.
