### ISSUE TITLE
Clear Key for offline, without persistent license support

### ISSUE THREAD

**Issue by phamduongnhatnam** [google/shaka-player#728]
- What version of Shaka Player are you using?
2.0.3
  - Can you reproduce the issue with our latest release version?
Yes
  - Can you reproduce the issue with the latest code from `master`?

- Are you using the demo app or your own custom app?
My app
  - If custom app, can you reproduce the issue using our demo app?
Yes

- What browser and OS are you using?
Chrome Android, Crosswalk.
Android 6

- What did you do?
 I noticed that the persistent-license is not yet supported for DRM in Chrome Android that mean we can't store and play offline for other DRM systems. But what if the Clear Key has already specified in the code?
Is there any way to store Clearkey encrypted content like Mp4 clear content and play it? I've give a try to do that with shaka-player 2.0.3 but not success.
  - What content did you load?
Mp4 Encrypted using Clearkey packaged by shaka-packager
    - If standard demo asset, which one?

    - If custom asset, what manifest and license server URIs?

  - How did you interact with the content, if at all?

- What did you expect to happen?
Play encrypted mp4 Clearkey content.

- What actually happened?
6001 Error.

**Comment by joeyparrish** [comment]
Clear Key content does not require a license request, so there is no dependency on a license server when offline.  However, Clear Key is not secure in terms of content security.

Shaka Player's offline storage system is built to store everything offline, including the license for protected content.  Without persistent license support, Shaka Player can't store protected content offline.  It is feasible to store the content offline without a license, then use Clear Key to decrypt, but Shaka Player is not designed that way.

**Comment by joeyparrish** [comment]
Of course, Shaka Player is open source, so you can always modify it to suit your needs.  The classes you would be interested in are DrmEngine, in lib/media/drm_engine.js, and Storage, in lib/offline/storage.js.

Sorry we can't help you directly with this.  Let us know if there is anything else we can do, or if you need further guidance through the code base.

**Comment by phamduongnhatnam** [comment]
Thank you so much @joeyparrish, in my use case I don't implement a license server. I have my content encrypted using clearkey, just need a little bit secure in our country that people can't play downloaded file directly. Currently I hide the key with in my application.
Can you guide me where to modify the source to allow the storing process of offline encrypted content?
P/S: I have read the code but can't find where to apply it.

**Comment by joeyparrish** [comment]
Where we call `drmEngine.init` in `Storage`, there is a boolean parameter set to `true` to tell `DrmEngine` that we need persistent sessions.  You could make this `false` for Clear Key.  That should allow you store the content offline.

In `Storage.prototype.createOfflineManifest_`, we store the session IDs to load them again later.  For Clear Key, that array of session IDs should be empty instead.  Otherwise, we would try to load those sessions and fail.

That should be a start, but I'm not sure if that's everything.  Let me know how it goes.

**Comment by phamduongnhatnam** [comment]
Awesom, I'll modify and test it then let you know how it goes.

**Comment by phamduongnhatnam** [comment]
@joeyparrish I have successfully modified the source in `storage.js` like what you have point and can play the encrypted content without network.

**Comment by joeyparrish** [comment]
@phamduongnhatnam, I'm glad I could help.  If you think there would be value in this feature for others, feel free to make a pull request.
