### ISSUE TITLE
4K on hosted demo not working for Chromecast Ultra

### ISSUE THREAD

**Issue by markbastiaans** [google/shaka-player#729]
- What version of Shaka Player are you using?
2.0.6-debug
  - Can you reproduce the issue with our latest release version?
Yes
  - Can you reproduce the issue with the latest code from `master`?
Yes

- Are you using the demo app or your own custom app?
The hosted demo app
  - If custom app, can you reproduce the issue using our demo app?
N/A

- What browser and OS are you using?
Chrome on Windows 7 x86 / Firefox on Windows 10 x64

- What did you do?
Tried casting a 4K asset from the hosted demo to a Chromecast Ultra
    - What content did you load?
Both standard demo assets and a custom DASH+HEVC UHD live asset
    - If standard demo asset, which one?
All Sintel 4K assets
    - If custom asset, what manifest and license server URIs?
N/A
  - How did you interact with the content, if at all?
Tried selecting resolution

- What did you expect to happen?
3840x2160 available in resolution selector

- What actually happened?
Only up to 1920x1080 available

Casting 4K video from other players (e.g. Youtube) works to this particular Chromecast in its current setup.
Thanks in advance for considering this issue!

**Comment by joeyparrish** [comment]
There may be something wrong with our 4k detection in `lib/cast/cast_receiver.js`.  We'll take a look.  Thanks!

**Comment by markbastiaans** [comment]
Thanks! Looking forward to a fix.

A temporary workaround seems to be forcing the resolution in `demo/receiver_app.js` with a well-placed `this.player_.setMaxHardwareResolution(3840, 2160);`

**Comment by joeyparrish** [comment]
(Please note that 4k resolutions will not be made available on a non-4k TV, even if the device is a Chromecast Ultra.  The Chromecast's resolution support check is based on the TV itself, as well as the device.)

Detection of 4k on Chromecast Ultra was introduced in v2.0.4, but our receiver app ID was still configured to serve v2.0.2.  This has now been updated to the latest, v2.0.6.  If you reboot the Chromecast, it should pick up the new URL and get the correct receiver app version.

I have updated the config, rebooted my Ultra, and tested with this up-to-date version on a 4k TV.  I am now seeing 4k resolutions available.  Sorry for the trouble!
