### ISSUE TITLE
List for bitrates + How can I count stalls that happen because of buffering ?

### ISSUE THREAD

**Issue by utkubulkan** [google/shaka-player#730]
Hi, 

How can I get the list of bitrates that is available in mpd and how can I count the number of stalls that happen during video presentation ?

Many thanks

- What version of Shaka Player are you using? 2.0.6

**Comment by joeyparrish** [comment]
You can get a list of tracks with `player.getTracks()`.  See the `bandwidth` field of the track, which is in bits/sec.  You can get stats about buffering (stalls) via `player.getStats()`.

For more details, please see the docs:
  Player: https://shaka-player-demo.appspot.com/docs/api/shaka.Player.html
  Tracks: https://shaka-player-demo.appspot.com/docs/api/shakaExtern.html#Track
  Stats: https://shaka-player-demo.appspot.com/docs/api/shakaExtern.html#Stats

Let us know if there's anything else we can do.

**Comment by joeyparrish** [comment]
@utkubulkan, I hope we have answered your question.  I will close the issue now, but we can reopen it if you need further assistance.  Thanks!
