### ISSUE TITLE
Playback halts on start in Firefox

### ISSUE THREAD

**Issue by OrenMe** [google/shaka-player#732]
- What version of Shaka Player are you using? 
v2.0.6, happens all the way to 2.0.1, doesn't happen on 2.0.0

  - Can you reproduce the issue with our latest release version? 
Yes

  - Can you reproduce the issue with the latest code from `master`? 
Yes

- Are you using the demo app or your own custom app? 
Demo and own

  - If custom app, can you reproduce the issue using our demo app? 
Yes

- What browser and OS are you using? 
Windows and Mac Firefox 52

- What did you do? 
Load a movie and play

  - What content did you load? 
     [My own clear media](https://cdnapisec.kaltura.com/p/2006242/sp/200624200/playManifest/entryId/0_kcgm3wo1/flavorIds/0_idbhwoal,0_f9gb7azr/format/mpegdash/protocol/https/a.mpd?referrer=aHR0cHM6Ly93d3cua2FsdHVyYS5jb20=)
    - If standard demo asset, which one?

    - If custom asset, what manifest and license server URIs?

  - How did you interact with the content, if at all?

- What did you expect to happen?
Playback starts when I press play

- What actually happened?
Playback starts for a fraction and then stops with spinner, if I seek it continues

[Attached logs for v2.0.0, v2.0.1 and v2.0.6](https://gist.github.com/OrenMe/977f31babf39858966c32195dbaf4c60)

**Comment by TheModMaker** [comment]
The first frame in the media starts at 0.25 sec.  Chrome ignores this gap and reports a buffered range starting at 0.  Firefox reports this gap and it is larger than what we will jump at the beginning.  I suggest working with the encoder to make the content start at 0, or using `presentationTimeOffset` in the manifest.

We are working on gap jumping which will help this content, see #555.

**Comment by joeyparrish** [comment]
Since this seems to be the same issue as #555, I'm going to close it as a duplicate.  We'll be addressing #555 as soon as possible.  Thanks!

**Comment by OrenMe** [comment]
Thanks @joeyparrish and @TheModMaker
