### ISSUE TITLE
Live DASH stream does not work in Shaka but works in dash-if-reference-player

### ISSUE THREAD

**Issue by radiantmediaplayer** [google/shaka-player#733]
- What version of Shaka Player are you using?
2.0.6
  - Can you reproduce the issue with our latest release version?
Yes
  - Can you reproduce the issue with the latest code from `master`?
Yes

- Are you using the demo app or your own custom app?
demo app (compiled from latest git because the test stream is not HTTPS so I could not test from online demo)

- What browser and OS are you using?
Latest stable Chrome on Windows 10

- What did you do?
Input DASH live stream (nimble streamer based) http://live1.karwan.tv/karwan.tv/vin-tv/manifest.mpd into demo app - see that streams does not start

- What did you expect to happen?
Stream should start - the same stream seems to work fine at http://mediapm.edgesuite.net/dash/public/nightly/samples/dash-if-reference-player/index.html

- What actually happened?
Shaka did not start 

I have attached the debug logs
```
Using native EME as-is.
mediasource.js:49 Using native MSE as-is.
promise.js:118 Using native Promises.
vttcue.js:36 Using native VTTCue.
drm_engine.js:1278 It is recommended that a robustness level be specified. Not specifying the robustness level could result in unexpected behavior in the future, potentially including failure to play.
(anonymous) @ drm_engine.js:1278
shaka.media.DrmEngine.probeSupport @ drm_engine.js:1277
shaka.Player.probeSupport @ player.js:399
shakaDemo.init @ main.js:133
streaming_engine.js:1117 (video:2) cannot find segment: currentPeriod.startTime=0 lookupTime=40596.03366661072
shaka.media.StreamingEngine.lookupSegmentPosition_ @ streaming_engine.js:1117
shaka.media.StreamingEngine.getSegmentReferenceNeeded_ @ streaming_engine.js:1069
shaka.media.StreamingEngine.update_ @ streaming_engine.js:958
shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:860
streaming_engine.js:1117 (audio:1) cannot find segment: currentPeriod.startTime=0 lookupTime=40596.03766655922
shaka.media.StreamingEngine.lookupSegmentPosition_ @ streaming_engine.js:1117
shaka.media.StreamingEngine.getSegmentReferenceNeeded_ @ streaming_engine.js:1069
shaka.media.StreamingEngine.update_ @ streaming_engine.js:958
shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:860
streaming_engine.js:1117 (video:2) cannot find segment: currentPeriod.startTime=0 lookupTime=40597.03766655922
shaka.media.StreamingEngine.lookupSegmentPosition_ @ streaming_engine.js:1117
shaka.media.StreamingEngine.getSegmentReferenceNeeded_ @ streaming_engine.js:1069
shaka.media.StreamingEngine.update_ @ streaming_engine.js:958
shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:860
streaming_engine.js:1117 (audio:1) cannot find segment: currentPeriod.startTime=0 lookupTime=40597.03966665268
shaka.media.StreamingEngine.lookupSegmentPosition_ @ streaming_engine.js:1117
shaka.media.StreamingEngine.getSegmentReferenceNeeded_ @ streaming_engine.js:1069
shaka.media.StreamingEngine.update_ @ streaming_engine.js:958
shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:860
streaming_engine.js:1117 (video:2) cannot find segment: currentPeriod.startTime=0 lookupTime=40598.0406665802
shaka.media.StreamingEngine.lookupSegmentPosition_ @ streaming_engine.js:1117
shaka.media.StreamingEngine.getSegmentReferenceNeeded_ @ streaming_engine.js:1069
shaka.media.StreamingEngine.update_ @ streaming_engine.js:958
shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:860
streaming_engine.js:1117 (audio:1) cannot find segment: currentPeriod.startTime=0 lookupTime=40598.04166650772
shaka.media.StreamingEngine.lookupSegmentPosition_ @ streaming_engine.js:1117
shaka.media.StreamingEngine.getSegmentReferenceNeeded_ @ streaming_engine.js:1069
shaka.media.StreamingEngine.update_ @ streaming_engine.js:958
shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:860
streaming_engine.js:1117 (video:2) cannot find segment: currentPeriod.startTime=0 lookupTime=40599.04266667366
shaka.media.StreamingEngine.lookupSegmentPosition_ @ streaming_engine.js:1117
shaka.media.StreamingEngine.getSegmentReferenceNeeded_ @ streaming_engine.js:1069
shaka.media.StreamingEngine.update_ @ streaming_engine.js:958
shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:860
streaming_engine.js:1117 (audio:1) cannot find segment: currentPeriod.startTime=0 lookupTime=40599.04766654968
shaka.media.StreamingEngine.lookupSegmentPosition_ @ streaming_engine.js:1117
shaka.media.StreamingEngine.getSegmentReferenceNeeded_ @ streaming_engine.js:1069
shaka.media.StreamingEngine.update_ @ streaming_engine.js:958
shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:860
streaming_engine.js:1117 (video:2) cannot find segment: currentPeriod.startTime=0 lookupTime=40600.04566669464
shaka.media.StreamingEngine.lookupSegmentPosition_ @ streaming_engine.js:1117
shaka.media.StreamingEngine.getSegmentReferenceNeeded_ @ streaming_engine.js:1069
shaka.media.StreamingEngine.update_ @ streaming_engine.js:958
shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:860
streaming_engine.js:1117 (audio:1) cannot find segment: currentPeriod.startTime=0 lookupTime=40600.04966664314
shaka.media.StreamingEngine.lookupSegmentPosition_ @ streaming_engine.js:1117
shaka.media.StreamingEngine.getSegmentReferenceNeeded_ @ streaming_engine.js:1069
shaka.media.StreamingEngine.update_ @ streaming_engine.js:958
shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:860
dash_parser.js:1091 Updating manifest...
streaming_engine.js:1117 (video:2) cannot find segment: currentPeriod.startTime=0 lookupTime=40601.04666662216
shaka.media.StreamingEngine.lookupSegmentPosition_ @ streaming_engine.js:1117
shaka.media.StreamingEngine.getSegmentReferenceNeeded_ @ streaming_engine.js:1069
shaka.media.StreamingEngine.update_ @ streaming_engine.js:958
shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:860
streaming_engine.js:1117 (audio:1) cannot find segment: currentPeriod.startTime=0 lookupTime=40601.05066657066
shaka.media.StreamingEngine.lookupSegmentPosition_ @ streaming_engine.js:1117
shaka.media.StreamingEngine.getSegmentReferenceNeeded_ @ streaming_engine.js:1069
shaka.media.StreamingEngine.update_ @ streaming_engine.js:958
shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:860
streaming_engine.js:1117 (video:2) cannot find segment: currentPeriod.startTime=0 lookupTime=40602.04766654968
shaka.media.StreamingEngine.lookupSegmentPosition_ @ streaming_engine.js:1117
shaka.media.StreamingEngine.getSegmentReferenceNeeded_ @ streaming_engine.js:1069
shaka.media.StreamingEngine.update_ @ streaming_engine.js:958
shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:860
streaming_engine.js:1117 (audio:1) cannot find segment: currentPeriod.startTime=0 lookupTime=40602.051666498184
shaka.media.StreamingEngine.lookupSegmentPosition_ @ streaming_engine.js:1117
shaka.media.StreamingEngine.getSegmentReferenceNeeded_ @ streaming_engine.js:1069
shaka.media.StreamingEngine.update_ @ streaming_engine.js:958
shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:860
streaming_engine.js:1117 (video:2) cannot find segment: currentPeriod.startTime=0 lookupTime=40603.04966664314
shaka.media.StreamingEngine.lookupSegmentPosition_ @ streaming_engine.js:1117
shaka.media.StreamingEngine.getSegmentReferenceNeeded_ @ streaming_engine.js:1069
shaka.media.StreamingEngine.update_ @ streaming_engine.js:958
shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:860
streaming_engine.js:1117 (audio:1) cannot find segment: currentPeriod.startTime=0 lookupTime=40603.05266666412
shaka.media.StreamingEngine.lookupSegmentPosition_ @ streaming_engine.js:1117
shaka.media.StreamingEngine.getSegmentReferenceNeeded_ @ streaming_engine.js:1069
shaka.media.StreamingEngine.update_ @ streaming_engine.js:958
shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:860
streaming_engine.js:1117 (video:2) cannot find segment: currentPeriod.startTime=0 lookupTime=40604.051666498184
shaka.media.StreamingEngine.lookupSegmentPosition_ @ streaming_engine.js:1117
shaka.media.StreamingEngine.getSegmentReferenceNeeded_ @ streaming_engine.js:1069
shaka.media.StreamingEngine.update_ @ streaming_engine.js:958
shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:860
streaming_engine.js:1117 (audio:1) cannot find segment: currentPeriod.startTime=0 lookupTime=40604.054666519165
shaka.media.StreamingEngine.lookupSegmentPosition_ @ streaming_engine.js:1117
shaka.media.StreamingEngine.getSegmentReferenceNeeded_ @ streaming_engine.js:1069
shaka.media.StreamingEngine.update_ @ streaming_engine.js:958
shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:860
streaming_engine.js:1117 (video:2) cannot find segment: currentPeriod.startTime=0 lookupTime=40605.053666591644
shaka.media.StreamingEngine.lookupSegmentPosition_ @ streaming_engine.js:1117
shaka.media.StreamingEngine.getSegmentReferenceNeeded_ @ streaming_engine.js:1069
shaka.media.StreamingEngine.update_ @ streaming_engine.js:958
shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:860
streaming_engine.js:1117 (audio:1) cannot find segment: currentPeriod.startTime=0 lookupTime=40605.056666612625
shaka.media.StreamingEngine.lookupSegmentPosition_ @ streaming_engine.js:1117
shaka.media.StreamingEngine.getSegmentReferenceNeeded_ @ streaming_engine.js:1069
shaka.media.StreamingEngine.update_ @ streaming_engine.js:958
shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:860
dash_parser.js:1091 Updating manifest...
streaming_engine.js:1117 (video:2) cannot find segment: currentPeriod.startTime=0 lookupTime=40606.4076666832
shaka.media.StreamingEngine.lookupSegmentPosition_ @ streaming_engine.js:1117
shaka.media.StreamingEngine.getSegmentReferenceNeeded_ @ streaming_engine.js:1069
shaka.media.StreamingEngine.update_ @ streaming_engine.js:958
shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:860
streaming_engine.js:1117 (audio:1) cannot find segment: currentPeriod.startTime=0 lookupTime=40606.40966653824
shaka.media.StreamingEngine.lookupSegmentPosition_ @ streaming_engine.js:1117
shaka.media.StreamingEngine.getSegmentReferenceNeeded_ @ streaming_engine.js:1069
shaka.media.StreamingEngine.update_ @ streaming_engine.js:958
shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:860
streaming_engine.js:1117 (video:2) cannot find segment: currentPeriod.startTime=0 lookupTime=40608.401666641235
shaka.media.StreamingEngine.lookupSegmentPosition_ @ streaming_engine.js:1117
shaka.media.StreamingEngine.getSegmentReferenceNeeded_ @ streaming_engine.js:1069
shaka.media.StreamingEngine.update_ @ streaming_engine.js:958
shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:860
streaming_engine.js:1117 (audio:1) cannot find segment: currentPeriod.startTime=0 lookupTime=40608.40366649628
shaka.media.StreamingEngine.lookupSegmentPosition_ @ streaming_engine.js:1117
shaka.media.StreamingEngine.getSegmentReferenceNeeded_ @ streaming_engine.js:1069
shaka.media.StreamingEngine.update_ @ streaming_engine.js:958
shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:860
streaming_engine.js:1117 (video:2) cannot find segment: currentPeriod.startTime=0 lookupTime=40610.40566658974
shaka.media.StreamingEngine.lookupSegmentPosition_ @ streaming_engine.js:1117
shaka.media.StreamingEngine.getSegmentReferenceNeeded_ @ streaming_engine.js:1069
shaka.media.StreamingEngine.update_ @ streaming_engine.js:958
shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:860
streaming_engine.js:1117 (audio:1) cannot find segment: currentPeriod.startTime=0 lookupTime=40610.40566658974
shaka.media.StreamingEngine.lookupSegmentPosition_ @ streaming_engine.js:1117
shaka.media.StreamingEngine.getSegmentReferenceNeeded_ @ streaming_engine.js:1069
shaka.media.StreamingEngine.update_ @ streaming_engine.js:958
shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:860
dash_parser.js:1091 Updating manifest...
streaming_engine.js:1117 (video:2) cannot find segment: currentPeriod.startTime=0 lookupTime=40612.41066646576
shaka.media.StreamingEngine.lookupSegmentPosition_ @ streaming_engine.js:1117
shaka.media.StreamingEngine.getSegmentReferenceNeeded_ @ streaming_engine.js:1069
shaka.media.StreamingEngine.update_ @ streaming_engine.js:958
shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:860
streaming_engine.js:1117 (audio:1) cannot find segment: currentPeriod.startTime=0 lookupTime=40612.4116666317
shaka.media.StreamingEngine.lookupSegmentPosition_ @ streaming_engine.js:1117
shaka.media.StreamingEngine.getSegmentReferenceNeeded_ @ streaming_engine.js:1069
shaka.media.StreamingEngine.update_ @ streaming_engine.js:958
shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:860
streaming_engine.js:1117 (video:2) cannot find segment: currentPeriod.startTime=0 lookupTime=40614.401666641235
shaka.media.StreamingEngine.lookupSegmentPosition_ @ streaming_engine.js:1117
shaka.media.StreamingEngine.getSegmentReferenceNeeded_ @ streaming_engine.js:1069
shaka.media.StreamingEngine.update_ @ streaming_engine.js:958
shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:860
streaming_engine.js:1117 (audio:1) cannot find segment: currentPeriod.startTime=0 lookupTime=40614.402666568756
shaka.media.StreamingEngine.lookupSegmentPosition_ @ streaming_engine.js:1117
shaka.media.StreamingEngine.getSegmentReferenceNeeded_ @ streaming_engine.js:1069
shaka.media.StreamingEngine.update_ @ streaming_engine.js:958
shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:860
streaming_engine.js:1117 (video:2) cannot find segment: currentPeriod.startTime=0 lookupTime=40615.40666651726
shaka.media.StreamingEngine.lookupSegmentPosition_ @ streaming_engine.js:1117
shaka.media.StreamingEngine.getSegmentReferenceNeeded_ @ streaming_engine.js:1069
shaka.media.StreamingEngine.update_ @ streaming_engine.js:958
shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:860
streaming_engine.js:1117 (audio:1) cannot find segment: currentPeriod.startTime=0 lookupTime=40615.40666651726
shaka.media.StreamingEngine.lookupSegmentPosition_ @ streaming_engine.js:1117
shaka.media.StreamingEngine.getSegmentReferenceNeeded_ @ streaming_engine.js:1069
shaka.media.StreamingEngine.update_ @ streaming_engine.js:958
shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:860
streaming_engine.js:1117 (video:2) cannot find segment: currentPeriod.startTime=0 lookupTime=40617.40366649628
shaka.media.StreamingEngine.lookupSegmentPosition_ @ streaming_engine.js:1117
shaka.media.StreamingEngine.getSegmentReferenceNeeded_ @ streaming_engine.js:1069
shaka.media.StreamingEngine.update_ @ streaming_engine.js:958
shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:860
streaming_engine.js:1117 (audio:1) cannot find segment: currentPeriod.startTime=0 lookupTime=40617.404666662216
shaka.media.StreamingEngine.lookupSegmentPosition_ @ streaming_engine.js:1117
shaka.media.StreamingEngine.getSegmentReferenceNeeded_ @ streaming_engine.js:1069
shaka.media.StreamingEngine.update_ @ streaming_engine.js:958
shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:860
dash_parser.js:1091 Updating manifest...
```

**Comment by ebeffim** [comment]
We encounter the same issue. We've been using dashjs and hear good words about shaka. But this issue is blocking us from moving to shaka

**Comment by ebeffim** [comment]
Attached is the very first mpd file fetched for our live stream. We would appreciate if you could point out what need to change for this manifest, in order for it to work.  

<?xml version="1.0" encoding="UTF-8"?>

<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" profiles="urn:mpeg:dash:profile:isoff-live:2011" type="dynamic" availabilityStartTime="1970-01-01T00:00:00Z" publishTime="2017-03-24T16:32:18Z" timeShiftBufferDepth="PT50S" minimumUpdatePeriod="PT10S" maxSegmentDuration="PT10S" minBufferTime="PT10S">
	<Period id="1" start="PT0S">
	<AdaptationSet id="1" group="1" bitstreamSwitching="true" segmentAlignment="true" contentType="video" mimeType="video/mp4"  maxWidth="1280" maxHeight="720" par="16:9" maxFrameRate="30" startWithSAP="1" maxPlayoutRate="30">
	<SegmentTemplate timescale="10000000" media="S!d2EKREFTSF9VTkVOQxIKVP7...8Bnw__/QualityLevels($Bandwidth$)/Fragments(video=$Time$)" initialization="S!d2EKREFTSF9VTkVOQxIKVP7...8Bnw__/QualityLevels($Bandwidth$)/Fragments(video=Init)" presentationTimeOffset="14903730205310280" >
	<SegmentTimeline>
	<S t="14903730805310280" d="100000000" r="4"/>
</SegmentTimeline>
</SegmentTemplate>
	<Representation id="video.1.L1" bandwidth="1048576" codecs="avc1.4d401e" width="640" height="360" frameRate="30" sar="1:1"/>
	<Representation id="video.1.L2" bandwidth="1258291" codecs="avc1.4d401f" width="960" height="540" frameRate="30" sar="1:1"/>
	<Representation id="video.1.L3" bandwidth="1677721" codecs="avc1.4d4028" width="1280" height="720" frameRate="30" sar="1:1"/>
</AdaptationSet>
	<AdaptationSet id="2" group="2" bitstreamSwitching="true" segmentAlignment="true" contentType="audio" mimeType="audio/mp4" lang="und">
	<AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
	<SegmentTemplate timescale="48000" media="S!d2EKREFTSF9VTkVOQxIKVP7...8Bnw__/QualityLevels($Bandwidth$)/Fragments(audio_482_und=$Time$)" initialization="S!d2EKREFTSF9VTkVOQxIKVP7...8Bnw__/QualityLevels($Bandwidth$)/Fragments(audio_482_und=Init)" presentationTimeOffset="71537904985489" >
	<SegmentTimeline>
	<S t="71537907865745" d="480256" r="2"/>
	<S d="479232"/>
	<S d="480256"/>
</SegmentTimeline>
</SegmentTemplate>
	<Representation id="audio_482_und.2.L1" bandwidth="64000" codecs="mp4a.40.2" audioSamplingRate="48000"/>
</AdaptationSet>
</Period></MPD>

Dashjs would issue the following requests and start to play. The segment index numbers are simply derived from t= and d= in the SegmentTimeline 

Request URL:http://172.29.3.205:5555/sdash/LIVE$channel1/10.mpd/S!d2EKREFTSF9VTkVOQxIKVP7...8Bnw__/QualityLevels(1048576)/Fragments(video=Init)

Request URL:http://172.29.3.205:5555/sdash/LIVE$channel1/10.mpd/S!d2EKREFTSF9VTkVOQxIKVP7...8Bnw__/QualityLevels(64000)/Fragments(audio_482_und=Init)

Request URL:http://172.29.3.205:5555/sdash/LIVE$channel1/10.mpd/S!d2EKREFTSF9VTkVOQxIKVP7...8Bnw__/QualityLevels(1048576)/Fragments(video=14903730905310280)


shaka errors out with "cannot find segment" (see below). The manifst does not have UTCTiming tag but we added the following in our code, where manfiestUri is the uri of this particular manifest.

player.configure({
    manifest: {
        dash: {
            'clockSyncUri': manifestUri
        }
    }
});
We would appreciate if you could point out what need to change for this manifest, in order for it to work.  

mediakeys.js:52 Using native EME as-is.
mediasource.js:49 Using native MSE as-is.
promise.js:118 Using native Promises.
vttcue.js:36 Using native VTTCue.
player.js:557 No preferred audio language set.  We will choose an arbitrary language initially
(anonymous) @ player.js:557
playerEval.js:143 The video has now been loaded!
streaming_engine.js:1128 (video:1) cannot find segment: currentPeriod.startTime=0 lookupTime=1490373094.6326666
shaka.media.StreamingEngine.lookupSegmentPosition_ @ streaming_engine.js:1128
shaka.media.StreamingEngine.getSegmentReferenceNeeded_ @ streaming_engine.js:1080
shaka.media.StreamingEngine.update_ @ streaming_engine.js:969
shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:872
streaming_engine.js:1128 (audio:4) cannot find segment: currentPeriod.startTime=0 lookupTime=1490373094.6346667
shaka.media.StreamingEngine.lookupSegmentPosition_ @ streaming_engine.js:1128
shaka.media.StreamingEngine.getSegmentReferenceNeeded_ @ streaming_engine.js:1080
shaka.media.StreamingEngine.update_ @ streaming_engine.js:969
shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:872
streaming_engine.js:1128 (video:1) cannot find segment: currentPeriod.startTime=0 lookupTime=1490373095.6346667
shaka.media.StreamingEngine.lookupSegmentPosition_ @ streaming_engine.js:1128
shaka.media.StreamingEngine.getSegmentReferenceNeeded_ @ streaming_engine.js:1080
shaka.media.StreamingEngine.update_ @ streaming_engine.js:969
shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:872
streaming_engine.js:1128 (audio:4) cannot find segment: currentPeriod.startTime=0 lookupTime=1490373095.6366665

**Comment by ebeffim** [comment]
[mpd-shaka.txt](https://github.com/google/shaka-player/files/869432/mpd-shaka.txt)

mpd file attached.

**Comment by ebeffim** [comment]
This is first time I report an issue. Not sure why the lines are crossed out.  Apologize for reporting one issue with multiple comments.

**Comment by joeyparrish** [comment]
Hi @radiantmediaplayer, @ebeffim, we will take a look.  Thank you for the report.

**Comment by joeyparrish** [comment]
The manifest at http://live1.karwan.tv/karwan.tv/vin-tv/manifest.mpd is failing due to clock sync issues with your server.

I fetched a copy of the manifest at unix timestamp 1490560582 ([attached](https://github.com/google/shaka-player/files/871023/nimble.mpd.txt)).  The manifest's `availabilityStartTime` attribute says `2017-03-25T14:59:56Z`, which is timestamp 1490453996.  This means the stream has been available for 1490560582 - 1490453996 = 106586 seconds.  So the largest timestamp in the media should be close to 106586 (give or take one segment).  The `timeShiftBufferDepth` attribute is 45 seconds, to the smallest timestamp in the media should be close to 106586 - 45 = 106541.

The first segment in the video stream's `SegmentTimeline` is at media time 11977175632.  Divide by timescale 90000, and you get time 133079.  The last timestamp in the timeline is 11977175632, + 6 segments with length 900000, which gives 11982575632.  Divide by timescale 90000, and you get time 133139.

So SegmentTimeline shows the range 133079 to 133139, while the MPD element shows the range 106541 to 106586.  The ends of those ranges are offset by 133139 - 106586 = 26553 seconds = roughly 7.3 hours.

Your server's clock is therefore off by 7.3 hours, which causes it to present an inaccurate timeline, which causes Shaka Player to request segments that won't be available until 7.3 hours in the future.

I don't know much about Nimble Streamer, so I can't say for certain how you should fix this, but I have a few guesses.  One of these should solve your problem:

1. If you're in control of your server and its clock, make sure your server is using NTP and always has an accurate clock.  This is **critical** for live streaming.  The [DASH-IF Interoperability Points v4.0](http://dashif.org/wp-content/uploads/2016/12/DASH-IF-IOP-v4.0-clean.pdf) has this to say on the subject:
> 3.5. Synchronization Considerations
> In order to properly access MPDs and Segments that are available on DASH servers, **DASH servers and clients should synchronize their clocks to a globally accurate time standard**. Specifically **it is expected that the Segment Availability Times** as computed from the MPD according to ISO/IEC 23009-1 [4], section 5.3.9.5 and additional details in ISO/IEC 23009-3 [6], section 6.4 **are accurately announced in the MPD.**
2. If you're not in control of the server and its clock, you must provide a `UTCTiming` element in the manifest so that the client has a way to synchronize with the server's idea of the current time.  You may need to update Nimble Streamer, configure it, or file a support request with the author.  Again, quoting [DASH-IF Interoperability Points v4.0](http://dashif.org/wp-content/uploads/2016/12/DASH-IF-IOP-v4.0-clean.pdf):
> 4.7.2. Service Provider Requirements and Guidelines
> If the Media Presentation is dynamic or if the MPD@availabilityStartTime is present then the service shall provide a Media Presentation as follows:
> - The segment availability times announced in the MPD should be generated from a device that is synchronized to a globally accurate timing source**, preferably using NTP.
> - The MPD **should contain at least one UTCTiming element** ...
> - **If the MPD does not contain any element UTCTiming** then the segments shall be available latest **at the announced segment availability time using a globally accurate timing source**.

Please feel free to reference this analysis and recommendations in any bug report you may file with Nimble.  Thanks!

**Comment by ebeffim** [comment]
Thanks for detailing your analysis. It seems that the manifest I included in my report has the same "time difference" issue. And here is my analysis of that manifest.

The publishTime="2017-03-24T16:32:18Z" (which is the same as the Date HTTP header) is 1490387538 sec and with availabilityStartTime="1970-01-01T00:00:00Z", it means that the stream has been available for  1490387538 seconds. with timeShiftBufferDepth of 50 second, the range of timestamp expected is between 1490387488 to 1490387538 seconds.

The first segment in the video stream's SegmentTimeline is at media time 14903730805310280. Divide by timescale 10000000, and we get time 1490373080. Compare with expected starting time 1490387488, the difference is 1490387488 - 1490373080 = 14408 seconds which is about 4 hours difference...

**Comment by alexpokotilo** [comment]
Hi,
I'm Nimble streamer team representative. I agree with your analysis.
Let me explain why your have availability time problem here.
When stream created we init availability stream time with current utc time. As provided manifest has timescale == 90000 this means source stream is mpegts. For mpegts streams time usually starts from arbitrary positive value. Moreover time may overrun and jump into the future from time to time and anyone who works with mpegts knows about that.
I know IOP requirements and in case if your push rtmp/rtsp stream what start from 0 your will not see such issues. In ideal world availability time requirements meat and everything will work fine. But consider the case when time on the server was wrong during manifest build or source stream moved timestamp back u

**Comment by alexpokotilo** [comment]
Hi,
I'm Nimble streamer team representative. I agree with your analysis.
Let me explain why your have availability time problem here.
When stream created we init availability stream time with current utc time. As provided manifest has timescale == 90000 this means source stream is mpegts. For mpegts streams time usually starts from arbitrary positive value. Moreover time may overrun and jump into the future from time to time and anyone who works with mpegts knows about that.
I know IOP requirements and in case if your push rtmp/rtsp stream what start from 0 your will not see such issues. In ideal world availability time requirements meat and everything will work fine. But consider the case when time on the server was wrong during manifest build or source stream moved timestamp back.
I don't want to say it's player issue but even DASH-IF already agreed there is something wrong with all these time processing in DASH. It looks like standard was made in assumption that there will not be any problems with time. But in anyway bitmovin and dash.js plays http://live1.karwan.tv/karwan.tv/vin-tv/manifest.mpd file.
You can easily check this here http://player.wmspanel.com/
Again I don't want to say shaka work not according to the spec. But if player see segments in manifest even with wrong start time I think it should player them. IOP doesn't provide us an answer how we should handle stream sources with timestamps that periodically reset and jump in the future. I see such streams every day

**Comment by radiantmediaplayer** [comment]
@joeyparrish I did contact Nimble streamer team and you can find their feedback above. I understand this is a grey area but as @alexpokotilo mentioned our concern is that this stream plays fine with other, notable, DASH-capable players. Shaka is a great DASH player and we find it much easier to deal with and more stable than other DASH capable players we have tested and used. I will get back to our user and explain a workaround in the meantime.

**Comment by alexpokotilo** [comment]
Hi,
we will arrange additional effort to follow IOP and DASH standard. Please consider to add additional robustness to the player as well

**Comment by joeyparrish** [comment]
Hi @radiantmediaplayer, @alexpokotilo,

In the past (Shaka Player v1), we attempted to work around problems in DASH manifests such as this one.  Those work-arounds caused bugs and maintenance challenges that my team could not keep up with.  In some cases, these work-arounds event caused us to fail on IOP-compliant content.

Therefore, we decided that Shaka Player v2 would be more strict in how we interpret and implement the spec.  This means we won't try to cope with or fix up non-compliant content.  I believe that Shaka Player is a more stable, interoperable product because of that decision.

I apologize for being inflexible on this point, but the beauty of open source is that you can always make a fork and change Shaka's behavior until you are able to solve the content issue.  And when your content does follow IOP, you will be able to confidently play that content not just in Shaka Player, but in any interoperable player.

Thanks for reaching out, and please do let us know if you need anything else.

**Comment by radiantmediaplayer** [comment]
@joeyparrish that is allright. Your approach makes sense and we are happy with the features and stability that shaka 2 is currently bringing. We have a workaround for this specific content so I am closing now.
