### ISSUE TITLE
Multi period stream hangs

### ISSUE THREAD

**Issue by soualid** [google/shaka-player#734]
Hello,

We are trying to play a multi period MPD to add a preroll to an existing video, both streams are protected using CENC (WV). The stream plays well using latest dashif test player, but not with latest shaka player.

The stream starts well, but do not switch on second period after the first one ends, when I try to seek into both periods, they both plays well.

You can reproduce the issue with the following mpd : 
https://s3-eu-west-1.amazonaws.com/vodstorage.arte.tv/test/preroll.mpd

Using the following licence server :
https://widevine-dash.ezdrm.com/proxy?pX=BA5EDC&username=eduthequepreprod_test

With : https://shaka-player-demo.appspot.com/demo/
And : http://dashif.org/reference/players/javascript/v2.4.1/samples/dash-if-reference-player/index.html

Thank you in advance for your feedback.

**Comment by TheModMaker** [comment]
The video stream for the first Period doesn't end at the end of the Period.  The Period ends at 11.008 sec, but the video stream ends at 10.96 sec.  This small gap breaks our buffering logic and puts us in a buffering state.

We are currently working on gap jumping and you can track it in #555, which should fix cases like this.

**Comment by soualid** [comment]
Thanks !
