### ISSUE TITLE
[Question]Logic for initial track/bitrate selection

### ISSUE THREAD

**Issue by OrenMe** [google/shaka-player#735]
Hi,

What is the mechanism in which Shaka decides the initial bitrate track selection? always start from lowest?
Currently there's a way to add restrictions, which will be hard cap limits.
Is there a way to request initial bitrate and start ABR logic from there?

Also, is there a way to determine this on spec level, e.g. in DASH manifest?
For example, in HLS the first track in the manifest is the one to be loaded first.

Thanks.

**Comment by joeyparrish** [comment]
Hi Oren,

In Shaka Player, AbrManager is the component which makes all ABR decisions, including the initial choice of tracks.  You can plug in your own ABR logic, but the default makes decisions based on a bandwidth estimate.

Before the ABR system has enough information to accurately estimate bandwidth, a default estimate is used, and this in turn dictates the first tracks selected.  Typically, the initial track is shown for about 2 segments while we build an estimate, but for content with 10-second segments, this can be 20 seconds of playback.

The default estimate can be configured by the application.  For docs, see:

https://shaka-player-demo.appspot.com/docs/api/shaka.Player.html#configure
https://shaka-player-demo.appspot.com/docs/api/shakaExtern.html#AbrConfiguration

Here's a quick example that sets the default bandwidth estimate to 1 Mbit:

```js
player.configure({
  abr: {
    defaultBandwidthEstimate: (1<<20)  // unit: bits/sec
  }
});
```

Does this answer your question?

**Comment by OrenMe** [comment]
Hi @joeyparrish, thanks for the example, totally clear.
Would you happen to know regarding the spec itself, is it like HLS where first chunklist in a playlist is the one selected for initial bitrate?

For example, in this case although the first chunklist bitrate is not the lowest an HLS player implementation would start at it and not at lowest one(which is the second)
```
#EXTM3U

#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=649879,CODECS="mp4a.40.2, avc1.4d401e"
gear2/prog_index.m3u8

#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=232370,CODECS="mp4a.40.2, avc1.4d4015"
gear1/prog_index.m3u8

#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=991714,CODECS="mp4a.40.2, avc1.4d401e"
gear3/prog_index.m3u8

#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1927833,CODECS="mp4a.40.2, avc1.4d401f"
gear4/prog_index.m3u8
```

**Comment by joeyparrish** [comment]
I am not aware of anything in the spec that would insist we start with the first without regard for bitrate, but I can't claim to know the whole spec by heart.  In any case, we always choose based on bitrate when the default AbrManager is used.

**Comment by OrenMe** [comment]
Thanks!

**Comment by joeyparrish** [comment]
Always happy to help.
