### ISSUE TITLE
6001 Error on Chrome 58+

### ISSUE THREAD

**Issue by salmoro** [google/shaka-player#736]
Videos that work perfectly with chrome 55-56 (57?) and Firefox, give 6001 errors on the latest Chromes (58-59). I can see the Widevine license requests in the "Network" tab in dev-tools and they seem to be normal.

This is with private content so if you need further information I'll PM you a link.
I've tested on the latest Shaka as well (built from master today) and I get the same results.

Thanks very much,
Sal

**Comment by joeyparrish** [comment]
Is the page URL http or https?

**Comment by salmoro** [comment]
My bad, I don't see the requests in the network tab. Which I do see in the working versions.
The player and content URLs are all http.

**Comment by salmoro** [comment]
@joeyparrish, just changed to https and all is good. Thanks very much.

**Comment by joeyparrish** [comment]
Okay, makes sense.  Starting in Chrome 58, EME and therefore protected content are only possible via https or localhost.  This is to keep Chrome's implementation in line with changes in the spec which require a secure context for EME.  You can find [Chrome's announcement here](https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/tXmKPlXsnCQ/discussion) and [our own announcement here](https://groups.google.com/forum/#!topic/shaka-player-users/L0dYA3TcAkA).
