### ISSUE TITLE
DRM Version Detection

### ISSUE THREAD

**Issue by boredom2** [google/shaka-player#738]
Hi there,

this is not an Issue, its just a Question.
Is there a Way to find out, which DRM System will be used?
We use a DRM System with Widevine AND PlayReady (which works very good), I just would like to know, if there is a way to get the chosen DRM System from Shaka itself easily?

Thanks,
Christoph

**Comment by Pierpaolo1992** [comment]
Maybe CDM `schemeIdUri` can uniquely identify PlayReady or Widevine?

**Comment by TheModMaker** [comment]
You can call `player.drmInfo()` after playback has started.  This will get the [DrmInfo](https://shaka-player-demo.appspot.com/docs/api/shakaExtern.html#DrmInfo) that was used to initialize EME.  In your case, the `keySystem` property will be `com.widevine.alpha` for Widevine, or `com.microsoft.playready` for PlayReady.

**Comment by boredom2** [comment]
Perfect, thanks!
