### ISSUE TITLE
Content not stored offline in demo. Manifest issue?

### ISSUE THREAD

**Issue by danyentezari** [google/shaka-player#739]
**- What version of Shaka Player are you using?**
v2.0.0-debug

  **- Can you reproduce the issue with our latest release version?**
The issue persists with Shaka Player v2.0.6-debug (hosted demo)

**- Are you using the demo app or your own custom app?**
The demo app, https://shaka-player-demo.appspot.com/demo/.

**- What browser and OS are you using?**
Google Chrome 57.0.2987.98, macOS Sierra 10.12.3.

**- What did you do?**
Tried to load custom asset and store offline.

**- What content did you load?**
https://s3.ap-south-1.amazonaws.com/debucket1/sample-dash/home/527379.mpd - Generated with Bitmovin

I did not enter a license server.

**- What did you expect to happen?**
The contents to be stored offline.

**- What actually happened?**
The window froze, 0% progress, and no console error. The video does play, however.

**Comment by joeyparrish** [comment]
Wow, this hung my tab in Chrome.  We will look into it.  Thanks for the report!

**Comment by joeyparrish** [comment]
Infinite loop!  :scream:

When we build a list of segments to download, we ask the stream for the next segment until it returns null.  This manifest uses SegmentTemplate, so a reference can be calculated for any segment number.  But for VOD, we should take the period duration into account and not return references that should not exist.

**Comment by danyentezari** [comment]
v2.1.0? I'll switch to Shaka Packager, then.

For your reference, here's the link to download the Bitmovin encoding output:
[https://we.tl/tqZyaCwPDB](https://we.tl/tqZyaCwPDB)

Best of luck!

**Comment by joeyparrish** [comment]
I'm putting it in the v2.1 milestone for tracking purposes, but we will cherry-pick the fix to our next bug fix release, v2.0.7.

**Comment by joeyparrish** [comment]
This was just released in v2.0.7.

**Comment by danyentezari** [comment]
@joeyparrish You are magnificent!

I really needed this to work 😄 .

**Comment by joeyparrish** [comment]
We are always happy to help.
