### ISSUE TITLE
Undetermined Language subtitle is added playing a video with HLS Native player

### ISSUE THREAD

**Issue by sebastien-code-it** [google/shaka-player#7392]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**If the problem is related to FairPlay, have you read the tutorial?**

yes

**What version of Shaka Player are you using?**

4.11.7

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `main`?**
yes

**Are you using the demo app or your own custom app?**
both

**If custom app, can you reproduce the issue using our demo app?**
yes

**What browser and OS are you using?**
Mac OS Sequoia and Safari 18.0

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**

https://na-fps.ezdrm.com/demo/ezdrm/master.m3u8
https://na-fps.ezdrm.com/demo/ezdrm/stream_1.m3u8

**What configuration are you using?  What is the output of `player.getNonDefaultConfiguration()`?**

This is visible on the demo :)

**What did you do?**

Go to the demo page : https://shaka-player-demo.appspot.com/demo/#audiolang=fr-FR;textlang=fr-FR;uilang=fr-FR;assetBase64=eyJuYW1lIjoiQmlnIEJ1Y2sgQnVubnkgKEZhaXJQbGF5KSIsInNob3J0TmFtZSI6IiIsImljb25VcmkiOiJodHRwczovL3N0b3JhZ2UuZ29vZ2xlYXBpcy5jb20vc2hha2EtYXNzZXQtaWNvbnMvYmlnX2J1Y2tfYnVubnkucG5nIiwibWFuaWZlc3RVcmkiOiJodHRwczovL25hLWZwcy5lemRybS5jb20vZGVtby9lemRybS9tYXN0ZXIubTN1OCIsInNvdXJjZSI6IkVaRFJNIiwiZm9jdXMiOmZhbHNlLCJkaXNhYmxlZCI6ZmFsc2UsImV4dHJhVGV4dCI6W10sImV4dHJhVGh1bWJuYWlsIjpbXSwiZXh0cmFDaGFwdGVyIjpbXSwiY2VydGlmaWNhdGVVcmkiOm51bGwsImRlc2NyaXB0aW9uIjpudWxsLCJpc0ZlYXR1cmVkIjpmYWxzZSwiZHJtIjpbIkZhaXJwbGF5IERSTSJdLCJmZWF0dXJlcyI6WyJIaWdoIGRlZmluaXRpb24iLCJITFMiLCJNUDQiLCJWT0QiXSwibGljZW5zZVNlcnZlcnMiOnsiX190eXBlX18iOiJtYXAiLCJjb20uYXBwbGUuZnBzIjoiaHR0cHM6Ly9mcHMuZXpkcm0uY29tL2FwaS9saWNlbnNlcy9iOTllZDllNS1jNjQxLTQ5ZDEtYmZhOC00MzY5MmI2ODZkZGIifSwibGljZW5zZVJlcXVlc3RIZWFkZXJzIjp7Il9fdHlwZV9fIjoibWFwIn0sInJlcXVlc3RGaWx0ZXIiOm51bGwsInJlc3BvbnNlRmlsdGVyIjpudWxsLCJjbGVhcktleXMiOnsiX190eXBlX18iOiJtYXAifSwiZXh0cmFDb25maWciOnsiZHJtIjp7ImFkdmFuY2VkIjp7ImNvbS5hcHBsZS5mcHMiOnsic2VydmVyQ2VydGlmaWNhdGVVcmkiOiJodHRwczovL2Zwcy5lemRybS5jb20vZGVtby92aWRlby9lbGVpc3VyZS5jZXIifX0sInNlcnZlcnMiOnsiY29tLmFwcGxlLmZwcyI6Imh0dHBzOi8vZnBzLmV6ZHJtLmNvbS9hcGkvbGljZW5zZXMvYjk5ZWQ5ZTUtYzY0MS00OWQxLWJmYTgtNDM2OTJiNjg2ZGRiIn19fSwiZXh0cmFVaUNvbmZpZyI6bnVsbCwiYWRUYWdVcmkiOm51bGwsImltYVZpZGVvSWQiOm51bGwsImltYUFzc2V0S2V5IjpudWxsLCJpbWFDb250ZW50U3JjSWQiOm51bGwsImltYU1hbmlmZXN0VHlwZSI6bnVsbCwibWVkaWFUYWlsb3JVcmwiOm51bGwsIm1lZGlhVGFpbG9yQWRzUGFyYW1zIjpudWxsLCJ1c2VJTUEiOnRydWUsIm1pbWVUeXBlIjpudWxsfQ==;panel=ALL_CONTENT;panelData=drm:FAIRPLAY;build=uncompiled

There is only one Fairplay DRM demo. 
Click on play. 
Then click on the gear to access the subtitles
There a  subtitle "Undetermined language" 

**What did you expect to happen?**
This subtitle should not be there as this video has not subtitles at all. 

**What actually happened?**

I think this is linked to the HLS native player somehow as this is not reproduced anywhere else in the demo.

**Are you planning send a PR to fix it?**
Unfortunately I will not have the bandwidth to send a PR. 

Thanks a lot to the team for maintaining such a great product :)
![subtitle bug reproduction](https://github.com/user-attachments/assets/0fcb2912-1ff2-44fa-9682-00e9de2eb1b5)

**Comment by joeyparrish** [comment]
You are right, there are no subs described in the playlists.

What is the behavior when you play this video directly with `<video src="...">` on Safari?  What do you get from `videoElement.textTracks`?

With native HLS, we are dependent on Safari for parsing and playback.  Though I don't know why Safari thinks it has subtitles, somehow it does.
