### ISSUE TITLE
Error when running all.sh

### ISSUE THREAD

**Issue by samdutton** [google/shaka-player#74]
I get the following error when trying to build all.sh:

    Exception in thread "main" java.lang.UnsupportedClassVersionError: 
    com/google/javascript/jscomp/CommandLineRunner : Unsupported major.minor version 51.0

**Comment by joeyparrish** [comment]
What OS are you on?  What version of Java do you have?

**Comment by samdutton** [comment]
Sorry – forgot to add that.

Mac OS X 10.9.5
Java 1.6.0_65

**Comment by joeyparrish** [comment]
The compiler is built with Java 1.7, so you will need that at a minimum.  Sorry for the inconvenience!  I will update the docs on github to mention this.

**Comment by samdutton** [comment]
Thanks Joey – I should have thought of that...

For anyone needing to update Java on Mac, I recommend the instructions here
<https://gist.github.com/johan/10590467>.
