### ISSUE TITLE
HLS live streaming support

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#740]
Our HLS implementation still lacks live streaming support

**Comment by PidginEnemy** [comment]
I waiting this feature too :)

**Comment by sergioavazquez** [comment]
Any news on this? I'm waiting for it too!

**Comment by joeyparrish** [comment]
Thanks for letting us know you're interested!

We've been working on it, but we have not been able to complete the work yet.  The model for live streaming in HLS is different from the DASH model, and we still have some serious refactoring to do.

**Comment by sergioavazquez** [comment]
Great! I'll give it a try when you're done with it!

**Comment by avelad** [comment]
Affter test the latest commit, it's not working with this stream: https://cdn.demo.anevia.com/live/eds/Arte/HLS-MP4/Arte.m3u8
I get: 
"Error: Shaka Error MANIFEST.HLS_COULD_NOT_PARSE_SEGMENT_START_TIME ()
    at new shaka.util.Error (http://localhost:8000/lib/util/error.js:72:13)
    at shaka.hls.HlsParser.<anonymous> (http://localhost:8000/lib/hls/hls_parser.js:1244:17)
    at <anonymous>"

The error occurred parsing a webvtt file.

**Comment by joeyparrish** [comment]
Yes, we are aware.  There are several more commits coming that will finish the implementation.  It's not quite done yet.

**Comment by avelad** [comment]
@joeyparrish, with this stream https://nightly-dot-shaka-player-demo.appspot.com/demo/#asset=https://cdn.demo.anevia.com/live/nas40/Arte/mirada_test/Arte.m3u8;lang=es and https://nightly-dot-shaka-player-demo.appspot.com/demo/#asset=https://cdn.demo.anevia.com/live/eds/Arte/HLS-MP4/Arte.m3u8;lang=es I see infinite loading only.

**Comment by joeyparrish** [comment]
@avelad, I will give those a try and see if it's the same bug I'm already working on.

**Comment by joeyparrish** [comment]
@avelad, it looks like a different bug, specific to TS live streams.  Can you file a new one, please?

We parse the TS segments to get their timestamps, since HLS doesn't provide that information.  However, as far as I can tell, the MP4 output from mux.js has different timestamps than what we parsed from the TS segments.  So the MediaSource timeline doesn't line up with the Player's seek range.

**Comment by avelad** [comment]
Thanks @joeyparrish . I raised https://github.com/google/shaka-player/issues/1102

About the second stream (HLS-MP4: https://cdn.demo.anevia.com/live/eds/Arte/HLS-MP4/Arte.m3u8 ), what is the problem?

**Comment by joeyparrish** [comment]
I'm not sure what's wrong with the second stream.  It's different from the other issues, though.  Can you file a new bug for that, too?  Please use the issue template to capture details on the behavior you're seeing.

**Comment by joeyparrish** [comment]
Modulo separate issues raised by @avelad, HLS live is working in the `master` branch and in the nightly build (which I just updated a few hours early).

We're going to close this (very general) issue now.  If you find problems with HLS live in the nightly build (as @avelad has), please file new issues so that we can focus on those individual bugs.  Thanks!
