### ISSUE TITLE
HLS I-frame-only playlist support

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#742]
We do not yet support trick mode in HLS.

**Comment by theodab** [comment]
It looks like there might not be enough information in iframe playlists generated by apple's tools to satisfy MediaSource.
I won't be able to work on this for a while. If anyone else wants to work on it, I have a WIP you can reference.

**Comment by joeyparrish** [comment]
Without reconstructing a container for the I-frames, this is infeasible on top of MediaSource.  Closing this feature request.
