### ISSUE TITLE
Make AbrManager targets configurable

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#744]
As requested by @dobrusev in https://github.com/google/shaka-player/issues/565#issuecomment-288330319, SimpleAbrManager could be configurable with regards to upgrade target, downgrade target, and switch interval.

**Comment by ismena** [comment]
The change is checked in. shakaExtern.AbrConfiguration now includes switchInterval, bandwidthUpgradeTarget and bandwidthDowngradeTarget fields.

**Comment by marcusparnwell** [comment]
@joeyparrish Is there a target date for release of this and 2.2? 
We are seeing higher rebuffering on shaka player than other players (hasPlayer etc) and believe not being able to set these values is the root cause.

**Comment by ismena** [comment]
@marcusparnwell You're addressing the right person in terms of asking about the release date, while Joey's getting back to you on this, let me note that the change is already available in the latest master should you want to get it sooner than it's officially released.

**Comment by joeyparrish** [comment]
I've just updated the [v2.2.0 milestone](https://github.com/google/shaka-player/milestone/13) and bumped some enhancements down to [v2.3.0](https://github.com/google/shaka-player/milestone/14).  I hope we will be able to wrap up v2.2.0 by the end of the month.
