### ISSUE TITLE
Widevine DASH Playback failure with Shaka player local setup

### ISSUE THREAD

**Issue by sivarajendranaidu** [google/shaka-player#748]
- What version of Shaka Player are you using?
Shaka Player v2.0.0-debug setup locally

- Are you using the demo app or your own custom app?
As current shaka player is not supporting playback over http; I had setup locally

- What browser and OS are you using?
Chrome Browser (Windows 8.1)

- What did you do?

 Created a Widevine CENC DASH Content using shaka packager with following command

./packager input=/home/siva/Desktop/fifo.mp4,stream=video,output=/home/siva/Desktop/fifo_v_cenc.mp4 --enable_widevine_encryption=true --key_server_url "https://license.uat.widevine.com/cenc/getcontentkey/widevine_test" --content_id "3031323334353637" --signer "widevine_test" --aes_signing_key "1ae8ccd0e7985cc0b6203a55855a1034afc252980e970ca90e5202689f947ab9" --aes_signing_iv "d58ce954203b7c9a9a9d467f59839249" -protection_scheme "cenc" --mpd_output /home/siva/Desktop/fifo_v_cenc.mpd
[0404/032902:INFO:demuxer.cc(58)] Initialize Demuxer for file '/home/siva/Desktop/fifo.mp4'.
[0404/032902:INFO:track_run_iterator.cc(166)] Edit list with media time 0 ignored.
[0404/032902:INFO:demuxer.cc(170)] Demuxer::Run() on file '/home/siva/Desktop/fifo.mp4'.
[0404/032904:INFO:single_segment_segmenter.cc(118)] Update media header (moov) and rewrite the file to '/home/siva/Desktop/fifo_v_cenc.mp4'.
[0404/032905:INFO:mp4_muxer.cc(165)] MP4 file '/home/siva/Desktop/fifo_v_cenc.mp4' finalized.
Packaging completed successfully.

and using LA_URL : https://proxy.uat.widevine.com/proxy in Shaka Player

- What did you expect to happen?
Expecting Playback to happen

- What actually happened?
Only first few frames are decoded and latter stalls

Please find the error prompted as follows:

Shaka Error DRM.LICENSE_REQUEST_FAILED (shaka.util.Error { "category": 1, "code": 1002, "data": [ "https://proxy.uat.widevine.com/proxy" ], "message": "Shaka Error NETWORK.HTTP_ERROR (https://proxy.uat.widevine.com/proxy)", "stack": "Error: Shaka Error NETWORK.HTTP_ERROR (https://proxy.uat.widevine.com/proxy)\n at new shaka.util.Error (http://192.168.9.79/shaka-player/lib/util/error.js:63:13)\n at XMLHttpRequest.xhr.onerror (http://192.168.9.79/shaka-player/lib/net/http_plugin.js:86:14)" })

**Comment by joeyparrish** [comment]
I expect this is the same cause as this report on the packager side: https://github.com/google/shaka-packager/issues/171

**Comment by joeyparrish** [comment]
@sivarajendranaidu, since you report in https://github.com/google/shaka-packager/issues/171#issuecomment-292010681 that this is working with a different license server, I'm going to go ahead and close this issue.  Thanks!
