### ISSUE TITLE
NPM publish more frequently

### ISSUE THREAD

**Issue by palmerj3** [google/shaka-player#75]
I would like to request more frequent publishes to NPM.

CommonJS support was unavailable in 1.2.x and now 1.3.x contains a bug I cannot work around (autoplay issue).  
Given the github issue I see it's been resolved but still not published to NPM thus my request.

It's probably not a good idea to auto-publish every single commit to master but perhaps each time an issue is resolved and verified via tests then a patch and/or minor release could be published.

It's typically several weeks between NPM publishes whereas issues are resolved quite often.

Thoughts?

**Comment by joeyparrish** [comment]
I'd like to streamline things and tag bugfix releases more frequently, but I just don't have the resources at the moment.  I hope to be able to improve this in the future.

The goal for our next bugfix release (v1.3.1) is to have all known issues in v1.3.0 fixed.  You can track progress here:  https://github.com/google/shaka-player/milestones/v1.3.1  This is currently scheduled for May 22, but this is just an estimate.

I'm very sorry for the inconvenience, but if you need to get ahead of the release schedule, you can always check out the latest sources from github and run the build script.

**Comment by palmerj3** [comment]
Cool thank you. As of now I'm still using shaka as a pre-compiled include in my project instead of an NPM dependency.

Ideally I would prefer seeing a release schedule that's more iterative where all resolved issues are published. Especially for non-breaking changes it seems very low risk to do so.

If there is any way I can help with this please let me know and I would be thrilled to lend a hand.

Thanks again for all you do - much appreciated

**Comment by joeyparrish** [comment]
Yeah, I'd like it to be more iterative, too.  It's a process issue, and we're working on it.  Thanks!
