### ISSUE TITLE
Live stream not playing with error cannot find segment

### ISSUE THREAD

**Issue by OrenMe** [google/shaka-player#754]
- What version of Shaka Player are you using? v2.0.8

  - Can you reproduce the issue with our latest release version? Yes

  - Can you reproduce the issue with the latest code from `master`? Yes

- Are you using the demo app or your own custom app? Demo app and custom

  - If custom app, can you reproduce the issue using our demo app?

- What browser and OS are you using? MAC Chrome

- What did you do? Load a live stream and hit play

  - What content did you load? Clear live stream

    - If standard demo asset, which one?

    - If custom asset, what manifest and license server URIs?

  - How did you interact with the content, if at all?

- What did you expect to happen? Expect it will start playing

- What actually happened? 
Got "streaming_engine.js:1023 (video:4) cannot find segment: currentPeriod.startTime=0 lookupTime=545665153.6760001" for many times and no playback

What does it mean when this warning appears?

Log file added
[shaka-player-demo.appspot.com-1492353855525.txt](https://github.com/google/shaka-player/files/924344/shaka-player-demo.appspot.com-1492353855525.txt)

**Comment by joeyparrish** [comment]
This looks like a time sync issue.  Can you provide us with a link to the specific live stream you are using?  Do you have issues with the live sim that appears in our list of demo assets under the DASH-IF heading?

**Comment by OrenMe** [comment]
@joeyparrish can I send it to you privately? the other demo assets are playing fine.
Also, the asset I'm testing is working on other players, such as dashjs, so I guess it is something with this stream characteristic and how Shaka is expecting it to be.

**Comment by joeyparrish** [comment]
Yes, you can send it privately.  My email is in CONTRIBUTORS.

It's not surprising that dashjs plays it.  Some live stream encoders produce content that does not accurately represent the presentation timeline.  Dashjs has some way of handling various kinds of not-quite-right content.

Can you tell me what encoder/packager/etc is used to produce your stream?  Have you checked for updates from them, in case this is a bug they have already fixed?

**Comment by OrenMe** [comment]
@joeyparrish sent more details over mail. Thanks.

**Comment by OrenMe** [comment]
Hi @joeyparrish - did you get a chance to test this? thanks.

**Comment by TheModMaker** [comment]
This is a clock sync issue.  You can add a `<UTCTiming>` element to the manifest or set the `.manifest.dash.clockSyncUri` configuration to fix this, see #376 for more info.

At `2017-04-20T16:25:02Z` (on my local clock) I fetched the manifest.  The `availabilityStartTime` is `2000-01-01T00:00:00Z`, so the current time in media time should be `546020702000 ms`.  The last segment in the manifest is listed as `5459893548158198`, converted to ms is `545989354815 ms`.  The difference is 31347 seconds.

**Comment by OrenMe** [comment]
thanks @TheModMaker! I'll check it out.

**Comment by joeyparrish** [comment]
@OrenMe, did we answer your question?  Is there anything else you need?

**Comment by OrenMe** [comment]
@joeyparrish still waiting for vendor to apply change, I'll update. Thanks.

**Comment by OrenMe** [comment]
Hi @joeyparrish - it seems that your advice solved the issue on Chrome and Firefox, but on IE11(win10, haven't tested win 8.1 yet) the stream doesn't work.
It seems that there's a bigint precision error that coerce the LSB and therefore we see requests to segments which doesn't exist on the server.
I sent you an updated stream URL in the email.

As this is another issue, let me know if you would like me to open a new one.

Thanks.

**Comment by TheModMaker** [comment]
I believe this will be fixed by #832.

**Comment by OrenMe** [comment]
Yes, this fix has been introduced by our team, and if it's acceptable then it solves this issue completely. Thanks.

**Comment by ismena** [comment]
Sounds good. Closing the issue.
