### ISSUE TITLE
Firefox 52.0.2(64bit) Shaka Error MEDIA.MEDIA_SOURCE_OPERATION_THREW (InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable)

### ISSUE THREAD

**Issue by Zorig** [google/shaka-player#755]
- What version of Shaka Player are you using?
2.0.8
  - Can you reproduce the issue with our latest release version?
    yes
  - Can you reproduce the issue with the latest code from `master`?
    unknown

- Are you using the demo app or your own custom app?
  I load [demo](https://shaka-player-demo.appspot.com/demo/) `Angel One (multicodec, multilingual, Widevine)`
  - If custom app, can you reproduce the issue using our demo app?

- What browser and OS are you using?
Linux 4.4.0-72-generic, Firefox 52.0.2 (64bit)

- What did you do?
  Just try to load demo widevine content
  - What content did you load?
    Angel One (multicodec, multilingual, Widevine)
    - If standard demo asset, which one?
      Angel One (multicodec, multilingual, Widevine)
    - If custom asset, what manifest and license server URIs?
 
  - How did you interact with the content, if at all?

- What did you expect to happen?
   Play just fine

- What actually happened?
 it gives me error on console `Media resource blob:https://shaka-player-demo.appspot.com/4ffb6bd6-deac-4088-be20-900eb82b2068 could not be decoded.`
also this one 
```
Player error Object { category: 3, code: 3015, data: Array[1], message: "Shaka Error MEDIA.MEDIA_SOURCE_OPER…", stack: "shaka.util.Error@https://shaka-play…" }  main.js:206:3
	shakaDemo.onError_ https://shaka-player-demo.appspot.com/demo/main.js:206:3
	shakaDemo.onErrorEvent_ https://shaka-player-demo.appspot.com/demo/main.js:197:3
	shaka.util.FakeEventTarget.prototype.dispatchEvent https://shaka-player-demo.appspot.com/lib/util/fake_event_target.js:119:9
	shaka.cast.CastProxy.prototype.playerProxyLocalEvent_ https://shaka-player-demo.appspot.com/lib/cast/cast_proxy.js:514:3
	shaka.util.FakeEventTarget.prototype.dispatchEvent https://shaka-player-demo.appspot.com/lib/util/fake_event_target.js:119:9
	shaka.Player.prototype.onError_ https://shaka-player-demo.appspot.com/lib/player.js:1722:3
	shaka.media.StreamingEngine.prototype.fetchAndAppend_/< https://shaka-player-demo.appspot.com/lib/media/streaming_engine.js:1174:9
```

**Comment by joeyparrish** [comment]
I can reproduce.  Not sure what's going on yet.

**Comment by joeyparrish** [comment]
"Angel One", multicodec (MP4 + WebM), Firefox on Linux:
 - works in the clear
 - fails to decode with Widevine
 - fails to start at all with ClearKey

"Tears of Steel", MP4 only, Firefox on Linux:
 - works in the clear
 - works with Widevine

"Angel One", same as above, but forcing the player to ignore Firefox's reported support of Opus:
 - works in the clear
 - works with Widevine
 - fails to start at all with ClearKey

So it seems that ClearKey is generally broken on Firefox, and so is the combination of Opus+Widevine.  I will file bugs on Mozilla.

**Comment by joeyparrish** [comment]
ClearKey is working on Firefox with the nightly build of Shaka Player.

Bug filed for the Opus failure: https://bugzilla.mozilla.org/show_bug.cgi?id=1357133

**Comment by Zorig** [comment]
Yeah forgot to mention "tears of steel" works. Anyway when I test it on os x it(angel one) works on Firefox 52.0.2

**Comment by cpeterso** [comment]
I commented in the [Firefox bug](https://bugzil.la/1357133). Firefox's Widevine CDM process is crashing.

**Comment by joeyparrish** [comment]
It appears that this has been fixed in Firefox.  I tested in Firefox 53 on Mac.
