### ISSUE TITLE
Offline deletion take too long time to remove a downloaded content

### ISSUE THREAD

**Issue by phamduongnhatnam** [google/shaka-player#756]
- What version of Shaka Player are you using?
2.0.6
  - Can you reproduce the issue with our latest release version?
Yes
  - Can you reproduce the issue with the latest code from `master`?
Yes

- Are you using the demo app or your own custom app?
Custom
  - If custom app, can you reproduce the issue using our demo app?

- What browser and OS are you using?
Chrome Android, Crosswalk + Ionic + Cordova

- What did you do?
Remove downloaded offline file. 18MB of content take ~34 seconds to remove.
  - What content did you load?
My own content
    - If standard demo asset, which one?

    - If custom asset, what manifest and license server URIs?

  - How did you interact with the content, if at all?

- What did you expect to happen?
Immediate or nearly immediate content deletion.

- What actually happened?
Deletion take very long time to remove the offline content.

**Comment by joeyparrish** [comment]
@phamduongnhatnam, can you reproduce this issue:

1. on desktop Chrome?
2. on Android Chrome directly without Crosswalk or Cordova?

**Comment by phamduongnhatnam** [comment]
Yes,
1. On Chrome desktop: 
- Download 207MB of content then delete it takes 17.49 seconds.
2. On Cordova with Crosswalk latest (on Chrome Android which a little bit faster): 
- Download the same file with 207MB, it takes 59.4 seconds.

**Comment by joeyparrish** [comment]
@phamduongnhatnam, I can't support Cordova or Crosswalk directly, but since you can reproduce slow deletes on desktop Chrome, it should be easy enough for us to look into.  Thanks for the report.

**Comment by phamduongnhatnam** [comment]
@joeyparrish Thanks, I know that cordova/crosswalk is not a main point for us.

**Comment by vaage** [comment]
@phamduongnhatnam I was able to improve the delete performance. Please run this through your benchmarking and let us know if it meets your expectations.

**Comment by joeyparrish** [comment]
This fix was just released in v2.1.2.

**Comment by phamduongnhatnam** [comment]
@joeyparrish Once again your work is awesome!

**Comment by joeyparrish** [comment]
I'm just the messenger!  Thanks belong to @vaage for this one.

**Comment by phamduongnhatnam** [comment]
@vaage I did the bench mark again and it take about 10 seconds to remove 1GB content in Chrome Desktop. The performance in Cordova+Crosswalk also improved. Congrats!
