### ISSUE TITLE
shaka.util.DataViewReader.readTerminatedString reads one more byte!

### ISSUE THREAD

**Issue by asdftu** [google/shaka-player#757]
this issue both in latest code from `master` and latest release version.

when parsed EMSG BOX,  just using following hex for example,

hex: `75 72 6E 3A 73 63 74 65 3A 73 63 74 65 33 35 3A 32 30 31 33 3A 78 6D 6C`` 00 00 00 01 31`
string: `urn:scte:scte35:2013:xml``....1`

readTerminatedString not only reads `75 72 6E 3A 73 63 74 65 3A 73 63 74 65 33 35 3A 32 30 31 33 3A 78 6D 6C` which means `urn:scte:scte35:2013:xml`, but also reads `00` which belongs next section `00 00 00 01 ` indicates the size.

**Comment by joeyparrish** [comment]
The `00` byte at the end of the string is the "terminated" part of `readTerminatedString`.

We based this code on the spec, which I will double-check.  In the mean time, can you provide a sample?  What packager/encoder produced this sample?

**Comment by joeyparrish** [comment]
Here's the definition of the emsg box in the DASH spec, ISO 23009-1:2014:

```
5.10.3.3.2 Definition
  Box Type: `emsg`
  Container: Segment
  Mandatory: No
  Quantity: Zero of more

5.10.3.3.3 Syntax
aligned(8) class DASHEventMessageBox extends FullBox(‘emsg’, version = 0, flags = 0) {
  string scheme_id_uri;
  string value;
  unsigned int(32) timescale;
  unsigned int(32) presentation_time_delta;
  unsigned int(32) event_duration;
  unsigned int(32) id;
  unsigned int(8)
  message_data[];
}
```

So the bytes after "scheme_id_uri" can't be a size as you said, since it is followed by "value".  I will dig up the definition of "string" to confirm that it contains a terminating nul character.

**Comment by asdftu** [comment]
thanks Joe,
I finally found it was the stream issue. the stream i used use 4 bytes int value indicates how long the string was. i had informed the stream provider to fix their issue.
thanks very much.

**Comment by joeyparrish** [comment]
Thanks for letting us know!
