### ISSUE TITLE
Better API for the track variants

### ISSUE THREAD

**Issue by Ross-cz** [google/shaka-player#758]
- What version of Shaka Player are you using? 395cc1745e9c51f3c0b66dfc7d3f5eee545a7e74

I would like to know easily, whether the track variants has video, audio or subtitle track. Now I have to check for a comma inside codecs. Here is sample output from the method getVariantTracks():
`{"id":7,"active":false,"type":"variant","bandwidth":1799135,"language":"en","kind":null,"width":1920,"height":1080,"frameRate":23.976023976023978,"mimeType":"video/mp4","codecs":"avc1.640032, mp4a.40.2","primary":false}`

It would be nice to have properties grouped instead of merged.
Btw, is it necessary to output constant property type = 'variant'?

Thanks!

**Comment by joeyparrish** [comment]
Text tracks are separate from variants.  Look for type == 'text'.

The combined codecs in variants is another side-effect of our HLS support, but I think we can probably change it.  Would you prefer to see audioCodec and videoCodec in separate fields?

**Comment by Ross-cz** [comment]
Hi Joey!

Thanks for the type clarification. We need to do the simple audio detection. If there aren't any audio tracks, we could somehow let users know about it.
I think its a great idea to just split codecs. Could you add audioChannelsCount too?

**Comment by joeyparrish** [comment]
Counting audio channels in DASH is complex.  There is another issue filled for that already (#424).  I'll update that issue soon with more details.

I'm fairly sure we can split up the codecs, though.

**Comment by joeyparrish** [comment]
This is now fixed in `master`, and I intend to cherry-pick it for v2.1.1 in the near future.  You can see it now in [our nightly build](https://nightly-dot-shaka-player-demo.appspot.com/demo/).  Please let us know if this meets your needs.

**Comment by joeyparrish** [comment]
Cherry-picked to v2.1.1.
