### ISSUE TITLE
CDNJS

### ISSUE THREAD

**Issue by boredom2** [google/shaka-player#760]
Hi there,

this is not a Bug or somehow Code-related :)
Could you maybe make the 2.1.0 Version available via CDNJS like the older Builds?
That would be great.

Thanks,
Christoph

**Comment by joeyparrish** [comment]
@boredom2, I understand your confusion.  I mentioned this in the release announcement, but it's not obvious at all.

CDNJS is populated automatically from npm (by a robot controlled entirely by CDNJS).  The CDNJS distribution therefore always lags behind npm by a few days.

If it doesn't show up in one week, file a bug at https://github.com/cdnjs/cdnjs to let them know that their update bot is not working.

**Comment by boredom2** [comment]
I see, thanks for the quick reply - as always:-)))

**Comment by joeyparrish** [comment]
Always happy to help!
