### ISSUE TITLE
Support for SegmentURL@indexRange attribute on SegmentList

### ISSUE THREAD

**Issue by sunilkumarmohanty** [google/shaka-player#765]
- What version of Shaka Player are you using?

  - Can you reproduce the issue with our latest release version? Yes

  - Can you reproduce the issue with the latest code from `master`?
Yes

- Are you using the demo app or your own custom app?
I am using the demo app
- What browser and OS are you using?

Chrome on Mac

- What did you do?

MPD File format

`<Period id="1" duration="PT0H9M56.459S">
  <AdaptationSet segmentAlignment="true" bitstreamSwitching="true" maxWidth="854" maxHeight="480" maxFrameRate="24" par="16:9" lang="und">
   <SegmentList>
    <Initialization sourceURL="bbb_320_24_dash_set1_init.mp4"/>
   </SegmentList>
   <Representation id="1" mimeType="video/mp4" codecs="avc3.64000D" width="320" height="240" frameRate="24" sar="4:3" startWithSAP="1" bandwidth="292021">
    <BaseURL>bbb_320_24_track1_dash.mp4</BaseURL>
    <SegmentList timescale="12288" duration="122880">
      <SegmentURL mediaRange="1061-258684" indexRange="1061-1332"/>
      <SegmentURL mediaRange="258685-726301" indexRange="258685-258956"/>
      <SegmentURL mediaRange="726302-1216364" indexRange="726302-726573"/>
      <SegmentURL mediaRange="1216365-1877332" indexRange="1216365-1216636"/>
      <SegmentURL mediaRange="1877333-2364205" indexRange="1877333-1877604"/>
      <SegmentURL mediaRange="2364206-2696636" indexRange="2364206-2364477"/>
      <SegmentURL mediaRange="2696637-3022175" indexRange="2696637-2696908"/>
...
`
- What actually happened?

I get the below message in the developer console

> We do not support the SegmentURL@indexRange attribute on SegmentList.  We only use the SegmentList@duration attribute or SegmentTimeline, which must be accurate.

Is there plan to support SegmentURL

Thanks & Regards
Sunil

**Comment by TheModMaker** [comment]
We have no plans to support `indexRange`.  This feature would require a large number of extra network requests just to get info about segment times.  Having this defies the point of a manifest, the manifest should contain the times of the segments so we don't have to download every segment first.  If you want to encode segment times in the container, you should be using `SegmentBase`.

Note that we do support `SegmentURL`, but we don't support the `indexRange` attribute.  We only support `SegmentURL` when it is used with the `duration` attribute or `SegmentTimeline`.  This allows us to get the segment times from the manifest.

I know that GPAC uses `indexRange`, but usually the `duration` is accurate.

**Comment by joeyparrish** [comment]
Since we have no plans to support this feature at this time, I'm marking this as "will not implement" and closing.  If you feel strongly about it, please let us know and we can discuss further.
