### ISSUE TITLE
Missing Audio Segment in Video Stream

### ISSUE THREAD

**Issue by hghazzi** [google/shaka-player#766]
- What version of Shaka Player are you using? 
2.0.7

- Can you reproduce the issue with our latest release version?
- Can you reproduce the issue with the latest code from `master`?
Can't reproduce in demo page since its a DRM stream with custom data.

- What browser and OS are you using?
Chrome/Mac

- What did you do?
I try playing the stream. It has 310 video chunks but only 309 audio chunks. A console 404 occurs trying to access the 310th audio chunk. Screenshot attached.

Can't share the stream but here are the snippets `AdaptationSet` elements with `SegmentTemplate`.

```
<Period id="0" start="PT0.0S">
    <AdaptationSet id="0" group="1" mimeType="video/mp4" maxWidth="1920" maxHeight="1080" par="16:9" frameRate="25" segmentAlignment="true" startWithSAP="1" subsegmentAlignment="true" subsegmentStartsWithSAP="1">
         ....
        <SegmentTemplate presentationTimeOffset="0" timescale="90000" duration="720000" startNumber="1" media="chunk_ctvideo_rid$RepresentationID$_cn$Number$_mpd.m4s" initialization="chunk_ctvideo_rid$RepresentationID$_cinit_mpd.m4s"/>
        <Representation id="p0va0br8000000" codecs="avc1.640028" width="1920" height="1080" sar="1:1" bandwidth="8000000" />
        <Representation id="p0va0br6499968" codecs="avc1.640028" width="1920" height="1080" sar="1:1" bandwidth="6499968" />
        <Representation id="p0va0br3600000" codecs="avc1.4d401f" width="1280" height="720" sar="1:1" bandwidth="3600000" />
        <Representation id="p0va0br2200000" codecs="avc1.4d401f" width="1024" height="576" sar="1:1" bandwidth="2200000" />
        <Representation id="p0va0br1800000" codecs="avc1.4d401f" width="960" height="540" sar="1:1" bandwidth="1800000" />
        <Representation id="p0va0br899968" codecs="avc1.4d401e" width="640" height="360" sar="1:1" bandwidth="899968" />
        <Representation id="p0va0br499968" codecs="avc1.4d4015" width="480" height="270" sar="1:1" bandwidth="499968" />
        <Representation id="p0va0br168000" codecs="avc1.4d400d" width="416" height="234" sar="1:1" bandwidth="168000" />
    </AdaptationSet>
    <AdaptationSet id="1" group="2" mimeType="audio/mp4" lang="eng" segmentAlignment="true" startWithSAP="1" subsegmentAlignment="true" subsegmentStartsWithSAP="1">
        <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
         .....
        <SegmentTemplate presentationTimeOffset="0" timescale="90000" duration="720000" startNumber="1" media="chunk_ctaudio_rid$RepresentationID$_cn$Number$_mpd.m4s" initialization="chunk_ctaudio_rid$RepresentationID$_cinit_mpd.m4s"/>
        <Representation id="p0aa0br95996" codecs="mp4a.40.2" audioSamplingRate="48000" bandwidth="95996">
        </Representation>
        <Representation id="p0aa0br63997" codecs="mp4a.40.2" audioSamplingRate="48000" bandwidth="63997">
        </Representation>
    </AdaptationSet>
</Period>
```
![chrome](https://cloud.githubusercontent.com/assets/584053/25495538/76ffdcca-2b4b-11e7-834d-49f497dfbc50.png)

Does shaka player handle a stream where there is a missing audio chunk?

**Comment by TheModMaker** [comment]
The manifest says that there are the same number of segments in the audio and video streams.  We have no way of telling that those audio segments don't exist.  When we get a 404 from the server, we can't know why it doesn't exist.  For example, in live streams, if the clock isn't synchronized correctly, we may request a segment before it is created, meaning we can't always trust a 404.  For VOD, a 404 from the server should be an error and we should propagate it, not hide it.

This manifest is bad.  It should only describe the segments that exist.  One option would be to change the `mediaPresentationDuration` or the `Period@duration` to remove the last video segments.  Since the last video segment won't be played by the browser since there isn't any audio data available.

**Comment by hghazzi** [comment]
Thanks for the info, gonna close the issue
