### ISSUE TITLE
Request to expose audio track role

### ISSUE THREAD

**Issue by forbesjo** [google/shaka-player#767]
This is a enhancement request for exposing an audio track's role in order to differentiate between a main English track and commentary (or any other role type that can share a language).

**Comment by ismena** [comment]
I think we can do that! Let me tentatively schedule it for 2.2 (tentatively in case our project visionaries don't approve :)).

Please note, that we don't have separate audio/video tracks anymore. Instead we have variant tracks which represent audio+video combinations. (This was introduced in 2.1 release which just went out).

**Comment by forbesjo** [comment]
Yep, I've taken that into account in the Shaka/dash.js compatible video.js plugin I'm working on

**Comment by tdaines** [comment]
+1 for this.  Will `getAudioLanguages()` and `setAudioLanguage()` also be modified so that an English commentary track can be selected when the main track is English as well?

**Comment by joeyparrish** [comment]
I don't see why not.  We'll do that, as well.

**Comment by tdaines** [comment]
Great thanks.  If you prefer that to be in a separate issue I'm happy to make a new one.

**Comment by joeyparrish** [comment]
No, I think we can do that here.

**Comment by tdaines** [comment]
@joeyparrish How do see audio track role coexisting with the label attribute being added by PR #811?

**Comment by joeyparrish** [comment]
There can only be one label (one `label` attribute in DASH, one `NAME` attribute in HLS).  There can be multiple roles in DASH, so the exposed role information will be an array.

Both accomplish similar goals.  Whichever is used by your content/encoder, we will expose the information so that your application can use it to make decisions.

**Comment by joeyparrish** [comment]
The first part of this fix has been cherry-picked to v2.1.3.
