### ISSUE TITLE
HLS Manifest is not detected

### ISSUE THREAD

**Issue by boredom2** [google/shaka-player#769]
- What version of Shaka Player are you using?
2.1.0

  - Can you reproduce the issue with our latest release version?
yes

  - Can you reproduce the issue with the latest code from `master`?
didnt try

- Are you using the demo app or your own custom app?
both

  - If custom app, can you reproduce the issue using our demo app?
yes

- What browser and OS are you using?
Safari 10, MacOS 10.12.4

- What did you do?
Testing HLS with our Azure CDN, which is able to playout HLS

  - What content did you load?
Example Manifest: https://nx-p01.akamaized.net/61e63a61-8a6a-4091-af4a-986888892f2b/85188_src.ism/Manifest(format=m3u8-aapl);

    - If standard demo asset, which one?

    - If custom asset, what manifest and license server URIs?

  - How did you interact with the content, if at all?
Nothing is played

- What did you expect to happen?
The Manifest gets accepted and played (like Safari itself does)

- What actually happened?
DASH ERROR occured - MANIFEST.UNABLE_TO_GUESS_MANIFEST_TYPE
I agree, that this is a rather ununsual File Extension in the URL :P, but the Content Type, submitted by the CDN seems to be correct, thats why its unclear for me, why this Manifest could not get identified?

**Comment by ismena** [comment]
Hi @boredom2,
The extension of the file is "application/vnd.apple.mpegurl", and our parser didn't recognize it as HLS. (That's the first time I see the extension like this as well :)).
Let me try adding it to HLS extensions and see how it goes.

**Comment by ismena** [comment]
Okay, so registering it as HLS helps, but then the parser starts getting trouble with guessing the mime type of the media playlists. It will take a bit of time to figure out how to approach this best, but we're on it!

**Comment by boredom2** [comment]
Thanks for looking into this. Thats the default HLS Output from Microsoft Azure Media Services - who would have thought, that they make it so difficult :)

**Comment by ismena** [comment]
Okay, it should work now.
Please note that the manifest lacks some other info as well (they don't provide language info for audio, for example, so the tracks will have language set to undefined ('und')).

**Comment by boredom2** [comment]
Thanks!

**Comment by joeyparrish** [comment]
This is being cherry-picked to v2.1.1.

**Comment by geniusq1981** [comment]
is this bug fixed in 2.3.0? but I still meet same error for some URL : "Unable to guess manifest type by file extension or by MIME type. undefined application/vnd.apple.mpegurl;charset=utf-8"

**Comment by joeyparrish** [comment]
@geniusq1981, this was fixed in v2.1.1 and v2.2.0 back in May.  If you are having issues with the latest release, please file a new issue and provide a content URL so that we can reproduce the issue.  If you cannot provide a manifest URL publicly, the issue template contains an email address where you can send the link privately, in addition to your public bug report.  Thanks!
