### ISSUE TITLE
Please provide functionality for choosing specific codecs from stream for hardware acceleration.

### ISSUE THREAD

**Issue by Rtizer-9** [google/shaka-player#7705]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

Yes

**Is your feature request related to a problem? Please describe.**

Hardware acceleration, that's what this is about. 

At present we don't have control over which codec can we play from a stream (h264,vp9,av1) even if that stream does indeed provide that codec apart from others available and in this situation the streaming service controls whichever codec they use from their own convenience point of view which more often than not result in a non-hardware accelerated codec resulting in high CPU usage and other resources consumption.

Currently as you already know, only latest hardware has hardware acceleration support for av1 which is specifically the codec youtube and some other platforms are prioritising more and more over other codecs.

**Describe the solution you'd like**

If Shaka can provide functionality for letting users choose which codec to play then we'll be able to choose the one which has hardware acceleration support on our specific hardware resulting in huge power saving from huge resource consumption. I did read in a codec related issue that web player like Shaka can only choose a certain functionality only when it's there in first place; here it's a case of functionlity being there (vp9,h264) and giving users control to choose it over something else (av1). 

**Describe alternatives you've considered**

NA

**Additional context**

Addons like [Not yet av1](https://github.com/Shimmermare/NotYetAV1) and h264ify and enhancedh264ify already provide such functionality in both chrome and firefox as you already know and from what I recall from Shaka's documentation, forcing a codec selection like this would be much more easier for Shaka.

**Are you planning send a PR to add it?**

No

**Comment by absidue** [comment]
@tykus160 shaka-player already lets you configure that it should choose smooth and power efficient streams, via the `preferredDecodingAttributes` setting.

**Comment by tykus160** [comment]
LOL on me then 😅
