### ISSUE TITLE
Allow using JavaScript Object manifest

### ISSUE THREAD

**Issue by raeesbhatti** [google/shaka-player#772]
As I understand it, right now you have to provide a manifest URL to `Player.load` to setup the player. But is there a way to provide manifest programmatically as a JavaScript object created from JSON?

I receive configuration information about the media in JSON format (can't get it in `mpd`), so, I was thinking if I could create manifest object from the JSON and pass it directly to the player.

**Comment by vaage** [comment]
Hello @raeesbhatti, If I understand you correctly, you have a JSON object that you want to convert to a manifest for Shaka Player to use. We do support custom manifest parsers, which I think would solve your problem. Have you looked at our tutorial on how to make your own manifest parser (https://github.com/google/shaka-player/blob/master/docs/tutorials/manifest-parser.md)?

**Comment by raeesbhatti** [comment]
Thank you @vaage, I think this is exactly what was needed. I'll look into it.
