### ISSUE TITLE
Angular shaka-player.compiled.js unresolved variable polyfill and Player

### ISSUE THREAD

**Issue by codegastudio** [google/shaka-player#773]
Hello,

Shaka Player version 2.1.0
Custom app (angular 4.0.3, angular-cli 1.0.0-beta.28.3)
Demo app run on local web server 

`python -V`
> Python 2.7.10

`java -version`
> java version "1.8.0_31"
> Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
> Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)

```
npm install shake-player --save
python build/all.py 
```
> fatal: No names found, cannot describe anything.
> npm ERR! code 1
> 184 files checked, no errors found.
> Scanned 3 files, no errors found (31 ms).
> Checking that the build files are complete...
> Checking the tests for type errors...
> Compiling the library...

mycustom.component.ts in my angular project
```
import shaka from "shaka-player/dist/shaka-player.compiled.js";
...
@ViewChild('video') videoRef: ElementRef;
...
constructor() {
    console.log(shaka);
}
...
ngOnInit() {
    shaka.polyfill.installAll();

    // Check to see if the browser supports the basic APIs Shaka needs.
    if (shaka.Player.isBrowserSupported()) {
      // Everything looks good!
    } else {
      // This browser does not have the minimum set of APIs we need.
      console.error('Browser not supported!');
    }
  }
...
```

`shaka.polyfill` is not defined like `shaka.Player`
`console.log(shaka);` in constructor display an empty object.
Same issue with ` import * as shaka from "shaka-player/dist/shaka-player.compiled.js";`

With ` import shaka from "shaka-player";` or `import * as shaka from "shaka-player";` `polyfill` is recognized as variable of shaka in editor but is undefined on load and `shaka.polyfill.installAll()` fail.
`shaka.Player` still Unresolved.

Any help is welcome

Regards

**Comment by joeyparrish** [comment]
@codegastudio, we don't have any experience with Angular or TypeScript, so I'm not sure how that "import" statement works.  It's likely that we don't have support for that loading mechanism in our wrapper.  See [build/wrapper.template.js](https://github.com/google/shaka-player/blob/master/build/wrapper.template.js) for the current wrapper mechanism, which supports CommonJS and AMD loaders.

I'm going to tentatively mark this as "enhancement" to support this type of import, but again, I don't know what's involved yet.

**Comment by joeyparrish** [comment]
I've been looking at TypeScript a bit.  Can you try this?

```ts
import * as shaka from "./shaka-player.compiled.js"
shaka.polyfill.installAll();
```

**Comment by codegastudio** [comment]
This working like that
```
import * as shaka from "shaka-player";
...
shaka.polyfill.installAll();
```
I think than i had a cache problem the previous time :/
Thx @joeyparrish
