### ISSUE TITLE
Playready Content with mixed segment (having both encrypted and unencrypted segments) is not playing in Shaka Player Demo App

### ISSUE THREAD

**Issue by rajlaxmi28** [google/shaka-player#775]
- What version of Shaka Player are you using?
Shaka Player v2.0.0-debug
  - Can you reproduce the issue with our latest release version?
Yes
  - Can you reproduce the issue with the latest code from `master`?
Yes
- Are you using the demo app or your own custom app?
Demo
  - If custom app, can you reproduce the issue using our demo app?

- What browser and OS are you using?
Browser - IE11,  Microsoft Edge
OS - Windows10

- What did you do?
I created two contents having first few segments encrypted followed by few unencrypted segments followed by encrypted segments.

case 1) Content having two boxes under stsd in init segment: one for encrypted and other for unencrypted playback. In media segment, it has "Sample Description Index" set to 2 for unencrypted segments.

case 2) Same Content as above but having sgpd with 0 iv size and kid info & sbgp boxes for unencrypted content.

I tried to play both contents in Shaka player for both Widevine and Playready DRM. Content is playing fine for Widevine DRM but for Playready it is not playing instead giving MEDIA.VIDEO_ERROR. 

![image1](https://cloud.githubusercontent.com/assets/25498535/25664374/0eefec82-3038-11e7-8d1a-0f01cb3e6ee2.png)

![consolelog](https://cloud.githubusercontent.com/assets/25498535/25664371/0d5aeec6-3038-11e7-9c27-7e9413b76e1b.png)

![networklog](https://cloud.githubusercontent.com/assets/25498535/25664370/0d560546-3038-11e7-9fcd-c29da7fb8a5a.png)

  - What content did you load?
Custom
    - If standard demo asset, which one?

    - If custom asset, what manifest and license server URIs?
Manifest:
http://115.119.242.24/mm/dash/vod/flr/test1/VODSERVICE_1234/TG_TEST_SD.mpd (Case 1)
http://115.119.242.24/mm/dash/vod/flr/test/VODSERVICE_1234/TG_TEST_SD.mpd (Case 2)

License Server URL:
http://115.119.242.24/drmclientproxy/playready/get_license

  - How did you interact with the content, if at all?
This content i created locally and using local server for getting license.

- What did you expect to happen?
I expected playback to happen

- What actually happened?
Content is playing fine for first few encrypted segments and when unencrypted segment is about to play, giving  MEDIA.VIDEO_ERROR.

This same contents are playing fine for Widevine. Please suggest me if i am missing something for Playready DRM?

**Comment by sivarajendranaidu** [comment]
Please find the License Server URL for Playready:
http://115.119.242.24/drmclientproxy/playready/get_license

**Comment by joeyparrish** [comment]
@rajlaxmi28, @sivarajendranaidu, do you have a license server URL for Widevine as well?  It might be useful to compare working vs non-working playback on the same content.

It seems that some part of this content might be incompatible with either PlayReady or the media stack in Edge.  I'm not sure if they support "clear lead" content or not, and I'm not sure where they would have that documented.  I recommend that you [file a ticket with Microsoft](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/) about this.  If you do, please link to it here so we can follow along.

Here's a link to the demo with your URLs pre-filled: [https://shaka-player-demo.appspot.com/demo/#asset=//115.119.242.24/mm/dash/vod/flr/test1/VODSERVICE_1234/TG_TEST_SD.mpd;license=//115.119.242.24/drmclientproxy/playready/get_license](https://shaka-player-demo.appspot.com/demo/#asset=//115.119.242.24/mm/dash/vod/flr/test1/VODSERVICE_1234/TG_TEST_SD.mpd;license=//115.119.242.24/drmclientproxy/playready/get_license)

Note, though, that your links are plain HTTP, and will not be accessible to an app running on HTTPS.  You will want to run an SSL-enabled service on port 443 before sending the above link in a Microsoft ticket.

**Comment by sivarajendranaidu** [comment]
@joeyparrish thanks a lot your support. With reference https://github.com/Dash-Industry-Forum/dash.js/issues/1615 this issue seams to with Edge Browser. Once we update the Windows (Edge Browser > 38) it worked well with our Shaka Player.
Hence its not our player issue

**Comment by joeyparrish** [comment]
Okay.  Seems to be fixed in EdgeHTML 14, so I'm going to close it now.  Thanks for the report!
