### ISSUE TITLE
build/all.py pollutes root folder on Windows

### ISSUE THREAD

**Issue by Ross-cz** [google/shaka-player#776]
- What version of Shaka Player are you using?
latest master (bf1c829eec1b7c057900dd9e80bb73ef685d1163)

- What browser and OS are you using?
Windows, npm 4.5.0

- What did you do?
`python build/all.py`

- What did you expect to happen?
git status clean report

- What actually happened?
Untracked / unignored files were created:
```
c:\git\shaka-player-repo>git status
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        esparse
        esparse.cmd
        esvalidate
        esvalidate.cmd
        htmlhint
        htmlhint.cmd
        in-install
        in-install.cmd
        in-publish
        in-publish.cmd
        karma
        karma.cmd
        not-in-install
        not-in-install.cmd
        not-in-publish
        not-in-publish.cmd
        r.js
        r.js.cmd
        r_js
        r_js.cmd
        rimraf
        rimraf.cmd

nothing added to commit but untracked files present (use "git add" to track)
```

**Comment by joeyparrish** [comment]
This is certainly not intentional.  We don't get the same behavior on Linux, but we'll try to reproduce on Windows.

**Comment by joeyparrish** [comment]
I tested on Windows 10 with npm 3.10.3, in a clean checkout at rev 0698987836bb68d0e35377ae9be8d3bcb8d4f492.

I find that `npm install` run manually does not pollute the folder with node bin files.

However, if I wipe out node_modules and run `python build/all.py`, letting it run `npm install` for me, I can reproduce the pollution:

```
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        esparse
        esparse.cmd
        esvalidate
        esvalidate.cmd
        htmlhint
        htmlhint.cmd
        in-install
        in-install.cmd
        in-publish
        in-publish.cmd
        karma
        karma.cmd
        not-in-install
        not-in-install.cmd
        not-in-publish
        not-in-publish.cmd
        r.js
        r.js.cmd
        r_js
        r_js.cmd
        rimraf
        rimraf.cmd

nothing added to commit but untracked files present (use "git add" to track)
```

There must be something we're doing wrong.  We'll investigate further.

**Comment by Ross-cz** [comment]
Thanks Joey. I don't keen on the fix. There is probably some incompatibility with cygwin used by python on the Windows.

Maybe the community can help and rework python scripts to full nodejs project?

**Comment by joeyparrish** [comment]
I don't think we're interested in moving the build scripts to nodejs at this time.  We use python in our test lab infrastructure, so it is useful for us to be able to import those build scripts as part of our automation.

**Comment by joeyparrish** [comment]
With npm v3.10.3:

`npm.cmd update` **does not** pollute the root folder.
`npm.cmd --prefix C:/cygwin64/home/user/shaka-player update` **does** pollute the root folder.
`npm.cmd --prefix . update` **does** pollute the root folder.

Since npm behaves differently on other platforms, and the behavior is specific to `--prefix` it seems to be a bug in `npm --prefix` on Windows.

**Comment by joeyparrish** [comment]
I filed npm/npm#17027 to fix the behavior of `--prefix`.  In the mean time, we may be able to work around it.
