### ISSUE TITLE
timelineregion* events do not include Event element

### ISSUE THREAD

**Issue by davemt** [google/shaka-player#779]
- What version of Shaka Player are you using?
latest master (@0698987)

- Are you using the demo app or your own custom app?
demo app

- What browser and OS are you using?
Firefox 52.0.2 on OSX

- What did you do?

  - What content did you load?
A custom (internal) asset with `<EventStream>` in the manifest. 

  - How did you interact with the content, if at all?
Added Added listeners for the `timelineregion*` events and examined event detail.

- What did you expect to happen?
The `event.detail.eventElement` should have been populated with an `Element` corresponding to `<EventStream>`>`<Event>`.

- What actually happened?
Blank `Object` in its place (method of copying `TimelineRegionInfo` does not include it).

I can submit a PR with a fix for this issue.

**Comment by joeyparrish** [comment]
Cherry-picked to v2.1.1.
