### ISSUE TITLE
Add support to the demo app for playing back assets from Verizon Digital Media

### ISSUE THREAD

**Issue by TheJohnBowers** [google/shaka-player#780]
This is more of a feature request than a bug, so I won't go through all the reproduction steps that were in the template.

I would like to request that support for Verizon Digital Media Services (or Uplynk) streams be added to the demo application.  This would provide an example of what is needed to communicate with the VDMS license proxies and playback VDMS streams, as well as providing some samples of what VDMS streams should be expected to look like.

**Comment by joeyparrish** [comment]
Sounds good to me.  I will check out the PR.

**Comment by joeyparrish** [comment]
Cherry-picked to v2.1.1 and v2.0.9.
