### ISSUE TITLE
player.load doesn't work with custom manifest retryParameters

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#782]
- What version of Shaka Player are you using? v2.1.0

  - Can you reproduce the issue with our latest release version? Yes

  - Can you reproduce the issue with the latest code from `master`? Yes

- Are you using the demo app or your own custom app? Custom

  - If custom app, can you reproduce the issue using our demo app? Yes, if iIchange the setupAssetMetadata config.

- What browser and OS are you using? Chrome 58 - Ubuntu 17.04

- What did you do?
Use this config:

```
var config = /** @type {shakaExtern.PlayerConfiguration} */(
  {
    drm: {},
    manifest: {
      dash: {},
      retryParameters: {
        maxAttempts: 4,
        baseDelay: 1000,
        backoffFactor: 2,
        fuzzFactor: 0.5,
        timeout: 0
      }
    }
  }
```

I change maxAttempts to 4 (with 0, 1, 2 the error doesn't occur)

Load any url that returns 404 (https://storage.googleapis.com/shaka-demo-assets/sintel/dash1.mpd)
While the attemps happen, you need load another assets(that exists). Player.load does nothing

**Comment by joeyparrish** [comment]
This is more difficult to reproduce in the latest code.  We no longer continue to retry a manifest request on a 404 or 403 error.  It is easier to reproduce now by setting a large `maxAttempts` (like 1000) and a small `timeout` (like 1 ms).

It seems that you are right.  I'm not seeing any effect from player.load() while it is fetching a manifest.

**Comment by joeyparrish** [comment]
A note for whoever picks up this bug: It would be ideal to start by writing a new test that reproduces this bug, perhaps in the 'load/unload' section of test/player_unit.js.
