### ISSUE TITLE
trackschanged event being triggered twice

### ISSUE THREAD

**Issue by hghazzi** [google/shaka-player#783]
- What version of Shaka Player are you using? **2.1.0**
 - Can you reproduce the issue with our latest release version? **Yes**
 - Can you reproduce the issue with the latest code from `master`? **Yes**
 - Are you using the demo app or your own custom app? **Both**
 - If custom app, can you reproduce the issue using our demo app? **Yes**

- What browser and OS are you using? **MacOS/Chrome**
- What did you do? **Added a `trackschanged` event listener**
 - What content did you load? **Angel One demo asset**
 - How did you interact with the content, if at all? **Loaded demo asset**

- What did you expect to happen? **`trackschanged` event listeners should only be triggered once** 
- What actually happened? **`trackschanged` event listeners was triggered twice**

**Comment by hghazzi** [comment]
Thanks!

**Comment by joeyparrish** [comment]
I'm planning to cherry-pick this to v2.1.1.

**Comment by hghazzi** [comment]
Thanks, @joeyparrish and @TheModMaker

**Comment by joeyparrish** [comment]
Cherry-picked to v2.1.1.
