### ISSUE TITLE
Second call of player.configure fails

### ISSUE THREAD

**Issue by Ross-cz** [google/shaka-player#784]
- What version of Shaka Player are you using?
395cc1745e9c51f3c0b66dfc7d3f5eee545a7e74
  - Can you reproduce the issue with our latest release version?
y
  - Can you reproduce the issue with the latest code from `master`?
y

- Are you using the demo app or your own custom app?
y
  - If custom app, can you reproduce the issue using our demo app?
y

- What browser and OS are you using?
any

- What did you do?
Load configuration using pseudo script called twice using console:
`window.shakaDemo.localPlayer_.configure({"drm":{"advanced":{"com.widevine.alpha":{"serverCertificate":new Uint8Array(1)}}}})
`
- What did you expect to happen?
no exception

- What actually happened?
first call result: undefined
second call result:
Uncaught TypeError: Cannot read property '0' of null

**Comment by joeyparrish** [comment]
It is easy enough to fix the failure, but we will lose type-checking on the serverCertificate parameter.

Therefore I'm going to fix this in two parts:
1. Fix the immediate failure in a very simple way, which can be cherry-picked to v2.1.1.  "serverCertificate" will be treated like "abr.manager" in `ConfigUtils`, and we will copy it directly, as opposed to recursively.  This means, though, that we will not be checking its type.
2. Apply a more detailed fix that will only appear in v2.2.  When we refactor ABR configuration for #744, "abr.manager" will be removed from the configuration.  This will make it easier to clean up and fix config merging in a way that allows type-checking of serverCertificate as a Uint8Array.

Part 2 will only be merged after #744 is fixed.

**Comment by joeyparrish** [comment]
The first part of the fix has been cherry-picked to v2.1.1 and v2.0.9.  The type of the `serverCertificate` field will not be checked by `configure()`.  Type-checking will be fixed in v2.2.0, as it depends on some refactoring in-progress.
