### ISSUE TITLE
Firefox: Prevent request with unsupported Widevine DRM robustness

### ISSUE THREAD

**Issue by Ross-cz** [google/shaka-player#786]
- What version of Shaka Player are you using?
2.1.0-debug

- Are you using the demo app or your own custom app?
d

- What browser and OS are you using?
Firefox 53.0.2 (32 bit), Windows

- What did you do?
Set Widevine DRM robustness to prevent console logs inside Chrome.
  - What content did you load?
Ange One (widevine)

  - How did you interact with the content, if at all?
Patch defaultConfiguration before clicking Load.

- What did you expect to happen?
Content playback with warning: unsupported drm configuration for SW_SECURE_CRYPTO.

- What actually happened?
Error: Shaka Error DRM.REQUESTED_KEY_SYSTEM_CONFIG_UNAVAILABLE ()
(undocumented: https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html#value:6001)

Patch script with set .drm.advanced.com.widevine.alpha:
```
shaka.Player.prototype.defaultConfig_ = function() {
  return {
    drm: {
      retryParameters: shaka.net.NetworkingEngine.defaultRetryParameters(),
      // These will all be verified by special cases in mergeConfigObjects_():
      servers: {},    // key is arbitrary key system ID, value must be string
      clearKeys: {},  // key is arbitrary key system ID, value must be string
      advanced: { 'com.widevine.alpha': { audioRobustness: "SW_SECURE_CRYPTO", videoRobustness: "SW_SECURE_CRYPTO" } },    // key is arbitrary key system ID, value is a record type
      delayLicenseRequestUntilPlayed: false
    },
    manifest: {
      retryParameters: shaka.net.NetworkingEngine.defaultRetryParameters(),
      dash: {
        customScheme: function(node) {
          // Reference node to keep closure from removing it.
          // If the argument is removed, it breaks our function length check
          // in mergeConfigObjects_().
          // TODO: Find a better solution if possible.
          // NOTE: Chrome App Content Security Policy prohibits usage of new
          // Function()

          if (node) return null;
        },
        clockSyncUri: '',
        processPeriodAdaptationSetNodes: function(sets) { return sets; },
        ignoreDrmInfo: false
      },
      hls: {
        defaultTimeOffset: 0
      }
    },
    streaming: {
      retryParameters: shaka.net.NetworkingEngine.defaultRetryParameters(),
      rebufferingGoal: 2,
      bufferingGoal: 10,
      bufferBehind: 30,
      ignoreTextStreamFailures: false,
      startAtSegmentBoundary: false,
      smallGapLimit: 0.5,
      jumpLargeGaps: false
    },
    abr: {
      manager: this.defaultAbrManager_,
      enabled: true,
      defaultBandwidthEstimate:
          shaka.abr.EwmaBandwidthEstimator.DEFAULT_ESTIMATE,
      restrictions: {
        minWidth: 0,
        maxWidth: Infinity,
        minHeight: 0,
        maxHeight: Infinity,
        minPixels: 0,
        maxPixels: Infinity,
        minBandwidth: 0,
        maxBandwidth: Infinity
      }
    },
    preferredAudioLanguage: '',
    preferredTextLanguage: '',
    restrictions: {
      minWidth: 0,
      maxWidth: Infinity,
      minHeight: 0,
      maxHeight: Infinity,
      minPixels: 0,
      maxPixels: Infinity,
      minBandwidth: 0,
      maxBandwidth: Infinity
    }
  };
};
```

**Comment by TheModMaker** [comment]
I don't understand your feature request.  Are you asking to suppress the unsupported error?

The current behavior is correct to throw an error.  The browser doesn't support the given robustness value.  Since you passed it in, we assume your assets require it, so we assume that the browser won't be able to play the asset.  A robustness level is treated like any other configuration; similarly, if you set `persistentStateRequired` and the browser doesn't support it, then we throw an error.

**Comment by Ross-cz** [comment]
I don't understand logical difference between SW_SECURE_CRYPTO and not specifing/throwing error. I thought this is the default on desktops.
I don't understand why I have to maintain non-understandable compatibility issues between Chrome and Firefox Widevine DRM modules.

I would expect better support for errors being produced by Widevine DRM / Shaka combination because of same company and possible NDA knowledge sharing. This is Widevine DRM demo player, isn't it?

Do we need to see this Chrome warning?
drm_engine.js:552 It is recommended that a robustness level be specified. Not specifying the robustness level could result in unexpected behavior, potentially including failure to play.

**Comment by joeyparrish** [comment]
Not specifying a robustness should be equivalent to the lowest robustness level, as I understand it.  It is possible that Widevine robustness values are not supported in Firefox yet, in which case someone should file a bug against Firefox.

The Widevine CDM should (ideally) work the same on Chrome and Firefox, but Mozilla is responsible for the EME implementation that sits between the CDM and the JavaScript application.  Robustness strings must be checked at that level, before the CDM is instantiated.

The Chrome warning about robustness is produced by Chrome itself, and is outside the control of Shaka Player (or any JS app).  As I understand it, that warning was added at a time when EME was considering making robustness required.  The spec as it stands today states of `robustness`:

> The empty string indicates that any ability to decrypt and decode the content type is acceptable.

Based on that spec text, I believe it is safe to ignore the warning.

**Comment by cpeterso** [comment]
Firefox has code to support `audioRobustness: "SW_SECURE_CRYPTO"` and `videoRobustness: "SW_SECURE_DECODE"` (not `SW_SECURE_CRYPTO` here).

@cpearce, is that correct? I see Firefox has code to check for these robustness strings but no tests.

**Comment by joeyparrish** [comment]
Since the Chrome warning is what led us here, I proposed removal of the misleading robustness warning in Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=720013

**Comment by cpearce** [comment]
Firefox doesn't recognize "SW_SECURE_CRYPTO" with video; it assumes you'll always want "SW_SECURE_DECODE". I didn't realize Chrome accepted both when I implemented Firefox's support. I'll add "SW_SECURE_CRYPTO" to the list of robustness values that Firefox recognizes for video.

**Comment by cpeterso** [comment]
cpearce filed [Firefox bug 1363605](https://bugzil.la/1363605) to support `SW_SECURE_CRYPTO`.

**Comment by cpearce** [comment]
Patch up in Firefox [bug 1363605](https://bugzil.la/1363605). I expect we'll ship this fix in Firefox 55 around 2017-08-08.

**Comment by Ross-cz** [comment]
Thank you guys for your great support. Managers will be happy.

I did sample robustness capability test for SW_SECURE_CRYPTO:
```
var config = null, widevineOptions = [
 { label: 'foo', // For debugging and/or identifying the selected config.
 initDataTypes: ['cenc', 'webm'],
 sessionTypes: ['temporary'],
 audioCapabilities: [
 // Preferred codec.
 { contentType: 'audio/mp4; codecs="mp4a.40.5"',
 robustness: 'SW_SECURE_CRYPTO'
 },
 // Next most-preferred codec.
 { contentType: 'audio/mp4; codecs="mp4a.40.2"',
 robustness: 'SW_SECURE_CRYPTO'
 },
 // Least preferred codec.
 { contentType: 'audio/webm; codecs="vorbis"',
 robustness: 'SW_SECURE_CRYPTO'
 },
 ],
 videoCapabilities: [
 // Preferred codec.
 { contentType: 'video/webm; codecs="vp9"',
 robustness: 'HW_SECURE_ALL'
 },
 { contentType: 'video/webm; codecs="vp9"',
 robustness: 'SW_SECURE_CRYPTO'
 },
 // Next most-preferred codec.
 { contentType: 'video/mp4; codecs="avc1.640028"', // high profile
 robustness: 'HW_SECURE_ALL'
 },
 { contentType: 'video/mp4; codecs="avc1.640028"',
 robustness: 'SW_SECURE_CRYPTO'
 },
 // Least preferred codec.
 { contentType: 'video/mp4; codecs="avc1.4d401e"', // main profile
 robustness: 'HW_SECURE_ALL'
 },
 { contentType: 'video/mp4; codecs="avc1.4d401e"',
 robustness: 'SW_SECURE_CRYPTO'
 },
 ],
 }
];
navigator.requestMediaKeySystemAccess(
 'com.widevine.alpha', widevineOptions)
 .then(function(result) {
 keySystemAccess = result;
 config = keySystemAccess.getConfiguration();
 console.log(config);
 });
```
Chrome: supports - "{"audioCapabilities":[{"contentType":"audio/mp4; codecs=\"mp4a.40.5\"","robustness":"SW_SECURE_CRYPTO"},{"contentType":"audio/mp4; codecs=\"mp4a.40.2\"","robustness":"SW_SECURE_CRYPTO"},{"contentType":"audio/webm; codecs=\"vorbis\"","robustness":"SW_SECURE_CRYPTO"}],"distinctiveIdentifier":"not-allowed","initDataTypes":["cenc","webm"],"label":"foo","persistentState":"not-allowed","sessionTypes":["temporary"],"videoCapabilities":[{"contentType":"video/webm; codecs=\"vp9\"","robustness":"SW_SECURE_CRYPTO"},{"contentType":"video/mp4; codecs=\"avc1.640028\"","robustness":"SW_SECURE_CRYPTO"},{"contentType":"video/mp4; codecs=\"avc1.4d401e\"","robustness":"SW_SECURE_CRYPTO"}]}"

Firefox: stucked at promise pending

**Comment by Ross-cz** [comment]
@cpearce Can you check my test inside last comment? It seems there is another bug inside Firefox, where it is stucked at promise pending when I query supported DRM robustness.

**Comment by cpearce** [comment]
@Ross-cz The fix to make Firefox support SW_SECURE_CRYPTO on video configurations is only in Firefox Nightly, it's not in Release or Beta Firefox yet.

With your test I get 5 supported configurations in Firefox Nightly 55, which will ship to our Release users on around 8 August.

If you replaced SW_SECURE_CRYPTO with SW_SECURE_DECODE on the video configs, you'd find it worked in both Chrome and Firefox.

**Comment by joeyparrish** [comment]
Firefox 55 is now the stable release.
