### ISSUE TITLE
IE11: fullscreen button disappears

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#787]
- What version of Shaka Player are you using?  *v2.1.0 and nightly*
- Are you using the demo app or your own custom app? *demo app*
- What browser and OS are you using? *IE11 on Windows 10*
- What did you do?

1. Click "load"
2. Try to go fullscreen

- What actually happened?

The fullscreen button is missing from the controls UI.

Manual inspection of the DOM reveals `<div id="controls" class="casting">`.  After clicking "load", the player starts thinking we are in casting mode, and CSS hides the fullscreen button.  It is still present before "load".

**Comment by michellezhuogg** [comment]
The root cause:
IE11 doesn't support the second parameter of toggle() method. 
https://github.com/google/shaka-player/blob/master/demo/controls.js#L553
http://caniuse.com/#search=classList

**Comment by joeyparrish** [comment]
The fix for this has been cherry-picked and will be released in v2.1.5.
