### ISSUE TITLE
Add option to not error on invalid XLink.

### ISSUE THREAD

**Issue by theodab** [google/shaka-player#788]
Refactor the xlink parser so there's the option of not replacing the period on error, or if there's nothing loaded.
I.E. so there can be a default placeholder advertisement if no advertisements load.
The DASH IOP mentions default content for periods with xlink links, which suggests this is the intended behavior.

**Comment by jide** [comment]
Hi,

According to changelog https://github.com/google/shaka-player/blob/master/CHANGELOG.md, a basic support for xlink has been implemented.

It references this issue, #587, but the mpd uri provided as an example there does not work, although it only uses `xlink:actuate="onLoad"`.

Any idea why ?

**Comment by joeyparrish** [comment]
@jide, the manifest in question (http://dash.edgesuite.net/fokus/adinsertion-samples/xlink/threeperiods.mpd) has two periods with audio & video, and one period with only video.  So the error message (UNPLAYABLE_PERIOD) is accurate.  We cannot switch between periods in which audio/video are missing.  So if any one period has audio & video, all periods must have both audio & video for this to be playable in a continuous MediaSource presentation.

Here is a link to a working xlink demo in Shaka Player, using content with consistent content types across all three periods: https://shaka-player-demo.appspot.com/demo/#asset=//storage.googleapis.com/shaka-demo-assets/heliocentrism-xlink/heliocentrism.mpd;play

**Comment by jide** [comment]
@joeyparrish Oh, I see, not familiar with error messages yet. Awesome !
