### ISSUE TITLE
Unplayable live manifest

### ISSUE THREAD

**Issue by ut0mt8** [google/shaka-player#793]
With the last version of shaka-player demo 2.1.0 -debug I m unable to play this manifest.
https://ec2-52-56-93-145.eu-west-2.compute.amazonaws.com/app/live/index.mpd

(ok this is a self signed certificate, but I add as exception in Firefox, or add in the keychain /mac).

I'm wondering if something is wrong in my manifest (it work with bitmovin, dashjs) ?
The console sees the manifest loading ; but no segment are downloaded , and nothing else in the console...

Any idea?

**Comment by joeyparrish** [comment]
@ut0mt8, can you please provide some additional information so we can assess the problem?

- Can you reproduce the issue with our latest release version?
- Can you reproduce the issue with the latest code from `master`?
- Are you using the demo app or your own custom app?
  - If custom app, can you reproduce the issue using our demo app?
- What did you do?
  - How did you interact with the content, if at all?
- What did you expect to happen?
- What actually happened? (Please include error messages/codes)

**Comment by ut0mt8** [comment]
>Can you reproduce the issue with our latest release version?
Yep with v2.1.1-debug.

>Can you reproduce the issue with the latest code from master?
Not tested.

>Are you using the demo app or your own custom app?
Yep with the demo on your website.

>If custom app, can you reproduce the issue using our demo app?
N/A

>What did you do?
Testing my manifest :)

>How did you interact with the content, if at all?
N/A

>What did you expect to happen?
The video playing :)

>What actually happened? (Please include error messages/codes)
Nothing. The mpd is fetched, and seems to be reloaded.
But no chunk are downloaded, so ..
Nothing in the console..

**Comment by joeyparrish** [comment]
I'm sorry it took so long to get to this issue.  I tried your manifest and got a 404 error from your server.  Do you have an updated link for us?

**Comment by ut0mt8** [comment]
Sorry for the late response. The link should be ok now. I have to make it more stable; but this should be testable.

**Comment by joeyparrish** [comment]
Here's a short link for convenience while testing this content: https://nightly-dot-shaka-player-demo.appspot.com/demo/#asset=https://ec2-52-56-93-145.eu-west-2.compute.amazonaws.com/app/live/index.mpd

I'm getting a mixed-content error while trying to fetch your time sync file as specified by UTCTiming:

> Mixed Content: The page at 'https://nightly-dot-shaka-player-demo.appspot.com/demo/#asset=https://ec2-52-56-93-145.eu-west-2.compute.amazonaws.com/app/live/index.mpd;lang=de' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://52.56.93.145/static/time.txt'. This request has been blocked; the content must be served over HTTPS.

That's one thing you'll need to fix on your end.  You can't load an HTTP resource inside of an HTTPS page. (When I fetch the time sync file manually, the `Date` header seems to be accurate.)

Your segment references seem to disagree with your `availabilityStartTime` and `timeShiftBufferDepth` attributes.  This is the reason your content does not play.

At the time I fetched the manifest, according to `availabilityStartTime`, the presentation times available should have been 37,616 through 38,264 (seconds). `<SegmentTimeline>`, though, says the most recent segment was time 2,662,171 - 2,662,174 (seconds). This is an apparent desynchronization of 2,623,910 seconds, or about 30 days.  This is a suspiciously round number.  I would recommend you check the clock on your server or encoder.

What encoder are you using?  Have you checked for an update?

**Comment by ut0mt8** [comment]
Ok for the mixed content it's just a matter of configuration. I fix it.
I use my own fork of nginx-rtmp-module, but I don't change this part.

I can confirm is that the servers is ntp synchronized. 
The avaibilityStartTime is correct; the timeShiftBuffer also.

Live example : 

    availabilityStartTime="2017-06-13T14:57:27Z"
    publishTime="2017-06-13T14:57:27Z"
    minimumUpdatePeriod="PT3.600S"
    minBufferTime="PT2.000S"
    timeShiftBufferDepth="P0Y00M00DT0H01M30.000S"

First segment is : 
  "2717229792"  / 1000  (the timescale).
3 days, 3 hours, 28 minutes and 42 seconds.

I know this is the timestamp of the internal encoder (elemantal server). The video flux was restarted 3 day ago.

What puzzle me, is that the same mpd work fine on dashjs or bitmotvin. 
And it start at the right time. 
How it is supposed to be calculated ?

**Comment by ut0mt8** [comment]
Ah and testing with and old release of shaka (as http://emmy9.casa.umass.edu/shaka-player/ shaka-1.6.2) the flux is OK.  ?!

**Comment by joeyparrish** [comment]
Shaka Player v2 is more strict than v1 about the presentation timeline.  In v1, we tried to handle content which is out of spec, but this ultimately led to subtle bugs and difficulty in maintenance.

Your segment times do not agree with the presentation timeline.  I would be happy to help you with a report to Elemental.  Ultimately, this is a bug in their encoder.

**Comment by ut0mt8** [comment]
Bug in elemental or in nginx-rtmp.
Another manifest (https://ec2-52-56-93-145.eu-west-2.compute.amazonaws.com/dash/live_hi/index.mpd) on the same input flux but transcoded by ffmpeg is ok.

I have to dig on why elemental send these king of timestamp (which correspond to nothing, perhaps a TS coded in the SDI original flux ?).
And I have to dig on why nginx-rtmp in this case honor the ts in rtmp, while it start at zero with ffmepg rtmp flux (which it ok).

**Comment by ut0mt8** [comment]
I finally found was going wrong.

Elemental Live Server sending onFi amf event (with what is supposed a Timecode) which completely broke the timestamp gestion of nginx-rtmp.
Disabling sending onFi event and selecting "starting a 0" timecode start produce a correct timeline...

I will make Elemental a report ; I'm really curious what is this supposed timecode (because it correspond to nothing).

Anyway I think we can close this issue as It is nothing to do with shaka-player.

Thks.
