### ISSUE TITLE
False positives in demo audio-only asset detection.

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#794]
- What version of Shaka Player are you using?  **`master`**
- Are you using the demo app or your own custom app? **demo app**
- What browser and OS are you using? **Chrome on Mac**
- What did you do?

Load any asset.

- What actually happened?

The audio-only poster was briefly visible between clicking "load" and playback starting.

Could be a race between `load()` resolution and `getVariantTracks()`.

**Comment by theodab** [comment]
This is not actually be a race condition. Instead, it's an issue with the logic for detecting audio-only assets; we currently check if a track is video or audio by the presence of a 'width' variable, but the resolution attribute in HLS is optional so some manifests might not contain in. In such manifests, we are mis-identifying video streams as being audio.

**Comment by joeyparrish** [comment]
As discussed offline, let's use the newly-added `videoCodec` field of `Track` to identify variants with video.

**Comment by joeyparrish** [comment]
This fix was just released in v2.1.2.
