### ISSUE TITLE
appData: asset with two different manifestUris

### ISSUE THREAD

**Issue by jorgitoml** [google/shaka-player#800]
Hi, 
I've modified the lib cast_proxy.js to work with two different manifestUris...one for the web player and anotherone for the chromecast player.
Using the uncompiled version of shakaplayer all works fine, but when I try to compile the player I'm facing this error:

shaka-player-2.1.1/lib/cast/cast_proxy.js:210: ERROR - Property manifestUriCC never defined on appData.asset 
this._manifestUriCc_ = appData.asset.manifestUriCC;

Could you tell me where I must define this extra property for the asset?

Kind regards.

**Comment by TheModMaker** [comment]
If the goal is to play different videos on the Chromecast vs locally, why not do the following:

```js
var player = castProxy.getPlayer();
if (castProxy.isCasting())
  player.load(remoteManifestUri);
else
  player.load(localManifestUri);
```

My guess that line was added to `CastProxy.prototype.setAppData`, right?  The problem is the argument has a type of `Object`, so the compiler doesn't know what fields it has.  If you really want to do this, you can change the function comment line to be `@param {{asset: {manifestUriCC: string}}} appData`.

**Comment by jorgitoml** [comment]
Great!
Tx TheModMaker!

**Comment by jorgitoml** [comment]
I'm using this code to solve the previous problem: 

ShakaControls.prototype.onCastStatusChange_ = function(event) {

...

var aux_appData = shakaPlayer.appData;	
	if(aux_appData != null){
                var isCasting = this.castProxy_.isCasting();
		var player = this.castProxy_.getPlayer();
		var video = this.castProxy_.getVideo();
		if (isCasting){
			player.unload().then(function() {
				player.load(aux_appData.asset.manifestUriCC).then(function(){video.play();});
			});
		}else{
			player.unload().then(function() {
				player.load(aux_appData.asset.manifestUriLocal).then(function(){video.play();});
			});
		}
	}
};

But I'm getting this error when returning form chromecast to local:
![c97899480a](https://cloud.githubusercontent.com/assets/1795137/26122313/588b9528-3a77-11e7-8ee0-ed8f23f9c54a.png)


Could you tell me how to solve it?
Tx!

**Comment by TheModMaker** [comment]
Error 7000 is [LOAD_INTERRUPTED](https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html#value:7000).  What is happening is that when you disconnect the Chromecast, we will attempt to resume the playback locally by calling `localPlayer.load(manifestUri)`.  This happens before we raise the event.  Then in your listener, you call `player.load()`, which interrupts the previous load, causing the error.  But this error can be ignored, so long as your load() call is succeeding.

**Comment by jorgitoml** [comment]
Ok, tx!
