### ISSUE TITLE
Widevine changes in Chrome 59

### ISSUE THREAD

**Issue by hghazzi** [google/shaka-player#801]
With the changes to the widevine changes in Chrome 59, how will this affect shaka player? Do we need to always set a server certificate, and if not, what are the uses where it is required?

https://www.widevine.com/product_news.html

**Comment by joeyparrish** [comment]
You will never be required to set a certificate.  If you do not set one, the Widevine CDM will provision one automatically.  Setting one explicitly is an optimization to save you the extra round trip and the extra server traffic.

**Comment by hghazzi** [comment]
Thanks for the clarification!
