### ISSUE TITLE
6001 Error on Server but Works Fine with Localhost

### ISSUE THREAD

**Issue by jamescahall** [google/shaka-player#803]
- What version of Shaka Player are you using?

2.1.1

  - Can you reproduce the issue with our latest release version?

Yes

  - Can you reproduce the issue with the latest code from `master`?

Yes

- Are you using the demo app or your own custom app?

Custom app or demo app.  Both have same issue.

  - If custom app, can you reproduce the issue using our demo app?

Yes, if demo app is loaded on to our own server (tried multiple servers).  No, if demo app you've set up online used:
https://shaka-player-demo.appspot.com/demo/#asset=//storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd;lang=en-US

- What browser and OS are you using?

Chrome 58

- What did you do?

load: shaka-player.compiled.js
call:  shaka.polyfill.installAll();

`if (shaka.Player.isBrowserSupported() == true) {
this.drmPlayer = new shaka.Player(<object id="av-player" type="application/avplayer" style="width:100%; height:100%; position:absolute; top:0px; left; 0px;"></object>);
            var _this = this;
            configuration = {};
            var features = [];
            if (Content.currentContent.licenseURLs != null) {
                var servers = {};
                if (Content.currentContent.licenseURLs["widevine"] != null) {
                    servers["com.widevine.alpha"] = Content.currentContent.licenseURLs["widevine"];
                }
                if (Content.currentContent.licenseURLs["playready"] != null) {
                    servers["com.microsoft.playready"] = Content.currentContent.licenseURLs["playready"];
                }
                configuration["drm"] = { servers: servers };
            }
            if (features.length > 0) {
                configuration["features"] = features;
            }
            this.drmPlayer.configure(configuration);
            this.drmPlayer.load(primaryVideoUrl).then(function() {
            }).catch(function(error) {
                log("DRM Load Error: " + error.code);
            });
}`
  - What content did you load?

Own content but get same issue with your demo player on our servers.  Widevine options are unavailable.

    - If standard demo asset, which one?

Any DRM protected assets do not work outside of your online demo.

    - If custom asset, what manifest and license server URIs?

Cannot provide.

  - How did you interact with the content, if at all?

Implementation above.

- What did you expect to happen?

Play content.

- What actually happened?

When hosted on a server, getting 6001 error.  When loading from your demo player above, I can see Using native EME as-is.  When I use on our own server I see EME not available.  If I load from localhost, I see Using native EME as-is and works fine.

**Comment by joeyparrish** [comment]
EME requires https starting in Chrome 58.  Chrome makes an exception for localhost, since that is considered a "secure context".  For more information, see https://github.com/google/shaka-player/issues/736#issuecomment-289104405

Does this help?

**Comment by jamescahall** [comment]
Yes thanks.  That solves it.  Greatly appreciated.

Regards,
James Cahall
Chief Technical Officer
Digital Media Interactive
james@dmi1011.com

**Comment by joeyparrish** [comment]
Glad we could help!
