### ISSUE TITLE
MediaSource support in Presto (Opera <= 12)

### ISSUE THREAD

**Issue by jamescahall** [google/shaka-player#804]
- What version of Shaka Player are you using?

2.1.1

  - Can you reproduce the issue with our latest release version?

Yes

  - Can you reproduce the issue with the latest code from `master`?

Yes

- Are you using the demo app or your own custom app?

Custom

  - If custom app, can you reproduce the issue using our demo app?

Issue is on Opera based TVs.  Can't load demo app.

- What browser and OS are you using?

Opera Blink.

- What did you expect to happen?

Play DRM content

- What actually happened?

Get MediaSource.isTypeSupported is not a function.

A number of mainstream TVs use the Opera Blink browser.  This error is thrown.  Is there any workaround or is Shaka Player and DRM not supported on these browsers?

Thanks

**Comment by jamescahall** [comment]
NOTE:  The isBrowserSupported check returns true

**Comment by joeyparrish** [comment]
Clearly, we should add `MediaSource.isTypeSupported` to the APIs we check for in `isBrowserSupported()`.

What version of Opera are these TVs based on?  I'm wondering if we could polyfill the missing functionality.

**Comment by jamescahall** [comment]
Sorry.  Not Blink.  Presto.

Here is a user agent (the most common browser used for smart TVs in 2015 and 2016).

Opera 9.80 (linux armv7l) Presto/2.12.362 version/12.11

**Comment by jamescahall** [comment]
Btw, If I stub the following in my app code to get past this:

MediaSource.isTypeSupported = function() {
	return true;
}

I then get back to a 6001 error (which I know is not the HTTPS issue in this case).  I'm supplying com.widevine.alpha and com.microsoft.playready license URLs.  I know the device does support PlayReady.  

On another TV running Presto 2.12.407, I don't get the 6001 error but then get a:
this.target.addEventListener is not a function error

**Comment by joeyparrish** [comment]
According to http://caniuse.com/#search=mediasource (click "show all" to see Presto versions of Opera), there is no MediaSource support in Presto (Opera 12 and under).

Unfortunately, Shaka Player only works with MediaSource.  As far as I know, it is infeasible to polyfill MediaSource as a whole.

**Comment by joeyparrish** [comment]
Since there is no way for us to support Presto without MediaSource, I am going to close this issue.  If you disagree, I'm happy to discuss any alternatives you might have in mind.
