### ISSUE TITLE
Cannot redefine property: fullscreenElement

### ISSUE THREAD

**Issue by JobaDiniz** [google/shaka-player#81]
Hi, I'm guessing this condition is wrong (taken from [here](https://github.com/google/shaka-player/blob/v1.3.0/lib/polyfill/fullscreen.js#L52-L60)):
```
if (!document.fullscreenElement) {
    Object.defineProperty(document, 'fullscreenElement', {
      get: function() {
        return document.mozFullScreenElement ||
               document.msFullscreenElement ||
               document.webkitFullscreenElement;
      }
    });
  }
```

**Comment by joeyparrish** [comment]
Already fixed in master by 7ea820c, but we'll leave this open until we've released v1.3.1, which will contain a cherry-pick of this fix.  Thanks!
