### ISSUE TITLE
setServerCertificate for widevine fails with error 6004

### ISSUE THREAD

**Issue by aleian84** [google/shaka-player#810]
- What version of Shaka Player are you using? 2.1.0

  - Can you reproduce the issue with our latest release version? Y

  - Can you reproduce the issue with the latest code from `master`? Y

- Are you using the demo app or your own custom app? Custom App

  - If custom app, can you reproduce the issue using our demo app? Y

- What browser and OS are you using? Chrome v59

- What did you do?

For the release of chrome 59 we have read from widevine website (https://www.widevine.com/product_news.html) that we can use the feature setServerCertificate as below : 

var **serverCertificate** = new Uint8Array(...);
player.configure({
  drm: {
    advanced: {
      'com.widevine.alpha': {
        serverCertificate: serverCertificate
      }
    }
  }
});_

We have tried to implement this feature on our customApp (attached file). 

The .bin file is downloaded correctly, we transform it from string to Unit8Array, but the error 6004 occurs. 

  -

 What content did you load? Encrypted content

    - If standard demo asset, which one? N/A

    - If custom asset, what manifest and license server URIs? N/A

  - How did you interact with the content, if at all? N/A

- What did you expect to happen? We expect the download of serverCertificate and the fruition of media content. (If we delete the piece of serverCertificate the content plays correctly)

- What actually happened? Error 6004 happen.

**Comment by aleian84** [comment]
![error](https://cloud.githubusercontent.com/assets/25437433/26144267/6b2eda5c-3ae8-11e7-9b36-aa7b41d3bfc1.png)

**Comment by aleian84** [comment]
var serverLicenseFile = 'https://' + location.host + '/license.bin';              // This is a license file that we’ve downloaded from https://storage.googleapis.com/wvdocs/wv-proxy-sample.tgz
                
$.ajax({
url: serverLicenseFile,
    success : function(response){
 
	  function str2ab(str) {          // function to get a Unit8Array
		 var buf = new ArrayBuffer(str.length*2);
		 var bufView = new Uint8Array(buf);
		
		 return bufView;
	  }
								
	  var serverCertificate = str2ab(response);

	  self.player.configure({
		 'preferredAudioLanguage': self.getDefaultAudioStream(),
		 manifest: {
						dash: {
							clockSyncUri: dateSync
						}
		 },
		 abr: {
			manager: abrManager
		 },
		 drm: {
			servers: {
				'com.widevine.alpha': URL_API["GetWidevineExternalKey"]+"&channel=STBTIVUON&cp_id="+self.currentContent.variant.cp_id
			},
			advanced: {
				'com.widevine.alpha': {
					  serverCertificate: serverCertificate, // for Chrome 59
					  'videoRobustness': 'SW_SECURE_CRYPTO',
					  'audioRobustness': 'SW_SECURE_CRYPTO'
				}
			}
		 }
	  });

	  self.load(mediaUrl);
    },
              
	error : function(error){
        console.log(error);
    }
});

**Comment by aleian84** [comment]
I have tried to send a ZIP file but an error occurs. You can find in first comment the png of the error and in the second comment our code. 

Thank you 
Alessio

**Comment by TheModMaker** [comment]
First, if you are going to make a network request for it, you might as well not do it and have the CDM do it.  The reason you would want to use `setServerCertificate` is to avoid the round trip to the server.  For example, if you embed it in the page, or if you make other requests at the same time.  Since you are making the request already, you can just have the browser do it for you.  Using `setServerCertificate` is optional.

Second, if the code you posted is exactly what you are using, it has an error in str2ab.  You create the array buffer, but don't fill it.  So you are giving us an array of 0s.  Also, you are using jQuery, which is converting the response to a string.  However, the certificate is actually binary.  This means that jQuery may be incorrectly converting the response to a string (for example, interpreting bytes as UTF-8 codepoints).  It would be better to use `XMLHttpRequest` to get the `ArrayBuffer` response directly.

**Comment by joeyparrish** [comment]
There are still reasons to request it from the server without letting the CDM do it.  The CDM will do it once per session, as opposed to once per page load.  Setting it in advance can also reduce playback latency for content that does not have a clear lead.

**Comment by aleian84** [comment]
Hi guys,
thank you for support. Now we implement following code but we have the same issue ( 6004 ). Can u help me to understand why?

var serverLicenseFile = 'https://' + location.host + '/license.bin';              // This is a license file that we’ve downloaded from https://storage.googleapis.com/wvdocs/wv-proxy-sample.tgz

var oReq = new XMLHttpRequest();

oReq.open("GET", serverLicenseFile, true);
oReq.responseType = "arraybuffer";

oReq.onload = function (oEvent) {
               var arrayBuffer = oReq.response; // Note: not oReq.responseText
               if (arrayBuffer) {
                              var serverCertificate = new Uint8Array(arrayBuffer);
                              self.player.configure({
                                             'preferredAudioLanguage': self.getDefaultAudioStream(),
                                             manifest: {
                                                            dash: {
                                                                           clockSyncUri: dateSync
                                                            }
                                             },
                                             abr: {
                                                            manager: abrManager
                                             },
                                             drm: {
                                                            servers: {
                                                                           'com.widevine.alpha': URL_API["GetWidevineExternalKey"]+"&channel=STBTIVUON&cp_id="+self.currentContent.variant.cp_id
                                                            },
                                                            advanced: {
                                                                           'com.widevine.alpha': {
                                                                                          serverCertificate: serverCertificate, // TODO: for Chrome 59
                                                                                          'videoRobustness': 'SW_SECURE_CRYPTO',
                                                                                          'audioRobustness': 'SW_SECURE_CRYPTO'
                                                                           }
                                                            }
                                             }
                              });

                              self.load(mediaUrl);

               }
};

oReq.send(null);

**Comment by joeyparrish** [comment]
That all looks reasonable to me, but perhaps @TheModMaker will spot something I missed.

The error message is based on the fact that the browser/CDM rejected the data you provided.  So I can only assume it's not the correct data in some way.

If you can send us the exact license.bin file, we could probably tell you if it's malformed in some way.  If you share the URL of that file with us, we could probably also tell you if there is some server issue that's corrupting the file.  You may find our emails in the CONTRIBUTORS file if you don't want to share these things publicly.

**Comment by aleian84** [comment]
Widevine provides the bin file from here : https://www.widevine.com/product_news.html

I download it from here : https://storage.googleapis.com/wvdownload/cert_license_widevine.tgz 

I unzip the tgz and I put the bin file on our apache server.

Thanks,
Let we know,
Alessio

**Comment by joeyparrish** [comment]
Thanks.  We will go through those same steps, but that may not help if you made a mistake on your end.  If you send us the exact file you are serving and/or the URL for that file on your server, we can compare that file with ours and tell you if your copy is corrupt somehow.

**Comment by aleian84** [comment]
Hi Joey,
we follow your suggestion and put the file on our server. 

Now we are able to play content with serverCertificate enabled.

Thank you for your support :+1:

**Comment by joeyparrish** [comment]
Glad I could help!

**Comment by hghazzi** [comment]
@joeyparrish We are experiencing the same issue with a certificate. I will email you the link to the bin file, if you have any insight, it would be greatly appreciated.

**Comment by JeffJassky** [comment]
Which OS and browser versions are you seeing this on?

**Comment by hghazzi** [comment]
Mac/Chrome

**Comment by joeyparrish** [comment]
@hghazzi, what error code do you get with the cert you sent via email?

**Comment by joeyparrish** [comment]
@hghazzi, I am able to play with your certificate, so there's nothing wrong with the contents.  Perhaps you are fetching it wrong?

If you are using XHR to fetch the cert, make sure you are using `responseType = 'arraybuffer'`.  See the MDN article ["Sending and Receiving Binary Data"](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Sending_and_Receiving_Binary_Data) for more details.

If you are using Shaka's `NetworkingEngine` to make the request, you will already get back an `ArrayBuffer`.

Shaka Player config wants a Uint8Array, so use something like `new Uint8Array(certBuffer)` for the value you pass to Shaka's DRM configuration.

Here's an example using `NetworkingEngine`:

```js
var requestType = shaka.net.NetworkingEngine.RequestType.APP;
var request = { uris: [ '810.cert.bin' ] };
var async = shakaDemo.localPlayer_.getNetworkingEngine().request(requestType, request);

async.then(function(response) {
  var cert = new Uint8Array(response.data);
  console.log('cert fetched', cert);

  // This config affects future calls to player.load()
  player.configure({
    drm: {
      'com.widevine.alpha': { serverCertificate: cert }
    }
  });
});
```

**Comment by hghazzi** [comment]
Here's the output from the server I tried setting up. Which proxy are you using?
[proxy.txt](https://github.com/google/shaka-player/files/1216542/proxy.txt)

**Comment by joeyparrish** [comment]
@hghazzi, it seems like you have a bug in your proxy.  Unfortunately, I can't really offer proxy support here.

**Comment by hghazzi** [comment]
Would you be able to provide a sample working proxy, or the one that you
used?

**Comment by joeyparrish** [comment]
I'm using the demo license server in our demo app: https://widevine-proxy.appspot.com/proxy
