### ISSUE TITLE
DrmEngine#unpackPlayReadyRequest fails in Tizen HTML5 application

### ISSUE THREAD

**Issue by chrisfillmore** [google/shaka-player#814]
The Tizen PlayReady CDM doesn't wrap the license message in XML as other PlayReady CDMs do (i.e IE11, Edge). It can be delivered to the license server as-is.

The proposed fix is to add a check for wrapping in DrmEngine#unpackPlayReadyRequest. If the message is not wrapped, return early. I have submitted PR #815.

**Comment by chrisfillmore** [comment]
I just want to add a note: I am having an ongoing problem getting Shaka to run on Tizen in compiled mode. It compiles fine, but I have so far been unable to get the player to work in compiled mode on the TV. I will be investigating this further.

**Comment by joeyparrish** [comment]
Thank you for contributing!  I will review your PR soon.

I am happy to help you with Tizen issues if I can.  Unfortunately, I don't have access to a Tizen device for testing.

Please do file an issue with details on what goes wrong in compiled mode.  When there are issues in compiled mode, the compiler is usually renaming something it should not.  We can definitely help you fix that.

**Comment by chrisfillmore** [comment]
Thanks Joey.

Also as a heads up -- all of my work / testing is in Tizen HTML5 application, i.e. _not_ the Tizen web browser.

**Comment by joeyparrish** [comment]
I admit, I'm not familiar with the distinction.  But we'll try to do what we can to help, either way.

**Comment by chrisfillmore** [comment]
The Tizen OS has a web browser, which I presume is like a regular browser. (I doubt anyone ever uses it.) But you can also develop native apps, either in an HTML5/JS environment or directly in C/C++.

**Comment by joeyparrish** [comment]
This fix was just released in v2.1.2.
