### ISSUE TITLE
MEDIA_SOURCE_OPERATION_FAILED(0) for some DASH manifests only in chrome

### ISSUE THREAD

**Issue by skstronghold** [google/shaka-player#820]
- What version of Shaka Player are you using?
   2.1.1
  - Can you reproduce the issue with our latest release version?
    Yes
  - Can you reproduce the issue with the latest code from `master`?
     Yes

- Are you using the demo app or your own custom app?
  Demo app
  - If custom app, can you reproduce the issue using our demo app?
    N/A

- What browser and OS are you using?
   Google Chrome: 58.0.3029.110 (64-bit) in Ubuntu 14.04

- What did you do?
  Tried to load manifest file in chrome
  - What content did you load?
     DASH manifest encoded using vp9 and opus.
    - If standard demo asset, which one?
       N/A
    - If custom asset, what manifest and license server URIs?
      {{removed}}
  - How did you interact with the content, if at all?
     No interaction, fails to load

- What did you expect to happen?
  I expected it to play. It works fine in Firefox.

- What actually happened?
   I was trying to test a DASH manifest encoded using vp9 and opus codecs. It doesn't play it in chrome but same manifest plays fine in Firefox. It happens only to some specific manifests.

**Comment by TheModMaker** [comment]
Looking at `chrome://media-internals` shows an error `Unsupported display unit type 4`.  This is out of our control, and is a problem with your packager or with your content.  See google/shaka-packager#192 for a similar case.

**Comment by skstronghold** [comment]
Setting proper aspect ratio fixed the issue.
