### ISSUE TITLE
HLS NAME attribute not supported

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#825]
When #811 lands, we should add support for the HLS `NAME` attribute, which would map to the track label.

**Comment by yuenghole** [comment]
Thanks a lot, Joey. 

Your Shaka Player is fantastic!!!

Besides, may I know when this enhancement will be released?

Thank you very much.

**Comment by joeyparrish** [comment]
After we land PR #811, we will have all the necessary framework to expose labels.  After that, adding support for HLS's `NAME` attribute will be quick and simple.

As for when it will be released, if you want to work with what's in the `master` branch, you'll have it much sooner.  We will have to review the feature to decide if it makes the cut for v2.1.x or if it waits until v2.2.0.  We try not to cherry-pick anything to a release branch that may introduce undue risk.

I'll update this issue when the decision is made.

**Comment by joeyparrish** [comment]
Cherry-picked to v2.1.3.
