### ISSUE TITLE
Add channelcount information on HLS audio tracks

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#826]
According to https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#section-4.3.4.1 

> CHANNELS
> 
> The value is a quoted-string that specifies an ordered, "/"-separated list of parameters.  If the TYPE attribute is AUDIO then the first parameter is a count of audio channels expressed as a decimal-integer, indicating the maximum number of independent, simultaneous audio channels present in any Media Segment in the Rendition.  For example, an AC-3 5.1 rendition would have a CHANNELS="6" attribute.  No other CHANNELS parameters are currently defined.
> 
> All audio EXT-X-MEDIA tags SHOULD have a CHANNELS attribute.  If a Master Playlist contains two renditions encoded with the same codec but a different number of channels, then the CHANNELS attribute is REQUIRED; otherwise it is OPTIONAL.

This issue is related to: https://github.com/google/shaka-player/issues/424

Sample:
https://tungsten.aaplimg.com/VOD/bipbop_adv_fmp4_example/master.m3u8
`#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aud1",LANGUAGE="en",NAME="English",AUTOSELECT=YES,DEFAULT=YES,CHANNELS="2",URI="a1/prog_index.m3u8"`
`#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aud2",LANGUAGE="en",NAME="English",AUTOSELECT=YES,DEFAULT=YES,CHANNELS="6",URI="a2/prog_index.m3u8"`
`#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aud3",LANGUAGE="en",NAME="English",AUTOSELECT=YES,DEFAULT=YES,CHANNELS="6",URI="a3/prog_index.m3u8"`

**Comment by ismena** [comment]
@avelad thanks for bringing this up, I think we could definitely add this for hls!
Let me schedule it for 2.2 unless @joeyparrish has objections.

**Comment by joeyparrish** [comment]
Sounds good to me.  And the spec is more clear than the corresponding feature in DASH.  :-)
