### ISSUE TITLE
Prefer Fetch API over XHR

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#829]
We should prefer the Fetch API whenever possible.  It looks like that's everywhere but IE 11 right now: 
 http://caniuse.com/#feat=fetch

**Comment by joeyparrish** [comment]
Note: @theodab has discovered that Fetch is missing timeout/abort functionality that would bring it to parity with XHR.  This means we will not always be able to use Fetch.

See whatwg/fetch#20 and whatwg/fetch#447.

**Comment by theodab** [comment]
As an update...
It looks like they have finally settled on a design for aborting fetches.
The AbortController has been implemented but not flighted on Edge, Mozilla has an implementation in 55+ nightly, and Chrome is planning on adding it soon. So it might not be too long till we can use Fetch.

**Comment by joeyparrish** [comment]
Thanks for the update!

**Comment by theodab** [comment]
We now have a fetch request scheme plugin. Note that, because this requires both the fetch API and the AbortController API, as of this moment it will only be used on Firefox and Edge.

**Comment by joeyparrish** [comment]
Chrome implementation bug: https://bugs.chromium.org/p/chromium/issues/detail?id=750599

It looks like some or all of the implementation of AbortController landed in Chrome early this week.  I haven't talked to Chrome team to confirm, but I expect it would launch in Chrome 66, due out in late April.
