### ISSUE TITLE
Shaka Player support page indicates that Playready is not supported on Edge 25

### ISSUE THREAD

**Issue by gigon** [google/shaka-player#833]
With the latest Shaka Player version (currently v2.1.2-debug),
I open [the Shaka demo support page ](https://shaka-player-demo.appspot.com/support.html).

The result: 
  "drm": {
     ...
    **"com.microsoft.playready": null,**
    ...
  },

I would expect the same result as IE11 shows:
  "drm": {
     ...
    **"com.microsoft.playready": {
      "persistentState": true
    },**
    ...
  },

The error I see in the debugger is: DRM.REQUESTED_KEY_SYSTEM_CONFIG_UNAVAILABLE.

OS: Windows 10 Enterprise version 1511 (64 bit)
Browser: Microsoft Edge 25.10586.672.0

Notes: 
I get the same error trying to load Playready videos, but it simpler to reproduce in the "support" page.

Does work on Edge 34!

**Comment by TheModMaker** [comment]
We only officially support the latest version of Edge, which is 39 (or the more common EdgeHTML version 14).  (Supposedly) Edge will be updated more often similarly to Chrome, so we are only supporting the latest version.  Edge has a number of bugs in it (especially with EME) and some newer bugs are mutually exclusive to older ones (e.g. #634).  We don't want to maintain support for older versions unless we have to.

**Comment by joeyparrish** [comment]
Yes, we only support the latest stable release of Edge.  We would consider support for older versions if you send a PR, but we don't have the time or resources to test all versions.

Closing for now, but we can continue to discuss a PR if you have the time or inclination to contribute.  Thanks!
