### ISSUE TITLE
Add separate fields for audio and video bandwidth for variant tracks

### ISSUE THREAD

**Issue by DanielLindstrm** [google/shaka-player#834]
**What version of Shaka Player are you using**:
2.1.2

Hi
I want to calculate MOS and I need the bitrate of the individual tracks. 
In previous versions you could get audio / video tracks separately, but now you can only get the combined (variant track) as I understand it? Is it possible to get the bitrate for the individual tracks somehow?

**Comment by ismena** [comment]
Hi @DanielLindstrm,
We switched from individual audio/video tracks to variants(audio+video combinations) starting 2.1 when we added HLS support. (This is the way HLS is structured), so the bandwidth of a variant track will be the combined bandwidth of both audio and video.

That being said, I don't see why we couldn't add separate fields for audio and video bandwidth and fill them if we know this information (we will for DASH and won't for HLS).
Would that help?

Please note, that you still won't be able to select individual audio and video streams, but only their variant combinations.

**Comment by DanielLindstrm** [comment]
Yes, it would help.
Thanks.
