### ISSUE TITLE
question about mse shim

### ISSUE THREAD

**Issue by publicocean0** [google/shaka-player#835]
**Have you read the [FAQ](https://goo.gl/njDlGk) and checked for duplicate issues**:
are you working on or is already available  a MSE shim using flash ?

**Comment by joeyparrish** [comment]
We have no plans to polyfill MediaSource through flash.  We only maintain our own polyfills for the browsers we directly support, all of which have MSE.

If you have access to a flash-based MSE implementation, you can always load that in addition to Shaka Player.  So long as `shaka.Player.isBrowserSupported()` returns true before you create a `Player`, it should work.

Does this help?

**Comment by publicocean0** [comment]
yes another question please .... in the past i realized  my player but i m thinking to pass to shaka. But there is a problem. My player uses a customized datasource for retrieval chunks ... 
is there a manual or source example or other for make easy to understand how to implement a additional datasource ?

**Comment by joeyparrish** [comment]
I'm not sure if I understand you.  Do you mean that you want to get media data from some custom piece of code, rather than directly from the network?

**Comment by publicocean0** [comment]
No it doesnt use dash specifications but custom specification and it retrieves data in different way ...There is a generic prototype Stream  class permitting to handle streams of data , to seek in a specific offset.

**Comment by joeyparrish** [comment]
We have many plugin interfaces you may want to explore: https://shaka-player-demo.appspot.com/docs/api/tutorial-plugins.html

[Manifest parser plugins](https://shaka-player-demo.appspot.com/docs/api/tutorial-manifest-parser.html) would allow you to source your media metadata from something other than DASH or HLS.  We don't care where the info comes from, but we need metadata in a certain format to allow us to generically stream the content and feed it to the browser using `MediaSource`.

[Networking plugins](https://v2-1-2-dot-shaka-player-demo.appspot.com/docs/api/lib_net_http_plugin.js.html#line35) allow you to provide data from a source other than HTTP.  You register your plugin to handle a certain URI scheme, and Shaka Player will invoke your plugin any time it wants data from a URI using that scheme.  For example, you could ask Shaka to load media from `myapp://foo/bar`, and we would invoke the "myapp" plugin to get the actual data.

Does this help?

**Comment by publicocean0** [comment]
yes i think. I will read this documentation for having a better idea about
it.
Thanks for your support :)

2017-05-31 19:23 GMT+02:00 Joey Parrish <notifications@github.com>:

**Comment by joeyparrish** [comment]
Happy to help!
