### ISSUE TITLE
PlayReady broken (in Edge and IE11) since 2.1.2

### ISSUE THREAD

**Issue by Ambroos** [google/shaka-player#837]
**Have you read the [FAQ](https://goo.gl/njDlGk) and checked for duplicate issues**: yes

**What version of Shaka Player are you using**: 2.1.2

**Can you reproduce the issue with our latest release version**: yes

**Can you reproduce the issue with the latest code from `master`**: haven't checked (most likely yes)

**Are you using the demo app or your own custom app**: both

**If custom app, can you reproduce the issue using our demo app**: yes

**What browser and OS are you using**: Edge 38, IE11 (latest)

**What are the manifest and license server URIs**: any PlayReady demo in the Shaka demo page
*(you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*

**What did you do?**
- Try to play a PlayReady-protected asset (Axinom and Tears of Steel) on the demo page
- Try to play a PlayReady-protected asset of our own (CastLabs DRMtoday with PlayReady) in our own integration

**What did you expect to happen?**
- The asset plays

**What actually happened?**
- The license request is only a single starting XML starting thing (`<`) and doesn't contain the usual XML/SOAP body. (Both on the demo page and in our own custom integration.)

2.1.1 works fine (custom integration, exact same issue on 2.1.2).

The Chromecast PlayReady does work fine once I manually set the license request header Content-Type to text/xml (is text/html by default for some reason).

**Comment by joeyparrish** [comment]
Looks like this was caused by PR #815.  I mistakenly disabled the relevant tests in c263e0bb.  I should have realized that we broke it, but I was distrustful of a failure from a third-party server.

I'll see what I can do to fix it.  Thanks!

**Comment by joeyparrish** [comment]
Cherry-picked to v2.1.3.
