### ISSUE TITLE
Request - Support for SMPTE-TT subtitles

### ISSUE THREAD

**Issue by kidmiracleman** [google/shaka-player#840]
Hi,

I have worked on some systems that transcode legacy linear broadcast steams to OTT.  In multilingual regions typically the live streams contain multiple DVB formatted subtitles.  DASH-IOP allows this format to be tunnelled via TTML (SMPTE-TT).   The reason is to avoid latency related to OCR conversion to text.

Is support for this format an enhancement that you guys would consider for Shaka Player ?

Thanks,

**Comment by joeyparrish** [comment]
If you can provide samples and point us to a spec, we could evaluate the format and make a decision based on that.  Thanks!

**Comment by kidmiracleman** [comment]
Thanks Joey,

The spec(s) are available from here : https://www.smpte.org/standards

Is there any way I can send you a content link privately?

**Comment by ismena** [comment]
Thanks @kidmiracleman, we'll take a look! As for the content, you can find Joey's (and the rest of the team's) emails in the CONTRIBUTORS file. Feel free to shoot the link to any of us! :)

**Comment by joeyparrish** [comment]
Please send private links to shaka-player-issues@google.com so the whole team gets them.  Thanks!

**Comment by kidmiracleman** [comment]
email sent.

**Comment by adgllorente** [comment]
Hi,

I've seen the milestone has been changed several times, @joeyparrish is the support to smpte-tt planned to be included in the 2.5 release or it will be moved to another release?

Thanks!

**Comment by TheModMaker** [comment]
It is not scheduled for v2.5, which is already late.  And v2.6 is a cleanup release and has already been planned.  So the minimum will be v2.7.

Although, scanning the specs, it looks like this is just TTML with some extra metadata.  So we may already support this at a basic level.  We already don't support the full TTML style set.  But with some small changes, we may support just displaying the text.  You could try registering the TTML text parser under the SMPTE-TT codec and seeing if that works.

**Comment by avelad** [comment]
I think it was resolved in v2.5.0. 

This issue can be closed.

**Comment by joeyparrish** [comment]
Thanks, @avelad.  We will close this on your recommendation.  If we have done this in error, the original poster can include `@shaka-bot reopen` in a comment to reopen the issue.
