### ISSUE TITLE
support flv thought flv.js

### ISSUE THREAD

**Issue by jimmywarting** [google/shaka-player#845]
Hate flash but I don't have other formats to play. Would you maybe consider adding this [flv.js](https://github.com/Bilibili/flv.js/)

> flv.js works by transmuxing FLV file stream into ISO BMFF (Fragmented MP4) segments, followed by feeding mp4 segments into an HTML5 <video> element through Media Source Extensions API.

**Comment by joeyparrish** [comment]
I don't see any reason you couldn't do this.  My team does not have time to do this, but we'd be happy to give you advice if you want to build a plugin for this.  In Shaka Player's architecture, this would be a response filter that translates flv into mp4.

Before you dive into such a project, though, I think it's worth asking: If your only format is FLV, why not use flv.js directly?  It sounds like it already does everything you need.

**Comment by jimmywarting** [comment]
hmm, okey.
Would still want this to work with Shaka player, it has other advantage like ChromeCast, offline/download support.

I got a question. if i want to cast a flv don't I need a custom receiver app then?

**Comment by joeyparrish** [comment]
Yes, you would need a receiver that can also play FLV.  If you build a plugin for Shaka Player, you can build a Shaka-based receiver as well and use the same plugin on the Chromecast.  We have library support for both sender and receiver.

**Comment by joeyparrish** [comment]
Let us know if you plan to send a PR or if you need any help building a plugin.  Or if you decide not to work on this, we can go ahead and close the issue.  Thanks!

**Comment by jimmywarting** [comment]
I won't do it. and i don't need it anymore
