### ISSUE TITLE
Use of Presentation API.

### ISSUE THREAD

**Issue by jimmywarting** [google/shaka-player#847]
Is it possible to build a plugin or implement this into shaka player itself?

Presentation API lets you cast to a second screen not only for ChromeCast but for other wireless technologies too.

**Comment by joeyparrish** [comment]
I see no reason you couldn't do this.  What browsers support it?  What devices support it, other than Chromecast?  Does Chromecast support it as well?

**Comment by jimmywarting** [comment]
Chrome and Chromecast supports it.
Seeing this as it's more like a standard more browser will eventually support it.

I know YouTube use the presentation API and it could cast to my smart Samsung TV that didn't had a Chromecast. Probably cuz it use DIAL protocol but not 100 sure

**Comment by joeyparrish** [comment]
I experimented with the Presentation API, and found that it was equivalent to tab-casting with a hidden tab.  It doesn't seem to be a good replacement for the Cast API, where the Cast device would be streaming content independent of the sender.
