### ISSUE TITLE
Reversed cue display order for identical time ranges

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#848]
Split from #821 filed by @ewosleger:

> Shaka v2.0.8
> We noticed Shaka is displaying our captions in reverse order from our embedded ttml files in the manifest:
> "jumped over the fence"
> "Quick brown fox"

> Regarding our captions in reverse order. A snippet of a specific ttml segment.
> `<p begin="00:00:55.000" end="00:00:56.541" region="pop1" style="basic" tts:extent="45% 5.33%" tts:origin="27.5% 79.33%">
>             JEANNIE:
>             <span tts:fontStyle="italic">You still</span>
>          </p>
>          <p begin="00:00:55.000" end="00:00:56.541" region="pop2" style="basic" tts:extent="67.5% 5.33%" tts:origin="15% 84.66%">
>             <span tts:fontStyle="italic">stubbornly insist on being</span>
>          </p>`
> 
> The first `<p>` "pop1" tss:origin y cord is 79.33% from the top. 
> The secons `<p>` "pop2" tss:origin y cord should be below "pop1" y at 84.66% however it is rendering above the first `<p>`.
> 
> <img width="660" alt="screen shot 2017-05-23 at 2 18 41 pm" src="https://cloud.githubusercontent.com/assets/3507090/26369708/7f5edbaa-3fc3-11e7-8e74-76526128a8c7.png">

**Comment by ismena** [comment]
As mentioned in comments to #821 I verified that we are parsing the "tts:origin" attribute and constructing the VttCues correctly, so it's likely to be a browser bug.
@ewosleger, if you let me know which browser(s) is/are affected I could verify the assumption and file bugs on them if need be.

**Comment by kjnsn** [comment]
So the browser is actually doing what the spec says: https://w3c.github.io/webvtt/#webvtt-cue-line-automatic

In a list of cues, the first cue will be given the line -1, the second -2, and so on. This leads to the captions appearing reversed.  I've checked dash.js and it has the same issue.

**Comment by joeyparrish** [comment]
If the browser behavior is to-spec, then we should reverse the order of the cues before sending them to the browser.

**Comment by joeyparrish** [comment]
We've pushed a fix to `master` for the case where line=auto, but we will leave this issue open a little longer until we can determine what the issue is in other cases.

**Comment by joeyparrish** [comment]
I'm unable to reproduce any issue in Chrome's support of line=.

I've tested line=-1, -2, -3 with snapToLines=true and line=10, 20, 30 with snapToLines=false.  In all cases, in any insertion order, the display is correct.

If you see any further issue with this, please let us know and we can reopen.

**Comment by joeyparrish** [comment]
Fix cherry-picked for v2.1.6.
