### ISSUE TITLE
Limit number of devices for Windevine protected content

### ISSUE THREAD

**Issue by aaani** [google/shaka-player#849]
Hello,

I am trying to limit the playback of encrypted content to only only device. License is served via Widevine. This [post](https://github.com/google/ExoPlayer/issues/1624) suggests that in the license proxy I can use `drm_cert_serial_number` to uniquely identify a device, but I am receiving the same `drm_cert_serial_number` whether license request arrives from my computer or my friend's computer. We're both using Google chrome 57 latest on mac. However when the request arrives from chrome android I get a popup to allow additional permissions for playing premium content and the `drm_cert_serial_number` is unique for it. I am wondering if `drm_cert_serial_number` can reliably be used for accessing whether the device is unique or not?

**Comment by joeyparrish** [comment]
@aaani, I think this might be the wrong forum for this question.  Shaka Player can't control this at all.  You are interested in features of the license proxy and CDM, but Shaka Player just sits in between the two (on top of the browser & CDM) and can't see any DRM-vendor-specific features.  I suggest contacting Widevine support directly.

**Comment by aaani** [comment]
Thanks. I'll close this issue.
