### ISSUE TITLE
better error messages when persistent licenses are not supported

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#85]
If the CDM used by this asset does not support persistent licenses, you will get an error like "None of the requested configurations were supported" or "Unsupported session type."

Ideally, we could combine these errors with the context of storing offline and provide a clearer message to the application like "This CDM does not support persistent licenses on this platform."

**Comment by ddorwin** [comment]
Note that a single request (with multiple configurations), you can determine whether persistent and temporary licenses are supported. Thus, the app (or Shaka) could determine that it can play the content but not persist it. I don't know whether this would be useful in this case.
