### ISSUE TITLE
Chromecast PlayReady license request is sent with Content-Type: text/html

### ISSUE THREAD

**Issue by Ambroos** [google/shaka-player#852]
**Have you read the [FAQ](https://goo.gl/njDlGk) and checked for duplicate issues**: yes

**What version of Shaka Player are you using**: 2.1.3

**Can you reproduce the issue with our latest release version**: yes

**Can you reproduce the issue with the latest code from `master`**: unknown

**Are you using the demo app or your own custom app**: custom app - cannot access Chromecast remote debugging in demo app

**If custom app, can you reproduce the issue using our demo app**: N/A

**What browser and OS are you using**: Chromecast 2

**What are the manifest and license server URIs**:
Cannot provide at this point (our signed licenses expire after 5 minutes) but it wouldn't surprise me if it was reproducible with the PlayReady test assets in the demo (which error when casting as well).

We use DRMtoday with both PlayReady and Widevine schemes in our manifests.

**What did you do?**
Play a DASH video that supports both PlayReady and Widevine on a Chromecast 2

**What did you expect to happen?**
The license request (either PlayReady or Widevine) should succeed and the video should play.

**What actually happened?**
The license request failed with a 415 unsupported media type, as it is sent with `Content-Type: text/html`.

Manually adding `request.headers['Content-Type'] = 'text/xml; charset=utf-8';` to the license request filter resolves the issue (as does removing PlayReady license servers from the configuration to make Shaka use Widevine instead, which works fine).

The exact same code works fine in Edge/IE11 with PlayReady (in 2.1.1 / 2.1.3).

I suspect the issue is caused by the correct header not being added in https://github.com/google/shaka-player/blob/9d9d1c70/lib/media/drm_engine.js#L1122

**Comment by joeyparrish** [comment]
The header is added, though.  See https://github.com/google/shaka-player/blob/9d9d1c70/lib/media/drm_engine.js#L1153

**Comment by joeyparrish** [comment]
I did some debugging on a Chromecast and found that we never entered that method.  It should be easy to fix.  Sorry for the inconvenience.
