### ISSUE TITLE
"shaka.util.MapUtils.forEach is not a function" on hosted demo today, v2.1.3-debug

### ISSUE THREAD

**Issue by ddennedy** [google/shaka-player#853]
**Have you read the [FAQ](https://goo.gl/njDlGk) and checked for duplicate issues**:

some

**What version of Shaka Player are you using**:

v2.1.3-debug

**Are you using the demo app or your own custom app**:

hosted demo

**What browser and OS are you using**:

Chrome 59.0.3071.86 on Windows 10

**What did you do?**

Load page, which preloads the Angel One asset, and click Load.

**What did you expect to happen?**

Audio and video to start playing.

**What actually happened?**

Only the error in $subject displayed.

**Comment by joeyparrish** [comment]
I can't reproduce.  Since we just pushed this version to the server, can you try clearing your browser cache and reloading?

**Comment by ddennedy** [comment]
Well, I just clicked shift-reload and the problem is gone. I am fairly sure I had already tried that. :) Oh well; case closed.
