### ISSUE TITLE
Use data saver mode signal to inform ABR decisions

### ISSUE THREAD

**Issue by hbengali** [google/shaka-player#855]
An API to signal when the user has turned on data saver mode is being discussed here:

https://github.com/WICG/netinfo/issues/42

Once this signal is available, Shaka player should respect the user's intent and change the stream selection logic to limit data consumption. The preferred mechanism for this would be to allow developers to restrict to a different max resolution/bandwidth when data saver is turned on, vs when it is not.

**Comment by joeyparrish** [comment]
Moving this to the backlog, since it does not appear to be available from the browser yet.

**Comment by joeyparrish** [comment]
This should be available now, so we just need to decide how our behavior will differ when the user enables data-saver mode.

**Comment by joeyparrish** [comment]
When the browser indicates that we should save data, we will default AbrManager's restrictions object to a max height of 360.  Apps can still override this, and users can still select higher resolution tracks when ABR is disabled.  The restrictions object will be treated as "soft" restrictions, meaning that if the restrictions cannot be met, we will not fail playback.

**Comment by joeyparrish** [comment]
Cherry-picked for v2.3.9 and v2.4.1.
