### ISSUE TITLE
Can shaka player read license proxy uri from the playlist?

### ISSUE THREAD

**Issue by aaani** [google/shaka-player#859]
Is there any way for shaka player to read the uri of the license proxy server from the playlist/manifest itself?

Currently I am hardcoding the license proxy server uri in the player config as per instructions here - https://shaka-player-demo.appspot.com/docs/api/tutorial-drm-config.html, but that doesn't work for me because the license proxy server uri changes for every playlist in my system so I want my users to be able to play DRM protected content just by adding the manifest url and without having to add license server URI in the shaka player config.

If there is absolutely no way to accomplish above, I can probably add a custom field in the ContentProtection tag of the manifest, could you provide some instructions on how I can read a custom attribute from the ContentProtection tag in the manifest and make it available to the `getNetworkingEngine().registerRequestFilter` callback so that I can forward it to the license proxy server.

Thanks!

**Comment by joeyparrish** [comment]
You should already be able to do this through a callback.  We have a `<ContentProtection>` callback for DASH that allows you to parse custom attributes/elements from the manifest and provide us with a `DrmInfo` object, which can include the license server URI.

Here are the docs on the DASH configuration, including the callback you can use: https://shaka-player-demo.appspot.com/docs/api/shakaExtern.html#DashManifestConfiguration

If there's a particular common (if non-standard) format you want us to support, support could be added to the manifest parsers.

**Comment by joeyparrish** [comment]
See also #484

**Comment by ismena** [comment]
@TheModMaker also gave an example in an email thread recently: https://groups.google.com/d/msg/shaka-player-users/fVDlZABXMF4/3b1NnHofAQAJ

@aaani feel free to take a look.

**Comment by aaani** [comment]
Awesome, that answers the second half of my question, so I can have a custom attribute and parse it in the configuration.

Is there any standard attribute/syntax for widevine that I can set in the manifest and shaka player would automatically default the license url to it? In #484 I do see there is some interest for `ms:laurl`, does widevine has a counterpart to it?

**Comment by joeyparrish** [comment]
No, Widevine does not have any recommended extensions to DASH.

**Comment by aaani** [comment]
Thanks!
