### ISSUE TITLE
Regression: choosing lowest-bandwidth codec leads to always picking audio-only variant for HLS

### ISSUE THREAD

**Issue by ismena** [google/shaka-player#861]
This was introduced by 434f1bf (CL that fixed #841). The fact that we started grouping variants by codecs and choosing the group with the smallest average bandwidth led to the player always choosing audio-only variants for HLS content that has at least one.
We can't switch from audio-only variants to audio+video, so we end up being stuck with audio-only.
A manifest to repro: https://nexxplayplus6.streaming.mediaservices.windows.net/32de1b7d-822c-43b2-b3a5-1cd97f0e9ae7/242391_src.ism/manifest(format=m3u8-aapl)

(Discovered by investigating #860).

**Comment by joeyparrish** [comment]
Given #824, where we can't switch to audio-only variants anyway, we should probably solve both problems at one by filtering out audio-only variants in cases where there are audio+video variants available.

**Comment by joeyparrish** [comment]
The fix for this has been cherry-picked and will be released in v2.1.5.
