### ISSUE TITLE
Document that https or localhost are required for encrypted content

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#867]
It has been discussed on github and in the mailing list before, but encrypted content in Chrome (and according to the EME spec) requires either https or localhost.  This should be made clear in the DRM-related tutorials and in the FAQ.

This issue was raised during this quarter's [CWIP class](http://www.widevine.com/cwip/).

**Comment by chrisfillmore** [comment]
From time to time I have had to advise people to use `--unsafely-treat-insecure-origin-as-secure`, perhaps the docs could also link to this page:

https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-powerful-features-on-insecure-origins

**Comment by joeyparrish** [comment]
Great advice.  Thanks!

**Comment by joeyparrish** [comment]
The changes to the docs have been cherry-picked and will be released in v2.1.5.
