### ISSUE TITLE
Wrong version number in released builds

### ISSUE THREAD

**Issue by boredom2** [google/shaka-player#869]
Hi there,

the compiled Version on CDNJS here:
https://cdnjs.cloudflare.com/ajax/libs/shaka-player/2.1.3/shaka-player.compiled.js seems to be wrong - it shows v2.1.2-17...
Search the Code for "v2." and you will see, that this Version offers v2.1.2-17-gf11a54a-dirty.
This seems not to be a clean final Version of the 2.1.3 Code.

I already opened a Ticket on CDNJS, but they said, its something your Side must fix.
Can you please check that?

**Comment by joeyparrish** [comment]
Yes, that is definitely a mistake we made in our release process.  The build was done before the tag was created, which caused the released build to have the wrong version number.

I went back through previous releases and found that v2.0.3 and v2.0.4 also had a bad version number in the binary.

I will see what I can do to fix the process for future releases, and I will try to find a way to fix the three builds that are already out with the wrong version numbers: v2.1.3, v2.0.4, v2.0.3.

**Comment by joeyparrish** [comment]
I will not be able to fix the version in the builds that went out via npm.  According to the docs on [`npm publish`](https://docs.npmjs.com/cli/publish):

> Once a package is published with a given name and version, that specific name and version combination can never be used again, even if it is removed with npm-unpublish.

I may be able to fix what's in [CDNJS](https://cdnjs.com/libraries/shaka-player) and [Google Hosted Libraries](https://developers.google.com/speed/libraries/?csw=1#shaka-player).

**Comment by joeyparrish** [comment]
The versions in Google Hosted Libraries are already correct.  (Those go through a different release process that is not driven by npm.)

So it is only npm (which we can't fix) and CDNJS (which I am working to fix).

We have fixed our npm release scripts to avoid this issue in future.

**Comment by boredom2** [comment]
Thanks for your Efforts!

**Comment by joeyparrish** [comment]
According to @PeterDaveHello in https://github.com/cdnjs/cdnjs/pull/11396#issuecomment-308197262, we can't update what's in CDNJS.  So there's nothing more we can do.

I apologize for the error in those releases.  We have fixed our processes so it should not happen again.  Builds on Google Hosted Libraries are not affected, but builds on NPM and CDNJS are.
