### ISSUE TITLE
Subtitles chunks don't load (but presented in mpd)

### ISSUE THREAD

**Issue by theifish** [google/shaka-player#875]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**: Yes

**What version of Shaka Player are you using**: 2.3

**Can you reproduce the issue with our latest release version**: Yes

**Can you reproduce the issue with the latest code from `master`**: Yes

**Are you using the demo app or your own custom app**: Own player

**If custom app, can you reproduce the issue using our demo app**: No (mpd protected with CORS), but it can be reproduced with "clear" Shaka library locally.

**What browser and OS are you using**: All

**What are the manifest and license server URIs**:
*(you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*

Manifest was sent to the email, mpd example in first comment (URLs changed)

**What did you do?**

Started a stream with Shaka and waiting for subtitles.

**What did you expect to happen?**

Subtitles show in player.

**What actually happened?**

No subtitles were shown in player, even subtitles chunks were not requested.

**Comment by theifish** [comment]
Here is MPD example:

```
<MPD xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="urn:mpeg:dash:schema:mpd:2011" xmlns:cenc="urn:mpeg:cenc:2013" xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011 http://standards.iso.org/ittf/PubliclyAvailableStandards/MPEG-DASH_schema_files/DASH-MPD.xsd" type="dynamic" publishTime="2017-06-13T09:46:39" minimumUpdatePeriod="PT10S" availabilityStartTime="2017-06-09T13:50:08Z" minBufferTime="PT30S" suggestedPresentationDelay="PT30S" timeShiftBufferDepth="PT2H0M0S" profiles="urn:mpeg:dash:profile:isoff-live:2011">
<Period start="PT0S" id="1">
<AdaptationSet mimeType="video/mp4" frameRate="25/1" segmentAlignment="true" subsegmentAlignment="true" startWithSAP="1" subsegmentStartsWithSAP="1" bitstreamSwitching="false">
<SegmentTemplate timescale="90000" duration="900000" startNumber="1"/>
<Representation id="1" width="1280" height="720" bandwidth="2400000" codecs="avc1.64001f">
<SegmentTemplate duration="900000" startNumber="1" media="/streams/tv/tvdash1-Frag-hd-5-20170609T134945_$Number%09d$.mp4" initialization="tvdash1-Frag-hd-5-20170609T134945init.mp4"/>
</Representation>
<Representation id="2" width="1280" height="720" bandwidth="1250000" codecs="avc1.64001f">
<SegmentTemplate duration="900000" startNumber="1" media="/streams/tv/tvdash1-Frag-hd-4-20170609T134945_$Number%09d$.mp4" initialization="tvdash1-Frag-hd-4-20170609T134945init.mp4"/>
</Representation>
<Representation id="3" width="640" height="360" bandwidth="950000" codecs="avc1.4d401e">
<SegmentTemplate duration="900000" startNumber="1" media="/streams/tv/tvdash1-Frag-hd-3-20170609T134945_$Number%09d$.mp4" initialization="tvdash1-Frag-hd-3-20170609T134945init.mp4"/>
</Representation>
<Representation id="4" width="640" height="360" bandwidth="650000" codecs="avc1.4d401e">
<SegmentTemplate duration="900000" startNumber="1" media="/streams/tv/tvdash1-Frag-hd-2-20170609T134945_$Number%09d$.mp4" initialization="tvdash1-Frag-hd-2-20170609T134945init.mp4"/>
</Representation>
<Representation id="5" width="640" height="360" bandwidth="350000" codecs="avc1.4d401e">
<SegmentTemplate duration="900000" startNumber="1" media="/streams/tv/tvdash1-Frag-hd-1-20170609T134945_$Number%09d$.mp4" initialization="tvdash1-Frag-hd-1-20170609T134945init.mp4"/>
</Representation>
</AdaptationSet>
<AdaptationSet mimeType="audio/mp4" lang="rus" segmentAlignment="0">
<SegmentTemplate timescale="48000" media="/streams/tv/tvdash1-Frag-hd-audio-20170609T134945_$Number%09d$.mp4" initialization="tvdash1-Frag-hd-audio-20170609T134945init.mp4" duration="480000" startNumber="1"/>
<Representation id="6" bandwidth="96000" audioSamplingRate="48000" codecs="mp4a.40.2"/>
</AdaptationSet>
<AdaptationSet mimeType="application/mp4" lang="rus">
<Role schemeIdUri="urn:mpeg:dash:role" value="subtitle"/>
<SegmentTemplate timescale="90000" media="/streams/tv/tvdash1-Frag-hd-caption-20170609T134945_$Number%09d$.mp4" initialization="tvdash1-Frag-hd-caption-20170609T134945init.mp4" duration="900000" startNumber="1"/>
<Representation id="7" bandwidth="256" codecs="stpp"/>
</AdaptationSet>
</Period>
</MPD>
```

**Comment by joeyparrish** [comment]
@theifish, can you please confirm your Shaka Player version?  v2.3 does not exist yet.

If you are using our demo app, you can see the version number at the top of the page.  Otherwise, check `shaka.Player.version` in the JS console.

I can confirm the behavior, and that there are no subtitles according to the parsed manifest.

**Comment by joeyparrish** [comment]
This appears to be a very small bug in the DASH parser.  Should be easy to fix.

**Comment by joeyparrish** [comment]
This is caused by the fact that `mimeType` appears on `AdaptationSet`, but `codecs` appears on `Representation`.  We have not seen this before.  Usually, these attributes would appear on the same element.  @theifish, can you tell us which encoder/packager you are using?

**Comment by theifish** [comment]
@joeyparrish sorry, actual version is 2.1.3

**Comment by captnced** [comment]
I've seen the very same manifest issue with an Ericsson Halo packager

**Comment by TheModMaker** [comment]
@captnced Please start a new issue for that and be sure to include an example manifest.  Thanks.

**Comment by kuznetcoff777** [comment]
Hi! When 2.2 version will be available?

We did some workarond with mainfest file and now it looks like this:
<?xml version="1.0" encoding="UTF-8"?>
<MPD xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="urn:mpeg:dash:schema:mpd:2011" xmlns:cenc="urn:mpeg:cenc:2013" xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011 http://standards.iso.org/ittf/PubliclyAvailableStandards/MPEG-DASH_schema_files/DASH-MPD.xsd" type="dynamic" publishTime="2017-07-25T14:13:51" minimumUpdatePeriod="PT10S" availabilityStartTime="2017-07-25T13:26:31" minBufferTime="PT30S" suggestedPresentationDelay="PT30S" timeShiftBufferDepth="PT2H0M0S" profiles="urn:mpeg:dash:profile:isoff-live:2011">
  <Period start="PT0S" id="1">
    <AdaptationSet mimeType="video/mp4" frameRate="25/1" segmentAlignment="true" subsegmentAlignment="true" startWithSAP="1" subsegmentStartsWithSAP="1" bitstreamSwitching="false">
      <SegmentTemplate timescale="90000" duration="900000" startNumber="1"/>
      <Representation id="1" width="1280" height="720" bandwidth="2400000" codecs="avc1.64001f">
        <SegmentTemplate duration="900000" startNumber="1" media="/streams/tv/tvdash1-Frag-hd-5-20170725T132607_$Number%09d$.mp4" initialization="tvdash1-Frag-hd-5-20170725T132607init.mp4"/>
      </Representation>
      <Representation id="2" width="1280" height="720" bandwidth="1250000" codecs="avc1.64001f">
        <SegmentTemplate duration="900000" startNumber="1" media="/streams/tv/tvdash1-Frag-hd-4-20170725T132607_$Number%09d$.mp4" initialization="tvdash1-Frag-hd-4-20170725T132607init.mp4"/>
      </Representation>
      <Representation id="3" width="640" height="360" bandwidth="950000" codecs="avc1.4d401e">
        <SegmentTemplate duration="900000" startNumber="1" media="/streams/tv/tvdash1-Frag-hd-3-20170725T132607_$Number%09d$.mp4" initialization="tvdash1-Frag-hd-3-20170725T132607init.mp4"/>
      </Representation>
      <Representation id="4" width="640" height="360" bandwidth="650000" codecs="avc1.4d401e">
        <SegmentTemplate duration="900000" startNumber="1" media="/streams/tv/tvdash1-Frag-hd-2-20170725T132607_$Number%09d$.mp4" initialization="tvdash1-Frag-hd-2-20170725T132607init.mp4"/>
      </Representation>
      <Representation id="5" width="640" height="360" bandwidth="350000" codecs="avc1.4d401e">
        <SegmentTemplate duration="900000" startNumber="1" media="/streams/tv/tvdash1-Frag-hd-1-20170725T132607_$Number%09d$.mp4" initialization="tvdash1-Frag-hd-1-20170725T132607init.mp4"/>
      </Representation>
    </AdaptationSet>
    <AdaptationSet mimeType="audio/mp4" lang="rus" segmentAlignment="0">
      <SegmentTemplate timescale="48000" media="/streams/tv/tvdash1-Frag-hd-audio-20170725T132607_$Number%09d$.mp4" initialization="tvdash1-Frag-hd-audio-20170725T132607init.mp4" duration="480000" startNumber="1"/>
      <Representation id="6" bandwidth="96000" audioSamplingRate="48000" codecs="mp4a.40.2"/>
    </AdaptationSet>
    <AdaptationSet mimeType="application/mp4" codecs="stpp" lang="rus">
      <Role schemeIdUri="urn:mpeg:dash:role" value="subtitle"/>
      <SegmentTemplate timescale="90000" media="/streams/tv/tvdash1-Frag-hd-caption-20170725T132607_$Number%09d$.mp4" initialization="tvdash1-Frag-hd-caption-20170725T132607init.mp4" duration="900000" startNumber="1"/>
      <Representation id="7" bandwidth="256"/>
    </AdaptationSet>
  </Period>
</MPD>


But anyway we dont see captions (only see as they are downloaded)

**Comment by joeyparrish** [comment]
@kuznetcoff777, the initial fix we made for this came out in v2.1.4.  We just released v2.1.6 which includes a fix for #919, which may explain subtitles downloaded and never displayed.  v2.2.0 will be out as soon as we resolve #960.

Please let us know whether v2.1.6 and the fix for #919 resolve your missing subtitle issue.  Thanks!

**Comment by theifish** [comment]
@joeyparrish, I'm trying to build v2.1.6 within ./build/all.py and see the following error:

[ERROR] *** A required dependency is missing: java

Have no idea why it need java.

**Comment by theifish** [comment]
I managed it, just start using jre64 from my Webstorm location. (I wish one day you'll change packager to any ordinary :) ).
Anyway, in 2.1.6 subtitles work, so the issue is resolved.

**Comment by joeyparrish** [comment]
@theifish, the JavaScript compiler we use is written in Java.  We have a brief mention of this in the README:

> In order to build, you simply need python v2.7 (for the build scripts) and JRE 7+ (for the compiler).

Glad to know the issue is now resolved for you.  Thanks for retesting!
