### ISSUE TITLE
Accessing cues from text parser plugin

### ISSUE THREAD

**Issue by hghazzi** [google/shaka-player#886]
Wanted to start a conversation about how the text parser plugin works. 

We are using the plugin to parse the cues ourselves, and as far as I can tell, every time a cues array buffer needs to be parsed, it creates a new instance of the text parser plugin. 

We are also trying to access the cues from the plugin as soon as they are parsed. Currently, we are using event handling to pass the cues as soon as they are parsed. But when we have multiple players instantiated, we can't identify which parsed cues are associated with which player. Any ideas on how we might be able to do that?

**Comment by joeyparrish** [comment]
I believe this will be handled by #796, in which we will provide a plugin interface for subtitle display after parsing.

**Comment by joeyparrish** [comment]
I'm adding a requirement to #796 to make sure the text display plugin can know which Player it belongs to, and I'm closing this as a duplicate.  Thanks!
