### ISSUE TITLE
[Feature request] unminified compiled version in dist (release)

### ISSUE THREAD

**Issue by kslimani** [google/shaka-player#888]
Currently, the package.json "main" field is pointing to `dist/shaka-player.compiled.js` which is a minified version of shaka player.

I think it would be a nice at each release to build a `shaka-player.compiled.js` (unminified) and a `shaka-player.compiled.min.js` (minified) with "main" field pointing to unminified version.

The motivation behind this request is when you import Shaka player (for example using NPM) and import it in your javascript application bundle as node module, you expect an unminified version of the module.

Also, i think when you compile your bundle and minify it (_for example using UglifyJS_), i think (_but i may be wrong!_) that the minified result may be more optimized if working from unminified source, instead of minified.

Does it make sense ?

**Comment by kslimani** [comment]
Nevermind, I just realized that project use closure compiler. Closing the issue.

**Comment by joeyparrish** [comment]
The compiled bundle is also minified.  We also ship a debug version (in which you can use source maps and set breakpoints) and the uncompiled library.

See these two tutorials for more details:

https://shaka-player-demo.appspot.com/docs/api/tutorial-basic-usage.html  (shows use of the compiled library)
https://shaka-player-demo.appspot.com/docs/api/tutorial-debugging.html  (shows use of the uncompiled library)

**Comment by kslimani** [comment]
Thank you, i will take a deeper look at python helper scripts.
