### ISSUE TITLE
shaka player 2.1.3 not playing dynamic manifest

### ISSUE THREAD

**Issue by ganantha** [google/shaka-player#895]
we are trying to play a clear DASH content with shaka 2.1.3 and we are facing issues.

`<?xml version="1.0" encoding="UTF-8"?>
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" profiles="urn:mpeg:dash:profile:isoff-live:2011" type="dynamic" availabilityStartTime="2017-06-17T10:40:35Z" publishTime="2017-06-17T10:40:44Z" minimumUpdatePeriod="PT12S" timeShiftBufferDepth="PT3600S" minBufferTime="PT12S">
<Period id="0" start="PT0S">
  <AdaptationSet mimeType="audio/mp4" lang="de" segmentAlignment="true" startWithSAP="1">
    <SegmentTemplate presentationTimeOffset="0" timescale="10000000" initialization="seg_$RepresentationID$_init.mp4" media="seg_$RepresentationID$_t$Time$.mp4">
      <SegmentTimeline>
        <S d="20480000" t="14976960060809000"/>
        <S d="20480000"/>
        <S d="19200000" t="14976960101769000"/>
        <S d="20480000" t="14976960120969000"/>
        <S d="20480000"/>
        <S d="19200000" t="14976960161929000"/>
        <S d="20480000" t="14976960181129000"/>
        <S d="18766222" t="14976960201609000"/>
        <S d="20480000" t="14976960220375222"/>
      </SegmentTimeline>
    </SegmentTemplate>
    <Representation id="audio512_0" bandwidth="200000" codecs="mp4a.40.2"></Representation>
  </AdaptationSet>
  <AdaptationSet mimeType="video/mp4" segmentAlignment="true" startWithSAP="1">
    <SegmentTemplate presentationTimeOffset="0" timescale="10000000" initialization="seg_$RepresentationID$_init.mp4" media="seg_$RepresentationID$_t$Time$.mp4">
      <SegmentTimeline>
        <S d="20000000" t="14976960060009000"/>
        <S d="20000000"/>
        <S d="20000000"/>
        <S d="20000000"/>
        <S d="20000000"/>
        <S d="20000000"/>
        <S d="20000000"/>
        <S d="20366222" t="14976960200009000"/>
        <S d="20000000" t="14976960220375222"/>
      </SegmentTimeline>
    </SegmentTemplate>
    <Representation id="video_0" bandwidth="1760000" width="720" height="400" codecs="avc1.4D401F" scanType="progressive"></Representation>
  </AdaptationSet>
</Period>
</MPD>
`

our server supports only one period. It cannot maintain context of the period delivered to various clients, meaning it cannot remember the presentation time offset for that period particularly to each client.

So we have tried to support multi periods. The idea is to have 5 periods in the manifest each for 12secs,
MPD refresh time is 12s, so when the MPD refresh happens we expect the first period to disappear and a new period to be appended in the end. MPD with multi period support is mentioned below. But even with this update we see that the shaka player is complaining in this error.

`if ((currentPeriod.startTime + reference.endTime < availabilityStart) ||
      (currentPeriod.startTime + reference.startTime > availabilityEnd)) {
    shaka.log.v1(logPrefix,
                 'segment is not available:',
                 'currentPeriod.startTime=' + currentPeriod.startTime,
                 'reference.startTime=' + reference.startTime,
                 'reference.endTime=' + reference.endTime,
                 'availabilityStart=' + availabilityStart,
                 'availabilityEnd=' + availabilityEnd);
    return null;
  }`

Can you kindly help us here. Mainly let us know if there is any other way around without multi period support or is this approach to multi period correct ? what should we correct to make shaka player understand our MPDs.

MPD after multi period support
 
`<?xml version="1.0" encoding="UTF-8"?>
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" profiles="urn:mpeg:dash:profile:isoff-live:2011" type="dynamic" availabilityStartTime="2017-06-17T10:45:22Z" publishTime="2017-06-17T10:45:33Z" minimumUpdatePeriod="PT12S" timeShiftBufferDepth="PT3600S" minBufferTime="PT12S">
<Period id="p179" start="PT1497696260S">
  <AdaptationSet mimeType="video/mp4" segmentAlignment="true" startWithSAP="1">
	  <SegmentTemplate presentationTimeOffset="14976962600006111" timescale="10000000" initialization="seg_$RepresentationID$_init.mp4" media="seg_$RepresentationID$_t$Time$.mp4">
		<SegmentTimeline>
		<S d="20000000" t="14976962600006111"/>
		<S d="20000000"/>
		<S d="20000000"/>
		<S d="20000000"/>
		<S d="20000000"/>
		<S d="20000000"/>
		</SegmentTimeline>
	  </SegmentTemplate>
	<Representation id="video_0" bandwidth="160000" width="128" height="96" codecs="avc1.42800B" scanType="progressive"></Representation>
	<Representation id="video_1" bandwidth="460000" width="512" height="288" codecs="avc1.42800B" scanType="progressive"></Representation>
	<Representation id="video_2" bandwidth="900000" width="640" height="360" codecs="avc1.42800B" scanType="progressive"></Representation>
	<Representation id="video_3" bandwidth="1460000" width="768" height="432" codecs="avc1.42800B" scanType="progressive"></Representation>
	<Representation id="video_4" bandwidth="2020000" width="1024" height="576" codecs="avc1.42800B" scanType="progressive"></Representation>
	<Representation id="video_5" bandwidth="2460000" width="960" height="540" codecs="avc1.42800B" scanType="progressive"></Representation>
	<Representation id="video_6" bandwidth="3680000" width="1280" height="720" codecs="avc1.42800B" scanType="progressive"></Representation>
	<Representation id="video_7" bandwidth="6880000" width="1920" height="1080" codecs="avc1.42800B" scanType="progressive"></Representation>
	</AdaptationSet>
</Period>
<Period id="p180" start="PT1497696272S">
  <AdaptationSet mimeType="video/mp4" segmentAlignment="true" startWithSAP="1">
	  <SegmentTemplate presentationTimeOffset="14976962720006111" timescale="10000000" initialization="seg_$RepresentationID$_init.mp4" media="seg_$RepresentationID$_t$Time$.mp4">
		<SegmentTimeline>
		<S d="20000000" t="14976962720006111"/>
		<S d="20000000"/>
		<S d="20000000"/>
		<S d="20000000"/>
		<S d="20000000"/>
		<S d="20000000"/>
		</SegmentTimeline>
	  </SegmentTemplate>
	<Representation id="video_0" bandwidth="160000" width="128" height="96" codecs="avc1.42800B" scanType="progressive"></Representation>
	<Representation id="video_1" bandwidth="460000" width="512" height="288" codecs="avc1.42800B" scanType="progressive"></Representation>
	<Representation id="video_2" bandwidth="900000" width="640" height="360" codecs="avc1.42800B" scanType="progressive"></Representation>
	<Representation id="video_3" bandwidth="1460000" width="768" height="432" codecs="avc1.42800B" scanType="progressive"></Representation>
	<Representation id="video_4" bandwidth="2020000" width="1024" height="576" codecs="avc1.42800B" scanType="progressive"></Representation>
	<Representation id="video_5" bandwidth="2460000" width="960" height="540" codecs="avc1.42800B" scanType="progressive"></Representation>
	<Representation id="video_6" bandwidth="3680000" width="1280" height="720" codecs="avc1.42800B" scanType="progressive"></Representation>
	<Representation id="video_7" bandwidth="6880000" width="1920" height="1080" codecs="avc1.42800B" scanType="progressive"></Representation>
	</AdaptationSet>
</Period>
<Period id="p181" start="PT1497696284S">
  <AdaptationSet mimeType="video/mp4" segmentAlignment="true" startWithSAP="1">
	  <SegmentTemplate presentationTimeOffset="14976962840006111" timescale="10000000" initialization="seg_$RepresentationID$_init.mp4" media="seg_$RepresentationID$_t$Time$.mp4">
		<SegmentTimeline>
		<S d="20000000" t="14976962840006111"/>
		<S d="20000000"/>
		<S d="20000000"/>
		<S d="20000000"/>
		<S d="20000000"/>
		<S d="20000000"/>
		</SegmentTimeline>
	  </SegmentTemplate>
	<Representation id="video_0" bandwidth="160000" width="128" height="96" codecs="avc1.42800B" scanType="progressive"></Representation>
	<Representation id="video_1" bandwidth="460000" width="512" height="288" codecs="avc1.42800B" scanType="progressive"></Representation>
	<Representation id="video_2" bandwidth="900000" width="640" height="360" codecs="avc1.42800B" scanType="progressive"></Representation>
	<Representation id="video_3" bandwidth="1460000" width="768" height="432" codecs="avc1.42800B" scanType="progressive"></Representation>
	<Representation id="video_4" bandwidth="2020000" width="1024" height="576" codecs="avc1.42800B" scanType="progressive"></Representation>
	<Representation id="video_5" bandwidth="2460000" width="960" height="540" codecs="avc1.42800B" scanType="progressive"></Representation>
	<Representation id="video_6" bandwidth="3680000" width="1280" height="720" codecs="avc1.42800B" scanType="progressive"></Representation>
	<Representation id="video_7" bandwidth="6880000" width="1920" height="1080" codecs="avc1.42800B" scanType="progressive"></Representation>
	</AdaptationSet>
</Period>
<Period id="p182" start="PT1497696296S">
  <AdaptationSet mimeType="video/mp4" segmentAlignment="true" startWithSAP="1">
	  <SegmentTemplate presentationTimeOffset="14976962960006111" timescale="10000000" initialization="seg_$RepresentationID$_init.mp4" media="seg_$RepresentationID$_t$Time$.mp4">
		<SegmentTimeline>
		<S d="20000000" t="14976962960006111"/>
		<S d="20000000"/>
		<S d="20000000"/>
		<S d="20000000"/>
		<S d="20000000"/>
		<S d="20000000"/>
		</SegmentTimeline>
	  </SegmentTemplate>
	<Representation id="video_0" bandwidth="160000" width="128" height="96" codecs="avc1.42800B" scanType="progressive"></Representation>
	<Representation id="video_1" bandwidth="460000" width="512" height="288" codecs="avc1.42800B" scanType="progressive"></Representation>
	<Representation id="video_2" bandwidth="900000" width="640" height="360" codecs="avc1.42800B" scanType="progressive"></Representation>
	<Representation id="video_3" bandwidth="1460000" width="768" height="432" codecs="avc1.42800B" scanType="progressive"></Representation>
	<Representation id="video_4" bandwidth="2020000" width="1024" height="576" codecs="avc1.42800B" scanType="progressive"></Representation>
	<Representation id="video_5" bandwidth="2460000" width="960" height="540" codecs="avc1.42800B" scanType="progressive"></Representation>
	<Representation id="video_6" bandwidth="3680000" width="1280" height="720" codecs="avc1.42800B" scanType="progressive"></Representation>
	<Representation id="video_7" bandwidth="6880000" width="1920" height="1080" codecs="avc1.42800B" scanType="progressive"></Representation>
	</AdaptationSet>
</Period>
<Period id="p183" start="PT1497696308S">
  <AdaptationSet mimeType="video/mp4" segmentAlignment="true" startWithSAP="1">
	  <SegmentTemplate presentationTimeOffset="14976963080006111" timescale="10000000" initialization="seg_$RepresentationID$_init.mp4" media="seg_$RepresentationID$_t$Time$.mp4">
		<SegmentTimeline>
		<S d="20000000" t="14976963080006111"/>
		</SegmentTimeline>
	  </SegmentTemplate>
	<Representation id="video_0" bandwidth="160000" width="128" height="96" codecs="avc1.42800B" scanType="progressive"></Representation>
	<Representation id="video_1" bandwidth="460000" width="512" height="288" codecs="avc1.42800B" scanType="progressive"></Representation>
	<Representation id="video_2" bandwidth="900000" width="640" height="360" codecs="avc1.42800B" scanType="progressive"></Representation>
	<Representation id="video_3" bandwidth="1460000" width="768" height="432" codecs="avc1.42800B" scanType="progressive"></Representation>
	<Representation id="video_4" bandwidth="2020000" width="1024" height="576" codecs="avc1.42800B" scanType="progressive"></Representation>
	<Representation id="video_5" bandwidth="2460000" width="960" height="540" codecs="avc1.42800B" scanType="progressive"></Representation>
	<Representation id="video_6" bandwidth="3680000" width="1280" height="720" codecs="avc1.42800B" scanType="progressive"></Representation>
	<Representation id="video_7" bandwidth="6880000" width="1920" height="1080" codecs="avc1.42800B" scanType="progressive"></Representation>
	</AdaptationSet>
</Period>
</MPD>
`

**Comment by TheModMaker** [comment]
Sorry for the delay.  Your first Period starts at `PT1497696260S`, this means that it should appear that far from the start of the presentation.  For live streams, the presentation starts at the `availabilityStartTime`, so that means that your first Period starts 47 years in the future.  Your handling of `presentationTimeOffset` and segment times look correct, but you need to adjust the Period start times so they are in the presentation correctly.  (or you could adjust the `availabilityStartTime` to be that far in the past)

**Comment by dhanapal20** [comment]
Hi 
Thanks for your detailed analysis, now we have modified the availabilityStartTime as relevant to content presentation time and now content playing well

**Comment by joeyparrish** [comment]
We are glad we were able to help.  Thanks for letting us know that the problem is now resolved.
