### ISSUE TITLE
timecode of stream

### ISSUE THREAD

**Issue by kuznetcoff777** [google/shaka-player#899]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**: Yes

**What version of Shaka Player are you using**: 2.1.3

**Can you reproduce the issue with our latest release version**:yes

**Can you reproduce the issue with the latest code from `master`**:yes

**Are you using the demo app or your own custom app**:Own player

**If custom app, can you reproduce the issue using our demo app**:No (mpd protected with CORS), but it can be reproduced with "clear" Shaka library locally.

**What browser and OS are you using**: All
 
**What are the manifest and license server URIs**: 
*(you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*
Exampld of MPD is in first comment

**What did you do?**
Started a stream with embemed timecode.

**What did you expect to happen?**
Player time line shoud be the same as timecode of stream. I expected that player takes information about current time position from segments. But it seems to that player do some calculations "getPlayheadTimeAsDate". Client and server (that makes mpeg-dash) is ntp syncronized. Initial 20 seconds shift i suppose can explain (maybe it is some bug or feature of packager) - but shift is moving ahead. I cannot understand how, beacuse i do sure that stream time code is not shifting - i checked it with a shedule of airs we have and burn-in timecode (packager burn in time code on a picture - and we checked then segments timecode with Sencore - they are the same, on a picture and on segment metadata).

**What actually happened?**
In player timeline there is a difference between it and time of stream ~ 20 seconds. And it shifts from one day to another (19,18,17...etc - approximate 0,3 seconds per day)

**Comment by kuznetcoff777** [comment]
Here is MPD example:

```
<MPD xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="urn:mpeg:dash:schema:mpd:2011" xmlns:cenc="urn:mpeg:cenc:2013" xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011 http://standards.iso.org/ittf/PubliclyAvailableStandards/MPEG-DASH_schema_files/DASH-MPD.xsd" type="dynamic" publishTime="2017-06-13T09:46:39" minimumUpdatePeriod="PT10S" availabilityStartTime="2017-06-09T13:50:08Z" minBufferTime="PT30S" suggestedPresentationDelay="PT30S" timeShiftBufferDepth="PT2H0M0S" profiles="urn:mpeg:dash:profile:isoff-live:2011">
<Period start="PT0S" id="1">
<AdaptationSet mimeType="video/mp4" frameRate="25/1" segmentAlignment="true" subsegmentAlignment="true" startWithSAP="1" subsegmentStartsWithSAP="1" bitstreamSwitching="false">
<SegmentTemplate timescale="90000" duration="900000" startNumber="1"/>
<Representation id="1" width="1280" height="720" bandwidth="2400000" codecs="avc1.64001f">
<SegmentTemplate duration="900000" startNumber="1" media="/streams/tv/tvdash1-Frag-hd-5-20170609T134945_$Number%09d$.mp4" initialization="tvdash1-Frag-hd-5-20170609T134945init.mp4"/>
</Representation>
<Representation id="2" width="1280" height="720" bandwidth="1250000" codecs="avc1.64001f">
<SegmentTemplate duration="900000" startNumber="1" media="/streams/tv/tvdash1-Frag-hd-4-20170609T134945_$Number%09d$.mp4" initialization="tvdash1-Frag-hd-4-20170609T134945init.mp4"/>
</Representation>
<Representation id="3" width="640" height="360" bandwidth="950000" codecs="avc1.4d401e">
<SegmentTemplate duration="900000" startNumber="1" media="/streams/tv/tvdash1-Frag-hd-3-20170609T134945_$Number%09d$.mp4" initialization="tvdash1-Frag-hd-3-20170609T134945init.mp4"/>
</Representation>
<Representation id="4" width="640" height="360" bandwidth="650000" codecs="avc1.4d401e">
<SegmentTemplate duration="900000" startNumber="1" media="/streams/tv/tvdash1-Frag-hd-2-20170609T134945_$Number%09d$.mp4" initialization="tvdash1-Frag-hd-2-20170609T134945init.mp4"/>
</Representation>
<Representation id="5" width="640" height="360" bandwidth="350000" codecs="avc1.4d401e">
<SegmentTemplate duration="900000" startNumber="1" media="/streams/tv/tvdash1-Frag-hd-1-20170609T134945_$Number%09d$.mp4" initialization="tvdash1-Frag-hd-1-20170609T134945init.mp4"/>
</Representation>
</AdaptationSet>
<AdaptationSet mimeType="audio/mp4" lang="rus" segmentAlignment="0">
<SegmentTemplate timescale="48000" media="/streams/tv/tvdash1-Frag-hd-audio-20170609T134945_$Number%09d$.mp4" initialization="tvdash1-Frag-hd-audio-20170609T134945init.mp4" duration="480000" startNumber="1"/>
<Representation id="6" bandwidth="96000" audioSamplingRate="48000" codecs="mp4a.40.2"/>
</AdaptationSet>
<AdaptationSet mimeType="application/mp4" lang="rus">
<Role schemeIdUri="urn:mpeg:dash:role" value="subtitle"/>
<SegmentTemplate timescale="90000" media="/streams/tv/tvdash1-Frag-hd-caption-20170609T134945_$Number%09d$.mp4" initialization="tvdash1-Frag-hd-caption-20170609T134945init.mp4" duration="900000" startNumber="1"/>
<Representation id="7" bandwidth="256" codecs="stpp"/>
</AdaptationSet>
</Period>
</MPD>

```

**Comment by kuznetcoff777** [comment]
@joeyparrish what is "needs triage"? Should i provide more info?

**Comment by vaage** [comment]
@kuznetcoff777 "needs triage" just means that we (the Shaka team) needs to go over it and allocate resources, determine milestones, etc.

**Comment by TheModMaker** [comment]
Can you give us a playable manifest?  Having a non-playable manifest like what you gave doesn't tell us much.  Though I do see that you don't have any clock synchronization in the manifest.  This can result in playback issues and time differences between the server and the client.  You should add a `<UTCTiming>` element to the manifest to synchronize the two.

When you say the difference is changing, is this for a single playback session, or are you reloading the page on the next day and seeing a larger difference?  When you are checking, is the playhead at the live edge (the rightmost part of the seek bar)?

You mention `getPlayheadTimeAsDate`, are you using that to determine the difference between the client and the server?  Or are you looking at the burned in time on the client vs the current wall clock time?  If you play this stream on different browsers or machines, do you see the same behavior?

**Comment by kuznetcoff777** [comment]
"Can you give us a playable manifest?" not at the moment, it is secured with CORS
" Though I do see that you don't have any clock synchronization in the manifest." - we made a fallback to clockSyncUri
"When you say the difference is changing, is this for a single playback session, or are you reloading the page on the next day and seeing a larger difference?" - not single playback session
"You mention getPlayheadTimeAsDate, are you using that to determine the difference between the client and the server?" -as i understand shaka player use it by default
"Or are you looking at the burned in time on the client vs the current wall clock time?" - dont get the question
"If you play this stream on different browsers or machines, do you see the same behavior?" - the same behaviour on different browsers

How to make shaka player to determine current time playing from metadata of video segments?

**Comment by kuznetcoff777** [comment]
![time-diff](https://user-images.githubusercontent.com/15265762/27628802-741cf134-5bf0-11e7-80c9-1b993504d361.png)
Here is how it looks in player at the moment of 18 days stream uptime.

**Comment by TheModMaker** [comment]
CORS is only enforced by the browser, and it is easy to bypass (Chrome has a `--disable-web-security` flag).  It also doesn't affect manually fetching it.  You could also provide a link to your app, which would not be restricted by CORS.  If you would rather not have the links be public, you can send them to <shaka-player-issues@google.com>.

The frame times in the video segments are relative to the start of the live stream.  So when the video is at 2 minutes, that means that we are playing 2 minutes into the live stream.  So the `getPlayheadTimeAsDate` literally takes the `video.currentTime` and adds the time the live stream started (which is the `availabilityStartTime` in the manifest).  So in this regard, we are using the times in the video to determine the current time.

What metadata are you talking about for detecting the current time?

I would also suggest running a single playback overnight and seeing if the gap changes.  If it doesn't change, it is probably a clock sync problem.  This may also happen if the `availabilityStartTime` changes, which is why it would help to have a live manifest to look at.

**Comment by kuznetcoff777** [comment]
"What metadata are you talking about for detecting the current time?" - time code, that is inserted/embeded in video segment (as i said i checked with Sencore 

I sent mpd link at shaka-player-issues@google.com

I have just restared stream, so you can see initial -20 seconds shift.

**Comment by kuznetcoff777** [comment]
Did you manage to check?

**Comment by TheModMaker** [comment]
I have looked at it a little, I  checked early yesterday, then in the evening, then this morning.  When I play live at the live edge, I see a delay (compared to my local clock) of almost exactly 1 minute.  This has not changed so far.  I also notice the 20 second difference between the burned-in time vs `getPlayheadTimeAsDate`, but I don't know if it is changing.

From what I can tell, the player is doing what it is supposed to.  The timecodes in the video segment matches the time we are returning in `getPlayheadTimeAsDate`.  My guess is that your encoder is burning in the wrong time.  Or the clock on your encoder's machine is different than your machine, which is causing the differences.

**Comment by kuznetcoff777** [comment]
"When I play live at the live edge, I see a delay (compared to my local clock) of almost exactly 1 minute. " - dont look at your local time of your machine, it is not so interesting. Anyway we dont use localtime of users, we look at clockSyncUri http://time.akamai.com/?iso
" I also notice the 20 second difference between the burned-in time vs getPlayheadTimeAsDate, but I don't know if it is changing." - it is changing, 3 days pased and ~1 second shifted already. Few days more and it will be more. Try in a 3 days, you will see ~2 seconds difference

" My guess is that your encoder is burning in the wrong time." - it is not true, i already explained ho i checked it comparing schedules.
". Or the clock on your encoder's machine is different than your machine, which is causing the differences." -as i said we dont use local time of user.

**Comment by kuznetcoff777** [comment]
I have to admit that this trick did not work, sorry for inconveniences. This test stream is made without audio and captions. Maybe this is the reason of not shifting stream. So i will investigate with encoder.

The last question, anyway, am i correctly understand that player does not take time metadata from video segments and just do calculate time from MPD file? And no other way to make player to take into account this time metadata?

**Comment by TheModMaker** [comment]
We do read the timestamps from the media segments (actually the browser does).  When we append a media segment, the browser looks at the times of the media frames to insert the frames into the timeline.  Then when playing the media, the `video.currentTime` is based on the frame times in the media files.  We only use the manifest times as an approximation so we can handle seeks.

**Comment by joeyparrish** [comment]
@kuznetcoff777, did you manage to resolve this?  Do you need further support from us on this issue?

**Comment by kuznetcoff777** [comment]
Yep, it seems to be encoder issue. I suppose we can close the issue.

**Comment by kuznetcoff777** [comment]
@TheModMaker 
I have to reopen ticket. You say that manifest time is used for approximation, but here is my example. I launch stream and see initial difference of 20 seconds between burn-in timecode and player time.
![initial](https://user-images.githubusercontent.com/15265762/30053198-9f7e99e2-9230-11e7-9e41-0f7b27c1900d.png)

After that i changed availabilityStartTime for 4 seconds back, so player time shift back for 4 seconds also
![after-change-ast](https://user-images.githubusercontent.com/15265762/30053273-e4e6b924-9230-11e7-9099-fa576886ebe6.png)
so now difference between burn-in timecode and player time is 16 seconds.

This code is used to get player time
```
    video.addEventListener('timeupdate', function () {
        time.innerHTML = player.getPlayheadTimeAsDate()
    });
```

So that means that shaka uses availabilityStartTime. It does not correlate with your words, that player takes time from metadata of video segments. Or i do something wrong and use not right function for getting time?

**Comment by kuznetcoff777** [comment]
Update 
video.currentTime - gives me 
416.735416

It seems to be that it is time from the start of stream. And it is not real timecode, that is inserted in metadata of video segments (
![pic_timing](https://user-images.githubusercontent.com/15265762/30054483-e234c082-9234-11e7-999b-3dce91be3de0.png)

**Comment by kuznetcoff777** [comment]
Given that this DASH service uses H.264 video the timecode information is bundled in the pic_timing info which is carried in the SEI_RBSP within the video itself. Can you please confirm that shaka player takes info about timecode from  SEI_RBSP? (Becuase we think that SEI_RBSP is not used by shaka player to determine timecode)

**Comment by vaage** [comment]
@kuznetcoff777 The answer to your question _"Can you please confirm that shaka player takes info about timecode from SEI_RBSP?"_, Shaka player does not directly read timecode information from SEI_RBSP. Shaka Player does not get any information directly from the codec. Shaka Player only gets information from the manifest and then passes buffers to Media Source Engine. From there the browser is responsible for handling all codec related information.

**Comment by kuznetcoff777** [comment]
@vaage Then i dont get why TheModMaker says one thing and you another. 

Anyway how can we make player time to be taken from metadata of videose gments? We faced the problem when timecode due to input source failures/drops resyncs (after some threshold, in our case 25 frames) with input timecode so it leads to changes of time code in video segments (in our case it goes back). But this changes are not reflected in mpd file, because if packager change availabilityStartTime then after a while player will try to fetch segments that are not even generated. So it is not right that player try to show stream time based on availabilityStartTime.

We use hds streaming now and flash player read time code info from video segments. So if input failres/drops happen, then it anyway does not lead to not correct player time.

**Comment by TheModMaker** [comment]
I am sorry I wasn't clear, we are in fact saying the same thing.  We don't parse the media directly, the browser does.  All we have access to is fields like `video.currentTime`, which is based on the frame times in the media.  What I meant is that the media segment times in the manifest are only used for seeking, times like `availabilityStartTime` are used.  We need to use `availabilityStartTime` to determine how far into the live stream we are.  If you change this field, we may think we are farther into the stream than we are.

The problem is that there are two times in the media.  The one the browser uses is in the mp4 container.  This value is exposed in fields like `video.currentTime`.  SEI is short for "supplemental enhancement information" and is contained in the codec data.  Unfortunately, the browser doesn't expose any way for us to get that data out of the media.  Since we don't parse the media, we have no way of getting it.

I would still think this is an encoder bug since your encoder is not handling gaps correctly.  The fact that the two media times don't match looks like a bug.

**Comment by joeyparrish** [comment]
@kuznetcoff777, JavaScript players do not generally have access to codec-level data.  The player feeds the media segments to the browser, which parses/demuxes them and decodes them.  There is nothing we can do in JavaScript to handle SEI.  If there is a conflict between SEI and the container, then I recommend you file a bug against your encoder for creating inconsistent metadata.  I am happy to assist with that if you need help.

As far as we can tell, `availabilityStartTime` is used by the player in a way that is consistent with the DASH spec.  Changing this field during a live stream is inconsistent with it's definition in the spec, so if your encoder does this, that seems like another encoder bug.

If there is anything we can do to help, please let us know.  For now, I am going to consider this issue closed.  We can reopen at any time if you wish.
