### ISSUE TITLE
MPD parser incorrectly refuses Periods without duration attribute

### ISSUE THREAD

**Issue by barbibulle** [google/shaka-player#9]
The MPD parser insists on finding an @duration attribute for a Period when the SegmentTemplate has a segment duration.
For simple static MPDs with only one Period element, the Period@duration attribute is optional. The Period duration can be inferred from the MPD@mediaPresentationDuration attribute

The DASH spec, section 5.3.2.1 indicates:
"...The Period extends until the PeriodStart of the next Period, or until the end of the Media Presentation in the case of the last Period..."

The shaka code that throws the error is:
mpd_processor.js, line 555
shaka.log.error(
                'SegmentTemplate provides a segment duration but the ' +
                'Period\'s duration is unknown.');

**Comment by joeyparrish** [comment]
Thanks for the report.  Can you please send a sample MPD which exhibits this behavior?

**Comment by joeyparrish** [comment]
Actually, never mind the MPD.  I found the issue.

The bug is in mpd_processor.js, in process().  The order of calculateDurations_() and processSegmentTemplates_() needs to be swapped.  Sorry for the inconvenience.

We'll push this fix out shortly in v1.1.

**Comment by barbibulle** [comment]
Thanks!

-- Gilles


On January 12, 2015 at 12:54:02 PM, joeyparrish (notifications@github.com) wrote:

Actually, never mind the MPD. I found the issue.

The bug is in mpd_processor.js, in process(). The order of calculateDurations_() and processSegmentTemplates_() needs to be swapped. Sorry for the inconvenience.

We'll push this fix out shortly in v1.1.

**Comment by joeyparrish** [comment]
v1.1 is out now.  The fix was slightly more complicated than I originally thought, though, so you may want to update.

Also, we now have a user mailing list where you can ask questions and receive notifications of new releases.  https://groups.google.com/forum/#!forum/shaka-player-users

Thanks again for the bug report!
