### ISSUE TITLE
Dash Live stream Error

### ISSUE THREAD

**Issue by mjaddani** [google/shaka-player#901]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**:
Yes

**What version of Shaka Player are you using**:
2.1.4
**Can you reproduce the issue with our latest release version**:
Yes
**Can you reproduce the issue with the latest code from `master`**:
Yes
**Are you using the demo app or your own custom app**:
Both
**If custom app, can you reproduce the issue using our demo app**:
yes
**What browser and OS are you using**:
Chrome, Firefox on Windows 10
**What are the manifest and license server URIs**:
*(you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*

I'send it with mail.

**What did you do?**
We teste the url and i have this error. This live stream works with dashif player

streaming_engine.js:1103 (audio:5) cannot find segment: currentPeriod.startTime=0 lookupTime=49926.84640002251
shaka.media.StreamingEngine.lookupSegmentPosition_ @ streaming_engine.js:1103
shaka.media.StreamingEngine.getSegmentReferenceNeeded_ @ streaming_engine.js:1055
shaka.media.StreamingEngine.update_ @ streaming_engine.js:944
shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:840
streaming_engine.js:1103 (video:12) cannot find segment: currentPeriod.startTime=0 lookupTime=49927.84739995003
shaka.media.StreamingEngine.lookupSegmentPosition_ @ streaming_engine.js:1103
shaka.media.StreamingEngine.getSegmentReferenceNeeded_ @ streaming_engine.js:1055
shaka.media.StreamingEngine.update_ @ streaming_engine.js:944
shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:840
streaming_engine.js:1103 (audio:5) cannot find segment: currentPeriod.startTime=0 lookupTime=49927.84739995003
shaka.media.StreamingEngine.lookupSegmentPosition_ @ streaming_engine.js:1103
shaka.media.StreamingEngine.getSegmentReferenceNeeded_ @ streaming_engine.js:1055
shaka.media.StreamingEngine.update_ @ streaming_engine.js:944
shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:840
streaming_engine.js:1103 (video:12) cannot find segment: currentPeriod.startTime=0 lookupTime=49928.84840011597
shaka.media.StreamingEngine.lookupSegmentPosition_ @ streaming_engine.js:1103
shaka.media.StreamingEngine.getSegmentReferenceNeeded_ @ streaming_engine.js:1055
shaka.media.StreamingEngine.update_ @ streaming_engine.js:944
shaka.media.StreamingEngine.onUpdate_ @ streaming_engine.js:840

**Comment by TheModMaker** [comment]
This is a bug on our part.  The time in the `availabilityStartTime` should default to UTC.  But we simply pass it to `Date.parse()`, which uses the local timezone.

It would be preferable for your assets to explicitly pass the timezone to avoid errors like this.  For example, use `2017-06-20T03:30:18Z`.

**Comment by joeyparrish** [comment]
The fix for this has been cherry-picked and will be released in v2.1.5.
