### ISSUE TITLE
Unexpected "There is a gap/overlap between Periods"

### ISSUE THREAD

**Issue by sandersaares** [google/shaka-player#909]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**: no

**What version of Shaka Player are you using**: 2.1.4-debug

**Can you reproduce the issue with our latest release version**: unknown

**Can you reproduce the issue with the latest code from `master`**: unknown

**Are you using the demo app or your own custom app**: shaka-player-demo.appspot.com

**If custom app, can you reproduce the issue using our demo app**: N/A

**What browser and OS are you using**: Chrome 58 on Windows 10.

**What are the manifest and license server URIs**: https://media.axprod.net/TestVectors/v8-MultiContent/Clear/Manifest.mpd

Detailed content description available at https://github.com/Axinom/dash-test-vectors

**What did you do?**
Pressed the Load button

**What did you expect to happen?**

Video plays without any errors/warnings.

**What actually happened?**

On manifest load, I get a warning saying `There is a gap/overlap between Periods` in the console. This is unexpected, as the timing appears correct based on my quick back of the envelope math.

Exploration of the variables involved shows the comparison leading to the warning is between `periodDuration = 10.197000000000344, givenDuration = 10.197` which makes me think some floating point shenanigans is to blame.

Possibly related: https://github.com/google/shaka-player/issues/882

**Comment by joeyparrish** [comment]
The fix for this has been cherry-picked and will be released in v2.1.5.
