### ISSUE TITLE
"Cannot read property 'startTime' of null" on seeking

### ISSUE THREAD

**Issue by sandersaares** [google/shaka-player#910]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**: yes

**What version of Shaka Player are you using**: 2.1.4-debug

**Can you reproduce the issue with our latest release version**: unknown

**Can you reproduce the issue with the latest code from `master`**: unknown

**Are you using the demo app or your own custom app**: shaka-player-demo.appspot.com

**If custom app, can you reproduce the issue using our demo app**: N/A

**What browser and OS are you using**: Chrome 58 on Windows 10

**What are the manifest and license server URIs**: https://media.axprod.net/TestVectors/v8-MultiContent/Clear/Manifest.mpd

**What did you do?**

* Entered URL and hit Load.
* Change audio language to `x-popmusic`
* Set video quality to 360p level
* Seek around within the first period (12 minutes or approximately the first third of the content)
* Or just wait - sometimes it appears without any seeking

Issue is erratic. The above steps seem to reproduce it semi-reliably on my PC but they seem very arbitrary to me.

**What did you expect to happen?**

Normal playback without any funny business or errors.

**What actually happened?**

```
Invalid cue times: Infinity - Infinity
shaka.media.TextEngine.makeCue @ text_engine.js:109
shaka.media.Mp4VttParser.assembleCue_ @ mp4_vtt_parser.js:314
shaka.media.Mp4VttParser.parseVTTC_ @ mp4_vtt_parser.js:287
shaka.media.Mp4VttParser.parseMedia @ mp4_vtt_parser.js:182
(anonymous) @ text_engine.js:173
streaming_engine.js:1281 Assertion failed: Should only receive a Shaka error
(anonymous) @ streaming_engine.js:1281
streaming_engine.js:1295 (text:33) failed fetch and append: code=undefined
(anonymous) @ streaming_engine.js:1295
player.js:2470 Assertion failed: Wrong error type!
shaka.Player.onError_ @ player.js:2470
(anonymous) @ streaming_engine.js:1304
main.js:488 Player error TypeError: Cannot read property 'startTime' of null
    at shaka.media.TextEngine.<anonymous> (text_engine.js:176)
    at <anonymous>
shakaDemo.onError_ @ main.js:488
shakaDemo.onErrorEvent_ @ main.js:479
shaka.util.FakeEventTarget.dispatchEvent @ fake_event_target.js:117
shaka.cast.CastProxy.playerProxyLocalEvent_ @ cast_proxy.js:529
shaka.util.FakeEventTarget.dispatchEvent @ fake_event_target.js:117
shaka.Player.onError_ @ player.js:2473
(anonymous) @ streaming_engine.js:1304
```

Exploration of the code indicates that the error appears to be due to `this.timescale_` being null in mp4_vtt_parser.js:184, which leads to an infinity being generated for start/end timestamps. The timescale in `mdhd` is 1000, so it is not clear to me why a null value exists in this variable.

**Comment by joeyparrish** [comment]
The fix for this has been cherry-picked and will be released in v2.1.5.
