### ISSUE TITLE
2nd period of v8-MultiContent does not start

### ISSUE THREAD

**Issue by sandersaares** [google/shaka-player#911]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**: yes

**What version of Shaka Player are you using**: 2.1.4-debug

**Can you reproduce the issue with our latest release version**: unknown

**Can you reproduce the issue with the latest code from `master`**: unknown

**Are you using the demo app or your own custom app**: shaka-player-demo.appspot.com

**If custom app, can you reproduce the issue using our demo app**: N/A

**What browser and OS are you using**: Chrome 58 on Windows 10

**What are the manifest and license server URIs**: https://media.axprod.net/TestVectors/v8-MultiContent/Clear/Manifest.mpd

**What did you do?**

* Press Load
* Seek to near end of first period and wait until first period ends (12 minutes and 13 seconds)

**What did you expect to happen?**

Playback continues into 2nd period.

**What actually happened?**

Playback stops and loading spinner appears, remaining forever. Nothing noteworthy in console.

**Comment by theodab** [comment]
I've tried that manifest with bitmovin's HTML5 player and with dash.js, and it didn't work on either of them. So it might be bad content. I'll investigate more.

**Comment by joeyparrish** [comment]
The fix for this has been cherry-picked and will be released in v2.1.5.
