### ISSUE TITLE
RESTRICTIONS_CANNOT_BE_MET is thrown in IE11

### ISSUE THREAD

**Issue by OrenMe** [google/shaka-player#912]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**:
Yes
**What version of Shaka Player are you using**:
2.1.3, 2.1.4
**Can you reproduce the issue with our latest release version**:
Yes
**Can you reproduce the issue with the latest code from `master`**:
will try and update
**Are you using the demo app or your own custom app**:
Demo
**If custom app, can you reproduce the issue using our demo app**:

**What browser and OS are you using**:
Win10, IE11
**What are the manifest and license server URIs**:
[Link to demo app](https://shaka-player-demo.appspot.com/demo/#asset=https://qa-nginx-vod.dev.kaltura.com/edash/p/4171/sp/417100/serveFlavor/entryId/0_2jiaa9tb/v/2/flavorId/0_,ujs8h5pq,cf9m7hw9,4u0xdczl,qmnf9ic4,p8zzc094,i6syf25p,kd5r6b9c,y5h9dvc1,gcgssdfu,/forceproxy/true/name/a.mp4.urlset/manifest.mpd;license=https://udrm2.dev.kaltura.com/cenc/playready/license?custom_data=eyJjYV9zeXN0ZW0iOiJPVlAiLCJ1c2VyX3Rva2VuIjoiWTJGak5UYzFaV0V5WTJWaE1EZ3pZMlkwTmpZeFlUQTJaVGt3TmpoaU5UUmtOVEF6TUdFek4zdzBNVGN4T3pReE56RTdNVFE1T0RVMU9UZzRNVHN3T3pFME9UZzBOek0wT0RFdU56a3lNVHN3TzNacFpYYzZLaXgzYVdSblpYUTZNVHM3IiwiYWNjb3VudF9pZCI6IjQxNzEiLCJjb250ZW50X2lkIjoiMF8yamlhYTl0YiIsImZpbGVzIjoiMF9wOHp6YzA5NCwwX2k2c3lmMjVwLDBfOTF1cDc0aXosMF9wc2JyN3dmNywwX3VqczhoNXBxLDBfY2Y5bTdodzksMF80dTB4ZGN6bCwwX3FtbmY5aWM0LDBfZjU2dGV2ZTIsMF83ZTNqNmVpYyJ9&signature=AHt07oLTZ9psE%2BxRiuN4NdheTcQ%3D&files=MF91anM4aDVwcSwwX2NmOW03aHc5LDBfNHUweGRjemwsMF9xbW5mOWljNA%3D%3D&;lang=en-US)
(License is valid for 24 hours)
**What did you do?**
Load manifest and hit play

**What did you expect to happen?**
Smooth playback

**What actually happened?**
Takes time to start playback, and RESTRICTIONS_CANNOT_BE_MET error is thrown

**Comment by forbesjo** [comment]
Sounds similar to https://github.com/google/shaka-player/issues/890 is resolved with https://github.com/google/shaka-player/commit/4aa2430a1b6cae7331cb6b2a51c0faea0dad82c4

**Comment by OrenMe** [comment]
Thanks @forbesjo.
Is there a scheduled release date for a fix?

**Comment by TheModMaker** [comment]
That change is already available if you use `master`; it will also appear in the v2.1.5 release, which will probably be released later next week.

**Comment by OrenMe** [comment]
thanks @TheModMaker
