### ISSUE TITLE
Playback freezes at end of video in Edge/IE11

### ISSUE THREAD

**Issue by forbesjo** [google/shaka-player#913]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**: 
Yes

**What version of Shaka Player are you using**:  
2.1.4

**Can you reproduce the issue with our latest release version**: 
Yes

**Can you reproduce the issue with the latest code from `master`**: 
Yes

**Are you using the demo app or your own custom app**: 
Custom

**If custom app, can you reproduce the issue using our demo app**: 
Yes

**What browser and OS are you using**: 
IE11 and Edge 38.14393.1066.0, Windows 10

**What are the manifest and license server URIs**: 
http://dash.edgesuite.net/akamai/bbb_30fps/bbb_30fps.mpd (this issue does not happen with other test content)

*(you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*

**What did you do?**
Seek near the end of the video and let the video finish.

**What did you expect to happen?**
Playback to end and set the player in an ended state

**What actually happened?**
Playback stops at 633.9008751. Duration is 634.5666666. 
End of the video buffer is 634.5666666, end of audio is 634.3547499.

**Comment by forbesjo** [comment]
Note that this source has never played through to the end in any version of the Shaka Player. It does in dash.js and native Edge playback.

**Comment by TheModMaker** [comment]
This is a platform bug.  We call `MediaSource.endOfStream` to indicate that no more content is coming.  The browser should update the `duration` to match the already buffered content, but sometimes it doesn't.  In this case, IE/Edge is stopping, waiting for more content.

You may want to [file a bug](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/) on Edge to fix it.  We will look into trying to work around it.

**Comment by joeyparrish** [comment]
IE and Edge are correctly truncating the duration to the largest of the buffered ranges for audio & video.  It's not obviously a platform bug as we previously thought.

**Comment by joeyparrish** [comment]
If we comment out setBuffering() in Playhead, the problem disappears.  This is called by PlayheadObserver, which calculates when we should or shouldn't be buffering.  So PlayheadObserver is sending Player into a buffering state on IE & Edge, when it shouldn't.

In this case, audio SourceBuffer ends at 634.35, video ends at 634.56, and duration is 634.46.  On Chrome, video.buffered is (surprisingly) the larger of the two, while on IE it's the smaller of the two SourceBuffers.  This calculation:

```js
  var atEnd = (bufferEnd >= duration) || this.video_.ended;
```

is therefore true on Chrome and false on IE.

**Comment by joeyparrish** [comment]
In `PlayheadObserver`, the local value `duration` is the video duration minus a fudge factor of 0.1 seconds (`shaka.media.PlayheadObserver.FUDGE_FACTOR_`), but the actual discrepancy for this content is 0.21 seconds.

The real source of truth is `mediaSource.readyState`, which is `'ended'`.  Ideally, we would use this instead of comparing buffered ranges to the duration.

**Comment by joeyparrish** [comment]
Cherry-picked for v2.1.7.
