### ISSUE TITLE
Does Shaka support HLS tags EXT-X-SESSION-KEY and EXT-X-DISCONTINUITY?

### ISSUE THREAD

**Issue by chrisfillmore** [google/shaka-player#914]
Hi folks,

We're trying to assess if Shaka is feasible for our HLS needs. Does Shaka's HLS support include support for the following tags:

EXT-X-SESSION-KEY
EXT-X-DISCONTINUITY

These guys didn't turn up in my search of the HLS parser plugin. I don't know a lot about HLS so please let me know if you need more detail and I can get it.

Thanks!

**Comment by ismena** [comment]
Hi @chrisfillmore,

Not at the moment. :( 

We have ad support on our roadmap later this year or in early 2018 I think, which should cover EXT-X-DISCONTINUITY.

I think we should be able to add support for EXT-X-SESSION-KEY earlier than that. Let me open a separate issue for it. I'll tentatively schedule it for v2.3.

**Comment by chrisfillmore** [comment]
Thanks @ismena !

**Comment by ismena** [comment]
@chrisfillmore We are likely to start looking at EXT-X-SESSION-KEY support soon. Do you think you might be able to privately share some content that has it with us for testing purposes?

**Comment by chrisfillmore** [comment]
@ismena looks like our live content uses it. It's not simple to share because there is a custom authorization process, but I can send you an email and provide you with a demo app to test with. I wasn't sure which email was yours, from looking at the CONTRIBUTORS file. Should I email shaka-player-issues?

**Comment by ismena** [comment]
Yes, shaka-player-issues would be great, thanks for your help!

**Comment by ismena** [comment]
+ @theodab as the most likely candidate to work on this :)

**Comment by chrisfillmore** [comment]
Wait @ismena I wasn't thinking -- the content is HLS-FP, but Shaka doesn't have FP support yet. Wouldn't EXT-X-SESSION-KEY denote FP content? How will this work?

**Comment by ismena** [comment]
If your content is FP-enrypted it won't work for now (you can follow the whole FP development drama in #382 if you're interested).

EXT-X-SESSION-KEY tag itself is not restricted to FairPlay, so we can still have it working with other encryption types, which probably doesn't help with your use case though :/

**Comment by chrisfillmore** [comment]
Darn, we have some HLS-PR content but it doesn't use EXT-X-SESSION-KEY. Sorry!

**Comment by ismena** [comment]
No worries :)
