### ISSUE TITLE
Regression in playback of live dash

### ISSUE THREAD

**Issue by yairans** [google/shaka-player#916]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**: Yes

**What version of Shaka Player are you using**: latest

**Can you reproduce the issue with our latest release version**: yes

**What browser and OS are you using**: Mac/chrome

**What are the manifest and license server URIs**:
*(you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*

sent in mail

**What did you do?**
load the manifets

**What did you expect to happen?**
playback

**What actually happened?**
The player is stuck.
If I change the video tag currentTime it starts to play.

note, in version 2.0.6 it works

**Comment by theodab** [comment]
I've reproduced this. This bug appears to have been introduced in 
e5ce395f37c9a57d7aa4601f7eb578afaf030617, where we added gap jumping.

**Comment by joeyparrish** [comment]
Fix cherry-picked for v2.1.6.
