### ISSUE TITLE
Make switch buffer size configurable like stream buffer size

### ISSUE THREAD

**Issue by allenevans** [google/shaka-player#92]
The switch buffer size is currently set to equal the stream buffer size.

When using a large buffer size e.g. `player.setStreamBufferSize(60);` I notice that the console reports `Assertion failed: Not enough data buffered to switch smoothly!` about 3 - 5 seconds into playback. This warning is not reported when using a stream buffer size of 15 seconds.

I propose to add the following apis on `player.js`:

`getSwitchStreamBufferSize()`
`setSwitchStreamBufferSize(bufferSizeInSeconds)`

This will allow us to configure Shaka at runtime to use a much smaller buffer during switching operations.

**Comment by joeyparrish** [comment]
Sorry for the delay in my response.

We're busy working on a major refactor (#51) right now, and one of the goals is actually to do away with buffering on switch.  The plan is to simply fetch the next segment from the new Representation.  If Representations are unaligned, the segment from the new Representation will partially overwrite the last buffered segment in the SourceBuffer.

Would this address your needs without the extra knobs?

**Comment by allenevans** [comment]
For now, we can wait until #51 has been resolved to see if this change is required.

I've put together a commit on our fork <https://goo.gl/m19pyh> that we intend to use for Shaka 1.3.1 and review this when 1.4.0 is released.

**Comment by joeyparrish** [comment]
Okay, sounds good.  We should see the first part of #51 land this week.
