### ISSUE TITLE
Error building as root

### ISSUE THREAD

**Issue by ssaguiar** [google/shaka-player#920]
I am trying to install the player in my Ubuntu ver 14 server, so I can play my camera stream to test dash.
I am comp[iling it as root because it will placed in my apache's http folder.

I get this error message after a while:

/mnt/sdc1/html/shaka-player# python build/all.py
[INFO] Generating Closure dependencies...
[INFO] Running Closure linter...
187 files checked, no errors found.
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone -q git://github.com/yaniswang/HTMLHint.git /root/.npm/_cacache/tmp/git-clone-20dba5fc
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-20dba5fc': Permissão negada
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-07-09T17_16_12_068Z-debug.log
Traceback (most recent call last):
  File "build/all.py", line 44, in <module>
    shakaBuildHelpers.run_main(main)
  File "/mnt/sdc1/html/shaka-player/build/shakaBuildHelpers.py", line 292, in run_main
    sys.exit(main(sys.argv[1:]))
  File "build/all.py", line 30, in main
    code = check.main([])
  File "/mnt/sdc1/html/shaka-player/build/check.py", line 156, in main
    elif not check_html_lint():
  File "/mnt/sdc1/html/shaka-player/build/check.py", line 69, in check_html_lint
    if not shakaBuildHelpers.update_node_modules():
  File "/mnt/sdc1/html/shaka-player/build/shakaBuildHelpers.py", line 270, in update_node_modules
    execute_get_output([cmd, 'install'])
  File "/mnt/sdc1/html/shaka-player/build/shakaBuildHelpers.py", line 143, in execute_get_output
    raise subprocess.CalledProcessError(obj.returncode, args[0], stdout)
subprocess.CalledProcessError: Command 'npm' returned non-zero exit status 1

Can somebody help telling what I am doing rong?
I Apologise if this is not the right place to ask such question.

Anyway thank you very much

Sergio

**Comment by ssaguiar** [comment]
Just got it:

in place of:
 python build/all.py

I did:
sudo python build/all.py

**Comment by joeyparrish** [comment]
We don't normally recommend building as root, but I'm glad you were able to solve it.  Is it okay to close this issue now, or is there something else we can do for you?

**Comment by ssaguiar** [comment]
Thank you very much. It's ok to close the issue.
I apologise for my mistake.

**Comment by joeyparrish** [comment]
No worries!
