### ISSUE TITLE
Segment Requests are not being cancelled/aborted on custom retryParameters

### ISSUE THREAD

**Issue by worg** [google/shaka-player#922]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**:

Yes
**What version of Shaka Player are you using**:

2.1.4

**Can you reproduce the issue with our latest release version**:
Yes

**Can you reproduce the issue with the latest code from `master`**:
Not tried

**Are you using the demo app or your own custom app**:
Works on demo app

**If custom app, can you reproduce the issue using our demo app**:
Yes

**What browser and OS are you using**:
Firefox/Chrome

**What are the manifest and license server URIs**:
*(you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*

**What did you do?**
use this config for streaming retry parameters:
```
retryParameters: {
      timeout: 1000,
      maxAttempts: 6,
      baseDelay: 500,
      backoffFactor: 2,
      fuzzFactor: 0.5,
    }
```

**What did you expect to happen?**
Segment requests that take longer than 1s should be cancelled/aborted and retried 'till maxAttempts
are met.

**What actually happened?**
Requests aren't cancelled [on non live content] and are retried, somehow this puts the player on loop

**Comment by vhuerta** [comment]
+1

**Comment by msol** [comment]
@joeyparrish Hi Joey, can u help us? Please

**Comment by joeyparrish** [comment]
Hi all, I am looking into this now.  I believe this issue, #762, and #937 are all one and the same.  I apologize for the delay.

**Comment by joeyparrish** [comment]
When I set the timeout low (for my fast connection, this is 100ms), I definitely see requests being canceled and retried.  For VOD, this eventually leads to a timeout error and no more retries.  For live, the player keeps trying based on the `infiniteRetriesForLiveStreams` configuration.

Is the issue that requests aren't being canceled?  Or that we (based on `player.isLive()` and configuration) may continue to try streaming?  You shouldn't see infinite retries for VOD.

How are you setting your retryParameters?  The `retryParameters` config exists separately for streaming, manifest, and drm requests.  This is the correct way to set it for streaming (segment requests):

```js
// In your own app:
player.configure({
  streaming: {
    retryParameters: { timeout: 100 }
  }
});

// In the JS console of the demo, before clicking the Load button:
debugConfig = {
  streaming: {
    retryParameters: { timeout: 100 }
  }
};
```

This would result in an error log of `Invalid config, unrecognized key .retryParameters`:

```js
player.configure({
  retryParameters: { timeout: 100 }
});
```

If you are using a compiled build, you are missing those error logs.

Does any of this help?

**Comment by joeyparrish** [comment]
I've also tagged you all in #960, in which I've proposed a general solution to retry behavior.  Separate from this timeout issue, your feedback on my proposal would be very welcome.  Thanks!

**Comment by worg** [comment]
Thanks @joeyparrish we'll be posting our feedback there!
