### ISSUE TITLE
Support tts:displayAlign on TTML

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#923]
Is possible add for support tts:displayAlign on TTML? This style is used for subtitle position.

Sample: https://shaka-player-demo.appspot.com/demo/#asset=https://irtdashreference-i.akamaihd.net/dash/live/901161/bfs/manifestARD.mpd;lang=es;play

Specification: https://www.w3.org/TR/ttaf1-dfxp/#style-attribute-displayAlign

**Comment by ismena** [comment]
That's a bit of a tricky question.
We use VTT cues to display text: https://w3c.github.io/webvtt/#vttcue and there is nothing in the interface that displayAlign could directly translate to. Looking at the doc I think we could arguably translate it to VttCue.positionAlign, but it's not supported by browsers at this point (hopefully it will be eventually), so it setting it will have no effect :(

We can still do it so it works once browsers implement it, but I'm afraid that's about the best we can do now.

On a related note: we're currently working on separating out text parsing and display logic so people can have custom text displayers, so I can make sure displayAlign is at least parsed if someone wants to use it in their custom display.
