### ISSUE TITLE
How can I style/brand the player ?

### ISSUE THREAD

**Issue by mhassanist** [google/shaka-player#926]
There are couple of things I'd like to control in the player. Things like: Style, Branding, Watermark and play speed control. I'm wondering if those features are available in the player or not even with a plugin.

**Comment by joeyparrish** [comment]
We don't currently provide a UI layer in the library, so you are already completely in control of styling and branding.  You can overlay things on top of the `<video>` element, as we do in our demo, and style them with CSS.  To turn off the browser's built-in video controls overlay, set `video.controls` to false in JavaScript or remove the `controls` attribute from the `<video>` element.

Play speed control is done through the HTML5 video API `video.playbackRate`.  Just set it to whatever you like.  If it goes into a buffering state, Shaka Player will set `playbackRate` to 0, then set it back to the your setting when playback resumes.

Does this answer your question?

**Comment by mhassanist** [comment]
It does. Thanks a lot.
