### ISSUE TITLE
Support styles on TTML

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#927]
Is it possible to support TTML styles?

tts:backgroundColor = <ebuttdt:distributionColorType>
tts:color = <ebuttdt:distributionColorType>
tts:direction = ( 'ltr' | 'rtl' )
tts:fontFamily = As defined in TTML 1.0, section 8.2.8
tts:fontSize = <ebuttd:distributionLengthType>
tts:fontStyle = ( 'normal' | 'italic' )
tts:lineHeight = ('normal' | <ebuttd:distributionLengthType>)
tts:fontWeight = ( 'normal' | 'bold' )
tts:textDecoration = ( 'none' | 'underline' )
tts:wrapOption = ( 'wrap' | 'noWrap' )

Specification of EBU-TT-D: https://tech.ebu.ch/docs/tech/tech3380.pdf

Sample with some of this styles: https://irtdashreference-i.akamaihd.net/dash/live/901161/bfs/manifestARD.mpd

More info: http://subtitling.irt.de/ website with dash-if player with previous stream and styled subtitles

**Comment by ismena** [comment]
We don't do text rendering at the moment, but we might start in the future as part of our UI effort. (We don't have the scope and timeline for that defined yet).

The best answer I can give now is same as with #923. I can make sure we parse these setting in TtmlParser and have them on our internal object representing a text cue once we transition to separate text parsing and display. If you'd like to have a custom text displayer, you'll be able to incorporate the settings.

If writing a custom plugin to display text is something that interests you, I can give you a heads up once the change to make it possible has landed.

**Comment by avelad** [comment]
Thanks @ismena. I'm interested on a custom plugin to display styled text. Once it is possible, can you indicate the steps to follow?

**Comment by ismena** [comment]
@avelad will do! I'm hoping to land the change by the end of this week and I'll follow up with you once it's done.

**Comment by avelad** [comment]
@ismena, I have seen your commits, but I do not see support for tts:direction = ( 'ltr' | 'rtl' ), is it intentional?

**Comment by ismena** [comment]
@avelad It seems I confused it with 'tts:writingMode' and though we already had support for it. Now when I look at it actually, I'm not sure I understand what is the significant difference between tts:direction and tts:writingMode.
Would you have any insight?

FYI, we're preparing an upgrade guide for v2.2 which will have details on the new parser/displayer system and the steps to upgrade.

**Comment by avelad** [comment]
@ismena 
Specs:
tts:writingMode --> https://www.w3.org/TR/ttaf1-dfxp/#style-attribute-writingMode
tts:direction --> https://www.w3.org/TR/ttaf1-dfxp/#style-attribute-direction

I think that direction attribute has a direct translation to css with https://www.w3schools.com/cssref/pr_text_direction.asp and writingMode attribute allow the same as direction atribute plus vertical modes.

Some packagers use direction attribute for use in the same stream arabic and english for example.

**Comment by avelad** [comment]
@ismena do you have any update about my previous comment?

**Comment by ismena** [comment]
Sorry for the delay, I'll try to address this today.

**Comment by ismena** [comment]
Okay, done :)
We are now parsing tts:direction attribute into our writingDirection setting.

Let me know if you have any questions!
