### ISSUE TITLE
Shaka Player Tutorial DRM COntent Fails to Play

### ISSUE THREAD

**Issue by NeilHollingum** [google/shaka-player#928]
I have read the FAQs and they do not help.
I am trying to run the Shaka player DRM tutorials with version of Shaka from Git Hub loaded on 7th July.
I am running on Chrome Browser and have tried on Windows 7 and Windows 10 with same results.

My Java Script as per tutorial for License Server Authentication:-

// myapp3.js
var manifestUri = '//storage.googleapis.com/shaka-demo-assets/sintel-widevine/dash.mpd';
var licenseServer = '//cwip-shaka-proxy.appspot.com/no_auth';

function initApp() {
  // Install built-in polyfills to patch browser incompatibilities.
  shaka.polyfill.installAll();

  // Check to see if the browser supports the basic APIs Shaka needs.
  if (shaka.Player.isBrowserSupported()) {
    // Everything looks good!
    initPlayer();
  } else {
    // This browser does not have the minimum set of APIs we need.
    console.error('Browser not supported!');
  }
}

function initPlayer() {
  // Create a Player instance.
  var video = document.getElementById('video');
  var player = new shaka.Player(video);

  // Attach player to the window to make it easy to access in the JS console.
  window.player = player;

  // Listen for error events.
  player.addEventListener('error', onErrorEvent);

    player.getNetworkingEngine().registerRequestFilter(function(type, request) {
    // Only add headers to license requests:
    if (type == shaka.net.NetworkingEngine.RequestType.LICENSE) {
      // This is the specific header name and value the server wants:
      request.headers['CWIP-Auth-Header'] = 'VGhpc0lzQVRlc3QK';
    }
  });
  
    player.configure({
    drm: {
      servers: { 'com.widevine.alpha': licenseServer }
    }
  });
  
  // Try to load a manifest.
  // This is an asynchronous process.
  player.load(manifestUri).then(function() {
    // This runs if the asynchronous load is successful.
    console.log('The video has now been loaded!');
  }).catch(onError);  // onError is executed if the asynchronous load fails.
}

function onErrorEvent(event) {
  // Extract the shaka.util.Error object from the event.
  onError(event.detail);
}

function onError(error) {
  // Log the error.
  console.error('Error code', error.code, 'object', error);
}

Ran the Web Page:-
<!DOCTYPE html>
<html>
  <head>
    
    <script src="third_party/closure/goog/base.js"></script>
    
    <script src="dist/deps.js"></script>
    
    <script src="shaka-player.uncompiled.js"></script>
	
    
    <script src="myapp3.js"></script>
  </head>
  <body>
    <video id="video"
           width="640"
           poster="//shaka-player-demo.appspot.com/assets/poster.jpg"
           controls autoplay></video>
  </body>
</html>

I expected the vidoe to play but got  error code 6001

"Error code 6001 object shaka.util.Error {severity: 2, category: 6, code: 6001, data: Array(0), message: "Shaka Error DRM.REQUESTED_KEY_SYSTEM_CONFIG_UNAVAILABLE ()"…}
onError @ myapp3.js:61"

Can Anybody help ?

**Comment by joeyparrish** [comment]
If you look up [the docs for error code 6001](https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html#value:6001), you'll see this:

> None of the requested key system configurations are available. This may happen under the following conditions:
>  - The key system is not supported.
>  - The key system does not support the features requested (e.g. persistent state).
>  - A user prompt was shown and the user denied access.
>  - The key system is not available from unsecure contexts. (ie. requires HTTPS) See https://goo.gl/EEhZqT.

This last point is probably the one affecting you.

In the nightly build, we have added a section to [the DRM config tutorial](https://nightly-dot-shaka-player-demo.appspot.com/docs/api/tutorial-drm-config.html) called "EME and http URLs", which says this:

> EME requires a secure URL to use.  This means you have to use `https` or be on `localhost`.  Currently only Chrome enforces it, but other browsers will in the future.  Also, because of mixed content requirements, if your site is using `https`, then your manifest and every segment will also need to use `https` too.
> 
> See: Chrome's [announcement][], Firefox's [intent to remove][firefox_bug], and how to [disable for testing][allow_http].

[allow_http]: https://www.chromium.org/Home/chromium-security/deprecating-powerful-features-on-insecure-origins
[announcement]: https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/tXmKPlXsnCQ/ptOETCUvBwAJ
[firefox_bug]: https://bugzilla.mozilla.org/show_bug.cgi?id=1322517

I think this should be called out more explicitly at the top of each DRM-related tutorial.  Would this help?

**Comment by joeyparrish** [comment]
I moved some things around in the docs to make this more clear.  The changes to the docs have been cherry-picked and will be released in v2.1.5.  Please let me know if this helps.

**Comment by NeilHollingum** [comment]
Thanks for your help. With the references on what you sent I was able to solve my problems.

 

Best Regards

 

Neil Hollingum

**Comment by joeyparrish** [comment]
Glad we could help!

**Comment by NeilHollingum** [comment]
Thanks for your help – I have found a solution to my problems.

 

Best Regards

 

Neil Hollingum
