### ISSUE TITLE
Configure player method

### ISSUE THREAD

**Issue by allenevans** [google/shaka-player#93]
It would be nice to have a generalized configure method on the player which accepts an object literal to specify values such as buffer size.

`var mediaPlayer = new shaka.player.Player(videoElement);`
`mediaPlayer.setStreamBufferSize(120);`

would become:

`var mediaPlayer = new shaka.player.Player(videoElement);`
`mediaPlayer.configure({ streamBufferSize : 120 });`

One significant advantage of doing this will be to reduce coupling to the specific player api methods. For example, if setStreamBufferSize was renamed to setBufferSize, the player would break whereas changing the name in the object literal will simply mean the values are ignored and playback would continue.

This would be helpful when A/B testing between player versions.

**Comment by joeyparrish** [comment]
I agree completely.  Configuration methods that did not already exist on Player in v1.3.1 could be moved purely to the new configure() interface.  Other configuration methods could be rewritten to delegate to configure internally, and would then be closure-annotated with "deprecated".
