### ISSUE TITLE
Stream incompatible with Shaka v2

### ISSUE THREAD

**Issue by dobrusev** [google/shaka-player#933]
I have a stream that doesn't play with Shaka v2 but plays with Shaka v1.
I see this logs in a loop in the demo player and the playback doesn't start.

(audio:11) looking up segment: presentationTime=207149.5926668644 currentPeriod.startTime=0
log_section.js:73 (video:2) looking up segment: presentationTime=207149.60766673088 currentPeriod.startTime=0

**What version of Shaka Player are you using**:
Tried Shaka v 2.1.5 stream doesn't start. Tried Shaka v1.6.2 playback is working. 

**Can you reproduce the issue with our latest release version**:
Yes I can reproduce the issue.

**Can you reproduce the issue with the latest code from `master`**:
Didn't try.

**Are you using the demo app or your own custom app**:
I'm using the demo app.

**What browser and OS are you using**:
Chrome Version 59 mac OS 10.12.5

**What are the manifest and license server URIs**:
sent to email address.

**What did you do?**
Run the demo app with custom manifest.

**What did you expect to happen?**
Have playback

**What actually happened?**
No playback starts, manifest is requested every few seconds and logs in consoles are.
"(audio:11) looking up segment: presentationTime=207149.5926668644 currentPeriod.startTime=0
log_section.js:73 (video:2) looking up segment: presentationTime=207149.60766673088 currentPeriod.startTime=0"

I have different manifest with the same content that works on the latest Shaka player:
sent to email address. 

Additional information:
the content is 24/7 stream. After recreating the manifest the player starts playing the content, so my suggestion is something with the time desync but we need to confirm what is the root cause of the issue and that player will not stop playing the content after awhile.

Where the differences comes from?

Thank you in advance and keep the good work!

**Comment by joeyparrish** [comment]
I don't see any major clock sync issues when I analyze the content, and it does play for me in the demo.

**Comment by joeyparrish** [comment]
Can you provide any other information?  Are there any additional steps I should take?

Since your manifest URL is private, I've sent you back a private repro link from the demo app to show what I'm doing.

**Comment by dobrusev** [comment]
@joeyparrish I provide you manifest from another DC that doesn't play with the test player.

After "recreating" the manifest the link that I previously provided started working for me as well.
We want to get to the bottom of the issue because we want to make sure that all the manifests are playing.

regards

**Comment by joeyparrish** [comment]
I analyzed the failing manifest and found that the presentation timeline differs from the segment references by 72454 seconds (a little over 20 hours).  So this appears to be either a clock sync issue or massive drift.

Can you tell us what encoder/packager you're using?  Have you checked for updated encoder/packager software?

The DASH spec allows for segment reference times to be "approximate", and goes on to define that as +/- 0.5 segment lengths.  20 hours is obviously much more inaccuracy than is allowed by the spec, so I believe the encoder/packager is at fault.

**Comment by dobrusev** [comment]
AWS Elemental Delta is the Packager. 

I forwarded the results from your investigation to the content provider.

Thank you once again for the fast and accurate response!

**Comment by joeyparrish** [comment]
Happy to help!  Do you mind if we close this bug now, or is there something else we can do to help?

**Comment by joeyparrish** [comment]
@dobrusev, we have decided to detect and attempt to correct issues like this in the player.  Can you make your stream available to us again for testing?

**Comment by dobrusev** [comment]
I will ask the content provider to return back the content.

**Comment by joeyparrish** [comment]
Thank you!

**Comment by dobrusev** [comment]
@joeyparrish We can give you an un-encrypted endpoint but the stream will work.
We tried, and we can't recreate the issue, that's why it was hard to see what was going on, it was just a one off. WeI can give you a copy of the incorrect manifest?

**Comment by joeyparrish** [comment]
A static copy of the broken manifest would not be sufficient for me to test my workaround.  I would need to test that I am able to play the content in spite of the manifest being incorrect.

If you can't recreate the issue, I will just have to proceed with unit testing and simulation, instead.  Thanks!

**Comment by joeyparrish** [comment]
The workaround is being reverted.  The timeline correction is actually making things worse in some cases.  Details in the commit message.
