### ISSUE TITLE
Add headers to the DRM License request

### ISSUE THREAD

**Issue by sarge** [google/shaka-player#94]
Hi , I would like to pass custom headers as part of the DRM license request.

Currently authentication cookies can be passed, but it would be handy if an header based authentication scheme could also be supported.

My intention was to complete this work, extending the DrmSchemeInfo and LicenseRequest. Sound sensible?

CLA is in progress.

Cheers

Mark

**Comment by tdrews** [comment]
Hi,

Check out 6d08f0b97a381d8cc7e20ba2d9a2b60cba50b2e2 which addressed Issue #62. With this patch DrmSchemeInfo now takes a licensePreProcessor callback which can modify the raw license request and add additional headers to the request itself.

**Comment by sarge** [comment]
Thanks! I just spotted that myself.
