### ISSUE TITLE
Playready license server URL update

### ISSUE THREAD

**Issue by BucherTomas** [google/shaka-player#945]
With the move of Shaka demo to https, it is necessary to update URL of Playready license server in assets.js. The older server playready.directtaps.net does not support https and is no longer updated,  test.playready.microsoft.com supports https and should be used from now on, please see http://playready.directtaps.net/ .

The full license server URL for Tears of Steel (PlayReady) asset should be updated to 
//test.playready.microsoft.com/service/rightsmanager.asmx?PlayRight=1&UseSimpleNonPersistentLicense=1

**Comment by joeyparrish** [comment]
Thanks!  Would you care to send a PR?

**Comment by BucherTomas** [comment]
One of you in the Shaka team can replace the URL with the one above and commit it in two minutes flat :) .

No need to add myself with that one line to the contributors which, from what I gathered, is a mandatory step for PR.

**Comment by joeyparrish** [comment]
No contribution is too small!

**Comment by joeyparrish** [comment]
This has been cherry-picked for v2.1.6.
