### ISSUE TITLE
ABR adapts across variants with different roles

### ISSUE THREAD

**Issue by bhh1988** [google/shaka-player#947]
If a video has multiple audio tracks, each with different roles (but with the same language), and there's no role-preference given, then the player is initialized with all of them as part of the same variant pool. The simple_abr_manager will then just adapt across them, so you could end up with different audio tracks playing in and out.

I have a fix for this, but I want to pose a more general question: was it an intentional design decision to not include the adaptation-set's ID into the variants? Technically according to the DASH spec, a player should not adapt across two different adaptation sets of the same type. But because the adaptation-set information is not currently captured in the "variants" structure, it's impossible for ABR to do the correct thing. Right now, we have to resort to using language/role combo as a signal for whether things are in the same adaptation-set or not, and this maybe tends to be fairly accurate but obviously can be not enough too.

**Comment by joeyparrish** [comment]
The fix has been backported for v2.1.6.
