### ISSUE TITLE
Shaka 1.6.4 supports DRM for live streaming?

### ISSUE THREAD

**Issue by roticv** [google/shaka-player#956]
Hi,

I am wondering if Shaka 1.6.4 supports DRM for live streaming. I have been trying to figure out why it is not working and from reading the code, DashVideoSource doesn't seem to reference EmeManager.

Thanks!

Regards,
Victor

**Comment by roticv** [comment]
Looks like EmeManager is attached in Player.

**Comment by joeyparrish** [comment]
Yes, we supported DRM in live streams in v1.6, but we are no longer maintaining v1.  Please consider upgrading to v2:

https://shaka-player-demo.appspot.com/docs/api/tutorial-upgrade-v1.html
