### ISSUE TITLE
Getting Availability Start Time from Shaka Player

### ISSUE THREAD

**Issue by markus101** [google/shaka-player#957]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**:
Yes

**What version of Shaka Player are you using**:
2.1.2

I've been looking for a way to get the Availability Start Time (AST) back from Shaka for the manifest it has parsed, I saw this previous discussion from 2015 https://groups.google.com/forum/#!topic/shaka-player-users/FkBdCt8mOIU Is parsing the manifest outside of Shaka the best way to get the AST?

In my case I'm being provided a stream that contains multiple items in succession and I know when each item starts/ends. If I know the AST and current position I can determine which item in the stream is currently playing and display information about it to the user.

A method on the player would be helpful to me, but I'm not sure if that is something worthwhile for others.

**Comment by joeyparrish** [comment]
There is no way to get this currently, but it's easy to add.
