### ISSUE TITLE
Autoplay failure with Shaka v1.5 / v1.6 in Firefox v55

### ISSUE THREAD

**Issue by aleian84** [google/shaka-player#958]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**: Yes

**What version of Shaka Player are you using**: 1.5.0 / 1.6.5

**Can you reproduce the issue with our latest release version**: No

**Can you reproduce the issue with the latest code from `master`**: No

**Are you using the demo app or your own custom app**: My custom app

**If custom app, can you reproduce the issue using our demo app**: No

**What browser and OS are you using**: Firefox beta version 55.0

**What are the manifest and license server URIs**:
*(you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*

**What did you do?**
I update Firefox to version beta 55.0 and my websites stop to work. Until Firefox version 54 is installed my websites worked correctly. 
Websites : 
https://www.infinitytv.it/ --> shaka player 1.5.0
https://play.mediasetpremium.it/ --> shaka player 1.6.5

I see from firebug that the first chunk are downloaded and after all is blocked.

You know any problems with new version of Firefox?

**What did you expect to happen?**
My websites should work.

**What actually happened?**
My websites don't work.

**Comment by joeyparrish** [comment]
@aleian84, are you the developer of these sites?  Or a user?

**Comment by joeyparrish** [comment]
I am unable to access those two premium sites you linked above without a paid account.  If you are responsible for their development, perhaps you could grant me access to help debug.

Using our demo, I am unable to reproduce your results.  I find that the v1.5.0 and v1.6.5 demos are both working for me in both Firefox 54 and 55 on Linux:

https://v1-5-0-dot-shaka-player-demo.appspot.com/
https://v1-6-5-dot-shaka-player-demo.appspot.com/

If you are the developer of these sites, I would be happy to work with you to resolve the issue.

If you are a user, please contact the owners of the sites.  Let them know that they have an issue with Firefox beta 55, and that the Shaka Player team is ready to help if they need it.

**Comment by cpeterso** [comment]
Note that Mozilla updated the Widevine CDM to version 1.4.8.970 in Firefox Beta 56 ([Firefox bug 1380175](https://bugzilla.mozilla.org/show_bug.cgi?id=1380175)) and version 1.4.8.984 in Firefox Nightly 57 ([Firefox bug 1383611](https://bugzilla.mozilla.org/show_bug.cgi?id=1383611)). That wouldn't affect Firefox 54 or 55 unless perhaps these video streaming services have already started requiring a Widevine version before it is available in Firefox.

**Comment by aleian84** [comment]
Hi Joey, yes I am the developer. Can I send to you the credentials in a private message? Can you send to me your account email?

@cpeterso : attached you can find two request body from Infinity PROD for the same content with the same user, one with FF54, the other with FF55.
A diff between the two body:

-	In FF54: “architecture_name x86-32” in FF55: “architecture_name x86-64”
-	In both: “widevine_cdm_version             1.4.8.9032”
-	In FF54 there is a final “null” in FF55 there is some bytes instead of null

Hope this help.

**Comment by aleian84** [comment]
[PayloadGetWidevineFF55.txt](https://github.com/google/shaka-player/files/1207725/PayloadGetWidevineFF55.txt)
[PayloadGetWidevineFF54.txt](https://github.com/google/shaka-player/files/1207726/PayloadGetWidevineFF54.txt)

**Comment by joeyparrish** [comment]
Yes, please send credentials to shaka-player-issues@google.com.  The information will remain confidential.

**Comment by aleian84** [comment]
@Joey I've sent to you an email with the credentials.

Thank you for the support,
Alessio

**Comment by joeyparrish** [comment]
@aleian84, I get playback on Firefox 54, but not Firefox 55.  On both versions of Firefox, I see a successful license request and response.  When I parse the license response, I see both versions received the same keys.

So the issue does not seem to be with the license request/response, and the request payload differences seem to be a red herring.

Still digging.

**Comment by joeyparrish** [comment]
On both browser versions, I see a key status of 'usable'.  So the CDM has accepted the license response in both cases.  I think we can therefore eliminate the CDM as the root of the issue.

**Comment by joeyparrish** [comment]
In both versions, I see the video buffer starts at 0.08 and `autoplay` is set to true.

In Firefox 55, while the video is not playing, I see 15 seconds of video buffered.  `playbackRate` is 1, `paused` is true.  If I run `video.play()` in the console, playback starts.

So this seems to be a failure of autoplay on Firefox 55.  @cpeterso, this is very easy to reproduce with the credentials and access instructions @aleian84 gave me.  @aleian84, perhaps you could work with @cpeterso to give him access as well?

This should probably transition to a Mozilla bug now, but I will leave it to the two of you to start that process.  For now, I'm marking this as "external bug" in our tracker.

**Comment by aleian84** [comment]
Hi Joey, thank you for your analysis, it is very useful. Yes, I'm available to work with @cpeterso. @joey could you give the credentials that I've sent on private email to @cpeterso?

**Comment by joeyparrish** [comment]
Done.  Let me know what else I can do.

**Comment by aleian84** [comment]
Thank you @joeyparrish. 
I'm thinking to resolve the issue on my website (until Firefox doesn't work) forcing video.play() from my code only for version 55 of Firefox (if I'm able to recognize it). What do you think? It's the correct approach?

**Comment by joeyparrish** [comment]
That may work.  You may also be able to skip detecting Firefox 55 entirely.  Calling video.play() when it is already playing should not hurt anything.

Note that on some mobile platforms, play() may only be called from a user interaction event, such as a click event.

**Comment by aleian84** [comment]
Perfect Joey, I will follow this approach.

Thank you again, you're the best.

Alessio

**Comment by cpeterso** [comment]
I bisected this regression to @jyavenard's fix for [Firefox bug 1382303](https://bugzilla.mozilla.org/show_bug.cgi?id=1382303). That was a fix for a BBC Player autoplay bug. I filed [Firefox bug 1389844](https://bugzilla.mozilla.org/show_bug.cgi?id=1389844) to track this new regression in Firefox 55.

Note that the BBC autoplay fix was uplifted/backported to the [Extended Support Release (ESR) version of Firefox 52](https://www.mozilla.org/en-US/firefox/organizations/faq/), which will continue to receive security fixes until 2018 Q1. If you need to add a workaround for Firefox 55+, you should also enable the workaround for Firefox 52. Even though there is no programmatic way to distinguish ESR Firefox 52 (with the BBC fix) from regular Firefox 52 (without the BBC fix), you can safely assume that anyone visiting your website with Firefox 52 is using the ESR version. Anyone using the regular version of Firefox should have been updated to a newer version months ago.

**Comment by jyavenard** [comment]
I have responded to the bugzilla entry. The change found in Firefox 55 and not present in 54 is related to the handling of autoplay attribute and when playback would actually start (that is when the play and playing events would be fired).
In FF 54, playing would have been incorrectly fired immediately, even with readyState equal to HAVE_NOTHING. Per spec, playing should only be fired if readyState is greater or equal to HAVE_FUTURE_DATA.

While I haven't actually checked on the code that no longer work, it indicates to me that the player incorrectly waits on the **playing** or **play** event to be fired to perform a particular action.

play will only be fired if

1. play() is called or

2.  if the autoplay attribute is set and "the autoplay attribute has caused playback to begin."
(https://html.spec.whatwg.org/multipage/media.html#event-media-play)

The autoplay attribute is to start playback when 
https://html.spec.whatwg.org/multipage/media.html#ready-states

> If the new ready state is HAVE_ENOUGH_DATA
>     If the autoplaying flag is true, and the paused attribute is true, and the media element has an autoplay attribute specified, and the media element's Document's active sandboxing flag set does not have the sandboxed automatic features browsing context flag set, then the user agent may also set the paused attribute to false, queue a task to fire a simple event named play, and queue a task to fire a simple event named playing.

With MSE, we consider that we have enough data (readyState will move to HAVE_ENOUGH_DATA) if the source buffer contains more than 10s of continuous data (with a fuzz of +- 500ms, that is any gaps in the data lesser than 500ms are ignored)

So the solution here is add more than 10s of data, not wait on the playing event or manually call play()

Adding. Ore than 10s of data, is I believe the best approach, as it pretty much guarantees playback won't stall later

**Comment by jyavenard** [comment]
@joeyparrish wrote:
> In Firefox 55, while the video is not playing, I see 15 seconds of video buffered. playbackRate is 1, paused is true. If I run video.play() in the console, playback starts.

Hmmm. That shouldn't be. 15s is more than enough.

Please provide me a way to reproduce the problem, thank you

**Comment by joeyparrish** [comment]
@jyavenard, Chris copied you on an email a couple hours ago with the credentials and instructions.

**Comment by jyavenard** [comment]
I have written mochitest to check on the behaviour should more than 10s data be loaded, the canplay, play and playing events are always fired as soon as the sourcebuffer contains more than 10s of video data.

**Comment by jyavenard** [comment]
reproduced it, it's because the data doesn't start at 0 but 0.08s....

**Comment by jyavenard** [comment]
IssueS (there were two) have been fixed in Firefox Nightly 57, uplift for 56 and ESR 52 have been requested.

Thank you for reporting the issue.

this bug can be closed

**Comment by joeyparrish** [comment]
Firefox 56 release is [currently scheduled for September 26](https://wiki.mozilla.org/RapidRelease/Calendar).  We'll keep this open until then, so it is easier for developers to find this issue and avoid filing a duplicate.

Thank you so much for your help!

**Comment by joeyparrish** [comment]
Firefox 56 is currently stable.  Closing.  Thanks, everyone!
