### ISSUE TITLE
Unable to play Axinom multi-key demo assets on IE11

### ISSUE THREAD

**Issue by TheModMaker** [google/shaka-player#959]
**What version of Shaka Player are you using**:
v2.1.5 and Nightly

**Can you reproduce the issue with our latest release version**:
Yes

**Can you reproduce the issue with the latest code from `master`**:
Yes

**What browser and OS are you using**:
IE11, Windows 10

**What are the manifest and license server URIs**:
*(you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*
Axinom Multi-DRM, multi-key
Axinom Multi-DRM, multi-key, multi-Period

**What actually happened?**
Got a `DRM.FAILED_TO_GENERATE_LICENSE_REQUEST` error caused by a PatchedMediaKeysMs error.  The native error code is 1, MS_MEDIA_KEYERR_UNKNOWN.

**Comment by joeyparrish** [comment]
Marking external for now, asking Axinom for assistance debugging.

**Comment by joeyparrish** [comment]
Axinom reports that IE11 does not support encrypted media with no PSSH box in it.  It would seem that their v7 test vectors omit the PSSH box from the media, and only contain a PSSH in the manifest.

**Comment by joeyparrish** [comment]
This issue is still around.  The error I get today is still FAILED_TO_GENERATE_LICENSE_REQUEST.

**Comment by joeyparrish** [comment]
Closing this stale external (non-Shaka) issue. In particular, we will follow Microsoft's lead and stop supporting IE soon.
