### ISSUE TITLE
Explicitly disabling ABR when selecting tracks

### ISSUE THREAD

**Issue by bhh1988** [google/shaka-player#962]
Looking at the docs here: https://github.com/google/shaka-player/blob/master/docs/tutorials/upgrade-v2-0.md

The example shows calling player.configure() AFTER selectVariantTrack(), to disable ABR. That doesn't seem to work well in practice. It seems better to call player.configure() to disable ABR BEFORE calling selectVariantTrack(). I think either the docs should change to reflect that, or the code should change to reflect the docs - my guess is that the problem is that inside of player.js's applyConfig_() method chooseStreamsAndSwitch_() is called before actually disabling ABR. It seems that most any call to player.configure() will potentially undo a previous selectVariantTrack() call.

I was testing this on HEAD of master about one week ago.

**Comment by joeyparrish** [comment]
You are correct.  We disable ABR first in the demo app, so the docs are at fault.

**Comment by joeyparrish** [comment]
The fix has been cherry-picked for v2.1.7.
