### ISSUE TITLE
video-audio-caption download correlation

### ISSUE THREAD

**Issue by kuznetcoff777** [google/shaka-player#964]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**:yes

**What version of Shaka Player are you using**:v2.1.6

**Can you reproduce the issue with our latest release version**:yes

**Can you reproduce the issue with the latest code from `master`**:

**Are you using the demo app or your own custom app**:demo

**If custom app, can you reproduce the issue using our demo app**:

**What browser and OS are you using**:chrome/ff

**What are the manifest and license server URIs**:
*(you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*

**What did you do?**opened stream and waited

**What did you expect to happen?** stream must play as fast as possible

**What actually happened?** several seconds to wait additionally

I throttled chrome to low network speed and saw that palyer downloaded segments in this way:
video-fragment-1(downloaded)
audio-fragment-1(downloaded)
caption-fragment-1(downloaded)
audio-fragment-2(downloaded)
caption-fragment-2(downloaded)
audio-fragment-3(downloaded)
caption-fragment-3(downloaded)
audio-fragment-4(downloaded)
video-fragment-2(still downloading)
caption-fragment-4(downloaded)
audio-fragment-5(downloaded)
caption-fragment-5(downloaded)

So video/audio/caption downloading is not correllated. If player have no video, why downlaod audio and caption? The same problem i described at https://github.com/Dash-Industry-Forum/dash.js/issues/1319
Can you make same fix here? It will be very helpful for low speed users.

**Comment by joeyparrish** [comment]
From the [dash.js code you referenced](https://github.com/AkamaiDASH/dash.js/commit/f328c5477d3fa0baa078b8cb289fd36fd612b96a), it would seem that you want us to avoid buffering more audio than we have already buffered for video.  Is that correct?

Can you explain the problem a bit more?  Why is it wrong to buffer video and audio independently?

Do you expect us to wait until a video segment is buffered before fetching the corresponding audio segment?  Or fetch them simultaneously?

**Comment by kuznetcoff777** [comment]
"you want us to avoid buffering more audio than we have already buffered for video. Is that correct?" - correct
"Do you expect us to wait until a video segment is buffered before fetching the corresponding audio segment? Or fetch them simultaneously?" - both methods wiil be ok, because at the moment available bandwith is used for downloading future audio-captions, but this bandwith could be used to download necessary video segment:

**Comment by kuznetcoff777** [comment]
So, is it possible?

**Comment by joeyparrish** [comment]
I think this is feasible.  Tentatively scheduled for v2.3.

**Comment by joeyparrish** [comment]
We hadn't planned to work on this right now, but it came up while working on another issue.  It seems to help that other issue, and it is fairly simple, so we will clean it up and try to get it out soon.

**Comment by joeyparrish** [comment]
Fix cherry-picked to v2.3.5.

**Comment by kuznetcoff777** [comment]
@joeyparrish Thanks!
