### ISSUE TITLE
Calling Player#getStats before Player#load causes TypeError: Cannot read property 'getBandwidthEstimate' of null

### ISSUE THREAD

**Issue by chrisfillmore** [google/shaka-player#968]
Looks like this bug was introduced with this refactor:
https://github.com/google/shaka-player/commit/859130fd45caca2762ea8ef315f1c8f0a66650c8

**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**:
Yes

**What version of Shaka Player are you using**:
Latest from Master

**Can you reproduce the issue with our latest release version**:
No

**Can you reproduce the issue with the latest code from `master`**:
Yes

**Are you using the demo app or your own custom app**:
Demo app

**What browser and OS are you using**:
MacOS 10.12.6 Chrome v60

**What did you do?**
Called Player#getStats() after instantiating a Player object.

**What did you expect to happen?**
A stats object would be returned.

**What actually happened?**
Uncaught (in promise) TypeError: Cannot read property 'getBandwidthEstimate' of null
    at shaka.Player.getStats (player.js:1556)
    ...

This is reproducible in the demo app by making the following change:

```
var localPlayer = new shaka.Player(localVideo);
localPlayer.getStats(); // Add this line
```

**Comment by joeyparrish** [comment]
Confirmed on `master`.  Not present in v2.1.x.

**Comment by joeyparrish** [comment]
Should be fixed now.  Thanks!
