### ISSUE TITLE
Pressing pause for the first time fails to pause on Chromecast

### ISSUE THREAD

**Issue by theodab** [google/shaka-player#970]
The first time you press the pause button, if you're casting to Chromecast, video playback does not pause. Subsequent presses work as intended, until you reload the page.

**Comment by theodab** [comment]
I tried this out on a Chromecast with newer firmware. The problem didn't happen there, so it looks like it's a Chromecast bug of some sort. Once they update, this will no longer be a problem.

**Comment by theodab** [comment]
Specifically, it works on 1.25, while our normal test Chromecast is 1.22.

**Comment by joeyparrish** [comment]
This is working on the latest Chromecast firmware, so this can be closed.
