### ISSUE TITLE
Player freezing after resuming from an ad break

### ISSUE THREAD

**Issue by chrisfillmore** [google/shaka-player#973]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**:
Yes

**What version of Shaka Player are you using**:
2.1.7 uncompiled

**Can you reproduce the issue with our latest release version**:
Yes

**Can you reproduce the issue with the latest code from `master`**:
Yes

**Are you using the demo app or your own custom app**:
Custom app

**If custom app, can you reproduce the issue using our demo app**:
Not possible due to custom authorization process

**What browser and OS are you using**:
MacOS 10.12.6 Chrome v60

**What are the manifest and license server URIs**:
*(you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*

**What did you do?**
Attempt to play multi-period live stream with dynamically inserted ads from our ads provider. Watch content, watch it switch to an ad break, watch it switch back to content.

**What did you expect to happen?**
Stream should play smoothly across ad breaks.

**What actually happened?**
A stream will play smoothly when you start watching. When it switches to an ad break, the switch may or may not be smooth (possibly depending on the content). Upon returning from an ad break, the player regularly "freezes" and we see failed assertions and Shaka warnings.

We are hoping to solicit Shaka team's expertise with the player, and with DASH in general, in troubleshooting our streams. I don't believe this is a client / player issue -- our running theory is that the content is problematic. I'm not an expert on DASH, though, so it's difficult for me to say with authority.

There are potentially multiple intersecting problems. In addition to the freezing problem I've described, I understand that there is also a problem with joining the stream mid-way through an ad break. There are also points where the player repeatedly downloads manifests without fetching chunks. We are also seeing chunk failures due to a problem with our encryptor (this results in HTTP 500 on some chunks).

I have sent a demo application by email. Please let me know if I can answer any questions. Thank you for your help!

**Comment by joeyparrish** [comment]
@chrisfillmore, we will need more detailed instructions to reproduce.  I have the demo app you sent, but it is not self-explanatory.

![dai](https://user-images.githubusercontent.com/6843156/29388090-23e67f4a-8298-11e7-9518-f9ddfa5e0455.png)

How do we go about loading the content and playing it?

I'm also not sure if the demo app is complete and working, since there are many error messages in the JS console.  Most are "Failed to load resource" for json or js files, and the last is "SyntaxError: Unexpected token" while parsing JSON.

**Comment by chrisfillmore** [comment]
@joeyparrish What folder are you running the server from? It needs to be from the root of wherever it's unzipped, because the app will try to load configs from a specific path.

Perhaps show me your browser address bar?

**Comment by joeyparrish** [comment]
Ah, that helps.  Which config do you want me to use?

I picked one arbitrarily and got CORS errors.  Is this expected?  Should I be using `chrome --disable-web-security` for this sample app?

**Comment by chrisfillmore** [comment]
Steps to get started (sorry if I missed these in my original email, I've been sending this out to a few people for testing):

1. Select DFW-PROD config
2. Application will go through a device activation process, you should see "Device successfully activated!" or "Device is already activated." in the logs. (If a network call fails, reload and start again.)
4. Select Cisco DRM radio button
5. There are a couple channels to test with. Enter one of the following numbers in the CCID field: 2355, 3669
6. Click Load

(If you get a license failure, do `localStorage.clear()`, reload and try again. This will force a fresh activation.

Ah yes, I forgot about CORS, probably because I am perpetually running Chrome with `--disable-web-security`. Yes you do need to do that. Thanks @joeyparrish!

**Comment by chrisfillmore** [comment]
@joeyparrish, our ads provider deployed an update over the weekend which they are hoping will address some of the freezing we are seeing. I tested this morning and didn't see an improvement, but I will be testing more contents tomorrow. I've also sent you an updated demo app. Thanks again for your help.

**Comment by chrisfillmore** [comment]
I've updated the demo application once more this morning and sent you folks an email.

**Comment by joeyparrish** [comment]
Thanks, Chris.  I'll try to take another look tomorrow.

**Comment by chrisfillmore** [comment]
Thanks Joey. I'm told that YoSpace deployed some changes yesterday and there's been some improvement. I'm watching stream 2355 now. I still see this warning during ad breaks:

_The last segment should not end after the end of the Period._

And after returning from the ad break I also see some failed assertions:

_Assertion failed: lastReference cannot begin after the end of the Period_

It looks like the player recovers well though. I joined the stream during an ad break and when it returned to content, there was a brief freeze, but the stream has been smooth since then. I played through another ad break with no hiccups at all.

**Comment by joeyparrish** [comment]
@chrisfillmore, does this mean the problem is resolved?  Or that it is improved, and now we are concerned about the failed assertions?

Looking at the assertion code in SegmentIndex, it looks like we expected any segments that start after the period ends to be dropped from the manifest.  But it doesn't look like it will affect playback.

**Comment by chrisfillmore** [comment]
I think YoSpace has made updates which have resolved most (maybe all) of the freezing issues we've been seeing. Thanks for checking in! I'll close the ticket for now.

**Comment by joeyparrish** [comment]
That's great news.  Thanks, Chris.

I'm sorry we weren't able to find the time to help more with this, but I'm glad it is resolved.

**Comment by chrisfillmore** [comment]
It's no problem. Feel free to let us know if an ask is too much given your workload. I totally understand that. We didn't really think this was a client / player problem to begin with, but of course it behooves us to investigate from all angles.

**Comment by joeyparrish** [comment]
No worries!  It wasn't too much to ask.  We've just been backlogged on issue triage lately and we're fighting our way back out now.
