### ISSUE TITLE
Safari failures in mediasource.js

### ISSUE THREAD

**Issue by bhh1988** [google/shaka-player#974]
Hello,

I just wanted to bring this to the group's attention in case people are unaware. I only see this issue on the master branch. I haven't been able to investigate deeply, but I noticed that for some videos I get failure to load in Safari, and it throws in mediasource.js, near the top of the ignoreUpdateEnd_ function. From some basic Safari browser debugging, it looks like sourceBuffer doesn't contain a 'mediaSource_' property, so mediaSource ends up being undefined. Instead, sourceBuffer contains a property called 'i' (yes the letter) which is the desired MediaSource object. It looks like it might be related to https://github.com/google/shaka-player/commit/adb8da4764e3080693252ba0211cd4f936fa27be , which isn't on the other branches but is on the master branch.

If this is a known issue and would not exist in the upcoming 2.2 release, that's great. Sorry I haven't been able to debug further, I figured I'd first notify the group and only dig in deeper if you guys really need me to.

**Comment by joeyparrish** [comment]
Does not seem to affect v2.1.x, but we fixed it in time for v2.2.0.  Thank you for the report!
