### ISSUE TITLE
Can not dynamically update ABR enabled

### ISSUE THREAD

**Issue by ckelsey** [google/shaka-player#975]
I'm using Shaka v2.1.5 and am having trouble setting ABR enabled to false. In my player, I list the available bitrate variant tracks as well as auto which is the default. When a user selects a variant, I call `player.selectTrack(track)`, but if the track is the one selected by abr, nothing happens and the player stays in auto which is kind of confusing for the user.

I had tried calling `player.configure({ abr: { enabled: false }})` but again nothing happens and the player continues to stay in auto.

Is there a better way to acheive this?

**Comment by joeyparrish** [comment]
That all looks correct to me.  I'm unable to reproduce using our appspot demo and the JS console:

https://v2-1-5-dot-shaka-player-demo.appspot.com/demo/#asset=//storage.googleapis.com/shaka-demo-assets/sintel/dash.mpd;lang=en-US

On my connection, I have enough bandwidth for 4k.  When ABR has adapted up to 4k, I select a low-res track that shows me I'm definitely not seeing an ABR decision.

In the debugger, I first get a handle to a low-res track.  Then I disable ABR.  Then I select that track.
```js
lowRes = shakaDemo.localPlayer_.getVariantTracks().filter(t => t.width == 256)[0];
shakaDemo.localPlayer_.configure({abr: {enabled: false}});
shakaDemo.localPlayer_.selectVariantTrack(lowRes, true /* clear buffer */);
```

This is working as expected for me.  If I re-enabled ABR, it adapts back to 4k:

```js
shakaDemo.localPlayer_.configure({abr: {enabled: true}});
```

**Comment by ckelsey** [comment]
Perfect thanks
