### ISSUE TITLE
ShakaPlayer v2.2.0 shows subtitles of previous stream

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#984]
**What version of Shaka Player are you using**:
v2.2.0

**Can you reproduce the issue with our latest release version**:
Yes

**Can you reproduce the issue with the latest code from `master`**:
Yes

**Are you using the demo app or your own custom app**:
Demo app

**What browser and OS are you using**:
Chrome 50 Ubuntu 17.04: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36

**What did you do?**
Enable the subtitles (CC button), reproduce Angel One some seconds (20 seconds eg) and then load Sintel 4K. 

**What did you expect to happen?**
Sintel 4K shows his subtitles.

**What actually happened?**
Sintel 4K shows Angel One subtitles and his subtitles.

[Aug 24 2017 9-47 AM.webm.zip](https://github.com/google/shaka-player/files/1248090/Aug.24.2017.9-47.AM.webm.zip)

**Comment by chrisfillmore** [comment]
I've also seen this in the demo app.

**Comment by joeyparrish** [comment]
Confirmed on v2.2.0.  Not present in v2.1.8.  This is probably a bug in our default text displayer.  The text displayer plugin interface was introduced in v2.2.0 and was not present in v2.1.x.

**Comment by joeyparrish** [comment]
This fix will be available in the nightly build tomorrow.  We will also release this fix in v2.2.1.

**Comment by avelad** [comment]
Are there release date for v2.2.1?

**Comment by joeyparrish** [comment]
I'm planning to wait until next week, so we can deal with incoming bug reports about v2.2.0.  You can always try the master branch in the mean time.

**Comment by joeyparrish** [comment]
Cherry-picked to v2.2.1
