### ISSUE TITLE
Demo: "shaka.Player.isBrowserSupported is not a function" error

### ISSUE THREAD

**Issue by beaufortfrancois** [google/shaka-player#985]
https://shaka-player-demo.appspot.com/demo/ shows "shaka.Player.isBrowserSupported is not a function" error. 

Platforms:
Google Chrome 62.0.3194.0 (Official Build) canary (64-bit) - Chrome OS
Google Chrome 62.0.3194.0 - Android O
Google Chrome 60.0.3112.107 - Android O

![screenshot 2017-08-24 at 10 20 31 am](https://user-images.githubusercontent.com/634478/29656814-e02ac56c-88b5-11e7-8b98-d0a5f5847a91.png)

**Comment by hbengali** [comment]
I am seeing a different error: Shaka Error MANIFEST.UNABLE_TO_GUESS_MANIFEST_TYPE 

I suspect something went wrong the deployment of v2.2.0

**Comment by chrisfillmore** [comment]
I also see shaka.Player.isBrowserSupported is not a function.

**Comment by joeyparrish** [comment]
Hi all,

Can you please try again?  I believe this was a caching issue on our appspot instance which should now be solved.

**Comment by hbengali** [comment]
It's now working for me.

**Comment by joeyparrish** [comment]
I believe this was caused by our previous default cache policy of 24 hours on appspot.  I have updated this to 1 hour, so future appspot pushes should be quickly consistent.  Sorry for the inconvenience!

**Comment by beaufortfrancois** [comment]
Thank you ;)
