### ISSUE TITLE
Support IMSC1 in HLS

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#986]
**IMSC1 in HLS**

Carried as XML text inside fMP4 Segments
HLS defines support for the IMSC1 Text profile
Mark your Media Playlists as IMSC1 with the CODECS attribute
• CODECS="stpp.TTML.im1t, …"

> //IMSC1 alongside WebVTT in a Master Playlist
> #EXTM3U
> #EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="vtt",LANGUAGE="eng",NAME="English",URI="vtt.m3u8"
> #EXT-X-STREAM-INF:BANDWIDTH=90000,CODECS="avc1.4d001e,ac-3",SUBTITLES="vtt"
> bipbop_gear1/prog_index.m3u8
> #EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="**imsc**",LANGUAGE="eng",NAME="English",URI="**imsc.m3u8**"
> #EXT-X-STREAM-INF:BANDWIDTH=90000,CODECS="avc1.4d001e,ac-3,**stpp.TTML.im1t**",SUBTITLES="**imsc**"
> bipbop_gear1/prog_index.m3u8

Documentation: 
https://devstreaming-cdn.apple.com/videos/wwdc/2017/504op4c3001w2f222/504/504_advances_in_http_live_streaming.pdf
https://developer.apple.com/videos/play/wwdc2017/504/
https://developer.apple.com/streaming/HLS-WWDC-2017-Preliminary-Spec.pdf

**Comment by joeyparrish** [comment]
We already support TTML in MP4 (independent of any particular manifest format such as HLS or DASH).  The parser for TTML in MP4 is registered by MIME type and codec string, so we can simply add "stpp.TTML.im1t" to that registration:

https://github.com/google/shaka-player/blob/33c38e9c7ef47abb35b7bd27e374999ab5b64b22/lib/text/mp4_ttml_parser.js#L91

**Comment by ismena** [comment]
Small nit: hls parser currently assumes all text streams it encounters are vtt, so will need to update it as well.

**Comment by joeyparrish** [comment]
This turns out to be much more complicated than I realized.  Still working on the solution.  Thanks!

**Comment by joeyparrish** [comment]
Cherry-picked to v2.2.1
