### ISSUE TITLE
shaka.text.Cue.textAlign is getting mangled

### ISSUE THREAD

**Issue by chrisfillmore** [google/shaka-player#987]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**:
Yes

**What version of Shaka Player are you using**:
2.2.0

**Can you reproduce the issue with our latest release version**:
Yes

**Can you reproduce the issue with the latest code from `master`**:
Unknown

**Are you using the demo app or your own custom app**:
~~Custom app~~ demo app

**If custom app, can you reproduce the issue using our demo app**:
~~No. Is there demo content that includes external vtt files (not embedded)? I'm not sure if this makes a difference.~~ Yes

**What browser and OS are you using**:
MacOS 10.12.6
Chrome 60.0.3112.101

**What are the manifest and license server URIs**:
~~I can send a demo application to reproduce, if necessary.~~ Sent manifest and license url to shaka-player-issues

**What did you do?**
Watched a stream with external vtt tracks (edit: left-aligned)

**What did you expect to happen?**
Stream to play normally and subtitles to appear left-aligned ('left' is the alignment value provided by the vtt tracks).

**What actually happened?**
Chrome produces warnings saying _The provided value 'undefined' is not a valid enum value of type AlignSetting._ The subtitles themselves also appear to be center-aligned (although they're oddly cropped... but this may be an issue in our demo application). I took some screenshots of the subtitles but I think they're a bit besides the point. I think this is the problem:

The warning comes from `shaka.text.SimpleTextDisplayer.prototype.convertToTextTrackCue_`, here:

```
vttCue.align = shakaCue.textAlign;
```

The value of `shakaCue.textAlign` is `undefined`.

This looks like a mangling / minification bug, because I don't get it when I run Shaka uncompiled. 

When I set a breakpoint and inspect in compiled mode, I see that `shaka.text.Cue.textAlign` looks like:
![screen shot 2017-08-24 at 11 14 23 am](https://user-images.githubusercontent.com/7190265/29673519-75138e1e-88bd-11e7-8f4c-132a67a90189.png)

So, when `textAlign` gets set on the cue point in `shaka.text.VttTextParser.setTextAlign_`, here:

```
cue.textAlign = Cue.textAlign[align.toUpperCase()];
```

... the value is `undefined`. I don't see this problem in Shaka v2.1.7.

**Comment by chrisfillmore** [comment]
Would you like me to send a demo app to reproduce?

**Comment by joeyparrish** [comment]
I haven't tried yet, but it sounds easy enough to reproduce.

It shouldn't be undefined, because the regex looks like this:

```js
  if ((results = /^align:(start|middle|center|end|left|right)$/.exec(word))) {
    VttTextParser.setTextAlign_(cue, results[1]);
```

So results[1] should only be one of those strings in the regex alternation.  Later, when we do this:

```js
    cue.textAlign = Cue.textAlign[align.toUpperCase()];
```

The value of align should definitely be one of the enumerated values.

We'll dig into this.  Thanks for the report!

**Comment by joeyparrish** [comment]
Okay, I thought it would be easy to repro, but I can't so far.  I have tried both "Angel One" (WebVTT subs) and "Sintel" (w/ MP4-embedded VTT text).  Can you please send a demo asset or app that reproduces the problem?

**Comment by chrisfillmore** [comment]
It's not the value of `results[1]` that is problematic. The value of `shaka.text.Cue.textAlign` in compiled Shaka is:

```
shaka.text.Cue.textAlign = {
  Hc: "end",
  Ic: "left",
  Mc: "right",
  Nc: "start",
  tb: "center"
}
```

So when we ask for `shaka.text.Cue.textAlign['left']`, the value is `undefined`.

I can send a demo over in just a bit.

**Comment by chrisfillmore** [comment]
I sent another email just now with repro steps for the Shaka demo app.

**Comment by ismena** [comment]
Received, thanks!

**Comment by joeyparrish** [comment]
It seems that we didn't catch this because we aren't testing with text streams that use these attributes.

**Comment by joeyparrish** [comment]
Cherry-picked to v2.2.1
