### ISSUE TITLE
Demo: "this.playerInterface_.filterAllPeriods is not a function" error

### ISSUE THREAD

**Issue by beaufortfrancois** [google/shaka-player#988]
Steps to reproduce:
1. Go to https://shaka-player-demo.appspot.com/demo/#asset=//storage.googleapis.com/shaka-demo-assets/angel-one-widevine/dash.mpd;lang=en-US
2. Click "Load" button
3. Scroll down, Expand "Offline" and click "Store" button
4. Error message "this.playerInterface_.filterAllPeriods is not a function" shows up

Platform: Google Chrome 62.0.3194.0 - Android O

**Comment by ismena** [comment]
Hi, do you mind realoading the page/clearing browser cache and trying again? This looks like a caching issue we've been having after deployment of 2.2, but it should be resolved now.
I also see that you were the one to open #985. Are you still seeing this although the issue from 985 has been resoled? (You left a comment there that made me assume it was working for you now :)).

**Comment by beaufortfrancois** [comment]
I've reset site setttings and I can still reproduce.
#985 works great now!

**Comment by joeyparrish** [comment]
Confirmed, even with the clear version of that asset.  Thanks!

**Comment by joeyparrish** [comment]
The bug seems to be in shaka.offline.Storage, but it isn't caught in the integration tests.  The issue is in the interface between the manifest parser and Storage, and our integration tests use fake manifests.  The filtering functionality is therefore not covered in these tests.

**Comment by joeyparrish** [comment]
The fix will be in the nightly build tomorrow, and in v2.2.1 after that.  Thanks!

**Comment by beaufortfrancois** [comment]
Where can I access the nightly build?

**Comment by avelad** [comment]
@beaufortfrancois You can access to nightly build in: https://nightly-dot-shaka-player-demo.appspot.com/demo/

**Comment by beaufortfrancois** [comment]
I can no longer reproduce the issue.
Thank you @joeyparrish and @avelad.

**Comment by joeyparrish** [comment]
Cherry-picked to v2.2.1
