### ISSUE TITLE
Enhancement request: detect preload="none" and delay requests

### ISSUE THREAD

**Issue by forbesjo** [google/shaka-player#989]
This is an enhancement request for the Shaka Player to detect the `preload='none'` setting and not make manifest/segment requests until a play request. The use case for this is to provide an option to reduce bandwidth costs and unnecessary license requests.

**Comment by joeyparrish** [comment]
Seems reasonable.  Thanks!

**Comment by joeyparrish** [comment]
@forbesjo, on further consideration, I am not so sure about this.  If you want to avoid requesting a manifest, why not just wait to call player.load()?

**Comment by forbesjo** [comment]
That makes sense, I’ll handle preload in my app and selectively load the source. Closing this issue.
