### ISSUE TITLE
Cannot read property 'length' of null when try to enable captioning

### ISSUE THREAD

**Issue by SemihGk** [google/shaka-player#990]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**:

**What version of Shaka Player are you using**:
2.2  (reproduced 2.1.x as well)

**Can you reproduce the issue with our latest release version**:
Yes.
**Can you reproduce the issue with the latest code from `master`**:
Yes
**Are you using the demo app or your own custom app**:
My custom app. I could not reproced the error on the demo app. Probably video contents in the demo app are not suitable for this error.

**If custom app, can you reproduce the issue using our demo app**:
No.

**What browser and OS are you using**:
Mac OS: 10.12.6
Chrome 60

**What are the manifest and license server URIs**:
*(you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*
If it's required, we can send the custom app.

**What did you do?**
Enabled captioning on and waited around a minute(time gap is unpredictable). Then, it caught the error when I tried to disable and enable again. 

**What did you expect to happen?**
It should not throw an error.

**What actually happened?**
Video is stopped. Please check the screenshot. As you may see it in screenshot, It throws the error at lib/text/simple_text_displayer.js :231, cues.length . When 'cues' is null. I put a console.log to show it in screenshot as well. 

<img width="899" alt="screen shot 2017-08-25 at 12 07 48 pm" src="https://user-images.githubusercontent.com/5814582/29722307-329a139c-898e-11e7-9c7f-6ccdde7ea3ef.png">

**Comment by ismena** [comment]
Hi @SemihGk, thanks for reporting.

Having access to the app/content would definitely help us figure out what's going on. Feel free to send it to shaka-player-issues@google.com.

**Comment by SemihGk** [comment]
Thank you for your prompt response. I just sent the app with its instructions. Please let me know if you need more information.

**Comment by SemihGk** [comment]
I was keep testing the demo app and I could finally reproduced the error. Please check the screenshot:
<img width="1337" alt="screen shot 2017-08-25 at 5 40 03 pm" src="https://user-images.githubusercontent.com/5814582/29733727-96929e4a-89bc-11e7-99cf-30d1f2bb7cd4.png">

**Comment by joeyparrish** [comment]
Did you reproduce in the demo by turning captions on and off?  Is it easier to reproduce in your own application than in the demo?

**Comment by SemihGk** [comment]
Yes, I turned on captions on. Then, waited maybe 30 minutes. I replayed the video again and turned off and on several times. After many tries, I could reproduce it. It is definitely tough to reproduce in the demo. It is much easier to reproduce it in our app.

**Comment by vaage** [comment]
A small update on this.

`TextTrack.cues` is only `null` when `mode` is set to `"disabled"`. As we can see in the initial post, the current text track that the displayer is set to `"disabled"`. This explains why we are getting a null list of cues.

What I am still looking into is why the track is being set to `"disabled"` in the first place. When toggling close captions on and off, the track is set to `"hidden"`. So at some other point, someone is setting `mode` to `"disabled"`.

**Comment by joeyparrish** [comment]
@SemihGk, is your application directly manipulating the track state instead of using `Player.setTextTrackVisibility()`?  Are you using custom video controls (`video.controls == false`) or the built-in browser controls (`video.controls == true`)?

It is possible that the browser built-in controls use "disabled" instead of "hidden".

**Comment by SemihGk** [comment]
Thank you for your responses, @vaage and @joeyparrish.

We did not set the mode to "disabled" in our application. Everything is just default. Also, same error is reproduced in the demo app. I assume demo app do not have any custom settings as well. It only happens when we turn captions on and off without changing any settings(including built-in browser controls).

**Comment by vaage** [comment]
@joeyparrish You are right. Once we change over to use the default browser built-in controls, it uses "disabled" instead of "hidden".

@SemihGk Thank you for bringing this to our attention. I will get a fix put together today.

**Comment by SemihGk** [comment]
Thank you, @vaage. We look forward to waiting the fix then.

**Comment by joeyparrish** [comment]
This will be cherry-picked to v2.2.2.
