### ISSUE TITLE
Use Network Information API on defaultBandwidthEstimate

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#994]
This issue is a request to implement a new feature.

Sample: https://googlechrome.github.io/samples/network-information/index.html
Documentation: http://wicg.github.io/netinfo/
Chrome Status: https://www.chromestatus.com/feature/6338383617982
Enabled by default in:
- Chrome for desktop release 61
- Chrome for Android release 38
- Opera for Android release 48

We can use downlink attribute for defaultBandwidthEstimate, eg: defaultBandwidthEstimate = 0.85 * <downlink attribute>

If Network Information API is not avalaible in the platfform, we should use the current method.

**Comment by joeyparrish** [comment]
This is a great suggestion.  Thanks!

**Comment by joeyparrish** [comment]
@ismena has already written the code for this, but I'm seeing some issues with low-quality data on certain platforms.  We will wait to launch in Shaka Player until data quality issues have been resolved.

Therefore, this may not land in v2.3.0.

**Comment by avelad** [comment]
@joeyparrish, what are the problems exactly?

**Comment by joeyparrish** [comment]
There seems to be an issue with hanging GETs.  Chrome team has [been made aware](https://bugs.chromium.org/p/chromium/issues/detail?id=368358#c44) and are working on a fix.

**Comment by avelad** [comment]
Version 62 has already been released. The problems have been fixed?

**Comment by joeyparrish** [comment]
They have, but I'm not certain if the fix was released in Chrome 62 or 63.  I will try to confirm.

**Comment by joeyparrish** [comment]
Still seeing the issue in Chrome 62.  I expect this will be fixed in Chrome 63, but I have yet to confirm.

**Comment by joeyparrish** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=770897 shows that fixes have been made to Chrome 63, which is scheduled to go stable in December.

We will avoid publishing this feature until the fixes in Chrome are in the hands of the masses.
